### ISSUE TITLE
Improved Detaching of Native Events when the props are no longer given

### ISSUE THREAD

**Issue by MPiccinato** [software-mansion/react-native-reanimated#1004]
## Description

I am using this library to control a collapsible header component and it is working great. However, I now have multiple AnimatedFlatLists created from `createAnimatedComponent` that are rendered at the same time side by side, essentially tab panels that the user can swipe left and right between. I do not want to unmount and remount them, but just switch which one has the listeners for the scroll events.

When switching between the panels and re-attaching the scroll events to a list that had them attached previously, I run into the error of...

`Event handler already set for the given view and event type` from  `REANodesManager.m`

This makes sense since it seems to not unattach the events if they just are not supplied again as props to the component. I am able to avoid this by checking in my component if the `onScroll` prop is defined and then calling `_detachNativeEvents()` on the component that was create from `createAnimatedComponent`.

While this works, it just doesn't feel sustainable. The proposed solution would be for the component from `createAnimatedComponent` to notice when the events are no longer in the props given and detach them.

### Caveats

I have not tested this or dug into it on Android, only iOS.

## Motivation

The main motivation behind this is clarity in what is expected if the props for the scroll events are no longer given to the component. It would be expected that they are long longer attached.

## Code example

```
<TabView>
  <Tabs>
    <TabOne />
    <TabTwo />
  </Tabs>
  <TabPanels>
    <TabPanelOne onScroll={active ? handleOnScroll : undefined } />
    <TabPanelTwo onScroll={active ? handleOnScroll : undefined } />
  </TabPanels>
</TabView>

**Comment by jakub-gonet** [comment]
Sorry for the delay.

This feature looks good but we can't really implement that because there's code that [relies on attached listeners](https://github.com/software-mansion/react-native-reanimated/pull/531).

Please share any insight you have on this issue, maybe we can get to something out of that.
