### ISSUE TITLE
When pulldown to refresh,app crash back

### ISSUE THREAD

**Issue by Dirk41Mavs** [software-mansion/react-native-reanimated#1012]
## Description
Use FlatList to render list,when pulldown to refresh,app crash back.Then i found react-native-reanimated of version 1.9.0 run well.

## Steps To Reproduce

1.

## Package versions

- React:16.11.0
- React Native:0.62.2
- React Native Reanimated:2.0.0-alpha.3

**Comment by jakub-gonet** [comment]
Please provide some example code triggering this issue, there's too little to take action about that.

Closing until more info is provided.
