### ISSUE TITLE
Typescript error - Can't build - Generic type 'Adaptable' requires 1 type argument(s)

### ISSUE THREAD

**Issue by elgambet** [software-mansion/react-native-reanimated#1021]
## Description

When using [material-top-tabs](https://github.com/react-navigation/react-navigation/tree/main/packages/material-top-tabs) (which uses this library) in a typescript React Native project the command "yarn tsc" fails, this error doesn't happen in [V2](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.4) 

## Steps To Reproduce

1. `npx --ignore-existing react-native init MyApp --template react-native-template-typescript`
2. Install dependencies: 
  2.1. `cd MyApp`
  2.2. `yarn add @react-navigation/material-top-tabs react-native-tab-view @react-navigation/native react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`
3. Update app.ts with code example:
4. Run `yarn tsc`

### Expected behavior
Build without errors

### Actual behavior
Throws error:

`node_modules/react-native-reanimated/react-native-reanimated.d.ts:237:36 - error TS2314: Generic type 'Adaptable' requires 1 type argument(s).`

## Snack or minimal code example

```
import 'react-native-gesture-handler';
import * as React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';
import {Text} from 'react-native';

const HomeScreen = () => <Text>Example</Text>;

const Tab = createMaterialTopTabNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
};

export default App;
```

## Package versions

- @react-native-community/masked-view: ^0.1.10
- @react-navigation/material-top-tabs: ^5.2.14
- @react-navigation/native: ^5.7.1
- react: 16.13.1
- react-native: 0.63.0
- react-native-gesture-handler: ^1.7.0
- react-native-reanimated: ^1.10.1
- react-native-safe-area-context: ^3.1.1
- react-native-screens: ^2.9.0
- react-native-tab-view: ^2.15.
- @babel/core: ^7.8.4
- @babel/runtime: ^7.8.4
- @react-native-community/eslint-config: ^1.1.0
- @types/jest: ^25.2.3
- @types/react-native: ^0.63.1
- @types/react-test-renderer: ^16.9.2
- @typescript-eslint/eslint-plugin: ^2.27.0
- @typescript-eslint/parser: ^2.27.0
- babel-jest: ^25.1.0
- eslint: ^6.5.1
- jest: ^25.1.0
- metro-react-native-babel-preset: ^0.59.0
- prettier: ^2.0.4
- react-test-renderer: 16.13.1
- typescript: ^3.8.

**Comment by jakub-gonet** [comment]
Thanks for the detailed description!

I prepared #1029, it should fix it.
