### ISSUE TITLE
Make reproducible builds from master branch

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1024]
## Description

Every time I try to [build](https://github.com/software-mansion/react-native-reanimated/issues/950) **react-native-reanimated** npm package from master it fails. 

I use script `createNPMPackage.sh`, other ways didn't work. Being able to build complete npm package from master is very important, otherwise I can't test patches against master branch and can't verify they are working.

```bash
...
> Task :buildReanimate
...
make: Leaving directory '/home/me/react-native-reanimated/android/src/main/JNI'
/home/me/react-native-reanimated/android/build/third-party-ndk/folly/folly/FileUtil.cpp:37:14: error: no matching function for call to 'wrapNoInt'
  return int(wrapNoInt(open, name, flags, mode));
             ^~~~~~~~~
/home/me/react-native-reanimated/android/build/third-party-ndk/folly/folly/detail/FileUtilDetail.h:34:9: note: candidate template ignored: couldn't infer template argument 'F'
ssize_t wrapNoInt(F f, Args... args) {
        ^
1 error generated.
make: *** [/home/me/.local/opt/android-sdk/ndk-bundle/build/core/build-binary.mk:478: /home/me/react-native-reanimated/android/build/tmp/buildReanimated/local/arm64-v8a/objs/folly_json/folly/FileUtil.o] Error 1
> Task :buildReanimated FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildReanimated'.
> Process 'command '/home/me/.local/opt/android-sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2
```

It would be very good to have CI tests that check source code from master at least is building for iOS and Android.

**Comment by terrysahaidak** [comment]
It seems like you're using some wrong version of folly.

Does run-android work for you? I would recommend to try to build for device/emulator using Android studio - what's how I used to build it.

**Comment by likern** [comment]
> It seems like you're using some wrong version of folly.
> 
> Does run-android work for you? I would recommend to try to build for device/emulator using Android studio - what's how I used to build it.

Script `createNPMPackage.sh` calls android tasks through gradle command line, I think there should be no difference whether I call tasks from command line or through Android Studio.

I've tried to call `assembleDebug` using Android Studio and see the same error.
Folly version is picked up and downloaded by `downloadFolly` task

```bash
Download https://github.com/facebook/folly/archive/v2020.01.13.00.tar.gz
> Task :downloadFolly
> Task :prepareFolly
```

```gradle
def FOLLY_VERSION = reactProperties.getProperty("FOLLY_VERSION")
...
task downloadFolly(dependsOn: createNativeDepsDirectories, type: Download) {
    src("https://github.com/facebook/folly/archive/v${FOLLY_VERSION}.tar.gz")
    onlyIfNewer(true)
    overwrite(false)
    dest(new File(downloadsDir, "folly-${FOLLY_VERSION}.tar.gz"))
}
```
which takes `FOLLY_VERSION` from `./node_modules/react-native/ReactAndroid/gradle.properties`
```gradle.properties
FOLLY_VERSION=2020.01.13.00
```
Is used the latest React Native version - now it is `0.63.2`, released 4 days ago.

**Comment by likern** [comment]
This is a related issue https://github.com/facebook/react-native/issues/28298

**Comment by likern** [comment]
> It seems like you're using some wrong version of folly.
> 
> Does run-android work for you? I would recommend to try to build for device/emulator using Android studio - what's how I used to build it.

After successfully generating **react-native-reanimated-2.0.0-alpha.4.tgz** I still see **"Unsatisfied Link Error"** for **reanimated.so** when try to use this reanimated package as dependency (using `yarn add file://...`).

![photo5204307569185762798](https://user-images.githubusercontent.com/842306/86964838-592eee80-c16f-11ea-82b6-4a19d2713b78.jpg)

**Comment by likern** [comment]
The same problem have with running Example app.
![Screenshot_2020-07-26-19-06-43-170_com miui bugreport](https://user-images.githubusercontent.com/842306/88483907-8e12b200-cf73-11ea-8afc-e70a835d699d.jpg)
