### ISSUE TITLE
set location of a view with panGestureHandler

### ISSUE THREAD

**Issue by mldb** [software-mansion/react-native-reanimated#103]
i try to create a seekbar with reanimated and panGestureHandler 
i use of example folder to create draggable seekbar and thats work fine
but i want when user tap on somewhere of bar the toggle jump to where user tapped
plz help

my code:
`this.offsetX = new Value(0)
    this.gestureState = new Value(-1)
    this.onGestureEvent = event([
      {
        nativeEvent: {
          translationX: this.dragX,
          state: this.gestureState,
        },
      },
    ])
    this.addX = add(this.offsetX, this.dragX)

    this.transX = cond(
      and(eq(this.gestureState, State.BEGAN), eq(this.draging, 0)),
      [call([this.posX], this.startDraging)],
      cond(
        eq(this.gestureState, State.ACTIVE),
        [call([this.addX], this.setTime), set(this.draging, 1), this.addX],
        cond(
          and(
            or(
              eq(this.gestureState, State.END),
              eq(this.gestureState, State.CANCELLED),
              eq(this.gestureState, State.FAILED),
            ),
            eq(this.draging, 1),
          ),
          [
            block([
              set(this.offsetX, this.addX),
              set(this.currentTime, this.addX),
              call([this.addX], this.setVideoTime),
              set(this.draging, 0),
            ]),
          ],
        ),
      ),
    )

 <PanGestureHandler
          maxPointers={1}
          hitSlop={{
            top: 15,
            left: 15,
            bottom: 15,
            right: 15,
          }}
          onGestureEvent={this.onGestureEvent}
          onHandlerStateChange={this.onGestureEvent}
        >
<Animated.View
                style={[
                  {
                    width,
                    height: 12,
                    flexDirection: 'row',
                    position: 'absolute',
                    alignItems: 'center',
                    bottom: 0,
                    left: -width,
                  },
                  {
                    transform: [
                      {
                        translateX: Animated.interpolate(
                          cond(greaterThan(this.draging, 0.5), this.transX, this.currentTime),
                          {
                            inputRange: [-1, 0, width, width + 1],
                            outputRange: [12, 12, width, width],
                          },
                        ),
                      },
                    ],
                  },
                ]}
              />
        </PanGestureHandler>
`

**Comment by osdnk** [comment]
Hi @mldb,
Could you please prepare code I could simply paste into editor and run? I do not clearly understand what's going on here
