### ISSUE TITLE
Render view only if shared value had specific value

### ISSUE THREAD

**Issue by Piero87** [software-mansion/react-native-reanimated#1039]
hello,
I have loked at your example: https://github.com/software-mansion/react-native-reanimated/blob/master/Example/src/SwipeableListExample.js and I wanna know if it's possible to render the Button only if the translateX has a specifc value, I wanna do this to decrease the number of view and memory used in page, is this possible? I have tried this:

```
  return (
    <View style={s.item}>
      <PanGestureHandler activeOffsetX={[-10, 10]} onGestureEvent={handler}>
        <Animated.View style={styles}>
          <ListItemContent item={item} />
           {translateX.value < 10 ? null : 
          <View style={s.buttonsContainer}>
            <Button item={removeButton} />
          </View>
           }
        </Animated.View>
      </PanGestureHandler>
    </View>
  );
```

but it's not working, any idea?

- React: 16.13.1
- React Native: 0.63.0
- React Native Reanimated: v2 alpha 4

**Comment by Szymon20000** [comment]
It's not possible right now to do it fully on UI thread. If it's not important for you then you can register for translateX changes and call a function that will change the state of the component.  
``` JS
const cb(translation) { 
  setState(shouldRender(translation));
}

useDerivedValue( () => {
    cb(translateX.value);
  }
)
```

**Comment by karol-bisztyga** [comment]
Hi @Piero87!
Such functionality is not supported, you would have to rerender the component to decrease the amount of rendered views.

I am closing this issue for two reasons:
- first, it's been answered,
- second: inactivity

If you feel like still have any doubts about this feel free to reopen the issue.
