### ISSUE TITLE
Can't compile Android: getUIViewOperationQueue() is not public in UIImplementation

### ISSUE THREAD

**Issue by mfkrause** [software-mansion/react-native-reanimated#1044]
## Description

I'm trying to compile an app for Android that is using react-native-reanimated 1.4.0. While it has worked flawlessly before, I now somehow get the error below.

### Screenshots
<img width="1858" alt="Bildschirmfoto 2020-07-29 um 19 35 01" src="https://user-images.githubusercontent.com/10306735/88833484-9ae11100-d1d2-11ea-84a5-cd9269781e46.png">

### Expected behavior
App should compile fine.

### Actual behavior
```
The following error is thrown during compiling:
[...]/node_modules/react-native-reanimated/android/src/main/java/de/facebook/react/uimanager/UIManagerReanimatedHelper.java:14: error: getUIViewOperationQueue() is not public in UIImplementation; cannot be accessed from outside package
    return uiImplementation.getUIViewOperationQueue().isEmpty();
                           ^
```

## Package versions

- React: 16.9.0
- React Native: 0.61.5
- React Native Reanimated: 1.4.0

**Edit**: Sorry, this issue should have gotten the Question label.

**Comment by jakub-gonet** [comment]
Hi,
did you clear gradle cache and reinstalled node_modules?

Also, did you update RN (or other dependencies) recently?

**Comment by jakub-gonet** [comment]
Closing the author responds.
This issue was not active for some time so I'm closing it.
If you need further help please reply.
