### ISSUE TITLE
Unable to resolve "./useValue" from "node_modules\react-native-reanimated\src\Animated.js"

### ISSUE THREAD

**Issue by avin-kavish** [software-mansion/react-native-reanimated#1045]
## Description

I'm trying to use `react-native-reanimated` with expo. After running `expo install react-native-reanimated`, I get the above mentioned error.

## Package versions

- React: 16.11.0
- React Native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
- React Native Reanimated: 1.9

**Comment by MauroTaliente** [comment]
I think useValue is a hook from the react-native-redash library

Saludos!

**Comment by jakub-gonet** [comment]
Please provide the output of commands:
- `less node_modules/react-native-reanimated/src/Animated.js`
- `ls node_modules/react-native-reanimated/src/`

Besides that, try [clearing watchman, node_modules, pods, and Gradle caches](https://github.com/software-mansion/react-native-reanimated/issues/1007#issuecomment-662438323).

Closing until more info is provided.

**Comment by avin-kavish** [comment]
some wierd interaction bug, few re-installs down the line it worked
