### ISSUE TITLE
Example -> TypeError: (0, _core.withNavigation) is not a function, liquid swipe example doesnt animate

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-reanimated#1049]
Installing the example app I'm met with the following error:

```
[Thu Jul 30 2020 17:28:46.962]  ERROR    TypeError: (0, _core.withNavigation) is not a function. (In '(0, 
_core.withNavigation)(LinkWithNavigation)', '(0, _core.withNavigation)' is undefined)
```

Also, removing the react-navigation part of the example the liquid swipe example is purely static and doesn't animate, is this correct?

**Comment by terrysahaidak** [comment]
Liquid swipe works only on iOS. What platform did you use?

**Comment by kyle-ssg** [comment]
Sorry, should have mentioned, this is cloning, npm installing/pod installing and running on iOS. I'll try just taking the markup over to the playground app.

**Comment by kyle-ssg** [comment]
Can't interact with it, same issue moving to the playground app.

Replication repo 
https://github.com/kyle-ssg/reanimated-liquid-swipe
![image](https://user-images.githubusercontent.com/8608314/88969238-7192b480-d2a8-11ea-8806-a656f1bbd281.png)

**Comment by kyle-ssg** [comment]
Sorry, no idea how or why but I've run it a couple days later and it works! So strange, before I couldn't interact with it on two separate projects!

**Comment by ethanshar** [comment]
Hey, 
I get the same issue myself. 
The app opens with a blank screen and the packager throws:
```
TypeError: (0, _core.withNavigation) is not a function. (In '(0, _core.withNavigation)(LinkWithNavigation)', '(0, _core.withNavigation)' is undefined)
```

Any idea on how to fix it? 

I followed the instructions here:
https://github.com/software-mansion/react-native-reanimated/tree/master/Example#run-the-example

**Comment by terrysahaidak** [comment]
Hi. Seems like it's related to missing package-lock.json in the project. Try to use yarn instead of npm.

**Comment by ethanshar** [comment]
Using Yarn worked. Thanks

**Comment by terrysahaidak** [comment]
hey @karol-bisztyga, here is another confirmation of the problem with npm because of missing package-lock :)

**Comment by Rawan-Eltobgy** [comment]
I am using yarn and facing the same issue

**Comment by jakub-gonet** [comment]
@Rawan-Eltobgy, please provide some repro repository.

**Comment by terrysahaidak** [comment]
Make sure you haven't overrided yarn.lock provided by the repo.

**Comment by khokon1116** [comment]
I'm having the same problem. Can someone refer me to the exact solution?

**Comment by Roka20012** [comment]
@khokonm 

Using `yarn v1.22.10` works for me
