### ISSUE TITLE
V2 Compatibility with react-navigation

### ISSUE THREAD

**Issue by allthetime** [software-mansion/react-native-reanimated#1050]
Hi, I'm wondering if anyone has v2 working with react-navigation. 

react-navigation requires reanimated as a dependency and attempting to run my project with v2 is leading to errors.

The first one was caused by the renaming of `Animated.interpolate` to `Animated.interpolateNode`

I patched these out but there are further, more obscure issues.

Just want some insight before I go too much further.

Thanks!

**Comment by jakub-gonet** [comment]
It should be working fine after renaming imports (`interpolate` and `Easing`). AFAIK, in newer versions navigation doesn't use reanimated at all.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.
