### ISSUE TITLE
v2 Color interpolation doesn't work

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1053]
## Description

In the example yield many results that are not as expected.

```
import React from "react";
import { View, StyleSheet, processColor } from "react-native";
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  interpolate,
  Extrapolate,
  withTiming,
} from "react-native-reanimated";

import { mix } from "../components/AnimatedHelpers";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "space-evenly",
  },
  box: {
    width: 100,
    height: 100,
  },
});

const blue = processColor("blue");
const red = processColor("red");

const Test = () => {
  const progress = useSharedValue(0);
  const style = useAnimatedStyle(() => {
    const backgroundColor = interpolate(
      progress.value,
      [0, 1],
      [blue, red],
      Extrapolate.CLAMP
    );
    return {
      backgroundColor,
    };
  });
  return (
    <View style={styles.container}>
      <Animated.View style={[styles.box, style]} />
    </View>
  );
};

export default Test;
``` 

Yields a red box (I would  have expected a blue one). The main issue, however, is when having a default value, for instance: `const progress = useSharedValue(0.5);` yields a transparent box.

Is it because `processColor` on the JS thread returns a number that doesn't make sense on the UI thread? In other example, I have built, everything works great except if `progress` has a default value.

**Comment by vamshi9666** [comment]
any update on this ?

**Comment by karol-bisztyga** [comment]
> any update on this ?
> 
> Edit: my bad. It is actually working for me.

Thanks for bringing it up, I missed this when merging color interpolation, should be close of course.
