### ISSUE TITLE
No animation end callback when using delay()

### ISSUE THREAD

**Issue by lachtos** [software-mansion/react-native-reanimated#1057]
## Description

When using `withSpring` with `delay` like `delay(100, withSpring(scale.value, {}, finished => {}))` the callback does not get called, meanwhile `withSpring(scale.value, {}, finished => {})` works fine.

## Steps To Reproduce

1. Use `withSpring` with `delay`

### Expected behavior

On animation end callback gets called

### Actual behavior

On animation end callback does not get called

## Snack or minimal code example

```
const scale = useSharedValue(0);

const animatedStyle = useAnimatedStyle(() => {
  const scl = delay(100, withSpring(scale.value, { damping: 15 }, finished => {
   console.log(`Animation ended; finished: ${finished}`); // <-- does not log when animated with delay
  }));

  return {
    transform: [{ scale: scl }]
  };
});

useEffect(() => {
  scale.value = 1;
}, []);
```

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.4

**Comment by MinimogDev** [comment]
Also happens when using `withTiming` and delay
