### ISSUE TITLE
No doc for react-native-reanimation v1 and v2

### ISSUE THREAD

**Issue by vikil143** [software-mansion/react-native-reanimated#1058]
## Description
I m search on the net for lots of time I don't get any proper doc please provide proper doc for a developer to use this library I want to learn this library fundamental and many peoples also so please provide some doc or any tutorial 
### Package versions
For version one and two

**Comment by jakub-gonet** [comment]
We are aware that [v1 docs](https://docs.swmansion.com/react-native-reanimated/docs/) are somewhat lacking proper guides but we want to focus on getting v2 ready which will be more user friendly to use (simpler API, writing animations in plain JS). [Docs for v2](https://docs.swmansion.com/react-native-reanimated/docs/next/) are in progress, most of the API is documented, [we have](https://blog.swmansion.com/introducing-reanimated-2-752b913af8b3) a few [articles](https://blog.swmansion.com/shared-values-in-reanimated-2-af0cb4ffe24) about [Reanimated 2](https://blog.swmansion.com/controlling-and-customizing-animations-in-reanimated-2-cee2d5d21285) as well. We'll be trying to improve those.

You can use external materials (e.g. excellent series ["Can it be done in React Native?"](https://www.youtube.com/c/wcandillon/playlists) by wcandillon) too.

If you want to improve v1 or v2 docs we'd be very grateful for any PR.
