### ISSUE TITLE
How to control pointerEvents props with a sharedValue ?

### ISSUE THREAD

**Issue by Daavidaviid** [software-mansion/react-native-reanimated#1059]
## Description

I'd like to control the `pointerEvents` value of an `Animated.View`, so I was thinking doing something like  : 

## Code

```

  const translateY = useSharedValue(0);

  ...

  const animatedProps = useAnimatedProps(() => {
    const pointerEvents = translateY.value === 1 ? undefined : 'box-none';

    return {
      pointerEvents,
    };
  });

  return (
    <Animated.View {...animatedProps} style={styles.container}>
      // CONTENT
    </Animated.View>
  );
```

Except it doesn't work the way I expected it to work. Someone knows how to solve this ?
Thanks.

### Package versions

- React: latest
- React Native: 0.63.2
- React Native Reanimated: alphaV4

ANSWER : 
I found this issue right after : 
https://github.com/software-mansion/react-native-reanimated/issues/895

Got it to work like that : 

```

  const translateY = useSharedValue(0);

  ...

  const animatedProps = useAnimatedProps(() => {
    const pointerEvents = translateY.value === 1 ? 'auto' : 'box-none';

    return {
      pointerEvents,
    };
  });

  return (
    <Animated.View {...{ animatedProps }} style={styles.container}>
      // CONTENT
    </Animated.View>
  );
```

**Comment by a-eid** [comment]
Hi, could u please let us know how you resolved this ?

**Comment by Daavidaviid** [comment]
At the end of my first message

**Comment by a-eid** [comment]
@Daavidaviid thank you

**Comment by terrysahaidak** [comment]
By the way you can use both booleans and strings as shared values :)

**Comment by Pnlvfx** [comment]
The solution that provide Daavidaviid seems to work however I get this typescript error that I'm trying to remove as I can't leave Typescript error: 

const animatedProps = useAnimatedProps(() => {
    const pointerEvents = opacityControl.value === 0 ? 'none' : 'auto';
    //https://github.com/software-mansion/react-native-reanimated/issues/1059
    return {
      pointerEvents,
    };
  });
  
  as you can see the pointerEvents could be none or auto there is no change that he could be undefined.. however I get this eror

No overload matches this call.
  Overload 1 of 2, '(props: AnimateProps<ViewProps> | Readonly<AnimateProps<ViewProps>>): View', gave the following error.
    Type '{ children: Element[]; animatedProps: Partial<{ pointerEvents: string; }>; style: ({ opacity: 0 | 1; } | { backgroundColor: string; flex: number; })[]; }' is not assignable to type 'Readonly<AnimateProps<ViewProps>>'.
      The types of 'animatedProps.pointerEvents' are incompatible between these types.
        Type 'string | undefined' is not assignable to type '"auto" | "none" | "box-none" | "box-only" | SharedValue<"auto" | "none" | "box-none" | "box-only" | undefined> | undefined'.
          Type 'string' is not assignable to type '"auto" | "none" | "box-none" | "box-only" | SharedValue<"auto" | "none" | "box-none" | "box-only" | undefined> | undefined'.
  Overload 2 of 2, '(props: AnimateProps<ViewProps>, context: any): View', gave the following error.
    Type '{ children: Element[]; animatedProps: Partial<{ pointerEvents: string; }>; style: ({ opacity: 0 | 1; } | { backgroundColor: string; flex: number; })[]; }' is not assignable to type 'Readonly<AnimateProps<ViewProps>>'.
      Types of property 'animatedProps' are incompatible.
        Type 'Partial<{ pointerEvents: string; }>' is not assignable to type 'Partial<AnimateProps<ViewProps>>'.
        
        
        And if I go with the mouse on top of the pointerEvents: (property) pointerEvents?: string | undefined

**Comment by giantslogik** [comment]
>     
>     Found a solution by myself: const pointerEvents = useSharedValue<'auto' | 'none'>('auto');
>     instead of using the opacityControl I've just created another sharedValue and the typescript error is gone
> ```

You don't need another shared value.
`const animatedProps = useAnimatedProps(() : {
        pointerEvents: 'box-none' | 'none' | 'box-only' | 'auto' | undefined;
      } => {
const pointerEvents = opacityControl.value === 0 ? 'none' : 'auto';
//https://github.com/software-mansion/react-native-reanimated/issues/1059
return {
pointerEvents,
};
});`
