### ISSUE TITLE
Question about createAnimatedComponent type

### ISSUE THREAD

**Issue by TheWirv** [software-mansion/react-native-reanimated#1063]
## Description
Is there a specific reason why `createAnimatedComponent` expects and returns `any`? instead of e.g. `T`?

If that would be a better solution, I'll gladly submit a PR. I just thought, maybe there's some specific reasoning behind it.

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 1.10.1

**Comment by jakub-gonet** [comment]
Yeah, [here are few links](https://github.com/software-mansion/react-native-reanimated/pull/791) regarding that issue. Problem is, we don't have TS tests setup (yet) and every change in types has to be checked locally.
