### ISSUE TITLE
How achieve callback onOpen in a Swipe Item in Flat List

### ISSUE THREAD

**Issue by Piero87** [software-mansion/react-native-reanimated#1069]
## Description

Hi,
I have created a swipe animation on items in a Flatlist, but I can't understand how create a callback to the parent when the the animation is completed and the swipe is "open", this is not a swipe to delete, I wanna swipe to reveal some buttons, and I want a callback when the buttons are revealed, and I can't understand how achieve this.
I have tried with the `call` function of reanimated with some condition, but it's triggered in loop and I can't understand how trigger it one time when the button are visibile and the animation is completed. I upload an example in a github project that I link here below.

I want ask you also two more thing:
- Can the code I write be improved?
- Can I create a logic to permit only one row open at a time? for example when I swipe another row I want the the row open close with the same animation, can someone guide to this? I think I have to use refs but I don't know how.

P.S. I can't use at the moment reanimated v2 because in my project I use Realm JS and it's not compatibile yet with Hermes Engine for android.

Thank you

## Code

https://github.com/Piero87/TestSwipeReanimated

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 1.10.1

**Comment by jakub-gonet** [comment]
The simplest way to do that is to pass the callback to the Component and use `call()` as you wrote. I don't see any use of it in your code so I can't tell if you're using it wrong. Keep in mind that you may cause rerenders when updating the state or props (which may loop your animation), you can also specify which values should trigger the `call()` node. One way to do that is to set some flag when you want to trigger the callback and use `call` in `useCode` or `Code` component which decomposes complex animations a bit.

I skimmed through your code and looks good to me, there's nothing particularly wrong with it.

You can create some manager passing Animated value which will act as a flag telling if the animation can execute, but that's my idea.

This is more like a Stackoverflow question about Reanimated, focused on the concrete example, so I'm closing it.

**Comment by Piero87** [comment]
Thanks you for your answer, I will try to ask it on stackoverflow, anyway, this is the callback I have tried:

```
  onOpenCallback = () => {
    console.log("OPEN");
    this.props.onOpen();
  };
```

```
                cond(clockRunning(this.clock2), [
                  spring(this.clock2, this.animState, springConfig(MAX_TRANSLATE * this.props.buttons.length)),
                  // Stop and reset clock when spring is complete
                  cond(this.animState.finished, [
                    stopClock(this.clock2),
                    set(this.animState.finished, 0),
                    **call([], () => this.onOpenCallback())**
                  ]),
                ]),
```

and the result is console.log("OPEN"); in loop in console, until I close the row, then stops.
I have also updated the code in the repository, can you help me?

**Comment by jakub-gonet** [comment]
As I said, you should try setting a flag in the stop branch:
```js
(...)

cond(this.animState.finished, [
                    stopClock(this.clock2),
                    set(this.animState.finished, 0),
                    set(this.shouldTriggerCallback, 1)
                  ]),
```

and use `Code` component to call it:
```jsx
<Code exec={
	() => 
	block([
	call([this.shouldTriggerCallback], () => this.onOpenCallback()), 
	set(this.shouldTriggerCallback, 0)])} 
/>
```

(I haven't tested it, but should work)

**Comment by Piero87** [comment]
Thank you for the answer, I had already tried a solution similar to yours, and I have the same problem, the loop of "Open" in console until I close the swipe. I have commited your suggestion in the repository so you can see if you want
