### ISSUE TITLE
[Question] I'm considering use Reanimated in a production app...

### ISSUE THREAD

**Issue by alpfilho** [software-mansion/react-native-reanimated#108]
... and I want to know if it is stable enough for making the same things that the original Animated API does.
If not, what I can do to help?

**Comment by enesTufekci** [comment]
I am also planning to use this library on production. Unfortunately the production ready alternatives are not good enough. So far I had no major problem with this (imo its one of the most under appreciated libraries).

**Comment by jakub-gonet** [comment]
Hey, I'm really sorry for the very late response 😔

As for now (11-2019) react-native-reanimated is production-ready and latest release is [1.4.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/1.4.0)

If you have other concerns regarding this topic feel free to reopen this issue
