### ISSUE TITLE
Require dependency array in useDerivedValue?

### ISSUE THREAD

**Issue by scottmas** [software-mansion/react-native-reanimated#1082]
## Description

Having come from the world of Mobx where auto dependency retriggers are the order of the day and having seen extremely complex and hard to debug code clusters emerge, my plea is for reanimated to not go down that road (unless there’s compelling technical reasons requiring it that I’m unaware of). In addition to being easier to debug, explicit dependency arrays are also more “React-ey” since users are used to dependency arrays in hooks.

Another confusing thing about not having dependency arrays is the way in which imperative effects are automatically triggered in response to value changes, as can be seen at the scroll to documentation: [https://docs.swmansion.com/react-native-reanimated/docs/next/api/nativeMethods/scrollTo/](https://docs.swmansion.com/react-native-reanimated/docs/next/api/nativeMethods/scrollTo/). This type of usage should properly be called an “effect” due to its similarity with Reacts useEffect.

What are your thoughts?

**Comment by karol-bisztyga** [comment]
Reanimated 2 API is constructed as following(regarding `useDerivedValue` and `useAnimatedStyle`): automatically update on any changes of those shared values, which have been mentioned in the callback body.

We are planning to add the functionality of dependencies array but this is connected to rerender handling and I suppose it isn't related to what you are talking about.

Getting back, what do you mean by "hard to debug code clusters"? If you meant some kind of deep recursions or complicated dependecy graphs I do not really think we are going to encounter such things in Reanimated 2. Of course you could hack your way to achieve a code like this but considering real usecases, I would have some doubts. It is however possible to add such functionality. I suppose it would make the API way less handy though.

As for the `scrollTo` example, the point was to call it on the UI thread, however I get your point here, like it isn't really using the derived value, just a space it provides, thus it in fact could be handled more gracefully(?). We will think about it, thanks.

**Comment by terrysahaidak** [comment]
I've been using Reanimated from March and it required explicit dependency array back then. From my personal experience, I can tell the new API which automatically tracks everything for you is way-way easier and handy. Each of my handlers had 8-15 dependencies. I'm sure in that case it's really easy to just forget some of the dependencies and spend a few hours debugging. Back then it would not work if I forgot to pass some of the dependencies, but with your proposal, it should.

I think this specific example with scrollTo could benefit from `useAnimatedReaction` hook

```ts
useAnimmatedReaction(
  () => scrollTo.value,
  (value) =>  scrollTo(aref, 0, value * 100, true),
);
```

**Comment by scottmas** [comment]
I haven't used Reanimated 2 much, so that real world experience is very interesting Terry. If the average number of dependencies is 8-15, that is a bit ludicrous.

And to your questions Karol, what you described is exactly what happened in my old MobX experience: deep recursive relationships and extremely complicated dependency graphs. The end result was that changing _anything_ potentially had the ability to change _everything_. Because of this, my data layer became a huge source of bugs and bugs were extremely difficult to track down. But I can see how it might be the case that such complexity may not arise in UI animations. Has real world experience on complex animations shown this to be the case?

As to your proposal Terry, it seems reasonable to me. Although I would personally prefer a more standard React style API, e.g. `useAnimatedEffect(() => {}, [])` or the like.

**Comment by terrysahaidak** [comment]
You can check my project reanimated-gallery which may be kinda the "real world usage". 

Btw, I use mobx (Mobx-State-Tree) too.

**Comment by karol-bisztyga** [comment]
I understand your point, however we've done some animations(calling one complex is kind of a statement that isn't well specified) and that's never been a case. If, in the future, it starts to be a case/problem we will switch to dependency array or at least give people an alternative. For now I don't think this is what's going to happen. Thanks for sharing your opinion, it means a lot to us. Does it answer your question @scottmas ?

**Comment by scottmas** [comment]
I think I can be brought on board auto dependency tracking. Since it only is for UI animations it does seem likely that the recursive nesting I was seeing in old Mobx code will be unlikely to happen.

I still would like to see some sort of differently named named function to drive imperative code like the scrollTo example. It just feels more "proper" to me, but maybe it's sixes. 

Thank you!

**Comment by artemis-prime** [comment]
Likely few will read this far, but in case, I've been using mobx on dozens of production projects since about 2016 with much contentment. So I feel the need to respond to the criticism of and perhaps influence the core issue of implicit dependencies as well.

IME, `mobx` is only "to responsive" if one doesn't use it well.  For example, if overused, `autorun` might have some `observables` updating while others are just dereferenced, which can produce the issues you're talking about.  On the other hand, having many small "mini-stores" that do one simple thing, and are often activated and cleaned-up via `useEffect()` almost never leads to these kinds of issues.  Another very underappreciated pattern in `mobx` is `reaction`, which allows you to precisely control what is listened to, and what is the effect.  I've found it more and more useful as time goes on.

Overall I've found it to be a far superior solution to React's relatively awkward state management than say, Redux.  FWIW, these days, neither I, not the juniors I train and manage ever run into the issues you're having.  

Good work, @mweststrate.  Maybe you can to chime in about the autodependency issue generally?
