### ISSUE TITLE
Animated node with ID {ID} does not exists

### ISSUE THREAD

**Issue by mldb** [software-mansion/react-native-reanimated#109]
sometimes when an animation is running and user press back and component unmount this error happening

in com.swmansion.reanimated.NodesManager

**Comment by osdnk** [comment]
Hi, @mldb 
Would you mind attaching some code?

**Comment by dlindstrm** [comment]
I have the same issue. When the component unmounts and I use `setValue` about the same time, it crashes in disconnectNodes in NodesManager.java. I have several other animated values that listens to gesture state and onScroll event. However, when I remove the setValue call it never crashes..

Just a simple example to clarify what is happening:
```
this.animatedWidth = new Value(0)

componentDidMount() {
  this.mounted = true
}

componentWillUnmount() {
  this.mounted = false
}

onLayout = e => {
  this.mounted && this.animatedWidth.setValue(e.nativeEvent.layout.width)
}
```

Any suggestions what to do? Stop throwing the `JSApplicationIllegalArgumentException`?

**Comment by osdnk** [comment]
@mldb 
Do you use setValue?

**Comment by mldb** [comment]
@osdnk Yes

**Comment by jakub-gonet** [comment]
Hey guys,
this thread seems inactive and PR submitted by @osdnk should fix this issue so I'm closing this issue.

If you have further concerns feel free to reopen
