### ISSUE TITLE
Reanimated2: exception in useAnimatedStyle

### ISSUE THREAD

**Issue by farwayer** [software-mansion/react-native-reanimated#1090]
## Description

Exception inside `useAnimatedStyle` function while trying to call `Object.values` on `updater._closure`:
```js
 TypeError: Cannot convert undefined value to object
```

### Screenshots

![Grimshot 2020-08-07 14-56-42](https://user-images.githubusercontent.com/2343101/89643582-bfb64200-d8be-11ea-9640-f00bc305098e.png)

## Package versions

- Platform: Android (not tested on iOS)
- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.5
- Hermes: 0.5.2-rc1
- Babel config: 
```js
module.exports = {
  plugins: [
    ['@babel/plugin-proposal-decorators', {legacy: true}],
    '@babel/plugin-proposal-export-namespace-from',
    ['babel-plugin-module-resolver', {root: 'src'}],
    'react-native-reanimated/plugin',
  ],
  presets: ['module:metro-react-native-babel-preset'],
}
```

**Comment by karol-bisztyga** [comment]
Hey, thanks for reporting, could you please provide a code snippet which causes the error?

**Comment by farwayer** [comment]
Nothing special, just calling `useAnimatedStyle`:
```js
useAnimationStyle(() => ({
  transform: [...],
}))
```
Look like it is more environment issue.

**Comment by terrysahaidak** [comment]
Did you try to run metro with reset cache?

**Comment by farwayer** [comment]
Thanks! Look like the problem really was with metro cache.

**Comment by terrysahaidak** [comment]
@karol-bisztyga @jakub-gonet worth adding this specific case where it throws on "`something._clousure` of undefined" to throubleshooting section in the docs

**Comment by jakub-gonet** [comment]
it's only connected with cache or something else as well?

**Comment by terrysahaidak** [comment]
I saw this like 5 times already. All the fixes were cache.

**Comment by NateAGeek** [comment]
I know web support is still technically in a different release, but I am experiencing this in V2 with TypeScript...

**Comment by terrysahaidak** [comment]
What exactly?

**Comment by NateAGeek** [comment]
Sorry for the lack of details. However, I'm using React Native Web and attempting to use Reanimated 2. It appears with my current configuration I am getting the following errors.

```×
TypeError: Cannot convert undefined or null to object
useAnimatedStyle
node_modules/react-native-reanimated/src/reanimated2/Hooks.js:270
  267 | export function useAnimatedStyle(updater, dependencies) {
  268 |   const viewTag = useSharedValue(-1);
  269 |   const initRef = useRef(null);
> 270 |   const inputs = Object.values(updater._closure);
  271 |   const viewRef = useRef(null);
  272 | 
  273 |   // build dependencies




src/components/MenuDrawer/MenuSection/MenuItem/index.tsx:28
  25 | const variantProps = useRestyle([menuVariants], restyleProps);
  26 | const offset = useSharedValue(0);
  27 | 
> 28 | const animatedStyles = useAnimatedStyle(() => {
  29 |   return {
  30 |     transform: [{ translateX: offset.value * 255 }],
  31 |   };
```

I'm not sure if this is due to some configuration on my end. However, it does seem similar to the error above.

**Comment by jakub-gonet** [comment]
@NateAGeek, did you install the babel plugin in your project?

**Comment by NateAGeek** [comment]
Darn, I am sorry if I am wasting time. However, I did indee forget to add the react-native-reanimated/plugin to my babel config.

```
module.exports = {
  plugins: [
    '@babel/plugin-proposal-class-properties',
    ["module-resolver", {
      "alias": {
        "^react-native$": "react-native-web"
      }
    }],
    'react-native-reanimated/plugin',
  ],
  presets: [
    //"module:metro-react-native-babel-preset",
    "babel-preset-gatsby",
  ]
};

```
The added ` '@babel/plugin-proposal-class-properties'` did not resolve the current issue I am facing. 

```
The project's Babel config is invalid: Unexpected token =

 ERROR

/app/client/node_modules/react-native-reanimated/plugin.js:108
  trie = [{}, false];
       ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/app/client/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/app/client/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/app/client/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at requireModule (/app/client/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPlugin (/app/client/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/files/plugins.js:68:17)
    at createDescriptor (/app/client/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/app/client/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/app/client/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/app/client/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
```

If this error is starting to differ heavily from the bug above, then I can create a new issue.

**Comment by NateAGeek** [comment]
I was able to resolve the babel issues by changing my babel.config.js to .babelrc.json as follows:
```
{
  "presets": [
    "babel-preset-gatsby"
  ],
  "plugins": [
    "react-native-reanimated/plugin"
  ]
}
```
I think this might have been a bit of a project specific case. However, I am starting to have issues with storybook(where I will open a ticket on their end). But I got a spring example to work on web!

**Comment by SounakB** [comment]
I am having the same issue as @NateAGeek 

The project's Babel config is invalid: Unexpected token =

/node_modules/react-native-reanimated/plugin.js:108
  trie = [{}, false];
       ^

**Comment by terrysahaidak** [comment]
> I am having the same issue as @NateAGeek 
> 
> The project's Babel config is invalid: Unexpected token =
> 
> /node_modules/react-native-reanimated/plugin.js:108
>   trie = [{}, false];
>        ^

Please, upgrade your node version to be 12

**Comment by SounakB** [comment]
> > I am having the same issue as @NateAGeek
> > The project's Babel config is invalid: Unexpected token =
> > /node_modules/react-native-reanimated/plugin.js:108
> > trie = [{}, false];
> > ^
> 
> Please, upgrade your node version to be 12

Using node version 14 fixed this.

**Comment by ahmadsiddiq-lang** [comment]
yarn start --reset-cache

run this code, it worked for me

refrens: https://docs.swmansion.com/react-native-reanimated/docs/next/troubleshooting/

**Comment by bharat-tiwari** [comment]
this is not fixed/closed yet, I too getting the same issue `yarn start --reset-cache` didn't help me

```
const AnimatedBar: () => React$Node = () => {
    const barWidth = useSharedValue(30);
    const barAnimatedStyle = useAnimatedStyle(() => {
        return {
            width: withTiming(barWidth.value, {
                duration: 500,
            }),
        };
    });

    const setBarWidth = () => {
        barWidth.value = 300;
    }

    return (
        <React.Fragment>
            <View>
                <IconButton
                    icon="menu-left"
                    color="#aaaaaa"
                    size={50}
                    onPress={() => setBarWidth()}
                />
            </View>
            <Animated.View style={[styles.bottomBar, barAnimatedStyle]}>
                <Text>BottomBar</Text>
            </Animated.View>
        </React.Fragment>
    );
}
```

**bable.config.js:**

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
  ],
};
```


Versions:

```
"react-native": "0.63.4",
"react-native-reanimated": "2.0.0-alpha.6",
```

**Comment by bharat-tiwari** [comment]
ok, after uninstalling/reinstalling , resetting yarn cache, `watchman watch-del-all`, etc couple of times, its working good now on iOS, the latest version I have is `"react-native-reanimated": "^2.0.0-alpha.9.2"`

On Android I am getting Hermes specific issues -  
ERROR    ReferenceError: Property '_eventTimestamp' doesn't exist, js engine: hermes
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes

haven't found any fix for this yet, I'll update here once I get to resolve this android hermes issue

**Comment by bharat-tiwari** [comment]
got it working for Android as well now with the below change to `android/app/build.gradle`

```
project.ext.react = [
    entryFile: "index.js", // Added this as given [here](https://reactnative.dev/docs/hermes)
    enableHermes: true,  // clean and rebuild if changing // <- this anyway is mentioned in the reanimated2 Installation guide
]
...
...
...
def enableHermes = project.ext.react.get("enableHermes", true); // <- changed 2nd param from false to true

```

after this, `cd android && ./gradlew clean` (or `cd android && sudo ./gradlew clean`)

removed app from android, yarn run android again, and this time no hermes errors
animation is working good now on android as well

**Comment by nandorojo** [comment]
I'm getting this error, but only when I try to run the app with Expo + Next.js and `2.0.0-rc.0`.

`expo start --ios` and `--web` both work fine.

I'm trying to reproduce/debug it, but wanted to see if anyone else ran into that.

It seems to be directly related to using `useAnimatedStyle`. Oddly, when I `console.log` inside of `useAnimatedStyle`, everything logs what is expected. I've tried clearing the cache and such, but this is not the issue.

If I remove `useAnimatedStyle` from my code, it works fine again. There isn't a very clear stack trace of what line is causing this.

# Update

I think I fixed it by wrapping a function being passed to `runOnJS`, as mentioned in the docs.

This broke:

```js
const [, safeToUnmount] = usePresence()

const style = useAnimatedStyle(() => {
  const callback = () => {
    runOnJs(safeToUnmount)()
  }

  ...etc
})
```

This worked:

```js
const [, safeToUnmount] = usePresence()

const safeToUnmountWrapped = () => {
  safeToUnmount()
}

const style = useAnimatedStyle(() => {
  const callback = () => {
    runOnJs(safeToUnmountWrapped)()
  }

  ...etc
})
```

**Comment by monthem** [comment]
If you're trying to use "useAnimatedStyle" working on storybook web. You may have to write "worklet" at the top of the passed function.

```js
const animatedStyle = useAnimatedStyle(() => {
    "worklet";
    
    //some logic
    return {
        //your style
    }
})
```

For my case, it happened because babel couldn't perceive [directive literal](https://tc39.es/ecma262/#directive-prologue) of useAnimatedStyle, which, I guess, should have been automatically added when I use the hook.

As a result, react-native-reanimated/plugin couldn't work as supposed. [This lines of code](https://github.com/software-mansion/react-native-reanimated/blob/462e21ee18e732cabc4381816486a5808ce7e961/plugin.js#L446) are supposed to find our codes (which we applied useAnimatedStyle) and process 'woklet' part.

So, the simple solution, which doesn't feel right, is to write "worklet" at the top of the passed function of useAnimatedStyle. So that, reanimated babel plugin can perceive the passed function wth directive.

Maybe it's a problem of storybook's default babel plugin. I suspect that one of babel plugin used in building storybook is blocking reanimated worklet to be injected in a right way.

**Comment by terrysahaidak** [comment]
@monthem could you please open a new issue regarding storybook?

babel plugin should handle all the default hooks. looks like storybook's babel plugin messes around with the hooks names and reanimated plugin can't detect them since worklet this is still working.

**Comment by chj-damon** [comment]
```code
watchman watch-del-all
yarn start --reset-cache
```

this doesn't work for me.

**Comment by JaccoGoris** [comment]
I have the same problem, I've followed all the guides I could find, did everything here, still keeps breaking
    ```TypeError: Cannot convert undefined or null to object
        at Function.values (<anonymous>)

      at useAnimatedStyle (node_modules/react-native-reanimated/lib/reanimated2/Hooks.js:332:27)```

**Comment by Parveshdhull** [comment]
This error occurs because `useAnimatedStyle` expects `worklet` as an argument ([ref](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle#updater-function)) and `react-native-reanimated/plugin` is supposed to convert the passed argument to `worklet` automatically ([ref](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/plugin.js#L7)).
But if the passed function didn't get converted into a `worklet` due to any reason above error shows.
For [example](https://stackoverflow.com/questions/72500152/interop-how-to-use-javascript-directive-in-clojurescript) directive will not work in cljs project.

Above error is only shown in the older version, like `2.1.0`, `2.2.0`, etc. newer versions don't show errors due to [this](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/src/reanimated2/hook/useAnimatedStyle.ts#L412) check, but the app just crashes with these logs

```
06-05 01:21:19.812 12779 12779 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Tried to synchronously call function {G__75911} from a different thread.
06-05 01:21:19.812 12779 12779 F DEBUG   : 
06-05 01:21:19.812 12779 12779 F DEBUG   : Occurred in worklet location: /home/parvesh_monu/Desktop/ArchFiles/React/status-react/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (492:18)
06-05 01:21:19.812 12779 12779 F DEBUG   : 
06-05 01:21:19.812 12779 12779 F DEBUG   : Possible solutions are:
06-05 01:21:19.812 12779 12779 F DEBUG   : a) If you want to synchronously execute this method, mark it as a Worklet
06-05 01:21:19.812 12779 12779 F DEBUG   : b) If you want to execute this method on the JS thread, wrap it using runOnJS
06-05 01:21:19.812 12779 12779 F DEBUG   :   at void com.swmansion.reanimated.AndroidErrorHandler.raise(java.lang.String) (AndroidErrorHandler.java:6)
```

I think there should also be an exported method for creating `worklet` instead of only relying on the directive. The method which currently exists is not completely implemented and is being removed in https://github.com/software-mansion/react-native-reanimated/pull/3254 PR.

Please don't remove the method and fix its implementation. Thank you cc: @piaskowyk
