### ISSUE TITLE
Get scroll velocity of ScrollView's onScroll event

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1105]
## Description

Hi! Is it possible to map the ScrollView's scroll velocity to an animated value? Since there is no mapping in the nativeEvent of the onScroll property (only y position), I've thought the only way to achieve this is to somehow monitor rate of change within time.

Is it possible to get the scroll velocity from just the contentOffset.y value? Or is there another method?

(using reanimated v1)

**Comment by jakub-gonet** [comment]
I'm afraid this is more RN question than a Reanimated question.

You can certainly try using y value and time to calculate velocity, you can try doing that with the help of [deceleration rate](https://reactnative.dev/docs/scrollview.html#decelerationrate) and a bit of physics as well. If RN doesn't send velocity in the event we can't expose it to the animated Value.

**Comment by mrousavy** [comment]
@jakub-gonet Sorry to bother, I've been trying to get this working for some time now, read a lot of tutorials but I couldn't figure out how to implement such animation. I've played around with `diff`, but couldn't come up with a solution, do you mind pointing me in the right direction?
