### ISSUE TITLE
Cant use same useAnimatedStyle for 2 components

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-reanimated#1106]
## Description

If I try to use an animated style on 2 components, one of the components does not have the style set. It seems that I have to create a duplicate one in order for it to work. 

See https://github.com/kyle-ssg/kyles-reanimated-2-playground/blob/master/App/components/Modal.tsx#L94 for replication. As soon as I define a duplicate useAnimatedStyle, both views work.

### Screenshots

```
    <Animated.View style={[styles.backdrop, **opacityStyle2**]}/>
           <ModalInner
               onDismissPress={onDismissPress}
               opacityStyle={opacityStyle}
               style={style}
               fadeContent={fadeContent}
           >{children}</ModalInner>
```

![image](https://user-images.githubusercontent.com/8608314/89915774-b1359680-dbee-11ea-81c0-3a95de28af2e.png)

```
    <Animated.View style={[styles.backdrop, **opacityStyle**]}/>
           <ModalInner
               onDismissPress={onDismissPress}
               opacityStyle={opacityStyle}
               style={style}
               fadeContent={fadeContent}
           >{children}</ModalInner>
```

![image](https://user-images.githubusercontent.com/8608314/89915933-e215cb80-dbee-11ea-95fd-05e77541e556.png)

## Steps To Reproduce

1. use an animated style on 2 views based on useAnimatedStyle

### Expected behaviour
I'd expect to be able to reuse the same style.

### Actual behaviour
The style only gets applied to 1 Animated.View if using on multiple.

## Snack or minimal code example
https://github.com/kyle-ssg/kyles-reanimated-2-playground

## Package versions

```
   "react": "16.13.1",
    "react-native": "0.63.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "2.0.0-alpha.5"
```

**Comment by jakub-gonet** [comment]
Please read discussion under #920
