### ISSUE TITLE
react-native-reanimated:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by wasim-abuzaher** [software-mansion/react-native-reanimated#1109]
## Description

Started to see build error on Android as per the below snippet

```> Task :react-native-reanimated:compileDebugJavaWithJavac FAILED
/Users/.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:171: error: cannot find symbol
              new GuardedRunnable(mContext.getExceptionHandler()) {
                                          ^
  symbol:   method getExceptionHandler()
  location: variable mContext of type ReactContext
Note: /Users/.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.
```
I tried to `npx jetify`, clean and rebuild the android project in Android Studio, remove the node_modules and re-run `npm install` but none worked for me

## Steps To Reproduce

1.

## Package versions

- React: "16.8.3"
- React Native: "0.59.9"
- React Native Reanimated: "^1.12.0"

**Comment by jakub-gonet** [comment]
Thanks for reporting.

This is related to #1031 which changes used a c-tor overload of `GuardedRunnable` which was deprecated in RN 0.61.

Can you try removing `.getExceptionHandler()` part of `node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java#167` line and check if your project builds correctly?

**Comment by jakub-gonet** [comment]
Reproduced on 0.59.

Fixed by #1110.

**Comment by wasim-abuzaher** [comment]
Thanks, v1.13.0 did the trick

**Comment by rajeevverma076** [comment]
Not working 

> Task :react-native-reanimated:downloadBoost FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
