### ISSUE TITLE
Task :react-native-reanimated:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by jameerjbr** [software-mansion/react-native-reanimated#1112]
## Description

react-native run-android this error come. please help me resolve this problem

### Screenshots
<img width="1429" alt="Screenshot 2020-08-12 at 5 58 44 PM" src="https://user-images.githubusercontent.com/30979037/90015115-c3363880-dcc5-11ea-9542-aa856d432b1b.png">

## Steps To Reproduce

1.

## Package versions

- React:  16.8.6
- React Native: 0.60.5
- React Native Reanimated: ^1.4.0

**Comment by jakub-gonet** [comment]
We are aware of this problem, the next release will be in a few hours.

You can try applying the patch from https://github.com/software-mansion/react-native-reanimated/commit/c3aefd5fa9ccfae62f70b154ca26ef821164cec2 commit as a temporary solution.
