### ISSUE TITLE
TypeError: Cannot read property 'createNode' of undefined

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [software-mansion/react-native-reanimated#1118]
## Description

When i run jest test, it is giving error  **TypeError: Cannot read property 'createNode' of undefined**.

### Screenshots
<img width="957" alt="Screenshot 2020-08-13 at 11 57 57 AM" src="https://user-images.githubusercontent.com/9896335/90101441-4efaa400-dd5c-11ea-9de7-a5452923450b.png">

<img width="599" alt="Screenshot 2020-08-13 at 11 59 18 AM" src="https://user-images.githubusercontent.com/9896335/90101512-70f42680-dd5c-11ea-9ff9-648d9f1ecc56.png">

## Steps To Reproduce

1. Just run **npm run test** with out any additional setup

### Expected behavior
It should run the tests successfully

### Actual behavior
It is giving the error while running the tests

## Snack or minimal code example

```
import 'react-native';
import React from 'react';

it('renders correctly', () => {
  // renderer.create(<App />);
  expect(1 + 1).toBe(2);
});

```
## Package versions

<img width="655" alt="Screenshot 2020-08-13 at 11 24 06 AM" src="https://user-images.githubusercontent.com/9896335/90099193-81ee6900-dd57-11ea-82b4-43fcb58bbf5d.png">

**Comment by jakub-gonet** [comment]
This is correct behavior as native modules aren't available while jest is running tests.

Add mock to get it to work, here's tutorial from react navigation:
https://reactnavigation.org/docs/testing/

**Comment by mtzfactory** [comment]
I'm having the same issue, tried to configure Jest but still same problem.

Currently using `react-native-reanimated` version `^1.13.2`

**Comment by Ridhi9977** [comment]
I have the Same issue when i write
 const Drawer = createDrawerNavigator();
and error appears
TypeError: Cannot read property 'createNode' of null, js engine: hermes 

How to solve it ?

**Comment by lukadisanto** [comment]
Same issue, how to resolve?

**Comment by AphexHenry** [comment]
1. delete the node_module folder
2. npm install
3. follow the steps here https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/ (mostly the babel file edit)

**Comment by lukadisanto** [comment]
Solved by integrating react-native-reanimated manually into android:

-  react-native.config.js:
`module.exports = {
  dependencies: {
    ....
    'react-native-reanimated': {
      platforms: {
        android: null
      }
    },
  }
};`

- android/app/build.gradle:
`...
dependencies {
   ...
   implementation files("../../node_modules/react-native-reanimated/android/react-native-reanimated-69-jsc.aar", ':react-native-reanimated')
`

- MainApplication.java:
`...
import com.swmansion.reanimated.ReanimatedPackage;
...
public class MainApplication extends MultiDexApplication implements ReactApplication {
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    ...
    @Override
    protected List<ReactPackage> getPackages() {
       return Arrays.<ReactPackage>asList(new MainReactPackage(),
           ...
           new ReanimatedPackage(),
       );
    }
    ...
}
`
