### ISSUE TITLE
Question on runOnUI/worklets - could this be used for performance improvements unrelated to animations?

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-reanimated#1120]
## Description

The whole worklet and runOnUI pattern is really interesting, my initial reactions to seeing this were possibilities totally unrelated to animation.

Given something as simple as this:

```
function updateValue(prop, cb) {
  'worklet';
  // do some complex non-blocking stuff
  cb(newData)
}

const VerticalSlider: FunctionComponent<ComponentType> = ({someProp}) => {
  const [uiResponse, setUIResponse] = useState("0")
  useEffect(() => {
    runOnUI(expensiveOp)(someProp, setUIResponse);
  }, [someProp]);

```

Unless I'm misunderstanding, there could be some use cases outside of animation where we could see performance benefits by offloading general operations to the other thread (i.e. data processing). Am I correct here or is it the case that rapid invocation of such runOnUI would often cost more than its worth.

I guess in general my question is do you see worklets / runOnUI as a potential pattern for performance improvements? I used a component set state example here, but Im also thinking about things such as sorting / filtering large lists or post processing of API responses.

**Comment by yolpsoftware** [comment]
As I understand it, the whole point of worklets and `runOnUI` is to run Javascript code fragments on the UI thread. This helps us to avoid crossing the bridge when stuff happens on its UI side (e.g. animations triggered by gestures).

You could probably use worklets and `runOnUI` to run data processing on the UI thread. However, this would mean that during such a computation, the UI thread is blocked, which could result in an unresponsive UI.

To me, it seems that one of the advantages of React Native is that generally, all the code you write does *not* run on the UI thread. This is the reason that in most scenarios, you don't have to do anything to keep your UI responsive. Imperative programming of UIs is hard. For animations, where the declarative nature of React shows its limits, you can program the UI thread using worklets. This is afaik currently the only way to directly run code on the UI thread, and this is a good thing.

If you have computations that really take a long time, you are better off by either

- moving them to the server
- running a third thread to run the computations, e.g. [react-native-workers](https://github.com/devfd/react-native-workers) or [this simpler approach](https://medium.com/@inkdrop/a-simple-way-to-run-js-in-background-thread-on-react-native-8fff345576da).

**Comment by kyle-ssg** [comment]
Oh wow that second approach is immense, but yeah I guess one of the worker libs would be the best approach.

Thanks a lot for your explanation it makes total sense!
