### ISSUE TITLE
TranslateX Animation Not Working with Flexbox

### ISSUE THREAD

**Issue by leonyjiang** [software-mansion/react-native-reanimated#1121]
## Description

Hi, I've been using this library for animations and have been really enjoying it so far. Thank you all for the hard work!

**The Problem**

I'm currently facing an issue implementing a basic search bar animation. The desired UI is for the search bar to shrink in width (on the right side) when focused on and reveal a "Cancel" button. I animated the `translateX` property of the "Cancel" button and was hoping flexbox would dynamically resize the text input. Unfortunately, this doesn't work as expected:

![translatex](https://user-images.githubusercontent.com/35908040/90184289-b8cd7a80-dd69-11ea-890f-dd3848d98634.gif)

As shown, the text input doesn't grow — it's as if the "Cancel" button still occupies that space (which it doesn't). This is probably due to my lack of understanding of how flexbox handles dynamic readjustments.

Another solution that semi-works involves animating the `width` property, though I've read that animating height, width, and other layout properties is sub-optimal due to the extra layout calculations. That looks like:

![width](https://user-images.githubusercontent.com/35908040/90185137-17dfbf00-dd6b-11ea-83cb-e7849561529a.gif)

But this is still not the desired animation, as the text layout changes along with the width. What is a straightforward and/or recommended approach to create this type of animation? Any help/resources would be greatly appreciated!
## Code
```js
const translateX = new Value(57); // initial position, 57 is width of cancel button

const handleFocus = () => { // handles focus on search bar
    const translateXInConfig = {
        duration: 200,
        toValue: 0,
        easing: Easing.inOut(Easing.ease),
    }
    timing(translateX, translateXInConfig).start();
}

const handleBlur = () => { // handles blur or press of "Cancel" button
    const translateXOutConfig = {
        duration: 200,
        toValue: 57,
        easing: Easing.inOut(Easing.ease),
    }
    timing(translateX, translateXOutConfig).start();
}

return ( // rendered JSX
    <View style={styles.container}>
        <View style={styles.inputContainer}>
            <SearchIcon />
            <TextInput style={styles.input} onFocus={handleFocus} onBlur={handleBlur}/>
        </View>
        <Animated.View style={{ transform: [{ translateX }] }}>
            <TouchableOpacity onPress={handleBlur}>
                <Text>Cancel</Text>
            </TouchableOpacity>
        </Animated.View>
    </View>
);

const styles = StyleSheet.create({ // only the relevant layout styles
    container: {
        flexDirection: "row",
    },
    inputContainer: {
        flexDirection: "row",
        flexGrow: 1,
    },
    input: {
        flex: 1,
    }
});
```

### Package versions

From `package.json`:
- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: ^1.9.0

**Comment by kyle-ssg** [comment]
@leonyjiang, I dont think this is really related to animations and more so a flexbox / styling issue. If you could get a quick repo or snack I could try help out. It might be that you'd want to position:"absolute" something here.

**Comment by leonyjiang** [comment]
I'd really appreciate that! [Here's the Snack I created](https://snack.expo.io/@leonyjiang/search-bar-animation). A potential solution would be to animate both the `width` property of the search bar and the `translateX` property of the cancel button, but I was hoping there'd be something simpler using flexbox.

**Comment by terrysahaidak** [comment]
I used to animate width of the bar here. But you need to measure the width of the cancel button.

**Comment by kyle-ssg** [comment]
Just spotted this, check https://snack.expo.io/@kyle-ssg/search-bar-animation @leonyjiang

**Comment by leonyjiang** [comment]
I think I'll go with that. Thank you @kyle-ssg, that was very helpful!
