### ISSUE TITLE
Issue with TimingAnimation

### ISSUE THREAD

**Issue by Biditmangal** [software-mansion/react-native-reanimated#1125]
## Description

error: Error: Unable to resolve module `./animations/TimingAnimation` from `node_modules\react-native-reanimated\src\Animated.js`:

## Steps To Reproduce

1. Just installed reanimated and this came, otherwise, everything was working fine. I was trying to use react-native-bottom-sheet library.

## Package versions

- React:"react": "16.13.1",
- React Native:"react-native": "^0.63.2",
- React Native Reanimated:"react-native-reanimated": "^1.13.0",
"react-native-gesture-handler": "^1.7.0",

**Comment by bluenex** [comment]
I experience this too. In my case, I cloned my project and did a clean install. `react-native run-ios` build is passing but metro bundler raises this exact error. 

I also found that revert `react-native-reanimated` to version `1.11.0` resolves the issue (1.12+ causes the same error). However, using `1.11.0` requires manual Jettify on Android.

**Comment by jakub-gonet** [comment]
This is related to stale caches, [here's a link](https://github.com/software-mansion/react-native-reanimated/issues/1007#issuecomment-662438323) that can help you
