### ISSUE TITLE
useValue throws error - Rendered more hooks than during previous render 

### ISSUE THREAD

**Issue by emclab** [software-mansion/react-native-reanimated#1126]
## Description

I am following this piece of [document](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/value) about how to use useValue in functional component because the dragging stops working after re-rendering in RN 0.62.2 app/react-native-reanimated 1.13/react-native-gesture-handler 1.7. Here is the code before change which runs fine:

                import Animated, { useValue } from "react-native-reanimated";
                .......
                const dragX = new Value(0);
                const dragY = new Value(0);

Here is with useValue:

               const dragX = useValue(0);   //<<== exactly same as it is in the document about value
               const dragY = new Value(0);

However the code above throws error:

![Capture](https://user-images.githubusercontent.com/946013/90301595-ceb86980-de55-11ea-8b87-a3931293ddd7.JPG)

Tried the following and the error is the same:

           const dragX = useValue(() => new Value(0));

I can't find more information about `value` except this one line statement in the document above.  Tried `useRef` and `useMemo` and the error is the same. What is the right way in function component to reference a value? Code example appreciated!

## Code

The hook is declared in method :

     const displayImg = (img_source, width, ht, index, modalWidth, modalHt, dataLen, sortFn) => {
        const aniIndex= new Value(index);
        const aniGridPR = new Value(gridPerRow);
        const dragX = useRef(new Value(0)).current;
        const dragY = new Value(0);
        const offsetX = new Value(0);
        const offsetY = new Value(0);
        const state = new Value(-1);
        const scale = new Value(1);
      .....
      }

### Package versions

- React: 16.11
- React Native: 0.62.2
- React Native Reanimated: 1.13.0

**Comment by jakub-gonet** [comment]
I'm guessing you're trying to call `displayImg` conditionally which breaks the method how React handles hooks. `useValue` is built on top of `useRef`, so this is problem with usage of hooks and not Reanimated.

Please provide full code defining and using `useValue`.
Closing until more info is given.

**Comment by emclab** [comment]
`jakub-gonet`, here is the code for function `displayImg`. Sorry it is long and a bit messy. I put a few lines for helping reading.

      function displayImg (img_source, width, ht, index, modalWidth, modalHt, dataLen, sortFn) {
        const aniIndex= new Value(index);
        const aniGridPR = new Value(gridPerRow);
        const dragX = useRef(new Value(0)).current;  //<<==here is the code with useRef/useValue. Tried one line only.
        const dragY = new Value(0);
        const offsetX = new Value(0);
        const offsetY = new Value(0);
        const state = new Value(-1);
        const scale = new Value(1);

        var gridPerRow;
        console.log("image width : ", width);
        console.log("image ht : ", ht);
        if (dataLen <= 4 && dataLen > 1) {
            gridPerRow = 2;
        } else if (dataLen > 4) {
            gridPerRow = 3;
        } else {
            gridPerRow = 1;
        };
        
                
        function onUp ([x, y, indx, gridPR]) {
            console.log("In on Up");
        };
                
        function onDrop ([x, y, indx, gridPR]) {
            var jump_y=0, jump_x=0, new_index, percentage;
            //jump_row               
            jump_y = y>0 ? Math.floor(y/ht) : -Math.floor(-y/ht);
            percentage = Math.abs((y%ht)/ht);
            //console.log("row percentage : ", percentage);
            if (percentage >= 0.3) (y>0 ? jump_y++ : jump_y--); //count if Y overlap 30% or more
            //jump col
            jump_x = x>0 ? Math.floor(x/width) : -Math.floor(-x/width);
            percentage = Math.abs((x%width)/width);
            if (percentage >= 0.3) (x>0 ? jump_x++ : jump_x--); //count if X overlap 30% or more
            new_index = indx + jump_y*gridPR + jump_x
            console.log("new index : ", new_index);
            if (new_index != indx) {
                sortFn(indx, new_index); //<<==sortFn is a method passed in from calling component to sort images after dragging.
            };
        };
        if (img_source && img_source!==[] && img_source!=={}) {
            if (dataLen == 1) { //<<==one image and no dragging but zooming.
                const scale = new Value(1);
                function onGestureStateChange() {
                    //handle scaling. not yet implemented
                };
                let scaleStyle = {
                    transform:[
                        { perspective: 500 },
                        {
                            scale :  scale
                        }
                    ]
                };
                return (
                    <><PinchGestureHandler onHandlerStateChange={onGestureStateChange}>  //<<==allow to zoom in image 
                        <Animated.View style={scaleStyle}>
                        <GridImage
                            img_source={img_source}
                            width={width}
                            ht={ht}
                            index={index}
                            modalWidth={modalWidth}
                            modalHt={modalHt}
                        />
                        
                        <ModalImage
                            img_source={img_source}
                            modalWidth={modalWidth}
                            modalHt={modalHt}
                            index={index}
                        />
                        </Animated.View>
                        </PinchGestureHandler>
                    </>
                    );
            } else {  //<<==when multiple images presented
                console.log("ani code");
                
                const addX = add(offsetX, dragX);
                const addY = add(offsetY, dragY);
                const transX = cond(eq(state, State.ACTIVE), addX);  
                const transY = cond(eq(state, State.ACTIVE), addY, 
                                        cond(eq(state, State.END), 
                                            cond(or(greaterOrEq(abs(divide(dragX,new Value(width))), new Value(0.3)), greaterOrEq(abs(divide(dragY,new Value(ht))), new Value(0.3))), 
                                                call([addX, addY, aniIndex, aniGridPR], onDrop))
                                            )  //<<==when image is moved 30% or more on X or Y, then call method onDrop. otherwise no move (image back to its original position)
                                        );
                                        
                const handleGesture = event([
                    {
                      nativeEvent: {
                        translationX: dragX,
                        translationY: dragY,
                        state,
                      },
                    }, 
                  ]);
                
                let aniStyle = {
                    transform:[
                        { translateX : transX },
                        { translateY : transY },
                        
                    ]
                };
                let scaleStyle = {
                    transform:[
                        { perspective: 500 },
                        {
                            scale :  scale
                        }
                    ]
                };
                return (
                    <>
            
                        <PanGestureHandler 
                            onGestureEvent={handleGesture} 
                            onHandlerStateChange={handleGesture}
                            minPointers={1}
                            maxPointers={1}>
                            <Animated.View style={[aniStyle ]}>
                            <GridImage
                                img_source={img_source}
                                width={width}
                                ht={ht}
                                index={index}
                            />
                            </Animated.View>
                        </PanGestureHandler>
                
                   
                    <ModalImage  
                        img_source={img_source}
                        modalWidth={modalWidth}
                        modalHt={modalHt}
                        index={index}
                />  //<<==show full image in modal
                    
                    </>
                    );
            };
            
        } else {
            return null;
        };
        
    };

**Comment by terrysahaidak** [comment]
You're doing exactly this (conditional render of the hooks) in the line where you have `case 1`: you're calling displayImg as a function. In order to fix this, you should use it as a component - `<DisplayImg />`

**Comment by emclab** [comment]
After converting `displayImg` to function component, useValue is working.

**Comment by emclab** [comment]
In app, there are `dragX, dragY, offsetX, offsetY, transX, transY, gesState, scale` defined for gesture handling. Currently `useValue` only applied to `dragX and dragY`. What are the other variables which needs to be `useValued` for preserving state after re-rendering?                                               

There is another use case which requires reset of all state and this is when uploading new images in `DisplayImages`  which triggers re-rendering. User shall be able to drag and sort again after new images are uploaded. The difference is that sorting only changes image order in data array and uploading increase the number of images in the data array.

**Comment by jakub-gonet** [comment]
By rule of thumb, you should reuse every Value with `useValue()` to prevent resetting state. Every other animated node should be reused as well, but that's more like perf optimization, it doesn't affect the correctness of the code.
