### ISSUE TITLE
TurboModuleRegistry NativeReanimated error

### ISSUE THREAD

**Issue by Eli-Nathan** [software-mansion/react-native-reanimated#1127]
## Description
Using this package along with [React Native Reanimated Bottom Sheet](https://github.com/osdnk/react-native-reanimated-bottom-sheet), I get this error on Android. (ios works great!)

Dismissing the error on my android emulator results in a blank white screen.

```
client_log | Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

[3] cllient_log | Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
```
<img width="569" alt="Screen Shot 2020-08-15 at 1 14 37 PM" src="https://user-images.githubusercontent.com/32842898/90312056-468ba000-def9-11ea-85e8-0a5160a5cca0.png">

## Steps To Reproduce

1. Install and link Reanimated v2
2. Install React native Bottom Sheet Lib (Uses reanimated v2)
3. Add any components that have a Reanimated v2 dependency

### Expected behavior
App is usable

### Actual behavior
App fails with the above error

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.5
- React Native Reanimated Bottom Sheet: ^1.0.0-alpha.22

**Comment by Eli-Nathan** [comment]
Completely removing the android device from my AVD manager and adding it again fixed the issue suggesting that it was something to do with my caching.

Closing now

**Comment by rpavlovs** [comment]
Same problem on iOS, removing android simulators from AVD didn't help

**Comment by jakub-gonet** [comment]
IIRC this should be resolved on newest alpha, have you tried updating?

**Comment by rpavlovs** [comment]
Yea, I've actually just installed alpha-8 following instructions and got this. I've only configured for iOS since that's the only platform I'll be building for - so no config other than Babel plugin

**Comment by wanderSX** [comment]
Getting the same when trying to enable remote debugger

**Comment by sanpoChew** [comment]
am also getting this with alpha-8 when trying to run on iOS

**Comment by harrysayers** [comment]
I too am getting this issue on IOS

**Comment by marionoratoRN** [comment]
Same here with alpha8 when trying to start the debugger

**Comment by mdcone** [comment]
I'm in the same boat.

**Comment by terrysahaidak** [comment]
All the people who report it could you please tell us the encampment you're using?

**Comment by mdcone** [comment]
XCode 12.1
React 16.13.1
React Native 0.63.3
React Native Reanimated 2.0.0-alpha.8
Node 12.18.2
npm 6.14.5
Pod RNReanimated 2.0.0-alpha.8

I can see ReanimatedModule in the NativeModules list, but not NativeReanimated (not sure if it's supposed to show up there at all). My Podfile.lock lists RNReanimated 2.0.0-alpha.8.

I also didn't follow the other version instructions dealing with TurboModules, and only have looked at the instructions for installing alpha 8. Perhaps there's something subtle I missed?

**Comment by terrysahaidak** [comment]
Did you upgrade or it's clean install of Reanimated?

**Comment by mdcone** [comment]
This was an upgrade from 1.4.0.

**Comment by mdcone** [comment]
I'm not familiar with the way TurboModules are supposed to get registered or appear to the RN runtime, so pardon my ignorance here, but I started stepping through RN's `TurboModuleRegistry` implementation and see that the `turboModuleProxy` constant (which is set by `global.__turboModuleProxy` is undefined. 

Again, I haven't done anything in my app to turn them on explicitly, so I'm not sure if this is `undefined` from something I did (or didn't do), or if it's supposed to be `undefined` if no TurboModules have been properly registered in the app. 

Thanks for any insights!

**Comment by terrysahaidak** [comment]
Did you enable TurboModules on Android as it explained in the installation guide?

**Comment by mdcone** [comment]
Sorry, to be clear, my problem is specifically iOS. I haven't attempted to build for Android yet. I realize this ticket was created originally in the Android context, but the rest of the comments were talking about iOS, so I joined in. Tomorrow I can try to get Android running and get back to you.

**Comment by MurphDirt879** [comment]
I am having the same issue with iOS. Andriod is working fine.

**Comment by mdcone** [comment]
More developments: I downloaded the playground application, fired it up, everything worked well. I turned on debugging and now I'm seeing the error. 

So, I turned debugging off on my app and we're back in business. This occurs in both iOS and Android for me. So it appears to be something with having the debugger enabled that is causing the issue. 

Digging in further, it looks like when we are in debug mode `global.__reanimatedModuleProxy` is undefined so then we go to ask for the module from the `TurboModuleRegistry.getEnforcing()` method, which bombs out in both scenarios. When not running in debug mode, `global.__reanimatedModuleProxy` is set.

I'm using the latest production version of Chrome - 86.0.4240.193

**Comment by mdcone** [comment]
I'm looking at the `UIResponder+Reanimated.mm` code and started stepping through. What's interesting to me is that when I am not attached to the debugger, the code runs. When I switch to attaching to the debugger, it doesn't run. Then when I switch back, it runs again.

**Comment by mdcone** [comment]
I've been digging into RN's `RCTCxxBridge` it look as if the code which would register the `__reanimatedModuleProxy` variable is wiped out if connect to the debugger. 

Line 336 of the bridge code checks to see if the `executorClass` is set, and if not, will call the code in `UIResponder+Reanimated.mm`. Otherwise, it hits the `else` branch which wipes out the `executorFactory` and constructs a new one generated with respect to the `executorClass`, thus removing the code which is executed during runtime initialization to register the `__reanimatedModuleProxy` global. This `executorClass` is only set if in a debug mode and is of type `RCTWebSocketExecutor`. 

Does that seem like a reasonable diagnosis? Thanks for the help!

**Comment by kotavy** [comment]
XCode 12.1
React 16.13.1
React Native 0.63.2
React Native Reanimated 2.0.0-alpha.8
Node 12.14.1
npm 6.14.7
Pod RNReanimated 2.0.0-alpha.8

After upgrading, the issue persists when trying to downgrade to reanimated 1.13.1

**Comment by mdcone** [comment]
@kotavy , did you run the bundler with `--reset-cache` after you downgraded? I had to so that in both an upgrade and downgrade scenarios.

**Comment by kotavy** [comment]
Thanks for the tip. I do have 1.13.1 working again after adding that to my all-in-one reset command:
`watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start --reset-cache`
Followed by running the sim again:
`yarn react-native run-ios --simulator 'iPad Air 2'`

I'll test upgrading in a similar way next.

**Comment by kotavy** [comment]
When loading with 2.0.0-alpha.8 I'm still running into `ExceptionsManager.js:179 Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.`

**Comment by mdcone** [comment]
That's the issue I'm running into as well. In my comments above, I detailed what I think is the reason, which is that the module registration mechanism the library is using in alpha.8 has a flaw in it. That flaw being, it doesn't work when the debugger is connected. I am unfamiliar with react-native's underlying native code registration mechanisms, especially with the new JSI system that Reanimated2 uses, but I stepped through the code yesterday and that was my conclusion. I'm just waiting on comments from the maintainers on if that's the case and if there is anything that can be done to patch it before a new version is release.

In the meantime, I have resorted to turning my debugging off and have resorted to print statements. Not optimal, and not a long term strategy, but it is allowing me to proceed.

**Comment by kotavy** [comment]
It seems like a solid lead, thank you for investigating. That's the issue that lead me here in the beginning. I'm trying alpha.6.1 now but if I'm stuck there I'll have to wait it out.

**Comment by jakub-gonet** [comment]
```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
```

This says that TurboModuleRegistry cannot find our turbo module. This can be coming from the wrong configuration of Reanimated or using a debugger. Debugging RN works by running JS in the browser (v8 engine) and making remote calls via bridge to the native side. Turbomodules work by sharing JS engine context on the native side, so when you run JS in the other engine it loses that context. Note that this is a limitation coming from RN and not Reanimated. [This comment](https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-663359904) may give some more insight into that.

If disabling debugger fixes your problem then it works like intended. If not, please create a repro repository to allow us to investigate this issue.

**Comment by mdcone** [comment]
Thanks @jakub-gonet! Do you think that there would be some value in allowing the debugger to be enabled, but if so, returning a mock of reanimated2? For those of us using reanimated2 is specific parts of our apps, doing do could enable us to debug non-reanimated dependent code.

**Comment by terrysahaidak** [comment]
I would rather suggest to just disable the code which uses Reanimated instead

**Comment by Benzer1406** [comment]
Have the same issue with:
Xcode: 12.0.1
RN: 0.63.3
react-native-reanimated: 2.0.0-alpha.8

**Comment by MattHorriganSunrise** [comment]
Its a requirement if your using react navigation:
https://reactnative.dev/docs/navigation

**Comment by matinzd** [comment]
I don't know why this issue is closed!

**Comment by Rizialdi** [comment]
I just had the same issue. Also wondering why this issue is closed.

**Comment by pkbiswal321** [comment]
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

    "react": "~16.13.1",
    "react-dom": "~16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-reanimated": "^2.0.0-alpha.9.2",

I just had the same issue

**Comment by surgeharb** [comment]
Please stick to this version `"react-native-reanimated": "2.0.0-alpha.6",`. I had the same issue, so make sure you have `2.0.0-alpha.6` and implemented the following instructions [https://docs.swmansion.com/react-native-reanimated/docs/2.0.0-alpha.7/installation/#ios](https://docs.swmansion.com/react-native-reanimated/docs/2.0.0-alpha.7/installation/#ios)

P.S.: Notice `#import <RNReanimated/REATurboModuleProvider.h>`, **REATurboModuleProvider** is renamed from **RETurboModuleProvider** (this module is used somewhere in the code it needs rename as well) and it seems that this file is not available in the newer version of reanimated.

**Comment by nomoreboredom** [comment]
Don't forget to run pod install

**Comment by aprilmintacpineda** [comment]
I get this when I `Shake Device -> Debug` the app.

**Comment by Ebeldev** [comment]
I do have the same problem. I had the "react-native-reanimated": "^2.0.0-alpha.9.2" version. I did reinstalled the version "react-native-reanimated": "^2.0.0-alpha.6". Flush the node_modules and the package-lock.json. Rebuild the app. And I still get the same error.

**Comment by yleclanche** [comment]
Same here. The issue arise when I'm in debug mode with expo.
If it passes in debug mode, the only way I can revert it is to reinstall the expo app, because the menu to disable the debug mode is not available when there is an error.

**Comment by 592da** [comment]
still happening, 
2.0.0-rc.1, xcode 12.3

**Comment by huy-lv** [comment]
@yleclanche you are right, if anyone got this problem, try to re install app and do not turn debug on :))

**Comment by dandre-hound** [comment]
I'm confused about the status of debugging with react-native-reanimated. In the alpha versions, we couldn't debug because turbo modules were enabled. Now in the release candidates the debug menu is enabled, but it kills react native as described above. Should the debug menu still be disabled? I would really like to use chrome debugging for why-did-you-render, but I'm unable to because of the reanimated integration.

**Comment by bneigher** [comment]
This is blocking me from moving to react native 0.64.0 as Hermes is getting first-class treatment

**Comment by cyberdude** [comment]
I'm having this problem.  It's unfortunate.

2.0.0-rc.2, xcode 12.3, RN-0.63.4

**Comment by ionflow** [comment]
Same issue here:

TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

xcode: 12.1
DevTools 4.10.1-3a8c04e3b2

  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.3",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-reanimated": "2.0.0-rc.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-preset-expo": "8.3.0"
  },

**Comment by keyboardshotgun** [comment]
Check Hermes engine is enabled and add some codes for RNA v2.
https://docs.swmansion.com/react-native-reanimated/docs/installation/

**Comment by canberkardic** [comment]
Same problem here when using debugging.

TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
 
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-reanimated": "^2.0.0-alpha.9.2",
Xcode 12.2

Hermes is enabled.
Turbo modules was set as described in the documentation.

**Comment by L-A** [comment]
I hope this is helpful and I'm not stating the obvious to everyone here:

The current (`rc.2`) docs [specify that RN's remote debugging will not work alongside JSI](https://docs.swmansion.com/react-native-reanimated/docs/about#known-problems-and-limitations).

For people looking to keep using Reanimated V2 _and_ continue logging to a console, the current solution is to use Flipper to connect to the device instead of enabling the in-browser remote debugger. It's already part of `react-native` on the device, so all you're missing is to run the desktop application to receive the app's logs:

https://fbflipper.com/

**Comment by Yandamuri** [comment]
@L-A I am getting this error even though I didn't enable the debug mode. I am using `"react-native-reanimated": "2.0.0-rc.3"` Can you please help me on this?

**Comment by Skr1pt1k** [comment]
I have this error on my m1 macbook pro...

**Comment by kg-currenxie** [comment]
Same in debug mode only..

**Comment by itzmestar** [comment]
i had the same error.

Solution: uninstalled current version for: @react-navigation/drawer @react-navigation/native @react-navigation/stack

then installed:
"@react-navigation/drawer": "^5.12.3",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",

this fixed the error

**Comment by JeffPatricio** [comment]
Hello, I was able to solve it by following the installation steps:

https://docs.swmansion.com/react-native-reanimated/docs/installation/

The problem is that I went to the automatic as usual to use react navigation and I had not performed these steps.

**Comment by hungnq139** [comment]
@Skr1pt1k  use newest flipper : Podfile : use_flipper!({ 'Flipper' => '0.79.1' })

**Comment by ithustle** [comment]
+1
Version: `2.0.0`

**Comment by TrebuhD** [comment]
Updating the flipper plugin like @hungnq139 suggested seems to have fixed this for me.

**Comment by aditigupta7** [comment]
install react-native-reanimated library step by step from 
https://docs.swmansion.com/react-native-reanimated/docs/installation/

I have resolved this problem through this.

**Comment by aditigupta7** [comment]
If you downgraded your library then it might give you other errors and issues so it will be better to install react-native-reanimated library through steps given in https://docs.swmansion.com/react-native-reanimated/docs/installation/
I read all the instructions and followed it.
Hope it will help you all too.

**Comment by aditigupta7** [comment]
Install react-native-reanimated by following steps in https://docs.swmansion.com/react-native-reanimated/docs/installation/

I resolved my problem through this.

**Comment by RaghavShubham** [comment]
I'm getting the same error in expo

**Comment by saurabh874** [comment]
I'm getting the same error.

**Comment by zhigang1992** [comment]
If it's happening for you on iOS, and you have a special RN setup (maybe with existing swift / objc projects)

Make sure your RNBridge's delegate is a UIResponser and not just a NSObject.

If look for `DONT_AUTOINSTALL_REANIMATED` flag, you'd find that it's extending only UIResponder, which would be fine  in most cases since by default RN uses AppDelegate for Bridge delegate.

But you are like us and put the react native code in its own NSObject class, this might be something to watch out for.

**Comment by p2mittal-dev** [comment]
**Error - TurboModuleRegistry.getEnforcing(...): 'NativeReanimated'**
Hello,
I got this[TurboModuleRegistry.getEnforcing(...): 'NativeReanimated'] error and i found the solution 
Step 1 - Download react native project from github  "https://github.com/software-mansion-labs/reanimated-2-playground".
Step 2- Then run command 
=> npm install
=> react-native start
=> react-native run-android
and build app 
Step 3- when its work move your required project files and install your required npm pakages.
Step 4 - Then run commands
=> npm cache clean --force
=> cd android
=> gradlew clean
=> gradle cleanBuildCache
=> gradlew build --refresh-dependencies
=> cd..
=> npx react-native start --reset-cache
=> npx react-native run-android
its work for me try once.

**Comment by Alecefe** [comment]
Solved downgrading react-native-reanimated to v1.13.2. The v2 of the package evenly crashes the app.

**Comment by TrisKnightGamer** [comment]
Package error ? i got same problem, hope it will be fixed soon

**Comment by TrisKnightGamer** [comment]
> Solved downgrading react-native-reanimated to v1.13.2. The v2 of the package evenly crashes the app.

I downgrade and meet another error : Unable to resolve module "react-native-reanimated/plugin"

**Comment by iamamanprajapati** [comment]
@trisknightgamer
It is not a permanent solution bro

**Comment by TrisKnightGamer** [comment]
> @TrisKnightGamer
> It is not a permanent solution bro

Package problem right ? I need a real reason to tell my client

**Comment by TrisKnightGamer** [comment]
> Solved downgrading react-native-reanimated to v1.13.2. The v2 of the package evenly crashes the app.

This solution help me, thank you.

**Comment by thabata-marchi** [comment]
Is there any previous version that we can use until we resolve this error?
Last year in the alpha version did not give this error.

**Comment by TrisKnightGamer** [comment]
@thabata-marchi use v1.13.2, i get no error with this version.

**Comment by thabata-marchi** [comment]
I need this animation to work: https://www.youtube.com/watch?v=6uixYHh7XEc
In Reanimated 1 you can't do this animation, In Reanimated 1 you can't do this animation, because it works in UI thread only.

**Comment by Honeyzed** [comment]
go  
to   this Path android/app/build.gradle
fix the : project.ext.react = [
  enableHermes: true  // <- here | clean and rebuild if changing
]
MainApplication.java

fix the :   import com.facebook.react.bridge.JSIModulePackage; // <- add
  import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add

  @Override
      protected JSIModulePackage getJSIModulePackage() {
        return new ReanimatedJSIModulePackage(); // <- add
      }

Add Reanimated's babel plugin to your babel.config.js:

fix :  plugins: [
          ...
          'react-native-reanimated/plugin',
      ],

**Comment by SarvaDev-123** [comment]
> Error Solved
> 
> Step 1 - Download react native project from github "https://github.com/software-mansion-labs/reanimated-2-playground".
> Step 2-
> npm install
> react-native start
> react-native run-android
> and build app
> Step 3- when its work move your required project files and install your required npm pakages.
> Step 4 -
> npm cache clean --force
> cd android
> gradlew clean
> gradle cleanBuildCache
> gradlew build --refresh-dependencies
> cd..
> npx react-native start --reset-cache
> npx react-native run-android
> its work for me try once.

@p2mittal-dev  It resolved when you cloning the reanimated-2-playground project. But I want how to install it another project without cloning .?

**Comment by TrisKnightGamer** [comment]
> go
> to this Path android/app/build.gradle
> fix the : project.ext.react = [
> enableHermes: true // <- here | clean and rebuild if changing
> ]
> MainApplication.java
> 
> fix the : import com.facebook.react.bridge.JSIModulePackage; // <- add
> import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add
> 
> @override
> protected JSIModulePackage getJSIModulePackage() {
> return new ReanimatedJSIModulePackage(); // <- add
> }
> 
> Add Reanimated's babel plugin to your babel.config.js:
> 
> fix : plugins: [
> ...
> 'react-native-reanimated/plugin',
> ],
> this step used .......solve the this problem TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found.
> thanku

it don't fix the error, i downgraded to 1.13.2 and it works

**Comment by TrisKnightGamer** [comment]
@SarvaDev-123 try downgraded to 1.13.2

**Comment by SarvaDev-123** [comment]
How to downgraded to 1.13.2  could you provide any command and animation works on (react-native-collapsible-tab-view) I am using this liberary

**Comment by TrisKnightGamer** [comment]
@SarvaDev-123 delete node_modules and package_lock.json then open terminal, enter this npm i react-native-reanimated@1.13.2

**Comment by SarvaDev-123** [comment]
@TrisKnightGamer when i add   plugins: [
      ...'react-native-reanimated/plugin',
    ], then run node modules  then it through error like this  "index.js: Cannot find module 'babel-plugin-r' "

**Comment by TrisKnightGamer** [comment]
> @TrisKnightGamer when i add plugins: [
> ...'react-native-reanimated/plugin',
> ], then run node modules then it through error like this "index.js: Cannot find module 'babel-plugin-r' "

@SarvaDev-123 you don't need to add this, just need downgrade to 1.13.2

**Comment by Dakuan** [comment]
this has cropped up again having previously been solved, even with instruction steps followed, broken on ioS simulators

**Comment by TrisKnightGamer** [comment]
@Dakuan you have tried to install react-native-reanimated with version 1.13.2, correct ?

**Comment by piaskowyk** [comment]
We got rid of `TurboModuleRegistry.getEnforcing()` in version `2.0.1`, so I think that upgrade could help. Let me know if it works.

**Comment by siddharthJadhav** [comment]
I am also having the same issue. Did anyone found the solution?

**Comment by waheedakhtar694** [comment]
I am getting this issue on ios with `react-native-reanimated  v2.10`

**Comment by skeie** [comment]
Updating to 2.2.0 worked for me

**Comment by hieunguyen-groove** [comment]
Upgrading to v2.0.1 worked for me.

**Comment by enlightenedpie** [comment]
> ```
> Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
> ```
> 
> This says that TurboModuleRegistry cannot find our turbo module. This can be coming from the wrong configuration of Reanimated or using a debugger. Debugging RN works by running JS in the browser (v8 engine) and making remote calls via bridge to the native side. Turbomodules work by sharing JS engine context on the native side, so when you run JS in the other engine it loses that context. Note that this is a limitation coming from RN and not Reanimated. [This comment](https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-663359904) may give some more insight into that.
> 
> If disabling debugger fixes your problem then it works like intended. If not, please create a repro repository to allow us to investigate this issue.

This was the fix for me. Running the debugger (from the RN debug menu) was breaking my app. I turned off the debugger and now the app builds perfectly.

**Comment by datvp09** [comment]
For me I did exactly these steps to make it run again:

1. `npm i react-native-reanimated`
2. `npx pod-install`
3. on developer menu, press `Debug with Chrome`
4. press `Turn off debugging`
5. delete app
6. Build again using Xcode or `react-native run-ios`

Look like the reason is Reanimated doesn't work with debugger, it only works with Flipper for now
