### ISSUE TITLE
Style doesn't work for Reanimated View when in a 2nd level nesting 

### ISSUE THREAD

**Issue by ethanshar** [software-mansion/react-native-reanimated#1129]
## Description

Passing nested style in an array doesn't work. When it's a 2 level nesting

## Steps To Reproduce

See code snippet.

### Expected behavior
Nesting a style (animated style for that matter) should work when nested in a 2nd level array.

### Actual behavior
Style doesn't take any effect and being ignored. 

## Snack or minimal code example

```
const animatedStyle = ...;

// Doesn't Work (2 level nesting)
<Reanimated.View style={[{backgroundColor: 'red'},[animatedStyle]]} />

// Works (1 level nesting)
<Reanimated.View style={[{backgroundColor: 'red'}, animatedStyle]} />
```

## Package versions
react-native-reanimated@2.0.0-alpha.5
react-native@0.62.2
react@16.11.0

**Comment by terrysahaidak** [comment]
Hi. This isn't Reanimated problem. AFAIK this should not work in React Native. Use Array.flatten for this.

**Comment by ethanshar** [comment]
Hi @terrysahaidak 
It does work with React Native View. 
for instance, the following examples works as expected
```
<View style={[{width: 100, height: 100}, [[[{borderWidth: 2}]]]]}/>
```

**Comment by terrysahaidak** [comment]
Does it work with Animated.View as well? Reanimated's createAnimatedComponent should work similar to Animated's one.

**Comment by ethanshar** [comment]
Ok, after some digging I realized it's not related to the View. 
Reanimated View can handle plain style nesting as long it is not a style created with the `useAnimatedStyle` hook. 
So, basically the problem is with the return value of `useAnimatedStyle`. 
Not sure if this can be fixed, I assume there's a reason why this hook returns something "different".

**Comment by ethanshar** [comment]
Hi @karol-bisztyga @jakub-gonet 
It appears this issue has returned in version 2.0.0.

**Comment by ethanshar** [comment]
Hi, 
Is there any update on this issue?

**Comment by ethanshar** [comment]
Hi @piaskowyk @jakub-gonet, 
How are you? 

Can you share an update on this issue?

We love reanimated and waited long time for v2 to be official. 
We're benn already using v1 in our [components library](https://github.com/wix/react-native-ui-lib).
But we'd like to start migrating to v2 and since we're building generic components where users can pass their own style and customize them, nesting styles is a must for us, without it, it'll be really difficult to create a components infrastructure on our end.

Anyway, thanks for all the amazing work!

**Comment by ethanshar** [comment]
Hi, 
Any update on this one?

**Comment by robertwt7** [comment]
hello peeps, i think this is related to #2768 , i'm still experiencing this issue in nested `Animated.View` within `Animated.ScrollView`
