### ISSUE TITLE
Capturing Animated (default export from react-native-reanimated) in worklet causes error loop

### ISSUE THREAD

**Issue by kmagiera** [software-mansion/react-native-reanimated#1132]
## Description

When Animated object (and perhaps this may work for other complex objects too) is captured in a worklet, this results in some unexpected error/crash behavior

## Steps To Reproduce

Render the app with one of the worklets capturing Animated object (see examples posted below).

### Expected behavior

Properties under Animated access from within a worklet (e.g. Animated.Extrapolate.CLAMP) should return their actual values.

### Actual behavior

The app goes into an error loop with the following stacktrace being thrown every second or so:
```
This error is located at:
    in FlatListStuff
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Mon Aug 17 2020 10:30:17.100]  ERROR    Error: Exception in HostFunction: <unknown>
```

## Snack or minimal code example

```js
import Animated, { useAnimatedStyle } from 'react-native-reanimated';

function Something() {
  const something = useAnimatedStyle(() => {
    return { backgroundColor: Animated.Extrapolate.CLAMP };
  });
  return <Animated.View style={something}/>
}
```

Full example as prepared by @ryanbaldwin: https://gist.githubusercontent.com/ryanbaldwin/68a5fa2c35dbfadf3d3a3bab2e96590d/raw/c2c81c1c0b4fedd6b3e6e251ecf8c39bff210c42/App.js

**Comment by luixo** [comment]
Hello,

I recently added `react-native-reanimated` (via `nativewind`) and stumbled upon exact same error whenever I used `Animated.View`.
Going back from `3.7.x` to `3.6.x` helped and I took some time to bisect the exact build, [3.7.0-nightly-20231221-ea5c667ce](https://www.npmjs.com/package/react-native-reanimated/v/3.7.0-nightly-20231221-ea5c667ce) is the first one to introduce the problem.
It basically narrows down the issue to this commit: https://github.com/software-mansion/react-native-reanimated/commit/5d1c25401268e114923effde5b1583557896a71c

Let me know if I can help you reproduce the issue.

My lib versions:
```ts
{
"react-native": "0.73.5",
"expo": "^50.0.7",
}
```
