### ISSUE TITLE
Coexistence of Reanimated version 1 and version 2

### ISSUE THREAD

**Issue by naishe** [software-mansion/react-native-reanimated#1134]
We have an existing app that uses [React Navigation](https://reactnavigation.org/docs/getting-started), which ties us down to version 1.x of Reanimated library. However, for the animations in our components, we want to use Reanimated v2. I know we can alias and install two different versions of the same package. And, the fact that both, version 1 and version 2, require editing Java and Objective C codes.

Since, we do not have a dedicated test team (It's a 3 people start-up), do you guys think these versions can coexist without any issue? Have anyone tried Reanimated along side of React Navigation?

Of course, we love react-native-gesture-handler too!

- "react": "16.13.1",
- "react-native": "0.63.2",
- "react-native-gesture-handler": "^1.7.0",
- "react-native-reanimated": "^1.13.0",

**Comment by jakub-gonet** [comment]
Reanimated 2 is _almost_ fully compatible with Reanimated 1 - you can mix and match those as long as you keep them in separate components (they may work in the same component but I haven't tested that though). Installing v2 keeps v1, so you can use both from the same version. 

[Here's a migration guide](https://docs.swmansion.com/react-native-reanimated/docs/next/migration) from our docs, if react-navigation still uses v1 you would have to prepare [patch-package](https://www.npmjs.com/package/patch-package) aliasing imports in there and after that everything should work like a charm.

If you have any further questions don't hesitate to reply.
