### ISSUE TITLE
Controlled AnimatedTextInput Problem

### ISSUE THREAD

**Issue by leonyjiang** [software-mansion/react-native-reanimated#1140]
## Description

I created an animated TextInput component using Animated's `createAnimatedComponent` and React Native's `TextInput` in an attempt to animate the color of the input's text color on focus and blur. This works in an uncontrolled setting, but fails when the value is controlled (see below). When the value is controlled, the TextInput loses focus on each character typed.

### Screenshots
| When the input is controlled by a state variable (undesired behavior) | When the input is uncontrolled (desired behavior, but with controlled input) |
| --- | --- |
| ![bad](https://user-images.githubusercontent.com/35908040/90560687-57841d80-e154-11ea-9aca-4d3a28fe63a5.gif) | ![good](https://user-images.githubusercontent.com/35908040/90560700-5ce16800-e154-11ea-89fd-bdd219cfe97b.gif) |

## Steps To Reproduce

Create an animated TextInput component, set its `color` property to some Animated Value. Upon focus and blur, initiate an animation for this Value. You will see that there is odd behavior when the input is controlled (uses `value` prop).

### Expected behavior
The focus and keyboard should behave normally when using a controlled TextInput.

### Actual behavior
The keyboard is dismissed every time the `value` state variable is updated.

## Snack or minimal code example

[Expo Snack available here](https://snack.expo.io/@leonyjiang/animatedtextinput-issue).

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: ^1.9.0

**Comment by jakub-gonet** [comment]
Move `const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);` out of component that you're rendering.

Every call to `onChangeText` rerenders your component and calls `createAnimatedComponent` which creates & destroys (after first rerender) a bunch of nodes on the native side. `createAnimatedComponent` should be always evaluated only once.

On the side note, you should move your `Animated.Value` to the component and use `useValue` hook to prevent it from recreating.

```js
export default function App() {
	const translateX = Animated.useValue(0);
	// (...)
}
```

If you have any further questions feel free to ask.
