### ISSUE TITLE
After installing reanimated 2 alpha.5 useAnimatedRef hook isn't a function

### ISSUE THREAD

**Issue by youssef212** [software-mansion/react-native-reanimated#1143]
## Description

After installing reanimated 2 alpha.5 useAnimatedRef couldn't be found (not a function, undefined etc..)

### Screenshots

![Screenshot_1597924249](https://user-images.githubusercontent.com/63873762/90766642-2c343680-e2ec-11ea-99a2-370b7cacdc1f.png)

## Steps To Reproduce

1.create a new react native project with typescript boilerplate
2. npm i react-native-reanimated@2.0.0-alpha.5
3. use useAnimatedRef from react-native-reanimated
4. run through run android

### Expected behavior

useAnimatedRef hook to be a function not undefined

### Actual behavior

useAnimatedRef hook  is undefined

## Snack or minimal code example

const aRef = useAnimatedRef();//use it in any funcitional component

## Package versions

react-native-reanimated@2.0.0-alpha.5

- React:
- React Native:
- React Native Reanimated:

**Comment by yolpsoftware** [comment]
`useAnimatedRef` works fine for me with alpha 5. For example, the minimal code example of #1108 uses `useAnimatedRef` and it works fine.

**Comment by jakub-gonet** [comment]
Do you install Reanimated using `npm install` by any chance?

**Comment by youssef212** [comment]
yes i am look step number 2

**Comment by jakub-gonet** [comment]
Oh, didn't notice, sorry.

We are aware of this issue, you can use yarn as a workaround for now.

**Comment by youssef212** [comment]
should i close the issue for now?

**Comment by jakub-gonet** [comment]
Yeah, I'll create a new issue linking it.
