### ISSUE TITLE
Installing Reanimated via npm fails in runtime

### ISSUE THREAD

**Issue by jakub-gonet** [software-mansion/react-native-reanimated#1145]
## Description

After installing Reanimated2 via `npm install react-native-reanimated@alpha` and running the app, app crashes with message similar to following:
```js
TypeError: (0, _core.withNavigation) is not a function. (In '(0, 
_core.withNavigation)(LinkWithNavigation)', '(0, _core.withNavigation)' is undefined)
```

[According to @terrysahaidak](https://github.com/software-mansion/react-native-reanimated/issues/1049#issuecomment-674741996) this is related to the missing package-lock.json

Linked issues:
- #1049
- #1143
- #867

## Known workarounds

Using yarn instead of npm 🙂 

## Package versions

- React Native Reanimated: v2 alpha

**Comment by terrysahaidak** [comment]
that's more a problem with example project. I use npm in my own project and it works :)

**Comment by Svarto** [comment]
I have similar errors

**Comment by terrysahaidak** [comment]
> I have similar errors

do you have these in Example project? For now the only workaround is to use yarn. Make sure yarn.lock is present.
