### ISSUE TITLE
Animated.ScrollView keyboardShouldPersistTaps with Animated.Node<boolean> doesn't work.

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-reanimated#1147]
## Description

when providing an `Animated.Node` for `keyboardShouldPersistTaps` for a ScrollView doesn't work. 
it'll always be 'never'. 

for example 

```
<ScrollView 
	scrollEnabled={cond(x, false, false)}
    keyboardShouldPersistTaps={cond(x, 'always', 'always' )}
...>
....

```

the scroll will be disabled but `keyboardShouldPersistTaps` has no effect.

https://snack.expo.io/@aeid/jealous-cheese

expected behavior: 
```
<ScrollView 
    keyboardShouldPersistTaps={A.Node<'Always'>}.. 
```
should behave the same as 

```
<ScrollView 
      keyboardShouldPersistTaps={'Always'}.. 
```

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: ^1.13.0

**Comment by a-eid** [comment]
@jakub-gonet hey, is there an update on this ? thanks

**Comment by jakub-gonet** [comment]
Haven't had time to take a look at it, but I've got this issue on my todo list, so I'll get to it eventually.

**Comment by a-eid** [comment]
thank you @jakub-gonet

**Comment by jakub-gonet** [comment]
I'm recently more focused on the TS rewrite of RNGH and I didn't have time to check this.

Maybe @zrebcu411 or @piaskowyk have some time to check it?

**Comment by a-eid** [comment]
@jakub-gonet @zrebcu411 @piaskowyk any updates on this.

**Comment by kmagiera** [comment]
Closing this in favor of #1526 where the issue related to `keyboardShouldPersistTaps` is discussed as well
