### ISSUE TITLE
Animation API: rename current to position

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1151]
This is nitpicking but it would be nice to rename current to position so we can use the position, velocity, acceleration terminology.

**Comment by wcandillon** [comment]
I have a similar comment about the naming of the function. I assumed that the with prefix implies composability and something that returns an animation. So shouldn't it be `withDelay(withRepeat(withTiming())`?

I'm currently building a couple of custom animations and I'm thinking of all prefixing them with `with`

**Comment by wcandillon** [comment]
unless current can be a non-numerical value?

**Comment by karol-bisztyga** [comment]
I would say renaming `current` to `position` is not necessary, for me it looks like a matter of personal preferences.

As for the `with` prefix, we are planning to do that, still it is rather low prio.

**Comment by wcandillon** [comment]
@karol-bisztyga I agree.
