### ISSUE TITLE
Web support for v2

### ISSUE THREAD

**Issue by kmagiera** [software-mansion/react-native-reanimated#1152]

**Comment by hosseinmd** [comment]
@terrysahaidak

**Comment by karol-bisztyga** [comment]
https://github.com/software-mansion/react-native-reanimated/tree/web-support

**Comment by hosseinmd** [comment]
Can we test this?

**Comment by karol-bisztyga** [comment]
Yes but it does contain bugs

**Comment by terrysahaidak** [comment]
Some features such as gesture handler support is missing right now

**Comment by karol-bisztyga** [comment]
Web support has been added, closing.
