### ISSUE TITLE
Repeat doesn't behave like withTiming

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1154]
The following example works: 

```
const progress = useDerivedValue(() => withTiming(1));
```

The following crashes: 

```
const progress = useDerivedValue(() => repeat(withTiming(1), -1, true));
```

I'm trying to achieve maximum composability between between animations and would like to write the following:

```
const paused = useSharedValue(false);
const progress = useDerivedValue(() => withPause(repeat(withTiming(1), -1, true)), paused);
```

**Comment by wcandillon** [comment]
I also have a concern about the boilerplate required to build custom animations. While I was able to build a custom animation outside reanimated 2, animations defined in animation.js seem to use boilerplate that might be useful to other animations (namely defineAnimation())

**Comment by karol-bisztyga** [comment]
@wcandillon does this problem still occur? I just tried it out and it worked just fine, can you confirm?

**Comment by wcandillon** [comment]
Thanks for following up on this, closing it.

**Comment by wcandillon** [comment]
I can confirm that the behaviour still happens:

```ts
  const progress = useSharedValue(0);
  useLayoutEffect(() => {
    progress.value = repeat(withTiming(1, {duration: 400}), -1, true);
  }, [progress.value]);
```

**Comment by wcandillon** [comment]
Closing again, looks this has been fixed.
