### ISSUE TITLE
How to use setState in worklet

### ISSUE THREAD

**Issue by mohammadanaraki** [software-mansion/react-native-reanimated#1155]
## Description

how to change state or same in reanimated v2 events 

## Code
````js
  const x = useSharedValue(0);
  const [state , setState] = React.useState(false);
  const gestureHandler = useAnimatedGestureHandler({
    onStart: (_, ctx) => {
      ctx.startX = x.value;
    },
    onActive: (event, ctx) => {
      x.value = ctx.startX + event.translationX;
    },
    onEnd: _ => {
      x.value = withSpring(0);
      setState(true); // <- how to use this here 
    },
  });
````
### Package versions

- React:
- React Native:
- React Native Reanimated: 2.0.0-alpha.5

**Comment by terrysahaidak** [comment]
Could you post more code? The code you provided works as expected on alpha.5.

**Comment by karol-bisztyga** [comment]
No @terrysahaidak it does not work properly, it does not read a proper value of a state on UI thread. Try with the following code and you'll see: `setState(!state); // <- how to use this here`

**Comment by terrysahaidak** [comment]
Yeah @karol-bisztyga, as well as `setState(v => !v)` I couldn't get to work. But I mean the provided code still works as expected :)

**Comment by mohammadanaraki** [comment]
> Yeah @karol-bisztyga, as well as `setState(v => !v)` I couldn't get to work. But I mean the provided code still works as expected :)

Yes ! :) 
i just made an example 
i meant can't access xD

**Comment by karol-bisztyga** [comment]
fixed in https://github.com/software-mansion/react-native-reanimated/pull/1165

**Comment by karol-bisztyga** [comment]
Fixed in https://github.com/software-mansion/react-native-reanimated/pull/1165
Now this code works as expected
```
import React from 'react';
import { TapGestureHandler } from 'react-native-gesture-handler';
import { View } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedGestureHandler,
  withSpring,
} from 'react-native-reanimated';

export default function App() {
  const x = useSharedValue(0);
  const [state, setState] = React.useState(false);

  console.log('rerender ' + state);

  const handler = useAnimatedGestureHandler({
    onStart: (_, ctx) => {
      ctx.startX = x.value;
    },
    onActive: (event, ctx) => {
      x.value = ctx.startX + event.translationX;
    },
    onEnd: (_) => {
      x.value = withSpring(0);
      setState(!state); // <- how to use this here
    },
  });

  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      <TapGestureHandler onGestureEvent={handler}>
        <Animated.View
          style={{ height: 100, width: 100, backgroundColor: 'red' }}
        />
      </TapGestureHandler>
    </View>
  );
}

```

**Comment by CDBridger** [comment]
I'm getting an Error "Tried to synchronously call function {bound dispatchAction} from a different thread." 
When I use setCurrentIndex(x => x + 1) within the onEnd callback

iOS
 RN: 0.63.4, 
 react-native-gesture-handler: 1.9.0, 
 react-native-reanimated: 2.0.0-alpha.9.2

**Comment by karol-bisztyga** [comment]
@CDBridger hey 👋 I think you missed the full error message there. There should be more:
```
Solution is:
a) If you want to synchronously execute this method, mark it as a Worklet
b) If you want to execute this method on the JS thread, wrap it using runOnJS
```
https://docs.swmansion.com/react-native-reanimated/docs/api/runOnJS

**Comment by erquhart** [comment]
I know this is old, but it's ranking up top in search so folks are probably still reading it. The last snippet doesn't work as expected - what @karol-bisztyga is pointing at in his last message is the need to wrap js thread functions in `runOnJS()`.

The previous comment docs link is now outdated, ~~here's the current one: https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS~~

**Update:** that one is now outdated too, this one is probably closest now: https://docs.swmansion.com/react-native-reanimated/docs/guides/worklets/#running-functions-from-worklets

To run a JS thread function from a worklet:
1. define the function outside of the worklet
2. pass the function as an argument to `runOnJS()` inside the worklet
3. `runOnJS()` will return a function that can be called inside the worklet
4. you can think of this new function as the same function, except "workletified" - call it like you would the original function
5. the function is typically created and executed in one statement, eg., `runOnJS(setState)(true)`

This works as expected (adds `runOnJS` import and uses it to wrap the `setState` call):

```ts
import React from 'react';
import { TapGestureHandler } from 'react-native-gesture-handler';
import { View } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedGestureHandler,
  withSpring,
  runOnJS,
} from 'react-native-reanimated';

export default function App() {
  const x = useSharedValue(0);
  const [state, setState] = React.useState(false);

  console.log('rerender ' + state);

  const handler = useAnimatedGestureHandler({
    onStart: (_, ctx) => {
      ctx.startX = x.value;
    },
    onActive: (event, ctx) => {
      x.value = ctx.startX + event.translationX;
    },
    onEnd: (_) => {
      x.value = withSpring(0);
      runOnJS(setState)(!state); // <- how to use this here
    },
  });

  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      <TapGestureHandler onGestureEvent={handler}>
        <Animated.View
          style={{ height: 100, width: 100, backgroundColor: 'red' }}
        />
      </TapGestureHandler>
    </View>
  );
}
```
