### ISSUE TITLE
Problems with loading app with Reanimated 2 [iOS]

### ISSUE THREAD

**Issue by jpudysz** [software-mansion/react-native-reanimated#1156]
## Description

Hello, thanks for the great update and your work to give us a stable version of reanimated 2. I checked previous issues and I didn't find anything similar.

The problem is pretty simple to explain. With `react-native-reanimated` I need to refresh app 3-6 times (sometimes even more) to make it load. Otherwise, I can see a white screen (screenshot below) without any error inside console/ Xcode. 
I was able to run the app only once on the physical device and I tried to refresh the app like 50 times.

To make it clear - reanimated is working correctly and I'm able to run example code without any issues/errors. I cannot hot reload the app nor make it work after the first refresh.

Do you have same problems or I'm missing some kind of additional step of the configuration?
I would really appreciate your hints.

### Screenshots

![screen](https://user-images.githubusercontent.com/9088288/91153086-0b8b2880-e6c0-11ea-9d94-ab6625f8e8de.png)

## Steps To Reproduce

1. Run the app with reanimated 2

### Expected behaviour
Hot reload/hard reload will work out of the box

### Actual behavior
Most of the time I can see a white screen without errors. I need to hard refresh the app multiple times

## Snack or minimal code example

I encountered it even without any reference to `react-native-reanimated` inside JavaScript. Just after enabling TurboModules

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.5 / tried also with master branch

**Comment by terrysahaidak** [comment]
Hi. Is there any logs in console?

**Comment by jpudysz** [comment]
No, console is clean.
I ran reanimated 2 playground repo and it was working without problems.
I installed reanimated 2 inside medium sized project - so something is interfering with current react native ecosystem. I will try to dig deeper and hopefully I will resolve it.

**Comment by terrysahaidak** [comment]
I had some problems with react-native-video component recently.

Also, keep in mind that as a part of reanimated installation you enable turbo modules and not all the libraries work well just yet.

**Comment by Szymon20000** [comment]
@jpudysz  I didn't observe any problems with the full reload on the master branch. Closing this for now. 
However, if you find out which library doesn't work well with Reanimated 2 please let us know.

**Comment by jpudysz** [comment]
It's because of `@react-navigation/stack`. Commenting out routing fixes problem immediately.

**Comment by Szymon20000** [comment]
@jpudysz So It's not a Reanimated problem?

**Comment by terrysahaidak** [comment]
Does RN uses TurboModules for everything else as well when we enable them @Szymon20000? If so I think something doesn't work properly with it.

**Comment by jpudysz** [comment]
I check my project's dependencies and the only lib which uses `react-native-reanimated` is `react-native-safe-area-context`
![Screenshot at Aug 26 11-04-03](https://user-images.githubusercontent.com/9088288/91291384-43b06b00-e795-11ea-85a1-96df25d0d6ff.jpg)

and it's used by `@react-navigation/stack`

![2](https://user-images.githubusercontent.com/9088288/91291387-46ab5b80-e795-11ea-986e-2ed4e83565d0.jpg)

I checked code of both libraries and migration section from your documentation and I didn't find anything which may interfere.. but still, something breaks it.

**Comment by jpudysz** [comment]
Here you can check how it looks like:

![Screen Recording 2020-08-26 at 12 15 13](https://user-images.githubusercontent.com/9088288/91291915-10221080-e796-11ea-8a65-4f7f16a7a439.gif)

**Comment by Szymon20000** [comment]
> Does RN use TurboModules for everything else as well when we enable them @Szymon20000? If so I think something doesn't work properly with it.

Yes, we turn on TurboModules globally.

**Comment by jpudysz** [comment]
I found the code responsible for the issue:
```diff
 <NavigationContainer
            ref={navigationRef}
-            // linking={{
-            //     prefixes: ['myAppPrefix://'],
-            //     config: {
-            //         screens: {
-            //             [ScreenNames.AuthSwitch]: 'auth/:message'
-            //         }
-            //     }
-            // }}
```

**Comment by guistrutzki** [comment]
I had this same issue and my NavigationContainer didn't have any props like linking. I fixed it stopping debug.
