### ISSUE TITLE
 Error: Unable to resolve module `./animations/TimingAnimation` from `node_modules\react-native-reanimated\src\Animated.js`

### ISSUE THREAD

**Issue by Hook-Da** [software-mansion/react-native-reanimated#1168]
## Description

Hello. I started new project recently and tried to install react native reanimated. After running app such error occured
![reanimated](https://user-images.githubusercontent.com/41588867/91645097-58ba2200-ea53-11ea-897d-736f9dff4532.PNG)

Packages version that a currently installed
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-reanimated": "^1.13.0",

- React:
- React Native:
- React Native Reanimated:

**Comment by jakub-gonet** [comment]
Duplicate of #1007.

This is related to stale caches, we removed those files in 1.13 and metro or watchman tries to read them.

Use --reset-cache flag when launching metro server and clear watchman caches.

**Comment by Hook-Da** [comment]
Thanks a lot!
