### ISSUE TITLE
Build failed 'A problem occurred configuring project ':react-native-reanimated'. in React native project

### ISSUE THREAD

**Issue by SanjanaTailor** [software-mansion/react-native-reanimated#1171]
https://stackoverflow.com/questions/63676080/build-failed-a-problem-occurred-configuring-project-react-native-reanimated
Facing this issue
- React:  "react": "16.8.6",
- React Native:   "react-native": "0.60.0",
- React Native Reanimated:  "react-native-reanimated": "1.4.0",

**Comment by jakub-gonet** [comment]
Hi @SanjanaTailor,

please don't link to the external sites when submitting issue, every information should be contained here.

I see you're using Windows, could you test if builds on Linux are working? This is related to line

`classpath += files(android.bootClasspath)`, so add `println classpath`
and `println android.bootClasspath` before this assignment inside `node_modules/react-native-reanimated/android/build.gradle` and report back printed values here.

Closing until more info is given.

**Comment by vitalii-slobodzian** [comment]
I solve such issue on Windows just by replacing forward slashes `/` with backward slashes `\` in `android\local.properties` file
