### ISSUE TITLE
Can't use state/variable for gesture handle

### ISSUE THREAD

**Issue by hngocl** [software-mansion/react-native-reanimated#1175]
Hi. I'm use PanGesture and clamp it inside View but it not working
---------Here my link code:
https://github.com/hngocl/RNChallenge/blob/master/src/app/features/children/bouncing/Bouncing.tsx

**Comment by jakub-gonet** [comment]
Could you please wrap your code in [code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)? It's really unreadable in this form.

**Comment by hngocl** [comment]
i updated my source. but not working

**Comment by jakub-gonet** [comment]
Could you stick to the issue template? Specifically, we need information about expected / current behavior and stacktraces if applicable.

What does it mean that it doesn't work? It crashes, doesn't react to gestures or something else?

Closing until more info is given.

**Comment by hngocl** [comment]
-----you can see my video. before refresh: option1. after refresh: option2
![boucing](https://user-images.githubusercontent.com/43195241/92007692-75ff3100-ed70-11ea-9e9d-85be66b66234.gif)

----and my log:
![image](https://user-images.githubusercontent.com/43195241/92007854-a3e47580-ed70-11ea-8da9-19c9a6d8fad3.png)
--- and my source:
import React, { memo, useCallback, useState, useMemo, useEffect } from 'react'
import { View, StyleSheet, Image, Dimensions, LayoutChangeEvent } from 'react-native'
import isEqual from 'react-fast-compare';
import { images } from '@assets/image';
import Animated, { useAnimatedGestureHandler, useSharedValue, useAnimatedStyle, withDecay, } from 'react-native-reanimated';
import { PanGestureHandler } from 'react-native-gesture-handler'
import { clampV2, withBouncingV2 } from '@animated';
import { useSafeArea } from 'react-native-safe-area-context';
const IMAGE_WIDTH = 250
const IMAGE_HEIGHT = 150
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window')

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white'
    },
    wrapImg: {
        width: IMAGE_WIDTH,
        height: IMAGE_HEIGHT,
        overflow: 'hidden'
    },
    img: {
        resizeMode: 'stretch',
        width: '100%',
        height: '100%'
    }
});
/**
 * option 1
 */
const bounceX = SCREEN_WIDTH - IMAGE_WIDTH
const bounceY = SCREEN_HEIGHT - IMAGE_HEIGHT
const BouncingComponent = () => {
    const [sizeWrap, setSizeWrap] = useState({ width: 0, height: 0 })
    /**
     * option 2
     */
    const bounceX = useMemo(() => sizeWrap.width - IMAGE_WIDTH, [sizeWrap])
    const bounceY = useMemo(() => sizeWrap.height - IMAGE_HEIGHT, [sizeWrap])

    const translateY = useSharedValue(0)
    const translateX = useSharedValue(0)
    const onGestureEvent = useAnimatedGestureHandler({
        onStart: (_, ctx) => {
            ctx.startX = translateX.value;
            ctx.startY = translateY.value;
        },
        onActive: (event, ctx) => {
            translateX.value = clampV2(ctx.startX + event.translationX, 0, bounceX)
            translateY.value = clampV2(ctx.startY + event.translationY, 0, bounceY)
        },
        onEnd: ({ velocityX, velocityY }, _) => {
            translateX.value = withBouncingV2(withDecay({ velocity: velocityX, },), 0, bounceX)
            translateY.value = withBouncingV2(withDecay({ velocity: velocityY, }), 0, bounceY)
        }
    })
    const _onLayout = useCallback(({ nativeEvent: { layout: { height, width } } }: LayoutChangeEvent) => {
        setSizeWrap({ width, height })
    }, [])
    const cardStyle = useAnimatedStyle(() => {
        return {
            transform: [{ translateX: translateX.value }, { translateY: translateY.value }]
        }
    })
    useEffect(() => {
        console.log('sizeWrap', sizeWrap)
    }, [sizeWrap])
    return (
        <View style={[styles.container]} onLayout={_onLayout}>
            <PanGestureHandler {...{ onGestureEvent }}>
                <Animated.View style={[styles.wrapImg, cardStyle]}>
                    <Image style={[styles.img]} source={images['card1']} />
                </Animated.View>
            </PanGestureHandler>
        </View>
    )
}

export const Bouncing = memo(BouncingComponent, isEqual)

**Comment by hngocl** [comment]
@jakub-gonet

**Comment by jakub-gonet** [comment]
Could you format your code? It's unreadable in this form.

**Comment by jakub-gonet** [comment]
Should be fixed on master.
