### ISSUE TITLE
measure method crashes application

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1178]
## Description

If `measure` is called before `onLayout` callback was called - it crashes application.
Previously (don't know why) it didn't crash application, but returned invalid (random?) layout data.

## Steps To Reproduce

This code fully reproduce behaviour https://gist.github.com/likern/40608efe9e4f2276803cc44a17146fdf. With `!onLayoutWasCalled` condition application crashes.
```ts
  if (!onLayoutWasCalled) {
    const layoutInfo: LayoutInfo = measure(viewRef);
    console.log(`layoutInfo: ${JSON.stringify(layoutInfo)}`);
  }
```

With `onLayoutWasCalled` condition (when `measure` is called after `onLayout`) - no errors. 
```ts
  if (onLayoutWasCalled) {
    const layoutInfo: LayoutInfo = measure(viewRef);
    console.log(`layoutInfo: ${JSON.stringify(layoutInfo)}`);
  }
```

### Expected behavior
If think, if it's possible, `measure` should detect when it was called. And if was called before `onLayout` - return `undefined` for every field:
```ts
{
  x: undefined,
  y: undefined,
  pageX: undefined,
  pageY: undefined,
  width: undefined,
  height: undefined
}
```
### Actual behavior

Application crashes or `measure` returns invalid data.

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.5

## Screenshots

<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/842306/91858031-59c89a80-ec71-11ea-918f-bfb91c772f14.jpg" width=270 height=480></td>
    <td><img src="https://user-images.githubusercontent.com/842306/91858034-5af9c780-ec71-11ea-8017-62f2a6ab201d.jpg" width=270 height=480></td>
    <td><img src="https://user-images.githubusercontent.com/842306/91858039-5b925e00-ec71-11ea-9ba3-3a49e66bd520.jpg" width=270 height=480></td>
  </tr>
 </table>

<table>
  <tr>
<td><img src="https://user-images.githubusercontent.com/842306/91858045-5c2af480-ec71-11ea-8fb8-0d954fc28779.jpg" width=270 height=480></td>
<td><img src="https://user-images.githubusercontent.com/842306/91858048-5d5c2180-ec71-11ea-921f-248a2cb7b3fa.jpg" width=270 height=480></td>
<td><img src="https://user-images.githubusercontent.com/842306/91858051-5df4b800-ec71-11ea-8953-537f6d963649.jpg" width=270 height=480></td>
  </tr>
 </table>

<table>
  <tr>
<td><img src="https://user-images.githubusercontent.com/842306/91858053-5e8d4e80-ec71-11ea-86ac-93fee11e4ec5.jpg" width=270 height=480></td>
<td><img src="https://user-images.githubusercontent.com/842306/91858056-5f25e500-ec71-11ea-8d20-f569f0a21a73.jpg" width=270 height=480></td>
<td><img src="https://user-images.githubusercontent.com/842306/91858061-5fbe7b80-ec71-11ea-88ee-dc3e47198a28.jpg" width=270 height=480></td>
  </tr>
 </table>

<table>
  <tr>
<td><img src="https://user-images.githubusercontent.com/842306/91858063-60571200-ec71-11ea-90ee-8a5ff529e18a.jpg" width=270 height=480></td>
<td><img src="https://user-images.githubusercontent.com/842306/91858066-60efa880-ec71-11ea-85da-4074b4ecb045.jpg" width=270 height=480></td>
  </tr>
 </table>

**Comment by Szymon20000** [comment]
When https://github.com/software-mansion/react-native-reanimated/pull/1205 is merged it will throw an error if there is a problem with measurement. However, we are still working on better error handling, so it's possible that you get an unintelligible error on the screen if you didn't catch it.
