### ISSUE TITLE
worklet doesn't execute it's full body

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1179]
## Description

According to my understanding this code https://gist.github.com/likern/7599926cdda1d4a5edd221a2630a44af should rerender component 1000 times.

And I have to see ```worklet: onFinish is called; index is 1000``` in logs.

**But**, sometimes I see that worklet doesn't work as expected.

**It started executing and then suddenly just stops executing it's body.**

`worklet: function start` is the last log message. That means worklet started executing and then **suddenly stopped at all**.

```bash
[Tue Sep 01 2020 17:26:20.844]  LOG      [MeasureLayout] index [8], props: {"message":"8"}
[Tue Sep 01 2020 17:26:20.848]  LOG      useEffect: before runOnUI
[Tue Sep 01 2020 17:26:20.848]  LOG      useEffect: after runOnUI
[Tue Sep 01 2020 17:26:20.850]  LOG      worklet: function start
```

while in worklet code there is unconditional next `console.log` should be executed:
```tsx
console.log('worklet: function start');
const onLayoutWasCalled = getIsOnLayoutCalled();
console.log(`worklet: onLayoutWasCalled is ${onLayoutWasCalled}`);
```

## Steps To Reproduce

Reproducing code https://gist.github.com/likern/7599926cdda1d4a5edd221a2630a44af 

### Expected behavior

Worklet should always execute it's full body.

### Actual behavior

Worklet stops executing it's body.

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.5

**Comment by karol-bisztyga** [comment]
I see you implemented that idea of `useAnimatedState` on your own and used it. This might not always work properly due to the fact that shared values are asynchronous.
Also it is not recommended to use `runOnUI` and it will probably be taken away in the future.
Now all the supported hooks are working fine with React's state. You can just go ahead with something like this:
```
const [state, setState] = useState();
useDerivedValue(() => {
	setState(state + 1);
	/* ... */
})
```

**Comment by likern** [comment]
> I see you implemented that idea of `useAnimatedState` on your own and used it. This might not always work properly due to the fact that shared values are asynchronous.
> Also it is not recommended to use `runOnUI` and it will probably be taken away in the future.
> Now all the supported hooks are working fine with React's state. You can just go ahead with something like this:
> 
> ```
> const [state, setState] = useState();
> useDerivedValue(() => {
> 	setState(state + 1);
> 	/* ... */
> })
> ```
> 
> Plus, I tried to reproduce the issue but failed, `onFinish` always logged. What platform did you use? Was it simulator or the device?

Am I correct that on your test runs there were 1000 index executions?

For me it sometimes works, sometimes stop working.
For testing I used real Android device Xiaomi Mi 9T Pro.

**Comment by karol-bisztyga** [comment]
Ran it 5 times in row obtained 1k executions each time, onFinish called as well. Tested it on older hardware(±2k16 android smartphone, also on iOS).
You can try to remove `useAnimatedState`. Once rea alpha 6 is released all the hooks are going to work properly with react's state.

**Comment by terrysahaidak** [comment]
I'm pretty sure you guys are using different versions of Reanimated that's why I have different results. 
@likern I would wait until alpha.6 is released or use the master branch (at least for iOS).

**Comment by karol-bisztyga** [comment]
@likern try with alpha 6 
https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.6

**Comment by karol-bisztyga** [comment]
@likern any update?

**Comment by likern** [comment]
> @likern any update?

Will try today

**Comment by karol-bisztyga** [comment]
> > @likern any update?
> 
> Will try today

Okay, thank you 🎉

**Comment by likern** [comment]
> > > @likern any update?
> > 
> > 
> > Will try today
> 
> Okay, thank you

I've run multiple times and couldn't catch this bug again on `2.0.0-alpha.6`. Everything is working as expected.
