### ISSUE TITLE
useSharedValue hook throws errror

### ISSUE THREAD

**Issue by oktaysenkan** [software-mansion/react-native-reanimated#1180]
## Description

useSharedValue hook throws "Object.values requires that input parameter not be null or undefined"

### Screenshots

<img width="323" alt="Screen Shot 2020-09-02 at 00 37 43" src="https://user-images.githubusercontent.com/42527467/91908693-a71a2b80-ecb4-11ea-99ed-35360391743c.png">

## Snack or minimal code example

```
const offset = useSharedValue(1);
```

## Package version

- React: 16.13.1
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.5

**Comment by jakub-gonet** [comment]
Have you installed reanimated babel plugin?

**Comment by terrysahaidak** [comment]
Make sure to run packaged with `--reset-cache` flag: `npx react-native start --reset-cache`.

**Comment by oktaysenkan** [comment]
I tried both of them

**babel.config.js**
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'babel-plugin-root-import',
      {
        rootPathPrefix: '~',
        rootPathSuffix: 'src',
      },
      'react-native-reanimated/plugin',
    ],
  ],
};
```

**Comment by jakub-gonet** [comment]
Firstly, try cleaning project with:

- [resetting metro cache](https://github.com/software-mansion/react-native-reanimated/issues/1180#issuecomment-685289286)
- resetting watchman cache - `watchman watch-del-all`

If that doesn't help try deleting xcode build artifacts & node_modules

If none of that will work please post the entire function (with dependencies, so if you're using any variable, include it as well in the snippet) or better, create sample code on which you can repro this.

Closing for now.

**Comment by Un3qual** [comment]
@oktaysenkan did you ever figure this out?

**Comment by terrysahaidak** [comment]
Cleaning all the caches and reinstalling node modules will indeed fix this.

**Comment by Terfender** [comment]
Upgrading node version fixed the issue for me.
Ref: https://github.com/software-mansion/react-native-reanimated/issues/1244#issuecomment-694468084
