### ISSUE TITLE
what is the alternative way in V1 to implement `measure` in V2?

### ISSUE THREAD

**Issue by chj-damon** [software-mansion/react-native-reanimated#1197]
## Description
in v2, `measure` function can be used to get position info about one element. I'm using v1 in my project, and I'm wondering if there's any easy way to achieve this.

### Package versions

- React: v16.12
- React Native: v63.0
- React Native Reanimated: 1.13.0

**Comment by jakub-gonet** [comment]
Not really, `measure` is implemented natively and we don't provide any node to access it. This functionality is only available in v2.
