### ISSUE TITLE
Examples don't run on android ?

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-reanimated#1200]
trying to run `Examples` on android with no luck, they run on IOS just fine.

```
> Configure project :react-native-reanimated
Compatible side by side NDK version was not found.
building Reanimated2
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ahmedeid/code-playground/react-native-reanimated/android/build.gradle' line: 272

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> NDK is not installed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
```

![Screen Shot 2020-09-06 at 11 59 38 AM](https://user-images.githubusercontent.com/19273413/92323370-729dcb00-f038-11ea-9238-23691aa6b042.png)

**Comment by terrysahaidak** [comment]
Example project is using raw sources of Reanimated 2. The reanimated 2 is built in c++.

So in order to compile it, you need to install Android NDK - that's exactly what the error tells you.

**Comment by jakub-gonet** [comment]
Seems like we need to update README for the example app.

**Comment by a-eid** [comment]
@jakub-gonet I'm not sure what's there to read, I did follow it, what am I missing ?

![Screen Shot 2020-09-07 at 2 02 31 AM](https://user-images.githubusercontent.com/19273413/92338098-47ee5980-f0ae-11ea-96af-3447efdc46df.png)

**Comment by jakub-gonet** [comment]
I meant from our side, it's not updated yet, I'll do that when I'll have a moment.

**Comment by a-eid** [comment]
thank you. @jakub-gonet

**Comment by shivamjjha** [comment]
@jakub-gonet it is not updated yet. LOL I googled this and got here.  Also, it is confusing it does not tell where to run `npx react-native run-android`(for android): in `root` of project or in `Examples` directory
