### ISSUE TITLE
Question: How to get a Native Module to work with reanimated

### ISSUE THREAD

**Issue by gmaclennan** [software-mansion/react-native-reanimated#1204]
## Description

I would like an event from a Native Module to update an `Animated.Node`. Specifically, I want to update a node in response to an event emitter attached to the device orientation, using a module such as https://github.com/cpojer/react-native-heading. I am working with Android and native Java code.

One solution I tried was wrapping the Native Module as a Native UI Component `<DeviceHeading />`, extending a Native View with an `onChange` prop, and trying to use:

```js
const AnimatedDeviceHeading = Animated.createAnimatedComponent(DeviceHeading)
```

You can see the example code https://github.com/gmaclennan/react-native-device-heading/blob/master/example/src/App.tsx

I do not have experience writing native modules and components, but I have read all the docs for both reanimated and react-native for native components, and I cannot find any guidance about how to write a Native Component / Module that works with reanimated.

Ultimately I want to create a view that rotates based on device heading, but using `react-native-reanimated` so that the view rotation happens on the native thread (listening to device heading changes in JS results in a laggy UI).

## Code

https://github.com/gmaclennan/react-native-device-heading/blob/master/example/src/App.tsx

### Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 1.13.0

**Comment by jakub-gonet** [comment]
Reanimated should work with any registered native event. I think your problem may be related to not registering events from the JS side, try checking out `UIManager.genericDirectEventTypes` from RN. Closing as this isn't directly related to Reanimated but RN.
