### ISSUE TITLE
Install module - alpha.6

### ISSUE THREAD

**Issue by hngocl** [software-mansion/react-native-reanimated#1212]
![image](https://user-images.githubusercontent.com/43195241/92552004-c5ba8c80-f289-11ea-9408-2844732d117c.png)
I tried to delete node_modules then reinstall. Help.

**Comment by gaishimo** [comment]
Could you try to change Node.js version?
This error occurs when Node.js version is 10.x.

**Comment by a-eid** [comment]
does `alhpa.6` work with RN0.62.2 ? 

@hngocl it should work with Node 12.

**Comment by hngocl** [comment]
> does `alhpa.6` work with RN0.62.2 ?
> 
> @hngocl it should work with Node 12.

yeah thank you. it work
