### ISSUE TITLE
Nested children are not rendered

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1216]
## Description

I'm trying to implement high-performant infinite scrolling component (as replacement to `FlastList` and `RecyclerListView`).
When I reach the end of current `Animated.ScrollView` I add another (additional) elements to `children` (grouped by `Page` component).

Additional `Page` component is rendered, while it's children not.

### Screenshots

<table>
  <tr>
   <td><img src="https://user-images.githubusercontent.com/842306/92778780-280aae80-f3aa-11ea-83aa-124f8d071500.jpg" width=270 height=480></td>
    <td><img src="https://user-images.githubusercontent.com/842306/92778775-26d98180-f3aa-11ea-961f-defdaa969a42.jpg" width=270 height=480></td>
  </tr>
 </table>

We see that additional `View` was added and contains `Text` components as children. But it's not rendered on the screen.
<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/842306/92780508-f266c500-f3ab-11ea-8bff-c40157ceb4c9.png" width=270></td>
   <td><img src="https://user-images.githubusercontent.com/842306/92780501-f1ce2e80-f3ab-11ea-8117-425f3f138d3c.png" width=270></td>
  </tr>
 </table>

## Steps To Reproduce

Swipe down until additional page is added.

### Expected behavior

Children of all pages should be rendered correctly.

### Actual behavior

Only children of first page are rendered, while for other pages I see empty views.

## Snack or minimal code example

Here is a reproduction code https://gist.github.com/likern/9bc003967a6dca5a9d791aebce0d9898

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by terrysahaidak** [comment]
Since everything you use Reanimated for is scroll handler, I would try to reproduce this error with regular js listener first. Because I don't see the reason it should now work because of Reanimated2 :)

**Comment by likern** [comment]
> Since everything you use Reanimated for is scroll handler, I would try to reproduce this error with regular js listener first. Because I don't see the reason it should now work because of Reanimated2 :)

I've rewritten using React Native's `ScrollView`. Can confirm this happens on original React Native's `ScrollView`.
https://gist.github.com/likern/466bd17a861a7a3839fabf5b0c6b1e30

Close this issue here.
