### ISSUE TITLE
Poor performance when using Recycler List View with React Native Reanimated

### ISSUE THREAD

**Issue by nenjamin2405** [software-mansion/react-native-reanimated#1219]
## Description

Specifically, the requirement for my **Android** app is to render a infinite list items (render about 10000 items to make the list long enough to feel like infinity), and there is a middle indicator to indicate which item is selected, you can see the illustration below:

![image](https://user-images.githubusercontent.com/16648769/92986436-fcd8aa00-f4e4-11ea-83a9-034b03c6d515.png)

So there are 2 things I need to solve:
1. Render a very long list
2. When user scrolls the list, it needs to show the real-time selected item smoothly (when I scroll fast, the selected state need to reflect smoothly)

I already solved the first one thanks to Recycler List View, it can render 10,000 items with no problem and I can scroll smoothly. However, when I apply styling (text color, font weight) as animated attributes for my rendered items, it became super laggy, and the selected state is NOT updated smoothly and pretty delayed, my idea of implementation is described in the expo below

## Code

https://snack.expo.io/@nathan.tqn/53c59b

When you run the above code on your phone, you will see the scrollable list is very smooth when there is no animated attributes attached to the selected text, but if you go to the file `RecycleCategoryItem.tsx` and uncomment my code snippet

![image](https://user-images.githubusercontent.com/16648769/92986552-03b3ec80-f4e6-11ea-955e-83a9ccf45c83.png)
 
then try to scroll, the laggy situation happens, and as I mentioned above, the selected state is NOT updated smoothly and pretty delayed.

So my question is how could I solve this, is this issue related to Recycler List View or React Native Reanimated? Am I doing the logic in the correct way? or is there another way for me to handle this kind of selected state smoothly, thanks for your time.

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 1.13.0

**Comment by terrysahaidak** [comment]
That's because recycle list keeps dropping invisible and rendering new components which causes all the reanimated nodes you use in the components to be dropped and created accordingly.

Consider at least using proc for those. Also, make sure you use useMemo to memoize them as well so they won't be recreated on each render.

**Comment by nenjamin2405** [comment]
Hi @terrysahaidak, thanks a lot for your response. I already used the `useValues` util from `react-native-redash` to make sure all the animated values won't be recreated, and I did try the `proc` but no luck. When I add a `console.log("render")` inside the function `rowRenderer` of recycler list, I saw that it didn't not re-rendered (or dropped) any item, I'm not sure what should I try next, below is what I just changed to see how it perform:

I made a global func `getColorForItem` outside of the functional component
![image](https://user-images.githubusercontent.com/16648769/93009666-e5b1bf00-f5ad-11ea-9060-e6d6a9a9c095.png)

I calculate the color for the item inside the `rowRenderer` function and pass it down to the item
![image](https://user-images.githubusercontent.com/16648769/93009670-ee09fa00-f5ad-11ea-9b9d-956c317c7e31.png)

As soon as the child item receive the animated color, it makes the whole list supper laggy, if I remove the part `{ color }`, the list scrolls smoothly
![image](https://user-images.githubusercontent.com/16648769/93009776-11817480-f5af-11ea-857b-5449b941e2a0.png)

**Comment by terrysahaidak** [comment]
Could you please provide a snack with that code so I can try to debug and help?

**Comment by nenjamin2405** [comment]
Hi @terrysahaidak, here they are:

**Comment by nenjamin2405** [comment]
Hi @terrysahaidak, thanks in advanced, here they are:
1. My old implementation (You can see the difference of performance by uncommenting the code snippet inside the `RecycleCategoryItem.tsx` file): https://snack.expo.io/@nathan.tqn/53c59b
2. The new one using proc: https://snack.expo.io/@nathan.tqn/recycler-list-and-react-native-reanimated-using-proc

**Comment by terrysahaidak** [comment]
Sorry, didn't see the link in the first comment :)

Could you try this same thing but instead of color use the opacity? If the opacity works, then this all because of the async nature of layout updates

Also, make sure you use scrollThrottle as 1.

**Comment by nenjamin2405** [comment]
Hi @terrysahaidak, I tried to update the `scrollThrottle ` and use the `opacity` instead of `color`, but it's still laggy while scrolling. Here is the snack of using animated opacity: https://snack.expo.io/@git/github.com/nenjamin2405/animated-recycler-list

**Comment by terrysahaidak** [comment]
After some testing I can clearly see:
1. The lag on iOS with color is because of the async nature of the color property update - currently, it won't be updated on UI Thread but on Layout Thread which causes it to lag
2. There is a bug on Android which causes the Android scroll event to be async which causes some delay on the Android side so the color update beehive the same way opacity does.
3. The current implementation won't be perfect anyway because you don't mask the element style but calculate the "active" index based on translate which causes it to "jump" - just run the opacity example on android simulator and you'll see it. Because of that, I suggest you try the masked view approach. You can learn about it more here: https://github.com/catalinmiron/react-native-animated-flatlist-picker

**Comment by nenjamin2405** [comment]
Hi @terrysahaidak, thanks a lot for your suggestion about the masked view approach. I already tried to apply the idea of that repo into my case but no luck. I created 2 synchronized recycler lists and used the scrollToOffset to scroll the mask, however, It's quite laggy on the mask because it's dependent on the the listener inside useEffect to scroll whenever the scrollY is changed:

```
 React.useEffect(() => {
    scrollY.addListener((v) => {
      if (darkRef?.current) {
        darkRef.current.scrollToOffset({
          offset: v.value,
          animated: false,
        });
      }
    });
  });
```

And I believe the code above cannot be run in the UI Thread, so the performance will be not good also. Together with that, because I leverage the absolute mask, during the scrolling, there will be 2 visible edges (top and bottom) of the mask which look quite weird, you can see the youtube video url (unlisted url) below:

https://youtu.be/uwvzRET-NYE

Thanks a lot for your support, but is there any other solutions for me to try, or I need to implement this list by writing the native code (Java in Android for specific) and link this list to React Native using React Native Bridge? I'm pretty frustrated now :(

**Comment by terrysahaidak** [comment]
Unfortunately, I'm not sure if you would be able to implement it with Reanimated v1, but v2 will allow you to run srollTo on UI thread.

I would try also to use a regular view and translate it instead of the scroll view and scrollToOffset.

**Comment by nenjamin2405** [comment]
Hi @terrysahaidak, but if I use the regular view, it means that I need to render a lot of items at the same time which might result in low performance right?

**Comment by terrysahaidak** [comment]
Well, probably you don't need to render hundreds of options, but you do so to make it infinity. So render only that amount you need and set translateY at some point to 0 to emulate it continues

**Comment by tomekzaw** [comment]
Closing this as we no longer support v1.
