### ISSUE TITLE
Reanimated-2-playground example crash in debug mode

### ISSUE THREAD

**Issue by caiphaav** [software-mansion/react-native-reanimated#1220]
![crash](https://user-images.githubusercontent.com/53155258/92992319-c144dc80-f4f2-11ea-93d3-bd5f6e93f215.gif)
## Steps To Reproduce

1. Copy playground repo git@github.com:software-mansion-labs/reanimated-2-playground.git
2. Install dependencies && run application
2. Turn on debug mode
3. App unfortunately crash

   "react": "16.13.1",
    "react-native": "0.63.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "2.0.0-alpha.6"

**Comment by terrysahaidak** [comment]
Since the app is running with TurboModules enabled, there is no way to enable debugger with TurboModules just yet. 

You can learn more about some of the limitations here:
https://docs.swmansion.com/react-native-reanimated/docs/next#known-problems-and-limitations

**Comment by caiphaav** [comment]
> Since the app is running with TurboModules enabled, there is no way to enable debugger with TurboModules just yet.
> 
> You can learn more about some of the limitations here:
> https://docs.swmansion.com/react-native-reanimated/docs/next#known-problems-and-limitations

Thanks for your answer!
Reanimated is my favourite library in RN and i want to use Reanimated2 in my current project.
Maybe this feature will come in the upcoming releases?

**Comment by jakub-gonet** [comment]
This is related to turbomodules and not to Reanimated, so we have to wait for support from RN. Debugging works by running app js in the browser and when you bind to the native C++ methods this is impossible to do (at the moment, at least). You can use Flipper to debug applications with Turbomodules enabled.

**Comment by johnnyfekete** [comment]
Thanks @jakub-gonet, your solution worked for me!

Instead of enabling debugging, I downloaded Flipper from https://fbflipper.com/
And boom, all the logs show up in that!

**Comment by zhaiyjgithub** [comment]
@jakub-gonet Thanks.

**Comment by scott-schibli** [comment]
Are there any debuggers that are currently compatible with expo and turbomodules?

**Comment by arled** [comment]
But this is a massive blocker @terrysahaidak

**Comment by ZeeshanAhmadKhalil** [comment]
> Turbomodules

Are you usign flipper on Mac or Windows?

On Windows its show blank white screen with following warning in console.

`bundle.js:592 Failed to load settings file Error: ENOENT: no such file or directory, open 'C:\Users\mk141\.config\flipper\settings.json'`

**Comment by ZeeshanAhmadKhalil** [comment]
flipper consols are  not better than chrome developer consoles

**Comment by maqeelqureshi** [comment]
How can I debug source code line by line?

**Comment by megabayt** [comment]
Is it possible to "mock" animations when debugger is enabled?
