### ISSUE TITLE
App flickering if scrollTo is used inside onScroll

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1221]
## Description

If I use `scrollTo` inside `onScroll` I see flickering (like screen rerendering, while elements on the screen are non rerendered) on Android.

### Screenshots

https://drive.google.com/file/d/17M0v6OcC2dcS9UDBDiBmp3PW-dnukSG3/view?usp=sharing

## Steps To Reproduce

1. Slowly swipe up at page borders (every 15 tasks)
2. See flickering

### Expected behavior

No visible flickering

### Actual behavior

Screen is flickering

## Snack or minimal code example

Provided code https://gist.github.com/likern/e38c9668895ee0d0be58b61eca574a6c

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by piaskowyk** [comment]
Hey @likern
I know that is a little late, but I reviewed your code. The problem is due to you trying to call async function on the UI thread, and this function requires to run on JS thread because it is not workletized. Try use `runOnJS()`
I recommend using the newest Reanimated version also.
