### ISSUE TITLE
I am trying to run reanimated v1 and alpha in same project using Yarn and I am facing the bellow issues during build

### ISSUE THREAD

**Issue by harshiths037** [software-mansion/react-native-reanimated#1222]
## Description
I am trying to run reanimated v1 and alpha in same project using Yarn and I am facing the bellow issues during build

## Code:

**`Type com.facebook.react.uimanager.UIManagerReanimatedHelper is defined multiple times: /home/nineleaps/clone/animateable/node_modules/react-native-reanimated/android/build/.transforms/0ec47a5eb5611ba0bc19ff08f43b0b0e/classes/classes.dex, /home/nineleaps/clone/animateable/node_modules/react-native-reanimatedV2/android/build/.transforms/8dbc98d6c24072f3f4dc3c53bfc37756/jetified-react-native-reanimated-62-runtime/classes.dex`**

### Package versions

- React:16.11.0
- React Native:0.62.2
- React Native Reanimated: npm:react-native-reanimated@alpha

**Comment by terrysahaidak** [comment]
You don't need to have them both in the same project. Reanimated 2 is almost 100% backward compatible. You can continue to use features from v1 with v2

**Comment by jakub-gonet** [comment]
*except two [renames](https://docs.swmansion.com/react-native-reanimated/docs/next/migration#renamed-methods)
