### ISSUE TITLE
rotate on Android requires a string

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1232]
In v1 we use numbers for rotations, in v2 numbers work for iOS but not for Android.

**Comment by wcandillon** [comment]
Was this released in alpha.9? I cannot confirm that it works on Android alpha.9

**Comment by Szymon20000** [comment]
I don't think it's a bug. According to the docs (https://reactnative.dev/docs/transforms#transform) rotate field should be a string. Since https://github.com/software-mansion/react-native-reanimated/pull/1299 has been merged it's possible to animate strings.

**Comment by wcandillon** [comment]
There isn't a performance drawback with having a string value? Just wondering.

**Comment by terrysahaidak** [comment]
From the code it's running the regex to extract the value and get the prefix only single time so it's is fast
