### ISSUE TITLE
app crashes with reanimated 2

### ISSUE THREAD

**Issue by valin0k** [software-mansion/react-native-reanimated#1233]
## Description

Hey guys! I installed the last version of reanimated v2, and when i'm trying to use some hooks, like: `withSpring`, `withTiming`, `useAnimatedScrollHandler `, `useAnimatedStyle ` etc.. app crashes. `useSharedValue` works fine. I also tried to downgrade react-native to 0.63.1 and react-native-reanimated to 2.0.0-alpha.5 and received the same errors on Android and iOS

### Screenshots

<img width="341" alt="Снимок экрана 2020-09-16 в 22 23 17" src="https://user-images.githubusercontent.com/8665687/93368469-3a885a80-f878-11ea-9b8e-0fd219155cef.png">
<img width="338" alt="Снимок экрана 2020-09-16 в 22 23 01" src="https://user-images.githubusercontent.com/8665687/93368472-3ceab480-f878-11ea-87e9-3d6cd7f1efca.png">

## Steps To Reproduce

I created a snack with minimal code to reproduce errors

### Expected behavior

all reanimated hooks works and the app doesn't crash

### Actual behavior

app crash

## Snack or minimal code example
https://snack.expo.io/@pavel.s/reanimated-2

## Package versions

- React: ^16.13.1
- React Native: ^0.63.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by terrysahaidak** [comment]
In order to pass useAnimatedScrollHandler to scroll view, you need to make sure ScrollView is animated - use `Animated.ScrollView` instead like so:

```ts
import Animated, { useSharedValue, useAnimatedScrollHandler } from 'react-native-reanimated';

export default function App() {
  const sharedHeaderSize = useSharedValue(185); 
  const transY = useSharedValue(0); 
 
  const scrollHandler = useAnimatedScrollHandler({ 
	onBeginDrag: (e) => {
      sharedHeaderSize.value = withTiming(10);
    }
  }); 

  return (
    <Animated.ScrollView onScroll={scrollHandler}>
    <View>
      {Array(50) 
        .fill(1) 
        .map((_, i) => { 
          return ( 
            <Text> 
              {i} 
            </Text> 
          ); 
        })} 
    </View>
    </ScrollView>
  );
}

```

**Comment by Szymon20000** [comment]
Looks like the problem has been resolved. We will close it for now but feel free to reopen anytime.

**Comment by valin0k** [comment]
@terrysahaidak thank you for noticing, i missed Animated in `Snack` but even when i'm using `useAnimatedStyle` from the example folder, i receive errors without any render data
<img width="1275" alt="Снимок экрана 2020-09-17 в 16 33 55" src="https://user-images.githubusercontent.com/8665687/93453225-9c41d680-f903-11ea-88dc-1852555998fc.png">
<img width="1273" alt="Снимок экрана 2020-09-17 в 16 33 40" src="https://user-images.githubusercontent.com/8665687/93453241-a19f2100-f903-11ea-8946-d70ff7d1e571.png">

**Comment by terrysahaidak** [comment]
Could you please make sure you used Reanimated's babel plugin which is required to make everything work? Also, make sure you run packager with `--reset-cache`.

**Comment by valin0k** [comment]
@terrysahaidak 
babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset', '@babel/preset-typescript'],
  plugins: ['babel-plugin-styled-components'],
  env: {
    production: {
      plugins: ['transform-remove-console', 'react-native-reanimated/plugin'],
    },
  },
};
```

**Comment by valin0k** [comment]
@terrysahaidak error disappear after `--reset-cache`, i'll check if everything will work and write in the next few hours

**Comment by valin0k** [comment]
@terrysahaidak thank you! The error appears because i added reanimated plugin only for a production build. And can i ask about another case? How to use animation for `FlatList` and `SectionList`? As i understood these animated components does not exists inside reanimated 2 and i can't use them like so:
```
import Animated, {useSharedValue, useAnimatedScrollHandler} from 'react-native-reanimated';

  const transY = useSharedValue(0);

  const scrollHandler = useAnimatedScrollHandler({
    onScroll: (event) => {
      transY.value = event.contentOffset.y;
    }
  });

return (
  <Animated.SectionList onScroll={scrollHandler}>
    ....
  </Animated.SectionList>
)
```

But if i `import Animated from react-native` and run following code:

```
import {useSharedValue, useAnimatedScrollHandler} from 'react-native-reanimated';
import Animated from react-native

const AnimatedSectionList = Animated.createAnimatedComponent(SectionList);

  const transY = useSharedValue(0);

  const scrollHandler = useAnimatedScrollHandler({
    onScroll: (event) => {
      transY.value = event.contentOffset.y;
    }
  });

return (
  <AnimatedSectionList onScroll={scrollHandler}>
    ....
  </AnimatedSectionList>
)
```

i receive error:
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-17 at 22 52 21](https://user-images.githubusercontent.com/8665687/93495766-af22ce00-f938-11ea-8872-8a56b1538587.png)

How to use `FlatList` and `SectionList` with reanimated 2?

**Comment by jakub-gonet** [comment]
Leave Animated import in place and use `createAnimatedComponent()` from it:
```jsx
import Animated, {useSharedValue, useAnimatedScrollHandler} from 'react-native-reanimated';
const AnimatedSectionList = Animated.createAnimatedComponent(SectionList);
  const transY = useSharedValue(0);

  const scrollHandler = useAnimatedScrollHandler({
    onScroll: (event) => {
      transY.value = event.contentOffset.y;
    }
  });

return (
  <AnimatedSectionList onScroll={scrollHandler}>
    ....
  </AnimatedSectionList>
)
```

**Comment by valin0k** [comment]
@jakub-gonet thank you! Uh, no errors anymore
