### ISSUE TITLE
Displaying local images is broken ('No suitable image URL loader found for XXX') after V2 upgrade on iOS

### ISSUE THREAD

**Issue by davidfarinha** [software-mansion/react-native-reanimated#1235]
## Description

In the V2 alpha, displaying local images with `react-native` <Image component is broken on iOS.

Displaying local images using either `assets-library://asset` (AVAsset) or `ph://` (PHAsset) doesn't work and causes a runtime error (see screenshots below):
```
<Image source={{ uri: 'assets-library://asset/asset.JPG?id=B589F112-6B90-40F2-9167-56F164DD5113&ext=JPG' }} style={{ height: 100, width: 100 }}/>
<Image source={{ uri: `ph://B589F112-6B90-40F2-9167-56F164DD5113` }} style={{ height: 100, width: 100 }}/>
```
This code works correctly displays images before configuring the native iOS project for reanimated V2 alpha (ie following the iOS instructions on the docs [here](https://docs.swmansion.com/react-native-reanimated/docs/next/installation#ios)), but breaks and stops rendering the images after upgrading to V2/enabling Turbo Modules.
The local images I'm trying to display 100% exist, and the exact same code displays the images correctly again after reverting the native iOS project changes required to upgrade to V2 alpha. 

Specifically after following the iOS installation guide for v2 and adding this required configuration to the `AppDelegate.mm` file, this error starts to occur:

```
- (id<RCTTurboModule>)getModuleInstanceFromClass:(Class)moduleClass
{
	if (moduleClass == RCTImageLoader.class) {
	return [[moduleClass alloc] initWithRedirectDelegate:nil
	loadersProvider:^NSArray<id<RCTImageURLLoader>> * {
		return @ [[RCTLocalAssetImageLoader new]];
	}
	decodersProvider:^NSArray<id<RCTImageDataDecoder>> * {
		return @ [[RCTGIFImageDecoder new]];
	}];
	} else if (moduleClass == RCTNetworking.class) {
	return [[moduleClass alloc] initWithHandlersProvider:^NSArray<id<RCTURLRequestHandler>> *{
		return @[
		[RCTHTTPRequestHandler new],
		[RCTDataRequestHandler new],
		[RCTFileRequestHandler new],
		];
	}];
	}
	return [moduleClass new];
}
```
and displaying images no longer works.

### Screenshots
![IMG_686E7AD3703E-1](https://user-images.githubusercontent.com/3890344/93393682-e0cd6380-f86a-11ea-9f42-8313b089dbcc.jpeg)
![IMG_DD5856D9185E-1](https://user-images.githubusercontent.com/3890344/93393687-e1fe9080-f86a-11ea-98cc-18b5566d78ff.jpeg)

## Steps To Reproduce

Try to display a local image from the camera roll/media library on iOS in this repository's Example project. 

1. Update any component in the example project (eg `./Example/src/App.js/MainScreen` component and attempt to render an image using `assets-library://asset` or `ph://`.
```
<Image source={{ uri: 'assets-library://asset/asset.JPG?id=B589F112-6B90-40F2-9167-56F164DD5113&ext=JPG' }} style={{ height: 100, width: 100 }}/>
<Image source={{ uri: `ph://B589F112-6B90-40F2-9167-56F164DD5113` }} style={{ height: 100, width: 100 }}/>
```
2. Observe runtime error and image not displayed.

### Expected behavior
Local images from the camera roll/media library on iOS should display after converting to reanimated V2.

### Actual behavior
Images do not display

## Package versions

- React: 16.13.1
- React Native: Tested on versions 0.63.0 - 0.63.3
- React Native Reanimated: Tested on versions  2.0.0-alpha.1 - 2.0.0-alpha.6

**Comment by terrysahaidak** [comment]
I think it's a problem of React Native under TurboModules. Could you please try this patch?
https://github.com/rainbow-me/rainbow/blob/develop/patches/react-native%2B0.63.2.patch

It will make sure Reanimated is the only module that uses TurboModules.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you still experience this problem using the latest alpha please reply.
