### ISSUE TITLE
Native code still emitting event after react component get unmounted

### ISSUE THREAD

**Issue by normanzb** [software-mansion/react-native-reanimated#1243]
## Description

If react component that uses reanimated's `call()` gets umounted at the right timing, the event listeners for `onReanimatedCall` will be detached before the native AnimatedNode gets properly teared down, which creates slim window for the native side to slip through some events.

A potential fix is to make `dropNode` resolve a promise and `await` it from JS side, as shown here:

https://github.com/normanzb/react-native-reanimated/commit/c9f2950f0d6c4f0d79dd78a93b5daa797d2df4a0

### Screenshots

<img src="https://user-images.githubusercontent.com/130634/93507452-9fde5900-f915-11ea-8045-7c2169a1b2a0.png" width="450" />

<img src="https://user-images.githubusercontent.com/130634/93507463-a7056700-f915-11ea-95cd-890e4482dc1d.png" width="450" />

## Steps To Reproduce

1. Clone and checkout my branch from here: https://github.com/normanzb/react-native-reanimated/tree/bug
2. `cd` into `Example` folder and build it according to the readme file
3. Open the app in simulator and click on the first item
4. Try step 3 a few more times if you don't see the warning message pop up.

### Expected behavior

Should be no warning message about `onReanimatedCall` 

### Actual behavior

Got warning message says:

> Sending `onReanimatedCall` with no listeners registered.

## Snack or minimal code example

https://github.com/normanzb/react-native-reanimated/blob/bug/Example/src/CallTest.js

## Package versions

- React: 16.13.1
- React Native: 0.63.0
- React Native Reanimated: 2.0.0-alpha.6 and 1.13.0

**Comment by jakub-gonet** [comment]
The problem with using async `dropNode` is that we'll have to wait for it to return. Drops will be communicated to JS on the next frame IIRC, so we have to wait 17ms for each drop. If we'd be dropping 500 nodes (which isn't that rare) we'd have to wait for 8.5s. I think we batch those calls somewhere so we can change that to be async and waiting for one frame on batch isn't that bad.

**Comment by jakub-gonet** [comment]
This is related to v1 and we're slowly deprecating this version. We don't want to introduce new changes there unless they're critical to the operation of the library, so I'll close that. If you want to prepare PR fixing that I'm happy to help.
