### ISSUE TITLE
"react-native-reanimated/plugin" does not work

### ISSUE THREAD

**Issue by fahelmoreira** [software-mansion/react-native-reanimated#1244]
### Screenshots
![IMG_3A3245021BDC-1](https://user-images.githubusercontent.com/39835527/93513458-4289de00-f8fc-11ea-8f50-31e88888f1c3.jpeg)
## Steps To Reproduce

1. add react-native-reanimated/plugin to babel.config.js

### Expected behavior
the code to compile
### Actual behavior
the bundler crashes 
## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by fahelmoreira** [comment]
yes! i did

**Comment by fahelmoreira** [comment]
still doesn't work, I don't know what to do anymore

**Comment by terrysahaidak** [comment]
Then it should work. Without any code we won't be able to help you, unfortunately.

**Comment by fahelmoreira** [comment]
that's the bable code

/* eslint-disable func-names */
const rootImportOpts = [
  {
    rootPathSuffix: './src',
    rootPathPrefix: 'src',
  },
  {
    rootPathSuffix: './src/screens',
    rootPathPrefix: 'screens',
  },
  {
    rootPathSuffix: './src/shared-components',
    rootPathPrefix: 'shared-components',
  },
  {
    rootPathSuffix: './src/utils',
    rootPathPrefix: 'utils',
  },
  {
    rootPathSuffix: './assets',
    rootPathPrefix: 'assets',
  },
  {
    rootPathSuffix: './src/context',
    rootPathPrefix: 'context',
  },
];
// require('babel-core').transform('code', { plugins: ['babel-plugin-rewire'] });

module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo', '@babel/preset-typescript'],
    sourceMaps: true,
    plugins: [
      [
        'babel-plugin-root-import',
        {
          paths: rootImportOpts,
        },
      ],
      // '@babel/proposal-class-properties',
      // '@babel/proposal-object-rest-spread',
      'transform-class-properties',
      // ['babel-plugin-rewire'],
      'react-native-reanimated/plugin',
    ],
  };
};

**Comment by fahelmoreira** [comment]
if i remove 

'react-native-reanimated/plugin', the error doesn't show

**Comment by terrysahaidak** [comment]
could you try the reanimated plugin to be the very first one one the list?

**Comment by jakub-gonet** [comment]
What is your node version? Try using node 12

**Comment by fahelmoreira** [comment]
it's 10.15.3

**Comment by fahelmoreira** [comment]
i tried the reanimated-2-playground 
git checkout git@github.com:software-mansion-labs/reanimated-2-playground.git
and got the same error

**Comment by jakub-gonet** [comment]
I think I saw someone having this problem and upgrading node version helped

**Comment by fahelmoreira** [comment]
It worked! thanks, man!!!

**Comment by fahelmoreira** [comment]
the could add to the documentation that requires node 12 or above!
