### ISSUE TITLE
When do we need to define 'worklet's/use runOnUI?

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1248]
## Description

Hi! I haven't found a clear answer to this in the docs, but currently I'm imperatively animating an opacity of my component whenever a button is pressed. That means, I've ended up with the following code:

```ts
const onPostPress = useCallback(() => {
	onPress(post);
	isTextHidden.current = true;
	textContainerOpacity.value = withTiming(0, { duration: 300 });
}, [animateTextContainer, onPress, post]);
```

Now I've thought, does `withTiming` run the animation on the UI JS thread or did I just run an animation on my React JS Thread? Then I came up with the following code:

```ts
const animateTextContainer = useCallback(
	(hidden: boolean) => {
		'worklet';
		textContainerOpacity.value = withTiming(hidden ? 0 : 1, { duration: 300 });
	},
	[textContainerOpacity],
);
const onPostPress = useCallback(() => {
	onPress(post);
	isTextHidden.current = true;
	runOnUI(animateTextContainer)(true);
}, [animateTextContainer, onPress, post]);
```

But I've heard `runOnUI` shouldn't be used often and will likely be removed in future versions. What's the correct way to animate opacity on button press (JS event)?

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by terrysahaidak** [comment]
You can just assign the animation and it will work. The only case where runOnUi might be required is if you have like 10 independent animations and should be sure they are executed in the same frame.

Worklet annotation should be used only if you want the code to be executed on UI Thread, without it it will be async.

**Comment by mrousavy** [comment]
@terrysahaidak I see, thanks. That also means that any assignment to shared values (.value =) with animations (withTiming, withSpring) will run on the UI thread, no matter where they are dispatched from?

**Comment by terrysahaidak** [comment]
You assign it on JS Thread, but the actual animation will be executed on UI Thread.

Also, if you assign value, it will trigger all the stuff depending on it on UI Thread too. But one thing to keep in mind - all those are async since we change threads.

**Comment by mrousavy** [comment]
@terrysahaidak Makes sense, thanks for your explanation. Now I gotta debug why my value changes won't reflect UI changes... 🧐

**Comment by terrysahaidak** [comment]
If you post more code we can find an issue

**Comment by mrousavy** [comment]
Okay so apparently my Shared Value doesn't get applied to it's style.

## Without useAnimatedStyle

```jsx
const headerStyle = { ...styles.header, transform: [{ translateY: -140 }] };

return ( /* ... */
	<Reanimated.View style={headerStyle}>
		/ * ... */
	</Reanimated.View>
	);
```

<img src="https://user-images.githubusercontent.com/15199031/93668239-8101d300-fa8b-11ea-8ef9-fb8b3c463447.png" width="55%">

> As you can see, it correctly translates the Y coord to -140.

## With useAnimatedStyle

```jsx
const headerStyle = useAnimatedStyle(() => {
	const y = Math.min(interpolate(scrollY.value, [0, 1], [1, 0]), 0);
	Logger.debug(`Header should be at ${y}`);
	return { ...styles.header, transform: [{ translateY: y }] };
});

return ( /* ... */
	<Reanimated.View style={headerStyle}>
		/ * ... */
	</Reanimated.View>
	);
```

Now when it's not scrolled it should be at `0`, which it is:

<img src="https://user-images.githubusercontent.com/15199031/93668281-b1497180-fa8b-11ea-9747-fef0fddbbb2c.png" width="55%">

But when I scroll, nothing changes: 

<img src="https://user-images.githubusercontent.com/15199031/93668294-c2927e00-fa8b-11ea-90fd-f4a10267675c.png" width="55%">

I scrolled the ScrollView which maps my scrollY shared value upwards, and in the console I can read `Header should be at ...` (`...` = some negative values, `-86`, etc...) but those changes aren't displayed in my view.

**Comment by mrousavy** [comment]
Okay I found out why that wasn't working. I cannot return the array including the `styles.header` static styles in my `useAnimatedStyles` hook. I had to only return the `transform`, and then merge the style together in my component.

So, this:

```jsx
const headerStyle = useAnimatedStyle(() => {
	const y = Math.min(interpolate(scrollY.value, [0, 1], [1, 0]), 0);
	Logger.debug(`Header should be at ${y}`);
	return { ...styles.header, transform: [{ translateY: y }] };
});

return ( /* ... */
	<Reanimated.View style={headerStyle}>
		/ * ... */
	</Reanimated.View>
	);
```

becomes this:

```jsx
const headerStyle = useAnimatedStyle(() => {
	const y = Math.min(interpolate(scrollY.value, [0, 1], [1, 0]), 0);
	Logger.debug(`Header should be at ${y}`);
	return { transform: [{ translateY: y }] };
});

return ( /* ... */
	<Reanimated.View style={[styles.header, headerStyle]}>
		/ * ... */
	</Reanimated.View>
	);
```

Is that intended behaviour? cc @kmagiera @jakub-gonet

**Comment by terrysahaidak** [comment]
That's because your interpolate return value between 0 and 1.

Interpolate works a bit differently. The first array is the input and is basically represent the subset of values should be taken from your shared value (first param).

The second array is a range of values it should interpolate to.

So basically in your case you need to 2rite something like that:

input will be [0, 140] - basically from scroll 0 to scroll 140
the output will be [0, -140]

`interpolate(scroll.value, [0, 140], [0, -140])`

**Comment by mrousavy** [comment]
@terrysahaidak actually that doesn't make a difference, since I'm not clamping it anyways. I've noticed that I used interpolate here to flip the value, so now I'm using:

```js
const y = Math.min(-scrollY.value, 0);
```

**Comment by jakub-gonet** [comment]
I think this is resolved so closing.
