### ISSUE TITLE
How to access the clock time

### ISSUE THREAD

**Issue by scrapecoder** [software-mansion/react-native-reanimated#1251]
## Description 
I'm running a clock for the animation which is working fine but I want to know time also meaning in the middle of the animation I want to check how much time it took and how much time is remaining to complete the animation. Is that possible to know?

## Code 
function runTiming(clock, value, dest) {
const state = {
finished: new Value(0),
position: new Value(0),
time: new Value(0),
frameTime: new Value(0),
};

const config = {
duration: 5000,
toValue: new Value(0),
easing: Easing.inOut(Easing.ease),
};

return block([
cond(clockRunning(clock), [
  // if the clock is already running we update the toValue, in case a new dest has been 
  passed in
    set(config.toValue, dest),
 ], [
  // if the clock isn't running we reset all the animation params and start the clock
  set(state.finished, 0),
  set(state.time, 0),
  set(state.position, value),
  set(state.frameTime, 0),
  set(config.toValue, dest),
  startClock(clock),
]),
// we run the step here that is going to update position
timing(clock, state, config),
// if the animation is over we stop the clock
cond(state.finished, debug('stop clock', stopClock(clock))),
// we made the block return the updated position
state.position,
 ]);
 

### Package versions
"react-native": "^0.63.0",
"react-native-reanimated": "1.13.0",

- React:
- React Native:
- React Native Reanimated:

**Comment by jakub-gonet** [comment]
You can't do that directly but you can try calculating it the same way [`timing` does that](https://github.com/software-mansion/react-native-reanimated/blob/master/src/animations/timing.js#L61). What's your use-case on that functionality?
