### ISSUE TITLE
useAnimatedStyle doesn't allow combining static styles

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1253]
## Description

The `useAnimatedStyle` hook only works when using purely animated values, so it cannot be used to merge additional static styles (e.g. from `StyleSheet.create`).

E.g.:

#### Doesn't work

```jsx
const headerStyle = useAnimatedStyle(() => [styles.header, { transform: [{ translateY: headerY.value }] }]);
// ...
return <Reanimated.View style={headerStyle} ... />
```

#### Works

```jsx
const headerStyle = useAnimatedStyle(() => ({ transform: [{ translateY: headerY.value }] }));
// ...
return <Reanimated.View style={[styles.header, headerStyle]} ... />
```

With "doesn't work" I mean that the transforms aren't applied at all. The `styles.header` values are correctly applied, but `translateY` just always stays `0`. (Even though the function is executed multiple times, checked with `console.log`!)

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by mrousavy** [comment]
So I've given this some more thought, and I can't wrap my head around if it's better to not allow that, or if that should be allowed.. 

To my understanding, the `useAnimatedStyle` hook is executed in the separate JS thread by reanimated everytime the `headerY` value changes, so every frame. We don't want to copy over the `styles.header` object and re-create those expensive arrays every frame, but that's what would happen, right?

If I combine it outside of the `useAnimatedStyle` hook (`<Reanimated.View style={[styles.header, animatedHeaderStyle]} ... />`), then the `styles.header` and `animatedHeaderStyle` objects are passed to the reanimated view by reference, making it a one time array allocation. Therefore it is best to write minimal code in the worklets and combine it afterwards with static stuff (styles), correct?

@kmagiera @jakub-gonet can you give me some insights if my answers are correct?

**Comment by mrousavy** [comment]
Since alpha 7 there is an exception thrown when trying to combine statics styles with animated styles in the `useAnimatedStyle` hook:

![Simulator Screen Shot - iPhone 11 - 2020-09-24 at 15 23 17](https://user-images.githubusercontent.com/15199031/94150850-f00b6d00-fe79-11ea-92d6-ff1b77933096.png)

**Comment by terrysahaidak** [comment]
useAnimatedStyle hook should return an object. then you should pass that object to styles. In that way, Reanimated Views can detect those and "subscribe" for changes.

So returning an array isn't something that was intended to be supported.

I'm not sure about the future so maybe @Szymon20000 or @kmagiera can tell more.

But, IMO, I don't think this should be ever supported, I don't see any additional value in this.

**Comment by mrousavy** [comment]
@terrysahaidak Makes sense to me. To statically apply styles then, we would have to combine them in the view directly, therefore allocating a new array on ever render. We can't combine those in a `useMemo` hooks beforehand, can we? (Useful for example if I have a custom component that has the following styles for a single view: `[styles.someStyle, styleObjectPassedViaProps, animatedStyle, { left: someCalculatedValue }]`)

Also, I know that we're currently in alpha, but I'd say we should give a detailed error message in case the user tries to misuse the `useAnimatedStyle` hook.

**Comment by terrysahaidak** [comment]
Static styles can be passed separately, calculated value can also be used either in animated styles or directly. no need to use array still.

Also, TS types should already forbid this, I guess.

Usefully error would be nice so in the meantime fell free to submit a PR :)

**Comment by mrousavy** [comment]
@terrysahaidak The types don't forbid this, since they use `StyleProp<..>`:

![Screenshot 2020-09-24 at 20 17 03](https://user-images.githubusercontent.com/15199031/94183660-109bed00-fea3-11ea-800a-200324ccca80.png)

.. which is defined as:

![Screenshot 2020-09-24 at 20 17 22](https://user-images.githubusercontent.com/15199031/94183651-0aa60c00-fea3-11ea-8677-6c9a48550f46.png)

Time for #270 😁

Do you want me to open a PR which explicitly defines the styles using a custom type? Something along the lines of:

```ts
export type AnimatedStyleProp<T> = T | RegisteredStyle<T>;
export function useAnimatedStyle<
  T extends AnimatedStyleProp<AnimateStyle<ViewStyle | ImageStyle | TextStyle>>
>(updater: () => T, deps?: DependencyList): T;
```

**Comment by terrysahaidak** [comment]
Right now we should allow only object to be returned from it. Everything else just won't work.

**Comment by mrousavy** [comment]
Yep. I've create a PR for this here: https://github.com/software-mansion/react-native-reanimated/pull/1276
