### ISSUE TITLE
Can't run Example directory on Android (Could not create service of type...)

### ISSUE THREAD

**Issue by lyonelz96** [software-mansion/react-native-reanimated#1275]
## Description

So for the life of me I can't figure out the reason I can't run the Example directory on android.

I installed the NDK and CMake following the instructions [here](https://developer.android.com/studio/projects/install-ndk)

Then I did the following:
```
git clone https://github.com/software-mansion/react-native-reanimated.git
cd react-native-reanimated/Example/
yarn install
npm run start
react-native run-android  **In another terminal instance **
```
## Error Message

![image](https://user-images.githubusercontent.com/43832900/94177883-4f608180-fe68-11ea-9448-e1aa27467654.png)

## Suspicions
 I'm guessing it's some kind of permission error? Not sure how to fix it.

**Comment by lyonelz96** [comment]
# Fixed!
Here's what I did to fix it:
So starting from scratch.
```
git clone https://github.com/software-mansion/react-native-reanimated.git
cd react-native-reanimated
yarn install
cd Example/
yarn install
```
Then I opened the Example/android directory in Android Studio and waited for it to do its magic. After waiting a little bit this popped up:
![Peek 2020-09-24 15-12](https://user-images.githubusercontent.com/43832900/94190775-90fa2800-fe7a-11ea-8ae5-ce199b3e6692.gif)

What that did in the repo was modify the build.gradle files in:
1. react-native-reanimated/android/build.gradle
![image](https://user-images.githubusercontent.com/43832900/94191040-edf5de00-fe7a-11ea-9fa0-84b74d27f8b3.png)

2. react-native-reanimated/Example/android/build.gradle
![image](https://user-images.githubusercontent.com/43832900/94191080-01a14480-fe7b-11ea-816d-7133fcf25492.png)

After that and making sure everything was good in Android Studio. I closed that and did:

```
cd react-native-reanimated/Example/
react-native run-android
```
And boom, it installs and works as intended!

I'll leave it up to you guys if you want to close the issue or not! :100:

**Comment by jakub-gonet** [comment]
I'll close it, but thanks for the detailed description and solution.
