### ISSUE TITLE
How to trigger re-render on sharedValue change?

### ISSUE THREAD

**Issue by jerryjfwang** [software-mansion/react-native-reanimated#1277]
## Description
I'm trying to show or hide a component depending on the sharedValue that controls the translation of another component. Both components have the same parent component. Since changing the sharedValue doesn't re-render the components, how can I achieve that behavior?

Right now, I'm just updating a React state variable in a useAnimatedStyle hook that returns an empty object. Are there any drawbacks to doing this?

Thanks!

### Package versions
- React: 16.13.1
- React Native: 0.63.1
- React Native Reanimated:  ^2.0.0-alpha.6

**Comment by karol-bisztyga** [comment]
It is alright although you could use `useDerivedValue` instead as it does less and is simpler/faster.

**Comment by terrysahaidak** [comment]
There is `useAnimatedReaction` hook which is designed to solve this exact case. 

```tsx
useAnimatedReaction(
  () => {
    return sv.value > 100
  },
  (shoudHide) => {
    if (shouldHide) hide() 
  },
);
```

**Comment by karol-bisztyga** [comment]
How's that better than `useDerivedValue(() => {if(sv.value > 100) { hide() }})`?
Maybe depends what goes down in `hide` but as I understand this there's just a simple state change.
