### ISSUE TITLE
iOS build failure with use_frameworks enabled

### ISSUE THREAD

**Issue by developer-darpan** [software-mansion/react-native-reanimated#1278]
## Description
iOS build failure if `use_frameworks` is enabled in Podfile.

Error: `<double-conversion/double-conversion.h> file not found`.

## Steps To Reproduce

1. clone https://github.com/software-mansion-labs/reanimated-2-playground & install dependencies
2. enable `use_frameworks` in ios/Podfile.
3. iOS build will fail.

### Expected behavior
iOS build failure.

- React: 16.13.1
- React Native: 0.63.1
- React Native Reanimated: 2.0.0-alpha.6

**Comment by Szymon20000** [comment]
I've checked several times and it seems to be working fine now.
