### ISSUE TITLE
"undefined is not an object" in styleDiff and styleUpdater

### ISSUE THREAD

**Issue by yolpsoftware** [software-mansion/react-native-reanimated#1283]
## Description

I'm getting this exception when running v2 alpha 6 on the Expo app with Expo SDK 39:

```
undefined is not an object (evaluating 'Object.keys(oldStyle)')

keys@[native code]
styleDiff
[native code]
styleUpdater
[native code]
_f
[native code]
```

### Screenshots

![image](https://user-images.githubusercontent.com/1302357/94325681-e714bb80-ff9f-11ea-8407-61ab9fd5ac9d.png)

## Steps To Reproduce

Unfortunately, I was not able to create a minimal repro. I had a minimal repro, but when I uploaded it to Github and ran the example on another workstation, the error did not happen again, so it seems that some local config / cache issue is involved. I'm going to try again to create a minimal repro, but I don't have much time the next two weeks.

That's why I'm posting the issue now, even though I don't have a repro. 1) maybe the stacktrace helps you guys to see where the problem is, and 2) maybe someone else has the same error?

## Package versions

```
    "react": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz",
    "react-native-reanimated": "2.0.0-alpha.6",
```

**Comment by HrantAbrahamyan** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/1270

**Comment by yolpsoftware** [comment]
@HrantAbrahamyan thank you! Didn't find that issue on Google 😊
