### ISSUE TITLE
iOS: Full app crash

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1284]
## Description

I'm receiving the following error on iOS:

```
com.facebook.react.JavaScript (17): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

I've implemented a stories screen using react-native-navigation, and see this error when I quickly close the story (= unmount the screen) while (or shortly before) I run an animation with reanimated. In this case it's a `withTiming` worklet.

This is my call stack at the time of the crash:

<img src="https://user-images.githubusercontent.com/15199031/94345704-31417f80-0028-11eb-9d80-1b9b24ede548.png" width="70%">

## Steps To Reproduce

1. Create app using react-native-navigation and reanimated
2. Open and close stories like a maniac
3. At some point, close the story (and therefore unmount the screen) exactly when a worklet is being started, not sure it it's caused by a timing function, or the timing function having a callback and then unmounting the Reanimated View.

### Expected behavior

I expect the story to close and any reanimated worklets/animations/state to be disposed

### Actual behavior

The app crashes with the error `com.facebook.react.JavaScript (17): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`

![Screenshot 2020-09-26 at 18 44 27](https://user-images.githubusercontent.com/15199031/94345716-50401180-0028-11eb-9b8d-5d5a86fc03d2.png)

## Snack or minimal code example

Working on this. Have to strip out a lot of things, not sure if I can easily replicate it using a simple example...

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha7
- React Native Navigation: 7.0.0-snapshot2020

**Comment by Ghya** [comment]
I have the same issue with a header, animated while scrolling
But the same animation was working 2 days ago, before react-native upgrade (0.63.0 -> 0.63.2)

**Comment by JB-CHAUVIN** [comment]
Hello, same issue goes for me on RN 0.63.2 and Reanimated 2 Alpha 7.

Animated.ScrollView with scrollHandler and complex animation make the app freeze...

**Comment by ajpaulingalls** [comment]
I'm also getting an iOS app freeze when regular animations run alongside reanimations.  Specifically, the main thread is stuck waiting for a semaphore on line 227 of REANodesManager.m, in the performOperations method:

```
dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
```

**Comment by jpudysz** [comment]
@Szymon20000 - I tested your fix from the master but issue still persists. Rewerting to @alpha.6 fixes the freezes

**Comment by Szymon20000** [comment]
Hey guys! 
I need a minimal code example. 
It's hard to fix the problem without seeing it.

**Comment by jpudysz** [comment]
App freezes randomly, but I have one place where it's reproducible each time. Its rather a big app so if you are interested I can offer video call with screen sharing

**Comment by Szymon20000** [comment]
@jpudysz Do you use Wix navigation?

**Comment by jpudysz** [comment]
No, my nagivation stack:
```
    "@react-navigation/native": "5.7.6",
    "@react-navigation/stack": "5.9.3",
```

**Comment by mrousavy** [comment]
@Szymon20000 I use wix navigation, but I don't really have a point where I can _always_ reproduce it :/
I'll investigate this further.

**Comment by Szymon20000** [comment]
@jpudysz Are you getting the same error and call stack as mentioned above?

**Comment by jpudysz** [comment]
No error, no crash, no logs in Xcode - but the app is frozen and not responding.

**Comment by mrousavy** [comment]
@jpudysz when the app is frozen hit the pause button in Xcode. Then show us your callstack

**Comment by Szymon20000** [comment]
Ok, I think the original problem has been solved by my fix. @jpudysz Your problem is probably caused by deadlock (probably because of our synchronic layout). I need a repo though. Your call stack will be also very helpful. 
@mrousavy Could you try our master build? https://docs.swmansion.com/react-native-reanimated/docs/installation#using-master-branch-builds (it should be available in 2.5 hours)

**Comment by jpudysz** [comment]
@mrousavy - after pause no additional logs, but I can confirm that problem is when I trigger animations + I'm calling navigate

**Comment by mrousavy** [comment]
> @mrousavy Could you try our master build? https://docs.swmansion.com/react-native-reanimated/docs/installation#using-master-branch-builds (it should be available in 2.5 hours)

Isn't npm able to directly install from GitHub? Anyways, will try that, thanks!

**Comment by kmagiera** [comment]
when testing on iOS you can install directly from NPM because xcode can compile c++ code. This is not the case on Android where the standard Android dev setup does not include NDK (toolchain needed to compile c++ code). The master builds include compiled version of the reanimated library, but if you only want to do test builds with xcode you can compile the library from sources

**Comment by mrousavy** [comment]
@kmagiera I'm aware of that, I do have the NDK toolchain installed 👍 

Only disadvantage is after every clean and rebuild I need to wait 3 years for it to build

**Comment by Alexandredc** [comment]
> No error, no crash, no logs in Xcode - but the app is frozen and not responding.

Same problem here: no errors, no crash, no logs.

My app use react-native `0.63.2` ans react-reanimated `^2.0.0-alpha.7`
The app freeze after a lot of toggling animation.

I don't know how to help 😕.

**Comment by JB-CHAUVIN** [comment]
> @jpudysz when the app is frozen hit the pause button in Xcode. Then show us your callstack. I might have experienced something similar, I always thought it was the navigation library's fault 🤔

Here is my stacktrace for the same problem :
`libsystem_kernel.dylib`semaphore_wait_trap:
    0x11c7c5e2c <+0>:  movq   %rcx, %r10
    0x11c7c5e2f <+3>:  movl   $0x1000024, %eax          ; imm = 0x1000024 
    0x11c7c5e34 <+8>:  syscall 
->  0x11c7c5e36 <+10>: retq   
    0x11c7c5e37 <+11>: nop    
`

I am using the latest version from the master branch (last COMMIT : https://github.com/software-mansion/react-native-reanimated/commit/ec5b3be4db62cc1f1b7c51bd251c81fd92d6dd97)

**Comment by JB-CHAUVIN** [comment]
If I replace in the file REANodesManager.m line 228 : 
`dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);`

By : 
`dispatch_semaphore_signal(semaphore);`

It is working ! 

Is it bad ? Will it hurts my iPhone memory ? Can it break react-native-reanimated ?
What do you think about it @Szymon20000 @jpudysz @mrousavy ?

Thanks for the reply,
I hope we will find a solution...

**Comment by drewandre** [comment]
Looking forward to a solution for this as well. Unfortunately the freezing I've been experiencing in v2.0.0-alpha.7 is also mostly random, but for me it doesn't necessarily occur when navigating. I do have react-navigation installed but all the freezing occurs on the home screen when I have a somewhat complex animation running. In a separate project, navigating while animating (using a portal to animate an image to a new screen) almost always freezes the UI on v2.0.0-alpha.7 and I had to downgrade to v2.0.0-alpha-6.1 to fix this.

The one interaction I have that 100% always causes a full frozen UI (with no logs, crashes or anything) is when I scroll and then animate the layout of the scroll container. I'm happy to share this code, though it's a large project. I can try to slim it down in an example repo if anyone would like that.

**Comment by Szymon20000** [comment]
We are almost sure what is causing the problem. We are working on it and should be solved soon.

**Comment by Alexandredc** [comment]
With `^2.0.0-alpha.8`, it works great on my app which had this issue on beta `^2.0.0-alpha.7`.
Thanks for your awesome work ! 🎉

**Comment by mrousavy** [comment]
same, nice job @Szymon20000  👍🎉

**Comment by kanelloc** [comment]
Got the same error after updating xcode to version 13. Any ideas?

**Comment by 592da** [comment]
Same as @kanelloc ,

xcode 13
RN 0.66
Reanimated 2.3.0-beta.2

?
