### ISSUE TITLE
Reloading Via React Native Debug Menu Causes Crash

### ISSUE THREAD

**Issue by ksitko** [software-mansion/react-native-reanimated#1285]
## Description

Hi, I'm using Reanimated V2 with a Expo Bare workflow app. Attempting to do a full reload in either iOS sim or Device causes a crash with a `com.facebook.react.JavaScript (13): signal SIGABRT` error in JSCRuntime::~JSCRuntime. Fast refresh does not cause a similar issue.

### Screenshots
<img width="1445" alt="Screen Shot 2020-09-26 at 2 26 09 PM" src="https://user-images.githubusercontent.com/13754630/94347752-d6e2f780-0004-11eb-90bd-a87538076ae9.png">

## Steps To Reproduce

Enable Turbomodules in ejected Bare workflow expo app and follow Reanimated V2 documentation to change AppDelegate.mm, load app, refresh using RN Debug Menu.

### Expected behavior

Normal refresh.

### Actual behavior

Crash

## Snack or minimal code example

The bug is in Bare work and I don't think Snacks support v2 yet.

## Package versions

`"react-native-reanimated": "2.0.0-alpha.6"`
```
Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    Expo Workflow: bare
```

**Comment by ksitko** [comment]
Resolved by #1256

**Comment by ksitko** [comment]
So while #1256 seems to fix it outside of expo, it seems to be incompatible with expo as it will freeze on animation. Furthermore in a bare expo environment using `"2.0.0-alpha.6.1"` still causes refresh crashes. Is there any fix to this?

**Comment by terrysahaidak** [comment]
Of you use bare workflow, I think you can try to just upgrade to the latest version, because you now have access to the native code and can change it (upgrade it).

**Comment by ksitko** [comment]
Unfortunately, that isn't the solution as my animations completely freeze the app in `2.0.0-alpha.7`, whereas they would work in `2.0.0-alpha.6.1` There are no xcode errors or react native errors that appear. The animation starts and then app just freezes.

**Comment by terrysahaidak** [comment]
Could you create a repro for this freeze case?

**Comment by ksitko** [comment]
Sure, I'll get back to you with that.

**Comment by Szymon20000** [comment]
@ksitko It would be awsome to have repro for app freezing. I've been trying to reproduce it for a long time. We are almost sure what is the root cause of the issue but we can't test it without a repro.

**Comment by ksitko** [comment]
@Szymon20000 @terrysahaidak [I have reproduced the issue](https://github.com/ksitko/rn2-freeze). It occurs when scrolling mid animation.
