### ISSUE TITLE
Complex Animation value is not available on init (JS thread)

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1290]
## Description

The following code snippets.

```
const animation = useSharedValue({ x: 0 });
const style = useAnimatedStyle(() => {
 console.log(animation.value);
  return {};
});
```

logs

```
undefined
{ x: 0}
```

**Comment by karol-bisztyga** [comment]
Hey @wcandillon I ran your example on both ios and android and received result `{x: 0}` in both cases. What platform and packages versions do you use?

**Comment by wcandillon** [comment]
I'm running RN 0.62 could that be the issue?

**Comment by karol-bisztyga** [comment]
I run with rn 62 on both platforms and it worked ok

**Comment by karol-bisztyga** [comment]
@wcandillon could you provide some more information regarding this?

**Comment by karol-bisztyga** [comment]
@wcandillon any update?

**Comment by wcandillon** [comment]
yes this issue is still active on my sode and I will provide a more
detailled bug report asap.

**Comment by karol-bisztyga** [comment]
Great, thank you 🙌

**Comment by wcandillon** [comment]
Thanks for following up on this. When investigating a bit further, I realized that my issue was completely unrelated. On my setup the spread operator nor the Object.assign is available. Is it expected? (alpha7, 0.63.3)

**Comment by terrysahaidak** [comment]
Yeah, it's in limitations. Prototype of object when you make it remote doesn't work.
