### ISSUE TITLE
withTiming callback unknown error

### ISSUE THREAD

**Issue by caiphaav** [software-mansion/react-native-reanimated#1294]
## Description
I'm want to dismiss overlay  when the animation is complete, but app crash when provide withTiming callback function. Maybe I do something wrong?

### Screenshots
[
![Screenshot_1601389869](https://user-images.githubusercontent.com/53155258/94573074-66451080-027a-11eb-9ee1-c0859dd15bcc.png)
](url)

## Snack or minimal code example

```
import React, { useEffect } from 'react';
import { View, StyleSheet } from 'react-native';
import { Colors, Spacing } from '@styles';
import Animated, {
    useAnimatedStyle,
    useSharedValue,
    withTiming,
    useDerivedValue,
} from 'react-native-reanimated';
import { Navigation } from 'react-native-navigation';

export const Toast = function ({ componentId }) {
    const progress = useSharedValue(-1);
    const translateY = useDerivedValue(() => {
        return progress.value * 130;
    });
    const animatedStyles = useAnimatedStyle(() => {
        if (progress.value == 0) {
            progress.value = withTiming(-1, null, (isFinished) => {
                if (isFinished) {
                    Navigation.dismissOverlay(componentId);
                }
            });
        }
        return {
            transform: [{ translateY: translateY.value }],
        };
    });
    useEffect(() => {
        progress.value = withTiming(0);
    }, []);
    return (
        <View style={styles.root}>
            <Animated.View style={[styles.toast, animatedStyles]} />
        </View>
    );
};

const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor:Colors.BLACK,
        paddingHorizontal: Spacing.SPACING_LG,
    },
    toast: {
        height: 130,
        width: '100%',
        borderRadius: Spacing.SPACING_SM,
        backgroundColor: Colors.GRAY_DARK,
    },
});

Toast.options = {
    overlay: {
        interceptTouchOutside: false,
    },
};
```

## Package versions
- React: "16.13.1"
- React Native: "0.63.2"
- React Native Reanimated: "2.0.0-alpha.7"

**Comment by jakub-gonet** [comment]
Could you please wrap your code in the code block? It's hard to read right now.

**Comment by caiphaav** [comment]
> Could you please wrap your code in the code block? It's hard to read right now.

Sorry. I edit my issue and wrap my code in the code block

**Comment by terrysahaidak** [comment]
The second parameter of withTiming should be `undefined`. This might be the case.

But also should not assign any shared values in useAnimatedStyle.

**Comment by karol-bisztyga** [comment]
@terrysahaidak
ad 1 - doesn't matter, can be `undefined` or `null` - both work
ad 2 - true, @caiphaav why don't you try to move this part
```
if (progress.value == 0) {
            progress.value = withTiming(-1, null, (isFinished) => {
                if (isFinished) {
                    Navigation.dismissOverlay(componentId);
                }
            });
        }
```
outside of the `useAnimatedStyle`. This is considered to be a bad practice. Not sure if that would fire this particular error though.

**Comment by caiphaav** [comment]
> @terrysahaidak
> ad 1 - doesn't matter, can be `undefined` or `null` - both work as a passed config object is implicitly converted when checked
> ad 2 - true, @caiphaav why don't you try to move this part
> 
> ```
> if (progress.value == 0) {
>             progress.value = withTiming(-1, null, (isFinished) => {
>                 if (isFinished) {
>                     Navigation.dismissOverlay(componentId);
>                 }
>             });
>         }
> ```
> 
> outside of the `useAnimatedStyle`. This is considered to be a bad practice. Not sure if that would fire this particular error though.

Thank you for your reply. Where I should move this part? To useeffect or another reanimated hook?

**Comment by karol-bisztyga** [comment]
In this case I would consider changing the idea i little bit. You could use `withSequence` for instance.
```
const Toast = function({ componentId }) {
  const progress = useSharedValue(-1);
  const translateY = useDerivedValue(() => {
    return progress.value * 130;
  });
  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateY: translateY.value }],
    };
  });
  useEffect(() => {
    progress.value = withSequence(
      withTiming(0),
      withTiming(
        -1,
        null,
        (isFinished) => {
          if (isFinished) {
            Navigation.dismissOverlay(componentId);
          }
        }
      )
    );
  }, []);
  return (
    <View style={styles.root}>
      <Animated.View style={[styles.toast, animatedStyles]} />
    </View>
  );
};
```
but it does not solve that issue. This call `Navigation.dismissOverlay(componentId);` probably causes problems as you stated in the issue. I'll try to come up with some solution.

**Comment by karol-bisztyga** [comment]
Unfortunaltely I could not reproduce the issue.
@caiphaav do you happen do have a full repo or something like that?

**Comment by caiphaav** [comment]
> Unfortunaltely I could not reproduce the issue.
> @caiphaav do you happen do have a full repo or something like that?

This problem appear when I use this component as react-native-navigation overlay
```
            Navigation.showOverlay({
                component: {
                    name: 'SimpleToast',
                    passProps: {
                        title: 'Log out!',
                    },
                    options: {
                        overlay: { interceptTouchOutside: false },
                    },
                },
            });
```

**Comment by caiphaav** [comment]
> > Unfortunaltely I could not reproduce the issue.
> > @caiphaav do you happen do have a full repo or something like that?
> 
> This problem appear when I use this component as react-native-navigation overlay
> 
> ```
>             Navigation.showOverlay({
>                 component: {
>                     name: 'SimpleToast',
>                     passProps: {
>                         title: 'Log out!',
>                     },
>                     options: {
>                         overlay: { interceptTouchOutside: false },
>                     },
>                 },
>             });
> ```
I only want to show a custom toast that appears and disappears for  some time 
And to remove Toast I must use callback after animations are done

**Comment by terrysahaidak** [comment]
> > > Unfortunaltely I could not reproduce the issue.
> > > @caiphaav do you happen do have a full repo or something like that?
> > 
> > 
> > This problem appear when I use this component as react-native-navigation overlay
> > ```
> >             Navigation.showOverlay({
> >                 component: {
> >                     name: 'SimpleToast',
> >                     passProps: {
> >                         title: 'Log out!',
> >                     },
> >                     options: {
> >                         overlay: { interceptTouchOutside: false },
> >                     },
> >                 },
> >             });
> > ```
> 
> I only want to show a custom toast that appears and disappears for some time
> And to remove Toast I must use callback after animations are done

Could you please create a reproducing repo then?

**Comment by caiphaav** [comment]
> > > > Unfortunaltely I could not reproduce the issue.
> > > > @caiphaav do you happen do have a full repo or something like that?
> > > 
> > > 
> > > This problem appear when I use this component as react-native-navigation overlay
> > > ```
> > >             Navigation.showOverlay({
> > >                 component: {
> > >                     name: 'SimpleToast',
> > >                     passProps: {
> > >                         title: 'Log out!',
> > >                     },
> > >                     options: {
> > >                         overlay: { interceptTouchOutside: false },
> > >                     },
> > >                 },
> > >             });
> > > ```
> > 
> > 
> > I only want to show a custom toast that appears and disappears for some time
> > And to remove Toast I must use callback after animations are done
> 
> Could you please create a reproducing repo then?

Okay. I'm try a little later) I will do my it during the weekend

**Comment by caiphaav** [comment]
@terrysahaidak @karol-bisztyga 
Sorry for a long waiting, guys. Here I reproduced an error:
https://github.com/caiphaav/reanimated2bug

**Comment by karol-bisztyga** [comment]
Hey!
Thanks for the repo :) I managed to get it working using new release https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.8

With `runOnJS` functionality such code works:
```
const dismiss = () => {
    Navigation.dismissOverlay(componentId);
  };
  const animatedStyles = useAnimatedStyle(() => {
    if (progress.value == 0) {
      progress.value = withTiming(-1, null, (isFinished) => {
        if (isFinished) {
          runOnJS(dismiss)();
        }
      });
    }
    return {
      transform: [{translateY: translateY.value}],
    };
  });
```

**Comment by karol-bisztyga** [comment]
Thing is we don't have an access to `this` inside `Navigation.dismissOverlay`. This is because in `runOnJS` we call `Object.defineProperty` so we more or less do something like this:
```
class A {
  foo() {
	//... playing with [this]
  }
}
// ...
const a = new A();
const ob = {}
Object.defineProperty(ob, 'foo', {enumerable: false, value: a.foo}); // we do something like this in runOnJS

a.foo(5); // normal [this] access
ob.foo(5); // [this] is not correct abviously
```

But if you wrap `Navigation.dismissOverlay` in some other function, that wrapper if being assigned via `Object.defineProperty` and `Navigation.dismissOverlay` belongs where it is supposed to.

**Comment by caiphaav** [comment]
@karol-bisztyga big thanks!

**Comment by manas3874** [comment]
But what if we want to pass config on the second parameter?
I want to pass a custom duration
