### ISSUE TITLE
Using custom interpolate function

### ISSUE THREAD

**Issue by sbycrosz** [software-mansion/react-native-reanimated#1302]
## Description

Hi, I wanted to use d3-interpolate-path with reanimated-v2 to make animated charts 

![chart-animation](https://user-images.githubusercontent.com/4867178/94774484-96162480-03f0-11eb-8626-c9a49c7c1bb7.gif)

At the moment, I'm kind of stuck when calling the interpolate function from useAnimatedProps, which I suspect is because d3-interpolate-path is being run on RN thread instead of the UI thread. Is this correct? Is there a way to have external functions run on UI thread instead?

Thanks!

## Code

https://github.com/sbycrosz/reanimated-2-playground/blob/master/Screen.js#L27

```js
import * as Svg from 'react-native-svg';

import Animated, {
  Easing,
  useAnimatedProps,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';
import {Button, View} from 'react-native';

import React, { useState } from 'react';
import { interpolatePath } from 'd3-interpolate-path';

const PATH1 = 'M0,300 L100,100 L200,200 L300,100 L400,140';
const PATH2 = 'M0,300 L100,150 L200,100 L300,200 L400,240';

const interpolator = interpolatePath(PATH1, PATH2);

const AnimatedSvgPath = Animated.createAnimatedComponent(Svg.Path);

export default function AnimatedStyleUpdateExample(props) {
  const progress = useSharedValue(0);

  const animatedProps = useAnimatedProps(() => {
    const path = interpolator(progress.value); // <<<<  path will return undefined here (because it's run on the main thread?)
    return { d: path };
  });

  return (
    <View style={{ flex: 1, alignItems: 'center' }}>
      <Svg.Svg
        style={{ borderWidth: 1 }}
        height={300}
        width={400}>
        <AnimatedSvgPath
          animatedProps={animatedProps}
          strokeWidth={1}
          stroke={'#000'} />
      </Svg.Svg>
      
      <Button
        title="toggle-animated"
        onPress={() => {
          progress.value = withTiming(progress.value ? 0 : 1, {
            duration: 1000,
            easing: Easing.inOut(Easing.cubic),
          })
        }} />
    </View>
  );
}


```

### Package versions

    "react-native": "0.63.1",
    "react-native-reanimated": "2.0.0-alpha.7",
    "react-native-svg": "12.1.0",
    "d3-interpolate-path": "^2.2.1",

**Comment by terrysahaidak** [comment]
Yes, it's because d3 is being run on JS Thread.

Right now there is no way to run external functions on UI Thread.

cc @kmagiera @Szymon20000

**Comment by jakub-gonet** [comment]
We're aware of this issue but for now, it's not possible to run an arbitrary function on the JS thread.

**Comment by terrysahaidak** [comment]
But it is possible to convert that to worklet. But yeah, it's hard.

**Comment by arturz** [comment]
@terrysahaidak Is it possible to easily convert my own pure function to worklet, that for example looks like that:
`fn = (x, y) => x * y `
Or should I have to entirely rewrite this function as a worklet?

(in my case I have a much bigger function that calculates props for <Line /> basing on x, y and length, but it is still a function without any side-effects)

**Comment by haibert** [comment]
Whats the correct way to morph from one SVG Path to another ? Do we need to use the d3-interpolate-path library or its possible to do it with the tools provided with reanimated its self ?

**Comment by sbycrosz** [comment]
Hi @haibert, I managed to add reanimated support to d3-interpolate-path, which you can check out [here](https://github.com/sbycrosz/d3-interpolate-path/tree/feat/react-native-reanimated-support)

Or 

```

**Comment by sbycrosz** [comment]
Hi, you can check out [my WIP branch](https://github.com/sbycrosz/reanimated-2-playground/commits/feat/animated-svg-path). I haven't worked on it for a while but hopefully, it still works.

**Comment by haibert** [comment]
Hello,
I just realized I was not installing your branch. After I install your branch and run I get the following error message

```
While trying to resolve module `d3-interpolate-path` from file `/Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/src/components/animatedNavBarTest/HomeSVG.js`, the package `/Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/build/d3-interpolate-path.js`. Indeed, none of these files exist:

  * /Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/build/d3-interpolate-path.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/build/d3-interpolate-path.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)

InternalError Metro has encountered an error: While trying to resolve module `d3-interpolate-path` from file `/Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/src/components/animatedNavBarTest/HomeSVG.js`, the package `/Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/build/d3-interpolate-path.js`. Indeed, none of these files exist:

  * /Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/build/d3-interpolate-path.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/d3-interpolate-path/build/d3-interpolate-path.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json): /Users/hb/Desktop/EjectEventShare/1EventShare-dev-client/node_modules/metro/src/node-haste/DependencyGraph.js (376:17)
```

**Comment by sbycrosz** [comment]
It's working fine on my machine. Try deleting your node_modules and then reinstalling

**Comment by haibert** [comment]
hmmm, still same error. im doing yarn add sbycrosz/d3-interpolate-path
im using expo, does this make a difference ?

**Comment by sbycrosz** [comment]
I have not tried Expo so I can't comment on that, but did you try [my example repo](https://github.com/sbycrosz/reanimated-2-playground/commits/feat/animated-svg-path)?
