### ISSUE TITLE
Using the hook dependencies

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1303]
## Description

Hi! I see that the hook's dependencies (`deps`) have only been recently added to the types (alpha7). I've added deps on all my hooks to let them memoize correctly, but there appears to be some sort of issue with the gesture handler hooks, since those are complex objects rather than simple "callback" functions.

![Screenshot 2020-10-01 at 10 17 14](https://user-images.githubusercontent.com/15199031/94785003-48d58b00-03cf-11eb-8b91-e0626ed7dd68.png)

Is there any way to use the `deps` right now to memoize the hooks? I assume it makes React re-renders a bit faster, since the worklets don't have to be re-parsed?

Also, the docs don't use `deps` either, I could create a PR for that to fill in the missing `deps` parameter in the code snippets.

### Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.7
- eslint: 7.10.0
- eslint-plugin-react-hooks: 4.1.2

#### `.eslintrc.js`

```js
module.exports = {
  // ...
  rules: {
    // ...
    'react-hooks/exhaustive-deps': [
      'warn',
      {
        additionalHooks: '(useCode|useDerivedValue|useAnimatedStyle|useAnimatedProps|useAnimatedGestureHandler|useAnimatedScrollHandler)',
      },
    ],
    // ...
  }
}
```

**Comment by karol-bisztyga** [comment]
Dependencies for gestures hooks work in similar manner as for the other hooks, those objects just consist of callbacks, so every one of those callbacks is treated like the callbacks passed to other hooks(e.g. useDerivedValue). To force memoization just pass the empty array for the deps `[]` and then only if any of those callbacks' body changes, the hooks reloads.

As for the docs, we're about to add the note about dependencies soon.

**Comment by M2Changezi** [comment]
@karol-bisztyga It just confused me the explanation about dependencies optional object may please discribe it with detail and example code
