### ISSUE TITLE
Recursive worklets for v2

### ISSUE THREAD

**Issue by nicefella** [software-mansion/react-native-reanimated#1306]
Hi, 

In the version 2 documentation, it says:

> Recursive worklets aren’t supported (however there are simple workarounds for this problem
https://docs.swmansion.com/react-native-reanimated/docs/next/about/#known-problems-and-limitations

May i ask what these workarounds are?

Thank you,

### Package versions

- React:
- React Native:
- React Native Reanimated:

**Comment by Szymon20000** [comment]
It's no longer true. We will update the documentation.

**Comment by friedebold** [comment]
Hello,

I have an issue when trying to scroll in my self-made drag&drop lists.

The goal is to manipulate a scrollY value when the dragged item is in a particular area of the screen.
I've tried to implement it directly in `onActive` of `useAnimatedGestureHandler`. However, this just fires when the event values are changed.

2nd try was with a recursive function called once when dragging starts. Sadly, calling `scroller()` recursively throws the error:
_scroller is not a function. (In 'scroller()', 'scroller' is undefined)_

```js
const scroller: () => void = () => {
    'worklet'
    if (isScrolling.value === 0) return
    else {
      console.log('scrolling...')
      return scroller()
    }
}

const gestureHandler = useAnimatedGestureHandler({
    onActive: (event, ctx) => {
      if (isScrolling.value !== 1) {
        isScrolling.value = 1
        scroller()
      }
    }
    onEnd: (_) => {
      isScrolling.value = 0
    }
})
```

Can anyone help?

**Comment by gksander** [comment]
Hi @friedebold - I just experienced this same issue. Changing

```ts
const scroller = () => { ... }
```

to

```ts
function scroller() { ... }
```

seems to resolve the issue for me. You might try that out.

**Comment by wcandillon** [comment]
thanks for the tip @gksander 
Is there a way to make it work for the lambda syntax as well?

**Comment by RemyNtshaykolo** [comment]
> Hi [@friedebold](https://github.com/friedebold) - I just experienced this same issue. Changing
> 
> const scroller = () => { ... }
> to
> 
> function scroller() { ... }
> seems to resolve the issue for me. You might try that out.

Thanks!!
