### ISSUE TITLE
When using v2 with turbo modules, usage of blobs doesn't work across the app (response.blob is not a function)

### ISSUE THREAD

**Issue by idanlo** [software-mansion/react-native-reanimated#1307]
## Description
After installing reanimated v2, some functionality of my app stopped working regarding blobs, and I get errors like `BlobModule is not supported` or `response.blob is not a function` (when trying to fetch and image and calling response.blob() on the response object). After changing in the AppDelegate.mm file from 
```
RCTEnableTurboModule(YES);
```
to 
```
RCTEnableTurboModule(NO);
```
All usage of blobs started working again, and all animations in our app still worked.

## Steps To Reproduce

1. install reanimated v2, 
2. use fetch() with a url that leads to an image file
3. call .blob() on the response object 
4. see error - 
```
TypeError: img.blob is not a function. (In 'img.blob()', 'img.blob' is undefined)
```

### Expected behavior
All native modules should still work (blob module in this case)

### Actual behavior
Error, blob modules seems to not exist

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.7

**Comment by jakub-gonet** [comment]
This is not Reanimated fault, seems like blob native module isn't yet compatible with Turbomodules.

**Comment by idanlo** [comment]
@jakub-gonet Probably. But I am saying that after I disabled turbo modules the animations still worked. Does this mean I can use reanimated v2 without turbo modules enabled?

**Comment by jakub-gonet** [comment]
Have you cleared the cache (metro, watchman, Gradle)? I'd be very surprised if it worked after doing that.

**Comment by idanlo** [comment]
Yeah. I'm also running it on a fresh install on my phone on TestFlight.

**Comment by jakub-gonet** [comment]
Huh, that's very strange, could you provide some minimal repro so I can test that too?

**Comment by terrysahaidak** [comment]
There is a patch in Rainbow 🌈 repo where they enable TurboModules only for Reanimated. This might help.

**Comment by osdnk** [comment]
Oh it's me

**Comment by idanlo** [comment]
Yeah I would love to get guidance on that if possible @osdnk

**Comment by osdnk** [comment]
Instead of RCT_ENABLE_TURBO_MODULES, I patched RN with this line:

https://github.com/rainbow-me/rainbow/blob/ef980afff0eabd066f0a30355f99887542f4654c/patches/react-native%2B0.63.2.patch#L41

**Comment by idanlo** [comment]
@osdnk so you deleted the 'RCTEnableTurboModule' function call?

**Comment by osdnk** [comment]
Yes, I did

**Comment by osdnk** [comment]
I don't need all advantages of the new architecture now and observed a ton of regressions I didn't have time to pay attention to

**Comment by idanlo** [comment]
@osdnk Thank you! I will try this out and let you know if I'm having any problems. I appreciate it 🙏🏻.

I kinda have to do this because this messed up blob usage for me for some reason. I'll enable it every now and then to see if blob support is added. It's pretty weird I didn't see any issues about this, I'm guessing blobs are used for a lot of file related stuff

**Comment by osdnk** [comment]
I don't know if my approach is correct, but we shipped it. Maybe just not too many users use reanimated 2 on prod? E.g we we had a lot of problems with Animated module in TM version. Maybe it's something worth mentioning in docs, @jakub-gonet?
