### ISSUE TITLE
Missing architectures for Android on daily npm builds

### ISSUE THREAD

**Issue by brunobar79** [software-mansion/react-native-reanimated#1321]
## Description

I was having trouble to get reanimated 2 working on my devices (sim works fine) when using the binares from `https://github.com/software-mansion/react-native-reanimated/actions?query=workflow%3A%22Build+npm+package%22`

After some debugging I realized that the generated .aar files only contain the x86 architecture.

I think this would be a nice to have for early users to try master on their apps without having to build from source which has no docs and takes a decent amount of time.

From what I can tell this has to do with the config of the CI machine that's building it, since the same command `./createNPMPackage.sh` generated all the archs. as expected in my own computer.

### Screenshots

AAR files built on CI via github actions:

![Screen Shot 2020-10-07 at 10 37 24 AM](https://user-images.githubusercontent.com/1247834/95351433-36f05e00-088f-11eb-9099-db6596a30e0b.png)

AAR files from npm package:
![Screen Shot 2020-10-07 at 10 40 49 AM](https://user-images.githubusercontent.com/1247834/95351507-4bccf180-088f-11eb-8d74-c64fb71136c7.png)

## Steps To Reproduce

1. Download the binaries from github actions
2. Inspect them using android studio

### Expected behavior

AAR files should contain all the architectures

### Actual behavior

AAR files only contain x86 architectures

## Package versions

- React: 16.11.0
- React Native: 0.63.2
- React Native Reanimated: 2.0-alpha-7

**Comment by jakub-gonet** [comment]
That's strange, I vaguely remember unsetting `CI` env variable inside script (which if set, builds only x86). Will fix shortly.
