### ISSUE TITLE
Problem with animation toogle block

### ISSUE THREAD

**Issue by VictorPullzz** [software-mansion/react-native-reanimated#1333]
## Description

Hi guys! I am trying to animate block switching. I am creating a FadeAnimation component so that it animates the horizontal switching of blocks. When I made it based on Reanimated 2 everything worked well. BUT. The application was not built for android, I rolled back to the 1st version and does't work :(

## Code

```js
// Fade component
export const FadeAnimation = ({ visibility = false, children }: IFadeAnimationProps) => {
	const show = new Animated.Value(visibility ? 1 : 0);

	const translateX = interpolate(show, {
		inputRange: [0, 1],
		outputRange: [100, 0],
		extrapolate: Extrapolate.CLAMP
	});

	const opacity = interpolate(show, {
		inputRange: [0, 1],
		outputRange: [0, 1],
		extrapolate: Extrapolate.CLAMP
	});

	return (
		<Animated.View
			style={{
				opacity,
				transform: [{
					translateX
				}],
			}}
		>
			{visibility ? children : null}
		</Animated.View>
	);
};

// Another component
<FadeAnimation visibility={step === 0}>
	<Box flex={1} width={SIZE_SLIDE}>
	     <FirstStep {...{ scrollToTop }}/>
	</Box>
</FadeAnimation>
```
-->

### Package versions
- React: 16.13.1
- React Native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz
- React Native Reanimated: ~1.9.0

**Comment by terrysahaidak** [comment]
If you want to reuse animated value between rerenders consider wrapping ith with useMemo.

**Comment by VictorPullzz** [comment]
@terrysahaidak Could you show me how to do it? 
I understand how useMemo works, I don't understand how to combine it with reanimated ...

**Comment by VictorPullzz** [comment]
I tried something like this:
```
const { animation } = useMemo(
		() => ({
			animation: new Value(visibility ? 1 : 0),
		}),
		[]
	);

	return (
		<Animated.View
			style={{
				opacity: animation.interpolate({
					inputRange: [0, 1],
					outputRange: [0, 1],
				}),
				transform: [{
					translateX: animation.interpolate({
						inputRange: [0, 1],
						outputRange: [100, 0],
					})
				}],
			}}
		>
			{visibility ? children : null}
		</Animated.View>
	);
```
But  but when i switch between steps i just get white screen:

```
<Box flex={1} paddingBottom={'m'}>
							{
								<FadeAnimation visibility={step === 0}>
									<Box flex={1} width={SIZE_SLIDE}>
										<FirstStep {...{ scrollToTop }}/>
									</Box>
								</FadeAnimation>
							}
							{
								<FadeAnimation visibility={step === 1}>
									<Box flex={1} width={SIZE_SLIDE}>
										<SecondStep/>
									</Box>
								</FadeAnimation>
							}
						</Box>
```

**Comment by terrysahaidak** [comment]
```
const animatedValue = useMemo(() => new Animated.Value(0),  [])
```

**Comment by VictorPullzz** [comment]
> I tried something like this:
> 
> ```
> const { animation } = useMemo(
> 		() => ({
> 			animation: new Value(visibility ? 1 : 0),
> 		}),
> 		[]
> 	);
> 
> 	return (
> 		<Animated.View
> 			style={{
> 				opacity: animation.interpolate({
> 					inputRange: [0, 1],
> 					outputRange: [0, 1],
> 				}),
> 				transform: [{
> 					translateX: animation.interpolate({
> 						inputRange: [0, 1],
> 						outputRange: [100, 0],
> 					})
> 				}],
> 			}}
> 		>
> 			{visibility ? children : null}
> 		</Animated.View>
> 	);
> ```
> 
> But but when i switch between steps i just get white screen:
> 
> ```
> <Box flex={1} paddingBottom={'m'}>
> 	{
> 		<FadeAnimation visibility={step === 0}>
> 			<Box flex={1} width={SIZE_SLIDE}>
> 				<FirstStep {...{ scrollToTop }}/>
> 			</Box>
> 		</FadeAnimation>
> 	}
> 	{
> 		<FadeAnimation visibility={step === 1}>
> 			<Box flex={1} width={SIZE_SLIDE}>
> 				<SecondStep/>
> 			</Box>
> 		</FadeAnimation>
> 	}
> </Box>
> ```

@terrysahaidak  Also, I tried this, tabs are switched, but there is no animation ...
```
const animatedValue = useMemo(() => new Animated.Value(visibility ? 1 : 0), []);

useEffect(() => {
	animatedValue.setValue(visibility ? 1 : 0);
}, [visibility]);

return (
	<Animated.View
		style={{
			opacity: interpolate(animatedValue, {
				inputRange: [0, 1],
				outputRange: [0, 1],
				extrapolate: Extrapolate.CLAMP,
			}),
			transform: [{
				translateX: interpolate(animatedValue, {
					inputRange: [0, 1],
					outputRange: [100, 0],
					extrapolate: Extrapolate.CLAMP,
				})
			}],
		}}
	>
		{visibility ? children : null}
	</Animated.View>
);
```

**Comment by VictorPullzz** [comment]
Does anyone know what the problem is?

**Comment by jakub-gonet** [comment]
You use `interpolate` which maps [0,1] to [0,1] in opacity. It won't animate, because you only switch between 0 and 1, so interpolate will return edge values only. You probably want to use [`timing`](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/animations/timing) to animate that.

**Comment by VictorPullzz** [comment]
@jakub-gonet I check this function, but it is not very clear how this should work, 
can you please write an example?)
