### ISSUE TITLE
Error when using useAnimatedStyle

### ISSUE THREAD

**Issue by trigun539** [software-mansion/react-native-reanimated#1335]
## Description
Testing out the example for animations here: https://docs.swmansion.com/react-native-reanimated/docs/animations But getting error in the screenshot. Also, tried other different ways to but as soon as useAnimatedStyle is used, get this error.

### Screenshots

![image](https://user-images.githubusercontent.com/508205/95662701-eedb7080-0b06-11eb-84fc-2b960cb8d1de.png)

## Steps To Reproduce

1. React native project
2. Install reanimated
3. Test an example that uses useAnimatedStyle

### Expected behavior

Should work as the example says it would.

### Actual behavior

Error thrown:
```
Unhandled JS Exception: undefined is not an object (evaluating 'Object.keys(oldStyle)')

keys@[native code]
styleDiff@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:185624:16
styleUpdater@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:185715:25
fun@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:185752:21

styleDiff
    index.bundle?platform=ios&dev=true&minify=false:185624:16
styleUpdater
    index.bundle?platform=ios&dev=true&minify=false:185715:25
fun
    index.bundle?platform=ios&dev=true&minify=false:185752:21
```

## Snack or minimal code example

```javascript
import React from 'react'
import { StyleSheet, Button } from 'react-native'
import Animated, {
  useSharedValue,
  useAnimatedStyle
} from 'react-native-reanimated'
import styled, { css } from 'styled-components'

const styles = StyleSheet.create({
  box: {
    backgroundColor: 'blue',
    borderRadius: 5,
    width: 20,
    height: 20
  }
})

const Box = () => {
  const offset = useSharedValue(0)

  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: offset.value * 255 }]
    }
  })

  return (
    <>
      <Animated.View style={[styles.box, animatedStyles]} />
      <Button onPress={() => (offset.value = Math.random())} title="Move" />
    </>
  )
}

export default Box
```

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.7
- NodeJS: 12.18.1

**Comment by terrysahaidak** [comment]
Did this happen after upgrading Reanimated?

Did you use Reanimated babel plugin? Make sure to run packager with reset cache flag.

**Comment by trigun539** [comment]
@terrysahaidak Run it with the reset cache and seems to be working now. Thanks!
