### ISSUE TITLE
Error in build android

### ISSUE THREAD

**Issue by VictorPullzz** [software-mansion/react-native-reanimated#1336]
## Description
Hi guys, I tryed build app on android with reanimated 2,  but unfortunately the build broke. I looked in android studio there was such an error:
ReactNativeJS: Running "main" with {"initialProps":{"exp":{"lastErrors":[{"isFatal":true,"errorMessage":"Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

## Steps To Reproduce

1. Install reanimated 2
2. Use.
3. Run command expo build:android
4. Tryed install on android phone

## Package versions
- React: 
- React Native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz
- React Native Reanimated: ^2.0.0-alpha.6
- NodeJS:

**Comment by coditza** [comment]
Same here, only that I'm using "react-native init" and "react-native run-android"

**Comment by drewandre** [comment]
@VictorPullzz are you sure you followed the android-specific installation instructions? Unfortunately you can't just `npm i react-native-reanimated@v2.0.0-alpha.6` yet. There are platform-specific installation requirement for [iOS](https://docs.swmansion.com/react-native-reanimated/docs/installation/#ios) and for [Android](https://docs.swmansion.com/react-native-reanimated/docs/installation/#android). You also need to add a [babel plugin](https://docs.swmansion.com/react-native-reanimated/docs/installation/#babel-plugin). If your build still doesn't work after that, maybe try building the [reanimated v2 playground repo](https://github.com/software-mansion-labs/reanimated-2-playground) (which is current at v2.0.0-alpha.7) to eliminate the possibility of it being an issue with your local environment.

**Comment by VictorPullzz** [comment]
@drewandre Hi, thanks for answer! Yes I follow instruction for expo. 
1 - yarn add react-native-reanimated@alpha
2 - added to babel.confi.js this  ```plugins: ['react-native-reanimated/plugin'],```

**Comment by jakub-gonet** [comment]
You also have to update your app.json to enable turbomodules:
```json
{
  "expo": {
    "experiments": {
      "turboModules": true
    }
  }
}
```

**Comment by Shing-Ho** [comment]
@jakub-gonet after I add it I am getting an error in metro bundler
```
• Field: experiments - should NOT have additional property 'turboModules'.
```

**Comment by jakub-gonet** [comment]
Are you using expo version with reanimated? It's supported since sdk 29.

**Comment by Shing-Ho** [comment]
I upgraded the expo version from 28 to 29 and was having "Operator 'abs' not found" error.
So I thought this is reanimated error so I upgraded version to alpha. And now I was having that error as well as with the 
`Turbomoduleregistry.getenforced` error

**Comment by jakub-gonet** [comment]
> was having "Operator 'abs' not found" error
AFAIK we replaced `abs` file with native implementation, so you may have a stale cache. Try running metro with `--reset-cache` flag

**Comment by Shing-Ho** [comment]
Thank you for reply.
Here's my overview:
v1.9: It's showing the app but when I click the textInput it's showing the `No command found with name "focus"`
v1.13.0: It's showing `Operator 'abs' not found` metro error
v2.0.0-alpha.6.1: It's showing `TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found.; Verify that a module by this name is registered in the native binary.`
Do you have any idea?

**Comment by jakub-gonet** [comment]
Can't really help without code examples, where's the `No command found with name "focus"` coming from?

TBH I'd try clearing cache and node_modules & reinstalling all installed modules via `expo install` (yarn/npm doesn't work with Expo IIRC)

**Comment by Shing-Ho** [comment]
!error[https://i.ibb.co/PtBcbCs/Screen-Shot-2020-11-18-at-4-58-03-AM.png]
Did you see this error before?

**Comment by jakub-gonet** [comment]
Yup, it's coming from the fact that RN couldn't find turbo modules for various reasons - most likely the cache is stale, the app's native code was not configured properly or we have a bug somewhere :smile:. I didn't see `No command found with name "focus"` though.

**Comment by Shing-Ho** [comment]
How can I clean the cache? I used to run the app using `expo start -- -c` and also I just tried `yarn cache clean` but it's still not working
