### ISSUE TITLE
Fix crash in expo standalone installation

### ISSUE THREAD

**Issue by kmagiera** [software-mansion/react-native-reanimated#1339]
Original report here: https://github.com/expo/expo/issues/10564

(Making a copy of this in reanimated repo so that we can track this on our project board)

**Comment by hosseinmd** [comment]
I have react-native-web project with reanimated v1, I tried to migrate to v2 but I got many bugs.
Seems web not supported yet.

**Comment by terrysahaidak** [comment]
Web is supported and most of the things should work. Could you please open separate issue for each bug with repro for it? In that case we can fix them.

**Comment by hosseinmd** [comment]
- (https://github.com/software-mansion/react-native-reanimated/issues/1377)
- (https://github.com/software-mansion/react-native-reanimated/issues/1364)

**Comment by sjchmiela** [comment]
Fixed in https://github.com/expo/expo/commit/c1deee4b2ed575b206a9d043b0b664c6e82f7702. 🙂

**Comment by jakub-gonet** [comment]
Closing then.
