### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by billel-boudchicha** [software-mansion/react-native-reanimated#1340]
## Description

I added RNN to an existing project
Error when building the app

`'RNReanimated/RETurboModuleProvider.h' file not found`

### Screenshots
<img width="1440" alt="Screenshot 2020-10-12 at 14 30 56" src="https://user-images.githubusercontent.com/8265063/95752307-bb7c1b80-0c97-11eb-964d-9f2ee445f82f.png">

## Steps To Reproduce

1.

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.7
- NodeJS: 12.16.3

**Comment by drewandre** [comment]
@billel-boudchicha take a look at the [2.0.0-alpha.6 release notes](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.6) -- these methods have been renamed.

**Comment by robrecord** [comment]
Please update the diff to reflect this.
https://github.com/software-mansion-labs/reanimated-2-playground/pull/8

**Comment by JanKaifer** [comment]
Hi, just came across this.

Your docs need to be updated too: https://www.reanimated2.com/docs/next/installation

**Comment by JanKaifer** [comment]
For anyone following docs here: https://www.reanimated2.com/docs/next/installation

They are **old** and **not working**.
For up-to-date docs go here: https://www.reanimated2.com/docs/next/installation

Just spent few hours figuring out why Xcode can't find `RNReanimated/RETurboModuleProvider` or `RNReanimated/REATurboModuleProvider`.

**Comment by KevinColemanInc** [comment]
@JanKaifer  up-to-date docs don't work either :'( (dead link).

**Comment by JanKaifer** [comment]
@KevinColemanInc
Try this one: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation

Probably just moved there.
