### ISSUE TITLE
Using useAnimatedStyle with contentContainerStyle inside Animated.ScrollView

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#1341]
## Description

I want to update the height of my ScrollView when adding an item but I keep getting `Property is not configurable`.
What is the correct way to pass this value ?

## Code

```js
const height = useDerivedValue(() => {
    return items.length * 200
}, [items])

const style = useAnimatedStyle(() => ({
    height: height.value
}))

return <Animated.ScrollView contentContainerStyle={[style]}> ... </Animated.ScrollView>
```

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.7

**Comment by terrysahaidak** [comment]
You should use useAnimatedProps. It's the same as useAnimatedStyle, but instead of styles you should return object with props.

Then you should pass it to the animated component as animatedProps property.

**Comment by Andarius** [comment]
Hey @terrysahaidak, I tried that already but it does not work, the app crashes immediately when passing a derived value

```
    const totalHeight = useDerivedValue(() => {
        return items.length * 200
    }, [items])

    const totalHeight2 = useSharedValue(400)

    const animatedProps = useAnimatedProps(() => ({
        contentContainerStyle: {
            height: totalHeight2.value
        }
    }))
```

Passing `totalHeight2` works but not `totalHeight` to 

```
<Animated.ScrollView animatedProps={animatedProps}>
```

**Comment by terrysahaidak** [comment]
Oh, I guess this won't work, I didn't read carefully your description, sorry.

The contentContainerStyle is a prop that is passing to the underlying view that wraps the content of Scroll view. That view is not animated - that's why you can't pass animated styles to it. But you can create your own container - just wrap the children of the ScrollView with your own animated view.

**Comment by terrysahaidak** [comment]
But overall this approach I see in your code doesn't have any advantages over just regular inline styles, even can be slover, because passing items to derived value dependencies will force it to recreate that derived value on each change. This will happen on JS Thread. And only when it's done - it will run the style change on UI Thread.

With inline styles it will do it on the render of items.

**Comment by Andarius** [comment]
The issue with inline style (it's what I'm using for now), is that for my use case the height of an item can change.
So it's a bit more complex, and if the ainmated height changes it won't trigger a re-render.

**Comment by Andarius** [comment]
Ok it works ! Thanks

![video](https://user-images.githubusercontent.com/5070712/95837573-069e3900-0d41-11eb-9631-05169fff8877.gif)

Side question: I tried using the `for(const x of items)` inside useDerivedValue but it crashes. Is it expected (because of Hermes ) ? Thanks again

**Comment by terrysahaidak** [comment]
seems like it's related to the limitations of capturing object to be used on UI Thread. It doesn't capture prototype property which causes iterations on these objects to not work.

**Comment by thisisgit** [comment]
Hi @terrysahaidak , I believe one of the reasons why people choose `contentContainerStyle` over separate child `View` as a container is to use `stickyHeaderIndices` property. Is there any known workaround to use `stickyHeaderIndices` property while using separate child container `Animated.View`?

**Comment by Omelyan** [comment]
> I believe one of the reasons why people choose `contentContainerStyle` over separate child `View` as a container is to use `stickyHeaderIndices` property
One of the reasons people choose "contentContainerStyle" is because this prop is the only right choice for some stylings of FlatList, for example. In case of ScrollView you just may use your own animated content wrapper (Animated.View) and do whatever you want, but it's surprisingly annoying that Reanimated declares Animated.FlatList which can't deal with "contentContainerStyle".
In many cases we want animate exactly the "contentContainerStyle" (of FlatList), not the "style"...

**Comment by Omelyan** [comment]
But here's a solution. FlatList "is" a "VirtualizedList", which in turn "is" a "ScrollView", which in nitty gritty details is RN' "ScrollContentViewNativeComponent". So, you can replace (patch) the last one with createAnimatedComponent(ScrollContentViewNativeComponent) and it will work well (in both Android and iOS) with animated "contentContainerStyle" prop and that's it! :)

**Comment by Morteyy** [comment]
> But here's a solution. `FlatList` "is" a `VirtualizedList`, which in turn "is" a `ScrollView`, which in nitty gritty details is RN' `ScrollContentViewNativeComponent`. So, you can replace (patch) the last one with `createAnimatedComponent(ScrollContentViewNativeComponent)`, drill it an animated `contentContainerStyle` prop from your FlatList or ScrollView, and that will work well (in both Android and iOS). That's it! :)

Hey, do you have a current method or idea? Unfortunately, your method doesn't work, or rather I can't get it to work. 
Thank you!

**Comment by Morteyy** [comment]
> But here's a solution. `FlatList` "is" a `VirtualizedList`, which in turn "is" a `ScrollView`, which in nitty gritty details is RN' `ScrollContentViewNativeComponent`. So, you can replace (patch) the last one with `createAnimatedComponent(ScrollContentViewNativeComponent)`, drill it an animated `contentContainerStyle` prop from your FlatList or ScrollView, and that will work well (in both Android and iOS). That's it! :)

Hey, do you have an actual method to use AnimatedStyle in contentContainerStyle of a Flatlist? I have tried your method, but unfortunately it doesn't work for me, or rather I can't get it to work.
Thank you!

**Comment by rb3198** [comment]
@Morteyy can you share your code? `contentContainerStyle` defined inside `useAnimatedProps` does not give me errors but the style is not being applied at all.

**Comment by Morteyy** [comment]
> @Morteyy can you please share your code? `contentContainerStyle` defined inside `useAnimatedProps` does not give me errors but the style is not being applied at all. Thanks!

Hey, I actually ended up using the animatedprop only in my ScrollView, but found a solution for the Flatlist for my use case anyway.

### For the ScrollView, I defined an Animated Prop like this:
![grafik](https://github.com/software-mansion/react-native-reanimated/assets/62238541/7325f099-2ea8-4013-bcb3-f2855b96136c)

And then I just put it as an animatedProp for my ScrollView.
![grafik](https://github.com/software-mansion/react-native-reanimated/assets/62238541/5045ca62-7104-466e-a7a9-b9cfa4a6f0ed)


### For my Flatlist I just used an Animated Variable (interpolate) for my case and added it in ContentContainerStyle like this:
Animated Style didn't work, but defining the prop I wanted (in this case: PaddingTop) and then using it in ContentContainerStyle worked.
![grafik](https://github.com/software-mansion/react-native-reanimated/assets/62238541/8a470d2f-beac-4c6d-b397-96ae1aed2515)
![grafik](https://github.com/software-mansion/react-native-reanimated/assets/62238541/59863298-806e-41c9-9d2b-919b38f49c53)

**Comment by kirillzyusko** [comment]
If you need to use FlatList and its `contentContainerStyle` property, then you can pass custom Scroll component:

```tsx
const CustomScrollContainer = forwardRef<ScrollView, ScrollViewProps>(
  ({children, contentContainerStyle, ...rest}, ref) => {
    return (
      <ScrollView {...rest} ref={ref}>
        <Reanimated.View style={[styles.horizontal, contentContainerStyle]}>
          {children}
        </Reanimated.View>
      </ScrollView>
    );
  }
);

// ...

  const contentContainerStyle = useAnimatedStyle(() => ({
    transform: [{translateX: -offset.value}],
  }), []);

return (
  <FlatList
    contentContainerStyle={contentContainerStyle}
    renderScrollComponent={(props) => <CustomScrollContainer {...props} />}
```
