### ISSUE TITLE
Missing declaration file for react-native-reanimated/mock

### ISSUE THREAD

**Issue by Thanaen** [software-mansion/react-native-reanimated#1352]
## Description

Hello,
I'm trying to create a mock of your library by creating a folder "__mocks__", and putting a "react-native-reanimated.ts" file in it.
In this file there is the following line:
`export { default } from 'react-native-reanimated/mock';`

Except TypeScript displays an error:  

> Could not find a declaration file for module 'react-native-reanimated/mock'. 'c:/Divers/Projets/UserLockPush/node_modules/react-native-reanimated/mock.js' implicitly has an 'any' type.
>   Try `npm install @types/react-native-reanimated` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-reanimated/mock';`ts(7016)

I tried in a "custom.d.ts" file to add a line `declare module "react-native-reanimated/mock"` , but for some mysterious reason, it breaks the module auto import of TypeScript and VS Code.

I think it's easy to find a temporary solution, so it's not a big deal. But I prefer to let you know!

## Steps To Reproduce
In a React Native + TypeScript project (optionally, using VS Code): 

1. Add the following line in a file: `export { default } from 'react-native-reanimated/mock';`

### Expected behavior

TypeScript doesn't complain.

### Actual behavior

TypeScript shows this error: 
> Could not find a declaration file for module 'react-native-reanimated/mock'. 'c:/Divers/Projets/UserLockPush/node_modules/react-native-reanimated/mock.js' implicitly has an 'any' type.
>   Try `npm install @types/react-native-reanimated` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-reanimated/mock';`ts(7016)

## Package versions

- React: 16.14.0
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.7
- NodeJS: x
- TypeScript: 4.0.3

Thank you for reading, and for you work. =)

**Comment by jkadamczyk** [comment]
Hi @Thanaen 
Thanks for submitting an issue, if I understand it correctly, our mocks do not support typescript, they are not typed and it is what is causing you issues. I marked the issue as a feature request, and I hope we will get to it sometime soon.

If you already found a way to work around it to implemented typings yourself by any chance, I encourage you to submit a pull request to help others use your solutions.

Thanks you again and have a good day 😊
