### ISSUE TITLE
Repeat functions is named differently in the documentation

### ISSUE THREAD

**Issue by robertreich306** [software-mansion/react-native-reanimated#1353]
## Description

After scratching my head, trying to use the withRepeat function as described here. [Doc](https://docs.swmansion.com/react-native-reanimated/docs/api/withRepeat) I figured out through go-to-definition, that the function was renamed to `repeat`. 

### Screenshots

<img width="826" alt="Screenshot 2020-10-18 at 15 07 51" src="https://user-images.githubusercontent.com/72611014/96368358-bd405600-1153-11eb-8939-dc6538f370f0.png">

## Steps To Reproduce

1. Install the library via yarn and get version 2.0.0-alpha-7.
2. Try to import withRepeat `import { withRepeat } from 'react-native-reanimated'`.

### Expected behavior

Function imported

### Actual behavior

IDE throws a lint error.

## Snack or minimal code example

```
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  Easing,
  withTiming,
  repeat,
  useAnimatedProps,
  withRepeat
} from 'react-native-reanimated';
```

## Package versions

- React: ^16.13.1
- React Native: ^0.63.3
- React Native Reanimated: ^2.0.0-alpha.7
- NodeJS: 12 LTS

PS: My enormous thanks to the individuals who have dedicated time and effort to this library.

**Comment by terrysahaidak** [comment]
It's the opposite. It has been renamed to withRepeat, but the documentstion was regenerated after that change.

**Comment by robertreich306** [comment]
I moved a bit on, and I noticed that the function didnt have matching argument type definition in the .d.ts file with the .js definition, as shown here:

<img width="570" alt="Screenshot 2020-10-18 at 15 33 58" src="https://user-images.githubusercontent.com/72611014/96368978-718fab80-1157-11eb-9a14-a769c4f7ba0a.png">

The yellow is one that I added.

**Comment by robertreich306** [comment]
@terrysahaidak So it's just pending the next update? I see. Thx

**Comment by terrysahaidak** [comment]
I can see it also hasn't been renamed in type definitions. You can create a PR fixing it.
