### ISSUE TITLE
Typescript type error when using interpolateColors

### ISSUE THREAD

**Issue by OrsanZ** [software-mansion/react-native-reanimated#1354]
## Description

Typescript displays the following error message when using interpolateColors on the color property of an Animated.Text Component:
```
No overload matches this call.
  Overload 1 of 2, '(props: AnimateProps<TextStyle, TextProps> | Readonly<AnimateProps<TextStyle, TextProps>>): Text', gave the following error.
    Type '{ color: Animated.Node<number>; }' is not assignable to type 'StyleProp<AnimateStyle<TextStyle>>'.
      Types of property 'color' are incompatible.
        Type 'AnimatedNode<number>' is not assignable to type 'string | unique symbol | AnimatedNode<string | unique symbol | undefined> | undefined'.
          Type 'AnimatedNode<number>' is not assignable to type 'AnimatedNode<string | unique symbol | undefined>'.
  Overload 2 of 2, '(props: AnimateProps<TextStyle, TextProps>, context: any): Text', gave the following error.
    Type '{ color: Animated.Node<number>; }' is not assignable to type 'StyleProp<AnimateStyle<TextStyle>>'.
      Types of property 'color' are incompatible.
        Type 'AnimatedNode<number>' is not assignable to type 'string | unique symbol | AnimatedNode<string | unique symbol | undefined> | undefined'.
          Type 'AnimatedNode<number>' is not assignable to type 'AnimatedNode<string | unique symbol | undefined>'
```

## Steps To Reproduce

1. Create a new react component with typescript
2. Add an animation
3. Use interpolateColors to change the (background) color of an animated component

## Snack or minimal code example

```
import React from 'react';
import Animated, { interpolateColors, Value } from 'react-native-reanimated';

export default class ReanimatedTest extends React.Component {
  state: { x: any };

  constructor(props: any) {
    super(props);
    this.state = {
      x: new Value(0),
    };
  }

  render() {
    return (
      <Animated.Text
        style={{
          color: interpolateColors(this.state.x, {
            inputRange: [0, 1],
            outputColorRange: ['rgba(255, 0, 0, 1)', 'rgba(0, 255, 0, 1)'],
          }),
        }}
      >
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos,
        similique?
      </Animated.Text>
    );
  }
}
```

## Package versions

- React: 16.13.1
- React Native: 39.0.3
- React Native Reanimated: 1.13.0

**Comment by Paroni** [comment]
I have the same problem. It also appears on Animated.View, and on React Native Reanimated: 1.13.1.

**Comment by rand0mdev** [comment]
I have the same problem with Reanimated 1.13.0 and react-native-redash: 14.2.3

**Comment by wilq32-pwitkowski** [comment]
Same problem here on 1.13.1

**Comment by michaelduminy** [comment]
RN 0.63.3
Reanimated 1.4.0

Similar problem here with the following code:

```javascript
import { processColor } from 'react-native'

Animated.cond(condition, processColor(myColor), undefined)
```
emits the following error
```
Error:(61, 35) TS2345: Argument of type 'number | unique symbol | null | undefined' is not assignable to parameter of type 'Adaptable<Value>'.
  Type 'undefined' is not assignable to type 'Adaptable<Value>'.
```

I believe this is because of the `unique symbol` typing of `OpaqueColorValue` in `@types/react-native` not being accepted as an 'Adaptable`.

**Comment by wilq32-pwitkowski** [comment]
For anyone having problem with this, temporary solution might be to
`interpolateColors(this.state.x, {
            inputRange: [0, 1],
            outputColorRange: ['rgba(255, 0, 0, 1)', 'rgba(0, 255, 0, 1)'],
          })`

go with 

`interpolateColors(this.state.x, {
            inputRange: [0, 1],
            outputColorRange: ['rgba(255, 0, 0, 1)', 'rgba(0, 255, 0, 1)'],
          }) as any`

Not perfect, but until it's fixed it just makes TS ignore this error.

**Comment by jakub-gonet** [comment]
@OrsanZ

Does changing `interpolateColors` type to the 
```ts
export function interpolateColors(
      animationValue: Adaptable<number>,
      {
        inputRange,
        outputColorRange,
      }: {
        inputRange: ReadonlyArray<Adaptable<number>>;
        outputColorRange: ReadonlyArray<Adaptable<string | number>>;
      }
    ): AnimatedNode<string>;
```

inside `node_modules/react-native-reanimated/react-native-reanimated.d.ts` help with this type mismatch?

**Comment by OrsanZ** [comment]
It does, although you might consider changing the `color(r, g, b, a)` function's return type too, as that is what is [returned by interpolateColors](https://github.com/software-mansion/react-native-reanimated/blob/2a6c6139a7ac80b4072bb812fdb0d0cad2fee1bc/src/derived/interpolateColors.js#L61). (Likely why the type is `AnimatedNode<number>`)

`color` can also return both [AnimatedNode\<string\>,](https://github.com/software-mansion/react-native-reanimated/blob/2a6c6139a7ac80b4072bb812fdb0d0cad2fee1bc/src/derived/color.js#L37) and [AnimatedNode\<number\>](https://github.com/software-mansion/react-native-reanimated/blob/2a6c6139a7ac80b4072bb812fdb0d0cad2fee1bc/src/derived/color.js#L46), but it's type is just  [AnimatedNode\<number\>](https://github.com/software-mansion/react-native-reanimated/blob/2a6c6139a7ac80b4072bb812fdb0d0cad2fee1bc/react-native-reanimated.d.ts#L340).

**Comment by chj-damon** [comment]
I'll make a PR for this, as I met the same problem using `react-native-redash`

**Comment by chj-damon** [comment]
https://github.com/software-mansion/react-native-reanimated/pull/1467

**Comment by cnx-caiobarroso** [comment]
react-native-reanimated@2.14.4

Still getting typescript error:

O tipo 'string | AnimatedNode<string>' não pode ser atribuído ao tipo 'number | ColorValue | undefined'.

Maybe the merge fixing this issue was rollbacked in v2 development?
