### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by JonnyBurger** [software-mansion/react-native-reanimated#1355]
In current master there are two typos that can be noticed by end users:

1. DONT_AUTOINTSTALL_REANIMATED is misspelled

https://github.com/software-mansion/react-native-reanimated/search?q=DONT_AUTOINTSTALL_REANIMATED

2. `different` is misspelled: https://github.com/software-mansion/react-native-reanimated/blob/9ebcb8efa687f607587e1ac0804ca91f32c90b24/Common/cpp/SharedItems/ShareableValue.cpp#L15

**Comment by jakub-gonet** [comment]
Thanks for reporting!
