### ISSUE TITLE
Unmounting components with shared values freezes UI (repro)

### ISSUE THREAD

**Issue by JonnyBurger** [software-mansion/react-native-reanimated#1356]
After unmounting and mounting again a component which runs an animation, the whole app freezes on iOS. All other buttons become unresponsive and CPU drops to 0%.

Tested with Alpha 6, Alpha 7, the current master ([this commit](https://github.com/software-mansion/react-native-reanimated/actions/runs/313694079)) and with PR #1346 (up until commit 0f39329), the problem unfortunately appears everywhere. RN version: 0.63.2.

About my usecase: Trying to run an animation within a virtualized list which can unmount components anytime. Also trying to make a graph work on portrait and landscape and it requires unmounting and remounting the component in a different location.

**Minimal reproduction case:**

Copy this component anywhere in an app. After 20-25 seconds the text will stop animating and the button stops responding to touches.

![RPReplay_Final1603110087](https://user-images.githubusercontent.com/1629785/96450529-a1ea4f00-1216-11eb-8d4d-a75458c78631.gif)

```tsx

import React, {useEffect, useState} from 'react';
import {Button, View} from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';

const Inner = () => {
  const val = useSharedValue(0);

  useEffect(() => {
    val.value = withTiming(100, {
      duration: 10000,
    });
  }, [val]);

  const style = useAnimatedStyle(() => {
    return {
      fontSize: val.value,
    };
  });

  return (
    <Animated.View
      style={{
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
      }}
    >
      <View style={{height: 100}}>
        <Animated.Text style={style}>HIII</Animated.Text>
      </View>
      <Button title="is UI still responsive?" onPress={() => alert('Yes')} />
    </Animated.View>
  );
};

export const ReanimatedBugReport = () => {
  const [updates, setUpdates] = useState(() => Date.now());

  useEffect(() => {
    setInterval(() => {
      setUpdates(Date.now());
    }, 3000);
  });

  return <Inner key={updates} />;
};

```

**Comment by terrysahaidak** [comment]
Can confirm this. Totally random and happens only on the real device for me.

**Comment by zkmoney** [comment]
@terrysahaidak I am experiencing the exact same issue, specifically to your point about it happening on a real device vs. the simulator.

**Comment by karol-bisztyga** [comment]
Hey!
Is this code correct? I mean did you do it that way on purpose?
```
export const ReanimatedBugReport = () => {
  const [updates, setUpdates] = useState(() => Date.now());

  useEffect(() => {
    setInterval(() => {
      setUpdates(Date.now());
    }, 3000);
  });

  return <Inner key={updates} />;
};
```
This results in a lot of rerenders which seem unnecessary. It runs on mount and every rerender(no array passed to `useEffect`) at the same time setting a state inside causing a rerender. I'm just not sure if that's a React's good practice. But I also know it's possible you did it consciously to achieve this specific behavior, that's why I'm asking.
Seems to work without freezing when empty array `[]` is passed to `useEffect`.

**Comment by JonnyBurger** [comment]
@karol-bisztyga 

Hey thanks for pointing this out!
Even though I constructed this example, I did not realize that this causes exponential rerenders. That makes it look much more dramatic than it really is.

I just ran some tests, here is a modified snippet:

```ts
import {default as React, useEffect, useState} from 'react';
import {Button, View} from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';

const Inner = () => {
  const val = useSharedValue(0);

  useEffect(() => {
    val.value = withTiming(100, {
      duration: 10000,
    });
  }, [val]);

  const style = useAnimatedStyle(() => {
    return {
      fontSize: val.value,
    };
  });

  return (
    <Animated.View
      style={{
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
      }}
    >
      <View style={{height: 100}}>
        <Animated.Text style={style}>HIII</Animated.Text>
      </View>
      <Button title="is UI still responsive?" onPress={() => alert('Yes')} />
    </Animated.View>
  );
};

let i = 0;

export const ReanimatedBugReport = () => {
  const [updates, setUpdates] = useState(() => Date.now());

  useEffect(() => {
    setInterval(() => {
      setUpdates(Date.now());
    }, 100);
  }, []);
  console.log('rerendering', i++);

  return <Inner key={updates} />;
};

export const AppEntryPoint = () => {
  return <ReanimatedBugReport />;
};
```

Now it rerenders every 100ms, and it prints a counter. I still get the freeze on a real device, once I got it after 1214 rerenders, once after 187 rerender, in my last try after 1610 rerenders
