### ISSUE TITLE
'TurboModuleRegistry' is not exported from 'react-native' react-native-web

### ISSUE THREAD

**Issue by pankajgupta1** [software-mansion/react-native-reanimated#1364]
## Description
I am getting this error:

```
Failed to compile.

./node_modules/react-native-reanimated/src/reanimated2/NativeReanimated.js
Attempted import error: 'TurboModuleRegistry' is not exported from 'react-native'.
```

I upgraded react native to 0.63.3, and used react-native-reanimated version **2.0.0-alpha.7**

I am getting this error for **react-native-web**.

Thanks.

**Comment by calumjames** [comment]
I'm getting a similar error but with a more appropriate path:

> ./node_modules/react-native-reanimated/src/reanimated2/NativeReanimated.js
Attempted import error: 'TurboModuleRegistry' is not exported from 'react-native-web/dist/index'.

I followed the instructions here: https://docs.expo.io/versions/latest/sdk/reanimated/#experimental-support-for-v2-alpha.

Are you using Expo, @pankajgupta1?

**Comment by pankajgupta1** [comment]
@calumjames thanks for your comment. 

I am not using Expo.

**Comment by terrysahaidak** [comment]
What is the compiler thrown this error? Is this TS compiler?

**Comment by pankajgupta1** [comment]
> What is the compiler thrown this error? Is this TS compiler?

No, I am not using the typescript in my code.

**Comment by pankajgupta1** [comment]
I tried to find the module which is throughing this error for this library is from babel-loader plugin. Inside that some react-dev-utils dependency throughing this error

**Comment by terrysahaidak** [comment]
This error is some eslint of whatever error. Try to install the latest types for ReactNative 
https://www.npmjs.com/package/@types/react-native

**Comment by terrysahaidak** [comment]
Can somebody provide a producing repository for this error, please?

**Comment by Shing-Ho** [comment]
I am having that in the expo

**Comment by calendee** [comment]
Here's a reproducible example:

https://github.com/calendee/react-native-reanimated-issue-1364

**Comment by Shing-Ho** [comment]
@calendee 
https://github.com/software-mansion/react-native-reanimated/issues/1336#issuecomment-729653604
I was having a similar issue like in there. Please try `expo install react-native-reanimated` and see which version is installing. And what's your expo version?

**Comment by jakub-gonet** [comment]
@calendee, @Shing-Ho: does #1378 fix that error for you? Could you please try applying this patch and reporting to us if it works?

**Comment by calendee** [comment]
@Shing-Ho To use the v2 of react-native-animated, the [instructions](https://docs.expo.io/versions/latest/sdk/reanimated/#experimental-support-for-v2-alpha) say to install with yarn or npm rather than expo.

**Comment by Shing-Ho** [comment]
@jakub-gonet I didn't try that 1378. I fixed my issue by updating sdkVersion of the app.json. I was using sdkVersion 39.0.0 but in my app.json it was 38.0.0 After fix it. It works well.

**Comment by calendee** [comment]
@jakub-gonet I tried the patch yesterday but it didn't work on my Expo project and all the tests failed. I tried to figure out how to make them pass but was unsuccessful. I'll try to do your patch again today.

**Comment by jakub-gonet** [comment]
I _think_ I fixed the issue with the tests but I'll have to wait on CI to confirm this.

**Comment by Shing-Ho** [comment]
Actually, I didn't try the alpha version. I was trying the 1.13 and 1.13 is working now after I changed the sdkVersion in app.json

**Comment by calendee** [comment]
@jakub-gonet Using `patch-package` with your latest commits resolved the warning for me.  Thanks!
