### ISSUE TITLE
How to use interpolateColors with the new reanimated v2 API? 

### ISSUE THREAD

**Issue by cmaycumber** [software-mansion/react-native-reanimated#1368]
## Description

I'm having trouble animating colors with the new API. I'm wondering what the best way to approach animating colors is. 

This is what I'm currently trying:
```jsx
const scale = useSharedValue(1);
  const backgroundColor = useSharedValue(0);
  const animatedStyles = useAnimatedStyle(() => {
    return {
      backgroundColor: interpolateColors(backgroundColor.value, {
        inputRange: [0, 1],
        outputColorRange: ["black", "white"],
      }),
      transform: [
        {
          scale: scale.value,
        },
      ],
    };
  });
```

This doesn't work because the interpolate color function returns an animated node. My biggest problem is figuring out where to use the AnimatedNode inside the new API. Any direction on this would be super helpful.

**Comment by karol-bisztyga** [comment]
Hi!
Try `interpolateColor`. The function with `s` suffix seems to be from reanimated 1.
