### ISSUE TITLE
Support Hermes on iOS

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1372]
## EDIT

I've created a PR for this here: https://github.com/software-mansion/react-native-reanimated/pull/1469 🎉 

## Description

Since react-native 0.64 will ship with Hermes engine as an opt-in for iOS (see: https://github.com/react-native-community/releases/issues/207), I was wondering if the Hermes engine will be supported by react-native-reanimated v2?

**Comment by kmagiera** [comment]
Hi @mrousavy – Thanks for bringing this to our attention. From the technical standpoint I don't see why it wouldn't be possible to support hermes on iOS when react-native supports it. Reanimated uses JSI which is a VM-agnostic interface and we already work with hermes on Android. When it comes to supporting two VMs at once there are some restrictions on Android where we need to ship pre-build libraries that are linked with a selected VM, however this is not the case on iOS where Reanimated native code is compiled along with the app. 

I will keep this issue open but we definitely won't be looking into this more unless React Native 0.64 RC is published. If you or anyone is willing to test it sooner with RN master we'd be open to merging a patch.

**Comment by mrousavy** [comment]
@kmagiera I've tested out react-native 0.64-rc.0 and enabled hermes on iOS and everything's working fine! 🎉 

There were a few small adjustments I had to make, I've created a PR for those: https://github.com/software-mansion/react-native-reanimated/pull/1469.

Everyone interested, this is how you get 0.64 with hermes on iOS going:

1. Install rn 0.64 rc0 (`npm i react-native@next`) 
2. Clean all your caches, Pods/ node_modules, lockfiles
3. Follow [this upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.63.3&to=0.64.0-rc.0)
4. Update your Podfile like this:

```diff
-  use_react_native!(:path => config[:reactNativePath])
+  use_react_native!(:path => config[:reactNativePath], :hermes_enabled => true)
```

**Comment by a-eid** [comment]
@mrousavy reanimated 2 doesn't work for me with `0.64-rc1` with or without hermes enabled.

**Comment by mrousavy** [comment]
@a-eid what does "doesn't work for me" mean? did you try my fixes? (#1469)

**Comment by a-eid** [comment]
@mrousavy I've not, I'm assuming your fixes are hermes related. 
but even without heremes RN doesn't compile, give me a sec I'll upload a screenshot with the error I get, keep in mind that `reanimated 1.9.*` does work fine.

**Comment by amserhii11** [comment]
For me, pods with Hermes can't be installed. Can someone help me? I just updated RN and added to Podfile hermes:enabled
![image](https://user-images.githubusercontent.com/27774005/111035781-a5c87900-8424-11eb-92d5-0eef48dbb5ed.png)

**Comment by SpawnAtis** [comment]
@amserhii11 Try `pod install --verbose `. You will see the pod size (~483mb) and your current download speed. I had slow download speed for `curl`. Actually, I don't know why.
