### ISSUE TITLE
Shared values cannot be updated (master)

### ISSUE THREAD

**Issue by JonnyBurger** [software-mansion/react-native-reanimated#1374]
I tried Reanimated from master on iOS (commit 5bba1b30f6ac1c1d6a3cc06eb6d46e8067137828).

Seems like when trying to change a shared value, it doesn't do anything anymore.

Expected result: Text 'Hello' appears
Actual result: Blank screen (opacity stays at 0).

## Snack or minimal code example

```tsx
import React, {useEffect} from 'react';
import {View} from 'react-native';
import Animated, {
	useAnimatedStyle,
	useSharedValue,
} from 'react-native-reanimated';

export const Playground = () => {
	const opacity = useSharedValue(0);

	useEffect(() => {
		opacity.value = 1;
	}, [opacity]);

	const style = useAnimatedStyle(() => {
		return {
			opacity: opacity.value,
		};
	});

	return (
		<View style={{justifyContent: 'center', alignItems: 'center', flex: 1}}>
			<Animated.Text style={style}>Hello</Animated.Text>
		</View>
	);
};

```
## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: master
- NodeJS: 14.13.0

**Comment by JonnyBurger** [comment]
Unfortunately it seems to be related to the PR which fixes freezing: https://github.com/software-mansion/react-native-reanimated/pull/1346

Going from Alpha 7 to master triggers this issue.

and trying to cherry-pick the changes of #1346 to Alpha 7 (which I should mention i did not do too precisely because a lot has changed) also triggered it.

**Comment by schusovskoy** [comment]
Hello, I have the exact same issue, using reanimated 2.1.0.

**Comment by schusovskoy** [comment]
@karol-bisztyga Could you please check if I'm wrong?

**Comment by karol-bisztyga** [comment]
@piaskowyk @jakub-gonet @Szymon20000

**Comment by schusovskoy** [comment]
@piaskowyk @jakub-gonet @Szymon20000 Guys, do you have any updates?

**Comment by schusovskoy** [comment]
@karol-bisztyga can I expect a solution in the near future, or it's difficult to address it now?

**Comment by jakub-gonet** [comment]
@karol-bisztyga and I don't work on Reanimated 2. I suggest creating a new issue with a repro example.

**Comment by akinncar** [comment]
any update? have the same problem on 2.1.0
