### ISSUE TITLE
Update installation guide in official docs

### ISSUE THREAD

**Issue by kAVArd** [software-mansion/react-native-reanimated#1375]
Firstly i opened [this installation guide](https://docs.swmansion.com/react-native-reanimated/docs/installation) and did manual setup. After that gifs in my project stopped working. I could not understand what the problem is. But i found a problem in code that need to past in AppDelegate.mm

Can you please update your docs? Thanks

**Comment by kAVArd** [comment]
But [old instruction](https://docs.swmansion.com/react-native-reanimated/docs/installation) doesn't compatible with gifs (they are static like an image).

**Comment by terrysahaidak** [comment]
That's because we enable TurboModules for the whole ReactNative in alpha.7 docs. Not all the RN modules are compatible with TurboModules just yet.

We don't do it anymore but this version you're pointing to the docs on master hasn't been released just yet.
