### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found

### ISSUE THREAD

**Issue by kAVArd** [software-mansion/react-native-reanimated#1376]
## Description
Had a first version of Reanimated. But wanted to migrate to v2. Was followed by [this](https://github.com/software-mansion/react-native-reanimated/blob/master/docs/docs/installation.md) guide. IOS app builded successfully, but when Metro Bundler finish to load, error is appear.

### Screenshots
<img width="571" alt="Screen Shot 2020-10-23 at 17 52 25" src="https://user-images.githubusercontent.com/40182275/97019050-85248300-1558-11eb-9e83-83a118bf15b7.png">

Can someone help with this problem? PLEASE

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.7
- NodeJS: 14.9.0

**Comment by terrysahaidak** [comment]
Hi. If you wan to use alpha.7 version - you need to follow its instructions because You're pointiny right now on the documentation of the master, not alpha.7. Many things have changed since.

Please, refer to the documentation on the docs website instead.

**Comment by Benzer1406** [comment]
Still having the same issue on alpha 8, RN 0.63.3 and xCode 12.0.1

**Comment by luizjr** [comment]
I have the same problem using 2.0.0.RC.0 but RC.1 didn't even allow my app to run.

**Comment by lieberscott** [comment]
I was having this problem on Android even after following the installation instructions on reanimated's documentation page, but after I cleared my gradle cache and rebuilt the project it worked.

`rm -rf $GRADLE_HOME/caches/build-cache-*`

See here:  https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache

**Comment by Saidfatah** [comment]
> I was having this problem on Android even after following the installation instructions on reanimated's documentation page, but after I cleared my gradle cache and rebuilt the project it worked.
> 
> `rm -rf $GRADLE_HOME/caches/build-cache-*`
> 
> See here: https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache

thanks you so much you saved my day

**Comment by saurabh874** [comment]
I am also facing same issue in iOS. any body have idea how to resolve it?

**Comment by p2mittal-dev** [comment]
**Error - TurboModuleRegistry.getEnforcing(...): 'NativeReanimated'**
**Cause - React Native Reanimated 2.0**

Hello,
I got this[TurboModuleRegistry.getEnforcing(...): 'NativeReanimated'] error and i found the solution 
Step 1 - Download react native project from github  "https://github.com/software-mansion-labs/reanimated-2-playground".
Step 2- Then run command 
=> npm install
=> react-native start
=> react-native run-android
and build app 
Step 3- when its work move your required project files and install your required npm pakages.
Step 4 - Then run commands
=> npm cache clean --force
=> cd android
=> gradlew clean
=> gradle cleanBuildCache
=> gradlew build --refresh-dependencies
=> cd..
=> npx react-native start --reset-cache
=> npx react-native run-android
its work for me try once.

**Comment by RohitKaushal7** [comment]
```bash
npx react-native start --reset-cache
```
^ this  worked for me :)
