### ISSUE TITLE
web: Can't resolve 'react-native/Libraries/Utilities/setAndForwardRef'

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion/react-native-reanimated#1377]
## Description
I installed reanimated v2 to my react-native-web project and received this error.

```
Module not found: Can't resolve 'react-native/Libraries/Utilities/setAndForwardRef' in '/Users/hosseinmohammadi/Documents/GitLab/poolkhord/node_modules/react-native-reanimated/src'
```

## Steps To Reproduce

1.

## Package versions

- React: 17.0.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.7
- NodeJS: 12

**Comment by terrysahaidak** [comment]
Hi! This error is more a problem of react-native-web, but still Reanimated here uses some private ReactNative API. You can submit a PR that extracts this util to Reanimated or avoids using it if it's possible.

**Comment by hosseinmd** [comment]
> Hi! This error is more a problem of react-native-web, but still Reanimated here uses some private ReactNative API. You can submit a PR that extracts this util to Reanimated or avoids using it if it's possible.

Done, Please check it

**Comment by terrysahaidak** [comment]
In the meantime, while you're waiting for this PR to get merged, you can use patch-package to fix it locally.
