### ISSUE TITLE
Jest: global.__reanimatedWorkletInit is not a function

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1380]
## Description

We've setup jest to snapshot-test components and functionality. I've installed reanimated v2 without problems and all tests ran perfectly. After creating some more complex animations and gestures, I found out that suddenly **all** tests failed with the same error:

![Screenshot 2020-10-26 at 10 19 09](https://user-images.githubusercontent.com/15199031/97154840-b7aac780-1774-11eb-8c8b-910e8bdb00d4.png)

> Note that I never touched those components/tests after installing reanimated v2

Unfortunately I have no idea what exactly caused this, since the tests in our `master` branch still run successfully, and I also got some smaller animations implemented over there.

## Steps To Reproduce

1. Install reanimated v2
2. Create some complex tests
3. Run jest

### Expected behavior

My tests should run successfully.

### Actual behavior

My tests fail. Even the ones I didn't touch.

## Snack or minimal code example

`jest.setup.ts`

```ts
const mock = jest.requireMock("react-native-reanimated");
jest.mock("react-native-reanimated", () => ({
  ...mock,
  useSharedValue: jest.fn().mockReturnValue(0),
  useAnimatedStyle: jest.fn().mockReturnValue({}),
  useAnimatedScrollHandler: jest.fn().mockReturnValue({}),
  createAnimatedComponent: (component) => jest.fn().mockReturnValue(component),
  __reanimatedWorkletInit: jest.fn(),
  ScrollView: "ScrollView",
}));

// ...

//@ts-expect-error
global.__reanimatedWorkletInit = jest.fn();
```

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.7
- @testing-library/jest-native: 3.4.3
- @testing-library/react-native: 7.0.2
- jest: 26.5.3
- NodeJS: v14.13.1

**Comment by jakub-gonet** [comment]
Reanimated uses it's own babel plugin to transform worklets. This is another instance of missing mocks in Rea v2 (#1230 should resolve some problems related to this). You can try disabling the babel plugin for the test environment or mock `__reanimatedWorkletInit`:

```js
beforeAll(() => {
global.__reanimatedWorkletInit = jest.fn();
});
```

**Comment by M-i-k-e-l** [comment]
What worked for us was adding the following to the `jest-setup.js` file:
```
global.__reanimatedWorkletInit = jest.fn();
```

**Comment by enesozturk** [comment]
Issue is old but want to ask before opening a new one:
 
```js
global.__reanimatedWorkletInit = jest.fn();
```
When I put this line to `jest-setup.js` file, issue goes but this time I have issue with `toHaveAnimatedStyle` assertion.
Stack Trace:

```bash
TypeError: Cannot read property 'value' of undefined

      29 |
      30 |     expect(navigationButtons).toBeTruthy();
    > 31 |     expect(navigationButtons).toHaveAnimatedStyle({});
         |                               ^
      32 |   });
      33 |
      34 |   it.skip("should show on completed page", () => {

      at getCurrentStyle (node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js:31:103)
      at compareStyle (node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js:91:26)
      at Object.toHaveAnimatedStyle (node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js:149:20)
      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:259:1)
      at Object.toHaveAnimatedStyle (node_modules/expect/build/index.js:343:15)
      at Object.<anonymous> (src/components/PageContainer/ProfileFormContainer/__tests__/NavigationButtons.test.js:31:31)
```

Why that can happen? Do you have the same issues? @jakub-gonet

**Comment by enesozturk** [comment]
In **react-native-reanimated/lib/reanimated2/jestSetup.js > `getCurrentStyle`** function, `received.props.animatedStyle.value` is throw error. 

Because `animatedStyle` returns undefined. Is this because we mocked `global.__reanimatedWorkletInit `?

**Comment by aphillipo** [comment]
Anyone found a fix for the toHaveAnimatedStyle() being missing in jest/typescript - seems very strange I can see it being added.

**Comment by CryptoDev4** [comment]
The @M-i-k-e-l solutions works like a charm! Thanks man :)

**Comment by OliverAThunes** [comment]
I'm still having an issue with this, using typescript.
`Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.`

**Comment by nandorojo** [comment]
It looks like Reanimated 2.8 is breaking on Next.js, throwing this error:

<img width="844" alt="Screen Shot 2022-04-28 at 5 13 57 PM" src="https://user-images.githubusercontent.com/13172299/165846913-3ee67bb7-93d6-4f35-a7ae-133bd5a85467.png">
