### ISSUE TITLE
Updating custom props on UI thread does not work on iOS

### ISSUE THREAD

**Issue by kmagiera** [software-mansion/react-native-reanimated#1387]
## Description

When using third party components it is no longer possible to register additional properties to be updated directly on the UI thread. With Reanimated 1 it was possible using methods like `addWhitelistedNativeProps` or `addWhitelistedUIProps`, but this is no longer the case in Reanimated 2.

I tracked this problem down to the following line:
https://github.com/software-mansion/react-native-reanimated/blob/08c93d0c6cfef9d6930b19cf98b20c7488cc08d7/ios/native/NativeProxy.mm#L87

Where we always assume that we update props for RCTView component. Hence custom properties are added to some other view types, the props aren't properly applied and are filtered out.

The correct resolution would be to figure out a way how we can avoid having the view type hardcoded like this. In Reanimated 1 we use UIManager.viewNameForReactTag – but this method is only allowed to be called on the ui manager thread which was ok in Rea 1 as we had a registration step that was run on that thread. In Rea 2 we don't have registration step and may need to try figure out where to take this information from.

**Comment by kyle-ssg** [comment]
Hi @kmagiera, came across this issue which perplexed me a bit.

Does this mean the following is not updated on the UI Thread? From what I could tell it was.

<img src="http://g.recordit.co/XfsADZ7fBS.gif"/>

***[Code](https://github.com/kyle-ssg/reanimated2-experiments/blob/master/App/components/AnimatedBlur.tsx#L33)***

```
const animatedProps = useAnimatedProps(() => {
    return {
      blurAmount: interpolate(animatedValue.value, [0, 1], [0, 25]),
    };
  });
```

**Comment by kmagiera** [comment]
@kyle-ssg – yes, the example you posted work because the updates are happening via JS thread. Parameters cannot be updated on UI unless added to the whitelist. Unfortunately due to a bug only RCTView instances can be updated properly on UI thread right now.

**Comment by karol-bisztyga** [comment]
Should be closed automatically when closing #1409

**Comment by kyle-ssg** [comment]
@karol-bisztyga, apologies for bugging you on this - but with this what will the process be for whitelisting props ? Also, is there a way I can validate that prop updates are on the UI thread?

**Comment by karol-bisztyga** [comment]
No worries my friend, I'm here to help. Now whitelisting happens automatically - that means you don't have to add props you want to update on UI thread manually, they're added dynamically.
The conditions are you have to use reanimated 2 and some new view name(by new I mean a name that hasn't appeared in the app yet) and also only those props will be added to the UI whitelist which are not present in the native whitelist.
If you want to check whether a prop is updated on UI I think you would have to debug the code, set the breakpoints and check it manually, but there may be some other way I'm not aware of.

**Comment by kyle-ssg** [comment]
Ok that's awesome news thanks for the info and for responding, so in theory blurAmount will be set natively now. I may have to wait until 9 is patched to try it out (based on modals / pull to refresh currently crashing) but excited to try this!

I think yeah, the new addition of the runOnJS Error prompt was really useful for me in keeping track of things that were going on, adding some sort of accessible bool for logging (maybe there is one) would really help I think.
