### ISSUE TITLE
Calling measure on the element which is off the screen causing crash on Android

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#1390]
## Description

If the element is off the screen (user can't see it) on iOS we can get its measurements, on Android it causing the app to crash.

## Steps To Reproduce

1. Run provided example
2. Wait 1 second. It will try to measure the element which is off the screen

### Expected behavior

Should work just like on iOS – should return values off the screen

### Actual behavior

Crashes

## Snack or minimal code example

```jsx
import React from 'react';
import { useEffect } from 'react';
import {
  FlatList,
  TapGestureHandler,
} from 'react-native-gesture-handler';
import Animated, {
  useAnimatedRef,
  useAnimatedGestureHandler,
  measure,
  runOnUI,
} from 'react-native-reanimated';

function Block({ index }) {
  const ref = useAnimatedRef();

  const handler = useAnimatedGestureHandler({
    onFinish: () => {
      console.log(measure(ref));
    },
  });

  useEffect(() => {
    if (index === 9) {
      setTimeout(
        () =>
          runOnUI(() => {
            'worklet';

            console.log(measure(ref));
          })(),
        1000,
      );
    }
  }, []);

  return (
    <TapGestureHandler onGestureEvent={handler}>
      <Animated.View
        ref={ref}
        style={{
          height: 200,
          marginBottom: 16,
          backgroundColor: 'red',
        }}
      />
    </TapGestureHandler>
  );
}

function Navigation() {
  return (
    <FlatList
      data={Array.from({ length: 10 }).map((item, index) => index)}
      renderItem={({ index }) => <Block index={index} />}
    />
  );
}
```

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.7
- NodeJS: 12.16.2

**Comment by piaskowyk** [comment]
Hi!
`measure()` function works properly. The problem is with the FlatList component. The FlatList has [VirtualizedList](https://reactnative.dev/docs/virtualizedlist) on - This is optimization based on rendering only visible components on screen. Unfortunately you can’t measure an item that does not exist.

You have some simply solutions:
- use try{} catch{} to wrap problematic code
- disable [virtualization](https://reactnative.dev/docs/virtualizedlist#disablevirtualization) but this is bad solution because have negative impact on performance nad is deprecated
- wrap `<FlatList>` with `<ScrollView>` component

**Comment by terrysahaidak** [comment]
Hi there, thanks for your reply, it seems like I had some caching issues on Android because now try-catch actually catches the error just like it's on iOS.

I will let you know if I find any other issues regarding that.

**Comment by terrysahaidak** [comment]
Hey @piaskowyk, I've upgraded my library from alpha.9 to rc.2 and try-catch block no longer helps me on Android.

Tried to clean all the possible caches.

Could you please check if this is a case for you as well? The last time this has been magically resolved for me. But this time it just crashes.

**Comment by piaskowyk** [comment]
Ok, I'll check it soon and let you know.

**Comment by fabcall** [comment]
I had a similar issue using measure in a component (actually, a floating label textinput which depends on some internal measurements) inside a BottomSheetView provided by react-native-bottomsheet. I've wrapped the relevant code in try-catch block, but the issue persists: even though it would work a few times, eventually It crashes, throwing "the view with tag n could not be measured". Replacing measure with onLayout fixes the problem.

If you need further inspections, I'll happily Helô.

**Comment by giovanijfc** [comment]
Hello, forgive me for the english of the google translator.

It seems to me that this is a rendering problem on android, the measure tries to get the measurements before the view is even rendered on the screen, I got a result with the code below.

```
const [alreadyRender, setAlreadyRender] = useState<boolean>(false)

useEffect(() => {
    if (!alreadyRender) return
    runOnUI(() => {
      'worklet'
      console.log(Platform.OS, measure(ref))
    })()
}, [alreadyRender])

<Container onLayout={() => setAlreadyRender(true)}>
```

**Comment by Noitidart** [comment]
Thanks @giovanijfc for that solution. I did slightly different, I run measure from JS until it gives me truthy bounds:

I use the util below `untilMeasured` before a worklet like this:

```
(async function () {
  const bounds = await untilMeasured(ref);

  (function startOpening() {
    'worklet';

    // use bounds here
  })();
)()
```

<details>
<summary>`untilMeasured` util</summary>

```
import Reanimated, * as ReanimatedUtils from 'react-native-reanimated';

function untilMeasured(ref: React.RefObject<Reanimated.View>) {
  return new Promise<NonNullable<BoundsOrNull>>(async resolve => {
    let bounds;
    for (let i = 0; i < 100; i++) {
      console.log('measuring');
      bounds = await new Promise<BoundsOrNull>(resolve => {
        ReanimatedUtils.runOnUI(measureOrNull)(ref, resolve);
      });

      if (bounds) {
        console.log(`Took ${i} attempts to measure`);
        resolve(bounds);
        return;
      } else {
        await new Promise(resolve => setTimeout(resolve, 0));
      }
    }

    throw new Error('COULD_NOT_MEASURE');
  });
}

/**
 * Use this to measure from JS. A callback is triggered with null, or the bounds.
 *
 */
type BoundsOrNull = null | ReturnType<typeof ReanimatedUtils.measure>;
function measureOrNull(
  ref: React.RefObject<Reanimated.View>,
  callback: (bounds: BoundsOrNull) => void
) {
  'worklet';
  let bounds;
  try {
    bounds = ReanimatedUtils.measure(ref);
  } catch (error) {
    ReanimatedUtils.runOnJS(callback)(null);
    return;
  }
  if (!bounds) {
    ReanimatedUtils.runOnJS(callback)(null);
  } else if (bounds.height === 0) {
    ReanimatedUtils.runOnJS(callback)(null);
  } else {
    ReanimatedUtils.runOnJS(callback)(bounds);
  }
}
```
</details>
