### ISSUE TITLE
useAnimatedProps example broken

### ISSUE THREAD

**Issue by nabati** [software-mansion/react-native-reanimated#1397]
## Description

The example used in the [documentation](https://docs.swmansion.com/react-native-reanimated/docs/next/api/useAnimatedProps/) for `useAnimatedProps` does not seem to be working. There are a couple of typos, but even fixing those just gives an error. 

![image](https://user-images.githubusercontent.com/1499050/97723027-970fa400-1acb-11eb-98d0-c074ce043808.png)

## Steps To Reproduce

1. Repro here https://github.com/software-mansion-labs/reanimated-2-playground/compare/master...nabati:pn/animated-props-example-broken?expand=1

## Snack or minimal code example

```
import React from 'react';
import Animated, {
  useSharedValue,
  useAnimatedProps,
} from 'react-native-reanimated';
import Svg, {Path} from 'react-native-svg';

const AnimatedPath = Animated.createAnimatedComponent(Path);

function App() {
  const radius = useSharedValue(50);

  const animatedProps = useAnimatedProps(() => {
    // draw a circle
    const path = `
    M 100, 100
    m -${radius}, 0
    a ${radius},${radius} 0 1,0 ${radius * 2},0
    a ${radius},${radius} 0 1,0 ${-radius * 2},0
    `;
    return {
      d: path,
    };
  });

  // attach animated props to an SVG path using animatedProps
  return (
    <Svg>
      <AnimatedPath animatedProps={animatedProps} fill="black" />
    </Svg>
  );
}

export default App;

```

## Package versions

- React: 16.13.1
- React Native: 0.63.1
- React Native Reanimated: 2.0.0 alpha 7
- react-native-svg: 12.1.0

**Comment by jakub-gonet** [comment]
Fixed by #1396.
