### ISSUE TITLE
After reload or restart an app it works fine but when i refresh code it was slow down the animation.

### ISSUE THREAD

**Issue by Venkatesh9Morla** [software-mansion/react-native-reanimated#1403]
## Description

my idea about my animation is to take the SVG path and get the length and animate from 0 positions to its length after complete repeat the same thing forever using the repeat function.

###Problem
It works for the first time when the app restarts but after refresh the code. The animation slows down and not working properly.
 
### code 
```
import React from 'react'
import { StyleSheet, Text, View } from 'react-native'
import Animated,{useAnimatedProps,useSharedValue,withTiming, Easing, repeat} 
  from 'react-native-reanimated';
import Svg,{Path} from 'react-native-svg';


const InfinityLoader = (props) => {

  const AnimatedPath = Animated.createAnimatedComponent(Path);
  const aniRef = React.useRef(null);
  const time = useSharedValue(0);
  const animatedProps = useAnimatedProps(()=>({
    strokeDashoffset: repeat(withTiming(time.value, { duration: 1500, easing: Easing.linear }),-5,false),
  }))
  React.useEffect(()=>{
    time.value = aniRef.current.getTotalLength();
    return () => {
      time.value = 0;
    }
  });
  return (<View style={styles.container}>
      <Svg height="50" width="100" viewBox="0 0 100 100">
      <AnimatedPath
        animatedProps={animatedProps}
        ref={aniRef}
        fill="none"
        stroke="#e90c59"
        strokeWidth="10"
          strokeDasharray="189.87580688476564 66.71312133789061"
        d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40
         51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 
        20C56.4 70 43.6 30 24.3 30z"
        strokeLinecap="round"
        strokeDashoffset="400"
      />
      </Svg>
    </View>);
}

export default InfinityLoader

const styles = StyleSheet.create({
  container: { 
    backgroundColor: '#1234' ,
    width: 'auto',
    height: 40,
    alignItems: "center",
    justifyContent: "center"
  }
})

```

### Screenshots
[First time when reloading of the app screen](https://i.ibb.co/6PppgK9/20201101-123740.gif)
[After refreshed the code screen](https://i.ibb.co/4pFb0tC/20201101-124045.gif)

## Steps To Reproduce

1.

## Package versions

- React:
- React Native:
- React Native Reanimated:
- NodeJS:

**Comment by jakub-gonet** [comment]
Could you please format the code using ``` blocks?

**Comment by Venkatesh9Morla** [comment]
> Could you please format the code using ``` blocks?

Yes, formatted the code.

**Comment by piaskowyk** [comment]
Hey @Venkatesh9Morla
It is a problem with `react-native-svg` unfortunately. You use `ref.current.getTotalLength()` and this function does not work properly. The issue have been already exists, you can check it [here](https://github.com/react-native-svg/react-native-svg/issues/1336)

**Comment by jasonnathan** [comment]
Any chance we get an update on the issue before stalebot strikes again? 🤣. Having the issue exactly as described. Was working fine when developing the component(s) but after a clean build and install, this issue came up. 

Anything to be done as a workaround? Makes it really frustrating to dev, especially for animations 😔

Cheers and thanks for the great library guys. 💪🏽😎
