### ISSUE TITLE
Calling makeMutable

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#1404]
## Description

Are they some big caveats against calling `makeMutable` directly ?
For instance, I want to maintain a list of shared values inside a ref, instead of calling `useShareValue`.
However, I can't call `useSharedValue` inside a hook, which is expected, but `makeMutable` will work.

**Comment by Szymon20000** [comment]
You can call makeMutable whenever you want. useSharedValue calls it only once (during the first render) and maintains the same object between rerenders. However, keep in mind that if you call makeMutable twice then you get two different objects, and changes made on the first one are not visible for the second one.

**Comment by Andarius** [comment]
Perfect ! Thanks for the answer.
