### ISSUE TITLE
alpha 7 iOS instructions

### ISSUE THREAD

**Issue by Thanaen** [software-mansion/react-native-reanimated#1405]
## Description

Hi,

I am using react-native-reanimated alpha 7, and would like to upgrade to alpha 8. In your docs, you write:

> NOTE: In previous releases, the installation process was manual and required turning turbo modules on. Some libraries break >when turbo modules are enabled so we decided to change our approach and we no longer use the standard way for >registering a turbo module. It let us simplify the installation process and as a result, you can safely undo all installation steps >from the _**previous instruction.**_

The problem is, when we click on "previous instruction", it simply refreshes the page, making the upgrade a bit complicated.

Would it be possible for you to make the alpha 7 iOS instructions available again ?

Thanks in advance !

**Comment by jakub-gonet** [comment]
It should be available under Versions > alpha.7, I'll prepare PR fixing this error, thanks for reporting that.
