### ISSUE TITLE
when i trying to edit it is getting deleted in below code

### ISSUE THREAD

**Issue by umkar-dayyala** [software-mansion/react-native-reanimated#1410]
### Package versions

- React:
- React Native:
- React Native Reanimated:

**Comment by umkar-dayyala** [comment]
//Editing UCTM configuration
function deleteUctm(callback) {
    return new Promise(function(resolve, reject) {
        //var delRequest= $.post( "delete.php",{id : id},
        var delRequest= $.post( "delete.php",{licenseEnabled : licenseEnabled, openLicense : openLicense, id : id, ip : ip, pwd : pwd, users : users, calls : calls, multi_tenant : multi_tenant, irsf : irsf, afi : afi, tls : tls, ha : ha, attestation : attestation, verification : verification, uctm_name : uctm_name },
            function(data) {
                if(data != null && data != ""){
                    alert( data );
                }
            })
            .fail(function() {
                alert( "Unable to connect to server." );
            });
            resolve();
    })
}

function addUctm() {
    setTimeout(function() {
        //var addRequest= $.post( "addUctm.php",{id : id, ip : ip, pwd : pwd, users : users, calls : calls, uctm_name : uctm_name },
        var addRequest= $.post( "addUctm.php",{ licenseEnabled : licenseEnabled, openLicense : openLicense, id : id, ip : ip, pwd : pwd, users : users, calls : calls, multi_tenant : multi_tenant, irsf : irsf, afi : afi, tls : tls, ha : ha, attestation : attestation, verification : verification, uctm_name : uctm_name },
            function(data) {
                if(data != null && data != ""){
                    if(data.includes("No license available")){
                        $("#checkBoxErr").text(data);
                    }else if(data.includes("Open License Key not")){
                        $("#openLicErr").text(data);
                    }else{
                        alert( data );
                    }
                }
                document.location.href = "globalConf.php";
            })
            .fail(function() {
                alert( "Unable to connect to server." );
            });
    }, 1000);
}
deleteUctm().then(addUctm)
}

by this code i am trying to edit the my existing configuration but it is getting deleted some times

**Comment by jakub-gonet** [comment]
This doesn't have any connection with this library.
