### ISSUE TITLE
Passing a sharedValue to a component

### ISSUE THREAD

**Issue by Eduardo-Balistieri** [software-mansion/react-native-reanimated#1411]
## Description

Basically I created a `sharedValue` and I want to use it in a child component.
Is there a way to do that?

## Code

```js
const App = () => {
    const translateX = useSharedValue(0)

    const gestureHandler = useAnimatedGestureHandler({
        // ...
    })

    const animatedStyles = useAnimatedStyle(() => {
        return {
            transform: [{ translateX: translateX.value }]
        }
    })

    return (
        <View style={styles.container}>
            <PanGestureHandler onGestureEvent={gestureHandler}>
                <Animated.View style={[styles.box, animatedStyles]}>
                    <View style={styles.mainOption}>
                        <Text style={styles.mainContent}>Swipe to remove</Text>
                    </View>

                    <Action x={Math.abs(translateX.value)} />
                </Animated.View>
            </PanGestureHandler>
        </View >
    )
}


const Action = ({ x }) => {
    const size = useSharedValue(x < height ? x : x + (x - height))
    // ...
}
```

**Comment by terrysahaidak** [comment]
Pass the shared value as is (not the .value thing) and use useDerivedValue to create a shared value based on that value.

**Comment by Eduardo-Balistieri** [comment]
> Pass the shared value as is (not the .value thing) and use useDerivedValue to create a shared value based on that value.

I tried something like that, but didn't work
```js
const Action = props => {
    const x = useSharedValue(0)

    useDerivedValue(() => {
        const formatedValue = Math.abs(props.x.value)
        x.value = formatedValue
    })
    // ...
}
```

The solution that I found is using a useless state to force re-render the component, then I get the new values
```js
const Action = props => {
    const [_, setState] = useState(0)

    const x = useDerivedValue(() => {
        const formatedValue = Math.abs(props.x.value)
        setState(formatedValue)
        return formatedValue
    })
    // ...
}
```
But it appears to be executed in JS thread instead the UI.
Do you have any suggestions?

**Comment by terrysahaidak** [comment]
in order to pass any value to component, you should use useAnimatedStyle. So just use x in there.

**Comment by Eduardo-Balistieri** [comment]
> in order to pass any value to component, you should use useAnimatedStyle. So just use x in there.

Yes, but about the state? You have another solution?

**Comment by terrysahaidak** [comment]
What do you need state here for?

**Comment by Eduardo-Balistieri** [comment]
> 
> 
> What do you need state here for?

As I said, with this code I only get the value of the first render

```js
 const x = useSharedValue(0)

    useDerivedValue(() => {
        const formatedValue = Math.abs(props.x.value)
        x.value = formatedValue
    })
```

The reason of the state is force an update, then I get the new value (props).
Do you have an example passing a sharedValue as props?

**Comment by terrysahaidak** [comment]
useDerivedValue call returns a shared value which will be updated each time the shared value you used from props is updated. you don't need to have another one.

Also, why do you need your component to rerender?

**Comment by Eduardo-Balistieri** [comment]
> 
> 
> useDerivedValue call returns a shared value which will be updated each time the shared value you used from props is updated. you don't need to have another one.
> 
> Also, why do you need your component to rerender?

I'm using a state because useDerivedValue is not updating.
If I print the value inside useDerivedValue its correct, but outside it doesn't change.

**Comment by terrysahaidak** [comment]
Could you please post a real code here? Unfortunately, I can't understand your intend by the extracted snippets you provided.

**Comment by Eduardo-Balistieri** [comment]
> Could you please post a real code here? Unfortunately, I can't understand your intend by the extracted snippets you provided.

Sure!
- [My repository](https://github.com/Eduardo-Balistieri/swipe)

**Comment by terrysahaidak** [comment]
Instead of this

```jsx
   const x = useSharedValue(0)

   useDerivedValue(() => {
      const formatedValue = Math.abs(props.x.value)
      x.value = formatedValue
   })

```

You should do this:

```jsx
   const x = useDerivedValue(() => {
      const formatedValue = Math.abs(props.x.value)
      return formatedValue;
   })
```

useDerivedValue will be executed each time props.x.value has changed. It will result in the change of `x.value`. So no, `x` itself won't be recreated, but the `.value` of it will be the result of useDerivedValue's callback.


Moving to the next part.

if you need the shared value which depends on some other values, you again need to use useDerivedValue. So this 

```jx
   const size = useSharedValue(
      x.value < height ?
         x.value :
         x.value + (x.value - height)
   )

   const translateX = useSharedValue(
      x.value < height ?
         0 :
         (x.value - height) / -2
   )
```

should be replaced with useDerivedValue

```
   const size = useDerivedValue(() =>
      x.value < height ?
         x.value :
         x.value + (x.value - height)
   )

   const translateX = useDerivedValue(() =>
      x.value < height ?
         0 :
         (x.value - height) / -2
   )
```

And the final part.

Interpolate - is just a function that returns a value. Only the time it's executed. In order for it to return interpolated opacity - you need to use it inside the useAnimatedStyle like so

```jsx
   const textStyles = useAnimatedStyle(() => {
     const opacity = interpolate(
       size.value,
       [height - 5, height + 5],
       [0, 1]
     );

      return {
         opacity: opacity
      }
   })
```

In this useAniamtedStyle, we access `size.value` so it subscribes for its changes. And now each time the size changes - we rerun the callback. So that interpolation function will be re-executed too. And will return a new value based on the current `size.value`.

**Comment by Eduardo-Balistieri** [comment]
> Instead of this
> 
> ```js-jsx
>    const x = useSharedValue(0)
> 
>    useDerivedValue(() => {
>       const formatedValue = Math.abs(props.x.value)
>       x.value = formatedValue
>    })
> ```
> 
> You should do this:
> 
> ```js-jsx
>    const x = useDerivedValue(() => {
>       const formatedValue = Math.abs(props.x.value)
>       return formatedValue;
>    })
> ```
> 
> useDerivedValue will be executed each time props.x.value has changed. It will result in the change of `x.value`. So no, `x` itself won't be recreated, but the `.value` of it will be the result of useDerivedValue's callback.
> 
> Moving to the next part.
> 
> if you need the shared value which depends on some other values, you again need to use useDerivedValue. So this
> 
> ```js-jsx
>    const size = useSharedValue(
>       x.value < height ?
>          x.value :
>          x.value + (x.value - height)
>    )
> 
>    const translateX = useSharedValue(
>       x.value < height ?
>          0 :
>          (x.value - height) / -2
>    )
> ```
> 
> should be replaced with useDerivedValue
> 
> ```js-jsx
>    const size = useDerivedValue(() =>
>       x.value < height ?
>          x.value :
>          x.value + (x.value - height)
>    )
> 
>    const translateX = useDerivedValue(() =>
>       x.value < height ?
>          0 :
>          (x.value - height) / -2
>    )
> ```
> 
> And the final part.
> 
> Interpolate - is just a function that returns a value. Only the time it's executed. In order for it to return interpolated opacity - you need to use it inside the useAnimatedStyle like so
> 
> ```js-jsx
>    const textStyles = useAnimatedStyle(() => {
>      const opacity = interpolate(
>        size.value,
>        [height - 5, height + 5],
>        [0, 1]
>      );
> 
>       return {
>          opacity: opacity
>       }
>    })
> ```
> 
> In this useAniamtedStyle, we access `size.value` so it subscribes for its changes. And now each time the size changes - we rerun the callback. So that interpolation function will be re-executed too. And will return a new value based on the current `size.value`.

Nice! It works, thank you very much.

**Comment by nitin-jotwani-fc** [comment]
I've followed above steps, but still for me value not updating in child. @terrysahaidak 
```
const App = () => {
    const translateX = useSharedValue(0)
   const scrollHandler = useAnimatedScrollHandler(event => {
      translateX.value = event.contentOffset.y
  })
    return (
        <View style={styles.container}>
            <AnimatedSectionList onScroll={scrollHandler} /> // This is working fine, on scroll values are getting updated
            <Action x={translateX} />
        </View >
    )
}

const Action = ({ x }) => {
    const size = useDerivedValue(() => x.value)
    // ... size value do not update here
}

**Comment by nitin-jotwani-fc** [comment]
Update: Was able to see animation if I apply in `useAnimatedStyle`. But, if I want to access value to do something conditional inside child component, that I'm unable to do.
size variable doesn't update outside. But works fine when applied as an animation using useAnimatedStyle.

**Comment by geroale** [comment]
Hello @nitin-jotwani-fc , I'm having the same issue. Have you managed to solve it?

**Comment by buitrbao222** [comment]
When I pass the sharedValue directly as a prop to the child component, this error appeared:
```Error: invalid value passed to `property_name`, maybe you forgot to use `.value`?```

**Comment by ucheNkadiCode** [comment]
My problem is i'm not passing a style to a component, I'm trying to pass a number value to an AnimatedCircle component so it can update the strokedashoffset

**Comment by andvalsol** [comment]
I'm facing the same issue, the shared value is not being updated.

**Comment by piaskowyk** [comment]
@andvalsol Please be aware that a change in shared value does not trigger a re-render. Instead, it invokes animation callbacks such as useAnimatedStyle.

**Comment by omeid** [comment]
Shouldn't it also trigger a useAnimatedProp?

**Comment by vkukade-altir** [comment]
@omeid I see that changes derived value doesn't trigger useAnimatedProps. I had to use workaround to get it work.
I had to create new shared value in child component along with derived value and then it worked. Finally I used  new shared value for text or style.

useAnimatedReaction(
      () => {
        return testDerived.value;
      },
      (currentValue, previousValue) => {
        if (currentValue !== previousValue) {
          newShared.value = currentValue;
        }
      },
    );
