### ISSUE TITLE
Error calling RCTDeviceEventEmitter.emit unknown

### ISSUE THREAD

**Issue by SohaibKtb** [software-mansion/react-native-reanimated#1415]
when I updated react-native-reanimated from version 1.13.1 to 2.0.0-alpha.8 the app stopped working

I got an error message: "Error calling rctdeviceeventemitter.emit unknown"

### Screenshots
![error](https://user-images.githubusercontent.com/48629268/98347793-95d8fc80-2020-11eb-81e6-7a38e34d4576.jpg)

I followed the installation instructions on the documentation page step by step

## Package versions
```js
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.1",
    "@react-native-community/datetimepicker": "^3.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.6.6",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/material-bottom-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "dotenv": "^8.2.0",
    "moment": "^2.29.1",
    "native-base": "^2.13.13",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-android-location-enabler": "^1.2.1",
    "react-native-animated-pagination-dot": "^0.1.8",
    "react-native-dotenv": "^2.3.0",
    "react-native-geolocation-service": "^5.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-google-places-autocomplete": "^1.8.3",
    "react-native-image-picker": "^2.3.4",
    "react-native-localization": "^2.1.6",
    "react-native-localize": "^1.4.1",
    "react-native-maps": "0.27.1",
    "react-native-modal": "^11.5.6",
    "react-native-open-maps": "^0.3.5",
    "react-native-paper": "^4.0.1",
    "react-native-permissions": "^2.1.5",
    "react-native-popup-menu": "^0.15.9",
    "react-native-qrcode-scanner": "^1.4.1",
    "react-native-reanimated": "^2.0.0-alpha.8",
    "react-native-restart": "^0.0.17",
    "react-native-safe-area-context": "^3.1.6",
    "react-native-screens": "^2.10.1",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-vector-icons": "^7.0.0"
  },
```

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.8
- NodeJS: 12.13.1

**Comment by timhilgenstoehler** [comment]
I just wanna add that I have the same problem with a clean new project aswell:

```
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-reanimated": "^2.0.0-alpha.8"

**Comment by martis900** [comment]
Having the same issue

**Comment by Harkindey** [comment]
This occurs on iOS and Crashes the app for me on android. Help.

**Comment by mohamed-sultan** [comment]
the same

**Comment by timhilgenstoehler** [comment]
Hey Guys, I fixed the issue by removing and 'node_modules' and doing 'yarn install' again!

**Comment by Harkindey** [comment]
@timhilgenstoehler really?

**Comment by brijeshbv** [comment]
Same issue.

**Comment by timhilgenstoehler** [comment]
> @timhilgenstoehler really what did you remove? and you are sure it is still
> 
> ```
>  "react-native-reanimated": "^2.0.0-alpha.8"
> ```
> 
> ?

Sorry I had a typo. I just removed the 'node_modules' folder and did 'yarn install' again. Did you tried this? 
And don't forget to do 'pod install' inside the iOS folder.

package.json
```
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-reanimated": "^2.0.0-alpha.8",
```

in my yarn lock it says also:
```
 version "2.0.0-alpha.8"
```

**Comment by FernandoJMedina** [comment]
> This occurs on iOS and android. Help.
> <img alt="Screenshot 2020-11-07 at 15 51 36" width="315" src="https://user-images.githubusercontent.com/14913673/98444303-2b53b980-2111-11eb-896a-bcc14e9dfc2d.png">

removing node_modules and reinstalling does not fix this problem.

**Comment by jose31canizar** [comment]
Removing related app folder and ModuleCache from derived data solves this problem. Your flow should probably include that clean step anyway: https://stackoverflow.com/questions/58927291/when-can-i-safely-delete-xcode-deriveddata-folder

**Comment by Harkindey** [comment]
This Error still persists

**Comment by somebody32** [comment]
For the flow to fix was:
1. ensuring babel plugin installed
2. `watchman watch-del-all` && `yarn start --reset-cache`

**Comment by SohaibKtb** [comment]
Hello @somebody32,

babel plugin already installed in the devDependencies:

```js
"devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^26.6.1",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
```

**Comment by somebody32** [comment]
@SohaibKtb it should be also added to babel.config.js: https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin

**Comment by SohaibKtb** [comment]
@somebody32 I did it also, see the description I provided in the first post
`I followed the installation instructions on the documentation page step by step`

**Comment by jakub-gonet** [comment]
Just making sure: did you remove all caches?

- `node_modules/` (`rm -rf node_modules`)
- metro cache (`react-native start --clear-cache`)
- watchman cache (`watchman watch-del-all`)
- Gradle cache (`gradle clean` in `android/` folder)
- Pods cache (`rm -rf Pods/ && pod instal`)
- Build artifacts from `xcodebuild` (clean project in xcode)

If none of the above commands fixes your problem please provide a reproduction repo so we can investigate it locally. Closing for now as build or config issue; will reopen when we'll be able to repro it.

**Comment by izanf** [comment]
The same error on here. Any solution for this?

**Comment by dilantha111** [comment]
Seems like this is happening for the production version of the react apps as well. 
```
"react-native": "0.64.2"
"react": "17.0.1"
```

Got these errors through firebase crashlytics 

```
Fatal Exception: java.lang.RuntimeException: Error calling RCTDeviceEventEmitter.emit
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:764)
````
Any idea on this?

**Comment by yalamandarao** [comment]
@jakub-gonet still issue occured. Any solutions 

"expo": "^48.0.0",
 "react-native": "0.71.3",

**Comment by nileshgalaxy** [comment]
still issue occured. Any solutions

"expo": "^48.0.0",
"react-native": "0.71.14",
