### ISSUE TITLE
Warning - Method `repeat` is deprecated. Please use `withRepeat` instead

### ISSUE THREAD

**Issue by bhaskarmurthy** [software-mansion/react-native-reanimated#1420]
## Description

I'm following the example to use the `withRepeat` hook, but getting a warning.

## Steps To Reproduce
Code below

### Expected behavior
Animation runs as expected, and repeats indefinitely. No crashes.

### Actual behavior
Warning when animation starts.
Crash when animation finishes.

## Snack or minimal code example

```
const ANGLE = 2;
const DURATION = 120;
const EASING = Easing.inOut(Easing.ease);

const AnimatedSmartGridTile = (props: SmartGridTileProps) => {
  const smartGridContext = useSmartGridContext();
  const editing = smartGridContext.editing;

  const rotation = useSharedValue(0);
  rotation.value = editing.value
    ? withSequence(
        // deviate left to start from -ANGLE
        withTiming(-ANGLE, {duration: DURATION / 2, easing: EASING}),
        // wobble between -ANGLE and ANGLE 7 times
        withRepeat(
          withTiming(ANGLE, {
            duration: DURATION,
            easing: EASING,
          }),
          -1,
          true,
        ),
        // go back to 0 at the end
        withTiming(0, {duration: DURATION / 2, easing: EASING}),
      )
    : 0;

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{rotateZ: `${rotation.value}deg`}],
  }));

  return (
    <Animated.View style={animatedStyle}>
      <SmartGridTile {...props} />
    </Animated.View>
  );
};
```

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.8
- NodeJS: 12.18.4

**Comment by piaskowyk** [comment]
Hi, 
I tried to reproduce your issue but this works for me.
I don’t know what SmartGridTile is. Is it your custom component or form some library?
Could you show me a stacktrace or description of this error?

**Comment by bhaskarmurthy** [comment]
hi @piaskowyk 

Yes, `SmartGridTile` is a custom view, it's just a simple Touchable with some custom styling.

There's no crash, simply a warning to use `withRepeat` instead of `repeat`

**Comment by piaskowyk** [comment]
This warning is because repeat() function is deprecated. You can use withRepeat() because at this moment repeat() calls a new withRepeat() function.

You wrote: "_Crash when animation finishes._"
Do you still have this problem or it was just warning about deprecated function?

**Comment by bhaskarmurthy** [comment]
I'm actually using `withRepeat` - code snippet below:

```
rotation.value = editing.value
    ? withSequence(
        // deviate left to start from -ANGLE
        withTiming(-ANGLE, {duration: DURATION / 2, easing: EASING}),
        // wobble between -ANGLE and ANGLE 7 times
        withRepeat(
          withTiming(ANGLE, {
            duration: DURATION,
            easing: EASING,
          }),
          -1,
          true,
        ),
        // go back to 0 at the end
        withTiming(0, {duration: DURATION / 2, easing: EASING}),
      )
    : 0;
```

Crash is not happening - it was not related to this issue.

**Comment by piaskowyk** [comment]
Ok, thanks for information. Good luck!
