### ISSUE TITLE
Worklets compiled with v2 hasn't been initialized (global.__reanimatedWorkletInit is not a function)

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1423]
I'm experiencing a peculiar use case where I'm having worklet functions processed by the babel plugin, used on the JS thread but v2 wasn't been imported anywhere. This is the case for instance where I have a boilerplate project for people to code along that uses worklets on the JS thread but reanimated hasn't been imported yet.

There is also the case where you might want to use redash functions on the JS thread without doing any animations stuff.
Should the babel plugin make the reanimated import for us in such case? I'm not sure I understand the details of this.

**Comment by jakub-gonet** [comment]
So if I understand correctly, you want to create worklets, but not use them? Or you want to use them, but treat like JS functions? 

Could you provide some examples?

**Comment by wcandillon** [comment]
A use case is either a boilerplate project where people will code along and reanimated 2 is not available yet but I'm using a function like round from redash I use it from both the JS and UI thread to consistently round on the both sides. But on the boilerplate, we only have the JS side for now.

**Comment by karol-bisztyga** [comment]
Hey William. Interesting case.
You could try to inject your own `global.__reanimatedWorkletInit` implementation(it could be an empty function):
```
import { View, Text } from 'react-native';
import React from 'react';

export default function AnimatedStyleUpdateExample() {
  global.__reanimatedWorkletInit = () => {};

  const f = () => {
    'worklet';
    console.log('Si');
  };

  console.log(f);

  return (
    <View>
      <Text>WORKING</Text>
    </View>
  );
}

```
I checked and it works.
I don't see how we could handle such case and why would we do that officially - worklets and the babel plugin are parts of the library not the standalone functionalities. Plus your use case does not cover a real world actions but some test environments.
That's my opinion but if you disagree, let me know. Otherwise is this closable?
Cheers William and thanks for bringing this up! :)

**Comment by wcandillon** [comment]
I agree @karol-bisztyga. A workaround is all I need. But would a better error message for such a scenario be possible?

**Comment by karol-bisztyga** [comment]
That would be good but I don't know how we could do this since it happens only when the library isn't imported 😅 So if I understand this correctly this seems to be beyond our control :/

**Comment by karol-bisztyga** [comment]
I mean the only place we could handle this is the babel plugin

**Comment by karol-bisztyga** [comment]
I don't think we have access to the app's `global` from the babel plugin so we would be able to check for such existence. But I might be wrong. If you see a way, let me know.

**Comment by karol-bisztyga** [comment]
Maybe it could be done but the priority for sure isn't high for the reasons I listed above. However we might do it in the future.

**Comment by Altaf12-design** [comment]
![Capture](https://user-images.githubusercontent.com/76280513/112735628-51b6ac00-8f6f-11eb-88c2-de9537cd7585.PNG)

**Comment by Altaf12-design** [comment]
https://docs.swmansion.com/react-native-reanimated/docs/installation/

**Comment by SSOURABH58** [comment]
Copy past Solution 😉 

step 1 - go to 🚗:
```
node_modules\react-native-redash\lib\module\Animations.js
```

step 2 - past this line on top 🗒️: 
```
 global.__reanimatedWorkletInit = () => {};
```

the result will look like this 👁️‍🗨️:
``` 
global.__reanimatedWorkletInit = () => {};
export var animationParameter=function animationParameter....
```

step 3 - restart the mero bundler 👍: 
```
r
or
expo start
```

**Comment by jakub-gonet** [comment]
@adamsimonini check out https://www.npmjs.com/package/patch-package

**Comment by Gamma169** [comment]
For those of you running into the problem v2.8.0 on web, I was able to resolve the issue by adding `global.__reanimatedWorkletInit = () => {};` to `/lib/reanimated2/core.js`  Note that it is the `lib` folder and not the `src` folder that made it work.

**Comment by LouisSyfer** [comment]
well done @Gamma169 👌

**Comment by LouisSyfer** [comment]
EDIT : global.__reanimatedWorkletInit = () => {}; added in UpdateProps.ts before export
It's ok on Android now too.
