### ISSUE TITLE
useSharedValue is not a function

### ISSUE THREAD

**Issue by shockdesign** [software-mansion/react-native-reanimated#1426]
## Description

Followed the steps to install alpha 8, then proceeded to setup my view, however none of the react-native-reanimated 2 hooks are available?

Looking at the default Animated object and I can't see the hooks there either.

![image](https://user-images.githubusercontent.com/138965/98809239-54f24500-2471-11eb-965d-ba036b24d045.png)

And looking node_modules/react-native-reanimated/src/reanimated2 has `Hooks.js` which has the correct hooks.

babel.config.js looks like:

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
}
```

### Screenshots

![Simulator Screen Shot - iPhone 11 - 2020-11-11 at 22 56 36](https://user-images.githubusercontent.com/138965/98809140-368c4980-2471-11eb-94ae-79ff79d414fe.png)

## Steps To Reproduce

1. Try using any of the new hooks via import

### Expected behavior

Hook is available

### Actual behavior

Hook isn't found

## Snack or minimal code example

```
import React from 'react'
import Animated, { useSharedValue } from 'react-native-reanimated'

export const Screen = ({ route, navigation }) => {
  const height = useSharedValue(0)

  return null
}
```

## Package versions

- React: 16.14.0
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.8
- NodeJS: v12.14.1

**Comment by mdcone** [comment]
Same thing happened to me because the bundler cached the old module. Run the bundler manually with the `--clear-cache` flag and see if that fixes things.

**Comment by shockdesign** [comment]
`npm cache clean --force` and manually deleting `node_modules/` and reinstalling still has the same issue..

@mdcone which bundler are you using `--clear-cache` with?

**Comment by mdcone** [comment]
@shockdesign, the react-native bundler. To get rid of its cache fire it up with `react-native start --clear-cache`.

**Comment by jakub-gonet** [comment]
As @mdcone said this is likely related to stale metro cache. You can try clearing watchman cache, [here's a gist](https://gist.github.com/EQuimper/a14c19461b7018dabca2dd6c3f123671) that should clear all JS artifacts. If you're using iOS remember to remove Pods too.

I'm closing this but if you'll have further problems with that don't hesitate to reply.

**Comment by canberkardic** [comment]
I have the same problem too.
Can't find any solution.
Deleting cache, watchman, node_modules, Pods is  not the solution.

**Comment by jakub-gonet** [comment]
@canberkardic do you use npm by any chance? We saw similar reports in the past. Try using yarn and if you can, please provide a reproducible repository – that will greatly help us resolve this error.
