### ISSUE TITLE
TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found.

### ISSUE THREAD

**Issue by mrmarktyy** [software-mansion/react-native-reanimated#1430]
## Description

A published version of app via Expo managed flow crashes on Android devices. But it works just fine on local development environment. It also works fine on iOS.

I followed the instructions on Expo document to installed the reanimated2 (Again, it works fine on both android and iOS in local development environment)
https://docs.expo.io/versions/latest/sdk/reanimated/

### Screenshots

![Screenshot_20201111-175540](https://user-images.githubusercontent.com/1808651/98874934-4e92b600-24cf-11eb-9ea1-cdd25a25b91d.png)

## Steps To Reproduce

1. Publish the app
```
$ expo publish
```
2. Open the published app via Expo on Android, it crashes 

### Expected behavior

It does not crash

## Snack or minimal code example

**NOTE: The bug will only reproduce when publishing the app to Expo and open in Expo Client on Android**
a) A bare minimum replicable codebase is available in this [snack](https://snack.expo.io/@ratecityadmin/41c34b)

b) Alternatively, following crna template

```bash
$ npx crna --template with-reanimated2
```

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.6
- NodeJS: 12.18.2
- Expo SDK: 39.0.3

**Comment by mdcone** [comment]
You can't use this library with debugging turned on because it uses TurboModules. For now, React Native TurboModules and debugging are mutually exclusive.

**Comment by mrmarktyy** [comment]
@mdcone Thanks for reply. It's a published app in Expo, how do I turn off the debugging ?

**Comment by karol-bisztyga** [comment]
> You can't use this library with debugging turned on because it uses TurboModules. For now, React Native TurboModules and debugging are mutually exclusive.

I think it's explained 👌

> @mdcone Thanks for the reply. It's a published app in Expo, how do I turn off the debugging?

This question isn't related to reanimated, looks more like being related to the expo.

I'm closing this for now, if you have any more doubts feel free to reopen or go with a new issue. Thank you 🙏
