### ISSUE TITLE
Animated keyboard events

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion/react-native-reanimated#1432]
## Description
A few months ago I made a PR to hooks repo, but after discussing we found that we need something native for the keyboard events
https://github.com/react-native-community/hooks/pull/205
I imagine something like a shared value that subscribed as a keyboard event on the native side. or a hook is like useAnimatedStyle.

**Comment by jakub-gonet** [comment]
I don't really understand how you want to use shared values to handle keyboard events. Could you describe your use case more clearly and fill all template sections?

**Comment by hosseinmd** [comment]
something like gesture handler events for example
```js
const anim = useSharedValue(0)
useAnimatedKeyboard({
  didShow(event){
     anim.value = withTiming(event.height)
  }
  didHide(_){
     anim.value = withTiming(0)
  }
})
```

**Comment by jakub-gonet** [comment]
I'll discuss this feature internally with the team but I'm not convinced about this feature. We want to focus on animations and listening to keyboard events isn't directly related to that.

**Comment by jakub-gonet** [comment]
There are a few problems with that.

First, we currently don't have any way to listen to non-direct events (that aren't connected to Views, keyboard event is a non-direct event). This feature is more related to generic event listening and not animations so we won't include it in this form in Reanimated.

We may consider adding this as a part of some other API in the future but for now, we don't want to make API more complex than it is today.

**Comment by jfrolich** [comment]
It would be great if we can animate with the keyboard. Currently, the only way to do that is to animated by ourselves, but the animation timing and curve are slightly different than the keyboard.
