### ISSUE TITLE
Use React Native Animated.Value in reanimated?

### ISSUE THREAD

**Issue by alexstrat** [software-mansion/react-native-reanimated#1433]
## Description

Can we use vanilla React Native Animated API's `Value` in reanimated?

This code throws `Invariant Violation: [16865,{"type":"value","value":"<<NaN>>"}] is not usable as a native method argument` for me:
```ts
import { Animated as RNAnimated } from 'react-native';
import Animated from 'react-native-reanimated';

const value = new RNAnimated.Value(0);
Animated.round(value);
```

I'm trying to use reanimated for animations with `@react-navigation/stack` which API only gives RNAnimated `Value`s.

### Package versions

- React: 16.9.0
- React Native: 0.61.5
- React Native Reanimated: 1.3.3
- `@react-navigation/stack` : 5.2.1

**Comment by jakub-gonet** [comment]
As far as I know, this is impossible. We use our own `Animated.Value` structure which is entirely different from RN Animated `Animated.Value`. 

However, you can try [registering a callback](https://reactnative.dev/docs/animatedvalue#addlistener) to value returned by `@react-navigation/stack` and calling `Animated.Value.setValue()` from Reanimated:

```js
import { Animated as RNAnimated } from 'react-native';
import Animated from 'react-native-reanimated';

const value = new RNAnimated.Value(0);
const reaValue = new Animated.Value(0);

value.addlistener(({value}) => reaValue.setValue(value));

Animated.round(reaValue);
```

but keep in mind that listeners and `.setValue` are async so your animation may be glitching or lagging a bit (especially when the JS thread is under heavy load).

If you have further questions feel free to ask.

**Comment by alexstrat** [comment]
Ok thanks for the answer!

Would it feasible to have a way to "follow" an RNAnimated Value on an other thread than the JS thread?

**Comment by jakub-gonet** [comment]
Not really because RNAnimated values are managed in the JS side by default and `useNativeDriver` moves a part of it to the native side, where you can't control how value is stored and modified. You potentially _could_ extend RNAnimated classes to get value updates but it's basically the same work that's required to create interop between RNAnimated and Reanimated.
