### ISSUE TITLE
Value of node abi39_0_0.host.exp.exponent.modules.api.reanimated.nodes.ParamNode@41e1b68 cannot be cast to a number

### ISSUE THREAD

**Issue by chj-damon** [software-mansion/react-native-reanimated#1436]
## Description

```ts
  const translateX = interpolate(animatedValue, {
    inputRange: [0, 0.5, 1],
    outputRange: ['0%', '50%', '0%'],
  });

<Animated.View style={{transform: [{ translateX }]}}>
```

### Screenshots
![image](https://user-images.githubusercontent.com/4902684/99072448-079be200-25ef-11eb-8ad5-497db3dd5901.png)

## Steps To Reproduce

https://github.com/chj-damon/mind-blowing-example

### Expected behavior
it should work fine on android devices
### Actual behavior
it reports error
## Package versions

- React: v16.13.1
- React Native: expo@39
- React Native Reanimated: 1.13.1

**Comment by jakub-gonet** [comment]
We only support numbers and strings with degrees in the `outputRange` currently.
