### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by mistikk** [software-mansion/react-native-reanimated#1439]
## Description

When I upgrade the v2.0.0-alpha.8 app stuck white screen on iOS simulator debug mode. I got this error in console; `Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`. Normal mode works as expected. Also v1.x has not this issue.

## Package versions

- React: 16.13.1
- React Native: 63.3
- React Native Reanimated: 2.0.0-alpha.8
- NodeJS: 10.21.0

**Comment by Benzer1406** [comment]
Same issue!

**Comment by ishmaell** [comment]
I've only started having this same issue after I installed `react-native-sqlite-storage`

**Comment by ishmaell** [comment]
Simple fix!

**Comment by Victorvikson1996** [comment]
> Kill the terminal/command prompt running your node JS and run your app again.

how do i do that

**Comment by karol-bisztyga** [comment]
Hey! Please try to run this using xcode and seek for the console. There should be more detailed error message, you can analyse it yourself or just copy all of the output from there here.

**Comment by Johan-dutoit** [comment]
FWIW I had the same issue (while upgrading to v2.9).   As Ishmaell suggested, just kill the bundler and rebuild/rerun from xcode/react-native run-ios and it started working again.

**Comment by VincentQuillien** [comment]
I have the same problem, here is the full log:


Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
Running "main" with {"rootTag":1,"initialProps":{}}
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
Unhandled JS Exception: Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by mistikk** [comment]
@ishmaell same result.
@karol-bisztyga I already did that, I couldn't see any specific issue on Xcode console
@Johan-dutoit I kill the node js task, also removed node modules, clear the caches, clean build folder from Xcode.. result is same

**Comment by vish2595** [comment]
Same issue

**Comment by dheeraj221b** [comment]
Same here

**Comment by eugenedw** [comment]
Please take a look at any errors that appear just prior to the AppRegistry complaint. In my case, I'd installed a new module/plugin using NPM, yet didn't link the module or run "pod install" to get it registered. After doing so, I was able to run the app.

example:
`react-native link @react-native-community/geolocation`

cd to ios and run:
`pod install`

**Comment by dheeraj221b** [comment]
Finally I was able to resolved this issue by replacing **extends TextInput** with **extends React.Component** in a custom TextInput component. I was experiencing this issue after upgrading the react native version from 0.61.2 to 0.63.3.

**Example:**
**Before Fix:**
import React from 'react';
import {TextInput} from 'react-native';
class CustomTextInput **extends TextInput**{
render(){
/**code**/
}
}

**After Fix:(Working code):**
import React from 'react';
import {TextInput} from 'react-native';
class CustomTextInput **extends React.Component**{
render(){
/**code**/
}
}

**Comment by mrbrentkelly** [comment]
+1, occurring for me on version `2.0.0-rc.0` on an iOS Simulator. Basically was wanting to try out reanimated2 in a project that was using reanimated1 but as soon as I try to use a shared value (`useSharedValue()`) I get the following error:

```
[Sat Nov 28 2020 21:37:27.599]  ERROR    Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
[Sat Nov 28 2020 21:37:27.600]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Sat Nov 28 2020 21:37:28.742]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

I have tried pretty much everything I can think of... `npx react-native --reset-cache`, `watchman watch-del-all
`, Clean iOS project, delete `Pods/`,  delete derived data.

My setup:

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 524.05 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/brent.kelly/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-21 | Intel x86 Atom_64, android-22 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | ARM 64 v8a, android-25 | Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-26 | Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google X86_ARM Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mrbrentkelly** [comment]
So I've managed to work out what was causing my issue [above](https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735294119) ^^. I was trying to use reanimated2 in a **brownfield** app where the `RCTBridge` gets initialized outside of the `AppDelete` (so `AppDelegate` does not implement the `RCTBridgeDelegate` protocol). In this circumstance the `jsExecutorFactoryForBridge` function from  [UIResponder+Reanimated.mm](https://github.com/software-mansion/react-native-reanimated/blob/master/ios/native/UIResponder+Reanimated.mm#L26) is never called, and therefore [global.__reanimatedModuleProxy](https://github.com/software-mansion/react-native-reanimated/blob/master/src/reanimated2/NativeReanimated.native.js#L3) is never setup for the JS layer to use.

**I've repro'd the issue** by forking the Reanimated2Playground repro and changing the AppDelegate to use a RCTBridge that's initialized from a separate class [here](https://github.com/mrbrentkelly/reanimated-2-playground/blob/master/ios/Reanimated2Playground/AppDelegate.swift#L19).

This works...

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, RCTBridgeDelegate {
  
  var window: UIWindow?
  
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {

    let bridge = RCTBridge(delegate: self, launchOptions: nil)
    let rootView = RCTRootView(bridge: bridge!,
                               moduleName: "Reanimated2Playground",
                               initialProperties: nil)

    self.window = UIWindow(frame: UIScreen.main.bounds);
   
    let rootViewController = UIViewController();
    rootViewController.view = rootView;
    
    self.window!.rootViewController = rootViewController;
    self.window?.makeKeyAndVisible();
                                
    return true
  }
  
  func sourceURL(for bridge: RCTBridge!) -> URL! {
    return RCTBundleURLProvider.sharedSettings()?.jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
  }
}
```

But this doesn't work...

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  
  var window: UIWindow?
  
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {

    let rootView = RCTRootView(bridge: BridgeManager.sharedInstance.bridge,
                               moduleName: "Reanimated2Playground",
                               initialProperties: nil)

    self.window = UIWindow(frame: UIScreen.main.bounds);
   
    let rootViewController = UIViewController();
    rootViewController.view = rootView;
    
    self.window!.rootViewController = rootViewController;
    self.window?.makeKeyAndVisible();
                                
    return true
  }
}

class BridgeManager: NSObject, RCTBridgeDelegate {
  lazy var bridge: RCTBridge = {
      return RCTBridge(delegate: self, launchOptions: nil)
  }()
  
  static let sharedInstance = BridgeManager()

  private override init() {
      super.init()
  }
  
  func sourceURL(for bridge: RCTBridge!) -> URL! {
    return RCTBundleURLProvider.sharedSettings()?.jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
  }
}
``` 

So it appears there is an issue with Reanimated2 and brownfield React Native apps (or apps that don't follow the traditional template from React Native [hello world](https://github.com/facebook/react-native/blob/master/template/ios/HelloWorld/AppDelegate.m)). **Should I raise a separate issue for this?** (_Feels quite important for Reanimated2 to work in Brownfield scenarios_)

**Comment by jakub-gonet** [comment]
@mrbrentkelly, sure thing! Please include a link to the repo reproducing this issue if that's not a problem, it'll make our lives easier when debugging & fixing this one.

**Comment by mrbrentkelly** [comment]
Sure, here it is...

https://github.com/mrbrentkelly/reanimated-2-playground/blob/master/ios/Reanimated2Playground/AppDelegate.swift#L19

**Comment by jfrolich** [comment]
I also run into this when using reanimated rc1 with `react-native-navigation` (It used to work in beta 8)

**Comment by spacesuitdiver** [comment]
`Just ran into this issue this evening. Similar issue using `react-native-navigation`.

**Comment by HamaBarhamou** [comment]
je viens de rencontré ce probeme egalement en executant https://reactnative.dev/docs/navigation de le documentation react-native

**Comment by ElForastero** [comment]
Still getting the issue with rc.2.

**Comment by declanelcocks** [comment]
Also get this when using v2...nothing special in my setup and v1 works fine.

**Comment by barbozafernando** [comment]
> Kill the terminal/command prompt running your node JS and run your app again.

Thank you. Doing this solved my problem.

**Comment by jakub-gonet** [comment]
You can't really use the debugger with turbo modules such as Reanimated v2. See [this comment](https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922) for more information.

**Comment by slorop41314** [comment]
I also run into this when using reanimated rc3 with react-native-navigation

**Comment by madandrija** [comment]
> You can't really use the debugger with turbo modules such as Reanimated v2. See [this comment](https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922) for more information.

The problem here is not that you can't use debugger with turbo modules (e.g. you can't debug Reanimated v2 code), the problem is that you can't use the debugger at all in your app, otherwise, if it's turned on, the app will crash as soon as it hits a screen where Reanimated v2 is used

**Comment by LaVielle** [comment]
I found this solution in the react-native-notification issues, which solved the problem for me: https://github.com/wix/react-native-notifications/issues/455#issuecomment-726094429
Essentially updating the hermes-engine to a patch version that solves a proxy issue 🧞

**Comment by jakub-gonet** [comment]
> The problem here is not that you can't use debugger with turbo modules (e.g. you can't debug Reanimated v2 code), the problem is that you can't use the debugger at all in your app, otherwise, if it's turned on, the app will crash as soon as it hits a screen where Reanimated v2 is used
>
> Edit: Flipper and Hermes Debugger work as expected, so I guess we wait for RN 0.64 to have Hermes for iOS as well

I meant exactly that. When you use any turbo module in your app, it'll crash after you try debugging the code that makes calls to it. That's why you can debug screens without Rea2 - Rea2 code hasn't yet run so it didn't call C++ code and didn't crash.

**Comment by rnnyrk** [comment]
Just updated to reanimated v2.x and RN 0.64, running into this issue as well. Any suggestions or fixes so far?

**Comment by ricardozv** [comment]
Any suggestions ? 

System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Memory: 206.85 MB / 7.65 GB
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.12.1 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by pkvov** [comment]
i face the same problem, then i delete App.js in the src folder, witch duplicate with App.tsx

**Comment by amirhosseinkabiri** [comment]
I hade the Same Issue but the problem was because I had the colors in a separated folder and in one of components I refers to a non-existing color... . But it didn't say where exactly the problem is! Hope it helps you...

**Comment by MontreaI** [comment]
I am running into this similar issue on Android and I am using React Native Brownfield.


2021-12-09 23:20:47.788 13933-14071/com.rivian.android.consumer E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
          This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by dov11** [comment]
@mrbrentkelly, BridgeManager in your example should be a subclass of UIResponder, because reanimated relies on the class that is used as a bridge delegate to be a subclass of UIResponder. See https://github.com/software-mansion/react-native-reanimated/pull/1323, [UIResponder+Reanimated](https://github.com/software-mansion/react-native-reanimated/blob/91d58df3ac90305c8abff928582281dfc23cfa0f/ios/native/UIResponder%2BReanimated.mm#L18).

I guess alternatively you can patch UIResponder+Reanimated. I had the same [issue](https://github.com/software-mansion/react-native-reanimated/issues/2791#issuecomment-1004779673)

**Comment by mrbrentkelly** [comment]
> @mrbrentkelly, BridgeManager in your example should be a subclass of UIResponder, because reanimated relies on the class that is used as a bridge delegate to be a subclass of UIResponder. See #1323, [UIResponder+Reanimated](https://github.com/software-mansion/react-native-reanimated/blob/91d58df3ac90305c8abff928582281dfc23cfa0f/ios/native/UIResponder%2BReanimated.mm#L18).
> 
> I guess alternatively you can patch UIResponder+Reanimated. I had the same [issue](https://github.com/software-mansion/react-native-reanimated/issues/2791#issuecomment-1004779673)

Yep exactly, that's what I was alluding to in my original message 👍 i.e. requiring your class to extend from UIResponder or else Reanimated won't be initialised correctly felt like it could be a bug that needed addressed for projects that don't setup their bridge as part of the AppDelegate.

**Comment by AlexHashgraph** [comment]
@dov11, @mrbrentkelly  I pretty much have the same issue, using react-native 0.64 & reanimation 2.3.1; I tried your solutions but still to no effect; when a class extends UIResponder; I get an Error: Value is undefined, expected an Object; If I leave it as just an NSObject like in the example shared [here](https://github.com/mrbrentkelly/reanimated-2-playground/blob/master/ios/Reanimated2Playground/BridgeManager.swift): I get the generic reanimated error Unhandled JS Exception: Error: If you want to use Reanimated 2 then go through our installation steps.

Am I missing a previous step by any chance? any help is much appreciated

**Comment by AlexHashgraph** [comment]
Update: I manage to get it to work with all reanimated versions until 2.3.0 ; 

there is definitely a bug on newer versions for this exact scenario in the way the jsExecutorFactoryForBridge is being called.

**Comment by samrith-s** [comment]
For anyone facing this issue with Android, here are some things which we added which fixes it for us.
- In the `build.gradle` file at [this line](https://github.com/software-mansion/react-native-reanimated/blob/main/android-npm/build.gradle#L34), it ceases to recognise other flavours. We fixed it by making the following change:
  ```diff
  -    Pattern pattern = Pattern.compile("(assemble|bundle|install|generate)(\\w*)(Release|Debug)")
  +    Pattern pattern = Pattern.compile("(assemble|bundle|install|generate)(\\w+)(Release|Debug)")
  ```
- The we realised the other issue was that with Reanimated, there were two projects in our code. Reanimated's `build.gradle` has a check for project but it does not exclude the `designsample` project. So we changed [this line](https://github.com/software-mansion/react-native-reanimated/blob/main/android-npm/build.gradle#L59) to:
  ```diff
  - if(project.getProperties().get("android") && Integer.parseInt(minor) < 65)
  + if(project.getProperties().get("android") && Integer.parseInt(minor) < 65 && !project.name.equalsIgnoreCase("designsample"))
  ```

And things started working for us!

**Comment by kasaiee** [comment]
According to the https://typeorm.io/changelog#deprecations, `CreateConnection` is deprecated. If you are using it, upgrade `typeorm`

**Comment by ThushalIntervest** [comment]
> So I've managed to work out what was causing my issue [above](https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735294119) ^^. I was trying to use reanimated2 in a **brownfield** app where the `RCTBridge` gets initialized outside of the `AppDelete` (so `AppDelegate` does not implement the `RCTBridgeDelegate` protocol). In this circumstance the `jsExecutorFactoryForBridge` function from [UIResponder+Reanimated.mm](https://github.com/software-mansion/react-native-reanimated/blob/master/ios/native/UIResponder+Reanimated.mm#L26) is never called, and therefore [global.__reanimatedModuleProxy](https://github.com/software-mansion/react-native-reanimated/blob/master/src/reanimated2/NativeReanimated.native.js#L3) is never setup for the JS layer to use.
> 
> **I've repro'd the issue** by forking the Reanimated2Playground repro and changing the AppDelegate to use a RCTBridge that's initialized from a separate class [here](https://github.com/mrbrentkelly/reanimated-2-playground/blob/master/ios/Reanimated2Playground/AppDelegate.swift#L19).
> 
> This works...
> 
> ```swift
> @UIApplicationMain
> class AppDelegate: UIResponder, UIApplicationDelegate, RCTBridgeDelegate {
>   
>   var window: UIWindow?
>   
>   func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
> 
>     let bridge = RCTBridge(delegate: self, launchOptions: nil)
>     let rootView = RCTRootView(bridge: bridge!,
>                                moduleName: "Reanimated2Playground",
>                                initialProperties: nil)
> 
>     self.window = UIWindow(frame: UIScreen.main.bounds);
>    
>     let rootViewController = UIViewController();
>     rootViewController.view = rootView;
>     
>     self.window!.rootViewController = rootViewController;
>     self.window?.makeKeyAndVisible();
>                                 
>     return true
>   }
>   
>   func sourceURL(for bridge: RCTBridge!) -> URL! {
>     return RCTBundleURLProvider.sharedSettings()?.jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
>   }
> }
> ```
> 
> But this doesn't work...
> 
> ```swift
> @UIApplicationMain
> class AppDelegate: UIResponder, UIApplicationDelegate {
>   
>   var window: UIWindow?
>   
>   func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
> 
>     let rootView = RCTRootView(bridge: BridgeManager.sharedInstance.bridge,
>                                moduleName: "Reanimated2Playground",
>                                initialProperties: nil)
> 
>     self.window = UIWindow(frame: UIScreen.main.bounds);
>    
>     let rootViewController = UIViewController();
>     rootViewController.view = rootView;
>     
>     self.window!.rootViewController = rootViewController;
>     self.window?.makeKeyAndVisible();
>                                 
>     return true
>   }
> }
> 
> // Bridge is initialized in a class that doesn't extend from UIResponder so some of 
> // the Reanimated init code from UIResponder+Reanimated.mm doesn't fire. 
> class BridgeManager: NSObject, RCTBridgeDelegate {
>   lazy var bridge: RCTBridge = {
>       return RCTBridge(delegate: self, launchOptions: nil)
>   }()
>   
>   static let sharedInstance = BridgeManager()
> 
>   private override init() {
>       super.init()
>   }
>   
>   func sourceURL(for bridge: RCTBridge!) -> URL! {
>     return RCTBundleURLProvider.sharedSettings()?.jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
>   }
> }
> ```
> 
> So it appears there is an issue with Reanimated2 and brownfield React Native apps (or apps that don't follow the traditional template from React Native [hello world](https://github.com/facebook/react-native/blob/master/template/ios/HelloWorld/AppDelegate.m)). **Should I raise a separate issue for this?** (_Feels quite important for Reanimated2 to work in Brownfield scenarios_)

This will works fine App but the debugger is not working for this change.

**Comment by dr1verrr** [comment]
That was worked for me finally. Add a few lines in MainApplication.java from this file
https://github.com/software-mansion-labs/reanimated-2-playground/blob/master/android/app/src/main/java/com/reanimated2playground/MainApplication.java

Any cache cleaning, babel setup advices did not help. It is just like retelling docs.

Add this imports.
`import com.facebook.react.bridge.JSIModulePackage;`
`import com.swmansion.reanimated.ReanimatedJSIModulePackage;`

Also add this method in ReactNativeHostWrapper
`protected JSIModulePackage getJSIModulePackage() {
        return new ReanimatedJSIModulePackage();
       }
`

And finally delete package-lock.json, reinstall node_modules, clean npm/yarn cache.

**Comment by YOEL311** [comment]
@mrbrentkelly 
thanks for your response
this work 
but to order put in my bridge property delegate I need to make a path on the original code
because RCTBridg doesn't get bundle URL and delegate in one initial method
we have two methods to initial RCTBridg 
https://github.com/facebook/react-native/blob/4e117cb09d208ca02f513d2101592d0ac10d4739/React/Base/RCTBridge.h#L82
````
/**
 * Creates a new bridge with a custom RCTBridgeDelegate.
 *
 * All the interaction with the JavaScript context should be done using the bridge
 * instance of the RCTBridgeModules. Modules will be automatically instantiated
 * using the default contructor, but you can optionally pass in an array of
 * pre-initialized module instances if they require additional init parameters
 * or configuration.
 */
- (instancetype)initWithDelegate:(id<RCTBridgeDelegate>)delegate launchOptions:(NSDictionary *)launchOptions;

/**
 * DEPRECATED: Use initWithDelegate:launchOptions: instead
 *
 * The designated initializer. This creates a new bridge on top of the specified
 * executor. The bridge should then be used for all subsequent communication
 * with the JavaScript code running in the executor. Modules will be automatically
 * instantiated using the default contructor, but you can optionally pass in an
 * array of pre-initialized module instances if they require additional init
 * parameters or configuration.
 */
- (instancetype)initWithBundleURL:(NSURL *)bundleURL
                   moduleProvider:(RCTBridgeModuleListProvider)block
                    launchOptions:(NSDictionary *)launchOptions;

````
how can I set it together?
