### ISSUE TITLE
What's the right way to use RunOnJS?

### ISSUE THREAD

**Issue by Johan-dutoit** [software-mansion/react-native-reanimated#1445]
## Description

I've looked at both the [PR](https://github.com/software-mansion/react-native-reanimated/pull/1431/files) that added a note on `RunOnJS` (p.s. this doesn't appear in the docs) and I've looked at the example found [here](https://github.com/software-mansion/react-native-reanimated/blob/ec53d29fd329815a9aaddf8f01abb1b24be05f27/Example/src/SwipeableListExample.js#L116-L118).  However I still get the redbox that says `Tried to synchronously call function {bound dispatchAction} from a different thread....`

What I'm trying to achieve, is to update local state once the animation completes.

## Code

```js
export function someAnimation(callback?: (isCancelled: boolean) => void) {
  'worklet';
  return withSequence(
    withTiming(1, {duration: 300, easing: Easing.linear}),
    withDelay(100, withTiming(2, {duration: 500, easing: Easing.linear}, callback)),
  );
}

// Inside a functional component 
const [value, setValue] = React.useState(false);

// Trigger it here on first render
React.useEffect(() => {
    shared.value = someAnimation(runOnJS(() => setValue(true)));
  }, []);
```

I've tried multiple variants (based on the two links above) to no avail.
i.e. 
```js
// And then I just tried doing random stuff in hopes it works
function setTheValue() { //including const declaration
  'worklet'; // and without 'worklet'
  setValue(true);
}
// Also
shared.value = someAnimation(runOnJS(() => { 'worklet'; setValue(true)}));
```

### Package versions

- React:  16.13.1
- React Native:0.63.3
- React Native Reanimated: 2.0.0-alpha.8 & 2.0.0-alpha.9 (tried both)

**Comment by dhirajanand014** [comment]
I too have the same issue [https://github.com/software-mansion/react-native-reanimated/issues/1393#issuecomment-726790287](url) . Also see the same issues below

**Comment by Johan-dutoit** [comment]
I'm unable to get the above scenario working, but I do have another scenario that does work..

```js
function MyComponent({ functionToCall }) {
  ...
  const animatedStyle = useAnimatedStyle(() => {
    const size = withTiming(1, { duration: 300 }, runOnJS(functionToCall));
    return {
      height: size,
      width: size
    }
  })
  ...
}

function MainComponent() {
  return (
    <MyComponent 
      functionToCall={() => {
        // Do stuff
      }}
    />
  );
}
```

**Comment by Andarius** [comment]
You can do `const size = withTiming(1, { duration: 300 }, () => runOnJS(functionToCall)())`

**Comment by Johan-dutoit** [comment]
Hi @Andarius, the code snippet [here](https://github.com/software-mansion/react-native-reanimated/issues/1445#issuecomment-728802579) works fine.  It's the snippet in OP that doesn't.  

I will however try your approach on my original issue.  Will report back.

**Comment by Johan-dutoit** [comment]
Sadly no, that results in the same error.  Here is what I tried.

`shared.value = someAnimation(() => runOnJS(someFunction)());`

**Comment by Andarius** [comment]
Why is `someAnimation` a worklet ? It's called from the JS Thread

**Comment by Johan-dutoit** [comment]
I'd say my lack of understanding worklets.  I removed 'worklet', however same error.

**Comment by Andarius** [comment]
The following works

```
  function updateShare(){
    setValue(true)
  }

  function callback(isCancelled: boolean){
      'worklet'
    console.log('isCancelled: ', isCancelled)
    runOnJS(updateShare)()
  }

  React.useEffect(() => {
    shared.value = someAnimation(callback)
}, [])
```

**Comment by riordanpawley** [comment]
I found that I had to rewrite all of my animated components to use useSharedValue instead of useState

**Comment by Johan-dutoit** [comment]
@Andarius this does work, thanks.  A bit convoluted.

I simplified it to the following, which still seemed to work

```
function callback(isCancelled: boolean){
  'worklet'
  runOnJS(setValue)(true);
}

React.useEffect(() => {
    shared.value = someAnimation(callback)
}, [])
```

**Comment by dhirajanand014** [comment]
> @Andarius this does work, thanks. A bit convoluted.
> 
> I simplified it to the following, which still seemed to work
> 
> ```
> function callback(isCancelled: boolean){
>   'worklet'
>   runOnJS(setValue)(true);
> }
> 
> React.useEffect(() => {
>     shared.value = someAnimation(callback)
> }, [])
> ```
> 
> even further simplified to
> 
> ```
> React.useEffect(() => {
>     shared.value = someAnimation(() => { 
>       'worklet';
>       runOnJS(setValue)(true)
>     });
> }, [])
> ```
> 
> I'll need to do some further digging to understand when and where to use worklet.
> 
> Once again, thanks for the help!

This doesn't work either!
