### ISSUE TITLE
Android interpolate color - Attempt to invoke virtual method 'int java.lang.Double.intValue()' on a null object reference

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-reanimated#1451]
## Description
I'm attempting to combine useAnimatedProps and interpolateColor with react-native-linear-gradient, everything works fine on iOS, however on Android I seem to get an exception.

I don't think this is a react-native-linear-gradient issue to be clear, it looks like setProps sends null values even though the JS thread reports them as not being null;

```
// JS
11-18 09:46:50.445 12090 12298 I ReactNativeJS: { colors: [ -16763747, -14621774, -14024762 ] }
Native     @ReactProp(name=PROP_COLORS)
11-18 09:46:50.469 12090 12090 I System.out: [null,null,null]

```

**Working version on iOS**
<img src="http://g.recordit.co/WrWecn2B6L.gif"/>

```
Attempt to invoke virtual method 'int java.lang.Double.intValue()' on a null object reference
11-18 09:10:52.905  7892  7892 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeArray.getInt(ReadableNativeArray.java:97)
11-18 09:10:52.905  7892  7892 E unknown:ReactNative: 	at com.BV.LinearGradient.LinearGradientView.setColors(LinearGradientView.java:51)
11-18 09:10:52.905  7892  7892 E unknown:ReactNative: 	at com.BV.LinearGradient.LinearGradientManager.setColors(LinearGradientManager.java:35)
11-18 09:10:52.905  7892  7892 E unknown:ReactNative: 	... 23 more

```

## Steps To Reproduce

[The Repository](https://github.com/kyle-ssg/reanimated2-experiments/)

[The Component](https://github.com/kyle-ssg/reanimated2-experiments/blob/master/App/components/AnimatedGradient.tsx)

### Expected behavior

Animation works.

### Actual behavior

App crashes with above exception. It looks like however reanimated v2 sets props on android, it results in sending [null,null,null].

## Package versions

```
 "react-native": "0.63.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^2.0.0-alpha.9",
```

**Comment by karol-bisztyga** [comment]
Hey! When I was trying to reproduce this issue I got the following error:

<details>
<summary>stack trace</summary>

```
[Tue Nov 24 2020 09:30:51.857]  ERROR    TypeError: Cannot read property 'map' of undefined

This error is located at:
    in LinearGradient (at AnimatedGradient.tsx:100)
    in AnimatedGradient (at stories/index.js:35)
    in WithSetValue (at stories/index.js:33)
    in RCTView (at View.js:34)
    in View (at stories/index.js:30)
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView) (at setup.js:20)
    in RCTView (at View.js:34)
    in View (created by StoryView)
    in StoryView (created by OnDeviceUI)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in emotion(View) (created by OnDeviceUI)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (created by OnDeviceUI)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (created by OnDeviceUI)
    in RCTView (at View.js:34)
    in View (created by AbsolutePositionedKeyboardAwareView)
    in RCTView (at View.js:34)
    in View (created by AbsolutePositionedKeyboardAwareView)
    in AbsolutePositionedKeyboardAwareView (created by OnDeviceUI)
    in RCTView (at View.js:34)
    in View (at KeyboardAvoidingView.js:218)
    in KeyboardAvoidingView (created by OnDeviceUI)
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView) (created by OnDeviceUI)
    in OnDeviceUI (created by StorybookRoot)
    in ThemeProvider (created by StorybookRoot)
    in StorybookRoot (at App.tsx:5)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39), js engine: hermes
```

</details>

I'm on origin/master and the only change I did was upgrading reanimated to alpha 9(you have alpha 8 in the repo and here you provided alpha 9 as a reproducing package version).

Is the code in the repository valid and I'm missing something?

**Comment by karol-bisztyga** [comment]
got the same error on master without any changes on Android, on iOS it works

**Comment by karol-bisztyga** [comment]
Ok now I see I missed that commented code, the issue reproduced.

**Comment by kyle-ssg** [comment]
Hey @karol-bisztyga actually I think I may have seen what is happening here..


I believe the problem is that for some reason colours are getting processed twice due to this line in the render https://github.com/react-native-linear-gradient/react-native-linear-gradient/blob/master/index.android.js#L87. However, this is slightly even more confusing as I thought that useAnimatedProps didn't trigger re-renders and set props natively, or at least used refs.

**Comment by karol-bisztyga** [comment]
Yes, changing this line to `colors={colors}` makes it work, however, that still leaves you with an infinite loop inside your app but that, as I understand, is just temporary bad design.

**Comment by kyle-ssg** [comment]
Yeah, the main issue is this crashing with set native props - iOS seems to work fine.

**Comment by karol-bisztyga** [comment]
So the solution for you would be not to use `processColor` in those places:
https://github.com/kyle-ssg/reanimated2-experiments/blob/master/App/components/AnimatedGradient.tsx#L34
https://github.com/kyle-ssg/reanimated2-experiments/blob/master/App/components/AnimatedGradient.tsx#L44
https://github.com/kyle-ssg/reanimated2-experiments/blob/master/App/components/AnimatedGradient.tsx#L54

**Comment by kyle-ssg** [comment]
Oh right thanks, and that'll mean I don't need to use the runOnJS for Android?

**Comment by karol-bisztyga** [comment]
With that said I realize that using `processColor` multiple times may happen and cause problems. We've encountered such situations and all we can do is try to secure it on the reanimated2 side(meaning that when you call `processColor` from rea2 library on a color that's already been processed we could handle such situations) but if it happens in RN side like here I don't think there's anything we can do.

**Comment by kyle-ssg** [comment]
Ok sure I guess this can be closed, I think I'm still a bit confused as to why I had to run Android prop updates via state / runOnJS (essentially an infinite loop as you say) rather than useAnimatedProps but I guess this could be react-native-linear-gradient side rather than reanimated.

Ok will just do some more figuring out, thanks.

**Comment by karol-bisztyga** [comment]
If you have your doubts, you can open a new issue with the question about what bothers you. Here we wanted to find out why the app crashes.

Thanks for cooperation and quick replies, best regards ✌️
