### ISSUE TITLE
Nested text can not be styled with reanimated - backgroundColor, color and etc

### ISSUE THREAD

**Issue by Strate** [software-mansion/react-native-reanimated#1455]
## Description

Hello, I'm trying to stylize `<Text>` which is nested to other `<Text>`, but in this case styling is not applied.

## Steps To Reproduce

See snack example

### Expected behavior
Nested text's backgroundColor, color and other styles which can be applied to nested text support animation

### Actual behavior
Nested text's backgroundColor, color and other styles which can be applied to nested text don't support animation

## Snack or minimal code example

https://snack.expo.io/ZrEZ2NTsc

## Package versions

- React:
- React Native: 0.63.3
- React Native Reanimated: 1.13.0

**Comment by hoangtrucit** [comment]
Why do you want to put the `Animated.Text` in `Animated.Text`

```js 
<Animated.Text style={{ marginTop: 20 }}>
        <Animated.Text
          style={{
            fontSize: 20,
            backgroundColor: Animated.interpolateColors(pressedState, {
              inputRange: [0, 1],
              outputColorRange: ['transparent', '#bbb'],
            }),
          }}>
          This text can not be animated
        </Animated.Text>
</Animated.Text>
```

I think we can resolve it with `View`

```js 
<View style={{ marginTop: 20 }}>
        <Animated.Text
          style={{
            fontSize: 20,
            backgroundColor: Animated.interpolateColors(pressedState, {
              inputRange: [0, 1],
              outputColorRange: ['transparent', '#bbb'],
            }),
          }}>
          This text can not be animated
        </Animated.Text>
</View>
```

**Comment by Strate** [comment]
@hoangtrucit I do it because I want to stylize only part of the text (in real life structure look like this: `<Text><Text>this need to be stylized</Text><Text> and this is not</Text></Text>`

**Comment by piaskowyk** [comment]
Hey @Strate 
I found a bug in your code in line 44, you should write:
`backgroundColor: Animated.interpolateColors(pressedState.value, {`
instead of
`backgroundColor: Animated.interpolateColors(pressedState, {`

**Comment by piaskowyk** [comment]
Hey @Strate 
I investigated this issue. If you write somethings like this:
```
<Text>
  string1
  <Text>
    string2
  </Text>
</Text>
```
[The React Native change the structure](https://reactnative.dev/docs/text#nested-text) to:
```
<RCTTextView>
  string1
  <RCTVirtualText>
    string2
  </RCTVirtualText>
</RCTTextView>
```
The `RCTTextView` is an native component but the `RCTVirtualText` is not and that is the reason why you can’t animate inner `<Text>` because in Reanimated you can animate only native nodes on layout. This can be a feature to implement in future, but now you could use solution by @hoangtrucit - change parent `Text` component to `View`

```
// this
<Text>
  <Text>this need to be stylized</Text>
  <Text> and this is not</Text>
</Text>

// to
<View>
  <Text>this need to be stylized</Text>
  <Text> and this is not</Text>
</View>
```

**Comment by yuriyyakym** [comment]
@piaskowyk This issue should be re-opened, because using `View` wrapper does not work with diacritics that are treated as a separate symbol:

https://github.com/software-mansion/react-native-reanimated/assets/18438911/3e21a8b3-b08c-4592-bd85-cf1d06fc9a20

**Comment by yuriyyakym** [comment]
I've got it working by wrapping Animated.Text into an additional Text:

```tsx
<Text style={styles.word}>
  {value.slice(0, highlightSymbolAt)}
  <Text>
    <Animated.Text style={[animatedStyle]}>{value[highlightSymbolAt]}</Animated.Text>
  </Text>
  {value.slice(highlightSymbolAt + 1)}
</Text>
```

https://github.com/software-mansion/react-native-reanimated/assets/18438911/384eb438-bc2c-4724-9d1f-a553b343538b

**Comment by mlazari** [comment]
It would be nice if this could work. I don't think it is possible to show text inline like this without nesting a Text in another Text:
![IMG_0334](https://github.com/software-mansion/react-native-reanimated/assets/4928274/2204a8c2-31e2-492d-b747-0e23a34c4335)
Changing the wrapper to a View (and thus not using nested Text) fixes the animations, but the animated text is not inline anymore with the rest of the text:
![IMG_0335](https://github.com/software-mansion/react-native-reanimated/assets/4928274/2e1df1b5-f77d-4734-a7f8-5bdf2cdb5d31)

**Comment by audrius-savickas** [comment]
@mlazari have you anyone else figured out if this is possible? @yuriyyakym for me your solution doesn't work, nested text still isn't animatable

**Comment by mlazari** [comment]
@audrius-savickas I have not.

**Comment by biw** [comment]
It might be worth opening this issue back up since this is no longer a note about this in the 3.x / 4.x docs 😄

**Comment by proambb** [comment]
It works on iOS, but on Android it does not work. Only wrapping with `View` makes it work on Android, but in this case text is not aligned vertically correctly (there is an [issue](https://github.com/facebook/react-native/issues/31955) in the ReactNative repo). 

Here is reproduction code I used with ReactNative `0.76` and `reanimated` version `3.16.7`. 
```tsx
import {Text, View, Button} from 'react-native';
import Animated, {interpolateColor, useAnimatedStyle, useSharedValue, withTiming} from 'react-native-reanimated';
import {useCallback} from "react";

const FONT_SIZE = 15;
export default function TabTwoScreen() {
    const opacity = useSharedValue(1);
    const toggleVisibility = useCallback(() => {
        opacity.value = withTiming(opacity.value === 1 ? 0 : 1)
    }, []);

    const animatedStyle = useAnimatedStyle(() => ({
        fontSize: FONT_SIZE,
        color: interpolateColor(opacity.value, [0, 1], ['rgba(0,0,0,0)', 'rgba(0,0,0,1)']),
    }))

    return (
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
            <Button title="Toggle visibility" onPress={toggleVisibility}/>
            <View style={{width: 170}}>
                <Text style={{fontSize: FONT_SIZE}}>
                    Some long long long text with{' '}
                    <Animated.Text style={animatedStyle}>disappear</Animated.Text>
                </Text>
            </View>
            <Animated.Text style={animatedStyle}>Not wrapped disappear</Animated.Text>
        </View>
    );
}
```

"disappear" word keeps being visible although it should disappear. 
Wrapping it with `View` results in the following layout. "disappear" word is misplaced. 

<img width="1164" height="2214" alt="Image" src="https://github.com/user-attachments/assets/c3cea042-83b4-4ef3-bd39-102ab90d49c6" />

@piaskowyk could you please take a look at the issue again? There is no word in the docs about nested `Text` components.

**Comment by quentez** [comment]
I'm having the same issue here. It works fine on iOS but not on Android.
