### ISSUE TITLE
Inconsistent EXC_BAD_ACCESS REAIOSScheduler crashes during development

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-reanimated#1459]
## Description

Now that we have a strong use-case for animation I want to start using this in a project, however it seems that whilst developing and I think with hot reloading we are seeing consistent crashes whilst saving files.

I appreciate there's not much to go on other than the fact we are developing / saving files however some sort of direction into potential causes we'd be really grateful.

### Screenshots
![image](https://user-images.githubusercontent.com/8608314/99684223-1a903580-2a79-11eb-8577-e25860a8b225.png)

## Steps To Reproduce

Make adjustments to an iOS application using reanimated, eventually after a few hot reloads the app crashes.

### Expected behavior
The app does not crash

### Actual behavior
The app crashes

## Snack or minimal code example
I can't really share that

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.8
- NodeJS: 12.15.0

**Comment by kyle-ssg** [comment]
> Validator encountered following problems:
> 
Sorted

**Comment by kyle-ssg** [comment]
Assuming that alpha 9.1 is stable I'll try on that and report back on this issue.

**Comment by owinter86** [comment]
I have the commit #1457 patched locally, but still have this error, it will crash every time you hard reload the metro server, I believe fast refresh will crash when the refreshing is deep enough to cause a full reload.

`0x00000001008d0ba4 ___ZN10reanimated15REAIOSScheduler12scheduleOnUIENSt3__18functionIFvvEEE_block_invoke + 100 (REAIOSScheduler.mm:24)`

**Comment by jakub-gonet** [comment]
@kyle-ssg, you can try testing this on our [master builds](https://docs.swmansion.com/react-native-reanimated/docs/installation#using-master-branch-builds) or patch it locally if you don't want to wait for the release.

**Comment by kyle-ssg** [comment]
@jakub-gonet If possible I'd rather just wait for the upcoming release, though we will be developing daily on the app where this issue replicated.

@owinter86 Just to clear things up, I didn't expect https://github.com/software-mansion/react-native-reanimated/pull/1457 to fix this issue it's just a big issue preventing us from using alpha 9.1. That's interesting though things sound slightly different in your case, refreshing doesn't cause the crash every time for us.

**Comment by kyle-ssg** [comment]
Testing this today on alpha 9.2
