### ISSUE TITLE
How should I control the opacity of carousel pagination?

### ISSUE THREAD

**Issue by nelsonprsousa** [software-mansion/react-native-reanimated#1460]
## Description
Hi guys, I am trying react-native-reanimated 2 for the first time, so this is a n00b question for sure.

I've implemented this carousel and this progress indicator component, but feels like my solution is a _hacky_ way of doing this. Basically, I am using `useAnimatedScrollHandler` hook on the carousel component to know what's the current item, and using the `useAnimatedStyle` hook in the progress indicator component to read it. Once I read it, I can check if the index of the current item is equal to the shared value (this is the _hacky_ way, I believe).

To avoid this, how can I calculate the opacity using the `useAnimatedStyle` hook? I know that `useAnimatedStyle` returns a `AnimatedStyle` component but I am not sure how I should calculate the opacity...

## Code

**AnimatedCarousel.tsx**
```typescript
const AnimatedCarousel: React.FC<IProps> = ({
    items,
    scale,
    cardWidth,
    margin,
}) => {
    const scroll = useSharedValue(0);
    const scrollIndicator = useSharedValue(0);
    const handleScroll = useAnimatedScrollHandler({
        onScroll: event => {
            const current = event.contentOffset.x / (cardWidth + margin);
            scroll.value = current;
            scrollIndicator.value = Math.round(current); // Getting the current item (0, 1, 2, etc)
        },
    });

    const paddingHorizontal = (theme.mixins.width - cardWidth) / 2;

    return (
        <>
            <AnimatedScrollView
                snapToInterval={cardWidth + margin}
                decelerationRate="fast"
                horizontal
                showsHorizontalScrollIndicator={false}
                onScroll={handleScroll}
                scrollEventThrottle={16}
                contentContainerStyle={{
                    paddingHorizontal,
                }}
            >
                {items.map((item, index) => (
                    <AnimatedCard
                        title={item.title}
                        subtitle={item.subtitle}
                        imagePath={item.imagePath}
                        navigationProps={item.navigation}
                        index={index}
                        scroll={scroll}
                        scale={scale}
                        isLastOne={isLastOne(index, items)}
                        cardWidth={cardWidth}
                        margin={margin}
                        key={item.title}
                    />
                ))}
            </AnimatedScrollView>
            <ProgressIndicator
                numberOfItems={items.length}
                scrollIndicator={scrollIndicator}
            />
        </>
    );
};
```

**ProgressIndicator.tsx**
```typescript
type IProps = {
    numberOfItems: number;
    scrollIndicator: Animated.SharedValue<number>;
};

const ProgressIndicator: React.FC<IProps> = ({
    numberOfItems,
    scrollIndicator,
}) => {
    const AnimatedStyles = (i: number): any => {
        return useAnimatedStyle(() => {
            return {
                opacity: i === scrollIndicator.value ? 1 : 0.3, // Checking if the current item is the one to "highlight"
            };
        });
    };

    const indicators = Array(numberOfItems)
        .fill({})
        .map((_, i) => {
            return <Dot key={i} style={[AnimatedStyles(i)]} />;
        });

    return <ProgressIndicatorWrapper>{indicators}</ProgressIndicatorWrapper>;
};
```

**Possible solution?**
```typescript
const animatedStyle = useAnimatedStyle(() => {
    return {
        opacity: scrollIndicator.value, // based on the index, how should I calculate the opacity (0...1)? Basically just the 'highlighted' dot should have opacity=1
    };
});
```

### Preview
<img width="411" alt="Screenshot 2020-11-19 at 21 51 39" src="https://user-images.githubusercontent.com/8364345/99728497-6ced4880-2ab1-11eb-8aca-bc607b24405e.png">

### Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.9

Thank you community 🚀

**Comment by nandorojo** [comment]
What are you trying to calculate the opacity of, the progress indicator?

Could you measure the total size of the scroll view, and then based on the current scroll position %, change the opacity of how visible the dot is?

**Comment by nelsonprsousa** [comment]
> Could you measure the total size of the scroll view, and then based on the current scroll position %, change the opacity of how visible the dot is? This might make it more fluid, since they'll animate as you swipe.

That's what I didn't understood, because I want all the dots to have the same opacity (let's say, 0.3) and just one with opacity, let's say, 1. 🤔  Not sure how to do it

**Comment by drewandre** [comment]
Hopefully this helps!

[Pagination component](https://gist.github.com/drewandre/6ef76e1c8a9328db496d6aba8d60a9a3)

Example usage with react-native-snap-carousel:

```
...
export function MyCarousel() {
  const progress = useSharedValue(0);
  const carouselRef = React.createRef(null)

  function setPaginationProgress(p) {
    'worklet';
    progress.value = p
  }

  const scrollHandler = ({
    nativeEvent: {
      contentSize: { width },
      contentOffset: { x }
    }
  }) => {
    setPaginationProgress(x / width)
  }

  return (
    <View style={styles.container}>
      <Carousel
        ref={carouselRef}
        data={entries}
        slideStyle={styles.slideStyle}
        onScroll={scrollHandler}
        scrollEventThrottle={16}
        decelerationRate='fast'
        sliderHeight={metrics.screenHeight}
        itemWidth={metrics.screenWidth}
        sliderWidth={metrics.screenWidth}
        windowSize={metrics.screenWidth}
        inactiveSlideOpacity={0}
        renderItem={renderItem}
      />
      <View style={styles.bottomContainer}>
        <Pagination
          numberOfPages={entries.length}
          progress={progress}
          scaleDots
        />
      </View>
    </View>
  )
}
```

**Comment by nelsonprsousa** [comment]
I'll take a look, thanks 🚀 

Just by curiosity, is react-native-snap-carousel using reanimated 2? Last time I checked didn't use 🤔

**Comment by drewandre** [comment]
It doesn't look like it uses reanimated at all (looking at the [package.json](https://github.com/archriss/react-native-snap-carousel/blob/v3.9.1/package.json)) but even if it used a different version under the hood, it shouldn't matter.

**Comment by nelsonprsousa** [comment]
Thank you very much @drewandre, it's working perfectly! 🚀

**Comment by drewandre** [comment]
No problem, you could also look at [react-native-animated-pagination-dots](https://github.com/weahforsage/react-native-animated-pagination-dots) that was released a couple weeks ago.
