### ISSUE TITLE
How can I JS state when animation end

### ISSUE THREAD

**Issue by mym0404** [software-mansion/react-native-reanimated#1464]
## Description

I read all docs and know the third parameter of `withTiming`, `withSpring` is an end callback of animation.
But when I try to set a state of React hook from `useState`, then the error is invoked.

I understand what is the problem in the thread level. currently, it seems there is no way to update JS state from UI state even if directing as a `worklet;` or using `runOnJS`.

Is there any way? Thank you.

## Environment

```json
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-reanimated": "2.0.0-alpha.9.1",
    "react-native-redash": "15.11.1",
```

**Comment by terrysahaidak** [comment]
Define state change callback on the React side and then execute that callback using runOnJS inside the animation's callback like so:

```js
withTiming(1, null, () => {
  runOnJS(setStateCallback)();
})
```

**Comment by mym0404** [comment]
Thank you for your answer. +1

**Comment by a-eid** [comment]
@terrysahaidak how do u pass arguments to `runOnJS` function.
