### ISSUE TITLE
Crash at startup with 9.2-alpha: Property _eventTimestamp doesn't exist

### ISSUE THREAD

**Issue by hardcodet** [software-mansion/react-native-reanimated#1476]
## Description

I ejected my expo app and migrated to Alpha 9.2. This works nicely on iOS, but on Android, I'm getting the error `Property _eventTimestamp doesn't exist` at startup with a hard crash. 

The only notion of that property seems to be here:
https://github.com/software-mansion/react-native-reanimated/pull/1419

I checked that I have the updated packages in `node_modules`, and also completely wiped and recreated the folder, so that shouldn't be an issue. I also see the `_getTimestamp` worklet in the package folder. It just doesn't seem to be working with my particular setup. Also tried `./gradlew clean` to no avail...

## steps to reproduce

I just migrated from @expo to the latest alpha (9.2)

## expected behavior

No crash at startup ;)

## actual behavior

Crash at startup

## Package Versions

```
React 16.13.1
RN 0.63.3
Reanimated 2.0.0-alpha.9.2
OS X / Android Simulator (Android 10)
```

**Comment by sow1ch** [comment]
Same issue with react-native-reanimated@2.0.0-alpha.9 ios

**Comment by hardcodet** [comment]
Don't see this anymore - upgraded all my packages, including RNRA to the RC, so closing this...
