### ISSUE TITLE
InterpolateColor fails on Android

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1478]
```
 const  v = useSharedValue(0);
 const animatedStyle = useAnimatedStyle(() => ({
    backgroundColor: interpolateColor(v.value, [-1, 0, 1], ['red', 'blue', 'green']),
  }));
```
fails with the following on Android:

<img width="1311" alt="Screen Shot 2020-11-26 at 10 07 08" src="https://user-images.githubusercontent.com/306134/100330515-57a37d00-2fcf-11eb-8926-e928a529a9cd.png">

**Comment by caiphaav** [comment]
@wcandillon It seems that color strings not working properly. But before it will be fixed, you can use 32bit numbers instead.
```
const animatedStyle = useAnimatedStyle(() => ({
    backgroundColor: interpolateColor(v.value, [-1, 0, 1], [0xffff0000, 0xff0000ff, 0xff00ff00]),
  }));
```

**Comment by wcandillon** [comment]
@caiphaav That sounds like a great workaround thks! It tried this approach by using processColor() but couldn't get it to work on Android.

**Comment by piaskowyk** [comment]
Hey @wcandillon, which version of react native and react-native-animated you use?

**Comment by wcandillon** [comment]
alpha 9.2 and rc.0

**Comment by myckhel** [comment]
wow @wcandillon can you help me out with the reanimated@alpha installation on 64.0-rc
i tried and follow the installation steps on https://docs.swmansion.com/react-native-reanimated/docs/installation but android build fails with output:
```bash
> Task :app:checkDebugAarMetadata FAILED
13 actionable tasks: 2 executed, 11 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-64.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: C:\Users\hp\Desktop\apps\mobile\rnext\node_modules\react-native-reanimated\android\react-native-reanimated-64.aar.
         > Transform's input file does not exist: C:\Users\hp\Desktop\apps\mobile\rnext\node_modules\react-native-reanimated\android\react-native-reanimated-64.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Im wondering if you have followed the exact same steps from the installation page or you did some extra.

Please i will appreciate if you can give me some Abracadabra tips.

**Comment by hannojg** [comment]
@myckhel Reanimated does not yet support RN 0.64 https://github.com/software-mansion/react-native-reanimated/issues/1486

**Comment by jakub-gonet** [comment]
@myckhel, please don't spam. This is unrelated to this issue.

**Comment by myckhel** [comment]
> @myckhel Reanimated does not yet support RN 0.64 #1486

Well
Im surprised how @wcandillon was able to use reanimated@alpha on 0.64.0-rc.0

**Comment by kyle-ssg** [comment]
Duplicate https://github.com/software-mansion/react-native-reanimated/issues/1472

**Comment by jakub-gonet** [comment]
Closing as duplicate.
