### ISSUE TITLE
No overload matches this call.

### ISSUE THREAD

**Issue by jbrainz** [software-mansion/react-native-reanimated#1481]
## Code

Error Message:
Overload 1 of 2, '(props: AnimateProps<ViewStyle, ViewProps> | Readonly<AnimateProps<ViewStyle, ViewProps>>): View', gave the following error.
    Type '{ backgroundColor: Animated.Node<number>; }' is not assignable to type 'StyleProp<AnimateStyle<ViewStyle>>'.
      Types of property 'backgroundColor' are incompatible.
        Type 'AnimatedNode<number>' is not assignable to type 'string | unique symbol | AnimatedNode<string | unique symbol | undefined> | undefined'.
          Type 'AnimatedNode<number>' is not assignable to type 'AnimatedNode<string | unique symbol | undefined>'.
            Type 'number' is not assignable to type 'string | unique symbol | undefined'.
  Overload 2 of 2, '(props: AnimateProps<ViewStyle, ViewProps>, context: any): View', gave the following error.
    Type '{ backgroundColor: Animated.Node<number>; }' is not assignable to type 'StyleProp<AnimateStyle<ViewStyle>>'.
      Types of property 'backgroundColor' are incompatible.
        Type 'AnimatedNode<number>' is not assignable to type 'string | unique symbol | AnimatedNode<string | unique symbol | undefined> | undefined'.
          Type 'AnimatedNode<number>' is not assignable to type 'AnimatedNode<string | unique symbol | undefined>'.ts(2769)
index.d.ts(2523, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<AnimateProps<ViewStyle, ViewProps>> & Readonly<...>'
index.d.ts(2523, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<AnimateProps<ViewStyle, ViewProps>> & Readonly<...>'

### Package versions

- React:
- React Native:
- React Native Reanimated:

**Comment by jakub-gonet** [comment]
Could you please format the error message, add more context, and provide library versions & code repro?

**Comment by jbrainz** [comment]
![error1](https://user-images.githubusercontent.com/24702087/100356569-b1b63980-2ff3-11eb-9faf-794b30c987d7.png)
![errorm](https://user-images.githubusercontent.com/24702087/100356697-dd392400-2ff3-11eb-888a-c21879eaad83.png)

**Comment by jakub-gonet** [comment]
We don't have `mixColor()` function in the Reanimated 2. Please edit the original post, providing the rest of the info (preferably without screenshots, they don't add much and are inconvenient for copy-pasting).

Closing until more information is given.
