### ISSUE TITLE
Update state from withTiming function callback

### ISSUE THREAD

**Issue by beqramo** [software-mansion/react-native-reanimated#1489]
## Description
Hi, I want to update state when animation is finished so I'm using callback function from the ``withTiming``  function.

it throws 
```
Tried to synchronously call function {bound dispatchAction} from a diffrent thread.
Solution is:
a) if you want to synchronously execute this method, mark it as a worklet
b) if you want to execute this method on the JS thread, wrap it using runOnJS
```

### Expected behavior
should update state without a problem
### Actual behavior
throws en error. BTW, it throws error on every this kind of animation function
## Snack or minimal code example
```js
 animation.value = withTiming(0, {duration: 300}, (isFinished) => {
      // 'worklet';
      setModalActive(0);

      // I left comments because to show you what I have tried already. 
      // I tried as many variants as I could(even if it was a bad variant).
      // runOnUI(() => {
      //    setModalActive(0);
      // });

      // setModalActive.call(Modal,0);
      // runOnUI(setModalActive.bind(Modal,0));
      // runOnJS(setModalActive.bind(Modal,0));

      // runOnUI(() => setModalActive(0));
      // runOnJS(() => setModalActive(0));

    });
```

## Package versions

- React:16.13.1
- React Native:63.1
- React Native Reanimated: 2.0.0-alpha.9
- NodeJS:

**Comment by mrousavy** [comment]
You're misusing `runOnJS`. The error description you posted is very descriptive, but the usage on `runOnJS` isn't, I get that. You cannot create lambdas in `runOnJS` (I also made that error at first, would be so much cleaner if we could use lambdas!), so instead of:

```ts
runOnJS(() => setSomething(false));
```

you do

```ts
runOnJS(setSomething)(false);
```

**Comment by beqramo** [comment]
@mrousavy  thanks, that was it.

**Comment by AdarshJais** [comment]
withTiming function callback gets triggered during render instead of getting triggered when the animation finished. 

`  const animatedProps = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateX: withTiming(xOffset.value, configTranslate),
        },
        {
          scale: withTiming(scaleOffSet.value, configScale, (finished) => {
            if (finished) {
              if (!isJwtTokenPresent.current) {
                runOnJS(onClickStartJourney)(null);
              }
            }
          }),
        },
      ],
    };
  });

const onClickStartJourney = () => {
    navigateTo("AppIntro");
  };

`

Am I missing something here?
