### ISSUE TITLE
useAnimatedGestureHandler is not updated when deps are updated

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1495]
## Description

If I use `useAnimatedGestureHandler` with dependencies and these dependencies are updated: returned `gestureHandler` from `useAnimatedGestureHandler` is not updated.

## Steps To Reproduce

1. Update dependencies (`snapPoints`) for `useAnimatedGestureHandler` and see returned value **was not updated**

### Expected behavior

returned value from `useAnimatedGestureHandler` should be updated when dependencies are updated

### Actual behavior

returned value from `useAnimatedGestureHandler` is not updated when dependencies are updated

## Snack or minimal code example

[useInteractivePanGestureHandler](https://gist.github.com/likern/625a08c39d041cf2fb117a1a721448be)

```tsx
    const [contentPanGestureHandler] = useInteractivePanGestureHandler(
      GESTURE.CONTENT,
      animatedPosition,
      snapPoints,
      animateToPoint,
      scrollableContentOffsetY
    );
    ...
    const internalContextVariables = useMemo(
      () => {
        console.log(`internalContextVariables is updated!`);
        return {
          animatedPosition,
          animationState,
          contentWrapperGestureRef,
          contentPanGestureHandler,
          scrollableContentOffsetY,
          scrollableDecelerationRate,
          setScrollableRef: handleSettingScrollableRef,
          removeScrollableRef
        };
      },
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [contentPanGestureHandler]
    );
    ...
<BottomSheetInternalProvider value={internalContextVariables}>
  <BottomSheetDraggableView
    style={[
      styles.contentContainer
    ]}
    onLayout={onContentLayout}
  >
    {typeof children === 'function'
      ? (children as Function)()
      : children}
  </BottomSheetDraggableView>
</BottomSheetInternalProvider>
```

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 15.2.1

**Comment by Szymon20000** [comment]
I've checked it on the master branch and it seems to work just fine. I checked on my own smaller examples though. 
If I understand correctly snapPoint in your code is an array. I guess the problem here is you pass the same array and it is modified.
In hooks we only use shallow comparison so it will not work.  I will close the issue tentatively. Let me know if I'm wrong and the problem occurs when you pass a new array.

**Comment by CallumHemsley** [comment]
@Szymon20000 I have an array of objects in state, and when it gets updated (I set an entirely new array doing `array.slice`) the array within the `useAnimatedGestureHandler` remains the previous state. Therefore even without shallow comparison, it's still not working. (I'm passing the state as a dependency)
