### ISSUE TITLE
Add onLayout native events for Reanimated 2 

### ISSUE THREAD

**Issue by AlexeyVlasenko** [software-mansion/react-native-reanimated#1497]
## Description

onLayout handler should work on UI thread 

## Motivation
`measure()` measures paddings with some infelicity, while onLayout returns correct height/width/etc.

## Example
The following example is default accordion animation with opened/closed component inside

1) Closed => Open transition (height)
![image](https://user-images.githubusercontent.com/25363536/100756851-5373c700-33f6-11eb-9bd0-b2f3610ac0e0.png)

2) Open => Closed transition (height)
![image](https://user-images.githubusercontent.com/25363536/100756864-566eb780-33f6-11eb-98b6-2cef9006dc19.png)

**Comment by likern** [comment]
@AlexeyVlasenko How this should be implemented?

Could you describe your vision and API? I think `onLayout` is expected to be called on JS side so changing `<View />` to Reanimated `<Animated.View />` does not cause error that JS function is called directly without `runOnJS`.

**Comment by nandorojo** [comment]
@likern is there a way to call `measure` whenever its size changes? Should we just call `measure` inside of `onLayout`?

**Comment by terrysahaidak** [comment]
I would go with that approach. It gives freedom to the developer.

```jsx
const handler = useAnimatedLayoutEvent((layout) => {
  "worklet";

  // do whatever you want
}, [])

<Animated.View onLayout={handler} />
```

**Comment by likern** [comment]
@terrysahaidak I like that approach, I think it's better than what I thought about (adding new on UI callback)

**Comment by nandorojo** [comment]
@terrysahaidak I assume that's not a real API yet, right? Seems like that would work for me.

**Comment by terrysahaidak** [comment]
Not yet. But would be cool to have. Measure is handy but doesn't work all the times.

**Comment by nandorojo** [comment]
Agreed, especially for web where layout changes are very common.

**Comment by Noitidart** [comment]
> ```js
> useAnimatedLayoutEvent
> ```

`useAnimatedLayoutEvent` hook does not exist I am using v2.3.1 - did they change it?

**Comment by Ubax** [comment]
@terrysahaidak @AlexeyVlasenko Could you open a topic about that in discussion?
This is more a feature request then issue.
