### ISSUE TITLE
Add recommendation of use strict mode

### ISSUE THREAD

**Issue by piaskowyk** [software-mansion/react-native-reanimated#1505]
## Description
Add console warning when someone doesn't use strict mode in application. Add to documentation information why you should use strict mode in your application and give instructions on how to enable auto inject `use strict` to modules with babel plugin.

### Caveats
We shouldn't add `use strict` without user knowledge because this can affect on rest of application.

## Motivation

Strict mode gives us many useful information about issues and undefined behaviors in code. Without strict mode we lose helpful information to debugging.
`use strict` isn’t added by default by babel - [more information here](https://github.com/facebook/metro/blob/0603ab1cd462205ddef062ba359c7b208b3fb81e/packages/metro-react-native-babel-preset/src/configs/main.js#L107). You must add plugin - [babel documentation](https://babeljs.io/docs/en/v7-migration#use-strict-and-this-in-commonjs) `@babel/plugin-transform-modules-commonjs` or `@babel/plugin-transform-strict-mode`

## Code example
no example code

**Comment by mrousavy** [comment]
Will strict mode be added in worklets when using TypeScript with the `"strict": true` flag?
