### ISSUE TITLE
PanHandler expect onGestureHandler to be a function

### ISSUE THREAD

**Issue by Evanion** [software-mansion/react-native-reanimated#1506]
## Description
I'm using `<PanGestureHandler />` from `react-native-gesture-handler@1.9.0`, and `useAnimatedGestureHandler` from `react-native-reanimated@2.0.0-rc.0`... the hook returns an object, and according to the docs I should just take what the hook returns and add it to the `<PanGestureHander onGestureEvent={gestureHandler} />` .. but I'm getting the following error
```
ERROR    Error: Expected `onGestureHandlerEvent` listener to be a function, instead got a value of `object` type.
```

## Code
```tsx
export const AuctionDetails: React.FC<Props> = ({ route }) => {
  const { auction } = route.params;
  // ...

  const onGestureEvent = useAnimatedGestureHandler({
    onStart: () => {
      isGestureActive.value = true;
    },
    onActive: ({ translationX, translationY }) => {
      translateX.value = translationX;
      translateY.value = translationY;
    },
    onEnd: ({ velocityX, velocityY }) => {
      if (snapPoint(translateY.value, velocityY, [0, height]) === height) {
        navigation.goBack();
      } else {
        translateX.value = withSpring(0, { velocity: velocityX });
        translateY.value = withSpring(0, { velocity: velocityY });
      }
      isGestureActive.value = false;
    },
  });
  // ...

return (
    <PanGestureHandler onGestureEvent={onGestureEvent}>
      <Animated.View style={containerStyle}>
        <SharedElement id={auction.id} style={{ flex: 1 }}>
          <Animated.View
            style={[
              {
                ...StyleSheet.absoluteFillObject,
                width: undefined,
                height: undefined,
              },
              imageStyle,
            ]}
          >
            <Image
              source={auction.source}
              style={StyleSheet.absoluteFillObject}
            />
          </Animated.View>
        </SharedElement>
      </Animated.View>
    </PanGestureHandler>
  );
};
```

### Package versions

- React: 16.13.1
- React Native: expo sdk 40
- React Native Reanimated: 2.0.0-rc.0
- React Native Gesture Handler: 1.9.0

**Comment by karol-bisztyga** [comment]
Hey

It's hard to say what went wrong here. The code looks healthy. You may try to clear the packages/caches and see if that helps. The same code works for me on multiple environments so it has to be something with your local setup.
```
rm -rf node_modules && yarn && cd ios && pod install && cd .. && yarn start --reset-cache
```
or/and maybe clean the iOS project and build again.

**Comment by karol-bisztyga** [comment]
Do you launch it on mobile or on the web? Maybe #1518 will do for you?

**Comment by myckhel** [comment]
I had the same problem before 

It frustrated my life untill i started thinking of switching to previous versions and rebuilding the app
When i used previous versions the error disappeared
And when i tried to switch back and rebuild to the latest version the error was no more.

I guess it would be due to cache as @karol-bisztyga suggested.

Maybe u should try to downgrade and upgrade.

**Comment by karol-bisztyga** [comment]
I'm closing this for now due to inactivity. If the issue persists, please let me know here and I will reopen.

**Comment by chungweileong94** [comment]
I'm facing the same issue on Android (I can't test it on IOS), tried to clean every and rebuild, and still the same. 
Quite frustrating.

**Comment by Essam-Harrous** [comment]
I have the same problem, is there any fix please?

**Comment by StampixSMO** [comment]
@karol-bisztyga Also having this issue

**Comment by chungweileong94** [comment]
@Essam-Harrous @StampixSMO If none of the clean & rebuild works, make sure you have `Animated.View` as the direct child to the `< PanGestureHandler  />`. That was the mistake I had few days ago.

**Comment by karol-bisztyga** [comment]
fwd @piaskowyk

**Comment by StampixSMO** [comment]
> @Essam-Harrous @StampixSMO If none of the clean & rebuild works, make sure you have `Animated.View` as the direct child to the `<PanGestureHandler />`. That was the mistake I had few days ago.

Very nice catch. That, indeed, solves it.

**Comment by alphonse92** [comment]
@chungweileong94 TY! Works like a charm!

**Comment by eduardoschneider** [comment]
I'm having the same issue right now, I've tried everything I could find, but nothing worked.

```
  const gestureHandler = useAnimatedGestureHandler({
    onStart: (event) => {
      console.log(event);
    },
    onCancel: (event) => {
      console.log(event);
    },
    onActive: (event) => {
      console.log(event);
    },
    onEnd: (event) => {
      console.log(event);
    }
  });
```

```
    <GestureHandlerRootView style={styles.container}>
      <PanGestureHandler onGestureEvent={gestureHandler}>
        <Animated.View style={[styles.circle, { transform:[{translateY : translateY}]}]}>
        </Animated.View>
      </PanGestureHandler>
    </GestureHandlerRootView>
```
```
export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "space-around",
    flexDirection: "column",
    backgroundColor: "#fff"
  },

  circle: {
      width: 150,
      height: 150,
      backgroundColor: "#c00000",
      borderRadius: 100
    },
  });
```

I also tried adding <PanGestureHandlerGestureEvent> since its typescript, but it also didnt work.

**Error: Expected `onGestureHandlerEvent` listener to be a function, instead got a value of `object` type.**

**Comment by Balthazar33** [comment]
> @Essam-Harrous @StampixSMO If none of the clean & rebuild works, make sure you have `Animated.View` as the direct child to the `<PanGestureHandler />`. That was the mistake I had few days ago.

In may case, I was importing `Animated `from '`react-native`', instead of importing it from '`react-native-reanimated`'

`import Animated from 'react-native-reanimated'` fixed the issue for me.
