### ISSUE TITLE
Crash on android using yarn workspaces monorepo

### ISSUE THREAD

**Issue by Bushuo** [software-mansion/react-native-reanimated#1508]
## Description

Hi, first of all thank you for your great work and this great library.
This is my first issue on github

I tried to get the example from the reanimated2-playground repo working in a monorepo.
When launching the app on android-emulator or my development device the app crashes.
### Screenshots
no screenshots, as the app immediately crashes
## Steps To Reproduce
1. clone the repo
2. run `yarn` from the root directory
3. start react-native

### Expected behavior
The example works
### Actual behavior
The app crashes
## Snack or minimal code example

minimal repo to reproduce this here [https://github.com/Bushuo/reanimated2-monorepo-crash](https://github.com/Bushuo/reanimated2-monorepo-crash)

Here are logs from `adb logcat`   
The full log can be found here [https://github.com/Bushuo/reanimated2-monorepo-crash/blob/master/abd-logcat-crash.txt](https://github.com/Bushuo/reanimated2-monorepo-crash/blob/master/abd-logcat-crash.txt)
I think the relevant part is:
```
12-07 09:35:11.033  2403  2403 I HermesVM: TypeError: Cannot delete property 'callback' of undefined  
12-07 09:35:11.033  2403  2403 I HermesVM:     at decorateAnimation (JavaScript:1:276)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at decorateAnimation (native)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at _f (JavaScript:1:243)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at defineAnimation (JavaScript:1:624)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at defineAnimation (native)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at withTiming (JavaScript:1:120)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at withTiming (native)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at _f (JavaScript:1:93)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at _f (native)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at styleUpdater (JavaScript:1:234)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at styleUpdater (native)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at _f (JavaScript:1:113)  
12-07 09:35:11.033  2403  2403 I HermesVM:     at _f (native)
12-07 09:35:11.036  2403  2403 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 2403 (imated2monorepo)
```
If you check out the commit history I tried it with alpha9.2 as well.  
Before adding any code from reanimated it also works as intended.  
## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: v12.14.1

**Comment by jakub-gonet** [comment]
Related to #858.

**Comment by Bushuo** [comment]
I fixed my issue by pinning the version of `metro-react-native-babel-preset` to `0.58.0`.

somehow in the root node_modules, there was `preset` with version `0.59.0` and in my apps node_modules there was version `0.58.0`

after that, it just worked.
For anyone having a similar issue: 
Make sure that everything inside of node_modules of the react-native app is hoisted to the root node_modules

Should I close this then?

**Comment by Bushuo** [comment]
Managed to fix it by applying this stackoverflow post 
[https://stackoverflow.com/questions/57656845/configure-multiple-transformers-resolvers-using-metro](https://stackoverflow.com/questions/57656845/configure-multiple-transformers-resolvers-using-metro)
But also adding the plugins from babel

```js
// customTransformer.js
var upstreamTransformer = require('metro-react-native-babel-transformer');
var svgTransformer = require('react-native-svg-transformer');

module.exports.transform = function ({src, filename, options, plugins}) {
  if (filename.endsWith('.svg')) {
    return svgTransformer.transform({src, filename, options});
  } else {
    return upstreamTransformer.transform({src, filename, options, plugins});
  }
};
```

```js
// metro.config.js from above
babelTransformerPath: require.resolve('./customTransformer.js'),
```

**Comment by Bushuo** [comment]
I found a workarround for this issue.
See https://github.com/kristerkari/react-native-svg-transformer/issues/113
