### ISSUE TITLE
Possibility to create custom native operators

### ISSUE THREAD

**Issue by reneeichhorn** [software-mansion/react-native-reanimated#151]
It would be nice from a developer perspective to be able add custom project specific operators.

I'd imagine a declarative API that allows to "register" new operators on both ios and android. 
IMO this would make reanimated even stronger as it is right now and it would also allow us to improve performance on very heavy animations or simply to make it easier to read / develop more advanced animations.

Any opinions on that?

**Comment by osdnk** [comment]
Hi @reneeichhorn 
Do you wish to write some native code for your case? If yes, I cannot really imagine how API should look like. 
Could you elaborate more about your case?

**Comment by reneeichhorn** [comment]
So lets say you want to animate an SVG path. Right now it would be a bit tricky and annoying to build the path out of multiple calculations and concat everything together. I'm also not sure how big the cost is the sync the whole calculation (defintion) tree over the thread.

With the given example it would be nice if I could write native operators like `createPiePath(radius, ...)`

**Comment by osdnk** [comment]
Yup, I have came across even more cases. E.g. I wanted recently to connect animation with some action e.g. haptic on iOS or opening keyboard or even focusing on some input. I could not imaging all these operators to library to I'd like to add some API which could allow creating "reanimated modules" which could communicate somehow with reanimated without JS.
How to do it? I don't know (yet!), but I want to avoid reflection in Java for cross-module communication.
I want it to be as simple in the result e.g.: 
```
yarn add reanimated-keyboard
react-native link reanimated-keyboard
```
then it will be possible to import it from `reanimated-keyboard` and use as "normal node"

**Comment by Ashoat** [comment]
I'm looking to implement something like this:

![](https://user-images.githubusercontent.com/8356318/51436612-002c7b80-1c99-11e9-8d44-2143644ae617.gif)

The way the interactive dismissal leaves the input accessory view above the tab bar is too complicated for React Native currently, which is limited by `ScrollView.keyboardDismissMode`, `InputAccessoryView`, and `LayoutAnimation`'s keyboard support (which backs `KeyboardAvoidingView`).

It would be awesome if I could implement something like this using `react-native-reanimated` and `react-native-gesture-handler`, but first I would need something like `reanimated-keyboard`. I imagine there would have to be some sort of node that outputs the keyboard's height as it's being dismissed, as well as some way to hook up a `PanGestureHandler`.

**Comment by ShaMan123** [comment]
+1

I came up with a similar need and came across this thread.
To my understanding (and for my use case):

Let's say there's a native react method `m(...args)` defined in some view module `view_module` that I want to evaluate as part of `Animated.Block` or some other node.
I need a function `createAnimatedNativeMethod(m, config)` that returns a node/function. This function takes animated_values as args and calls `m` with their primitive values, returning a `node` set to the return value of `m`.

This way I could do something like this:
```ts
const val1: Value, val2: Value, val3: Value;
const animatedM = createAnimatedNativeMethod(m);
set(val3, animatedM(val1, val2))
```

Normally `m` is defined as follows: 
```js
m(viewTag, ...args, callbackOrPromise)
```

This means that:
1. There will be need to pass the view's tag => `findNodeHandle()` => can be done with `set` at initialization of view.
1. There will be a need to proxy the `Callback | Promise` arg passed to the method and extracting the return value from it.
1. The return type must be compatible with `Value`

What do you guys think? Is this too narrow of a use case?

**Comment by kmagiera** [comment]
Closing this as we won't be adding big new features to reanimated 1. This kind of functionality is covered in the new Reanimated 2 and we would rather focus on stabilizing the new API and hope y'all will try it soon and that it will resolve the need of having such function in Reanimated 1.x
