### ISSUE TITLE
why useSharedValue can use in here?

### ISSUE THREAD

**Issue by wcly** [software-mansion/react-native-reanimated#1512]
https://github.com/software-mansion/react-native-reanimated/blob/718cdcab67432927697fc61fdda64fa4abf865f4/Example/src/MeasureExample.js#L23

why it can run without throw an Error like this👇
```bash
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
```

**Comment by ysfzrn** [comment]
useSharedValue is a hook. You are calling this hook inside of map function.

Maybe you can try this
```js 
const contentHeights = useSharedValue( 
  Object.assign( 
    {},  
    ...indices.map((i) => ({[i]: 0}))
  )
) 
```

**Comment by satya164** [comment]
https://reactjs.org/docs/hooks-rules.html
