### ISSUE TITLE
AnimatedNode should use requestAnimationFrame instead of setImmediate for web

### ISSUE THREAD

**Issue by DrRefactor** [software-mansion/react-native-reanimated#1520]
Using setImmediate cause animations/mutations to be done with significant delay. This can be observed especially when UI is under heavy load.

I'm not sure whether native platforms share same problem, didn't observe even on low-end Android TV boxes. React Native docs suggests requestAnimationFrame should be used though. I'll leave it open to discussions.
https://reactnative.dev/docs/timers 

I will create PR soon, let's discuss there.

**Comment by nandorojo** [comment]
Another upside of this change: it would help fix this bug that causes Reanimated to constantly break in Next.js: https://github.com/expo/expo/issues/7996
