### ISSUE TITLE
useAnimatedProps doesn't work work scrollview keyboardShouldPersistTap.

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-reanimated#1526]
## Description

using `useAnimatedProps` to control ScrollViews KeyboardShouldpersistTap doesn't work. 

## Steps To Reproduce

using useAnimatedProps to control a ScrollViews KeyboardShouldpersistTap. 

### Expected behavior
it should respect the KeyboardShouldpersistTap value from `useAnimatedProps` 

### Actual behavior

it doesn't respect the keyboardShouldPersistTaps value from `useAnimatedProps` 

## Snack or minimal code example

```tsx

import * as React from 'react';
import { TextInput } from 'react-native';
import A, { useAnimatedProps, useSharedValue } from 'react-native-reanimated';

export default function Home() {
  const disableDismissingKeyboard = useSharedValue<boolean>(false);

  const animatedProps = useAnimatedProps(() => {
    return {
      keyboardShouldPersistTaps: disableDismissingKeyboard.value ? 'always' : 'never',
    };
  });

  return (
      <A.ScrollView style={{ flex: 1, backgroundColor: '#ccc', paddingTop: 70 }} {...{ animatedProps}}>
        <TextInput style={{ height: 40, marginBottom: 22, backgroundColor: 'red' }} />
        <TextInput
          style={{ height: 40, backgroundColor: 'blue' }}
          onBlur={() => {
            disableDismissingKeyboard.value = false;
          }}
          onFocus={() => {
            disableDismissingKeyboard.value = true;
          }}
        />
      </A.ScrollView>
  );
}
```
it doesn't seem that snack supports reanimated 2 just yet...

## Package versions

- React: 16.13.1
- React Native: 64.3
- React Native Reanimated: ^2.0.0-rc.0 
- NodeJS: 14.5.1

**Comment by a-eid** [comment]
this is still an issue on RC1 ^^.

**Comment by kmagiera** [comment]
Hi @a-eid – thanks for reporting this problem. Unfortunately supporting `keyboardShouldPersistTaps` property is not possible with reanimated as it does not map to a native view property but instead it is handled by the JS-based implementation of the ScrollView (see how it is being used in RN's ScrollView: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/Libraries/Components/ScrollView/ScrollView.js)

With reanimated we can only support properties that needs to be reflected on the native side. Changes to props that are handled by the component implementation cannot be reflected w/o re-render so updating them outside of the render scope would have no effect anyways. If you want this prop changed, you'll need to trigger a component state update and you can do this directly from reanimated worklet using`runOnJS` helper method: https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/api/miscellaneous/runOnJS/
