### ISSUE TITLE
[v2 regression] TextInput animation stopped working in rc.0

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1528]
redash using an `AnimatedTextInput` to animate text but it stopped working in rc.0. Here is the implementation: https://github.com/wcandillon/react-native-redash/blob/master/src/ReText.tsx. I was unsuccessful debugging the issue. Are there any leads on how I could educate myself on what createAnimatedComponent does exactly? It would probably help me to debug the issue.

**Comment by karol-bisztyga** [comment]
Hey. Have you tried [this](https://github.com/software-mansion/react-native-reanimated/issues/1487#issuecomment-741945426)? If you haven't, please do and let me know whether it works.

**Comment by wcandillon** [comment]
Thanks @karol-bisztyga! I would still be interested to learn more about the internals of settings a prop value from the UI thread. How would I go about learning that?

**Comment by karol-bisztyga** [comment]
I'm not aware of anything but just reading the code. AFAIK, unfortunately, there ain't any global rules for that. Some props work some don't, every case is different. But if you find out I'm wrong I'm always happy to know something about that. Some time ago I was asking the same question actually 😅
