### ISSUE TITLE
v2 regression: complex default values fail on init (JS thread)

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1532]
On init, default values of shared values seem to be undefined on init (on JS thread) which seems fine. However when values are complex, this might cause a crash. For instance: 

```tsx
const data = useSharedValue({ a: true, b: false, path: "..." });
const animatedProps = useAnimatedProps(() => ({ d: data.value.path }));
```

**Comment by Szymon20000** [comment]
I've checked and shared values are defined on both UI and RN side from start.

**Comment by RNEvok** [comment]
Same problem. Reanimated version: "2.17.0".
