### ISSUE TITLE
[IOS] animations with duration less than 500ms are ignore when the keyboard is showing ?

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-reanimated#1534]
## Description
please observe IOS behavior below, you can see than when the input is blurred the animation is fine, while when it's focused it skippes the animation. if I up the timeing to 500 or more it kinda works. 
also please note that if I disable soft keyboard, it works fine.

### Screenshots

![android rn2](https://user-images.githubusercontent.com/19273413/102006882-16c89980-3d2d-11eb-8d4a-902ec542c53a.gif)

![IOS rn 2](https://user-images.githubusercontent.com/19273413/102006886-1defa780-3d2d-11eb-8693-ee8634c1dca1.gif)

## Steps To Reproduce

try to animate height, transform or position based on a value drived by the keyboard 
on => 1 off => 0

### Expected behavior
it should animate as usual

### Actual behavior
it is skipped when keyboard is showing 

## Snack or minimal code example

```tsx
import * as React from 'react';
import { View, TextInput , StyleSheet } from 'react-native';
import A, { useAnimatedStyle, useSharedValue, withTiming } from 'react-native-reanimated';

export function TextInput2() {
  const active = useSharedValue<number>(0);

  function handleFocus() {
     active.value = 0;
  }

  function handleBlur() {
    active.value = 1;
  }

  const containerStyles = useAnimatedStyle(() => {
    return {
      height: withTiming(active.value === 0 ? 20 : 40),
      // backgroundColor: A.interpolateColor(withTiming(active.value), [0, 1], ['green', 'blue']),
    };
  }, []);

  return (
    <A.View style={[styles.container, containerStyles]}>
      <TextInput onFocus={handleFocus} onBlur={handleBlur} style={{ backgroundColor: 'white' }} />
    </A.View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'red',
    borderWidth: StyleSheet.hairlineWidth,
  },
});

```

## Package versions

- React: 16.13.1
- React Native: 63.4
- React Native Reanimated: ^2.0.0-rc.0
- NodeJS: v14.15.1

**Comment by jakub-gonet** [comment]
Hi, why did you close this question? Was it an issue in your code?

**Comment by a-eid** [comment]
@jakub-gonet there hasn't been any responses for a while & it seems to be working on my physical device.

**Comment by jakub-gonet** [comment]
I see.
Don't worry about no responses, we have issues backlog and we try to go through them periodically.
