### ISSUE TITLE
Bug: Building with build-tools v29.0.2 instead of using the version in the root project 

### ISSUE THREAD

**Issue by SaeedZhiany** [software-mansion/react-native-reanimated#1541]
## Description

I bumped my project Build-Tools to version `30.0.2` and even remove version `29.0.2`, but somehow when I want to build my project, the gradle config of this library forces the building process to download version `29.0.2` and use it to build it. none of my other dependencies have this problem.

```bash
> Configure project :react-native-reanimated
File C:\Users\SAEED\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 29.0.2 in C:\Users\SAEED\AppData\Local\Android\Sdk\licenses
License for package Android SDK Build-Tools 29.0.2 accepted.
Preparing "Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)".
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" ready.
Installing Android SDK Build-Tools 29.0.2 in C:\Users\SAEED\AppData\Local\Android\Sdk\build-tools\29.0.2
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" complete.
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" finished.
```

### Expected behavior

I'm expecting that this library built by the root project's build-Tools version. like my other dependencies.

### Actual behavior

It seems this library is using its own specified build-Tools version.

## Package versions

- React: `16.13.1`
- React Native: `0.63.4`
- React Native Reanimated: `1.13.2`

**Comment by SaeedZhiany** [comment]
Hi @friederbluemle 

have you any idea why this is happening? I remembered we fixed this library gradle configuration before.

**Comment by SaeedZhiany** [comment]
Hi @friederbluemle 

have you any idea why this is happening? I remembered we fixed this library's gradle configuration before.

**Comment by SaeedZhiany** [comment]
Hi @friederbluemle 

have you any idea why this is happening? I remember we fixed this library's gradle configuration before.

**Comment by friederbluemle** [comment]
Hi @SaeedZhiany - Unfortunately I am not sure why this is happening without taking a closer look. It could be caused indirectly by a related dependency that still declares the older version.

**Comment by ChristophGr** [comment]
Maybe it has something to do with this:
https://github.com/facebook/react-native/pull/30721
