### ISSUE TITLE
app crashes if animation running while unmounting

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1548]
## Description

I have `TaskSettings` screen which appears by mounting and unmounting
```ts
{activeScreen.kind === ActiveScreenKind.TASK_SETTINGS && (
  <TaskSettings id={activeScreen.taskId} /> )}
```

inside I have bottom sheet component.

- If bottom sheet is open (or is opening) - press on back button should close bottom sheet
- If bottom sheet is closed (or is closing) - press on back button should close task settings screen

### Screenshots

<table>
  <tr>
    <td>Task Settings</td>
    <td>Task Settings with Bottom Sheet</td>
  </tr>
  <tr>
    <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687505-a1fbd080-4200-11eb-8e20-269bc294bafb.jpg"></td>
    <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687513-aa540b80-4200-11eb-9788-a81aca845dd8.jpg"></td>
  </tr>
 </table>

### Crash Report

<table>
  <tr>
    <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687800-d40e3200-4202-11eb-8593-db15bc3cef98.jpg"></td>
    <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687801-d4a6c880-4202-11eb-8cad-d088db42881e.jpg"></td>
  <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687802-d4a6c880-4202-11eb-8c53-1009d75c0e6d.jpg"></td>
  <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687803-d53f5f00-4202-11eb-895b-3ebd52bdd01f.jpg"></td>
  <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687796-d2446e80-4202-11eb-9240-e1a17fa3ab17.jpg"></td>
  <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687797-d2dd0500-4202-11eb-8c50-59b318f7d2e9.jpg"></td>
  <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687798-d3759b80-4202-11eb-85b4-6bc4a2bafe73.jpg"></td>
  <td valign="top"><img src="https://user-images.githubusercontent.com/842306/102687799-d3759b80-4202-11eb-957e-4bc82d0fc571.jpg"></td>
  </tr>
 </table>

### Video

https://user-images.githubusercontent.com/842306/102687922-e0df5580-4203-11eb-96db-61b8b18bb243.mp4

## Snack or minimal code example

I can reproduce using the same bottom sheet component on another example application if slow down animation.
This PR reproduces application crashes https://github.com/breeffy/react-native-bottom-sheet/pull/41
There is **example** folder with example application.

I'm sure the main reason is that while bottom sheet animation is still running - parent component is unmounting.

https://drive.google.com/file/d/19FHtucf-b7DnvKtuASS-riDtEFaW7o08/view?usp=sharing

## Steps to Reproduce

1. Run animation
2. While animation is happening - unmount parent component

## Expected Behavior
Application should not crash

## Actual Behavior
Application crashes

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 15.2.1

**Comment by jakub-gonet** [comment]
I'm not sure if this should be reported here. We don't have resources to debug libraries depending on Reanimated. If you're able to repro this with Reanimated v2 only, please reply, I'll reopen this.
