### ISSUE TITLE
proper way of running animations while using conditions logic

### ISSUE THREAD

**Issue by hoffmannjan** [software-mansion/react-native-reanimated#155]
Hi,

my problem is pretty simple, what I'm trying to achieve is replicate `ScrollView` in reanimated because I need more control over this view behavior, but I'm mainly have problem with building kind of pager that will move you up to position that you need.

Look at `onPressNext()` - I don't think this is elegant way of running animation of my setup, but It also is unpredictable - I can't run this animation by pressing "Next" button on 1 slide more than one time.

There is snack with my code so you can look at the whole situation.
https://snack.expo.io/@jhoffmann/slider

Hope you guys will have some idea of doing this in clean and predictable way :).

Best, JH

**Comment by jakub-gonet** [comment]
Hey, I'm terribly sorry for the late response 😔

I think this issue may be outdated nearly a year later, so I'm closing it.

If you still face the same problem feel free to reopen
