### ISSUE TITLE
TypeScript: useAnimatedReaction is missing return type

### ISSUE THREAD

**Issue by maxammann** [software-mansion/react-native-reanimated#1553]
## Description

TypeScript 3.8 shows an error 

```
TS7010: 'useAnimatedReaction', which lacks return-type annotation, implicitly has an 'any' return type.
```

in these lines:

https://github.com/software-mansion/react-native-reanimated/blob/ba07df0698dd18957e3dcc5f0c29621b20983202/react-native-reanimated.d.ts#L480-L484

```
    export function useAnimatedReaction<D>(
      dependencies: () => D,
      effects: (dependencies: D) => void,
      deps?: DependencyList
    );
```

## Steps To Reproduce

Use TypeScript together with reanimated v2

### Expected behavior

* No TS error

### Actual behavior

```
TS7010: 'useAnimatedReaction', which lacks return-type annotation, implicitly has an 'any' return type.
```

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-rc.1
- NodeJS: v12.20.0

**Comment by piaskowyk** [comment]
@jakub-gonet You are working on TS in Reanimated now, right? Could you check this?
