### ISSUE TITLE
Android, ScrollView and onScroll event: when scroll performed by fling - there is a lag between visible scroll and captured by reanimated

### ISSUE THREAD

**Issue by Strate** [software-mansion/react-native-reanimated#1554]
## Description

If you use ScrollView, and attach reanimated to onScroll, then updated reanimated value is not in sync while scroll performed by fling gesture. This happens only in android, and only with Reanimated, not with origin Animated module

### Screenshots

You can check this video, red square on top has translateY which depends on scrollY position.

https://user-images.githubusercontent.com/392644/102798437-25b0eb00-43c2-11eb-880f-178d99584861.mov

## steps to reproduce

Check snack

## expected behavior

value attached to onScroll event always in sync with real visible scroll position

## actual behavior

value attached to onScroll event is not in sync when scrollview flings on android

## Snack or minimal code example

https://snack.expo.io/3MSacfgSG

## Package versions
- React Native Reanimated: 1.13.0

**Comment by dan-lee** [comment]
Is there anything new or a workaround for this behavior? This looks quite laggy on a state of the art phone

**Comment by viper4595** [comment]
I think it is not reanimated bugs. In my case, add prop overScrollMode="never" to ScrollView fixed the problem.

**Comment by dan-lee** [comment]
@viper4595 I tried it and unfortunately, it didn't fix it for me.

**Comment by jakub-gonet** [comment]
If you want to implement a sticky header you can just take the header out of the list, like so:
```jsx
import * as React from 'react';

import {View} from 'react-native';
// import { Animated } from "react-native";
import Animated from 'react-native-reanimated';
//
export default class App extends React.Component {
  contentOffset = new Animated.Value(0);
  onScroll = Animated.event([
    {nativeEvent: {contentOffset: {y: this.contentOffset}}},
  ]);

  render() {
    return (
      <>
        <Animated.View
          style={{
            zIndex: 10,
            height: 40,
            backgroundColor: 'red',
            backgroundColor: 'red',
          }}
          scrollEventThrottle={16}
        />
        <Animated.ScrollView onScroll={this.onScroll}>
          <View style={{height: 500, backgroundColor: 'cyan'}} />
          <View style={{height: 500, backgroundColor: 'blue'}} />
          <View style={{height: 500, backgroundColor: 'green'}} />
          <View style={{height: 500, backgroundColor: 'orange'}} />
        </Animated.ScrollView>
      </>
    );
  }
}
```

https://user-images.githubusercontent.com/12465392/114411399-6d939200-9bac-11eb-889b-302d13a9bfd1.mov

Why do you want it inside ScrollView?

**Comment by Strate** [comment]
@jakub-gonet actually I trying to implement different things, such as parallax scrolling or sticky elements. Code in demo just for reproduce purposes.

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request. I recommend to use Reanimated v2.
