### ISSUE TITLE
Android crash when reloading JS bundle

### ISSUE THREAD

**Issue by JB-CHAUVIN** [software-mansion/react-native-reanimated#1563]
## Description

When my app is restarting because of a CodePush restart, I have the following Android native crash : 

## Stack trace

12-23 15:49:17.446 18702 18702 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 18702 (gedim.maiia.pro)
12-23 15:49:17.600 19110 19110 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-23 15:49:17.600 19110 19110 F DEBUG   : Build fingerprint: 'samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU8ETI2:user/release-keys'
12-23 15:49:17.600 19110 19110 F DEBUG   : Revision: '9'
12-23 15:49:17.600 19110 19110 F DEBUG   : ABI: 'arm64'
12-23 15:49:17.600 19110 19110 F DEBUG   : pid: 18702, tid: 18702, name: gedim.maiia.pro  >>> com.cegedim.maiia.pro <<<
12-23 15:49:17.600 19110 19110 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-23 15:49:17.605 19110 19110 F DEBUG   : Abort message: 'java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x726f7774654e7265'
12-23 15:49:17.605 19110 19110 F DEBUG   :     x0   0000000000000000  x1   000000000000490e  x2   0000000000000006  x3   0000000000000008
12-23 15:49:17.605 19110 19110 F DEBUG   :     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0080808080808080
12-23 15:49:17.605 19110 19110 F DEBUG   :     x8   0000000000000083  x9   3bee2f7a910de3fa  x10  0000000000000000  x11  0000000000000001
12-23 15:49:17.605 19110 19110 F DEBUG   :     x12  ffffffffffffffff  x13  0000000000000008  x14  ffffffffffffffff  x15  0000b02a41d6805c
12-23 15:49:17.605 19110 19110 F DEBUG   :     x16  000000771790e2f8  x17  00000077178af408  x18  0000000000000020  x19  000000000000490e
12-23 15:49:17.605 19110 19110 F DEBUG   :     x20  000000000000490e  x21  00000076ed08ec80  x22  000000000000000b  x23  0000000000001020
12-23 15:49:17.605 19110 19110 F DEBUG   :     x24  0000000000000041  x25  00000076f2e19800  x26  000000000000101f  x27  0000007fd238d760
12-23 15:49:17.605 19110 19110 F DEBUG   :     x28  0000000000000043  x29  0000007fd238d600  x30  0000007717861bd4
12-23 15:49:17.605 19110 19110 F DEBUG   :     sp   0000007fd238d5c0  pc   00000077178af410  pstate 0000000060000000
12-23 15:49:17.616 19110 19110 F DEBUG   :
12-23 15:49:17.616 19110 19110 F DEBUG   : backtrace:
12-23 15:49:17.616 19110 19110 F DEBUG   :     #00 pc 000000000006b410  /system/lib64/libc.so (tgkill+8)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #01 pc 000000000001dbd0  /system/lib64/libc.so (abort+88)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #02 pc 00000000004377e0  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+528)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #03 pc 0000000000437ef0  /system/lib64/libart.so (_ZN3art7Runtime7AborterEPKc+24)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #04 pc 0000000000522a3c  /system/lib64/libart.so (_ZN7android4base10LogMessageD1Ev+900)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #05 pc 00000000002d5c84  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1716)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #06 pc 00000000002d5f50  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+176)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #07 pc 0000000000462870  /system/lib64/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+448)
12-23 15:49:17.616 19110 19110 F DEBUG   :     #08 pc 0000000000107e1c  /system/lib64/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+116)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #09 pc 0000000000106a78  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+856)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #10 pc 00000000000f7dc4  /system/lib64/libart.so (_ZN3art8CheckJNI14GetObjectClassEP7_JNIEnvP8_jobject+644)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #11 pc 000000000002d8d4  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so (_ZNK8facebook3jni7JObject8getClassEv+40)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #12 pc 0000000000037400  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so
12-23 15:49:17.617 19110 19110 F DEBUG   :     #13 pc 0000000000037180  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so
12-23 15:49:17.617 19110 19110 F DEBUG   :     #14 pc 00000000000415d4  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so (_ZN10reanimated22NativeReanimatedModule18maybeRequestRenderEv+100)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #15 pc 0000000000043254  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so
12-23 15:49:17.617 19110 19110 F DEBUG   :     #16 pc 000000000005e904  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so (_ZN10reanimated9Scheduler9triggerUIEv+56)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #17 pc 000000000002f3f4  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so (_ZN8facebook3jni6detail13MethodWrapperIMN10reanimated16AndroidSchedulerEFvvEXadL_ZNS4_9triggerUIEvEES4_vJEE8dispatchENS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassIS4_NS1_15BaseHybridClassEE8JavaPartENS0_7JObjectEvE11_javaobjectEEE+28)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #18 pc 000000000002f374  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/lib/arm64/libreanimated.so (_ZN8facebook3jni6detail15FunctionWrapperIPFvNS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassIN10reanimated16AndroidSchedulerENS1_15BaseHybridClassEE8JavaPartENS0_7JObjectEvE11_javaobjectEEEEXadL_ZNS1_13MethodWrapperIMS7_FvvEXadL_ZNS7_9triggerUIEvEES7_vJEE8dispatchESF_EESE_vJEE4callEP7_JNIEnvP8_jobject+56)
12-23 15:49:17.617 19110 19110 F DEBUG   :     #19 pc 000000000006fcec  /data/app/com.cegedim.maiia.pro-BECbb2i3YQ95cYWKOSZwiA==/oat/arm64/base.odex (offset 0x61000)

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-rc 1

**Comment by karol-bisztyga** [comment]
Hi! Could you please provide some reproducing code? Thanks

**Comment by JB-CHAUVIN** [comment]
@karol-bisztyga just use the package react-native restart to reload JS on Android ? App will crash.

**Comment by Szymon20000** [comment]
I've checked on master and it's working fine.  I used react-native-restart just like you said. We have fixed some memory management issues since the last release so it probably doesn't occur anymore.
