### ISSUE TITLE
Updating shared value and then reading it does not return the assigned value

### ISSUE THREAD

**Issue by hardcodet** [software-mansion/react-native-reanimated#1568]
## Description

I had a weird sort of issues that I got down to this here:

- I have a shared value (`useSharedValue`)
- Updating the shared value and immediately reading it returns the old value. This caused havoc down my component tree since I'm passing the shared value around.

I boiled it down to this

- calculate the new value and store it in a local variable (`pos`)
- update the shared variable (`positions.value = pos`)
- log both the local variable and the `value` of my shared value
- they are *not* the same! `positions.value` still returns me it's "old" value

```
        const positions = useSharedValue<Positions>(...);
        
        --

        const pos = Object.assign({}, ... )
        
        // update shared value
        positions.value = pos;
        
        // log both local variable and shared value: positions.value still returns the value from the previous render!
        console.log("...", pos, positions.value);
```

## Steps To Reproduce

See snippet above

### Expected behavior

`positions.value` should return the value I just assigned to it.

### Actual behavior

`positions.value` returns the previously assigned value. This seems to be timing related though - I had other scenarios where this seemed to work (unless this crept in with RC1).

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: RC1
- NodeJS: 14.5.0

**Comment by piaskowyk** [comment]
Hey, well yes, it is true but this is how [shared value](https://docs.swmansion.com/react-native-reanimated/docs/shared-values) works. SharedValue is asynchronous, because we need to update SV on UI thread instead of JS thread.  Look at [setter function](https://github.com/software-mansion/react-native-reanimated/blob/master/Common/cpp/SharedItems/MutableValue.cpp#L39). In summary, Shared Value has asynchronous save and does not support instant update of value. 
What is your use case? Do you really need a synchronous update of SharedValue?

**Comment by hardcodet** [comment]
Hi @piaskowyk  
The problem was that I was passing the shared value down to child components. On re-render, they still used the old value, which messed up pretty much everything. I worked around the issue by simply not doing that, so I guess it boils down to being aware of that limitation. Thanks for chiming in!

**Comment by piaskowyk** [comment]
Is it possible for you to give me example code with this behavior? It'll be helpful for me in finding potential solutions.

**Comment by hardcodet** [comment]
I'd love to help, but I'm afraid that code is gone - there wasn't even an intermediate commit, so i really don't have the snippets anymore. Sorry!
