### ISSUE TITLE
Set Linear Gradient angle through reanimated

### ISSUE THREAD

**Issue by senthilsivanath** [software-mansion/react-native-reanimated#157]
using react-native-linear-gradient, trying to use panResponders output to set the gradient angle. But i am getting error the value is incompatible. 

Possible to use reanimated values in custom views i.e excluding Animated.View and Animated.Image

**Comment by senthilsivanath** [comment]
Got it working. Please correct me if usage is incorrect,

Step 1 : Whitelist the properties that can be modified via reanimated 
Step 2 : Create animated component like Animated.Image by passing your / third party component

```js
Animated.addWhitelistedUIProps('angle')
Animated.addWhitelistedUIProps('useAngle')
const AnimatedLinearGradient = Animated.createAnimatedComponent(LinearGradient)
```
Step 3: Use  AnimatedLinearGradient in your jsx

```jsx
<AnimatedLinearGradient useAngle={true}  angle={this.gestureX} />
```

**Comment by osdnk** [comment]
Hi @senthilsivanath 
Could you try `addWhitelistedNativeProps` instead of 'addWhitelistedUIProps'?

**Comment by osdnk** [comment]
Hey,
I think this issue is outdated for you and decided to close it.
If you still face the problem, please let me know.
