### ISSUE TITLE
useReanimatedProps with custom component not updating on iOS

### ISSUE THREAD

**Issue by eliaslecomte** [software-mansion/react-native-reanimated#1576]
## Description

I'm trying to update text like [ReText from react-native-redash](https://github.com/wcandillon/react-native-redash/blob/master/src/ReText.tsx). This is working correctly on Android but not on iOS.

### Screenshots

Android (where it is working):
![screen-recording-android](https://user-images.githubusercontent.com/636528/103222309-707fb500-4924-11eb-9bb0-0f3f4f896db7.gif)

## Steps To Reproduce

1. Update shared value
2. Update text via animatedProps

### Expected behavior

Text should update without rerender.

### Actual behavior

Text does not update.

## Snack or minimal code example

const sliderValue = useSharedValue(25);

const formatted = useDerivedValue(
    () => `${sliderValue.value}`,
    [currentSliderValue],
  );

<ReText text={formatted} style={{ color: 'black' }} />

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-rc.1
- NodeJS: v12.16.2
- React Native Redash: 16.0.4

**Comment by piaskowyk** [comment]
Hey @eliaslecomte 
I tried to reproduce your issue but I need to know more details about your code. How do you initialise and update `currentSliderValue`? Could you provide me a bigger chunk of example code?

**Comment by Szymon20000** [comment]
```JS
import React, { useEffect } from "react";
import { StyleSheet, View } from "react-native";
import { ReText } from 'react-native-redash';
import Animated, {
  useAnimatedStyle,
  useDerivedValue,
  useSharedValue,
  withSpring,
  withTiming,
} from "react-native-reanimated";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  card: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 100,
    height: 50,
  },
});

const DynamicSpring = () => {
  const x = useSharedValue('0deg');
  useEffect(() => {
    x.value = withTiming('300deg', { duration: 5000 });
  });
  
  return (
    <View style={styles.container}>
      <ReText
        text={x}
        style={{ color: "black", fontVariant: ["tabular-nums"] }}
      />
    </View>
  );
};

export default DynamicSpring;
```

**Comment by eliaslecomte** [comment]
Thanks for the sample code @Szymon20000, having the same issue :-D?

If required I could make a small react-native app to reproduce @piaskowyk and thanks for your time!

**Comment by eliaslecomte** [comment]
The PR https://github.com/software-mansion/react-native-reanimated/pull/1584 does fix it for my app on iOS 👍 . I can't test if there are consequences for Android as I have an issue with building it from that commit 😖 .
