### ISSUE TITLE
React-native-web support

### ISSUE THREAD

**Issue by CanVeeD** [software-mansion/react-native-reanimated#1604]
Is there any information regarding official **support of react-native-web**? Looks like it not working right now

Thanks

**Comment by piaskowyk** [comment]
Hey @CanVeeD 
Reanimated supports web version. You can try to run [example app](https://github.com/software-mansion/react-native-reanimated/tree/master/Example).
To run web version of Example app you should run two commands from Example/package.json:
- `generate-web`
- `start-web`

Is it answer for your question?

**Comment by piaskowyk** [comment]
If you want to know more information about web version, you can look at [this docs](https://docs.swmansion.com/react-native-reanimated/docs/web-support) or create new thread in [discussion](https://github.com/software-mansion/react-native-reanimated/discussions).

**Comment by piaskowyk** [comment]
@CanVeeD Have you any more questions or can I close this issue?

**Comment by karol-bisztyga** [comment]
Actually, `start-web` suffices. Closing this for now.
