### ISSUE TITLE
AnimatedDebug is using depricated global.Expo.Constants object (SDK40)

### ISSUE THREAD

**Issue by Egizas** [software-mansion/react-native-reanimated#1612]
## Description
After upgrading to expo SDK40, I started getting this warning:
```
Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).

The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals
```

After a bit of investigation I found that it is caused the use of `global.Expo.Constants.appOwnership`

## Steps To Reproduce
just use expo SDK 40 and react-native-reanimated

### Expected behavior
No warning is  caused

### Actual behavior
![image](https://user-images.githubusercontent.com/15939884/104135985-a5175600-5393-11eb-8648-8281da2f37d8.png)

## Package versions
1.13.0

Could some one fix this and create PR?

**Comment by Egizas** [comment]
Am I the only one concerned that this library will not be usable with expo SDK41?

**Comment by vikingbr** [comment]
Same problem here

**Comment by thorapps** [comment]
any solution to this?

**Comment by imsam67** [comment]
I understand v2 has been released. Does this new version address/fix this issue we're all experiencing in our apps that use Expo SDK 40? A response, one way or another would be appreciated. Thanks!

**Comment by jakub-gonet** [comment]
Thanks to @brentvatne this fix will be probably patched in the Expo SDK and I'll backport it to the v1, so everyone's versions should keep working.
