### ISSUE TITLE
not able to assign percent values to width

### ISSUE THREAD

**Issue by bharat-tiwari** [software-mansion/react-native-reanimated#1613]
## Description

the way sometimes we set width of some elements in RN stylesheets as percent value - { width: '100%' }, this seem to be  not supported in reanimated2 when used with typescript 

 
### Screenshots

![1](https://user-images.githubusercontent.com/13016554/104148944-f9bdcf80-5399-11eb-99cd-376eac45493d.png)

![2](https://user-images.githubusercontent.com/13016554/104148950-017d7400-539a-11eb-9995-51dc3ab3228a.png)

## Steps To Reproduce
as can be seen in above screenshot

### Expected behavior
string values should be accepted for width prop type in useAnimation 

### Actual behavior
string values are not currently accepted for width prop type in useAnimation 

## Package versions
- React: "16.13.1"
- React Native: "0.63.4"
- React Native Reanimated: "2.0.0-alpha.9.2"
- NodeJS: 12.14.0

**Comment by abumubarak-dev** [comment]
@bharat-tiwari  you the % inside the withTiming instead of the useSharedValue
E.g 
<img width="493" alt="Screenshot 2024-06-15 at 18 42 55" src="https://github.com/software-mansion/react-native-reanimated/assets/47022889/c89c4103-4a42-4708-856d-cf6ff30cc4a1">
