### ISSUE TITLE
Problem with React Navigation drawers - screen overlay not removed

### ISSUE THREAD

**Issue by pinpointpanda** [software-mansion/react-native-reanimated#1616]
## Description

Not 100% sure if this is a `reanimated` thing or one for `react-navigation`, however, with reanimated `2.0.0-rc.1` there is a weird bug when using a React Navigation drawer on **Android** that seems to prevent the overlay being removed correctly. It results in a screen being unclickable. This doesn't happen with previous versions of reanimated (tested with `2.0.0-alpha.6` and bug is not present) and doesn't seem to happen on iOS either.

### Screenshots

Video below:
https://user-images.githubusercontent.com/25434369/104173823-9e75f680-5406-11eb-9977-232a9b37bb53.mp4

## Steps To Reproduce

1. Clone [this repo](https://github.com/pinpointpanda/reanim-drawer-bug)
2. Run `yarn` to install packages (latest `react-navigation` is in here)
3. Run `yarn android` to run on your simulator/device.
4. Click the animate button a few times - everything works as expected
5. Click 'Open Drawer' - the drawer opens
6. Click on the backdrop to hide the drawer - the drawer will close
7. Try and click anything else on the screen - it's not possible, like there's some kind of overlay still in place.

(If you slide the drawer out from the left-hand edge and slide it back in again, the screen does work as expected. It's only when clicking on the backdrop to remove the overlay that this bug occurs).

### Expected behavior

Drawer should work as expected and the screen should remain interactive once the drawer is closed.

### Actual behavior

Screen can't be interacted with once the drawer has closed.

## Snack or minimal code example

[Minimal code repo](https://github.com/pinpointpanda/reanim-drawer-bug)

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc.1
- NodeJS: 12.16.3

**Comment by zethius21** [comment]
Same issue on latest build (with @react-navigation/drawer: 5.11.5)

**Comment by Empty44** [comment]
Same problem with @react-navigation/drawer: 5.11.5 and react-native-reanimated: 2.0.0-rc.2

**Comment by pandevim** [comment]
This bug persists for `"@react-navigation/drawer": "5.12.2"`

**Comment by sarthakpranesh** [comment]
Hey, I am facing the same issue with `2.0.0-rc.2`. Is there a temporary fix for this bug that can be used for now, while we wait for the next release with bug fixes?

**Comment by AhmadHddad** [comment]
Is there any workaround for @react-navigation/drawer I tried to install the latest version and the bug still persists.

**Comment by sarthakpranesh** [comment]
Hey @AhmadHddad, I tried the `2.0.0-alpha.6` as mentioned by @pinpointpanda in the issue. This version works well with `@react-navigation/drawer`, only issue is it required extra configuration on iOS. Looking forward for the `rc.3` release 🚀

**Comment by jakub-gonet** [comment]
@sarthakpranesh
@AhmadHddad
> Hey, I am facing the same issue with 2.0.0-rc.2. Is there a temporary fix for this bug that can be used for now, while we wait for the next release with bug fixes?

You can use [patch-package](https://www.npmjs.com/package/patch-package) to temporarily use patch from #1665.

**Comment by AhmadHddad** [comment]
@sarthakpranesh, @jakub-gonet, thanks guys, I was able to downgrade to a lower version of @react-navigation/drawer, it worked just fine  "@react-navigation/drawer": "^5.9.0",

**Comment by pinpointpanda** [comment]
Thanks for the resolve! Can confirm that this is no longer an issue in `2.0.0-rc.3` 🎉

**Comment by tomo10** [comment]
hello

Still having issue an issue with the following setup:
"react-native-reanimated": "^2.0.0"
"@react-navigation/drawer": "5.12.3" 

I've also tried reanimated "2.1.0"

When loading screen within Drawer Navigator on Android get err:
"Cannot read property setNativeView of undefined"

**Comment by pinpointpanda** [comment]
@tomo10 - that seems to be a different error to the one in this issue. Probably a good idea to create a new issue, along with a reproduction Snack/repo.
