### ISSUE TITLE
scrollTo doesnt work or respond to the web

### ISSUE THREAD

**Issue by oldi92** [software-mansion/react-native-reanimated#1627]
## Description
I am building a drag and drop app similiar to trello cards. I used the Reaniamted 2 playground repo as a start. When i am dragging a cloumn i want  to scroll programmatically in x axis with the scrollTo provided by Reaniamted v2. In the ios and android it is work just perfect and you can scroll. In web it doesnt respond at all, it is not throwing any erros it no showing anything it just doesnt work.

### Expected behavior
Expected to scroll left or right

### Actual behavior
The scrollTo doesnt work or respond at all

## Steps To Reproduce

Use the onScroll attribute with event from reanimated
The animated value is not updating

1. Create an Animated.Scrollview component
2. Pass it a useAniamtedRef from Reaniamted 2 as a ref
3. Import and use scrollTo from Reaniamted 2 library and pass it a random x value to check if it is scrolling 

## Package versions

Expo Asset: 8.2.0
React Native: 0.63.4
React Native Reanimated: 2.0.0-rc.1
React Native Web: 0.14.7

**Comment by karol-bisztyga** [comment]
Hi!
I don't know what code you are using so it's hard to tell what went wrong but my prediction is that you invoked `scrollTo` incorrectly for the web. Take a look at this code:

```
import React from 'react';
import { scrollTo, useAnimatedRef } from 'react-native-reanimated';
import { ScrollView, View, Button, Platform } from 'react-native';

export default function Test() {
  const aref = useAnimatedRef();

  return (
    <>
      <Button
        title="press"
        onPress={() => {
          const y = Math.random() * 700;
          console.log('here', y)

          if (Platform.OS === 'web') {
            if (aref && aref.current) {
              aref.current.scrollTo({ y });
            }
          } else {
            scrollTo(aref, 0, y, true);
          }
        }}
      />
      <View style={{ height: 300 }}>
        <ScrollView style={{ backgroundColor: 'green', width: 120 }} ref={aref}>
          {Array(10)
            .fill(null)
            .map((_, i) => {
              return (
                <View
                  key={i}
                  style={{
                    width: 100,
                    height: 100,
                    backgroundColor: i % 2 ? 'purple' : 'orange',
                  }}
                />
              );
            })}
        </ScrollView>
      </View>
    </>
  );
}

```

**Comment by karol-bisztyga** [comment]
Let me know if that solves your problem.

**Comment by oldi92** [comment]
It work, i used the ref.current.scrollTo as you said. Thank you!

**Comment by karol-bisztyga** [comment]
Cool. This is because there's no UI thread on the web so we can simply call `scrollTo` from the `ScrollView` just like that(it's [here](https://github.com/facebook/react-native/blob/aebccd3f923c920bd85fb9e5fbdd2a8a75d3ad3d/Libraries/Components/ScrollView/ScrollView.js#L834)).

I know it's not in the docs(the page is unfinished) - sorry about that, we will try to update the docs soon.

**Comment by oldi92** [comment]
No worrie at all thank you guys. You have done a huge work reanimated 2 docs are just the cherry in pie :)
