### ISSUE TITLE
Drop in performance with a lot of objects

### ISSUE THREAD

**Issue by alexfov** [software-mansion/react-native-reanimated#1635]
## Description

Hello dear developers. I just encountered big drop in performance compared with reanimated v1 when you have about 50 Views with own SharedValue and own rotate transformation (especially on android device) . V2 shows about 40 fps, when v1 shows 60. Is v1 more performant? Or I do something wrong?

### Screenshots
v2

https://user-images.githubusercontent.com/39302602/104703629-9da3d400-5728-11eb-960f-7f667257cd3f.mp4

v1

https://user-images.githubusercontent.com/39302602/104703724-bdd39300-5728-11eb-9add-1c588a51279c.mp4

## Steps To Reproduce
Use code below or:
1.  Add 50 Animated.Views with own Shared value and run rotate transformation

### Expected behavior
60fps

### Actual behavior
40fps

## Snack or minimal code example
```js
import { loop } from "react-native-redash/src/v1";

const dummy = new Array(50).fill(1);
function App() {
  return (
    <View style={{ flex: 1, flexDirection: "row", flexWrap: "wrap" }}>
      {dummy.map((_, i) => {
        const val = useSharedValue(0);

        val.value = withRepeat(
          withTiming(1, { duration: Math.random() * 2000 + 4000 }),
          -1
        );

        const style = useAnimatedStyle(() => {
          return {
            transform: [
              { rotate: interpolate(val.value, [0, 1], [0, Math.PI * 2]) + "rad" },
            ],
          };
        });

        //reanimated1 code
        // const val = loop({ duration: Math.random() * 2000 + 4000 });

        // const style = {
        //   transform: [
        //     {
        //       rotate: concat(
        //         interpolateNode(val, {
        //           inputRange: [0, 1],
        //           outputRange: [0, Math.PI * 2],
        //         }),
        //         "rad"
        //       ),
        //     },
        //   ],
        // };
        return (
          <Animated.View
            key={i}
            style={[
              {
                width: 60,
                height: 60,
                borderWidth: 1,
                backgroundColor: `hsl(${(360 / dummy.length) * i}, 100%, 40%)`,
              },
              style,
            ]}
          />
        );
      })}
    </View>
  );
}
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-alpha.9.2
- NodeJS: 14.15.1
- Android 9 (Redmi Note7) but the same on IOS with bigger Views count

**Comment by chybisov** [comment]
Also facing this issue, but with just 6 views and transform scale. FPS ~40-50 😞

**Comment by jakub-gonet** [comment]
Discussion about this issue: https://github.com/software-mansion/react-native-reanimated/discussions/1632

**Comment by bitmnemonix** [comment]
I have the same issue with as few as 3 objects on a not so high-end samsung tablet, for 10 object it went down to 30-40fps and
for 100 ojects it was like 3fps

`const OSIZE = 100;

//---------------------------------------------------------------
//
//---------------------------------------------------------------
export default function App() {
    const frames = useSharedValue(0);
    useEffect(() => {
        frames.value = withTiming(1, {duration: 12000});
    }, []);

    const aniStyle = new Array(OSIZE).fill(0).map((_, i) =>
        useAnimatedProps(() => {
        return {
            y: interpolate(frames.value, [0, 1], [0, windowHeight - 50], Extrapolate.CLAMP)
        }
    }, []));

    return <View style={[{...StyleSheet.absoluteFill}]}>
        <Svg key={'s'} height={windowHeight} width={windowWidth} 
            style={[{position: 'absolute'}]}>
            {new Array(OSIZE).fill(0).map((_, i) =>
              <AnimatedRect key={'r' + i} x={Math.random()*windowWidth} animatedProps={aniStyle[i]} width="50" height="50" fill={'pink'}/>
            )}
       </Svg>
    </View>
}
`

**Comment by piaskowyk** [comment]
We improved performance since 2.3.+ version - https://github.com/software-mansion/react-native-reanimated/pull/1879

**Comment by piaskowyk** [comment]
@bitmnemonix now you can use shared animated style (one style for many components) and this will instantly improve your performance.
Results here - https://twitter.com/kzzzf/status/1421104290085576710

**Comment by alexfov** [comment]
Thank you, software mansion, great job
