### ISSUE TITLE
[V2.0.0-rc.2] Android files missing from npm module

### ISSUE THREAD

**Issue by evengul** [software-mansion/react-native-reanimated#1649]
## Description

I was trying to implement Reanimated V2 (RC.2) on our react native (0.63.3) project, but found that the files under `android` only contains the files from `android-npm`, which only has an empty class in it. In the docs, it said to `import com.swmansion.reanimated.ReanimatedJSIModulePackage;`, but I can't do this since the files aren't there. I tried to get them from the [build artifacts](https://github.com/software-mansion/react-native-reanimated/actions?query=workflow%3A%22Build+npm+package%22) as well, but these don't have the necessary files either. Could I be missing some step in my process here, or is there actually something missing?

### Screenshots
![file structure of react-native-reanimated in node_modules](https://firebasestorage.googleapis.com/v0/b/flatz-60aa7.appspot.com/o/images%2Fissue%2020.01.2021.png?alt=media&token=ecec3cd8-2265-4b9c-8f84-d412eaac8ae9)

Here is the file structure of `react-native-reanimated` in the node_modules folder. As you can see, `com.swmansion.reanimated.ReanimatedJSIModulePackage` isn't here.
## Steps To Reproduce

1. `npm install react-native-reanimated@2.0.0-rc.2`
2. `import com.swmansion.reanimated.ReanimatedJSIModulePackage;` in `MainApplication.java` in the react-native project.

### Expected behavior
The file should exist in the `android/src` folder.

### Actual behavior
The file isn't there, and can't be imported.

## Snack or minimal code example

Terminal: `npm install react-native-reanimated@2.0.0-rc.2`
`MainApplication.java`: `import com.swmansion.reanimated.ReanimatedJSIModulePackage;`

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-rc.2
- NodeJS: Not used here?

**Comment by evengul** [comment]
Apparantly the files were included in some other place, Android Studio automagically found them when I cleaned and compiled debug sources for my project.

**Comment by matiasmm** [comment]
I'm still having tis issue.

```
Cannot resolve symbol: 'ReanimatedJSIModulePackage'
```

When i import `import com.swmansion.reanimated.ReanimatedJSIModulePackage;`
