### ISSUE TITLE
Using Reanimated 2 with MobX 5

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#1650]
In my project im using MobX5 also Firebase. 
These packages were required  to `disable` Hermes module.

If i turn on i get this error 
`Error: [mobx] MobX 5+ requires Proxy and Symbol objects. If your environment doesn't support Symbol or Proxy objects, please downgrade to MobX 4. For React Native Android, consider upgrading JSCore., js engine: hermes`
 

and if i try to use it without hermes the app just crashing.

so how can I use v2 of reanimated in this case?

**Comment by tankers746** [comment]
I use reanimated V2 with mobx 5 and hermes (0.5.2-rc1) and have not seen that error.

**Comment by a-eid** [comment]
this is not related to reanimated 2, this is a hermes issue, please check this issue 
https://github.com/facebook/hermes/issues/33

also version 0.64 should have hermes that supports proxies by default.
