### ISSUE TITLE
Update useSharedValue and others not to reinitialize on re-render

### ISSUE THREAD

**Issue by kmagiera** [software-mansion/react-native-reanimated#1655]
This issue is about making a change in `useSharedValue` and `useEvent` to avoid reinitializing the value when rerender with a different init value happens.

## Description

The logic responsible for overriding shared value has been added in #1042 as a mean of handling fast reloads. The ideas seemed to be that when fast reload happens, we may provide a different init value for the hook and hence the shared value should also update. However, the solution which relied on checking whether the init value is different than the previously used init value also triggers when component is rerendered with a different init. In such a case we'd reset shared value in many cases causing unexpected updates or stopping the currently running animation.

This problem has been reported in #1293 and addressed in #1351 by adding an additional parameter that can be used to prevent "rebuild". However, this does not seem like a good way of resolving the problem. It seem like the default behavior is actually to never rebuild unless we have a refresh. This is exactly how hook like `useState` works. It appears to differentiate between cases when it needs to update because of refresh and prevents state resets when new init value is provided but there was no refresh.

I think the best way to go with this is bascially rely on `useState` mechanism when creating shared value. This should give us exact same behavior to `useState`. Here is one way `useSharedValue` can be implemented:

```js
export function useSharedValue(init) {
  return useState(() => makeMutable(init))[0];
}
```

(I haven't tested this implementation but you get the idea)

## Steps To Reproduce

1. Make component that takes some prop and use that prop as init for useSharedValue 
2. Make that component re-render with different values provided to the prop

### Expected behavior

The shared value should never update after the first time it is initialized. It should update however if we change the init value in the source code and perform fast refresh.

### Actual behavior

See that the shared value updates matching the newly provided init.

## Snack or minimal code example

Don't have a snack example for this. I'm sorry dear issue checker bot.

## Package versions

- React: 16
- React Native: 0.63
- React Native Reanimated: 2.0.0-rc.2
- NodeJS: idk

**Comment by karol-bisztyga** [comment]
Hey!
The code you posted will not work because of the `problem 2` from #1619. We have to explicitly break animations on component unmount. I think what would suffice here is to set the default value of `shouldRebuild` parameter to `false` or we could remove the rebuilding code totally.

**Comment by kmagiera** [comment]
then in addition we can still keep the `useEffect` bit to facilitate unmounting. When it comes to `useSharedValue` with `false` it breaks fast reload scenarios (that is it never updates while it is expected for the new values to be used on reload). Using `useState` seem like a much simpler and more resilient way

**Comment by karol-bisztyga** [comment]
I think the current version of the hooks works ok with `false` passed as rebuild argument. You can try this code:

```
import { useSharedValue } from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React, { useState } from 'react';

export default function AnimatedStyleUpdateExample(props) {
  const [state, setState] = useState(77);
  const [stateCopy, setStateCopy] = useState(state);
  const svRebuild = useSharedValue(state);
  const svNotRebuild = useSharedValue(state, false);

  setImmediate(() => {
    console.log(
      'render',
      state,
      svRebuild.value,
      stateCopy,
      svNotRebuild.value
    );
  })

  return (
    <View>
      <Button
        title="set state"
        onPress={() => {
          setState(state + 1);
        }}
      />
    </View>
  );
}
```

`svNotRebuild` does not update on render(when the state is being changed) but it does on fast refresh(when you modify value passed to the first call of `useState` in the component and save the file). Can you verify? Am I missing something?

**Comment by sreuter** [comment]
I'm not sure if it's 100% related, but I'm still running into similar issues in the latest version: https://github.com/software-mansion/react-native-reanimated/issues/2019
