### ISSUE TITLE
"TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found" on Android with Expo SDK40

### ISSUE THREAD

**Issue by outaTiME** [software-mansion/react-native-reanimated#1662]
Hi guys,
I had already reported an error for this topic before but I did not have the error stack since it is something that occurs randomly in some androids, and I also could not physically reproduce it in any of my devices.

https://github.com/software-mansion/react-native-reanimated/issues/1454

Yesterday one of the users of my application sent me a screenshot of the error report.

An issue was created for this issue in the expo repository, I hope it is useful and can help us solve its cause:

https://github.com/expo/expo/issues/11672 

Thanks !!!

**Comment by sfalihi** [comment]
i'm getting this error, too
i cleared .gradle but still getting this error.

**Comment by Sandeep155Vibhuti** [comment]
Please follow the Original Doc :->
https://docs.swmansion.com/react-native-reanimated/docs/installation/

**Comment by p2mittal-dev** [comment]
**Error - TurboModuleRegistry.getEnforcing(...): 'NativeReanimated'**
**Cause - React Native Reanimated 2.0**

Hello,
I got this[TurboModuleRegistry.getEnforcing(...): 'NativeReanimated'] error and i found the solution 
Step 1 - Download react native project from github  "https://github.com/software-mansion-labs/reanimated-2-playground".
Step 2- Then run command 
=> npm install
=> react-native start
=> react-native run-android
and build app 
Step 3- when its work move your required project files and install your required npm pakages.
Step 4 - Then run commands
=> npm cache clean --force
=> cd android
=> gradlew clean
=> gradle cleanBuildCache
=> gradlew build --refresh-dependencies
=> cd..
=> npx react-native start --reset-cache
=> npx react-native run-android
its work for me try once.

**Comment by piaskowyk** [comment]
We removed TurboModuleRegistry some time ago - https://github.com/software-mansion/react-native-reanimated/pull/1845
I recommend update Expo and Reanimated, but if after this the issue will still affect you, you should clear cache like in @p2mittal-dev 's comment.
