### ISSUE TITLE
React Native Debugger - ERROR - TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' 

### ISSUE THREAD

**Issue by ionflow** [software-mansion/react-native-reanimated#1663]
## Description

Running a basic example in an Expo client while running React Native Debugger on port 19000. Getting the following error:

Invariant Violation
ExceptionsManager.js:179
TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

### Screenshots

![image](https://user-images.githubusercontent.com/4053903/105948014-0fc8c280-601f-11eb-9b8e-5f46356dad53.png)

### Expected behavior

No errors

### Actual behavior

Error (see above)

## Snack or minimal code example

```
import Animated, {
  useSharedValue,
  withTiming,
  useAnimatedStyle,
  Easing,
} from "react-native-reanimated";
import { View, Button } from "react-native";
import React from "react";

export default function AnimatedStyleUpdateExample(props) {
  const randomWidth = useSharedValue(10);

  const config = {
    duration: 500,
    easing: Easing.bezier(0.5, 0.01, 0, 1),
  };

  const style = useAnimatedStyle(() => {
    return {
      width: withTiming(randomWidth.value, config),
    };
  });

  return (
    <View>
      <Animated.View
        style={[
          { width: 100, height: 80, backgroundColor: "black", margin: 30 },
          style,
        ]}
      />
      <Button
        title="toggle"
        onPress={() => {
          randomWidth.value = Math.random() * 350;
        }}
      />
    </View>
  );
}
```

## Package versions
```
{
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.3",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-reanimated": "2.0.0-rc.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-preset-expo": "8.3.0"
  },
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo web",
    "eject": "expo eject"
  },
  "private": true
}
```

**Comment by productfrontenddeveloper** [comment]
The same problem happened with me.

**Comment by piaskowyk** [comment]
Hey @ionflow
My first association with this issue is a missing configuration Reanimated for android. Did you add a dependency to `MainApplication.java`, enabled Hermes, and added the babel plugin? It isn't added by default, unfortunately 😕
Look at this instruction: https://docs.swmansion.com/react-native-reanimated/docs/installation
Please let me know if it doesn't help then I will check this.

**Comment by productfrontenddeveloper** [comment]
@piaskowyk 

> My first association with this issue is a missing configuration Reanimated for android. Did you add a dependency to `MainApplication.java`, enabled Hermes, and added the babel plugin? It isn't added by default, unfortunately 😕
> Look at this instruction: https://docs.swmansion.com/react-native-reanimated/docs/installation
> Please let me know if it doesn't help then I will check this.

These are all attached. I am having the same problem. 
![Screen Shot 2021-02-01 at 13 34 53](https://user-images.githubusercontent.com/38668796/106447310-648e9200-6492-11eb-9ae9-9eaffbbdafa6.png)

**Comment by dpyeates** [comment]
I see this on iOS. It ONLY happens when you turn on debugging. With debugging turned off it does not occur.

**Comment by jakub-gonet** [comment]
Have you tried using [Flipper](https://fbflipper.com/) for debugging? 
Remote debugging in Chrome works by running JS code in Chrome's V8 and connecting to the Bridge. We use Turbomodules (which don't use Bridge at all) so Chrome can't connect with the native side – this error is expected but could be described better. 
AFAIK Flipper should work with Android without problems on any recent RN version and iOS should work after RN 0.64.

**Comment by productfrontenddeveloper** [comment]
@jakub-gonet hmm flipper used thank you. 
How to console.log() see flipper ?

**Comment by walterholohan** [comment]
@jakub-gonet when do you think a update will be pushed to fix this issue? 

We are using this library in a project however some of our developers use the chrome debugger to debug our app on a physical ios device. Flipper is sometimes difficult to get working on a real physical device.

**Comment by jakub-gonet** [comment]
It's not a matter of fixing this issue - chrome debugging works via running JS in the browser and establishing a tunnel to the native app via the bridge. Turbomodules doesn't use the bridge and they're C++ binaries without any means of communication so running their code through chrome is impossible. The only way to debug a component written with turbomodule integration is by using Flipper.

**Comment by eee9** [comment]
The same error on react native cli project. react native reanimated 2.0.0.
It doesn't matter device/emulator and Hermes on/off.
When I downgrade react native reanimated to 1.13.2 the error disappear.

**Comment by derekblank** [comment]
> The only way to debug a component written with turbomodule integration is by using Flipper.

@jakub-gonet Yikes. We've turned off Flipper in our app and removed all references to it. I don't think we'll ever go back to using it. Does that mean we can't/shouldn't ever use react-native-reanimated@2.0.0? Or is there a possibility in the future that rna2 would work without Flipper?

**Comment by Dakuan** [comment]
dealbreaker over here :(

**Comment by arled** [comment]
This is still an issue. is there a fix for this?!!!!!!

**Comment by walterholohan** [comment]
@arled there is no fix. This is expected behaviour. Check out @jakub-gonet answer above. TLDR: use flipper to debug

**Comment by Dakuan** [comment]
Flipper doesn't work with expo...we have reluctantly refactored to remove all our renanimated code :(

**Comment by range-of-motion** [comment]
Same issue here, once you enable debugging shit hits the fan (same error as OP).

**Comment by fjaffrezic** [comment]
Same issue :-(

**Comment by devshorts** [comment]
What does "use flipper to debug" even mean? Flipper doesn't have a way to connect to a debug port to set breakpoints. You still can't do performance profiling. If "debug" just means see "console.log" statements thats a poor statement of debugging.

**Comment by 1337mus** [comment]
@jakub-gonet Any thoughts on @devshorts comment above? Thanks in advance.

**Comment by AzeemSarwar1** [comment]
No update till react-native-reanimated 3.3.0😩

**Comment by piaskowyk** [comment]
Latest version of Reaniamted 2 (2.17.0) and 3 (3.4.0). should supports remote debugger 🤔

**Comment by amadeus** [comment]
When attempting to profile on the UI thread, I can start the profiler, but when I end it, the app crashes (both on ios and android) with the following error: 

<img width="864" alt="CleanShot 2023-08-15 at 15 18 04@2x" src="https://github.com/software-mansion/react-native-reanimated/assets/83376/934125e4-d0cb-4ed6-a348-9253e6c8eeec">
