### ISSUE TITLE
"No bundle URL present" error in Example app

### ISSUE THREAD

**Issue by vandrieu** [software-mansion/react-native-reanimated#1673]
## Description

After following the steps from the react-native-reanimated/Example page (https://github.com/software-mansion/react-native-reanimated/tree/master/Example), my Simulator show up and reads:
```
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
```
### Screenshots

<img width="437" alt="Capture d’écran 2021-01-29 à 01 31 25" src="https://user-images.githubusercontent.com/46876905/106215682-c8366800-61d1-11eb-8e5b-b085fb10a865.png">

## Steps To Reproduce

The steps to reproduce are the ones from react-native-reanimated/Example/README.md:

- clone the repository
- yarn install
- cd Example/
- yarn install
- cd ios && pod install && cd ..
- react-native run-ios

### Expected behavior

Example app works

### Actual behavior

Example app reads "No bundle URL present"

## Snack or minimal code example

No code added compared to https://github.com/software-mansion/react-native-reanimated/tree/master/Example

## Package versions

See package.json from https://github.com/software-mansion/react-native-reanimated/tree/master/Example

**Comment by karol-bisztyga** [comment]
This command does not seem to run the metro server. Please run the following command in the Example directory: `yarn start`. After that, please reload the app.

**Comment by vandrieu** [comment]
Thanks for the solution @karol-bisztyga

**Comment by cheehieu** [comment]
Ran into this runtime error while upgrading to React Native 0.72 and Reanimated 3.4.1... What eventually worked for me was deleting the `yarn.lock` file and rebuilding.
