### ISSUE TITLE
interpolateNode is not a function

### ISSUE THREAD

**Issue by DeniferSantiago** [software-mansion/react-native-reanimated#1677]
## Description
I just updated reanimated to version 2.0.0-rc.2, following the steps in [the documentation](https://docs.swmansion.com/react-native-reanimated/docs/installation) then I have read [the migration guide](https://docs.swmansion.com/react-native-reanimated/docs/migration) in which it tells me that I should change my imports from interpolate to interpolateNode and I have done so, but unfortunately I get the following error:
### Screenshots
![WhatsApp Image 2021-01-29 at 6 20 45 PM](https://user-images.githubusercontent.com/41799285/106333407-f7df8180-625e-11eb-8cda-da9103425fa5.jpeg)

## Steps To Reproduce
These are the steps I have taken:

1. Update reanimated: `npm i react-native-reanimated@next`
2. Add babel plugin: `react-native-reanimated/plugin` in _babel.config.js_
3.  Turn on Hermes engine, setting: `enableHermes: true` in _android/app/build.gradle_
4. modify the _MainAplication.java_ file as the documentation [indicates](https://docs.swmansion.com/react-native-reanimated/docs/installation#android)
5. Clean gradle proyect: `cd android; ./gradlew clean`
6. Run the project for android

Also I have tried to clear cache and everything like that as indicated [here](https://stackoverflow.com/a/51375437/10112486).

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc.2
- NodeJS: 6.14.7

**Comment by jakub-gonet** [comment]
Have you tried using yarn? There were similar reports in the past and sometimes using yarn helped.

**Comment by L-Yeiser** [comment]
In react-native-reanimated 2.2.0 Animated.interpolate is no longer a function. To quote the docs:
```
When using interpolate imported directly from react-native-reanimated v1, in v2 you should use interpolateNode instead. If you were using a class member method AnimatedValue.interpolate, no change is necessary.
```

**Comment by chandniKkpl** [comment]
I am using react native version 0.66.4 and Reanimated version 1.8.0 and I am getting this error 
The error message "TypeError: (0, _reactNativeReanimated.useAnimatedRef) is not a function" typically occurs in React Native when there is an issue with importing or using the useAnimatedRef function from react-native-reanimated

**Comment by divonelnc** [comment]
> In react-native-reanimated 2.2.0 Animated.interpolate is no longer a function. To quote the docs:
> 
> ```
> When using interpolate imported directly from react-native-reanimated v1, in v2 you should use interpolateNode instead. If you were using a class member method AnimatedValue.interpolate, no change is necessary.
> ```

The issue is not with interpolate, but with interpolateNode. I am also running into this... I am using Animated.interpolateNode but I get the "_reactNativeReanimated.default.interpolateNode is not a function" error.
