### ISSUE TITLE
TypeError: (0, _reactNativeReanimated.useAnimatedRef) is not a function

### ISSUE THREAD

**Issue by danielfein** [software-mansion/react-native-reanimated#1678]
## Description
I just installed react-native-reanimated@next and am using rc.2. Received this error:

`TypeError: (0, _reactNativeReanimated.useAnimatedRef) is not a function. (In '(0, _reactNativeReanimated.useAnimatedRef)()', '(0, _reactNativeReanimated.useAnimatedRef)' is undefined)`

If I console.log(useAnimatedRef) it's undefined.

## Steps To Reproduce

1. Install react-native-reanimated@next
2. import useAnimatedRef `import { useAnimatedRef } from 'react-native-reanimated'`
3. assign to variable: `const containerRef = useAnimatedRef()`

### Expected behavior

I'd expect useAnimatedRef to be assigned to containerRef

### Actual behavior

Instead React Native complains here:

![Simulator Screen Shot - iPhone 11 - 2021-01-30 at 08 44 30](https://user-images.githubusercontent.com/1616865/106357967-62cc9f00-62d7-11eb-9921-723ae766a92d.png)

## Snack or minimal code example

```
import { useAnimatedRef } from 'react-native-reanimated'
const Thing = (props) => {
  const containerRef = useAnimatedRef()
}
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc.2

**Comment by piaskowyk** [comment]
Maybe this is related to your issue: https://github.com/software-mansion/react-native-reanimated/issues/1677#issuecomment-770654402 Do you use `yarn` or `npm`?

**Comment by danielfein** [comment]
That was it, I was using npm. After switching to Yarn it worked! thank you!

**Comment by chandniKkpl** [comment]
I used Yarn but it is still not working
