### ISSUE TITLE
Reanimatedv2 Task :app:checkDebugAarMetadata FAILED

### ISSUE THREAD

**Issue by productfrontenddeveloper** [software-mansion/react-native-reanimated#1680]
## Description

```

> Task :app:checkDebugAarMetadata FAILED

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-64.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: /aaa-reactnative/node_modules/react-native-reanimated/android/react-native-reanimated-64.aar.
         > Transform's input file does not exist: /aaa-reactnative/node_modules/react-native-reanimated/android/react-native-reanimated-64.aar. (See https://issuetracker.google.com/issues/158753935)
```

## Steps To Reproduce

1. yarn react-native run-android 

## Package versions

- React: 17.0.1
- React Native: 0.64.0-rc.2
- React Native Reanimated: ^2.0.0-rc.2
- NodeJS: v14.15.3

**Comment by piaskowyk** [comment]
Hey @productfrontenddeveloper 
We haven't support `react-native@0.64` yet. I made PR who has added this support for android. I think we will add this within the next release.

**Comment by zifahm** [comment]
@piaskowyk  in the mean time is there a work around? patch package it or somethin?

**Comment by productfrontenddeveloper** [comment]
```
> Configure project :react-native-reanimated
Native libs debug enabled: false

FAILURE: Build failed with an exception.

* Where:
Build file '/asd/node_modules/react-native-reanimated/android/build.gradle' line: 72

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> /asd/node_modules/react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
```

**Comment by productfrontenddeveloper** [comment]
@piaskowyk 

```
> Configure project :react-native-reanimated
Native libs debug enabled: false

FAILURE: Build failed with an exception.

* Where:
Build file '/asd/node_modules/react-native-reanimated/android/build.gradle' line: 72

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> /asd/node_modules/react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
```

**Comment by piaskowyk** [comment]
Do you use a building script? https://github.com/software-mansion/react-native-reanimated/blob/master/createNPMPackage.sh

**Comment by productfrontenddeveloper** [comment]
> Do you use a building script? https://github.com/software-mansion/react-native-reanimated/blob/master/createNPMPackage.sh

no, i am used yarn android or 
```cd android; ./gradlew cleanBuildCache; cd ..``` 
or android studio run some problem

**Comment by productfrontenddeveloper** [comment]
@piaskowyk

![image](https://user-images.githubusercontent.com/38668796/106742806-90467f00-662e-11eb-8ec4-b0344084b5e5.png)
and  some problem

**Comment by piaskowyk** [comment]
To build a package you should use a `createNPMPackage.sh`
But this problem: `./createNPMPackage.sh: line 19: gladle: command not found` - it's mean you haven't installed `gradle` globally on your computer

**Comment by productfrontenddeveloper** [comment]
@piaskowyk 
global gradle add and sh buiild
```
success Saved 0 new dependencies.
✨  Done in 107.34s.
+ rm -rf 'android/build/outputs/aar/*.aar'
+ cd android
+ gradle clean

Welcome to Gradle 6.8.1!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8.1/release-notes.html
```

```
> Configure project :react-native-reanimated
Native libs debug enabled: false

FAILURE: Build failed with an exception.

* Where:
Build file '/asd/node_modules/react-native-reanimated/android/build.gradle' line: 72

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> /asd/node_modules/react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by piaskowyk** [comment]
It looks like you try to build a package inside node_modules, right? Let me know if I'm wrong.
I'm not sure how you built this, but should do this in this way:
`git clone https://github.com/software-mansion/react-native-reanimated.git && cd react-native-reanimated && yarn && ./createNPMPackage.sh`
And if this still doesn't work for you please let me know.

**Comment by productfrontenddeveloper** [comment]
> It looks like you try to build a package inside node_modules, right? Let me know if I'm wrong.
> I'm not sure how you built this, but should do this in this way:
> `git clone https://github.com/software-mansion/react-native-reanimated.git && cd react-native-reanimated && yarn && ./createNPMPackage.sh`
> And if this still doesn't work for you please let me know.

@piaskowyk 
iam react native project create .sh and run .sh

![Screen Shot 2021-02-03 at 17 31 10](https://user-images.githubusercontent.com/38668796/106761185-9dbb3380-6645-11eb-8f11-2ce736d66109.png)

**Comment by productfrontenddeveloper** [comment]
```
* What went wrong:
A problem occurred evaluating root project 'android'.
> NDK is not installed
```


![Screen Shot 2021-02-03 at 19 25 39](https://user-images.githubusercontent.com/38668796/106776967-9ac83f00-6655-11eb-840d-5834f236cf64.png)

**Comment by productfrontenddeveloper** [comment]
thank you fixed

**Comment by productfrontenddeveloper** [comment]
New problem :)

yarn android 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':react-native-reanimated:buildReanimated' (type 'Exec').
> Directory '/aaa/node_modules/react-native-reanimated/android/src/main/Common' specified for property '$3' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Comment by productfrontenddeveloper** [comment]
> New problem :) @piaskowyk @jakub-gonet
> 
> yarn android
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem was found with the configuration of task ':react-native-reanimated:buildReanimated' (type 'Exec').
> > Directory '/aaa/node_modules/react-native-reanimated/android/src/main/Common' specified for property '$3' does not exist.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ```

@piaskowyk  @jakub-gonet Did you see my message?

**Comment by jakub-gonet** [comment]
Yes, I've got it twice in my notifications. Please don't tag maintainers that often, we dedicate only part of our time to checking issues and we definitely _can see_ responses and tagging. Issues are dedicated to actual bugs. We don't usually provide support for problems with builds or configs, those should be submitted in [QA section of Discussions](https://github.com/software-mansion/react-native-reanimated/discussions/categories/q-a).

That being said, I suppose you still try building reanimated in the node_modules, this won't work. The only way to generate a package is to follow the advice written by @piaskowyk [here](https://github.com/software-mansion/react-native-reanimated/issues/1680#issuecomment-772550598) or reiterated by me [here](https://github.com/software-mansion/react-native-reanimated/issues/1680#issuecomment-772569424).

The simplest way though is to wait for the release which should happen in the next few days. You can also use daily builds, instructions are [described in the documentation](https://docs.swmansion.com/react-native-reanimated/docs/next/installation#using-master-branch-builds).

**Comment by RapestaNatalia** [comment]
Hi guys,

I have a similar problem, but not exactly the same:

```
What went wrong:
Execution failed for task ':app:mergeDevDebugAssets'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
  > Failed to transform react-native-reanimated-63.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}.
   > Execution failed for JetifyTransform: /Users/nataliarapesta/Documents/App4/mobile-app-react-native/node_modules/react-native-reanimated/android/react-native-reanimated-63.aar.
     > Check failed
```
React: 16.13.1
React Native: 0.63.4
React Native Reanimated: ^2.0.0
NodeJS: v14.16.1

I test a lot of ways to resolve it. For example,I install the library manually, clean cache a lot of times, changing to a new version 2.0.1 or 2.1.0, unistall and install Java, Android Studio and SDKs but it is always the same error . It only happens with Android, iOS is ok and I see the library into node-modules.

It was installed with react-navigation, but in the project, it is not uses directly.

**Comment by RapestaNatalia** [comment]
Hi guys,

I have a similar problem, but not exactly the same:
```

What went wrong:
Execution failed for task ':app:mergeDevDebugAssets'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
  > Failed to transform react-native-reanimated-63.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}.
   > Execution failed for JetifyTransform: /Users/nataliaraspeta/Documents/TECO/Proyectos/Migración 2/App4/mobile-app-react-native/node_modules/react-native-reanimated/android/react-native-reanimated-63.aar.
     > Check failed


```

React: 16.13.1
React Native: 0.63.4
React Native Reanimated: ^2.0.0
NodeJS: v14.16.1

I have tested a lot of ways to resolve it. For example,I installedthe library manually, I cleaned cache a lot of times, I changed to a new version of react-native-reanimated 2.0.1 or 2.1.0 , unistalled and installed Java, Android Studio and SDKs but it is always the same error . It only happens with Android, iOS is ok and I see the library into node-modules.

It was installed with react-navigation, but in the project, it is not uses directly.

Any suggestions?

Thanks

**Comment by RapestaNatalia** [comment]
Hi guys,

I have a similar problem, but not exactly the same:
```

What went wrong:
Execution failed for task ':app:mergeDevDebugAssets'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
  > Failed to transform react-native-reanimated-63.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}.
   > Execution failed for JetifyTransform: /Users/nataliaraspeta/Documents/App4/mobile-app-react-native/node_modules/react-native-reanimated/android/react-native-reanimated-63.aar.
     > Check failed


```

React: 16.13.1
React Native: 0.63.4
React Native Reanimated: ^2.0.0
NodeJS: v14.16.1

I have tested a lot of ways to resolve it. For example,I installedthe library manually, I cleaned cache a lot of times, I changed to a new version of react-native-reanimated 2.0.1 or 2.1.0 , unistalled and installed Java, Android Studio and SDKs but it is always the same error . It only happens with Android, iOS is ok and I see the library into node-modules.

It was installed with react-navigation, but in the project, it is not uses directly.

Any suggestions?

Thanks

**Comment by RapestaNatalia** [comment]
Hi guys,

I have a similar problem, but not exactly the same:
```

What went wrong:
Execution failed for task ':app:mergeDevDebugAssets'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
  > Failed to transform react-native-reanimated-63.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}.
   > Execution failed for JetifyTransform: /Users/nataliarapesta/Documents/App4/mobile-app-react-native/node_modules/react-native-reanimated/android/react-native-reanimated-63.aar.
     > Check failed


```

React: 16.13.1
React Native: 0.63.4
React Native Reanimated: ^2.0.0
NodeJS: v14.16.1

I have tested a lot of ways to resolve it. For example,I installed the library manually, I cleaned cache a lot of times, I changed to a new version of react-native-reanimated 2.0.1 or 2.1.0 , unistalled and installed Java, Android Studio and SDKs but it is always the same error . It only happens with Android, iOS is ok and I see the library into node-modules.

It was installed with react-navigation, but in the project, it is not uses directly.

Any suggestions?

Thanks

**Comment by peyman-hakemi** [comment]
@RapestaNatalia i have the same issue
do you find a solution?

**Comment by RapestaNatalia** [comment]
@peyman-hakemi with this set up?

React: 16.13.1
React Native: 0.63.4
React Native Reanimated: ^2.0.0
NodeJS: v14.16.1

This post is for React Native 0.64 but I have this issue with 0.63. Have you already tried my suggestions?  I want to know if it is really necessary  to have it installed with react-navigation, because the project works if it is not there.

**Comment by peyman-hakemi** [comment]
React: 16.9.0
React Native: 0.61.5
React Native Reanimated: ^2.0.0 // i tried v1 also
NodeJS: v14.16.0

yes i did the suggestions but no luck

**Comment by RapestaNatalia** [comment]
@peyman-hakemi I've created  [ a bug with react native 0.63](https://github.com/software-mansion/react-native-reanimated/issues/1928#issuecomment-817707536).

**Comment by henricks** [comment]
@RapestaNatalia got stuck at the same point. Have you found any solution yet.

**Comment by pervinpashazade** [comment]
same problem ;(

**Comment by NibyP** [comment]
I also go the same issue.
![Screenshot 2021-09-02 202728](https://user-images.githubusercontent.com/31720147/131867286-d8321e69-5dc0-4bd3-a2a1-21d1a168648b.png)
![Screenshot 2021-09-02 202646](https://user-images.githubusercontent.com/31720147/131867327-841fb172-fa31-42e5-a7a4-fcd61cfbcff1.png)
Any help will be appreciated.

**Comment by nimblepe** [comment]
in my case I installed react-native-reanimated@2.3.0-alpha.3 and it works

**Comment by nimblepe** [comment]
in my case I have installed react-native-reanimated@2.3.0-alpha.2 and it works... I have tried with alpha3 but it returns an error in my project

**Comment by pratius** [comment]
> in my case I have installed react-native-reanimated@2.3.0-alpha.2 and it works... I have tried with alpha3 but it returns an error in my project

Not working for me

**Comment by pratius** [comment]
Please let me know anyone got a fix.

I'm facing the below issues

 What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.

**Comment by DianRH** [comment]
I had the same bug with react native 0.66 I updated react-native-reanimated with the last versión at this moment 2.3.0-beta.2 and works fine :D

**Comment by joncardasis** [comment]
@pratius I had the same issue with RN 0.64.2. I explicitly installed 2.2.0 which worked.  `"react-native-reanimated": "2.2.0"`

> Please let me know anyone got a fix.
> 
> I'm facing the below issues
> 
> What went wrong: A problem occurred evaluating project ':react-native-reanimated'.
> 
> > Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.

**Comment by samshahbazi** [comment]
@naolworku I can't get what you mean exactly...where should we paste the files?
