### ISSUE TITLE
Reanimated's dependencies vulnerabilities

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [software-mansion/react-native-reanimated#1689]
## Description
Node Fetch did not honor the size option after following a redirect, which means that when a content size was over the limit, a FetchError would never get thrown and the process would end without failure.

For most people, this fix will have a little or no impact. However, if you are relying on node-fetch to gate files above a size, the impact could be significant, for example: If you don't double-check the size of the data after fetch() has completed, your JS thread could get tied up doing work on a large file (DoS) and/or cost you money in computing.
Remediation
Upgrade to version 2.6.1 or 3.0.0-beta.9
Resources
https://github.com/node-fetch/node-fetch/security/advisories/GHSA-w7rc-rwvf-8q5r
##screenshot 
<img width="574" alt="Screen Shot 2021-02-04 at 12 54 58 PM" src="https://user-images.githubusercontent.com/65596246/106883098-31ddd700-66e8-11eb-8bc6-a58980ae9a57.png">

all the details are under : https://www.npmjs.com/advisories/1556
## Steps To Reproduce
run npm command 
### Expected behavior
 shouldn't see any severity vulnerabilities which is related to react-native-reanimated 
### Actual behavior
one  severity vulnerabilities appeared 
### package versions
 "react-native-reanimated": "^1.13.2"

**Comment by jakub-gonet** [comment]
Could please describe clearer how this applies to Reanimated?
Also, please stick to the issue template.

Closing until more information is given.

**Comment by ghadeeraqraa1992** [comment]
> ## Issue validator
> The issue is invalid!
> 
> * Section required but not found: description(for label 🐞 bug)
> * Section required but not found: steps to reproduce(for label 🐞 bug)
> * Section required but not found: expected behavior(for label 🐞 bug)
> * Section required but not found: actual behavior(for label 🐞 bug)
> * Section required but not found: package versions(for label 🐞 bug)

the above sections are not available since it is vulnerabilities require your attention to resolve

**Comment by ghadeeraqraa1992** [comment]
> Could please describe clearer how this applies to Reanimated?
> Also, please stick to the issue template.
> 
> Closing until more information is given.

more information added
