### ISSUE TITLE
Canceling animated scroll / conflict between user and programmatic scroll

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#1699]
## Description

If a `scrollTo` with animation is in progress and the user starts to scroll via a touch gesture, there's a conflict and the scroll starts flickering wildly.

### Screenshots

https://user-images.githubusercontent.com/697707/107122502-ba9f7300-68a0-11eb-8565-174995dfebe6.mov

## Steps To Reproduce

In this example above, `scrollTo()` is called to "snap" to a new position when the user releases the touch. 

I have started another scroll gesture by finger right as it was programatically scrolling:

### Expected behavior

Would it be possible to either:
* cancel the animated scroll automatically when the user starts his own scroll (maybe by adding an optional property to `onScroll(..., cancelOnTouch?: boolean)`
* provide a method to cancel the scroll via an event, like `onBeginDrag` (`cancelScroll(ref)`)

### Actual behavior

Conflict between programmatic scroll and user scroll

## Snack or minimal code example

N/A but not hard to reproduce

## Package versions

- React Native Reanimated: 2.0.0-rc.0

**Comment by andreialecu** [comment]
Possibly helpful for the native side of things:

https://stackoverflow.com/questions/3410777/how-can-i-programmatically-force-stop-scrolling-in-a-uiscrollview

https://stackoverflow.com/questions/38695468/stop-scrollview-scrolling-on-user-touch

**Comment by andreialecu** [comment]
After further experimentation this may actually not be an issue. The bug was caused by something else.

**Comment by andreialecu** [comment]
Reopening, actually this **is** a problem. But I found a workaround:

In `onBeginDrag` you can just do a non-animated scroll in place to exactly the same position. This requires keeping track of where the scroll is however.

```ts
      onBeginDrag: () => {
        // stop animated scrolls
        scrollTo(ref, 0, scrollYCurrent.value, false)
```

**Comment by andreialecu** [comment]
@piaskowyk this is not `android` btw.

I had to remove the workaround mentioned above. We noticed a very bizarre issue with calling `scrollTo` in `onBeginDrag` on `iOS`

Basically any `Touchable*` from `react-native` would stop working after scrolling the scrollview down past the first screen or so. 

But the ones in `react-native-gesture-handler` would continue working.

Reported in:
https://github.com/PedroBern/react-native-collapsible-tab-view/issues/123

**Comment by Ubax** [comment]
@andreialecu Could check if the issue still happens on the latest version?
If yes then could you explain what you would like us to do?

**Comment by andreialecu** [comment]
Hey @Ubax can you clarify which version that would be? 

The 2.3.x line is completely unstable for us resulting in crashes on startup due to: https://github.com/software-mansion/react-native-reanimated/issues/2722#issuecomment-1004095531 

And there's also a bug with scroll events, with `onMomentumEnd` no longer being called. Ref: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/221 and https://github.com/software-mansion/react-native-reanimated/issues/2735

**Comment by Ubax** [comment]
@andreialecu Sorry for that, but I think I misunderstood your previous comment. Do you mean that #1701 is the same issue or that it causes the issue?

**Comment by andreialecu** [comment]
Ah, no, sorry, #1701 was a different issue. My comment relating to it can be disregarded.

The initial issue I mentioned here might still probably happen in recent versions, I'm not entirely sure because I'm stuck on 2.2.x.

**Comment by Ubax** [comment]
@andreialecu Just to make sure what is exactly the issue here. Is it using `scrollTo` in `onBeginDrag` or is it the feature request for canceling the scroll?

**Comment by andreialecu** [comment]
The issue was that once an animated scroll is in progress, if the user does their own scrolling during that time, the two will conflict and the screen will jump around.

This is an old issue so I'm not sure of all the specifics, but I was able to initially make some progress in trying to cancel the ongoing animated scroll using `scrollTo(ref, 0, scrollYCurrent.value + 0.1, false)` but this resulted in various other glitches due to the misalignment by `0.1`.

I think if there was a direct way to cancel the scrolling programatically, this would be solved.

**Comment by Ubax** [comment]
@andreialecu Could you open a thread for discussions for it (canceling scrolling programmatically) and propose some solution there?

Without repro it would be hard to fix this particular case and the place for new features is in discussion. I will close this issue now, but if you think that we should still work on it please let us know.

**Comment by khagesh1998** [comment]
Facing similar problem. Need to stop scrolling till I collapse header. @andreialecu can you please share if you find the solution?

**Comment by Jlexyc** [comment]
The same issue here. So basically I have a case, when content of a scroll view can be changed and I need to scroll content to top. So basically `scrollTo` function works, but even after it ScrollView keeps decelerating from the new position.
Didn't find a way to stop scroll on content update.

**Comment by quicksilverr** [comment]
Hey @Ubax , Please can you share the discussion link?

**Comment by quicksilverr** [comment]
Hey @andreialecu can't we use onTouchMove, see, if there's a change from the intital pageX value, in negative or positive direction, if that's the case, Then only update useSharedValue or do a scrollTo?
