### ISSUE TITLE
Can't cast NoopNode to abi39_0_0.......... reanimated.nodes.ClockNode

### ISSUE THREAD

**Issue by MuttakinHasib** [software-mansion/react-native-reanimated#1700]
#### Screenshots

![Screenshot_2021-02-07-16-20-30-774_host exp exponent](https://user-images.githubusercontent.com/44552983/107143765-0d406400-6961-11eb-8656-f47a5fc2eacf.jpg)

**Comment by ghulamhussainjoyo** [comment]
have you found any solution to this error?
