### ISSUE TITLE
Android: `scrollTo` with FlatList breaks as soon as refresh control is added

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#1703]
## Description

Using `scrollTo` with a normal FlatList seems to work great, just until it gets a RefreshControl.

This only seems to occur on Android. On iOS everything works fine.

## Steps To Reproduce

```tsx

const AnimatedFlatList = Animated.createAnimatedComponent(FlatList)

<AnimatedFlatList
      ref={ref}
      ...
      onRefresh={() => {}} // comment out and it scrolls
      refreshing={true}    //
    />

scrollTo(ref, ...) // on android it only scrolls when refresh control is missing

```

### Expected behavior

Programmatic scrolling should work.

### Actual behavior

Nothing happens.

## Snack or minimal code example

See above.

## Package versions

- React Native: via Expo 40.0.1
- React Native Reanimated: 2.0.0-rc.0

Only occurs on Android

**Comment by PedroBern** [comment]
Same issue here on `rc.0`

**Comment by andreialecu** [comment]
Note that ScrollView works fine. Only FlatList is affected.
