### ISSUE TITLE
Task :react-native-reanimated:androidJavadoc - gives me 100 warnings

### ISSUE THREAD

**Issue by luizwhite** [software-mansion/react-native-reanimated#1712]
## Description

Clean build on my project gives me 100 warnings on **Task :react-native-reanimated:androidJavadoc**

When i say clean build, i mean [this](https://stackoverflow.com/a/49603409/14469037)

## Steps to reproduce

[this](https://stackoverflow.com/a/49603409/14469037) then

`yarn`;
`yarn android --deviceId emulator-5554`

### Actual behavior

https://gist.github.com/luizwhite/f431ec367d6187178b4d745e4bb01ac1

### Expected behavior

no warnings about not existing packages

## Snack or minimal code example

`yarn android --deviceId emulator-5554`

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: ^1.13.1

## Note

According to this [post](https://stackoverflow.com/posts/64786637/revisions), and with this [issue comment](https://github.com/software-mansion/react-native-reanimated/issues/215#issuecomment-765538455) (last edit), removing --deviceId flag should fix the problem, but i need the deviceId flag, and this is not a solution

## Behavior shortened
```bash
> Task :react-native-reanimated:androidJavadoc
.../node_modules/react-native-reanimated/android/src/main/java/com/facebook/react/uimanager/UIManagerReanimatedHelper.java:11: error: cannot find symbol
  public static boolean isOperationQueueEmpty(UIImplementation uiImplementation) {
                                              ^
  symbol:   class UIImplementation
  location: class UIManagerReanimatedHelper
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:5: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.Arguments;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:6: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.Callback;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:7: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.GuardedRunnable;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:8: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.JSApplicationIllegalArgumentException;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:9: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactContext;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:10: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReadableMap;

...

.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nodes/AlwaysNode.java:8: error: cannot find symbol
  public AlwaysNode(int nodeID, ReadableMap config, NodesManager nodesManager) {
                                ^
  symbol:   class ReadableMap
  location: class AlwaysNode
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java:3: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.JavaOnlyArray;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java:4: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.JavaOnlyMap;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java:5: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReadableArray;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java:6: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReadableMap;
                                ^
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java:7: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReadableType;
                                ^
100 warnings

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 43s
461 actionable tasks: 461 executed
info Connecting to the development server...
info Installing the app on the device "emulator-5554"...
Performing Streamed Install
Success
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.testapp/.MainActivity }
✨  Done in 303.39s.
```

**Comment by luizwhite** [comment]
maybe this is not classified as a bug, so feel free to remove the tag

**Comment by smartHOTELeu** [comment]
I got same problem. Error comes when I run ./gradlew build

**Comment by luizwhite** [comment]
@jakub-gonet  Apparently when using a newer gradle with react-native-reanimated v2 those warning don't show anymore

**Comment by thanh90** [comment]
in my case, i cannot upgrade to reanimated v2 due to react-navigation-tabs using v1.9.0. i had to downgrade Android Studio to 4.1

**Comment by varbex** [comment]
I´m having the same issue using gradle 6, removing --deviceId as OP indicated indeed solved the problem.
Anyone could give me a short insight on why this happens?
Upgrading the lib or gradle, what would be the best workaround solution?

**Comment by zewt** [comment]
I was banging my head against this too.  It looks like React has completely a different codepath if you specify --deviceId.  It seems to build a lot more than needed, so the build takes ages.  This just seems to be getting triggered as a side-effect of that.  Fixing these warnings/errors would be fine, but the React issue might be making your builds take a lot longer like it was mine.

I haven't looked into it further, just an FYI for other people hitting this.

**Comment by HGalloway** [comment]
Did anyone find a solution to this error?

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request.

**Comment by AkshayBhimani** [comment]
Issue is regarding `--deviceId` parameter for sure. But, did any one find solution?

**Comment by erickalvesduobox** [comment]
My solution was to build with Android Studio using the debug variant.
Then later change the bundle location in the device to my local network.

**Comment by SanjanaTailor** [comment]
Execution failed for task ':react-native-reanimated:androidJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/node_modules/react-native-reanimated/android/build/tmp/androidJavadoc/javadoc.options'

**Comment by 98rahul** [comment]
### react-native-reanimated:androidJavadoc FAILED  

listed version used --
 "react-native-reanimated": "~1.13.0",
   "react": "18.2.0",
  "react-native": "0.71.1",

any solution ??
