### ISSUE TITLE
Typescript: style prop added by createAnimatedComponent() is flagged

### ISSUE THREAD

**Issue by helixbass** [software-mansion/react-native-reanimated#1717]
## Description

Typescript is flagging the `style` prop on eg `<AnimatedCircle>` as nonexistent when in fact it works at runtime (and wasn't flagged by Reanimated v1 types)

## Steps To Reproduce

```
import {Circle} from 'react-native-svg'

const AnimatedCircle = Animated.createAnimatedComponent(Circle)

type AnimatedCircleStyleProp = (typeof AnimatedCircle)['style']
```

The above gets flagged by Typescript as `Property 'style' does not exist on type 'ComponentType<AnimateProps<CircleProps>>'.`

Looking at the types for Reanimated, this is because `AnimateProps` only includes `style` prop if the wrapped component's type includes a `style` prop. And I guess `<Circle>` doesn't actually have a `style` prop. But clearly Reanimated's `createAnimatedComponent()` wrapper adds support for a `style` prop since passing an animated-value `style` prop still works at runtime in Reanimated v2. And I'm not sure what the types were for Reanimated v1 but it did not flag this as a type error

### Expected behavior

No Typescript error, `style` prop on `<AnimatedCircle>` should be typed appropriately (`StyleProp<AnimateStyle<...>>`?)

### Actual behavior

Typescript flags a type error

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-rc.3
- NodeJS: 14.15.3
- Typescript: 3.9.7

**Comment by tomekzaw** [comment]
Still an issue with Reanimated 2.3.1.
