### ISSUE TITLE
yarn workspace worklet location crash

### ISSUE THREAD

**Issue by nikolaigeorgie** [software-mansion/react-native-reanimated#1720]
## Description

I'm trying to take the reanimated-2-playground repo and run the project using yarn workspaces. Once moving the example project to the yarn workspace environment mainly requiring node_modules from the root workspace (such as ../node_modules -> ../../../node_modules) rather than the local project workspace, there seems to be errors in the "worklet location" ... attempting to "synchrounously call function {assign} from a different thread..

It seems like the error is due to an incorrect declaration of the worklet location? not really sure but would love any help. thank you.

### Screenshots
![simulator_screenshot_3FB346F5-6049-402E-ACB2-6CECD5188E13](https://user-images.githubusercontent.com/11046180/107892044-5d767380-6ed7-11eb-9876-2989eb6abdc6.png)

## Steps To Reproduce

You can checkout my example repo under ## Snack or minicode example 

or ..

1. create a yarn workspace (by confirming to the following folder structure)

work/
work/package.json
work/packages/reanimated-2-playground

2. copy package.json from example repo i provided.

3. In work/packages/reanimated-2-playground install `yarn add path` (the npm package) and update metro.config.js to include 
```
projectRoot: require('path').resolve(__dirname, '../../'),
```

4. Update work/packages/reanimated-2-playground/Podfile to appear as such (changing the relative node_modules to the hoisted node_modules by the yarn workspace)
```
require_relative '../../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Reanimated2Playground' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

```

5. Update work/packages/reanimated-2-playground/AppDelegate.m sourceURLForBridge to appear as such

```
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"packages/rabbiyosefmizrachi/index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}
```

7. Run `yarn` from the root directory.

8. Run  `cd packages/reanimted-2-playground/ios && pod install && cd ../ && yarn start

9. Run `yarn ios` from the root directory. 

### Expected behavior

Expected behavior is for the project to appear and function as it does from the fresh install of reanimated 2 playground. https://github.com/software-mansion-labs/reanimated-2-playground.git

I have no issues in reanimated version 1 .. i also have about 45 packages in one of my projects where this issue doesn't exist for any other package. 

### Actual behavior

It seems that the project in yarn workspaces begins to "Try to synchrounously call function {assign} from a different thread"...

Using `runOnJs` shouldn't be required because the code is the EXACT example code from the reaniamted 2 playground.

## Snack or minimal code example

Here is the repo i published (with the steps below)

https://github.com/nikolaigeorgie/reanimated-yarn-workspace.git

To run the repo just

1. yarn
2. yarn ios
3. (ensure the server is running using `yarn start` or `npm run start` in the `work/packages/reanimated-2-playground` directory

## Package versions

- React:
- React Native:
- React Native Reanimated:
- NodeJS:

**Comment by jakub-gonet** [comment]
Related #858.

**Comment by ericlifs** [comment]
Same issue happening to me and I do have the same babel config and version as mentioned at #858. Currently there is no way of making it work.

**Comment by nikolaigeorgie** [comment]
@ericlifs  i created a demo of a working version with reanimated + yarn workspaces. https://github.com/nikolaigeorgie/yarn-workspaces-reanimated.git check it out.. it's based off of https://github.com/brunolemos/react-native-web-monorepo

**Comment by fortezhuo** [comment]
@nikolaigeorgie, sorry to bother.. I have tried to clone your repo and run locally. I have failed to build while running using XCode, but no error occurs while run using react-native run-ios. Do you have some clue for solving this problem ?

https://github.com/software-mansion/react-native-reanimated/issues/858#issuecomment-795093204
