### ISSUE TITLE
ANR:  Input dispatching timed out 

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#1727]
## Description

App crashes on Android in production with this error

### Screenshots

```
ANR:  Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 5564.1ms.)
        at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java:-2)
        at com.swmansion.reanimated.Scheduler.access$000(Scheduler.java:7)
        at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:17)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7711)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

Full stack trace [here](https://gist.github.com/Andarius/3fb3b2e1418fa2f27503592669c23d69)

## Steps To Reproduce

Let the app run for a few minutes

### Expected behavior

No crash

### Actual behavior

Crash

## Snack or minimal code example

Unknown, Sorry not to be helpful here...

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: ^2.0.0-rc.3

**Comment by Szymon20000** [comment]
Looks like our method `triggerUI` is called from two different threads at the same time. We only call it through `RNcontext.runOnUiQueueThread()` method.
```Java
mContext.runOnUiQueueThread(()->{triggerUI});
```
It would be really helpful if you could answer our questions:

Do you have multiple instances of react-native in your project? 
Do you use headless JS?
Do you use any library for background tasks?

**Comment by Andarius** [comment]
Hey @Szymon20000 

**Do you have multiple instances of react-native in your project?**
No
**Do you use headless JS?**
No
**Do you use any library for background tasks?**
Maybe bugsnag (the reporting lib) otherwise no

**Comment by Szymon20000** [comment]
Yeah, `package.json` can be helpful too.

**Comment by Andarius** [comment]
Here are the deps
```
"dependencies": {
    "@bugsnag/react-native": "^7.6.0",
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/cameraroll": "^4.0.2",
    "@react-native-community/clipboard": "^1.5.0",
    "@react-native-community/datetimepicker": "^3.0.1",
    "@react-native-community/google-signin": "^4.0.3",
    "@react-native-community/viewpager": "^4.1.6",
    "i18next": "^19.8.5",
    "lodash.clonedeep": "^4.5.0",
    "react": "16.13.1",
    "react-i18next": "^11.8.5",
    "react-native": "0.63.0",
    "react-native-calendars": "^1.831.0",
    "react-native-config": "^1.4.2",
    "react-native-fast-image": "^8.3.2",
    "react-native-fbsdk": "^3.0.0",
    "react-native-firebase-test-lab": "^0.0.2",
    "react-native-gallery-toolkit": "^1.0.0-alpha.1.1",
    "react-native-gesture-handler": "1.9.0",
    "react-native-localize": "^1.3.0",
    "react-native-navigation": "^7.9.0",
    "react-native-reanimated": "^2.0.0-rc.3",
    "react-native-svg": "^v12.1.0",
    "react-native-video": "^5.1.0-alpha8",
    "react-native-webview": "^7.4.3",
    "react-redux": "^7.2.1",
    "redux-saga": "^1.1.1",
    "reselect": "^4.0.0",
    "rn-fetch-blob": "^0.12.0"
  },
  ```

**Comment by jakub-gonet** [comment]
Do you have any custom integration on the native side? Like native libraries, components, or just custom logic that creates Fragments or Activities?

**Comment by Andarius** [comment]
No I don't

**Comment by mrousavy** [comment]
Maybe this just happens when the user exits the app and the UI queue is no longer accepting dispatches?

**Comment by s-aleinik** [comment]
Hello! I'm also facing the same issue, but I use 'react-native-background-fetch' and `headless` in it config:

```
BackgroundFetch.configure(
      {
        startOnBoot: true,
        enableHeadless: true,
        stopOnTerminate: false,
        requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
        minimumFetchInterval: BACKGROUND_FETCH_INTERVAL_IN_MINUTES
      },
      updateToken,
      onTimeout
    );

    BackgroundFetch.registerHeadlessTask(updateTokenHeadlessAndroid);
```

Could it lead to this ANR?

**Comment by Andarius** [comment]
Seems to be fixed in latest version, closing

**Comment by Montyc666** [comment]
> ## Description
> 
> App crashes on Android in production with this error
> 
> ### Screenshots
> 
> ```
> ANR:  Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 5564.1ms.)
>         at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java:-2)
>         at com.swmansion.reanimated.Scheduler.access$000(Scheduler.java:7)
>         at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:17)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7711)
>         at java.lang.reflect.Method.invoke(Method.java:-2)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> ```
> 
> Full stack trace [here](https://gist.github.com/Andarius/3fb3b2e1418fa2f27503592669c23d69)
> 
> 
> ## Steps To Reproduce
> 
> Let the app run for a few minutes
> 
> ### Expected behavior
> 
> No crash
> 
> ### Actual behavior
> 
> Crash
> 
> ## Snack or minimal code example
> 
> Unknown, Sorry not to be helpful here...
> 
> ## Package versions
> 
> - React: 16.13.1
> - React Native: 0.63.2
> - React Native Reanimated: ^2.0.0-rc.3
> 
> 

Thanks

**Comment by Montyc666** [comment]
> ## Description
> App crashes on Android in production with this error
> 
> ### Screenshots
> ```
> ANR:  Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 5564.1ms.)
>         at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java:-2)
>         at com.swmansion.reanimated.Scheduler.access$000(Scheduler.java:7)
>         at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:17)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7711)
>         at java.lang.reflect.Method.invoke(Method.java:-2)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> ```
> 
> Full stack trace [here](https://gist.github.com/Andarius/3fb3b2e1418fa2f27503592669c23d69)
> 
> ## Steps To Reproduce
> Let the app run for a few minutes
> 
> ### Expected behavior
> No crash
> 
> ### Actual behavior
> Crash
> 
> ## Snack or minimal code example
> Unknown, Sorry not to be helpful here...
> 
> ## Package versions
> * React: 16.13.1
> * React Native: 0.63.2
> * React Native Reanimated: ^2.0.0-rc.3

4:12:40 PM

78%

H

Additional info

ANR in com.android.chrome (com.android.chrome/org.chromium.c

hrome.browser. ChromeTabbedActivity),

time-89737832

Reason: Input dispatching timed out (128ee8

com.android.chrome/org.chromium.chrome.browse r.Chrome TabbedActivity (server) is not responding. Waited 5001ms for KeyEvent)

Load: 25.23/30.06/30.34

Output from /proc/pressure/memory some avg10-8.66 avg60-8.48 avg300=10.17

total=1296948464 full avg10=4.13 avg60-3.69 avg300=2.82 total-558536438

----- End output from /proc/pressure/memory -

Android time [2023-02-25 16:11:17.87] [89758.719] CPU usage from 0ms to 14370ms later (2023-02-25 16:10:56.981 to 2023-02-25 16:11:11.350): 156% 21978/com.android.chrome: 144% user +

12% kernel / faults: 207111 minor 65 major 17% 1243/system_server: 8.5% user + 8.9% kernel/

faults: 17776 minor 459 major 17% 159/kswapd0: 0% user + 17% kernel

13% 30763/

com.android.chrome:sandboxed_process0:org.chro

mium.content.app.Sandboxed ProcessService0:90: 11% user + 1.4% kernel/ faults: 13995 minor 17

major

11% 26604/

com.android.chrome:sandboxed_process0:org.chro mium.content.app.Sandboxed ProcessService0:71: 9.2% user 2.4% kernel/ faults: 71481 minor 42

major

7.1% 1611/com.android.systemui: 4% user + 3.1%

kernel/ faults: 12325 minor 245 major 6.1% 2647/com.google.android.inputmethod.latin: 3.5% user + 2.6% kernel/ faults: 13970 minor 316

major 4% 738/surfaceflinger: 2.2% user + 1.7% kernel/ faults: 1741 minor 7 major

BACK

**Comment by zain-khalid** [comment]
I am using RN 0.63.4 and facing the same issue in production applications. Can anyone confirm that this issue is fixed in RN latest version?
