### ISSUE TITLE
useDerivedValue returns TypeError: No default value

### ISSUE THREAD

**Issue by SaadAhmadSaddiqui** [software-mansion/react-native-reanimated#1729]
## Description

Just moved from v1 to v2 and was trying to use the `useDerivedValue()` hook, but if I try to use it anywhere or even console.log it, it gives me a `TypeError: No default value`. 

### Full call stack
```
TypeError: No default value

This error is located at:
    in Dot (at Test.js:27)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at Test.js:25)
    in RCTView (at View.js:34)
    in View (at Test.js:24)
    in Test (at App.js:31)
    in RCTView (at View.js:34)
    in View (at App.js:30)
    in StateProvider (at App.js:29)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
- node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
- node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
- node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
- node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
- node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
- node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
- node_modules\react-native\Libraries\Core\ReactFiberErrorDialog.js:43:2 in showErrorDialog
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15257:32 in logCapturedError
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15361:20 in logError
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:16597:12 in update.callback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7106:2 in callCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7127:20 in commitUpdateQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15801:25 in commitLifeCycles
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18744:22 in commitLayoutEffects
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:265:4 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:476:2 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18483:29 in commitRootImpl
* [native code]:null in commitRootImpl
- node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18317:17 in commitRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17697:12 in performSyncWorkOnRoot
* [native code]:null in performSyncWorkOnRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
- node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17125:30 in scheduleUpdateOnFiber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11003:16 in dispatchAction
* [native code]:null in dispatchAction
- node_modules\expo-font\build\FontHooks.js:18:33 in loadAsync.then$argument_0
- node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
- node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```
### Screenshots

The file where I'm using it in. A basic Test example:
![image](https://user-images.githubusercontent.com/27802188/108277330-aefe5700-7192-11eb-8fa9-0290accbeecc.png)

Where I'm using the `currentIndex`:
![image](https://user-images.githubusercontent.com/27802188/108277574-0bfa0d00-7193-11eb-9f94-39c7ebe2c27b.png)

package.json deps:
![image](https://user-images.githubusercontent.com/27802188/108278076-e6b9ce80-7193-11eb-8fba-1784926d742f.png)

babel.config.js:
![image](https://user-images.githubusercontent.com/27802188/108274652-9db34b80-718e-11eb-917d-c964a63f6ddb.png)

app.json:
![image](https://user-images.githubusercontent.com/27802188/108274754-c3d8eb80-718e-11eb-9aeb-586306777413.png)

errors as shown on the android phone: 

![image](https://user-images.githubusercontent.com/27802188/108280083-10c0c000-7197-11eb-8e49-bde46b5a3549.png)

-----

![image](https://user-images.githubusercontent.com/27802188/108280127-2afa9e00-7197-11eb-8340-76091fe30d63.png)

## Steps To Reproduce

1. create a react native app with expo
2. follow this guide to enable react native reanimated v2 : https://docs.expo.io/versions/latest/sdk/reanimated/
3. try to use `useDerivedValue()` on any file

### Expected behavior

I expect to use `useDerivedValue()` to get the currentIndex page while swapping on a ScrollView

### Actual behavior

App crashes and sends `TypeError: No default value`

## Snack or minimal code example

A snack example. But of course it doesn't run reanimated 2.0.0-rc.0 . But it's something to look at and replicate:
https://snack.expo.io/@gr8/test-for-usederivedvalue

## Package versions

- React: 16.13.1
- React Native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 12.20.0

**Comment by jamesehly** [comment]
Like a shared value, derived values return on object with a value attribute (as noted here: https://docs.swmansion.com/react-native-reanimated/docs/2.1.0/api/useDerivedValue/#returns).  So in your case you would need to use currentIndex.value.  The documentation example (https://docs.swmansion.com/react-native-reanimated/docs/2.1.0/api/useDerivedValue/#example) is confusing on this point because it looks like you can use the derived value like any other variable, but it isn't showing that the SomeComponent has to use width.value at some point.

**Comment by piaskowyk** [comment]
As a first argument to `interpolate` you should pass `currentIndex.value` instead of `currentIndex`. Also your `index` is `undefined` :/
