### ISSUE TITLE
Unable to open release application with Reanimated

### ISSUE THREAD

**Issue by bralandealmeida** [software-mansion/react-native-reanimated#1734]
## Description

It is not possible to open the application using Reanimated v2. A fatal exception is generated and the application closes immediately.

This error only occurs in release applications and does not occur during development. I don't know if the error is in my setup or if it is due to incompatibility with other libs.

I managed to solve my problem by adding the following rule to the proguard, however, I don't know what the real impact of this is on the application.

`-keep class com.facebook.react.turbomodule.** { *; }`

## Steps To Reproduce

1.  Open the release application

### Expected behavior

1.  Open the release application

### Actual behavior

1.  Closes immediately

## Snack or minimal code example

Following is the error log generated:

`
FATAL EXCEPTION: create_react_context
Process: [app name], PID: 9487
java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/turbomodule/core/CallInvokerHolderImpl;.<init>(Lcom/facebook/jni/HybridData;)V"
at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder(Native Method)
at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder()
at com.swmansion.reanimated.NativeProxy.<init>()
at com.swmansion.reanimated.c.v()
at com.swmansion.reanimated.d.getJSIModules()
at com.facebook.react.q.p()
at com.facebook.react.q.c()
at com.facebook.react.q$e.run()
at java.lang.Thread.run(Thread.java:761)
`

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: ^2.0.0-rc.3
- NodeJS: v15.2.0

**Comment by jakub-gonet** [comment]
This line is needed since proguard strips not used classes and we bundle reanimated in other package than react native so it can't detect it.

We have step for the proguard in installation guide in our docs:
https://docs.swmansion.com/react-native-reanimated//react-native-reanimated/docs/installation

I'm closing it, since this behavior is expected.
