### ISSUE TITLE
Cannot find module 'react-native-reanimated/plugin' from project folder

### ISSUE THREAD

**Issue by Yandamuri** [software-mansion/react-native-reanimated#1737]
## Description
I am using this package as a dependency of [react-native-draggable-flatlist](https://github.com/computerjazz/react-native-draggable-flatlist). When I did `npm install react-native-reanimated` `v1.13.2` got installed automatically. And when I ran the app got following error.

> Cannot find module 'react-native-reanimated/plugin' from project folder

below is babel.config.js

          module.exports = {
            presets: ['module:metro-react-native-babel-preset'],
            plugins: [ 'react-native-reanimated/plugin']
          };

### Screenshots
![Capture](https://user-images.githubusercontent.com/31983789/108498710-45d22d00-72d3-11eb-8f89-b5f676f425d5.PNG)

## Steps To Reproduce

Just do  `npm install react-native-reanimated`. Then Run the app.

### Expected behavior
reanimated shouldn't give any errors
### Actual behavior
Showing above mentioned error when app is ran

## Snack or minimal code example
Con't provide any snack since error belongs to package installation

## Package versions
- React: **"16.13.1"**
- React Native: **"0.63.2"**
- React Native Reanimated: "1.13.2"

**Comment by jakub-gonet** [comment]
You use Reanimated v1, you don't need the plugin to get it working. Try removing it from the babel plugins and check if it resolves this issue for you.

**Comment by Yandamuri** [comment]
@jakub-gonet I have removed plugin as you said and ran the app. Now I am getting following error,

`Error: Unable to resolve module `./reanimated2` from `node_modules\react-native-reanimated\src\Animated.js`:`

How Can I proceed now?

**Comment by jakub-gonet** [comment]
Please add more context (screenshots, stack traces), I csnnot help you with the message alone. Please note you have Animated v1 installed and you (or other libraries) csnnot use reanimated v2 features.

**Comment by Yandamuri** [comment]
@jakub-gonet I have deleted node_modules and installed. cleaned cache. Then Installed `reanimated v1.13.2`. Surprisingly it's working now.

Can you please confirm that Hermes engine to be enabled or not `reanimated V1`?

**Comment by jakub-gonet** [comment]
In v1, Reanimated will work with with any js engine.

**Comment by SarvaDev-123** [comment]
@Yandamuri  How to installed reanimated v1.13.2. it?

**Comment by Yandamuri** [comment]
@SarvaDev-123 npm install react-native-reanimated@1.13.2

**Comment by tingting-1201** [comment]
> @SarvaDev-123 npm install react-native-reanimated@1.13.2

Has it been resolved? I have the same problem。

**Comment by Danksta** [comment]
i've got the same issue. Any solution for this?

**Comment by Yandamuri** [comment]
> @jakub-gonet I have deleted node_modules and installed. cleaned cache. Then Installed `reanimated v1.13.2`. Surprisingly it's working now.
> 
> Can you please confirm that Hermes engine to be enabled or not `reanimated V1`?

@Danksta Did you followed this solution?

**Comment by vishal-gtl** [comment]
> You use Reanimated v1, you don't need the plugin to get it working. Try removing it from the babel plugins and check if it resolves this issue for you.

This is work for me.

I have removed the latest version plugin and add "react-native-reanimated": "1.13.3".

and remove plugin entry from babel.config.js

**Comment by jotaxzx** [comment]
> > Utiliza Reanimated v1, no necesita el complemento para que funcione. Intente eliminarlo de los complementos de babel y verifique si resuelve este problema por usted.
> 
> Esto es trabajo para mi.
> 
> Eliminé el complemento de la última versión y agregué "react-native-reanimated": "1.13.3".
> 
> y elimine la entrada del complemento de babel.config.js

for me it also worked with version 1.13.3 and I had to install rn-nodeify

**Comment by mohammedfayezneoito** [comment]
is the version you installed is alpha?? i got same error and i solve is 
```
npm i react-native-reanimated
```

**Comment by yogendrajs** [comment]
```
TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')
```
Got this error with drawer-navigation even after having
```
"react-native-reanimated": "1.13.3"
```

The above solutions are not working for me. Any workaround?

**Comment by Aditya1942** [comment]
this worked for me [click here](https://stackoverflow.com/a/69317483/11654146)

**Comment by jackie20** [comment]
npm install react-native-reanimated@1.13.3 --force 
worked for me

**Comment by mwaqarshahid** [comment]
> You use Reanimated v1, you don't need the plugin to get it working. Try removing it from the babel plugins and check if it resolves this issue for you.

This worked for me.

My dependencies are as follows:

"dependencies": {
    "@react-native-clipboard/clipboard": "^1.11.2",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/push-notification-ios": "^1.11.0",
    "@react-native-firebase/app": "^18.3.2",
    "@react-native-firebase/messaging": "^18.3.2",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@reduxjs/toolkit": "^1.9.5",
    "@rneui/base": "^4.0.0-rc.8",
    "@rneui/themed": "^4.0.0-rc.8",
    "@sentry/react-native": "^5.9.1",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "@types/react-native-i18n": "^2.0.0",
    "@types/react-native-push-notification": "^8.1.1",
    "axios": "^1.5.0",
    "patch-package": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-elements": "^3.4.3",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-i18n": "^2.0.15",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.2.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^1.13.2",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-toast-message": "^2.1.6",
    "react-native-vector-icons": "^10.0.0",
    "react-redux": "^8.1.2",
    "redux-thunk": "^2.4.2"
  }

**Comment by kundannetsetDemo** [comment]
Error: Unable to resolve module ./pluginUtils from /Users/node_modules/react-native-reanimated/src/reanimated2/index.ts:

**Comment by Agiliis** [comment]
> @jakub-gonet I have deleted node_modules and installed. cleaned cache. Then Installed `reanimated v1.13.2`. Surprisingly it's working now.

wow. somehow that worked too

**Comment by coderealm** [comment]
> npm install react-native-reanimated@1.13.3 --force worked for me

This worked for me like charm
