### ISSUE TITLE
The onScroll function is not called

### ISSUE THREAD

**Issue by zyslife** [software-mansion/react-native-reanimated#1746]
## Description

```
function scrollTo(
      ref: RefObject<ReactNativeScrollView | ScrollView>,
      x: number,
      y: number,
      animated: boolean
    ): void
```
When I use the `scrollTo` function and pass in the argument `animated:false`, the onScroll function doesn't get called in iOS.
I get the results I want on Android.

## Steps To Reproduce

1. Call the scrollTo function to scroll the scrollView
2. Look at the onScroll function being called

### Expected behavior

I want the onScroll function to be called and updated.(ios)

### Actual behavior

The onScroll function doesn't get called in iOS

## Snack or minimal code example

```
import React from 'react';
import { View, TouchableOpacity, Text } from 'react-native';
import Animated, {
    useAnimatedScrollHandler,
    useAnimatedRef,
    scrollTo,
    runOnUI,
} from 'react-native-reanimated';


function ScrollExample() {
    const animatedRef = useAnimatedRef();
    const scrollHandler = useAnimatedScrollHandler({
        onScroll: (e) => {
            console.log('onScroll==>', e);
        },
    });

    const scrollToPosition = () => {
        'worklet'
        runOnUI(scrollTo)(animatedRef, 0, 100, false)
    }

    return (
        <View style={{ flex: 1 }}>
            <TouchableOpacity style={{ height: 50, justifyContent: 'center' }} onPress={() => {
                scrollToPosition()
            }}>
                <Text>ScrollTo ScrollView</Text>
            </TouchableOpacity>
            <Animated.ScrollView
                ref={animatedRef}
                scrollEventThrottle={1}
                onScroll={scrollHandler}>
                {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((item, index) => {
                    return <View style={{ height: 100, backgroundColor: index % 2 === 0 ? 'red' : 'blue' }} />
                })}
            </Animated.ScrollView>
        </View>
    );
}

export default ScrollExample;

```

## Package versions

`"react-native-reanimated": "2.0.0-rc.0"`

- React:16.13.1
- React Native:0.63.4
- React Native Reanimated:2.0.0-rc.0

**Comment by Szymon20000** [comment]
Could you update reanimated to version 2.0.0-rc.3? I think we already fixed a similar problem.

**Comment by zyslife** [comment]
> Could you update reanimated to version 2.0.0-rc.3? I think we already fixed a similar problem.

`ReferenceError: Can't find variable: _setGlobalConsole`
Version 2.0.0-rc.3 will report an error.

**Comment by Szymon20000** [comment]
@zyslife I think that you use Expo. Unfortunately, RC.0 is the latest version available in the Expo client. I'm almost entirely sure we have already fixed it so I will close the issue tentatively. If you have the same problem with the next version of Expo, please let me know.
