### ISSUE TITLE
Value is undefined, expected an Object

### ISSUE THREAD

**Issue by enesozturk** [software-mansion/react-native-reanimated#1758]
## Description

Hi, I am trying to pass list of objects that includes fields as `function` type to a component. But when I try to pass shared value list to a React state to render, it can not call functions. When I try to press Touchable, it gives the error.

*Value is undefined, expected an Object*.

I am not sure if it is because of wrong usage or a bug. Thats why sorry for that if I am wrong place.

### Screenshots

<img width="387" alt="Screen Shot 2021-02-26 at 11 01 12 AM" src="https://user-images.githubusercontent.com/19428358/109273843-c937d500-7823-11eb-9d2b-c0ddfd83fed4.png">

<img width="389" alt="Screen Shot 2021-02-26 at 11 41 41 AM" src="https://user-images.githubusercontent.com/19428358/109276904-a60f2480-7827-11eb-9992-310bcbd8e9a8.png">

## Steps To Reproduce

1. Provide a shared list that has list of objects has function as field
2. Move shared list to a state
3. Try rendering list and using onPress handlers of the objects

### Expected behavior

Render React.ReactNode and call handler functions passed with Shared Value

### Actual behavior

I does not render and gives above error when I use the onPress function

## Snack or minimal code example

Here how I pass functions;
```js
export type MenuItemProps = {
  title: string;
  onPress: () => void;
};

const list = useSharedValue<MenuItemProps[]>([
    {
      text: 'Action 1',
      onPress: () => {
        console.log('Action 1');
      },
    },
    {
      text: 'Action 2',
      onPress: () => {
        console.log('Action 2');
      },
    },
]);

<List items={items} />

```

And List component sets shared value to state to be able to render:

`List.tsx`
```js
const MenuList = ({ items }: { items: Animated.SharedValue<MenuItemProps[]> }) => {
  // I set my list to React state to be able to render
  const [itemList, setItemList] = React.useState<MenuItemProps[]>([]);

  const setter = (items: MenuItemProps[]) => {
    setItemList(items);
  };

  useAnimatedReaction(
    () => items.value,
    items => {
      runOnJS(setter)(items);
    },
    [items]
  );

  return (
    <>
      {itemList.map((item: MenuItemProps) => {
        return (
          <TouchableOpacity onPress={item.onPress}>
            <Text>{item.text}</Text>
          </TouchableOpacity>
        );
      })}
    </>
  );
};
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc-3
- NodeJS: 15.5.1

**Comment by enesozturk** [comment]
Problem is solved for now. Here was the scenario for me;

I tried my example on and Expo project and there was no problem calling onPress handler and rendering icon. So I did this steps for my bare RN project;

- Set iOS target from 10 to 11. (Did this for another reason actually)
- Remove `Podfile.lock` file and `Pods` folder
- Remove `node_modules`
- Install npm packages and run `cd ios && pod install`

When I build and run my project problem was solved. Still not sure what was the problem before and **will try to reproduce** it. For now it is working as expected.

**Comment by gabrielbull** [comment]
Error is still happening after 2.1.0. Please reopen issue.

**Comment by enesozturk** [comment]
It is solved for me after v2.1.0 actually. Did your tried wrap your JS callback with `runOnJS`? And also calling any function in third params without checking `isFinished` looks like anti pattern for me.

**Comment by gabrielbull** [comment]
Yes, as I said, it works when running on the JS thread with runOnJS. But maybe the error should be more obvious because I had a lot of code to dig through to find what caused it. When you run JS thread code in worklets, it usually tells you, but here, it throws this cryptic error.

**Comment by alakdam07** [comment]
@enesozturk I am getting the same issue. I removed the `node_moudles`, clean cache and reinstall  `node_moudles` but still I am getting issue.

```
import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  Dimensions,
  useWindowDimensions,
  SafeAreaView,
} from 'react-native';

import MapView from 'react-native-maps';
import Animated, {
  Extrapolate,
  interpolate,
  useAnimatedGestureHandler,
  useAnimatedStyle,
  withTiming,
  useSharedValue,
} from 'react-native-reanimated';

import {
  PanGestureHandler,
  PanGestureHandlerGestureEvent,
} from 'react-native-gesture-handler';

type AnimatedGHContext = {
  startX: number;
  startY: number;
};

const { width } = Dimensions.get('screen');

const initialRegion = {
  latitudeDelta: 15,
  longitudeDelta: 15,
  latitude: 60.1098678,
  longitude: 24.7385084,
};

export default function App() {
  const { height } = useWindowDimensions();

  const panY = useSharedValue(0);

  const gestureHandler = useAnimatedGestureHandler<
    PanGestureHandlerGestureEvent,
    AnimatedGHContext
  >(
    {
      onStart(_, context) {
        context.startY = panY.value;
      },
      onActive(event, context) {
        panY.value = context.startY + event.translationY;
      },
      onEnd() {
        if (panY.value < -height * 0.4) {
          panY.value = withTiming(-(height * 0.6));
        } else {
          panY.value = withTiming(0);
        }
      },
    },
    [height],
  );

  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateY: interpolate(panY.value, [-1, 0], [-1, 0], {
            extrapolateLeft: Extrapolate.EXTEND,
            extrapolateRight: Extrapolate.CLAMP,
          }),
        },
      ],
    };
  });

  return (
    <View style={{ flex: 1 }}>
      <MapView style={styles.mapStyle} initialRegion={initialRegion} />
      <PanGestureHandler onGestureEvent={gestureHandler}>
        <Animated.View
          style={[styles.container, { top: height * 0.7 }, animatedStyle]}
        >
          <Animated.View style={styles.grbber} />
          <SafeAreaView style={styles.wrapper}>
            <View style={styles.content}>
              <Text style={styles.title}>I am scroll sheet</Text>
              <View style={styles.fakeContent} />
            </View>
          </SafeAreaView>
        </Animated.View>
      </PanGestureHandler>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    shadowColor: 'black',
    shadowOffset: {
      height: -6,
      width: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    borderTopEndRadius: 15,
    borderTopLeftRadius: 15,
  },
  mapStyle: {
    width: width,
    height: 800, 
  },
  wrapper: {
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  title: {
    fontWeight: '400',
    fontSize: 22,
  },
  fakeContent: {
    flex: 1,
    height: 1000,
  },
  grbber: {
    width: 60,
    alignSelf: 'center',
    marginTop: 5,
    borderTopWidth: 5,
    borderTopColor: '#aaa',
  },
});

```


| Tech        | Version |
| ----------- | ------- |
| react-native-reanimated      | ^2.2.1 |


My Goal is make like this 

https://user-images.githubusercontent.com/47625626/132988572-bcd72dbc-66b8-4dd9-a71f-a43d11517515.mp4

**Comment by vxm5091** [comment]
In case this is helpful for anyone, I was getting a similar error when using the `withTiming()` hook. I was importing `Easing` from `react-native`. It should be imported from `react-native-reanimated`.

**Comment by mhammerc** [comment]
> In case this is helpful for anyone, I was getting a similar error when using the `withTiming()` hook. I was importing `Easing` from `react-native`. It should be imported from `react-native-reanimated`.

Thank you! This is a subtil hard-to-trace error!

**Comment by jmrossy** [comment]
I continue to see this issue on even when wrapping the `withTiming` callback in `runOnJS`, but it the error only occurs on iOS 13. Things seem to work fine in the iOS 15 simulator.

**Comment by Bartozzz** [comment]
This issue is still persisting and the error is unclear. I managed to find a fix (workaround?). I think it might need some more documentation:

```tsx
import { useSharedValue, withTiming, runOnJS } from 'react-native-reanimated';

const someSharedValue = useSharedValue(0);

const handleAnimationEnd = (finished?: boolean) => {}
const handleAnimationEndWrappedInRunOnJS = runOnJS(handleAnimationEnd);

// ❌ Will not work:
someSharedValue.value = withTiming(50, {}, handleAnimationEnd);
// ❌ Will not work:
someSharedValue.value = withTiming(50, {}, handleAnimationEndWrappedInRunOnJS);
// ✅ Will work:
someSharedValue.value = withTiming(50, {}, (finished) => runOnJS(handleAnimationEnd)(finished));
```

**Comment by chrispader** [comment]
This issue is also still happening for me at `react-native-reanimated@2.3.3`

**Comment by iway1** [comment]
happened to me when I imported `Easing` from `react-native` instead of `react-native-reanimated`
