### ISSUE TITLE
Error when creating multiple animation values at the same time

### ISSUE THREAD

**Issue by szalaybalazs** [software-mansion/react-native-reanimated#1760]
Hello

## Description

We are creating a long list of cards (~40-120 cards), rendered in a flatlist.
The animated value controls the heightof each card, based on the props of the cards.

When rendering the list we get the following error, randomly: ```Exception trown while executing UI block: ***-[__NSArrayMsetObject:atIndexedSubscript:]: object cannot be nil```

### Screenshots
![03093e17c9becf1dcdcdb37649261eee33a55213657dfcf5a5d075377e09c188](https://user-images.githubusercontent.com/26822176/109288186-d3a69e80-7824-11eb-9c5e-d475dbe68c28.png)

## Steps To Reproduce

1. Create a long list of cards rendered in a flatlist
2. Add an animated value to each card, and a boolean prop, set to `false` by default
3. Update the prop for one of the components, the error occures once in about every 20 change.

### Expected behavior

It should work without throwing an error.

### Actual behavior

When rendering the list we get the following error, randomly: ```Exception trown while executing UI block: ***-[__NSArrayMsetObject:atIndexedSubscript:]: object cannot be nil```

## Snack or minimal code example

```

const Card: FunctionComponent<iCardProps> = ({ name, featured, last, active, color, id, onSelect }) => {
  const transition = useMemoOne(() => new Value<number>(active ? 1 : 0), []);
  const opacity = useMemoOne(() => new Value<number>(0), []);
  useEffect(() => {
    timing(transition, {
      duration: 320,
      easing: Easing.inOut(Easing.sin),
      toValue: active ? 1 : 0,
    }).start();
  }, [active]);

  const _handleLoad = () => {
    timing(opacity, {
      duration: 320,
      easing: Easing.inOut(Easing.sin),
      toValue: 1,
    }).start();
  };

  const _handleSelect = () => onSelect?.(id);
  const height = multiply(MATERIAL_HEIGHT, add(1, multiply(transition, 2)));
  const contentHeight = add(height, last ? 0 : PADDING);
  return (
    <TouchableWithoutFeedback onPress={_handleSelect}>
      <Animated.View style={[styles.wrapper, { height, opacity }]}>
        <Animated.View style={[styles.content, { height: contentHeight }]}>
          <View style={styles.labelWrapper}>
            <Text style={[styles.label, color?.l < 50 && styles.light]}>{name}</Text>
          </View>
          <Image onLoad={_handleLoad} style={styles.image} source={{ uri: featured?.url }} resizeMode='cover' />
        </Animated.View>
      </Animated.View>
    </TouchableWithoutFeedback>
  );
};
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 1.13.2

Thank you in advance for the help.

**Comment by jakub-gonet** [comment]
Could you please attach **whole** code example that we can copy & paste and run in the project?

**Comment by szalaybalazs** [comment]
Hi @jakub-gonet,

I have uploaded a demo project to github: https://github.com/szalaybalazs/reanimated-demo

Please just play with the app by either tapping on the "type" titles, or by flinging on the list.
For me, the error occurred nearly instantly.

**Comment by hannojg** [comment]
I am getting the same error when using `AnimatedLayout`in 2.3.0-alpha1 on iOS. Android works

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request.
