### ISSUE TITLE
scrollTo without animation breaks sticky headers in ScrollView

### ISSUE THREAD

**Issue by JackShannon** [software-mansion/react-native-reanimated#1762]
## Description

Reanimated 2 scrollTo function breaks sticky headers (ignores that they are there), when animation paramater is set to false.

      scrollTo(ref, 0, 900, true); // respects sticky headers

      scrollTo(ref, 0, 900, false);  // ignores sticky headers

### Screenshots

![image](https://user-images.githubusercontent.com/865983/109320200-ac14fd80-7847-11eb-9bb7-b748176fe2a3.png)

upon using scrollTo:

![image](https://user-images.githubusercontent.com/865983/109320269-bd5e0a00-7847-11eb-9242-9b9f9a4f3415.png)

Notice that the sticky header has not remained there.

## Steps To Reproduce

1. Press "scrollTo" to see expected behaviour
2. Press the "reanimated scrollTo" button to see the actual behaviour

### Expected behavior

Sticky headers should be sticky.

### Actual behavior

Sticky headers are ignored.

## Snack or minimal code example

https://snack.expo.io/CpjxOeeol

This also happens in "^2.0.0-rc.3" without expo also, you can copy the snack code into a minimal react native project.

## Package versions

- React: 16.13.1
- React Native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
- React Native Reanimated: 2.0.0-rc.0
- NodeJS:

**Comment by andreialecu** [comment]
Also ran into this, a workaround that seemed to work was to do something like:

```ts
 scrollTo(ref, 0, 899, false);
 scrollTo(ref, 0, 900, true); // 1px animated scroll 
```

**Comment by JackShannon** [comment]
@andreialecu Thanks for this.

Your workaround does give the correct end result but seems to cause the sticky header to disappear for one frame when I tried it in the example above. Do you get this too?


https://user-images.githubusercontent.com/865983/109403648-698e1680-7956-11eb-806d-d6214ba54274.mov

**Comment by Szymon20000** [comment]
I've checked and we already fixed it. Fix will be available in the next release.
