### ISSUE TITLE
Rendering shared value<list> with FlatList

### ISSUE THREAD

**Issue by enesozturk** [software-mansion/react-native-reanimated#1787]
## Description

Hi,I am trying to render a list of elements with AnimatedFlatList. But the data list is coming as SharedValue. And because of the performance issues I am trying to avoid re-renders by memoizing my components. Passing list to AnimatedFlatList is not rendering the list even if shared value change.

If somehow I rerender the `MenuList` component, items are getting rendered. Is that the normal behaviour or do I missing something? Can we pass FlatList's `data` prop as shared value list?

## Steps To Reproduce

1. Create a shared value that keeps list of objects
2. Create an animated flat list component and pass shared list to flat list
3. Update shared list

### Expected behavior

I expected elements to be rendered even if component rerendered.

### Actual behavior

FlatList does not renders elements.

## Snack or minimal code example

```js
type MenuInternalProps = {
  items: MenuItemProps[];
  // x: number
  // y: number
  // ...
};

type menuProps = Animated.SharedValue<MenuInternalProps>;

const MenuList = () => {
  const { menuProps } = useInternal();

  const renderMenuItem = ({
    item,
    index,
  }: {
    item: MenuItemProps;
    index: number;
  }) => (
    <MenuItem
      item={item}
      isLast={menuProps.value.items.length == index + 1}
    />
  );
  const keyExtractor = useCallback(() => nanoid(), []);

  return (
    <AnimatedFlatList
      data={menuProps.value.items}
      keyExtractor={keyExtractor}
      renderItem={renderMenuItem}
      scrollEnabled={false}
    />
  );
};
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 15.0

**Comment by nandorojo** [comment]
I might be wrong here, but wouldn't you need to use `animatedProps`?

Something like:

```jsx
const animatedProps = useAnimatedProps(() => ({
  data: menuProps.value.items
}))

return <AnimatedFlatList animatedProps={animatedProps} />
```

I assume you'd have to whitelist that prop too. I don't fully understand when `animatedProps` should get used, though, so this could be wrong. It isn't clear to me if you can use a shared value in render code like your code sample or not.

**Comment by ehsan6sha** [comment]
To me it looks like sharedValue does not detect change in array values, so I used a lastItemValue and lastItemIndex and set them whenever I inserted or deleted an item in animated array, and useDerivedValue on those two.

**Comment by szydlovsky** [comment]
The issue is connected to deprecated (and unsupported) API. Nonetheless, shared values are meant to be like refs - they don't trigger re-renders and never will. Thus, closing the issue
