### ISSUE TITLE
iOS - 'NativeReanimated' could not be found.

### ISSUE THREAD

**Issue by BrendonSled** [software-mansion/react-native-reanimated#1793]
## Description

When running iOS I get the following error:
```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
```

I've followed the instructions on the website. Android works fine, this is just an issue with iOS.

I've attempted to wipe all the cache, pods, clean install, etc. Nothing seems to solve the problem.

## Steps To Reproduce

Here is an example project:
https://github.com/BrendonSled/react-native-reanimated-example

## Expected Behavior

Runs

## Actual Behavior

Doesn't run

## Snack or minimal code example
https://github.com/BrendonSled/react-native-reanimated-example

## Package versions

- React: 17.0.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0
- NodeJS: 14.15.5

**Comment by scrapecoder** [comment]
facing same issue

**Comment by BrendonSled** [comment]
This also doesn't seem to work with the `create-react-native-app`. There must be some missing install instructions for iOS.

**Comment by MananDesai54** [comment]
use reanimated version 1.13 then it will work fine

**Comment by BrendonSled** [comment]
Small update to this issue - it looks like upgrading to react native 0.64.0 solves the issue. 

This is the same version the example is using in this project.

**Comment by dotansimha** [comment]
Same here with RN 0.63, since updating to v2. Downgrading back to v1 resolved it for now.

**Comment by batical** [comment]
Try without debug mode. Switch ton Flipper for debugging

**Comment by BrendonSled** [comment]
I haven’t turned on debug and still get the error

**Comment by grit96** [comment]
I get the same with debug turned on, but it works with debug turned off.

**Comment by grit96** [comment]
Apparently this is a [known limitation](https://docs.swmansion.com/react-native-reanimated/docs/#known-problems-and-limitations)

**Comment by BrendonSled** [comment]
> I get the same with debug turned on, but it works with debug turned off.

Can you try cloning the example repository I added and trying that?

**Comment by grit96** [comment]
@BrendonSled yes I was trying your example repo

**Comment by BrendonSled** [comment]
<img width="673" alt="Screen Shot 2021-03-08 at 10 13 37 AM" src="https://user-images.githubusercontent.com/1565184/110348162-f55b0f00-7ff6-11eb-80d3-3ce508228f53.png">

@grit96 is this the debug you're talking about?

**Comment by grit96** [comment]
@BrendonSled Yes

**Comment by BrendonSled** [comment]
Very weird, as you can see from the screenshot I'm not in the debugging mode and I received that error.

**Comment by BrendonSled** [comment]
I finally got it.

In the AppDelegate.m I was using `initWithBundleURL` which does not seem to be supported. Instead using `initWithBridge` works.

here is my change:

```
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"main"
                                            initialProperties:nil];
```
