### ISSUE TITLE
interpolateColor on <Animated.Text /> causes warning

### ISSUE THREAD

**Issue by swushi** [software-mansion/react-native-reanimated#1794]
## Description
When interpolating the color of an `<Animated.Text>` the following warning is displayed:

> Warning: You are setting the style `{ color: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { color: ... } }`

The animation works fine, however, the warning is annoying and I don't want to ignore it as it may be an underlying issue of some sort.

### Screenshots
![IMG_0791](https://user-images.githubusercontent.com/34108400/110176493-fc043f00-7dc8-11eb-9770-31d8b643a616.PNG)

## Steps To Reproduce

```js
const colorMap = useSharedValue(0);

const animatedPlaceholderStyles = useAnimatedStyle(() => ({
      color: interpolateColor(
        colorMap.value,
        [0, 1, 2],
        [inactiveColor, activeColor, errorColor]
      ),
    }));

return (
      <Animated.View style={[styles.container, animatedContainerStyle]}>
        <Animated.Text
          style={[styles.placeholder, animatedPlaceholderStyles]}
          onLayout={handlePlaceholderLayout}
        >
          {placeholder}
        </Animated.Text>
      </Animated.View>
    );
```

### Expected behavior

No warning with expected animation.

### Actual behavior

Warning with expected animation.

## Snack or minimal code example

See above.

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 12.18.3

**Comment by tomekzaw** [comment]
@swushi, thank you for the report. I have tried to reproduce this issue in [Reanimated 2 Playground](https://github.com/software-mansion-labs/reanimated-2-playground), but I get no warning. The attached code example seems a bit incomplete so I mocked the missing parts except for `animatedContainerStyle` and `handlePlaceholderLayout`. Please provide the missing information so we can investigate and resolve any underlying issues.

<summary>
Screen.js
<details>

```js
import Animated, {
  Easing,
  interpolateColor,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';
import {Button, StyleSheet} from 'react-native';

import React from 'react';

export default function AnimatedStyleUpdateExample(props) {
  const colorMap = useSharedValue(0);

  const animatedPlaceholderStyles = useAnimatedStyle(() => ({
    color: interpolateColor(
      colorMap.value,
      [0, 1, 2],
      [inactiveColor, activeColor, errorColor],
    ),
  }));

  const handlePlaceholderLayout = () => {};

  const handlePress = () => {
    colorMap.value = withTiming(Math.random() * 2, {
      duration: 500,
      easing: Easing.linear,
    });
  };

  return (
    <>
      <Animated.View style={[styles.container, animatedContainerStyle]}>
        <Animated.Text
          style={[styles.placeholder, animatedPlaceholderStyles]}
          onLayout={handlePlaceholderLayout}>
          {placeholder}
        </Animated.Text>
      </Animated.View>
      <Button onPress={handlePress} title="Click me" />
    </>
  );
}

const inactiveColor = 'black',
  activeColor = 'lime',
  errorColor = 'red';

const animatedContainerStyle = {};

const placeholder = 'placeholder';

const styles = StyleSheet.create({
  container: {},
  placeholder: {},
});
```

</details>
</summary>

**Comment by swushi** [comment]
The exact code that has this error is my library [react-native-input-outline](https://github.com/swushi/react-native-input-outline).

Feel free to follow the contributing guide and before running just remove the `LogBox.ignore` line at the very bottom of the file located in both `InputOutline` and `InputStandard`.

**Comment by tomekzaw** [comment]
@swushi Thank you for the detailed description. I have reproduced the issue on the example app from your repository (using Reanimated 2.0.0-rc.0) by commenting out the `LogBox.ignore` calls.

After bumping Reanimated to 2.0.0 to check if the problem persists on the latest release, I get the following error:

<img src="https://user-images.githubusercontent.com/20516055/112328743-e6db4b80-8cb6-11eb-9dbd-2ecc7d34c84e.png" alt="" width="200" />

However, when I add your library as a dependency to our Reanimated 2 Example app, remove the `LogBox.ignore` calls from source code located in `node_modules` and then replace any existing screen with one of the [showcase examples](https://github.com/swushi/react-native-input-outline/tree/main/example/src), there are no warnings or errors at all (in particular, color interpolation works great). This suggests that there might be either a problem with using Reanimated 2 on Expo or some issue specific to your example app.

**Comment by fufylev** [comment]
I have the same issue
RN 0.64.0
Reanimated v.2.1.0
This code produces an error
`Warning: You are setting the style { color: ... } as a prop. You should nest it in a style object. E.g. { style: { color: ... } }`
`
import React, { useEffect } from 'react';
import { StyleSheet, View } from 'react-native';
import Animated, {
    useSharedValue,
    useAnimatedStyle,
    withDelay,
    withSpring,
    interpolateColor,
    withTiming,
    useDerivedValue,
} from 'react-native-reanimated';
import LinearGradient from 'react-native-linear-gradient';

export interface ProgressBarProps {
    level: number;
}

const GRADIENT_BACKGROUND = {
    colors: ['#F2F2F2', '#FCFCFC'],
};

const GRADIENT_PROGRESS = {
    colors: ['#36DDD2', '#249ADB'],
};

export const ProgressBar: React.FC<ProgressBarProps> = ({ level }) => {
    const widthValue = useSharedValue<number>(0);
    const color1 = useSharedValue<number>(0);
    const color2 = useSharedValue<number>(0);
    const color3 = useSharedValue<number>(0);

    const style = useAnimatedStyle(() => {
        return {
            width: withDelay(
                500,
                withSpring(`${widthValue.value}%`, {
                    damping: 50,
                    stiffness: 20,
                }),
            ),
        };
    });

    const colorOne = useDerivedValue(() => interpolateColor(color1.value, [0, 1], ['#0D0D0D29', '#ffffff']));
    const colorOneStyle = useAnimatedStyle(() => ({
        color: colorOne.value,
    }));

    const colorTwo = useDerivedValue(() => interpolateColor(color2.value, [0, 1], ['#0D0D0D29', '#ffffff']));
    const colorTwoStyle = useAnimatedStyle(() => ({
        color: colorTwo.value,
    }));

    const colorThree = useDerivedValue(() =>
        interpolateColor(color3.value, [0, 1], ['#0D0D0D29', '#ffffff']),
    );
    const colorThreeStyle = useAnimatedStyle(() => ({
        color: colorThree.value,
    }));

    useEffect(() => {
        color1.value = withTiming(level >= 1 ? 1 : 0, { duration: 1500 });
        color2.value = withTiming(level >= 2 ? 1 : 0, { duration: 1500 });
        color3.value = withTiming(level === 3 ? 1 : 0, { duration: 1500 });
        const widthLevel = () => {
            switch (level) {
                case 1:
                    return 35;
                case 2:
                    return 60;
                case 3:
                    return 100;
                default:
                    return 15;
            }
        };
        widthValue.value = widthLevel();
    }, [color1, color2, color3, level, widthValue]);

    return (
        <LinearGradient {...GRADIENT_BACKGROUND} style={styles.container}>
            <View style={styles.numbersRow}>
                <Animated.Text style={[styles.level, colorOneStyle]}>1</Animated.Text>
                <Animated.Text style={[styles.level, colorTwoStyle]}>2</Animated.Text>
                <Animated.Text style={[styles.level, colorThreeStyle]}>3</Animated.Text>
            </View>
            <Animated.View style={[styles.animation, style]}>
                <LinearGradient {...GRADIENT_PROGRESS} style={styles.gradient} />
            </Animated.View>
        </LinearGradient>
    );
};

const styles = StyleSheet.create({
    container: {
        width: '100%',
        height: 22,
        borderRadius: 11,
        backgroundColor: '#2F2E47',
        position: 'relative',
    },
    animation: {
        height: 22,
        borderRadius: 11,
        overflow: 'hidden',
    },
    gradient: {
        flex: 1,
    },
    numbersRow: {
        position: 'absolute',
        flexDirection: 'row',
        zIndex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    level: {
        fontSize: 14,
        textAlign: 'right',
        fontWeight: 'bold',
        width: '25%',
    },
});
`

**Comment by swansontec** [comment]
After many, many hours of debugging, I finally have some insight into what causes this!

The native Objective C / Java node manager uses a whitelist to determine which props it can set natively. There is a Javascript function called [`configureProps`](https://github.com/software-mansion/react-native-reanimated/blob/a8d9720ee5312a43cc4e3beb02e70b2fc6a030ae/src/ConfigHelper.js#L108) that is responsible for building this whitelist and sending it down to the native code. This needs to happen *before* any rendering takes place, or the native Objective C / Javascript code will treat everything as a JS prop, which causes this warning.

The tricky thing is that recent React Native versions load modules lazily by default. This means `configureProps` won't have a chance to run until some poor animated component decides to render for the first time. By then, it's too late. The native `configureProps` call will get batched up on the bridge, and won't execute until after the render completes with an empty whitelist.

One super-hacky way to defeat the lazy module loading is to add code like this to the app's `index.js`:

```js
import Animated from 'react-native-reanimated'

Animated.addWhitelistedNativeProps({})
```

This forces react-native-reanimated to download the whitelist before the app has a chance to render anything.

**Comment by kmagiera** [comment]
Hi @swushi – the code you provided does not seem to be complete. I tried to repro the problem by adding missing parts but don't get the warning on the most recent reanimated version. Here is the code I used:

```js
import React from 'react';
import { StyleSheet } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  interpolateColor,
} from 'react-native-reanimated';

const inactiveColor = '#ff0000';
const activeColor = '#00ff00';
const errorColor = '#0000ff';

function App(): React.ReactElement {
  const colorMap = useSharedValue(0);

  const animatedPlaceholderStyles = useAnimatedStyle(() => ({
    color: interpolateColor(
      colorMap.value,
      [0, 1, 2],
      [inactiveColor, activeColor, errorColor]
    ),
  }));

  const animatedContainerStyle = useAnimatedStyle(() => ({}));

  return (
    <Animated.View style={[styles.container, animatedContainerStyle]}>
      <Animated.Text style={[styles.placeholder, animatedPlaceholderStyles]}>
        {'lol'}
      </Animated.Text>
    </Animated.View>
  );
}

export const styles = StyleSheet.create({
  container: {
    margin: 150,
  },
  placeholder: {},
});

export default App;
```

**Comment by kmagiera** [comment]
Also wanted to thank @swansontec for the investigation, but again, it appears like this is something that we should be able to reproduce locally. So sharing some repository that'd allow us to reproduce would be much appreciated.

**Comment by swushi** [comment]
Apologies for the faulty code. I currently have this working in another project, no issue.
