### ISSUE TITLE
ReferenceError: can't find variable: _globalSetter

### ISSUE THREAD

**Issue by YMalikk** [software-mansion/react-native-reanimated#1795]
## Description
Hi, 
so i was using the v1 of react-native-reanimated, when i upgrade to v2, i got the error bellow 

### Screenshots
![Simulator Screen Shot - iPhone 11 - 2021-03-06 at 05 16 09](https://user-images.githubusercontent.com/37501156/110195807-45dc3c00-7e40-11eb-89dc-7b580462f323.png)

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 14.15.0

**Comment by brentvatne** [comment]
you probably forgot to add the babel plugin

**Comment by piaskowyk** [comment]
Hey @YMalikk 
the most possibly are two reasons:
- you didn't added Reaniamted plugin
- you didn't clear cache

#### How to add plugin
check your babel.config.js file if contains following line:
```
module.exports = {
  ...
  plugins: ['react-native-reanimated/plugin'],
  ...
};
```
more detailed instruction in our docs: https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin

#### How to clear cache
You can try something like this:
```
// in your root project catalog
rm -rf ./node_modules && yarn cache clean && yarn
cd ios && pod deintegrate && pod install && cd .. 
yarn start --reset-cache
```
