### ISSUE TITLE
Importing createDrawerNavigator throws 'NativeReanimated' error.

### ISSUE THREAD

**Issue by ModusPwnens1337** [software-mansion/react-native-reanimated#1798]
### Description
After following the installation instructions for [React Navigation](https://reactnavigation.org/docs/getting-started/) and then [Drawer Navigation](https://reactnavigation.org/docs/drawer-based-navigation/), I am getting a NativeReanimated error.

I have reanimated in both my package-lock.json:
```    
"react-native-reanimated": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/react-native-reanimated/-/react-native-reanimated-2.0.0.tgz",
      "integrity": "sha512-kIrdBoXSky7DQ62SOgosgimKM+Lt+SzAaM+ovVpCLBcwUK2aYRfLxa9ffgvKjeH9/n7dONlwEMjbKssGkuyq2Q==",
      "requires": {
        "@babel/plugin-transform-object-assign": "^7.10.4",
        "fbjs": "^3.0.0",
        "mockdate": "^3.0.2",
        "string-hash-64": "^1.0.3"
      }
```
and in my package.json:
```  
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.18.1"
  }
  ```

It was installed vis the React Navigation instructions as follows:
`npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`

This is the error I'm receiving in Metro and node after running **npx react-native run-android:**
[Sat Mar 06 2021 10:25:12.380]  **BUNDLE  ./index.js**

[Sat Mar 06 2021 10:25:15.192]  **ERROR    Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.**
[Sat Mar 06 2021 10:25:15.196]  **ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)**
[Sat Mar 06 2021 10:25:15.196]  **ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)**

In the emulator I'm just receiving a blank white screen.

### Screenshots
![image](https://user-images.githubusercontent.com/6161922/110212233-63bd9700-7e68-11eb-86ff-0616981769f0.png)
![image](https://user-images.githubusercontent.com/6161922/110212284-aa12f600-7e68-11eb-8718-26609dc489c8.png)
![image](https://user-images.githubusercontent.com/6161922/110212302-bbf49900-7e68-11eb-89e6-789f1724d818.png)

## Steps To Reproduce
1. Try to run the app via: **npx react-native run-android**

### Expected behavior
The app should run.

### Actual behavior
I get a blank white screen.

## Snack or minimal code example
Commenting out this line: **import { createDrawerNavigator } from '@react-navigation/drawer';** fixes the error.

![image](https://user-images.githubusercontent.com/6161922/110212461-7d131300-7e69-11eb-9bc6-3bd439e3a28e.png)

## Package versions
Windows 10
Visual Studio Code

    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.18.1"
- NodeJS: **v10.19.0**

**Comment by ModusPwnens1337** [comment]
https://github.com/react-navigation/react-navigation/issues/9389#issuecomment-791991490

**Comment by usinghs** [comment]
FYI. I faced same issue while using reanimated version 2.0.0

Version "react-native-reanimated": "^1.13.2" works fine.

**Comment by batical** [comment]
did you try without debug mode ?

**Comment by fatihkck** [comment]
I get same error too while using reanimated version 2.0.0
I install version react-native-reanimated": "^1.13.2". It is working fine.

**Comment by MEsteves22** [comment]
Hello, 
I am currently having the same problem on Android since I upgraded react-native-reanimated to version 2.0.0. I had to downgrade back to version 1.13.2.

**Comment by ModusPwnens1337** [comment]
> FYI. I faced same issue while using reanimated version 2.0.0
> 
> Version "react-native-reanimated": "^1.13.2" works fine.

After I uninstall reanimated then install version 1.13.2 I get the following error:
`error: Error: Unable to resolve module ./reanimated2 from ...\node_modules\react-native-reanimated\src\Animated.js:`

**Comment by ModusPwnens1337** [comment]
> Hello,
> I am currently having the same problem on Android since I upgraded react-native-reanimated to version 2.0.0. I had to downgrade back to version 1.13.2.

After I uninstall reanimated then install version 1.13.2 I get the following error:
`error: Error: Unable to resolve module ./reanimated2 from ...\node_modules\react-native-reanimated\src\Animated.js:`

**Comment by konstantingoretzki** [comment]
> 
> 
> > Hello,
> > I am currently having the same problem on Android since I upgraded react-native-reanimated to version 2.0.0. I had to downgrade back to version 1.13.2.
> 
> After I uninstall reanimated then install version 1.13.2 I get the following error:
> `error: Error: Unable to resolve module ./reanimated2 from ...\node_modules\react-native-reanimated\src\Animated.js:`

Can confirm this behaviour. Downgrading throws the same error on my side.

Here are my dependencies:
```
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-android-location-enabler": "^1.1.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.18.1"
```

Also using VSCode on Win 10.

**Comment by ModusPwnens1337** [comment]
> > > Hello,
> > > I am currently having the same problem on Android since I upgraded react-native-reanimated to version 2.0.0. I had to downgrade back to version 1.13.2.
> > 
> > 
> > After I uninstall reanimated then install version 1.13.2 I get the following error:
> > `error: Error: Unable to resolve module ./reanimated2 from ...\node_modules\react-native-reanimated\src\Animated.js:`
> 
> Can confirm this behaviour. Downgrading throws the same error on my side.
> 
> Here are my dependencies:
> 
> ```
>     "@react-native-community/masked-view": "^0.1.10",
>     "@react-native-community/netinfo": "^6.0.0",
>     "@react-navigation/drawer": "^5.12.4",
>     "@react-navigation/native": "^5.9.3",
>     "@react-navigation/stack": "^5.14.3",
>     "react": "16.13.1",
>     "react-native": "0.63.4",
>     "react-native-android-location-enabler": "^1.1.0",
>     "react-native-gesture-handler": "^1.10.3",
>     "react-native-reanimated": "^1.13.2",
>     "react-native-safe-area-context": "^3.1.9",
>     "react-native-screens": "^2.18.1"
> ```
> 
> Also using VSCode on Win 10.

Have you gotten anywhere with this?

**Comment by konstantingoretzki** [comment]
> 
> 
> > > > Hello,
> > > > I am currently having the same problem on Android since I upgraded react-native-reanimated to version 2.0.0. I had to downgrade back to version 1.13.2.
> > > 
> > > 
> > > After I uninstall reanimated then install version 1.13.2 I get the following error:
> > > `error: Error: Unable to resolve module ./reanimated2 from ...\node_modules\react-native-reanimated\src\Animated.js:`
> > 
> > 
> > Can confirm this behaviour. Downgrading throws the same error on my side.
> > Here are my dependencies:
> > ```
> >     "@react-native-community/masked-view": "^0.1.10",
> >     "@react-native-community/netinfo": "^6.0.0",
> >     "@react-navigation/drawer": "^5.12.4",
> >     "@react-navigation/native": "^5.9.3",
> >     "@react-navigation/stack": "^5.14.3",
> >     "react": "16.13.1",
> >     "react-native": "0.63.4",
> >     "react-native-android-location-enabler": "^1.1.0",
> >     "react-native-gesture-handler": "^1.10.3",
> >     "react-native-reanimated": "^1.13.2",
> >     "react-native-safe-area-context": "^3.1.9",
> >     "react-native-screens": "^2.18.1"
> > ```
> > 
> > 
> > Also using VSCode on Win 10.
> 
> Have you gotten anywhere with this?

Unfortunately no.
I've tried almost all release candidate and older version but they all fail due to dependency issues.

I am currently using the stack navigator so that I can focus on other parts during the development.
Switching is fortunately very easy. But the side menu of the drawer is in the long term a feature I really need ...

**Comment by itzmestar** [comment]
Indeed I got the same error as well. Clear out the cache. Uninstalled and install react-native-reanimated again. Close metro server. Uninstalled app on emulator. Then it should work.

**Comment by ModusPwnens1337** [comment]
> Indeed I got the same error as well. Clear out the cache. Uninstalled and install react-native-reanimated again. Close metro server. Uninstalled app on emulator. Then it should work.

I tried all of that except clearing cache, which cache are you talking about?

**Comment by ModusPwnens1337** [comment]
> > > > > Hello,
> > > > > I am currently having the same problem on Android since I upgraded react-native-reanimated to version 2.0.0. I had to downgrade back to version 1.13.2.
> > > > 
> > > > 
> > > > After I uninstall reanimated then install version 1.13.2 I get the following error:
> > > > `error: Error: Unable to resolve module ./reanimated2 from ...\node_modules\react-native-reanimated\src\Animated.js:`
> > > 
> > > 
> > > Can confirm this behaviour. Downgrading throws the same error on my side.
> > > Here are my dependencies:
> > > ```
> > >     "@react-native-community/masked-view": "^0.1.10",
> > >     "@react-native-community/netinfo": "^6.0.0",
> > >     "@react-navigation/drawer": "^5.12.4",
> > >     "@react-navigation/native": "^5.9.3",
> > >     "@react-navigation/stack": "^5.14.3",
> > >     "react": "16.13.1",
> > >     "react-native": "0.63.4",
> > >     "react-native-android-location-enabler": "^1.1.0",
> > >     "react-native-gesture-handler": "^1.10.3",
> > >     "react-native-reanimated": "^1.13.2",
> > >     "react-native-safe-area-context": "^3.1.9",
> > >     "react-native-screens": "^2.18.1"
> > > ```
> > > 
> > > 
> > > Also using VSCode on Win 10.
> > 
> > 
> > Have you gotten anywhere with this?
> 
> Unfortunately no.
> I've tried almost all release candidate and older version but they all fail due to dependency issues.
> 
> I am currently using the stack navigator so that I can focus on other parts during the development.
> Switching is fortunately very easy. But the side menu of the drawer is in the long term a feature I really need ...
> 
> Edit: I've just found the issue #1127 and tried the solution from @itzmestar, but it also hasn't worked :/
> I've tried using the following cmds:
> 
> ```
> npm uninstall @react-navigation/drawer @react-navigation/native @react-navigation/stack
> npm install --save @react-navigation/drawer@5.12.3 @react-navigation/native@5.9.2 @react-navigation/stack@5.14.2
> ```

I googled how to clear cache and sure enough it fixed my issue [stackoverflow](https://stackoverflow.com/questions/46878638/how-to-clear-react-native-cache)

I just ran the following in my project directory:
`npm start -- --reset-cache`

**Comment by konstantingoretzki** [comment]
Yay - it finally works.
I've tried a couple of things before it has actually worked.
I had to reinstall / downgrade the react-navigation libs AND downgrade to the older react-native-reanimated@1.13.2.

Since I've tried a lot of combinations and I am not sure how reliable the integrated terminal history of VSCode with PS is, I am not 100% sure if these were the commands. However they might help for future reference.

```
# install after react-navigation instructions --> npm install @react-navigation/drawer

# remove core elements like drawer and reinstall using older / current version
npm uninstall @react-navigation/drawer @react-navigation/native @react-navigation/stack
npm install --save @react-navigation/drawer@5.12.3 @react-navigation/native@5.9.2 @react-navigation/stack@5.14.2

# maybe uninstall before? --> npm uninstall react-native-reanimated (I think I've skipped this)
# install older version
npm install --save react-native-reanimated@1.13.2

# start app on device (maybe delete first)
npx react-native run-android

# reset cache if not working
npm start -- --reset-cache
```

Besides this seems like "just a temp. fix" so this problem might happen with future versions before we determined the cause.

**Comment by raajnadar** [comment]
run `npx react-native start --reset-cache` after that `npx react-native run-android` or `npx react-native run-ios`

**Comment by YunusEmreNalbant** [comment]
> run `npx react-native start --reset-cache` after that `npx react-native run-android` or `npx react-native run-ios`

thank yo bro... I almost went crazy.

**Comment by AlgoPole** [comment]
I can't run any of my applications in react native on my android simulator with reanimated2 (DrawerNavigator throws an error, NativeReanimated not found). Are you sure this new module have ever been tested before commiting?

**Comment by raajnadar** [comment]
React navigation v5 is not compatible with reanimated 2

**Comment by preetgaggu** [comment]
I have solved this problem. Move on to **React Navigation v6** . V6 is mostly same as V5. if not solved than down grade **react-native-reanimated** to version 1. Don't forget to start react native project with `npx react-native start --reset-cache`

**Comment by Vinaybandarapu** [comment]
> run `npx react-native start --reset-cache` after that `npx react-native run-android` or `npx react-native run-ios`

while running `npx react-native start --reset-cache` i'm facing this issue :-
error Failed to load configuration of your project.
Config Validation Error: "project.ios.project" is not allowed

    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
info Run CLI with --verbose flag for more details.

**Comment by Izzy-glen** [comment]
> run `npx react-native start --reset-cache` after that `npx react-native run-android` or `npx react-native run-ios`

Thanks A Ton Damn

**Comment by ggrachdev** [comment]
I tried setting - "react-native-reanimated": "2.11.0" and it didn't work. As a result, the problem was solved by installing the latest version of "react-native-screens" and managed to build the apk through android studio
