### ISSUE TITLE
'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by MananDesai54** [software-mansion/react-native-reanimated#1799]
## Description
I am using react navigation library which uses react navigation as dependency, but after release of react native reanimated v2 it is breaking and giving this kind of error, I tried all possible stuff but not solved, then i switched to version 1.13.0 of reanimated then it stated working so there is some problem for reanimated v2 and react navigation.

## Steps To Reproduce
refer [this guide](https://reactnavigation.org/docs/getting-started/) and create bare react native project with react native reanimated v2 and then [refer this](https://reactnavigation.org/docs/hello-react-navigation) to create navigator

### Expected behavior
It should run

### Actual behavior
It is breaking

## Package versions

- React:  16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0
- NodeJS: 15.5.1
- React Navigation: 5.9.3

**Comment by BrendonSled** [comment]
duplicate of #1793

**Comment by MananDesai54** [comment]
Oh My bad
