### ISSUE TITLE
Android - remote debugging crash

### ISSUE THREAD

**Issue by grit96** [software-mansion/react-native-reanimated#1806]
## Description

App crashes when using Debug from the RN debug menu

## Steps To Reproduce

1. Run example app
2. Press Debug from the RN debug menu
3. App crashes

### Expected behavior

Doesn't crash

### Actual behavior

![image](https://user-images.githubusercontent.com/3957608/110323206-33aef900-800c-11eb-8c21-f2be58eede90.png)

## Snack or minimal code example

https://github.com/grit96/RNAnimatedExample

## Package versions

- React: 16.3.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0
- NodeJS: 10.19.0

**Comment by jakub-gonet** [comment]
This is working as intended, check ["Known problems and limitations"](https://docs.swmansion.com/react-native-reanimated/docs#known-problems-and-limitations) in our docs.

**Comment by grit96** [comment]
Thanks for the information. Are there any plans to support remote debugging again or is it likely to be phased out with Flipper replacing it?

**Comment by jakub-gonet** [comment]
We can't do that due to the technical reasons mentioned in the comment linked above. We probably can disable Reanimated if it isn't used on a particular screen but this solution isn't really scalable. 
The best solution at the moment is to use Flipper.

**Comment by aprilmintacpineda** [comment]
I just ran into this issue, Flipper is the best option as far as I can tell.
