### ISSUE TITLE
useAnimatedProps don't use a current SharedValue state

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-reanimated#1808]
## Description

If you use `animatedProps` on web, it only uses the initial value. Any changes to shared values does nothing.

### Screenshots

https://www.loom.com/share/dc2aa06097b34de99b9182d059cadc95

Here's a video. Notice that, if I change the initial shared value and refresh the page, it works as expected. However, if I mutate the shared value in a function, `useAnimatedProps` still returns the initial value.

In my case, I'm trying to enable/disable pointer events for the bottom button.

## Steps To Reproduce
 
1. Create reanimated project
2. Add `useAnimatedProps` to a component
3. Run `yarn web`

### Expected behavior

Mutating a shared value (in the example, `pointerEvents.value`) should result in the `animatedProps` updating on web.

### Actual behavior

The initial value returned by `useAnimatedProps` never updates.

## Snack or minimal code example

I created a minimal reproduction [here](https://github.com/nandorojo/reanimated-UAP-web-bug).

<details>
  <summary><b>Code here</b></summary>

```jsx
import * as React from "react";
import { StyleSheet, View, Button } from "react-native";
import Animated, {
  useAnimatedProps,
  useSharedValue,
} from "react-native-reanimated";

// these both do nothing for web
Animated.addWhitelistedNativeProps({
  pointerEvents: true,
});
Animated.addWhitelistedUIProps({
  pointerEvents: true,
});

export default function App() {
  const pointerEvents = useSharedValue("auto");

  const bottomProps = useAnimatedProps(() => ({
    pointerEvents: pointerEvents.value,
  }));

  const toggle = () => {
    if (pointerEvents.value === "none") {
      pointerEvents.value = "auto";
    } else {
      pointerEvents.value = "none";
    }
    console.log("pointer events:", pointerEvents.value);
  };

  return (
    <View style={styles.container}>
      <View style={styles.half}>
        <Button color="black" title="Toggle Pointer Events" onPress={toggle} />
      </View>
      <Animated.View
        style={[styles.half, styles.bottom]}
        animatedProps={bottomProps}
      >
        <Button
          color="black"
          title="Press me?"
          onPress={() => alert("has pointer events!")}
        />
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  half: {
    flex: 1,
    backgroundColor: "hotpink",
    justifyContent: "center",
    alignItems: "center",
  },
  bottom: {
    backgroundColor: "green",
  },
});
```

</details>

## Package versions

- React: `16.13.1`
- React Native: Expo SDK 40
- React Native Reanimated: `2.0.0-rc.0` (the same happens on the stable `v2`)
- NodeJS: `v14.2.0`

**Comment by nandorojo** [comment]
When using React Native SVG and animated props on web, the props on web are being passed directly to the html as `[Object object]` (I noticed this by inspecting the html). It's a bit harder to make a repro, but I can try for this as well.

**Comment by piaskowyk** [comment]
@nandorojo Thanks for the well-described issue and for preparing the playground repo. It is really helpful 🙌  
Problem solved.

**Comment by nandorojo** [comment]
Thanks for the quick repoly @piaskowyk!

**Comment by nandorojo** [comment]
@piaskowyk Question: I'm getting similar behavior if I use both `style` and `animatedProps` on an `Animated.View`.

```tsx
const style = useAnimatedStyle(...)
const props = useAnimatedProps(...)

return <Animated.View style={style} animatedProps={props} />
```

I've only tested this on web so far. Is this a known issue? Should I just be splitting this into two components?

Splitting the components on web solves it:

```tsx
const Component = () => {
  const pointerEvents = useSharedValue('auto')

  const toggle = () => {
    pointerEvents.value === 'auto' ? (pointerEvents.value = 'none') : (pointerEvents.value = 'auto')
  }

  const style = useAnimatedStyle(() => ({}))
  const props = useAnimatedProps(() => ({
    pointerEvents: pointerEvents.value
  }))

  return (
    <Animated.View style={style}>
      <Animated.View animatedProps={props} />
    </Animated.View>
  )
}
```

**Comment by codeSantiago** [comment]
I've just ran into the same issue when trying to animate a svg circle, it does not only not works but it also affects other animations, when i was animating some lines as soon i added the animatedProps to the AnimatedCircle none of the others animations ran anymore.
