### ISSUE TITLE
App crash when import react-navigation-drawer, error in turbo modules rn-reanimated(all versions)

### ISSUE THREAD

**Issue by jcvidela** [software-mansion/react-native-reanimated#1822]
## Description
When I am import react-navigation-drawer or @react-navigation/drawer, the app crash showing it's error in console
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary

### Screenshots
![image](https://user-images.githubusercontent.com/42773351/111018929-ca780e80-839a-11eb-89a1-73991d63ca2a.png)

## Steps To Reproduce

1. Create new React Native project, npx react-native init drawer.
2. Copy and paste this example, https://reactnavigation.org/docs/drawer-based-navigation/ or use setup your drawer manually.
3. Run app in development.

### Expected behavior
Drawer navigator

### Actual behavior
Crashed app
## Snack or minimal code example
I use this example, but all versions crash with the same error
https://reactnavigation.org/docs/drawer-based-navigation/ or use setup your drawer manually.

## Package versions
"dependencies": {
    "@react-navigation/drawer": "^5.12.4",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^2.18.1",
    "react-navigation": "^4.4.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },

- React:
- React Native:
- React Native Reanimated:
- NodeJS:

**Comment by mrousavy** [comment]
Could you check your `package-lock.json` and search for `react-native-reanimated` to see if anything installed a v1 version of REA?

[react-navigation/drawer](https://github.com/react-navigation/react-navigation/blob/main/packages/drawer/package.json#L69) has no specific setting for REA, but it might be worth a shot anyways.

**Comment by thainquet** [comment]
got the same problem after installing reanimated v2.
i switched to init new project, specific react-native-reanimated to use v1 in package.json then yarn install
After that, everything works fine

**Comment by jcvidela** [comment]
Partially resolved issue, thanks @thainquet,
React navigation does not have support for react native reanimated 2, instead it is replaced by version 1.
