### ISSUE TITLE
[2.0.0] Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by Waqas-Jani** [software-mansion/react-native-reanimated#1825]
Hey, I'm facing this issue in 2.x.x version,When importing @react-navigation/drawer. but perviouse version 1.x.x working fine.
React-native 0.63.4 

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0
- NodeJS: 14.15.5

**Comment by PritishSawant** [comment]
Yup i am facing same issue as well on RN v 0.64

**Comment by braincore** [comment]
Bit of a long shot, but I'm also getting this error when using reanimated from an iOS share extension.

**Comment by piaskowyk** [comment]
@Waqas-Jani 
Did you use `npm` or `yarn`? (you should use `yarn`) Did you add Reanimated plugin?
#### How to add plugin
check your babel.config.js file if contains following line:
```
module.exports = {
  ...
  plugins: ['react-native-reanimated/plugin'],
  ...
};
```
more detailed instruction in our docs: https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin

**Comment by preetgaggu** [comment]
I have solved this problem. Move on to **React Navigation v6** . V6 is mostly same as V5. if not solved than down grade **react-native-reanimated** to version 1. Don't forget to start react native project with `npx react-native start --reset-cache`

**Comment by abdullahkhan70** [comment]
> I have solved this problem. Move on to **React Navigation v6** . V6 is mostly same as V5. if not solved than down grade **react-native-reanimated** to version 1. Don't forget to start react native project with `npx react-native start --reset-cache`

Well, I am facing this same problem from the android side. My iOS is working fine, but my Android side giving me this error. Do you know anything about how can I sort out this problem?
I am using react-native-reanimated:2.0.0 and also react-native: 0.62.0.
Basically, I developed this app using react-native:0.63.2 and react-native-reanimated:2.0.0-rc.3. Is there any way to sort out this problem?

**Comment by raultunduc1995** [comment]
```
React-Native: 0.62.0
React-Navigation: ^5
Reanimate: ^2.0.0
```

This message is shown in the Xcode's logs when running the app on iOS, but it works perfectly on Android.
I don't know what I am doing wrong.
I have followed all the steps described in the documentation.
Please help!

**Comment by preetgaggu** [comment]
@abdullahkhan70 i am using react-native 0.64.0 version, react-native-reanimated 1.0.0 and Navigation V6. Make sure you must have React-native-reanimated 1.0.0 and Navigation V6 install. Than try to run on android. Problem will be solved easily.

**Comment by preetgaggu** [comment]
@raultunduc1995 I got same error Use these library as mentioned below.
`React-Native: 0.63.0 or 0.64.0 or may be 0.62.0 also work
React-Navigation: 6.0.0 (Launched few days ago )
React-Native-Reanimated 1.0.0` 

Hope your problem will be solved.

**Comment by abdullahkhan70** [comment]
> @abdullahkhan70 i am using react-native 0.64.0 version, react-native-reanimated 1.0.0 and Navigation V6. Make sure you must have React-native-reanimated 1.0.0 and Navigation V6 install. Than try to run on android. Problem will be solved easily.

Should I install @react-navigation/next version? and as well as it's drawer and the other relevant libraries.

**Comment by preetgaggu** [comment]
@abdullahkhan70  yes .. you have to install @react-navigation/ next version and drawer.

**Comment by abdullahkhan70** [comment]
> @abdullahkhan70 yes .. you have to install @react-navigation/ next version and drawer.

@preetgaggu when I try to compile through android studio the react native reanimated: 1.0.0 is giving this problem.

import android.support.transition.TransitionManager; does not exist.
^

what should I do?

**Comment by raultunduc1995** [comment]
> @raultunduc1995 I got same error Use these library as mentioned below.
> `React-Native: 0.63.0 or 0.64.0 or may be 0.62.0 also work React-Navigation: 6.0.0 (Launched few days ago ) React-Native-Reanimated 1.0.0`
> 
> Hope your problem will be solved.

@preetgaggu I do not want to upgrade to navigation 6.
I want to use the same navigation version and the same react-native version.
So, I assume that reanimated 2 is not backward-compatible? 
I just wanted to use reanimated 2 and that's it but it seems it's full of bugs....
You guys really need to work harder on this version

**Comment by abdullahkhan70** [comment]
@preetgaggu  Now my iOS is also not working :(

**Comment by abdullahkhan70** [comment]
@preetgaggu Should I use navigation 6 and reanimated 2? Maybe, this would sort out the problem.

**Comment by preetgaggu** [comment]
@abdullahkhan70  Brother i have solved my problem this way.. Try to upgrade React Native Version to 0.64.0 . I have used React Navigation 6 with Reanimated 1.0.0. If not solved than wait some time and i didn't check my app with IOS.

**Comment by mosoakinyemi** [comment]
I had this issue on iOS, solved it by simply deleting the app on the simulator and reinstalling with `npx react-native run-ios`

**Comment by raultunduc1995** [comment]
Solved the problem on iOS.
this is the answer: https://github.com/software-mansion/react-native-reanimated/issues/1793#issuecomment-792937253
I just needed to follow the migration to RN: 0.62

**Comment by abdullahkhan70** [comment]
@raultunduc1995 brother, I am still facing this error. All of the sudden my iOS is not working at all.

**Comment by Waqas-Jani** [comment]
i downgrade the react-native-reanimated to 1.x.x ,then working fine

**Comment by minhchienwikipedia** [comment]
Any updated? I'm still getting this issue with RN `0.63.4` and Reanimated `2.0.0`

**Comment by 4yki** [comment]
> Solved the problem on iOS.
> this is the answer: [#1793 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/1793#issuecomment-792937253)
> I just needed to follow the migration to RN: 0.62

this helped me! thx

**Comment by Rohan-ult** [comment]
Same Problem

**Comment by swanand246** [comment]
> 
> 
> i downgrade the react-native-reanimated to 1.x.x ,then working fine

how to downgrade the react-native reanimated to 1.x.x.Currently I am facing same issue and I am not getting how to downgrade the react-native-reanimated.Please Help.

**Comment by udaris** [comment]
> @abdullahkhan70 Brother i have solved my problem this way.. Try to upgrade React Native Version to 0.64.0 . I have used React Navigation 6 with Reanimated 1.0.0. If not solved than wait some time and i didn't check my app with IOS.

Can you plz tell me how to install Reanimated 1.0.0? , npm i react-native-reanimated not working it also only reanimated2. I am also with this error when I use drawer navigation.

**Comment by udaris** [comment]
> > i downgrade the react-native-reanimated to 1.x.x ,then working fine
> 
> how to downgrade the react-native reanimated to 1.x.x.Currently I am facing same issue and I am not getting how to downgrade the react-native-reanimated.Please Help.

I think it can downgrade using npm i react-native-reanimated@1.0.0 , but it get another errors not loading app. app build is failed. with this error:
BUILD FAILED in 3s

error Failed to install the app. Make sure you have the 
Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Udari\Proj1\node_modules\react-native-reanimated\android\build.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Cannot get property 'supportLibVersion' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (C:\Users\U\Proj1\node_modules\execa\index.js:174:9)
    at C:\Users\U\Proj1\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (C:\Users\U\Proj1\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\U\Proj1\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

**Comment by udaris** [comment]
Yes, it is working with reanimated1 in drawer navigation. thank you! for me, I use npm i react-native-reanimated@1.13.2.
