### ISSUE TITLE
V2.0.0-rc.0 different thread error when using hooks provided in reanimated v2

### ISSUE THREAD

**Issue by haibert** [software-mansion/react-native-reanimated#1826]
### issue: 
Getting the following error anytime  a reanimated hook is used within the useAnimatedStyle hook. 

![Simulator Screen Shot - iPhone 12 - 2021-03-14 at 11 35 20](https://user-images.githubusercontent.com/31780749/111080202-9c89eb80-84ba-11eb-977a-05ba98de117c.png)

### Description
I am using reanimted v2.0.0-rc.0 because thats the version that runs with expo currently. The entire app crashes when the component mounts if there is a reanimated hook such as withTiming nested within the useAnimatedStyle hook.

Tell us what's happening here.
If I nest a reanimated hook within another reanimated hook I get the error. Other wise there is no crash. 

### Screenshots
<img width="679" alt="Screen Shot 2021-03-14 at 11 54 27 AM" src="https://user-images.githubusercontent.com/31780749/111080529-21293980-84bc-11eb-8195-f364c2d35c6a.png">

<img width="478" alt="Screen Shot 2021-03-14 at 11 55 23 AM" src="https://user-images.githubusercontent.com/31780749/111080560-3900bd80-84bc-11eb-9468-f05ac62430ce.png">

### Steps to reproduce
1. install reanimated V2.0.0-rc.0
2. just launch the app and try out the code provided below. 
3. Im also using react navigation 5 I'm not sure if that matters.

### Expected behavior
Expected behavior is for there to be no crashes and the animation to carry out. 

### Actual behavior
App crashes right when the component mounts. 

## Snack or minimal code example

import { View, StyleSheet, TouchableWithoutFeedback } from 'react-native'
import React from 'react'
import Animated, {
    useSharedValue,
    useAnimatedStyle,
    withTiming,
} from 'react-native-reanimated'

const Transitions = () => {
    const animation = useSharedValue(0)

    const animationStyle = useAnimatedStyle(() => {
        return {
            transform: [
                {
                    translateX: withTiming(
                        animation.value,
                        {
                            duration: 1000,
                        },
                        () => {
                            animation.value = 0
                        }
                    ),
                },
            ],
        }
    })

    return (
        <View style={styles.container}>
            <TouchableWithoutFeedback
                onPress={() => {
                    animation.value = 200
                }}
            >
                <Animated.View style={[styles.box, animationStyle]} />
            </TouchableWithoutFeedback>
        </View>
    )
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    box: {
        width: 200,
        height: 200,
        backgroundColor: '#631d94',
    },
})

export default Transitions

## Package versions

- React: 16.13.1
- React Native: "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
- React Native Reanimated: 2.0.0-rc.0
- NodeJS: 14.15.1

**Comment by JacopoPatroclo** [comment]
I encouter the same type of issue using the useAnimatedStyle hook but I'm not sure if they have the same root couse.

For example in my case I'have used the box example from the documentation:
```
export const AnimationScreen: React.FC<AnimationScreenProps> = ({}) => {
  const offset = useSharedValue(0);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: withSpring(offset.value * 255) }],
    };
  }, [offset]);

  return (
      <View>
        <Text>Hello home</Text>
        <Animated.View style={[styles.box, animatedStyles]}></Animated.View>
        <Button
          title="Animate"
          onPress={() => (offset.value = Math.random())}
        />
      </View>
  );
};
```
And I've encoutered this error
![Schermata 2021-03-14 alle 22 45 07](https://user-images.githubusercontent.com/42748150/111085273-ef918c00-8516-11eb-9461-caa43bcb5400.png)

I've tried to debug it localy inside my node_modules folder and it turns out that was the Object.assign method on line 307 in `src/reanimated2/Hooks.js` and on line 58 and 100 inside `src/reanimated2/animations.js`. Swapping the assign function with the almost equivalent spread operator makes the error go away and everything seems to work.

example on line 100 in `src/reanimated2/animations.js`
```
 // animation[i] = Object.assign({}, animationCopy);
 animation[i] = { ...animationCopy }
```

Not sure is the problem is related to something else in my setup due to the fact that I'm using react-native inside an nx monorepo with [this](https://github.com/nrwl/nx-react-native) plugin.

Anyway hope that this post helps, thanks for this amazing tool !! You guys are the best !!

## Package versions

    React: 17.0.1
    React Native: 0.63.2
    React Native Reanimated: 2.0.0
    NodeJS: 14.15.4

## Babel config

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
    'transform-inline-environment-variables',
    'babel-plugin-transform-typescript-metadata',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
  ],
};
```

**Comment by haibert** [comment]
Very interesting. Thank you so much for the reply! Unfortunately the error is not showing me the root file causing the error. I went through all the js files inside the reanimated folder and searched for inOut and it looks like it was declared inside Easing.js like so: 

`
function inOut(easing) {
  'worklet';
  return (t) => {
    'worklet';
    if (t < 0.5) {
      return easing(t * 2) / 2;
    }
    return 1 - easing((1 - t) * 2) / 2;
  };
}
`

Not sure what i would need to do to fix the issue though...

**Comment by haibert** [comment]
FIXED ! 
My issue was............. I was using npm and not yarn. Couldn't believe it. I spent an entire day troubleshooting this and I hope that other people running into this issue will be spared those painful hours. Im switching over to yarn for good!

If you're using expo, and using npm install yarn and run the following commands:

** 
yarn add react-native-reanimated@2.0.0-rc.0
yarn add react-native-gesture-handler
rm -r node_modules
yarn watchman watch-del-al
rm -fr $TMPDIR/metro-cache
yarn add --save core-js@^3
yarn
expo start -c  
**

**Comment by piaskowyk** [comment]
If fixed I close
