### ISSUE TITLE
Different handling of PanGestureHandler with <Animated.View> inside for iOS and Android. 

### ISSUE THREAD

**Issue by wojtus7** [software-mansion/react-native-reanimated#1827]
## Description

Different handling of PanGestureHandler with <Animated.View> inside for iOS and Android. 
Complex explanation below in `Actual Behavior` 👇

## Steps To Reproduce

1. `git clone https://github.com/wojtus7/reanimated-story-cards/tree/reanimated2-issue`
2. This is standard Reanimated2-Playground so `yarn` and `pod install`
3. Run on Android and iOS
4. Play around with `animatedMovableCard` -`useAnimatedStyle`: `animatedStyle` with `transform` in `Card.js` file.

### Expected behavior

The same both for iOS and Android. 
Preferably IMO the way Android behaves is better and more consistent.

### Actual behavior

Android and iOS are working in a different manner while calculating `translationX` and `translationY` in `PanGestureHandler` while callback `onGestureEvent`.
Android always return `x` and `y` in relation to the wrapper axes ( When I swipe right only `translationX`  goes up)
On the other hand iOS's `translationX` and `translationY` are connected to the first `Animated.View` inside `PanGestureHandler`. That means if that <Animated.View> is rotated the returned by `GestureHandler` values can vary. 
In the given example, the `x` and `y` are switched because the card is rotated by 180 deg on `Y` axis.

This is also inconsistent and makes it impossible to write one code for two platforms (There is a workaround for iOS that you can make first <Animated.View> static (no rotation or anything), and animate <Animated.View> inside of that first <Animated.View>. It makes your axes static, but it is also confounding and you gotta know about the bug itself.

## Snack or minimal code example

Pls see `Steps To Reproduce` above 👆 (Sorry it's not minimal but I hope it's good enough)

## Package versions

- React: "16.13.1",
- React Native: "0.63.4",
- React Native Reanimated: "2.0.0",
- NodeJS: v12.13.0

**Comment by WoLewicki** [comment]
Can you check if the issue still occur in the newest versions of the libraries?

**Comment by wojtus7** [comment]
Issue no longer exist when using:
```    
"react-native-gesture-handler": "^2.2.0",
"react-native-reanimated": "^2.3.1",
```
Good job
