### ISSUE TITLE
TurboModuleRegistry.getEnforcing(...) - HELP!!!

### ISSUE THREAD

**Issue by aqilhex** [software-mansion/react-native-reanimated#1838]
## Description
I can't find any solution to fix this error caused by react-native-reanimated@2.0.0, Downgraded to v1.x.x , Clearing cache, Enabling jetifier did not help. Someone help me please, I need it to work with react-navigation/drawer.

- React: 17.0.1
- React Native: 0.64.0
- React Native Reanimated: 2.0.0
- NodeJS: v12.16.3

**Comment by mosoakinyemi** [comment]
I had this same issue for iOS, I solved it simply by:
1. Deleting the app on the simulator 
2. Running `npx react-native run-ios`

**Comment by 4yki** [comment]
Same for me with:
- React Native: 0.64.0
- React Native Reanimated: 2.0.0

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

**Comment by teamzz111** [comment]
Same here

 Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

**Comment by boonook** [comment]
Same for me with

remove @react-navigation/drawer  normal
use @react-navigation/drawer error

**Comment by melero2000** [comment]
Same issue for me:

- React Native: 0.64.0
- React Native Reanimated: 2.0.0
- react-navigation/drawer: 5.12.4

**Comment by jakub-gonet** [comment]
Duplicate of #1825.
