### ISSUE TITLE
Updating useAnimatedGestureHandler causes stutters

### ISSUE THREAD

**Issue by bobsmits** [software-mansion/react-native-reanimated#1841]
## Description
When useAnimatedGestureHandler is updated it can cause stutters in the animation. 

#### Long description:
We have a carousel with cards in our app. When rebuilding it from the default react animations and gestures to reanimated 2 we noticed stutters when swiping between the cards. We first thought it was because we were rendering new elements during the animations. We use the same implementation as the list view for rendering the next card. Witch relies on InteractionManager.runAfterInteractions, witch does not seem to care about reanimated animations. It took me two days to find out where the stutters finally came from. 

During the animation the some props of the card where updated causing useAnimatedGestureHandler to be updated. Supplying a memoize to the useAnimatedGestureHandler fixed the stutter.

Even in a new react app with minimal implementation updating useAnimatedGestureHandler causes stutters. If this is expected behaviour I think the docs should be updated with a warning that updating useAnimatedGestureHandler cause stutters in the animation.

### Screenshots
https://user-images.githubusercontent.com/20045348/111468530-f17d6a00-8725-11eb-9d94-56f29ccc92a7.mp4

## Steps To Reproduce
Update useAnimatedGestureHandler during animations, or run the supplied demo.

### Expected behavior
Updating useAnimatedGestureHandler does not cause stutters.

### Actual behavior
Updating useAnimatedGestureHandler causes stutters and frame drops.

## Snack or minimal code example
https://github.com/bobsmits/react-native-reanimated-2-hickup-demo

## Package versions

Latest versions of reanimated 2 and react.

**Comment by sibyl666** [comment]
I have the exact same problem. When I scroll on flatlist It stutters the same as in the video. Just changing reanimated stuff to react native animated solves the problem.

**Comment by Ubax** [comment]
@bobsmits Could you check if it still happens on 2.3.x?
