### ISSUE TITLE
 ERROR  Error: Requiring module "node_modules/@react-navigation/drawer/src/index.tsx", which threw an exception: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by iamamanprajapati** [software-mansion/react-native-reanimated#1849]
## Description
When I use React Navigation in my React Native then Error occurs

### Screenshots
 
![Screenshot from 2021-03-20 00-22-22](https://user-images.githubusercontent.com/49456931/111829729-14b93c80-8913-11eb-8833-6c7a9e8e5908.png)

## Package versions
"@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/material-bottom-tabs": "^5.3.14",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1"

- React:
- React Native:
- React Native Reanimated:
- NodeJS:

**Comment by gabrielmares** [comment]
same issue with react-native-reanimated, i downgrade to 1.13.2 and fixit
#https://github.com/software-mansion/react-native-reanimated/issues/1127#issuecomment-802309032

**Comment by iamamanprajapati** [comment]
@gabrielmares
It is not a permanent solution bro

**Comment by gabrielmares** [comment]
i hope, but it's only options that works for me, you will try with this https://github.com/software-mansion/react-native-reanimated/issues/1127#issuecomment-801668922

**Comment by BrendonSled** [comment]
what platform? ios or android? 

There are also lots of other issues logged like this. Typically the main culprits are 

- Babel plugin not installed
- Android clean never run
- Metro clean never run
- Outdated `AppDelegate.m`

**Comment by gabrielmares** [comment]
Android, when i tried to use @react-navigation/drawer@6.0.0-next.2 in my case

**Comment by mppvgithub** [comment]
> Android, when i tried to use @react-navigation/drawer@6.0.0-next.2 in my case

is this working??

**Comment by irohitb** [comment]
> i hope, but it's only options that works for me, you will try with this [#1127 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/1127#issuecomment-801668922)

That's not a valid solution tbh.

**Comment by piaskowyk** [comment]
It should be fixed by this PR: https://github.com/software-mansion/react-native-reanimated/pull/1845 We'll release today a new version with this fix.

**Comment by Elijah-trillionz** [comment]
still not fixed

**Comment by kodejuice** [comment]
still not fixed

**Comment by Raidro** [comment]
still not fixed

**Comment by Riowaldy** [comment]
still not fixed

**Comment by jenschr** [comment]
still not fixed
(easy solution: not use this module)
