### ISSUE TITLE
Cannot create array of refs using useAnimatedRef()

### ISSUE THREAD

**Issue by haibert** [software-mansion/react-native-reanimated#1855]
## Description
Cannot create an array of refs using useAnimatedRef. Below I have mentioned how one can create an array of refs using a traditional useRef but for some reason useAnimatedRef does not recognize arrays. Even when an empty array is placed inside such as const refArray = useAnimatedRef([]) one cannot use .push or any other array methods on the ref. This is a problem because there are times where we need to create arrays of refs. Is there a different approach to making an array of refs that I’m not aware of? I tried plenty of work arounds but none work. 

### Expected behavior
expected behavior if for useAnimatedRef to recognize the array inside of it

### Actual behavior
It does not recognize the array and the app crashes consequently. 

## Snack or minimal code example
code bellow does not work since the array is not recognized. 
   ` const refArray = useAnimatedRef([])
refArray.current.push(SOME_ITEM)
`

This is how one would create an array of refs using traditional useRef. This obviously does not work since there is no createRef equivalent for useAnimatedRef()
`const refArray = useRef([...Array()].map(() => createRef())) `

## Package versions

React: 16.13.1
React Native: 0.63.4
React Native Reanimated: 2.0.0-rc.0
NodeJS: 12.3.0

**Comment by mrousavy** [comment]
Why are you using an animated ref to store an array?

**Comment by haibert** [comment]
The reason I need an array of refs is because I have a list of images and I need the ref for each image to create the tap to expand animation from image origin. Also exiting the image shrinks the image down back to its origin on the screen. Just like how instagram works.

**Comment by haibert** [comment]
Here is the source code for the useAnimatedRef hook. I tried to compare it to the regular useRef source code but they did not look similar at all and I do not have the JS knowledge required to have any idea how to add this functionality. 

`   
  export function useAnimatedRef() {
  const tag = useSharedValue(-1);
  const ref = useRef(null);

  if (!ref.current) {
    const fun = function(component) {
      'worklet';
      // enters when ref is set by attaching to a component
      if (component) {
        tag.value = getTag(component);
        fun.current = component;
      }
      return tag.value;
    };

    Object.defineProperty(fun, 'current', {
      value: null,
      writable: true,
      enumerable: false,
    });
    ref.current = fun;
  }

  return ref.current;
}
`

**Comment by piaskowyk** [comment]
Hey @haibert
So I think that this is not a bug, but you should use it in another way. You need an array of `animationRef`, not `animationRef` contains an array. One `animationRef` can be connected with only one component because `animationRef` storing view tag from UI.
Let's try something like this:
```js
const refsArray = new Array(10).fill(useAnimationRef());
```
Let me know if you have any questions.

**Comment by haibert** [comment]
> ```js
> const refsArray = new Array(10).fill(useAnimationRef())
> ```

I need the exact equivalent of the following line `let imagesMeasures = useRef([...Array()].map(() => createRef()))` and the reason for this is that as i'm iterating through an array of images I am return a JSX component, these components are stacked  like a grid (much like instagram) and I need a ref of each one of them to make sure I know the location and measurements of each image, so I can animate the images from their original size to take over the entire screen and then to go back to their origin once the image is closed. (again much like instagram) This was possible with the built in animation API, but I don't think its possible to recreate this logic with the current useAniamtedRef() provided by reanimatedv2

**Comment by haibert** [comment]
`
<View style={styles.grid}>
                    {images.map((item, index) => {
                        const changingImageStyle =
                            index === activeIndex ? activeIndexStyle : undefined
                        return (
                            <TouchableWithoutFeedback
                                key={index}
                                onPress={() => handleOpenImage(index)}
                            >
                                <Image
                                    style={[
                                        styles.gridImage,
                                        changingImageStyle,
                                    ]}
                                    resizeMode="cover"
                                    source={item}
                                    onLayout={() => {}}
                                    ref={(image) =>
                                        (imagesMeasures.current[index] = image)
                                    }
                                />
                            </TouchableWithoutFeedback>
                        )
                    })}
                </View>`

incase you are wondering where and how the array of refs gets used.
