### ISSUE TITLE
Android app crashes instantly in release mode

### ISSUE THREAD

**Issue by Ahmad-Abdelhafez** [software-mansion/react-native-reanimated#1868]
## Description
Hello,

I installed reanimated v2 on my app.
and it crashes on Release mode after instantly after the splash screen.
the below are the logs 

Even though i am not enabling Proguard on my App!

### Expected behavior
Not crashing 
### Actual behavior & steps to reproduce
Just generate a release build then open the app.

## Snack or minimal code example
The below are the logs
> 03-24 22:47:06.382: E/AndroidRuntime(17328): FATAL EXCEPTION: create_react_context
03-24 22:47:06.382: E/AndroidRuntime(17328): Process: com.inspireui.mstorecommerce, PID: 17328
03-24 22:47:06.382: E/AndroidRuntime(17328): java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/turbomodule/core/CallInvokerHolderImpl;.<init>(Lcom/facebook/jni/HybridData;)V"
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder(Native Method)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder(Unknown Source:0)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.swmansion.reanimated.NativeProxy.<init>(Unknown Source:7)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.swmansion.reanimated.d.a(Unknown Source:2)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.swmansion.reanimated.e.getJSIModules(Unknown Source:12)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.facebook.react.m.a(Unknown Source:135)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.facebook.react.m.a(Unknown Source:0)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at com.facebook.react.m$5.run(Unknown Source:68)
03-24 22:47:06.382: E/AndroidRuntime(17328): 	at java.lang.Thread.run(Thread.java:919)
## Package versions

- React Native: 0.63.3
- React Native Reanimated: 2.0.0

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by tomekzaw** [comment]
@Ahmad-Abdelhafez Thank you for the report. Unfortunately I was not able to reproduce the issue on our Reanimated 2 Playground app.

```sh
git clone https://github.com/software-mansion-labs/reanimated-2-playground.git
cd reanimated-2-playground
yarn install
yarn react-native start
yarn react-native run-android
```

These are the exact commands I was using (from [this tutorial](https://www.instamobile.io/android-development/generate-react-native-release-build-android/)):

```sh
keytool -genkey -v -keystore your_key_name.keystore -alias your_key_alias -keyalg RSA -keysize 2048 -validity 10000
mv your_key_name.keystore ./android/app
```

I've added release signing config in `build.gradle`:
```gradle
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file('your_key_name.keystore')
            storePassword 'password'
            keyAlias 'your_key_alias'
            keyPassword 'password'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
```

```sh
react-native bundle --platform android --dev false \
  --entry-file index.js \
  --bundle-output android/app/src/main/assets/index.android.bundle \
  --assets-dest android/app/build/intermediates/res/merged/release/

cd android && ./gradlew assembleRelease
```

Actually, I was getting an `Error: Duplicate resources` on `:app:mergeReleaseResources` task. The solution was to remove the `raw` directory: 
```sh
rm -rf ./android/app/src/main/res/raw
```

Then I run `react-native bundle` and `./gradlew assembleRelease` again and it worked now.

Finally, I copied `android/app/build/outputs/apk/app-release.apk` onto a virtual device to install the APK (actually I needed to uninstall the old version of the app). When installed, the app successfully launches and works on my virtual device.

**Comment by Ahmad-Abdelhafez** [comment]
After enabling Progaurd and add the reanimated rule to the Proguard from the documentation, 
`-keep class com.facebook.react.turbomodule.** { *; }`

and the the app worked!

I find that weird that it is not working without enabling Progaurds!

**Comment by MuhammadRafeh** [comment]
@Ahmad-Abdelhafez  where to add this line?

**Comment by Darapsas** [comment]
@MuhammadRafeh append it to the `android/app/proguard-rules.pro` file

**Comment by agusvazquez** [comment]
Hello! I have experienced this same issue, perhaps we should update the docs?
