### ISSUE TITLE
useSharedValue Chinese string shows error

### ISSUE THREAD

**Issue by BooYeu** [software-mansion/react-native-reanimated#1873]
## Description

useSharedValue Chinese string shows error

### Expected behavior

show right chinese, not error code

### Actual behavior & steps to reproduce

When I get it , it shows error code not Chinese

## Snack or minimal code example

const chinese = useSharedValue('');
chinese.value="你好";

## Package versions

- React Native:0.64.0
- React Native Reanimated:2.0.1
- NodeJS:12.9.0
- Xcode:14.4
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS

**Comment by jakub-gonet** [comment]
Could you please attach a full reproduction example and a screenshot of the error?

**Comment by BooYeu** [comment]
I don't know how to use this component . I found this bug because of the other component's dependency . So I edit some codes from the other component.
The original code is here :https://github.com/enesozturk/react-native-hold-menu/blob/a46822b1b13e82e74e3fcee5b18daf231a31bd9e/src/components/menu/MenuList.tsx#L114
And the props "items" is [{text:'你好',onPress:()=>{}},{text:'你好',onPress:()=>{}}];

I write the simple code below just like the url code. Maybe it is wrong and I don't know how to write.
`
let myText='你好';
const prevText = useSharedValue('');

const setter = (items) => {
    console.warn(items)
    setItemList(items);
    prevText.value = items;
  };

  useAnimatedReaction(
    () => myText,
    _text=> {
      console.warn(_text)
      if (_text!== prevText.value) {
        runOnJS(setter)(_text);
      }
    },
    [myText]
  );`

console image:
![11616864759_ pic](https://user-images.githubusercontent.com/16587763/112728350-c97dda00-8f61-11eb-8b64-a0e893f89130.jpg)

the react-native-hold-menu shows:
![21616864765_ pic](https://user-images.githubusercontent.com/16587763/112728356-dbf81380-8f61-11eb-9287-ada37a5b6333.jpg)

**Comment by BooYeu** [comment]
When use Chinese in Shared Value. It shows error code:https://github.com/enesozturk/react-native-hold-menu/issues/10#issuecomment-808724563

**Comment by BooYeu** [comment]
the console:[{"onPress": [Function hostFunction], "text": "￯﾿ﾯ￯ﾾ﾿￯ﾾﾦ￯﾿ﾯ￯ﾾﾾ￯ﾾﾋ￯﾿ﾯ￯ﾾﾾ￯ﾾﾷ￯﾿ﾯ￯ﾾ﾿￯ﾾﾨ￯﾿ﾯ￯ﾾﾾ￯ﾾﾴ￯﾿ﾯ￯ﾾﾾ￯ﾾﾝ"}, {"onPress": [Function hostFunction], "text": "￯﾿ﾯ￯ﾾ﾿￯ﾾﾥ￯﾿ﾯ￯ﾾﾾ￯ﾾﾈ￯﾿ﾯ￯ﾾﾾ￯ﾾﾠ￯﾿ﾯ￯ﾾ﾿￯ﾾﾩ￯﾿ﾯ￯ﾾﾾ￯ﾾﾙ￯﾿ﾯ￯ﾾﾾ￯ﾾﾤ￯﾿ﾯ￯ﾾ﾿￯ﾾﾨ￯﾿ﾯ￯ﾾﾾ￯ﾾﾮ￯﾿ﾯ￯ﾾﾾ￯ﾾﾰ￯﾿ﾯ￯ﾾ﾿￯ﾾﾥ￯﾿ﾯ￯ﾾﾾ￯ﾾﾽ￯﾿ﾯ￯ﾾﾾ￯ﾾﾕ"}, {"onPress": [Function hostFunction], "text": "￯﾿ﾯ￯ﾾ﾿￯ﾾﾤ￯﾿ﾯ￯ﾾﾾ￯ﾾﾸ￯﾿ﾯ￯ﾾﾾ￯ﾾﾾ￯﾿ﾯ￯ﾾ﾿￯ﾾﾦ￯﾿ﾯ￯ﾾﾾ￯ﾾﾊ￯﾿ﾯ￯ﾾﾾ￯ﾾﾥ"}]

**Comment by jakub-gonet** [comment]
Could you check if you use the latest version of reanimated?
node_modules/react-native-hold-menu/node_modules shouldn't contain Reanimated at all. You can also check yarn.lock to see if it was resolved correctly.

**Comment by BooYeu** [comment]
My reanimated is latest.
It doesn't have a folder node_modules in it .It's catalog is:
![2709e9976c0cbd1dd83314465a7b3db](https://user-images.githubusercontent.com/16587763/112860439-66698000-90e6-11eb-9a3f-5274f2f808ce.jpg)
And it's package.json is:
`
{
  "name": "react-native-reanimated",
  "version": "2.0.1",
  "description": "More powerful alternative to Animated library for React Native.",
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "yarn run format && yarn run lint-check && yarn run test:unit",
    "test:unit": "jest",
    "format": "prettier --write --list-different './src/**/*.js'",
    "lint-check": "eslint --ext '.js,.ts,.tsx' src/ && yarn prettier --check src/",
    "release": "npm login && release-it",
    "type:check": "yarn tsc"
  },
  "main": "src/Animated.js",
  "module": "lib/module/Animated",
  "react-native": "src/Animated",
  "source": "src/Animated",
  "types": "react-native-reanimated.d.ts",
  "files": [
    "Common/",
    "src/",
    "lib/",
    "android/src/main/AndroidManifest.xml",
    "android/src/main/java/",
    "android/build.gradle",
    "android/",
    "ios/",
    "!ios/build/",
    "RNReanimated.podspec",
    "README.md",
    "react-native-reanimated.d.ts",
    "mock.js",
    "plugin.js",
    "!__snapshots__",
    "!*.test.js",
    "!*.test.js.map"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/software-mansion/react-native-reanimated.git"
  },
  "author": {
    "email": "krzys.magiera@gmail.com",
    "name": "Krzysztof Magiera"
  },
  "license": "MIT",
  "readmeFilename": "README.md",
  "bugs": {
    "url": "https://github.com/software-mansion/react-native-reanimated/issues"
  },
  "homepage": "https://github.com/software-mansion/react-native-reanimated#readme",
  "dependencies": {
    "@babel/plugin-transform-object-assign": "^7.10.4",
    "fbjs": "^3.0.0",
    "mockdate": "^3.0.2",
    "string-hash-64": "^1.0.3"
  },
  "peerDependencies": {
    "react": "*",
    "react-native": "*",
    "react-native-gesture-handler": "*"
  },
  "devDependencies": {
    "@babel/core": "^7.7.5",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@babel/preset-env": "^7.7.6",
    "@babel/preset-typescript": "^7.7.4",
    "@react-native-community/bob": "^0.14.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "@testing-library/jest-native": "^3.4.3",
    "@testing-library/react-hooks": "^5.0.3",
    "@testing-library/react-native": "^7.1.0",
    "@types/babel-types": "^7.0.9",
    "@types/babel__core": "^7.1.12",
    "@types/babel__generator": "^7.6.2",
    "@types/babel__traverse": "^7.0.15",
    "@types/jest": "^26.0.15",
    "@types/react-native": "^0.63.50",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.4.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-import-resolver-babel-module": "^5.2.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "husky": "^4.2.5",
    "jest": "^24.9.0",
    "lint-staged": "^10.2.11",
    "prettier": "^2.2.1",
    "react": "17.0.1",
    "react-native": "^0.63.4",
    "react-native-gesture-handler": "^1.6.1",
    "react-test-renderer": "17.0.1",
    "release-it": "^13.1.1",
    "typescript": "^4.1.3"
  },
  "lint-staged": {
    "*.js": [
      "eslint --ext '.js,.ts,.tsx' src/",
      "prettier --write"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "release-it": {
    "hooks": {
      "before:git:bump": [
        "# check if version corresponds to changes in native files  \n  if git diff --name-only ${latestVersion} HEAD | egrep '(android/.*)|(ios/.*)' -q ; then egrep '\\.0$' -q <<< ${version} ; else true ; fi ;"
      ]
    }
  },
  "@react-native-community/bob": {
    "source": "src",
    "output": "lib",
    "targets": [
      "commonjs",
      "module"
    ]
  }
}

Look forward to your reply.Thank you very much!
`

**Comment by BooYeu** [comment]
2.1.0 is ok
