### ISSUE TITLE
 includes fields as function type to a component Error

### ISSUE THREAD

**Issue by BooYeu** [software-mansion/react-native-reanimated#1874]
## Description
onPress run error

### Expected behavior

https://github.com/software-mansion/react-native-reanimated/pull/1844 , It seems not update in 2.0.1?

### Actual behavior & steps to reproduce

https://github.com/software-mansion/react-native-reanimated/issues/1758

## Snack or minimal code example

https://github.com/software-mansion/react-native-reanimated/issues/1758

## Package versions

- React Native:0.64.9
- React Native Reanimated:2.0.1
- NodeJS:14.6
- Xcode:-
- Java & Gradle:-

## Affected platforms

- [ ] Android
- [ ] iOS

**Comment by piaskowyk** [comment]
Yes, 2.0.1 doesn't fully release. It contains just a single patch for `react-native-navigation`. We'll release a new version with all fixed issues since 2.0.0 soon.
