### ISSUE TITLE
App with Reanimated loads bundle and executes JavaScript twice

### ISSUE THREAD

**Issue by mogery** [software-mansion/react-native-reanimated#1905]
## Description
When using Reanimated, the app will start loading and executing the bundle twice. This also occurs in Release. This only happens on Android.

### Expected behavior
The app will only load once.

### Actual behavior & steps to reproduce
The app will start loading twice, causing race conditions and etc.

1. Create an app
2. Get something animating on the screen
3. Build in debug for android, run
4. Reload the app (do it multiple times if it doesn't happen for the first time, also: on an app i'm working on, this has gotten so extreme that all i need to do is exit the app and restart it, and this starts happening.)
5. Observe the bundle being loaded twice from the bundler

## Snack or minimal code example
[See this repo with an example app showing the behaviour.](https://github.com/mogery/rnr-double-load-repro)

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0
- NodeJS: 12.22.0
- Xcode: N/A
- Java & Gradle: 11.0.10 & 6.7

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey, I tried to reproduce your issue but without success :/

https://user-images.githubusercontent.com/36106620/151572192-830267aa-e596-49e6-b1fe-b663a48043dc.mov

**Comment by piaskowyk** [comment]
I recommend updating Reaniamted and the others dependencies. If you have more question feel free to ask me.
