### ISSUE TITLE
Animated FlatList created with Animated.createAnimatedComponent lag with onScroll

### ISSUE THREAD

**Issue by fbeccaceci** [software-mansion/react-native-reanimated#1906]
## Description
https://user-images.githubusercontent.com/32967519/113504388-12bcc380-9538-11eb-8b4a-7db91e9e993a.MP4

I'm using an animated flatlist created using Animated.createAnimatedComponent, the problem is that on ios the onScroll event is not smooth at all, in the example i'm applying a transformation on the y axis based on the scroll value of the onScroll event, and as you can see the animation is not smooth

### Expected behavior

The animation is smooth 

### Actual behavior & steps to reproduce

The animation lags

## Snack or minimal code example

https://github.com/fbeccaceci/reanimated-2-flatlist

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.1.0
- NodeJS: v15.11.0
- Xcode: 12.4 
- Java & Gradle: openjdk 11.0.10 Gradle 6.8.3

## Affected platforms
- [ ] iOS

**Comment by piaskowyk** [comment]
Hey @fbeccaceci, Generally this is not a bug. You should set shared value in another way because you don't use animation now.
Currently, you have:
```js
const onScroll = useAnimatedScrollHandler({
  onScroll: (evt, _) => {
    scrollValue.value = evt.contentOffset.x;
  },
});
```
So you set a new position in every event, but the event is happened rather than 60 times per second - that's why this is sharp change.
You should use something like this:
```js
const onScroll = useAnimatedScrollHandler({
  onScroll: (evt, _) => {
    scrollValue.value = withTiming(evt.contentOffset.x, { duration: 100 });
  },
});
```
In this way, I use animation to change the shared value and the position change is smooth like here:

https://user-images.githubusercontent.com/36106620/113894259-1e261e00-97c8-11eb-8e42-b677a828dd2f.mov

**Comment by Abbaskatariya** [comment]
I'm using an animated flatlist created using Animated.createAnimatedComponent, the problem is that on android and ios the onScroll event is not smooth


Expected behavior
The animation is smooth

Actual behavior & steps to reproduce
The animation lags

  const updateScrollYTrans = useCallback((value: number) => {
        'worklet'
        scrollY.value = Math.max(value, 0)
    }, [scrollY])

    const updateShareValue = useCallback((value: number) => {
        'worklet'
        if (curIndexValue.value !== index) return
        //Avoid causing updates to the ShareAnimatedValue after the drop-down has finished
        if (isRefreshing.value !== isRefreshingWithAnimation.value) return;
        shareAnimatedValue.value = value
    }, [curIndexValue.value, shareAnimatedValue, index, isRefreshing.value, isRefreshingWithAnimation.value])

    const tryToSnap = useCallback(() => {
        'worklet'
        if (!enableSnap) return;
        cancelAnimation(isScrolling)
        if (canSnapFunc()) {
            isScrolling.value = 1
            isScrolling.value = withTiming(0, { duration: scrollingCheckDuration }, (isFinished) => {

                if (isFinished && canSnapFunc()) {
                    needSnap.value = false
                    snapAfterGlideOver({
                        sceneRef: _scrollView,
                        shareAnimatedValue,
                        headerHeight,
                        frozeTop
                    })
                }
            })
        }
    }, [isScrolling.value, _scrollView, needSnap, shareAnimatedValue, headerHeight, frozeTop, enableSnap, scrollingCheckDuration])

    const onScrollAnimateEvent = useAnimatedScrollHandler(
        {
            onScroll: (event, ctx) => {
                realY.value = event.contentOffset.y
                let moveY = Math.max(event.contentOffset.y, 0)

                if (isRefreshingWithAnimation.value || isRefreshing.value) return
                tryToSnap()
                moveY = isRefreshing.value && isRefreshingWithAnimation.value ? moveY + refreshHeight : moveY
                updateScrollYTrans(moveY)
                updateShareValue(moveY)
            },
            onMomentumBegin: () => {
                isLosingMomentum.value = true
            },
            onMomentumEnd: () => {
                isLosingMomentum.value = false
            }
        }, [curIndexValue, updateShareValue, updateScrollYTrans, isRefreshingWithAnimation, tryToSnap]
    )
