### ISSUE TITLE
animate svg fill color

### ISSUE THREAD

**Issue by Stevemoretz** [software-mansion/react-native-reanimated#1909]
## Description
fill color doesn't get animated!

When the color changes in animation nothing happens.
### Expected behavior
The color should be animated.
### Actual behavior & steps to reproduce
```js
    const animatedProps = useAnimatedProps(()=>{
        const fill = progress.value ? colorNumber2hex(interpolateColor(progress.value,
            [0,1],
            ['rgba(255,255,255,1)','rgba(0,148,68,1)'],
            'RGB')) : 'white'
        console.log(fill);
        return {d : d,fill : fill};
    });
```
I log fill and I get colors :

```
#acdcc2
#95d2b1
#6ac192
#54b782
#2fa866
#1da059
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#009444
#29a562
#3dae71
#66bf8f
#7dc9a0
#b8e1cb
#daf0e4
#f8fcfa
#ffffff
```
## Package versions

- React Native: expo sdk 40.0.1

## Affected platforms

- [x] iOS

**Comment by Stevemoretz** [comment]
Fixed it with using rgb 😐

```js
return {d : d,fill : hex2RgbA(fill)};
```

**Comment by Stevemoretz** [comment]
Actually let it be open maybe it's a bug?
Or it's supposed to take only rgb and not hex?

**Comment by Daavidaviid** [comment]
I'm having a similar issue. `interpolateColor` returns -1 and other negative values on Android and it's causing issues and I get error messages like `"-14935012" is not a valid color or brush`

**Comment by mlecoq** [comment]
I have a similar issue with `marker`

```
  const rectangleAnimatedProps = useAnimatedProps(() => {
    return {
      ...(currentItem.value?.type === "rectangle"
        ? currentItem.value.data
        : { x: 0, y: 0, width: 0, height: 0 }),
      stroke: currentItem.value?.type === "rectangle" ? "rgb(0,0,0)" : "none",
      fill: "none",
      strokeWidth: 2,
      marker:
        currentItem.value?.type === "rectangle" ? "url(#selection)" : undefined,
    };
  });
```

With a dynamic marker I want to make visible selected svg

I have also noticed that this way to do it does not work at all (no properties are updated)
```
const rectangleAnimatedPropsBis = useAnimatedProps(() => {
    return currentItem.value?.type === "rectangle"
      ? {
          ...currentItem.value.data,
          stroke: "rgb(0,0,0)",
          fill: "none",
          strokeWidth: 2,
          marker: "url(#selection)",
        }
      : {};
  });
```

**Comment by mlecoq** [comment]
I also have issue on `stroke` if I use hsl color like `hsl(156, 100%, 50%)`, after conversion to rgb colors it works fine

**Comment by hmust92** [comment]
Bump, running into the same issue. Will try @Stevemoretz solution.

**Comment by hmust92** [comment]
Bump! I am running into the same issue.

> Fixed it with using rgb 😐
> 
> ```js
> return {d : d,fill : hex2RgbA(fill)};
> ```

I can only get the fill to animate on the Path (not on SVG) using rgb colors.

It animates the fill correctly on an AnimatedPath using rgb colors.
It doesn't animate the fill at all on an AnimatedSvg using any type of color.

**Comment by grean** [comment]
if i use a color named like this ('red', 'blue', etc..) for stroke prop on a Path, it doesn't work when the animation has to change the value but it works for the beginning of the animation.
Replace rgb(0,0,255) instead of blue for example, it's working..
I don't understand.

**Comment by Stevemoretz** [comment]
> if i use a color named like this ('red', 'blue', etc..) for stroke prop on a Path, it doesn't work when the animation has to change the value but it works for the beginning of the animation.
> Replace rgb(0,0,255) instead of blue for example, it's working..
> I don't understand.

Yeah that's why I kept this issue open, it has some limitation as it seems you're supposed to use hex in a lot of places and for this specific case you should use rgb.

All can be done with a bunch of functions you can easily convert hex to rgba and also you can use a library which converts the 'red' , 'blue' , ... to rgba or to hex then to rgba.

**Comment by declanelcocks** [comment]
Also ran into this issue. Use case:

I have two `LinearGradient`'s with `Stop` components to define two gradients which works the standard way with `fill={url(#gradient)}` on the `Path` component. However, after turning it into an `AnimatedPath` to try switching between two gradient URLs, I'm not able to update the gradient using Reanimated.

It's a bit crappy because I'm actually not sure how you can achieve that with Reanimated. The Path that uses the gradient is an `AnimatedPath` as the `d` property animates, but there's no way to animate the `stopColor` on a `Stop` component via Reanimated, and trying to perform the update via `useState` or any other React method negatively affects the performance.

**Comment by kacperkapusciak** [comment]
Hi @Stevemoretz, @mlecoq, @grean 

It seems like https://github.com/software-mansion/react-native-reanimated/pull/2776 could resolve this issue. Could you confirm that?

Changes from this PR will be released in the next version of `react-native-reanimated`.

**Comment by mlecoq** [comment]
I have tried with example app in https://github.com/ArchireportTeam/react-native-svg-draw but I have an issue with 2.3.1 (and last available build of reanimated) 
 

First this error 

```
Process: com.example.reactnativesvgdraw, PID: 7803
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.facebook.react.bridge.JavaOnlyArray.getDouble(JavaOnlyArray.java:91)
	at com.horcrux.svg.RenderableView.setupPaint(RenderableView.java:485)
	at com.horcrux.svg.RenderableView.setupFillPaint(RenderableView.java:435)
```

and even if I patch this issue (received color is [0.0]) with the following code 

```
    if(colors.size >= 4){
                    // solid color
                    paint.setARGB(
                            (int) (colors.size() > 4 ? colors.getDouble(4) * opacity * 255 : opacity * 255),
                            (int) (colors.getDouble(1) * 255),
                            (int) (colors.getDouble(2) * 255),
                            (int) (colors.getDouble(3) * 255));
                    } else {
                        paint.setARGB(opacity * 255, 0, 0, 0);
                    }
```

 I have then this error 

```
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: java.lang.AssertionError: Illegal type provided
  at void com.swmansion.reanimated.AndroidErrorHandler.raise(java.lang.String) (AndroidErrorHandler.java:6)
  at void com.swmansion.reanimated.Scheduler.triggerUI() (Scheduler.java:-2)
  at void com.swmansion.reanimated.Scheduler$1.run() (Scheduler.java:24)
  at void com.swmansion.reanimated.Scheduler$2.runGuarded() (Scheduler.java:43)
  at void com.facebook.react.bridge.GuardedRunnable.run() (GuardedRunnable.java:31)
  at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:883)
```

**Comment by mlecoq** [comment]
@kacperkapusciak I have tried latest build on iOS (didn't manage to use it on android, I have this issue : ```* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86_64/libreactnativejni.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake```) 


If I try to draw this line on iOS 

```
export default function App() {
  const lineAnimatedProps = useAnimatedProps(() => {
    return {
      x1: 50,
      y1: 50,
      x2: 200,
      y2: 200,
      stroke: "hsl(0, 100%, 50%)",
      strokeWidth: 10,
      markerEnd: "url(#arrowhead)",
    };
  }, []);

  return (
    <View style={styles.container}>
      <Svg style={{ flex: 1 }}>
        <AnimatedLine animatedProps={lineAnimatedProps} />
      </Svg>
    </View>


  );
}
```

instead of having a red line, I have a green one 

<img src="https://user-images.githubusercontent.com/3649784/151572656-3661b6cd-9cb6-4736-8a22-c218a9929f48.png" width="150px"/>

**Comment by paulocf92** [comment]
Hex colors are not working for `fill` with `useAnimatedProps`, only rgb. My versions are as follows:
```"react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-reanimated": "^2.8.0",
    "react-native-svg": "^12.3.0"
```

I'm using a Circle, animated with reanimated.

**Comment by sanduluca** [comment]
rgb colors also not working(on android). The app just crashes

**Comment by Daavidaviid** [comment]
> rgb colors also not working(on android). The app just crashes

It's sad it happens :/ We had to remove all usage of this lib in our app because of things like that, we had a lot of crash in production

**Comment by 256hz** [comment]
I was able to animate the fill/stroke color with the `color` style key (which is unique to react-native-svg).  Assuming you have an SVG component all set up as a Reanimated component:

1. find the color you want to change in the .svg, set it to "currentColor" (`fill="currentColor"`})
2. create an animated style in the component with the key `color`:
   ```
   const colorChange = useAnimatedStyle(() => ({
     color: interpolateColor(progress.value, [0, 1], ['red', 'blue']),
   }));
   ```
3. pass to the style prop (<YourSvg style={colorChange} ... />)

**Comment by Latropos** [comment]
Closing, since this issue should be already fixed

**Comment by githistory** [comment]
2024 into 2025, issue still exists

**Comment by MoOx** [comment]
> I was able to animate the fill/stroke color with the `color` style key (which is unique to react-native-svg). Assuming you have an SVG component all set up as a Reanimated component:
> 
> 1. find the color you want to animate in the .svg, set it to "currentColor" (`fill="currentColor"`})
> 2. create an animated style with the key `color`:
>    ```js
>    const colorChange = useAnimatedStyle(() => ({
>      color: interpolateColor(progress.value, [0, 1], ['red', 'blue']),
>    }));
>    ```
> 3. pass to the style prop (`<YourSvg style={colorChange} ... />`)

This should definitely be in the documentation somewhere !

**Comment by lorenzocelli** [comment]
In my case the issue was fixed by enabling the feature flag `EXPERIMENTAL_CSS_ANIMATIONS_FOR_SVG_COMPONENTS`:
https://docs.swmansion.com/react-native-reanimated/docs/guides/feature-flags/#experimental_css_animations_for_svg_components
