### ISSUE TITLE
Error when the animation engine is switched to V8

### ISSUE THREAD

**Issue by hanhailong** [software-mansion/react-native-reanimated#1915]
## Description

Error when the animation engine is switched to V8

![image](https://user-images.githubusercontent.com/4241807/113821918-50775180-97af-11eb-9f6b-67ebd531d086.png)
![image](https://user-images.githubusercontent.com/4241807/113821936-5705c900-97af-11eb-849e-0f682aaa0fc4.png)

### Expected behavior

App should not error

### Actual behavior & steps to reproduce

The animation engine switch to V8 is wrong

## Snack or minimal code example

![image](https://user-images.githubusercontent.com/4241807/113822260-caa7d600-97af-11eb-8d04-4e7e03794458.png)

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0
- NodeJS: 14.5.0
- Xcode:  NA
- Java & Gradle:  1.8 & 6.7

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by jakub-gonet** [comment]
At the moment we only support JSC & Hermes. We may support V8 in the future but we need to discuss this internally. We'll post any updates about that in https://github.com/software-mansion/react-native-reanimated/discussions/1897.
