### ISSUE TITLE
Jest error Invariant Violation: Native module cannot be null 2.1.0

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#1916]
## Description
When running tests with the **2.1.0** version, the following error is raised.

```
  ● Test suite failed to run

    Invariant Violation: Native module cannot be null.

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:49:7)
      at Object.<anonymous> (node_modules/react-native-reanimated/lib/ReanimatedEventEmitter.js:4:16)
      at Object.<anonymous> (node_modules/react-native-reanimated/lib/createAnimatedComponent.js:3:1)
```
Downgrading to **2.0.0** does not raise an error

### Expected behavior

No error raised

### Actual behavior & steps to reproduce

Run jest with 2.1.0 version

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.1.0
- NodeJS: v14.8.0
- Xcode: NA
- Java & Gradle: NA

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey @Andarius 
You should change the path to `setUpJestTest()` function in your jest-setup.js file to:
```
require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
```
We changed the location of this file during the codebase migration to TS, and we forgot to update documentation.

**Comment by Andarius** [comment]
Thanks @piaskowyk  for the quick answer! It works again now.

**Comment by Daavidaviid** [comment]
Am i the only one getting this message :
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory 
```

After adding reanimated 2 to my jest setup file ?
