### ISSUE TITLE
Crash on React Native 0.59.3

### ISSUE THREAD

**Issue by MarianneAK** [software-mansion/react-native-reanimated#1918]
I've followed the documentation on how to install react-native-reanimated, but I'm getting the following error : 

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'react-native-reanimated-59.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform

I've looked in the node_modules folder of the library, there is no file with the name of  'react-native-reanimated-59.aar' .
I'm using React Native  version 0.59.3

**Comment by piaskowyk** [comment]
Hey @MarianneAK, In Reanimated v2, We officially support just `react-native` `0.62`, `0.63`, and `0.64`. Even if we use other `aar` file for react-native 0.59, I am not sure that will work, but I'll try to check it.
