### ISSUE TITLE
Reanimated 2.1.0 makes the Hermes Debugger in Flipper crash

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#1923]
## Description

Been troubleshooting an issue with the app crashing when using the Hermes Debugger:

https://github.com/facebook/hermes/issues/491

I noticed in the device logs a warning about `libjsc.so` not being found, but since I was using Hermes that error didn't make much sense. (a similar error report is here: https://github.com/facebook/react-native/issues/25537)

I noticed 2.1.0 added support for JSC. So I reverted to 2.0.1 to see if the warning above was produced by reanimated.

Reverting to 2.0.1 got rid of the `libjsc.so` warning, and the Hermes Debugger no longer crashes.

### Expected behavior

Hermes Debugger should not crash.

### Actual behavior & steps to reproduce

Hermes Debugger crashes with RN 0.64 and reanimated 2.1.0 on an Android real device.

A native stack trace can be found in: https://github.com/facebook/hermes/issues/491

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.1.0

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by mutablestudio** [comment]
I'm also dealing with this now and can't get a local AS build to run without crashing. I setup a pure RN sample project and added reanimated2 plus hermes 0.7.2, plus some of the standard node_modules. I added rea2 imports to the home screen and rendered an `Animated.View`. The app will run without any crash (just loading one home screen) on same device that crashes with my own RN app w rea2 (Pixel 3, Anrdoid 11). Sample app is using RN 64.0.

So not sure that this is a rea2 issue, but def seems to be Hermes related. Rolling back now to older Hermes versions to see if that helps.

**Comment by andreialecu** [comment]
I mentioned in the initial post that Reanimated 2.0.1 works. This is related to #1842

**Comment by piaskowyk** [comment]
I know the reason and working on a solution.

**Comment by rplankenhorn** [comment]
@piaskowyk Any update on this?

**Comment by oleksandr-dziuban** [comment]
Also waiting this fix, thanks a lot...

**Comment by piaskowyk** [comment]
Hey, It will be fixed by: https://github.com/software-mansion/react-native-reanimated/pull/2047 We want to release a new version tomorrow.

**Comment by MaxToyberman** [comment]
Hi ! 
@piaskowyk flipper works, but changing to debug in developer menu crashes the app.

**Comment by jameskennethrobinson** [comment]
@MaxToyberman this is also happening for me. did you find a workaround for opening up the debug menu?

**Comment by terrysahaidak** [comment]
Hey, @MaxToyberman, could you please open a new issue with all the details? I will help us to track and fix it.

**Comment by andreialecu** [comment]
FWIW the debug menu (Chrome debugging) will not work because of React Native's Turbo Modules. It's not Reanimated's fault. 

See:
https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-813684618

Only flipper can be used when Turbo Modules are enabled, and Reanimated uses them.

**Comment by Echelpoel** [comment]
@andreialecu looks like Chrome debugging support has been added in [2.3.0-alpha.2](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.3.0-alpha.2)?
