### ISSUE TITLE
Update state causes the screen to flicker 

### ISSUE THREAD

**Issue by hwhh** [software-mansion/react-native-reanimated#1926]
## Description

I am trying to make a "card stack" animated component, and I discovered that when I update state from within a worklet (within the "useAnimatedGestureHandler" hook) the screen flashes white (code and gif below). I am not sure if this is a bug or if I am doing something wrong but it does seem strange that this happens.

```
withTiming(1, {duration: SWIPE_ANIM_DURATION}, () => {
                'worklet';
                runOnJS(setCurrentIndex)(currIndex == data.length - 1 ? 0 :  currIndex + 1);
}) 
```

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/17745809/114267625-bdc7f400-99f4-11eb-8106-4cb031c9274a.gif)

I have also tried using "useDerivedValue" as well as "useAnimatedProps" and when I do the screen does not re-render and the result is as follows:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17745809/114267594-848f8400-99f4-11eb-8cf5-7716ff28edb1.gif)

### Expected behavior

Rerendering shouldn't cause the screen to flicker in this manner

## Snack or minimal code example

Full Code: https://snack.expo.io/@hhargreaves/tenacious-carrot

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0
- React Native Gesture Handler: 1.10.3
## Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey @hwhh 
I tested this a little and I suppose that the problem may be with this code:
```js
viewStackedAnim.value = withSequence(
  withTiming(1, {duration: SWIPE_ANIM_DURATION}, () => {
    'worklet';
    runOnJS(setCurrentIndex)(currIndex.value);
  }),
  withTiming(0, {duration: 0}),
);
```
It can be a reason for flicker. `runOnJS(setCurrentIndex)(currIndex.value)` call render of component with `viewStackedAnim.value = 1` and next you instantly try to set `viewStackedAnim.value` to `0` and all rest of animation is depended by this shared value. It is your intentional logic?

**Comment by hwhh** [comment]
Hi @piaskowyk , 

This is the intended logic, but I have now decided to do it a different way so this is no longer relevant. Closing out for now.

**Comment by sebaferreras** [comment]
@hwhh I'm having a similar issue... Is there any advice/suggestion that you would like to share?

It'd be super useful to know how did you solve the issue :)

**Comment by vinz-mehra** [comment]
I also have a similar issue
