### ISSUE TITLE
Cannot read property 'findHostInstance_DEPRECATED' of undefined

### ISSUE THREAD

**Issue by batical** [software-mansion/react-native-reanimated#1927]
## Description

I upgrade from version 2.0.1 to 2.1.0 and got red screen with this message when launching the app
TypeError: Cannot read property 'findHostInstance_DEPRECATED' of undefined

### Expected behavior
Display the content off app
Start the app.

### Actual behavior & steps to reproduce
Error seems to come from navigation drawer. but was working on 2.0.1
<img width="555" alt="Capture d’écran 2021-04-10 à 19 53 35" src="https://user-images.githubusercontent.com/7248073/114279776-9a259d80-9a36-11eb-833b-7d3df95759de.png">

## Package versions

- React Native: 0.64
- React Native Reanimated:2.1.0
- NodeJS:v12.10.0
- Xcode: 12.4
- Java & Gradle: did not try on android right now

## Affected platforms

- [ ] Android
- [x] iOS

**Comment by jakub-gonet** [comment]
1. Try removing all caches (node_modules, XCode cache, pods cache, etc)
2. Make sure you ran `pod install` after the update
3. Please show us an output of those commands:
	```bash
	grep -C 5 'function findHostInstance_DEPRECATED' node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-dev.js;
	cat node_modules/react-native/Libraries/Renderer/shims/ReactNative.js
	```

**Comment by batical** [comment]
I still have the issue. after doing the following

Clean all with 
- watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-*  && yarn cache clean && rm -Rf ./node_modules
- remove folder pods and podfile.lock (which I may have forgot when I tried)
- clean Xcode, remove all archive, derived data
- pod reintegrate, remove pods folder, podfile


here is the content of the command

```
  };
}

var ReactCurrentOwner$3 = ReactSharedInternals.ReactCurrentOwner;

function findHostInstance_DEPRECATED(componentOrHandle) {
  {
    var owner = ReactCurrentOwner$3.current;

    if (owner !== null && owner.stateNode !== null) {
      if (!owner.stateNode._warnedAboutRefsInRender) {

```

I tried some strange thing after 
- revert to version "2.0.1" in package.json
- yarn  (without cleaning nothing)

WITHOUT doing a pod update or install,  I managed to make it working and use one reanimated v2 animation :p 

- After that I clean , pod install , build with the correct version and it is also working

**Comment by jakub-gonet** [comment]
To sum it up - when you base on 2.0.1 it's working but after a clean install of 2.1.0 it throws this error in JS?

Are you able to provide a reproduction repo?

**Comment by batical** [comment]
Yes that's a summary. Even If I cheat using 2.1.0 native code with 2.0.1 js code :)

We are using a Monorepo (only yarn, without lerna or other tools)
I cannot provide the repo I am working on(company). Not sure I will find extra extra hours to create a new reproductible one.

I will try on a fresh clean new Mac next week

**Comment by batical** [comment]
@jakub-gonet after multiple try etc. I managed to find the reason.

In my metro.config.js I had
babelTransformerPath: require.resolve('react-native-typescript-transformer')
 
I don't remember the reason it is present and if we still need it.  but without, it is working in my project

**Comment by jakub-gonet** [comment]
That's strange. RN's default babel config is adapted to compile TS files so using this transformer shouldn't be needed. Do you have heavily customized babel/metro config?

**Comment by batical** [comment]
here is the metro.config (watch folder is for workspace)


```

const path = require('path')
module.exports = {
  watchFolders: [__dirname, path.resolve(__dirname, '../../')],
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true
      }
    })
    //babelTransformerPath: require.resolve('react-native-typescript-transformer')
  }
}
```

and the babel

```
module.exports = {
  presets: [
    [
      'module:metro-react-native-babel-preset',

    ]
  ],
  plugins: [
    ['@babel/plugin-external-helpers'],
    ['@babel/plugin-proposal-decorators', { legacy: true }],

    [
      'babel-plugin-module-resolver',
      {
        extensions: ['.ts', '.tsx', '.js', '.ios.js', '.android.js', '.ios.tsx', '.android.tsx', '.ios.ts', '.android.ts'],
        alias: {
          '@assets': './src/assets',
          '@design': './src/design',
          '@navigation': './src/navigation',
          '@containers': './src/containers',
          '@components': './src/components',
          '@hooks': './src/hooks',
          '@store': './src/store',
          '@services': './src/data/services',
          '@themes': './src/themes',
          '@utils': './src/utils'
        }
      }
    ], ['react-native-reanimated/plugin']
  ],
  env: {
    prod: {
      plugins: ['transform-remove-console']
    },
    production: {
      plugins: ['transform-remove-console']
    }
  }
}

```

**Comment by jakub-gonet** [comment]
You said that you removed metro caches. Have you tried running metro with --reset-cache flag? Between those two versions we also partially migrated to TS, could you share your tsconfig with us as well? Maybe tsc processes (or not processes but they should be, not sure here) reanimated's files.

**Comment by batical** [comment]
I have a  clean command that remove all node_mdules in all workspace etc
and doing also

`watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-*  && yarn cache clean `

I will provide the tsconfig there is in the folder mobile if it can help you. 

```
{
  "compilerOptions": {
    "noEmit": true,
    "target": "ES2019",
    "allowJs": true,
    "module": "commonjs",
    "allowSyntheticDefaultImports": true,
    "lib": ["es6", "dom"],
    "jsx": "react",
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": false,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "esModuleInterop": true,
    "strict": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "baseUrl": "./",
    "rootDirs": ["src"],
    "typeRoots": ["node_modules/@types", "../../node_modules/@types", "../types/dist"]
  },
  "composite": true,
  "include": ["src/**/*", "index.d.ts"],
  "exclude": [
    ...
  ]
}
```

**Comment by piaskowyk** [comment]
Could you try to use the latest version of Reanimated 2.3.1?

**Comment by nitish24p** [comment]
I am trying to run this with the following configs
**React Native: "0.63.5",
React native reanimated: "2.4.0",**

**babelrc**
```json
{
    "presets": ["module:metro-react-native-babel-preset"],
    "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "react-native-reanimated/plugin"
    ]
}
```

custom metro config
```javascript
const blacklist = require('metro-config/src/defaults/blacklist')

module.exports = {
  resolver: {
    blacklistRE: blacklist([
      /node_modules\/.*\/node_modules\/react-native\/.*/,
    ]),
  },
  transformer: {
    babelTransformerPath: require.resolve(
      "react-native-typescript-transformer"
    ),
  },
};
```

Im still getting this issue, i cleared node modules and reran npm install. but im still getting the same issue.

**Comment by chj-damon** [comment]
this issue happens again in react-native@0.72.3 and react-native-reanimated@3.4.0
you can try this repo to reproduce it: [https://github.com/thundersdata-frontend/rn-template/tree/newArc-repo](https://github.com/thundersdata-frontend/rn-template/tree/newArc-repo)

**Comment by wezter96** [comment]
@piaskowyk It seems like this issue still occurs, we are getting it with the following.
Should I open a new issue for this or should we reopen this one? 😄 
“expo”: “49.0.13",
“react-native”: “0.72.5",
“react-native-reanimated”: “3.5.4",

**Comment by danielrhodes** [comment]
Also seeing this. Same versions as above.

**Comment by JasonAtallah** [comment]
Is there any update on this? I'm seeing the same issues with 
```
"react-native": "0.77.0",
"react-native-reanimated": "3.16.7"
```

**Comment by tkud04** [comment]
God bless you @kickbk updating to v2.22.0 solved this issue for me.

**Comment by kickbk** [comment]
One other thing to keep in mind. If using `v.2.22`, you can no longer use `<NativeViewGestureHandler disallowInterruption={true}>` (see [deprecation notice](https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/nativeview-gh/)), instead, with the new API it will look like this:
```ts
const Component = () => {
  const nativeGesture = Gesture.Native().disallowInterruption(true);
  return (
    <GestureDetector gesture={nativeGesture}>
      <WebView
        ...
        nestedScrollEnabled={true} // Allows nested scrolling
        androidLayerType="hardware"
      />
    </GestureDetector>
  )
}
```
I'm using `<WebView>` as an example since I was working on it just now, but it's just an example.
@gorhom maybe we should update the [docs](https://gorhom.dev/react-native-bottom-sheet/troubleshooting#my-component-gesture-interaction-gets-conflicted-with-bottom-sheet-interactions-)?
