### ISSUE TITLE
Jest - FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Daavidaviid** [software-mansion/react-native-reanimated#1929]
## Description

When I run my jest test suites after I just installed Reanimated 2 without adding anything to my components with `yarn jest` I get : 

```
<--- Last few GCs --->

[1197:0x1046b0000]    68378 ms: Mark-sweep 2028.1 (2062.8) -> 2021.0 (2064.1) MB, 1959.7 / 0.0 ms  (average mu = 0.110, current mu = 0.034) allocation failure scavenge might not succeed
[1197:0x1046b0000]    71290 ms: Mark-sweep 2029.3 (2080.3) -> 2022.2 (2080.6) MB, 2859.1 / 0.0 ms  (average mu = 0.060, current mu = 0.018) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1012b8fd5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a4379 node::Abort() [/usr/local/bin/node]
 3: 0x1000a44df node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e5d67 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e5d03 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100383ce5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x1003857aa v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x100380e79 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x10037e711 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10038cfaa v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10038d031 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x100353de0 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
13: 0x1004e8732 v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::AddArguments(v8::internal::Handle<v8::internal::JSArray>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::BuiltinArguments*, unsigned int, v8::internal::(anonymous namespace)::Where) [/usr/local/bin/node]
14: 0x100258e07 v8::internal::Builtin_ArrayUnshift(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x100a50159 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
error Command failed with signal "SIGABRT".
```

I installed reanimated 2 in jest setup file this way : 
```
require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
```

### Expected behavior

It should run perfectly

### Actual behavior & steps to reproduce

1. Install reanimated 2.1.0
2. Run jest test suites

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.1.0
- NodeJS: 14.7.0
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by jakub-gonet** [comment]
Hi, thanks for the report.
Could you try observing node memory usage
1. when Reanimated's `setUpTests()` is called
2. and when it's not?

How big is your test suite? It'd be awesome if you could prepare a reproduction example since Jest in Reanimated repo is working flawlessly.

It looks like your machine didn't have enough RAM to allow node to properly initialize so it crashed.
That may be a memory leak from our end but I want to make sure this isn't related to machine specs.

**Comment by Daavidaviid** [comment]
Seems like normally each node process running during the jest test suites are using between 300 and 800Mo of ram usage, but when the tests arrive on this specific file `A.test.tsx`, it never ends and the memory reach 2.06Go of ram usage.

When I run the test with `jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));` in jest setup it runs normally but with `require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();` from Reanimated2 it fails.

In the file `A.test.tsx` there is a nested TopBarNavigator from `@react-navigation/material-top-tabs` and it seems like when I get rid of it the test runs okay.

I'm not sure what is causing this

**Comment by Daavidaviid** [comment]
I narrowed it down to :

When I created a `Tab` with : 
```
const Tab = createMaterialTopTabNavigator();
```

If I pass the prop `initialLayout` to : 
```
<Tab.Navigator ... />
```

It fails. So I don't think it's linked to reanimated 2 but still it only happens when I use the new jest setup

**Comment by jakub-gonet** [comment]
Are you able to prepare a reproduction example with that test? It's preferable for us if you could strip any project-related components and logic. We encountered a similar problem when we had an import dependency cycle in the test so it may be some direction to look for.

**Comment by Daavidaviid** [comment]
@jakub-gonet I'm gonna post a repo with an example tomorrow

**Comment by rrebase** [comment]
Ran into this error as well with `"react-native-reanimated": "2.1.0"`

Happens with `require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests()` when jest hits `reanimated1` code, specifically `Animated.timing(clock, state, config)` inside `Animated.block`.

Adding `jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'))` to only that that test file is a working workaround.

**Comment by Daavidaviid** [comment]
> @jakub-gonet I'm gonna post a repo with an example tomorrow 

Oops I forgot about that sorry.
I able to solve to find a workaround.

**Comment by npetridis** [comment]
> > @jakub-gonet I'm gonna post a repo with an example tomorrow
> 
> Oops I forgot about that sorry.
> I able to solve to find a workaround.

What was the workaround?

**Comment by trivikr** [comment]
> I able to solve to find a workaround.

What was the workaround @Daavidaviid?
Did you pass `--clear-cache` as suggested in https://github.com/facebook/jest/issues/9980#issuecomment-624303275

**Comment by Daavidaviid** [comment]
I hate it when someone says he found a solution and then disappears without sharing it…

And I did it, sorry 😩

I can't remember exactly what workaround it was. All I know is that we created a fallback for most animations using reanimated v1, so maybe we are still using v1 during our tests.

Not helping very much sorry 😣
