### ISSUE TITLE
Attempt to invoke virtual method 'boolean abi40_0_0.exp.exponent.modules.api.reanimated.NativeProxy.isAnyHandlerWaitingForEvent(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by NicolasAlt128** [software-mansion/react-native-reanimated#1933]
## Description

**_Attempt to invoke virtual method 'boolean abi40_0_0.exp.exponent.modules.api.reanimated.NativeProxy.isAnyHandlerWaitingForEvent(java.lang.String)' on a null object reference_**

Whenever I launch the application, the above error appears, however, when I reload the application, it starts and works normally. Could someone help me with this? I don't understand very well who solving this error, it does not specify a file that I know.

### Expected behavior

Run my app without any errors

### Actual behavior & steps to reproduce

My app show this error..

![U8Ep5](https://user-images.githubusercontent.com/34657452/114557056-9463ce00-9c69-11eb-9b25-d1cfefa70df2.png)

## Snack or minimal code example

Files mentionned in this error are not mine

## Package versions

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/datetimepicker": "3.0.4",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-firebase/app": "^10.5.0",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "expo": "~40.0.0",
    "expo-custom-switch": "^1.0.2",
    "expo-image-manipulator": "~8.4.0",
    "expo-image-picker": "~9.2.0",
    "expo-permissions": "~10.0.0",
    "expo-print": "~9.2.0",
    "expo-sharing": "~8.5.0",
    "expo-status-bar": "~1.0.3",
    "express": "^4.17.1",
    "firebase": "7.9.0",
    "firebase-tools": "^9.4.0",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-action-button": "^2.8.5",
    "react-native-elements": "^3.2.0",
    "react-native-floating-action": "^1.21.0",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-modal": "^11.7.0",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-tags-input": "^1.0.10",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}
```

## Affected platforms

- [X] Android

**Comment by NicolasAlt128** [comment]
@jakub-gonet  Hi, do you have solution for this issues ? Can i deploy my app despite this error ?

**Comment by jakub-gonet** [comment]
Hard to say, this is the first time I see this crash.

1. Have you ejected from Expo?
2. Can you reproduce it consistently after reloading or it only shows up sometimes?
3. Did you try upgrading to Expo 41?

> Files mentionned in this error are not mine

We need a reproduction example to debug it locally, it's hard to do only by using (incomplete) stacktrace.

**Comment by newyorksoul** [comment]
I'm having this exact same problem on Expo 40 for android only. If not that error its preceded by another saying

`Error while updating property 'showsverticalscrollindicator' of a view managed by: RCTScrollView

java.lang.String cannot be cast to java.lang.Boolean`

**Comment by yuripaoloni** [comment]
I'm experiencing the same issues in the same circumstances as @jakub-gonet.

**Comment by jakub-gonet** [comment]
This isn't really actionable right now, we need a full stack trace to investigate it. If you are able to answer my questions and can provide stack traces please reply.

**Comment by MichaelKim39** [comment]
> Hard to say, this is the first time I see this crash.
> 
> 1. Have you ejected from Expo?
> 2. Can you reproduce it consistently after reloading or it only shows up sometimes?
> 3. Did you try upgrading to Expo 41?
> 
> > Files mentionned in this error are not mine
> 
> We need a reproduction example to debug it locally, it's hard to do only by using (incomplete) stacktrace.

1. I have not ejected from expo and getting this error
2. Cannot reproduce consistently, or atleast not sure how to, seems to show up randomly "sometimes"
3. Have not tried upgrading to expo 41 yet, should this matter?

**Comment by ConorHoey22** [comment]
has anyone resolved this ??

I am getting this issue also

**Comment by Heckerbl** [comment]
I too am getting the same error has anyone solved the issue yet 🤔

**Comment by WNetin** [comment]
any solution?

**Comment by webthe** [comment]
Downgrade your expo client to 2.23.x. Everything works just fine. The latest update on the expo client has some issues.

**Comment by webthe** [comment]
> I too am getting the same error has anyone solved the issue yet thinking
Downgrade your expo client to 2.23.x. Everything works just fine. The latest update on the expo client has some issues.
