### ISSUE TITLE
[Bug] interpolateColors and interpolateColor not working in Reanimated v2

### ISSUE THREAD

**Issue by vantuan88291** [software-mansion/react-native-reanimated#1934]
## Description

i Have used interpolateColors and interpolateColor but not working in Reanimated v2. This is example:
` const getBackgroundColor = interpolateColors(scroll.value, {
    inputRange: [0, HEIGHT_SLIDE / 2, HEIGHT_SLIDE],
    outputColorRange: ['red', 'blue', 'white'],
  })`
`<Animated.View style={{backgroundColor: getBackgroundColor}}>...</Animated.View>`
interpolateColor is the same. The backgroundColor not change when scroll.value change, it just show _red_, the first color in array. I also try opacity with `useDerivedValue` and it work perfect, but change color it's not work.

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 21.1.0
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by mrousavy** [comment]
You have to use a mapper (`useAnimatedStyle`) and `interpolateColor` (no `s` at the end) for this.

```ts
const style = useAnimatedStyle(() => ({ backgroundColor: interpolateColor(scroll.value, [0, HEIGHT_SLIDE / 2, HEIGHT_SLIDE], ['red', 'blue', 'white']) }), [scroll]);
return <Animated.View style={style}> ...
```

**Comment by vantuan88291** [comment]
> You have to use a mapper (`useAnimatedStyle`) and `interpolateColor` (no `s` at the end) for this.
> 
> ```ts
> const style = useAnimatedStyle(() => ({ backgroundColor: interpolateColor(scroll.value, [0, HEIGHT_SLIDE / 2, HEIGHT_SLIDE], ['red', 'blue', 'white']) }), [scroll]);
> return <Animated.View style={style}> ...
> ```

i used this before, exactly like you said, but its doesn't work too. I have to use like that:
`const colors = [color.transparent, color.primary]`
```
const bgHeader = useDerivedValue(() =>
    interpolate(scrollY.value, [0, heightBanner - 50], [0, 1], Extrapolate.CLAMP),
  )
```
```
  const hdBg = useAnimatedStyle(() => ({
    backgroundColor: colors[bgHeader.value],
  }))
```

This way is worked. But use `interpolateColor` doesn't work, it just show the color in first of array.

**Comment by piaskowyk** [comment]
Hey @vantuan88291 
In Reanimated v2 you should use something like this:
```js
import Animated, {
  useSharedValue,
  withTiming,
  useAnimatedStyle,
  interpolateColor
} from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React from 'react';

function AnimatedStyleUpdateExample(): React.ReactElement {

  const scroll = useSharedValue(0);

  const style = useAnimatedStyle(() => {
    return {
      backgroundColor: interpolateColor(
        scroll.value, 
        [0, 1, 2],
        ['red', 'blue', 'green']
      )
    }
  });

  return (
    <View>
      <Animated.View style={[{width: 100, height: 80}, style]} />

      <Button
        title="toggle"
        onPress={() => {
          scroll.value = withTiming(Math.random() * 2)
        }}
      />
    </View>
  );
}

export default AnimatedStyleUpdateExample;
```
Let me know if you have more questions.

**Comment by vantuan88291** [comment]
thank you, it's worked!
