### ISSUE TITLE
createAnimatedComponent with 'Stop' from 'react-native-svg' throws Error

### ISSUE THREAD

**Issue by henrmota** [software-mansion/react-native-reanimated#1938]
## Description
When I try to use a AnimatedStop on react-native-svg, I get the following error:
<img width="403" alt="Screenshot 2021-04-16 at 15 21 35" src="https://user-images.githubusercontent.com/896860/115038426-70052d00-9ec7-11eb-86c0-c57684d8a28b.png">.

This was happening here, and it was fixed previously >> https://github.com/software-mansion/react-native-reanimated/issues/1569

### Expected behavior
Allow to animate stop

### Actual behavior & steps to reproduce
Doesn't allow to animate the stop, just create one to see.

## Snack or minimal code example

```TS
const AnimatedStop = Animated.createAnimatedComponent(Stop);
...
 const color = useDerivedValue(() => {
        return interpolateColor(Math.max(progressY.value, progressX.value), [0, 1], ['hsl(153,72%,70%)', 'hsl(153,72%,86%)']);
    });
  ...
return <LinearGradient id="grad" x1="0" y1="0" x2="0" y2="1">
      <Stop offset="0" stopColor="hsl(153,72%,70%)" stopOpacity="1" />
      <AnimatedStop animatedProps={gradientAnimatedProps} />
  </LinearGradient>

```

## Package versions
2.1.0

- react-native: "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
- React Native Reanimated:~2.1.0
- NodeJS: 15.9.0

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by Wetsie** [comment]
Having the same issue

**Comment by rohith-purella** [comment]
Is there any solution for this issue

**Comment by chiliwax** [comment]
same here

**Comment by arjunghimire** [comment]
same here

**Comment by renochew** [comment]
Just bump into this bug, any chance following up this issue?

**Comment by Ubax** [comment]
@henrmota @renochew Could you provide a bit bigger repro (a whole component)?

**Comment by renochew** [comment]
@Ubax  Thank you very much for the reply. This is a simple but full app you could try and would trigger the error in question:

```javascript
import React from 'react';
import {View} from 'react-native';
import Animated, {useAnimatedProps} from 'react-native-reanimated';
import Svg, {Circle, Defs, LinearGradient, Stop} from 'react-native-svg';

const App = () => {
  const AnimatedStop = Animated.createAnimatedComponent(Stop);

  //const AnimatedProps = useAnimatedProps(() => {
  //  return {offset: 1};
  //});

  return (
    <View>
      <Svg width="200" height="200">
        <Defs>
          <LinearGradient id="grad" x1="0" y1="0" x2="1" y2="0">
            <AnimatedStop offset="0" stopColor="#FFD080" stopOpacity="1" />
            <Stop offset="1" stopColor="red" stopOpacity="1" />
          </LinearGradient>
        </Defs>
        <Circle cx="50" cy="50" r="50" fill="url(#grad)"></Circle>
      </Svg>
    </View>
  );
};

export default App;
```

**Comment by eflashcards** [comment]
Still happen in the latest version react-native-svg & react-native-reanimated

**Comment by liamhp-hotspot** [comment]
Anyone have a workaround?

**Comment by J3698** [comment]
Is there any workaround for this?
