### ISSUE TITLE
Invariant violation: native module cannot be null Jest

### ISSUE THREAD

**Issue by Prernabudh** [software-mansion/react-native-reanimated#1941]
## Description

On running jest --coverage, the following error message shows up:
![image](https://user-images.githubusercontent.com/48886463/115202568-25c4bb80-a114-11eb-9df3-f4e6a3b381f0.png)
 
I have already added this line to jestSetup file:
![image](https://user-images.githubusercontent.com/48886463/115202675-4260f380-a114-11eb-847d-b5aad90a6085.png)

Reanimated version
![image](https://user-images.githubusercontent.com/48886463/115202757-5ad10e00-a114-11eb-9166-23c5291d2034.png)

react-native-reanimated has been added to transformIgnorePatterns in package.json

### Expected behavior
The tests should pass

### Actual behavior & steps to reproduce
The tests keep failing with the error shown above
Run jest with 2.0.0

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.0.0
- NodeJS: 12.19.0

**Comment by mrbrentkelly** [comment]
I'm hitting the same issue with version `2.1.0`.

Tried following the jest setup instructions here https://docs.swmansion.com/react-native-reanimated/docs/testing#setup but didn't work for me 🤔 

Instead what I had to do was this in my Jest setup file...

```typescript
// @ts-ignore
global.__reanimatedWorkletInit = jest.fn();

jest.mock('react-native-reanimated', () => {
  return {
    // @ts-ignore
    ...jest.requireActual('react-native-reanimated/mock'),
    useSharedValue: jest.fn,
    useAnimatedStyle: jest.fn,
    withTiming: jest.fn,
    withSpring: jest.fn,
    withRepeat: jest.fn,
    withSequence: jest.fn,
    useAnimatedProps: jest.fn,
    Easing: {
      linear: jest.fn,
      elastic: jest.fn,
    },
  };
});
```

Which I pieced together from other similar past issues:

https://github.com/software-mansion/react-native-reanimated/issues/205#issuecomment-596119975
https://github.com/software-mansion/react-native-reanimated/issues/954#issuecomment-706671334
https://github.com/software-mansion/react-native-reanimated/issues/1380#issuecomment-726060076

**Comment by piaskowyk** [comment]
Does this issue still occur in version 2.3.1?
