### ISSUE TITLE
error: Error: Unable to resolve module `./Easing` from `node_modules\react-native-reanimated\src\Animated.js`:

### ISSUE THREAD

**Issue by keshav-optisol** [software-mansion/react-native-reanimated#1943]
## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by jakub-gonet** [comment]
Duplicate of #1896.
