### ISSUE TITLE
TypeScript types taken as literals

### ISSUE THREAD

**Issue by esthor** [software-mansion/react-native-reanimated#195]
Type definitions are a little weird. I'm having TS get angry with Animated Values. When I pass a number as a Value, it takes it as a literal. Current workaround is to pass a number with `<number>` to force the type. Otherwise, it will take my `0` or whatever else I pass it as the type, literally.

![screen shot 2019-02-25 at 1 50 34 pm](https://user-images.githubusercontent.com/11945900/53361453-c983f980-3905-11e9-91ed-cb5b07a136a5.png)
![screen shot 2019-02-25 at 2 00 31 pm](https://user-images.githubusercontent.com/11945900/53361456-cab52680-3905-11e9-8a0b-fe463dabcc68.png)

**Comment by satya164** [comment]
That syntax isn't valid inside .tsx files. Use `foo as SomeType` syntax.

**Comment by satya164** [comment]
That looks bit weird. What is this code doing?

**Comment by esthor** [comment]
This is in a file that has just been refactored from JS -> TS...everything worked fine in JS, just this typing is not right. TS is just assuming that the type is `0` in this case, or whatever value is passed, it just takes the value as the type, literally. The type definition just seems off, since to fix this, I basically have to explicitly tell TS that the type is `number` every time.

**Comment by satya164** [comment]
You have `(value?: 0)` where you annotate the type of value as `0`, and also `<0>` which passes `0` as the type, so looks to me like the annotations are wrong. But again the whole expression `const Value: new <0>(value?: 0) => Animated.Value<0>;` also doesn't look like valid TS and typing it in https://www.typescriptlang.org/play/index.html produces some weird JS. What exactly the expression does here?

**Comment by esthor** [comment]
Oh, I think I should clarify...The `const Value: new <0>(value?: 0) => Animated.Value<0>` and `const Value: new <number>(value?: number) => Animated.Value<number>` are the TS peek helpers in VS Code when I hover over `Value` in the actual code. I posted the screenshot to show what the peek shows when I hover over the type definition of `Value` from `react-native-reanimated`. My actual code is just `arbitraryVariableName = new Value(0);`or `arbitraryVariableName = new Value<number>(0);`

**Comment by satya164** [comment]
Ahh gotcha. Didn't expect that TS infers `0` as a type, but again it does the same if you do `const value = 0` (`value` is of type `0`), so I think it's expected.

I think this inference is so that you can pass `value` to a function like `(input: 0 | 1): void` etc. Though this inference doesn't seem to cause any issues in actual usage is `0` is a subtype of `number`.

Are you having other issues due to this inference or it's just the type hint?

**Comment by esthor** [comment]
Well, TS gets pretty upset later if I let it stay at `new Value(0);` without the explicit `<number>` and then try to setup parts of my animation like so: 
![screen shot 2019-02-28 at 3 40 42 pm](https://user-images.githubusercontent.com/11945900/53597144-65fd0480-3b6f-11e9-89d3-20968889ccdf.png)

**Comment by satya164** [comment]
Vert=y weird. I have always passed the type parameter so never seen this issue.

Changing the definitions to something like this seems to work:

```ts
class AnimatedValue<T extends Value> extends AnimatedNode<T> {
  constructor(value?: T);

  setValue(
    value: T extends number
      ? number
      : T extends string
      ? string
      : T extends boolean
      ? boolean
      : never
  ): void;
}
```

Looks super ugly though.

**Comment by jakub-gonet** [comment]
Hey, I'm sorry for the late response 😔

I think this issue may be outdated now, so I'm closing it.

If you still face the same problem feel free to reopen
