### ISSUE TITLE
`measure` fails if View is in `InputAccessoryView`

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1954]
## Description

Trying to measure (`measure(...)`) returns an empty object (`{ }`) if the View is inside of an `<InputAccessoryView>`.

I'm doing this to make the ScrollView adjust it's `contentInsets` interactively (by measuring the View in `InputAccessoryView` I know the current keyboard height).

The `InputAccessoryView` does not exist in the same React Root as the other Views, so this is why `measure` fails.

### Expected behavior

I expect it to still measure correctly.

### Actual behavior & steps to reproduce

It returns `{ }`. No `pageY`, no `height`, etc..

## Snack or minimal code example

```tsx
import React from "react";
import {
  Text,
  View,
  StyleSheet,
  ScrollView,
  InputAccessoryView,
  TextInput,
} from "react-native";

import Reanimated, {
  measure,
  useAnimatedRef,
  useAnimatedScrollHandler,
} from "react-native-reanimated";

export default function App() {
  const view = useAnimatedRef();

  const onScroll = useAnimatedScrollHandler({
    onScroll: (event) => {
      console.log("On Scroll!");
      try {
        const pos = measure(view);
        console.log(`View pos: ${JSON.stringify(pos)}`);
      } catch {
        console.error("Failed to measure view in InputAccessoryView!");
      }
    },
  });

  return (
    <View style={styles.container}>
      <Reanimated.ScrollView onScroll={onScroll} scrollEventThrottle={1}>
        <Text>Some content.</Text>
        <Text>Some content.</Text>
        <Text>Some content.</Text>
        <Text>Some content.</Text>
        <Text>Some content.</Text>
        <Text>Some content.</Text>
        <Text>Some content.</Text>
        <Text>Some content.</Text>
      </Reanimated.ScrollView>

      <InputAccessoryView>
        <Reanimated.View
          style={{ width: 300, height: 30, backgroundColor: "red" }}
          ref={view}>
          {/* <TextInput /> */}
        </Reanimated.View>
      </InputAccessoryView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```

> Couldn't get Snack to run, but here's a link anyways: https://snack.expo.io/E2skhBRja

While scrolling you'll see this output:

```
 LOG  On Scroll!
 LOG  View pos: {}
 LOG  On Scroll!
 LOG  View pos: {}
 LOG  On Scroll!
 LOG  View pos: {}
```

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0

## Affected platforms

- [ ] Android
- [x] iOS (`InputAccessoryView` only exists on iOS)
- [ ] Web

**Comment by jkadamczyk** [comment]
Hey @mrousavy

We didn't get to fixing the issue You filed. But maybe you fixed it yourself or found a solution that works around it. Would you mind sharing how didi you manage the problem? Perhaps someone else searching for similar issue will find it and get an answer.

**Comment by Latropos** [comment]
Now it works:

https://github.com/software-mansion/react-native-reanimated/assets/56199675/855b78e9-5f40-4685-ab39-40e0a7f32236

The issue is quite old, so I suppose that react-native has changed implementation of `InputAccessoryView` in the meantime which solved the problem.
