### ISSUE TITLE
withTiming callback is not executed if toValue is 0

### ISSUE THREAD

**Issue by yanush** [software-mansion/react-native-reanimated#1959]
## Description

When using withTiming and trying to animate a value to 0, callback is not being executed

### Expected behavior
Should execute

### Actual behavior & steps to reproduce
Just try the line below:

## Snack or minimal code example

	translateY.value = withTiming(y, { duration: 200 }, finished => {
		console.log('animation finished: ' + String(finished)); //this line is logged only if y value is not 0
	});

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0

## Affected platforms

- [X] Android
- [X] iOS
- [X] Web

**Comment by LuuchoRocha** [comment]
If the new value is the same as the old value the callback doesn't run

**Comment by jmysliv** [comment]
@LuuchoRocha has right. However, we decided that it is more intuitive if the callback runs every time the user trigger animation, even if the new value is the same as the old value. I'm gonna change it.
