### ISSUE TITLE
I cannot interact on an element in absolute when I have several gesture handler only on Android

### ISSUE THREAD

**Issue by Mathiaslachot** [software-mansion/react-native-reanimated#1968]
## Description

Unable to interact with my element in absolute. I have PanGestureHandler, RotationGestureHandler and PinchGestureHandler simultaneously which encompass my element but on android it does not work while on IOS all work perfectly.

### Expected behavior

The expected behavior is the same as on IOS, which I can move, rotate my item on Android.

### Actual behavior & steps to reproduce

Example code below

## Snack or minimal code example

```
  <PanGestureHandler
        ref={panRef}
        simultaneousHandlers={[pinchRef, rotatationRef]}
        onGestureEvent={eventHandlerPan}>
        <Animated.View>
          <RotationGestureHandler
            ref={rotatationRef}
            onGestureEvent={eventHandlerRotation}
            simultaneousHandlers={[panRef, pinchRef]}>
            <Animated.View>
              <PinchGestureHandler
                ref={pinchRef}
                simultaneousHandlers={[panRef, rotatationRef]}
                onGestureEvent={eventHandlerPinch}>
                <Animated.View collapsable={false}>
                  <Animated.View style={uas} />
                </Animated.View>
              </PinchGestureHandler>
            </Animated.View>
          </RotationGestureHandler>
        </Animated.View>
      </PanGestureHandler>
```

## Package versions

- React Native: 0.63.3
- React Native Reanimated: 2.0.0
- React Native Gesture Handler: 1.7.0

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by Covicake** [comment]
I have a similar problem.

I'm not using any gesture handler, but I have a transition in an animated view that has a `position: absolute`. On iOS it works as expected, but on Android I can't use TouchableOpacity (from react-native nor from react-native-gesture-handler) or Pressable (from react-native).

In fact, what actually gets the "press" event is the element beneath my animated view. I'm almost certain that our issues are related

**Comment by Mathiaslachot** [comment]
any news ?

**Comment by Covicake** [comment]
@Mathiaslachot why did you close it? :(
