### ISSUE TITLE
Accordion created with Reanimated v2 does not work inside a Modal component

### ISSUE THREAD

**Issue by emilioschepis** [software-mansion/react-native-reanimated#1973]
## Description

Reanimated accordions do not seem to work when placed inside a React Native `<Modal />`.

The same component with expanding accordions works flawlessly in normal conditions, but seems to get stuck when called inside a modal.

The same code seems to work fine in Android. I can only reproduce in iOS.

### Expected behavior

The accordion keeps its expanding animations and view layout even when used inside a modal.

### Actual behavior & steps to reproduce

The accordion's height is stuck once opened, and even if the contents are correctly hidden, there is no animation and the layout does not return to the starting state.

## Snack or minimal code example

I have created a fresh React Native project on 0.64.0 and pasted a working Accordion implementation from [this open source repository](https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/reanimated-2/src/Accordion).

Here is a repository to reproduce the bug with a simple homepage and two accordions (one outside the modal working correctly, and one inside that presents the bug).

https://github.com/emilioschepis/reanimated-2-in-modal

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.0.0
- NodeJS: 12.x
- Xcode: 12.4
- Java & Gradle: N/A

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by NikitaDudin** [comment]
```
import React from 'react';
import {StyleSheet, Text, TouchableWithoutFeedback, View} from 'react-native';
import Animated, {
  useAnimatedRef,
  useSharedValue,
  useAnimatedStyle,
  useDerivedValue,
  withSpring,
  withTiming,
  interpolate,
} from 'react-native-reanimated';

import Item from './ListItem';

const styles = StyleSheet.create({
  container: {
    marginTop: 16,
    backgroundColor: 'white',
    padding: 16,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  items: {
    overflow: 'hidden',
  },
  content: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  }
});

const List = ({list}) => {
  const open = useSharedValue(false);
  const progress = useDerivedValue(() =>
    open.value ? withSpring(1) : withTiming(0),
  );
  const height = useSharedValue(0);
  const headerStyle = useAnimatedStyle(() => ({
    borderBottomLeftRadius: progress.value === 0 ? 8 : 0,
    borderBottomRightRadius: progress.value === 0 ? 8 : 0,
  }));
  const style = useAnimatedStyle(() => ({
    height: interpolate(progress.value, [0, 1], [0, height.value]),
    opacity: progress.value === 0 ? 0 : 1,
  }), [progress, height]);
  return (
    <>
      <TouchableWithoutFeedback
        onPress={() => {
          open.value = !open.value;
        }}>
        <Animated.View style={[styles.container, headerStyle]}>
          <Text style={styles.title}>Total Points</Text>
          {/* <Chevron {...{progress}} /> */}
        </Animated.View>
      </TouchableWithoutFeedback>
      <Animated.View style={[styles.items, style]}>
        <View
          onLayout={({
            nativeEvent: {
              layout: {height: h},
            },
          }) => height.value = h}
          style={styles.content}
          >
          {list.items.map((item, key) => (
            <Item
              key={key}
              isLast={key === list.items.length - 1}
              {...{item}}
            />
          ))}
        </View>
      </Animated.View>
    </>
  );
};

export default List;

```

**Comment by emclab** [comment]
`NikitaDudin`, is the code above working for you? I changed to interpolate and onLayout (in place of measure) and still app stopped working. Mine is not in a modal.

**Comment by NikitaDudin** [comment]
@emclab, yes it woking. Tested on android emulator(MacOS) and android device.
The application throws an error when stopped, could you provide more information?
What flow of your application: expo managed, expo bare or create-react-native-app?
Hermes engine enabled? ```android/app/build.gradle```
```
project.ext.react = [
  enableHermes: true  // <- here | clean and rebuild if changing
]
```
Turbo modules disabled? remove from ```MainActivity.java``` 
```static {
   ReactFeatureFlags.useTurboModules = true;
 }
```

May be need clean android project, react-native project and restart application
```cd android && ./gradlew clean```
```npx react-native run-android --reset-cache``

**Comment by emclab** [comment]
Hi @NikitaDudin , just posted the code under the question linked. Many thanks.

**Comment by piaskowyk** [comment]
This is a problem with `measure` on iOS. I will fix it.

**Comment by emilioschepis** [comment]
@piaskowyk I look forward to the fix! Thank you very much.
