### ISSUE TITLE
Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

### ISSUE THREAD

**Issue by renepeter** [software-mansion/react-native-reanimated#1975]
## Description
Got this error on a project I started like 2 days ago, couldn't figure out what it was so I decided to try a fresh install and see if it persists... it did. Fresh install via Expo CLI, install react-native reanimated, replaced content of App.tsx with one of the examples in the Example/src folder. 

Tried to run, no bueno.

I've tried to clear all caches, by running both just in case it was some weird issue with npm:
`yarn cache clean`

`npm cache clean --force`

I also tried clearing the metro cache by deleting the `metro-cache` folder as outlined [here](https://docs.expo.io/troubleshooting/clear-cache-windows/).

On another issue, similar to this one, someone recommended running `npm start -- --reset-cache`, but I just got an error `error: unknown option '--reset-cache'`

Am I just doing something wrong?

### Expected behavior
Should be able to install library and run examples without issue.

### Actual behavior & steps to reproduce
Fresh Expo install using:
`expo init reanimated -t expo-template-blank-typescript`

Installed `react-native-reanimated` v2 as per instructions at [Expo website](https://docs.expo.io/versions/latest/sdk/reanimated/)

Replaced code inside `App.tsx` with [AnimatedStyleUpdateExample.tsx](https://github.com/software-mansion/react-native-reanimated/blob/master/Example/src/AnimatedStyleUpdateExample.tsx) found in the [Example/src folder](https://github.com/software-mansion/react-native-reanimated/tree/master/Example/src)

Renamed function from AnimatedStyleUpdateExample to App.

Run `expo start`

Attempt to load via Expo Go on Android device, get error.

## Package versions
```{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~41.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-reanimated": "~2.1.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "typescript": "~4.0.0"
  },
  "private": true
}
```

- OSE: Windows 10
- Expo SDK: 41.0.0
- React Native: 0.63.3
- React Native Reanimated: 2.1.0
- NodeJS: 14.15.1
- Xcode: 
- Java & Gradle: 

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by renepeter** [comment]
Sigh, after spending all that time creating this issue.

I kept trying to make it work and ran expo with the following command:
`expo start --clear`
and everything magically works now -__-

Guess I didn't clear ALL the caches.

**Comment by avet-m** [comment]
react-native start --reset-cache

**Comment by ChanHyuk-Im** [comment]
Try this command.

`npm start -- --reset-cache`
