### ISSUE TITLE
Android app crash on debug chrome Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by pmella16** [software-mansion/react-native-reanimated#1986]
## Description
Hi, i am with react navigation 5 and reanimated, when try to debug on chrome the app crash and get this error 

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)

if delete this part of code of the official instalation the debug mode works fine
MainApplication.java

    @Override   
    protected JSIModulePackage getJSIModulePackage() {
      return new ReanimatedJSIModulePackage();
  }

### Expected behavior

debug mode work in android app with no delete code from MainApplication.java

### Actual behavior & steps to reproduce
install react navigation 5 with tab

https://reactnavigation.org/docs/material-top-tab-navigator

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0
- NodeJS: v14.16.1
- Xcode:
- Java & Gradle: 4.1.0

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by jakub-gonet** [comment]
This is expected, Reanimated2 doesn't support remote debugging.
https://docs.swmansion.com/react-native-reanimated/docs/installation#installing-the-package
