### ISSUE TITLE
MapPanel buggy interpolation

### ISSUE THREAD

**Issue by alisherakb** [software-mansion/react-native-reanimated#200]
Originally this issue was posted in react-native-interactable repo but I haven’t received response. I tried your example, but got the same behaviour.

---

 In MapPanel example **interpolation** inside Animated.View **starts** in reverse order on restart until you start to drag:

![image 2019-02-28 21 30 05](https://user-images.githubusercontent.com/26904008/53592939-0408c300-3ba0-11e9-8a38-8fafe8be87fc.jpg)

---

Reproducing:
It may not appear instantly on this example. But if you try 10 restarts, 2-3  of them will be buggy(reverse interpolation) until you start to drag. 
Making more complex animations(backgroundColor, Height, SVG paths) may decrease successful restart to 0, meaning that all your interpolations will be reversed.

---

Using: 
> animatedNativeDriver={true}

Solves the issue. But limits me on making more complex animations (backgroundColor, Height, SVG paths).

--- 
"react-native": "0.57.3"
"react-native-interactable": "^0.1.10"

---
Need your help guys, please!!!

**Comment by jakub-gonet** [comment]
Hi @alisherakb,
I'm terribly sorry that this issue went unnoticed 😔

This issue is quite old, so it's probably outdated and I'm closing it.

If you have any further questions please comment, I'm happy to provide assitance.
