### ISSUE TITLE
Update types on animated scroll view to not use `getNode()`

### ISSUE THREAD

**Issue by gp3gp3gp3** [software-mansion/react-native-reanimated#2005]
## Description

Currently if you add an Animated.ScrollView and have a ref on it, while accessing the `scrollTo`  prop, typescript complains that `scrollTo` doesn't exist (but functions correctly).  If you use `getNode`, the TS compiles but you get a yellow warning about it no longer being necessary.

![Screenshot](https://user-images.githubusercontent.com/9616513/117561320-d400b880-b063-11eb-9b62-20e2c8a8f455.jpg)
![Screen Shot 2021-05-09 at 1 10 38 AM](https://user-images.githubusercontent.com/9616513/117561325-d95e0300-b063-11eb-85bc-9455757165bc.png)

### Expected behavior

TS to compile without throwing errors

### Actual behavior & steps to reproduce

Errors being thrown

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.0.1
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by aminerol** [comment]
for Reanimated 2, they added a new api to scroll animated scrollviews, here is how you do it:

```js
const scrollView = useAnimatedRef<Animated.ScrollView>();
scrollTo(scrollView, 0, scrollY.value, false);
```

**Comment by jmysliv** [comment]
Hi @gp3gp3gp3! 
@aminerol is right, check out our [docs](https://docs.swmansion.com/react-native-reanimated/docs/next/api/nativeMethods/scrollTo).
