### ISSUE TITLE
suport flatlist probem on refresh

### ISSUE THREAD

**Issue by misaku** [software-mansion/react-native-reanimated#2008]
## Description
i use reanimated with flatlist but cant work onRefresh withe animated flatlist

### Expected behavior
work same flatlist but with onscroll

### Actual behavior & steps to reproduce

- create AnimatedFlatList
- try to use onRefresh functionality

## Snack or minimal code example
```JS
const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);
```
```JS
        <AnimatedFlatList
          data={filterTotal}
          renderItem={renderItem}
          keyExtractor={(item: {id: any}, idx: any) => item.id + idx}
          onScroll={scrollHandler}
          onRefresh={resetData}
          refreshing={refreshLoading}
        />
```

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0
- NodeJS: v14.16.1
- Xcode:
- Java : 11.0.11

## Affected platforms

- [x] Android
- [ ] iOS ???? // I did'nt try
- [ ] Web

**Comment by Stevemoretz** [comment]
IOS is fine I have exactly this problem only on Android.

**Comment by AlexSirenko** [comment]
Yep, seems reletive issue https://github.com/software-mansion/react-native-gesture-handler/issues/1067

**Comment by Ubax** [comment]
@misaku Could you confirm that this issue is the same as in https://github.com/software-mansion/react-native-gesture-handler/issues/1067?
Could you also provide a recording of what happens?
