### ISSUE TITLE
interpolateColor on android is not working

### ISSUE THREAD

**Issue by Daavidaviid** [software-mansion/react-native-reanimated#2009]
## Description

I found a case where it seems like interpolateColor is not working on android when I try to animate the fill prop of a Path (react-native-svg) with `useAnimatedProps`. Link to a repo to reproduce the issue : https://github.com/Daavidaviid/android-issue-fill-reanimated

The issue seems to arise when the derived value is not consumed directly but after a loading period.

| Screenshot 1        | Screenshot 2           |
| ------------- |:-------------:|
| <img width="343" alt="Screen Shot 2021-05-10 at 07 13 05" src="https://user-images.githubusercontent.com/32457364/117643954-59b55e80-b15f-11eb-8213-e28e11f95bb9.png">     | <img width="343" alt="Screen Shot 2021-05-10 at 07 13 20" src="https://user-images.githubusercontent.com/32457364/117643960-5b7f2200-b15f-11eb-9251-8090a919af35.png"> |

### Expected behavior

Possible to animate fill property with reanimated and scroll animation

### Actual behavior & steps to reproduce

Not working and getting the warning message :  
```
"-11545781" is not a valid color or brush 
```

## Snack or minimal code example

https://github.com/Daavidaviid/android-issue-fill-reanimated

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.1.0
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by Daavidaviid** [comment]
I updated the example to make it clearer

**Comment by divykj** [comment]
I'm facing the same issue!

**Comment by jmysliv** [comment]
Hi @Daavidaviid! I tested it on reanimated `2.3.0-alpha.2` and interpolate color was working fine with scrolling. The value that is returned by `interpolateColor` is also a valid color number on Android, so this warning is probably an issue with `react-native-svg`. If you still will be encountering some problems, let me know and I'll reopen this issue.
