### ISSUE TITLE
useDerivedValue throws Render Error - Object not extensible

### ISSUE THREAD

**Issue by skam22** [software-mansion/react-native-reanimated#2015]
## Description

useDerivedValue throwing error when accessing a dynamic array of data.

### Expected behavior

expect useDerivedValue to return the correct value from within the dynamic array.

### Actual behavior & steps to reproduce

simulator throws a render error, Attempting to define property on object that is not extensible.

if the data array is hardcoded then useDerivedValue returns the correct value from within the static array.

## Snack or minimal code example

_**this code will throw an error:**_

`const ValuesAnimated = ({translateX}) => {
  const ARRAY = useSelector(selectArray); //ARRAY LOADED FROM REDUX STORE

  const test = useDerivedValue(() => {
    cost data = ARRAY[translateX.value]
    return data;
  });`

_**this code works fine but the data is hardcoded:**_
`const ValuesAnimated = ({translateX}) => {
  const ARRAY = [{"key1": value1, "key2": value2}, {"key1": value2, "key2": value3},{"key1": value4, "key2": value5}]

  const test = useDerivedValue(() => {
    cost data = ARRAY[translateX.value]
    return data;
  });`

if I console.log(ARRAY) when it's loaded dynamically it outputs to the terminal just fine, but attempting to interact with the array from within the useDerivedValue worklet will always throw an error of "Attempting to define property on object that is not extensible."

**_this code will throw an object is not extensible error:_**

`const ValuesAnimated = ({translateX}) => {
  const ARRAY = useSelector(selectArray); //ARRAY LOADED FROM REDUX STORE

  const test = useDerivedValue(() => {
    console.log(ARRAY)
    return 1;
  });`

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.1.0
- NodeJS: 14.16.0
- Xcode: 12.5 (12E262)

## Affected platforms

- [ ] Android
- [x ] iOS
- [ ] Web

**Comment by skam22** [comment]
for anyone else who encounters this problem, I solved it by assigning the dynamic array to a sharedValue after wrapping it with JSON.parse(JSON.stringify(ARRAY).

`const sharedArray = useSharedValue(JSON.parse(JSON.stringify(ARRAY)))`

I was then able to access SharedArray.value from within the useDerivedValue method, and although the useDerivedValue method did not return a shared value (the constant returned undefined when console logged), I was still able to assign values to other shared values before the return.

`
const firstKey = useSharedValue()
const secondKey = useSharedValue()
const test = useDerivedValue(() => {
    const temporary = sharedArray.value[translateX.value] // returns correct item in Array @ index (translateX.value)

    firstKey.value = temporary.firstKey
    secondKey.value = temporary.secondKey

    return temporary // test.value still returns undefined but at least it works for now
`

I'm sure there's a more elegant way of solving the problem but this worked for me.

**Comment by piaskowyk** [comment]
If you pass an object to a worklet, this object is freezing and you can't modify it. If you want to pass redux object please pass here a copy of object, `Object.assign()` or `{ ...obj }`
