### ISSUE TITLE
Shared values do frequently reset on web

### ISSUE THREAD

**Issue by sreuter** [software-mansion/react-native-reanimated#2019]
## Description

I'm in the progress of updating to Expo SDK 41, which includes an update of react-native-web 2.0.0-rc.0 to ~2.1.0 and also an upgrade of react-native-web to 0.16.x.

Since updating, animations on web are often reset to their initial value.

Here's a simple component to replicate:

```import React from "react";

import { useEffect } from "react";
import { ViewStyle } from "react-native";
import Animated, {
  Easing,
  useAnimatedStyle,
  useSharedValue,
  withDelay,
  withTiming,
} from "react-native-reanimated";

interface FadeInViewProps {
  children: JSX.Element[] | JSX.Element;
  delay?: number;
  inverted?: boolean;
  style?: ViewStyle;
}

export const FadeInView = (props: FadeInViewProps): JSX.Element => {
  const { inverted, delay = 0 } = props;

  const slideAnim = useSharedValue(20 * (inverted ? -1 : 1));
  const fadeAnim = useSharedValue(0);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateY: slideAnim.value }],
      opacity: fadeAnim.value,
    };
  });

  useEffect(() => {
    slideAnim.value = withDelay(
      delay,
      withTiming(0, {
        easing: Easing.out(Easing.ease),
        duration: 500,
      })
    );
    fadeAnim.value = withDelay(
      delay,
      withTiming(1, {
        easing: Easing.out(Easing.ease),
        duration: 500,
      })
    );
  }, []);

  return (
    <Animated.View style={[props.style, animatedStyles]}>
      {props.children}
    </Animated.View>
  );
};
```

I use this component to wrap screen content, so it nicely fades in. This used to work just perfectly, no matter how much I navigated between screens.

### Expected behavior

Screens fade in and stay visible.

### Actual behavior & steps to reproduce

The screen is not visible after certain re-renders. While the slideAnim.value stays correct (at `0`), the fadeAnim.value is being from 1 to 0.

## Package versions

- Expo SDK: 41
- React Native: 0.6.3
- React Native Web: 0.16.2
- React Native Reanimated: 0.16.2

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by robertherber** [comment]
I've noticed this as well

**Comment by sreuter** [comment]
@robertherber Did you find out why this is happening? @jakub-gonet, any ideas on this one?

**Comment by sreuter** [comment]
It seems like the issue is specifically about animating an opacity from `0` to something. It doesn't seem to happen with any other shared values.

**Comment by robertherber** [comment]
> It seems like the issue is specifically about animating an opacity from `0` to something. It doesn't seem to happen with any other shared values.

Yes, this aligns with my experience as well

**Comment by axeldelafosse** [comment]
> It seems like the issue is specifically about animating an opacity from 0 to something. It doesn't seem to happen with any other shared values.

Yeah, I just had the same issue with `shadowOpacity`

**Comment by hashedname** [comment]
Unfortunately I believe this happens on native too (both Android and iOS). 

In fact somehow this issue #2078  is related to this. In the snack of the issue I mentioned, if we initialize `positionY` to 100, on every new pan gesture the problem is experienced at that position, which shouldn't happen. I'd expect to experience it at the position the dragged item is released.

**Comment by SimpleCreations** [comment]
I'm experiencing the same issue on iOS — every time my component re-renders, the shared value gets reset to its initial value. Is there a workaround for this?

**Comment by sbaiahmed1** [comment]
This is still an issue on reanimated v 2.2.4 and Im facing it. Is there any workaround guys please ?

**Comment by kacperkapusciak** [comment]
Hello @sreuter :wave:

I cannot seem to reproduce the issue on the newest version of `react-native-reanimated`. Video:

https://user-images.githubusercontent.com/39658211/151552758-b881a077-feb4-411d-aa85-75a388bf76d0.mov
