### ISSUE TITLE
Hooks support? 

### ISSUE THREAD

**Issue by LiteCatDev** [software-mansion/react-native-reanimated#202]
Now that hooks are already a thing in react native, will this library adapt to create his own hooks ?

**Comment by osdnk** [comment]
`withSpring`? Sounds nice, but how actually could it work?

**Comment by jakub-gonet** [comment]
AFAIK reanimated uses only [useCode](https://software-mansion.github.io/react-native-reanimated/code.html#animated-usecode) for now (11-2019)

This thread seems to be inactive, so I'm closing it now.

If you have further questions feel free to reopen this issue 🙂
