### ISSUE TITLE
TextInput onBlur animation hot reload iOS crash

### ISSUE THREAD

**Issue by danilobuerger** [software-mansion/react-native-reanimated#2035]
## Description

When using `TextInput.onBlur` to trigger an animation, the app crashes on hot reload.

### Expected behavior

The app should not crash and hot reload instead.

### Actual behavior & steps to reproduce

The app crashes.

## Snack or minimal code example

```
import * as React from "react";
import { TextInput } from "react-native";
import { useSharedValue, withTiming } from "react-native-reanimated";

function TextInputTest() {
  const isFocused = useSharedValue(1);
  return <TextInput onBlur={() => (isFocused.value = withTiming(0))} value="foo" />;
}

export default TextInputTest;
```

Focusing this component and then triggering a hot reload will crash on iOS.

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0
- NodeJS: 14.16.1
- Xcode: 12.5

## Affected platforms

- [x] iOS

Did not test other platforms.

**Comment by jmysliv** [comment]
@danilobuerger are you still facing this issue? I was trying to reproduce it, however, the hot reload worked fine with your code example.

**Comment by danilobuerger** [comment]
@jmysliv we didn't go ahead with using rea because of this bug so I don't know what the status of it is right now. Did you try reproducing it with the above listed versions or just current?

**Comment by jmysliv** [comment]
@danilobuerger both of them and both worked.

**Comment by danilobuerger** [comment]
@jmysliv I did a little testing. I was unable to reproduce this with the [rea2 playground](https://github.com/software-mansion-labs/reanimated-2-playground). However, I was able to reproduce it with the [rnn playground](https://github.com/wix/react-native-navigation/tree/master/playground). This would suggest a problem if there are multiple root views in play. Here is a diff (for TextInputTest.tsx see above) on the current rnn playground to reproduce this issue:

```diff
diff --git a/babel.config.js b/babel.config.js
index c1d044b7c..cdf7ebe6a 100644
--- a/babel.config.js
+++ b/babel.config.js
@@ -5,6 +5,7 @@ module.exports = function (api) {
     plugins: [
       '@babel/plugin-proposal-export-namespace-from',
       '@babel/plugin-proposal-export-default-from',
+      'react-native-reanimated/plugin',
     ],
   };
 };
diff --git a/package.json b/package.json
index 2fb359527..10039a4f8 100644
--- a/package.json
+++ b/package.json
@@ -99,7 +99,7 @@
     "react-native": "0.63.2",
     "react-native-fast-image": "^8.3.4",
     "react-native-gesture-handler": "^1.6.1",
-    "react-native-reanimated": "^1.9.0",
+    "react-native-reanimated": "2.2.0",
     "react-native-ui-lib": "5.11.0",
     "react-redux": "5.x.x",
     "react-test-renderer": "16.13.1",
diff --git a/playground/src/screens/LayoutsScreen.tsx b/playground/src/screens/LayoutsScreen.tsx
index 711a7e4e9..b194bbe9a 100644
--- a/playground/src/screens/LayoutsScreen.tsx
+++ b/playground/src/screens/LayoutsScreen.tsx
@@ -13,6 +13,7 @@ import Screens from './Screens';
 import Navigation from '../services/Navigation';
 import { stack } from '../commons/Layouts';
 import { Text } from 'react-native';
+import TextInputTest from '../components/TextInputTest';
 
 const {
   WELCOME_SCREEN_HEADER,
@@ -67,6 +68,7 @@ export default class LayoutsScreen extends NavigationComponent<NavigationCompone
           onPress={this.splitView}
         />
         <Text>{this.state.componentDidAppear && 'componentDidAppear'}</Text>
+        <TextInputTest />
       </Root>
     );
   }

```

**Comment by danilobuerger** [comment]
Still reproducible with current rnn playground and rea 2.5.0
