### ISSUE TITLE
Early return from block

### ISSUE THREAD

**Issue by naftalibeder** [software-mansion/react-native-reanimated#204]
Is there any way to return or break early out of a block sequence? E.g.:

```
const foo = block([
  cond(
    eq(bar, 0),
    return  // or break
  ),
  set(baz, 1)  // imagine more complicated logic here
])
```

This would allow flattening of what tend to be pretty deeply nested conditionals. Thanks!

**Comment by osdnk** [comment]
I think it's a reasonable approach. I haven't faced this problem, but I'm open to discussions if you can provide some good use cases.

**Comment by osdnk** [comment]
For now, I'm closing, but feel free to continue a discussion.
