### ISSUE TITLE
Native module cannot be null?

### ISSUE THREAD

**Issue by galuh1300d** [software-mansion/react-native-reanimated#206]
Why this error happen?

<img width="390" alt="screen shot 2019-03-08 at 13 23 54" src="https://user-images.githubusercontent.com/43464041/54023904-c40d9580-41c8-11e9-8e99-956c3c6d52f2.png">

**Comment by dsznajder** [comment]
@galuh1300d Could you provide reproduction code? It's kinda wild guess what happened with that information.

**Comment by galuh1300d** [comment]
> @galuh1300d Could you provide reproduction code? It's kinda wild guess what happened with that information.

My code was deleted, i got this error while installing react-native-tab-view
i've reported in that repo but the answers suggest me to react-native link react-native-reanimated, if the error still happened they suggest me to report this in this repo

**Comment by dsznajder** [comment]
I've seen this error only when `react-native-reanimated` wasn't linked or after linking I forgot to rerun the app (`react-native run-ios`). I can't figure out what it was without a code.

**Comment by ValentinBlokhin** [comment]
I have the same issue on RN 0.59

**Comment by nlabofa** [comment]
The issue is that `react-native link react-native-reanimated`  is not properly linking the **react-native-reanimated** library. You have to link it manually in Xcode. i.e add `RNReanimated.xcodeproj` to the libraries folder, then add `libReanimated.a` to the link binary with libraries

**Comment by marlti7** [comment]
I have the same issue on RN 0.59
when i have link

**Comment by tyuwan** [comment]
Same issue on RN 0.58

**Comment by HughBerriez** [comment]
@nlabofa where do I find ```libReanimated.a```? Can't seem to find it.. Thanks!

**Comment by usrbowe** [comment]
**ℹ️ TIP**:
To verify if linking works properly or not, just check `ios/ProjectName.xcodeproj/project.pbxproj` should have few changes, including `libRnReanimated.a`.
If changes are in place, make sure to have run `pod install` from `ios` folder.

**Comment by anastely** [comment]
@usrbowe Hey, I can't see any folder or file as name `project.pbxproj `& `libRnReanimated.a` !

**Comment by jakub-gonet** [comment]
Hey folks,
this thread seems inactive so I'm closing it

if `react-native link react-native-reanimated` or @nlabofa's solution doesn't work, don't hesitate to ask

**Comment by cherucole** [comment]
> I've seen this error only when `react-native-reanimated` wasn't linked or after linking I forgot to rerun the app (`react-native run-ios`). I can't figure out what it was without a code.

I also noticed it happened to me and I had to re-run 'react-native run-ios'

**Comment by Azaz0723** [comment]
I have  updated my application from react native 0.57.1 to 0.60.5 and its throwing this error
![simulator_screenshot_84D01BA3-2A91-4796-8E5B-4B2D73CC8661](https://user-images.githubusercontent.com/99475916/159850152-01d9a96c-b70a-43f8-8e6e-522409929d6f.png)
any body have  faced same issue can help me out
