### ISSUE TITLE
measure not working properly on v2.2.0 

### ISSUE THREAD

**Issue by husseinAbdulnabi** [software-mansion/react-native-reanimated#2076]
## Description
using measure function in useDerivedValue is throwing a weird bug, happening only when upgrading from v2.1.0 into v2.2.0, same code on both, v2.1.0 is working as expected, v2.2.0 is not working even after putting the measure in try {} catch {} block

### Expected behavior
`measure(container)` should throw a normal error that would be catched normally in the catch block.
### Actual behavior & steps to reproduce
`measure(container)` is just crashing the whole t
hing as shown in the screenshot
## Snack or minimal code example
```
 const Example = (props) => {
    const container = useAnimatedRef();
    const [open, setOpen] = useState(true);

    const translateY = useDerivedValue(() => {
      try {
        const bounds = measure(container);
        if (open) {
          return withTiming(0, {duration});
        } else {
          return withTiming(bounds.height, {duration});
        }
      } catch (e) {
        return 1000;
      }
    }, [open]);

  const cardStyle = useAnimatedStyle(() => {
      return {
        transform: [
          {
            translateY: translateY.value,
          },
        ],
      };
    });
  return (
      <Animated.View
          ref={container}
          style={[
            styles.content,
            cardStyle,
          ]}>
          {props.children}
        </Animated.View>
  )
}
```

## Package versions

- React Native: 0.64.1
- React Native Reanimated: v2.2.0
- NodeJS: latest stable
- Xcode: 12.5
- Java & Gradle:

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web
![Screen Shot 2021-05-29 at 10 26 53 PM](https://user-images.githubusercontent.com/9201625/120082789-88bf5000-c0cd-11eb-8c8c-e64b99518e1e.png)

**Comment by piaskowyk** [comment]
Fixed for iOS with: https://github.com/software-mansion/react-native-reanimated/pull/2153 On Android problems still occur. 😕

**Comment by piaskowyk** [comment]
Should be fix by: https://github.com/software-mansion/react-native-reanimated/pull/2209
