### ISSUE TITLE
Animated view positioned incorrectly with absolute Y from PanGestureHandler

### ISSUE THREAD

**Issue by hashedname** [software-mansion/react-native-reanimated#2078]
## Description

Basically when the user drags an item I render a copy of it with an absolute position where the user is making the gesture. The problem is that when the user taps and holds the item, the state changes to `BEGAN`, but the absolute positioned item is placed at the wrong position (at the top), while if the user moves it and the state changes to `ACTIVE` it is positioned correctly and moves along with the gesture of the user. I placed some logs and I can't see any odd value except for the `onLayout` event which actually prints 0 when the state changes to `BEGAN`.

Is this a bug or am I missing something?

https://user-images.githubusercontent.com/85024703/120111968-32591c80-c174-11eb-9e84-d86b8fcfb71b.mp4

### Expected behavior

Absolute view positioned where the drag gesture starts.

### Actual behavior & steps to reproduce

The absolute view is not positioned where the drag gesture starts.

Use `absoluteY` from PanGestureHandler `onStart` and `onActive` to positition an absolute animated view.

## Snack or minimal code example

https://snack.expo.io/sLXZ7Y8OO

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.2.0
- React Native Gesture Handler: 1.10.3

## Affected platforms

- [X] Android
- [X] iOS

**Comment by jmysliv** [comment]
After investigation, it seems to be the same problem as in #2019, so if you don't mind I'm gonna close this issue. We are planning to fix this after this week's release.
