### ISSUE TITLE
Build fails with react-native 0.64.1 and hermes_enabled = true and react-native-reanimated = 2.2.0

### ISSUE THREAD

**Issue by KPUbhada** [software-mansion/react-native-reanimated#2080]
Build fail with enable harmes in iOS
Describe the bug
I have try with all possible case like - delete pod file, clear cache and other option but app not run when Hermes on in iOS.

Environment

Platform: react-native 0.64.1
SDK version: 2.2.0
OS version: Latest OS
Xcode: 12.4
React Native version: 0.64.1
SDK installation (CocoaPods + version or manual): Latest
How widespread is the issue. Percentage of devices affected.
Steps to reproduce = Just install latest version and harmes on - App not build

Error
fatal error: 'hermes/hermes.h' file not found

Showing Recent Errors Only
/react-native-reanimated/ios/native/UIResponder+Reanimated.mm:19:

**Comment by piaskowyk** [comment]
Hey @KPUbhada 👋
I tried to reproduce your issue but it works for me. Probably it can be related to your project configuration, could you share your repo where I can reproduce your problem?

**Comment by piaskowyk** [comment]
Inactive, so I need to close but if you still have this issue feel free to reopen or notify me.
