### ISSUE TITLE
Race condition in animated style for animated icon component

### ISSUE THREAD

**Issue by enesozturk** [software-mansion/react-native-reanimated#2087]
## Description

Hi 👋🏽 I have a situation about an animation logic and I am not sure if it is a because of my design or it is a bug. Actually after many try, I thought it might be race condition issue in background.

Using v2 for [my package](https://github.com/enesozturk/react-native-hold-menu).  As you can see below, `<MenuList/>` has many `<MenuItem/>` and they has `<MenuItemIcon />` component inside. When I change theme (it is a shared value comes from context), AnimatedIcon's color is not changing as expected.

Instead of using `<AnimatedIcon />`, if I render `<Animated.Text />`, it is working as expected. Do you have any idea what can cause this issue? 

Other details below.
Thanks in advance. 

### Expected behavior

Changing icon color on theme change.

### Actual behavior & steps to reproduce

Some icon colors changing and some not. 

## Snack or minimal code example

I get Icon component and theme from user as Provider prop;

```js
import FeatherIcon from 'react-native-vector-icons/Feather';
...
<HoldMenuProvider iconComponent={FeatherIcon} theme={state.theme}>
...
</HoldMenuProvider/>
```

In Provider, I create AnimatedIcon from the `iconComponent`

```js
export let AnimatedIcon: any;

const ProviderComponent = ({
  iconComponent,
}: HoldMenuProviderProps) => {
  AnimatedIcon = Animated.createAnimatedComponent(iconComponent);
   
   ...
}
```

In `<MenuItemIcon />`, I import AnimatedIcon from Provider and use `useAnimatedProps`. (Also tried `useAnimatedStyles`):

```js
import { AnimatedIcon } from '../provider/Provider';
..
const MenuItemIconComponent = ({ item }: MenuItemIconComponentProps) => {
  const { theme } = useInternal();

  const iconColor = useAnimatedProps(() => {
    const color = getColor(item.isTitle, item.isDestructive, theme.value);

    return { color };
  }, [theme, item]);

  return (
    <>
      {!item.isTitle && item.icon && (
        <AnimatedIcon name={item.icon} size={18} animatedProps={iconColor} />
      )}
    </>
  );
};

const MenuItemIcon = React.memo(MenuItemIconComponent, isEqual);
```

### Screen Records

If I render AnimatedIcon:

https://user-images.githubusercontent.com/19428358/120377427-c6b6b100-c325-11eb-8785-48ad9ce63f55.mov

And turned it to `Animated.Text`:

https://user-images.githubusercontent.com/19428358/120377377-b56da480-c325-11eb-8efe-5e2812863a47.mov

## Package versions

- React Native: ~0.63.4
- React Native Reanimated: 2.1.0
- NodeJS: v14.17.0

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by mrousavy** [comment]
Isn't the Icon a text itself? Maybe `color` does not go through the text properties and is therefore animated on a native-module thread instead of the UI thread?

**Comment by enesozturk** [comment]
> Isn't the Icon a text itself? Maybe `color` does not go through the text properties and is therefore animated on a native-module thread instead of the UI thread?

Icon is normally a AnimatedIcon component (I updated the code snippets). User just gives icon name as string. In `<MenuItemIcon />` I just change it is color as theme change. I also tried `useAnimatedStyles` for stying but not solved unfortunately. Still trying to understand what cause it.

**Comment by jmysliv** [comment]
Hey @enesozturk, are you still having this issue? Can you provide a more detailed example to help me fix it?

**Comment by enesozturk** [comment]
Hi @jmysliv, I have not solved this issue yet, and also did not tried the issue with never versions of Reanimated (not sure published fixes related to this). Do need any other description, explanation, code snippets etc?

**Comment by jmysliv** [comment]
@enesozturk yes I would appreciate some more detailed code example or a link to the GitHub repository, so I can have a full view of the problem.

**Comment by enesozturk** [comment]
I checked the issue details to see if there is missing info. Maybe just show the real code of my project: 

- Importing the `AnimatedIcon` component which is created in [Provider](https://github.com/enesozturk/react-native-hold-menu/blob/c908bdbccab8b5454d606942df59633c60c7f331/src/components/provider/Provider.tsx#L27) on the first render. https://github.com/enesozturk/react-native-hold-menu/blob/c908bdbccab8b5454d606942df59633c60c7f331/src/components/menu/MenuItem.tsx#L22
- And giving it a animated style in line 68, same file. Here, I also tried to use `animatedProps` because Icon component uses both `color="red"` and `styles={{color: 'red'}}` for stying. But result is same as first video.

What i tried is, converted icon component to Text to see if problem is related to Icon component. And as we see in second video, colors are changing as expected when theme is change. 

Please let me know if there is some pieces that you did not understand. Thanks!

**Comment by enesozturk** [comment]
@jmysliv Do you have any update on this issue?

**Comment by jmysliv** [comment]
@enesozturk No, we are working currently on the next alpha release, I'm gonna look at it after release.

**Comment by enesozturk** [comment]
@jmysliv Oh cool, that is ok then 👍🏽

**Comment by tjzel** [comment]
I tried to reproduce the problem with Reanimated 3.6.1 but even after bumping required packages I couldn't get the app to build correctly with the error `Unable to resolve "react-native-hold-menu" from "src/App.tsx"` - if you want us to investigate the issue further please upgrade your library.
