### ISSUE TITLE
Support for SVG, Canvas, and/or Victory

### ISSUE THREAD

**Issue by ericvicenti** [software-mansion/react-native-reanimated#210]
I have some graphs that are in desperate need of animation.

My normal go-to for graph work in RN is victory/(victory native), but I could also work with SVGs or even RN Canvas.

What do y'all recommend for a short term solution? What would be the best long-term approach to put on the roadmap?

**Comment by wcandillon** [comment]
Shape animations seems to work well already (https://www.youtube.com/watch?v=rkUuxN21hOA).
Regarding path animation, it seems that you can set a string to an Animation value on iOS and everything works well (this string value could be an SVG Path). However this technic doesn't seem to work on Android (getting a ValueNode cannot be cast to a number exception).

**Comment by jakub-gonet** [comment]
Hi @ericvicenti,
I'm really sorry that this issue wasn't noticed.

If you still face this problem you can try using `createAnimatedComponent` with [react native SVG path component](https://github.com/react-native-community/react-native-svg#path) and animating.

If you have further questions feel free to ask.
