### ISSUE TITLE
[REASetNode beginContext:prevCallID:]

### ISSUE THREAD

**Issue by canpoyrazoglu** [software-mansion/react-native-reanimated#2109]
## Description

I'm not using Reanimated myself directly, but when I encounter a component which uses Reanimated behind the scenes (in this case React Native Draggable FlatList https://github.com/computerjazz/react-native-draggable-flatlist) my app immediately crashes with an Objective-C exception:

`-[REASetNode beginContext:prevCallID:]: unrecognized selector sent to instance 0x6000015cf2f0`

Here is a screenshot of the crash from Xcode with Objective-C exceptions enabled:

![Screen Shot 2021-06-06 at 13 42 53](https://user-images.githubusercontent.com/4348413/120921599-25d14880-c6cd-11eb-9b80-099d1c16be80.jpg)

Since it's an internal crash from React Native Reanimated native code itself, I think it's caused by something within the Reanimated library, not the library that is using it. I haven't checked this part of the app for weeks, and it was working since I last checked, and made many version bumps in the meantime so I don't know at which exact point it started breaking.

I've also stumbled upon a React Native JS warning which appears right before this crash occurs but I'm not sure if it's related or just coincidence:

`ReactNativeFiberHostComponent: Calling getNode() on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.`

### Expected behavior

It should not crash and it should work normally.

### Actual behavior & steps to reproduce

Have a draggable flat list (https://github.com/computerjazz/react-native-draggable-flatlist). It doesn't even need to have any items, empty `[]` data is sufficient to reproduce the bug.
Render that list anywhere in the app.
Whole app crashes with a native Objective-C exception as above, originating from `REACallFuncNode.m` file.

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.0
- NodeJS: 14.9
- Xcode: 12.5
- Java & Gradle: n/a (working with only iOS)

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

This happens both on simulator (iPhone 12) and actual device (iPhone 12 Pro Max) both running iOS 14.5.
(Haven't checked anything but iOS. Maybe they crash on others too)

**Comment by jmysliv** [comment]
@canpoyrazoglu I couldn't reproduce that crash, however, it seems to be related with this issue: computerjazz/react-native-draggable-flatlist#277 and the fact that they still don't support reanimated v2: computerjazz/react-native-draggable-flatlist#247. 
If you still encounter this issue, can you please provide some more detailed code example so I could reproduce it?

**Comment by canpoyrazoglu** [comment]
@jmysliv After reverting back to Reanimated v1.x, I can confirm that the problem went away.

**Comment by computerjazz** [comment]
That would be a shame if there were breaking backwards compatibility changes in reanimated v2. 
I am unable to upgrade react-native-draggable-flatlist to reanimated v2 because it is much less performant than v1 for the use case (react-native-draggable-flatlist uses lots of optimized `proc` nodes that are much more performant than the corresponding `useDerivedValue`, see discussion here: https://github.com/software-mansion/react-native-reanimated/discussions/1632).
