### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by quarrant** [software-mansion/react-native-reanimated#211]
I had an error with pod install... package.json version is 1.0.0-alpha.12, but last github version is 10..

[!] Error installing RNReanimated
[!] /usr/local/bin/git clone https://github.com/kmagiera/react-native-reanimated.git /var/folders/db/ywc4ccn105ld2lp7s1wr_7v40000gn/T/d20190314-74626-c4u5ip --template= --single-branch --depth 1 --branch 1.0.0-alpha.12

**Comment by jakub-gonet** [comment]
Hey @quarrant,
I'm really sorry this issue went unnoticed 😔

If you're still facing this problem please reopen this issue, I'm happy to help you resolve it
