### ISSUE TITLE
v2.3.0-alpha.1 Tried to synchronously call function {_createForOfIteratorHelperLoose} from a different thread

### ISSUE THREAD

**Issue by myckhel** [software-mansion/react-native-reanimated#2120]
## Description
Error when ran the `v2.3.0-alpha.1` on ios
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-08 at 13 13 17](https://user-images.githubusercontent.com/34090541/121183191-b9d11a80-c85b-11eb-9ba0-5f62084083ec.png)

### Expected behavior
Run app without error

### Actual behavior & steps to reproduce
- yarn add react-native@alpha
- pod install
- xcode build project
- run project

## Package versions

- React Native: v0.64.2
- React Native Reanimated: v2.3.0-alpha.1
- Xcode: 12.4

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by diego-paired** [comment]
Same issue, with `Hermes` enabled on iOS

**Comment by alexpchin** [comment]
Which version is this fix available in? It's not been pushed to v2.3.0-alpha.1 has it?

**Comment by myckhel** [comment]
> Which version is this fix available in? It's not been pushed to v2.3.0-alpha.1 has it?

i dont think so.

maybe you wait for `alpha.2`

**Comment by alexpchin** [comment]
Ok, did a patch - wasn't clear which version it had been committed to. Thanks!
