### ISSUE TITLE
Invariant Violation: requireNativeComponent: "REALayoutView" was not found in the UIManager.

### ISSUE THREAD

**Issue by SAYEM5522** [software-mansion/react-native-reanimated#2127]
## Description

When I am using LayoutAnimation component from react-native-reanimated the above error is showing 
### Expected behavior
app works fine 
## Snack or minimal code example
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Animated, { AnimatedLayout, SlideInRight, SlideOutLeft } from 'react-native-reanimated';
export default function App() {
  return (
    <AnimatedLayout>
       <Animated.View 
                    entering={SlideInRight.delay(300)} 
                    exiting={SlideOutLeft.delay(300)} 
                    style={styles.left} 
                />
    </AnimatedLayout>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  left:{
    width:200,
    height:100,
    backgroundColor:'red'
  }
});

## Package versions
 "react-native-reanimated": "2.3.0-alpha.1",

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android

**Comment by jakub-gonet** [comment]
Try running `./gradlew clean` in `android/` directory and run metro with `--reset-cache` flag (i.e. yarn start --reset-cache). This will reset any build artefacts on Android and everything will be built from scratch.

**Comment by mrousavy** [comment]
Are you using expo? I don't think the latest REA alpha works on expo yet..

**Comment by SAYEM5522** [comment]
> Are you using expo? I don't think the latest REA alpha works on expo yet..
Yes,I am using Expo

**Comment by piaskowyk** [comment]
Exactly as @mrousavy said. I can confirm Expo doesn't support Reanimated in alpha version yet, but I think that new features will be available in Expo soon but before this, we want to test the layout animations.
