### ISSUE TITLE
Build failure when not using `app` on android application module 

### ISSUE THREAD

**Issue by doniwinata0309** [software-mansion/react-native-reanimated#2129]
## Description

Hi, I got build error when using reanimated V2 because my application module name is not `app`

error:
Build file '/Users/doni.winata/tvlk/district-traveloka/packages/apps/node_modules/react-native-reanimated/android/build.gradle' line: 10

Probably it related this code : https://github.com/software-mansion/react-native-reanimated/blob/master/android/build.gradle#L36

This is build.gradle inside our packages/apps/node_modules/react-native-reanimated/android/build.gradle'

```
import groovy.json.JsonSlurper;
configurations.maybeCreate("default")
def inputFile = new File(projectDir, '../../react-native/package.json')
def json = new JsonSlurper().parseText(inputFile.text)
def reactNativeVersion = json.version as String
def (major, minor, patch) = reactNativeVersion.tokenize('.')
def engine = "jsc"
if (project(':app').ext.react.enableHermes) {
    engine = "hermes"
}

artifacts.add("default", file("react-native-reanimated-${minor}-${engine}.aar"))

```
As we can see it trying to read `app` modules, while we are using `appentry` name on our app module.

### Expected behavior
Using any name on application module should works
### Actual behavior & steps to reproduce
Not using `app` name on application module will failed the build

**Comment by brijeshvishwanath** [comment]
We are facing this issue too, our app module name is different and this hardcoding of app module is blocking us currently.

**Comment by Szymon20000** [comment]
Do you know any way for accessing the main module name?  If not then I think we need to add a possibility to pass that name to reanimated. Maybe by setting rootProject.ext.mainModuleName variable. What do you think?

**Comment by doniwinata0309** [comment]
That may be a way to do it. Maybe there is also another way from gradle task to scan module that applying android application, and get the name. But not sure as well, i am not so familiar authoring gradle plugin.

**Comment by doniwinata0309** [comment]
Maybe something like this
```
    pluginManager.withPlugin("com.android.application") {
        //do something
    }
```
