### ISSUE TITLE
Does not build using react-native 0.65.0-rc.0 on Android

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#2131]
## Description

Opening this so it can be tracked, I realize it's super early for 0.65.

I just tried updating a project to react-native v0.65.0-rc.0 but reanimated makes the build fail on Android.

### Expected behavior

Build should succeed.

### Actual behavior & steps to reproduce

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-65-hermes.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: .../node_modules/react-native-reanimated/android/react-native-reanimated-65-hermes.aar.
         > Transform's input file does not exist: .../node_modules/react-native-reanimated/android/react-native-reanimated-65-hermes.aar. (See https://issuetracker.google.com/issues/158753935)
```

## Snack or minimal code example

Upgrade `react-native` to `0.65.0-rc.0` and run `react-native run-android`

## Package versions

- React Native: 0.65.0-rc.0
- React Native Reanimated: 2.2.0

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by andreialecu** [comment]
Ref: https://github.com/react-native-community/releases/blob/e0636e5aa858320e9695a9c252849d5c97783507/CHANGELOG.md

**Comment by Szymon20000** [comment]
Thank you for opening the issue. We will take care of this when react native 0.65 is closer to release.

**Comment by myckhel** [comment]
Release candidate 1 released https://github.com/facebook/react-native/releases/tag/v0.65.0-rc.1

Please if you can make the support fast 🙏🏽 .

We are willing to test the alpha versions at early stages but its not good for reanimated to always be the one blocking from testing the alpha versions.

**Comment by mrousavy** [comment]
@Szymon20000 @piaskowyk why do you build separate `.aar`s for each react native version in the first place? You're not linking any react native specific code with the `.aar` anyways

**Comment by piaskowyk** [comment]
Some .so libs are incompatible between versions. Temporary solution is here and works: https://github.com/software-mansion/react-native-reanimated/pull/2167
But like you said, 8 aars is too much, so I and Szymon will try to find a better solution.

**Comment by san-Gold** [comment]
My project is solved in this way：
yarn add react-native-reanimated@^2.3.0
