### ISSUE TITLE
Not working in react-native-web 

### ISSUE THREAD

**Issue by sdevansh96** [software-mansion/react-native-reanimated#2132]
Hello,

I am using react native reanimated version (2.2.0).
It is working fine for ios and android but if I use it for web (react-native-web) it is giving error in the chrome console and the application is crashing in web.
Same issue is if I add @react-navigation/drawer, getting the same error in web.

Is there anyway to ignore or run react native reanimated in web.?

**Comment by Szymon20000** [comment]
@sdevansh96 I've just ran reanimated (master version) on web and everything works fine. Please, add more details.

**Comment by sdevansh96** [comment]
Hello @Szymon20000 

Attaching the screen shot of the error

<img width="859" alt="Screenshot 2021-06-15 at 2 44 30 PM" src="https://user-images.githubusercontent.com/20424016/122027205-899ff380-cde8-11eb-91e5-09a7bf4e18f7.png">

**Comment by sdevansh96** [comment]
If I remove all the code containing react-native-reanimated code, then the web is working but if I add   @react-navigation/drawer from react navigation then also facing the same error as mentioned above.

For the rest of the navigators (@react-navigation/stack, @react-navigation/bottom-tabs ) web is working fine and not getting the process error.

**Comment by saikatkundu** [comment]
If I  add  import {createDrawerNavigator} from '@react-navigation/drawer' in my code I'm getting the following error

`ERROR in ./node_modules/react-native-reanimated/lib/createAnimatedComponent.js 448:8
Module parse failed: Unexpected token (448:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       });
|       return (
>         <Component {...props} ref={this._setComponentRef} {...platformProps} />
|       );
|     }
 @ ./node_modules/react-native-reanimated/lib/Animated.js 2:0-64 11:8-31 12:8-31 13:9-32 14:14-37 15:2-25
 @ ./node_modules/@react-navigation/drawer/lib/module/views/Drawer.js 7:0-47 36:4-12 54:26-40 55:25-39 357:62-75 362:40-53 386:43-56 390:77-90 392:41-54
 @ ./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js 10:0-30 197:38-44
 @ ./node_modules/@react-navigation/drawer/lib/module/index.js 9:0-59 9:0-59`

**Comment by gust42** [comment]
add this to DefinePlugin in webpack.config.js
```
__DEV__: process.env,
```

**Comment by marcuzgabriel** [comment]
In your compileNodeModules remember to add @react-navigation/drawer if its not already resolved

In your plugins try to add this:
```Javascript
plugins: [
    new HtmlWebpackPlugin({
      template: path.join(__dirname, 'index.html'),
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      // See: https://github.com/necolas/react-native-web/issues/349
      process: {
        env: { },
      },
        __DEV__: JSON.stringify(true),
    }),
  ],
```

**Comment by sdevansh96** [comment]
@gust42,  @marcuzgabriel 

Thank you guys for the help, both the solutions are working.
