### ISSUE TITLE
withTiming callback with hook useState crash application on android 

### ISSUE THREAD

**Issue by SusulAdam** [software-mansion/react-native-reanimated#2134]
## Description

When i use hook useState in withTiming callback application crashes and turn of on android. I don't have any errors

### Expected behavior

Animation should stop and  assign appropriate values ​​to useState hook

### Actual behavior & steps to reproduce

Just try component below: 

## Snack or minimal code example

```
const Counter = () => {
	const [count, setCount] = useState(0);

	const animationValue = useSharedValue(0);

	const animatedBackground = useDerivedValue(() => {
		return interpolateColor(animationValue.value, [0, 1], ['#2a2055', '#ad2424']);
	});

	const animationStyle = useAnimatedStyle(() => {
		return {
			backgroundColor: animatedBackground.value,
		};
	});

	const startAnimation = () => {
		animationValue.value = withTiming(
			1,
			{
				duration: 200,
			},
			(isFinished) => {
				if (isFinished) {
					setCount(0);
				}
			}
		);
	};

	return (
		<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
			<Pressable
				style={{ margin: 30, width: 50, height: 50, backgroundColor: 'blue' }}
				onPress={() => setCount(count + 1)}
			>
				<Text style={{ fontSize: 30, textAlign: 'center', color: 'white' }}>{count}</Text>
			</Pressable>
			<TouchableWithoutFeedback onPress={() => startAnimation()}>
				<Animated.View style={[animationStyle, { width: 100, height: 100 }]} />
			</TouchableWithoutFeedback>
		</View>
	);
};
```

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.2.0
- NodeJS: 14.16.1
- Gradle: 6.7

## Affected platforms

- [x] Android

**Comment by Szymon20000** [comment]
You have to wrap setCount call into `runOnJS()` because animations' callbacks are wrokletized automatically. 
```js
runOnJS(setCount)(0);
```

**Comment by NikkiDelRosso** [comment]
No error message is displayed, just a hard, silent app crash. I was also trying to trigger a state change at the end of an existing animation.

Is there some way that we can get inline documentation for the `withTiming` to explain this requirement to save future devs from the pain that I went through here to find out _what_ was crashing, then _why_ it was crashing? That or an error message as a fallback would be immensely helpful.

The current documentation on these is pretty light and this is a situation that could use more detail, as it was pretty a unexpected syntax requirement:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/563879/203406231-98eb731a-09e8-4bc2-bce3-977f6435285a.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/563879/203406257-863f35ef-6d36-4550-886b-67efefe999ba.png">

**Comment by KrisLau** [comment]
@Szymon20000 I agree with @NikkiDelRosso the callback really doesn't have any examples or warning in the documentation.

**Comment by olimexsmart** [comment]
This is still absolutely valid. Moreover, `runOnJS` is now deprecated
