### ISSUE TITLE
Crash: Prevents using React Native Sampling Profiler on Hermes/Android

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#2143]
## Description

Using the Sampling Profiler with Hermes on Android makes the app crash as soon as the profiling is stopped.

There is a comment by a React Native maintainer in https://github.com/facebook/hermes/issues/491#issuecomment-816121451 which mentions this is caused by reanimated's threading.

> Thanks for reporting this. It seems like reanimated works by scheduling Hermes runtimes on multiple threads. I'm not familiar with how reanimated is set up, but our sampling profiler does not currently automatically support moving a given runtime between threads, so it is likely that the sampling profiler crash is a result of that.

> We would need more information about how reanimated handles the runtime to get a sense for what the problem might be with the debugger.

I'm trying to debug some Android performance issues and Reanimated seems to be preventing me from it.

It seems that the React Native team may be willing to help with this, if someone could answer the query above.

### Expected behavior

Shouldn't crash.

### Actual behavior & steps to reproduce

Crashes

## Snack or minimal code example

I think it happens by default as soon as reanimated is used. 

On Android: Open the developer menu and enable sampling profiler, after a few seconds, disable it.

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.2.0

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by andreialecu** [comment]
Crash dump is in: https://github.com/facebook/hermes/issues/491#issuecomment-815826343

**Comment by yinshurman** [comment]
same issues .
The most annoying thing is that reanimated  causes React native remote debugging tools like  RNDebugger or chrome debugger crash , so i changed to flipper, now   it is reanimated again that causes the sampling profiler crash ! 
You Reanimated just blocked every path to debugging😂

**Comment by dannyhw** [comment]
Same for us also, any workaround for this?

**Comment by pinkbluein** [comment]
Updating it to version 2.2.4 solves this issue. Was facing the same above-mentioned issue with version 2.2.0.

**Comment by pinkbluein** [comment]
Same for me, any workaround?

**Comment by CloudCityxx** [comment]
Same for me, any workaround?

**Comment by JulianKingman** [comment]
So is the final solution to disable the sample profiler? I'm trying to sample my android app, but it crashes every time. Is there a way to use the profiler? Will there be a way? Can I help make a way? Thanks!
