### ISSUE TITLE
useAnimatedStyle not setting backgroundColor on prop updates when element is conditionally outputted

### ISSUE THREAD

**Issue by simongoot** [software-mansion/react-native-reanimated#2144]
## Description

We have a carousel which has buttons for navigation in the bottom. On the last slide a button is conditionally outputted based on a state "isLastSlide".
The button is disabled per default and then controlled by another state "buttonDisabled" to turn active and get the call-to-action color.

We use useAnimatedStyle hook to animate backgroundColor of the button, but in this case, the button stays with disabled state appearance (grey color) no matter what the state of props tell the button to become during carousel swiping.
When we log the values inside the Button component all of it is set correctly, even within the worklet that controls the buttonBackground color.

### Expected behavior
Button should change appearance based on prop updates when the element is outputted conditinally.

### Actual behavior & steps to reproduce
Button only appear in initially rendered state and props does not update appearance in UI. Solution needed was to use display: none style instead of an IF condition for the component.

1. Add a component with useAnimatedStyle hook that set backgroundColor based on a disabled prop.
2. Conditionally output the component by a state-change (for example if slide-index is the last one)
3. Navigate to the last slide.

## Snack or minimal code example

Conditional button output:

```
{isLastSlide && 
    <Button
        disabled={buttonDisabled}
        buttonColor="buttonCtaColor"
    >
        ButtonTitle
    </Button>
}
```

In buttonComponent:

```
const buttonDisabledStyles = useAnimatedStyle(() => {
    return { backgroundColor: props.disabled ? '#555555' : '#000000' };
});
```

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.1.0

## Affected platforms

- [ x ] Android
- [ x ] iOS
- [ x ] Web

**Comment by hashedname** [comment]
I think you're missing a dependency, try with:

```
const buttonDisabledStyles = useAnimatedStyle(() => {
    return { backgroundColor: props.disabled ? '#555555' : '#000000' };
}, [props.disabled]);
```

**Comment by simongoot** [comment]
> I think you're missing a dependency, try with:
> 
> ```
> const buttonDisabledStyles = useAnimatedStyle(() => {
>     return { backgroundColor: props.disabled ? '#555555' : '#000000' };
> }, [props.disabled]);
> ```
> 
> By the way, is there anything more in the animated style? You don't need to use useAnimatedStyle with that style only.

Dependencies does not make any difference, we have tried all that.

Yes there is more, i just simplified the code example as much i could.
How would you do without using useAnimatedStyle?

**Comment by hashedname** [comment]
I'd leave only animated style inside `useAnimatedStyle` and move all the other style outside, like:

```
const buttonDisabledStyle = { backgroundColor: props.disabled ? '#555555' : '#000000' };
const animatedStyle = useAnimatedStyle(() => {
   // ...
});

return (
   <Animated.View style={[buttonDisabledStyle, animatedStyle]}>
      {/* ... */}
   </Animated.View>
);
```

**Comment by thespacemanatee** [comment]
> I'd leave only animated style inside `useAnimatedStyle` and move all the other style outside, like:
> 
> ```
> const buttonDisabledStyle = { backgroundColor: props.disabled ? '#555555' : '#000000' };
> const animatedStyle = useAnimatedStyle(() => ({
>    opacity: mySharedValue.value,
>    // ...
> }));
> 
> return (
>    <Animated.View style={[buttonDisabledStyle, animatedStyle]}>
>       {/* ... */}
>    </Animated.View>
> );
> ```
> 
> which should work as you expect.

In Reanimated 2, you have to include all styles in `useAnimatedStyles`. It doesn't support concatenating styles like in v1.

**Comment by jsellam** [comment]
Hi, I have the same problem with useAnimatedStyle dependencies in (reanimated 2.2.0)

 ```
 const usersStyle = useAnimatedStyle(() => {
    const py = interpolate(
      slide.value,
      [0, 0.5, 1],
      [0, 20, 80],
      Extrapolate.CLAMP,
    );
    return {
      position: 'absolute',
      bottom: isLandscape ? 16 : 100,
      left: 0,
      transform: [{translateY: py}],
    };
  }, [isLandscape]);
```

So, I will try to separate animated styles & not animated styles.

Is it a bug ?

@hashedname you should use useMemo to combine your styles in an array ^^

**Comment by thespacemanatee** [comment]
> Hi, I have the same problem with useAnimatedStyle dependencies in (reanimated 2.2.0)
> 
> ```
> const usersStyle = useAnimatedStyle(() => {
>    const py = interpolate(
>      slide.value,
>      [0, 0.5, 1],
>      [0, 20, 80],
>      Extrapolate.CLAMP,
>    );
>    return {
>      position: 'absolute',
>      bottom: isLandscape ? 16 : 100,
>      left: 0,
>      transform: [{translateY: py}],
>    };
>  }, [isLandscape]);
> ```
> 
> So, I will try to separate animated styles & not animated styles.
> 
> Is it a bug ?
> 
> @hashedname you should use useMemo to combine your styles in an array ^^

You should create styles outside of the component as shown by @hashedname, and combine them with this syntax 
```js
<Animated.View style={[unAnimatedStyle, animatedStyle]}>
      {/* ... */}
   </Animated.View>
```
Animated Styles only respond to shared value changes and not generic javascript expressions.

**Comment by jmysliv** [comment]
@thespacemanatee has a point. If you want to animate backgroundColor use shared value, which you can set using `useEffect` hook. You can do something like that:

```js
const backgroundColor = useSharedValue(0);
useEffect(() => {
    if (disabled){
        backgroundColor.value = withTiming(0);
    } else {
        backgroundColor.value = withTiming(1);
    }
}, [disabled]);

const buttonDisabledStyles = useAnimatedStyle(() => {
    return {
        backgroundColor: interpolateColor(
            backgroundColor.value,
            [0, 1],
            ['#555555', '#000000'],
        ),
    }
})
```

**Comment by JDMathew** [comment]
I had a similar issue but it was because my dependent props were not stateful
