### ISSUE TITLE
[Android] Crash when going to next screen use Reanimated 

### ISSUE THREAD

**Issue by trilam1409** [software-mansion/react-native-reanimated#2150]
## Description
There are some issues with the Android build. I track on Firebase Crashlytic show (only Android):

``
Crashed: Thread #1
SIGABRT 0x0000000000000000
0   libc.so                                                         (Missing)
1   libc.so                                                          (Missing)
2   libc++_shared.so                                        (Missing)
3   libc++_shared.so                                        (Missing)
4   libreanimated.so                                        (Missing)
5   libreanimated.so                                        (Missing)
6   libreanimated.so                                        (Missing)
7   libhermes-executor-common-release.so (Missing)
8   libhermes.so                                              (Missing)
9   libhermes.so                                              (Missing)
10 libhermes.so                                              (Missing)
11  libhermes.so                                              (Missing)
12  libhermes.so                                             (Missing)
13  libhermes.so                                             (Missing)
14  libhermes.so                                             (Missing)
15  libhermes.so                                             (Missing)
16  libreanimated.so                                       (Missing) 
``

### Expected behavior
No crash

### Actual behavior & steps to reproduce
The user crash on some devices.
I don't how to reproduce these cases.

## Snack or minimal code example
`
import React, {forwardRef, useRef, useImperativeHandle, useEffect} from 'react';
import Styles from './styles';
import {PRIMARY_RED, DEFAULT_TEXT_FIELD} from '../../styles/Colors.variable';
import {Input} from './index';
import Icon from '../Icon/IconComponent';
import {View} from 'react-native';
import Animated, {
  useAnimatedStyle,
  withTiming,
  useSharedValue,
} from "react-native-reanimated";

type Types = {
  errors?: object;
  touched?: boolean;
  label?: string;
  style?: object;
  value: string;
  [x: string]: any;
};

const InputPipe = forwardRef(
  ({errors, touched, label, value, style, ...props}: Types, ref: any) => {

    const isError = touched && errors;
    const transformX = useSharedValue(0);
    const transformY = useSharedValue(0);
    const scale = useSharedValue(1);
    const inputRef = useRef();
    useImperativeHandle(ref, () => ({
      focus: () => {
        inputRef.current.focus();
      },
    }));

    useEffect(() => {
      if (value.length) {
        transformX.value = -4;
        transformY.value = -25;
        scale.value = 0.9;
      }
    }, []);

    const labelAnimatedStyle = useAnimatedStyle(() => {
      return {
        transform: [
          {translateX: withTiming(transformX.value, {duration: 200})},
          {translateY: withTiming(transformY.value, {duration: 200})},
          {scale: withTiming(scale.value, {duration: 200})},
        ],
      };
    });

    const _labelPress = () => {
      inputRef.current.focus();
    };

    return (
      <View>
        <Input
          ref={inputRef}
          {...props}
          style={[Styles.pipeInput, style]}
          placeholderTextColor={DEFAULT_TEXT_FIELD}
          value={value}
          onFocus={() => {
            transformX.value = -4;
            transformY.value = -25;
            scale.value = 0.9;
          }}
          onBlur={() => {
            if (value.length === 0) {
              transformX.value = 0;
              transformY.value = 0;
              scale.value = 1;
            }
          }}
          right={
            isError && (
              <Icon icon={'alert-circle-outline'} color={PRIMARY_RED} />
            )
          }
        />
        {label && (
          <Animated.Text
            onPress={_labelPress}
            style={[Styles.pipeInputLabel, labelAnimatedStyle]}>
            {label}
          </Animated.Text>
        )}
      </View>
    );
  }
);
export default InputPipe;`

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.1.0
- NodeJS: 15.11.0
- Java & Gradle: 15.0.1 & 6.7.1

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by Szymon20000** [comment]
It seems like it's not a problem with reanimated but with React native itself. https://github.com/facebook/react-native/issues/29978 Closing this tentatively. Feel free to reopen if you think it's our bug.

**Comment by BooYeu** [comment]
Maybe something wrong with react-native-reanimated when use useImperativeHandle and ref in it
[https://github.com/facebook/react-native/issues/32105](url)
[https://github.com/enesozturk/react-native-hold-menu/issues/43](url)
@Szymon20000

**Comment by BooYeu** [comment]
It shows error in all platform
