### ISSUE TITLE
App crashes when connected to debugger & and often destroyed when it was made into a production application

### ISSUE THREAD

**Issue by dodiwknd** [software-mansion/react-native-reanimated#2155]
## description
app crashes when connected to debugger

### Actual behavior in dev mode
when I connect to the debugger, the app crashes immediately

### Actual behavior in production mode
the application often occurs force close

### Message from sentry in dev mode
![image](https://user-images.githubusercontent.com/82150448/123505443-53d0f980-d689-11eb-96d4-29ba41388883.png)
![image](https://user-images.githubusercontent.com/82150448/123505461-69deba00-d689-11eb-9004-5d98079badc3.png)

## Message from sentry when it is a production application
![image](https://user-images.githubusercontent.com/82150448/123505552-fe491c80-d689-11eb-87c8-f91f366e0d67.png)
![image](https://user-images.githubusercontent.com/82150448/123505561-07d28480-d68a-11eb-8006-4e1714f9a88a.png)

## Package versions

- React Native: 6.4
- React Native Reanimated: 2.2.0
- NodeJS: v14.x.x
- Xcode: 
- Java & Gradle: 8, 6.5
-  RN debuger: 0.10.13

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by thespacemanatee** [comment]
If you did read the docs, they have already mentioned that Reanimated 2 is incompatible with remote JS debugger. The only debugger you can currently use is Flipper. I understand where the frustration comes from though because it took me days before coming across the tiny notice about this issue in the docs.

**Comment by henrymoulton** [comment]
I think right now the UX is not good for Reanimated 2 users who are using Hermes. https://github.com/facebook/hermes/issues/541

**Comment by dodiwknd** [comment]
thanks @thespacemanatee  for telling me i finally forced to use flipper for the current debugger.

btw @henrymoulton I don't use `hermes` for my project

**Comment by jmysliv** [comment]
Fixed by #2197

**Comment by jaexplorer** [comment]
I want to start using reanimated across the main parts of my app. But I use react dev tools debugger alot for debugging production errors, redux, etc with our large user base. If I use reanimated on these screens, the app will crash when I visit them. 

Is it in the roadmap to address this? Is there a way for it to ignore reanimated so I can still use the debugger for other things on those screens?
