### ISSUE TITLE
Cannot build production on Android

### ISSUE THREAD

**Issue by jeffreyjw** [software-mansion/react-native-reanimated#2160]
## Description

Making a production build with `./gradlew ":app:bundleRelease"` yields an error message: 

```
error node_modules/react-native-reanimated/src/reanimated2/interpolation.ts: node_modules/react-native-reanimated/src/reanimated2/interpolation.ts: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "BooleanLiteral".
```

### Expected behavior

Should build without error, as dev mode builds correctly

### Actual behavior & steps to reproduce

Go through the install instructions and build with `./gradlew ":app:bundleRelease". `react-native run-android` works correctly

## Package versions

- React Native: 0.63.3,
- React Native Reanimated: ^2.3.0-alpha.1
- NodeJS: v12.13.1
- Xcode: 12.2 (Build version 12B45b) (has the same problem as android)
- Java & Gradle: 
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Ubuntu 11.0.7+10-post-Ubuntu-2ubuntu219.10)
OS:           Linux 5.3.0-64-generic amd64

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by jakub-gonet** [comment]
This looks like the Babel plugin was only enabled for development, can you check that?

**Comment by piaskowyk** [comment]
@jeffreyjw Thanks for your submission 🙌
