### ISSUE TITLE
Web - Animation stops working if Animated Component is removed and re-attached to the DOM 

### ISSUE THREAD

**Issue by mrsimply** [software-mansion/react-native-reanimated#2179]
## Description

I need to completely remove a component once in a while and re-attach it to the DOM later again, e.g. if a component is currently visible or invisible. On the web however **Animated Components stop working** once they are **removed and re-attached** to the DOM. However it works perfectly well in native.

### Expected behavior

Animations should continue working on the web when they are removed and re-attached to the DOM - as they do in native.

### Actual behavior & steps to reproduce

https://user-images.githubusercontent.com/52707816/124557760-2549e000-de3a-11eb-8cdf-328b9d246954.mov

```jsx
import Slider from '@react-native-community/slider';
import React, { useState } from 'react';
import { Button, Text, View } from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';

const App = () => {
  const [visible, setVisible] = useState(true);
  const scale = useSharedValue(1);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      backgroundColor: 'yellow',
      padding: 20,
      transform: [{ scale: scale.value }],
    };
  });

  return (
    <View style={{ flex: 1 }}>
      <View style={{ flexDirection: 'row', padding: 20 }}>
        <Slider
          minimumValue={1}
          maximumValue={4}
          onValueChange={(value) => {
            scale.value = value;
          }}
        />
        <Button
          title={'Hide Animated View'}
          onPress={() => setVisible(!visible)}
        />
      </View>
      <View
        style={{
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        {visible && (
          <Animated.View style={animatedStyle}>
            <Text>I scale only once</Text>
          </Animated.View>
        )}
      </View>
    </View>
  );
};

export default App;
```

## Snack or minimal code example

I created a small repo to reproduce. Please find it here: https://github.com/mrsimply/reanimated2-bug-web

## Package versions

```JSON
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-native-reanimated": "^2.2.0",
    "react-native-web": "^0.17.1",
    "react-scripts": "4.0.3"
  },
```

## Affected platforms

- [ ] Android
- [ ] iOS
- [X] Web

**Comment by jmysliv** [comment]
This issue seems to be resolved by #1470. I modified your example and tested it and it worked properly.

https://user-images.githubusercontent.com/48885911/126750308-28410399-2c39-414d-afe8-666ba31a43ce.mov
