### ISSUE TITLE
 Error: Requiring module "node_modules/react-native-reanimated/src/animations/decay.js", which threw an exception: TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

### ISSUE THREAD

**Issue by naxir** [software-mansion/react-native-reanimated#2189]
Error: Requiring module "node_modules/react-native-reanimated/src/animations/decay.js", which threw an exception: TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

After installing react-native-reanimated 
when i import  import {Transition, Transitioning} from 'react-native-reanimated';
Then I'm facing above error:

Version Details are
 "react": "^17.0.2",
  "react-native": "^0.64.2",

**Comment by jakub-gonet** [comment]
Isn't this a duplicate of #2146?

**Comment by naxir** [comment]
@jakub-gonet  both are same

**Comment by jakub-gonet** [comment]
So I'll close this one in that case.
