### ISSUE TITLE
Please 🙏 release master with v2.3.0-alpha.2 atleast

### ISSUE THREAD

**Issue by myckhel** [software-mansion/react-native-reanimated#2214]
## Description

Please release master with alpha atleast, so that we can test [react-native v0.65](https://github.com/facebook/react-native/releases/tag/v0.65.0-rc.3)

## Package versions

- React Native: v0.65-rc.3
- React Native Reanimated: v2.3.0-alpha.2

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by piaskowyk** [comment]
@myckhel We want to release a new version next week.

**Comment by piaskowyk** [comment]
Almost everything is ready for this.

**Comment by myckhel** [comment]
Thanks 🙏
