### ISSUE TITLE
Cannot createAnimatedComponent using StatusBar  

### ISSUE THREAD

**Issue by Nazort** [software-mansion/react-native-reanimated#2226]
## Description

I'm trying to animate the Status Bar backgroundColor using reanimated, I'm creating my StatusBar as an `AnimatedStatusBar` using `createAnimatedComponent` 

### Expected behavior

Being able to create an AnimatedStatusBar using  `createAnimatedComponent`

### Actual behavior & steps to reproduce

I'm creating the `AnimatedStatusBar` like so : 

```
import Animated from 'react-native-reanimated';
import { StatusBar } from 'react-native';

const AnimatedStatusBar = Animated.createAnimatedComponent(StatusBar);

const MyComp: React.FC<Props> = ({ ... }) => {

...

   return (
         <AnimatedStatusBar
            backgroundColor={'#4a4ad5'}
         />
   )

}
```

When the screen starts rendering, I got the following error : 

```
Cannot find host instance for this component. Maybe it renders nothing ? 
```

The error is thrown in `createAnimatedComponent.js`

If I try to do the same with the react-native `Animated.createAnimatedComponent` it works without error.

## Snack or minimal code example

The above code should be enough to reproduce.

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.2.0

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web (not tested)

**Comment by jakub-gonet** [comment]
AFAIK to create an animated component from Reanimated you need to provide a component that has the underlying native view.
[StatusBar](https://github.com/facebook/react-native/blob/main/Libraries/Components/StatusBar/StatusBar.js#L491) renders nothing so it can't be animated. 

Why do you need to animate a StatusBar component?

**Comment by Nazort** [comment]
Oh I understand, now the error makes more sense, thanks. 

I wanted to animate the StatusBar backgroundColor to fix a design issue I had on Android, that was probably not the most simple way to fix it but when I had this error I got confused. I found a better solution using the `translucent` props with a transparent color so that I don't have to animate the color of the StatusBar.
