### ISSUE TITLE
Fixes: Unable to find a specification for `React-Core` depended upon by `RNReanimated`

### ISSUE THREAD

**Issue by zomars** [software-mansion/react-native-reanimated#2227]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-reanimated@1.13.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-reanimated/RNReanimated.podspec b/node_modules/react-native-reanimated/RNReanimated.podspec
index 1939eb9..60cb241 100644
--- a/node_modules/react-native-reanimated/RNReanimated.podspec
+++ b/node_modules/react-native-reanimated/RNReanimated.podspec
@@ -19,6 +19,5 @@ Pod::Spec.new do |s|
   s.source_files = "ios/**/*.{h,m}"
   s.requires_arc = true
 
-  s.dependency "React-Core"
+  s.dependency "React"
 end
-
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jakub-gonet** [comment]
Could you attach a version of the Cocoapods and React Native as well? How can we repro this issue?

**Comment by zomars** [comment]
Sure! I'm using `"react-native": "0.59.9"` and `COCOAPODS: 1.10.1`.

**Comment by zomars** [comment]
This error is happening when running `pod install`

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request.
