### ISSUE TITLE
Layout Transistions aren't firing on Android

### ISSUE THREAD

**Issue by IAmMarcellus** [software-mansion/react-native-reanimated#2228]
## Description

When using layout transitions with Reanimated 2 on Android, animations don't fire on state change and all the components in the AnimatedLayout stop responding to touch, although they work perfectly on iOS. The animations do fire if I manually change a style property on an Animated.View and then live refresh the app.

### Expected behavior
On a state change, the style properties that change should animate from one state to the next.

### Actual behavior & steps to reproduce
On a state change, the properties that should be animated as they change, either immediately change to the next state without animating or don't change at all. To reproduce, try to change the marginTop property of an Animated.View with a Layout Transition.

## Snack or minimal code example

```
const App = () => {
  const [areControlsShown, setAreControlsShown] = React.useState(true);

  const controlsHeight = 170;

  const toggleControls = () => {
    setAreControlsShown(!areControlsShown);
  };

  return (
    <AnimatedLayout>
      <SearchBar
        style={[
          styles.searchBar,
          areControlsShown ? styles.fullWidth : styles.partialWidth,
        ]}
      />
      <Animated.View
        layout={Animation.duration(500).easing(Easing.ease)}
        style={[
          styles.fullWidth,
          {
            marginTop: areControlsShown ? -50 : -100 + -1 * controlsHeight,
          },
        ]}
      >
        <Controls
          onTogglePress={toggleControls}
          areControlsShown={areControlsShown}
          height={controlsHeight}
        />
      </Animated.View>
    </AnimatedLayout>
  );
};

const Controls = (props) => {
  return (
    <Animated.View style={styles.mainContainer}>
      <View style={styles.topSpacer} />
      <View
        style={[
          themedStyles.controlsContainer,
          { height: props.height },
          props.areControlsShown
            ? styles.controlsContainerShown
            : styles.controlsContainerHidden,
        ]}
      >
        [ ... ]
      </View>
      <TouchableOpacity
        style={[
          themedStyles.toggleButton,
          props.areControlsShown
            ? styles.toggleButtonActive
            : styles.toggleButtonInactive,
        ]}
        onPress={props.onTogglePress}
      >
        <View style={styles.iconSpacer} />
        <View style={styles.controlsIconContainer}>
          <Icon
            style={styles.controlsToggleIcon}
            fill={theme["color-primary-default"]}
            name={props.areControlsShown ? "arrow-up" : "options-2-outline"}
          />
        </View>
      </TouchableOpacity>
    </Animated.View>
  );
}
```

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 1.3.0-alpha.1
- NodeJS: 16.5.0
- Xcode: 12.5.1
- Java & Gradle: 1.8.0_292 (JVM), 6.7 (Gradle)

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by jmysliv** [comment]
Hey @IAmMarcellus! I'm not sure what is this Animation object that you pass as a layout props here: 
```js
      <Animated.View
        layout={Animation.duration(500).easing(Easing.ease)}
        style={[
          styles.fullWidth,
          {
            marginTop: areControlsShown ? -50 : -100 + -1 * controlsHeight,
          },
        ]}
      >
``` 
Did you extend the Layout class, or create your own custom one? If so it will be helpful if you share that code too.
I've tried to reproduce this bug but for me, Layout Transitions works perfectly on Android. Maybe it's a cache issue, try to run: 
```bash
rm -rf ./node_modules && yarn && cd ios && pod deintegrate && pod install && cd .. && yarn start --reset-cache
```
If that won't help can you share the full example so it will be easier for me to reproduce this bug?

**Comment by IAmMarcellus** [comment]
@jmysliv Oh sorry, the "Animation" object is actually just the "Layout" object aliased because I was importing another "Layout" object and missed it when making the code generic. I think I found the root problem to this and it was different enough that I made a new issue for it: https://github.com/software-mansion/react-native-reanimated/issues/2235; and I'll close this one. That issue also includes a "full" example that you should be able to copy/paste into a new project without needing any additional code, but if its not complete enough, let me know!
