### ISSUE TITLE
runOnJS return undefined instead of the returned value of called function

### ISSUE THREAD

**Issue by esinanturan** [software-mansion/react-native-reanimated#2232]
## Description

I am running runOnJS function in useDerivedValue hook this way 
```
import React from 'react';
import {SafeAreaView, StyleSheet, Button} from 'react-native';
import {runOnJS, useDerivedValue} from 'react-native-reanimated';
import {vs} from 'react-native-size-matters';

const App = () => {
  const wrapper = value => {
    return vs(value);
  };

  const derived = useDerivedValue(() => {
    return runOnJS(wrapper)(50);
  });

  const onClick = () => {
    console.log(derived.value);
  };

  return (
    <SafeAreaView>
      <Button onPress={onClick} title="Click" />
    </SafeAreaView>
  );
};
```
in the wrapper function I am doing some other calculation normally but as an example I return the given argument but console log return undefined instead of given value

### Expected behavior

wrapper function wrapped with runOnJS should return calculated value

### Actual behavior & steps to reproduce

actual behavior is it returns undefined it can be reproduced with simply defining a wrapper function for custom calculation and 
wrapping it with runOnJS function.

## Snack or minimal code example
https://snack.expo.dev/@e.sinanturan/surprised-donut
I have tried it on web version it works but in devices it returns undefined

## Package versions

"react": "17.0.1",
"react-native": "0.64.2",
"react-native-reanimated": "^2.2.0",
"react-native-size-matters": "^0.4.0"

- React Native: 0.64.2
- React Native Reanimated: ^2.2.0
- NodeJS: v14.17.0
- Xcode: 12
- Java & Gradle: java:1.8 , gradle:6.7

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by jmysliv** [comment]
Hi, @esinanturan! The function returned by `runOnJS` is a void function, so it's why you are getting undefined, see [this](https://github.com/software-mansion/react-native-reanimated/blob/master/react-native-reanimated.d.ts#L501). Set state inside your wrapper function instead of returning value and it should work.
```js
import React from 'react';
import {SafeAreaView, StyleSheet, Button} from 'react-native';
import {runOnJS, useDerivedValue} from 'react-native-reanimated';
import {vs} from 'react-native-size-matters';

const App = () => {
  const [ value, setValue ] = useState(null);
  const wrapper = value => {
    setValue(vs(value));
  };

  const derived = useDerivedValue(() => {
    runOnJS(wrapper)(50);
    return value;
  });

  const onClick = () => {
    console.log(derived.value);
  };

  return (
    <SafeAreaView>
      <Button onPress={onClick} title="Click" />
    </SafeAreaView>
  );
};
```

**Comment by esinanturan** [comment]
@jmysliv But when i tested that code in expo snack it works in web version why is that ?

**Comment by jmysliv** [comment]
@esinanturan It worked because in the web there is only one thread and therefore `runOnJS` simply returns the function you are passing (see [this](https://github.com/software-mansion/react-native-reanimated/blob/master/src/reanimated2/core.ts#L341)). Using `runOnJS` doesn't make much sense on the web.
