### ISSUE TITLE
No export in RNRenderer for web results in esbuild warning

### ISSUE THREAD

**Issue by MixMasterMitch** [software-mansion/react-native-reanimated#2233]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-reanimated@2.2.0` for the project I'm working on.

While using esbuild to bundle a react native web package, I get the warning:
```
node_modules/react-native-reanimated/lib/createAnimatedComponent.js:14:9: warning: Import "RNRenderer" will always be undefined because the file "node_modules/react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web.js" has no exports
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web.js b/node_modules/react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web.js
index 3918c74..6e6bc5c 100644
--- a/node_modules/react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web.js
+++ b/node_modules/react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web.js
@@ -1 +1,4 @@
 "use strict";
+
+// RNRender is not used for web. An export is still defined to eliminate warnings from bundlers such as esbuild.
+module.exports = null;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jaivinwylde** [comment]
I'm getting these issues on web with expo router v2. What's going on here? Has anyone else run into this?

<img width="561" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/46613979/9bde182c-e0ec-4268-a8b8-c32ffd9da0e6">

**Comment by abhikhedekar4241** [comment]
@jaivinwylde I am getting the same error. Did you find a fix for that by any chance?

**Comment by jaivinwylde** [comment]
> @jaivinwylde I am getting the same error. Did you find a fix for that by any chance?

sorry we had to move off of expo router because this issue was preventing us from working. so I don't know what's wrong.
