### ISSUE TITLE
React-native-svg transform matrix animation not occuring.

### ISSUE THREAD

**Issue by ACregan** [software-mansion/react-native-reanimated#2252]
## Description

My app is a landscape orientation fixed game. It has a Animated Group (react-native-svg) called AnimatedXylophoneGroup which I wish to scale and transition into view from the bottom of the screen. I am attempting to acheive this by using useSharedValue to transition the values from '1.8' to '1' and using that to calculate the transform matrix (I have also attempted this using translate and scale properties - neither works as expected)

### Expected behavior
The AnimatedXylophoneGroup of Polygons should transition and scale from off the bottom of the view into view as the shared value tweens from 1.8 to 1.

### Actual behavior & steps to reproduce
No transition occurs, although the sharedValue does update.

https://snack.expo.dev/@c0un7z3r0/b21698

## Package versions
    "expo": "~42.0.1",
    "expo-app-loading": "^1.1.2",
    "expo-asset": "~8.3.2",
    "expo-av": "~9.2.3",
    "expo-screen-orientation": "~3.2.1",
    "expo-status-bar": "~1.0.4",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-reanimated": "~2.3.0-alpha.1",
    "react-native-svg": "12.1.1",
    "react-native-web": "~0.13.12"

Node v14.17.3

## Affected platforms

- [ x] Android
- [ untested ] iOS
- [ untested ] Web

VISUALS:
Should transition from:
![image](https://user-images.githubusercontent.com/6025693/128137982-02be3dd8-0c1a-4c7e-95ad-39e0c21c8dc0.png)
To:
![image](https://user-images.githubusercontent.com/6025693/128138015-95b1c3b6-911e-4258-a524-ef6b2098f49e.png)
Screenshots taken on Google Pixel 3xl

**Comment by ACregan** [comment]
Thanks so much, Its not the exact effect I wanted but It gives me a starting point to work from.  
Just for my own understanding, am I correct in thinking that if you want to transition props (which I do - specifically the transform='matrix...' property on the AnimatedXylophoneGroup then I should use 'useAnimatedProps'? 
I only ask because it seems my use case is valid for useAnimatedProps and I beleive my implementation was correct but as you can see it doesnt work. I just want to understand if my implementation is wrong or if the 2.3.0-alpha version of the library does not yet have this particular property configured properly yet?
Once again, Thanks for your help.

**Comment by fabioportieri** [comment]
yes i think your implementation was correct too since transform is a property of svg g element, but apparently you can't use it that way.. luckily for your usecase i think you can set up a withSequence() of different scale / translate animations with a common css transform and achieve the same result..

**Comment by ACregan** [comment]
Rolling back to 2.2.0 seems to make it work with the scale and translate but matrix still does not work.

**Comment by ACregan** [comment]
Finally achevieved the effect I wanted:
https://snack.expo.dev/@c0un7z3r0/sadistic-bacon-update
Its worth noting for anyone with a similar issue, working with 2.2.0 or react-native-reanimated on expo was required, it just crashes out on 2.3.0-alpha at the time of writing. Thanks to @fabioportieri  for the help!

**Comment by haibert** [comment]
Hey guys, maybe someone here can help me out...
Im stuck in the same scenario as #1302. I want to Animate the d on a SVG from one path to another.. the interpolator that ships with reanimated doesn't seem to work for this if I understand correctly? which is why people use 
`import { interpolatePath } from 'd3-interpolate-path'` 
issue with this is it doesn't run on the UI thread. So how can one animate the d on an animated SVG component from one path to another ?

**Comment by jmysliv** [comment]
Hi, @ACregan! Have you tried to create a props adapter as described in the [docs](https://docs.swmansion.com/react-native-reanimated/docs/api/useAnimatedProps#createanimatedpropadapter). It can look something like [this](https://github.com/software-mansion/react-native-reanimated/blob/master/src/reanimated2/PropAdapters.ts#L5) and I think it's perfect for your use case. Let me know if it worked!

**Comment by ACregan** [comment]
Hi @jmysliv, 

I solved that problem satisfactorily but the timing of your reply is impeccable! Im now trying to rotate a group using ``` transform={rotate(a, x y)}``` and struggling with that and I think that writing an adaptor that transforms that syntax into transformMatrix would solve the problem. 
This is my first time using this library (or expo/react-native for that matter), so I dont have that required experience to have confidence that the problem is with the library - I keep thinking that its probably my implementation that is at fault. Its the only way to learn I suppose!

Thanks for getting in touch.

**Comment by jmysliv** [comment]
@ACregan okay, I'm gonna close this issue then. Keep learning and if you have any questions feel free to ask. Also if you find out that there is certainly a problem with reanimated and not your implementation, ping me and I'll reopen this issue.

**Comment by ACregan** [comment]
Hi @jmysliv, I think the issue is still valid. The matrix transition seemed like a correct implementation (https://snack.expo.dev/@c0un7z3r0/b21698) but did not work. Likewise I am currently facing the same issue with a ```transform={rotate(a, x, y)}``` I will post a seperate issue for that shortly but these are valid properties which do not seem to transition as expected (again - if its my implementation thats at fault, appologies).

**Comment by jmysliv** [comment]
@ACregan In your snack, I can't find any props adapter, that could convert that transform props and it's probably the reason why it doesn't work. Few comments above you can find the link to the docs and an example of how such an adapter can look like.

**Comment by ACregan** [comment]
I see, I didnt realise they were required. I wrongly assumed they follow the same pattern as useAnimatedStyle and the values can be string concatenated. I'll take a look. Thanks!

BTW, I opened the issue (https://github.com/software-mansion/react-native-reanimated/issues/2295) I'll update this with a props adapter and delete/update as required. Thanks again
