### ISSUE TITLE
WIP: Using too many worklets causes UI frame drops.

### ISSUE THREAD

**Issue by JanKaifer** [software-mansion/react-native-reanimated#2260]
[ISSUE CREATION IN PROGRESS]

## Description

Using a few helper worklets (~5) in gesture event handlers is killing performance.

### Expected behavior

Helper worklets should affect performance that much (or it should be said in docs - using more than 3 worklets in the event handler is going to cost you frames).

### Actual behavior & steps to reproduce

I created few helper worklets like:

```ts
    const capValueBetween = (val: number, minVal: number, maxVal: number) => {
      'worklet';
      if (minVal > maxVal) return (minVal + maxVal) / 2;
      if (minVal > val) return minVal;
      if (maxVal < val) return maxVal;
      return val;
    };

    const capScale = (scale: number) => {
      'worklet';
      return capValueBetween(scale, minScale, maxScale);
    };

    const capX = (newX: number) => {
      'worklet';
      const limit = (contentWidth.value - width.value / scale.value) / 2;
      return capValueBetween(newX, -limit, limit);
    };

    const capY = (newY: number) => {
      'worklet';
      const limit = (contentHeight.value - height.value / scale.value) / 2;
      return capValueBetween(newY, -limit, limit);
    };
```

Then I used Panning and Pitching with gesture handler and UI thread was dropping to ~30 fpss and JS to ~15 fps.

When I inlined those functions It jumped to 58-60 fps on both UI and JS.

## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by JanKaifer** [comment]
Was unable to reproduce in snack expo. 😢

**Comment by piaskowyk** [comment]
Hi @JanKaifer 
Could you share this code? I will try to reproduce it locally on my devices. The performance issues are important for me.

**Comment by JanKaifer** [comment]
Hey, sorry I am affraid I cannot share with you our codebase, but essentially its PanHandler for moving around and Pinch Handler for zooming in. With ~20 unique worklets (with useDerivedValues and useAnimatedStyles) it was slow and when reducing that number to ~10 with duplicated code it inproved significantly.

Anyway great job with reabimated ♥️

Will try to create more complex MWE again this afternoon.

**Comment by terrysahaidak** [comment]
How many components were using useDerivedValue? 

I was facing problems when I was trying to use useAnimatedStyle. It is uses the same API as useDerivedValue under the hood.

The logic was:
- I have an image gallery component
- I have a list of images
- I tap on the image and it transitions into the gallery view
- Each image in the list uses `useAnimatedStyle` for its opacity
- When I press on the image - it sets its opacity to 0
- But when I change the active image (swipe across the gallery) it changes the previous image's opacity to 1 and the only active image is 0
- So each image's useAnimatedStyle listens to `activeIndex` share value

Since the list can have like 50-80 images in the grid it leads to big performance problems.

[This line](https://github.com/terrysahaidak/react-native-gallery-toolkit/blob/master/src/Gallery/GalleryList.tsx#L76) was causing problems.

**Comment by JanKaifer** [comment]
It was a single component with a single image that can be moved and pinched. Around ~20 worklets.

**Comment by JanKaifer** [comment]
Weird.
Recreated the whole thing in the expo. And it runs smoothly, like real smooth.
https://snack.expo.dev/@jankaifer/reanimated-example-2

I don't know if integration with my react app could be affecting performance or it can be affected by a ton of javascript running in the background in my app (reanimated1 still felt smoother in my app, even though I'm currently dipping only to ~55).

**Comment by terrysahaidak** [comment]
Could you check out the UI thread fps? 
Do you render something in the background?
Also, the expo could use a different version of Reanimated 2 and this may be a solution.
What version of Reanimated 2 did you use?

**Comment by JanKaifer** [comment]
Expo starts lagging with ~600 worklets on each move event.

1. I was talking about UI thread (ie drops to 55ish, but usually 60) JS was dipping to 19fps on larger rerenders (expected), and to 50ish on gestures
- It was slow even without background renders
- I use reanimated `2.2.0`.

I Will share a video of my app.

**Comment by terrysahaidak** [comment]
Could you try the latest alpha release? There were implemented few related perf improvements.

**Comment by chakrihacker** [comment]
@JanKaifer Can you tell which commit?

**Comment by JanKaifer** [comment]
@chakrihacker I'm not sure I know what you mean.

I just `checkout`-ed older revision of my code (old commit). Installed appropriate versions saved in `yarn.lock` and it worked fine.

So working version and slow version have exactly the same code in git.
