### ISSUE TITLE
1.0.0 iOS  ** ARCHIVE FAILED **

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [software-mansion/react-native-reanimated#228]
/node_modules/react-native-reanimated/ios/Transitioning/REAAllTransitions.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by iamacup** [comment]
I am also getting failures on 1.0.0:

`info Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_REATransitionManager", referenced from:

info       objc-class-ref in libRNReanimated.a(REAModule.o)

info ld: symbol(s) not found for architecture x86_64

info clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by iamacup** [comment]
managed to fix it with this: https://github.com/kmagiera/react-native-gesture-handler/issues/387#issuecomment-458249386

**Comment by jakub-gonet** [comment]
Hey, sorry for the late response 😔

I think this issue may be outdated now, so I'm closing it.

If the solution provided by @iamacup doesn't work for you or you have other questions regarding this issue feel free to reopen
