### ISSUE TITLE
Frame drops on Android for confetti like animation

### ISSUE THREAD

**Issue by chakrihacker** [software-mansion/react-native-reanimated#2293]
## Description

I am trying to build a confetti animation. This works perfectly fine on iOS, but on Android, both JS and UI thread frames drop to 5fps and lots of frames are dropped.

### Expected behavior

Minimal frame drop

### Actual behavior & steps to reproduce

95% of frames dropped

## Snack or minimal code example

https://gist.github.com/chakrihacker/95cb663fc6db87514643a31a64e3f23e

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2 and 2.3 alpha
- NodeJS: 16
- Java & Gradle: 1.8 and 6.7

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by terrysahaidak** [comment]
Hey. Quick question. Is this on Android Hermes?
Could you please try on a fresh React Native 0.65 with latest Hermes if so?

**Comment by chakrihacker** [comment]
App is crashing while using 0.65.

Here's what I got from Android logcat

> E/libc++abi: terminating with uncaught exception of type std::runtime_error: Unable to retrieve jni environment. Is the thread attached?

**Comment by chakrihacker** [comment]
When the app is not crashed, I definitely saw an improvement from 5fps to 10fps

**Comment by happyfloat** [comment]
I just upgraded to RN 0.65 and my Android Pixel 5 is also crashing most of the time with this error message:

> E/libc++abi: terminating with uncaught exception of type std::runtime_error: Unable to retrieve jni environment. Is the thread attached?

**Comment by kamalthebidigital** [comment]
Hello, same issue with me after upgrading react native v0.65, Please help me

**Comment by isidoro98** [comment]
Hey has anyone found the reason for this crash?
Facing the same issue with:
```
 "react-native-reanimated": "2.3.0-alpha.2",
 "react-native": "0.65.1",
```

**Comment by chakrihacker** [comment]
Commenting wouldn't solve the issue, if you want to get notified about this, you can subscribe to it

**Comment by badalsaibo** [comment]
```json
 "react-native": "0.75.4",
 "react-native-reanimated": "^3.15.4",
 "react-native-svg": "^15.7.1"
```
Notice how the frame drops as I changed the confetti from `1` to `50` and goes back up when set to `1` again

https://github.com/user-attachments/assets/cbf10197-4aa9-40d2-bd7d-a7616355656a
