### ISSUE TITLE
React-native-svg Group transform rotate transition with useAnimatedProps not working.

### ISSUE THREAD

**Issue by ACregan** [software-mansion/react-native-reanimated#2295]
## Description

I am attempting to rotate a svg group. The rotation works fine without transition however when trying to transition this value the rotation fails.

### Expected behavior

The Svg Group should rotate.

### Actual behavior & steps to reproduce
See snack - click the 'Change Note' text to select a random rotation value - it should transition between states over 0.4 seconds but the change occurs instantly.

## Snack or minimal code example

You can see from this snack that the rotation works correctly _without_ transition:
https://snack.expo.dev/0NDLxaOgv

When I attempt to transition that with ```useAnimatedProps``` then no transition occurs and no rotation is applied at all.
https://snack.expo.dev/@c0un7z3r0/nervous-salsa

## Package versions
    "expo": "~42.0.1",
    "expo-app-loading": "^1.1.2",
    "expo-asset": "~8.3.2",
    "expo-av": "~9.2.3",
    "expo-screen-orientation": "~3.2.1",
    "expo-status-bar": "~1.0.4",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-reanimated": "~2.2.0",
    "react-native-svg": "12.1.1",
    "react-native-web": "~0.13.12"

- React Native: 42
- React Native Reanimated: 2.2.0
- NodeJS: 14.17.3
- Xcode: NA
- Java & Gradle: NA

## Affected platforms

- [ x] Android
- [ untested ] iOS
- [ untested ] Web

**Comment by jmysliv** [comment]
@ACregan try defining `useAnimatedProps` llike this:
```js
 const rotateAnimatedProps = useAnimatedProps(() => {
    return {
      transform: [
        {rotate: withTiming(`${rotateTransition.value}deg`, config)},
      ]
    }
  })
```

**Comment by ACregan** [comment]
It needs to rotate around a specific point. The SVG spec for transform rotate differs from the CSS implementation, it has 3 params: angle, rotateOriginX and rotateOriginY (it also does not need the `deg` adding to the angle).  I tried a modified version of that, like so:
https://snack.expo.dev/@c0un7z3r0/nervous-salsa-update

I also tried to use css to acheive this but the transformOrigin property is not supported in react-native so I cant get the element to pivot around the point required unless I get transform rotate on this group to behave as expected.

**Comment by jmysliv** [comment]
It won't work that way cause reanimated in every frame has to parse that prop value to float to calculate the current value of the animation and it can't parse string like that `"-80 212 152"`. You have to do it in another way.

**Comment by jmysliv** [comment]
@ACregan It appeared that react-native-svg supports animation with react-native syntax only, see react-native-svg/react-native-svg#714, so I'm gonna close this issue for now.

**Comment by rissois** [comment]
Depending on your requirements, you can make 5 separate transformations:
translateX to x distance of point of rotation
translateX to y distance of point of rotation
rotate
translateX: -x
translateY: -y

**Comment by Pakile** [comment]
Hi @rissois,
I tried to like your way but it not working with G in SVG
Do you have any solutions for this? Many thanks
<img width="762" alt="Screen Shot 2022-08-04 at 21 22 12" src="https://user-images.githubusercontent.com/76195408/182870916-8295febf-6dd5-4148-ba24-323121231d52.png">

https://user-images.githubusercontent.com/76195408/182871822-9225f0a3-d3dc-4df8-9219-978851bf7d70.mov
