### ISSUE TITLE
Build fails on Android with: Cannot find symbol com.swmansion.reanimated.ReanimatedJSIModulePackage

### ISSUE THREAD

**Issue by Stophface** [software-mansion/react-native-reanimated#2310]
## Description
I try to build an Android Project. The `Gradle Build` works without an error. However, when I try to run the app on the device, I get an Error. 

### Expected behavior
I want the app to start on the emulator. 

### Actual behavior & steps to reproduce
Running the app fails with this error:
> /Users/.../android/app/src/main/java/com/mapstar/MainApplication.java:20: error: cannot find symbol
import com.swmansion.reanimated.ReanimatedJSIModulePackage; 

and

> /Users/.../android/app/src/main/java/com/mapstar/MainApplication.java:54: error: cannot find symbol
          return new ReanimatedJSIModulePackage(); // <- add
                     ^
  symbol: class ReanimatedJSIModulePackage

## Package versions
- React Native: 0.63.4
- React Native Reanimated: 1.13.2
- NodeJS: v14.16.1
- Android Gradle PlugIn Version: 3.5.3
- Gradle Version 6.2

## Affected platforms

- [ x ] Android
- [ ] iOS
- [ ] Web

**Comment by skopz356** [comment]
@Stophface I can confirm this issue. Why is it closed? I do not see any linked pull request. Thank you

**Comment by PatrickBokhove** [comment]
Any updates on this? Still experiencing this bug.

"react": "17.0.2",
"react-native": "0.65.1",
"react-native-reanimated": "2.2.2",

![image](https://user-images.githubusercontent.com/7600895/135591241-bd19b303-c8a3-44b8-90ad-ea6278f9f4d3.png)

**Comment by PatrickBokhove** [comment]
> Any updates on this? Still experiencing this bug.
> 
> "react": "17.0.2", "react-native": "0.65.1", "react-native-reanimated": "2.2.2",
> 
> ![image](https://user-images.githubusercontent.com/7600895/135591241-bd19b303-c8a3-44b8-90ad-ea6278f9f4d3.png)

Fixed it by running gradle sync and restarting the metro bundler with the --reset-cache flag

**Comment by ElviraBurchik** [comment]
Hey folks 👋 I experience the same issue on monorepo with 
`"react": "17.0.2", "react-native": "0.66.3", "react-native-reanimated": "2.2.4"` 

@Stophface how did you initially solve it? 🙏

**Comment by nishadadilshan** [comment]
I experience the same issue with
"react": "18.2.0","react-native": "0.71.0", "react-native-reanimated": "3.0.2"

is there any solution ?
