### ISSUE TITLE
Can't find variable: shouldBeUseWeb

### ISSUE THREAD

**Issue by michaelkoo3232** [software-mansion/react-native-reanimated#2314]
## Description
The red screen showing error Can't find variable: shouldBeUseWeb after bundling.

###  Expected behavior
- successfully open the app

### Actual behavior & steps to reproduce
- user react navigation v6 drawer.

## Snack or minimal code example
import {createDrawerNavigator} from '@react-navigation/drawer';
import SettingScreen from '../../Containers/SettingScreen';
import {Text, Button} from 'react-native';
import React from 'react';
import {
  DrawerContentScrollView,
  DrawerItemList,
} from '@react-navigation/drawer';
import {ApplicationStyles} from '../../Themes';
import HomeNavigation from './HomeNavigation';
const {drawerStyle} = ApplicationStyles;

const drawerContent = (props) => {
  return (
    <DrawerContentScrollView {...props}>
      <Button
        title={'close'}
        onPress={() => {
          props.navigation.closeDrawer();
        }}
      />
      <DrawerItemList {...props} />
      <Text>Menu Item</Text>
    </DrawerContentScrollView>
  );
};

const MyDrawer = () => {
  const Drawer = createDrawerNavigator();
  return (
    <Drawer.Navigator
      screenOptions={{
        drawerStyle,
      }}
      drawerContent={drawerContent}
      swipeEnabled={false}>
      <Drawer.Screen name={'HomeNavigation'} component={HomeNavigation} />
      <Drawer.Screen name={'Setting'} component={SettingScreen} />
    </Drawer.Navigator>
  );
};

export default MyDrawer;

## Package versions

- React Native: 0.65.0
- React Native Reanimated: 2.3.0-alpha.2
- NodeJS: 12.14.1
- Java & Gradle: 1.8.0_282

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by michaelkoo3232** [comment]
Please add import { nativeShouldBeMock, shouldBeUseWeb } from './PlatformChecker' in src/reanimated2/core.ts

**Comment by jmysliv** [comment]
@michaelkoo3232 It has been already resolved by #2289.

**Comment by AlphaJuliettOmega** [comment]
@jmysliv ok but now it is resolved and merged, but when will this be in an Alpha / some kind of Release?

The error is still present on `"react-native-reanimated": "2.3.0-alpha.2",`

```
ReferenceError: shouldBeUseWeb is not defined
```

**Comment by jmysliv** [comment]
@AlphaJuliettOmega yeah I know, that is why we are planning to release `2.3.0-alpha.3` this week.

**Comment by AlphaJuliettOmega** [comment]
@jmysliv perfection, thanks for the clarification

**Comment by 452MJ** [comment]
Any progress update?

**Comment by piaskowyk** [comment]
It will be today - I hope 🙌
