### ISSUE TITLE
Updating a shared value from useEffect sometimes gets neglected

### ISSUE THREAD

**Issue by bobsmits** [software-mansion/react-native-reanimated#2338]
## Description
Updating a shared value from a useEffect hook that also triggers a re-render sometimes gets neglected. 

### Expected behavior
The shared value gets updated

### Actual behavior & steps to reproduce
The new value gets ignored. See demo component te reproduce.

## Snack or minimal code example

If you press the green button in the example below the box will move down 10px. Once every 20? times the shared value does not update. Tested on an Iphone Xs sim.
 
```
import React, {useEffect, useState} from 'react';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';
import {View, StyleSheet, TouchableOpacity} from 'react-native';

const Example = () => {
  const translateY = useSharedValue(0);
  const [useEffectTrigger, updateUseEffectTrigger] = useState(0);
  const [state, updateState] = useState(0);

  const handlePress = () => {
    updateUseEffectTrigger(useEffectTrigger + 1);
  };

  useEffect(() => {
    updateState(state + 1);
    translateY.value = (state + 1) * 10;
  }, [useEffectTrigger]);

  const animatedStyles = useAnimatedStyle(
    () => ({
      transform: [{translateY: translateY.value}],
    }),
    [],
  );

  return (
    <View style={styles.wrapper}>
      <TouchableOpacity
        onPress={handlePress}
        style={{
          top: 100,
          width: 50,
          height: 50,
          left: 150,
          backgroundColor: 'green',
        }}
      />
      <Animated.View style={[styles.animated, animatedStyles]} />
    </View>
  );
};

export default Example;

const styles = StyleSheet.create({
  wrapper: {
    backgroundColor: 'white',
    width: '100%',
    height: '100%',
  },
  animated: {
    left: 10,
    width: 50,
    height: 50,
    backgroundColor: 'red',
  },
});
```

## Package versions

React Native: 0.63.3
React Native Reanimated: Alpha 2

## Affected platforms

- [ ] Android (Did not test)
- [X] iOS

**Comment by CDBridger** [comment]
experiencing same thing when I tried as a work around for another bug I was getting (which was initial value of shared value being incorrect)

**Comment by kkafar** [comment]
Hey @bobsmits! Can you confirm that this still happens on latest release version of Reanimated?

I've been clicking your demo for quite a few minutes now and I can not notice this effect.

**Comment by stereoplegic** [comment]
Same issue in iOS with Reanimated versions 2.9.1 (Expo SDK 46) and 2.13.0. Tested on a 2021 iPad. I'm trying to reset opacity and translateX values after calling useState setter (provided to dependency array in useEffect), in a react-native-gesture-handler PanGestureHandler with useAnimatedGestureHandler. Values are updated just fine during the gesture (using useDerivedValue), setState gets called at onEnd and rerender occurs just fine. Like @bobsmits, my issue is that the shared values occasionally fail to update on iOS. Happens every 10-20ish times when I try to set them in useEffect, useLayoutEffect, or in a component's onLayout prop.

**Comment by ucheNkadiCode** [comment]
This is happening to me. It seems like my sharedValue is always one step behind of the props that are being passed in. The props are correct but the shared value is not updating the UseDerivedValue properly.
