### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by osdnk** [software-mansion/react-native-reanimated#234]
I hope it shouldn't be like 
![D3ZC6MuXsAAV4xy](https://user-images.githubusercontent.com/25709300/55756437-d68e1f80-5a51-11e9-86bb-c9186c98274b.jpg)

**Comment by brunolemos** [comment]
https://www.reddit.com/r/reactnative/comments/dgc8kq/tired_to_upgrade_one_of_my_projects_to_0605_i/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by jakub-gonet** [comment]
I believe this is resolved by #505
