### ISSUE TITLE
`interpolate` not backwards compatible with [0,0] range

### ISSUE THREAD

**Issue by xaviershay** [software-mansion/react-native-reanimated#235]
Hello! Thanks for this library - it seems like it's going to be a big improvement over the old `Animated`.

I'm trying to upgrade an app to RN 0.59, which via [`react-navigation`](https://github.com/react-navigation/react-navigation/issues/5684) and `react-navigation-tabs` has necessitated upgrading to this library. I'm getting a whole lot of `NaN` from what I was expecting to be backwards compatible calls (from README: "Use the same Animated library API from React Native that you've been using. You don't need to change anything."). For example, the [interpolate](https://github.com/react-native-community/react-native-tab-view/releases/tag/v2.0.1) example from the release notes:

    # Old API
    > a = new OldAnimated.Value(4)
    > a._value
    4
    > a.__getValue()
    4
    > c = a.interpolate({inputRange: [0, 10], outputRange: [10, 20], extrapolate: 'clamp'})
    AnimatedInterpolation {_children: Array(0), _parent: AnimatedValue, _config: Object, _interpolation: function}
    > c._value
    undefined
    > c.__getValue()
    14

    # New API
    > b = new Animated.Value(5)
    > b._value
    5
    > b.__getValue()
    NaN
    > d = Animated.interpolate(b, {inputRange: [0, 10], outputRange: [10, 20], extrapolate: 'clamp'})
    AnimatedCond {__lastLoopID: 0, __memoizedValue: null, __children: Array(0), __nodeID: 7266, __nodeConfig: Object…}
    > d._value
    undefined
    > d.__getValue()
    NaN

(I'm not sure which of `_value` or `__getValue()` is supposed to be the same, I can't find public API clearly documented, but this does seem to be causing my issue.)

I've also noticed similar disparities in other functions, such as return value of `Animated.subtract`.

This leads to hard to track down bugs, since the `NaN` value often gets all the way into native code and gives no stack trace as to where it originated.

What is the intended scope of backwards compatibility here? Am I doing it wrong?

**Comment by xaviershay** [comment]
So on further investigation, though I'm still curious about the values returned above, I'm managed to find some "working" instances of `interpolate` in my app, so it's probably something different going on. Will re-open if I can get a better repro.

**Comment by xaviershay** [comment]
I think I figured out an actual incompatibility: in the old API, interpolating between `[0, 0]` would return 0, where as with new API it returns `NaN`. While the latter is "more correct", it causes an error that doesn't point to the source of the issue:

```
Error while updating property 'transform' of a view managed by: RCTView

null

Cannot set 'scaleX' to Float.NaN
updateViewProp
    ViewManagersPropertyCache.java:95
setProperty
    ViewManagerPropertyUpdater.java:132
updateProps
    ViewManagerPropertyUpdater.java:51
updateProperties
    ViewManager.java:35
updateProperties
    NativeViewHierarchyManager.java:138
synchronouslyUpdateViewOnUIThread
    UIImplementation.java:338
evaluate
    PropsNode.java:104
evaluate
    PropsNode.java:19
value
    Node.java:41
update
    PropsNode.java:132
runUpdates
    Node.java:122
onAnimationFrame
    NodesManager.java:157
access$000
    NodesManager.java:52
doFrameGuarded
    NodesManager.java:105
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:166
doFrame
    ChoreographerCompat.java:110
run
    Choreographer.java:947
doCallbacks
    Choreographer.java:761
doFrame
    Choreographer.java:693
run
    Choreographer.java:935
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
loop
    Looper.java:193
main
    ActivityThread.java:6669
invoke
    Method.java
run
    RuntimeInit.java:493
main
    ZygoteInit.java:858
```

As a result, the only way I know of to debug is to effectively rebuild the app from scratch (manual bisect) to find offending code.

**Comment by xaviershay** [comment]
I'm also able to get errors like the following, though am not sure if they're related yet (nor exactly how to repro them):

```
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
eval
    OperatorNode.java:180
evaluate
    OperatorNode.java:43
evaluate
    OperatorNode.java:284
value
    Node.java:41
evaluate
    OperatorNode.java:145
evaluate
    OperatorNode.java:284
value
    Node.java:41
evaluate
    OperatorNode.java:157
evaluate
    OperatorNode.java:284
value
    Node.java:41
getNodeValue
    NodesManager.java:198
evaluate
    CondNode.java:19
value
    Node.java:41
evaluate
    BlockNode.java:20
value
    Node.java:41
evaluate
    BlockNode.java:20
value
    Node.java:41
getNodeValue
    NodesManager.java:198
evaluate
    SetNode.java:19
value
    Node.java:41
evaluate
    AlwaysNode.java:21
evaluate
    AlwaysNode.java:6
value
    Node.java:41
update
    AlwaysNode.java:16
runUpdates
    Node.java:122
onAnimationFrame
    NodesManager.java:157
access$000
    NodesManager.java:52
doFrameGuarded
    NodesManager.java:105
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:166
doFrame
    ChoreographerCompat.java:110
run
    Choreographer.java:947
doCallbacks
    Choreographer.java:761
doFrame
    Choreographer.java:693
run
    Choreographer.java:935
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
loop
    Looper.java:193
main
    ActivityThread.java:6669
invoke
    Method.java
run
    RuntimeInit.java:493
main
    ZygoteInit.java:858
```

**Comment by shockdesign** [comment]
👋 Getting the same issue here, thanks @xaviershay for highlighting!

**Comment by kristfal** [comment]
This may be caused by an issue related to a subset of Android 9 devices when you're building with SDK tools 28. You likely bumped to 28 while upgrading to RN59, which could be the issue, and not this lib in itself.

Please have a look at:
https://github.com/n4kz/react-native-indicators/issues/22
https://github.com/react-native-community/react-native-tab-view/issues/715

Could you see if you can answer a few of the test cases? 

Thanks

**Comment by xaviershay** [comment]
Interesting! I'll try and take a look this week, but we've since upgrade via another route so I might not have an easy repro any more.

It would have been on either a Pixel or a Nexus 5X, they're the only two I have emulators set up for.

**Comment by kristfal** [comment]
@xaviershay I was trying to repro the crash using a Pixel emulator on API level 28, but i couldn't repro.

Would you be able to share the AVD commands for creating your current emulators? With those, I may be able to fix this.

**Comment by xaviershay** [comment]
I made them using Android Studio UI. Here is a screenshot (The Nexus 4 one is new so I definitely wasn't testing on that).

<img width="1110" alt="Screen Shot 2019-06-12 at 9 03 14 am" src="https://user-images.githubusercontent.com/1714/59312566-f90e1480-8cf0-11e9-8a5a-035dd5776ba1.png">


(sorry am pretty new to mobile)

**Comment by JulianKingman** [comment]
I was getting a doubleValue error when the duration for a Animation.timing function config was undefined. Oops 😨

**Comment by raimonkh** [comment]
Dirty solution, you can interpolate from 0 to 0.01... so basically never interpolate to the same number but to a fraction of it close to 0... that fixed our problems
