### ISSUE TITLE
[iOS] No command found with name "scrollTo" on `2.3.0-alpha.3`

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#2364]
## Description

Getting `No command found with name "scrollTo"` after updating to alpha 3. 

This error did not occur on alpha 2.

I have cleaned the iOS build folder, and started with `--reset-cache` but it is still occurring.

### Expected behavior

No error

### Actual behavior & steps to reproduce

It can be reproduced on this branch:
https://github.com/andreialecu/rnctv-react-native-bare-test/tree/bug-scrollto

https://user-images.githubusercontent.com/697707/131982258-1bc1523f-82a6-4aa7-8c6d-3df92acbadf6.mov

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-alpha.3

## Affected platforms

- [x] iOS

**Comment by andreialecu** [comment]
There's also a native crash soon afterwards:

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type facebook::jsi::JSError: undefined is not an object (evaluating 'jsThis._closure')
 
workletValueSetter@/Users/andreialecu/Work/contrib/repros/rnctv-react-native-bare-test/node_modules/react-native-reanimated/src/reanimated2/core.ts (181:0):1:63
[native code]
[native code]
```

**Comment by andreialecu** [comment]
For reference, same repro working with alpha 2:

https://user-images.githubusercontent.com/697707/131986902-c246650a-9f41-48f4-a5ed-114e6e235b75.mp4

**Comment by BooYeu** [comment]
Same error~~

**Comment by SimpleCreations** [comment]
I'm getting a similar error when focusing a `TextInput`:

![Simulator Screen Shot - iPhone 11 Pro - 2021-09-03 at 14 42 08](https://user-images.githubusercontent.com/12449725/131999934-7af8e494-607e-4940-a8a9-5ad3d39374f6.png)

**Comment by piaskowyk** [comment]
@jmysliv Can it be related to enabling software keyboard on iOS?

**Comment by gabrielbezerra81** [comment]
I'm having this issue also when swiping tabs. Also TabBar onPress stopped working in alpha 3.

**Comment by TrebuhD** [comment]
@piaskowyk it doesn't look related to the software keyboard. At least, toggling the software keyboard in the Simulator doesn't change anything.

Here's the full error log:

```
No command found with name "focus"

-[RCTUIManager dispatchViewManagerCommand:commandID:commandArgs:]
    RCTUIManager.m:1132
__invoking___
-[NSInvocation invoke]
-[NSInvocation invokeWithTarget:]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread
```

**Comment by NoerNova** [comment]
Same issue on here 

affect iOS only
on `No command found with name "scrollTo"` affect react-native-snap-carousel
and `No command found with name "focus"` affect react-native TextInput


- react-native: 65.1
- react-native-reanimated: 2.3.0-alpha.3

**Comment by ramisalem** [comment]
Any update on this issue?

**Comment by piaskowyk** [comment]
@ramisalem fixed 😄  Changes will be available in the next release of the alpha version.
