### ISSUE TITLE
[Android] Release build with proguard is crashing in 2.3.0-alpha3, worked fine in alpha 2.

### ISSUE THREAD

**Issue by gabrielbezerra81** [software-mansion/react-native-reanimated#2367]
### Expected behavior

Start production app without crashing.

### Actual behavior & steps to reproduce

Release build crashes when starting if proguard is enabled. Works fine when proguard is disabled. Only happened when upgraded to alpha 3 version, 2.2.0 and alpha 2 worked fine.

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-alpha.3
- NodeJS: 14.17.3
- Xcode: 12.5.1
- Java & Gradle: java 1.8.0_301; AGP 4.2.2; Gradle 6.9.1

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web
[proguard-rules-staging.txt](https://github.com/software-mansion/react-native-reanimated/files/7105969/proguard-rules-staging.txt)

Stacktrace:

```
ReanimatedNativeHierarchyManager.java, line 7
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.uimanager.l1.e.b(android.view.View, int, int, int, int)' on a null object reference

com.swmansion.reanimated.layoutReanimation.g.C ReanimatedNativeHierarchyManager.java:7
com.facebook.react.uimanager.y0$v.b UIViewOperationQueue.java:2
com.facebook.react.uimanager.y0$a.run UIViewOperationQueue.java:18
com.facebook.react.uimanager.y0.U UIViewOperationQueue.java:10
com.facebook.react.uimanager.y0.s UIViewOperationQueue.java:1
com.facebook.react.uimanager.y0$j.c UIViewOperationQueue.java:6
com.facebook.react.uimanager.f.a GuardedFrameCallback.java:1
com.facebook.react.modules.core.g$d.a ReactChoreographer.java:7
com.facebook.react.modules.core.a$a$a.doFrame ChoreographerCompat.java:1
android.view.Choreographer$CallbackRecord.run Choreographer.java:1008
android.view.Choreographer.doCallbacks Choreographer.java:809
android.view.Choreographer.doFrame Choreographer.java:740
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:995
android.os.Handler.handleCallback Handler.java:938
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:246
android.app.ActivityThread.main ActivityThread.java:8512
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:602
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1130
```

**Comment by piaskowyk** [comment]
I think I know why it happens, but could you paste here logs from the crash - this will be really helpful?

**Comment by gabrielbezerra81** [comment]
Just updated with the stack trace

**Comment by piaskowyk** [comment]
Thanks! That is exactly what I wanted.

**Comment by jxom** [comment]
Can confirm, I am getting something similar when I include an `onRefresh` prop on a `SectionList` 🧐

**Comment by j-piasecki** [comment]
Hi! Are you still experiencing this problem after upgrading to the stable release of 2.3?
