### ISSUE TITLE
PanGestureHandler doesn't work when debugging / EasingNode error Reanimated 2.3.0.alpha.3

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#2368]
I just upgraded my reanimated from `2.2.0` to `2.3.0-alpha.3` but got some issues.
I was happy with 2.2.0 but i needed `Debug with Chrome`.

## Description
Firstly when i enable debugging i saw that Pan animations are not working on debug mode enabled. Simply elements doesn't move.

after that i noticed that reanimated forcing me to change `Easing` functions  with `EasingNode`.
I have done this, but this time i got this error below when i drag and drop the element.
![Simulator Screen Shot - iPhone 12 - 2021-09-03 at 23 39 53](https://user-images.githubusercontent.com/44513402/132064576-b5c9cd67-0121-45ef-b261-5e36fc99cf2c.png)

## Package versions
- React Native:     "react-native": "0.64.2",
- React Native Reanimated:    "react-native-reanimated": "^2.3.0-alpha.3",
- NodeJS: 12
- Xcode: 12.5
- Java & Gradle: -

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey @Bayramito 👋
Is it possible for you to provide an example snack of code to reproduce the issue? It will be really helpful for us!

**Comment by Bayramito** [comment]
`export const animationcConfig = {
  easing: Easing.inOut(Easing.ease),
  duration: 350,
};`

`        useAnimatedReaction(
          () => positions.value[child.props.title],
          newOrder => {
            const newPosition = getPosition(newOrder);
            translateX.value = withSpring(newPosition.x, animationcConfig);
            translateY.value = withSpring(newPosition.y, animationcConfig);
          },
        );
        const onGestureEvent = useAnimatedGestureHandler({
          onStart: (_, ctx) => {
            if (editing) {
              isGestureActive.value = true;
              ctx.x = translateX.value;
              ctx.y = translateY.value;
            }
          },
          onActive: ({translationX, translationY}, ctx) => {
            if (editing) {
              translateX.value = ctx.x + translationX;
              translateY.value = ctx.y + translationY;
              const oldOrder = positions.value[child.props.title];
              const newOrder = getOrder(translateX.value, translateY.value, Object.keys(positions.value).length - 1);
              if (oldOrder !== newOrder) {
                const idToSwap = Object.keys(positions.value).find(key => positions.value[key] === newOrder);
                if (idToSwap) {
                  const newPositions = JSON.parse(JSON.stringify(positions.value));
                  newPositions[child.props.title] = newOrder;
                  newPositions[idToSwap] = oldOrder;
                  positions.value = newPositions;
                }
              }
              const lowerBound = scrollY.value;
              const uppoerBound = lowerBound + containerHeight - SIZE;
              const maxScroll = contentHeight - containerHeight;
              const scrollLeft = maxScroll - scrollY.value;
              if (translateY.value < lowerBound) {
                const diff = Math.min(lowerBound - translateY.value, lowerBound);
                scrollY.value -= diff;
                ctx.y -= diff;
                scrollTo(scrollView, 0, scrollY.value, false);
                translateY.value = ctx.y + translationY;
              }

              if (translateY.value > uppoerBound) {
                const diff = Math.min(translateY.value - uppoerBound, scrollLeft);
                scrollY.value += diff;
                ctx.y += diff;
                scrollTo(scrollView, 0, scrollY.value, false);
                translateY.value = ctx.y + translationY;
              }
            }
          },
          onEnd: () => {
            const destionation = getPosition(positions.value[child.props.title]);
            translateX.value = withTiming(destionation.x, animationcConfig, () => {
              isGestureActive.value = false;
            });
            translateY.value = withTiming(destionation.y, animationcConfig);
            runOnJS(showresult)(positions.value);
          },
        });
        return (
          <Animated.View key={child.props.title} style={rStyle}>
            <PanGestureHandler enabled={editing} onGestureEvent={onGestureEvent}>
              <Animated.View style={StyleSheet.absoluteFill}>
                <Item key={child.props.title} id={child.props.title} positions={positions}>
                  {child}
                </Item>
              </Animated.View>
            </PanGestureHandler>
          </Animated.View>
        );
      })}
      {/* {editing && <View style={{...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,.3)", zIndex: 91}} />} */}
    </Animated.ScrollView>
  );
};`

**Comment by Bayramito** [comment]
Simply when i  change Easing below to EasingNode it crashes.


`export const animationcConfig = {
  easing: Easing.inOut(Easing.ease),
  duration: 350,
};`


I use this config on following,

`        useAnimatedReaction(
          () => positions.value[child.props.title],
          newOrder => {
            const newPosition = getPosition(newOrder);
            translateX.value = withSpring(newPosition.x, animationcConfig);
            translateY.value = withSpring(newPosition.y, animationcConfig);
          },
        );`

`translateX.value = withTiming(destionation.x, animationcConfig, () => {
              isGestureActive.value = false;
            });
            translateY.value = withTiming(destionation.y, animationcConfig);
            runOnJS(showresult)(positions.value);
          },`

**Comment by alakdam07** [comment]
@piaskowyk After updating the package. I am getting this Typescript error: **Type 'EasingFunction' is not assignable to type 'EasingNodeFunction'.** 

```
import { useCallback, useEffect, useState } from 'react';
import Animated, { Easing } from 'react-native-reanimated';

type Props = {
  isSelected: boolean;
};

const useAnimatedTab = ({ isSelected }: Props) => {
  const tabColor = isSelected ? '#007841' : '#484848';
  const [animatedValue] = useState(new Animated.Value(isSelected ? 0 : 1));
  const translateY = animatedValue.interpolate({
    inputRange: [0, 1],
    outputRange: [0, 4],
  });

  const _startAnimation = useCallback(() => {
    Animated.timing(animatedValue, {
      toValue: 1,
      duration: 150,
      easing: Easing.ease, // when I hover the error : The expected type comes from property 'easing' which is declared here on type 'TimingConfig'
    }).start();
  }, [animatedValue]);

  const _reverseAnimation = useCallback(() => {
    Animated.timing(animatedValue, {
      toValue: 0,
      duration: 150,
      easing: Easing.ease, // when I hover the error : The expected type comes from property 'easing' which is declared here on type 'TimingConfig'
    }).start();
  }, [animatedValue]);

  useEffect(() => {
    if (!isSelected) {
      _startAnimation();
    } else {
      _reverseAnimation();
    }
  }, [_reverseAnimation, _startAnimation, isSelected]);

  return {
    translateY,
    tabColor,
  };
};

export default useAnimatedTab;
```



## New package information 

| Tech        | Version |
| ----------- | ------- |
| react-native-reanimated       | ^2.2.1|


## How Can I use the 

**This is the Error I am getting now after update the package**
<img width="1387" alt="Screenshot 2021-09-12 at 9 45 28" src="https://user-images.githubusercontent.com/47625626/132976646-a8af1302-3533-4f7e-9dbe-8d32341b9060.png">

**Comment by Bayramito** [comment]
I also get this error on this version 
![Simulator Screen Shot - iPhone 12 - 2021-09-15 at 12 35 17](https://user-images.githubusercontent.com/44513402/133417230-1ee1a597-ffaf-4523-a801-c2ea251ce249.png)

**Comment by piaskowyk** [comment]
Since release of Reanimated 3, I think that this issue is a bit outdated. If you still facing this issue just let me know.
