### ISSUE TITLE
[2.3.0-alpha.3] Trying to remove a view index above child count 0

### ISSUE THREAD

**Issue by 0nlyDev** [software-mansion/react-native-reanimated#2393]
## Description

Getting when using the package in conjunction with react-native-google-places-autocomplete.
1. It happens when you type in and then delete (maybe just delete if you already preload the field) with some text
> Trying to remove a view index above child count 0
![Capture](https://user-images.githubusercontent.com/89726447/132598143-f8f717d6-cc6d-40a9-abf8-ed2d892e4b32.PNG)
2. The text input sometimes becomes unclickable

### Expected behavior
To not throw error and to be able to click everywhere on the screen

### Actual behavior & steps to reproduce
Install "react-native": "0.65.1", "react-native-google-places-autocomplete": "^2.4.1", "react-native-reanimated": "^2.3.0-alpha.3",
Then run the example code from bellow, start deleting the default text from the text input field and you should get the error. 

## Snack or minimal code example
```
import React from 'react';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

const GooglePlacesInput = () => {
  return (
    <GooglePlacesAutocomplete
      placeholder='Search'
      onPress={(data, details = null) => {
        // 'details' is provided when fetchDetails = true
        console.log(data, details);
      }}
      query={{
        key: 'YOUR API KEY',
        language: 'en',
      }}
      requestUrl={{
        useOnPlatform: 'web', // or "all"
        url:
          'https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api', // or any proxy server that hits https://maps.googleapis.com/maps/api
        headers: {
          Authorization: `an auth token`, // if required for your proxy
        },
      }}
    />
  );
};

export default GooglePlacesInput;
```

## Package versions
`"scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/drawer": "^6.1.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-geolocation-service": "^5.3.0-beta.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-maps": "0.28.0",
    "react-native-maps-directions": "^1.8.0",
    "react-native-reanimated": "^2.3.0-alpha.3",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.6.0",
    "react-native-vector-icons": "^8.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.0",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"`

## Affected platforms

- Android

**Comment by Szymon20000** [comment]
Did anyone encounter a similar issue but without using react-native-google-places-autocomplete?

**Comment by tonydatw** [comment]
@piaskowyk now i'm getting this error not only for google autocomplete package, but also for react-native-multiple-select. Have version 2.3.0-alpha.3
