### ISSUE TITLE
[iOS] Pod install error Unable to find a specification for `React-callinvoker` depended upon by `RNReanimated`

### ISSUE THREAD

**Issue by ihiteshkumar** [software-mansion/react-native-reanimated#2398]
### Discussed in https://github.com/software-mansion/react-native-reanimated/discussions/2397

<div type='discussions-op-text'>

<sup>Originally posted by **ihiteshkumar** September  9, 2021</sup>
Getting this error when pod install on iOS

Unable to find a specification for `React-callinvoker` depended upon by `RNReanimated`

React-callinvoker is already available in pod:

    pod 'ReactCommon/callinvoker', :path => "../../common/ReactNative/libs/react-native/ReactCommon"

![Screenshot 2021-09-09 at 1 59 13 PM](https://user-images.githubusercontent.com/9604287/132651664-897aa3e9-b598-45d3-b3cc-8aaac2373477.png)
</div>

**Comment by piaskowyk** [comment]
Is it possible for you to provide an example repo to reproduce this issue?

**Comment by abarisic86** [comment]
@ihiteshkumar how did you resolve this?

**Comment by ihiteshkumar** [comment]
> @ihiteshkumar how did you resolve this?

@abarisic86 This issue is not resolved yet.

**Comment by abarisic86** [comment]
I manage to solve it by reverting back to the 1.7 version of the library.

**Comment by kkafar** [comment]
Hey @ihiteshkumar!
More detailed information is needed (repo with project in which this problem occurs).
