### ISSUE TITLE
[2.2.1] Android Application Crashes After Update (from 2.2.0)

### ISSUE THREAD

**Issue by archcorsair** [software-mansion/react-native-reanimated#2407]
## Description
Updated `react-native-reanimated` from `2.2.0` to `2.2.1` and the android application instantly crashes on startup. Reverting back to `2.2.0` does not cause crashing.
**The issue does not impact iOS** 

### Expected behavior
Android should not crash after upgrading to 2.2.1

### Actual behavior & steps to reproduce
Upgrade to 2.2.1
Attempt to run android application, instant crash.

## Snack or minimal code example

There is no JS error but I was only able to grab a snippet of the error:
```FATAL EXCEPTION: FlipperEventBaseThread```
I fully uninstalled the application and did a full clean, cleared all caches, etc.

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.1
- NodeJS: 16.7.0
- Xcode: Xcode 12.5.1 | Build version 12E507
- Java & Gradle: Gradle 4.2.1

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by thuyngocha98** [comment]
same issue!

**Comment by gabpaet** [comment]
I am also experiencing this issue after upgrading to 2.2.1

**Comment by kmagiera** [comment]
Hi @archcorsair  @thuyngocha98 @gabpaet – thanks for reporting and for your comments. Can you try if this issue still persist on the most recent version?

**Comment by piaskowyk** [comment]
Issue seems to be inactive. I recommend to upgrade Reanimated version to 3.+ - Rea 3 contains a lot of stability improvements.
