### ISSUE TITLE
Worklets link doesn't work

### ISSUE THREAD

**Issue by Gentlee** [software-mansion/react-native-reanimated#2425]
https://docs.swmansion.com/react-native-reanimated/docs/next/worklets/

It is a first link in google search.

**Comment by enzomanuelmangano** [comment]
Do you refer to this link?
- https://docs.swmansion.com/react-native-reanimated/docs/next/fundamentals/worklets

**Comment by piaskowyk** [comment]
Thanks for your report, but we need to wait for Google bots to reindex our documentation.
https://docs.swmansion.com/react-native-reanimated/docs
