### ISSUE TITLE
jumping animation

### ISSUE THREAD

**Issue by lucasvieceli** [software-mansion/react-native-reanimated#2427]
## Description
I'm doing an animation of the label, to go up, when the input is focused, I'm using absolute position

am I doing something wrong?

I thought it could be state, but there is no state updating

video:
https://files.fm/f/6audve379

### Expected behavior
label animation is jumping, it should be rising fluid

### Actual behavior & steps to reproduce
I put the two codes in the gist to be able to view
## Snack or minimal code example
https://gist.github.com/lucasvieceli/ded8ad22b67d7c7238711dd8ef67fa68

## Package versions

- React Native: SDK 42
- React Native Reanimated:2.3.0-alpha.3
- NodeJS: 14.17.6
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by Ubax** [comment]
@lucasvieceli Could you check if your repro is correct?
I opened it and I think that are some lines missing. 
Try adding extensions to file names (*.tsx) in gist. The GitHub will color the code then.
