### ISSUE TITLE
[2.2.1] Building android app crashes

### ISSUE THREAD

**Issue by pc-lover** [software-mansion/react-native-reanimated#2428]
## Description
When using version 2.2.1, the file `android/build.gradle` uses `Pattern.implementation` method which is not existed hence causing error. 

After spending time investigation, it looks like the original file `android-npm/build.gradle` from source code used correct method `Pattern.compile`. But it got replaced to `Pattern.implementation` when client running `gradlew assembleRelease -p .`

https://stackoverflow.com/questions/44402024/why-android-change-compile-to-implementation-configuration-in-gradle-depende

The logs from client contain:
```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
...
...
No signature of method: static java.util.regex.Pattern.implementation() is applicable for argument types: (String) values: [generate(\w+)(Release|Debug)]
```

Btw, I'm using Xcode 13 beta 5 but not sure if it's the beta version causing the problem.

### Expected behavior
The lib doesn't throwing error and works as the old version `2.2.0`

### Actual behavior & steps to reproduce
1. Client runs: `gradlew assembleRelease -p .`
2. Gets error: No signature of method: static java.util.regex.Pattern.implementation() is applicable for argument types: (String) values: [generate(\w+)(Release|Debug)]

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.2.1
- NodeJS: 12.22.6
- Xcode: Version 13.0 beta 5
- Java & Gradle: OpenJdk 8 and Gradle 6.7

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
This problem should be resolved with: https://github.com/software-mansion/react-native-reanimated/pull/2564 Let me know if you still have this issue.
