### ISSUE TITLE
Error while building iOS: 'React/RCTView.h' file not found

### ISSUE THREAD

**Issue by kingdaro** [software-mansion/react-native-reanimated#244]
In the file `ios/Transitioning/REATransitionValues.m`, I get the error `'React/RCTView.h' file not found` when trying to make a debug build. My experience with Xcode is limited, so I suspect it's a local issue, but I haven't managed to Google myself to a solution as of yet. I'm on React Native 0.59.4

**Comment by kingdaro** [comment]
I seem to have fixed it by specifying the react pod dependencies manually
```ruby
  # specify react dependencies manually,
  # fixes various "'something.h' file not found" errors
  pod 'React', path: "../node_modules/react-native", subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```
I'm betting the issue was that it was trying to pull an old, incompatible version of React (it was pulling a pod with version (0.11.something)

**Comment by rochapablo** [comment]
Getting the same error, but the workaround above didn't work for me.

```
"react": "16.8.3",
"react-native": "0.59.5",
"react-native-gesture-handler": "^1.2.1",
"react-native-reanimated": "^1.1.0",
```

**Comment by jakub-gonet** [comment]
Hi all,
sorry for the late response 😔

This issue is probably outdated, so I'm closing it.

If you have further questions don't hesitate to ask!
