### ISSUE TITLE
App crashes with Xcode 13.

### ISSUE THREAD

**Issue by kanelloc** [software-mansion/react-native-reanimated#2448]
## Description
Hello guys,
After updating xcode from v12.5 to v13 App keep crashing on startup.

If I remove reanimated 2 app is launched successfully.

The main problem is when both reanimated 2 and Jitsi meet sdk are installed.

There is no problem if the packages are installed standalone

When running on xcode i got the following logs. 
<img width="812" alt="Screenshot 2021-09-23 at 5 13 23 PM" src="https://user-images.githubusercontent.com/17724315/134523831-1929f1e3-abb2-4e2c-892f-d5b80a55117f.png">

## Expected behavior
App launch after build

## Actual behavior & steps to reproduce
The app crashes with the error com.facebook.react.JavaScript (17): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

## Package versions
- React Native: 063.2
- React Native Reanimated:  2.2.0
- NodeJS: 12
- Xcode: 13
- Jitsi meet: 3.7.2

**Comment by dgreasi** [comment]
I can confirm. Reproduced with a clean project [here](https://github.com/dgreasi/JitsiReanimatedError).

```
node: 12.X

"@shopify/restyle": "^1.4.0",
"react": "17.0.2",
"react-native": "0.65.1",
"react-native-jitsi-meet": "^2.1.2",
"react-native-reanimated": "^2.2.2",
"react-native-safe-area-context": "^3.3.2"
```

If one of the "react-native-jitsi-meet", "react-native-reanimated" is removed from the project it builds and works just fine.

**Comment by dimaportenko** [comment]
It happens only in DEBUG mode, production builds work fine on my end.

**Comment by erdemildiz** [comment]
+1

**Comment by hanifmhd** [comment]
is there any solution for this?

**Comment by dfabreguette-ap** [comment]
I have same problem.
I'm using JitsiMeet also,with react-native-animated, as a dependency of @react-navigation/drawer.
How can I fix this please ? It keeps from using simulators and my iphone on iOS 15.1.

If that can I help i use :

 Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/davidfabreguette/.rvm/rubies/ruby-2.7.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.15.0 => 0.15.0 
      expo: ~41.0.1 => 41.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

**Comment by kanelloc** [comment]
Any update? So far we have not been able to solve it

**Comment by icc-romeu** [comment]
We finally applied a workaround. We developed a UI interface for Jitsi and used https://github.com/jitsi/lib-jitsi-meet that does not use the iOS Native Jitsi bundle, so you will not have problems with reanimated. 

I hope that helps.

**Comment by piaskowyk** [comment]
@icc-romeu thanks for the info and for resolving of problem 🙌
