### ISSUE TITLE
Wrong version when installing with "next" postfix

### ISSUE THREAD

**Issue by inferusvv** [software-mansion/react-native-reanimated#2449]
Latest stable version is 2.2.2.

[Docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#installing-the-package) saying how to install alpha: 

> First step is to install react-native-reanimated **alpha** as a dependency in your project:
> 
> yarn add react-native-reanimated@next

Latest alpha is `2.3.0-alpha.3`

**next** is just 2.0.0:

![Снимок экрана 2021-09-23 в 17 22 32](https://user-images.githubusercontent.com/3227120/134524984-765b1b6f-3bd0-4c4c-a4ec-60c696c2d4fe.png)

So from docs I can't understand which version you are recommending to install.

**Comment by jmysliv** [comment]
Hi @inferusvv, thanks for reporting this issue. We've changed the next tag to `2.3.0-alpha.3`.
