### ISSUE TITLE
[RN 0.66] Android build failure, Execution failed for JetifyTransform

### ISSUE THREAD

**Issue by hsavit1** [software-mansion/react-native-reanimated#2452]
## Description

Currently, the rc4 of react native 0.66 looks to be stable and should be [promoted to main early next week](https://github.com/react-native-community/releases/issues/246#issuecomment-926316260). 

When building my project with reanimated on android, I'm getting this error

Building on an M1 mac. Reanimated v2.2.2 . This was building for 0.65.1

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-66-hermes.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: /Users/me/my_app/node_modules/react-native-reanimated/android/react-native-reanimated-66-hermes.aar.
         > Transform's input file does not exist: /Users/me/my_app/node_modules/react-native-reanimated/android/react-native-reanimated-66-hermes.aar. (See https://issuetracker.google.com/issues/158753935)
```

### Expected behavior

It builds

### Actual behavior & steps to reproduce

It won't build

## Package versions

- React Native: 0.66-rc4
- React Native Reanimated: 2.2.2 and v2.3.0-alpha3
- NodeJS: 16.10
- Xcode: 13
- Java & Gradle: gradle 6.9

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
We haven't support `react-native@0.66` yet. But I'm working on this at this moment, so It should be available soon.
