### ISSUE TITLE
[RN 0.66] iOS build failure: 'boost/operators.hpp' file not found

### ISSUE THREAD

**Issue by losh11** [software-mansion/react-native-reanimated#2456]
## Description

After updating to React Native 0.66.0-rc.4, building with Xcode 13.0 results in build error with message: `/Users/loshan/Repos/plasma/ios/Pods/Headers/Public/RCT-Folly/folly/dynamic.h:63:10: 'boost/operators.hpp' file not found`. Uninstalling react-native-reanimated makes the error goes away, so I believe that the issue is specifically with this library.

![](https://i.imgur.com/i0q4IGP.png)

### Expected behavior

For build to succeed without erroring.

### Actual behavior & steps to reproduce

Use expo to create repo with react-native version 0.66.0-rc.4. Add `react-native-reanimated`

## Package versions

- React Native: 0.66.0-rc.4
- React Native Reanimated: 2.3.0-beta.1
- NodeJS: 14.17.5
- Xcode: 13.0

## Affected platforms

- [ ] iOS

**Comment by natew** [comment]
Maybe a clue on how to do it here, not positive but seems to be a recent edit that touches the boost dep. I'll give it a run in a bit:

https://github.com/th3rdwave/react-native-reanimated/blob/311b11f7e1f51f6a7c55c02790309f49d3c44f62/RNReanimated.podspec

**Comment by erdemildiz** [comment]
+1

**Comment by Sahil5963** [comment]
Same issue here

**Comment by goddie** [comment]
There is something wrong in Pods Xcode Project Header Search Path. 
"$(PODS_ROOT)/boost-for-react-native" is an old setting, you may add a line:
"$(PODS_ROOT)/boost"

**Comment by irmakcosarsahna** [comment]
Same issue

**Comment by kesha-antonov** [comment]
Changing `"$(PODS_ROOT)/boost-for-react-native"` to `"$(PODS_ROOT)/boost"` helps

<img width="971" alt="Screenshot 2021-10-04 at 11 44 44" src="https://user-images.githubusercontent.com/11584712/135821022-9c517db2-d3ed-486c-ad59-4cd678970da3.png">

**Comment by rnnyrk** [comment]
Same issue for me. Unfortunately changing the Header Search Path of boost didn't work for me.. Any ideas?
<img width="1239" alt="Screenshot 2021-10-05 at 15 15 13" src="https://user-images.githubusercontent.com/4519142/136030376-8f0056de-3106-4df7-afc8-f4776e236abb.png">
<img width="270" alt="Screenshot 2021-10-05 at 15 15 28" src="https://user-images.githubusercontent.com/4519142/136030391-0fa37d97-bba1-43e0-b8a5-8050f118754d.png">

**Comment by kesha-antonov** [comment]
Try `"react-native-reanimated": "2.3.0-beta.2"`
It has fix for search paths

**Comment by rnnyrk** [comment]
I can confirm this is working! Thanks 💯 👍

**Comment by Alexanderjansson91** [comment]
After I change "$(PODS_ROOT)/boost-for-react-native" to "$(PODS_ROOT)/boost" I get this error: 

_Thread 1: "-[REAEventDispatcher setBridge:]: unrecognized selector sent to instance 0x600001f0ba20"_

I have tried with pod install, but then the changes disappear. Anything else I can try?

**Comment by yz1311** [comment]
> After I change "$(PODS_ROOT)/boost-for-react-native" to "$(PODS_ROOT)/boost" I get this error:
> 
> _Thread 1: "-[REAEventDispatcher setBridge:]: unrecognized selector sent to instance 0x600001f0ba20"_
> 
> I have tried with pod install, but then the changes disappear. Anything else I can try?

same here!

**Comment by Parmar-Bansi** [comment]
> `"react-native-reanimated": "2.3.0-beta.2"`

not working in my case any other solution..??

**Comment by hmadhsan** [comment]
Tried every solution, nothing worked for me on iOS xCode

**Comment by hmadhsan** [comment]
> react-native-reanimated": "2.3.0-beta.2

have u found the solution anyway?

**Comment by hmadhsan** [comment]
> > `"react-native-reanimated": "2.3.0-beta.2"`
> 
> not working in my case any other solution..??

have u found the solution anyway?

**Comment by aleksandrovfe** [comment]
Any solutions? 

` "react-native": "0.72.4",`

<img width="264" alt="Screenshot 2024-02-19 at 13 24 41" src="https://github.com/software-mansion/react-native-reanimated/assets/47118920/2256221e-8ec2-47a5-81d0-6aa17312492b">

**Comment by uiop25800** [comment]
> Any solutions?
> 
> ` "react-native": "0.72.4",`
> 
> <img alt="Screenshot 2024-02-19 at 14 51 38" width="1372" src="https://private-user-images.githubusercontent.com/47118920/305954878-ef6a4b38-8358-492a-9a7c-50f2a21d2e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTEyNDAsIm5iZiI6MTcwOTcxMDk0MCwicGF0aCI6Ii80NzExODkyMC8zMDU5NTQ4NzgtZWY2YTRiMzgtODM1OC00OTJhLTlhN2MtNTBmMmEyMWQyZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA3NDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YzkxZWNkMWMzZDhkNjBjMmI0OWFlNjRhZWNmMzgzMDQzZDc1MTIwNGQ4ZTIzZDAwN2U1OTZiYzgzNDNkZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S28c0UNmofG4PJe4jS8vRymkW544Y2uA8rrThW-moaA">

Same issue.

**Comment by isma3l** [comment]
:(
