### ISSUE TITLE
ViewManager for tag xxxxxxxxxxx could not be found. react-native-admob-native-ads

### ISSUE THREAD

**Issue by TrungNguyen153** [software-mansion/react-native-reanimated#2457]
## Description
Throw ViewManager for tag xxxxxxxxxxx could not be found when unmount NativeAdView ( component's react-native-admob-native-ads).

react-native-admob-native-ads version 0.5.0 and 0.4.1 ( another version not test yet but 0.4.1 used stable with reanimated 2.2.0

resolveViewManager ( NativeViewHierarchyManager.java:112)
dfs ( ReanimatedNativeHierarchyManager.java:116)
dfs ( ReanimatedNativeHierarchyManager.java:127)
deleteView ( ReanimatedNativeHierarchyManager.java:106)
manageChildren ( NativeViewHierarchyManager.java:482)
manageChildren ( ReanimatedNativeHierarchyManager.java:230)

### Expected behavior
Not throw error when unmount NativeAdView ( component's react-native-admob-native-ads)

### Actual behavior & steps to reproduce
just unmount NativeAdView ( component's react-native-admob-native-ads ) 

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.1
- NodeJS: 16.+
- Xcode:
- Java & Gradle: 11

## Affected platforms

- [x] Android
- [ ] iOS (Not test yet)
- [ ] Web (Not test yet)

**Comment by Kesmek** [comment]
I have the same issue comfirmed on versions 4.0.0 - 4.2.1 (latest) of [react-native-camera](https://github.com/react-native-camera/react-native-camera) when the component is unmounted. This error might tangentially be related to #2460 as this error also occurs when unmounting a stack screen that contains a RNCamera component.
