### ISSUE TITLE
'RNScreens/RNSScreen.h' file not found

### ISSUE THREAD

**Issue by manastunga787** [software-mansion/react-native-reanimated#2463]
## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.1
- NodeJS: v16.0.0
- Xcode: Version 12.4 (12D4e)

## Affected platforms

- [ ] iOS
<img width="1952" alt="Screenshot 2021-09-28 at 4 31 21 PM" src="https://user-images.githubusercontent.com/6284177/135076403-99aeaea4-6258-4a9c-8602-998c8b0f79a0.png">

**Comment by piaskowyk** [comment]
Hey @manastunga787 👋
Fixed here: https://github.com/software-mansion/react-native-reanimated/pull/2377 - it will be available in the next release. But you can use this command to fix it `yarn add react-native-screens && cd ios && pod install`

**Comment by kuzzmi** [comment]
Even with `react-native-screens` it fails.

```
    "react-native-screens": "^3.8.0",
    "react-native-reanimated": "^2.3.0-beta.1",
``` 

Pods cleaned and reinstalled, RNScreens is included in the Pods project.
