### ISSUE TITLE
[2.3.0-beta.2](IOS) TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by meftunca** [software-mansion/react-native-reanimated#2482]
![simulator_screenshot_1866C906-502B-4A31-834C-330356033082](https://user-images.githubusercontent.com/19187204/135869815-a5036849-98b2-4f99-9e6d-5089c76f3293.png)

## Description
TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes

### Expected behavior
This error should not occur

### Actual behavior & steps to reproduce
N/A
## Package versions

 

- React Native:0.66.0
- React Native Reanimated: 2.3.0-beta.2
- NodeJS:16.10.0
- Xcode:13
- Java & Gradle:

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by sercand** [comment]
I have the same issue but I don't use Hermes engine

**Comment by YLzpppp** [comment]
the same error
os: andriod 10
rn: 0.66
renimated: 2.3.0-beta.2

**Comment by juancarlosqr** [comment]
Having the same error:

OS: Android 10
RN: 0.66
Reanimated: 2.3.0-beta.2

**Comment by Rafnexx** [comment]
I can confirm that problem exists on Android.

OS: Android 11,
RN: 0.66,
Reanimated: 2.3.0-beta.2

**Comment by piaskowyk** [comment]
Hey @meftunca 👋
Could you (or someone who can reproduce this issue) prepare a showcase repo to reproduce this issue? 🙏

**Comment by SergiOnGit** [comment]
Exactly the same here. Cache resetting doesn't help.

**Comment by meftunca** [comment]
> Hey @meftunca 👋 Could you (or someone who can reproduce this issue) prepare a showcase repo to reproduce this issue? 🙏



> At first, I recommend clearing all application cache, for example: `rm -rf ./node_modules && yarn && cd ios && pod deintegrate && pod install && cd .. && yarn start --reset-cache"`



I already tried and got the same error

**Comment by samrith-s** [comment]
@piaskowyk I am getting this same issue, and unable to figure out why. I have a detail comment [here](https://github.com/software-mansion/react-native-reanimated/issues/2525#issuecomment-964370156). Been stuck with it for around 2 months.

**Comment by samrith-s** [comment]
Also figured by logging, `global` doesn't have `__reanimatedModuleProxy` as a property. So `global.__reanimatedModuleProxy` is always `undefined`

**Comment by samrith-s** [comment]
If you want a reproduction, you can check out the [Reanimated2 Playground sandbox created by Software Mansion](https://codesandbox.io/s/reanimated2playground-83hf7). It has the same error.

**Comment by uragecz** [comment]
Why this issue is closed ? I am having same problem on android on latest version of this library.. (using hermes)

**Comment by MichaelDanielTom** [comment]
After months of trying to figure out why, on iOS, reanimated 2.0 -2.2 was subtly not working and why 2.3 was running into this issue, I think the root problem currently is [this](https://github.com/software-mansion/react-native-reanimated/issues/2791). We had a custom `RCTBridgeDelegate` instead of using our `AppDelegate` like the template/example apps use. To fix the issue if you also have a bridge delegate, you can either:

1) Implement the requisite `sourceURLForBridge` method on your `AppDelegate` class and use your app delegate as a delegate for your bridge.
2) Make your custom `RCTBridgeDelegate` a subclass of `UIResponder`.

**Comment by samrith-s** [comment]
> After months of trying to figure out why, on iOS, reanimated 2.0 -2.2 was subtly not working and why 2.3 was running into this issue, I think the root problem currently is [this](https://github.com/software-mansion/react-native-reanimated/issues/2791). We had a custom `RCTBridgeDelegate` instead of using our `AppDelegate` like the template/example apps use. To fix the issue if you also have a bridge delegate, you can either:
> 
> 1. Implement the requisite `sourceURLForBridge` method on your `AppDelegate` class and use your app delegate as a delegate for your bridge.
> 2. Make your custom `RCTBridgeDelegate` a subclass of `UIResponder`.

This is what worked for us as well just yesterday!
