### ISSUE TITLE
[2.2.2] RN0.66 support

### ISSUE THREAD

**Issue by Sixzero** [software-mansion/react-native-reanimated#2483]
Lets create the .aar file, so without upgrading to 2.3.0-beta.2, we can use RN0.66.

Also I don't know if it is just my but upgradeing ro 2.3.0-beta.2 gives me white screen on my application main screen, I am using reanimated heavily, so I can give more details if I am going to spend time on finding the issue in the beta release, as for now I hope it is just temporary. 2.3.0-beta.1 worked like a charm with RN0.65.1.

**Comment by hannojg** [comment]
I can confirm that using RN 0.65.1 and upgrading from REA 2.3.0.beta-1 to 2.3.0.beta-2 causes a crash on iOS.

**Comment by vlad-ps** [comment]
I can deploy to an iOS device using RN 0.66 and REA 2.3.0.beta-2 and it works, but the app freezes after opening and closing any RN modal. This behaviour was previously observed on RN 65.2 and REA 2.3.0.alpha-3. Everything worked fine on RN 65.2 and REA 2.3.0.alpha-2, but I can't use REA 2.3.0.alpha-2 with RN 0.66.

**Comment by hannojg** [comment]
I will try to create a reproduction today for this issue 


Am Montag, Oktober 4, 2021, 11:19 PM schrieb Vlad Tonkonogov ***@***.***>:




I can deploy to an iOS device using RN 0.66 and REA 2.3.0.beta-2 and it works, but the app freezes after opening and closing any RN modal. This behaviour was previously observed on RN 65.2 and REA 2.3.0.alpha-3. Everything worked fine on RN 65.2 and REA 2.3.0.alpha-2, but I can't use REA 2.3.0.alpha-2 with RN 0.66.

**Comment by Sanglepp** [comment]
> I can deploy to an iOS device using RN 0.66 and REA 2.3.0.beta-2 and it works, but the app freezes after opening and closing any RN modal. This behaviour was previously observed on RN 65.2 and REA 2.3.0.alpha-3. Everything worked fine on RN 65.2 and REA 2.3.0.alpha-2, but I can't use REA 2.3.0.alpha-2 with RN 0.66.

I can confirm the freezing issue with 2.3.0.beta-2 (also with 2.3.0.alpha-3). Otherwise the app builds with RN0.66 and REA 2.3.0.beta-2. 

The feezing issue is also open here https://github.com/software-mansion/react-native-reanimated/issues/2244

**Comment by piaskowyk** [comment]
Hello everyone 👋
We have just decided to release 2.2.3 with support for `react-native@0.66` this week. So please be patient we will do it 🚀

**Comment by dotansimha** [comment]
> Hey, [`2.2.3`](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.2.3) is out! 🙂 (cc: @sbin1211 @dotansimha)

Perfect! It works with `react-native-reanimated@2.2.3`
