### ISSUE TITLE
error when i install react native reanimated v2

### ISSUE THREAD

**Issue by rismantrdr** [software-mansion/react-native-reanimated#2484]
## Description
Error when I install react-native-reanimated v2 on react native v0.66.0, 
I have to install @react-navigation/drawer v6.1.6 but I got an error like this:

> yarn run v1.22.15
> $ react-native run-android
> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
> Jetifier found 964 file(s) to forward-jetify. Using 4 workers...
> info JS server already running.
> info Installing the app...
> > Task :app:checkDebugAarMetadata FAILED
>
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
> 7 actionable tasks: 2 executed, 5 up-to-date
>
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Failed to transform react-native-reanimated-66-jsc.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
>       > Execution failed for JetifyTransform: /home/risman/drive/android/project/CashierApp/node_modules/react-native-reanimated/android/react-native-reanimated-66-jsc.aar.
>          > Transform's input file does not exist: /home/risman/drive/android/project/CashierApp/node_modules/react-native-reanimated/android/react-native-reanimated-66-jsc.aar. (See https://issuetracker.google.com/issues/158753935)
>
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>
> * Get more help at https://help.gradle.org
>
> BUILD FAILED in 7s
>
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
>
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Failed to transform react-native-reanimated-66-jsc.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
>       > Execution failed for JetifyTransform: /home/risman/drive/android/project/CashierApp/node_modules/react-native-reanimated/android/react-native-reanimated-66-jsc.aar.
>          > Transform's input file does not exist: /home/risman/drive/android/project/CashierApp/node_modules/react-native-reanimated/android/react-native-reanimated-66-jsc.aar. (See https://issuetracker.google.com/issues/158753935)
>
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>
> * Get more help at https://help.gradle.org
>
>BUILD FAILED in 7s

>   at makeError (/home/risman/drive/android/project/CashierApp/node_modules/execa/index.js:174:9)
>    at /home/risman/drive/android/project/CashierApp/node_modules/execa/index.js:278:16
>    at processTicksAndRejections (node:internal/process/task_queues:96:5)
>    at async runOnAllDevices (/home/risman/drive/android/project/CashierApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
>    at async Command.handleAction (/home/risman/drive/android/project/CashierApp/node_modules/@react-native-community/cli/build/index.js:192:9)
> info Run CLI with --verbose flag for more details.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Actual behavior & steps to reproduce
step 1 -> install react native
step 2 -> install react-navigation v6
step 3 -> install @react-navigation/drawer and yarn add react-native-gesture-handler react-native-reanimated, i follow original doc on https://reactnavigation.org/docs/drawer-navigator/#installation

## Snack or minimal code example
https://github.com/rismantrdr/react-native-reanimate_v2-issue.git

## Package versions

- React Native: 0.66.0
- React Native Reanimated: 2.3.0-beta.1
- NodeJS: v16.3.0
- Xcode: -
- Java & Gradle: openjdk version "11.0.11" 2021-04-20 & Gradle 6.9

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by eugenemlee** [comment]
I had the same error while trying to upgrade to RN 0.66. Upgrading `react-native-reanimated` to `2.3.0-beta.2` solved the above error but brought about other issues, see #2482 for example. I've opted to stick to RN 0.65.1 until `react-native-reanimated` is stable and throughly tested.

**Comment by piaskowyk** [comment]
Hello everyone! 👋  
You should update Reanimated to `2.3.0-beta.2` because since this version we added support for `react-native@0.66`

**Comment by zxwGH** [comment]
> 大家好！ 👋 你应该更新 Reanimated 到`2.3.0-beta.2`因为从这个版本我们增加了对`react-native@0.66`

你好，问题依然存在（> Task :app:checkDebugAarMetadata FAILED），我的版本react-native@0.66.2、react-native-reanimated@2.2.4，

**Comment by zxwGH** [comment]
> Hello everyone! 👋 You should update Reanimated to `2.3.0-beta.2` because since this version we added support for `react-native@0.66`

Hello, the problem still exists (> task: app: checkdebugaarmetadata failed). My version react- native@0.66.2 、react-native- reanimated@2.2.4 ，
