### ISSUE TITLE
Error build react-native project V2.2.2 -  (in target 'RNReanimated' from project 'Pods')

### ISSUE THREAD

**Issue by Remigar2012** [software-mansion/react-native-reanimated#2498]
## Description
`(in target 'RNReanimated' from project 'Pods')`

![image](https://user-images.githubusercontent.com/38878586/136201609-b08f8c04-91f2-45b0-a9fb-23a5c0d6cb99.png)

### Expected behavior
Correct build project

### Actual behavior & steps to reproduce
`npx react-native run-ios --simulator="iPhone 12"`

## Package versions

- "react-native-reanimated": "^2.2.2",
- React: v17.0.2,
- React Native":  v0.66.0,
- React Native Reanimated: v2.2.2
- NodeJS: v16.9.1
- Xcode: v13.0 (13A233)

## Affected platforms

- [x] iOS

**Comment by joshuaaron** [comment]
Also having this issue:

OS: iOS

```bash
"react": "17.0.2",
"react-native": "0.66.0",
"react-native-reanimated": "2.2.2",
"react-native-gesture-handler": "1.10.3",
```

node: v14.17.6

**Comment by purellarohith** [comment]
Same error any solution?

**Comment by mgchoi239** [comment]
Was able to resolve Build failure problem by substituting
use_flipper!( )
in ios/Podfile with
use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0','Flipper-RSocket' => '1.3.1' })
But now the app immediately closes after attempting to open it. Never ending problemss

**Comment by kondratjev** [comment]
Update `react-native-reanimated` to `2.3.0-beta.2` or higher.

**Comment by kkafar** [comment]
Hey @Remigar2012, can you confirm that updating reanimated (as @kondratjev mentioned) works?
