### ISSUE TITLE
ReferenceError: Property '_stopObservingProgress' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by DennisSnijder** [software-mansion/react-native-reanimated#2502]
## Description
When booting my app using the new reaniamted 2.3.0 - beta 2, i get the error `ReferenceError: Property '_stopObservingProgress' doesn't exist, js engine: hermes`

![](https://i.gyazo.com/c92ede2534897525fc14d29ff8cd9f2f.png)

## Package versions
- React native 0.66
- React native reanimated 2.3.0 - beta 2
- Xcode: 13

## Affected platforms
-  iOS

**Comment by Yonom** [comment]
Clearing the metro cache was enough in my case to fix this issue (tested on 2.3-beta.4), it would be great if this step was not necessary (or if instructions were provided for all the users who will upgrade to 2.3 in the final release)

**Comment by mym0404** [comment]
`yarn start --reset-cache` is a way to clear cache.

**Comment by DennisSnijder** [comment]
Seems to be fixed in the newer releases, cheers @piaskowyk

**Comment by nandorojo** [comment]
This error is breaking Expo Snack SDK 44 with Reanimated 2.3: https://github.com/expo/snack/issues/245

**Comment by pke** [comment]
> Seems to be fixed in the newer releases, cheers @piaskowyk

No its not. Just ran into this when updating from 2.2.4 to 2.5.0
