### ISSUE TITLE
2.3.0-beta.2 TypeScript issues

### ISSUE THREAD

**Issue by mjmasn** [software-mansion/react-native-reanimated#2510]
## Description
```
node_modules/react-native-reanimated/react-native-reanimated.d.ts:439:17 - error TS2314: Generic type 'AnimateStyle' requires 1 type argument(s).

439     animations: AnimateStyle;
                    ~~~~~~~~~~~~

node_modules/react-native-reanimated/react-native-reanimated.d.ts:662:44 - error TS2304: Cannot find name 'ScrollView'.

662     ref: RefObject<ReactNativeScrollView | ScrollView>,
                                               ~~~~~~~~~~

node_modules/react-native-reanimated/react-native-reanimated.d.ts:1061:50 - error TS2339: Property 'ReverseAnimation' does not exist on type 'typeof Animated'.

1061   export const ReverseAnimation: typeof Animated.ReverseAnimation;
                                                      ~~~~~~~~~~~~~~~~


Found 3 errors.
```

### Expected behavior

No TypeScript errors from within the library

### Actual behavior & steps to reproduce

Install 2.3.0-beta.2 and run `tsc --noEmit`

## Snack or minimal code example
n/a

## Package versions

- React Native: 0.66
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: v16.10.0
- Xcode: Version 13.0 (13A233)
- Java & Gradle: 17 / 7.3 nightly build
- TypeScript: 4.2.3

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by mjmasn** [comment]
@TheWirv Thanks for taking the time to write a smart-arse comment but I'm reporting a bug in the TS definitions for a pre-release version of this library, not something from my own code. Granted I could probably work my way through each error and submit a PR but I imagine it's probably a minor oversight and being unfamiliar with the internals of reanimated I'm sure it'll be a much quicker fix for someone who already knows the codebase.

**Comment by TheWirv** [comment]
Oh, you're right. I didn't catch that. I am truly sorry! It's just, the open source community is full of people just dumping their shit into an issue without doing their own research, and this looked to me like you reported errors that TS threw in your own codebase. I don't `tsc` the `node_modules` dir, so I never noticed this issue.

I'll take everything back. Again, I'm sorry. 🙏🏼

**Comment by adbl** [comment]
Off topic: I wish everyone had the maturity and courage to own and take back like was done here! 🤩

**Comment by SimenB** [comment]
Still an issue with the stable release 2.3.1 which is included with Expo 44

**Comment by Latropos** [comment]
In meantime we have made heavy refactors on our typescript types, everything should work now.
