### ISSUE TITLE
Layout Animation not started in inline conditional operator

### ISSUE THREAD

**Issue by wjaykim** [software-mansion/react-native-reanimated#2517]
## Description

When I try to apply layout animation using inline if-else conditional operator(`boolean ? Component1 : Component2`), layout animation is not started when the condition changes.

But I found that when I use inline if conditional operator(`boolean && Component`), entering/exiting animation works.

### Expected behavior

Layout animation(Entering, Exiting) is started when condition variable changes

### Actual behavior & steps to reproduce

Animation not started

## Snack or minimal code example

https://snack.expo.dev/YHC4fTh9s

```js
export default function App() {
  const [enabled, setEnabled] = React.useState(false);
  return (
    <View style={styles.container}>
      {/* NOT WORKING */}
      {enabled ? (
        <Animated.Text entering={FadeIn} exiting={FadeOut}>
          Enabled
        </Animated.Text>
      ) : (
        <Animated.Text entering={FadeIn} exiting={FadeOut}>
          Disabled
        </Animated.Text>
      )}
      {/* WORKING */}
      {enabled && 
        <Animated.Text entering={FadeIn} exiting={FadeOut}>
          Enabled
        </Animated.Text>
      }
      {!enabled && 
        <Animated.Text entering={FadeIn} exiting={FadeOut}>
          Disabled
        </Animated.Text>
      }
      <Button title="toggle" onPress={() => setEnabled(!enabled)} />
    </View>
  );
}
```

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: 14
- Xcode: 13
- Java: 8
- Gradle: 7.0.2

## Affected platforms

- [ ] Android (Not Tested)
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
In layout animation, we base on react operation `mount`, `layout`(update) and `unmount` and this
```js
{enabled ? (
  <Animated.Text entering={FadeIn} exiting={FadeOut}>
    Enabled
  </Animated.Text>
) : (
  <Animated.Text entering={FadeIn} exiting={FadeOut}>
    Disabled
  </Animated.Text>
)}
```
is interpreted by react as `layout`
but this
```js
{enabled && 
  <Animated.Text entering={FadeIn} exiting={FadeOut}>
    Enabled
  </Animated.Text>
}
{!enabled && 
  <Animated.Text entering={FadeIn} exiting={FadeOut}>
    Disabled
  </Animated.Text>
}
```
is interpreted by react as `unmount` and `mount`
so It's actually not a bug because we are based on react events.

**Comment by frantisekhanzlikbl** [comment]
note to future myself or anyone who runs into this:

it's enough to add the `key` props to the switched views, and everything works as expected.
