### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')

### ISSUE THREAD

**Issue by shobhitsinghal624** [software-mansion/react-native-reanimated#2525]
## Description

App crashes with this error:
```
TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
```

### Expected behavior
App should not crash.

### Actual behavior & steps to reproduce
NA

## Snack or minimal code example
NA

## Package versions

- React Native: 0.66
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: v14.17.6
- Xcode: 13
- Java & Gradle: latest

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

![image](https://user-images.githubusercontent.com/4579093/136814252-23b629f8-b681-4662-957e-1b348e62399c.png)

**Comment by mjmasn** [comment]
I'm taking a look a reproducing this with a fresh RN app 👍🏻 will report back soon!

**Comment by mjmasn** [comment]
In the meantime here is my `npx react-native info` output:
```
❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 214.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: javac 17 - /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mjmasn** [comment]
Sorry I take that back, this does error with the SalesForce SDK-generated app, both on Android and iOS just by importing `import Animated from 'react-native-reanimated'` in index.js. Maybe they didn't upgrade their template correctly for RN 0.66...

**Comment by gavrichards** [comment]
I've figured it out - there are some steps in the installation docs that must not have been there when I initially installed this package.
Step 2 here: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android
My app is now starting up successfully. Thanks for the nudge @mjmasn.

**Comment by harrymash2006** [comment]
Hi guys, anyone got this fixed ?

**Comment by samrith-s** [comment]
I have followed all the steps, but things are still not working. It works on Android, but doesn;t work on iOS. What am I missing?
```bash
info Fetching system and libraries information...
(node:74558) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/samrith.shankar/Work/d11/d11-react-native/node_modules/chai/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 920.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /var/folders/y_/gy00qtms2kq6v3380xs2k1cm0000gq/T/yarn--1636477167680-0.13777315466882145/node
    Yarn: 1.22.11 - /var/folders/y_/gy00qtms2kq6v3380xs2k1cm0000gq/T/yarn--1636477167680-0.13777315466882145/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-25 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.2 => 0.66.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Reanimated version: `2.3.0-beta.2`

I keep getting this error:
```bash
ERROR  TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes
ERROR  Error: Requiring module "d11-app/src/components/DummyNotification.tsx", which threw an exception: TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes
```

I did some digging and
-  it seems that the error is coming in [this file and line](https://github.com/software-mansion/react-native-reanimated/blob/master/src/reanimated2/NativeReanimated/NativeReanimated.ts#L15)
- it can't find `InnerNativeModules` which is being assigned in [this line](https://github.com/software-mansion/react-native-reanimated/blob/master/src/reanimated2/NativeReanimated/NativeReanimated.ts#L4)

**Comment by crstian** [comment]
I think I figured it out. In my case it worked on Android, but didn't work on iOS. It is now working fine.

I followed all the installation steps [here](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation) - and therefore turned off autoinstall by mistake:
```
post_install do |installer|
   installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
           config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
       end
   end
end
```

After removing the compilation flag **DONT_AUTOINSTALL_REANIMATED** again, it worked. Please make sure to re-install your pods and clean your npm cache.

Hope that helps!

**Comment by enaqx** [comment]
I do expereince the same issue, but in my case it fails for App Clip https://developer.apple.com/app-clips/ iOS target. It works for ordinary iOS target.


Here is my Pofdile

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'UnrollMe' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'Unroll.me' do
    inherit! :complete
  end
end
```

and react-native info

```➤ npx react-native info*
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 487.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by AdamTyler** [comment]
I spent a few hours debugging this and my issue was very specific and might not apply to everyone but as a data point:

The issue I ran into was my `AppDelegate` main class was extending `NSObject` instead of the react native default `UIResponder`.
Making that change resolved my issue.

**Comment by fuekiin** [comment]
Running into the same Issue trying to use reanimated within a Swift Framework.

**Comment by hugosbg** [comment]
I temporarily resolved that way

downgrade from **2.3.1** to **2.2.4**

```bash
yarn remove react-native-reanimated
yarn add react-native-reanimated@2.2.4 -E
```

and with these installation instructions: https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/installation

my environment is like this

```text
"react": "17.0.2",
"react-native": "0.66.4"
"react-native-reanimated": "2.2.4"
...
```

**Comment by daheeahn** [comment]
> I temporarily resolved that way
> 
> downgrade from **2.3.1** to **2.2.4**
> 
> ```shell
> yarn remove react-native-reanimated
> yarn add react-native-reanimated@2.2.4 -E
> ```
> 
> and with these installation instructions: https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/installation
> 
> my environment is like this
> 
> ```
> "react": "17.0.2",
> "react-native": "0.66.4"
> "react-native-reanimated": "2.2.4"
> ...
> ```

Thx!!!

**Comment by piaskowyk** [comment]
Has anyone got this issue still?

**Comment by TomasSestak** [comment]
> Has anyone got this issue still?

Yep after I downgraded to 2.2.0, because getting weird bugs on newest version but Expo notifies that I need to update. When I update its ok tho

**Comment by piaskowyk** [comment]
@TomasSestak could you provide me a repo to reproduce the issue? It helps me a lot! 🙏

**Comment by charity-detalytics** [comment]
@piaskowyk How about this https://codesandbox.io/s/reanimated2playground-83hf7?

**Comment by BadduCoder** [comment]
> I've figured it out - there are some steps in the installation docs that must not have been there when I initially installed this package. Step 2 here: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android My app is now starting up successfully. Thanks for the nudge @mjmasn.

Just follow this guide:
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android

Thanks @gavrichards @mjmasn

**Comment by piaskowyk** [comment]
@charity-detalytics
> @piaskowyk How about this https://codesandbox.io/s/reanimated2playground-83hf7?

To resolve this issue on the web you should update reanimated to 2.3.1

**Comment by piaskowyk** [comment]
The most probable causes of this issue are:
- you added `DONT_AUTOINSTALL_REANIMATED` flag to your Podfile
- you didn't complete installation steps from - https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation
To be sure, please clear the application cache also.

**Comment by piaskowyk** [comment]
If this doesn't help please provide me a repo to reproduce the issue and we will fix it.

**Comment by rohitjindal018** [comment]
> The most probable causes of this issue are:
> 
> * you added `DONT_AUTOINSTALL_REANIMATED` flag to your Podfile
> * you didn't complete installation steps from - https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation
>   To be sure, please clear the application cache also.

Tried the above, still doesn't work. Trying to setup renanimated2 with swift. Have tried with both (with and without CPP flag).  still getting installCoreFunctions is undefined. global.__reanimatedModuleProxy is not getting set.

**Comment by charity-detalytics** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735456092 works for me.

**Comment by rohitjindal018** [comment]
> [#1439 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735456092) works for me.

Worked like a charm for me. Thanks

**Comment by frankbolviken** [comment]
We have this issue still on our app. Works fine on iOS until 2.2.0, but upgrading beyond 2.3.0 and this error arrives. We need to have a version which does not require hermes.
