### ISSUE TITLE
Jest test failed SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by TaufanP** [software-mansion/react-native-reanimated#2526]
## Description

I create a simple PanGestureHandler layout and use onGestureEvent to change my useSharedValue. The animation works fine, but I got an error on my test.

### Expected behavior
The test should succeed, I just test the snapshot. I also have configured my setup-jest file for react-native-reanimted from react native navigation docs. https://reactnavigation.org/docs/testing/

### Actual behavior & steps to reproduce
![image](https://user-images.githubusercontent.com/33638021/136888726-722e2625-6e75-487c-9566-f4abea04f250.png)

Steps to reproduce:
run yarn jest

my test file:
```
import "react-native";
import React from "react";
import App from "../App";
import { act, create } from "react-test-renderer";

it("renders correctly", async () => {
  await act(async () => expect(create(<App />).toJSON()).toMatchSnapshot());
});
```

## Snack or minimal code example
```
import React, { PropsWithChildren } from "react";
import {
  PanGestureHandler,
  PanGestureHandlerGestureEvent,
} from "react-native-gesture-handler";
import Animated, {
  useAnimatedGestureHandler,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from "react-native-reanimated";
import { TouchProps } from "./type";

const Touch = ({
  children,
  ...props
}: PropsWithChildren<TouchProps>) => {

  const scale = useSharedValue(1);

  const onGestureEvent =
    useAnimatedGestureHandler<PanGestureHandlerGestureEvent>({
      onStart: () => (scale.value = withTiming(0.96, { duration: 80 })),
      onActive: () => (scale.value = withTiming(0.96, { duration: 80 })),
      onFinish: () => (scale.value = withTiming(1)),
      onEnd: () => (scale.value = withTiming(1)),
    });

  const touchStyle = useAnimatedStyle(() => ({
    transform: [{ scale: scale.value }],
  }));

  return (
    <PanGestureHandler {...props} onGestureEvent={onGestureEvent}>
      <Animated.View style={touchStyle}>{children}</Animated.View>
    </PanGestureHandler>
  );
};

export default Touch;
```

**Setup file**
```
import "react-native-gesture-handler/jestSetup";

jest.mock("react-native-reanimated", () => {
  const Reanimated = require("react-native-reanimated/mock");
  Reanimated.default.call = () => {};

  return Reanimated;
});

// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock("react-native/Libraries/Animated/NativeAnimatedHelper");

```

## Package versions

- React Native: 0.66.0
- React Native Reanimated: 2.3.0-beta.2

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by kkafar** [comment]
I failed to reproduce exactly the same error, but had something close (the same error message, but for different token).

To get `jest` to work with typescript & reanimated you should make sure you did the following: 

* Follow [reanimated docs on jest setup](https://docs.swmansion.com/react-native-reanimated/docs/guide/testing/)
* By default all content of the `node_modules` dir is ignored by plugin, so you need to enable it at least for `react-native` & `reanimated` so the source code gets transpiled (I found it also necessary to enable `@react-native`). To enable, you simply put the following in you jest config:

```
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|react-native-reanimated|@react-native)/)',
  ]
```
* I also had these dev dependencies installed:
```
  "devDependencies": {
...
    "@babel/preset-env": "^7.16.4",
    "@babel/preset-typescript": "^7.16.0",
...
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.66.4",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
...
    "jest": "^27.3.1",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
```





You can take look at how to setup jest tests for reanimated in [this template repo](https://github.com/kkafar/basic-reanimated-setup).

**Comment by kkafar** [comment]
More over this
* https://github.com/software-mansion/react-native-reanimated/pull/2549

should have fixed it
