### ISSUE TITLE
Animated ScrollView _this.props.OnScroll is not a function

### ISSUE THREAD

**Issue by rnnyrk** [software-mansion/react-native-reanimated#2529]
## Description
I would like to animate a React Navigation header based on scrolling an `Animated.ScrollView`. Initially this works perfect. Although, when developing and the application is hot reloading, the scrolling seems to breaks. It looks like the `props.onScroll` method all of a sudden removed from the `ScrollView` (see screenshot). 

It's hard to debug what to do about this, so I was hoping anyone here has any clue?

In the repository these are the relevant files:
- [ScrollContext](https://github.com/react-prime/react-prime-native/blob/moti-tryout/src/app/components/modules/general/ScrollContext/index.tsx)
- [ScreenHeader](https://github.com/react-prime/react-prime-native/blob/moti-tryout/src/app/components/modules/headers/ScreenHeader/index.tsx)
- [Dashboard](https://github.com/react-prime/react-prime-native/blob/moti-tryout/src/app/components/screens/general/Dashboard/index.tsx)

<img width="411" alt="Screenshot 2021-10-12 at 15 08 05" src="https://user-images.githubusercontent.com/4519142/136962021-3caeb7e1-fc65-4375-ad86-11963559eb05.png">

### Expected behavior
On refresh (Hot Reload) the scroll behaviour should be exactly the same as before hot reloading. 

### Actual behavior & steps to reproduce
1. [Download the repo](https://github.com/react-prime/react-prime-native/tree/moti-tryout)
2. `npm install && cd ios && pod install`
3. Open xcode
4. Run project in simulator with scheme "Test - Debug"
5. On the Onboarding screen press "Go"
6. Next page "Dashboard" is as explained above

## Snack or minimal code example
[See the repository, branch moti-tryout](https://github.com/react-prime/react-prime-native/tree/moti-tryout)

## Package versions
- React Native: "react-native": "0.65.1",
- React Native Reanimated: "react-native-reanimated": "2.2.2",
- NodeJS: v14.16.0
- Xcode: Version 13.0 (13A233)
- Java & Gradle: - (only iOS for now)

**React Navigation:**
- "@react-navigation/bottom-tabs": "6.0.7",
- "@react-navigation/native": "6.0.4",
- "@react-navigation/stack": "6.0.9",

## Affected platforms
- [ ] Android
- [x] iOS
- [ ] Web

**Comment by ErkanGorgulu** [comment]
I just had this error with `Animated.FlatList`. I updated the package to `2.4.1`, tried creating animated component with Animated.createAnimatedComponent but it still didn't work. I tried using multiple events like 

`  const scrollHandler = useAnimatedScrollHandler({
    onScroll: event => {
      scrollY.value = event.contentOffset.y;
    },
    onBeginDrag: e => {
      scrollY.value = true;
    },
    onEndDrag: e => {
      scrollY.value = false;
    }
  });`

and tried using single `onScroll` event but still, I got this error. I didn't try it on `ScrollView` since I really depend on `pullToRefresh` and `onEndReached` which `ScrollView` doesn't have. The only thing I was able to find is that `useAnimatedScrollHandler` returns an object instead of a function which creates this error. When I tried logging the object I got this:

`{"current": {"eventNames": ["onScroll"], "listeners": {}, "reattachNeeded": false, "registrations": [], "viewTag": undefined, "worklet": [Function _f]}}`

Maybe someone can elaborate what is going on and help with the issue. Thanks in advance.

**Comment by JameDodgers** [comment]
> I just had this error with `Animated.FlatList`. I updated the package to `2.4.1`, tried creating animated component with Animated.createAnimatedComponent but it still didn't work. I tried using multiple events like
> 
> ` const scrollHandler = useAnimatedScrollHandler({ onScroll: event => { scrollY.value = event.contentOffset.y; }, onBeginDrag: e => { scrollY.value = true; }, onEndDrag: e => { scrollY.value = false; } });`
> 
> and tried using single `onScroll` event but still, I got this error. I didn't try it on `ScrollView` since I really depend on `pullToRefresh` and `onEndReached` which `ScrollView` doesn't have. The only thing I was able to find is that `useAnimatedScrollHandler` returns an object instead of a function which creates this error. When I tried logging the object I got this:
> 
> `{"current": {"eventNames": ["onScroll"], "listeners": {}, "reattachNeeded": false, "registrations": [], "viewTag": undefined, "worklet": [Function _f]}}`
> 
> Maybe someone can elaborate what is going on and help with the issue. Thanks in advance.

Check if you're importing Animated from react-native-reanimated and not react-native. After changing that I stopped getting this error.

**Comment by K-Jaiswal-Ashish** [comment]
I am facing same issue , Above solution did not work for me

**Comment by simeon619** [comment]
@K-Jaiswal-Ashish  use Animated from reanimated and not react-native

**Comment by Dugariya** [comment]
I am facing same issue , Above solution did not work for me

**Comment by L4liK0rn** [comment]
I am facing same issue , Above solution did not work for me

**Comment by Pullze** [comment]
For those facing the same issue recently, try to set `useNativeDriver` to false in `Animated.event`'s config like this:
```JavaScript
Animated.event(
            [{
                nativeEvent: {
                ...
             },],
            // if use native driver, then cause an error
            { useNativeDriver: false },)
```
This solved the issue on my side, but I don't know what triggered this exactly.

**Comment by atultiwaree** [comment]
> > I just had this error with `Animated.FlatList`. I updated the package to `2.4.1`, tried creating animated component with Animated.createAnimatedComponent but it still didn't work. I tried using multiple events like
> > ` const scrollHandler = useAnimatedScrollHandler({ onScroll: event => { scrollY.value = event.contentOffset.y; }, onBeginDrag: e => { scrollY.value = true; }, onEndDrag: e => { scrollY.value = false; } });`
> > and tried using single `onScroll` event but still, I got this error. I didn't try it on `ScrollView` since I really depend on `pullToRefresh` and `onEndReached` which `ScrollView` doesn't have. The only thing I was able to find is that `useAnimatedScrollHandler` returns an object instead of a function which creates this error. When I tried logging the object I got this:
> > `{"current": {"eventNames": ["onScroll"], "listeners": {}, "reattachNeeded": false, "registrations": [], "viewTag": undefined, "worklet": [Function _f]}}`
> > Maybe someone can elaborate what is going on and help with the issue. Thanks in advance.
> 
> Check if you're importing Animated from react-native-reanimated and not react-native. After changing that I stopped getting this error.

Animated is not present in react-native-reanimated not getting any suggestions in vscode

**Comment by Snouzy** [comment]
> Animated is not present in react-native-reanimated not getting any suggestions in vscode

it's a default export so you have to do something like this : 

`import Animated, { useAnimatedScrollHandler, useAnimatedStyle, useSharedValue, withSpring, withTiming } from 'react-native-reanimated'`

**Comment by jakubboguski** [comment]
Tip: Make sure the component you're using `onScroll` comes from `Animated` ([ref](https://docs.swmansion.com/react-native-reanimated/docs/2.x/api/hooks/useAnimatedScrollHandler/#example))

**Comment by kuldeep-IT** [comment]
> For those facing the same issue recently, try to set `useNativeDriver` to false in `Animated.event`'s config like this:
> 
> Animated.event(
>             [{
>                 nativeEvent: {
>                 ...
>              },],
>             // if use native driver, then cause an error
>             { useNativeDriver: false },)
> This solved the issue on my side, but I don't know what triggered this exactly.

Thank you so much! It's worked for me and you saved my time 😍

**Comment by ET-isReady** [comment]
Instead of using <ScrollView>, use <Animated.ScrollView>

**Comment by ET-isReady** [comment]
Use <Animated.ScrollView> instead of just regular ScrollView

**Comment by lawvs** [comment]
Make sure to import `Animated` from `react-native-reanimated` instead of `react-native`!

```diff
- import { Animated } from "react-native"
+ import Animated from "react-native-reanimated"
```

**Comment by atitpatel** [comment]
@Snouzy I was in a similar boat as yours and got around it by:

`
     
    // using a simple scrollHandler function did the trick for me
    const handleScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
        const offsetY = event.nativeEvent.contentOffset.y;
        showCollapsedHeader.value = offsetY > animationOffset;
    };


    return (
        <View style={styles.container}>
            {shouldShowCollapsedHeader && (
                <Animated.View style={[styles.header, animatedStyles]}>
                    <HeaderVariations.Basic title={title} subTitle={subTitle} rightNodes={headerRightNodes} />
                </Animated.View>
            )}
            <SectionList {...otherProps} onScroll={handleScroll} scrollEventThrottle={16} ref={listRef} />
        </View>
    );
`
