### ISSUE TITLE
undefined is not an object (evaluating 'previousValue.toString')

### ISSUE THREAD

**Issue by purnadi-winarno** [software-mansion/react-native-reanimated#2531]
### Expected behavior
app can run without error

## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Closing due to not providing a reproduction.
