### ISSUE TITLE
"react-native-reanimated": "2.3.0-alpha.2" Not working

### ISSUE THREAD

**Issue by rajwebsoft** [software-mansion/react-native-reanimated#2536]
When using this plugins then screen will hand if open the model pull the FlatList, also any where pull page also stack the screen or lock screen, also workin in lower version "2.2.2" on react-native "react-native": "^0.66.0"

So please help me or upgrade with 2.3 stable version,

## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by kacperkapusciak** [comment]
Closing due to no response.
