### ISSUE TITLE
Animation glitches when re-rendering (2.3.0.beta.2)

### ISSUE THREAD

**Issue by bobsmits** [software-mansion/react-native-reanimated#2540]
## Description

The animation returns to its starting position for 1 frame when a component re-renders.
https://user-images.githubusercontent.com/20045348/137302524-276f465d-e591-4703-b657-70c316b507d0.mp4

### Expected behavior

The animations runs smoothly when a component re-renders

### Actual behavior & steps to reproduce

Updating the component while the animation is running causes glitches

## Snack or minimal code example

```
import React, {useEffect, useState} from 'react';
import {View} from 'react-native';
import Reanimated, {
  Easing,
  interpolate,
  useSharedValue,
  runOnJS,
  withTiming,
  useAnimatedStyle,
} from 'react-native-reanimated';

export default () => {
  const transition = useSharedValue(0);

  const [status, setStatus] = useState('closed'); // closed | open | closing | done
  useEffect(() => {
    setTimeout(start, 200);
  }, []);

  const start = () => {
    setTimeout(() => {
      runOnJS(setStatus)('open');
    }, 800);

    transition.value = withTiming(1, {
      duration: 3 * 1000,
      easing: Easing.bezier(0.17, 0.36, 0.16, 1.01),
    });
  };

  const animatedStyle = useAnimatedStyle(
    () => ({
      transform: [
        {
          translateY: interpolate(transition.value, [0, 1.0], [0, 250]),
        },
      ],
    }),
    [],
  );

  return (
    <View
      style={{
        width: '100%',
        height: '100%',
        padding: 20,
        backgroundColor: 'green',
      }}>
      <Reanimated.View
        style={[
          {
            width: 50,
            height: 50,
            position: 'absolute',
            top: 40,
            left: 40,
            backgroundColor: 'red',
          },
          animatedStyle,
        ]}
      />
    </View>
  );
};
```

## Package versions

- React Native: 0.63.3
- React Native Reanimated: 2.3.0.beta.2 

## Affected platforms

- [ ] Android (Did not test)
- [x] iOS
- [ ] Web

**Comment by msageryd** [comment]
I might have a similar problem.
I'm rendering two Animated.View on top of each other with absolute positioning. The top view is animated (scaling in and out over the bottom view).

Sometimes I see a glitch at the beginning of the animation. The glitch never appears in the simulator, only on an iOS device (I haven't tried on Android).

I recorded the animation so I could step trough frame by frame in iMovie. It looks as if the top view is not rendered for exactly one frame, which makes the bottom view fully visible. The frame in which this happens is frame no 2, i.e. almost att the start of the animation.

I have checked the sharedValue and it seems fine. I did this by console logging from inside of useDerivedValue. The sharedValue always seems to be a consistent nice series of incrementing values.

I have tried to speed up and slow doen the animation. It doesn't matter if the animation is 100ms or several seconds. The glitch always looks the same and it always appears for a single frame. It's not consistent. I'd say that it glitches about 1/3 or 1/4 of the animations, i.e. sometimes everything looks perfect.

I have tried with and without animating the opacity. No difference.

I have also tried without scaling transformation, i.e. only a translateX. No difference.

What can I do to debug this further?

**Comment by msageryd** [comment]
Follow up..
I will try to share the recordings to explain the glitch.

The first file is the transition in full speed. The glitch is quite obvious.
https://user-images.githubusercontent.com/4483085/149636861-686868e0-afc5-4bbd-8266-eebb3d38f363.mp4

The second file is showing the glitch frame by frame. After a couple of frames, I reverse and go back frame by frame to see the glitch again.
https://user-images.githubusercontent.com/4483085/149636867-6b3b03f3-9208-43a6-a226-e99e975bd73d.mp4

I have console.logged everywhere I suspected something fishy happening, but I cannot catch anything unusual. The rendered components, the shared value, the mounting and unmounting, the coodfinates, etc. Everything looks exactly the same with or without the glitch, which makes me think that something is going on at the native side.

**Comment by Tauka** [comment]
I'm experiencing this issue with `react-native-reanimated@2.7.0`, `react-native@0.68.1`, on iOS 15.4.1

**Comment by Latropos** [comment]
I've just tested the issue with the newest version of Reanimated 3 and it seems that the issue no longer persists. Please see the attached recording:

https://github.com/software-mansion/react-native-reanimated/assets/56199675/19adbec6-39fb-4a65-bfba-877917132997
