### ISSUE TITLE
setState called without a StateWrapper

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#2544]
Hi,

## Description
In my project im using Reanimated `v.2.2.2` with `react-native v0.64.2` and its almost working perfectly everywhere. 
I have lots of gestures and animations in my project with it , like pinch activities, drag and drops, drag and sorts etc... they all working fine on this version. 

BUT, yesterday i just wanted to make a button draggable around the screen, 
with a component like this:

```
const CreatePostButton = ({color, onPress}) => {
  const translateX = useSharedValue(1);
  const translateY = useSharedValue(1);

  const gestureHandler = useAnimatedGestureHandler({
    onStart: (_, ctx) => {
      ctx.PosX = translateX.value;
      ctx.PosY = translateY.value;
    },
    onActive: (event, ctx) => {
      translateX.value = event.translationX + ctx.PosX;
      translateY.value = event.translationY + ctx.PosY;
    },
    onEnd: (event, ctx) => {
      if (translateY.value > -height / 5 || translateY.value < -height + height / 3.5) {
        translateX.value = withTiming(1);
        translateY.value = withTiming(1);
      }
    },
  });

  const rStyle = useAnimatedStyle(() => {
    return {
      backgroundColor: color || colorsComponent.mainBackgroundColor,
      transform: [{translateX: translateX.value}, {translateY: translateY.value}],
      zIndex: 999,
      width: 50,
      height: 50,
      justifyContent: "center",
      bottom: 25,
      alignItems: "center",
      shadowColor: "#000",
      borderRadius: 25,
      borderWidth: 3,
      borderColor: colorsComponent.defaultBackgroundColor,
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.15,
      shadowRadius: 3,
      elevation: 5,
    };
  });
  return (
    <TapGestureHandler onActivated={onPress}>
      <Animated.View style={rStyle}>
        <PanGestureHandler maxPointers={1} onGestureEvent={gestureHandler}>
          <Animated.View style={StyleSheet.absoluteFill}>
            <FastImage source={imagesMain.plus_stroke} style={{width: 20, height: 20}} resizeMode="contain" />
          </Animated.View>
        </PanGestureHandler>
      </Animated.View>
    </TapGestureHandler>
  );
};
```

as you can see its not that complicated one, it is very simple drag and drop but after i ve done this, i've got a release.apk to test it, and once i open the screen where this button included, the app crashed. On crash report i just saw
`onRender error` with reanimated, then i used logcat to get more detail  and found following error:

`E/unknown:FabricViewStateManager: setState called without a StateWrapper`

Interesting thing is, im not getting any errors on debug apk.  on Debug mode everything works fine, this happens only on release apk thats why i used logcat to debug this error.

## Package Versions
    "react-native-reanimated": "^2.2.2",
    "react-native": "0.64.2",
    "react-native-gesture-handler": "^1.8.0",

## Expected Behavior

----

## actual behavior & steps to reproduce seems

----

**Comment by Bayramito** [comment]
FIXED! 

I actually noticed lately that i passed all the styles throught the `useAnimatedStyle` like shadows like position justifycontent etc..  so i move them into StyleSheet and give them to the element as like `style={[animatedStyle,styles.animatedContainer]}` and it fixed

**Comment by mwegener-com** [comment]
Same problem but I never used useAnimatedStyle

**Comment by lreardon** [comment]
Any update on this? I'm experiencing the same issue

**Comment by gaberogan** [comment]
Has anyone found any workarounds? I'm experiencing the same issue.
