### ISSUE TITLE
Exception thrown while executing UI block: Attempted to remove non-existent subview

### ISSUE THREAD

**Issue by nomi9995** [software-mansion/react-native-reanimated#2554]
<img src="https://user-images.githubusercontent.com/36044436/138065953-6d9d1085-462c-4cf9-99c3-e9630c848345.png" width="300" />

## Description
I am using [react-native-shimmer](https://github.com/oblador/react-native-shimmer). when I update `react-native@0.66.1` and `react-native-reanimated@2.3.0-alpha.3` then I am receiving the below error 
```
Exception thrown while executing UI block: Attempted to remove non-existent subview
```
at

https://github.com/software-mansion/react-native-reanimated/blob/ce76e66aaf47c26bb1ff818d72a50b55e092ca05/ios/LayoutReanimation/REAAnimationsManager.m#L101

because it has conflict with [react-native-shimmer](https://github.com/oblador/react-native-shimmer)

[RNShimmeringView.m#L28](https://github.com/oblador/react-native-shimmer/blob/620a9e899df40e1bef38127d4ef61384e1a195c5/ios/RNShimmeringView.m#L28)

### Expected behavior
Should not throw the error.

### Actual behavior & Steps To Reproduce
Repro: https://github.com/nomi9995/ReproNonExistentsubview
Throws an error but still works if I just close it.

just installed  `Package versions` which I added below. 
then below code will reproduce this error
```
import React, {useState} from 'react';
import {SafeAreaView, StyleSheet, Text, View, Button} from 'react-native';
import Shimmer from 'react-native-shimmer';

const App = () => {
  const [isVisible, setIsVisible] = useState<boolean>(true);

  return (
    <SafeAreaView style={styles.container}>
      {isVisible && (
        <Shimmer>
          <Text>Loading...</Text>
        </Shimmer>
      )}
      <Button
        onPress={() => setIsVisible(!isVisible)}
        title={isVisible ? 'Hide' : 'Visible'}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default App;
```

## Package versions

- React Native: ^v0.66.1
- React Native Reanimated: ^2.3.0-alpha.3
- react-native-shimmer: ^0.6.0

## Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
I prepared PR with a fix but I think that this should be fixed by the shimmer side. I prepared PR for shimmer also, and we will see.

**Comment by piaskowyk** [comment]
I prepared PR to fix it by Shimmer side - https://github.com/oblador/react-native-shimmer/pull/33

**Comment by piaskowyk** [comment]
I need to wait for a reply from the Shimmer maintainter. If you need a hotfix you can use a package patch with one of my PR.

**Comment by nomi9995** [comment]
@piaskowyk I also made a patch to shimmer along ago when I opened this issue but if another library is also using the same thing then I think reanimated should check subview exist or not

**Comment by piaskowyk** [comment]
Standard `removeReactSubview` doesn't throw exceptions if you remove components again, so this is a little change in interface. I think we should keep the react's interface.
