### ISSUE TITLE
iOS crash EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Gentlee** [software-mansion/react-native-reanimated#2556]
## Description

We got native crashes periodically EXC_BAD_ACCESS.

### Expected behavior

no crashes

### Actual behavior & steps to reproduce

This one i caught on ios simulator. Also receive other crashes periodically on lower versions of reanimated and react-native, on ios and android devices.

 We have lots of reanimated code, not sure what to sent here because not sure what actually causes the crash.

## Snack or minimal code example

![Screenshot 2021-10-21 at 01 18 03](https://user-images.githubusercontent.com/2361140/138180780-165438e3-8735-4623-936c-9231485193c1.png)

![Screenshot 2021-10-21 at 01 20 35](https://user-images.githubusercontent.com/2361140/138180787-867fabc2-a99f-46e8-84a0-1e57a4ee7063.png)

## Package versions

- React Native: 0.66.1
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: v14.17.6
- Xcode: 12.5.1

## Affected platforms

- [ ] Android
- [x] iOS Simulator
- [ ] Web

**Comment by piaskowyk** [comment]
Should be fixed with - https://github.com/software-mansion/react-native-reanimated/pull/2512
Could you try to run the latest version of reanimated beta? If a problem still exists please let me know
