### ISSUE TITLE
Animated.event crashing the app

### ISSUE THREAD

**Issue by SourceCipher** [software-mansion/react-native-reanimated#2570]
### Expected behavior
App should not crash and the card swiping should be working fine

### Actual behavior & steps to reproduce
After the bundling is finished, the app crashes with the following error:

![image](https://user-images.githubusercontent.com/351018/138597256-bfa8ce45-4f5a-4027-9eb4-d924f47c1ddb.png)

## Snack or minimal code example

The issue is within this code, but cant understand whats causing it. This code is within constructor:

```
 this.onGestureEvent = Animated.event([{ nativeEvent: { translationX: this.dragX } }], {
      useNativeDriver: true,
      listener: this.handleOverlays,
    })
```

It was working just fine couple of weeks ago. Have no idea whats causing this to crash now. I have tried reinstalling node modules, cache clean etc, many times. Same result. I also tried updating to the latest animated library, but the app not even builds.

## Package versions

- React Native:  **^0.65.1**
- React Native Reanimated: **2.3.0-alpha.3**
- NodeJS: **14.17.6**
- Xcode: -
- Java & Gradle:  **14.0.2.0 & 4.2.1**

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by jakub-gonet** [comment]
We have too little information on this one. Could you prepare a minimal repro example so we can check it out ourselves?
