### ISSUE TITLE
[ios] Race condition causing animation style not to be applied

### ISSUE THREAD

**Issue by hannojg** [software-mansion/react-native-reanimated#2571]
## Description

In our app, we have a page where a view gets measured. Based on the view's layout we apply some animated styles to some other animated components on that page.

We noticed that upon opening the page the animated style hasn't always been applied, although we could tell from the logs, that the measurement took place and the shared value has been updated to the view's layout.

### Expected behavior

After the view has been measured and the shared value has been updated, the animated styles "get updated" accordingly.

### Actual behavior & steps to reproduce

In this video, the orange rectangle is supposed to translate 60px on the y-axis after a measurement took place. It doesn't _always_ do so. After a fast refresh or so, you could see that the animated style gets applied properly.

https://user-images.githubusercontent.com/16821682/138614372-f0d39775-ffea-4935-9891-ea2f8d3b7fb8.mov

## Snack or minimal code example

The code for reproducing this roughly looks this:

```js
  const someMeasuredValue = useSharedValue(0);
  const onLayout = useCallback(() => {
    someMeasuredValue.value = 60;
  }, [someMeasuredValue]);

  const animStyle = useAnimatedStyle(() => {
    console.log("shared value:", someMeasuredValue.value);
    // Output is:
    // shared value: 0
    // shared value: 0
    // shared value: 60 <- here I would expect the view to be translated

    return ({
      transform: [{
        translateY: someMeasuredValue.value,
      }]
    });
}, [someMeasuredValue]);
```

You can use this full reproduction: https://github.com/hannojg/rea-v2.3-race-condition-bug
It only seems to happen when you push a new page (using the page as the start page I wasn't able to cause this issue).

Also important: I first tried to create the reproduction as a snack with rea 2.2, there the issue didn't happen. So I guess it's a regression.

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.3.0-beta.3 (happens also on beta 2) 
- NodeJS: 14
- Xcode: 12.5
- Java & Gradle: /

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by 10000multiplier** [comment]
Can confirm, I'm also experiencing this `onLayout` race condition on `2.3.0-beta.3`.

**Comment by hannojg** [comment]
Still happening on `2.3.1`

**Comment by cjhines** [comment]
I am experiencing this on `2.4.1`.

**Comment by VictorPulzz** [comment]
Yes this issue happening on "react-native-reanimated": "^2.4.1"
Component not rerender, when I change useSharedValue:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/23406402/158026635-a04672e3-bcee-43fd-92d3-ec4e0b214b80.png">
Got it on ios 15.2 simulator iPhone 11

**Comment by lightrow** [comment]
still happening on 2.10.0
