### ISSUE TITLE
useAnimatedProps doesn't work on `progress` in `lottie-react-native`

### ISSUE THREAD

**Issue by bolan9999** [software-mansion/react-native-reanimated#2576]
## Description

 `useAnimatedProps`  doesn't work on `progress` in `lottie-react-native` while the `progress` prop in `lottie-react-native` supports animation with `useNativeDriver`. 

### Expected behavior

lottie animate.

### Actual behavior & steps to reproduce

I tried to use `useAnimatedProps` to let it animate in UI thread. But failed.

## Snack or minimal code example

```
Reanimated.addWhitelistedUIProps({ progress: true });
const ReanimatedLottieView = Reanimated.createAnimatedComponent(LottieView);
...

const progress = useSharedValue(0);
const animatedProps = useAnimatedProps(() => {
    const progress = ...
    return { progress };
});
<ReanimatedLottieView animatedProps={animatedProps}/>

```

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.0
- NodeJS: -
- Xcode: -
- Java & Gradle: -

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by furkanb** [comment]
Works fine as long as you're passing [all of the props](https://github.com/lottie-react-native/lottie-react-native/blob/2e2c92fa99f8c120e6c70a6ad6daa04e1b4a7e6a/src/js/LottieView.js#L83):

```js
  const lottieAnimatedProps = useAnimatedProps(() => {
    return {
      progress: withTiming(fav ? 1 : 0, { duration: 500 }),
      speed: 1,
      loop: false,
      autoPlay: false,
      autoSize: false,
      enableMergePathsAndroidForKitKatAndAbove: false,
      cacheComposition: true,
      resizeMode: 'contain',
    };
  });
```

**Comment by WoLewicki** [comment]
Does this issue still occur in the newest versions of the library? Also, are you sure it is a problem on the side of `react-native-reanimated`? If so, could you provide a simple repo with the reproduction so we could easily work on it?

**Comment by whydidoo** [comment]
I have a same problem with LinearGradient component that contains interpolation of colors. It's working on IOS but not android
`const animateValue = useSharedValue(Number(0));
  const { gray3 } = useGetColorsByTheme();
  const { colors, ...props } = getThemeGradient('purpleLinear')!;
  const [start, end] = colors;

  useEffect(() => {
    animateValue.value = withTiming(Number(value), {
      duration: 400,
    });
  }, [value, animateValue]); 

  const animatedProps = useAnimatedProps(() => {
    return {
      ...props,
      colors: [
        mixColor(animateValue.value, gray3, start),
        mixColor(animateValue.value, gray3, end),
      ],
    };
  }, []);
const circleAnimatedStyle = useAnimatedStyle(
    () => ({
      left: interpolate(
        animateValue.value,
        [0, 1],
        [positionCircle, widthToggle - sizeSircle - positionCircle],
      ),
    }),
    [animateValue],
  );

  return (
    <TouchableWithoutFeedback
      containerStyle={style.container}
      onPress={onPress}
      disabled={disabled}>
      <AnimatedGradient animatedProps={animatedProps}>
        <CircleStyledAnimated style={circleAnimatedStyle} />
      </AnimatedGradient>
    </TouchableWithoutFeedback>
`
