### ISSUE TITLE
Build failed with an exception Android

### ISSUE THREAD

**Issue by peymannaderi3** [software-mansion/react-native-reanimated#258]
i just created an empty react native project using react-native init.
then i added reanimated using   yarn add react-native-reanimated and linked it.
this is the error i get while building:

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.android.support:transition:28.0.0.
  Searched in the following locations:
    - file:/C:/Android/sdk/extras/m2repository/com/android/support/transition/28.0.0/transition-28.0.0.pom
    - file:/C:/Android/sdk/extras/m2repository/com/android/support/transition/28.0.0/transition-28.0.0.jar
    - file:/C:/Android/sdk/extras/google/m2repository/com/android/support/transition/28.0.0/transition-28.0.0.pom
    - file:/C:/Android/sdk/extras/google/m2repository/com/android/support/transition/28.0.0/transition-28.0.0.jar
    - file:/C:/Android/sdk/extras/android/m2repository/com/android/support/transition/28.0.0/transition-28.0.0.pom
    - file:/C:/Android/sdk/extras/android/m2repository/com/android/support/transition/28.0.0/transition-28.0.0.jar
    - file:/C:/Users/peiman/.m2/repository/com/android/support/transition/28.0.0/transition-28.0.0.pom
    - file:/C:/Users/peiman/.m2/repository/com/android/support/transition/28.0.0/transition-28.0.0.jar
    - https://dl.google.com/dl/android/maven2/com/android/support/transition/28.0.0/transition-28.0.0.pom
    - https://dl.google.com/dl/android/maven2/com/android/support/transition/28.0.0/transition-28.0.0.jar
    - https://jcenter.bintray.com/com/android/support/transition/28.0.0/transition-28.0.0.pom
    - https://jcenter.bintray.com/com/android/support/transition/28.0.0/transition-28.0.0.jar
    - file:/F:/React/tinder/node_modules/react-native/android/com/android/support/transition/28.0.0/transition-28.0.0.pom
    - file:/F:/React/tinder/node_modules/react-native/android/com/android/support/transition/28.0.0/transition-28.0.0.jar
  Required by:
      project :app > project :react-native-reanimated

**Comment by AlirezaAzizi145** [comment]
@peymannaderi3 man ham in moshkel ro daram. shoma be solution naresidid?

**Comment by sunchenyang** [comment]
@peymannaderi3 Has this problem been solved?

**Comment by jakub-gonet** [comment]
Hi @peymannaderi3,
sorry for letting this issue go unnoticed 😔

I'm closing it now but if you need further assistance, I'm glad to help 🙂
