### ISSUE TITLE
Fail to run pod with 2.3.0-beta.3 in monorepo

### ISSUE THREAD

**Issue by rborn** [software-mansion/react-native-reanimated#2585]
## Description

The last change in the podspec file fails in a monorepo.

### Expected behavior

It "should work", 2.3.0-beta.2 works fine

### Actual behavior & steps to reproduce

I have a monorepo with yarn workspaces, and it seems the search for reactVersion fails to find the file.

## Snack or minimal code example

Just udpdated from 2.3.0-beta.2  to 2.3.0-beta.3

This is the error log (you can see the full path of the module and app)

```
[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: No such file or directory @ rb_sysopen - /Users/dan/Work/clients/current/emjoy/monorepo/packages/mobileapp/node_modules/react-native-reanimated/node_modules/react-native/package.json.

 #  from /Users/dan/Work/clients/current/emjoy/monorepo/packages/mobileapp/node_modules/react-native-reanimated/RNReanimated.podspec:11
 #  -------------------------------------------
 #    # Example app
 >    reactVersion = JSON.parse(File.read(File.join(__dir__, "node_modules", "react-native", "package.json")))["version"]
 #  end
 #  -------------------------------------------
```

## Package versions

- React Native: 0.66.0
- React Native Reanimated: 2.3.0-beta.3
- NodeJS: v16.11.1
- Xcode: 13.0
- Java & Gradle:

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by rborn** [comment]
@piaskowyk I'm really sorry, I tried to make a minimal repo that would reproduce my setup, but for some reason I cannot reproduce the issue. 
I have setup everything almost as in my repo  (except  the 1000000000  deps I have) but the issue won't show.

I think we can close this as it seems to be very specific to my env.
Sorry for the mess 😻

**Comment by piaskowyk** [comment]
I know how to reproduce it, so I will fix it 😃

**Comment by rborn** [comment]
@piaskowyk OMG 😻

**Comment by HuuNguyen312** [comment]
I can't run Android with Monorepo (reanimated: ^3.0.0-rc.0)

This is error log
```
FAILURE: Build failed with an exception.

* Where:
Build file '/xxx/Workspace/MyProject/node_modules/react-native-reanimated/android/build.gradle' line: 105

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> /xxx/Workspace/MyProject/node_modules/react-native/package.json (No such file or directory)
```

**Comment by kristfal** [comment]
Change this:

```
def isDeveloperMode() {
    // developer mode, to run Example app
    return false // file("$projectDir/../node_modules/react-native/package.json").exists()
}
```

And build works for monorepo.

**Comment by HuuNguyen312** [comment]
I solved this issue by adding  ` "**/react-native-reanimated" `to nohoist, and using peerDependencies: "react-native-reanimated": "*",
