### ISSUE TITLE
Derived value returning a worklet function leads to undefined behaviour

### ISSUE THREAD

**Issue by ericschaal** [software-mansion/react-native-reanimated#2587]
## Description

Returning a worklet function in a derived value leads to undefined behaviour.

### Expected behavior

Worklet function returned by the derived value should be defined and usable.

### Actual behavior & steps to reproduce

The snack below contains a console.log statement in a `useAnimatedProps` updater function and  prints the following in the console:

```
iOS Running app on iPhone

    chartData.value.scaleY(0): undefined,
    chartData.value.scaleY: function CallbackObject() {
    [native code]
    },
    chartData.value.path: M 0,0


    chartData.value.scaleY(0): 100,
    chartData.value.scaleY: function _f(y){return interpolate(y,[domain.y.min,domain.y.max],[ctx.windowRec.y1,ctx.windowRec.y0]);},
    chartData.value.path: M 0,0
```

Looks like chartData.value.scaleY worklet function is not defined properly when `useAnimatedProps` runs for the first time. Also I'm also not sure why  `useAnimatedProps ` updater fn  runs twice.

I might be doing something wrong, tbh I'm new to this library.

## Snack or minimal code example

https://snack.expo.dev/SE7tcRnUD

Run on iOS or Android to reproduce. 

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.0
- NodeJS: 14.15.2
- Xcode: 13.1

## Affected platforms

- [X] Android
- [X] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey, actually this is not a bug, it is how it works. The lambda passed to `useAnimatedProps` is run in two contexts React Runtime on JS thread and Reanimated Runtime on UI thread, first log is from UI thread second from JS thread, that's why you received different results.
