### ISSUE TITLE
[Web] Can't use `null` inside of `useDerivedValue`

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-reanimated#2589]
## Description

If you pass `null` as a variable from the JS context to `useDerivedValue`, it breaks on web.

### Expected behavior

`null` should work as a variable in `useDerivedValue`.

### Actual behavior & steps to reproduce

1. Create a variable pointing to `null` in the JS context.
2. Inside of `useDerivedValue`, access that variable.
3. Run it on Web

## Snack or minimal code example

Snack: https://snack.expo.dev/@nandorojo/derived-value-web-issue

<img width="1515" alt="Screen Shot 2021-10-31 at 2 31 05 PM" src="https://user-images.githubusercontent.com/13172299/139596942-fe5c05fe-9e3b-44c1-b065-b9c8c71298e2.png">

Code:

```tsx
import React from 'react'
import { useDerivedValue } from 'react-native-reanimated'
 
export default function HelloWorld() {
  const broken = null
  useDerivedValue(() => {
    const d = broken
  })
  return <></>
} 
```

To fix it, turn `broken` into 0. Or, comment it out:

<img width="1550" alt="Screen Shot 2021-10-31 at 2 31 49 PM" src="https://user-images.githubusercontent.com/13172299/139596961-6ab7acf3-4ae0-45e7-ab7e-55a98c954627.png">

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.0
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

## Added Context

It works fine on iOS:

![image](https://user-images.githubusercontent.com/13172299/139597005-b21ac0bf-a897-487f-97d1-324e780a4b54.png)

**Comment by brianreavis** [comment]
This also affects useAnimatedStyle: https://github.com/software-mansion/react-native-reanimated/issues/2628

(Just noticed this issue after typing that one up; my apologies for the duplicate!)
