### ISSUE TITLE
Initial value of shared value not used in animated props 

### ISSUE THREAD

**Issue by schiller-manuel** [software-mansion/react-native-reanimated#2604]
## Description
The initial value of a shared value does not affect animated props, only when the shared value is updated after the initial render, the value is used.

This happened to me when trying to animate SVG elements and setting an initial rotation value.

### Expected behavior
The SVG element should be rotated in the initial render.

### Actual behavior & steps to reproduce
SVG element is only rotated after the shared value is updated after the initial render.

## Snack or minimal code example

````
import * as React from 'react';
import { View, Button } from 'react-native';

import Animated, {
  useSharedValue,
  useAnimatedProps
} from 'react-native-reanimated';

import Svg, {Rect} from 'react-native-svg';

const AnimatedRect = Animated.createAnimatedComponent(Rect);

export default function App() {
  const rotation = useSharedValue(10);
  const props = useAnimatedProps(() => {
    return {
      transform: [{ rotateZ: `${rotation.value}deg` }]
    };
  });
  return (
    <View style={{flex:1}}>
      <Svg width={200} height={200}>
        <AnimatedRect x={100} y={100} width={100} height={10} fill="#000" animatedProps={props} />
      </Svg>
      <Button title="increase rotation" onPress={() => (rotation.value++)} />
    </View>
  );
}
````

https://snack.expo.dev/cZ0nS-AvQ

## Package versions

- "react-native": "0.64.1",
- "react-native-reanimated": "2.2.4
-  "react-native-svg": "^12.2.0",

## Affected platforms

- [x] Android
- [x] iOS

**Comment by CDBridger** [comment]
I'm getting a similar issue, the initial value of my shared value is initialising to the wrong value. it's almost as if its using the same initial value of a seperate component elsewhere which has its own shared value.

**Comment by piaskowyk** [comment]
Hey, I have already checked and it works on 2.3.0
