### ISSUE TITLE
App is crashing on refresh in debug mode (iOS)

### ISSUE THREAD

**Issue by reymanov** [software-mansion/react-native-reanimated#2606]
## Description

React native app is crashing on refresh when in debug mode, giving the following error: 
`Exception thrown while executing UI block: *** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil `

<img width="407" alt="Zrzut ekranu 2021-11-7 o 18 30 12" src="https://user-images.githubusercontent.com/60399481/140655772-46b0815b-faaa-4b27-b80e-3f7a7b287303.png">

This issue was already mentioned here:  #216 but it was closed without any answer so I'm opening again.

### Expected behavior 
App won't crash when refreshing in debug mode

### Actual behavior & steps to reproduce
It occurs when the app is being refreshed by saving code action in code editor.

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: v16.13.0
- Xcode: 13.1

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Could you provide an example repo to reproduce your issue?

**Comment by reymanov** [comment]
Unfortunately i won't be able to provide an example repo as it happened in customers application

**Comment by KonstantinZhukovskij** [comment]
any news here?

**Comment by jakub-gonet** [comment]
We need a repro example on that one to fix that, unfortunately. @reymanov does it crash consistently on every refresh? Maybe you can provide a list of packages you use?
