### ISSUE TITLE
Type definition does not fit to createAnimatedEvent's return type

### ISSUE THREAD

**Issue by MichelBahl** [software-mansion/react-native-reanimated#2616]
As defined here the return type should be an callback.

https://github.com/software-mansion/react-native-reanimated/blob/249577aa0142dc516e9b5e5fa78b76a4ab848995/react-native-reanimated.d.ts#L350-L355

But the code below return an object:

```javascript
  const onPanGestureEvent = Reanimated.event(
    [
      {
        nativeEvent: {
          translationX: _touchX,
        },
      },
    ],
    {
      useNativeDriver: true,
    }
  );
```

Here is the implementation of event/createAnimatedEvent

https://github.com/software-mansion/react-native-reanimated/blob/249577aa0142dc516e9b5e5fa78b76a4ab848995/src/reanimated1/core/AnimatedEvent.js#L124-L126

**Comment by jakub-gonet** [comment]
Reanimated 1 uses callback type because it's used in place of handlers, mapping events from components. What's your specific use-case for the "true" type?
