### ISSUE TITLE
useAnimatedProps with `react-native-svg` Path performance issues

### ISSUE THREAD

**Issue by arasrezaei** [software-mansion/react-native-reanimated#2618]
## Description
animating react native svg path causes serious frame drops on both JS and UI thread on android

### Expected behavior
60FPS

### Actual behavior & steps to reproduce
30-40 FPS

## Snack or minimal code example
```
  const newProps = useAnimatedProps(() => {
    return {
      d: `M 0 0, H ${x.value}, V ${HEIGHT}, H 0, Z`,
    };
  });

return
    <Svg
      style={[StyleSheet.absoluteFill,]}>
      <AnimatedPath
        animatedProps={newProps}
        fill={'black'}
      />
    </Svg>
```

## Package versions
reanimated: v2.3.0-beta.2,
react-native-svg: v12.1.1,
react-native: v0.66.2

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

## UPDATE
No matter what JS Engine, it drops frames a lot …
(Tested on Hermes & JSC)

**Comment by nandorojo** [comment]
Are you using Hermes? Because I've had degraded performance with my SVGs on Hermes.

**Comment by arasrezaei** [comment]
> Are you using Hermes? Because I've had degraded performance with my SVGs on Hermes.

Yes, hermes 0.90 I think, 
This engine suffers a lot from performance issues and bad developer tools 🙁

**Comment by Only-IceSoul** [comment]
svg use software layer. try painter.

**Comment by nandorojo** [comment]
Rather than just getting performance issues, my `AnimatedSVG`'s `animatedProps` doesn't work properly.

```ts
const svgProps = useAnimatedProps(() => ({
  width: withTiming(isActive.value ? 300 : 100)
}))

return <AnimatedSVG animatedProps={svgProps} height={height} />
```

In the code above, it doesn't animate with a timing animation. Instead, it just snaps into place. @piaskowyk should I open a separate issue for this?

**Comment by guidodipaolo** [comment]
Happening the same here!

**Comment by kmagiera** [comment]
Hi @arasrezaei – would you be able to update the provided repro to at least show how the value gets updated. I understand the issue more or less but it'd save us a lot of time if we avoided trying to guess all the missing details. Preferably sending a link to github repo where the issue is reproduced would be the best. Thank you!

**Comment by kmagiera** [comment]
Also if anyone else from the commenters have time to fill in these details that'd be very much appreciated

**Comment by arasrezaei** [comment]
> Also if anyone else from the commenters have time to fill in these details that'd be very much appreciated

Hello there this is the repo:
https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season4/src/LiquidSwipe

**Repro:**
First of all remove this line so android device use masked view:
https://github.com/wcandillon/can-it-be-done-in-react-native/blob/07c223e8d6ff2bd1f11afc69e0e0ad9af40c31ca/season4/src/LiquidSwipe/Wave.tsx#L133

I also replaced masked view with a hardware accelerated solution. It slightly improved performance but again it was not 60 FPS.

Tested this on samsung galaxy S8

**Comment by jesuspc** [comment]
Also seeing this issue. A simple animatedProps on an SVG Path creates a spike to 100% CPU usage and a dramatic increase in phone temperature.

**Comment by emroot** [comment]
Same here. I'm using an animatedRect inside a scrollView and the perfomance drop is pretty significant. UI drops from 60 to ~10

**Comment by alabsi91** [comment]
Same here, I am experiencing drop in performance when updating an SVG Path's `d` attribute using `useAnimatedProps` on scroll inside a `ScrollView`.

**Comment by ucheNkadiCode** [comment]
has anyone seen an improvement here? I've been trying to have a dynamic svg circle drawn and the performance is definitely degraded

**Comment by arasrezaei** [comment]
> has anyone seen an improvement here? I've been trying to have a dynamic svg circle drawn and the performance is definitely degraded

Which reanimated version?

**Comment by ucheNkadiCode** [comment]
Sorry after upgrading to reanimated 3.1.2 and svg 13.5.0 I’m no longer having this issue 

I was previously in 2.17.0

**Comment by Latropos** [comment]
Closing this issue, since it persists only on Reanimated2, and now we only fix critical issues for this older version. The valid solution is to update Reanimated and svg
