### ISSUE TITLE
[Web] `setImmediate` SSR regression in 2.3.0-beta.3

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-reanimated#2621]
## Description

If you run 2.3.0-beta.3 with Next.js, you get this error:

![image](https://user-images.githubusercontent.com/13172299/141209365-9f31b772-7609-431f-bed8-26330ad3e011.png)

### Expected behavior

`setImmediate` should not be used on Web. Instead, it should use `requestAnimationFrame`. This is a regression from previous versions, where this replacement was already made.

It was originally fixed here: https://github.com/software-mansion/react-native-reanimated/pull/1891

### Actual behavior & steps to reproduce

Create an SSR app, use reanimated 2.3.0-beta.3.

## Snack or minimal code example

I can create one if necessary, but this bug has historically been an issue with Reanimated.

## Package versions

- React Native: 0.64.3
- React Native Reanimated: 2.3.0-beta.3
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

## Patch

This patch fixes it:

```patch
diff --git a/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js b/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js
index 2db94aa..3f1d699 100644
--- a/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js
+++ b/node_modules/react-native-reanimated/lib/reanimated2/ViewDescriptorsSet.js
@@ -1,5 +1,14 @@
 import { useRef } from 'react';
 import { makeMutable } from './core';
+import { Platform } from 'react-native';
+
+let updater
+if (Platform.OS === 'web') {
+  updater = requestAnimationFrame
+} else {
+  updater = setImmediate
+}
+
 export function makeViewDescriptorsSet() {
     const ref = useRef(null);
     if (ref.current === null) {
@@ -18,7 +27,7 @@ export function makeViewDescriptorsSet() {
                 data.items.push(item);
                 if (!data.waitForInsertSync) {
                     data.waitForInsertSync = true;
-                    setImmediate(() => {
+                    updater(() => {
                         data.sharableViewDescriptors.value = data.items;
                         data.waitForInsertSync = false;
                     });
@@ -28,7 +37,7 @@ export function makeViewDescriptorsSet() {
                 data.batchToRemove.add(viewTag);
                 if (!data.waitForRemoveSync) {
                     data.waitForRemoveSync = true;
-                    setImmediate(() => {
+                    updater(() => {
                         const items = [];
                         for (const item of data.items) {
                             if (data.batchToRemove.has(item.tag)) {

```

**Comment by nandorojo** [comment]
Opened a PR to solve this at https://github.com/software-mansion/react-native-reanimated/pull/2622

**Comment by piaskowyk** [comment]
Thanks to report and PR 😍 I will test it before release and I will merge it if everything will be ok.
