### ISSUE TITLE
huge fps drop useDerivedValue and Statusbar

### ISSUE THREAD

**Issue by dancixx** [software-mansion/react-native-reanimated#2623]
### Expected behavior
I would like to change the Statusbar bgcolor on the scroll event with an animated scrollview and I noticed that this method cause a huge fps drop on Android.

## Snack or minimal code example
```
const barStyleAndroid = (translateYValue: number) =>
        typeof teamStyle?.welcomeTileStyle?.tileStyle !== 'undefined' && teamStyle?.welcomeTileStyle?.tileStyle === 'large'
           ? translateYValue >= 0.5
                ? StatusBar.setBarStyle('dark-content', true)
                : StatusBar.setBarStyle('light-content', true)
            : StatusBar.setBarStyle('dark-content', true);
    const barBackground = (translateYValue: number) =>
        translateYValue < getStatusBarHeight() ? StatusBar.setBackgroundColor(teamStyle?.welcomeTileStyle?.backgroundColor, true) : StatusBar.setBackgroundColor('#FFFFFF', true);

const scrollHandler = useAnimatedScrollHandler(({ contentOffset: { y } }) => {
        opacity.value = y / 100;

        if (!PLATFORM_IOS) {
            translateY.value = y;
        }
    });

useDerivedValue(() => {
        if (isFocused) {
            if (PLATFORM_IOS) {
                runOnJS(barStyleIOS)(opacity?.value);
            } else {
                // runOnJS(barStyleAndroid)(translateY?.value);
                // runOnJS(barBackground)(translateY?.value);
            }
        }
    }, [isFocused]);
```

## Package versions

- React Native: 0.66.1
- React Native Reanimated: 2.2.3
- NodeJS: 16.13.0
- Xcode: 13.
- Java & Gradle: 6.9

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by nandorojo** [comment]
That's probably because it's running on the JS thread.

**Comment by dancixx** [comment]
I followed the docs. :)

**Comment by nandorojo** [comment]
Yeah, but you’re using runOnJS on every animation step, which is clogging up the JS thread. You’d be better off setting `animated={true}` on your status bar component, and then show/hide if the scroll is greater/less than 100

**Comment by dancixx** [comment]
Okay but I don't want to hide it, Id like to change the style between dark and light on scroll event but I will check the useAnimatedReaction hook too.

**Comment by kkafar** [comment]
Thanks for reporting! However the description lacks some details. The code sample you posted has missing components, therefore it would be the best if you provided repo with minimal project in which this problem occurs, so we don't have to guess whats there.
