### ISSUE TITLE
v2.2.x is broken for Web, and Expo points to 2.2.0. JavaScript typo.

### ISSUE THREAD

**Issue by ngokevin** [software-mansion/react-native-reanimated#2635]
## Description

https://github.com/expo/expo/issues/15217

Error: `TypeError: undefined is not an object (evaluating 'component.previousStyle')` (setNativeProps)

```js
export const _updatePropsJS = (_viewTag, _viewName, updates, viewRef) => {
    if (viewRef.current && viewRef.current._component) {
        const [rawStyles] = Object.keys(updates).reduce((acc, key) => {
            const value = updates[key];
            const index = typeof value === 'function' ? 1 : 0;
            acc[index][key] = value;
            return acc;
        }, [{}, {}]);

       // viewRef._component, THIS IS ALWAYS UNDEFINED.
        setNativeProps(viewRef._component, rawStyles);
    }
};
```

There is a typo, it should be passing `viewRef.current._component`.

### Expected behavior

No JavaScript typo.

## Snack or minimal code example

```
yarn add moti
expo install react-native-reanimated
```

```js
import {MotiView} from 'moti';

function Test () {
  return <MotiView animate={{opacity: 1}}/>
}
```

## Package versions
v.2.2.0 to v2.2.4 that Expo pooints to

```
Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.7 => 0.16.7
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed
```

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by ngokevin** [comment]
Here's a patch that can be released as 2.2.5 https://github.com/learncoupling/react-native-reanimated/commit/d04e736b09db24f6327d345ffe237b57eb62f7c7 and then we'd need to get Expo to point to it.

**Comment by piaskowyk** [comment]
Resolved here - https://github.com/software-mansion/react-native-reanimated/commit/d5f2525f37f55f6c3eb1c7e41807b6917612b7cc We will release it in the next stable version 2.2.5.

**Comment by ChinaSilence** [comment]
When will version 2.2.5 will be released?

**Comment by dohooo** [comment]
When will version 2.2.5 will be released?

**Comment by tiste** [comment]
Hello @piaskowyk! Do you know when the 2.2.5 could be released in npm registry? I tried the fix with higher version and it works well, but I'm stuck with ~2.2.x with expo.
