### ISSUE TITLE
Ignore certain child elements with Transitions?

### ISSUE THREAD

**Issue by davidpaulsson** [software-mansion/react-native-reanimated#265]
First off, thank you for an amazing lib.

I'm wondering if it's possible to ignore certain Transition child elements from animating? I have some nested text that updates and behaves really terrible, but the rest of the view is behaving really really good.

**Comment by jpamarohorta** [comment]
Hello, I would also like to know if this is possible. Thanks!

**Comment by kmagiera** [comment]
Hey @davidpaulsson ! Appreciate your feedback however based on your description it is difficult to us to figure out what you are requesting the lib should do.

We'd love to consider new additions to Transition API but would need more comprehensive description with code samples (e.g. how you'd propose the API should look like) along with some examples of what behavior you currently expirience (again, with code samples and preferably video samples).

For now I'm going to close this issue, when you have some time to work on providing the above info feel free to open a new one. Thanks!

**Comment by sintylapse** [comment]
would be helpful to https://github.com/software-mansion/react-native-reanimated/issues/806
