### ISSUE TITLE
Shared value updates inside of onEndDrag does not appear to trigger  useDerivedValue hook.

### ISSUE THREAD

**Issue by Eljoy** [software-mansion/react-native-reanimated#2666]
## Description

Shared value updates inside of onEndDrag does not appear to trigger  useDerivedValue hook.

### Expected behavior

scroll shared value changes inside onEndDrag should trigger useDerivedValue callback which snaps scroll to previous or next item.

### Actual behavior & steps to reproduce

scroll shared value changes don't trigger useDerivedValue callback 

## Snack or minimal code example
```
export function ProfileInfoScrollView({
}: ProfileInfoScrollView.Props) {
  const { profiles } = useProfile()
  const [containerHeight, setContainerHeight] = useState(0)
  const aref = useAnimatedRef<FlatList>()

  const scroll = useSharedValue(0)

  useDerivedValue(() => {
    scrollTo(aref as any, 0, scroll.value * containerHeight, true)
  })

  const animatedScrollHandler = useAnimatedScrollHandler<{
    beginOffset: number
  }>({
    onBeginDrag: (e, c) => {
      c.beginOffset = e.contentOffset.y
    },
    onEndDrag: (e, c) => {
      const currentOffset = e.contentOffset.y
      const direction = currentOffset > c.beginOffset ? 'down' : 'up'
      scroll.value = direction === 'up' ? scroll.value - 1 : scroll.value + 1
    },
  })

  return (
    <View
      onLayout={(event) => {
        const { height } = event.nativeEvent.layout
        setContainerHeight(height)
      }}>
      <Button
        title="scroll down"
        onPress={() => {
          scroll.value = scroll.value + 1
          if (scroll.value >= 10) scroll.value = 0
        }}
      />
      <AnimatedFlatList
        ref={aref}
        data={profiles}
        onScroll={animatedScrollHandler}
        getItemLayout={(_, index) => {
          return {
            length: containerHeight,
            index,
            offset: index * containerHeight,
          }
        }}
        scrollEventThrottle={16}
        renderItem={({ item: p }: ListRenderItemInfo<Profile>) => (
          <ProfileInfo height={containerHeight} key={p.id} profile={p} />
        )}
        keyExtractor={(p: Profile) => p.id}
      />
    </View>
  )
}

```

## Package versions

- React Native: 0.66.2
- React Native Reanimated: 2.2.4, 2.3.0-beta.4
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by hannojg** [comment]
This might be independent from `onEndDrag`. When we upgraded to beta4 we also discovered cases in our app where useDerivedValue or the shared value doesn't seem to get updated at all. Still trying to create a reproduction for it

**Comment by Eljoy** [comment]
@hannojg What version you used before where this feature worked properly ?

**Comment by hannojg** [comment]
I found the issue, will open a ticket shortly and share it here, hold on !

**Comment by acollazomayer** [comment]
@Eljoy @hannojg I have the same issue. I used to have version 2.2.4 and now I am in 2.3.0-beta.4. Were you able to solve it?

**Comment by hannojg** [comment]
A temporary fix for me is to uncomment the lines in the file mentioned in this issue
https://github.com/software-mansion/react-native-reanimated/issues/2667

**Comment by tomekzaw** [comment]
@Eljoy Hello and thanks for reporting!

Since this issue seems to be related to #2667, can you please check if #2668 resolves it?

**Comment by Eljoy** [comment]
@tomekzaw Well, the useSharedValue seems to be triggered. Although now I see that there is an issue of scrollTo function not working when there is still an active scroll momentum. Thanks.

**Comment by Eljoy** [comment]
Now the latter complaint does not seem to be an issue anymore and it all works like a charm.

**Comment by piaskowyk** [comment]
Same solution - https://github.com/software-mansion/react-native-reanimated/issues/2675#issuecomment-984792563
