### ISSUE TITLE
类型“AnimatedNode<any>”缺少类型“AnimatedValue<0>”中的以下属性: setValue, interpolate

### ISSUE THREAD

**Issue by BadtzMaru** [software-mansion/react-native-reanimated#2670]
1. class Component

translateX = new Animated.Value(0);

2.
this.translateX = cond(
  eq(gestureState, State.END),
  [
    set(translationX, runSpring(clockX, translationX, snapPoint)),
    set(offsetX, translationX),
    cond(and(eq(clockRunning(clockX), 0), neq(translationX, 0)), [
      call([translationX], this.swipped),
    ]),
    translationX,
  ],
  cond(
    eq(gestureState, State.BEGAN),
    [stopClock(clockX), translationX],
    translationX
  )
);

**Comment by piaskowyk** [comment]
Hey, I see that your issue is related to reanimated v1 but unfortunately we no longer support v1 😢

**Comment by BadtzMaru** [comment]
> 

All Right. emm....  thanks for replay.  I find anthor way to do.

**Comment by BadtzMaru** [comment]
> Hey, I see that your issue is related to reanimated v1 but unfortunately we no longer support v1 😢

All right. emm... Thanks for replay. I'll find other one to do this code.
