### ISSUE TITLE
Debug With Chrome feature?

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#2671]
Hello im just wondering when we will get back the 'Debug With Chrome' feature back ?

in v2 i never could use it, still waiting to fix this issue and currently im at 2.2.4. any estimated release for this? Thanks!

**Comment by Bua-C** [comment]
Same here

**Comment by pontusab** [comment]
Try the latest v2.3 release

**Comment by alexfov** [comment]
> Try the latest v2.3 release

I have the same problem

**Comment by danferd33** [comment]
Me too. Version 2.3.0 doesn't work

**Comment by radko93** [comment]
Is this even supposed to be back at any point? With JSI it will never work the same like before.

**Comment by kamlesh1000** [comment]
Version 2.3.0 doesn't work. Same issue.

**Comment by Bayramito** [comment]
I use safari for debugging but it crashes when i reload the app

**Comment by hoanglam10499** [comment]
version 2.3.0 doesn't work.
![image](https://user-images.githubusercontent.com/37326429/145855501-2a67c3cc-d93a-4839-a8fd-f7e72b9ff9b4.png)

**Comment by pastean** [comment]
also interested. I can't use it reanimated on work projects because of this

**Comment by piaskowyk** [comment]
The problem is only on the Android platform?

**Comment by Bayramito** [comment]
No, personally i've got it on both

**Comment by piaskowyk** [comment]
@Bayramito What does happen on iOS? Could you tell me more?
btw, I have already fixed chrome debugger on Android - https://github.com/software-mansion/react-native-reanimated/pull/2795

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue on iOS?

**Comment by Bayramito** [comment]
> Hey, could you provide a repo to reproduce your issue on iOS?

Sorry for responding that late... 

Actually i m using RN 2.2.4 in my company project. But i will try to reproduce same issue on a repo.

Btw, im getting this error on Android from Logcat when i hit 'Debug'

2021-12-31 13:28:31.371 6558-6558/com.omuz E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~yPDaQE3Hb95I-8qTTgI84w==/com.twsit-rjxIhqFfTT2koT0CYhy9TA==/lib/x86/libjscexecutor.so in namespace classloader-namespace result: 0

**Comment by Bayramito** [comment]
Well,
I tested it on a new project, looks its working fine.  Idk whats wrong with my existing project maybe some dependency issue,

actually you can check my dependencies here.

babel.config.js File:

`module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [["@babel/plugin-proposal-decorators", {legacy: true}], "react-native-reanimated/plugin"],
};
`

package.json

`{
  "name": "Omuz",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "lint-staged": "lint-staged",
    "postinstall": "patch-package",
    "format": "prettier --write \"src/**/*.js\"",
    "format:staged": "prettier --write",
    "prepare": "husky install"
  },
  "dependencies": {
    "@fawazahmed/react-native-read-more": "^1.1.5",
    "@gorhom/bottom-sheet": "^2.0.0",
    "@native-html/iframe-plugin": "^2.5.0",
    "@react-native-community/async-storage": "^1.6.3",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/cameraroll": "^4.0.0",
    "@react-native-community/datetimepicker": "^3.0.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^4.6.1",
    "@react-native-firebase/app": "^12.7.2",
    "@react-native-firebase/crashlytics": "^12.7.2",
    "@react-native-mapbox-gl/maps": "^8.5.0",
    "@react-navigation/bottom-tabs": "^6.0.7",
    "@react-navigation/compat": "^5.1.9",
    "@react-navigation/core": "^6.0.2",
    "@react-navigation/drawer": "^6.1.6",
    "@react-navigation/elements": "^1.1.2",
    "@react-navigation/material-bottom-tabs": "^6.0.7",
    "@react-navigation/material-top-tabs": "^6.0.4",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/stack": "^6.0.9",
    "async-mutex": "^0.2.4",
    "buffer": "^5.4.3",
    "expo-gl": "^10.4.2",
    "expo-gl-cpp": "^10.4.1",
    "expo-image-manipulator": "^9.2.2",
    "formik": "^2.1.5",
    "geolib": "^3.3.1",
    "gl-react": "^5.0.0",
    "gl-react-native": "^5.0.0",
    "i18n-js": "^3.7.1",
    "i18next": "^19.8.2",
    "install": "^0.13.0",
    "lodash": "^4.17.15",
    "lodash.memoize": "^4.1.2",
    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^4.0.2",
    "mobx": "^5.15.0",
    "mobx-observable-promise": "^0.4.12",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^6.1.4",
    "moment": "^2.24.0",
    "moment-duration-format": "^2.3.2",
    "npm": "^7.20.3",
    "patch-package": "^6.2.2",
    "prop-types": "^15.7.2",
    "pusher-js": "^6.0.3",
    "qs": "^6.9.4",
    "react": "17.0.1",
    "react-i18next": "^11.7.3",
    "react-native": "0.64.2",
    "react-native-animatable": "^1.3.3",
    "react-native-animate-number": "^0.1.2",
    "react-native-app-console": "^0.1.35",
    "react-native-appearance": "^0.3.4",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-camera": "^4.2.0",
    "react-native-circular-action-menu": "^0.5.0",
    "react-native-collapsible": "^1.5.3",
    "react-native-confetti-cannon": "^1.5.0",
    "react-native-confirmation-code-field": "^6.5.0",
    "react-native-contacts": "^7.0.0",
    "react-native-countdown-component": "^2.7.1",
    "react-native-create-thumbnail": "^1.2.2",
    "react-native-datepicker": "^1.7.2",
    "react-native-deep-linking": "^2.2.0",
    "react-native-device-info": "^5.5.7",
    "react-native-easy-toast": "^1.2.0",
    "react-native-exception-handler": "^2.10.8",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-fast-image": "^8.3.2",
    "react-native-fit-image": "^1.5.5",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-gl-image-filters": "^0.4.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-image-crop-picker": "^0.35.3",
    "react-native-image-filter-kit": "^0.8.0",
    "react-native-image-picker": "^4.0.6",
    "react-native-image-zoom-viewer": "^3.0.0",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-largelist": "^3.1.0-rc.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^1.4.0",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-map-clustering": "^3.4.2",
    "react-native-maps": "0.28.0",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal": "^11.6.1",
    "react-native-modalize": "^2.0.3",
    "react-native-onesignal": "^4.0.4",
    "react-native-pager-view": "^5.4.4",
    "react-native-paper": "^4.9.2",
    "react-native-parsed-text": "0.0.22-beta.3",
    "react-native-permissions": "^3.0.5",
    "react-native-popup-menu": "^0.15.10",
    "react-native-progress-steps": "^1.3.4",
    "react-native-radial-menu": "^1.1.0",
    "react-native-read-more-text": "^1.1.2",
    "react-native-reanimated": "^2.3.1",
    "react-native-redash": "^14.2.2",
    "react-native-render-html": "^6.1.0",
    "react-native-restart": "0.0.17",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.8.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-share": "^3.3.2",
    "react-native-shared-element": "^0.8.3",
    "react-native-skeleton-placeholder": "^2.0.7",
    "react-native-snap-carousel": "^4.0.0-beta.5",
    "react-native-spring-scrollview": "^3.0.2",
    "react-native-stars": "^1.2.1",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swipe-list-view": "^3.2.3",
    "react-native-switch-pro": "^1.0.5",
    "react-native-switch-selector": "^2.1.4",
    "react-native-tab-view": "^3.1.1",
    "react-native-unimodules": "^0.14.6",
    "react-native-vector-icons": "^9.0.0",
    "react-native-video": "^4.4.5",
    "react-native-video-cache": "^2.0.5",
    "react-native-webview": "^11.15.0",
    "react-native-youtube-iframe": "^2.2.1",
    "react-navigation": "^4.4.2",
    "react-navigation-header-buttons": "^3.0.4",
    "react-navigation-shared-element": "^3.1.3",
    "react-timeout": "^1.2.0",
    "recyclerlistview": "^3.0.5",
    "rn-range-slider": "^2.0.4",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-decorators": "^7.7.0",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/node": "^14.14.28",
    "@types/react-native": "^0.63.50",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^3.2.0",
    "eslint": "^7.22.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^6.15.0",
    "eslint-import-resolver-babel-module": "^5.1.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "husky": "^7.0.2",
    "jest": "^26.6.3",
    "jetifier": "^1.6.6",
    "lint-staged": "^10.5.4",
    "metro-react-native-babel-preset": "^0.64.0",
    "prettier": "^2.2.1",
    "react-test-renderer": "17.0.1"
  },
  "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'",
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ]
  }
}
`
