### ISSUE TITLE
ScrollTo does not seem to work inside animatedScrollHandler or inside useDerivedValue while shared value is changed inside useDerivedValue.

### ISSUE THREAD

**Issue by Eljoy** [software-mansion/react-native-reanimated#2675]
## Description
ScrollTo does not seem to work when sharedValue is changed inside animatedScrollHandler. Use case example: one might want to scroll to the next item on drag release.
I don't think that [https://github.com/software-mansion/react-native-reanimated/pull/2580](#2580) will solve the issue since it happens both on ios and android.

### Expected behavior
ScrollTo should work either inside animatedScrollHandler or as a result of shared value changes inside  animatedScrollHandler.

### Actual behavior & steps to reproduce
ScrollTo does not have any effect.

## Complete code example:

```
const Comp = () => {
  const aref = useAnimatedRef<FlatList>();
  const scroll = useSharedValue(0);
  const { width, height } = useWindowDimensions();

  useDerivedValue(() => {
    scrollTo(aref, 0, scroll.value * height, true);
  });

  const items = Array.from(Array(10).keys());

  const animatedScrollHandler = useAnimatedScrollHandler<{
    beginOffset: number
  }>({
    onBeginDrag: (e, c) => {
      c.beginOffset = e.contentOffset.y;
    },
    onEndDrag: (e, c) => {
      const currentOffset = e.contentOffset.y;
      const direction = currentOffset > c.beginOffset ? "down" : "up";
      scroll.value =
        direction === "up" ? scroll.value - 1 : scroll.value + 1;
    }
  });

  return (
    <View>
      <Button
        title="scroll down"
        onPress={() => {
          scroll.value = scroll.value + 1;
          if (scroll.value >= 10) scroll.value = 0;
        }}
      />
      <View style={{ width, height, backgroundColor: "green" }}>
        <AnimatedFlatList
          ref={aref}
          data={items}
          onScroll={animatedScrollHandler}
          style={{ backgroundColor: "orange", width }} renderItem={(itemInfo: any) => (
          <View
            key={itemInfo.item}
            style={{
              backgroundColor: "white",
              width: width - 20,
              height: height - 50,
              marginHorizontal: 10,
              borderBottomWidth: 2,
              borderBottomColor: "orange",
              alignItems: "center",
              justifyContent: "center"
            }}
          >
            <Text style={{ fontSize: 48 }}>{itemInfo.item}</Text>
          </View>
        )}>
        </AnimatedFlatList>
      </View>
    </View>
  );
};
```

## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.3.0-beta.4
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey, It actually not a bug, it is just how it works. Look at this:

https://user-images.githubusercontent.com/36106620/144462589-986ec4ed-c3df-44c4-a0f4-3e31b4f0a6cf.mov

If you call `scrollTo` during the animation of the scroll it doesn't work, because this is a conflict between scroll two scrolls at the same time. You should use event onListScrollEnd like.
`onDragEnd != onScrollEnd`

**Comment by Eljoy** [comment]
@piaskowyk It's definitely a bug. If you try to press scrollTo button while scroll is in progress it would work. Also this use case works just fine when using just react native FlatList approach. This issue should not be closed.

**Comment by Eljoy** [comment]
Also for the ios if you would duplicate scrollTo call it will work (although not for android):
```
    scrollTo(aref, 0, scroll.value * height, true);
    scrollTo(aref, 0, scroll.value * height, true);
```
