### ISSUE TITLE
2.3.0-beta.4 crashes:  "Property '_setGestureState' doesn't exist"

### ISSUE THREAD

**Issue by taschik** [software-mansion/react-native-reanimated#2677]
## Description
I upgraded from 2.3.0-beta.3 to 2.3.0-beta.4 and now upon start the app crashes with the following error:

```
 ERROR  ReferenceError: Property '_setGestureState' doesn't exist, js engine: hermes
 WARN  RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

### Expected behavior

The app doesn't crash.

## Package versions

- React Native: "react-native": "0.66.3",
- React Native Reanimated: "react-native-reanimated": "^2.3.0-beta.4",
- NodeJS: v14.17.5
- Xcode:13.1
- Java & Gradle: Am only able to test it on iOS

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey, It looks like a cache issue. Did you try to run `yarn start --reset-cache`?

**Comment by DigitalZebra** [comment]
Ran in to the same issue after updating to `2.3.0-beta.4` from `2.3.0-beta.1`. 
Resetting the cache fixed the issue for me, thanks much @piaskowyk !

**Comment by gpbaculio** [comment]
@DigitalZebra did warning RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks go away?

**Comment by taschik** [comment]
Resetting all caches and fresh install of everything helped clearing that. Thanks for the hint.
