### ISSUE TITLE
interpolatenode with useAnimatedStyle does not work

### ISSUE THREAD

**Issue by hugobarragon** [software-mansion/react-native-reanimated#2682]
### Expected behavior
using interpolatenode with useAnimatedStyle to change a style to update

### Actual behavior & steps to reproduce
interpolatenode update witin useAnimatedStyle but style does not change or update

## Snack or minimal code example  
  basic example to show/hide text on scroll with opcacity
  
https://snack.expo.dev/@hugobarragon/reanimated-2-interpolatenode-example

## Package versions

- React Native: React Native 0.63
- React Native Reanimated: "react-native-reanimated": "~2.2.0",
- NodeJS: v14.16.1
- Xcode:
- Java & Gradle:

## Affected platforms

- [X] Android
- [X] iOS
- [X] Web

**Comment by piaskowyk** [comment]
Hey, You shouldn't mix reanimated v1 with reanimated v2. `interpolateNode` is from reanimated v1. 
Try this:
```js
const animatedStyles = useAnimatedStyle(() => {
  return {
    opacity: interpolate(scrollY.value, [0, 97], [0, 1]),
  };
});
```

**Comment by hugobarragon** [comment]
@piaskowyk Well maybe there is something wrong then
check the docs here for v2 version
https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/api/miscellaneous/interpolate  
 docs are saying the opposite
"Be aware that interpolate was renamed in reanimated v2 to interpolateNode and should not be confused with interpolate from the new API."


changed from interpolatedNode to interpolate still does not work!  
```
 const animatedStyles = useAnimatedStyle(() => {
    let newOpacity = interpolate(scrollY.value, {
      inputRange: [0, 97],
      outputRange: [0, 1],
    });

    return {
      opacity: newOpacity,
    };
  });
  ```
  
  here is the link with interpolate instead of interpolateNode
  https://snack.expo.dev/@hugobarragon/reanimated-2-interpolate-example

**Comment by hugobarragon** [comment]
@piaskowyk please reopen the issue to adress it
