### ISSUE TITLE
Loop animation crashes Android Build in Expo

### ISSUE THREAD

**Issue by Karthik-B-06** [software-mansion/react-native-reanimated#2697]
## Description
I am trying to build a Loop/Rotate animation using the withRepeat function available in reanimated. 

### Expected behavior

A rotating square on the mount in iOS and Android. 

### Actual behavior & steps to reproduce
Works fine in iOS. Crashes the App in Android using Expo Build.

## Snack or minimal code example

```
import React, { useEffect } from 'react';
import Animated, {
  Easing,
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withTiming,
} from 'react-native-reanimated';

export const RotateAnimation: React.FC = () => {
  const rotate = useSharedValue(0);
  useEffect(() => {
    rotate.value = withRepeat(
      withTiming(360, {
        duration: 1000,
        easing: Easing.linear,
      }),
      -1,
      false
    );
  }, [rotate]);
  const rotationStyle = useAnimatedStyle(() => {
    return {
      transform: [
        {
          rotate: `${rotate.value}deg`,
        },
      ],
    };
  });

  return (
    <Animated.View
      style={[{ height: 20, width: 20, backgroundColor: 'red' }, rotationStyle]}
    />
  );
};

```

## Package versions

- React Native: ^0.64.3
- React Native Reanimated: ^2.2.2
- NodeJS: v16.13.0
- Xcode: (Using EXPO Go)
- Java & Gradle:

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by WoLewicki** [comment]
I tried to run your code in Expo SDK 44 and the app does not crash both on `iOS` and `Android`. I will close this issue then. Feel free to comment if I something is wrong and we can reopen it.
