### ISSUE TITLE
Rewrite to TS

### ISSUE THREAD

**Issue by osdnk** [software-mansion/react-native-reanimated#270]
I still observe that typings in this lib are not perfect and still face issues with bad types definitions. 
Maintaining typings in the separeted file is difficult and leads to errors because they're not deeply tested. 

Also, using TS might allow eliminate many bugs and make the developing core more confident.

**Comment by dsznajder** [comment]
@osdnk I can help with this but I'm not sure if you would like to rewrite the whole package in one PR or partially?

**Comment by osdnk** [comment]
I'll happily rewrite everything at once. It's not a lot of code and I think it would be difficult to do it gradually.

**Comment by jakub-gonet** [comment]
Related to #829

**Comment by hosseinmd** [comment]
@dsznajder Is this in progress? If not, @osdnk I would like to do this task.

**Comment by jakub-gonet** [comment]
I tried to do it, there's some progress on that.

The biggest problem right now is a disparity between types and js code (i.e. `AnimatedValue` extends `InternalAnimatedValue` and not `AnimatedNode` like in types) but I didn't have time to fix it yet.

You can check out [my branch](https://github.com/software-mansion/react-native-reanimated/tree/%40kuba/add-ts) to see progress.
I think I have v2 rebased version locally, so I'll update it shortly.

**Comment by terrysahaidak** [comment]
Not sure about v1, but v2 can definitely be rewritten in TS (as well as web version). Not that many code should be written :)

**Comment by mrousavy** [comment]
Not sure if this is directly related, but the following code:
![Screenshot 2020-09-25 at 15 52 15](https://user-images.githubusercontent.com/15199031/94275298-16e3a500-ff47-11ea-8dd4-ab18aa6d8511.png)
makes TypeScript complain: 

```ts
Type 'true' is not assignable to type 'false'. ts(2322)
```

**Comment by jakub-gonet** [comment]
It's not, please open another issue.

**Comment by yolpsoftware** [comment]
@mrousavy Same thing with `useState(0)`, where you won't be able to assign a non-zero number.

You can workaround like this:

```
const hasBeenSwiped = useSharedValue(false as boolean);
```

or

```
const [state, setState] = useState(0 as number);
```

**Comment by hosseinmd** [comment]
@yolpsoftware is right. You can do this too
```js
const hasBeenSwiped = useSharedValue<boolean>(false);
```
