### ISSUE TITLE
Huge frame drop reanimated 2

### ISSUE THREAD

**Issue by arasrezaei** [software-mansion/react-native-reanimated#2700]
## Description
The FPS drops significantly in couple of seconds after app  start. Incredible thing when I tap and touch screen fast frame rate goes up again!!!!!!

### Expected behavior
Good FPS (60 FPS in emulator)

### Actual behavior & steps to reproduce
Bad FPS

## Snack or minimal code example

```
import Animated, {
  useSharedValue,
  withTiming,
  useAnimatedStyle,
  Easing
} from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React from 'react';

function AnimatedStyleUpdateExample(): React.ReactElement {
  const randomWidth = useSharedValue(10);

  const config = {
    duration: 500,
    easing: Easing.bezier(0.5, 0.01, 0, 1),
  };

  const itemCount = 100;

  const components = [];
  for(let i = 0; i < itemCount; i++) {
    components.push(
      <Animated.View key={i}
        style={[
          { width: 100, height: 5, backgroundColor: 'black', margin: 1 },
          useAnimatedStyle(() => {
            return {
              width: withRepeat(withTiming(Math.random() * 350, config),-1,true),
            };
          }),
        ]}
      />
    )
  }

  return (
    <View
      style={{
        flex: 1,
        flexDirection: 'column',
      }}>
      { components }
    </View>
  );
}
export default AnimatedStyleUpdateExample;
```
## Package versions

- React Native: 0.66
- React Native Reanimated: 2.3.0
- NodeJS: 16
- Xcode: '
- Java & Gradle: '

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by arasrezaei** [comment]
Tested on samsung galaxy s8+ 
With hermes / jsc (same results)
WithRepeat function

**Comment by arasrezaei** [comment]
https://user-images.githubusercontent.com/36116677/145118489-d8a7c1a4-a879-4e2c-8755-83d6b19dab0c.mp4

**Comment by patrickkempff** [comment]
@arasrezaei do you also have this issue on 2.2.4?

**Comment by arasrezaei** [comment]
> 

Same error on 2.2 
Please test it on android devices and you will see frame drops

**Comment by radko93** [comment]
You are creating all components from scratch on every render, how this can prove anything?

**Comment by arasrezaei** [comment]
> You are creating all components from scratch on every render, how this can prove anything?

AFAIK, This is one of examples reanimated team test performance, could you please fix code to not render all from scratch? 
Cause values are random and all should re render on every frame.
Please correct me if I'm wrong ...

**Comment by Only-IceSoul** [comment]
Svg use software without cache, try painter.

**Comment by Only-IceSoul** [comment]
You are creating 100 loop.

**Comment by arasrezaei** [comment]
> You are creating 100 loop.

This is one of performance test measurement by reanimated it self I think, could you make it faster?
I dont think 100 views are much for a device like Samsung S8 because if we animate 100 views at same time on android native animations, we can stay 60...
Even flutter's canvas can handle 100 widgets animate with 60 ...

**Comment by Only-IceSoul** [comment]
> > You are creating 100 loop.
> 
> This is one of performance test measurement by reanimated team I think, could it be faster with some code optimizations? I dont think 100 views are much for a device like Samsung S8 because if we animate 100 views at same time on android native animations, we can stay 60... Even flutter's canvas can handle 100 widgets animate with 60 ...

 100 withRepeat are running at the same time.
"withRepeat(withTiming(Math.random() * 350, config),-1,true)".

**Comment by dannyhw** [comment]
@arasrezaei 
Recreating the components on every render is not good practice for performance and it's not necessary for the example you created. You could just as easily create a static list of components. You should also not be calling a hook inside a loop.

The problem is with the way you are using react and not specifically with reanimated.

![image](https://user-images.githubusercontent.com/3481514/145612436-40443dcf-5a19-4461-9565-10db683c3086.png)

For example you could do this instead.

```
import Animated, {
  useSharedValue,
  withTiming,
  withRepeat,
  useAnimatedStyle,
  Easing,
} from 'react-native-reanimated';
import {View} from 'react-native';
import React, {ReactElement} from 'react';

const config = {
  duration: 500,
  easing: Easing.bezier(0.5, 0.01, 0, 1),
};
const AnimatedBar = () => (
  <Animated.View
    style={[
      {width: 100, height: 5, backgroundColor: 'black', margin: 1},
      useAnimatedStyle(() => {
        return {
          width: withRepeat(withTiming(Math.random() * 350, config), -1, true),
        };
      }),
    ]}
  />
);

const itemCount = 100;
const components: ReactElement[] = [];
for (let i = 0; i < itemCount; i++) {
  components.push(<AnimatedBar />);
}

function AnimatedStyleUpdateExample(): React.ReactElement {
  return (
    <View
      style={{
        flex: 1,
        flexDirection: 'column',
      }}>
      {components}
    </View>
  );
}
export default AnimatedStyleUpdateExample;
```

**Comment by Only-IceSoul** [comment]
> > > > You are creating 100 loop.
> > > 
> > > 
> > > This is one of performance test measurement by reanimated team I think, could it be faster with some code optimizations? I dont think 100 views are much for a device like Samsung S8 because if we animate 100 views at same time on android native animations, we can stay 60... Even flutter's canvas can handle 100 widgets animate with 60 ...
> > 
> > 
> > 100 withRepeat are running at the same time. "withRepeat(withTiming(Math.random() * 350, config),-1,true)".
> 
> And what's problem with this? It creates an equalizer like effect, could you optimize it for better fps?

Animate canvas and not the layout

**Comment by arasrezaei** [comment]
> 

could you please refer to canvas package?
