### ISSUE TITLE
Animated.FlatList is broken

### ISSUE THREAD

**Issue by Elabar** [software-mansion/react-native-reanimated#2704]
## Description
Button in FlatList is not pressable after the element is unmounted. Kinda hard to explain verbally, please take a look at the video below. Interestingly, if you used `Animated.FlatList` before, and swap it back to regular `FlatList`, the regular `FlatList` will be affected as well. You need to restart the bundler to resolve the problem.

### Expected behavior
Pressable in next element should be pressable after the previous element is removed.

https://user-images.githubusercontent.com/15872787/145156335-3af68ea6-167e-45b7-94df-438a03cf750c.mp4

### Actual behavior & steps to reproduce
As you can see in the video, after deleting one element, the Pressable in next element is not pressable.

https://user-images.githubusercontent.com/15872787/145156207-1888ad3f-1da9-4378-b3ff-652bdd65c95a.mp4

## Snack or minimal code example
diff between these implementation is within the FlatList only

<details>
<summary>React Native's FlatList implementation</summary>

```jsx
import React, {useState} from 'react';
import {
  Button,
  View,
  Text,
  FlatList,
  TextInput,
  SafeAreaView,
} from 'react-native';

function Participant({name, onRemove, id}) {
  return (
    <View style={[styles.participantView]}>
      <Text>{`${name};${id}`}</Text>
      <Button title="Remove" color="red" onPress={onRemove} />
    </View>
  );
}

const App = () => {
  const [inputValue, setInputValue] = useState('Reanimated');
  const [participantList, setParticipantList] = useState([]);

  const addParticipant = () => {
    setParticipantList(
      [{name: inputValue, id: Date.now().toString()}].concat(participantList),
    );
  };

  const renderParticipant = React.useCallback(({item: participant}) => {
    const removeParticipant2 = () => {
      setParticipantList(prev => {
        return prev.filter(prevPar => prevPar.id !== participant.id);
      });
    };
    return (
      <Participant
        key={participant.id + 'FLATLIST'}
        id={participant.id}
        name={participant.name}
        onRemove={removeParticipant2}
      />
    );
  }, []);

  return (
    <SafeAreaView style={{flex: 1, width: '100%'}}>
      <View style={styles.listView}>
        <Text>FlatList</Text>
        <FlatList
          data={participantList}
          style={[{width: '100%'}]}
          renderItem={renderParticipant}
        />
      </View>

      <View style={[styles.bottomRow]}>
        <View style={[styles.textInput]}>
          <Text>Add participant: </Text>
          <TextInput
            placeholder="Name"
            value={inputValue}
            onChangeText={setInputValue}
          />
        </View>

        <Button
          title="Add"
          disabled={inputValue === ''}
          onPress={addParticipant}
        />
      </View>
    </SafeAreaView>
  );
};

const styles = {
  participantView: {
    borderBottomColor: 'black',
    flex: 1,
    borderBottomWidth: 1,
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fffbeb',
  },
  listView: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  bottomRow: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
  },
  textInput: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
};

export default App;

```
</details>

<details>
<summary>Problematic Animated.FlatList implementation</summary>

```jsx
import React, {useState} from 'react';
import {Button, View, Text, TextInput, SafeAreaView} from 'react-native';
import Animated, {
  Layout,
  LightSpeedInLeft,
  LightSpeedOutLeft,
} from 'react-native-reanimated';

function Participant({name, onRemove, id}) {
  return (
    <Animated.View
      style={[styles.participantView]}
      entering={LightSpeedInLeft}
      exiting={LightSpeedOutLeft}
      layout={Layout.springify()}>
      <Text>{`${name};${id}`}</Text>
      <Button title="Remove" color="red" onPress={onRemove} />
    </Animated.View>
  );
}

const App = () => {
  const [inputValue, setInputValue] = useState('Reanimated');
  const [participantList, setParticipantList] = useState([]);

  const addParticipant = () => {
    setParticipantList(
      [{name: inputValue, id: Date.now().toString()}].concat(participantList),
    );
  };

  const renderParticipant = React.useCallback(({item: participant}) => {
    const removeParticipant2 = () => {
      setParticipantList(prev => {
        return prev.filter(prevPar => prevPar.id !== participant.id);
      });
    };
    return (
      <Participant
        key={participant.id + 'FLATLIST'}
        id={participant.id}
        name={participant.name}
        onRemove={removeParticipant2}
      />
    );
  }, []);

  return (
    <SafeAreaView style={{flex: 1, width: '100%'}}>
      <View style={styles.listView}>
        <Text>Animated.FlatList</Text>
        <Animated.FlatList
          itemLayoutAnimation={Layout.springify()}
          data={participantList}
          style={[{width: '100%'}]}
          renderItem={renderParticipant}
        />
      </View>

      <View style={[styles.bottomRow]}>
        <View style={[styles.textInput]}>
          <Text>Add participant: </Text>
          <TextInput
            placeholder="Name"
            value={inputValue}
            onChangeText={setInputValue}
          />
        </View>

        <Button
          title="Add"
          disabled={inputValue === ''}
          onPress={addParticipant}
        />
      </View>
    </SafeAreaView>
  );
};

const styles = {
  participantView: {
    borderBottomColor: 'black',
    flex: 1,
    borderBottomWidth: 1,
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fffbeb',
  },
  listView: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  bottomRow: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
  },
  textInput: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
};

export default App;

```
</details>

## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.3
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [ ] iOS (not sure)
- [ ] Web (not sure)

**Comment by braincore** [comment]
Similar issue here with v2.3.0 + LayoutAnimation. After removing a flatlist entry and re-adding it (same key) after a couple renders, the touchable for that entry does not work.

**Comment by frerjo** [comment]
This issue does not seem isolated to `Animated.FlatList`. The same issue can be observed when animating the list items of a regular RN `SectionList` with layout animations.

**Comment by ObidosDev** [comment]
Same for me. Items not clickable

**Comment by mitchellmcm27** [comment]
Yes, something similar happened to me using v2.3.0. A sort of zombie version of a list would be left over after remounting the list with new data. It would block interaction with the actual list. Happened to ScrollView, FlatList, everything I tried. I seem to remember errors from the XCode console about react shadow nodes being out of sync or something. 

I somehow had a hunch that it was related to a change in this PR https://github.com/software-mansion/react-native-reanimated/pull/2647

Downgrading to v2.2.x fixed the issue for me.

Sorry this is super vague. I was stuck on this for several days, trying to narrow it down, and had tons of tabs open, etc. When I fixed the problem by downgrading reanimated to v2.2, I was in a hurry to get unstuck. Hope this comment helps someone track something down.

**Comment by SvenJonsson** [comment]
Not sure how related but the work around I found might help someone. On Android I have had issues with exiting layout animations depending on the View structure (shown below). The result was a zombie View that blocked interaction.

Simplified App structure:
* react-navigation stack navigator
* Main View has a Scrollview with a few collections
* Detail View has a Flatlist with the many items inside one of these collections. It also has a notification coming down on top of the Flatlist that uses re-animated LayoutAnimations for entering and exiting animation. It was this notification that triggered the issue detailed below.

Issue:
On Android dismissing the notification on the Detail View and then navigating back to the Main View leaves a zombie View in the react-navigation stack somehow that blocks interaction on the Main View. The zombie View seems to follow normal zIndex stack order so if I put in a high zIndex I can interact with the content below. It could be that it is also left in iOS but that it doesn't block interactions in the same way so I don't notice it.  

Notification View structure that triggers the bug: 

```
shouldShow ? (
    <View style={...}>        
      <Animated.View
        entering={SlideInUp.duration(duration).delay(delayIn)}
        exiting={SlideOutUp.duration(duration)}
        style={...}
      >
       [...]
      </Animated.View>
    </View>
  ) : null
```
  
I found a work around by changing the structure to:
```
shouldShow ? (
    <Animated.View        
       entering={SlideInUp.duration(duration).delay(delayIn)}
       exiting={SlideOutUp.duration(duration)}
       style={...}>
      <View style={...}>
        [...]
      </View>
    </Animated.View>
  ) : null
```
Also making the inner View Animated.View seems to solve it, or at least make it less prevalent, without changing the structure.

**Comment by jdlk07** [comment]
I'm having the same issue after updating Expo SDK 43 > 44 which also updated reanimated from v2.2.x > 2.3.x. 

When the `Animated.FlatList` data changes, there are left over "zombie" children from the previous data set or if the `listEmptyComponent` was rendered, it stays "on screen". Both the stale children and `listEmptyComponent` show that they are unmounted however the component remains on screen but can not be interacted with.

This only seems to happen after I trigger any of the new API Layout methods (ie. `entering`, `exiting`) anywhere in the app, it doesn't have to be triggered from within the aforementioned FlatList or from within the same screen. Once I removed the `entering` and `exiting` props from `Animated.View`  the FlatList was working as intended.

And as @Elabar mentioned, you need to restart the bundler to see the changes.

**Comment by frederikchrlarsen** [comment]
I am experiencing the exact same thing as @jdlk07

**Comment by Guuz** [comment]
This even happens when i just use an Animated.View with one of the default layoutanimations anywhere on my screen. As soon as i do that "ghost" views stick around on Android. Like the ListEmptyComponent for instance.

**Comment by SvenJonsson** [comment]
We experienced the same as @Guuz at first and thought we had fixed it removing the Layout Animations from our project. Unfortunately we still have lingering zombie view issues. 

It's not straightforward to reproduce either, it just happens at seemingly random. Perhaps something is using this internally in reanimated? Can't find any 3d party library that uses Layout Animations in our project. We discovered it yesterday on Android but it might impact iOS as well.

We're running 2.3.1 and updating today to 2.4.1 to try to resolve the issue but didn't see any mention in the release notes about it. Otherwise downgrading is the only option I guess.

**Comment by AlexanderEggers** [comment]
We are only facing this issue on Android at the moment. Downgrading is not really an option because we want to support newer react native versions. I guess if that issue is not resolved soon, I might need to find a different animation library.

**Comment by Elabar** [comment]
@AlexanderEggers Can you try downgrading to 2.2.4 (Before introducing Layout Animation)? I can use it with RN v0.67.2 (latest stable as of writing) without problem.

**Comment by AlexanderEggers** [comment]
I will need to do some major refactoring of my code in that case (had some crashes around how I am running certain animations which does not happen with the latest reanimated version). It is also unlikely that 2.2.x is going to support the upcoming 0.68.x version.

**Comment by Elabar** [comment]
@AlexanderEggers can you show a the portion of the code that result in this crash?

**Comment by MichaelDanielTom** [comment]
Does anyone know if this issue still exists in reanimated 3? We've been blocked from using the entering/exiting/layout apis because of this issue and are wondering if investing the time to upgrade to one of the version 3 rc's would be worth it.

**Comment by Latropos** [comment]
I've just tested it with the newest reanimated - everything seems to work correctly! 🥳 
Thanks to everybody for submitting and commenting the issue.

**Comment by LucasHimelfarb** [comment]
@Latropos you tested it in both Platforms? Because in iOS apparently is not working. I mean, the prop itemLayoutAnimation do nothing in mi case. I've the last version of Reanimated and it is my flatlist:

```
              <Animated.FlatList
                  data={sessions}
                  style={Style.list}
                  renderItem={renderItem}
                  itemLayoutAnimation={FadeIn}
                  keyExtractor={item => item.id}
                  ItemSeparatorComponent={<View style={{height: 16}}/>}
              />
```

**Comment by Latropos** [comment]
@LucasHimelfarb 
Hi! 
>  you tested it in both Platforms? Because in iOS apparently is not working. **I mean, the prop itemLayoutAnimation do nothing in mi case.**

Yeah, I've tested it. This issue "Animated.FlatList is broken" is not related to prop `itemLayoutAnimation`, it is about FlatList Items containing pressable elements that became not pressable and this bug is the bug that is already fixed.

You describe some different anomaly, however, I think that everything works as desired, only FadeIn is not a valid layout animation - it is an entering animation. Please use something like below:
`itemLayoutAnimation={Layout.springify()}`
Here you can see it working:

https://github.com/software-mansion/react-native-reanimated/assets/56199675/00a18fd7-3dbe-4833-8ade-db80f1d65559

cc @kacperkapusciak We don't describe `itemLayoutAnimation` in our docs at all. 😱
