### ISSUE TITLE
InnerNativeModule.enableLayoutAnimations is not a function on Animated.Flatlist

### ISSUE THREAD

**Issue by adscud** [software-mansion/react-native-reanimated#2705]
## Description
I am using `react-native-reanimated@2.3.0` with `expo@43`, I'm trying to use the `Animated.FlatList` with `itemLayoutAnimation={Layout.springify()}` and this error message appears.

```
TypeError: InnerNativeModule.enableLayoutAnimations is not a function. (In 'InnerNativeModule.enableLayoutAnimations(flag)', 'InnerNativeModule.enableLayoutAnimations' is undefined)
```

### Expected behavior

Use layout animation on `Animated.FlatList`.

### Actual behavior & steps to reproduce

1. Using `<Animated.Flatlist>` with this props `itemLayoutAnimation={Layout.springify()}` with `expo@43`

## Snack or minimal code example

<details>
<summary>Example of FlatList implementation</summary>
<p>

```tsx
<Animated.FlatList
    itemLayoutAnimation={Layout.springify()}
    contentContainerStyle={tailwind.style({ 'flex-1': !props.data.length })}
    data={props.data}
    {...{
        renderItem,
        keyExtractor,
        getItemLayout,
    }}
    ListHeaderComponent={props.HeaderComponent}
    ListEmptyComponent={props.EmptyComponent}
    onViewableItemsChanged={onViewableItemsChanged.current}
    onEndReached={props.onEndReached}
    showsVerticalScrollIndicator={false}
    contentInsetAdjustmentBehavior='automatic'
/>
```

</p>
</details>  

## Package versions

- React Native: 0.64.3
- React Native Reanimated: 2.3.0
- Expo: 43.0.3

## Affected platforms

- [X] (?) Android
- [X] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello! Unfortunately, Expo SDK 43 does not support Reanimated 2.3.0 yet as it comes with brand new native code for layout animations etc. Hopefully it will be included in Expo SDK 44 coming soon!
