### ISSUE TITLE
Can't build Android release since 2.3.0 version

### ISSUE THREAD

**Issue by TomCorvus** [software-mansion/react-native-reanimated#2707]
## Description

Hello 👋,

I can't build Android release since react-native-reanimated: 2.3.0.

### Expected behavior

Can build AAB release

### Actual behavior & steps to reproduce

An error when I build the app Debug or Release :
```
> Task :react-native-reanimated:compileReleaseJavaWithJavac FAILED
/Users/runner/work/1/s/packages/***/node_modules/react-native-reanimated/android/expo/src/main/java/expo/modules/adapters/reanimated/EXReanimatedPackage.java:18: error: <anonymous expo.modules.adapters.reanimated.EXReanimatedPackage$1> is not abstract and does not override abstract method getBundleAssetName(boolean) in expo.modules.core.interfaces.ReactNativeHostHandler
    final ReactNativeHostHandler handler = new ReactNativeHostHandler() {
                                                                        ^
1 error

FAILURE: Build failed with an exception.
```

To reproduce, just init a bare workflow project with Expo and reanimated, and try to build debug release with Android Studio.

## Package versions

```
"expo": "^43.0.4",
"react-native-reanimated": "~2.3.0",
"react-native": "~0.64.3",
```

- NodeJS: 8.1.1
- Gradle : 4.2.2
- Java:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

Thanks 🙏

**Comment by pronevich** [comment]
It's the same issue for any type of build as debug in dev and release.

**Comment by piaskowyk** [comment]
Hello! Unfortunately, Expo SDK 43 does not support Reanimated 2.3.0 yet as it comes with brand new native code for layout animations etc. Hopefully it will be included in Expo SDK 44 coming soon!

**Comment by pairohit305** [comment]
is there any solution?? I am facing same problem!

**Comment by pronevich** [comment]
@pairohit305 in Expo project or bare RN?

**Comment by pairohit305** [comment]
@pronevich I am using expo 43 with bare RN build
