### ISSUE TITLE
Android R8: Type com.swmansion.reanimated.BuildConfig is defined multiple times after upgrading to 2.3.0

### ISSUE THREAD

**Issue by MingaudasVagonis** [software-mansion/react-native-reanimated#2711]
## Description
We are getting  `Type com.swmansion.reanimated.BuildConfig is defined multiple times` when executing the task :app:minifyReleaseWithR8. 

This started happening after upgrading to `v2.3.0` from `v2.3.0-beta.4` - **which was working fine**. We are using expo **modules** and we were getting this issue #2707 but that was fixed after upgrading to `expo v43.0.4 `

Conflicting files:
`*/.gradle/caches/transforms-3/de89dd491315155bcf462fb6bb0d5335/transformed/jetified-react-native-reanimated-66-hermes-runtime.jar:com/swmansion/reanimated/BuildConfig.class`
`*/node_modules/react-native-reanimated/android/build/intermediates/runtime_library_classes_jar/release/classes.jar:com/swmansion/reanimated/BuildConfig.class`

### Expected behavior
Able to build a minified release.
### Actual behavior & steps to reproduce
Build failure.
## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.3.0
- NodeJS: 16.13.0
- Xcode: 13.1
- Java & Gradle: 15.0.1 & 6.9
- Expo: 43.0.4

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by Kudo** [comment]
it's my bad! will create a pr addressing this. thanks!

**Comment by MingaudasVagonis** [comment]
That was fast, thank you!

**Comment by MingaudasVagonis** [comment]
Should the patch containing changes in that PR fix it? After applying I'm getting a new one, and I guess that also could be related to expo integration? (judging from the android-npm/build.gradle)
 
`Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-reanimated project caused this error: */node_modules/react-native-reanimated/android/react-native-reanimated-66-hermes.aar`

**Comment by Kudo** [comment]
@MingaudasVagonis interesting! what's the gradle command you executed? i'm curious why you are building a react-native-reanimated aar.

**Comment by MingaudasVagonis** [comment]
@Kudo I'm not quite sure myself why. After `:app:minifyReleaseWithR8`, task `:react-native-reanimated:bundleReleaseAar` is called and fails immediately.

**Comment by Kudo** [comment]
i probably find the difference. typically i run `./gradlew :app:assembleRelease` but not `./gradlew assembleRelease`. the later one will also take some time to generate aars for each library projects.
anyway, i'll try to find some solution to deal with the error. thanks for your information.

**Comment by Kudo** [comment]
@MingaudasVagonis can you help to verify if https://github.com/software-mansion/react-native-reanimated/pull/2713/commits/7cfee74b20ce4293552feb83c562b9f55a0278cf works for you?

**Comment by MingaudasVagonis** [comment]
@Kudo It's building without issues now, thanks!

**Comment by riamon-v** [comment]
How can you install this version of the repo since it is not published to npm yet ?

I have an issue when trying to add the github url in my package.json directly

**Comment by MingaudasVagonis** [comment]
@riamon-v you can apply a patch with [patch-package](https://www.npmjs.com/package/patch-package) until the changes are merged.

**Comment by renchap** [comment]
A release would be welcome to fix this issue, as it is impacting quite a lot of apps :)

**Comment by WilliamAlexander** [comment]
Tried bare rn project with expo 43 and -reanimated 2.3.0. No joy

Rolled -reanimared back to 2.2.4 and it works
