### ISSUE TITLE
[Bug] FlatList stops rendering items with Reanimated v2 installed.

### ISSUE THREAD

**Issue by ammarahm-ed** [software-mansion/react-native-reanimated#2712]
Hello, I have a FlatList rendering some items in my app. The does not use reanimated in FlatList. Yesterday I decided to upgrade from reanimated v1 to v2. Upon upgrading everything worked fine except FlatList not rendering any items at all. Rendering would work only if I would forcefully rerender the FlatList on state changes using the `key` prop. 

I then reverted all the changes and downgraded back to v1 and everything worked as expected again.

### Expected behavior

FlatList should render items properly.

## Package versions
- React Native: 0.66.3
- React Native Reanimated: latest beta
- NodeJS: 14.x
- Java & Gradle: Gradle 6.9

## Affected platforms

- [x] Android  - Tested only on android 
- [ ] iOS - Not tested
- [ ] Web - Not tested

**Comment by piaskowyk** [comment]
Hey @ammarahm-ed, could you provide a repo to reproduce your issue?

**Comment by ammarahm-ed** [comment]
#2802 should fix this hopefully. Closing
