### ISSUE TITLE
[Android] ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by MontreaI** [software-mansion/react-native-reanimated#2726]
## Description

I am currently using React Native Brownfield to handle my react native modules with my Android project, and when I try to launch my application I get the following error:

`E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
          This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.`

It looks like the iOS equivalent is already reported by someone else noted here: https://github.com/software-mansion/react-native-reanimated/issues/1439#issue-742586262

### Expected behavior

It should not crash when launching my application

### Actual behavior & steps to reproduce

I get this error immediately when I launch my app.

## Package versions

- react-native-cli: 2.0.1
- react-native: 0.66.4
- React Native Reanimated: 2.3.0
- NodeJS: v17.2.0
- Java & Gradle: Android SDK 31, Java 11, Gradle 7

## Affected platforms

- [x] Android

**Comment by nabarun1995** [comment]
same problem i've faceing

**Comment by tomekzaw** [comment]
Hello @MontreaI! Did you follow the installation instructions from [here](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/)? If it still doesn't work for you, here's some tips:

1. Make sure you have added Reanimated's Babel plugin to babel.config.js:
```js
plugins: [
      ...
      'react-native-reanimated/plugin',
],
```
Note that it must be the last on the list.

2. Reset cache: (`yarn start --reset-cache` or `expo r -c` if you're using expo)
3. Check if you have more than one babel configuration file (`babel.config.js`, .`babelrc`)
