### ISSUE TITLE
TypeError: global.performance.now is not a function

### ISSUE THREAD

**Issue by baveku** [software-mansion/react-native-reanimated#2730]
## Description

App crash when we start animation
TypeError: global.performance.now is not a function
### Expected behavior
Scroll Without Crashed
### Actual behavior & steps to reproduce
- Scroll on Flatlist
## Snack or minimal code example

```ts
<FlatList style={{ flex: 1 }}
				contentInset={{ top: 24 }}
				data={posts}
				renderScrollComponent={props => <Animated.ScrollView {...props} />}
				renderItem={({ item, index }) => <FeedCell post={item} imageIndex={item.id} onRemove={() => onRemove(item.id)} />}
				keyExtractor={(item, ind) => `${item.id}`}
				// Performance settings
				removeClippedSubviews={true} // Unmount components when outside of window
				initialNumToRender={6} // Reduce initial render amount
				maxToRenderPerBatch={2} // Reduce number in each render batch
				updateCellsBatchingPeriod={100} // Increase time between renders
				windowSize={6}
				scrollIndicatorInsets={{ top: 0 }}
			/>
```
## Package versions

- React Native: 0.64.4
- React Native Reanimated: 2.3.0
- NodeJS: 17
- Xcode: 13
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ x] iOS
- [ ] Web

**Comment by Crysp** [comment]
same issue, when use `useAnimatedStyle`

**Comment by chrisnojima** [comment]
this is due to https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/core.ts#L386 clobbering the values

**Comment by enesozturk** [comment]
Same here with `v2.3.1` in Expo app. Trying to use it with Storybook RN. I have a basic stack: 

```js
<Stack.Navigator>
  <Stack.Screen name="Home" component={TabNavigator} />
  <Stack.Screen name="Storybook" component={Story} />
</Stack.Navigator>
```

When I navigate to `Storybook` page, it is ok but when press go back. I got the issue.

<img width="451" alt="Screen Shot 2021-12-17 at 21 18 50" src="https://user-images.githubusercontent.com/19428358/146590070-37f640b3-b562-442d-9a19-6e8c08386b37.png">

Packages:
```json
{
  "expo": "^44.0.0",
  "react-native-reanimated": "~2.3.1",
}
```

Should I share any other details?

**Comment by enesozturk** [comment]
I think we can close this too, it is fixed in https://github.com/software-mansion/react-native-reanimated/pull/2761 by @michaelknoch and @piaskowyk.
