### ISSUE TITLE
Spreading animated style into style prop removes all styles

### ISSUE THREAD

**Issue by andrekovac** [software-mansion/react-native-reanimated#2731]
## Description

Passing animated style via spread operator doesn't work.

### Expected behavior

animated style should be applied

### Actual behavior & steps to reproduce

Style doesn't take any effect and being ignored. Additionally all other style of the element is gone.

## Snack or minimal code example

Given

```js
const offset = useSharedValue(buffer);
const animatedStyles = useAnimatedStyle(() => ({
  transform: [{ translateX: offset.value }],
}));
```

adding an animated style like this lets all the styles on the element disappear:

```
<Animated.View
  style={{
    width: 90,
    height: 90,
    backgroundColor: 'red',
    ...animatedStyles,
  }}
/>
```

See [this expo snack](https://snack.expo.dev/@andrusch/reanimated2---spread-animated-value)

## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.3.0
- NodeJS: v12.22.7
- Xcode: 12.5.1

## Affected platforms

Tested on iOS, but seems like a general issue to me.

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by brianreavis** [comment]
With reanimated, you'll want to use react-native's _array of styles_ convention like in the [example](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle#example):

```js
style={[{
    width: 90,
    height: 90,
    backgroundColor: 'red',
}, animatedStyles]}
```

**Comment by andrekovac** [comment]
> With reanimated, you'll want to use react-native's _array of styles_ convention like in the [example](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle#example):
> 
> ```js
> style={[{
>     width: 90,
>     height: 90,
>     backgroundColor: 'red',
> }, animatedStyles]}
> ```

That's what is used everywhere and which works. But is there a special reason why the spread operator doesn't work for reanimated?

**Comment by brianreavis** [comment]
It's because `useAnimatedStyle` returns a special object that's not just style properties: https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/hook/useAnimatedStyle.ts#L536 (which is then interpreted in [createAnimatedComponent](https://github.com/software-mansion/react-native-reanimated/blob/688a244b3826b0f6cde52e9490eee5fe0d3e9bf9/src/createAnimatedComponent.tsx#L411))

**Comment by jakub-gonet** [comment]
Resolved, closing.
