### ISSUE TITLE
Layout animation doesn't work with FlatList

### ISSUE THREAD

**Issue by Pietro-Putelli** [software-mansion/react-native-reanimated#2737]
Reanimated version: 2.3.0
When I try to use FlatList instead of ScrollView, as shown in the tutorial below, the Layout.springify() doesn't work.
https://docs.swmansion.com/react-native-reanimated/docs/tutorials/LayoutAnimations/layoutAnimations

Someone suggests to apply this path: https://patch-diff.githubusercontent.com/raw/piaskowyk/react-native/pull/1.patch.
How can I apply the patch?
Is there an alternative solution?

Thank you

**Comment by DigitalZebra** [comment]
I believe this is what `itemLayoutAnimation` is supposed to be for on Reanimated2's version of `FlatList`: https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/component/FlatList.tsx#L26

So I'd expect something like this to work (instead of the `Animated.ScrollView`):
```tsx
<Animated.FlatList
        data={participantList}
        keyExtractor={p => p.id}
        style={[{width: '100%'}]}
        itemLayoutAnimation={Layout.springify()}
        renderItem={({item: participant}) => {
          return (
            <Participant
              name={participant.name}
              onRemove={() => removeParticipant(participant.id)}
            />
          )
        }}
      />
```

However, I'm getting the same behavior as a normal `FlatList`- which is there's no `springify` on the position of the items when adding/removing.

**Comment by andresribeiro** [comment]
Same here

**Comment by DigitalZebra** [comment]
> I believe this is what `itemLayoutAnimation` is supposed to be for on Reanimated2's version of `FlatList`: https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/component/FlatList.tsx#L26
> 
> So I'd expect something like this to work (instead of the `Animated.ScrollView`):
> 
> ```tsx
> <Animated.FlatList
>         data={participantList}
>         keyExtractor={p => p.id}
>         style={[{width: '100%'}]}
>         itemLayoutAnimation={Layout.springify()}
>         renderItem={({item: participant}) => {
>           return (
>             <Participant
>               name={participant.name}
>               onRemove={() => removeParticipant(participant.id)}
>             />
>           )
>         }}
>       />
> ```
> 
> However, I'm getting the same behavior as a normal `FlatList`- which is there's no `springify` on the position of the items when adding/removing.

Ah turns out this code works on iOS, but not on Android - so seems like this is an Android only issue.

**Comment by Hirbod** [comment]
Layout animation does not work on iOS either correctly. All the animations do only work as long as the Flatlist Item which you try to add or remove is not in the overflowed area. As soon as your element is in a overflowed (eg hidden segment), the animations do not trigger on them. When my list shrinks or I remove elements at an index where the item is not overflowed, the animation works. (at least on iOS)

**Comment by Pietro-Putelli** [comment]
I can now confirm, that react native reanimated 2.3.0 works with the code I’ve initially published.
Thank you, all the software mansion developers for the best react-native library.

**Comment by j-piasecki** [comment]
Hi! It's recommended to use `FlatList` exported from `react-native-reanimated` it should also solve the problem.

**Comment by tarikko** [comment]
Not working for android :(
ig it's better to just use ScrollView instead :disappointed: 
anyway I will still wait for better support

**Comment by 000xuandu** [comment]
Same bug. 

```
const DATA = Array(10)
  .fill(1)
  .map((_, index) => index + 1);

<Animated.FlatList
        data={data}
        style={{flex: 1}}
        renderItem={({item}) => (
          <Animated.View
            key={item}
            entering={FadeIn}
            exiting={FadeOut}
            layout={Layout.delay(100)}
            style={styles.listItem}>
            <Text>{item}</Text>
          </Animated.View>
        )}
      />
```

https://user-images.githubusercontent.com/33916400/157805089-cc2dc2f9-4122-4def-80ba-62e1b361bc8e.mov

**Comment by arunim2405** [comment]
Any updates on this?

**Comment by nandorojo** [comment]
You need to use the [`itemLayoutAnimation`](https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/component/FlatList.tsx#L27) on the `Animated.FlatList`:

```tsx
<Animated.FlatList 
  itemLayoutAnimation={Layout.springify()}
/>
```

**Comment by tarikko** [comment]
> You need to use the [`itemLayoutAnimation`](https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/component/FlatList.tsx#L27) on the `Animated.FlatList`:
> 
> ```tsx
> // put this outside of render code
> const layout = Layout.springify()
> 
> <Animated.FlatList 
>   itemLayoutAnimation={layout}
> />
> ```

If you can make a demo, then that would be awesome.

**Comment by agoyal0422** [comment]
> You need to use the [`itemLayoutAnimation`](https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/component/FlatList.tsx#L27) prop on the `Animated.FlatList`:
> 
> ```tsx
> // put this outside of render code
> const layout = Layout.springify()
> 
> <Animated.FlatList 
>   itemLayoutAnimation={layout}
> />
> ```

This doesn't work for me. I'm still getting no animations on a Flatlist View with numColumns={2}

**Comment by kevindingens** [comment]
Bumping this issue - problem persists across both iOS and Android, even when using the above suggested, elsewhere suggested, and combinations of each.

**Comment by hadnet** [comment]
This is still an issue, a very serious problem may add. I'm using Reanimated 3-rc and nothing works, I read like a dozen of issues and non of them fix this problem.

**Comment by bi885895** [comment]
do you have any news? I code on my android device and when i delete item from array, animation don't work

**Comment by eprice122** [comment]
I am seeing this issue as well

**Comment by YunsGeek** [comment]
same here

**Comment by milanp93** [comment]
You can make entering and exciting animations by wrapping your ListItem in Animated.View, or put it inside the ListItem component:
`<Animated.View entering={BounceInLeft} exiting={BounceOutRight}>
      <PostItem item={item} />
    </Animated.View>`
    Entering animation works for me on both Android and IOS, but the existing animations still not working.

**Comment by km5x2** [comment]
This issue still exists 😞

**Comment by shedworth** [comment]
Still a thing

**Comment by amaurycoudr** [comment]
get the same issue as well

**Comment by dimaportenko** [comment]
@fakhergh thanks for sharing. I've just tried it with new expo project and 
```
    "react-native-reanimated": "~2.14.4"
```
iOS is working just fine. Android isn't working. What version are you using?

**Comment by NanddoSalas** [comment]
@fakhergh I tried implementing `CellRendererComponent` while using `reanimated: 2.14.4` but I didn't work on my project so I just copied and pasted your code and It didn't work again, can You share your package.json?

**Comment by fukemy** [comment]
> 

Hi, which version reanimated you used? This code work for ios, but not working with Android

**Comment by dimaportenko** [comment]
From my smoke test, it works on the version
```
"react-native-reanimated": "^3.1.0"
```

**Comment by OGreeni** [comment]
Any update on this? This is a pretty serious issue.

**Comment by aurangs7** [comment]
Same issue with FlatList, no animation on Android or iOS.

**Comment by fukemy** [comment]
@dimaportenko can u share piecies of code that you make the animation work?

**Comment by dimaportenko** [comment]
@fukemy I think it was https://github.com/dimaportenko/react-native-reanimated-issues-2737. But I don't really remember.

**Comment by Bonassa** [comment]
> > You can make entering and exciting animations by wrapping your ListItem in Animated.View, or put it inside the ListItem component: `const renderItem = ({ item }) => ( <Animated.View entering={BounceInLeft} exiting={BounceOutRight}> <PostItem item={item} /> </Animated.View> )` Entering animation works for me on both Android and IOS, but the existing animations still not working. P.S. it works with classic FlatList don't need to import FlatList from Reanimated.
> 
> Hi everyone, `entering` and `exiting` animations are not enough for list items animation's harmony and `itemLayoutAnimation` is not working with `createAnimatedComponent` function. Therefore, you should override the `CellRendererComponent` property of the animated list, see the example below for an animated flatlist, it is working fine on both Android and iOS.
> 
> ```
> import * as React from 'react';
> import { FlatList } from 'react-native';
> 
> const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);
> 
> // you can use it to create a section list e.g: 
> // const AnimatedSectionList = Animated.createAnimatedComponent(SectionList);
> 
> 
> function App() {
>   const [items, setItems] = React.useState<Array<any>>([]);
> 
>   const renderItem = React.useCallback(
>     ({ item }: any) => (
>       <TouchableOpacity
>           activeOpacity={0.9}
>           onPress={() => {
>             setItems(prevState => prevState.filter((i: number) => i !== item));
>           }}>
>           <View style={{height:100, marginVertical: 12, backgroundColor: "red" }}>
>             <Text style={{ color: "white", fontSize: 18}}>
>               {item}
>             </Text>
>           </View>
>       </TouchableOpacity>
>     ),
>     [],
>   );
> 
>   const onPress = React.useCallback(() => {
>     setItems(prevState => {
>       return [Date.now(), ...prevState];
>     });
>   }, []);
> 
>   const keyExtractor = React.useCallback((item: any) => {
>     return item.toString();
>   }, []);
> 
>   const renderCell = React.useCallback(
>     (props: any) => (
>       <Animated.View
>          {...props}
>           layout={Layout.springify()}
>           entering={ZoomIn}
>           exiting={ZoomOut}/>
>     ),
>     [],
>   );
> 
>   return (
>     <View style={{flex:1}} >
>       <Button title="ADD ITEM" onPress={onPress} />
>       <AnimatedFlatList
>         contentContainerStyle={{ paddingHorizontal: 24 }}
>         data={items}
>         renderItem={renderItem}
>         keyExtractor={keyExtractor}
>         CellRendererComponent={renderCell}
>       />
>     </View>
>   );
> }
> ```

That worked for me. I just made a callback function for the CellRendererComponent, and for typescript is possible to type the AnimatedFlatList.

```
const AnimatedFlatList = Animated.createAnimatedComponent(FlatList<YOUR_FLATLIST_TYPE>);

const renderCell = useCallback(
    (props: any) => (
      <Animated.View
        {...props}
        entering={SlideInRight}
        exiting={SlideOutRight}
        layout={Layout.springify()}
      />
    ),
    []
  );

<AnimatedFlatList
  data={taskHistory}
  keyExtractor={item => item.id}
  renderItem={({ item }) => (
   // Normal use
  )}
  CellRendererComponent={renderCell} // <- Add this
  ItemSeparatorComponent={ListSeparator}
/>
```

**Comment by marco2216** [comment]
Entering animation was not working for me in the renderCell on Android. But layout in renderCell works, and then combining that with adding an entering animation in the renderItem give the expected result.

**Comment by ali-soltanii** [comment]
> const renderCell = React.useCallback(
>     (props: any) => (
>       <Animated.View
>          {...props}
>           layout={Layout.springify()}
>           entering={ZoomIn}
>           exiting={ZoomOut}/>
>     ),
>     [],
>   );

This worked for me
Thank you.

**Comment by ali-soltanii** [comment]
> > You can make entering and exciting animations by wrapping your ListItem in Animated.View, or put it inside the ListItem component: `const renderItem = ({ item }) => ( <Animated.View entering={BounceInLeft} exiting={BounceOutRight}> <PostItem item={item} /> </Animated.View> )` Entering animation works for me on both Android and IOS, but the existing animations still not working. P.S. it works with classic FlatList don't need to import FlatList from Reanimated.
> 
> Hi everyone, `entering` and `exiting` animations are not enough for list items animation's harmony and `itemLayoutAnimation` is not working with `createAnimatedComponent` function. Therefore, you should override the `CellRendererComponent` property of the animated list, see the example below for an animated flatlist, it is working fine on both Android and iOS.
> 
> ```
> import * as React from 'react';
> import { FlatList } from 'react-native';
> 
> const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);
> 
> // you can use it to create a section list e.g: 
> // const AnimatedSectionList = Animated.createAnimatedComponent(SectionList);
> 
> 
> function App() {
>   const [items, setItems] = React.useState<Array<any>>([]);
> 
>   const renderItem = React.useCallback(
>     ({ item }: any) => (
>       <TouchableOpacity
>           activeOpacity={0.9}
>           onPress={() => {
>             setItems(prevState => prevState.filter((i: number) => i !== item));
>           }}>
>           <View style={{height:100, marginVertical: 12, backgroundColor: "red" }}>
>             <Text style={{ color: "white", fontSize: 18}}>
>               {item}
>             </Text>
>           </View>
>       </TouchableOpacity>
>     ),
>     [],
>   );
> 
>   const onPress = React.useCallback(() => {
>     setItems(prevState => {
>       return [Date.now(), ...prevState];
>     });
>   }, []);
> 
>   const keyExtractor = React.useCallback((item: any) => {
>     return item.toString();
>   }, []);
> 
>   const renderCell = React.useCallback(
>     (props: any) => (
>       <Animated.View
>          {...props}
>           layout={Layout.springify()}
>           entering={ZoomIn}
>           exiting={ZoomOut}/>
>     ),
>     [],
>   );
> 
>   return (
>     <View style={{flex:1}} >
>       <Button title="ADD ITEM" onPress={onPress} />
>       <AnimatedFlatList
>         contentContainerStyle={{ paddingHorizontal: 24 }}
>         data={items}
>         renderItem={renderItem}
>         keyExtractor={keyExtractor}
>         CellRendererComponent={renderCell}
>       />
>     </View>
>   );
> }
> ```
> 
> Here is visual results:
> 
> Android	iOS
> ![](https://user-images.githubusercontent.com/32802712/234582610-cf042959-78c7-4577-b13e-bc76ce7166c8.gif)	![](https://user-images.githubusercontent.com/32802712/234584755-45b54026-8be2-4659-8f1b-4f20ed16afeb.gif)

This worked for me.
Thank you

**Comment by Latropos** [comment]
I can confirmed that in discussion there are several solution fixing this issue. We are not going to fix issues with layout animations for Reanimated 2 - please use any of provided workaround or try using Reanimated 3.

**Comment by Latropos** [comment]
You can also fix the problem using prop `itemLayoutAnimation: Layout.Springify()` in your AnimatedFlatList.

**Comment by Bi0max** [comment]
> You can also fix the problem using prop `itemLayoutAnimation: Layout.Springify()` in your AnimatedFlatList.

Hi @Latropos , this still does not work on Android. I have Reanimated version 3.6.2.

**Comment by NiccoloCase** [comment]
same issue. with numColumns it doesn't work
