### ISSUE TITLE
'RNGestureHandlerStateManager.h' file not found

### ISSUE THREAD

**Issue by tapz** [software-mansion/react-native-reanimated#2740]
## Description

Xcode gives the following error when building:

> 'RNGestureHandlerStateManager.h' file not found

NativeProxy.mm:
`#import "RNGestureHandlerStateManager.h"`

NativeMethods.h
`#import "RNGestureHandlerStateManager.h"`

Works when I add "../" to the path:

`#import "../RNGestureHandlerStateManager.h"`

I don't know how this is supposed to work for anybody without either modifying the import or some search path.

### Expected behavior

File found

### Actual behavior & steps to reproduce

File not found

## Snack or minimal code example

`#import "RNGestureHandlerStateManager.h"`

## Package versions

- React Native: 0.66.4
- React Native Reanimated: 2.3.0
- NodeJS: 14.18.1
- Xcode: 13.1 (13A1030d)
- CocoaPods: 1.11.2

## Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

**Comment by kirilgorbachov** [comment]
+1

**Comment by edykim** [comment]
I found that the issue occurs when I have `use_frameworks!` in the Podfile. I couldn't figure out the difference, so I replaced some dependencies which requires `use_frameworks!` to non-required one.

**Comment by tapz** [comment]
I tried to make RNReanimated to use static frameworks and static library build type in podfile, but that did not help. Maybe I just create a PR for the .. paths :-)

**Comment by piaskowyk** [comment]
Hey, Is it possible you provide a repo to reproduce your issue?

**Comment by tapz** [comment]
@piaskowyk Here's a repo to reproduce this:

https://github.com/tapz/reanimatederror-example

**Comment by iKoru** [comment]
still occurs in version 2.3.1

**Comment by skdev24** [comment]
I'm facing a crash with version 2.2.4 https://github.com/software-mansion/react-native-reanimated/issues/2327#issue-981221150, and the solution for this is to update reanimated version to 2.3.1, which I'm not able to do because of the "RNGestureHandlerStateManager.h file not being found" build error.

**Comment by piaskowyk** [comment]
@tapz Thanks to your repro I resolved the problem in 5 minutes - thanks a lot! ❤️
This PR should resolve a problem - https://github.com/software-mansion/react-native-reanimated/pull/2815
