### ISSUE TITLE
Undefined is not an object (evaluating 'InnernativeModule.installCoreFunctions')

### ISSUE THREAD

**Issue by tapz** [software-mansion/react-native-reanimated#2741]
## Description

When starting the app, the following error is displayed:

> Undefined is not an object (evaluating 'InnernativeModule.installCoreFunctions')

Call stack
installCoreFunctions
  NativeReanimated.ts:14:3

![IMG_1581](https://user-images.githubusercontent.com/11726387/145877190-9c0d92f1-a16f-42c4-8d68-2111c296b8be.jpeg)

### Expected behavior

No errors

### Actual behavior & steps to reproduce

Errors

## Snack or minimal code example

Hermes is disabled as most of the pods fail to build when it's enabled.

```
import React, { useEffect } from 'react';

import {
  Dimensions,
  StyleSheet
} from 'react-native';

import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withTiming,
  runOnJS,
  runOnUI
} from 'react-native-reanimated';

import {
  GestureDetector,
  Gesture
} from 'react-native-gesture-handler';
```

## Package versions

- React Native: 0.66.4
- React Native Reanimated: 2.3.0
- NodeJS: 14.18.1
- Xcode: 13.1 (13A1030d)
- CocoaPods: 1.11.2

## Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

**Comment by fuekiin** [comment]
+1

**Comment by hugosbg** [comment]
see https://github.com/software-mansion/react-native-reanimated/issues/2525#issuecomment-1000628677

**Comment by piaskowyk** [comment]
Hey, could you (or anyone with the same issue) provide a repo to reproduce your issue?

**Comment by piaskowyk** [comment]
You can also look at this comment: https://github.com/software-mansion/react-native-reanimated/issues/2525#issuecomment-968918669 maybe it will be useful.

**Comment by tapz** [comment]
@piaskowyk Here's are repo to reproduce the issue. The repo also reproduces #[2740](https://github.com/software-mansion/react-native-reanimated/issues/2740) 

https://github.com/tapz/reanimatederror-example

**Comment by piaskowyk** [comment]
This isn't Reanimated issue but I resolved this problem. You missed bridge initialization in your AppDelegate. The bridge initialization creates native modules. That is why ReanimatedNativeModule was undefined.

You should modify AppDelegate -> application from this:
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
  let rootView = RCTRootView(bundleURL: self.bundleUrl, moduleName: "Example", initialProperties: [:], launchOptions: launchOptions)
    
  let window = UIWindow(frame: UIScreen.main.bounds)
  self.window = window

  let rootViewController = UIViewController()
  rootViewController.view = rootView
  
  window.rootViewController = rootViewController
  window.makeKeyAndVisible()
  return true
}
```
to something like this:
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
  let window = UIWindow(frame: UIScreen.main.bounds)
  self.window = window
  
  guard let bridge = RCTBridge(delegate: self, launchOptions: launchOptions) else { return false }
  let rootView = RCTRootView(bridge: bridge, moduleName: "Example", initialProperties: nil)
  
  let rootViewController = UIViewController()
  rootViewController.view = rootView
  
  window.rootViewController = rootViewController
  window.makeKeyAndVisible()
  return true
}
```

This resolved problem for me:

https://user-images.githubusercontent.com/36106620/148586732-6745f05d-6abc-4ae7-af7d-7f17ac2b3531.mov

**Comment by tapz** [comment]
The bridge should be created automatically. But nice if I can make it work by using another initializer :-)

```
 * - Convenience initializer -
 * A bridge will be created internally.
 * This initializer is intended to be used when the app has a single RCTRootView,
 * otherwise create an `RCTBridge` and pass it in via `initWithBridge:moduleName:`
 * to all the instances.
 */
- (instancetype)initWithBundleURL:(NSURL *)bundleURL
```

**Comment by zzyhdu** [comment]
Same issue here. Not work with initWithBundleURL:moduleProvider:launchOptions.

**Comment by edgaregidio** [comment]
1 - Make sure you have installed the correct dependencies. The error you are getting indicates that a file was not found. Make sure you installed the react-native-gesture-handler library correctly and added the necessary lines in the Podfile.

2 - Try clearing your project's cache and reinstalling dependencies. To do this, you can run the following commands:

```
npm start -- --reset-cache
npm run ios -- --reset-cache
rm -rf node_modules && npm install
cd ios && rm -rf Pods && pod install && cd ..
npm run ios
```

If the above steps don't work, try removing and reinstalling the react-native-reanimated library. To do this, run the following commands:


```
yarn remove react-native-reanimated
cd ios && pod install && cd ..
yarn add react-native-reanimated
cd ios && pod install && cd ..

```
If the error persists, try creating a new project and copy your current project's source code into the new project.

I hope one of these solutions helps resolve the issue.
