### ISSUE TITLE
Reanimated babel plugin transforms JS to crashing form if const/let declarations are preserved

### ISSUE THREAD

**Issue by DrRefactor** [software-mansion/react-native-reanimated#2742]
## Description

Reanimated2 babel plugin causes JS to crash when using e.g. useAnimatedRef

If const/let declarations are not transpiled to vars, output JS is crashing due to referencing parent function's variable from withing its declaration - inside internal `_closure` property.

Let me show an example of hook/useAnimatedRef.ts compilation:
 
original:
```
export function useAnimatedRef<T extends Component>(): RefObjectFunction<T> {
  const tag = useSharedValue<number | null>(-1);
  const ref = useRef<RefObjectFunction<T>>();

  if (!ref.current) {
    const fun: RefObjectFunction<T> = <RefObjectFunction<T>>((component) => {
      'worklet';
      // enters when ref is set by attaching to a component
      if (component) {
        tag.value = getTag(component);
        fun.current = component;
      }
      return tag.value;
    });

    Object.defineProperty(fun, 'current', {
      value: null,
      writable: true,
      enumerable: false,
    });
    ref.current = fun;
  }

  return ref.current;
}
```

compiled:
```
export function useAnimatedRef() {
  const tag = useSharedValue(-1);
  const ref = useRef();

  if (!ref.current) {
    const fun = function () {
      const _f = function (component) {
        // enters when ref is set by attaching to a component
        if (component) {
          tag.value = getTag(component);
          fun.current = component;
        }

        return tag.value;
      };

      _f._closure = {
        tag,
        getTag,
        fun // <--------------------------- this crashes!
      };
      _f.asString = "function _f(component){const{tag,getTag,fun}=jsThis._closure;{if(component){tag.value=getTag(component);fun.current=component;}return tag.value;}}";
      _f.__workletHash = 2837072662922;
      _f.__location = "/Users/pawelwieckowski/Projects/com/reanimated2-plugin-crash-repro/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedRef.ts (15:61)";

      global.__reanimatedWorkletInit(_f);

      return _f;
    }();

    Object.defineProperty(fun, 'current', {
      value: null,
      writable: true,
      enumerable: false
    });
    ref.current = fun;
  }

  return ref.current;
}
```

### Expected behavior
No crash, safe references in `_closure` with support of consts and lets.

### Actual behavior & steps to reproduce
Fast track:
1. Go to https://github.com/DrRefactor/reanimated2-plugin-crash-repro/commits/main/useAnimatedRef.compiled.js
1. See commits before & after fix https://github.com/DrRefactor/react-native-reanimated/commit/9212505ef426ea8a8c1ed73fe891530ac6381f8d is applied

Full repro:
1. Clone https://github.com/DrRefactor/reanimated2-plugin-crash-repro
1. `yarn`
1. `git checkout bd87ede7d2f1e344f75c8a7dc678b5ac88b2501d` (pre-fix version)
1. `yarn compile`
1. open compiled `useAnimatedRef.compiled.js`, see incorrect JS code 
1. `git checkout main`
1. `yarn compile`
1. open compiled js file

## Snack or minimal code example

https://github.com/DrRefactor/reanimated2-plugin-crash-repro

## Package versions

- React Native: *
- React Native Reanimated: 2.3.0
- NodeJS: *
- Xcode: *
- Java & Gradle: *

## Affected platforms

- [x] Android (not sure if it's reliably possible to configure babel this way, assuming - yes)
- [x] iOS (not sure if it's reliably possible to configure babel this way, assuming - yes)
- [x] Web

I will provide PR shortly, let's discuss there on whether my approach is good or not

**Comment by DrRefactor** [comment]
Super-simplified repro is pasting stripped code of compiled `useAnimatedRef` into e.g. browser console:
```
const fun = function () {
      const _f = function (component) {};

      _f._closure = {
        fun
      };

      return _f;
 }();
```

I've also tried pasting this into expo snack, but it seems to compile code before running it... and I fear `eval` too much to share snack with it inside :sweat_smile:

**Comment by piaskowyk** [comment]
Sorry for the late response, but I think this issue is no longer relevant in Reanimated 3. If you still facing this problem let me know.
