### ISSUE TITLE
missing interpolateColors mock

### ISSUE THREAD

**Issue by YOEL311** [software-mansion/react-native-reanimated#2749]
## Description

fix #2748

**Comment by orazoulay** [comment]
thanks

**Comment by avielyoeff** [comment]
thanks

**Comment by idandamri** [comment]
thanks

**Comment by piaskowyk** [comment]
Fixed with: https://github.com/software-mansion/react-native-reanimated/pull/2748

**Comment by YOEL311** [comment]
@piaskowyk 
When will a new version be released?

**Comment by ethanshar** [comment]
Any chances this will be released as a hotfix 🙏
