### ISSUE TITLE
[react-native-svg] regressions with react-native-reanimated 2.3.1

### ISSUE THREAD

**Issue by mlecoq** [software-mansion/react-native-reanimated#2750]
## Description

I have developed a small library to draw on pictures:

https://github.com/ArchireportTeam/react-native-svg-draw

When I use 2.3.1, I have the following issues (which are not present in 2.2.4):

On **Android**(only): fill: 'none' (in https://github.com/ArchireportTeam/react-native-svg-draw/blob/main/src/components/DrawCore/CurrentAnimatedItem.tsx) make a crash 

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.facebook.react.bridge.JavaOnlyArray.getDouble(JavaOnlyArray.java:91)
	at com.horcrux.svg.RenderableView.setupPaint(RenderableView.java:485)
	at com.horcrux.svg.RenderableView.setupFillPaint(RenderableView.java:435)
```

On **iOS** and **Android**:
Markers are sometimes not displayed (while drawing arrow for example)

### Expected behavior
The library have the same behavior with reanimated 2.2.4 and 2.3.1

### Actual behavior & steps to reproduce
Upgrade example app from https://github.com/ArchireportTeam/react-native-svg-draw to reanimated 2.3.1 and run the app

On **Android**, remove `fill: 'none'` in `CurrentAnimatedItem.tsx` to avoid the crash. 

Try to add arrows (with 2.2.4 arrow head is displayed, with 2.3.1 not)

## Snack or minimal code example
https://github.com/ArchireportTeam/react-native-svg-draw 

 

## Package versions
2.3.1

- React Native: 0.66.2
- React Native Reanimated: 2.3.1
- NodeJS: 16.13.1
- Xcode:
- Java & Gradle: jdk 8.0.312-zulu / gradle 4.2.2

## Affected platforms

- [X] Android
- [X] iOS
- [ ] Web

**Comment by nandorojo** [comment]
On iOS, if I try to animate the width of an SVG with `useAnimatedProps`, it no longer animates.

**Comment by schiller-manuel** [comment]
I also encountered a bug with `react-native-reanimated` 2.3.1 and `react-native-svg`.

I created a reproducer here:
https://github.com/schiller-manuel/reanimated-2-playground/tree/svg-bug-2.3.1

**Description**

When the app is started, the Text is placed almost entirely offscreen, the left upper screen corner shows a small part of the text.

When I save the file to trigger fast-refresh, the text is rendered at the correct position.

**Demo video**

https://user-images.githubusercontent.com/6340397/147280100-85cc5a42-88bc-439c-a220-5bccb3c54a1d.mp4

**Comment by kacperkapusciak** [comment]
Hi @mlecoq :wave:

We don't have enough resources to debug repro inside such a large repo. Could you provide a small, minimal, self-contained reproduction? Eg. a snack or a self-contained code snippet with all the necessary imports?

Cheers

**Comment by kacperkapusciak** [comment]
Hi @schiller-manuel,

Could you create a new issue with this information? These problems seem unrelated.

Cheers

**Comment by mlecoq** [comment]
@kacperkapusciak I have created a very small example here to reproduce crash on android : git@github.com:mlecoq/reanimated-2-svg-issue.git - app crashes on startup

**Comment by mlecoq** [comment]
@kacperkapusciak on a separated branch https://github.com/mlecoq/reanimated-2-svg-issue/tree/markerIssue
 
I have made a small example on marker issue which occurs on both iOS and android

**Comment by schiller-manuel** [comment]
> Hi @schiller-manuel,
> 
> Could you create a new issue with this information? These problems seem unrelated.
> 
> Cheers

@kacperkapusciak  done => https://github.com/software-mansion/react-native-reanimated/issues/2900
