### ISSUE TITLE
[2.3.0-beta.4] Rotate not working as expected

### ISSUE THREAD

**Issue by daxaxelrod** [software-mansion/react-native-reanimated#2754]
The rotate transform has inconsistent behavoir. Using just rotate: shareValue.value works on ios as expected. Android throws an error when rotate doesnt come in as a string. When you pass `${shareValue.value}deg` to android, nothing happens and the ios animation stops working.
```javascript
const animatedStyles = useAnimatedStyle(() => {
  return {
    transform: [
      { rotate: derivedAngle.value },
    ],
  }
})
```

## Package versions
"react-native": "0.63.4",
"react-native-reanimated": "2.3.0-beta.4",
"react-native-redash": "^16.2.3",

## Affected platforms

- [ X ] Android
- [ X ] iOS
- [ ] Web

**Comment by kmagiera** [comment]
@daxaxelrod – thanks for reporting but the description lacks a lot of details about how the issue should be reproduced. It'd be much appreciated if you could provide a code of the whole component or best if there is a repository on github that we can try. Otherwise, we often spend more time guessing the missing details which makes results in fewer time we can spend on addressing the issues. Thanks!

Also: this is possibly related to #1062 ?

**Comment by evd1ser** [comment]
same problem when i add any rotation all transitions removed:

```
import React, { Component } from 'react';
import Animated, { Extrapolate, Value } from 'react-native-reanimated';

export class WebPlayground extends Component {
  private _rotateValue = new Value<number>(0);

  componentDidMount() {
    setTimeout(()=>{
      console.log('change rotate');
      this._rotateValue.setValue(1);
    }, 500);
  }

  render() {
    const rotate = this._rotateValue.interpolate({
      inputRange: [0, 1],
      // outputRange: [0, 45],
      outputRange: ['0deg', '30deg'],
      extrapolate: Extrapolate.CLAMP,
    });
    const translateX = this._rotateValue.interpolate({
      inputRange: [0, 1],
      outputRange: [10, 300],
      extrapolate: Extrapolate.CLAMP,
    });

    return (
      <Animated.View style={[{
        width: 50,
        height: 50,
        backgroundColor: '#f00',
        transform: [
          // any value crash transitions
          // { rotate },
          // { rotateZ: '10deg' },
          // { rotate: '10deg' },
          // { rotate: 45 },
          // only translateX work fine
          { translateX },
        ],
      }]} />
    );
  }
}
```

if no rotation, css transform created normal
<img width="265" alt="Снимок экрана 2022-04-12 в 16 14 03" src="https://user-images.githubusercontent.com/15332093/162970518-d9ca16bf-934f-4f96-873b-54747b1bea87.png">

if i add this property:
<img width="277" alt="Снимок экрана 2022-04-12 в 16 14 53" src="https://user-images.githubusercontent.com/15332093/162970679-8b1a3b13-e0b8-4e43-93dc-04bd494e3f63.png">


i use "react-native-reanimated": "2.6.0"

**Comment by evd1ser** [comment]
Okay, I think i can found the problem: when i want use `outputRange: ['0deg', '30deg'],` reanimate remove 'deg' and transform it to 'rad' number value, but web needs string (like `3.14rad`) not only number (`3.14`).

**Comment by evd1ser** [comment]
for my case i can add patch file with patch-package:

```diff
diff --git a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedTransform.js b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedTransform.js
index 9d5c5de..4ccb5d8 100644
--- a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedTransform.js
+++ b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedTransform.js
@@ -1,3 +1,4 @@
+import { Platform } from 'react-native';
 import AnimatedNode from './AnimatedNode';
 
 import deepEqual from 'lodash.isequal';
@@ -69,7 +70,11 @@ class AnimatedTransform extends AnimatedNode {
       for (const key in transform) {
         const value = transform[key];
         if (value instanceof AnimatedNode) {
-          result[key] = value.__getValue();
+          if(Platform.OS === 'web' && key.startsWith('rotate')){
+            result[key] = value.__getValue() + 'rad';
+          } else {
+            result[key] = value.__getValue();
+          }
         }
       }
       return result;

```
