### ISSUE TITLE
[iOS release] cause random crash with react-native-video

### ISSUE THREAD

**Issue by Deodes** [software-mansion/react-native-reanimated#2757]
When use react-native-reanimated with react-native-video at launch, app can crash with:

`libc++abi: terminating with uncaught exception of type folly::json::print_error: folly::toJson: JSON object value was an INF`

### Expected behavior

App not randomly crash

### Actual behavior & steps to reproduce

Install react-native-reanimated(v2 or more) and react-native-video and call: `this.videoPlayerRef.seek(...)`

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.2.2, 2.3.1 (maybe more)
- NodeJS: 17.2.0
- Xcode: 13.1

## Affected platforms

- [X] iOS

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?

**Comment by Deodes** [comment]
@piaskowyk it is quite difficult to reproduce because it is a large and commercial project. I will try to create a new one with the same versions of dependencies and share with you as soon as possible

**Comment by Deodes** [comment]
@piaskowyk after update react-native to 0.66.4 and react-native-reanimated to 3.2.1 the error has become more informative: 

`libc++abi: terminating with uncaught exception of type folly::json::print_error: folly::toJson: JSON object value was an INF when serializing value at "playableDuration"`

**Comment by jakub-gonet** [comment]
Does it crash every time you call `videoPlayerRef.seek` or only when you use it inside the worklets? We need a repro and more information to solve that issue, unfortunately.

**Comment by tomekzaw** [comment]
Duplicate of #1776, working on a fix right now.
