### ISSUE TITLE
Layout animation leave orphaned component in Expo

### ISSUE THREAD

**Issue by dpnick** [software-mansion/react-native-reanimated#2758]
## Description

I found a strange behavior while trying to use react-native-reanimated layout animation with the latest Expo SDK (44). Component with layout animation seems to leave orphaned component at re-render. (related [expo issue](https://github.com/expo/expo/issues/15600)) 

I have a simple conditional rendering, when the component mount it should display a spinner for 3000ms and then a list of (transparent for demo purpose) items. However, on the first render after the 3000ms the spinner AND the list are both visible at the same time.

If I reload the project everything works as expect. But as soon as I completely restart the app, this behavior happen.

I was able to reproduce this behavior in a fresh new app, I will include the steps bellow.

https://user-images.githubusercontent.com/23317360/146521672-a5c679cf-eff2-4ba8-baee-a99346778f37.mov

### Expected behavior

The layout animation works as expected (and are, actually, awesome). But it seems to introduce a bug with conditional component rendering. In my case, after 3000ms, the spinner is supposed to be hidden and replaced by the list. 

### Actual behavior & steps to reproduce

At component mount a spinner is supposed to be visible during 3000ms. After this time, the spinner should be replaced by a scrollview.

Check my minimal code bellow.

## Snack or minimal code example

// update to expo 44 (currently beta) to be able to use `react-native-reanimated` > 2
```
$ EXPO_BETA=1 expo init --npm
$ # Choose "blank (TypeScript)"
$ expo install react-native-reanimated react-native-screens
```

babel.config.js
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
```

App.tsx
```
import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import Animated, {
  FadeInUp,
  FadeOutDown,
  Layout,
} from 'react-native-reanimated';

const AnimatedView = Animated.createAnimatedComponent(View);

export default function App() {
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    const timeout = setTimeout(() => setIsLoading(false), 3000);
    return () => {
      clearTimeout(timeout);
    };
  }, []);

  return (
    <View style={styles.container}>
      {isLoading ? (
        <ActivityIndicator size='large' color='red' />
      ) : (
        <AnimatedView
          entering={FadeInUp}
          exiting={FadeOutDown}
          layout={Layout.springify()}
          style={styles.scrollContainer}
        >
          {[...Array(10).keys()].map((value) => (
            <View style={styles.row} key={value}>
              <Text>row n°{value}</Text>
            </View>
          ))}
        </AnimatedView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContainer: {
    flex: 1,
    width: '100%',
  },
  row: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    height: 50,
  },
});
```

## Package versions

```
    "expo": "~44.0.0",
    "react-native": "0.64.3",
    "react-native-reanimated": "~2.3.1",
    "react-native-screens": "~3.10.1"
```

Node.js: v14.15.3

## Affected platforms

- [ ] Android : (not sure, unable to test at the moment)
- [x] iOS

**Comment by pairohit305** [comment]
Thanks for reporting this issue man! I am facing same bug in my app
![Screenshot_2021 12 18_02 22 45 452](https://user-images.githubusercontent.com/36040318/146606552-1b83afc1-2c16-4b31-86cd-0f0a1253e712.png)
Overlapping on condition render and it goes if I manually refresh

**Comment by pairohit305** [comment]
that grey thing is a skeleton loader which is overlapping with the content!

**Comment by pairohit305** [comment]
i am too using expo 44, reanimated 2 and screen in my package

**Comment by dpnick** [comment]
Thanks! Glad to know I'm not the only one affected 😄

**Comment by pairohit305** [comment]
any update ? on how to fix this bug?

**Comment by dpnick** [comment]
not yet unfortunately

**Comment by bryansum** [comment]
Looked at this some more and it repros beginning with `2.3.0-beta.4` (and not `2.3.0-beta.3`), so was introduced by one of the commits in https://github.com/software-mansion/react-native-reanimated/releases/tag/2.3.0-beta.4

**Comment by bryansum** [comment]
Weird calling `enableLayoutAnimations(true)` in `App.tsx` fixes this for me:
```
--- a/App.tsx
+++ b/App.tsx
@@ -1,12 +1,14 @@
 import { useEffect, useState } from "react";
 import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
 import Animated, {
+  enableLayoutAnimations,
   FadeInUp,
   FadeOutDown,
   Layout,
 } from "react-native-reanimated";
 
 const AnimatedView = Animated.createAnimatedComponent(View);
+enableLayoutAnimations(true);
```

**Comment by dpnick** [comment]
@bryansum i can confirm it resolved the issue for me too

**Comment by intagaming** [comment]
@bryansum Apparently, doing this would make my component ignore the Header of the Native Stack Header from React Navigation. It just sat behind the Header.
I'm using Expo. `expo install` won't let me install `2.3.0-beta.3`, and currently my `npm install` just hang when installing it either, so I could not try to downgrade Reanimated. It's currently `2.3.1`.
