### ISSUE TITLE
Default parameter on worklet causes "Can't find variable" after upgrading from 2.2 to 2.3.1

### ISSUE THREAD

**Issue by guiccbr** [software-mansion/react-native-reanimated#2763]
## Description

I just upgraded from 2.2 to 2.3.1. Everything was working fine, but then I started to see an error of the type "Can't find variable". The error turned out to be because I was using a default parameter in a worklet. See the example below for more details. 

### Expected behavior

I'd expect default parameters to continue to work fine on worklets.

### Actual behavior & steps to reproduce

Check details below

#### This doesn't work!

```
const DEFAULT_VALUE = 'any-value';

function myWorklet(value: string = DEFAULT_VALUE) { // This doesn't work
  'worklet';
  console.log(value);
}
```

Whenever this worklet is called, I'm getting `Can't find variable 'value'`. If I pass the default value directly though, it works. The problem seems to happen only when I have the variable defined outside of the worklet.

#### This works!

```
function myWorklet(value: string = 'any-value') { // This works!
  'worklet';
  console.log(value);
}
```

## Package versions

- React Native: 0.66.1
- React Native Reanimated: 2.3.1

## Affected platforms

- [ ] Android (not sure)
- [X] iOS
- [ ] Web (not sure)

**Comment by jkadamczyk** [comment]
Hi @guiccbr 

Did you try clearing all cache? By all I mean since your issue appears on iOS, did you clean JS cache, iOS build cache, iOS DerivedData, and removed `Pods` and reinstalled with `pod install`?

**Comment by Latropos** [comment]
Closed due to inactivity

**Comment by bfricka** [comment]
This issue occurs for me as well. Clearing cache makes no difference in my case. The previously declared value can certainly be used, but not using default parameter syntax. In order words:

```ts
const FOO = 1

const thisFails = (v = FOO) => {
  'worklet'
  console.log(v)
}

const thisWorks = (v?: number) => {
  'worklet'
  v ??= FOO
  console.log(v)
}
```
