### ISSUE TITLE
Nested objects for useAnimatedProps

### ISSUE THREAD

**Issue by dozsolti** [software-mansion/react-native-reanimated#2767]
## Description
Fails to use a nested object with useAnimatedProps. Most likely the same issue as https://github.com/software-mansion/react-native-reanimated/pull/2257 but isn't fixed for useAnimatedProps.

### Expected behavior
To be able to animated properties from a deeper level.

### Actual behavior & steps to reproduce
![image](https://user-images.githubusercontent.com/17215747/146682517-98dc8612-e0ed-460b-b253-92175d3c4dca.png)

## Snack or minimal code example
`import React, { useEffect } from "react";
import MapView, { Marker } from "react-native-maps";
import { StyleSheet, View, Dimensions } from "react-native";
import * as Location from "expo-location";
import { MaterialIcons } from "@expo/vector-icons";
import Animated, {
    useAnimatedProps,
    useSharedValue,
    withTiming,
} from "react-native-reanimated";

Animated.addWhitelistedNativeProps({ coordinate: true });

const AnimatedMarker = Animated.createAnimatedComponent(Marker);

const MapScreen = () => {
    const lat = useSharedValue(0);
    const long = useSharedValue(0);

    const StartWatchingLocation = async () => {
        await Location.requestForegroundPermissionsAsync();
        await Location.watchPositionAsync(
            { accuracy: Location.Accuracy.Highest, interval: 100 },
            (loc) => {
                console.log("lat", loc.coords.latitude); // <- this works
                lat.value = withTiming(loc.coords.latitude);
                long.value = withTiming(loc.coords.longitude);
            }
        );
    };

    const locationProp = useAnimatedProps(() => {
        // if I return a single level object, it works
        return {
            coordinate: {
                latitude: lat.value,
                longitude: long.value,
            },
        };
    }, [lat, long]);

    useEffect(() => {
        StartWatchingLocation();
    }, []);

    return (
        <View style={styles.container}>
            <MapView style={styles.map}>
                <AnimatedMarker animatedProps={locationProp} flat>
                    <MaterialIcons name="navigation" size={36} color="blue" />
                </AnimatedMarker>
            </MapView>
        </View>
    );
};

export default MapScreen;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
        alignItems: "center",
        justifyContent: "center",
    },
    map: {
        width: Dimensions.get("window").width,
        height: Dimensions.get("window").height,
    },
});
`
## Package versions

- React Native: 0.64.3
- React Native Reanimated: ~2.2.0
- NodeJS: v14.17.3

## Affected platforms

- [X] Android
- [ ] iOS - not tested
- [ ] Web - not tested

**Comment by piaskowyk** [comment]
You should use `addWhitelistedNativeProps({coordinate: true})` or `addWhitelistedUIProps({coordinate: true})`, more info here https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedProps

It is because Reanimated doesn't support by default any custom props, you should add them manually to allowlist.

**Comment by dozsolti** [comment]
Thanks for the help.
I've tried with `Animated.addWhitelistedNativeProps({ coordinate: true });` as you can see in the code sample above and nothing.
But works like a charm with `addWhitelistedUIProps`.
