### ISSUE TITLE
FlatList inverted, itemLayoutAnimation and Typescript not working

### ISSUE THREAD

**Issue by MasonLe2497** [software-mansion/react-native-reanimated#2769]
https://user-images.githubusercontent.com/43195241/146722205-34558cbe-5ffd-4653-b648-e99fd6c0c852.mp4

## Description
I found this issue when use Animated.FlatList with inverted. You can see my video below:

### Expected behavior
inverted, itemLayoutAnimation and Typescript working
### Actual behavior & steps to reproduce
Install library then use Animated.FlatList

## Snack or minimal code example
``` tsx
import React, {memo, useCallback, useState} from 'react';
import isEqual from 'react-fast-compare';
import {Button, Text, View} from 'react-native';
import Animated, {Layout} from 'react-native-reanimated';
import {SafeAreaView} from 'react-native-safe-area-context';

const LoginComponent = () => {
  // state
  const [data, setData] = useState<Array<string>>([
    'Hello',
    'Hi',
    'My name is Jon',
  ]);

  // func
  const onPush = useCallback(() => {
    setData(d => ['New Text'].concat(d));
  }, []);

  // render
  return (
    <SafeAreaView style={{flex: 1}}>
      <Animated.FlatList
        inverted
        itemLayoutAnimation={Layout.springify()}
        renderItem={({item, index}) => {
          return (
            <View key={index}>
              <Text>{item}</Text>
            </View>
          );
        }}
        data={data}
      />
      <Button title={'PUSH'} onPress={onPush} />
    </SafeAreaView>
  );
};

export const Login = memo(LoginComponent, isEqual);

```

## Typescript error
![image](https://user-images.githubusercontent.com/43195241/146722660-232b3a53-ad01-403b-9642-cdf41ac24b65.png)

## Package versions

- React Native: 0.66.4
- React Native Reanimated: 2.3.1
- NodeJS: 17.3.0
- Xcode: 12.5.1

## Affected platforms

- [] Android
- [x] iOS
- [ ] Web

**Comment by Swiftwork** [comment]
I also notice that using
```ts
Animated.createAnimatedComponent(FlatList)
```
or
```ts
Animated.FlatList
```
breaks type inference of the children. For the first example
```ts
Animated.createAnimatedComponent<FlatListProps<ChildType>>(FlatList)
```
can be used to restore some functionality. But this should probably be handled more generically with `Animated.FlatList`.

**Comment by Ubax** [comment]
@MasonLe2497 Is this a problem with typescript only?
I mean is there any bug on the video you attached?

**Comment by punksta** [comment]
Perhaps I am getting the same issue. It's not typescript, it's `inverted` behavior.

## expected behavior
https://reactnative.dev/docs/flatlist#inverted
>Reverses the direction of scroll. Uses scale transforms of 

## actual behavior
`inverted` is mirroring the list elements against X axis. Instead of reversing the direction of scroll.

## FlatList
![simulator_screenshot_739E8E94-288E-4E2C-9BDB-09EACAC772FF](https://user-images.githubusercontent.com/13404754/151816003-ece05fb2-f01b-400d-ab7c-913f02ff3d59.png)

## Animated.FlatList
![simulator_screenshot_AD0624A9-9229-4A17-BCAE-D42F39206FD3](https://user-images.githubusercontent.com/13404754/151816075-8995ff06-272c-4915-83db-d342beb5f110.png)


I fixed my issue by rotating elements back on X axis.

```

 export const WeightList = () => {
  const { data } = useWeightHistory()
  return (
    <Animated.FlatList
      style={{
        flex: 1
      }}
      keyExtractor={keyExtractor}
      inverted
      data={data}
      renderItem={info => (
        <Animated.View
          style={{
            transform: [
              {
                rotateX: '180deg'
              }
            ]
          }}
        >
          {renderItem(info.item)}
        </Animated.View>
      )}
    />
  )
}
```

**Comment by Ubax** [comment]
Thank you. Good that you found a workaround.

We will take a look at this issue in the near future, but I cannot tell when precisely.

**Comment by kmalyshev** [comment]
The bug is quite annoying for a chat app. Thank you for posting the workaround

**Comment by homosape** [comment]
Thanks for posting workaround, this issue is indeed a nuisance when building a chat feature

**Comment by alistairholt** [comment]
Would be nice if we didn't have to hack it back to working the same way that FlatList does by using transforms.
