### ISSUE TITLE
Require cycles (v1.0.1)

### ISSUE THREAD

**Issue by penphy-dev** [software-mansion/react-native-reanimated#277]
As version 1.0.1, there're 6 require cycles:
![image](https://user-images.githubusercontent.com/48114766/57504921-acfe3780-7320-11e9-9dc0-fed660f989ee.png)
![image](https://user-images.githubusercontent.com/48114766/57504935-b6879f80-7320-11e9-8085-4abf114fba07.png)
Please help me to fix this issue. Thank you!

**Comment by liCat** [comment]
the Same!

**Comment by samiede** [comment]
As per [https://github.com/kmagiera/react-native-reanimated/issues/159#issuecomment-486578624](this comment) it is fixes in master and this probably fixed in the next version.

**Comment by jakub-gonet** [comment]
Hi @penphy-dev,
I'm sorry for the late response 😔

As @samiede mentioned bugfix for this issue was submitted in #187 and released in 1.1 version, so it should be working now.

If the problem persists please reopen this issue.
