### ISSUE TITLE
Layout Animation doesn't work on Android with FlatList

### ISSUE THREAD

**Issue by adscud** [software-mansion/react-native-reanimated#2770]
## Description
There is two different behavior between iOS and Android, in fact on iOS this code runs without any problem but on Android none of theses animations works.

### Expected behavior

The items should enter and exit smoothly for both platforms.

### Actual behavior & steps to reproduce
iOS => The items enter and exit smoothly
Android => The items enter and exit without animations

To reproduce, just runs this code with your own `renderItem`.

## Snack or minimal code example

```tsx
import React from 'react'
import { FlatList, FlatListProps } from 'react-native'
import Animated, { FadeInUp, FadeOut } from 'react-native-reanimated'

interface Props extends FlatListProps<any> {

}

const AnimatedFlatList = Animated.createAnimatedComponent(FlatList)

const createCellRenderer = () => {
    const cellRenderer: React.FC = (props) => {
        return (
            <Animated.View
                entering={FadeInUp.duration(250)}
                exiting={FadeOut.duration(250)}
            >
                {props.children}
            </Animated.View>
        )
    }

    return cellRenderer
}

export const AnimatedList = (props: Props) => {
    const CellRenderer = React.useMemo(
        () => createCellRenderer(),
        [],
    )

    return (
        <AnimatedFlatList
            {...props}
            CellRendererComponent={CellRenderer}
        />
    )
}

```

## Package versions

- React Native: `0.64.3`
- React Native Reanimated: `2.3.1`
- NodeJS: `16.13.0`

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by Elabar** [comment]
For LayoutAnimation, please try Animated.FlatList as shown here #2674  instead of using createAnimatedComponent.

But there are some weird bugs atm #2703 #2704

**Comment by adscud** [comment]
In fact, their example use `createAnimatedComponent`, take a look here: https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/component/FlatList.tsx

**Comment by Elabar** [comment]
thats not example, it is their version of FlatList which overwrite the original FlatList's CellRendererComponent

**Comment by jakub-gonet** [comment]
Idea: Have you tried replacing default scrollView with `createAnimatedComponent(ScrollView)` via `renderScrollComponent`?

**Comment by adscud** [comment]
@jakub-gonet Hello, 
In fact, I use the Flat List in this issue, your idea remains valuable?

**Comment by jakub-gonet** [comment]
FlatList is actually VirtualizedList that uses ScrollView under the hood, my idea is to replace this component with AnimatedScrollView. You can use `renderScrollComponent` prop in FlatList to control which component is used for scrolling (as I said, ScrollView is the default but you can replace it with different component).

**Comment by adscud** [comment]
Nice idea, little bit busy for now, but I'll try it !!!
Thanks.

**Comment by adscud** [comment]
I come to the news. I tested your implementation which didn't change much, I went back to the basic Flat List without overloading the cellRenderer, it works for the entering animation on both platforms, only the exiting on Android doesn't works.

It's an improvement I have an animation for the entering on Android. :)

**Comment by Stevemoretz** [comment]
Tested both with `Animated.Flatlist` and `Flatlist` neither work on iOS.

```
    "react-native-reanimated": "~2.3.1",
```

**Comment by jacobSND** [comment]
I'm having the same issue, entering works on both platforms but exiting only works on IOS. Did you happen to find a solution for this?

**Comment by adscud** [comment]
@jacobSND Nop

**Comment by asfand-butt** [comment]
Still, having the same issue any update on this?

**Comment by eprice122** [comment]
Also seeing this issue

**Comment by tondeee** [comment]
as well

**Comment by albanx** [comment]
Issue is still open and replicable. I am using Expo react native and flat list

**Comment by eprice122** [comment]
Anyone found a solution for this yet?

**Comment by fukemy** [comment]
any solution now? I am using v3.1.0 but seem not solved

**Comment by Latropos** [comment]
Closing this issue, since
* `const AnimatedFlatList = Animated.createAnimatedComponent(FlatList)`
is not a valid way to create animated flatlist, please use Animated.FlatList instead
* We overwrite prop `CellRendererComponent` so unfortunately providing its value is not supported
