### ISSUE TITLE
 ERROR  Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

### ISSUE THREAD

**Issue by Justin9606** [software-mansion/react-native-reanimated#2774]
## Description
I did 
->  yarn add react-native-reanimated@next
-> plugins: ['react-native-reanimated/plugin'],
-> cd ios && pod install
but did not work then I have removed the app and rebuild and restart the metro but still having this issue.
 ERROR  Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?
 
 

### Actual behavior & steps to reproduce
import Animated from 'react-native-reanimated';
I am having this issue for ios 
## Package versions
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-reanimated": "^2.3.1",

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by yaoz0816** [comment]
I have the same problem
iOS && Android
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-reanimated": "^2.3.0",

**Comment by tomekzaw** [comment]
You may need to reset your cache with `yarn react-native start --reset-cache`.

**Comment by Justin9606** [comment]
> You may need to reset your cache with `yarn react-native start --reset-cache`.

Hi @tomekzaw thank you for the suggestion but I have done reset the cache and  I even close the VSC. XCode and simulator and start new but the same issue

**Comment by Ritesh175862** [comment]
If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports'
Solution:
In babel.config.js,
module.exports = {
presets: ['module:metro-react-native-babel-preset'],
plugins: ['react-native-reanimated/plugin'],
};
(The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .

**Comment by Justin9606** [comment]
> If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .

Thank you @Ritesh175862 

It worked once I reset my Laptop

**Comment by phamhieu1412** [comment]
> If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .

yes, work for me, RN 0.63.4, react 16.13.1, react-native-reanimated 2.2.4

**Comment by lijiaxinghaha** [comment]
> 我有同样的问题 iOS && Android "react": "17.0.2", "react-native": "0.66.4", "react-native-reanimated": "^2.3.0",

你好 你这个问题得到解决了吗 上面说的 --reset-cache 我都试过了 还是不行

**Comment by Yvan2Ero** [comment]
> If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .

It doesn't work when using **react-native-0.67.3**, **typescript-^4.4.4** and **react-native-reanimated-^2.4.1**, please need help.

**Comment by shivampandey191** [comment]
> > If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .
> 
> It doesn't work when using **react-native-0.67.3**, **typescript-^4.4.4** and **react-native-reanimated-^2.4.1**, please need help.

i had the same issue , then i just follow this steps 
1- setup reanimated in mainapplication.java file , enable hermes and bable.config according to official site
2- run command -> cd android and ./gradlew clean
3- cd..
4- npx react-native start --reset-cache
if this dont work then close node , vs code and emulator and follow the steps from step number 2 again

**Comment by allemanfredi** [comment]
> > If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .
> 
> Thank you @Ritesh175862
> 
> It worked once I reset my Laptop

same on my side!

**Comment by mariovillamizar** [comment]
> > > If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .
> > 
> > 
> > Thank you @Ritesh175862
> > It worked once I reset my Laptop
> 
> same on my side!

Same for me!

**Comment by biplovappservinc** [comment]
> > If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .
> 
> Thank you @Ritesh175862
> 
> It worked once I reset my Laptop

this is not the solution

**Comment by biplovappservinc** [comment]
Please have a look on the solution [Link](https://stackoverflow.com/a/72004286/8526684)

**Comment by mikemcguire** [comment]
I kept overlooking this in the other comments, boiling it down for simplicity/others who refuse to read the other comments in detail. 
Check both `.babelrc` and `babel.config.*`  I kept adding to `babel.config.js` and forgot we were using `.babelrc`

**Comment by muneebejazz** [comment]
for expo you just need 
expo start --clear

**Comment by BhoomikaGangadhar** [comment]
Hello 
I have the same problem
 Android
"react": "17.0.2",
  "react-native": "0.68.2",
"react-native-reanimated": "^2.8.0",

Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by adiakritos** [comment]
> You may need to reset your cache with `yarn react-native start --reset-cache`.

I was getting this error on a fresh install of RN that uses expo.

```
    "expo": "~45.0.0",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-reanimated": "~2.8.0"

```

Using `yarn cache clean` I assumed would work. But it didn't, so I assumed this one wouldn't work either. But it did.

When it loaded metro without Expo, it provided one line: 

`warning: the transform cache was reset.`

So the problem in my case has something to do with caching for the bundler metro, and not with yarn.

I tested it in my existing project for which I was troubleshooting and it seems to have corrected the problem.

Thank you.

**Comment by omerenma** [comment]
I was able to fix this error by refactoring the babel.config.js code from  
this
 module.exports = function (api) {
 	api.cache(true);
 	return {
 		presets: ["babel-preset-expo"],
 		plugins: ["react-native-reanimated/plugin"],
 	};
 };

to module.exports = {
	presets: ["babel-preset-expo"],
	plugins: ["react-native-reanimated/plugin"],
};
and it worked

**Comment by BhoomikaGangadhar** [comment]
> I was able to fix this error by refactoring the babel.config.js code from this module.exports = function (api) { api.cache(true); return { presets: ["babel-preset-expo"], plugins: ["react-native-reanimated/plugin"], }; };
> 
> to module.exports = { presets: ["babel-preset-expo"], plugins: ["react-native-reanimated/plugin"], }; and it worked

Thank you for the replay
already tried same method to solve the issues but no use still facing the same problem.

**Comment by heroshinn** [comment]
> yarn react-native start --reset-cache

Thanks buddy Worked for me.
What I Did:
1. updated the babel.config.js as described by @Ritesh175862 
2. run > yarn react-native start --reset-cache
3. cd to android and  run ./gradlew clean
4.  run > yarn android

**Comment by heroshinn** [comment]
> If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .

Thanks buddy Worked for me.
What I Did:

updated the babel.config.js as described by @Ritesh175862
run > yarn react-native start --reset-cache
cd to android and run ./gradlew clean
run > yarn android

**Comment by heroshinn** [comment]
> If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .

Thanks buddy Worked for me.
What I Did:

1. updated the babel.config.js as described by @Ritesh175862
2. run > yarn react-native start --reset-cache
3. cd to android and run ./gradlew clean
4. run > yarn android

**Comment by parmodkuma** [comment]
> If you ever chance upon this error, fret not. Pop over to babel.config.js, simply add 'react-native-reanimated/plugin' under “plugins” in'module.exports' Solution: In babel.config.js, module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], }; (The above is a basic example to recreate the error and solution. Your babel.config.js might be different. As long as the 'react-native-reanimated/plugin' is added correctly, the error should be resolved after restarting the development server and running npx react-native start --reset-cache .

thanks
