### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeReanimated.Layout.springify')

### ISSUE THREAD

**Issue by da45** [software-mansion/react-native-reanimated#2778]
Hi
I am using 
 "expo": "~43.0.2",
"react-native": "0.64.3",

I followed Reanimated installation instructions as required , but got the following error when calling any Layout Animation
TypeError: undefined is not an object (evaluating '_reactNativeReanimated.Layout.springify')

any help please

**Comment by RichardLindhout** [comment]
upgrade expo

**Comment by da45** [comment]
> upgrade expo

No, it doesn't work even with expo upgrade, I followed exactly the installation manual as required,

**Comment by da45** [comment]
Thank you @RichardLindhout  it works fine now, my SDK was outdated
