### ISSUE TITLE
couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found:

### ISSUE THREAD

**Issue by vinaysgl** [software-mansion/react-native-reanimated#2783]
Getting this error while writing
 @Override
        protected JSIModulePackage getJSIModulePackage() {
          return new ReanimatedJSIModulePackage(); // <- add
        }
in main application.java
## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Sorry, but I don't understand your problem, could you prepare a repo to reproduce your problem and describe what is the issue or paste some logs here?
