### ISSUE TITLE
Requiring module "node_modules/react-native-reanimated/src/Animated.js", which threw an exception: TypeError: undefined is not an object 

### ISSUE THREAD

**Issue by MrGautamojha** [software-mansion/react-native-reanimated#2789]
Getting such error in node terminal

<img width="1180" alt="Screenshot 2021-12-27 at 4 03 50 PM" src="https://user-images.githubusercontent.com/47115026/147463343-56108edb-11ea-45e4-b2ca-be4257f9427a.png">

React-native --0.65
"react-native-reanimated": "^2.3.1",
 "react-native-gesture-handler": "^2.1.0",

**Comment by piaskowyk** [comment]
This looks like a cache problem, could you create all cache in your application (`yarn start --reset-cache`)? But if it doesn't help, would you prepare an example repo to produce your issue?

**Comment by anasalaqeel** [comment]
I got the same error after expo updating

**Comment by MrGautamojha** [comment]
> This looks like a cache problem, could you create all cache in your application (`yarn start --reset-cache`)? But if it doesn't help, would you prepare an example repo to produce your issue?

not worked for me.

**Comment by piaskowyk** [comment]
Really, I want to help, but if anyone won't provide a reproduction I'm not able to fix it :/

**Comment by lewisMachilika** [comment]
Make sure your **babel.config.js** looks like below
```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
``` 
Once that is done the run **expo r -c** to clear the cache

**Comment by masnoonmulla** [comment]
@MrGautamojha did you find any solution for this? I am also facing the same error.

**Comment by Riadh-Mkhinini** [comment]
i have the same issue

**Comment by MrGautamojha** [comment]
> @MrGautamojha did you find any solution for this? I am also facing the same error.


Downgrade NPM  version fixed this issue for now

"react-native-gesture-handler": "1.10.3",
    "react-native-reanimated": "1.9.0",

**Comment by benrbowers** [comment]
It looks like there is now an expo command to fix the version number issue:
`expo doctor --fix-dependencies`

Also make sure you clear cache again as suggested above
