### ISSUE TITLE
isAnimated api

### ISSUE THREAD

**Issue by vaukalak** [software-mansion/react-native-reanimated#279]
There would be awesome to have an API, that just allows to understand if a value is a reanimated node, just like `Array.isArray`, we could use:
```
const { isAnimated } = Animated;

isAnimated(valueOrNode);
```

**Comment by jakub-gonet** [comment]
Hi,
sorry for the late response 😔

I think adding `isAnimated` function wouldn't give us many benefits, I don't see any use cases for that.
But if you need that you can try using [instanceof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) for determining if the given object is an instance of AnimatedNode or AnimatedValue.

Hope it resolves your issue, feel free to ask further questions.
