### ISSUE TITLE
Reanimated module is not initialized when a class that implements the RCTBridgeDelegate Protocol is used

### ISSUE THREAD

**Issue by dov11** [software-mansion/react-native-reanimated#2791]
## Description
Reanimated module is not initialized when a class that implements the `RCTBridgeDelegate` Protocol is used (e.g. when [dependency injections](https://reactnative.dev/docs/native-modules-ios#dependency-injection) are needed/brownfield apps). App throws `undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')`

When a class that implements the RCTBridgeDelegate Protocol is used, [jsExecutorFactoryForBridge](https://github.com/software-mansion/react-native-reanimated/blob/cec101716d5690f51187c0f739b3ea3e7080440e/ios/native/UIResponder%2BReanimated.mm#L19) in UIResponder+Reanimated.mm is never called.

My understanding is this happens because this condition
```
    if ([self.delegate conformsToProtocol:@protocol(RCTCxxBridgeDelegate)]) {
```
[in RCTCxxBridge.mm](https://github.com/facebook/react-native/blob/725bffce51282d649b7e071873eec76c379b1ede/React/CxxBridge/RCTCxxBridge.mm#L465) is not satisfied and `[cxxDelegate jsExecutorFactoryForBridge:self]` is not called [here](https://github.com/facebook/react-native/blob/725bffce51282d649b7e071873eec76c379b1ede/React/CxxBridge/RCTCxxBridge.mm#L467).

### Expected behavior

Reanimated module is initialized.

### Actual behavior & steps to reproduce

Module is not initialized and App crashes with `undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')`. Please see link to the fork of reanimated 2 playground below to reporoduce

## Snack or minimal code example
[fork of reanimated 2 playground that demonstrates the issue](https://github.com/dov11/reanimated-2-playground/tree/delegate_bridge) (branch name `delegate_bridge`)

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.1 (also tested on 2.3.1, 2.2.4)
- NodeJS: 14.18.0
- Xcode: 13.1
- Java & Gradle: not relevant

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by dov11** [comment]
The module will autoinstall if the class that implements the RCTBridgeDelegate Protocol is a subclass of UIResponder. 
E.g. in the example fork above:
```
ClassThatImplementsRCTBridgeDelegate : UIResponder
```

Alternatively, Reanimated can be patched with `patch-package`:
```
diff --git a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h
index 3ee3797..0805b0d 100644
--- a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h
+++ b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h
@@ -3,7 +3,7 @@
 
 #ifndef DONT_AUTOINSTALL_REANIMATED
 
-@interface UIResponder (Reanimated) <RCTCxxBridgeDelegate>
+@interface NSObject (Reanimated) <RCTCxxBridgeDelegate>
 
 @end
 
diff --git a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm
index 28c9262..a815e12 100644
--- a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm
+++ b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm
@@ -15,7 +15,7 @@
 
 #ifndef DONT_AUTOINSTALL_REANIMATED
 
-@implementation UIResponder (Reanimated)
+@implementation NSObject (Reanimated)
 - (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
 {
   const auto installer = reanimated::REAJSIExecutorRuntimeInstaller(bridge, NULL);
```

**Comment by MichaelDanielTom** [comment]
Was this closed because there was a fix somewhere? I feel like this is still an issue, and having the delegate be a subclass of UIResponder shouldn't be required.

For me at least this was the root cause of https://github.com/software-mansion/react-native-reanimated/issues/2525 in our brownfield app. Also @dov11 great find!

**Comment by adrianha** [comment]
> The module will autoinstall if the class that implements the RCTBridgeDelegate Protocol is a subclass of UIResponder. E.g. in the example fork above:
> 
> ```
> ClassThatImplementsRCTBridgeDelegate : UIResponder
> ```
> 
> Alternatively, Reanimated can be patched with `patch-package`:
> 
> ```
> diff --git a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h
> index 3ee3797..0805b0d 100644
> --- a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h
> +++ b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.h
> @@ -3,7 +3,7 @@
>  
>  #ifndef DONT_AUTOINSTALL_REANIMATED
>  
> -@interface UIResponder (Reanimated) <RCTCxxBridgeDelegate>
> +@interface NSObject (Reanimated) <RCTCxxBridgeDelegate>
>  
>  @end
>  
> diff --git a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm
> index 28c9262..a815e12 100644
> --- a/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm
> +++ b/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm
> @@ -15,7 +15,7 @@
>  
>  #ifndef DONT_AUTOINSTALL_REANIMATED
>  
> -@implementation UIResponder (Reanimated)
> +@implementation NSObject (Reanimated)
>  - (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
>  {
>    const auto installer = reanimated::REAJSIExecutorRuntimeInstaller(bridge, NULL);
> ```

this patch also works on my case (brownfield app). do you think there'll be side effect when applying this patch? cc @tomekzaw

**Comment by tomekzaw** [comment]
Hey @adrianha, thanks for the patch. I remember there was some reason why `UIResponder` was chosen over `NSObject`, but unfortunately I don't remember the details. I will let you know soon.

**Comment by adrianha** [comment]
just created new repo to repro (init with RN 0.69 + Reanimated 2.9.1) this issue:
- [main](https://github.com/adrianha/reanimated69/tree/main): `bridge` initiated in `AppDelegate` –> Reanimated works fine
- [custom-bridge](https://github.com/adrianha/reanimated69/tree/custom-bridge): `bridge` initiated outside of `AppDelegate` –> throws `TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions')`

**Comment by hmarques98** [comment]
> just created new repo (init with RN 0.69 + Reanimated 2.9.1) to repro this issue:
> 
> * [main](https://github.com/adrianha/reanimated69/tree/main): `bridge` initiated in `AppDelegate` –> Reanimated works fine
> * [custom-bridge](https://github.com/adrianha/reanimated69/tree/custom-bridge): `bridge` initiated outside of `AppDelegate` –> throws `TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions')`

The same issue here

**Comment by meberl-detego** [comment]
> just created new repo (init with RN 0.69 + Reanimated 2.9.1) to repro this issue:
> 
>     * [main](https://github.com/adrianha/reanimated69/tree/main): `bridge` initiated in `AppDelegate` –> Reanimated works fine
> 
>     * [custom-bridge](https://github.com/adrianha/reanimated69/tree/custom-bridge): `bridge` initiated outside of `AppDelegate` –> throws `TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions')`

In our case we had to use UIResponder instead of NSObject for our ReactNativeBridge

**Comment by mununki** [comment]
```
react-native: 0.71.3
react-native-reanimated: 2.9.1
```
```
├─┬ @gorhom/bottom-sheet@4.4.5
│ └── react-native-reanimated@2.9.1 deduped
├─┬ @react-navigation/drawer@6.6.0
│ └── react-native-reanimated@2.9.1 deduped
├─┬ react-native-reanimated-carousel@3.3.0
│ └── react-native-reanimated@2.9.1 deduped
└── react-native-reanimated@2.9.1
```
```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  id<RCTBridgeDelegate> moduleInitializer = [[BrazeReactBridge alloc] init];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:moduleInitializer
                                            launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"smartfarm"
                                            initialProperties:nil];
  self.bridge = rootView.bridge;

  // Configure views in the application
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  ...
}
```
I've tried to patch-package to change the UIResponder to NSObject, but still same error occurred. Any clue to fix this?

**Comment by alzalabany** [comment]
i'm having same issue on 0.71.3

**Comment by guilherme-vp** [comment]
> I've tried to patch-package to change the UIResponder to NSObject, but still same error occurred. Any clue to fix this? The installation guide is all checked: babel plugin, --reset-cache, remove node_modules, pod install, etc.
> 
> ```
> react-native: 0.71.3
> react-native-reanimated: 2.9.1
> ```
> 
> ```
> ├─┬ @gorhom/bottom-sheet@4.4.5
> │ └── react-native-reanimated@2.9.1 deduped
> ├─┬ @react-navigation/drawer@6.6.0
> │ └── react-native-reanimated@2.9.1 deduped
> ├─┬ react-native-reanimated-carousel@3.3.0
> │ └── react-native-reanimated@2.9.1 deduped
> └── react-native-reanimated@2.9.1
> ```
> 
> ```objc
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   id<RCTBridgeDelegate> moduleInitializer = [[BrazeReactBridge alloc] init];
>   RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:moduleInitializer
>                                             launchOptions:launchOptions];
>   RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
>                                                    moduleName:@"smartfarm"
>                                             initialProperties:nil];
>   self.bridge = rootView.bridge;
> 
>   // Configure views in the application
>   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
>   UIViewController *rootViewController = [UIViewController new];
>   rootViewController.view = rootView;
>   self.window.rootViewController = rootViewController;
>   [self.window makeKeyAndVisible];
>   ...
> }
> ```
> 
> ```
> 2023-03-01 16:58:12.694428+0900 smartfarm[12643:2375820] Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x11bf18f10>.
> 2023-03-01 16:58:12.694470+0900 smartfarm[12643:2376076] [I] <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
> 2023-03-01 16:58:12.710983+0900 smartfarm[12643:2376076] [javascript] TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes
> 2023-03-01 16:58:12.714608+0900 smartfarm[12643:2376076] [javascript] Running "smartfarm
> 2023-03-01 16:58:12.714737+0900 smartfarm[12643:2376076] [javascript] Invariant Violation: "smartfarm" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
> ```

I'm having the same issue with Braze bridge <> React Native Reanimated, I've tried applying the changes that Braze docs recommend (using JS Bundle instead), but doesn't work either. Applying the patch didn't work for me. 
@mununki, were you able to fix it?

**Comment by mununki** [comment]
@guilherme-vp Here is my implementation with v0.71
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    self.moduleName = @"smartfarm";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};
  [super application:application didFinishLaunchingWithOptions:launchOptions];


  BRZConfiguration *configuration = [[BRZConfiguration alloc] initWithApiKey:apiKey endpoint:brazeEndpoint];
  // configuration.triggerMinimumTimeInterval = 1;  // 기본값 30
  configuration.logger.level = BRZLoggerLevelInfo;
  Braze *braze = [BrazeReactBridge initBraze:configuration];
  AppDelegate.braze = braze;
  ...
  UIView *rootView = self.window.rootViewController.view;

  return yes;
}
```
NSObject, I still had issues with Reanimated when using the official Braze example and guide. I've seen Braze init fine without initializer when using the code above.
