### ISSUE TITLE
Error: Requiring module "node_modules\react-native-reanimated\src\Animated.js", which threw an exception: Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

### ISSUE THREAD

**Issue by lewisMachilika** [software-mansion/react-native-reanimated#2793]
## Description
I am trying to use createDrawerNavigator from import { createDrawerNavigator } from '@react-navigation/drawer'; in react native. However, I am getting the error above

### Expected behavior
The expected behavior is to work as described in the documentation however on the ground it is different.
### Actual behavior & steps to reproduce
Add **import 'react-native-gesture-handler';** at the top of my **App.js**
In **babel.config.js** add **reanimated/plugin** as below
```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: [
      'babel-preset-expo',
      'module:metro-react-native-babel-preset'
    ],
    plugins: [
      'react-native-reanimated/plugin',
    ]
  };
};

```
## Snack or minimal code example

Below is my *Drawer.js* file
```
import * as React from 'react';
import { Button, View } from 'react-native';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { NavigationContainer } from '@react-navigation/native';

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button
        onPress={() => navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    </View>
  );
}

function NotificationsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button onPress={() => navigation.goBack()} title="Go back home" />
    </View>
  );
}

const Drawer = createDrawerNavigator();

export default function MyDrawer() {
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Notifications" component={NotificationsScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
}
``` 

## Package versions

- React Native:
- React Native Reanimated:

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by patrickdunagan** [comment]
Same issue, following.

**Comment by lewisMachilika** [comment]
If you can check 

> I had the same issue. Found this on Expo.
> 
> https://docs.expo.dev/versions/latest/sdk/reanimated/#installation
> 
> add the plugins line to your babel.config.js
> 
> module.exports = function (api) { api.cache(true) return { presets: ['babel-preset-expo'], plugins: ['react-native-reanimated/plugin'], } }

I have already added that code but its still not working

**Comment by kosick** [comment]
When I was trying to upgrade reanimated module 2.1.3 to 2.3.0, I got the similar issue.
I found solutions in below link. 
In short I added '@babel/preset-env' '@babel/preset-typescript' dev dependencies to my project.

[gesture handler issue](https://github.com/software-mansion/react-native-gesture-handler/issues/1765#issuecomment-999256242)

**Comment by ammarahm-ed** [comment]
@lewisMachilika Try to reset metro bundler cache. `yarn start --reset-cache`.

**Comment by piaskowyk** [comment]
Did you try to clear cache according to @ammarahm-ed 's suggestions? `yarn start --reset-cache` 
It looks like a cache issue.

**Comment by lewisMachilika** [comment]
> @lewisMachilika Try to reset metro bundler cache. `yarn start --reset-cache`.

it worked through **expo r -c**

**Comment by lewisMachilika** [comment]
Run **expo r -c** After adding below code to **babel.config.js** 

module.exports = function (api) {
api.cache(true)
return {
presets: ['babel-preset-expo'],
plugins: ['react-native-reanimated/plugin'],
}
}

**Comment by piaskowyk** [comment]
@lewisMachilika thanks for the update!

**Comment by IsPriamo** [comment]
> Run **expo r -c** After adding below code to **babel.config.js**
> 
> module.exports = function (api) { api.cache(true) return { presets: ['babel-preset-expo'], plugins: ['react-native-reanimated/plugin'], } }

It doesn't work for me, I even add something to the babel file and it exits the expo unexpectedly.

**Comment by mohitz007** [comment]
> 

just add the plugins line rest of function will be already present

**Comment by mohitz007** [comment]
> > Run **expo r -c** After adding below code to **babel.config.js**
> > module.exports = function (api) { api.cache(true) return { presets: ['babel-preset-expo'], plugins: ['react-native-reanimated/plugin'], } }
> 
> It doesn't work for me, I even add something to the babel file and it exits the expo unexpectedly.

just add the plugins line rest of function will be already present

**Comment by Jevgeni-i-am** [comment]
Got fixed my issue with this topics information. Thanx a lot!

**Comment by matteocollina** [comment]
After edited the babel.config.js file, try with:
`expo start --clear`
It works for me

**Comment by mohanrajmurugasen** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/2793#issuecomment-1003296834

using this steps work for me

**Comment by saqibkafeel** [comment]
why this major issue is closed ? this issue still exist, wasting time on this bug from last one week

**Comment by mohitjson** [comment]
> 

Thanku so much it worked

**Comment by saqibkafeel** [comment]
> > 
> 
> Thanku so much it worked

please post the solution

**Comment by mohitjson** [comment]
> > > 
> > 
> > 
> > Thanku so much it worked
> 
> please post the solution

problem is in react reanimated dependency which is used by drawer navigator and expo stored tat file so we have to reset expo cache and add plugin to babel.config which by default not installed while intalling dependencies

**Comment by maxhudson** [comment]
expo r -c

**Comment by dilane3** [comment]
> Run **expo r -c** After adding below code to **babel.config.js**
> 
> module.exports = function (api) { api.cache(true) return { presets: ['babel-preset-expo'], plugins: ['react-native-reanimated/plugin'], } }

Thank you so much @lewisMachilika

**Comment by Pat-Gekoski** [comment]
I created a brand new expo project.......none of these solutions worked for me 😣

**Comment by PeterAbdalla** [comment]
Still an issue using SDK 45

**Comment by mohashamoon** [comment]
Having the same issue here, using SDK 45 and can't fix it :(

**Comment by saerdyey** [comment]
I had this problem using SDK 44 and tried following steps I found online, nothing works. But then I solved it with this steps:

I just followed the documentation here [https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/](url)

after following that I run **expo doctor --fix-dependencies** to fix the compatibility.

I didn't run **expo r -c**, but you might also need run it.

**Comment by teifler** [comment]
I have the same issue with expo. I want to start the debug mode:
Android Bundling complete 2372ms
Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4 from C:\Users\U766244\WebstormProjects\app/.:

None of these files exist:
  * debugger-ui\debuggerWorker.aca173c4(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
  * debugger-ui\debuggerWorker.aca173c4\index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)

**Comment by teifler** [comment]
I found a solution, which fixed the issue in my case:


This is temporary fix. This is working perfectly on my side. you have to edit this file

node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js

```
callNativeSyncHook(
    moduleID: number,
    methodID: number,
    params: any[],
    onFail: ?Function,
    onSucc: ?Function,
  ): any {
    const isDebuggingEnabled = (typeof atob !== 'undefined');
    this.processCallbacks(moduleID, methodID, params, onFail, onSucc);
    if(!isDebuggingEnabled)
    {
      return global.nativeCallSyncHook(moduleID, methodID, params);
    }
  }

```

**Comment by rohitthakre** [comment]
> 

Its working thanks plugins: ['react-native-reanimated/plugin'],

**Comment by nabtron** [comment]
run using this command: npx react-native start --reset-cache

also make sure your code is similar to: files shown here: https://socalledhacker.com/react-native-drawer-navigation-without-any-errors/
