### ISSUE TITLE
Can't get Layout Animations to work on a simple View

### ISSUE THREAD

**Issue by ernestasgobionis** [software-mansion/react-native-reanimated#2800]
## Description

Not sure if it's a bug in the library, or if I'm missing something in the setup, but I can't get Layout Animations to work in any way, none of the stages seem to be working (entering, exiting, layout). I have a simple view that I'm trying to animate when toggling a state variable, but it just appears without any animations at all.

### Expected behavior

Expected the view to fade in and out when mounting/unmounting.

### Actual behavior & steps to reproduce

No animations are working in either stage.

## Snack or minimal code example

```
{showView && <Animated.View
       style={[styles.ball, animatedStyles]}
       entering={FadeIn.duration(2000).springify().mass(0.3)}
       exiting={FadeOut.duration(2000).springify().mass(0.3)}
/>}
```

## Package versions

- React Native: 0.66.0
- React Native Reanimated: 2.3.1 / https://github.com/software-mansion/react-native-reanimated#main (tried with both)
- NodeJS: 16.1.0
- Xcode: 13.2.1

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by Majiedo** [comment]
You seems using the useAnimatedStyle with component, 

`{showView && <Animated.View style={styles.ball} entering={FadeIn.duration(2000).springify().mass(0.3)} exiting={FadeOut.duration(2000).springify().mass(0.3)} />}`

**Comment by ernestasgobionis** [comment]
@Majiedo oh sorry, I forgot to mention that I tried it both ways actually, with and without the animated styles, and I still got the same outcome.

**Comment by Flam3rboy** [comment]
same, I've just setup the LayoutAnimation example, but the entering and exiting animation doesn't work.

**Comment by muraterd** [comment]
+1
I have the same problem.

**Comment by kkafar** [comment]
Hey @ernestasgobionis!

I encourage you to check out how it's done in the [Example app](https://github.com/software-mansion/react-native-reanimated/blob/2c489378fc0b4e1a92ed87102fa3f79f36710e27/Example/src/LayoutReanimation/DefaultAnimations.tsx#L97-L542)

If it won't help, it would really help us if you provided Snack code example

**Comment by ernestasgobionis** [comment]
Hi @kkafar,

I think I have checked the Example app before and everything was working fine there, and as far as I remember I basically copied one of the examples and it didn't work.

But now I tried to reproduce it, and it seems to work now (magic 😀). Unless I was doing something different when submitting this issue, but I think it was an even simpler case that I used to reproduce it now.

**Comment by kkafar** [comment]
Sometimes it this way! :D Glad to hear its working for you. Closing.
