### ISSUE TITLE
MyApplication class cannot be cast to com.facebook.react.ReactApplication

### ISSUE THREAD

**Issue by rishabh876** [software-mansion/react-native-reanimated#2801]
I am currently working on upgrading RN version of my project from 0.61.5 to 0.63.4. In parallel I am also upgrading reanimated v1.13.2 to v2.3.1. 
Now the problem is that I don't have ReactApplication. I build ReactInstanceManager in my activity.

## Description
After upgrading I get the following error on app launch 

> com.example.MyApplication class cannot be cast to com.facebook.react.ReactApplication
> createUiManager (ReanimatedPackage.java : 70)

### Expected behavior
No crash on app start.

### Actual behavior & steps to reproduce
Steps: Upgrading from v1 to v2 without any ReactApplication.

## Snack or minimal code example

```
// onCreate of my activity
        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                                                    .setApplication(getApplication())
                                                    .setCurrentActivity(this)
                                                    .setBundleAssetName("index.android.bundle")
                                                    .setJSMainModulePath("index")
                                                    .setJSIModulesPackage((reactApplicationContext, jsContext) -> {
                                                        return new ReanimatedJSIModulePackage().getJSIModules(reactApplicationContext, jsContext);
                                                    })
                                                    .addPackage(new LinearGradientPackage())
                                                    .addPackage(new ImagePickerPackage())
                                                    .addPackage(new ImageResizerPackage())
                                                    .addPackage(new SvgPackage())
                                                    .addPackage(new FastImageViewPackage())
                                                    .addPackage(new NetInfoPackage())
                                                    .addPackage(new LottiePackage())
                                                    .addPackage(new RNPermissionsPackage())
                                                    .addPackage(new RNGestureHandlerPackage())
                                                    .addPackage(new BackgroundTimerPackage())
                                                    .addPackage(new RNCWebViewPackage())
                                                    .addPackage(new ReanimatedPackage())
                                                    .setUseDeveloperSupport(BuildConfig.DEBUG)
                                                    .setInitialLifecycleState(LifecycleState.RESUMED)
                                                    .build();

        Bundle initialProps = getInitProps();
        mReactRootView.startReactApplication(mReactInstanceManager, "example", initialProps);
        setContentView(mReactRootView);
```

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.3.1
- NodeJS: v14.5.0
- Xcode: 
- Java & Gradle: 3.5.3

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by WFolini** [comment]
I am facing the same issue, and I created this issue #2719. I put some findings there. 
I believe that this issue is a blocker for android apps that uses `ReactInstanceManager` for building the React Native activity.
I was not able to find any workaround to make it work.

**Comment by jkadamczyk** [comment]
Hi @WFolini @rishabh876 
If I understand the issue correctly. You have an app that is a native app, that uses React Native in parts of the app.
If you have any more context to provide I will be very grateful if you added it to this issue.
Thank you for reporting and have a nice day!

**Comment by jkadamczyk** [comment]
@WFolini @rishabh876 BTW if you could create a small app with just reanimated and refactored so that it is not using ReactApplication, that would be great

**Comment by jakub-gonet** [comment]
This is very similar to #2719.

**Comment by WFolini** [comment]
@jkadamczyk In my case, it is as you mentioned. Is an android project that has different android apps where they share this custom React Native activity. 
I have created a small dummy android project with a custom React Native activity where you can reproduce the issue. You can check it in #2719. Also, I create the PR https://github.com/software-mansion/react-native-reanimated/pull/2863. 
Let me know if I can help with something else.

**Comment by iamarjun** [comment]
Facing the same exact issue

**Comment by Rakiah** [comment]
any update on this ?
This is quite a blocker

**Comment by WFolini** [comment]
Hey guys, I left a comment about how to solve this issue here below. Hope it helps
https://github.com/software-mansion/react-native-reanimated/issues/2719#issuecomment-1462077819

**Comment by Latropos** [comment]
I confirm that above-mentioned solution works. Also this issue is duplicating the problem described in https://github.com/software-mansion/react-native-reanimated/issues/2710
