### ISSUE TITLE
Problems with babel-plugin-istanbul

### ISSUE THREAD

**Issue by LeoRedin** [software-mansion/react-native-reanimated#2804]
## Description

I am trying to instrument my code using ```babel-plugin-istanbul``` but whenever I add that to my plugins list I get always the same error saying that I tried to call function { } from a different thread.

### Expected behavior

I expect the animations to work with the instrumentation that babel produces.

### Actual behavior & steps to reproduce

The app does not even start and if you clone the repo and try to run it you'll face the issue.

## Snack or minimal code example

I've created [this](https://github.com/LeoRedin/reanimated-istanbul) repo to reproduce the error.

## Package versions

- React Native: 0.66.4
- React Native Reanimated: ^2.3.1
- NodeJS: v14.16.1
- Xcode: 13.1 (13A1030d)

## Affected platforms

- [x] Android (I marked but I haven't tested, the problem should persist)
- [x] iOS
- [ ] Web

**Comment by Latropos** [comment]
Close due to inactivity
