### ISSUE TITLE
Reanimated does not work in mixed development of ios and react native

### ISSUE THREAD

**Issue by lzl5771060** [software-mansion/react-native-reanimated#2805]
## Description
In ios, I use viewDidLoad to load react native, and reanimated does not work properly

I got this error in version 2.0.0-2.2.4
![截屏2022-01-05 上午10 25 28](https://user-images.githubusercontent.com/75652584/148150888-0c61b018-6f9f-423d-9eef-9b7233982f55.png)

## Snack or minimal code example

`#import <Foundation/Foundation.h>
#import "RnViewController.h"
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
@implementation RnViewController

- (void)viewDidLoad {

  [super viewDidLoad];

  NSURL *jsCodeLocation;
  #if DEBUG
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  #else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  #endif

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName:@"MyRn" initialProperties:nil launchOptions:nil];

  self.view = rootView;
  
}

@end
`

## Package versions

- React Native: 0.64.3
- React Native Reanimated: 2.2.0
- NodeJS: 16.13.1
- Xcode: 1.11.2
- Java & Gradle: 

## Affected platforms

- [ ] Android
- [ yes] iOS
- [ ] Web

**Comment by lzl5771060** [comment]
Do you use viewDidLaod to load reanimated2 in a certain page of ios, can it work normally, or are there other ways to load it?
2.3.0-2.3.1 also does not work.

**Comment by piaskowyk** [comment]
Same issue but on Android: https://github.com/software-mansion/react-native-reanimated/issues/2801

**Comment by AlexHashgraph** [comment]
i have the exact same issue, tried all versions starting with 2.0

**Comment by AlexHashgraph** [comment]
it's happening when trying to integrate native modules with RN and when that rn uses reanimated ; had same issue on android until I added:
ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSIModulesPackage(new ReanimatedJSIModulePackage());

when using RCTBridge on ios however, can't seem to find anything to get it to work
