### ISSUE TITLE
Test new bot

### ISSUE THREAD

**Issue by piaskowyk** [software-mansion/react-native-reanimated#2808]
## Description

test 123

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      5   |
| react-native-reanimated              |    5     |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by kacperkapusciak** [comment]
Here this is my repro: https://snack.expo.dev/@kacperkapusciak/react-navigation-example
