### ISSUE TITLE
react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)

### ISSUE THREAD

**Issue by dguard** [software-mansion/react-native-reanimated#2813]
## Description

react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
![image](https://user-images.githubusercontent.com/1911516/148517709-91f3be52-5f29-433f-b843-48f82b8e5cca.png)

### Actual behavior & steps to reproduce
1. cd Example
2. npm run start
3. react-native run android

## Snack or minimal code example
```
cd /var/www
git clone https://github.com/software-mansion/react-native-reanimated
cd react-native-reanimated
cd Example
yarn
npx react-native run-android
```
## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.67.0-rc.4|
| react-native-reanimated              |^2.3.1|
| NodeJS                               |v12.20.0|
| Java                                 |openjdk 11.0.13 2021-10-19|
| Gradle                               | 7.2 |
| expo                                 | Metro |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by dguard** [comment]
There was issue with parent module.
Go to parent module of `Example/` 
```cd /var/www/react-native-reanimated``` 

and install deps in parent module 
```yarn```


Also I meet with issue with NDK. In my NDK path `/home/${USER}/Android/Sdk/ndk` I had empty directory with NDK 21.4.7075529

And I installed NDK using Android Studio
![image](https://user-images.githubusercontent.com/1911516/148523826-d52dd373-5265-4d50-b476-a0af75525a32.png)

And I did for installed 23.1.7779620 version:
```
cd /home/${USER}/Android/Sdk/ndk
rm -rf 21.4.7075529
ln -s 23.1.7779620 21.4.7075529
```

**Comment by kacperkapusciak** [comment]
Hi @dguard,
To run the Example app you also need to run `yarn` in the `react-native-reanimated` directory because it uses some of the gradle tasks directly from the root folder. 

```
git clone https://github.com/software-mansion/react-native-reanimated
cd react-native-reanimated
yarn
cd Example
yarn
yarn start
# in new terminal instance
npx react-native run-android
```

Cheers

**Comment by dguard** [comment]
@kacperkapusciak 
yep, may be add these details to
```
https://github.com/software-mansion/react-native-reanimated/tree/main/Example
```

Because I thought that this is independent module

**Comment by dguard** [comment]
Thanks
Solved

**Comment by radiorz** [comment]
how to solved? i try to run example app ,but failed
