### ISSUE TITLE
`onActive` of useAnimatedGestureHandler is not working with Android.

### ISSUE THREAD

**Issue by boodong-kwanee** [software-mansion/react-native-reanimated#2822]
## Description

I'm using `useAnimatedGestureHandler` to implement doughnut chart.
With iOS, it's totally working well but with Android, `onStart` of `useAnimatedGestureHandler` is only working.

### Expected behavior
Every feature of `useAnimatedGestureHandler` should work in android.

### Actual behavior & steps to reproduce
Only `onStart` is working.

## Snack or minimal code example
```js
 const panGestureHandler = useAnimatedGestureHandler({
    onStart: ({x, y}) => {
      const x1 = x - (radius + 50);
      const y1 = -(y - (radius + 50));

      let theta = (Math.atan(y1 / x1) * 180) / Math.PI;

      if (x1 >= 0 && y1 >= 0) {
        theta = theta;
      } else if (x1 < 0 && y1 >= 0) {
        theta += 180;
      } else if (x1 < 0 && y1 < 0) {
        theta += 180;
      } else {
        theta += 360;
      }

      if (selectedIndex.value !== null) {
        // selectedIndex.value = null;
      } else {
        currentDegree.value = theta;
      }
    },
    onActive: ({x, y}) => {
      console.log('ON ACTIVE');
    }),
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.66.3|
| react-native-reanimated              |^2.3.0|
| Java                                 |         |
| Gradle                               |         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by Latropos** [comment]
I've tested the problem with the newest reanimated and everything seems to work fine. Probably we have already fixed your bug.
