### ISSUE TITLE
App crashes when using React Native Debugger part 2 

### ISSUE THREAD

**Issue by 29er** [software-mansion/react-native-reanimated#2827]
## Description
app is crashing when running RN debugger. global.performance.now is not a function

### Expected behavior
app doesn't crash

### Actual behavior & steps to reproduce
 just run RN debugger 
## Snack or minimal code example

no code available, it crashes upon any component that uses RNA

## Package versions
2.3.1

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.66.3   |
| react-native-reanimated              | 2.3.1  |
| NodeJS                               |   17.0.1      |
| Xcode                                |   13.2.1      |
| Java                                 |         |
| Gradle                               |         |

## Affected platforms

- [x ] Android
- [x ] iOS
- [ ] Web

if change line 386 from core.ts
```
      global.performance = {
        now: global._chronoNow,
      };
```
to 
```
      if (global.performance == null) {
        global.performance = {
          now: global._chronoNow,
        };
      }
```
it works

**Comment by Hirbod** [comment]
https://docs.swmansion.com/react-native-reanimated/docs/#known-problems-and-limitations

> As the library uses JSI for synchronous native methods access, remote debugging is no longer possible. You can use Flipper for debugging your JS code, however connecting debugger to JS context which runs on the UI thread is not currently supported.

**Comment by LuigiMaestrelli** [comment]
So, are you planning to break the most common debugger method for every app, that is it?

**Comment by Hirbod** [comment]
It's just not possible due to the architecture. You might want to read a bit about TurboModules, JSI, Fabric etc to understand it. Setting up Flipper is a 10 minute task and will give you all the tools you need to debug.

**Comment by 29er** [comment]
wow,  super frustrating as I can't ask an entire dev team to change their debugging approach. noone uses flipper.
oh well thanks anyway !

**Comment by minhchienwikipedia** [comment]
it's fixed but not yet have a new version for it, please find the issue exists or not before creating a new one  https://github.com/software-mansion/react-native-reanimated/pull/2771

**Comment by 29er** [comment]
Thank you!
