### ISSUE TITLE
Increase in JS bundle size after updating from ^1.10.1 to 2.3.1 

### ISSUE THREAD

**Issue by shubhamdeol** [software-mansion/react-native-reanimated#2844]
Can we do something about this. 
This is after analysing the bundle size using 
react-native-bundle-visualizer 

Attaching screenshot for reference
<img width="227" alt="Screenshot 2022-01-15 at 12 00 17 AM" src="https://user-images.githubusercontent.com/11364449/149567533-50818821-38a1-4f3c-b8b8-ad8902b7f2a3.png">
![new](https://user-images.githubusercontent.com/11364449/149567547-80c81484-bf19-478e-aaca-232f5e3bf178.png)

**Comment by piaskowyk** [comment]
Yes, we added a lot of new features since version 1.10.1 and in effect, we have significantly more codes than before. Imo 385KB is not too much. How much size is acceptable for you?

**Comment by shubhamdeol** [comment]
@piaskowyk Our current app size is 12mb for android. Our competitors having app sizes around 9 mb, even though they have advantage of being purely native App. JS bundle size also impacts the startup time. After React Native, Reanimated is second most contributor to bundle size for my app. I think less than 150KB can be acceptable. 

I can see Layout animations are taking nearly half of reanimated size. 

I am not able to use Layout Animations. 
Layout animations does not work well with React Navigations's Native stack, Screens stops detecting header height once I enable Layout animations, But that's another issue may be I should open issue in react-native-screens or React Navigation

**Comment by paldepind** [comment]
I have the same problem. According to react-native-bundle-visualizer Reanimated is the largest of all the dependencies of my project (not counting react-native itself). It would be really great if it could be made smaller and/or more tree-shakeable.

**Comment by Hirbod** [comment]
LayoutAnimation should be opt-in imho

**Comment by grinono** [comment]
We have the same concern, if it's possible to reduce package size that would be great to increase startup time.
