### ISSUE TITLE
Memory leak on android using continues animation

### ISSUE THREAD

**Issue by Daanoz** [software-mansion/react-native-reanimated#2849]
## Description

I've used reanimated combined with react-native-svg to create a live graph, but I notice increasing memory usage when the graph is running for a long while. It might be related to #2824 but I actually mainly observe the behavior on Android. I think I managed to isolate the origin to reanimated; but happy to be proven wrong :). 

### Expected behavior

No increasing memory.

### Actual behavior & steps to reproduce

Some screengrabs from the android profiler (running react-native release bundle)

![image](https://user-images.githubusercontent.com/3742687/149678478-e4f1cf49-7ac4-42bb-b8f4-ba34cad8a90e.png)
![image](https://user-images.githubusercontent.com/3742687/149678482-606cd4c9-91df-4f22-8362-60ccb70acf0d.png)

## Snack or minimal code example

Extracted a snippet of my app in a separate repo:
https://github.com/daanoz/reanimated-live-graph
![image](https://user-images.githubusercontent.com/3742687/149678529-14c2bea8-d0fc-446d-bb5d-8b8431ad039b.png)

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.66.4    |
| react-native-reanimated              |    2.3.1     |
| NodeJS                               |     16    |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by bozkayaSalihX** [comment]
I have the same issue with that sentry always throwing oom error please fix the issue

**Comment by see2ever** [comment]
face the same problem in ios

**Comment by Daanoz** [comment]
> Hey! 👋 
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a snippet of code, a [snack](https://snack.expo.dev/) or a link to a GitHub repository that reproduces the problem?

Yes there is: https://github.com/daanoz/reanimated-live-graph

**Comment by tj-mc** [comment]
Same here. About 2mb leaked for every screen unmount in my case

**Comment by piaskowyk** [comment]
Issue is resolved in Reanimated 3 🎉 I recommend to upgrade to latest 3.+ version.

**Comment by piaskowyk** [comment]
@tj-mc 
> Same here. About 2mb leaked for every screen unmount in my case

You issue comes from `react-native-screens` and the maintainers are working on it.
