### ISSUE TITLE
Animation withCallback, Value is undefined, expected an Object

### ISSUE THREAD

**Issue by fristyr** [software-mansion/react-native-reanimated#2866]
## Description

I need to have a callBack after the animation ends
But when I add withCallback, I have error modal
Value is undefined, expected an Object

```javascript
const animationEnd = SlideOutRight.withCallback((finished: boolean) => {
// other code
});

{!shouldAnimate && (
   <Animated.View entering={SlideInLeft} exiting={animationEnd}>
      <View />
    </Animated.View>
)}
```

### Expected behavior
a callBack after animation ends

### Actual behavior & steps to reproduce
After state changes, animation starts and then error modal if withCallback was selected

![Screenshot 2022-01-21 at 15 42 21](https://user-images.githubusercontent.com/33237937/150548298-e8abf744-6ea4-46e3-9055-65ba94f8fbad.png)

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.64.3     |
| react-native-reanimated              |   ~2.3.1     |
| NodeJS                               |      v14.18.0   |
| expo                                 |    44     |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by jquartz** [comment]
@fristyr I had this issue and solved it by declaring the callback function as a worklet then running my JS code with the runOnJS function

```
const animationEnd = SlideOutRight.withCallback((finished: boolean) => {
    'worklet';
    if (finished) { 
       runOnJs(myCallback)() 
    }
});

**Comment by fristyr** [comment]
@jquartz Thanks for your answer but now I have a different error if I include **runOnJs**
Without  **runOnJs** it's working fine and I can run my callback

![Screenshot 2022-01-22 123425](https://user-images.githubusercontent.com/33237937/150688933-52201b3e-f530-46c4-9d5c-e56784e0bd91.png)

**Comment by jquartz** [comment]
If your callback can be excecuted on the native thread then you should be set without runOnJS, but not sure why you are getting that error without seeing the code

**Comment by fristyr** [comment]
Oh, it was because I wasn’t enough attentive...
So instead of the solution above, I did next

```javascript
const animationEnd = SlideOutRight.withCallback((finished: boolean) => {
    'worklet';
    if (finished) { 
       // Wrong
       runOnJs(myCallback() <- //here was my problem  )() 
       // Correct
       runOnJs(myCallback)() 
    }
});
```

**Comment by JohnathanWhite** [comment]
For me i just needed to return the call back 

`
exiting={FadeOutLeft.withCallback(finished => {
          'worklet';
          return () => {
            if (finished) {
              
            }
          }
        })}`
