### ISSUE TITLE
How to queue new values (Array/Queue/Batch/Sequence)

### ISSUE THREAD

**Issue by gabrielbull** [software-mansion/react-native-reanimated#287]
Hi,

I'd like to have an Array of values for sequencing an animation. 

For example, it could be [1, 5, 2], and I would shift the first value at the end of a timing and re-run the timing again to the shifted value. The reason it would be useful doing this with an array is that I could add as many values as possible. For instance, if the user does an action, I add a new value to the end of the array and wait until all previous values are animated.

In my example, I can't just update the toValue of the timing, I need to wait until all previous animations are finished.

**Comment by jakub-gonet** [comment]
Hi, sorry for the late response.

I don't really see your use case without the provided code. We recently released reanimated v2 which supports using arrays in animations, so this should solve it.

I'm closing it, but feel free to reply.
