### ISSUE TITLE
Animation lagging on some high-end android devices 

### ISSUE THREAD

**Issue by gpavlov21** [software-mansion/react-native-reanimated#2870]
I`m having a weird problem with a fairly simple animation which expands a Animated.View , that I call when pressing a TouchableOpacity:
```
    height.value = withTiming(calculatedHeight, {
      duration: 300,
      easing: Easing.inOut(Easing.ease),
    });
```
On IOS is running very nice on 60fps, but on some Android phones like Samsung S20/S21 Ultra, the animation is lagging a lot. I tried it on an older Samsung(A5) and on it is running fine again on 60 fps. Any suggestions are appreciated.

What are the exact versions of packages and tools that you are using?
| name                                             | version |
| ------------------------------------ | ------- |
| react-native                                   | 0.64.3 |
| react-native-reanimated               | 2.2.0 |
| NodeJS                                          | 14.16.1 |
| expo                                              |SDK 43 |

**Comment by WoLewicki** [comment]
Can you check if the problem still occurs in the newest version of the library? If so, could you provide a simple repro in a form of a repo or a snack?
