### ISSUE TITLE
Android build fails with react-native-reanimated: Cannot get property 'react' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by SherMish** [software-mansion/react-native-reanimated#2872]
### Expected behavior
The build to succeed.

### Actual behavior & steps to reproduce
yarn add react-native-reanimated@next
build in android studio
error:
```A problem occurred evaluating project ':react-native-reanimated'.
A problem occurred evaluating project ':react-native-reanimated'.
> Cannot get property 'react' on extra properties extension as it does not exist
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':react-native-reanimated'.
...
...
...
caused by: groovy.lang.MissingPropertyException: Cannot get property 'react' on extra properties extension as it does not exist
	at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.getProperty(DefaultExtraPropertiesExtension.java:68)
	at build_69cjznbgqdaagbeb8n2srxehm$_run_closure1.doCall(/home/sharon/SVN/android_vpn/android_branches/sharon/RNApp/AwesomeProject/node_modules/react-native-reanimated/android/build.gradle:55)
	at jdk.internal.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.sun.proxy.$Proxy40.accept(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor761.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.66.4|
| react-native-reanimated              |2.2.0|
| NodeJS                               |16.13.1 |
| Xcode                                |         |
| Java                                 |11.0.13|
| Gradle                               |6.8|
| expo                                 |         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?

**Comment by tymmesyde** [comment]
Same issue after upgrading to react-native@0.70.1

**Comment by scruff311** [comment]
Same issue with a fresh integration into an existing Android project using react-native@0.70.1 and react-native-reanimated@2.13.0

**Comment by PR-Here** [comment]
Getting same Issue
<img width="946" alt="Screenshot 2023-07-27 at 1 55 47 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/89129280/5ae4084e-5c65-4ddb-a532-feda96dcba76">

**Comment by trucuit** [comment]
Getting same Issue

**Comment by gauravjoshi-vahan** [comment]
Is there a solution to this? Cannot use any other library either that has a dependency on react-native-reanimated.

**Comment by trucuit** [comment]
smae issue
