### ISSUE TITLE
Android back button can't exit the app anymore after installation. 

### ISSUE THREAD

**Issue by dreson4** [software-mansion/react-native-reanimated#2883]
## Description

I have integrated RN on top of my native android app, it opens as a new activity when I click a button from my native app. The app worked fine and the back button when I'm at RN's home screen always exits back to native app. After installing reanimated-2 before even doing anything, the back button has stopped working completely when I'm at the home screen, I can't quit to go back to native, even `BackHandler.exitApp()` doesn't work. The app simply can't be closed at all. 

### Expected behavior
Close the app when I'm at the home screen when I press the back button. Or BackHandler.exitApp() should work. 

### Actual behavior & steps to reproduce
To reproduce simply add react native to a native android project, install reanimated, the back button stops working. 

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   ^0.67.0       |
| react-native-reanimated              |    2.3.0     |
| Java                                 |    11.0.1     |
| Gradle                               |   7.0.4      |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?
