### ISSUE TITLE
Style respects initial value sometimes for a frame, and sometimes stuck there

### ISSUE THREAD

**Issue by Noitidart** [software-mansion/react-native-reanimated#2887]
## Description

The shared-value should be respected at all times. In reanimated 2.3.1, the style is sometimes respect initial-value when it is no longer at that.

### Expected behavior

1. https://snack.expo.dev/@themasjidapp/34299d is on expo 43 with reanimated v2.2.0 you will see it works fine.

### Actual behavior & steps to reproduce
1. Install expo v44, and install reanimated which will be 2.3.1
2. Copy this snack above into this new project.
3. Then you will see the square vertically centered in the screen (most times, sometimes it stays stuck at initial transform value of -1)
4. If you see it vertically centered, press on "increment" you will see it either flicker to the initial transform value of -1, and then jump back. Or you will see it get stuck up at -1. If you do a useAnimatedReaction you will see the transform value is not -1, it is the vertically centered one, however the style is respecting the initial value of -1.

I have been hitting this issue for awhile, here are some videos an examples - https://github.com/software-mansion/react-native-reanimated/discussions/2857

## Snack or minimal code example

This is good snack - https://snack.expo.dev/@themasjidapp/34299d

Snack doesnt yet support expo 44 which has reanimated 2.3.1 - so to reproduce the bug, please copy snack and paste it into expo 44 with reanimated 2.3.1

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native-reanimated              |  2.3.1       |
| expo                                 |     44    |

## Affected platforms

- [ ] Android - untested on Android but I think it will happen there too.
- [x] iOS
- [ ] Web

**Comment by Noitidart** [comment]
Updated

**Comment by Noitidart** [comment]
Here's another post and video about this.

>  This is happening to me too in other uses. It seems for one frame to jump back to the initial value of the useSharedValue, even though that value is no longer that initial value. Sometimes this is devastating. 

> For example I have a modal that slides up, so initially its completely off screen. It then shows and then I have some content in there. The content triggers a re-render, and then the modal gets stuck at the initial value which is completely offscreen. I have a video where it doesn't get stuck, but flickers and flickers back in the topics I posted below. Here's a video of getting "stuck" in another situation where this "initial value jump despite value not changing" happens - when I click tag "Whoa" it gets telported to top left which was initial - https://giant.gfycat.com/KnobbyAnchoredCirriped.mp4

> The way I know the value doesn't change is I added this to detect changes:

> ```
>       ReanimatedUtils.useAnimatedReaction(
>         () => x.value,
>         (value, prevValue) => {
>           if (prevValue !== null) {
>             console.log(props.tag, 'x changed', value, prevValue);
>           }
>         },
>         [x, props.tag]
>       );
> ```

> And it never logs a change, yet visually it is definitely at initial value.

**Comment by JackShannon** [comment]
We've also been encountering issues with the jump to initial value for the last few weeks. Does anyone know a workaround?

**Comment by Noitidart** [comment]
Thanks Jack for sharing. One work around, which doesn't apply to all situations, just some, was starting the shared value at the final value, and then before starting the animation set the shared value to the initial value. But this led to another intermittent issue where setting it to initial value right before starting animation was not taking affect:

```
const FINAL = 1;
const INITIAL = 0;
const sharedValue = useSharedValue(FINAL);

useEffect(() => {
  sharedValue.value = INITIAL; ////// this one would have no effect sometimes
  sharedValue.value = withTiming(FINAL)
}, [])
```

**Comment by JackShannon** [comment]
Thank you Noitidart for the workaround. In our case the final value is unknown (drag and drop list) unfortunately.

Actually since I posted last, I reread your initial post where you said it works on 2.2.0. I've tried this version and it's working fine. Thank you for this :)

I hope that this bug can be sorted so we can use the latest reanimated features soon!

**Comment by Noitidart** [comment]
Oh awesome, haha I forgot to recommend trying 2.2.0. Thanks for chiming in to up vote this issue, its been a killer.

**Comment by Noitidart** [comment]
Just a gentle bump on this, to see if anyone has discovered anything or any workarounds for it?

**Comment by sebaferreras** [comment]
Thank you @Noitidart for opening this issue! I've been implementing and re-implementing the same thing over and over again just to always find the same glitch in the animations and I think it may be related to this.

I've created this Expo Snack with the most relevant parts of the code (it doesn't work on the browser but it should work fine on iOS): https://snack.expo.dev/@sebaferreras/swipe-issue

After a card is swiped right, the state is updated to add the next card and all cards are animated based on their index (using some custom `entering` layout animations):
- The third card is animated to look like it was added at the bottom of the stack (`becomesThird`).
- The second card is animated to look like it's the third card moving to the second position (`becomesSecond`).
- The first card is animated to look like it's the second card moving to the first position (`becomesFirst`).

As it can be seen in the following demo video, **sometimes** there's a glitch where the first card appears at the end position for a frame, before being animated as expected (for example it can be seen when swiping the card number 16 to the right):

https://user-images.githubusercontent.com/17194770/200182976-63f19149-c6f8-42fb-a4ee-5e5d2383be4e.mp4

This is the same glitch but frame by frame:

https://user-images.githubusercontent.com/17194770/200184269-a53346aa-851d-4e7a-bf3a-de13cdd2c5cf.mp4

It's very subtle but it can be seen in that demo video that the issue happens as soon as `index` goes from 1 to 2 which means as soon as the state changes and the component is rerendered.

Do you think that this could be related or it could be a different issue?

Just in case, I'm using:
```
"react-native-reanimated": "~2.9.1",
"react-native-gesture-handler": "~2.5.0"
```

**Comment by sebaferreras** [comment]
Sorry for the confusion, I deleted my comment because I found the issue and it was actually something wrong on my end.

In my case, the issue was because I was applying an entering layout animation but I was also setting some animated styles to that same element:

```
  const someEnteringAnimation = new Keyframe({...}).duration(350);

  const cardStyle = useAnimatedStyle(() => {
    return {
      transform: [
        { scale: cardScale.value },
        { rotate: cardRotation.value },
        { translateX: cardTranslateX.value },
        { translateY: cardTranslateY.value },
      ],
    };
  });
  
  ...
  ...
  ... 
  
  <Animated.View
        entering={someEnteringAnimation}
        style={[styles.card, cardStyle]}>
        ....
  </Animated.View>
```

So there was a conflict between the layout animation and the animated style. I updated the code to only apply the animated style once the entering animation is done, and everything seems to be working fine.

Thanks :)

**Comment by Noitidart** [comment]
Ah this is very useful, thanks for sharing!

**Comment by szydlovsky** [comment]
Hi everyone, as we are doing some older issues cleanup, I am happy to announce that latest versions (3.12.1) don't have the issue anymore!

**Comment by Noitidart** [comment]
Thank you @szydlovsky! Do you know which version it was fixed it? Was a very curious bug, I wonder what fixed it.

**Comment by szydlovsky** [comment]
@Noitidart no clue unfortunately, styles have gone through a lot of changes since November 2022 haha

**Comment by szydlovsky** [comment]
You can try binary searching through version if you are really curious 😄

**Comment by Noitidart** [comment]
Haha no problem thanks very much for this note and testing to see if this was fixed!
