### ISSUE TITLE
No variants found for `react-native-reanimated`

### ISSUE THREAD

**Issue by gkeenleyTest** [software-mansion/react-native-reanimated#2888]
## Description

I upgraded my React Native project to Gradle 7.0.2 and now when I open Android Studio it says No variants found for ':react-native-reanimated'. I'm using react-native-reanimated@1.13.3, and from the documentation for versions 1.x.x there's no real configuration, so I'm not sure how to approach this. Has anyone run into anything similar? I'm using react-native@0.63.4, gradle 7.0.2, and Android Gradle Plugin 7.0.0.

## Snack or minimal code example
`import Animated from 'react-native-reanimated';`

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.63.4        |
| react-native-reanimated              |1.13.3         |
| NodeJS                               |14.15.4         |
| Xcode                                |13.1         |
| Java                                 |openjdk version "11.0.10"         |
| Gradle                               |7.0.2         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by j-piasecki** [comment]
Hi! Unfortunately Reanimated 1 is no longer supported. For quick solutions, besides downgrading gradle since it worked for you before, you can try checking if you have correct Android SDK.
