### ISSUE TITLE
App crashed when debugging mode is enabled

### ISSUE THREAD

**Issue by G-638** [software-mansion/react-native-reanimated#2892]
## Description
I am using ```react-native-reanimated```. Since I started using reanimated, the app crashes if debugging mode is enabled. Once I uninstall reanimated package the app runs in debugging mode perfectly.

### Expected behavior
debugging mode should work as usual

### Actual behavior & steps to reproduce
app crashes if the debugging mode is enabled

## Snack or minimal code example
No specific code is required. Just installing the package is sufficient.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.64.2    |
| react-native-reanimated              |    2.2.2     |
| NodeJS                               |    v12.22.8     |

## Affected platforms

- [x] Android

**Comment by piaskowyk** [comment]
It should work in the next release 2.3.2 (the release will be next week)

**Comment by mohammedelnady** [comment]
speaking from that next week, It **DOESN'T WORK !!**

**Comment by piaskowyk** [comment]
`Time is relative` - like Einstein said 😄  Sorry for the delay but I was a couple of days off. Finally, I have just published a new release with many fixes - https://www.npmjs.com/package/react-native-reanimated/v/2.4.0

**Comment by mohammedelnady** [comment]
Christopher Nolan Reacts Love,  😄 😄😄 
 Thanks Dude & Happy Coding

**Comment by G-638** [comment]
> It should work in the next release 2.4.0 (the release will be next week)

ya, In new release 2.4.1 , debugger os working fine. Thank you! 🙂🤝

**Comment by adityacfcs** [comment]
hi @piaskowyk debugger is not working in version 2.8.0
