### ISSUE TITLE
Hot reload iOS crash due to EXC_BAD_ACCESS on rt.global()

### ISSUE THREAD

**Issue by tomekzaw** [software-mansion/react-native-reanimated#2899]
With this issue I'd like to gather all bug reports related to EXC_BAD_ACCESS crash when hot-reloading the app on iOS:

- #2035 (confirmed)
- ...

This is how the crash looks like in its natural environment:

![](https://user-images.githubusercontent.com/20516055/151563308-27911aee-0f95-44e5-93b6-aa5ab4a42408.png)

The crash happens because when `requestRender` lambda is executed, the JS runtime has already been deallocated (as a result of hot-reload). Most likely, this is due to some missing cleanup.

**Note:** This bug is mostly relevant in debug mode during development as the JS runtime gets deallocated when reloading the app. However, it also appears in release builds when using code-push updates.

**Comment by phamhungvn** [comment]
This bug is in the release mode as well. Sometimes we need to reload the app after upgrading it with [code-push](https://github.com/microsoft/code-push)

**Comment by phamhungvn** [comment]
Hi @tomekzaw Does you have plan for fixing this crash in next release?

**Comment by danilobuerger** [comment]
Hi @tomekzaw 👋 were you able to reproduce it with the issue I linked?

**Comment by tomekzaw** [comment]
Hello! I've managed to check out your repro but somehow couldn't reproduce it on my M1. I'm quite busy recently but @piaskowyk promised to take a look on this.

**Comment by danilobuerger** [comment]
@tomekzaw @piaskowyk PR is at #3090

**Comment by phamhungvn** [comment]
> @tomekzaw @piaskowyk PR is at #3090

@danilobuerger I tried your code in PR, but I still got crash when the app reload.
I'm using function `CodePush.reloadApp()` from `CodePush` package.

**Comment by danilobuerger** [comment]
@phamhungvn my issue is probably different to yours. I am trying to fix hot reloading.
