### ISSUE TITLE
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code.

### ISSUE THREAD

**Issue by dmahajan980** [software-mansion/react-native-reanimated#2911]
## Description

I am receiving the following warning when using `Animated.View`:

```
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: AnimatedComponent

Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: AnimatedComponent
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | ^0.64.3 |
| react-native-reanimated              | ~2.3.1 |
| NodeJS                               | 16.13.0 |
| expo                                 | ~44.0.0 |

**Comment by kkafar** [comment]
Hey @dmahajan980,
Can you provide minimal code example where this warning occurs (Snack, repository, code snippet)?

**Comment by nassif7** [comment]
I got the same issue. 
It seems to happen when using the <React.StrictMode> since i removed i stopped seeing this warning

**Comment by AdamTyler** [comment]
Same here. As @nassif7 said, the issue started appearing when wrapping my app in `<React.StrictMode>`

**Comment by michakfromparis** [comment]
same here. All up to date to expo 48 etc. React.StrictMode triggers it

**Comment by longphung** [comment]
I have created a minimal reproduction of the issue in a GitHub.
This is the project directly after running `npx react-native@latest init`
Here's the link: https://github.com/longphung/react-native-animated-strict-mode 
All I did was wrap the App component in `React.StrictMode` and the error apepars in the log.

**Comment by Latropos** [comment]
During last year we have done a lot of work to start using strict mode in our repository and the problem seems to be no longer reproducible.
