### ISSUE TITLE
Incorrect arrow function babel transform inside of `useAnimatedStyle`

### ISSUE THREAD

**Issue by elGatoMantocko** [software-mansion/react-native-reanimated#2916]
## Description

Babel/metro is compiling functions inside of `useAnimatedStyle` incorrectly.

```tsx
const style = useAnimatedStyle(() => ({ shadowRadius: 10 }));
```

is getting compiled to

```tsx
const style = useAnimatedStyle(() => { shadowRadius: 10 })
```

But this results in a runtime error.

```
error: SyntaxError: MyComponent.tsx: MyComponent.tsx: Unexpected token, expected ";" (4:14)

  2 | (() => {
> 4 |   shadowRadius: 10,
    |               ^
  5 |   shadowOpacity: 0.5,
```

### Expected behavior

If babel is allowed to output arrow functions, it should follow correct arrow syntax.

Either compile to `useAnimatedStyle(() => { return { ... } })` or `useAnimatedStyle(() => ({ ... }))`.

### Actual behavior & steps to reproduce

Using the latest babel/react-native-reanimated, write a style that uses the hook `useAnimatedStyle` with an arrow function like so:

```tsx
const style = useAnimatedStyle(() => ({ shadowRadius: 10 }));
```

And note the babel output.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.64.2       |
| react-native-reanimated              |  2.3.1       |
| NodeJS                               |  14.17.6       |
| Xcode                                |  13.2.1       |
| Babel/Core                                 |   7.16.12      |
| Babel/Runtime                               |  7.16.7       |

## Affected platforms

This may impact others, I just haven't tested it.

- [x] Android
- [x] iOS
- [ ] Web

**Comment by Latropos** [comment]
We are unable to reproduce this bug on our end, its is possible that you have forgotten to add reanimated babel plugin. If the problem persists you may also try updating reanimated
