### ISSUE TITLE
Build error on initial app RN 0.67.2

### ISSUE THREAD

**Issue by Omelyan** [software-mansion/react-native-reanimated#2922]
## Description
There's an error while simplest npx init for current RN version 0.67.2, and everything was fine for RN 0.64.2...

**ERROR: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes**

### Actual behavior & steps to reproduce
1. npx react-native init test (current latest RN version is 0.67.2)
2. install Reanimated...
3. replace App.js by:
```import React from 'react';
import {View} from 'react-native';

import Animated from 'react-native-reanimated';

const App = () => (
  <View style={{height: 100, aspectRatio: 1, backgroundColor: 'tomato'}} />
);

export default App;
```
4. npx react-native run-android and you'll get the error above.

## Snack or minimal code example
Just create an app by calling npx react-native test, install Reanimated, import Reanimated lib from App.js and try to run...

## Package versions
"react": "17.0.2",
"react-native": "0.67.2",
"react-native-reanimated": "^2.3.1"

## Affected platforms

- [x ] Android
- [ ] iOS
- [ ] Web

**Comment by milan2sky** [comment]
fuck It seems that I have also this error in one of my projects

**Comment by gk37497** [comment]
RN  0.67.2 -> 0.66 or older. it worked

**Comment by rjuevesano** [comment]
> 

works for me.. thanks @gk37497

**Comment by rjuevesano** [comment]
> RN 0.67.2 -> 0.66 or older. it worked

works for me.. thanks @gk37497

**Comment by itsmelion** [comment]
Hurts my heart when the fix is downgrading. 💔
