### ISSUE TITLE
Circular Require in upcoming version 2.4.0, which would probably cause core methods 'undefined' in worklet.

### ISSUE THREAD

**Issue by yiheyang** [software-mansion/react-native-reanimated#2924]
## Description

Circular Require in upcoming version 3.4.0, which would probably cause core methods 'undefined' in worklet.

withXXX in worklet function would throw undefined is not a function near "defineAnimation", which is in util.ts(affected in circular requrie)

I compare the working tree vs 2.3.1 then found the reason: 

"import { useSharedValue } from './hook/useSharedValue';" causing all these problems.

## Snack or minimal code example

no need.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |         |
| react-native-reanimated              |         |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

![image](https://user-images.githubusercontent.com/8202550/152225602-05e338b9-f7f4-4b88-b7d3-2f8b54b34ca5.png)

**Comment by Latropos** [comment]
Thank you for submitting the issue! We have solved the problem a long time ago (and we've added `circular_dependency_check` to prevent any similar issues in the future).
