### ISSUE TITLE
Tried to synchronously call anonymous function from a different thread.

### ISSUE THREAD

**Issue by NastuzziSamy** [software-mansion/react-native-reanimated#2926]
Hi !

## Description

I tried to wrap useDerivedValue and useAnimatedStyle but each time, I got the following error.

### Expected behavior

With worklets, runOnUI, runOnJS, nothing worked for me.

### Actual behavior & steps to reproduce

![272218218_301642415357109_1703424319279721962_n](https://user-images.githubusercontent.com/24639904/152241499-0948204c-1ccd-478b-ba54-09b925d64d15.jpg)

```typescript
const width = useCalculatedValue(() =>
		withTiming(250, {
			duration: 250,
		})
	);
// or
const [style, setLeft, setWidth] = useAnimation((left, width) => ({
        left,
        width,
}), [0, 0]);
```

## Snack or minimal code example

```typescript
import { useSharedValue, useAnimatedStyle, useDerivedValue } from 'react-native-reanimated';

// Works perfectly.
export const useAnimatedValue = (defaultValue = 0): [any, CallableFunction] => {
	const animatedValue = useSharedValue(defaultValue);

	return [animatedValue.value, (value) => (animatedValue.value = value)];
};

export const useCalculatedValue = (calculate: CallableFunction): [any, CallableFunction] =>
	useDerivedValue(calculate).value;

export const useAnimation = (
	calculateStyle: CallableFunction,
	defaultValues = [0]
): [any, ...CallableFunction[]] => {
	const animatedValues = defaultValues.map((defaultValue) => useAnimatedValue(defaultValue));
	const values = animatedValues.map(([value]) => value);

	return [
		useAnimatedStyle(() => calculateStyle(...values)),
		...animatedValues.map(([, setValue]) => setValue),
	];
};
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.64.3       |
| react-native-reanimated              |    2.3.1    |
| NodeJS                               |   14      |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |     44.0.0    |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

Thanks a lot :)

**Comment by Basir-PD** [comment]
any solution to this issue yet?

**Comment by NastuzziSamy** [comment]
I personnaly droped this idea, as I think, I badly understood how it works, so I used the classic way.

**Comment by danielfein** [comment]
Still getting this issue, any ideas?

**Comment by NastuzziSamy** [comment]
You can't have this approach as they are like references from ui thread.
