### ISSUE TITLE
Animated.Text freezes UI on Android

### ISSUE THREAD

**Issue by AlexanderEggers** [software-mansion/react-native-reanimated#2927]
## Description

The Animated.Text is working fine on iOS but is freezes the UI on Android. There is no log or exception which explains this behavior. I also tried to use Animated.View which results in the same behavior.

### Expected behavior

Animation are playing like on iOS.

### Actual behavior & steps to reproduce

Freezes UI without any logs or exception which prevents the user from seeing the relevant screen.

## Snack or minimal code example

```
<Animated.Text
   entering={FadeInRight}
   exiting={FadeOutLeft}
>
   {props.value}
</Animated.Text>
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.67.1       |
| react-native-reanimated              |   2.3.1      |
| NodeJS                               |    v14.17.5     |
| Xcode                                |     13.2.1     |
| Java                                 |     11.0.12+0    |
| Gradle                               |    7.3.3     |
| expo                                 |    44.0.6     |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by SvenJonsson** [comment]
@AlexanderEggers This is due to LayoutAnimations (entering, exiting) leaving a zombie view that prevents interaction see #2704 for example.
