### ISSUE TITLE
Android build failure in build 2.3.x with detox artifact

### ISSUE THREAD

**Issue by jarvisluong** [software-mansion/react-native-reanimated#2928]
## Description

Hi! A fresh react native project integrating with detox, using react-native-reanimated@2.3.x will yield a build failure with following error:

The command I'm running is:

```
./gradlew assembleDebugAndroidTest -DtestBuildType=debug
```

```
> Task :react-native-reanimated:processDebugAndroidTestManifest FAILED
[:react-native-reanimated] /home/root/app/node_modules/react-native-reanimated/android/build/intermediates/merged_manifest/debug/AndroidManifest.xml Warning:
	Package name 'com.swmansion.reanimated' used in: :react-native-reanimated, react-native-reanimated-64-jsc.aar.
[androidx.vectordrawable:vectordrawable-animated:1.0.0] /root/.gradle/caches/transforms-3/1a1fc95fdcfb9f6e2e551d13c4ca70dc/transformed/vectordrawable-animated-1.0.0/AndroidManifest.xml Warning:
	Package name 'androidx.vectordrawable' used in: androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1.
/home/root/app/node_modules/react-native-reanimated/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger16221606182624431729.xml:5:5-72 Error:
	uses-sdk:minSdkVersion 1 cannot be smaller than version 16 declared in library [react-native-reanimated-64-jsc.aar] /root/.gradle/caches/transforms-3/7a68d808289551ce7ccd09f052f191a4/transformed/jetified-react-native-reanimated-64-jsc/AndroidManifest.xml as the library might be using APIs not available in 1
	Suggestion: use a compatible library with a minSdk of at most 1,
		or increase this project's minSdk version to at least 16,
		or use tools:overrideLibrary="com.swmansion.reanimated" to force usage (may lead to runtime failures)
```

This issue doesn't happen when I downgrade to 2.2.4

## Snack or minimal code example

I'm preparing a reproducible example

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.64.3    |
| react-native-reanimated              |    2.3.1     |
| NodeJS                               |    v16.13.1     |
| Java                                 |     openjdk version "11.0.10" 2021-01-19    |
| Gradle                               |     6.7    |
| expo                                 |   44.0.6      |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by leonardomdr** [comment]
@jarvisluong I am facing the same issue here. Let me know if you have any progress fixing it. I will do the same if I can fix it here.

I am using react-native-reanimated version 2.3.1 as well. I was at 2.3.0 and detox was running fine. 

I noticed that it started to happen after I included expo in my project...

**Comment by TwistedMinda** [comment]
Running into the same issue, but on only on the androidTest build type. Neither 2.3.0 nor 2.2.4 as mentioned worked for me.

**Comment by leonardomdr** [comment]
> Running into the same issue, but on only on the androidTest build type. Neither 2.3.0 nor 2.2.4 as mentioned worked for me.

Try installing version 2.3.1, but after that, do a gradlew clean and then rebuild. At least here, it worked.

**Comment by filipengberg** [comment]
I just tried version 2.4.1 but get the same issue. Tried doing `./gradlew clean` but did not help. Same issue on 2.3.1

**Comment by TwistedMinda** [comment]
Didn't work either. However, and i'm very about it: using last version of React-native (0.67.1) and last version of reanimated (2.4.1) it now works. That feels good ;)

**Comment by mauricedoepke** [comment]
I could circumvent this by adding
```
defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 1)
}
```
to the android section of the linked gradle.
I have no idea of the workings of gradle files, but this seems to take the minSdkVersion from the expo project and uses it for reanimated as well.

<img width="542" alt="Screenshot 2022-03-07 at 00 30 22" src="https://user-images.githubusercontent.com/16628813/156946986-88251066-4973-4ca6-8c0f-709c0a6aee63.png">

Might adding this code or similar to reanimated be a solution for this issue?

**Comment by aidooyaw1992** [comment]
i added this in the reanimated plugin  expo/src/linking.gradle
  defaultConfig{
            minSdkVersion safeExtGet('minSdkVersion', 1)
        }
  
"react-native-reanimated": "^2.3.0",

**Comment by piaskowyk** [comment]
Check if it works with Reanimated 3, please 🙏
