### ISSUE TITLE
Reanimeted v2.3.x BROKE my whole application in the most non-obvious places - this is a very raw version and do not upgrade to it!

### ISSUE THREAD

**Issue by vladyslavNiemtsev** [software-mansion/react-native-reanimated#2930]
### Expected behavior

Correct work without A LOT OF bugs.

## Affected platforms

- [ x] Android
- [ x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
I understand your frustration, but we do what we can to stabilize reanimated. I really want to help you but to be honest, I literally don't know what happened. Could you provide more details?

**Comment by hirbod** [comment]
@piaskowyk I think everything comes down to #2851 and #2580. The regressions introduced had quite an impact on a lot of libraries, e.g react-native-bottom-sheet and moti, just to name two widely used libs.
It is kinda frustrating, for sure, but I take a bow for being so chilled and cool after such a rude and disrespectful ticket on a OSS project. I would've closed it without any reaction.

@vladyslavNiemtsev you might want to spend couple of thousands of € to get priority support from SWM.

**Comment by Only-IceSoul** [comment]
Expo dev client and reanimated are not working together. It would be nice if they fixed it. (Android)

**Comment by vladyslavNiemtsev** [comment]
@hirbod @piaskowyk  HI!

Guys, I apologize for the created ticket and the description for it in such a rude and disrespectful form without a single specificity. 
These were some quick emotions.

It's really true that the guys are doing an incredible job for both the OSS project. Thanks a lot for it!

Btw, in our team we decided to thank your team financially, but I did not find any sponsor links..
Could you give me this link or some instructions how to say you Thanks!
