### ISSUE TITLE
error while running the iOS app 

### ISSUE THREAD

**Issue by sankar-gp** [software-mansion/react-native-reanimated#2935]
I'm getting the following error while running the iOS application using "npx react-native run-ios"

**Expected behavior**
The app launches.

**Actual behavior & steps to reproduce**
The app crashes on launch with the following error 

The following build commands failed:
        CompileC /Users/h481626/Library/Developer/Xcode/DerivedData/MAXPROMobileaccess-bdrgpfvupyvelufltdljjecsahgr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/NativeMethods.o /Users/h481626/Documents/WORKSPACE_HONEYWELL/REACT_NATIVE_OFF/MC_APP_Off/src/app/node_modules/react-native-reanimated/ios/native/NativeMethods.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods')

**Package versions**
"@react-native-async-storage/async-storage": "^1.15.17",
    "i18next": "^21.6.10",
    "native-base": "^3.3.4",
    "react": "17.0.2",
    "react-i18next": "^11.15.3",
    "react-native": "0.67.2",
    "react-native-biometrics": "^2.1.4",
    "react-native-cardview": "^2.0.5",
    "react-native-connectivity-status": "^1.5.2",
    "react-native-device-info": "^8.4.8",
    "react-native-exit-app": "^1.1.0",
    "react-native-gesture-handler": "^2.2.0",
    "react-native-localize": "^2.1.9",
    "react-native-permissions": "^3.2.0",
    "react-native-reanimated": "^2.3.0-beta.2",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-restart": "0.0.24",
    "react-native-router-flux": "^4.3.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.2",
    "react-native-toast-message": "^2.1.1"

**Affected platforms**
iOS

**Comment by piaskowyk** [comment]
Hey 👋
Could you provide a repo to reproduce your issue? Because your logs are incomplete and I can't diagnose the problem based on these.

**Comment by abhinav-official** [comment]
@sankar-gp any updates regarding this?
