### ISSUE TITLE
[Android] build failed - react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)

### ISSUE THREAD

**Issue by Md-Mudassir47** [software-mansion/react-native-reanimated#2936]
## Description

Android build is failing after i had installed a specific [commit](https://github.com/software-mansion/react-native-reanimated/commit/e52d733ab9f0fc33e52c54c8d7adbfe86a2608ac) to fix the null pointer issue 

<img width="1012" alt="Screenshot 2022-02-04 at 12 58 31 PM" src="https://user-images.githubusercontent.com/85115578/152489089-17c3d9f5-4037-4b1f-b803-2c1e3efd8285.png">

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.66.3       |
| react-native-reanimated              |  github:software-mansion/react-native-reanimated#e52d733ab9f0fc33e52c54c8d7adbfe86a2608ac       |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by kkafar** [comment]
Hi @Md-Mudassir47,
it is subject to change, but right now it is impossible to install reanimated directly from github (we are working on building from source). 

It seems to me, that the commit you wanted was merged & [released with reanimated 2.4.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.4.0), so upgrading to newest release should help!
