### ISSUE TITLE
🐛 [iOS] fatal crash - cannot read params of undefined

### ISSUE THREAD

**Issue by a-tokyo** [software-mansion/react-native-reanimated#2939]
## Description
When upgrading from `^2.2.3` to `^2.3.1`, App crashes on startup with the error:
```
error: node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts: /Users/Tokyo/Dev/plural/mobile-app/node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts: Cannot read property 'params' of undefined
```

### Expected behavior
App should startup normally

### Actual behavior & steps to reproduce
- Create a RN app using react navigation and reanimated 2.2.3.
- Attempt upgrading reanimated to 2.3.1

## Snack or minimal code example

```js
<App><AppNavigation /></App>
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.66.4|
| react-native-reanimated              |2.3.1 |
| NodeJS                               |14.18|
| Xcode                                |13.2.1|
| Java                                 |11.0.14|
| Gradle                               |6.9|

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey 👋 Could you provide me with the babel version do you use?

**Comment by A-Tokyo** [comment]
@piaskowyk Thanks for your response, here you go!

package.json
```js
    "@babel/core": "^7.16.12",
    "@babel/plugin-external-helpers": "^7.16.7",
    "@babel/plugin-proposal-decorators": "^7.16.7",
    "@babel/plugin-proposal-export-default-from": "^7.16.7",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.16.7",
    "@babel/plugin-proposal-optional-chaining": "^7.16.7",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-flow": "^7.16.7",
    "@babel/preset-react": "^7.16.7",
    "@babel/preset-typescript": "^7.16.7",
    "@babel/runtime": "^7.16.7",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^27.4.6",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-relay": "^12.0.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "babel-preset-react-native": "^4.0.1",
```

babel.config.js
```js
module.exports = {
  passPerPreset: true,
  presets: ['module:metro-react-native-babel-preset', '@babel/preset-flow', '@babel/preset-typescript'],
  plugins: [
    [
      'relay',
      {
        schema: './graphql/schema.graphql',
      },
    ],
    [
      'transform-inline-environment-variables',
      {
        include: ['NODE_ENV', 'REACT_APP_HOST_ENV', 'REACT_APP_*'],
      },
    ],
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-nullish-coalescing-operator',
    'lodash',
    'react-native-reanimated/plugin',
  ],
};

```

**Comment by BasixKOR** [comment]
Note for those who ended up here: Your babel config should be configured to compile arrow functions, so that the reanimated plugin receives a normal function expression which prevents transpiling the arrow function inside the plugin.
