### ISSUE TITLE
width & height & more example broken on android

### ISSUE THREAD

**Issue by kdawgwilk** [software-mansion/react-native-reanimated#294]
width & height & more example in example app broken on android with the following error

Emulator: Nexus_5X_API_27

![image](https://user-images.githubusercontent.com/7799267/58649305-04ad1480-82c9-11e9-86d3-389f12c914d3.png)

**Comment by lake2** [comment]
same issue +1

**Comment by jakub-gonet** [comment]
Thanks for submitting this issue!

I created PR which fixes this bug (#485).
