### ISSUE TITLE
FlatList Sticky Header Style Is Reset On Fetch With Dynamic Data Array

### ISSUE THREAD

**Issue by Kesmek** [software-mansion/react-native-reanimated#2943]
## Description
To preface all this, I am not quite sure if this library is even the root cause of this issue, however since I'm using a component exported from the Animated namespace I will assume so for now.

Using a FlatList exported from the Animated namespace in this library with data of dynamic length (e.g. length of data is not static) alongside a sticky header with some dynamic style (backgroundColor, translation, etc.) causes the style to be reset each time new data is fetched. There will be a video attached that clearly shows this in action.

Upon doing some of my own research into ways to get around this issue, I've found that react native actually exposes a prop named "stickyHeaderComponent" which is for custom sticky headers that use custom transforms. I assume that creating and passing my own component to this prop is a good first step. I should mention that I am not an expert when it comes to making wrapper components like this, but nonetheless since there is very little documentation on how to use this prop I cannot figure out how to properly implement this prop with an Animated component.

### Expected behavior
The sticky header's style does not change when new data is fetched.

### Actual behavior & steps to reproduce
The sticky header's style is reset when new data is fetched and it is corrected immediately once you scroll.

Steps
1. Scroll to bottom of FlatList to initiate mockAPI to add more items to data array (can also be observed any time items are added to the data array)
2. Data is fetched after 1 second
2. Header style will be reset
3. Scrolling fixes the incorrect header style

https://user-images.githubusercontent.com/38704268/152619259-6620b37a-1f43-4a97-976a-626388f9423c.mp4

## Snack or minimal code example
I apologize if this example may be slightly convoluted but it is as simple as I believe necessary. Note that the issue is on the "rea-sticky-header-issue" branch.

https://github.com/Kesmek/test/tree/rea-sticky-header-issue

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.67.2         |
| react-native-reanimated              |2.3.1         |
| NodeJS                               |v17.3.0         |
| Java                                 |openjdk version "11.0.13"         |
| Gradle                               |7.2         |

## Affected platforms
I have only been able to test this on an android device both physical and emulator, however it may be present on other devices as well.

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by Latropos** [comment]
Thank you for submitting the issue! It looks that it is already solved in newest version of Reanimated 3:

https://github.com/software-mansion/react-native-reanimated/assets/56199675/feb2e226-894f-4db9-ab9e-32de5b32b051
