### ISSUE TITLE
App crashes when rotateX hooked with useAnimatedGestureHandler

### ISSUE THREAD

**Issue by laraprabhu** [software-mansion/react-native-reanimated#2946]
## Description
I encountered a bug with react-native-reanimated@2.3.1 and react-native-gesture-handler@2.2.0.

When I hook a gesture handler, with rotateX of transform, using `useAnimatedGestureHandler`, the app crashes when the value of rotateX crosses or exactly at 90deg. In android, the app works without any issues, no crashes.

On the other hand, if we set the value of rotateX manually(in a hard coded way) to 90deg or a value nearby 90deg, it renders properly in both IOS and Android.

### Expected behavior
In IOS, the app should not crash when rotateX value comes nearby 90deg or at 90deg, during a gesture event.

### Actual behavior
In IOS, the app is crashing when rotateX value comes nearby 90deg or at 90deg, during a gesture event.

## Demo
https://youtu.be/-JsrVUYVSsM

## Snack or minimal code example
``` Javascript
import React from 'react';

import { Dimensions, StyleSheet } from 'react-native';
import { PanGestureHandler, GestureHandlerRootView } from 'react-native-gesture-handler';
import Animated, { interpolate, useAnimatedGestureHandler, useSharedValue, useAnimatedStyle } from 'react-native-reanimated';

const { height: winHeight } = Dimensions.get('window');

const App = () => {
  const translateY = useSharedValue(0);

  const panGestureEvent = useAnimatedGestureHandler({
    onStart: (_, ctx) => {
      ctx.translateY = translateY.value;
    },
    onActive: (e, ctx) => {
      translateY.value = ctx.translateY + e.translationY;
    },
    onEnd: () => {
      translateY.value = 0;
    }
  });

  const rStyle = useAnimatedStyle(() => {
    const interpolatedRotateX = interpolate(
      translateY.value,
      [0, -winHeight],
      [0, 360],
    );

    console.log(interpolatedRotateX);

    return {
      transform: [
        { perspective: 2500 },
        { rotateX: interpolatedRotateX + 'deg'}
      ],
    };
  });

  return (
    <GestureHandlerRootView>
      <PanGestureHandler onGestureEvent={panGestureEvent}>
        <Animated.View style={[rStyle, styles.container]}>
        </Animated.View>
      </PanGestureHandler>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  container: {
    height: winHeight,
    backgroundColor: 'red'
  }
});

export default App;
```
## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.67.1      |
| react-native-reanimated              |    2.3.1     |
| react-native-gesture-handler             |    2.2.0    |
| NodeJS                               |    v14.17.3     |
| Xcode                                |     12.3    |
| IOS                                 |    14.3     |

## Affected platforms

- [ ] Android
- [x] iOS

**Comment by Latropos** [comment]
I couldn't reproduce your crash neither on Android nor IOS. I suppose it got already solved.

**Comment by Latropos** [comment]
https://github.com/software-mansion/react-native-reanimated/assets/56199675/75287337-6161-4ca2-b89a-8d38b4938043
