### ISSUE TITLE
Using imageViewer with componentDidUpdate

### ISSUE THREAD

**Issue by phillmill** [software-mansion/react-native-reanimated#295]
Hello!

I'm attempting to use dynamic image dimension values in the imageViewer example. I see in the example it uses this to set the bounds.

<pre>
const panLowY = add(
  panUpY,
  multiply(-HEIGHT, add(max(1, this._scale), -1))
);
</pre>

What I want to do is replace the HEIGHT constant (and WIDTH) with custom prop values like this

<pre>
const panLowY = add(
  panUpY,
  multiply(-this.props.imgHeight, add(max(1, this._scale), -1))
);
</pre>

But when the component updates, it seems to be still using the old values as the boundaries. 

I've tried many different things to get this to work, so I'm posting here for some advice! I thought that maybe if I create Animated Values in the constructor like le so:

<pre>
constructor(props) {
  this.imgWidth = new Value(this.props.imgWidth);
  this.imgHeight = new Value(this.props.imgHeight);
}
</pre>

Then set their values when the component updates

<pre>
componentDidUpdate() {
   this.imgWidth.setValue(this.props.imgWidth);
   this.imgHeight.setValue(this.props.imgHeight);
}
</pre>

And reference it the panLowY definition we'd be in businesss!

<pre>
const panLowY = add(
  panUpY,
  multiply(-this.imgHeight, add(max(1, this._scale), -1))
);
</pre>

But unfortunately no luck, am I on the right track?

Thanks

**Comment by jakub-gonet** [comment]
Hey @phillmill,

sorry for the late response

Do you still face this problem or can I close this issue?

**Comment by phillmill** [comment]
@jakub-gonet I worked around it. I wish I could remember what I did, but I can't!

So yeah you can close

**Comment by jakub-gonet** [comment]
That's a pity :c

I'm closing it then, thanks for asking
