### ISSUE TITLE
interpolateColor on Animated.Text stops working

### ISSUE THREAD

**Issue by scaraux** [software-mansion/react-native-reanimated#2957]
## Description

We are using a combination of `useAnimatedStyle`, `interpolateColor` and `withTiming` to animate the color of text-labels on our Bottom Tab Bar.

![IMG_0018](https://user-images.githubusercontent.com/26309761/152706974-60aca5cb-8344-4955-a6e7-f97ea1e8dfb7.jpg)

**On the first few clicks**, while switching tabs a couple times, the text color animation works smoothly. Then it stops interpolating properly and the text only brutally changes color after some delay. We also animate the color of the "svg icon" above that label exactly the same way, and it works perfectly.

I don't believe this has to do with anything related to the Bottom Navigation Bar, and I made sure that no component is unexpectedly re-mounted when it should not.

### Expected behavior

Should always interpolate

### Actual behavior & steps to reproduce

When switching `isFocused` on and off, the interpolation stops working as expected after a couple animations. The text color only jump from the first color to the last (see video)

https://user-images.githubusercontent.com/26309761/152707137-1d92615c-2a48-4e70-94ed-7529b82f7222.mov

## Snack or minimal code example

The following component is defined in our `<TabButton />`, within the `Tab.Navigator`' `tabBar` component.

```
const TabLabel = ({
  label,
  isFocused,
}: {
  label: string;
  isFocused: boolean;
}) => {
  const focusedAnimated = useSharedValue(0);

  useEffect(() => {
    const nb = isFocused ? 1 : 0;
    focusedAnimated.value = withTiming(nb, { duration: 400 });
  }, [isFocused]);

  const textColor = useAnimatedStyle(() => {
    const color = interpolateColor(
      isFocused ? 1 : 0,
      [0, 1],
      [PrimaryColorPalette.MAIN_4, OtherColorPalette.PURPLE],
    );

    return {
      color,
    };
  });

  return (
    <View>
      <Animated.Text style={[TextStyles.body3medium, textColor]}>
        {label}
      </Animated.Text>
    </View>
  );
};
```

## Package versions

2.4.0

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.66.3       |
| react-native-reanimated       2.4.0       |         |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by huynq1175** [comment]
same here

**Comment by MikeSpitz** [comment]
Did anyone get anywhere with this? 😢
