### ISSUE TITLE
runOnJs crashes the entire app on Android

### ISSUE THREAD

**Issue by ovidiuwin** [software-mansion/react-native-reanimated#2963]
## Description

runOnJs function called inside the useAnimatedGestureHandler hook caused the app to crash entirely on Android. I know this has been discussed [here](https://github.com/software-mansion/react-native-reanimated/issues/1393) already but the bug is still happening. Maybe this is not a bug and I'm doing something wrong (I'm not very experienced with react native)

### Expected behavior

Run the function without crashing the app

### Actual behavior & steps to reproduce
I made a simple Modal component with the functionality to close the modal when dragging from the top. 
Steps: Run the snack on Android -> Open the modal then try to close it by dragging down from the top of the modal contents.

## Snack or minimal code example
https://snack.expo.dev/@ovidiu1207/modal_with_pangesture

## Package versions
Check snack

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by RayVR** [comment]
you are not passing setIsOpen or isOpen into ModalContent component.

**Comment by ovidiuwin** [comment]
> you are not passing setIsOpen or isOpen into ModalContent component.

Oh wow, I feel so stupid for not seeing that 🙈  Thanks! This issue can be closed then.
