### ISSUE TITLE
Animated props do not work on images on IOS

### ISSUE THREAD

**Issue by maidul98** [software-mansion/react-native-reanimated#2974]
### Discussed in https://github.com/software-mansion/react-native-reanimated/discussions/2973

<div type='discussions-op-text'>

<sup>Originally posted by **maidul98** February  8, 2022</sup>
When i updated the shared value holding an URI to an image, the update doesn't change the image.

```
  const sharedHeaderSize = useSharedValue(185); 
  const img = useSharedValue("https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"); 

  const props = useAnimatedProps(()=>{
    return {
      source: {uri: img.value}
    }
  }, [img])

  return (
    <View style={{marginTop: 100}}>
      <TouchableOpacity onPress={() => img.value = "https://www.pngkit.com/png/full/119-1198978_mono-sound-wave-waveform-track.png"}><Text>Click here</Text></TouchableOpacity>
      <Animated.Image animatedProps={props} style={{height: 120, width: "100%"}}/>
    </View>
  );

```

When you click the text, it updates the shared value but the prop doesn't update so the image stays the same
Issue reproduced here: https://snack.expo.dev/@maidul98/reanimated-2 </div>

**Comment by wintermaples** [comment]
I have checked below code (changed maidui98's code), works correctly on android(expo-go) but doesn't work on web(snack).
```
import React, { useEffect } from 'react';
import {
  Text,
  View,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Button,
} from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withTiming,
  useAnimatedScrollHandler,
  withSpring,
  useAnimatedProps,
} from 'react-native-reanimated';

export default function App() {
  const sharedHeaderSize = useSharedValue(10);
  const img = useSharedValue(
    'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
  );
  const [a, setA] = React.useState(0);

  // useEffect(()=>{
  //   transY.value = "dwddwddeef d"
  //   console.log(transY)
  // }, [])

  const props = useAnimatedProps(() => {
    return {
      source: { uri: img.value },
    };
  });

  const style = useAnimatedStyle(() => {
    return {
      height: sharedHeaderSize.value,
      width: sharedHeaderSize.value
    };
  });

  return (
    <View style={{ marginTop: 100 }}>
      <TouchableOpacity
        onPress={() =>
          (img.value =
            'https://www.pngkit.com/png/full/119-1198978_mono-sound-wave-waveform-track.png')
        }>
        <Text>HELLO</Text>
      </TouchableOpacity>
      <Button
        onPress={() => {
          sharedHeaderSize.value = 200;
        }}
        title="hoge"
      />
      <Animated.Image
        animatedProps={props}
        style={[{ width: '100%' }, style]}
      />
    </View>
  );
}
```

**Comment by maidul98** [comment]
Yeah bug exists on IOS, not sure why

**Comment by coneforapine** [comment]
I don't think there's a reason for using this package for updating image sources. Try using `useState` with a boolean and give the URL conditionally. That way react should know when to re-render your image component.

**Comment by andrewdang17** [comment]
@coneforapine it is still a valid question that I would like to know the answer to. Maybe they are building an video frame scrubber that needs to update images quickly

**Comment by karlmarxlopez** [comment]
This is is still happening when you animate the `blurRadius` prop

**Comment by luisfuertes** [comment]
Same error over here on iOS device

**Comment by gtokman** [comment]
I solved this with a library I made for images: https://github.com/candlefinance/faster-image

```
const AnimatedImage = Animated.createAnimatedComponent(FasterImageView)

  const animatedProps = useAnimatedProps(() => {
    return {
      url: image.value,
    }
  })
  ```

**Comment by huschu** [comment]
Both of the original snack (https://snack.expo.dev/@maidul98/reanimated-2) and the one from @wintermaples don't work on any of the platforms (anymore?) which makes me wonder if this is just not supported. Would be nice to have an answer to this.

**Comment by szydlovsky** [comment]
@huschu hey. Yeah, Reanimated isn't a library specifically for handling images and their sources. `useAnimatedProps` is meant to be used with props that take part in animations. Just as @coneforapine mentioned:


> I don't think there's a reason for using this package for updating image sources. Try using `useState` with a boolean and give the URL conditionally. That way react should know when to re-render your image component.

we also think that using this hook for changing image source is definitely an overkill. Seems like @gtokman's library can help if anyone fancies to still do it [this way](https://github.com/software-mansion/react-native-reanimated/issues/2974#issuecomment-1628092308).
