### ISSUE TITLE
transform styles not affecting Animated.View when using LayoutAnimation on the same element

### ISSUE THREAD

**Issue by masarbazi** [software-mansion/react-native-reanimated#2975]
## Description
`transform` style is not taking effect when using `style` prop along with `entering` animation on the same `Animated.View`.
 * However this problem could be resolved by wrapping `Animated.View` by another parent `Animated.View` and defining entering prop on that, this report is just FYI.

## what's happening vs. expected behavior
Entering animation works but not taking effect by transform style prop.
![github-reanimted-issue-report](https://user-images.githubusercontent.com/29546473/153130925-2bad9716-28bd-451c-9063-24fd6246d93b.png)

## Minimal code example
```javascript
   ...
    <Animated.View
      style={{
        transform: [
          {perspective: 1000},
          {rotateZ: '10deg'},
          {scale: 0.85},
          {rotateX: '10deg'},
        ]
      }}
      entering={RollInLeft} // none of above styles are working because of this guy here.
     >
         ... 
```

## Snack
Expo sdk 43 installs reanimated 2.2.0 which does not support layout animations, so couldn't produce issue there but here is the code: 
[Snack (Just code)](https://snack.expo.dev/@masarbazi/reanimated_2975)

## Package versions
react-native 65.1
react-native-reanimated 2.4.1
nodejs 16.13.2

## Affected platforms
Just using Android here. don't know if other platforms are affected.

**Comment by Latropos** [comment]
Both Android and IOS are affected

**Comment by Latropos** [comment]
The suggested solution is to add a wrapper with entry/exit animation, we have also added an extra warning to inform users about this behaviour
