### ISSUE TITLE
Maven plugin has been deprecated, and flipper is an issue.

### ISSUE THREAD

**Issue by CTOverton** [software-mansion/react-native-reanimated#2984]
## Description

In reference to #703, I know that in Reanimated v2 this issue has been resolved. And I know support of Reanimated v1 has also been deprecated.

That being said I've run into a frustrating issue to say the least. I'm using a library that relies on Reanimated v1. That being said since the maven issue has not been resolved in v1 I can't get my project to build. 

Is it easy enough to resolve the maven plugin issue in Reanimated v1? 
[Gradle Migration of Maven docs](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html?_ga=2.75635734.285909718.1643309427-1875229636.1643309427#removal_of_the_legacy_maven_plugin)

I know this is a bigger ask but I know I speak for my whole team when I say we would seriously appreciate it!

### Expected behavior

Reanimated v1 should build in Android with gradle versions 7+ by removing maven plugin.

### Actual behavior & steps to reproduce

Use Reanimated v1.13.3 in an Android project with gradel version 7.2 or higher.

## Snack or minimal code example

1. Create a new react native project
2. `yarn add react-native-reanimated@1.13.3`
3. Edit `android/gradle/wrapper/gradle-wrapper.properties` 
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
```
4. Sync gradle and you will see
```
A problem occurred evaluating project ':react-native-reanimated'.
> Plugin with id 'maven' not found.
```

https://snack.expo.dev/@ctoverton/e81f96

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.67.1         |
| react-native-reanimated              |1.13.3         |
| NodeJS                               |v16.13.1 |
| Xcode                                |13.2.1         |
| Java                                 |11.0.11         |
| Gradle                               |7.2-all         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by CptMaumau** [comment]
@CTOverton in react-native-reanimated's `build.gradle` comment/remove line `apply plugin: 'maven'` and also the `repositories.mavenDeployer` block then run `npx patch-package react-native-reanimated`.
