### ISSUE TITLE
addListener feature is missing

### ISSUE THREAD

**Issue by nomi9995** [software-mansion/react-native-reanimated#299]
addListener feature is missing. that is implemented in Animated core but not in Reanimated. by the way this is awesome library only this feature is missing

**Comment by wcandillon** [comment]
You can use `call()` instead. See this example: https://github.com/wcandillon/can-it-be-done-in-react-native/blob/44309bc70ab488754c798e6527bd55f0ce1e67c4/season2/learnji/components/Translation.tsx

**Comment by nomi9995** [comment]
@wcandillon yeah, I know call. but i am not satisfied by call. I want to add the listener in componentDIdMount. so I can test the same example from core Animated

**Comment by osdnk** [comment]
I don't think it's a feature we want to include and it's not in the scope of the library.

**Comment by grnkvch** [comment]
It will be great upgrade call callback with more arguments, because original listener also has layout information in arguments, it provides comfort way to avoid manipulation with onLayout events and etc.

**Comment by danieloi** [comment]
I wanted this feature so I could fire a function, once the animation is stopped or ends. 

I discovered Animation.start() takes a callback as an argument that does just that 🥳

**Comment by chj-damon** [comment]
@danieloi I'm sorry, but what do you mean about `Animation.start()`? I cannot find any information about this method on the doc.
