### ISSUE TITLE
Not working with Fabric on iOS

### ISSUE THREAD

**Issue by oblador** [software-mansion/react-native-reanimated#2991]
## Description

Using latest Reanimated (2.4.1) together with the current 0.68 release candidate is not working with the new architecture/fabric enabled on iOS. 

### Expected behavior

The app compiles with the `USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1` flags. 

### Actual behavior & steps to reproduce

The app fails to compile with the error:
```
'react/config/ReactNativeConfig.h' file not found
```

## Snack or minimal code example

```bash
npx react-native init ReanimatedFabric --version 0.68.0-rc.1
cd ReanimatedFabric
yarn add react-native-reanimated@2.4.1
cd ios
USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
yarn ios
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.68.0-rc.0, 0.68.0-rc.1        |
| react-native-reanimated              | 2.2.4, 2.4.1        |
| NodeJS                               | 16.14.0        |
| Xcode                                |  13.2.1       |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello! We're actively working on porting Reanimated to Fabric but it's not completely ready yet. In fact, Reanimated integrates quite closely with the renderer system so we need to rewrite some parts specifically for Fabric and that's exactly what we have been doing for the past few months.

The good news is that in parallel we're porting react-native-gesture-handler and react-native-screens to Fabric as well so hopefully the developers will be able to enable Fabric in their apps as soon as possible.

**Comment by nomi9995** [comment]
https://github.com/software-mansion/react-native-reanimated/discussions/2880

I also opened discussion for nightly release support but now new architecture has shipped

**Comment by alantoa** [comment]
Same issue.
I upgrade `react-native-reanimated` to `v2.6.0` still has issue.

**Comment by Tjerk-Haaye-Henricus** [comment]
Issue still exists with the latest version

**Comment by nomi9995** [comment]
@alantoa @Tjerk-Haaye-Henricus they are actively working on it you can check the Fabric branch https://github.com/software-mansion/react-native-reanimated/tree/fabric

**Comment by Tjerk-Haaye-Henricus** [comment]
Amazing :)  Thanks a thousand times for that information 🙏
btw: i really really in love with your work and i'm using all of your rn repos inside of several projects 🤓

**Comment by mikeislearning** [comment]
FYI this does still seem be happening with react-native 0.68.1 and react-native-reanimated 2.8.0. I really appreciate all the hard work you guys are doing!

**Comment by PrinceUBS** [comment]
> FYI this does still seem be happening with react-native 0.68.1 and react-native-reanimated 2.8.0. I really appreciate all the hard work you guys are doing!

+1

**Comment by ahmadzraiq** [comment]
Any update?

**Comment by mikeislearning** [comment]
@ahmadzraiq They announced that version 3 should resolve this: https://blog.swmansion.com/announcing-reanimated-3-16167428c5f7

**Comment by dutradotdev** [comment]
any update? i am having this issue

**Comment by dutradotdev** [comment]
@mikeislearning "If you’d like to try running Reanimated on the new Fabric architecture, make sure that you are using at least version 0.69 of React Native"

so it's not working for expo SDK 45, right? (Expo SDK 45 uses v0.68.2)

**Comment by Tjerk-Haaye-Henricus** [comment]
> any update? i am having this issue

Version 3 is coming 😏  and hopefully solving this issue.

https://github.com/software-mansion/react-native-reanimated/releases/tag/3.0.0-rc.0

**Comment by dutradotdev** [comment]
what about expo projects? https://github.com/software-mansion/react-native-reanimated/issues/2991#issuecomment-1134626618 @Tjerk-Haaye-Henricus

**Comment by hannojg** [comment]
@dutradotdev

> so it's not working for expo SDK 45, right? (Expo SDK 45 uses v0.68.2)

yes, this is correct.

**Comment by maxperry** [comment]
I'm still getting `'react/config/ReactNativeConfig.h' file not found` when building react-native v0.68.2 with v3.0.0-rc.0 and Fabric enabled. 

Could you anyone confirm that v3.0.0-rc.0 is supposed to work with Fabric enabled?

**Comment by hannojg** [comment]
@maxperry Yes, but only with using RN 0.69, where you have the new arch enabled.

**Comment by skurgansky-sugarcrm** [comment]
we got RN 0.69 released but the error 'react/config/ReactNativeConfig.h' file not found is still here

**Comment by piaskowyk** [comment]
If you want to use Fabric in your app you need to install Reanimated 3, but if you just want to use react-native@0.69 you should use Reanimated 2.9.1

**Comment by WNemencha** [comment]
What if 0.68.2 (expo 45) is a hard requirement and the app depends on reanimated?

**Comment by tomekzaw** [comment]
Hey all, just wanted to sum up the discussion and close the issue since it was resolved with the release of 3.0.0-rc.0, which is the very first version that supports the new React Native renderer, Fabric. 🎉 

If you’d like to try running **Reanimated on the new Fabric architecture**, you need to upgrade to React Native 0.69 (or newer) and install Reanimated 3.0.0-rc.0 (or newer). Note that it will not work with Reanimated 2.x or React Native 0.68.x. For more details, check out [this blog post](https://blog.swmansion.com/announcing-reanimated-3-16167428c5f7).

If you want to use **Reanimated on the old Paper architecture**, you can still use version 2.x and React Native 0.64+. However, if you don't use old Reanimated 1 API, we encourage you to upgrade to Reanimated 3 (which is fully-compatible with Reanimated 2 API and built from sources on both platforms).

Currently (as of July 2022), Expo SDK does not support Fabric yet. Expo SDK 45 includes react-native 0.68.2 and react-native-reanimated 2.x which does not support Fabric.

**Comment by fawad-khalil** [comment]
I am getting this error on RN v0.70.1 with new architecture and fabric enabled.  I have installed `3.0.0-rc.2` version of reanimated. Tried re-install node_modules, and pods. Also tried deleting pod lock file and cleaning build from XCode, but didn't help. @tomekzaw

**Comment by tomekzaw** [comment]
@fawad-khalil Can you try removing `ios/build` folder of your app?

**Comment by shahmeer-ali** [comment]
> I am getting this error on RN v0.70.1 with new architecture and fabric enabled. I have installed `3.0.0-rc.2` version of reanimated. Tried re-install node_modules, and pods. Also tried deleting pod lock file and cleaning build from XCode, but didn't help. @tomekzaw

So any solution so far making Reanimated to work with Fabric?

[screenshot](https://imgur.com/a/MF57DD8)

**Comment by tomekzaw** [comment]
> So any solution so far making Reanimated to work with Fabric?

Hey, Reanimated works with Fabric. If it doesn't work for you in your app, this is probably an issue with your configuration or setup.

@shahmeer-ali Have you tried any steps that worked for other people?
- https://github.com/software-mansion/react-native-reanimated/issues/3316#issuecomment-1169065858
- https://github.com/facebook/react-native/issues/33522#issuecomment-1216563652

**Comment by Commaando** [comment]
@tomekzaw 
 Invalid `RNReanimated.podspec` file: [react-native-reanimated] Reanimated 3.2.0 supports the New Architecture only on the latest minor release of React Native. Please upgrade to React Native 0.72.0+ or downgrade to an older version of Reanimated v3.


I am getting this message . only thing i did was new react native init , and pod install with fabric, and then installed reanimated all . by default react native is coming with .71 version. and reanimated asks for .72, i think its not stable yet so is there any solution to this.

**Comment by tomekzaw** [comment]
@Commaando Yeah, Reanimated 3.1.0 and 3.2.0 support Fabric only with React Native 0.72 which is not stable yet (currently latest pre-release is 0.72.0-rc.5). Sorry for this, we were just too fast. If you really need to use Reanimated with React Native 0.71, please use `react-native-reanimated@3.0.2`.

**Comment by Commaando** [comment]
@tomekzaw thanks it works fine now .
