### ISSUE TITLE
[Web] LayoutAnimation does not work on the web

### ISSUE THREAD

**Issue by thespacemanatee** [software-mansion/react-native-reanimated#2993]
## Description
`LayoutAnimation` doesn't work on the web, even with the simplest example.

### Expected behavior
Component and layout should be animating on entering and exit.

### Actual behavior & steps to reproduce
Nothing happens.

## Snack or minimal code example
```js
<Animated.View
  key={`${card.suit}${card.value}`}
  entering={ZoomIn}
  exiting={ZoomOut}
  layout={Layout}
  style={styles.playedCardContainer}
>
    <PlayingCard />
</Animated.View>
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.64.3     |
| react-native-reanimated              |    2.4.1     |
| expo                                 |     44.0.6    |

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by piaskowyk** [comment]
Yes, the layout animation for the web hasn't been implemented yet. We will work on this in the future but I am not able to say when specific, unfortunately. 😕

**Comment by thespacemanatee** [comment]
@piaskowyk thank you for replying, much appreciated! Currently, I can polyfill layout change animations using useEffect and animated styles but I haven't found a way to do replicate the onExit functionality yet.

**Comment by maitriyogin** [comment]
could you share what you did with the polyfill?
Huge thanks,
Stephen.

**Comment by szado** [comment]
@piaskowyk Are there any updates on this topic? 
Information in docs about unsupported layout animations on web would be helpful. There is no even a warning in console when you trying to use reanimated with expo on web.

**Comment by nthh** [comment]
@piaskowyk Any updates or help needed here?
