### ISSUE TITLE
OnPress not working when used with useAnimatedProps

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#2995]
## Description

Using `onPress` alongside `animatedProps` with a `RectButton` from **react-native-gesture-handler**  does not work.
Pressing the button does not trigger the `onPress`

I also tried passing `onPress` as a worklet to `animatedProps` but it crashes the app.

```ts
function onPressWl() {
        'worklet'
        runOnJS(onPress)()
    }
```

One way around this is to wrap the RectButton inside a `GestureDetector`.

### Expected behavior

Should trigger the `onPress`

### Actual behavior & steps to reproduce

Ripple appears but onPress is not triggered. Follow Snack to reproduce

## Snack or minimal code example

```ts
import React from 'react'
import { RectButton } from 'react-native-gesture-handler'
import Animated, {
    useAnimatedProps,
    useSharedValue
} from 'react-native-reanimated'

const AnimatedButton = Animated.createAnimatedComponent(RectButton)

const Test = function () {
    const enabled = useSharedValue<boolean>(true)

    const animatedProps = useAnimatedProps(() => {
        return {
            enabled: enabled.value
        }
    }, [])

    const onPress = () => {
        console.log('Pressed')
    }

    return (
        <AnimatedButton
            style={{
                width: 100,
                height: 50,
                backgroundColor: 'red'
            }}
            animatedProps={animatedProps}
            onPress={onPress}
        />
    )
}
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.66.4     |
| react-native-reanimated              |   2.4.0      |
| react-native-gesture-handler                               |   2.2.0      |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by thongle12** [comment]
Do you address this problem? @Andarius
