### ISSUE TITLE
useAnimatedStyle with transform crashes the app

### ISSUE THREAD

**Issue by coneforapine** [software-mansion/react-native-reanimated#3000]
## Description
I was trying to create a collapsable jumbotron for my app but whenever I use `useAnimatedStyle` with the combination of `useAnimatedScrollHandler` the app crashes without any logs whatsoever. I'm getting these crashes both on iOS and android.

### Expected behavior
Not to crash.
### Actual behavior & steps to reproduce
Provided in snack
## Snack or minimal code example
https://snack.expo.dev/bXKLBIm4b

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      0.66.4   |
| react-native-reanimated            |  ^2.3.1          |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by jangsoori** [comment]
Try using `interpolate` instead of `interpolateNode`.  

```js
const translateY = interpolate(scrollPosition.value, 
       [-320, 0, 320, 320 + 1],
       [-320 / 2, 0, 320 * 0.75, 320 * 0.75],
    );
```

**Comment by coneforapine** [comment]
That didn't work. Also removing the interpolation altogether and giving `translateY` a constant value also crashes. I assume there's something wrong with `useAnimatedStyle`.

**Comment by coneforapine** [comment]
I couldn't run it on snack probably because of the expo, but trying on `reanimated-2-playground` works fine. I tested both with 2.4.1 and 2.3.1. It looks like it's crashing because I used `interpolateNode`. Thank you

**Comment by chanphiromsok** [comment]
> Hey, unfortunately, you can't mix Reanimated v1 with v2. You should use `interpolate` instead of `interpolateNode`. I noticed that you mentioned that this issue still occurs even if you use `interpolate`. I have already checked this and this works for me, could you check this example on the newest version 2.4.1, and let me know if it works?
> 
> code

you are right react-native-reanimated v2 make me confused when you use ```interpolateNode``` inside ```useAnimateStyle``` it will crash with ```useShareValue ``` so i use ```interpolate``` instead of ```interpolateNode```



here is my working example react-native-reanimatedv2
```typescript
const shareValue = useSharedValue(0);
const animateStyle = useAnimatedStyle(() => {
        return {
            height: device.height,
            transform: [
                {
                    translateY: interpolate(
                        shareValue.value,
                        [0, 1],
                        [0, -device.height * 0.28],
                        Extrapolate.CLAMP
                    )
                }
            ]
        };
    });
```
