### ISSUE TITLE
No field isChromeDebugger of type Z in class Lcom/swmansion/reanimated/Utils; or its superclasses

### ISSUE THREAD

**Issue by MahmudHasanMenon** [software-mansion/react-native-reanimated#3010]
I am developing a React Native project using jitsi-meet SDK 5.0.0. Everything is working fine but when i use jitsi-meet SDK 5.0.0 i got this error when app run and crash.

`No field isChromeDebugger of type Z in class Lcom/swmansion/reanimated/Utils; or its superclasses `

![Screen Shot 2022-02-17 at 5 59 45 pm](https://user-images.githubusercontent.com/29507500/154477554-bb304444-58d4-43ef-bf54-9c659e8e509f.png)

**Step to reproduction:**

`I can't share my project repo as it is private. But here is some step you can regenerate the issue.`

1. Create a fresh React-native(0.66.4) project
2. install react-native-jitsi-meet(2.2.0) and add android configuration.
3. install react-native-reanimated(2.4.1) and add android configuration
4. install react-native-gesture-handler and other peer dependency

then in android/build.gradle add custom jitsi-meet SDK(5.0.0) location. My one is like below
`maven {
             url "file:/Users/localadmin/DefaultJitsi"  
        } `

here is my custom SDK

[jitsiMeetSdk](https://drive.google.com/drive/folders/1YIEAZFsfNrELpgWCNy3eZPrarMTPwjnf?usp=sharing)

please download the SDK from google drive and place it any location of your pc ( my one macOS).

### Expected behavior
 App should not crash on opening.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      0.66.4   |
| react-native-reanimated              |   2.4.1      |
| NodeJS                               |     16.14.0    |
| react-native-jitsi-meet                                |    2.2.0     |
| Java                                 |     java 13.0.1    |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [ ] Android

**Comment by piaskowyk** [comment]
It looks like proguard configuration Issue. Could you try to disable proguard name shadowing for reanimated Utils class?
