### ISSUE TITLE
Crash developing while adding a exiting LayoutAnimation

### ISSUE THREAD

**Issue by henrymoulton** [software-mansion/react-native-reanimated#3014]
## Description

Simulator crash when adding a `SlideInDown` exiting LayoutAnimation. `FadeOut` work fine.

### Expected behavior

No Crash

### Actual behavior & steps to reproduce

Simulator crashes with 

```
Exception in HostFunction: Javascript worklet error
Error: Javascript worklet error
at workletValueSetter (native)
at startAnimationForTag (react-native-reanimated/src/reanimated2/layoutReanimation/LayoutAnimationRepository.ts (7:8):1:1222)
Error: Exception in HostFunction: Javascript worklet error
Error: Javascript worklet error
at workletValueSetter (native)
at startAnimationForTag (react-native-reanimated/src/reanimated2/layoutReanimation/LayoutAnimationRepository.ts (7:8):1:1222)
at workletValueSetter (native)
at startAnimationForTag (-native-reanimated/src/reanimated2/layoutReanimation/LayoutAnimationRepository.ts (7:8):1:1222)
abort() called


Kernel Triage:
VM - pmap_enter failed with resource shortage
```

## Snack or minimal code example

```
{!isVisible && (
        <Animated.View
          entering={SlideInDown.delay(DELAY)
            .duration(1500)
            .easing(Easing.bezier(CURVE))}
          exiting={SlideInDown}
        >
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.64.2     |
| react-native-reanimated              |    2.4.1     |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by FilipeAraujo** [comment]
@henrymoulton I don't know if you already fixed this but try adding `SlideOutDown`. There are `In` and `Out` animations.

**Comment by Latropos** [comment]
Seems that you've accidentally added exiting animation instead of entering, you can fix the problem applying the suggestion above.

**Comment by suwu150** [comment]
@FilipeAraujo any update?
