### ISSUE TITLE
Animation on SectionList elements does not always run

### ISSUE THREAD

**Issue by TomCorvus** [software-mansion/react-native-reanimated#3020]
## Description

👋 Hi,

I created a component to display items smoothly in SectionList but sometimes some items don't display. They exist, you can click on it but the opacity animation didn't run or this is a buggy display.

### Expected behavior

Items appear.

### Actual behavior & steps to reproduce

Scroll faster on snack example. Sometimes, items don't display. You can click on it (see console.log) but you can't see them.
The example is simple but it appears more frequently on my app where items and style are more complex.
Maybe I do something wrong but how can I avoid this?
This is not specific to the SectionList, it can appear on other element wrapped by AnimatedOpacity and when there are several of these elements. (multiple animation)

https://user-images.githubusercontent.com/3451011/154960679-43d4fa2c-b2d7-4ad4-a096-bd7395fbaabf.mov

## Snack or minimal code example

https://snack.expo.dev/@tom.corvus/reanimated-smoothy-display

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      ~0.66.4   |
| react-native-reanimated              |    ~2.4.1     |

## Affected platforms

- [x] Android
- [x] iOS

**Comment by szydlovsky** [comment]
The issue seems to be fixed in the v3 newer versions:)
