### ISSUE TITLE
[TS] Improper ref type of components in Animated namespace

### ISSUE THREAD

**Issue by DrRefactor** [software-mansion/react-native-reanimated#3023]
## Description

It seems issue https://github.com/software-mansion/react-native-reanimated/issues/2005 is relevant again.

E.g. ScrollView class is exported as:
https://github.com/software-mansion/react-native-reanimated/blob/main/react-native-reanimated.d.ts#L268

Actual ScrollView implementation does not expose getNode() though, causing crash when trying to call it.

### Expected behavior
Types are correct, extending base RN ScrollView type. Allowing to type-safely call ref.scrollTo().

### Actual behavior & steps to reproduce
Types are incorrect:
```
const ref = useRef<Animated.ScrollView>(null);
(...)
const node = ref.current?.getNode(); // fine TS-wise, but crashes
conse node2 = ref.current?.scrollTo(); // TS error, but works fine in runtime
```

## Snack or minimal code example

See above.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native-reanimated                     | 2.3.1 |

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by Latropos** [comment]
Closing, since we have rewritten our typescript types, which means that this issue got outdated.
