### ISSUE TITLE
useAnimatedReaction does not trigger when used with onLayout

### ISSUE THREAD

**Issue by AcidNoX** [software-mansion/react-native-reanimated#3024]
## Description

I'm attempting to build a horizontally scrollable tabs component using reanimated 2. The active tab should be centered by default. To do this, I need to measure all of the tabs to know how much to translate the container view, ie the "track"

To position the track correctly on the first render and also to know how much to translate based on the current tab index, I'm storing an array of { index: number, width: number} using a shared value:
```jsx
const widths = useSharedValue<Array<{ index: number; width: number }>>([]);
```

I'm updating this shared value using the onLayout event:

```jsx
const tabs = [
  {
    name: "Skin",
  },
  {
    name: "Hair style",
  },
  {
    name: "Hair color",
  },
  {
    name: "Facial hair",
  },
  {
    name: "Coat",
  },
];

...


{tabs.map((tab, index) => (
  <Animated.View
    key={tab.name}
    style={styles.tabItem}
    onLayout={(e) => {
      console.log("ON LAYOUT", widths.value.length);
      widths.value.push({ index, width: e.nativeEvent.layout.width });
    }}
  >
    <Text style={styles.text}>{tab.name}</Text>
  </Animated.View>
))}
```
And then updating the position using useAnimatedReaction:
```jsx
const scrollToIndex = (index: number) => {
  "worklet";

  // ...omitted for brevity 
};

useAnimatedReaction(
  () => {
      console.log("PREPARE ");
      return widths.value;
  },
  (res) => {
    console.log("REACTING", res);
    if (res.length < 1) return;

    scrollToIndex(0);
  }
);
```
I'm expecting to see the "prepare" and "react" functions execute either after each time `width.value` is mutated OR once after all onLayouts have finished executing. In reality, the animated reaction is only executed once before any of the onLayout functions run (see expected behavior below).

I'm not sure if this because I'm not updating the reference of the shared value? I've tried `widths.value = [...widths.value, ({ index, width: e.nativeEvent.layout.width })` but has a race condition issue where each onLayout event overwrites the previous value.

I feel like measuring a list of elements and storing that information is a pretty common use case so I'd be really grateful if someone can tell me if I'm doing anything wrong! :)

Thanks,

Lee

### Expected behavior
EXPECTED CONSOLE OUTPUT:
```
PREPARE 
REACTING Array []
ON LAYOUT 0
ON LAYOUT 1
ON LAYOUT 2
ON LAYOUT 3
ON LAYOUT 4
PREPARE 
REACTING Array [...]
```
### Actual behavior
ACTUAL CONSOLE OUTPUT:
```
PREPARE 
REACTING Array []
ON LAYOUT 0
ON LAYOUT 1
ON LAYOUT 2
ON LAYOUT 3
ON LAYOUT 4
```
### Steps to reproduce

1. Create a shared array value.
2. Render a list of Views
3. Add an onLayout handler to those views
4. In the handler, add an object (containing the width and index) to the shared value array.
5. Add useAnimatedReaction.
6. In the prepare function, return the shared value.
7. Add some kind of debug to observe that the "prepare" and "react" functions do not execute when the shared value is mutated.

## Snack or minimal code example

https://github.com/AcidNoX/use-animated-reaction-repro

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.64.3         |
| react-native-reanimated              | 2.3.2        |
| NodeJS                               |16.13.2         |
| Xcode                                | 13.2.1         |
| Java                                 | openjdk version "11.0.11"        |
| Gradle                               |what ever expo uses         |
| expo                                 | 44.0.0        |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by AcidNoX** [comment]
Hi all, any chance of some kind of update on this please? - Having used useAnimatedReaction a little more in the past 6 weeks it feels relatively flakey - Multiple times I've tried using it, it has not executed the prepare or reaction functions when animated properties have mutated.

Any kind of feedback would be appreciated, especially if it's something I'm doing wrong!
Thanks in advance, Lee.

**Comment by olawalethefirst** [comment]
Hello @AcidNoX  you found a work around for this already, right?

**Comment by claytercek** [comment]
Ran into the same issue, realized this was due to the fact that I was mutating the array instead of creating a new array when updating the shared value. Modifying the onLayout event handler mentioned above with the following should do the trick:

```diff
- widths.value.push({ index, width: e.nativeEvent.layout.width });
+ widths.value = [...widths.value, { index, width: e.nativeEvent.layout.width }];
```

**Comment by piaskowyk** [comment]
I can confirm @claytercek posted correct solution 👏

**Comment by yayvery** [comment]
> I can confirm @claytercek posted correct solution 👏

@piaskowyk as of Reanimated 3.7.0+ this solution no longer works - https://github.com/software-mansion/react-native-reanimated/issues/5735
