### ISSUE TITLE
Package json main points to non existing file in 2.3.2

### ISSUE THREAD

**Issue by byCedric** [software-mansion/react-native-reanimated#3026]
## Description

Hi! It seems that Reanimated v2.3.2 includes a fix for the chrome debugger, but also includes the issue fixed in https://github.com/software-mansion/react-native-reanimated/pull/2962 (released in 2.4.1).

What's happening here is that v2.3.2 includes the `lib/src` folder issue:
- [2.3.1 is compiled properly to `lib/Animated.js`](https://cdn.jsdelivr.net/npm/react-native-reanimated@2.3.1/lib/Animated.js)
- [2.3.2 uses `lib/src/Animated.js`](https://cdn.jsdelivr.net/npm/react-native-reanimated@2.3.2/lib/src/Animated.js) ([package.json still points to `lib/Animated.js`](https://cdn.jsdelivr.net/npm/react-native-reanimated@2.3.2/package.json))

### Expected behavior

Version 2.3.2 causes some weird errors in packages that use reanimated as nested (peer)dependency, e.g. moti. It errors with "module not found", not really explaining the missing entry point well (but that's a node problem).

### Actual behavior & steps to reproduce

![image](https://user-images.githubusercontent.com/1203991/155034751-1d4b37ea-13eb-4139-8181-a1f556c07314.png)

```bash
$ expo init MyApp
$ yarn add react-native-reanimated@2.3.2 # (or just expo install)
$ node --print "require.resolve('react-native-reanimated')"
```

## Snack or minimal code example

https://github.com/byCedric/reanimated-2.3.2-error

Specially crafted by @CodingItWrong, and forked by me to satisfy the thirst of this repro-bot

```bash
$ expo init MyApp
$ yarn add react-native-reanimated@2.3.2 # (or just expo install)
$ node --print "require.resolve('react-native-reanimated')"
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.64.3       |
| react-native-reanimated              |  2.3.2       |
| NodeJS                               | 16.13.1       |
| Xcode                                | -        |
| Java                                 |  -       |
| Gradle                               | -        |
| expo                                 | ^44.0.0 |

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by CodingItWrong** [comment]
The issue actually _does_ have a snippet of code to reproduce the issue.

But if it helps to have a repo, here you go: https://github.com/CodingItWrong/reanimated-2.3.2-error

**Comment by byCedric** [comment]
Friendly ping, it has been a week and version `~2.3.x` is still broken. Expo uses this tilde selector in SDK 44, so for all new Expo users, this is broken. (unless they use a yarn lockfile, or manually pin to an older version)

**Comment by piaskowyk** [comment]
Thanks for report and sorry for my delay :/ 
Should be fixed with: https://www.npmjs.com/package/react-native-reanimated/v/2.3.3

**Comment by byCedric** [comment]
Thanks 😄
