### ISSUE TITLE
Web: Keyframe.js: Cannot read property 'params' of undefined react-native-reanimated/plugin.js:308:36

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion/react-native-reanimated#3027]
### Expected behavior
work
### Actual behavior & steps to reproduce
Web crashing

Maybe the problem is here
```js
  const workletFunction = t.functionExpression(
    t.identifier(name),
    fun.program.body[0].expression.params,
    prependClosureVariablesIfNecessary(
      closureVariables,
      fun.program.body[0].expression.body
    )
  );
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.67.2    |
| react-native-reanimated              |    2.4.1     |
| NodeJS                               |    4.18.1     |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |
| react-native-web.          |  0.17.6 |
| react-scripts                   | 5.0.0

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by Wilson-Lim** [comment]
When will this be fixed ? , or is there alternate solution ? 

currently not working on my rnw project

**Comment by hosseinmd** [comment]
i have a script for this if you want a can share it

**Comment by dcenatiempo** [comment]
another temp solution would be to set your babel versions to the following in the `package.json`:

``` 
  "@babel/core": "7.17.5",
  "@babel/runtime": "7.17.2",
```

**Comment by 467057463** [comment]
i also white this error in react native web
``` bash
TypeError: D:\work\blog_rn_web\node_modules\react-native-reanimated\lib\reanimated2\layoutReanimation\animationBuilder\Keyframe.js: Cannot read property 'params' of undefined
```
