### ISSUE TITLE
Android: onMomentumScrollEnd not working !

### ISSUE THREAD

**Issue by Gorhom** [software-mansion/react-native-reanimated#303]
Hi there 👋

While I was implementing parallax header on my app I have notice that event `onMomentumScrollEnd` on `Animated.ScrollView` it's not been triggered - on **Android Only** - when i pass an `AnimatedEvent`, However when i pass a simple `console.log` it worked 🧐

here is a simple app to reproduce it:

```js
import React, { Component } from "react";
import { SafeAreaView, StyleSheet, Text, View } from "react-native";
import Animated from "react-native-reanimated";

const { event, block, set, cond, eq, Value } = Animated;

const getItems = () => {
  let item = [];
  for (let i = 0; i < 100; i++) {
    item.push(i);
  }
  return item;
};

export default class App extends Component {
  constructor(props) {
    super(props);
    this._scrollY = new Value(0);
  }
  renderContent = () => {
    return (
      <View style={styles.contentContainer}>
        {getItems().map(item => (
          <View key={`item-${item}`} style={styles.itemContainer}>
            <Text style={styles.itemText}>{`item-${item}`}</Text>
          </View>
        ))}
      </View>
    );
  };

  render() {
    return (
      <SafeAreaView style={styles.container}>
        <Animated.ScrollView
          // onMomentumScrollEnd={() => console.log("WORKING HERE")}
          onMomentumScrollEnd={event([
            {
              // @Android : NOT WORKING !
              nativeEvent: ({ contentOffset }) => set(this._scrollY, contentOffset.y)
            }
          ])}
          style={styles.container}
        >
          {this.renderContent()}
          <Animated.View
            style={[
              styles.awesomeHeader,
              {
                transform: [{ translateY: this._scrollY }]
              }
            ]}
          />
        </Animated.ScrollView>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white"
  },
  contentContainer: {
    padding: 12
  },
  itemContainer: {
    marginVertical: 6,
    padding: 6,
    backgroundColor: "#dfdfdf"
  },
  itemText: {
    color: "#000"
  },
  awesomeHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    backgroundColor: "red"
  }
});
```

Thanks

**Comment by jakub-gonet** [comment]
Hi @Gorhom,
I'm really sorry that your issue went unnoticed 😔

I reproduced this issue and it seems that `onMomentumScrollEnd` kinda doesn't work (`onScrollEndDrag` works for example) although your code had one error: you shouldn't mix passing object and function as an argument to `event()` node:
instead of
```
onMomentumScrollEnd={event([{
// @Android : NOT WORKING !
  nativeEvent: ({ contentOffset }) => set(this._scrollY, contentOffset.y)}
])}
```

you should use:
```
 onMomentumScrollEnd={
  event([
    {
      nativeEvent: {
        contentOffset: {
          y: this._scrollY,
        },
      },
    },
  ])
}
```
or
```
onMomentumScrollEnd={
  e => this._scrollY.setValue(e.nativeEvent.contentOffset.y)
}
```

(incidentally, first code doesn't work, second does work - probably some bug in RN, I'll investigate it later)

I'm closing this issue, but if you have further questions don't hesitate to ask.

**Comment by anastely** [comment]
Hey @jakub-gonet 
Still didn't work in Andorid
`onMomentumScrollEnd` not triggered,
What I implement, 
next, prev Slider
when I call
`flatListRef.current.scrollToIndex({animated: true, index: 1});` 

`onMomentumScrollEnd` not Triggered in Android "iOS work well"


`onMomentumScrollEnd={(ev) => {
          const newIndex = Math.round(ev.nativeEvent.contentOffset.x / ITEM_WIDTH);
          indexItem.current = newIndex;
          console.log('onMomentumScrollEnd', newIndex); // Not logs!
        }}`

**Comment by jakub-gonet** [comment]
@anastely, please open a new issue if you have a small and working repro for this, comments on closed issues are easily missed.

**Comment by trickeyd** [comment]
I have just hit this issue too.

**Comment by netojose** [comment]
Still happening with me now

**Comment by arasrezaei** [comment]
wow, still not working!

**Comment by KennyCallegari** [comment]
I've just had an issue with `onMomentumScrollEnd` and I have a similar case as @anastely : I need to get the visible item index.

I used `onViewableItemsChanged` to bypass the issue : 
```
const onViewableItemsChanged = ({ viewableItems }: { viewableItems: ViewToken[]}) => {
  const newIndex = viewableItems[viewableItems.length - 1]?.index || 0

  onItemIndexChange(newIndex)
}
```

This works fine on Android and iOS for me, I hope it can help some of you.

I'm sorry for everyone who want the exact `contentOffset.x` or `y`, I don't have a solution for that. I hope they re-open this thread.
