### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by hardikcc** [software-mansion/react-native-reanimated#3031]
## Description

I am using reanimated as dependancy to react-native-navigation. Due to compatibility issue with other plugin, I had to downgrade RN version to 0.62.2. I am getting the below error on application startup (iphone 11 simulator). In this place, it has to load login screen. I can see the login screen if I press dismiss, but on entering any input, same error come back.

Unsupported

reanimated::REAIOSErrorHandler::raiseSpec()
    REAIOSErrorHandler.mm:18
reanimated::ErrorHandler::raise()::'lambda'()::operator()()
decltype(std::__1::forward<reanimated::ErrorHandler::raise()::'lambda'()&>(fp)()) std::__1::__invoke<reanimated::ErrorHandler::raise()::'lambda'()&>(reanimated::ErrorHandler::raise()::'lambda'()&)
void std::__1::__invoke_void_return_wrapper<void, true>::__call<reanimated::ErrorHandler::raise()::'lambda'()&>(reanimated::ErrorHandler::raise()::'lambda'()&)
std::__1::__function::__alloc_func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocator<reanimated::ErrorHandler::raise()::'lambda'()>, void ()>::operator()()
std::__1::__function::__func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocator<reanimated::ErrorHandler::raise()::'lambda'()>, void ()>::operator()()
std::__1::__function::__value_func<void ()>::operator()() const
std::__1::function<void ()>::operator()() const
reanimated::REAIOSScheduler::scheduleOnUI(std::__1::function<void ()>)
reanimated::ErrorHandler::raise()
reanimated::NativeReanimatedModule::onEvent(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
invocation function for block in reanimated::createReanimatedModule(RCTBridge*, std::__1::shared_ptr<facebook::react::CallInvoker>)
__33-[REANodesManager dispatchEvent:]_block_invoke
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0

### Expected behavior

It should open login screen.

## Snack or minimal code example
```
import * as React from 'react';
import { DefaultTheme, Provider as PaperProvider } from 'react-native-paper';
// import LoginScreen from './Screens/login';
import AsyncStorage from '@react-native-async-storage/async-storage';
import HomeScreen from './Screens/home';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import LoginScreen from './Screens/login';

const theme = {
    ...DefaultTheme,
    roundness: 2,
    colors: {
        ...DefaultTheme.colors,
        primary: '#0ABFBF',
        accent: '#F76540',
    },
};

export const storeData = async (key, value) => {
    try {
        await AsyncStorage.setItem(key, value);
    } catch (e) {
        // saving error
        console.error(e);
    }
}
// const App = () => {
//   return (
//     <PaperProvider theme={theme}>
//       <LoginScreen />
//     </PaperProvider>
//   );
// };
export const AuthContext = React.createContext();
export default function App({ navigation }) {

    const Stack = createStackNavigator();

    const [state, dispatch] = React.useReducer(

        (prevState, action) => {
            switch (action.type) {
                case 'RESTORE_TOKEN':
                    return {
                        ...prevState,
                        userToken: action.token,
                        isLoading: false,
                    };
                case 'SIGN_IN':
                    return {
                        ...prevState,
                        isSignout: false,
                        userToken: action.token,
                    };
                case 'SIGN_OUT':
                    return {
                        ...prevState,
                        isSignout: true,
                        userToken: null,
                    };
            }
        }, {
        isLoading: true,
        isSignout: false,
        userToken: null,
    }
    );

    React.useEffect(() => {
        // Fetch the token from storage then navigate to our appropriate place
        const bootstrapAsync = async () => {
            let userToken;
            try {
                userToken = await AsyncStorage.getItem('@userToken');
            } catch (e) {
                console.error(e);
            }
            dispatch({ type: 'RESTORE_TOKEN', token: userToken });
        };

        bootstrapAsync();
    }, []);

    const authContext = React.useMemo(
        () => ({
            signIn: async data => {
                var responseData = JSON.parse(data);
                // console.log("Response Data in Signin", responseData);
                var entityMapping = responseData.entityMapping;
                // console.log("Entitymapping", entityMapping);
                var physicianMapping = entityMapping.filter(x => x.ownertype == 8);
                await storeData("@authdata", JSON.stringify(responseData));
                await storeData("@doctorid", physicianMapping[0].ownerid.toString());
                await storeData("@userToken", responseData.token);
                dispatch({ type: 'SIGN_IN', token: responseData.token });
            },
            signOut: () => dispatch({ type: 'SIGN_OUT' }),
            signUp: async data => {
                var userToken;
                dispatch({ type: 'SIGN_IN', token: userToken });
            },
        }), []
    );

    return (< PaperProvider theme={theme} >
        <AuthContext.Provider value={authContext} >
            <NavigationContainer>
                <Stack.Navigator>{state.userToken == null ? (<Stack.Screen name="SignIn"
                            options={
                                {
                                    headerShown: false
                                }
                            }
                            component={LoginScreen}
                        />) : (<Stack.Screen name="Home"
                            component={HomeScreen}

                            options={
                                {
                                    headerShown: false
                                }
                            }/>)}</Stack.Navigator></NavigationContainer>
        </AuthContext.Provider>
    </PaperProvider >
    );
}
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.62.2|
| react-native-reanimated              | 2.3.0|
| NodeJS                               |16.13.2|
| Xcode                                |13.2.1|
| Java                                 |11.0.14|
| Gradle                               |         |
| expo                                 |not used|

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Did you try to update Reanimated to 2.4.1?

**Comment by hardikcc** [comment]
Yes, I created a minimal version of code using react native 0.63, drawer navigation and JITSI. Still getting same error on app load. If I dismiss error, it shows screen but any interaction takes to same error.

**Comment by OshedheMunasinghe** [comment]
I am also having a problem with Drawer navigation. It doesn't work with reanimate. I have also fallowed by this guide https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

**Comment by mistricky** [comment]
Same problem with react-native@0.62.1

**Comment by Stringsaeed** [comment]
downgrading to `2.2.0` made it works
