### ISSUE TITLE
babel plugin add location with absolute location

### ISSUE THREAD

**Issue by charlzyx** [software-mansion/react-native-reanimated#3033]
## Description
after babel plugin used , my js bundle has some code like next line code, with absolute path, 

`open t.__location="/Users/xxxx/project/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx (232:2)` 

however, i'm woring on split react native bundler, this case my split bundle code not same with the common bundle, of course, reanimated is in the common, is it any use ? maybe replace it to relative path if no used.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.67.3     |
| react-native-reanimated              |   2.4.1      |
| NodeJS                               |      16.0   |
| Xcode                                |    -     |
| Java                                 |       -  |
| Gradle                               |      -   |
| expo                                 |       -  |

## Affected platforms

- [ x] Android
- [ x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
This one resolves you issue: https://github.com/software-mansion/react-native-reanimated/pull/3141 🎉
