### ISSUE TITLE
Debug - Navigate from Stack to Drawer

### ISSUE THREAD

**Issue by Rakee08** [software-mansion/react-native-reanimated#3039]
## Description
On debug mode Navigation is not working when navigate from stack navigator to drawer navigator.

### Expected behavior
Should navigate on debug as same as release

### Actual behavior & steps to reproduce
On debug mode navigation not working

## Snack or minimal code example
import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';

import Login from '../screens/Login';
import DrawerNavigator from './DrawerNavigator';

const Stack = createStackNavigator();

const screenOptionStyle = {
  headerStyle: {
    backgroundColor: '#9AC4F8',
  },
  headerTintColor: 'white',
  headerBackTitle: 'Back',
};

const MainStackNavigator = () => {
  return (
    <Stack.Navigator screenOptions={screenOptionStyle}>
      <Stack.Screen name="Home" component={Login} />
      <Stack.Screen name="Drawer" component={DrawerNavigator} /> // Passing Drawer
    </Stack.Navigator>
  );
};

export default MainStackNavigator;

import React from 'react';

import {createDrawerNavigator} from '@react-navigation/drawer';

import About from '../screens/About';
import Home from '../screens/Home';
import Contact from '../screens/Contact';

const Drawer = createDrawerNavigator();

const DrawerNavigator = () => {
  return (
    <Drawer.Navigator>
      <Drawer.Screen name="Home" component={Home} />
      <Drawer.Screen name="About" component={About} />
      <Drawer.Screen name="Contact" component={Contact} />
    </Drawer.Navigator>
  );
};

export default DrawerNavigator;

On press calling navigation.navigate('Drawer') // Working on normal, not working on debug mode

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.66.4     |
| react-native-reanimated              |     2.4.1    |
| NodeJS                               |     17.13.1    |
| Xcode                                |    13.2.1     |
| Java                                 |      1.8.0_292   |

## Affected platforms

- [x] Android
- [x] iOS
- [x ] Web

**Comment by alicjamarciniak** [comment]
I'm having the same issue

**Comment by krisidmisso** [comment]
For me it only crashes in Android debug mode . iOS debug mode works fine. Also android release apk seems to work fine.

@Rakee08 were you able to find a solution?

**Comment by krisidmisso** [comment]
Tried `reanimated` `2.9.1` and `3.0.rc1`. Both have issues. Going back to `react-native-reanimated:"2.2.4"` seems like a temporary workaround
