### ISSUE TITLE
Box shadow not working as expected

### ISSUE THREAD

**Issue by wststone** [software-mansion/react-native-reanimated#3040]
## Description

I am rendering a list of dropdowns, the first time it is rendered, everything seems fine. After opening and closing the dropdown, there are these weird shadow between each dropdown.
<img width="402" alt="2022-03-01 11 22 40" src="https://user-images.githubusercontent.com/42225395/156098928-296c874c-53e4-4103-97dd-40086cb0fab2.png">

### Expected behavior
Not having the shadow on the background after open and closing the dropdown
### Actual behavior & steps to reproduce
Clone the github repo and install dependecies
## Snack or minimal code example
https://github.com/wststone/reanimated-box-shadow-issue

## Package versions
2.3.1 in the example repo, but have the same issue in 2.4.1

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.64.3    |
| react-native-reanimated              |      2.3.1   |
| NodeJS                               |        16.14.0 |
| Xcode                                |       13.12.1 |
| Java                                 |       14.0.2  |
| Gradle                               |    unknown     |
| expo                                 |        44.0 |

## Affected platforms
Only tested in ios simulator

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by Latropos** [comment]
Unable to reproduce the error:

https://github.com/software-mansion/react-native-reanimated/assets/56199675/d0d7aa02-6512-42d7-b9f7-87086ffdb455
