### ISSUE TITLE
Animation not working on web

### ISSUE THREAD

**Issue by rnike** [software-mansion/react-native-reanimated#3057]
## Description

The package seems not working on web, 

using `useSharedValue`, component style not updating when the value is changed

I've added `react-native-reanimated/plugin` to the last element of `bable.confing.js` `plugins` array, is any thing else I've missed?

### Expected behavior

after press on touchable
1. sees `press log` with new value
2. sees `render log` with new value
3. layout updated with animation to new style

### Actual behavior & steps to reproduce

after press on touchable
1.  only sees `press log` with new value
2. `render log` not showing
3. layout is not updating

## Snack or minimal code example

```js
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withSpring,
} from 'react-native-reanimated';

const styles = StyleSheet.create({
  ball: {
    margin: 5,
    width: 30,
    height: 30,
    backgroundColor: 'red',
    borderRadius: 100,
  },
});

export default () => {
  const offset = useSharedValue(1);
  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: -150 + offset.value * 150 }],
    };
  });

  console.log('render log', offset.value);

  return (
    <View style={{ marginTop: 100, alignItems: 'center' }}>
      <TouchableOpacity
        onPress={() => {
          offset.value = withSpring(Math.random());
          console.log('press log', offset.value);
        }}
      >
        <Text>Press to animate</Text>
      </TouchableOpacity>
      <Animated.View style={[styles.ball, animatedStyles]} />
    </View>
  );
};

```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.66.4     |
| react-native-reanimated              |       2.4.1  |
| NodeJS                               |    v14.17.0     |
| Xcode                                |    -     |
| Java                                 |      -   |
| Gradle                               |     -    |
| expo                                 |     -    |

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by piaskowyk** [comment]
Hey @rnike 
You should use `with<Animation>` in a little different way. You can't do something like this `withSpring(Math.random()) + 5` because `withSpring` returns object instead of number. To make it works you should do something like this:
```js
const animatedStyles = useAnimatedStyle(() => {
  return {
    transform: [{ translateX: offset.value }],
  };
});

offset.value = withSpring(-150 + Math.random() * 150);
```
or
```js
const animatedStyles = useAnimatedStyle(() => {
  return {
    transform: [{ translateX: withSpring(-150 + offset.value * 150) }],
  };
});

offset.value = Math.random();
```
or
```js
const animatedStyles = useAnimatedStyle(() => {
  return {
    transform: [{ translateX: withSpring(offset.value) }],
  };
});

offset.value = -150 + Math.random() * 150;
```

**Comment by rnike** [comment]
@piaskowyk Thanks for the reply, I've tried each of the solutions you've provided, but neither did they work, the issue is still the same, the component is not animating.

Also tried my code on iOS, not like on web, the animation works as expected on iOS.

**Comment by rnike** [comment]
I manage it working by adding a useState hook to force the component to rerender

and also useAnimatedStyle should add deps in order to make it's value changed

```diff
+import { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withSpring,
} from 'react-native-reanimated';

const styles = StyleSheet.create({
  ball: {
    margin: 5,
    width: 30,
    height: 30,
    backgroundColor: 'red',
    borderRadius: 100,
  },
});

export default () => {
+  const [state, setState] = useState(true);
  const offset = useSharedValue(1);
  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: withSpring(-150 + offset.value * 150) }],
    };
- });
+ }, [state]);

  console.log('render log', offset.value);

  return (
    <View style={{ marginTop: 100, alignItems: 'center' }}>
      <TouchableOpacity
        onPress={() => {
          offset.value = Math.random();
+          setState(v => !v);
          console.log('press log', offset.value);
        }}
      >
        <Text>Press to animate</Text>
      </TouchableOpacity>
      <Animated.View style={[styles.ball, animatedStyles]} />
    </View>
  );
};
```

but this workaround will not be accepted in our codebase, does anyone know how to fix it?
