### ISSUE TITLE
Animating viewBox with react-native-svg

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [software-mansion/react-native-reanimated#3060]
### Discussed in https://github.com/software-mansion/react-native-reanimated/discussions/2181

<div type='discussions-op-text'>

<sup>Originally posted by **Andarius** July  6, 2021</sup>
Hey ! 
I'm trying to implement a zoom feature on a line chart using `react-native-svg`.
I'm not sure what the best option is, but I was looking into updating the `viewBox` prop to try emulating the zoom.
However, this code does not seem to have any effect:

```
const AnimatedSvg = Animated.createAnimatedComponent(Svg)

 const animatedSvgProps = useAnimatedProps<SvgProps>(() => {
        return {
            viewBox: `${translateX.value} 0 ${animatedWidth.value * scale.value} ${animatedHeight.value}`
        }
    })
<AnimatedSvg animatedProps={animatedSvgProps} />
```

Any ideas on why it's not updating here ?
It works if a re-render happens</div>

I am trying to do that exact same thing. This article shows animating a viewBox on web and trying to achieve the same...

https://www.motiontricks.com/basic-svg-viewbox-animation/

If you scroll down to Final Result you will see it in action.

I understand it can be pulled off with style transform, but it is much harder. Animating the viewBox has many benefits compared to figuring out the math for using a transform style.

I started with something simple, just trying to move the viewBox...

```
.
.
.

const viewBoxX = useSharedValue(0);

// On component mount run animation
useEffect(() => {
  viewBoxX.value = withTiming(1000, {
      duration: 2500,
      easing: Easing.bezier(0.25, 0.1, 0.25, 1)
  });
},[]);

.
.
.

const animatedProps = useAnimatedProps(() => {
   return {
      viewBox: `${viewBoxX.value} 0 1600 767`,
   };
});

.
.
.

// animatedProps should be the viewBox
<AnimatedSvg animatedProps={animatedProps} width={windowWidth} height={windowHeight / aspectRatio} preserveAspectRatio="xMidYMid meet">
  <SvgImage
  href={{uri: imageSource.uri }}
  />	
</AnimatedSvg>

```

Has anyone figured out how to animate the viewBox property in react-native-svg using reanimated2?

**Comment by iGroza** [comment]
same question +1

**Comment by theonetheycallneo** [comment]
same question +1

**Comment by Latropos** [comment]
Hi! You may try using some dedicated libraries to make svg zoom like this one: https://github.com/garblovians/react-native-svg-pan-zoom

**Comment by ericcAtGitHub** [comment]
I think it is an issue of react-native-svg after checking its code:

On Web, the prop name "viewBox" is transformed by a "camelCaseToDashed" function to "view-box", which does not match the svg attribute name;

On app, I find the following helpful: [https://stackoverflow.com/a/77737987](https://stackoverflow.com/a/77737987)
