### ISSUE TITLE
how to replicate onGestureEvent onBegin action using useAnimatedGestureHandler

### ISSUE THREAD

**Issue by hugoh59** [software-mansion/react-native-reanimated#3061]
I need my gesture handler to respond as soon as a user puts his thumb down on the screen, actually onStart only fires when the thumb starts moving right or left. 

```
const onGestureEvent = useAnimatedGestureHandler({
        onStart: () => {
            isActive.value = true;
        },
        onActive: (event) => {
            ...
        },
        onEnd: () => {
            isActive.value = false;
        },
  });
```

**Comment by Latropos** [comment]
Actually `onStart` in `useAnimatedGestureHandler` is expected to work exactly the way you've described, and I've just tested on both Android and IOS that it actually works this way:
If your `useAnimatedGestureHandler` is for some reason acting weird, please try to update all your dependencies.

https://github.com/software-mansion/react-native-reanimated/assets/56199675/4b6e9f04-c808-481b-939b-d764c0959974
