### ISSUE TITLE
debug android platform freeze the application

### ISSUE THREAD

**Issue by TonyFTannous** [software-mansion/react-native-reanimated#3065]
hello
I am using react-native-reanimated v2 (version 2.0.1), and evrything go well. but when i switch to debug mode. chrome devtool stop working after 20-30 second and my app freeze (android platform only, on ios work fine)
before today this issue doesn't appear, and i can debug my app using chrome devtool without any problem

i used the following:

"react": "^17.0.1",
"react-native": "^0.64.3",
 react-native-reanimated it was 2.0.1. and after frezzing i tried the following version 2.2.0, 2.4.0, 2.3.3 . the same issue still

please any help, what happen it was working fine in debug mode

**Comment by Gazfay** [comment]
@TonyFTannous Please read limitations section: https://docs.swmansion.com/react-native-reanimated/docs/#known-problems-and-limitations

You can't use chrome remote debugging.

**Comment by TonyFTannous** [comment]
@Gazfay Thanks you for your answere. but my question is i created my project from 1 year ago and till yesterday evrything go well and i can debug it thru chrome devtools (the version of react native reanimated still the same 2.0.1, I did not upgrade it).
so only android platform stop working in debug mode, but ios platform still working.
is this is normal.
if i use flipper, to debug i should enabled hermes, right. every thing work fine except hermes debugger
![hermes](https://user-images.githubusercontent.com/33982255/158051012-7eac74fc-b3ad-4fcb-bfce-f5b2581ceb40.png)

**Comment by TonyFTannous** [comment]
@Gazfay, thanks you
