### ISSUE TITLE
Problem with refresh useSharedValue

### ISSUE THREAD

**Issue by VictorPulzz** [software-mansion/react-native-reanimated#3066]
## Description
Try to create simple scrollView, here code, but scrollOffset / useSharedValue not updated

### Expected behavior
useSharedValue must be updated

### Actual behavior & steps to reproduce
Not updated.
Just paste my code, and create simple slider

## Snack or minimal code example
```
  const scrollOffset = useSharedValue<number>(0)
  const scrollRef = useAnimatedRef<Animated.ScrollView>()
  const styles = useStyles()

  const onScroll = useAnimatedScrollHandler((event) => {
    scrollOffset.value = event.contentOffset.x
  })

  const activeSlideIndex = useDerivedValue(() => {
    return Math.round(scrollOffset.value / WIDTH)
  })

  console.log(scrollOffset)
  
....
   <Animated.ScrollView
          ref={scrollRef}
          pagingEnabled
          decelerationRate="fast"
          showsHorizontalScrollIndicator={false}
          scrollEventThrottle={16}
          horizontal
          bounces
          snapToInterval={WIDTH}
          onScroll={onScroll}
        >
       ....
   </Animated.ScrollView>
....
```
## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.67.3      |
| react-native-reanimated              |   ^2.4.1      |
| NodeJS                               |    16.13.1     |
| Xcode                                |     13.2.1    |
| Java                                 |     -    |
| Gradle                               |    -     |
| expo                                 |   bare react - native      |
| Version IOS in simulator | 15.2|
## Affected platforms

- [ ] Android
- [x ] iOS
- [ ] Web

**Comment by VictorPulzz** [comment]
Also, I setup clear project, and add simple this code from link: https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useSharedValue/
And component not update value

**Comment by piaskowyk** [comment]
I think that this should help - https://github.com/software-mansion/react-native-reanimated/pull/2580 Could you check if version 2.5.0 works for you?

**Comment by VictorPulzz** [comment]
@savelichalex Yes my bad, I already figure out in this, thanks)

**Comment by hungtooc** [comment]
@VictorPulzz so how to handle this? I'm newbie,
