### ISSUE TITLE
java.lang.NoSuchMethodError: no non-static method "Ljava/lang/Class;.getUpTime()Ljava/lang/String;"

### ISSUE THREAD

**Issue by kristfal** [software-mansion/react-native-reanimated#3079]
## Description

Seeing the following crash in production:

```
java.lang.NoSuchMethodError: no non-static method "Ljava/lang/Class;.getUpTime()Ljava/lang/String;"
```

### Expected behavior

No crash

### Actual behavior & steps to reproduce

Unknown – crash from production log. Full stack trace:

```
java.lang.NoSuchMethodError: no non-static method "Ljava/lang/Class;.getUpTime()Ljava/lang/String;"

com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent NativeProxy.java
com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent NativeProxy.java:57
com.mapbox.rctmgl.components.AbstractEvent.dispatch AbstractEvent.java:28
com.swmansion.reanimated.NodesManager.handleEvent NodesManager.java:517
com.swmansion.reanimated.NodesManager.onEventDispatch NodesManager.java:491
com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent EventDispatcherImpl.java:116
com.mapbox.rctmgl.components.AbstractEventEmitter.handleEvent AbstractEventEmitter.java:43
com.mapbox.rctmgl.components.mapview.RCTMGLMapView.handleMapChangedEvent RCTMGLMapView.java:1421
com.mapbox.rctmgl.components.mapview.RCTMGLMapView.sendRegionDidChangeEvent RCTMGLMapView.java:1401
com.mapbox.rctmgl.components.mapview.RCTMGLMapView$2.onCameraIdle RCTMGLMapView.java:466
com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.executeOnCameraIdle CameraChangeDispatcher.java:140
com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.access$300 CameraChangeDispatcher.java:21
com.mapbox.mapboxsdk.maps.CameraChangeDispatcher$CameraChangeHandler.handleMessage CameraChangeDispatcher.java:177
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loop Looper.java:223
android.app.ActivityThread.main ActivityThread.java:7723
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:612
com.android.internal.os.ZygoteInit.main ZygoteInit.java:997
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                        0.65.1
| react-native-reanimated    2.4.1

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
It looks like proguard configuration issue. Could you try to mark as required these classes in your proguard config?

**Comment by kristfal** [comment]
@piaskowyk we don't run Progard either, so this has us puzzled. Any suggestion for how to dig deeper?

**Comment by tomekzaw** [comment]
@kristfal Last month we renamed one of our internal methods from `getUpTime` to `getUptime` (see [here](https://github.com/software-mansion/react-native-reanimated/commit/561f4d5731f7e6ea217b6e4303bfbc97c953d6b9#diff-324f5710aa2f853640c557ec71c6bac78bd5e2dd55e1a80661bff848a7157d25R166)). The error comes from C++ part of Reanimated trying to invoke `getUptime` method via JNI which does not exist now. It seems like there was some mismatch between C++ precompiled sources (distributed as shared library `libreanimated.so` within `.aar`) and Java sources.

**Comment by hrupesh** [comment]
Hi @tomekzaw , is there any possible fix for this in futrue?

**Comment by mduthilleul** [comment]
Same issue here.
proguard not enabled, using react-native-reanimated 2.6.0.

**Comment by Sumit-Budhiraja** [comment]
Any update on this one.?
Still facing this issue.

**Comment by mylesdawson** [comment]
Also facing this using react-native-reanimated 2.2.3, any updates would be greatly appreciated

**Comment by stephenkopylov** [comment]
Facing the same

```
ReactNative: 0.68.2
react-native-reanimated: 2.8.0
```

**Comment by jacob-li-hj** [comment]
+1 same issue
`
"react-native": "0.64.3"
"react-native-reanimated": "2.3.3"
`

**Comment by tomekzaw** [comment]
Hey, do you use Expo managed workflow? If yes, then the JS version of Reanimated (in `node_modules`) must match the version from SDK.

**Comment by jacob-li-hj** [comment]
I don't use Expo managed workflow, I use react-native directly

**Comment by swathi2378** [comment]
Any update on this one?
Still facing this issue.
