### ISSUE TITLE
Type erros in react-native-reanimated.d.ts

### ISSUE THREAD

**Issue by lfjnascimento** [software-mansion/react-native-reanimated#3081]
## Description

Many type errors are thrown when `skipLibCheck` is false and you run `yarn type:check`

### Expected behavior

Should not return type errors when running `yarn type:check` with  `skipLibCheck` as false

### Actual behavior & steps to reproduce

In the react-native-reanimated repository
Set  `skipLibCheck` in tsconfig.json to `false` > run `yarn type:check`

## Snack or minimal code example

https://github.com/software-mansion/react-native-reanimated

## Package versions

n/a

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

Errors log: [erros.txt](https://github.com/software-mansion/react-native-reanimated/files/8289166/erros.txt)

**Comment by marf** [comment]
Same error here

**Comment by haveneersrobin** [comment]
Duplicate of https://github.com/software-mansion/react-native-reanimated/issues/3087 which contains a bit more information :)
