### ISSUE TITLE
[2.5.0] [RN: 0.66.0] [expo: 44.0.4] Android build fails with 2.5.0 version

### ISSUE THREAD

**Issue by KochMario** [software-mansion/react-native-reanimated#3086]
## Description

I've just tried to update react-native-reanimated to version 2.5.0. However, the Android doesn't build anymore.
Previously I had react-native-reanimated version 2.4.1 installed.

### Expected behavior

Can build / run android. E.g. `react-native run-android`

### Actual behavior & steps to reproduce
An error when I try and build the debug version with `react-native run-android`.

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/***/node_modules/expo/android/build/generated/expo/src/main/java/expo/modules/ExpoModulesPackageList.java:13: error: package expo.modules.adapters.reanimated does not exist
      new expo.modules.adapters.reanimated.EXReanimatedPackage(),
1 error

FAILURE: Build failed with an exception.
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.66.0       |
| react-native-reanimated              |  2.5.0       |
| expo                                 |    44.0.4     |
| Gradle                               | 6.9        |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

Thanks :pray:

**Comment by piaskowyk** [comment]
Hey, Expo hasn't supported the newest Reanimated version yet. They going to update Reanimated version at the end of March.
