### ISSUE TITLE
[Android] Reanimated 2.5.0 not compatible with expo

### ISSUE THREAD

**Issue by AlexanderEggers** [software-mansion/react-native-reanimated#3088]
## Description

When updating to 2.5.0, expo cannot find the relevant reanimated package anymore. The following line in the generated expo file is breaking: 

```
error: package expo.modules.adapters.reanimated does not exist
      new expo.modules.adapters.reanimated.EXReanimatedPackage(),
```

### Expected behavior

Works with latest version of expo.

### Actual behavior & steps to reproduce

Build error when compiling. The only workaround is to exclude the reanimated package from the expo package list via

Inside the package.json file:
```
"expo": {
    "autolinking": {
      "exclude": [
        "react-native-reanimated"
      ]
    }
  },
```

## Snack or minimal code example

Use a template expo 44 project and add reanimated 2.5.0. The android build will fail with the mentioned error.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.67.4     |
| react-native-reanimated              |     2.5.0    |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |     44.0.6    |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by KROSF** [comment]
Reproducible example https://github.com/muchobien/ownda-app/pull/144

**Comment by hirbod** [comment]
I can confirm this. It does indeed break with the custom dev client.

**Comment by hirbod** [comment]
@AlexanderEggers where did you add the exclude? Never seen this autolinking flag.

**Comment by thespacemanatee** [comment]
Are there any downsides to this workaround?

**Comment by hirbod** [comment]
@thespacemanatee so far, I have not encountered any downsides so far.

**Comment by piaskowyk** [comment]
Hey, Expo hasn't supported the newest Reanimated version yet. They going to update Reanimated version at the end of March. We can't add by ourselves we need to wait for the Expo team.
