### ISSUE TITLE
ShareableValue.h:9:10: fatal error: 'AnimatedSensorModule.h' file not found

### ISSUE THREAD

**Issue by rajaryan1990** [software-mansion/react-native-reanimated#3089]
In file included from ../../../../src/main/cpp/VisionCamera.cpp:3:
  In file included from ../../../../src/main/cpp/FrameProcessorRuntimeManager.h:13:
  In file included from /some_path/node_modules/react-native-reanimated/Common/cpp/headers/SharedItems/RuntimeManager.h:9:
  /some_path/node_modules/react-native-reanimated/Common/cpp/headers/SharedItems/ShareableValue.h:9:10: fatal error: 'AnimatedSensorModule.h' file not found
  #include "AnimatedSensorModule.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.
  [8/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/CameraView.cpp.o
  [9/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o
  ninja: build stopped: subcommand failed.
 
React Native Version: 0.64.2
Reanimated Version: 2.5.0
Vision Camera version: 2.9.4

Build is running on IOS but failing on Android

**Comment by mtroskot** [comment]
@rajaryan1990 Open android studio -> set view to Project -> add AnimatedSensorModule.h manually into Shared items https://github.com/software-mansion/react-native-reanimated/blob/d6d5f966a44b96ec3b1396a2a2d7c93b6a7abcf2/Common/cpp/headers/AnimatedSensor/AnimatedSensorModule.h

**Comment by well-ington** [comment]
you can also downgrade your react-native-reanimated to version 2.4.0 to get rid of the error

**Comment by mtroskot** [comment]
2.5.0 fixes some bugs that cause crashes on android, so an downgrade isn't advisable

**Comment by piaskowyk** [comment]
It looks like a problem with cache or problem with loading reanimated by `react-native-vision-camera`

**Comment by icc-guerrero** [comment]
> It looks like a problem with cache or problem with loading reanimated by `react-native-vision-camera`

I confirm it (version 2.9.4). Not sure if it's fixed for newer ones

Applying this patch to android CMakeLists.txt in react-native-vision-camera@2.9.4 solves the issue:

`diff --git a/node_modules/react-native-vision-camera/android/CMakeLists.txt b/node_modules/react-native-vision-camera/android/CMakeLists.txt
--- a/node_modules/react-native-vision-camera/android/CMakeLists.txt
+++ b/node_modules/react-native-vision-camera/android/CMakeLists.txt

@@ -49,6 +49,7 @@
         "${NODE_MODULES_DIR}/react-native-reanimated/Common/cpp/headers/SharedItems"
         "${NODE_MODULES_DIR}/react-native-reanimated/Common/cpp/headers/Registries"
         "${NODE_MODULES_DIR}/react-native-reanimated/Common/cpp/headers/LayoutAnimations"
+       "${NODE_MODULES_DIR}/react-native-reanimated/Common/cpp/headers/AnimatedSensor"
         "${NODE_MODULES_DIR}/react-native-reanimated/Common/cpp/hidden_headers"
         "src/main/cpp"
 )`

**Comment by kofkgoing** [comment]
Hello. how can I install 2.9.4??
