### ISSUE TITLE
Layout animations create duplicates nodes in react native SVG 

### ISSUE THREAD

**Issue by punksta** [software-mansion/react-native-reanimated#3093]
## Description

I am using react-native-svg in my project. `entering` animation in any place of the project creates duplicate svg nodes.

I replicated this behavior in 2 apps I am working on. One is using victory-native(https://apps.apple.com/us/app/diet-doctor-eat/id1440002708), another is using `react-native-responsive-linechart`(https://apps.apple.com/us/app/facing-it-overcome-anxiety/id1589812719)

### Expected behavior
Layout animations don't affect SVG nodes

### Actual behavior & steps to reproduce

I am rendering dynamic data represented by "Path". Pay attention on duplicate nodes on the first video and compare with second.

```
export default function App() {
    const [showAnimatedView, setShowAnimatedView] = useState(false);

    useEffect(() => {
        async function f() {
            for (let i = 0; i < 5; i++) {
                await new Promise(n => setTimeout(n, 200));
                setShowAnimatedView(false)
                await new Promise(n => setTimeout(n, 200));
                setShowAnimatedView(true)
            }
        }
        f();
    }, []);
  return (
      <GestureHandlerRootView style={{flex:1}}>
          <Graph/>
          {enableLayoutAnimation && showAnimatedView && <Animated.View
                                       entering={FadeInDown}
          >
          </Animated.View>}
      </GestureHandlerRootView>
  );
}
```

### with layout animation on
https://user-images.githubusercontent.com/13404754/159659737-943c34a1-d3f6-4c9d-a3d0-d002f4b963c2.mov

### without layout animation

https://user-images.githubusercontent.com/13404754/159659950-248bdcee-917d-402a-b01a-76a15017bf88.mov

## Snack or minimal code example
https://github.com/punksta/reanimated-layout-svg-bug

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.64.3    |
| react-native-reanimated              |2.3.1  |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 | 44.0.0 |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by hirbod** [comment]
Interesting, #3124 might also have a connection to your issue.

**Comment by hirbod** [comment]
I kinda feel like that LayoutManager is somehow duplicating nodes generally for animation purposes, which could somehow lead to all kind of issues and weird edge cases.

**Comment by LeviWilliams** [comment]
@hirbod definitely related, we experienced this in our project as well with the svg's alongside the issues mentioned in #3124

**Comment by Latropos** [comment]
Hi! We have fixed this problem rewriting Layout animations in Reanimated 3. I've just tested your example with this new version of the library and it seems to work very well.
