### ISSUE TITLE
[Android] Build failed with error 2 files found with path 'lib/arm64-v8a/libturbomodulejsijni.so' from inputs

### ISSUE THREAD

**Issue by duyta7598** [software-mansion/react-native-reanimated#3095]
## Description
Yesterday my project worked fine with no problem, till today it build fail and come with this error

> Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/arm64-v8a/libturbomodulejsijni.so' from inputs:
      - /Users/duyta/App/bizverse-mobile-demo/node_modules/react-native-reanimated/android/build/.transforms/8a8cf876d82615a6cbf61d3899d3a813/jetified-react-native-reanimated-63-jsc/jni
      - /Users/duyta/.gradle/caches/transforms-2/files-2.1/af55fcd9b5bf0a474271d2a2f351496d/jetified-react-native-0.66.4/jni
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

I fix it with this code 
 

> packagingOptions {
>     pickFirst 'lib/arm64-v8a/libturbomodulejsijni.so'
>     pickFirst 'lib/x86_64/libturbomodulejsijni.so'
>     pickFirst 'lib/armeabi-v7a/libturbomodulejsijni.so'
>     pickFirst 'lib/x86/libturbomodulejsijni.so'
> }

in android/app/build.gradle, it makes build complete but app crash at start up with no log
I have tried many version of reanimated but still the same error
Can any one help me?

### Expected behavior
Build success with no crash

### Actual behavior & steps to reproduce

Build failed

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.63.2       |
| react-native-reanimated              |   2.5.0      |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by rizky-pm** [comment]
I have same error like you, any solution? thanks

**Comment by dfabreguette-ap** [comment]
same error as well !
Adding the "pickFirst" causes the build to succeed but the this crash, presumely because of the duplicated lib build ?
 
2022-03-25 15:14:22.997 13426-13488/com.em.butterlink E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.em.butterlink, PID: 13426
    java.lang.IncompatibleClassChangeError: Found interface com.facebook.react.uimanager.events.EventDispatcher, but class was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/~~SYXTrbTunXlDkAkmif_NWg==/com.em.butterlink-IQluB60YFcXwvZGXd10DMg==/base.apk!classes3.dex)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:163)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1336)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
        at java.lang.Thread.run(Thread.java:923)

**Comment by rizky-pm** [comment]
> same error as well ! Adding the "pickFirst" causes the build to succeed but the this crash, presumely because of the duplicated lib build ?
> 
> ```
> 2022-03-25 15:14:22.997 13426-13488/com.em.butterlink E/AndroidRuntime: FATAL EXCEPTION: create_react_context
>    Process: com.em.butterlink, PID: 13426
>    java.lang.IncompatibleClassChangeError: Found interface com.facebook.react.uimanager.events.EventDispatcher, but class was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/~~SYXTrbTunXlDkAkmif_NWg==/com.em.butterlink-IQluB60YFcXwvZGXd10DMg==/base.apk!classes3.dex)
>        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:163)
>        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100)
>        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17)
>        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1336)
>        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
>        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
>        at java.lang.Thread.run(Thread.java:923)
>       
> ```
> 
> I can't push my code as it's not open source code.

I solved it, it was because reanimated package version 2+, try to downgrade below version 2

**Comment by davidfabreguette** [comment]
Ok thank you for your response.
What's weird for me is that I used to have version 2.3 a few days ago, but for some reasons, I had to run expo install and it breaked my android setup. 
Donwgrading to 1 solves the issue but has some other down effects... Does anyone else have the same error ?

**Comment by dfabreguette-ap** [comment]
I had to force react native version to expo SDK 44 latest supported version : 0.64.3.

```
implementation("com.facebook.react:react-native:0.64.3") {
    force=true
}
```

**Comment by Jyotiraditya008** [comment]
> I had to force react native version to expo SDK 44 latest supported version : 0.64.3.
> 
> ```
> implementation("com.facebook.react:react-native:0.64.3") {
>     force=true
> }
> ```

I tried this solution, error is gone but now its giving this error " org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'. "
