### ISSUE TITLE
TouchableWithoutFeedback clips children components

### ISSUE THREAD

**Issue by todorone** [software-mansion/react-native-reanimated#310]
It does not respect `overflow` style, while React Native's internal does.

**Comment by jakub-gonet** [comment]
Hey @todorone,
sorry for the late response.

Can you provide more information and ideally, a snack with minimal working example?

**Comment by todorone** [comment]
Hey @jakub-gonet 
Thanks for getting into it. That's the snack - https://snack.expo.io/Hk2_bZEpH It uses `TouchableOpacity`, but i guess it's the same for all RNGH's Touchable*

Source:
```
import React from 'react'
import { View, TouchableOpacity } from 'react-native'
import { TouchableOpacity as RNGHTouchableOpacity } from 'react-native-gesture-handler'

export default class App extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <TouchableOpacity style={{ width: 100, height: 50, marginBottom: 50 }}>
          <View style={{ width: 200, height: 50, backgroundColor: 'blue' }} />
        </TouchableOpacity>
        
        <RNGHTouchableOpacity style={{ width: 100, height: 50 }}>
          <View style={{ width: 200, height: 50, backgroundColor: 'grey' }} />
        </RNGHTouchableOpacity>
      </View>
    )
  }
}
```

Result:
![Screenshot_2019-12-03-17-39-11-905_host exp exponent](https://user-images.githubusercontent.com/423701/70065600-0ba83d00-15f4-11ea-8e95-83522e1c03f1.jpg)
