### ISSUE TITLE
`interpolateNode` causes crash

### ISSUE THREAD

**Issue by 256hz** [software-mansion/react-native-reanimated#3104]
## Description

I want to try swapping out the new `interpolate` for the old `interpolateNode` in my project to see if I can get any performance gains out of it.  When I use `interpolateNode`, I get a crash in the native layer.

The samples I copied below work using `interpolate` (and the new syntax).  This is in a bare React Native project at 0.64.2.  Version numbers for everything are below in the table.

I do have code in other files still using the new `interpolate` and syntax, I'm not sure if that matters.  The examples below are all within one file, which doesn't use the new `interpolate` at all.  We also use the React Native Animated api elsewhere in the project.

I did see #875 but it didn't seem related.

### Expected behavior

`interpolateNode` returns interpolated values

### Actual behavior & steps to reproduce

Code samples are below, but the steps for me are to use `interpolateNode` within the function bodies of useAnimatedProps and useAnimatedStyle hooks.

Actual behavior is a crash out of the app.
Seems like the crash is in turbomodules maybe?
- iOS stack trace (sorry, quite long): https://gist.github.com/256hz/fa23b6cebf42d7b5dfe42fe707bd1a1d
- Android: `A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7719c4df30 in tid 15891 (mqt_js), pid 12611 (app.development)` (this is all I have been able to find so far)

## Snack or minimal code example

Here are a couple of places I've tried interpolateNode:

```javascript
  const lottieProgressProp = useAnimatedProps(() => ({
    progress: interpolateNode(lottieProgress.value, {
      inputRange: [-1, 0, 1, 2, 3],
      // variables are numbers between 0 and 1
      outputRange: [0, TINY_GREEN_DOT_MARK, FULL_TREE_PROGRESS_MARK, AWARD_MARK, END_MARK],
    }),
  }));
```

```javascript
  // variables are numbers between 0 and 1
  const viewStyle = useAnimatedStyle(() => {
    const viewInputs = [1.5, 2, 2.5, 3];
    const sizeOutputs = [smallViewSize, bigViewSize, bigViewSize, bigViewSize * 0.95];
    const marginOutputs = [
      0,
      0 - (bigViewSize - smallViewSize) / 2,
      0 - (bigViewSize - smallViewSize) / 2,
      0 - (bigViewSize * 0.95 - smallViewSize) / 2,
    ];

    return {
      height: interpolateNode(lottieProgress.value, {
        inputRange: viewInputs,
        outputRange: sizeOutputs,
      }),
      marginRight: interpolateNode(lottieProgress.value, {
        inputRange: viewInputs,
        outputRange: marginOutputs,
      }),
      marginTop: interpolateNode(lottieProgress.value, {
        inputRange: viewInputs,
        outputRange: marginOutputs,
      }),
      opacity: interpolateNode(lottieProgress.value, {
        inputRange: viewInputs,
        outputRange: [0, 1, 1, 0],
      }),
      width: interpolateNode(lottieProgress.value, {
        inputRange: viewInputs,
        outputRange: sizeOutputs,
      }),
    };
  });
```

Happy to provide more code if it would help.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.64.2      |
| react-native-reanimated              | 2.2.4     |
| NodeJS                               | 16.13.0    |
| Xcode                                | 13.2.1 |
| Java                                 | adoptOpenJDK 11.0.11 |
| Gradle                               | 6.9 |

## Affected platforms

- [X] Android
- [X] iOS
- [ ] Web

Thank you for looking through this! All the best.

**Comment by mrvincenzo** [comment]
@256hz Was you able to figure it out?

**Comment by 256hz** [comment]
@mrvincenzo nope, we stuck with the new interpolate

**Comment by Latropos** [comment]
Closing since interpolateNode was removed in reanimated 3.0 and now we encourage and we have very limited support for reanimated 2.
