### ISSUE TITLE
TypeError: global.__reanimatedWorkletInit is not a function

### ISSUE THREAD

**Issue by ethanneff** [software-mansion/react-native-reanimated#3111]
### Description
 error when running tests

### Snack or minimal code example

  ● Test suite failed to run

    TypeError: global.__reanimatedWorkletInit is not a function

      at node_modules/react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureStateManager.ts:16:36
      at Object.<anonymous> (node_modules/react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureStateManager.ts:16:36)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/lib/commonjs/handlers/gestures/GestureDetector.tsx:20:1)

### Package versions
    "react-native-reanimated": "2.4.1",

### Affected platforms
 react native jest

**Comment by ethanneff** [comment]
solution:

`global.d.ts`
```ts
declare namespace global {
  function __reanimatedWorkletInit(): void;
}
```

`jest.setup.ts`
```ts
global.__reanimatedWorkletInit = jest.fn();

```

**Comment by ThaungThanHan** [comment]
> solution:
> 
> `global.d.ts`
> 
> ```ts
> declare namespace global {
>   function __reanimatedWorkletInit(): void;
> }
> ```
> 
> `jest.setup.ts`
> 
> ```ts
> global.__reanimatedWorkletInit = jest.fn();
> ```

Where can I find globa.d.ts file and jest.setup.ts files? Please help

**Comment by tomekzaw** [comment]
`__reanimatedWorkletInit` has been removed in #3143.

@ethanneff @ThaungThanHan Can you please check if this works for you on Reanimated 2.7.0 without mock function?

**Comment by rayhk6** [comment]
I don't know where can I find globa.d.ts file and jest.setup.ts files too.

**Comment by krtejeda** [comment]
I'm still running into this issue with createAnimatedComponent.

**Comment by TiagoJacobs** [comment]
hello @krtejeda - can  you try to add this line in your App.tsx?

```js
global.__reanimatedWorkletInit = () => {};
```

**Comment by krtejeda** [comment]
@TiagoJacobs Yeah that seems to work. Thanks!

**Comment by danmartens** [comment]
I just saw this error after upgrading to the latest version (2.8.0) and running `react-native start --reset-cache` fixed the issue for me.

**Comment by nandorojo** [comment]
I'm seeing this error at runtime in Next.js using 2.8.0.

**Comment by nhuhoa103** [comment]
> I just saw this error after upgrading to the latest version (2.8.0) and running `react-native start --reset-cache` fixed the issue for me.

It works for me, thank you

**Comment by jamesallain** [comment]
I fixed this error by putting the react-native-reanimated/plugin last in babel.config.js. Which it clearly states to do in the [docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation)... 
```  module.exports = {
      ...
      plugins: [
          ...
          'react-native-reanimated/plugin',
      ],
  };
```

**Comment by nandorojo** [comment]
I solved this by:

1. clearing all caches and node modules (including `.expo` and `.next` folders)
2. upgrading to RN Gesture Handler 2.4

if you’re using npm, and it still doesn’t work, try this:

```sh
npm i --legacy-peer-deps
```

**Comment by himrocks33** [comment]
@nandorojo Thank you!  Deleting the .expo directory is finally what got this working.

**Comment by himrocks33** [comment]
@nandorojo I spoke to soon.  Upgrading react-native-gesture-handler now causes this issue on Android:
`["RNGestureHandlerRootView" was not found in the UIManager]`
Attempted the suggested fixes for this: 
`(https://stackoverflow.com/questions/71396210/rngesturehandlerrootview-was-not-found-in-the-uimanager)`
None of which seem to work.

**Comment by himrocks33** [comment]
@nandorojo I spoke to soon upgrading react-native-gesture-handler to 2.4 causes this issue on android:
`["RNGestureHandlerRootView" was not found in the UIManager]`
I attempted suggested fixes here:
`https://stackoverflow.com/questions/71396210/rngesturehandlerrootview-was-not-found-in-the-uimanager`
None of which seem to make a difference.  Only way to get android to work is to downgrade RN Gesture Handler.

**Comment by himrocks33** [comment]
Okay, so upgrading to 2.4.2 did cause an issue for me.  I downgraded back to ~2.2.1 of RNGH and cleared all cache again.  
delete `.expo`, `node_modules`, `yarn.lock`
run `yarn start -c`

I have my app running on web, iOS and Android all side by side now and it seems to work fine.  The issue seems to just be the cache.  Upgrading RNGH to 2.4.2 though caused the other issues above so I do not recommend upgrading.

**Comment by nandorojo** [comment]
did you wrap your app in `RNGestureHandlerRootView`?

**Comment by himrocks33** [comment]
@nandorojo I just attempted to wrap in `RNGestureHandlerRootView` does not make a difference.  Android still throws the same error.  Cleared all cache as well. 2.4.2 does not seem to agree with Android on SDK 45.

**Comment by thaitd0396** [comment]
> Okay, so upgrading to 2.4.2 did cause an issue for me. I downgraded back to ~2.2.1 of RNGH and cleared all cache again. delete `.expo`, `node_modules`, `yarn.lock` run `yarn` run `yarn start -c`
> 
> I have my app running on web, iOS and Android all side by side now and it seems to work fine. The issue seems to just be the cache. Upgrading RNGH to 2.4.2 though caused the other issues above so I do not recommend upgrading.

It worked, thank bro <3

**Comment by NathanNovak** [comment]
> I just saw this error after upgrading to the latest version (2.8.0) and running `react-native start --reset-cache` fixed the issue for me.

@danmartens Thanks this worked!

**Comment by faizqadri234** [comment]
> I just saw this error after upgrading to the latest version (2.8.0) and running `react-native start --reset-cache` fixed the issue for me.

Thanks 😊. It solved the issue

**Comment by Pinturaj** [comment]
> 

react-native start --reset-cache is not a command

**Comment by arvinio** [comment]
Looks like the error is coming from `react-native-gesture-handler`. Try mocking it:

```
jest.mock('react-native-gesture-handler', () => jest.fn());
```

**Comment by wrsulliv** [comment]
To patch `2.8.0` for web:

1.  Enable [patch-package](https://github.com/ds300/patch-package)
2. Patch as [described here](https://github.com/wcandillon/react-native-redash/issues/395#issuecomment-1146540432)
3. Save the patch `npx patch-package react-native-reanimated`

Now, when you run `npm i` it will automatically patch the library.  If you're using yarn, you may need additional steps for the `postinstall` hook to work.

I wish I had the time to dig in and better understand the problem, but until there's a long-term solution, this workaround is good enough for me.

**Comment by gomo** [comment]
> solution:
> 
> `global.d.ts`
> 
> ```ts
> declare namespace global {
>   function __reanimatedWorkletInit(): void;
> }
> ```
> 
> `jest.setup.ts`
> 
> ```ts
> global.__reanimatedWorkletInit = jest.fn();
> ```

In my environment, the code of `globals.d.ts` did not work with that, and the following worked.

```ts
// globals.d.ts
declare module globalThis {
  var __reanimatedWorkletInit: () => void;
}
```

**Comment by najam-falcon** [comment]
**react-native run-ios** or **react-native run-android**
**npm start -- --reset-cache**
Hopefully it works

**Comment by Youssef-Durgham** [comment]
> I just saw this error after upgrading to the latest version (2.8.0) and running `react-native start --reset-cache` fixed the issue for me.

solve my error thx

**Comment by Youssef-Durgham** [comment]
try to use this 
expo start -c   
will fix your error

**Comment by ali-husnain** [comment]
> To patch `2.8.0` for web (also using Expo 45):
> 
> 1. Enable [patch-package](https://github.com/ds300/patch-package)
> 2. Patch as [described here](https://github.com/wcandillon/react-native-redash/issues/395#issuecomment-1146540432)
> 3. Save the patch `npx patch-package react-native-reanimated`
> 
> Now, when you run `npm i` it will automatically patch the package. If you're using yarn, you may need additional steps for the `postinstall` hook to work.
> 
> I wish I had the time to dig in and better understand the problem, but until there's a long-term solution, this workaround is good enough for me.

@wrsulliv Thanks you save my life

**Comment by hotaryuzaki** [comment]
i have same problem, but there is none above suggestions is works for me.
will it solve if i upgrade to latest version of react-native-reanimated?

**Comment by jhaypee04** [comment]
Is it that this error cannot be solved in snack?

**Comment by RNtaate** [comment]
> hello @krtejeda - can you try to add this line in your App.tsx?
> 
> ```js
> global.__reanimatedWorkletInit = () => {};
> ```

This seemed to work when I face this error on `Expo Snack` while working with bottom tabs and Navigation. Thanks

**Comment by gediminasnn** [comment]
For me the problem was that I was having older react-native-reanimated version in my package.json file ("react-native-reanimated": "2.2.4"), after changing it to the newest one ("react-native-reanimated": "3.1.0") the error didn't show up anymore.

**Comment by gediminasnn** [comment]
Make sure all your dependencies are up to date

**Comment by MosesMusoke** [comment]
Hi I solved this by adding '@babel/plugin-proposal-export-namespace-from' as the last in the plugins within babel.config.js file.   
plugins: [
      'react-native-reanimated/plugin',
      '@babel/plugin-proposal-export-namespace-from',
    ],
