### ISSUE TITLE
App crashes at startup in a device I have with a stack trace pointing to this library

### ISSUE THREAD

**Issue by fermmm** [software-mansion/react-native-reanimated#3118]
## Description

My app is working in many devices but there is one where it doesn't work because of a crash when the app is starting, the crash is related with this library. The device with the problem is a Samsung Galaxy Grand Prime SM-G531M with Android 5.1.1

![Screenshot_2022-03-30-22-04-34](https://user-images.githubusercontent.com/3660373/160956113-938ed2d3-c519-4fae-a13b-dce31adbc757.png)
![Screenshot_2022-03-30-22-03-41](https://user-images.githubusercontent.com/3660373/160956132-0232b894-178d-4a5c-8222-150e447277ca.png)

My app uses Expo with bare workflow.

### Expected behavior

I expect my app to work in all Android devices without crashes related to this library.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                        0.64.3
| react-native-reanimated    ~2.3.1
| NodeJS                              16.13.2
| Gradle                              6.9
| expo                                 |>=44.0.0-0 <45.0.0 (Bare workflow)

## Affected platforms

- [X ] Android
- [ ] iOS
- [ ] Web

This is a minimal project where you can reproduce the issue:
https://drive.google.com/drive/folders/1-16dBEGmHfM9k1lwnQSUTG_XVLY17OSH

**Comment by piaskowyk** [comment]
I am quite sure that we have already fixed this issue. Could you update your version of Reanimated to the leatest?

**Comment by Latropos** [comment]
This problem seems to be already solved in newest versions of reanimated.
