### ISSUE TITLE
v1.13.4 fails to build with Gradle 7

### ISSUE THREAD

**Issue by TheAlmightyBob** [software-mansion/react-native-reanimated#3119]
## Description

Despite #2881, v1.13.4 is still incompatible with Gradle 7. Gradle 7 removed "compile" in favor of "implementation," and the `android/build.gradle` file is still using `compile` in the context of

```
task androidJavadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += files(android.bootClasspath)
    classpath += files(project.getConfigurations().getByName('compile').asList())
    include '**/*.java'
}
```

which results in the error `Configuration with name 'compile' not found.`

### Expected behavior

Projects using the latest v1 of `react-native-reanimated` can build with Gradle 7.

### Actual behavior & steps to reproduce

Updating to Gradle 7 fails to build `react-native-reanimated` with `Configuration with name 'compile' not found.`, specifically pointing at the `files(project.getConfigurations().getByName('compile').asList())` line.

Alternate simple repro steps:
1. Use `npx react-native init` to create a new React Native app
2. `yarn add react-native-reanimated@1.13.4`
3. `yarn android`

## Snack or minimal code example

https://github.com/TheAlmightyBob/ReanimatedGradle7

(this is simply the result of following the "alternate simple repro steps" above)

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.66.4      |
| react-native-reanimated              |    1.13.4     |
| Java                                 |    11     |
| Gradle                               |    7.1.1 or 7.2     |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey, this one should resolve your problem: https://github.com/software-mansion/react-native-reanimated/pull/3120 most probably I will release the new version on Monday.

**Comment by piaskowyk** [comment]
Sorry but we no longer support Reanimated v1, but this PR should resolve your problem: https://github.com/software-mansion/react-native-reanimated/pull/3120

**Comment by TheAlmightyBob** [comment]
@piaskowyk That was my PR, I just thought the PR should come with an Issue that it fixes (I think other projects prefer/require that, but maybe y'all don't)

Re: "we no longer support Reanimated v1", has that been communicated elsewhere? What I see on the documentation for v2 is:
> Reanimated 2 is in an early version. As we wanted to share it with the community as soon as we could, the library still has some rough edges and limitations

(and it is indeed those rough edges and limitations that make v2 unusable for us at this time)

From which I thought v1 was still supported as the more stable option.
