### ISSUE TITLE
[Android] Java patch doesn't seem to be applied when building from cache

### ISSUE THREAD

**Issue by Looooong** [software-mansion/react-native-reanimated#3138]
## Description

Since I upgraded to version 2.5.0, whenever I change a dependency not related to `react-native-reanimated` and start an Android build from existing cache, the `ReanimatedUIImplementation.java` doesn't seem to be patched and will result in the following error:

```
...\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\layoutReanimation\ReanimatedUIImplementation.java:13: error: cannot find symbol 
      ViewManagerResolver viewManagerResolver,
      ^
  symbol:   class ViewManagerResolver
  location: class ReanimatedUIImplementation
```

Cleaning Android build and re-building from scratch does work. However, this means that our CI cannot rely on Android build cache anymore.

### Expected behavior

I should be able to re-build sucessfully from cache whenever Android project or dependency changes.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.63.4        |
| react-native-reanimated              | 2.5.0        |
| NodeJS                               | 14.17.0        |
| Xcode                                |         |
| Java                                 | 1.8        |
| Gradle                               | 4.1.2        |
| expo                                 |         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by jzxchiang1** [comment]
Unfortunately I get this error even after I run `cd android && ./gradlew clean`.

I'm on RN 0.64.2 and 2.6.0.

Any idea what may be going wrong?

**Comment by cleandevcode** [comment]
"react-native": "0.63.4",
"react-native-reanimated": "^2.4.1",

I have same issue.

**Comment by cleandevcode** [comment]
I fixed this way.

`yarn remove react-native-reanimated`
`yarn add react-native-reanimated@^2.4.1`
`yarn run android`

It worked like a charm!

**Comment by agilbani** [comment]
> yarn run android

im still facing error

**Comment by FabioMFGaspar** [comment]
I manage to fix this by updating the React, react-native and babel/core versions

react: 16.13.1 -> 17.0.2
react-native: 0.63.4 -> 0.66.1
@babel/core: ^7.8.4 -> ^7.12.9

I think that only updating react might solve it but I updated the 3

**Comment by kayallapl** [comment]
> I fixed this way.
> 
> `yarn remove react-native-reanimated` `yarn add react-native-reanimated@^2.4.1` `yarn run android`
> 
> It worked like a charm!

Thank you!! Worked for me

**Comment by Looooong** [comment]
I don't get this error anymore after upgrading both React and React Native

```
react: 16.13.1 -> 17.0.2
react-native: 0.63.4 -> 0.64.3
```

Probably, for Reanimated 2.5.0, React Native version should be upgraded to 0.64 or newer.

**Comment by ratz6** [comment]
We use RN version "0.64.2" and REA version "^2.8.0"
If I use the old node modules I see this structure in re-animated >

![image](https://user-images.githubusercontent.com/77700933/178905169-58f29687-265c-492a-87c2-9d00cd64abf5.png)

But If do yarn install even without changing anything in package.json I see the reanimated-64.aar file not available ?

![image](https://user-images.githubusercontent.com/77700933/178905239-711378dd-dc19-4ee9-807d-e92edda79ddd.png)

I'm able to work if I use the old node modules and that's possible until I change the package.json.
Should I spend my time upgrading the RN version (which is a pain as unimodules are involved) or what else can be done here from reanimated side ?

**Comment by fogg4444** [comment]
I wish I could solve this.....

**Comment by fogg4444** [comment]
> 

So, do we know why this works? It's about the patching not applying unless you completely re-install? I've had issues pop up with this library for months across various versions of React and React Native. Can't seem to find what the root cause is...

**Comment by oleksandr-dziuban** [comment]
Same error reproducible for our project on CI:

React v1.8.0.
React Native v0.69.6
React Native Reanimated: v2.10.0

```

Task :react-native-reanimated:compileReleaseJavaWithJavac FAILED
/builds/engineering/mobile/investor-app/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedUIManager.java:15: error: cannot find symbol
class ReaUiImplementationProvider extends UIImplementationProvider {
                                          ^
  symbol: class UIImplementationProvider
/builds/engineering/mobile/investor-app/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedUIManager.java:17: error: method does not override or implement a method from a supertype
  @Override
  ^
/builds/engineering/mobile/investor-app/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedUIManager.java:38: error: no suitable constructor found for UIManagerModule(ReactApplicationContext,List<ViewManager>,ReaUiImplementationProvider,int)
    super(
    ^
    constructor UIManagerModule.UIManagerModule(ReactApplicationContext,ViewManagerResolver,int) is not applicable
      (actual and formal argument lists differ in length)
    constructor UIManagerModule.UIManagerModule(ReactApplicationContext,List<ViewManager>,int) is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
FAILURE: Build failed with an exception.

```

**Comment by oleksandr-dziuban** [comment]
https://github.com/facebook/react-native/issues/35210
