### ISSUE TITLE
TypeError: _reactNativeReanimated.Easing.bezier(...) is not a function

### ISSUE THREAD

**Issue by kokosky93** [software-mansion/react-native-reanimated#3142]
## Description

I try tu use Easing.bezier() function but following error is beeing thrown after android bundling complete
TypeError: _reactNativeReanimated.Easing.bezier(...) is not a function is thrown

I was trying different package versions, clearing cache and so on. No luck.

In Visual Studio Code I don't see any type error. Also I can find bezier function in node moduels.

### Actual behavior & steps to reproduce

expo init app -t expo-template-blank-typescript
expo install react-native-reanimated

Easing.bezier(0.16, 1, 0.3, 1)(progress.value)

## Snack or minimal code example

Easing.bezier(0.16, 1, 0.3, 1)(progress.value)

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      0.64.3  
| react-native-reanimated              |        2.3.3
| NodeJS                               |         14.16.1
| expo                                 |         44.0.6

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by kokosky93** [comment]
This package is a nightmare. I downgraded my expo and react-native-reanimated as it was suggested in 
https://github.com/software-mansion/react-native-reanimated/issues/2766#issuecomment-997492787
However now I see different error. Nothing is working. I have spent so much time on this.
Is there anyone who are having the same issue as me and was able to resolve that?

**Comment by younes0** [comment]
@kokosky93 had this on Web only: I forgot to add the babel plugin `@babel/plugin-proposal-export-namespace-from`

**Comment by Latropos** [comment]
Hi! You may want to check our docs [LINK](https://docs.swmansion.com/react-native-reanimated/docs/animations/withTiming/) or look at our code example:
```javascript
  const config = {
    duration: 500,
    easing: Easing.bezier(0.5, 0.01, 0, 1),
  };

  const style = useAnimatedStyle(() => {
    return {
      width: withTiming(randomWidth.value, config),
    };
  });
```
