### ISSUE TITLE
`maybeFlushUpdateBuffer` applies batched props updates with a delay

### ISSUE THREAD

**Issue by savelichalex** [software-mansion/react-native-reanimated#3145]
## Description

I noticed a regression after https://github.com/software-mansion/react-native-reanimated/pull/2580 . We have bottom sheets, they're changing their position with `translateY` after mount (React one). There's a problem with reproducing it, as in a "lightweight" components it seems to works fine, I guess it's only about complicated ones (or maybe even something else running on background). So I sat with a debugger for some time and I noticed, that there's a delay between `updateProps` and `maybeFlushUpdateBuffer` ([the branch after atomic check](https://github.com/software-mansion/react-native-reanimated/blob/main/ios/REANodesManager.m#L606)). If you take a look at the attached video, the moment when a sheet (and an overlay behind it) is rendered properly after a mount, is at the same time, when `maybeFlushUpdateBuffer` fires.

I didn't dig too much what can cause `uiManagerWillPerformMounting` to fire with a delay, since I found [a workaround](https://github.com/tonlabs/UIKit/blob/b6b6d3a4fc99149753b70eed843ef5472f2bbf73/kit/popups/src/Sheets/UISheet/UISheet.tsx#L130-L156) (basically I just start animation only after a View is mounted, to avoid falling into logic from https://github.com/software-mansion/react-native-reanimated/pull/2580).
I just want bring awareness that the problem exists.

My personal guess - maybe `uiManagerWillPerformMounting` is not the best source to rely on, but I also don't see a better solution for now. I also thought that maybe it's sth related to `atomic`, maybe `uiManagerWillPerformMounting` fires properly, but doesn't see that `_shouldFlushUpdateBuffer` was updated. 🤷‍♂️

### Actual behavior & steps to reproduce

https://user-images.githubusercontent.com/6286454/162118770-299e18e8-7530-4dfc-a771-8c4436a2d26f.mp4

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.67.3     |
| react-native-reanimated              |   >=2.5.0      |
| NodeJS                               |    14.17.6     |
| Xcode                                |    13.2.1     |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by savelichalex** [comment]
@piaskowyk sorry that I didn't include a minimal reproduction, but I just want to bring awareness of the potential problem in case you meet it in some place

**Comment by Latropos** [comment]
Closing since we are dropping support for Reanimated 2
