### ISSUE TITLE
TypeError: global.__reanimatedWorkletInit is not a function on debug mode

### ISSUE THREAD

**Issue by fadi-quader-mox** [software-mansion/react-native-reanimated#3146]
## Description
I've upgraded to version 2.6.0. to fix remote debugging. The issue is fixed on ios, however, there's some issue on **Android** when remote debugging is enabled 
```
TypeError: global.__reanimatedWorkletInit is not a function
```
and then the app freezes.
<img width="757" alt="image" src="https://user-images.githubusercontent.com/102506966/162132112-b1cec0f2-ee10-4169-9f0b-5736f5914c15.png">

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.67.3    |
| react-native-reanimated              |     2.6.0    |
| NodeJS                               |    v16.14.2     |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
@fadi-quader-mox We've removed `__reanimatedWorkletInit` in #3143.

Can you please upgrade to Reanimated 2.7.0 and let us know if it helps?

**Comment by nandorojo** [comment]
<img width="900" alt="Screen Shot 2022-04-28 at 5 20 00 PM" src="https://user-images.githubusercontent.com/13172299/165847774-045809c4-ea5e-4def-8a3e-780f975b7432.png">

I'm seeing this on `2.8.0` on Web. I fixed it by upgrading `react-native-gesture-handler` and removing `.next`.

**Comment by codeion** [comment]
@nandorojo What do you mean by removing .next?
I'm also facing this issue on 2.8.0 on web with latest react-native-gesture-handler 2.4.2

**Comment by nandorojo** [comment]
that's a folder next.js creates. it's relevant if you're using next.

**Comment by codeion** [comment]
@nandorojo Thanks, but I'm not using next.js (works fine on iOS and Android, but not on Web)
Any other suggestion?

**Comment by himrocks33** [comment]
@codeion I'm having the same issue on web... Any progress on this?

**Comment by sergeu90** [comment]
I have same issue on electron. but on web all good

**Comment by wrsulliv** [comment]
> @fadi-quader-mox We've removed `__reanimatedWorkletInit` in #3143.
> 
> Can you please upgrade to Reanimated 2.7.0 and let us know if it helps?

I am using `2.8.0` and getting this same error on web.

**Comment by gang544043963** [comment]
2.9.1 the same error:
```
 ERROR  TypeError: global.__reanimatedWorkletInit is not a function. (In 'global.__reanimatedWorkletInit(_f)', 'global.__reanimatedWorkletInit' is undefined)
```

**Comment by tomekzaw** [comment]
Hello @gang544043963!

In Reanimated 2.7.0 we completely removed `__reanimatedWorkletInit` from Reanimated codebase (see https://github.com/software-mansion/react-native-reanimated/pull/3143).

Can you please clear your application cache with `yarn start --reset-cache` and let us know if it works for you?

**Comment by wrsulliv** [comment]
@gang544043963 @tomekzaw  I ended up patching and documented it here: https://github.com/software-mansion/react-native-reanimated/issues/3111#issuecomment-1179370383
