### ISSUE TITLE
Update installation guide (0.68.0)

### ISSUE THREAD

**Issue by pjc0247** [software-mansion/react-native-reanimated#3147]
## Description

Current version of the [installation guide](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#android) is outdated and does not compatible with new arch enabled projects.

There's predefined `getJSIModulePackage` so i can't override the method.

https://github.com/facebook/react-native/blob/main/template/android/app/src/main/java/com/helloworld/newarchitecture/MainApplicationReactNativeHost.java#L71-L73

Thanks!

### Expected behavior

Installation guide for fabric enabled projects.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |         |
| react-native-reanimated              |         |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by rayhk6** [comment]
@pjc0247 I encountered an error when installing this package with React Native 0.68. Did you find a solution yet? Thanks.

**Comment by pjc0247** [comment]
@rayhk6 not yet, but you may want to try `0.68.1` which includes a fix for `react-native-reanimated`.

https://github.com/facebook/react-native/commit/58a2eb7f37c2dc27ad3575618778ad5b23599b27

**Comment by kristijantomic** [comment]
I have tried to 0.68.1 but i got following error 😢 

`
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTView
04-15 06:58:55.860  7663  7663 F DEBUG   :   at void com.swmansion.reanimated.AndroidErrorHandler.raise(java.lang.String) (AndroidErrorHandler.java:6)`

**Comment by nickprihodko** [comment]
@pjc0247 Hi! Also not working with react-native 0.68.17
Any updates of this?
Thanks

**Comment by pjc0247** [comment]
@nickprihodko I noticed that they just removed their initialization step on Android (pls see https://github.com/software-mansion/react-native-reanimated/pull/3005)
So you don't need to override the `getJSIModulePackage` method.

btw i'm not sure it works with 0.68.1,  I decided to upgrade my project with new arch later.
