### ISSUE TITLE
findAndUpdateNodes was passed a nullish node in rn-web using class component

### ISSUE THREAD

**Issue by evd1ser** [software-mansion/react-native-reanimated#3156]
## Description

When i use react-native-reanimated in React.Component I get an error
```
findAndUpdateNodes was passed a nullish node
```

### Expected behavior
No error, smooth animation of width

### Actual behavior & steps to reproduce
code example:
```
import Animated, { Value, timing, EasingNode, } from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React, { Component } from 'react';

export class WebPlayground extends Component {
  randomWidth = new Value<number>(10);

  render() {
    return (
      <View>
        <Animated.View
          style={[
            { width: 100, height: 80, backgroundColor: 'black', margin: 30 },
            { width: this.randomWidth },
          ]}
        />
        <Button
          title="toggle"
          onPress={() => {
            const newValue = Math.random() * 350;
            timing(this.randomWidth, {
              toValue: newValue,
              duration: 500,
              easing: EasingNode.bezier(0.5, 0.01, 0, 1),
            }).start();
          }}
        />
      </View>
    );
  }
}

```
This problem only if i want create timing animation. Without timing when i use `this.randomWidth.setValue(newValue);` width is changing normal but animation changes drastically

Or if i rewrite on function component it also work fine with hooks ([from offitial example](https://github.com/software-mansion-labs/reanimated-2-playground/blob/master/Screen.js)):
```
import Animated, { useSharedValue, withTiming, useAnimatedStyle, Easing } from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React from 'react';

export function WebPlayground(props) {
  const randomWidth = useSharedValue(10);

  const config = {
    duration: 500,
    easing: Easing.bezier(0.5, 0.01, 0, 1),
  };

  const style = useAnimatedStyle(() => {
    return {
      width: withTiming(randomWidth.value, config),
    };
  });

  return (
    <View>
      <Animated.View
        style={[
          { width: 100, height: 80, backgroundColor: 'black', margin: 30 },
          style,
        ]}
      />
      <Button
        title="toggle"
        onPress={() => {
          randomWidth.value = Math.random() * 350;
        }}
      />
    </View>
  );
}
```

## Package versions

| name                                    | version |
| -------------------------- | ------- |
| react-native                         |  0.66.4 |
| react-native-reanimated    |  2.6.0 |
| NodeJS                                | 16.10.0 |
| react-native-web.               | 0.17.6 |

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by evd1ser** [comment]
I change this and warning is hide
```diff
diff --git a/node_modules/react-native-reanimated/.DS_Store b/node_modules/react-native-reanimated/.DS_Store
new file mode 100644
index 0000000..3bd1b89
Binary files /dev/null and b/node_modules/react-native-reanimated/.DS_Store differ
diff --git a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedNode.js b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedNode.js
index d7892d8..138044a 100644
--- a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedNode.js
+++ b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedNode.js
@@ -61,7 +61,7 @@ function runPropUpdates() {
     } else {
       const nodes = node.__getChildren();
       if (nodes) {
-        for (let i = 0, l = nodes.length; i < l; i++) {
+        for (let i = 0; i < nodes.length; i++) {
           findAndUpdateNodes(nodes[i]);
         }
       }
```

**Comment by evd1ser** [comment]
For smooth animation in web need change (work for me):
```diff
diff --git a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
index 8cab95d..ec31e64 100644
--- a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
+++ b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
@@ -9,7 +9,9 @@ import { val } from '../val';
 // Animated value wrapped with extra methods for omit cycle of dependencies
 export default class AnimatedValue extends InternalAnimatedValue {
   setValue(value) {
-    this.__detachAnimation(this._animation);
+    if (Platform.OS !== 'web'){
+      this.__detachAnimation(this._animation);
+    }
     if (
       Platform.OS === 'web' ||
       Platform.OS === 'windows' ||
```

**Comment by beerent** [comment]
> For smooth animation in web need change (work for me):
> 
> ```diff
> diff --git a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
> index 8cab95d..ec31e64 100644
> --- a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
> +++ b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
> @@ -9,7 +9,9 @@ import { val } from '../val';
>  // Animated value wrapped with extra methods for omit cycle of dependencies
>  export default class AnimatedValue extends InternalAnimatedValue {
>    setValue(value) {
> -    this.__detachAnimation(this._animation);
> +    if (Platform.OS !== 'web'){
> +      this.__detachAnimation(this._animation);
> +    }
>      if (
>        Platform.OS === 'web' ||
>        Platform.OS === 'windows' ||
> ```

I needed this to get web to work. Thanks!

**Comment by maxilie** [comment]
> For smooth animation in web need change (work for me):
> 
> ```diff
> diff --git a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
> index 8cab95d..ec31e64 100644
> --- a/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
> +++ b/node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedValue.js
> @@ -9,7 +9,9 @@ import { val } from '../val';
>  // Animated value wrapped with extra methods for omit cycle of dependencies
>  export default class AnimatedValue extends InternalAnimatedValue {
>    setValue(value) {
> -    this.__detachAnimation(this._animation);
> +    if (Platform.OS !== 'web'){
> +      this.__detachAnimation(this._animation);
> +    }
>      if (
>        Platform.OS === 'web' ||
>        Platform.OS === 'windows' ||
> ```

This worked for me. But how does one patch it so that the fix is built-in after a new build? Anyone know?
