### ISSUE TITLE
Animation height style sometimes not being applied in 2.5.0 (Race Condition?)

### ISSUE THREAD

**Issue by henrymoulton** [software-mansion/react-native-reanimated#3158]
## Description

I saw that https://github.com/software-mansion/react-native-reanimated/pull/2580 was meant to fix https://github.com/software-mansion/react-native-reanimated/issues/2836.

We're still seeing occurrences of [react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet)  not appearing, even after upgrading to 2.5.0

### Expected behavior

Bottom Sheet should appear

### Actual behavior & steps to reproduce

Use app in development/production and see that bottom sheet doesn't appear.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.66.4      |
| react-native-reanimated              | ^2.5.0        |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |  44       |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

Haven't seen it on iOS yet.

**Comment by hirbod** [comment]
@henrymoulton I am a heavy user of RNBS. I can't confirm that. Can you create a reproduction case?

**Comment by henrymoulton** [comment]
@hirbod thanks for replying! What version of RN/RNBS/Reanimated are you using? Out of interest do you test your own app in prod on Android?

I'm working on figuring out if this happens on iOS, so far not, and so it's going to be tricky to track down why it's happening only on Android and create a reproduction.

**Comment by hirbod** [comment]
Oh, I see. I did not test my Android app in production yet, only in debug mode but I did not account any regressions so far. iOS is working great for me (in debug and prod).

I am on RN 0.64.3 (will upgrade to 0.68 soon), beside that I am using the same versions as you.

**Comment by henrymoulton** [comment]
Will probably try the fix suggested in https://github.com/software-mansion/react-native-reanimated/issues/2836#issuecomment-1013096114 as a workaround and see if that fixes it
