### ISSUE TITLE
Using PlatformColor in useAnimatedStyle throws an error

### ISSUE THREAD

**Issue by ethanshar** [software-mansion/react-native-reanimated#3164]
## Description
I have a const that holds a color from `PlatformColor` API, for instance `const myColor = PlatformColor('systemBlue')`
When using this const inside `useAnimatedStyle` while it's being used in another random component's style I get the following error: 
in iOS - `TypeError: Attempting to define property on object that is not extensible.`
in Android - `TypeError: Cannot add new property '__reanimatedHostObjectRef'`

And the app crashes right after.

### Expected behavior
Error should not been thrown

### Actual behavior & steps to reproduce
Error thrown and the app crash. 
See code snippet in order to reproduce 

## Snack or minimal code example

```
import {PlatformColor, View, Text} from 'react-native'
import Animated, {useAnimatedStyle} from 'react-native-reanimated'

const myColor = PlatformColor('systemBlue');
// const myColor = PlatformColor('@android:color/holo_blue_bright') // for Android
function App() {

const animatedStyle = useAnimatedStyle(()=> {
  return {
    width: 100,
    height: 100,
    backgroundColor: myColor
  }
})
return <View>
  <Text style={{color: myColor}}> Some Text </Text> // commenting this line prevent from error to be thrown
  <Animated.View style={animatedStyle}/>
</View>
}
```

Cloning `myColor` before using in `useAnimatedStyle` solve the problem. 

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.66.4 |
| react-native-reanimated              | 2.4.1 |
| NodeJS                               |14.17.0|
| Xcode                                |13.1|
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by Latropos** [comment]
Thank you for submitting the issue! We are glad to inform yo that app don't crash anymore. Unfortunately platform colour still can't be animated. This feature is not going to be supported, since it would require a lot of effort, and PlatformColor is not commonly used.
