### ISSUE TITLE
Expo + reanimated not work

### ISSUE THREAD

**Issue by ariran5** [software-mansion/react-native-reanimated#3179]
## Description
Hi, I try write code like there https://youtu.be/KvRqsRwpwhY?t=433 and I use expo
need animate bottom sheet from bottom to top with touch events

### Expected behavior
works without errors

### Actual behavior & steps to reproduce
if I use 2.3.* version app shows this error
<img width="236" alt="Снимок экрана 2022-04-14 в 20 51 00" src="https://user-images.githubusercontent.com/12746457/163448892-44501cd5-5e57-436d-a219-c5a260cf96d5.png">

and if I use 2.7.0 version 
<img width="231" alt="Снимок экрана 2022-04-14 в 20 56 15" src="https://user-images.githubusercontent.com/12746457/163449317-1d5f85b0-a031-4d25-a226-e87792200f93.png">

## Snack or minimal code example

code
https://snack.expo.dev/DZPfBM5UO

## Package versions
2.7.0 and 2.3.1-2.3.3

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.64    |
| react-native-reanimated              |   2.3.1 | 2.7.0      |
| NodeJS                               |      16   |
| Xcode                                |     13    |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |      44   |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by brentvatne** [comment]
only reanimated 2.3.1 is supported in sdk 44

the snack example you linked to is sdk 43, which uses an older version.

**Comment by nixolas1** [comment]
So is it possible to use Reanimated 2.8.0 with Expo somehow? 
I'm trying to update to get the deadlock fix that was released in 2.8.0, but no luck yet.

**Comment by piaskowyk** [comment]
@nixolas1 Expo SDK 45 supports Reanimated 2.8
