### ISSUE TITLE
[v1 api] Calling setValue while debugging freezes app

### ISSUE THREAD

**Issue by computerjazz** [software-mansion/react-native-reanimated#3182]
## Description

Using the v1 api with chrome debugging on, calling `myAnimatedValue.setValue()` causes the app to freeze.

### Expected behavior
App may be used with chrome debugger on.

### Actual behavior & steps to reproduce
App freezes when used with chrome debugger on.

## Snack or minimal code example
![reanimated_setValue-bug](https://user-images.githubusercontent.com/6730148/163628487-b7b5ae92-d42b-480a-946b-ff9c95acca5f.gif)

```tsx
export default function App() {

  const [clicks, setClicks] = useState(0)
  const animVal = useValue<number>(0)

  return (
    <View style={{ flex: 1, marginTop: 45, marginBottom: 50 }}>
      <TouchableOpacity
        style={styles.btn}
        onPress={() => {
          const nextClicks = clicks + 1

          animVal.setValue(nextClicks)

          setClicks(nextClicks)

        }}
      >
        <Text style={styles.text}>Click Me</Text>
      </TouchableOpacity>
      <Text style={styles.counterText}>{`Number of clicks: ${clicks}`}</Text>
    </View>
  );
}
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.65.1       |
| react-native-reanimated              |    2.7.0     |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by StationSoen** [comment]
+1

**Comment by vasihc** [comment]
Same Problem +1

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1 :/ But, maybe you want to try Reanimated v2 API - is much better.

**Comment by computerjazz** [comment]
@piaskowyk I agree the v2 API is nicer, but I have been unable to use it due to performance issues so I've been locked to v1. see the other issue I opened: https://github.com/software-mansion/react-native-reanimated/issues/2845

I have been noticing that performance has getting better lately, I'm hoping I can migrate to v2 in the near future.
