### ISSUE TITLE
undefined is not an object newStyle[key]

### ISSUE THREAD

**Issue by yachaka** [software-mansion/react-native-reanimated#3183]
Just leaving this here as reference for this error when it happens

This happens because either you don't have the babel plugin included, with `'react-native-reanimated/plugin'` in `babel.config.js`,
Or just like in my case, it was because I was using the arrow returning function shorthand :
```
const styles = useAnimatedStyles(() => ({ /* my styles here */ }));
```
Which I replaced to :
```
const styles = useAnimatedStyles(() => {
  return {
    /* my styles here */
  }
});
```

Reanimated version: 2.4.1

**Comment by tomekzaw** [comment]
Hello @yachaka! Thanks for sharing the solution, we really appreciate it. To sum up, here are the steps:

1. Make sure you've added Reanimated Babel plugin in `babel.config.js` (see [installation docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin)), for example:

    ```js
    module.exports = {
      presets: ['module:metro-react-native-babel-preset'],
      plugins: ['react-native-reanimated/plugin'],            // <- add this line
    };
    ```

2. Reset your application cache with
    * `yarn start --reset-cache`
    * OR `npm start -- --reset-cache`
    * OR `expo start -c`
 
3. Reload your app
