### ISSUE TITLE
Unable to resolve module '..utils'

### ISSUE THREAD

**Issue by Lakeyour** [software-mansion/react-native-reanimated#319]
Hello, I've been experimenting with this package and after I finally got the **react-native-gesture-handler** to cooperate, this package turned up with this error

Currently using this version of the package
`"react-native-reanimated": "^1.1.0",`

It seems like a specific file related to the reanimated package is missing a reference or failed to install it onto my system
<img width="326" alt="image" src="https://user-images.githubusercontent.com/25793711/59847531-0cf5ee00-9363-11e9-9294-b39af8eef7b3.png">

What I'm trying to implement into my project is **react-native-tab-view**, however I can't seem to identify the problem here so I would love some help

**EDIT**: I went and looked in my node_modules folder and the folder is there, which means the installation was not a problem

I guess that this line of code would be needed in the AnimatedClock file somewhere
`import utils from '../utils'`

Although I'm not using the AnimatedClock anywhere in my project I'm confused as to why this error happens

**Comment by GNPhoque** [comment]
Same thing for me, tried using react navigation createAnimatedSwitchNavigator from https://reactnavigation.org/docs/en/animated-switch-navigator.html just copy paste + npm i and get the same error, I guess this AnimatedClock is called by the Transition but what can I do?

**Comment by Ashkan-Oliaie** [comment]
getting the same error

**Comment by kagawagao** [comment]
you may need to reset metro cache, try this command:
```bash
npm start -- --reset-cache
```

**Comment by GNPhoque** [comment]
Hhhmm this did not do the trick for me.
First thing after clearing cache (expo r -c) an error appeared saying React was not found (error pointing to the line where I use <Transition.Together>) 
Adding `import React from 'react'; `triggers an other error 

> undefined is not a function (near '...(0, _reactNavigationAnimatedSwitch.createAnimatedSwitchNavigator)...')

**Comment by IAmAbhishekTomar** [comment]
This is works for me  Thanks!! @GNPhoque 

> expo r -c

**Comment by jakub-gonet** [comment]
Hey @Lakeyour,
thanks for submitting this issue and I hope solutions provided by @kagawagao and @GNPhoque resolves your problem 🙂 

I'm closing it, but if you have further questions feel free to reopen
