### ISSUE TITLE
Android crash app 

### ISSUE THREAD

**Issue by zakariadhaimi** [software-mansion/react-native-reanimated#3201]
## Description

Android simulator crashes with no error after launching the app when i delete the animation it works and work good on IOS react native version 0.68.1 and react-native-reanimated version 2.8.0  .

## Snack or minimal code example
```js
const outlineStyle = useAnimatedStyle(() => {
        return {
            transform: [
                {
                    scale: interpolate(liked.value, [1, 0], [0, 1], Extrapolate.CLAMP),
                },
            ],
            easing: Easing.bounce,

        };
    });
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      0.68.1   |
| react-native-reanimated              |      2.8.8   |
| NodeJS                               |    14.17.0     |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |      7.3.3   |
| expo                                 |         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by AndersonVanzo** [comment]
Hey, did you find out any solution? Same problem here
