### ISSUE TITLE
Can't build android

### ISSUE THREAD

**Issue by naum43312016** [software-mansion/react-native-reanimated#3208]
I have "react-native-reanimated": "2.7.0", when I am trying to build Android, I get this error
CMake Error: The source directory "/Users/nauma/Desktop/DEV/rumble_mobile/node_modules/react-native-reanimated/android/--clean-first" does not exist.

same with 2.8.0
can somebody help with that?
Thanks.

- [x ] Android
- [ ] iOS
- [ ] Web

**Comment by mitchdowney** [comment]
@piaskowyk FWIW we are getting this error in our F-Droid build pipeline. We are using react-native-reanimated 2.8.0. Any advice or questions would be appreciated. Sorry, I don't know how to put together a repro for this unfortunately...

https://dev.azure.com/podverse/podverse-fdroid/_build/results?buildId=798&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=96589d7f-1e77-5bd8-e480-061dbe1d8b75&l=1751

**Comment by mitchdowney** [comment]
@naum43312016 @piaskowyk I'm not 100% sure I'm remembering this correctly...but I think I resolved this issue by upgrading from Gradle 4.2.1 to 7.2.0.

I ended up reverting to Gradle 7.0.4 to deal with a separate issue, but it seems like both Gradle 7 versions resolved the build issue.

https://github.com/podverse/podverse-rn/commit/48f32e92833d24bb1225d5fa2326c47be4da6f34
