### ISSUE TITLE
Issue interacting with React Native Maps, re-adds children that were removed

### ISSUE THREAD

**Issue by l-barbosa** [software-mansion/react-native-reanimated#3210]
## Description

Initially thought to be a bug with the [react-native-maps](https://github.com/react-native-maps/react-native-maps) library, the issue was that map markers, children of the `MapView` component, were being removed but remained in place.
After trying to set up a demo project to post the bug report to `react-native-maps` the issue was not manifesting itself on the demo project.
After setting breakpoints on the Obj-C side of `react-native-maps`, I found that as the project is removing children, `react-native-reanimated` seems to be adding them back. This in turn causes `react-native-maps` to intercept the adding of children, which causes it to add the marker back to the map.

### Expected behavior
Markers should be removed from the map as the `<Marker />` child is removed from the `<MapView />`

### Actual behavior & steps to reproduce
Markers are removed but re-added to the view

## Snack or minimal code example
You can find a repository that shows the issue [here](https://github.com/l-barbosa/react-native-maps-reanimated-issue).
There you'll find the following section:
```
{showMarkers && (
        <Animated.View
          style={styles.animation}
          entering={BounceIn}
          exiting={BounceOut}>
          <Text style={styles.animationText}>
            Useless animation to trigger the use of reanimated!
          </Text>
        </Animated.View>
      )}
```
This animation is there so that `reanimated` enters the picture. If you remove this block, everything works as expected and markers are removed as you zoom out and re-added as you zoom back in.

It's not clear if the issue is with the way `reanimated` does things or if it's how `react-native-maps` handles markers. From what I can see, since markers are not standard views but are added as "Annotations" by calling the respective iOS sdk method, subviews are being intercepted by `react-native-maps` so that the annotation can be added instead. However, somewhere in the process `reanimated` seems to be syncing the children and adding them back.

This has been posted on their repo too, before the connection with `reanimated` was found, you can find it [here](https://github.com/react-native-maps/react-native-maps/issues/4214), 

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.68.1    |
| react-native-reanimated              |    2.8.0     |
| react-native-maps              |    0.31.0     |

## Affected platforms

- [ ] Android
- [ x ] iOS
- [ ] Web

**Comment by l-barbosa** [comment]
I was able to work around the issue by patching the library.
You can find [the patch](https://github.com/l-barbosa/react-native-maps-reanimated-issue/blob/master/patches/react-native-reanimated%2B2.8.0.patch) in the demo repository.

Unfortunately involves detecting the presence of the `react-native-maps` library so I don't think it's a great contribution to this library.
The patch just excludes AIRMapMarker from being re-added for layout animations in a similar way that it is current excluding `RNSScreenView` from `react-native-screens`. I wonder what the two cases have in common to require this exception.
I know that in the case of the map marker, it's not an actual "view" that gets added as such but intercepted to call the SDK method to add the annotation/marker.

Leaving this information here in case someone more familiar with the process can find a more generic approach to this that can be included in the library.

**Comment by arvind-balaji** [comment]
Any chance there is a javsacript-side workaround/patch for this? Our is app is using Expo at the moment and I'd hate to have to eject just to patch this bug.

**Comment by aaron-barbieriaghib** [comment]
@l-barbosa I think i'm experiencing the same exact issue. But patching the node module doesn't seem to be working for me. @arvind-balaji I'm also using expo, what was your solution to this?

**Comment by vxm5091** [comment]
+1 having this issue as well when using `react-native-maps` with `react-native-reanimated`. Is there any other potential fix on the `reanimated` side? 

`react-native-reanimated 2.8.0`

![IMG_9B3AE1F9541E-1](https://user-images.githubusercontent.com/57078583/200076664-0b477151-3af7-4e0e-aba2-17fe01618b44.jpeg)

**Comment by bbarthec** [comment]
I'm cross-posting my solution to the problem:
- https://github.com/react-native-maps/react-native-maps/issues/4214#issuecomment-1330745910

**Comment by tjzel** [comment]
I tested it on Reanimated 3.6.1 and everything seems to be fine.
