### ISSUE TITLE
Typescript error with style prop of Animated.View

### ISSUE THREAD

**Issue by alois-beto** [software-mansion/react-native-reanimated#3213]
There is a Typescript error when using an `Animated.Value` in style prop of an `Animated.View` component:

```typescript
const driver = useRef<Animated.Value<number>>(new Animated.Value(0)).current;

// ...

const opacity = driver.interpolate({
	inputRange: [0, 0.5, 1],
	outputRange: [0, 0, 1],
});

return <Animated.View style={{ opacity }} />;
```

Leads to this TS error on `style` prop : 
```
No overload matches this call.
  Overload 1 of 2, '(props: AnimateProps<ViewProps> | Readonly<AnimateProps<ViewProps>>): View', gave the following error.
    Type '{ opacity: Reanimated.Node<number>; }' is not assignable to type '((false | ViewStyle | RegisteredStyle<ViewStyle> | RecursiveArray<ViewStyle | Falsy | RegisteredStyle<ViewStyle>> | AnimatedNode<...>) & (false | ... 4 more ... | RecursiveArray<...>)) | null | undefined'.
      Type '{ opacity: Reanimated.Node<number>; }' is not assignable to type 'undefined'.
  Overload 2 of 2, '(props: AnimateProps<ViewProps>, context: any): View', gave the following error.
    Type '{ opacity: Reanimated.Node<number>; }' is not assignable to type '((false | ViewStyle | RegisteredStyle<ViewStyle> | RecursiveArray<ViewStyle | Falsy | RegisteredStyle<ViewStyle>> | AnimatedNode<...>) & (false | ... 4 more ... | RecursiveArray<...>)) | null | undefined'.
      Type '{ opacity: Reanimated.Node<number>; }' is not assignable to type 'undefined'.ts(2769)
```

This bug is present since version 2.4.1, there is already an issue opened at that time (#2968) but the bug still exists with latest version (2.8.0) so I am opening this one.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.68.1      |
| react-native-reanimated              |   2.8.0      |
| NodeJS                               |    16.15.0     |
| Typescript                                |     4.6.3    |

**Comment by Ryanjso** [comment]
were you able to figure this out?

**Comment by alois-beto** [comment]
No 😕
I put some `@ts-ignore` temporarily 🤷‍♂️

**Comment by Ryanjso** [comment]
I actually found the answer shortly after commenting, I probably should have looked a bit more 🤦🏼‍♂️. Looks like it was fixed in end of Jun if you upgrade to latest version 
https://github.com/software-mansion/react-native-reanimated/pull/3301

**Comment by alois-beto** [comment]
Oh great I will look into this

**Comment by Latropos** [comment]
Thanks for reporting the issue! Yes, the bug has already been fixed, please try newer release
