### ISSUE TITLE
Layout animations don't work when Debug with Chrome is enabled

### ISSUE THREAD

**Issue by camcnz** [software-mansion/react-native-reanimated#3218]
## Description
The layout animations and events (entering, exiting, layout) don't work when Debug with Chrome is enabled

### Actual behavior & steps to reproduce

Run the app then turn on Debug with Chrome. None of the animations work after.

## Snack or minimal code example

```
const App = () => {
  const [count, setCount] = useState(0);

  return (
    <View style={styles.counterContainer}>
      <Animated.View
        key={count}
        style={styles.counterFlip}
        entering={FlipInXUp.springify()}
        exiting={FlipOutXDown.springify()}>
        <Text style={styles.counterText}>{count}</Text>
      </Animated.View>
      <Pressable
        style={[styles.button, styles.subBtn]}
        onPress={() => setCount(count - 1)}>
        <Text style={styles.btnText}>{'-'}</Text>
      </Pressable>
      <Pressable
        style={[styles.button, styles.addBtn]}
        onPress={() => setCount(count + 1)}>
        <Text style={styles.btnText}>{'+'}</Text>
      </Pressable>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  counterContainer: {
    backgroundColor: '#EEE',
    width: '90%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    marginBottom: 8,
    overflow: 'hidden',
    paddingVertical: 8,
  },
  counterText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 54,
    letterSpacing: 2,
    lineHeight: 64,
  },
  button: {
    position: 'absolute',
    backgroundColor: '#111',
    top: 0,
    borderRadius: 40,
    height: 80,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subBtn: {left: 6},
  addBtn: {right: 6},
  btnText: {
    color: '#FFF',
    fontWeight: '400',
    fontSize: 54,
    lineHeight: 56,
  },
  counterFlip: {
    backgroundColor: '#000',
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    height: 90,
    borderRadius: 6,
  },
});

export default App;
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.67.2      |
| react-native-reanimated              |    2.8.0     |
| NodeJS                               |     16.13.1   |
| Xcode                                |    13.2.1      |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by hirbod** [comment]
Strong advice: do not use LayoutAnimations until this issue is solved:
https://github.com/software-mansion/react-native-reanimated/issues/3124

**Comment by piaskowyk** [comment]
Hey @camcnz Until we implement Layout Animation for the web there is no possibility to use Layout Animation with Chrome debugger. LA requires native implementation, but the Chrome engine can't execute the native JSI function inside its own runtime. At this moment I don't know when we will implement LA for the web.
