### ISSUE TITLE
Configuration with name 'compile' not found.

### ISSUE THREAD

**Issue by FallikTheCat** [software-mansion/react-native-reanimated#3242]
## Description

Hi, so I created a new project a few days ago. I was working on iOS and everything was fine. Then yesterday when I try to run android, I got this error.

Build file 'F:\reactnative\\***AppName***\node_modules\react-native-reanimated\android\build.gradle' line: 64

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Configuration with name 'compile' not found.
 -->

### Actual behavior & steps to reproduce

//In projects folder

yarn add react-native-reanimated
yarn react-native run-android

## Snack or minimal code example

![Ekran görüntüsü 2022-05-14 140718](https://user-images.githubusercontent.com/43357370/168423181-d9a8c17a-4896-4a3a-a3f3-0e1bda918b74.png)

## Package versions

"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.4",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/analytics": "^14.9.3",
    "@react-native-firebase/app": "^14.9.3",
    "@react-native-firebase/crashlytics": "^14.9.3",
    "@react-native-firebase/database": "^14.9.3",
    "@react-native-firebase/messaging": "^14.9.3",
    "react": "17.0.2",
    "react-native": "^0.68.2",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-reanimated": "1.13.4",
    "react-native-router-flux": "^4.3.1",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1"
  },
## Affected platforms

- [X ] Android
- [ ] iOS
- [ ] Web

**Comment by ngxhuyhoang** [comment]
Same

**Comment by piaskowyk** [comment]
Unfortunately, we no longer support Reanimated v1 :/ I recommend updating to 2.+ version.

**Comment by antFrancon** [comment]
Hi @FallikTheCat
I've encountered the same issue with a legacy app.
Here is the patch I applied to make it work again with reanimated v1:

```diff
+configurations {
+  customConfig.extendsFrom implementation
+}
+
 afterEvaluate { project ->
 
     task androidJavadoc(type: Javadoc) {
         source = android.sourceSets.main.java.srcDirs
         classpath += files(android.bootClasspath)
-        classpath += files(project.getConfigurations().getByName('compile').asList())
+        classpath += files(project.getConfigurations().getByName('customConfig').asList())
         include '**/*.java'
     }
```

**Comment by Bilal-Abdeen** [comment]
I found a workaround, which was suggested for a different error #2494. 

Add a section to the file `<project_folder>/android/build.gradle`
```
subprojects { subproject ->
        if(project['name'] == 'react-native-reanimated'){
            project.configurations { compile { } }
        }
}
```

**Comment by kwambokaB** [comment]
> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

This works. Thank you

**Comment by bosz** [comment]
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

Thanks a lot. This worked well for me.

**Comment by aishwaryashi** [comment]
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```
where should i add this in  build.gradle file  ?

**Comment by Bilal-Abdeen** [comment]
@aishwaryashi You can add it to the bottom of the file (outside all sections).

**Comment by artnest** [comment]
> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

Thanks, that worked! Although I want to add a suggestion, because the IDE shows me a warning and complaints about inconvertible types. Also `subproject` variable is unused.
```groovy-gradle
subprojects { project ->
    if (project.name == 'react-native-reanimated') {
        project.configurations { compile {} }
    }
}
```

**Comment by yasminOrdex** [comment]
> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

not 

> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

not worked

**Comment by MathewAzmat** [comment]
> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

Thank you! worked for me

**Comment by hackaprende** [comment]
> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

The error is gone, but then when compiling the app does not find the libraries:
error: package com.facebook.react.bridge does not exist

**Comment by zoomc** [comment]
> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

i love you

**Comment by Ef-Eff** [comment]
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

This has given me another error
```
> Failed to apply plugin 'com.facebook.react.rootproject'.
   > A problem occurred configuring project ':app'.
      > Cannot change resolution strategy of dependency configuration ':react-native-reanimated:compile' after it has been resolved.
      ```

**Comment by fabioguieiro** [comment]
> I found a workaround, which was suggested for a different error #2494.
> 
> Add a section to the file `<project_folder>/android/build.gradle`
> 
> ```groovy-gradle
> subprojects { subproject ->
>         if(project['name'] == 'react-native-reanimated'){
>             project.configurations { compile { } }
>         }
> }
> ```

worked like a charm, thanks

**Comment by User-DK** [comment]
@Bilal-Abdeen Thanks a lot Worked for me as well!!
