### ISSUE TITLE
SlideInLeft or SlideInRight not working at android.

### ISSUE THREAD

**Issue by sbin1211** [software-mansion/react-native-reanimated#3245]
SlideInLeft or SlideInRight not working at android.

## Description

run bellow code at android,  it not work at android, but okay at ios.
```
export const AnimtedTest = () => {
	const [toggle, setToggle] = React.useState(false);
	return (
		<View>
			<Press
				onPress={() => {
					setToggle(!toggle);
				}}
			>
				<Text>Test</Text>
			</Press>
			{toggle && (
				<Animated.View entering={SlideInLeft} exiting={SlideOutDown}>
					<Text>googl</Text>
				</Animated.View>
			)}
		</View>
	);
};
```
but if we wrap it inside another Animated.View, then it behaviour  correctly at android 

```
export const AnimtedTest = () => {
	const [toggle, setToggle] = React.useState(false);
	return (
		<View>
			<Press
				onPress={() => {
					setToggle(!toggle);
				}}
			>
				<Text>Test</Text>
			</Press>
			{toggle && (
 // here wrapped by another Aniamted.View
				<Animated.View>
					<Animated.View entering={SlideInLeft} exiting={SlideOutDown}>
						<Text>googl</Text>
					</Animated.View>
				</Animated.View>
			)}
		</View>
	);
};
```

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.68    |
| react-native-reanimated              |   ~2.8.0      |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by bfricka** [comment]
I'm able to use `SlideInLeft` with no issues on Android w/ RN 0.67.4 and latest stable reanimated. Layout animations are currently bugged (using even one of them causes duplicate nodes that never get destroyed), and shouldn't be used, but they do work.

**Comment by Latropos** [comment]
Hi @sbin1211!

Thank you for submitting your issue!
Right now everything works fine on android. Did you have two emulators (IOS & android) open at the time of testing? In such a case android may show random bugs (but refreshing should help). We have also rewritten our layout animations (which means that it is also possible that the bug existed and got fixed)

https://github.com/software-mansion/react-native-reanimated/assets/56199675/c315de9b-e0f3-4fce-88d2-ed27b6da897c
