### ISSUE TITLE
Automatically import Animated operators

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#325]
see #503

**Comment by wcandillon** [comment]
These seem to now work on VSCode.

**Comment by satya164** [comment]
I think it's best just to drop the default export and use named export for everything:

```js
import {Value, eq} from "react-native-reanimated";
```

We destructure the default export later anyway, and if someone wants `Animated.x` they could always do `* as Animated`.

**Comment by tsdmrfth** [comment]
@wcandillon The second idea makes more sense. 🤔
