### ISSUE TITLE
Failed to run Example

### ISSUE THREAD

**Issue by nartc** [software-mansion/react-native-reanimated#326]
![image](https://user-images.githubusercontent.com/25516557/60316327-a6a73780-992f-11e9-981c-ee1506c89898.png)

Got this error trying to run the `Example`

I've tried:
- `npm start`
- `yarn start`
- `reset-cache`
...all the suggestions in the error...

but still failing. Any suggestions?

**Comment by jakub-gonet** [comment]
Hi, 
sorry for the late response

This issue is quite old so I'm closing it.

If the problem still persists or you have further questions I'm glad to assist you
