### ISSUE TITLE
[iOS] Build errors with reanimated 3.0.0-rc.0 and react-native 0.68.2/0.69.0-rc.1

### ISSUE THREAD

**Issue by kesha-antonov** [software-mansion/react-native-reanimated#3260]
## Description

Hi!

I've tried to build reanimated with recent RN and have errors:

<img width="825" alt="Screenshot 2022-05-19 at 14 43 24" src="https://user-images.githubusercontent.com/11584712/169285976-77892c72-ec1b-41fe-b605-8c8f296dda6d.png">

### Expected behavior

No errors.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.69.0-rc.1    |
| react-native-reanimated              |      3.0.0-rc.0   |
| NodeJS                               |      v16.14.0   |
| Xcode                                |        13.3.1 |
| Java                                 |    openjdk 11.0.15 2022-04-19 LTS     |
| Gradle                               |    7.1.1     |
| expo                                 |      45.0.4   |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by kerryaustin** [comment]
Same issue here, fresh install RN (0.69.0-rc.3) and reanimated (3.0.0-rc.0)

**Comment by kerryaustin** [comment]
Figured out my issue, I believe I installed react-native via an old react-native-cli. The errors above were dude to having 0.68.2 versions of pods being installed even though i had react-native pinned to 0.69.

@kesha-antonov you might want to check that you actually have react-native 0.69 in your node_modules.

FYI 0.69 new arch installs hermes by default and the hermes-engine build took a long time (~1 hour) on my 2018 mbp

**Comment by kesha-antonov** [comment]
> Figured out my issue, I believe I installed react-native via an old react-native-cli. The errors above were due to having 0.68.2 versions of pods being installed even though i had react-native pinned to 0.69.
> 
> @kesha-antonov you might want to check that you actually have react-native 0.69 in your node_modules.
> 
> FYI 0.69 new arch installs hermes by default and the hermes-engine build took a long time (~1 hour) on my 2018 mbp

Couldn't build with rn 0.69-rc.3
