### ISSUE TITLE
Transform with key of `translateY` must be a number

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-reanimated#3262]
## Description

Since upgrading to React Native `0.68`, and Reanimated `2.8`, I can no longer use strings for animated transform values without getting an error.

The error is only thrown if a string transform is used on the view's _first render_.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/13172299/169348062-cd467096-cc9c-4457-8076-12196b2dc512.png">

### Expected behavior

This shouldn't crash. It worked fine on older versions of RN.

```ts
const style = useAnimatedStyle(() => ({
    transform: [
      {
        translateY: withSpring("0%"),
      },
    ],
  }))
```

I think this happens because the initial style is passed down as a plain object to React Native or something. If I use it **after the first render**, then it works fine.

### Actual behavior & steps to reproduce

Use a string for `translateY` inside of `useAnimatedStyle`.

Again, it **only breaks if it has a string on the initial render.**

### Code

```jsx
import Animated, {
  useAnimatedStyle,
  withSpring,
} from "react-native-reanimated";

export default function App() {
  const style = useAnimatedStyle(() => ({
    transform: [
      {
        translateY: withSpring("0%"),
      },
    ],
  }));

  return <Animated.View style={style} />;
}
```

Repo: https://github.com/nandorojo/reanimated-transform-bug

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.68.2     |
| react-native-reanimated              |   2.8      |
| expo                                 |   45      |

## Affected platforms
 
- [ ] Android
- [x] iOS
- [ ] Web

## Hack solution

Since this only breaks on first mount, you can fix it by using a `number` before the component has mounted. This is not desirable, however.

```tsx
import { useEffect } from "react";
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withSpring,
} from "react-native-reanimated";

export default function App() {
  const mounted = useSharedValue(false);
  const style = useAnimatedStyle(() => ({
    transform: [
      {
        translateY: !mounted.value ? 0 : withSpring("0%"),
      },
    ],
  }));

  useEffect(() => {
    mounted.value = true;
  }, []);

  return <Animated.View style={style} />;
}
```

**Comment by nandorojo** [comment]
Here is a RN patch I am using to make it work:

`node_modules/react-native/Libraries/StyleSheet/processTransform.js` line 246:

```diff
case 'translateX':
case 'translateY':
+ break
```

**Comment by switz** [comment]
Ah this is is showing up at https://github.com/nandorojo/moti/issues/301

anyone know of a workaround without patching RN?

**Comment by garrettboatman** [comment]
For any Tamagui users landing here, I had to roll back to `1.39.9` to fix this.

**Comment by Latropos** [comment]
Thank you very much for submitting the issue. Indeed you're right that it has been working before and now the above-mentioned behaviour is no longer supported. However the support was dropped from react native and we have limited possibilities to implement deprecated features in our library. You can check in react-native documentation that now translate values are expected to be numbers: https://reactnative.dev/docs/transforms
