### ISSUE TITLE
Dynamic withSequence Call only called once

### ISSUE THREAD

**Issue by NathanCFoster** [software-mansion/react-native-reanimated#3269]
## Description

```js
const rotationStyle = useAnimatedStyle(() => {
        return {
            transform:
                [
                    {
                        rotate: shakeRotate.value !== 1 ?
                            withTiming(show ? "180deg" : "0deg", { duration: 300, easing: Easing.bounce })
                            :
                            withSequence(
                                withTiming("30deg", { duration: 100, easing: Easing.in }),
                                withTiming("-30deg", { duration: 100, easing: Easing.in }),
                                withTiming("0deg", { duration: 100, easing: Easing.in }))
                    }
                ]
        }
    }, [show, update])
```

When running above code the animation is only played once, and is cancelled. After the animation is cancelled it won't run again.

### Expected behavior

With sequence animation isn't cancelled and is able to run multiple times.

### Actual behavior & steps to reproduce

Add an animated view with a touchable component and on press update the state {update} while having shakeRotate.value set as 1. 

## Snack or minimal code example

Minimal code example is above

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.68.1 |
| react-native-reanimated              |  2.8.0 |
| NodeJS                               |  16.5.0|
| Xcode 13.4
Build version 13F17a|

## Affected platforms

- [unsure ] Android
- [x ] iOS
- [ unsure] Web

**Comment by graszka22** [comment]
I can reproduce it on all platforms, here is a snack: https://snack.expo.dev/KmEYozpZs (click the red button quickly a few times, animation will stop working).
