### ISSUE TITLE
Android crash when using ReText inside a Flatlist with getItemLayout set

### ISSUE THREAD

**Issue by JohanLH** [software-mansion/react-native-reanimated#3270]
## Description

When using ReText from react-native-redash inside a flatlist where getItemLayout is set with itemHeight it will cause the view to crash on android with error `Attempt to read from field 'Int androld.vIew. VIewGroup$LayoutParams.wldth on a null object reference`

### Expected behavior

It should behave the same as ios and not crash.

### Actual behavior & steps to reproduce

Clone `git clone https://github.com/software-mansion-labs/reanimated-2-playground.git`

yarn add react-native-redash

Replace Screen.js with the below snippet, run the app and it should crash on android. If you remove getItemLayout or if the list is too tiny to be scroll it will work great.

## Snack or minimal code example

```js
import React from 'react';
import {
  useSharedValue,
  withTiming,
  useDerivedValue,
} from 'react-native-reanimated';
import {FlatList, View, Button} from 'react-native';
import {ReText} from 'react-native-redash';

const data = [1, 2, 3, 4, 5, 56, 7, 8, 9];

export default function AnimatedStyleUpdateExample(props) {
  const randomWidth = useSharedValue(10);

  const test = useDerivedValue(() => `${randomWidth.value}`);

  return (
    <View style={{flex: 1}}>
      <FlatList
        keyExtractor={(item) => item}
        data={data}
        getItemLayout={(data, index) => ({
          length: 400,
          offset: 400 * index,
          index,
        })}
        renderItem={() => (
          <View style={{height: 400}}>
            <ReText text={test} />
          </View>
        )}
      />
      <Button
        title="toggle"
        onPress={() => {
          randomWidth.value = withTiming(Math.random() * 350, {
            duration: 10000,
          });
        }}
      />
    </View>
  );
}
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.65.1    |
| react-native-reanimated              |    2.3.1     |
| NodeJS                               |    17.6.0     |
| Xcode                                |   13.1      |
| Java                                 |     11.0.15    |
| Gradle                               |     6.9    |

## Affected platforms

- [ x ] Android
- [ ] iOS
- [ ] Web

**Comment by Latropos** [comment]
I've just tested your issue (on newest reanimated) and it seems to work fine. It is very old so I can assume we have already fix it.
