### ISSUE TITLE
[RN 0.65, REA 2.2.1, 2.5.0, 2.8.0] IOS Only Crash on startup

### ISSUE THREAD

**Issue by Hezron-Nelapati** [software-mansion/react-native-reanimated#3285]
## Description
ios app is crashing on startup.

I tried using REA 2.8.0, 2.5.0, 2.2.1, but the ios app is crashing on startup.

### Expected behavior
App should run without errors.

### Actual behavior & steps to reproduce
ios app is crashing on startup.

## Snack or minimal code example

<img width="587" alt="Screenshot 2022-06-03 at 2 16 37 AM" src="https://user-images.githubusercontent.com/62951600/171736974-c6c72294-4bda-4037-924c-5ba07df1272d.png">

## Package versions

React Native Info

System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 28.76 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-30 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.2 => 0.65.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Related Dependencies Versions:

"react-native-reanimated": "2.2.1",
"react-native-screens": "3.11.0",
"react-native-gesture-handler": "^2.4.2",
"@react-native-masked-view/masked-view": "^0.2.6",
"@react-navigation/bottom-tabs": "^6.3.1",
"@react-navigation/drawer": "^6.4.1",
"@react-navigation/native": "^6.0.10",
"@react-navigation/native-stack": "^6.6.2",
"@react-navigation/stack": "^6.2.1",

## Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

**Comment by sulemanbutt10** [comment]
i am facing this same error... plz provide a solution.

**Comment by Hezron-Nelapati** [comment]
@sulemanbutt10 Downgrade to version 1, it will work.

**Comment by graszka22** [comment]
Please provide a minimal reproducible example, for example a link to a Github repository.

**Comment by Hezron-Nelapati** [comment]
@graszka22 From my understanding, just using the reanimated v2 package itself is causing a issue. You can take a look at related dependencies and even integrate them into a demo project. I'm sure you will get the same issue.

**Comment by graszka22** [comment]
I've just run a newly cloned reanimated playground with exactly the same dependencies on iOS and no crash for me. Without more details we're not able to help you.

**Comment by Hezron-Nelapati** [comment]
@graszka22 I also tried to replicate it, but unable to do so. I think you can close the issue. But when the issue occured the issue came from this function and lead to creation of bad pointer with address of 0x0. As you can see in the initial screenshot, cloneSymbol function generated a 0x0 address, not sure how the original address of event got converted to 0x0.

<img width="778" alt="Screenshot 2022-06-19 at 10 12 15 PM" src="https://user-images.githubusercontent.com/62951600/174491481-9fa934b0-cd1a-490c-b4bc-2265b4874101.png">
