### ISSUE TITLE
[Android] Build failed during upgrading to react-native 0.68 (fabric)

### ISSUE THREAD

**Issue by MichDreby** [software-mansion/react-native-reanimated#3292]
Build failed during upgrading to react-native 0.68.2 (fabric)

## Description

Try upgrading react-native from 0.67.2 to 0.68.2 with enabled new architecture.
1. made everything according official guide (https://reactnative.dev/docs/new-architecture-intro)
2. newArchEnabled=false (in gradle.properties)
3. everything is fine

But, when set newArchEnabled=true (in gradle.properties) android build is failed, the following error:

Execution failed for task ':react-native-reanimated:buildCMakeDebug'.
> Build command failed.
  Error while executing process /Users/michdreby/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/android/.cxx/Debug/2ex1e2t2/armeabi-v7a reanimated}
  ninja: Entering directory `/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/android/.cxx/Debug/2ex1e2t2/armeabi-v7a'
  [1/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Tools/FeaturesConfig.cpp.o
  [2/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Tools/WorkletEventHandler.cpp.o
  [3/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Tools/Scheduler.cpp.o
  [4/19] Building CXX object CMakeFiles/reanimated.dir/src/main/cpp/TurboModule.cpp.o
  [5/19] Building CXX object CMakeFiles/reanimated.dir/src/main/cpp/OnLoad.cpp.o
  FAILED: CMakeFiles/reanimated.dir/src/main/cpp/OnLoad.cpp.o 
  /Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dreanimated_EXPORTS -I../../../../../../react-native/ReactAndroid/src/main/jni/first-party/fbjni/headers -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/third-party-ndk/glog/exported -I../../../../../../react-native/React -I../../../../../../react-native/React/Base -I../../../../../../react-native/ReactAndroid/src/main/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/jni -I../../../../../../react-native/ReactCommon -I../../../../../../react-native/ReactCommon/callinvoker -I../../../../../../react-native/ReactCommon/jsi -I../../../../../../react-native/ReactCommon/react/renderer/graphics/platform/cxx -I../../../../../../react-native/ReactCommon/runtimeexecutor -I../../../../../../react-native/ReactCommon/turbomodule/core -I../../../../../../react-native/ReactCommon/turbomodule -I../../../../../../react-native/ReactCommon/yoga -I../../../../../../hermes-engine/android/include -I../../../../../Common/cpp/headers/Tools -I../../../../../Common/cpp/headers/SpecTools -I../../../../../Common/cpp/headers/NativeModules -I../../../../../Common/cpp/headers/SharedItems -I../../../../../Common/cpp/headers/Registries -I../../../../../Common/cpp/headers/LayoutAnimations -I../../../../../Common/cpp/headers/AnimatedSensor -I../../../../../Common/cpp/headers/Fabric -I../../../../../Common/cpp/hidden_headers -I../../../../src/main/cpp/headers -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DFOLLY_HAVE_RECVMMSG=1 -DFOLLY_HAVE_PTHREAD=1 -DON_ANDROID -DONANDROID -DANDROID -DFOR_HERMES=true -fexceptions -fno-omit-frame-pointer -frtti -Wno-sign-compare -std=c++17 -Wall -DRCT_NEW_ARCH_ENABLED -O0 -fno-limit-debug-info  -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/reanimated.dir/src/main/cpp/OnLoad.cpp.o -MF CMakeFiles/reanimated.dir/src/main/cpp/OnLoad.cpp.o.d -o CMakeFiles/reanimated.dir/src/main/cpp/OnLoad.cpp.o -c ../../../../src/main/cpp/OnLoad.cpp
  In file included from ../../../../src/main/cpp/OnLoad.cpp:6:
  ../../../../src/main/cpp/headers/NativeProxy.h:4:10: fatal error: 'JFabricUIManager.h' file not found
  #include <JFabricUIManager.h>
           ^~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [6/19] Building CXX object CMakeFiles/reanimated.dir/src/main/cpp/NativeProxy.cpp.o
  FAILED: CMakeFiles/reanimated.dir/src/main/cpp/NativeProxy.cpp.o 
  /Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dreanimated_EXPORTS -I../../../../../../react-native/ReactAndroid/src/main/jni/first-party/fbjni/headers -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/third-party-ndk/glog/exported -I../../../../../../react-native/React -I../../../../../../react-native/React/Base -I../../../../../../react-native/ReactAndroid/src/main/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/jni -I../../../../../../react-native/ReactCommon -I../../../../../../react-native/ReactCommon/callinvoker -I../../../../../../react-native/ReactCommon/jsi -I../../../../../../react-native/ReactCommon/react/renderer/graphics/platform/cxx -I../../../../../../react-native/ReactCommon/runtimeexecutor -I../../../../../../react-native/ReactCommon/turbomodule/core -I../../../../../../react-native/ReactCommon/turbomodule -I../../../../../../react-native/ReactCommon/yoga -I../../../../../../hermes-engine/android/include -I../../../../../Common/cpp/headers/Tools -I../../../../../Common/cpp/headers/SpecTools -I../../../../../Common/cpp/headers/NativeModules -I../../../../../Common/cpp/headers/SharedItems -I../../../../../Common/cpp/headers/Registries -I../../../../../Common/cpp/headers/LayoutAnimations -I../../../../../Common/cpp/headers/AnimatedSensor -I../../../../../Common/cpp/headers/Fabric -I../../../../../Common/cpp/hidden_headers -I../../../../src/main/cpp/headers -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DFOLLY_HAVE_RECVMMSG=1 -DFOLLY_HAVE_PTHREAD=1 -DON_ANDROID -DONANDROID -DANDROID -DFOR_HERMES=true -fexceptions -fno-omit-frame-pointer -frtti -Wno-sign-compare -std=c++17 -Wall -DRCT_NEW_ARCH_ENABLED -O0 -fno-limit-debug-info  -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/reanimated.dir/src/main/cpp/NativeProxy.cpp.o -MF CMakeFiles/reanimated.dir/src/main/cpp/NativeProxy.cpp.o.d -o CMakeFiles/reanimated.dir/src/main/cpp/NativeProxy.cpp.o -c ../../../../src/main/cpp/NativeProxy.cpp
  In file included from ../../../../src/main/cpp/NativeProxy.cpp:20:
  ../../../../src/main/cpp/headers/NativeProxy.h:4:10: fatal error: 'JFabricUIManager.h' file not found
  #include <JFabricUIManager.h>
           ^~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [7/19] Building CXX object CMakeFiles/reanimated.dir/src/main/cpp/AndroidErrorHandler.cpp.o
  [8/19] Building CXX object CMakeFiles/reanimated.dir/src/main/cpp/AndroidScheduler.cpp.o
  [9/19] Building CXX object CMakeFiles/reanimated.dir/src/main/cpp/JNIHelper.cpp.o
  [10/19] Building CXX object CMakeFiles/reanimated.dir/src/main/cpp/LayoutAnimations.cpp.o
  [11/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsProxy.cpp.o
  [12/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp.o
  [13/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Tools/JSIStoreValueUser.cpp.o
  [14/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Tools/Mapper.cpp.o
  [15/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp.o
  FAILED: CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp.o 
  /Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dreanimated_EXPORTS -I../../../../../../react-native/ReactAndroid/src/main/jni/first-party/fbjni/headers -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/third-party-ndk/glog/exported -I../../../../../../react-native/React -I../../../../../../react-native/React/Base -I../../../../../../react-native/ReactAndroid/src/main/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/jni -I../../../../../../react-native/ReactCommon -I../../../../../../react-native/ReactCommon/callinvoker -I../../../../../../react-native/ReactCommon/jsi -I../../../../../../react-native/ReactCommon/react/renderer/graphics/platform/cxx -I../../../../../../react-native/ReactCommon/runtimeexecutor -I../../../../../../react-native/ReactCommon/turbomodule/core -I../../../../../../react-native/ReactCommon/turbomodule -I../../../../../../react-native/ReactCommon/yoga -I../../../../../../hermes-engine/android/include -I../../../../../Common/cpp/headers/Tools -I../../../../../Common/cpp/headers/SpecTools -I../../../../../Common/cpp/headers/NativeModules -I../../../../../Common/cpp/headers/SharedItems -I../../../../../Common/cpp/headers/Registries -I../../../../../Common/cpp/headers/LayoutAnimations -I../../../../../Common/cpp/headers/AnimatedSensor -I../../../../../Common/cpp/headers/Fabric -I../../../../../Common/cpp/hidden_headers -I../../../../src/main/cpp/headers -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DFOLLY_HAVE_RECVMMSG=1 -DFOLLY_HAVE_PTHREAD=1 -DON_ANDROID -DONANDROID -DANDROID -DFOR_HERMES=true -fexceptions -fno-omit-frame-pointer -frtti -Wno-sign-compare -std=c++17 -Wall -DRCT_NEW_ARCH_ENABLED -O0 -fno-limit-debug-info  -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp.o -MF CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp.o.d -o CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp.o -c /Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp
  /Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp:54:47: error: 'getShadowTreeRegistry' is a private member of 'facebook::react::UIManager'
    const auto &shadowTreeRegistry = uiManager->getShadowTreeRegistry();
                                                ^
  ../../../../../../react-native/ReactCommon/react/renderer/uimanager/UIManager.h:187:29: note: declared private here
    ShadowTreeRegistry const &getShadowTreeRegistry() const;
                              ^
  1 error generated.
  [16/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Tools/RuntimeDecorator.cpp.o
  [17/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp.o
  FAILED: CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp.o 
  /Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/michdreby/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dreanimated_EXPORTS -I../../../../../../react-native/ReactAndroid/src/main/jni/first-party/fbjni/headers -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/third-party-ndk/glog/exported -I../../../../../../react-native/React -I../../../../../../react-native/React/Base -I../../../../../../react-native/ReactAndroid/src/main/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I../../../../../../react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/jni -I../../../../../../react-native/ReactCommon -I../../../../../../react-native/ReactCommon/callinvoker -I../../../../../../react-native/ReactCommon/jsi -I../../../../../../react-native/ReactCommon/react/renderer/graphics/platform/cxx -I../../../../../../react-native/ReactCommon/runtimeexecutor -I../../../../../../react-native/ReactCommon/turbomodule/core -I../../../../../../react-native/ReactCommon/turbomodule -I../../../../../../react-native/ReactCommon/yoga -I../../../../../../hermes-engine/android/include -I../../../../../Common/cpp/headers/Tools -I../../../../../Common/cpp/headers/SpecTools -I../../../../../Common/cpp/headers/NativeModules -I../../../../../Common/cpp/headers/SharedItems -I../../../../../Common/cpp/headers/Registries -I../../../../../Common/cpp/headers/LayoutAnimations -I../../../../../Common/cpp/headers/AnimatedSensor -I../../../../../Common/cpp/headers/Fabric -I../../../../../Common/cpp/hidden_headers -I../../../../src/main/cpp/headers -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DFOLLY_HAVE_RECVMMSG=1 -DFOLLY_HAVE_PTHREAD=1 -DON_ANDROID -DONANDROID -DANDROID -DFOR_HERMES=true -fexceptions -fno-omit-frame-pointer -frtti -Wno-sign-compare -std=c++17 -Wall -DRCT_NEW_ARCH_ENABLED -O0 -fno-limit-debug-info  -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp.o -MF CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp.o.d -o CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp.o -c /Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp
  /Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp:505:48: error: 'getShadowTreeRegistry' is a private member of 'facebook::react::UIManager'
    const auto &shadowTreeRegistry = uiManager_->getShadowTreeRegistry();
                                                 ^
  ../../../../../../react-native/ReactCommon/react/renderer/uimanager/UIManager.h:187:29: note: declared private here
    ShadowTreeRegistry const &getShadowTreeRegistry() const;
                              ^
  1 error generated.
  [18/19] Building CXX object CMakeFiles/reanimated.dir/Users/michdreby/Desktop/h3-fe-consumer/node_modules/react-native-reanimated/Common/cpp/Fabric/ReanimatedUIManagerBinding.cpp.o
  ninja: build stopped: subcommand failed.
  

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Expected behavior
Build is OK

### Actual behavior & steps to reproduce
npx react-native run-android 

## Package versions
"dependencies": {
    "@apollo/client": "^3.4.16",
    "@expo/react-native-action-sheet": "3.13.0",
    "@microsoft/applicationinsights-react-native": "^2.2.9",
    "@microsoft/applicationinsights-web": "^2.5.11",
    "@notifee/react-native": "^3.0.4",
    "@react-native-async-storage/async-storage": "1.15.9",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/cameraroll": "4.0.4",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^6.0.2",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.4",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/analytics": "14.11.0",
    "@react-native-firebase/app": "14.11.0",
    "@react-native-firebase/crashlytics": "14.11.0",
    "@react-native-firebase/dynamic-links": "14.11.0",
    "@react-native-firebase/messaging": "14.11.0",
    "@react-native-picker/picker": "^1.16.8",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/elements": "^1.1.2",
    "@react-navigation/material-top-tabs": "^6.0.6",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "@testing-library/react-hooks": "^3.4.2",
    "@types/omit-deep-lodash": "^1.1.0",
    "@types/react-native-calendars": "^1.20.12",
    "@types/react-native-snap-carousel": "^3.8.4",
    "@types/string.prototype.matchall": "^4.0.0",
    "@types/yup": "^0.29.8",
    "apollo-link-http": "^1.5.17",
    "apollo-link-queue": "^3.1.0",
    "camelcase-keys": "^6.2.2",
    "card-validator": "^8.1.0",
    "core-js": "^3.12.1",
    "date-fns": "2.23.0",
    "date-fns-tz": "^1.1.6",
    "expo": "^45.0.0",
    "expo-camera": "12.2.0",
    "expo-location": "14.2.2",
    "expo-media-library": "14.1.0",
    "expo-permissions": "13.2.0",
    "formik": "^2.2.1",
    "graphql": "^15.3.0",
    "graphql-tag": "^2.12.4",
    "i18next": "^19.7.0",
    "js-base64": "^3.7.2",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.20",
    "loglevel": "^1.7.1",
    "metro-config": "^0.63.0",
    "omit-deep-lodash": "^1.1.5",
    "patch-package": "^6.4.7",
    "react": "17.0.2",
    "react-i18next": "^11.7.3",
    "react-native": "0.68.2",
    "react-native-android-downloading-notifications": "0.0.3",
    "react-native-android-keyboard-adjust": "^1.2.0",
    "react-native-app-auth": "^6.0.1",
    "react-native-base64": "^0.2.1",
    "react-native-calendars": "^1.505.0",
    "react-native-codegen": "^0.69.1",
    "react-native-date-picker": "^4.2.0",
    "react-native-device-info": "^7.0.2",
    "react-native-document-picker": "^5.0.3",
    "react-native-exception-handler": "^2.10.10",
    "react-native-file-viewer": "^2.1.4",
    "react-native-fingerprint-scanner": "^6.0.0",
    "react-native-fs": "^2.17.0",
    "react-native-gesture-handler": "2.4.2",
    "react-native-gradle-plugin": "^0.0.7",
    "react-native-image-picker": "4.7.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-json-tree": "^1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.1.4",
    "react-native-map-link": "^2.8.2",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal": "^13.0.0",
    "react-native-pager-view": "^5.4.6",
    "react-native-parsed-text": "0.0.22",
    "react-native-pdf": "^6.2.2",
    "react-native-rate": "^1.2.9",
    "react-native-reanimated": "3.0.0-rc.0",
    "react-native-render-html": "^5.1.0",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "3.12.0",
    "react-native-shake": "^5.0.1",
    "react-native-size-matters": "^0.4.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^2.16.0",
    "react-native-toast-notifications": "^3.2.2",
    "react-native-ultimate-config": "4.0.0",
    "react-native-uuid": "^2.0.0",
    "react-native-webview": "^11.13.0",
    "requestidlecallback-polyfill": "^1.0.2",
    "rn-fetch-blob": "^0.12.0",
    "rn-secure-storage": "^2.0.6",
    "sendbird": "3.1.7",
    "stack-beautifier": "^1.0.2",
    "string.prototype.matchall": "^4.0.3",
    "victory-core": "^36.2.0",
    "victory-native": "^36.2.0",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-typescript": "^7.12.1",
    "@babel/runtime": "^7.12.5",
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@graphql-codegen/cli": "^1.19.1",
    "@graphql-codegen/typescript": "^1.17.11",
    "@react-native-community/eslint-config": "^1.1.0",
    "@storybook/addon-actions": "^6.3.8",
    "@storybook/addon-knobs": "^5.3.21",
    "@storybook/addon-links": "^6.3.8",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/addons": "^6.3.8",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "@testing-library/react-hooks": "^3.7.0",
    "@testing-library/react-native": "^7.0.2",
    "@types/i18next": "^13.0.0",
    "@types/jest": "^26.0.24",
    "@types/lodash": "^4.14.165",
    "@types/loglevel": "^1.6.3",
    "@types/react-gateway": "^2.8.3",
    "@types/react-i18next": "^8.1.0",
    "@types/react-native": "^0.66.16",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-test-renderer": "^16.9.2",
    "@typescript-eslint/eslint-plugin": "^4.1.1",
    "@typescript-eslint/parser": "^4.1.1",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.1.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-resolve-barrel-files": "0.2.0",
    "eslint": "7.32.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-barrel-files": "./libs/eslint-plugin-barrel-files",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-path": "1.0.1",
    "eslint-plugin-react": "^7.21.2",
    "eslint-plugin-react-hooks": "^4.0.0",
    "eslint-plugin-react-native": "^4.0.0",
    "eslint-plugin-simple-import-sort": "^7.0.0",
    "eslint-plugin-sonarjs": "^0.11.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^4.3.0",
    "i18next-scanner": "^2.11.0",
    "i18next-scanner-typescript": "^1.0.6",
    "jest": "^26.6.3",
    "jest-junit": "^12.0.0",
    "lint-staged": "^10.4.0",
    "metro-react-native-babel-preset": "0.67.0",
    "mock-apollo-client": "^1.2.0",
    "mockdate": "^3.0.2",
    "react-dom": "^17.0.2",
    "react-native-dotenv": "^2.5.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.1.0"
  },

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.68.2      |
| react-native-reanimated              |    3.0.0-rc.0     |
| NodeJS                               |   16.15.0      |
| Xcode                                |         |
| Java                                 |    11.0.15     |
| Gradle                               |     7.x    |
| expo                                 |    45.0.0     |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello! Reanimated 3 supports Fabric starting from 0.69.0-rc.0.

**Comment by MichDreby** [comment]
Yes, it was the reason, thanks a lot!

**Comment by Siliconvelly** [comment]
I am using Reanimated 3 and raect-native version 0.70.0 still getting this issue please fix this issue as soon as possible.

**Comment by Siliconvelly** [comment]
> I am using Reanimated 3 and raect-native version 0.70.0 still getting this issue please fix this issue as soon as possible.


I am using Reanimated 3 and raect-native version 0.70.0 still getting this issue please fix this issue as soon as possible.

**Comment by NensiKasundra** [comment]
I'm getting issues in the 0.70 react-native projects and using react-native-reanimated version 3.0.0-rc.2 
```

../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found

> Task :react-native-reanimated:buildCMakeDebug[x86] FAILED

node_modules/react-native-reanimated/Common/cpp/Tools/JSIStoreValueUser.cpp:4:
  ../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
  #include <fbjni/fbjni.h>
           ^~~~~~~~~~~~~~~
  1 error generated.
```


Any clue for the above one? 

Thanks in Advance for your help!

**Comment by NicolasMeza** [comment]
> I'm getting issues in the 0.70 react-native projects and using react-native-reanimated version 3.0.0-rc.2
> 
> ```
> 
> ../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
> 
> > Task :react-native-reanimated:buildCMakeDebug[x86] FAILED
> 
> node_modules/react-native-reanimated/Common/cpp/Tools/JSIStoreValueUser.cpp:4:
>   ../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
>   #include <fbjni/fbjni.h>
>            ^~~~~~~~~~~~~~~
>   1 error generated.
> ```
> 
> Any clue for the above one?
> 
> Thanks in Advance for your help!

I'm also having the same error

**Comment by maxoschepkov** [comment]
Interesting why it's closed, I've the same issue with RN 0.69.5.

**Comment by NicolasMeza** [comment]
> > I'm getting issues in the 0.70 react-native projects and using react-native-reanimated version 3.0.0-rc.2
> > ```
> > 
> > ../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
> > 
> > > Task :react-native-reanimated:buildCMakeDebug[x86] FAILED
> > 
> > node_modules/react-native-reanimated/Common/cpp/Tools/JSIStoreValueUser.cpp:4:
> >   ../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
> >   #include <fbjni/fbjni.h>
> >            ^~~~~~~~~~~~~~~
> >   1 error generated.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any clue for the above one?
> > Thanks in Advance for your help!
> 
> I'm also having the same error

In RN 0.70 I solved by adding this line:  android.disableAutomaticComponentCreation=true  in android/gradle.properties

**Comment by peterchijioke** [comment]
hi guys , I am also facing same issue here.

**Comment by hit-cod** [comment]
> > > I'm getting issues in the 0.70 react-native projects and using react-native-reanimated version 3.0.0-rc.2
> > > ```
> > > 
> > > ../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
> > > 
> > > > Task :react-native-reanimated:buildCMakeDebug[x86] FAILED
> > > 
> > > node_modules/react-native-reanimated/Common/cpp/Tools/JSIStoreValueUser.cpp:4:
> > >   ../../../../src/main/cpp/headers/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
> > >   #include <fbjni/fbjni.h>
> > >            ^~~~~~~~~~~~~~~
> > >   1 error generated.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Any clue for the above one?
> > > Thanks in Advance for your help!
> > 
> > 
> > I'm also having the same error
> 
> In RN 0.70 I solved by adding this line: android.disableAutomaticComponentCreation=true in android/gradle.properties
> 
> Steps: 1- Close Android Studio 2- Add android.disableAutomaticComponentCreation=true in android/gradle.properties 3- Reopen project and build.

this worked for me too, additionally i cleared yarn and android studio cache. adding this line was actually written in gradle warnings

**Comment by ccyfly** [comment]
I have same error in `2.10` in RN `0.70.1`.

**Comment by vagnerlandio** [comment]
I have the same error in `2.10` and in RN `0.70`

close the project in android studio and run in the root of the project `rm -rf node_modules && yarn install` solved for me.
