### ISSUE TITLE
 App crashes randomly - only Android 12 and mostly Samsung devices

### ISSUE THREAD

**Issue by ilyagru** [software-mansion/react-native-reanimated#3294]
## Description

I'm opening an issue here for one which is reported to the React Native team. Could you take a look please? Maybe it is related? I think the react-native-reanimated team might have some fresh ideas on how to resolve it. 

- https://github.com/facebook/react-native/issues/33375 App crashes randomly - only Android12 #33375 

### Expected behavior

No crash.

### Actual behavior & steps to reproduce

To reproduce you need at least:

1. Android 12
2. Samsung device
3. React Native 0.68.2

Crashes as https://github.com/facebook/react-native/issues/33375#issuecomment-1139618328

Please see the whole thread for more logs and info.

## Snack or minimal code example

For example, here is a reproduction https://github.com/facebook/react-native/issues/33375#issuecomment-1059844263
https://github.com/jefersonvinicius/react-native-crashing-example

## Package versions

This information is also available in the thread.

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.68.2 |
| react-native-reanimated              | ^2.8.0 |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by jarredt** [comment]
We are having this issue as well, except we're on React Native 0.64.3.

**Comment by jarredt** [comment]
Wondering if https://github.com/software-mansion/react-native-reanimated/issues/3080 is related.

**Comment by ilyagru** [comment]
Yes @jarredt it seems occuring only on Samsungs with Android 12. #3080 might be related. It looks like many people who updating their devices to Android 12 and start experience the crash, even in different React Native apps. Any ideas for a workaround?

**Comment by webdevmario** [comment]
expo: 45.0.0
react-native: 0.68.2
react-native-reanimated: 2.8.0

I too noticed this issue cropping up amongst Android 12/Samsung devices once we upgraded to Expo SDK 45.

Our app makes use of React Navigation 6 and react-native-reanimated is a dependency so I cannot remove it.

I created a minimal Expo test app to evaluate and it is if in fact the addition of this package that causes it to crash on Android 12/Samsung devices. If I remove it, the crashing stops.

#3080 does seem to be related.

https://github.com/facebook/react-native/issues/33375 appears to be the root issue/cause. Some comments suggest RN 0.69.0 will address but it would be good to have some confirmation from RN devs + react-native-reanimated devs on Samsung devices.

Below is the code I used for my test. Take out reanimated and it should stop crashing on these devices.

```json
{
  "name": "expo-demo",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "expo": "~45.0.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-reanimated": "~2.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

```js
// App.js

import * as SplashScreen from 'expo-splash-screen';
import React, { useEffect, useState } from 'react';
import RootNavigator from './src/navigation/RootNavigator';

export default function App() {
  const [appIsReady, setAppIsReady] = useState(false);

  useEffect(() => {
    async function initApp () {
      try {
        await SplashScreen.preventAutoHideAsync();
      } catch (e) {
        console.log(e);
      } finally {
        setAppIsReady(true);
      }
    }

    initApp();
  }, []);

  if (!appIsReady) {
    return null;
  }

  return (
    <RootNavigator />
  );
}
```

```js

// RootNavigator.js

import * as SplashScreen from 'expo-splash-screen';
import React, { useEffect, useState } from 'react';
import RootNavigator from './src/navigation/RootNavigator';

export default function App() {
  const [appIsReady, setAppIsReady] = useState(false);

  useEffect(() => {
    async function initApp () {
      try {
        await SplashScreen.preventAutoHideAsync();
      } catch (e) {
        console.log(e);
      } finally {
        setAppIsReady(true);
      }
    }

    initApp();
  }, []);

  if (!appIsReady) {
    return null;
  }

  return (
    <RootNavigator />
  );
}
```

**Comment by ilyagru** [comment]
Hi! Any update on this one? RN 0.69.1 hasn't resolved this issue. And since there is a repro, could anyone from maintainers please take a look?

**Comment by ilyagru** [comment]
@webdevmario "1 of 3 tasks"  means it is not related to tasks but to the affected platforms, it occurs only on Android, hence 1 checkbox is checked.

**Comment by webdevmario** [comment]
@ilyagru Ah, I see. Thank you for clarifying.

**Comment by RhyG** [comment]
Hi, just wondering if anyone knows of any movement on this issue? I can see in the thread in the react-native repo there has been a bunch of comments and a repro, but no updates as to fixes. This is currently affecting quite a lot of our users, is there anything that could be done in the meantime to prevent this error from happening? Keen to help where possible, but not at all a native developer sadly.

**Comment by MuhammadRafeh** [comment]
Any updates?

**Comment by robertwt7** [comment]
could this be related to #3234? we are experiencing the same issue, it seems like it happens when using predefined animations, in my case is `FadeInUp`

**Comment by joviksdev** [comment]
Having similar issues too, application crashes on android 12, Samsung device, has there been a fix on this?

**Comment by bangdy** [comment]
I also have crash on my release at first time only for Samsung android 12 phone. 
I need to maintain react-native-reanimated for react-navigation/drawer.
So, not fundamental solution, I used [react-native-restart](https://github.com/avishayil/react-native-restart) for resetting app first time only. It could be temporary solution.

`useEffect(() => {
    const checkFirstTime = async () => {
      const result = await getItemFromAsync('notFirst');
      if (result) {
        console.log('notFirst : ', result);
      } else {
        await setItemToAsync('notFirst', true);
        RNRestart.Restart();
      }
      SplashScreen.hide();
    };
    checkFirstTime();
  }, []);`

**Comment by vincemavill** [comment]
I solve the issue by  changing targetSdkVersion = 31 to argetSdkVersion = 30

**Comment by vjsingh95** [comment]
> maintain react-native-reanimated for react-navigation/drawer.
> So, not fundamental solution,

How you uploaded the app with targetSdkVersion 30 ? Google play console is asking for target 31 or higher.

**Comment by codal-mpawar** [comment]
right @vjsingh95 if we need to upload the app on the google play console then it must targetSdkVersion = 31.

**Comment by jonathanroze** [comment]
Did you find a way to fix this issue ? Thanks

**Comment by grant-solomons** [comment]
I am also experiencing this issue just on samsung devices

**Comment by vjsingh95** [comment]
Please add below line to build gradle file.

 implementation 'androidx.work:work-runtime:2.7.1'

**Comment by jonathanroze** [comment]
> Please add below line to build gradle file.
> 
> implementation 'androidx.work:work-runtime:2.7.1'

Thanks, I already try this way, an this error is still throw on Android 12!

**Comment by adityabrovitech** [comment]
> Any solution for this? Notifications working when app in foreground but in background not working in targetsdkversion 31.

you should add POST_NOTIFICATION permission above  targetsdkversion 31 for android 13

**Comment by Arise-cn** [comment]
Did you find a way to fix this issue ? Thanks

**Comment by Latropos** [comment]
Closing since we have limited our support for Reanimated v2 since release of the Reanimated 3, please upgrade
