### ISSUE TITLE
imageViewer example panning not scaled on iOS

### ISSUE THREAD

**Issue by louispvb** [software-mansion/react-native-reanimated#33]
I tried out the imageViewer example and when you zoom in on iOS, the panning translation does not scale with the zoom. So when zoomed in and panning, the image will move slower than the touch.

On android this worked correctly.

**Comment by Haper** [comment]
```
function dragDiff(value, updating, scale) {
  const tmp = new Value(0);
  const prev = new Value(0);
  const corValue = Platform.OS === 'ios' ? multiply(value, scale) : value;
  return cond(
    updating,
    [set(tmp, sub(corValue, prev)), set(prev, corValue), tmp],
    set(prev, 0)
  );
}
```

```
...
    dragDiff(dragX, panActive, scale),
...
    dragDiff(dragY, panActive, scale),
...
```

**Comment by sebastian-schlecht** [comment]
Thanks @Haper! This solved our issue.

**Comment by miodrage** [comment]
Thank you! @Haper

**Comment by jakub-gonet** [comment]
Thanks @Haper for providing a working solution! 🎉 

I'm closing this issue if you have any further questions feel free to reopen
