### ISSUE TITLE
Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project

### ISSUE THREAD

**Issue by maheshlodha** [software-mansion/react-native-reanimated#3319]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/maheshlodha/development/react-native/stocksecurities/node_modules/react-native-reanimated/android/build.gradle' line: 152

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project.

**Comment by chzappsinc** [comment]
change  `$rnMinorVersion` to `$rnMinorVersionCopy`

This is just a print log and doesn't affect our project 


```
 if (rnMinorVersionCopy < 63) {
            println "No AAR for react-native-reanimated found. Attempting to build from source."
        } else { // aar exists, but was build for lower react-native version
            println "\n\n\n"
            println "****************************************************************************************"
            println "\n\n\n"
            println "WARNING reanimated - no version-specific reanimated AAR for react-native version $rnMinorVersionCopy found."
            println "Falling back to AAR for react-native version $rnMinorVersionCopy."
            println "The react-native JSI interface is not ABI-safe yet, this may result in crashes."
            println "Please post a pull request to implement support for react-native version $rnMinorVersionCopy to the reanimated repo."
            println "Thanks!"
            println "\n\n\n"
            println "****************************************************************************************"

            return aar
        }
```

**Comment by maheshlodha** [comment]
I have try this solution. But i have gotten a warning
It is warning:-

WARNING reanimated - no version-specific reanimated AAR for react-native version 68 found.
Falling back to AAR for react-native version 68.
The react-native JSI interface is not ABI-safe yet, this may result in crashes.
Please post a pull request to implement support for react-native version 68 to the reanimated repo.
Thanks!

**Comment by chzappsinc** [comment]
Let’s wait until they updates for RN 0.69

**Comment by maheshlodha** [comment]
> change `$rnMinorVersion` to `$rnMinorVersionCopy`
> 
> This is just a print log and doesn't affect our project
> 
> [EXAMPLE](https://github.com/software-mansion/react-native-reanimated/pull/3322/commits/bb4db23469c4a4379d6984498d539d460620fc83)
> 
> ```
>  if (rnMinorVersionCopy < 63) {
>             println "No AAR for react-native-reanimated found. Attempting to build from source."
>         } else { // aar exists, but was build for lower react-native version
>             println "\n\n\n"
>             println "****************************************************************************************"
>             println "\n\n\n"
>             println "WARNING reanimated - no version-specific reanimated AAR for react-native version $rnMinorVersionCopy found."
>             println "Falling back to AAR for react-native version $rnMinorVersionCopy."
>             println "The react-native JSI interface is not ABI-safe yet, this may result in crashes."
>             println "Please post a pull request to implement support for react-native version $rnMinorVersionCopy to the reanimated repo."
>             println "Thanks!"
>             println "\n\n\n"
>             println "****************************************************************************************"
> 
>             return aar
>         }
> ```

But This change are

**Comment by ghorbani-m** [comment]
The same issue, while upgrading react-native to `0.69.0`

**Comment by rubeshh** [comment]
There are no answers. but it was closed. what is this?

**Comment by ManthanG369** [comment]
I am also facing same error

**Comment by Aakash359** [comment]
Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project.
I have tried all the solution but no one is working can please anyone suggest what should i do this happen b.cos i have upgrade my react native version from 62 to 0.69.1

**Comment by chzappsinc** [comment]
> Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project.
> I have tried all the solution but no one is working can please anyone suggest what should i do this happen b.cos i have upgrade my react native version from 62 to 0.69.1

Try this

https://github.com/software-mansion/react-native-reanimated/issues/3319#issuecomment-1165885046

**Comment by Aakash359** [comment]
> rnMinorVersionCopy

On which file i have to change this can you please let me know ?

**Comment by chzappsinc** [comment]
> > rnMinorVersionCopy
> 
> On which file i have to change this can you please let me know ?

Are you using Android studio?

**Comment by Aakash359** [comment]
> > Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project.
> > I have tried all the solution but no one is working can please anyone suggest what should i do this happen b.cos i have upgrade my react native version from 62 to 0.69.1
> 
> Try this
> 
> [#3319 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/3319#issuecomment-1165885046)



> > > rnMinorVersionCopy
> > 
> > 
> > On which file i have to change this can you please let me know ?
> 
> Are you using Android studio?

Yes i am

**Comment by chzappsinc** [comment]
Ok then goto Android Studio and scroll down 
You will see
`react-native-reanimated build.gradle
`

**Comment by Aakash359** [comment]
> rnMinorVersion

Yes it's working fine now 😊 but i am getting issues 😬 some another libraries migrating a project from older version to newer it's not a east task

**Comment by chzappsinc** [comment]
> > rnMinorVersion
> 
> Yes it's working fine now 😊 but i am getting issues 😬 some another libraries. migrating a project from older version to newer it's not a easy task

Yes you should wait or try yarn upgrade, Need to do above step one more time

**Comment by roboticambiental** [comment]
I have the same issue than @Aakash359 before following instructions of @chzappsinc and after.
These are my dependencies:

"dependencies": {
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "react": "18.0.0",
    "react-native": "^0.69.1",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.69.0",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.70.3",
    "react-test-renderer": "18.0.0",
    "typescript": "^4.4.4"
  },

Error after rename $rnMinorVersion to $rnMinorVersionCopy:
* What went wrong:
Execution failed for task ':react-native-screens:compileDebugKotlin'.

Error before rename $rnMinorVersion to $rnMinorVersionCopy:
What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.

**Comment by samthui** [comment]
> change `$rnMinorVersion` to `$rnMinorVersionCopy`
> 
> This is just a print log and doesn't affect our project
> 
> [EXAMPLE](https://github.com/software-mansion/react-native-reanimated/pull/3322/commits/bb4db23469c4a4379d6984498d539d460620fc83)
> 
> ```
>  if (rnMinorVersionCopy < 63) {
>             println "No AAR for react-native-reanimated found. Attempting to build from source."
>         } else { // aar exists, but was build for lower react-native version
>             println "\n\n\n"
>             println "****************************************************************************************"
>             println "\n\n\n"
>             println "WARNING reanimated - no version-specific reanimated AAR for react-native version $rnMinorVersionCopy found."
>             println "Falling back to AAR for react-native version $rnMinorVersionCopy."
>             println "The react-native JSI interface is not ABI-safe yet, this may result in crashes."
>             println "Please post a pull request to implement support for react-native version $rnMinorVersionCopy to the reanimated repo."
>             println "Thanks!"
>             println "\n\n\n"
>             println "****************************************************************************************"
> 
>             return aar
>         }
> ```

Tried this and it comes to another error (same as @Aakash359 and @roboticambiental )
```Execution failed for task ':react-native-screens:compileDebugKotlin'.```


Also, I quite don't understand, if `This is just a print log and doesn't affect our project` then why doing so passed the issue?

**Comment by izbari** [comment]
same issue and takes 5-6 min. while build on android side

**Comment by chzappsinc** [comment]
> same issue and takes 5-6 min. while build on android side
> 
> 

Whats your RN version and This lib version

**Comment by izbari** [comment]
> > same issue and takes 5-6 min. while build on android side
> 
> Whats your RN version and This lib version

 "react-native-reanimated": "^2.9.1"
  "react-native": "0.69.1"

**Comment by izbari** [comment]
@chzappsinc actually issue is every build on android side takes 5-6 min (configuring project: react-native-reanimated). This is very frustrating

**Comment by chzappsinc** [comment]
Ok bro, Try

Go to project Root terminal and run this

`cd android && ./gradlew clean`

try to build again

**Comment by jpgcarvalho** [comment]
I'm heading the same error, i tried downgrade the emulator's version and doesn't work

**Comment by adamgajzlerowicz** [comment]
I had this problem also. Eventually upgraded to 
```
"react-native": "0.69.2",
"react-native-reanimated": "2.9.1",
```

Then 
`cd android && ./gradlew clean`

Rebuilt the project. all runs fine!

**Comment by morgan4080** [comment]
`"react-native": "0.69.2",
"react-native-reanimated": "2.9.1",`

A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.appcompat:appcompat:1.4.1.

**Comment by chzappsinc** [comment]
For RN Version less than 0.69 use 
`react-native-reanimated@2.8.0`

**Comment by pottercomuneo** [comment]
Same error here, with RN at 0.69.4 and reanimated@2.6.0
I tried upgrading to reanimated@2.9.1 and I'm having more errors

**Comment by chzappsinc** [comment]
> Same error here, with RN at 0.69.4 and reanimated@2.6.0
> 
> I tried upgrading to reanimated@2.9.1 and I'm having more errors

Can you show the errors

**Comment by rafaelsalves** [comment]
I update my React Navigation to 6.x.x. In this version react-native-reanimated ins't dependency of react-navigation. So, IN THIS CASE, i removed react-native-reanimated and works.

**Comment by suwu150** [comment]
> `"react-native": "0.69.2", "react-native-reanimated": "2.9.1",`
> 
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction > The minCompileSdk (31) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) is greater than this module's compileSdkVersion (android-30). Dependency: androidx.appcompat:appcompat:1.4.1.

any result?

**Comment by giladm** [comment]
I am using react-native 0.69.3 and also had an issue with compiling reanimated@2.10. I updated to @2.11.0 and it fixed my compile error.

**Comment by Basir-PD** [comment]
Upgrading to react-native-reanimated@2.9.1` solved the issue

**Comment by error-try-again** [comment]
Had the same issue earlier today on 2.9.1. Upgrading to react-native-reanimated:2.13.0 solved my issue.

**Comment by vanoob404** [comment]
> I had this problem also. Eventually upgraded to
> 
> ```
> "react-native": "0.69.2",
> "react-native-reanimated": "2.9.1",
> ```
> 
> Then `cd android && ./gradlew clean`
> 
> Rebuilt the project. all runs fine!

It worked!!!
Respect++

**Comment by stivenm16** [comment]
> I am using react-native 0.69.3 and also had an issue with compiling reanimated@2.10. I updated to @2.11.0 and it fixed my compile error.

This version works to me!

**Comment by Jcstack** [comment]
> I had this problem also. Eventually upgraded to
> 
> ```
> "react-native": "0.69.2",
> "react-native-reanimated": "2.9.1",
> ```
> 
> Then `cd android && ./gradlew clean`
> 
> Rebuilt the project. all runs fine!

This solution is helpful for me. Thanks!

**Comment by JuanRdBO** [comment]
I get thie error 

`> Could not get unknown property 'minor' for project ':react-native-reanimated' of type org.gradle.api.Project.`

after upgrading to RN 0.71.3

**Comment by maskowe** [comment]
@JuanRdBO  - I just got the same error with trying react-native-reanimated (using version ~2.12.0) for my upgrade to RN 0.71.3.    Did you find any answer or solution?

**Comment by JuanRdBO** [comment]
@maskowe I have been able to run it successfully with the following dependencies:

"expo": "^48.0.0",
"react-native": "0.71.3",
"react-native-reanimated": "~2.14.4",

**Comment by aavetisyanIT** [comment]
> @maskowe I have been able to run it successfully with the following dependencies:
> 
> "expo": "^48.0.0", "react-native": "0.71.3", "react-native-reanimated": "~2.14.4",
> 
> Remember to install pods on the iOS folder

This worked for me! Thank you JuanRdBO

**Comment by maskowe** [comment]
Thanks so much.   But someone said on another issue that only reanimated 3
supported RN 71 and so I hope that it's not true

**Comment by SubhashFxkart** [comment]
> @maskowe I have been able to run it successfully with the following dependencies:
> 
> "expo": "^48.0.0", "react-native": "0.71.3", "react-native-reanimated": "~2.14.4",
> 
> Remember to install pods on the iOS folder

still getting error? what's your react version?

**Comment by maskowe** [comment]
@SubhashFxkart I’m not getting any errors now — react version is 18.2.0

**Comment by goddypete57** [comment]
i have this warning  below when runing on android  

WARNING reanimated - no version-specific reanimated AAR for react-native version 72 found.
Falling back to AAR for react-native version 71.
The react-native JSI interface is not ABI-safe yet, this may result in crashes.
Please post a pull request to implement support for react-native version 72 to the reanimated repo.
Thanks!
and it crashes on ios when navigating to another screen without error but navigation is working perfectly on android ,pls i need help
