### ISSUE TITLE
useAnimatedProps with svg not working

### ISSUE THREAD

**Issue by louisholley** [software-mansion/react-native-reanimated#3321]
## Description
following the example [here](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedProps/) directly, the code is erroring in our project with `TypeError: Cannot read properties of undefined (reading 'setAttribute')`

it's occurring here in `react-native-reanimated/lib/reanimated2/js-reanimated/index.js`:

```
  if (typeof component.setNativeProps === 'function') {
      setNativeProps(component, rawStyles);
    } else if (Object.keys(component.props).length > 0) {
      Object.keys(component.props).forEach((key) => {
        if (!rawStyles[key]) {
          return;
        }
        const dashedKey = key.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
        component._touchableNode.setAttribute(dashedKey, rawStyles[key]);
      });
```

### Expected behavior
the example outlined in the docs should work

### Actual behavior & steps to reproduce
errors with cannot read property "setAttribute" of undefined

## Snack or minimal code example
see the docs - we've copied the code there exactly

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      0.68   |
| react-native-reanimated              |   2.8.0      |
| NodeJS                               |    16.15.0     |
| expo                                 |     45    |

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by tannersatch** [comment]
Any update on this? Anyone know if there is an older version I can revert to that works?

**Comment by tgreco** [comment]
Same issue

**Comment by Frit** [comment]
Same for me, ios react-native-reanimated@2.10.0

can be tested on this example: Circular Progress Bar
https://github.com/enzomanuelmangano/animate-with-reanimated/blob/main/08-circular-progress-bar/App.tsx

**Comment by wjaykim** [comment]
I found workaround for this bug:
Just set empty function for `onPress` prop like this:
```js
<AnimatedCircle
  cx="50%"
  cy="50%"
  r="5"
  animatedProps={circleProps}
  onPress={() => {}}
/>
```

I guess this is because `_touchableNode`(which is referenced in [this line](https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/js-reanimated/index.ts#L39)) for the svg component is only added when touchable related props exist([related line in react-native-svg](https://github.com/react-native-svg/react-native-svg/blob/main/src/ReactNativeSVG.web.ts#L255)).

**Comment by saeedblanchette** [comment]
react-native-svg v 13.5.0  worked for me in the web using useAnmatedProps

**Comment by acollazomayer** [comment]
This is happening to. me to.  have the version `react-native-reanimated` 3.0.2 `react-native-svg` 13.8.0. Any news on how. to fix this. 
It is reproducable with. this https://github.com/enzomanuelmangano/animate-with-reanimated/blob/main/08-circular-progress-bar/App.tsx

**Comment by acollazomayer** [comment]
I've created a repository that replicates the issue that I am having hope this helps. https://github.com/acollazomayer/ReanimatedSVGBug

**Comment by saeedblanchette** [comment]
> I found a workaround for this bug. Just set empty function for `onPress` prop of component you want to animate like this:
> 
> ```js
> <AnimatedCircle
>   cx="50%"
>   cy="50%"
>   r="5"
>   animatedProps={circleProps}
>   onPress={() => {}}
> />
> ```
> 
> I guess this is because `_touchableNode`(which is referenced in [this line](https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/js-reanimated/index.ts#L39)) for the svg component is only added when touchable related props exist([related line in react-native-svg](https://github.com/react-native-svg/react-native-svg/blob/main/src/ReactNativeSVG.web.ts#L255)).

I just  used  a workaround  and  I did work for  @acollazomayer

**Comment by Isrrr** [comment]
> @Isrrr did you found a fix?

Nope

**Comment by geetesh-gupta** [comment]
> I found workaround for this bug. Just set empty function for `onPress` prop of component you want to animate like this:
> 
> ```js
> <AnimatedCircle
>   cx="50%"
>   cy="50%"
>   r="5"
>   animatedProps={circleProps}
>   onPress={() => {}}
> />
> ```
> 
> I guess this is because `_touchableNode`(which is referenced in [this line](https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/js-reanimated/index.ts#L39)) for the svg component is only added when touchable related props exist([related line in react-native-svg](https://github.com/react-native-svg/react-native-svg/blob/main/src/ReactNativeSVG.web.ts#L255)).

This works but I get a lot of warnings as errors for all touch related props in the console titled `Warning: Unknown event handler property onStartShouldSetResponder. It will be ignored. at circle`

Any workaround for the errors? or Proper fix?

**Comment by etiennelacoursiere** [comment]
I had the problem with the `setAttribute` error on web on `react-native-svg: 13.4.0`. Updating to `13.9.0` fixed it for me. 

Now it works but i have a bunch of errors in the console for: `Error: <circle> attribute transform: Expected transform function, "undefined".`

My react-native-reanimated version is: `2.14.4`

**Comment by tjzel** [comment]
The issue isn't present in Reanimated 3.6.1.

**Comment by mk0116** [comment]
This is still present in 3.6.1 on web. @tjzel

**Comment by Nehal-Zeller** [comment]
Issue is present on react-native-reanimated": "3.16.1" and  "lottie-react-native": "^6.7.2"

**Comment by kaumac** [comment]
Same for "next" (reanimated 4.x)

**Comment by patrycjakalinska** [comment]
hi everyone, I've checked example from docs on newest `3.17.2` Reanimated and it is working without any errors - we're using `"react-native-svg": "15.11.2",` - if the issue is still present could you provide more information how to reproduce it, so I can investigate?

thanks!

https://github.com/user-attachments/assets/40632c4d-a35c-4044-98a2-ad407aa7bcb7

**Comment by soulfresh** [comment]
@patrycjakalinska For me, the issue was happening during testing so I opened a separate ticket: https://github.com/software-mansion/react-native-reanimated/issues/6414. There's a demo repo on that ticket.

**Comment by patrycjakalinska** [comment]
hi @soulfresh, thanks for response! We enabled testing `useAnimatedProps` in 3.17.2 (#7231) - unfortunately `react-native-svg` is not testable because of their managment of props

**Comment by soulfresh** [comment]
Awesome! I ended up mocking `react-native-svg` so hopefully 3.17.2 fixes my testing issues 🤞
