### ISSUE TITLE
Switch from 14 to 17 for 0.69 RN

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-reanimated#3326]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-reanimated@2.8.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-reanimated/RNReanimated.podspec b/node_modules/react-native-reanimated/RNReanimated.podspec
index 33ea1c6..da5ed40 100644
--- a/node_modules/react-native-reanimated/RNReanimated.podspec
+++ b/node_modules/react-native-reanimated/RNReanimated.podspec
@@ -79,7 +79,7 @@ Pod::Spec.new do |s|
   }
   s.compiler_flags = folly_compiler_flags + ' ' + boost_compiler_flags
   s.xcconfig               = {
-    "CLANG_CXX_LANGUAGE_STANDARD" => "c++14",
+    "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
     "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\" \"$(PODS_ROOT)/boost-for-react-native\" \"$(PODS_ROOT)/glog\" \"$(PODS_ROOT)/#{folly_prefix}Folly\" \"${PODS_ROOT}/Headers/Public/React-hermes\" \"${PODS_ROOT}/Headers/Public/hermes-engine\"",
                                "OTHER_CFLAGS" => "$(inherited)" + " " + folly_flags  }
 
diff --git a/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js b/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js
index 5ae42ec..8c7f631 100644
--- a/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js
+++ b/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js
@@ -145,7 +145,7 @@ export const advanceAnimationByFrame = (count) => {
     jest.advanceTimersByTime(frameTime);
 };
 export const setUpTests = (userConfig = {}) => {
-    const expect = require('expect');
+    const { expect } = require('@jest/globals');
     require('setimmediate');
     frameTime = Math.round(1000 / config.fps);
     config = Object.assign(Object.assign({}, config), userConfig);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by piaskowyk** [comment]
Hey, I have already merged a fix for it, it will be available in the next release.  https://github.com/software-mansion/react-native-reanimated/pull/3347

**Comment by faroutchris** [comment]
@piaskowyk I think this patch also makes sure to fix this warning when running pod install, besides the jest fix

[!] Can't merge user_target_xcconfig for pod targets: ["RNReanimated", "hermes-engine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

**Comment by billnbell** [comment]
OK for 
```
-    "CLANG_CXX_LANGUAGE_STANDARD" => "c++14",
+    "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
```

For latest React Native it requires that one. Not sure if we can make it dynamic based on version ?

**Comment by codeOlam** [comment]
I am getting same error when i installed the latest version of react-native-reanimated: `react-native-reanimated@2.9.1` and when i downgraded to `react-native-reanimated@2.4.1`, i still got `[!] Can't merge user_target_xcconfig for pod targets: ["RNReanimated", "hermes-engine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.`

- react => v18.0.0
- react-native => v0.69.1
- Node => v18.0.0
- Xcode => v13.2.1 (13C100)

Is there any fix or work around for this yet?

**Comment by JayFeldman12** [comment]
@codeOlam, you can use [patch-package](https://github.com/ds300/patch-package) as described in [the original post](https://github.com/software-mansion/react-native-reanimated/issues/3326#issue-1285085977) as a workaround, and hopefully a new version will be released soon and the patch-package file can be deleted after upgrading.

**Comment by codeOlam** [comment]
Thank you **JayFeldman12**. I was able to get a fix yesterday. by following this solution: https://github.com/software-mansion/react-native-reanimated/issues/3305#issuecomment-1170000433. I also had to install `NDK(side-by-side)` and `CMake` via android studio.

**Comment by emmadal** [comment]
i had the same problem, in `node_modules/react-native-reanimated/RNReanimated.podspec` change ` "CLANG_CXX_LANGUAGE_STANDARD" => "c++14"` to ` "CLANG_CXX_LANGUAGE_STANDARD" => "c++17"`, 
then use 
```sh 
npx patch-package react-native-reanimated
``` 
to patch your new changes

**Comment by josemojena** [comment]
After the update to react-reanimated to the 2.10.0 version, I am still getting the warning when running `pod install`. Any suggestions?

**Comment by emmadal** [comment]
> After the update to react-reanimated to the 2.10.0 version, I am still getting the warning when running `pod install`. Any suggestions?

please read this https://github.com/software-mansion/react-native-reanimated/issues/3326#issuecomment-1225057452

**Comment by malikhamza0546** [comment]
"react-native-reanimated": "^3.0.0-rc.3", just install this version of reac-native-reanimated package, your problem will be solved.

**Comment by nandorojo** [comment]
> 

Weirdly I'm still getting this problem with version `2.14.4`.

**Comment by Alex1899** [comment]
I still get this warning even though I am on version `3.0.2 ` it has `CLANG_CXX_LANGUAGE_STANDARD` set to `c++17` already. My Xcode version `14.2`. I would appreciate it a lot if somebody who fixed this can share the solution. Thank you!
