### ISSUE TITLE
GestureDetector getting "stuck/freeze" on new mount

### ISSUE THREAD

**Issue by Norfeldt** [software-mansion/react-native-reanimated#3331]
## Description

When changing the react state by picking 6M it does a rerender but the gesture detector is stuck. Pressen the 6M makes it wake up and work again.

### Expected behavior

Not having the pan gesture froozen (UI and JS thread seems fine)

### Actual behavior & steps to reproduce

Try the provided snack and see how it should work.
Then try to comment out the hack and watch it sometimes get stuck. 

## Snack or minimal code example

https://snack.expo.dev/@nord_investments/github.com-norfeldt-spike-chart-gesture-reanimated

Tuesday 28 June 2022 on lines 59-63 in `./App.tsx` I have to do a delayed state update with setTimeout.

```tsx
<DataRangeOption
              label={item as DataRangeKeys}
              onPress={(item) => {
                setActiveDataRangeLabel(item as DataRangeKeys)
                setData(dataRanges[item as DataRangeKeys])

                // hack to avoid lagging the UI thread 🦟
                setTimeout(() => {
                  setData(dataRanges[item as DataRangeKeys])
                  setActiveDataRangeLabel(item as DataRangeKeys)
                }, 1000)
              }}
              active={item === activeDataRangeLabel}
            />
```

## Package versions

```
{
  "name": "spike-chart-gesture-reanimated",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~45.0.0",
    "expo-linear-gradient": "~11.3.0",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-reanimated": "~2.8.0",
    "react-native-redash": "^16.3.0",
    "react-native-svg": "12.3.0",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.66.13",
    "typescript": "~4.3.5"
  },
  "private": true,
  "resolutions": {
    "@types/react": "~17.0.47"
  }
}
```

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.68.2     |
| react-native-reanimated              |      2.8.0   |
| NodeJS                               |     v16.15.1    |
| Xcode                                |   N/A      |
| Java                                 |     N/A    |
| Gradle                               |      N/A   |
| expo                                 |  2.24.3.101 (supported SDK 43, 44, 45)      |

expo-cli 5.4.11 

## Affected platforms

- [ ] Android (not tested)
- [x] iOS
- [ ] Web (not tested)

**Comment by szydlovsky** [comment]
@Norfeldt hi, I know it's been some time but the given snack is super complicated and  broken. I would like to know if the issue is still there in newest v3 versions. Would you be able to check it again?

**Comment by szydlovsky** [comment]
+ it seems to be more related to `react-native-gesture-handler` more than to `reanimated` in the first place 😄
