### ISSUE TITLE
> Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project.        

### ISSUE THREAD

**Issue by ravi123saxena** [software-mansion/react-native-reanimated#3338]
A problem occurred evaluating project ':react-native-reanimated'.
> Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project.   

 "react": "18.0.0",
 "react-native": "0.69.1",
 "react-native-reanimated": "^2.8.0",

**Comment by piaskowyk** [comment]
Resolved in 2.9.1
