### ISSUE TITLE
Bundled Hermes usage

### ISSUE THREAD

**Issue by zolbooo** [software-mansion/react-native-reanimated#3348]
## Description
`react-native-reanimated` uses `hermes-engine` package in builds on Android. This could potentially break some apps/builds.

### Expected behavior
Use bundled hermes which is located in `node_modules/react-native/sdks`.

### Actual behavior & steps to reproduce
--

## Snack or minimal code example

https://github.com/software-mansion/react-native-reanimated/blob/main/android/build.gradle#L443

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.69.1    |
| react-native-reanimated              |     3.0.0-rc.0    |

## Affected platforms

- [x] Android
- [ ] iOS (Probably)
- [ ] Web

**Comment by andac-ozcan** [comment]
Testing new fabric renderer with using 3.0.0-rc.0 and RN 0.69.2. It's building and working fine with that version. But 3.0.0-rc.0 and RN 0.70.0-rc.0 builds are failing on executing step with `Could not find the hermes-engine npm package` error.

**Comment by tomekzaw** [comment]
Hello @zolbooo! Thanks for letting us know so early. Indeed, starting from React Native 0.69, Hermes is no longer distributed as `hermes-engine` npm package. Instead, a specific version of Hermes is bundled in React Native as pre-built AAR (on the old architecture) or built from sources from a specific tag (with Fabric enabled). This issue will resolved in #3417.

Thanks @andac-ozcan for checking the behaviour on 0.69 and 0.70. 

We plan to release Reanimated 2.10 with support for React Native 0.70 this week.
