### ISSUE TITLE
support for reanimated 3 rc 0

### ISSUE THREAD

**Issue by aleluiah** [software-mansion/react-native-reanimated#3349]
we would like to see v8 support for reanimated 3 rc 0

**Comment by piaskowyk** [comment]
Support for v8 will be available in 3.0.0-rc.1. We have already merged PR with it - https://github.com/software-mansion/react-native-reanimated/pull/3132

**Comment by AndreiCalazans** [comment]
@piaskowyk can Kudo's PR be ported back to V2? Has that been thought of?

**Comment by kylecesmat** [comment]
@AndreiCalazans see https://github.com/software-mansion/react-native-reanimated/issues/3381#issuecomment-1182964497

Also worth noting that the current reanimated@3 w/ v8 support will only support Paper, with additional work needed for Fabric (seems like its in progress though) https://github.com/software-mansion/react-native-reanimated/pull/3132#pullrequestreview-1024481524
