### ISSUE TITLE
Reanimated 3.0.0-rc.0 crashes on Fabric-enabled apps

### ISSUE THREAD

**Issue by zolbooo** [software-mansion/react-native-reanimated#3350]
## Description
Any `react-native-reanimated` calls crash app with Segmentation fault on both iOS and Android.

### Expected behavior
Apps should not crash

### Actual behavior & steps to reproduce
1. Clone repro from link below
2. Run `yarn`
3.  `cd ios && RCT_NEW_ARCH_ENABLED=1 pod install`
4. `yarn run ios`

## Snack or minimal code example

https://github.com/zolbooo/reanimated-crash

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.69.1     |
| react-native-reanimated              |     3.0.0-rc.0    |
| NodeJS                               |    v16.13.2     |
| Xcode                                |     13.4.1 (13F100)    |
| Java                                 |     Zulu11.56+19-CA    |
| Gradle                               |    7.3.3     |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by gavrix** [comment]
The issues seems to be in how Reanimated overrides `UIManagerBinding` in https://github.com/software-mansion/react-native-reanimated/blob/main/Common/cpp/Fabric/ReanimatedUIManagerBinding.cpp#L19-L23

original, fabric's UIManagerBinding has private `eventHandler_ ` which is used to dispatch events 
https://github.com/facebook/react-native/blob/main/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp#L131-L140
and it is initialized with js function asynchronously as part of `runApplication` here: https://github.com/facebook/react-native/blob/main/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp#L445-L460

When ReanimatedUIManagerBinding overrides Fabric's UIManagerBinding it installs a new instance which doesn't have `eventHandler_` initialized. Any subsequent call to dispatchEvents will then attempt to de-reference a nullptr here https://github.com/facebook/react-native/blob/main/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp#L135


I think the proper solution would be catch original instance of UIManagerBinding and wrap in Reanimated's replacement and forward dispatched events onto original instance.

**Comment by tomekzaw** [comment]
@zolbooo Thanks for reporting this issue. I've cloned the repo you provided and installed pods with Fabric enabled using `RCT_NEW_ARCH_ENABLED=1 pod install` but still wasn't able to reproduce the crash, both in debug and release mode, both on simulator and a real device 😢 

@gavrix Indeed, `dispatchEvent` will crash if `eventHandler_` is nullptr and there are at least two possible scenarios:
1. RN installs `nativeFabricUIManager`, then React.js calls `registerEventHandler` and initializes `eventHandler_`. Next, Reanimated overwrites `nativeFabricUIManager` without setting `eventHandler_` so `dispatchEvent` will crash.
2. Reanimated installs `nativeFabricUIManager` before RN and `dispatchEvent` is invoked before React.js calls `registerEventHandler` 

When we were implementing `ReanimatedUIManagerBinding`, we confirmed that Reanimated calls `ReanimatedUIManagerBinding::createAndInstallIfNeeded` before RN injects its `UIManagerBinding` into JS runtime. Here's a screenshot from the debugger showing that `nativeFabricUIManager` is undefined:
 
<img width="892" alt="Zrzut ekranu 2022-07-19 o 09 54 48" src="https://user-images.githubusercontent.com/20516055/179704500-c722c987-12cb-4003-9dff-87b611b9d482.png">

@gavrix @zolbooo Can you please add the following line of code, set a breakpoint, launch the app and tell us what is the value of `nativeFabricUIManager` in your case?

```cpp
auto existingUiManagerBinding = runtime.global().getProperty(runtime, uiManagerModuleName);
```

**Comment by zolbooo** [comment]
Weirdly, issue disappeared on MacBook Pro 14 inch with M1. I was using MBP 13 inch with Intel Core i5 when this crash appeared.
This issue also could be related to Cocoapods (I was using cocoapods installed globally on old machine) and now I am using `rvm` with `bundle install`.

Let me find an x86 machine and try to reproduce issue again. Where should I add new code with breakpoint?

**Comment by zolbooo** [comment]
It seems that `uiManager` was already initialized before `createAndInstallIfNeeded` is called:
<img width="805" alt="Screen Shot 2022-07-19 at 17 16 28" src="https://user-images.githubusercontent.com/33338165/179714770-27beebf6-e0d8-4c3f-9145-f3bc09d6b4ad.png">

**Comment by zolbooo** [comment]
> @zolbooo @gavrix I've implemented a fix. Can you please check if #3402 works for you?
> 
> Here's how you can checkout a specific commit in `package.json`:
> 
> ```
> "react-native-reanimated": "software-mansion/react-native-reanimated#3407457472c912433a4b9ff2c0053a7944604b37"
> ```

Everything works now, great! Do you any estimates when this fix is released?

**Comment by tomekzaw** [comment]
@zolbooo Thank you. Can you please check one more time if it works on 1f4b8acd3d26d7f2c4fd035e30833b083cb039f6?

> Do you any estimates when this fix will be released?

Once it works, we will merge it as soon as possible (this week). We are still working on some Fabric-specific improvements that we wish to include in next release.

> Sorry, I forgot to revert my workaround before testing

Just out of curiosity, what was your workaround? 😄

**Comment by zolbooo** [comment]
> Just out of curiosity, what was your workaround? 😄

I imported `react-native-reanimated` in `index.js` before App renders.

**Comment by zolbooo** [comment]
> @zolbooo Thank you. Can you please check one more time if it works on [1f4b8ac](https://github.com/software-mansion/react-native-reanimated/commit/1f4b8acd3d26d7f2c4fd035e30833b083cb039f6)?

Yep, everything is fine now.

**Comment by tomekzaw** [comment]
@zolbooo Great news! Thanks for your help. Looking forward to merging #3402 once it's reviewed.
