### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by xclidongbo** [software-mansion/react-native-reanimated#3352]
React Native: 0.63.2

Could not find method android() for arguments [build_4r6xsikqee700koo7212wljzb$_run_closure1@44fcfae4] on project ':react-native-reanimated' of type org.gradle.api.Project.

**Comment by tomekzaw** [comment]
Hello @xclidongbo! When exactly does this error appear? How do you build the app? Which version of Reanimated are you using?

**Comment by xclidongbo** [comment]
```
subprojects {
    afterEvaluate {
        project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion 30
                    buildToolsVersion "30.0.2"
                }
            }
    }
}
```
