### ISSUE TITLE
tried to synchronously call  annonymus function from a diffrent thread .occured in node_modules/react-native-reanimated/src/reanimated2/hook/useanimatedstyle... possible solutions are:-1.if you synchronously execute this method ,mark it as worklet, 2.if you want to execute this method on the js thread, wrap it using runOnJs... 

### ISSUE THREAD

**Issue by ardhendu12345** [software-mansion/react-native-reanimated#3356]
## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |         |
| react-native-reanimated              |         |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by ardhendu12345** [comment]
React native reanimated function works properly for android but in case of react ios it provides the error..

**Comment by linweiboy** [comment]
you can try:
yarn start --reset-cache
npm start -- --reset-cache
expo start -c
This may be caused by the cache, I successfully solved the problem by running yarn start --reset-cache

**Comment by tomekzaw** [comment]
Hello @ardhendu12345! Thanks for submitting this issue.

It looks like you are trying to directly call an anonymous function which is not a worklet from a worklet.

Most likely you need to add `'worklet';` directive at the beginning of the body of the anonymous function as well.

Check out https://github.com/software-mansion/react-native-reanimated/issues/3367#issuecomment-1195247461 from analogous issue for a more detailed explanation.
