### ISSUE TITLE
Cannot read properties of undefined (reading 'opts')

### ISSUE THREAD

**Issue by jeremyspritelyco** [software-mansion/react-native-reanimated#3362]
## Description
Fresh install react-native-reanimated with expo 45

### Expected behavior
It should work

### Actual behavior & steps to reproduce
```
Cannot read properties of undefined (reading 'opts')
TypeError: Cannot read properties of undefined (reading 'opts')
    at pre (.../node_modules/react-native-reanimated/plugin.js:764:16)
```

## Snack or minimal code example
Not yet.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.68.2    |
| react-native-reanimated              |      2.8.0   |
| NodeJS                               |   16      |
| Xcode                                |    13     |
| Java                                 |     11    |
| Gradle                               |      ?   |
| expo                                 |     45    |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by jeremyspritelyco** [comment]
I am missing and reanimated to babel configuration. Closed that issue.

**Comment by AlanCasal** [comment]
Facing the same issue here with 
"react-native-reanimated": "~3.10.1"

"react-native": "0.74.5",
"react": "18.2.0",
"expo": "~51.0.28",

halp 🥲

**Comment by nandorcsupor** [comment]
What's the solution to this ? 
- I made a fresh Expo project with template Navigation and typescript.
- Did the steps here to add react-native-reanimated : https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/

- So added a metro.config.js and a babel.config.js - Even though both of these were not part of the original expo stuff.
- App.json plugins: "plugins": ["expo-router", "react-native-reanimated/plugin"],

any solution ?
