### ISSUE TITLE
Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`

### ISSUE THREAD

**Issue by kartikMygoldkart** [software-mansion/react-native-reanimated#3364]
## Description

After Adding React-native-reanimated getting this error
error: node_modules/react-native-reanimated/src/index.ts: /Users/mgk_devops/Desktop/SafariTabsReactNative/SafariTabs/node_modules/react-native-reanimated/src/index.ts: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  5 | export * from './reanimated1';
  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';
    |        ^^^^^^^^^^^^
  8 |

### Actual behavior & steps to reproduce

npm i react-native-reanimated
import Transitioning from "react-native-reanimated"
nix react-native run-android

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.69.1   |
| react-native-reanimated              |  2.9.1       |
| NodeJS                               |   v16.14.2      |
| Xcode                                |  13.3       |
| Java                                 |    11.0.11     |
| Gradle                               |   7.4.2      |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by kartikMygoldkart** [comment]
It doesn't requires minimal code because I haven't written any it throws error upon importing the library

**Comment by piaskowyk** [comment]
Did you add Reanimated Babel plugin? more instructions here - https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin

**Comment by kartikMygoldkart** [comment]
Thanks after adding Babel Plugin and reseting cache its working now

**Comment by stage88** [comment]
My config looks like this and I get the same error, started happening since moving to RN 0.69.1.
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
};
```

**Comment by kartikMygoldkart** [comment]
@stage88 
this is how my babel plugin.js looks like
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ///This Plugin should be last
    'react-native-reanimated/plugin',
],
};

**Comment by prasad-11-cairs** [comment]
having same issue for me also

error: node_modules/react-native-reanimated/src/index.ts: /Users/cti1050/Documents/React-Native/Projects/MAP-CLIENT-APP/node_modules/react-native-reanimated/src/index.ts: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  5 | export * from './reanimated1';
  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';
    |        ^^^^^^^^^^^^
  8 |

**Comment by Yandamuri** [comment]
@vidkreca-inova Yes, That was the issue. Now it's working well.

**Comment by ShinJongUng** [comment]
How to fix it? 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/65454966/177989135-8a4a4141-11d9-4540-86fc-11512ff81d42.png">
i have same issue

**Comment by stage88** [comment]
Using the below command seems to have fixed my issue, thanks @kartikMygoldkart 
```
react-native start --reset-cache
```

**Comment by sbezerrarafa** [comment]
someone managed to solve

**Comment by Yandamuri** [comment]
> someone managed to solve

Have you applied above mentioned solutions?

**Comment by cyrielo** [comment]
> How to fix it?
> <img alt="image" width="565" src="https://user-images.githubusercontent.com/65454966/177989135-8a4a4141-11d9-4540-86fc-11512ff81d42.png">
> i have same issue

I have exactly this same issue.

My babel config looks like this 👇 

`
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    '@babel/plugin-proposal-export-namespace-from',
    ['babel-plugin-transform-remove-imports', {
      "test": [
          'react-toastify', 
          'exceljs', 
          'file-saver', 
      ]
  },],
  'react-native-reanimated/plugin']
};


`

**Comment by michelorthcba** [comment]
this works for me

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ...
    'react-native-reanimated/plugin',
  ],
};

And

yarn start --reset-cache
npm start -- --reset-cache
expo start -c

**Comment by jhonataveronesecrme** [comment]
I use expo, and I'm having the same problem, I couldn't solve the problem with the solutions above

**Comment by Mujahid122418** [comment]
> > How to fix it?
> > <img alt="image" width="565" src="https://user-images.githubusercontent.com/65454966/177989135-8a4a4141-11d9-4540-86fc-11512ff81d42.png">
> > i have same issue
> 
> I have exactly this same issue.
> 
> My babel config looks like this 👇
> 
> ```
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   plugins: [
>     '@babel/plugin-proposal-export-namespace-from',
>     ['babel-plugin-transform-remove-imports', {
>       "test": [
>           'react-toastify', 
>           'exceljs', 
>           'file-saver', 
>       ]
>   },],
>   'react-native-reanimated/plugin']
> };
> ```



> > How to fix it?
> > <img alt="image" width="565" src="https://user-images.githubusercontent.com/65454966/177989135-8a4a4141-11d9-4540-86fc-11512ff81d42.png">
> > i have same issue
> 
> I have exactly this same issue.
> 
> My babel config looks like this 👇
> 
> ```
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   plugins: [
>     '@babel/plugin-proposal-export-namespace-from',
>     ['babel-plugin-transform-remove-imports', {
>       "test": [
>           'react-toastify', 
>           'exceljs', 
>           'file-saver', 
>       ]
>   },],
>   'react-native-reanimated/plugin']
> };
> ```

I have the same issue? how to fix it?

**Comment by cyrielo** [comment]
Ensure that npx pod-install runs successfully without errors

**Comment by ManuDavril31** [comment]
this works for me

`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
`

**Comment by memoray** [comment]
this worked for me too (on mac)

module.exports = {
presets: ['module:metro-react-native-babel-preset'],
plugins: ['react-native-reanimated/plugin'],
};

**Comment by DannyPark1** [comment]
anyone who couldn't solve this issue even tho after adding 'react-native-reanimated/plugin' as a plugin in babel.config.js?

**Comment by xrarberimed** [comment]
Even after adding 'react-native-reanimated/plugin' to babel.config.js as a plugin, I couldn't solve this problem.

**Comment by udayarajurs** [comment]
this worked for me 

module.exports = {
presets: ['module:metro-react-native-babel-preset'],
plugins: ['react-native-reanimated/plugin'],
};

**Comment by Abdel-dev1** [comment]
dosen't work form me ? any propositions !
module.exports = {
presets: ['module:metro-react-native-babel-preset'],
plugins: ['react-native-reanimated/plugin'],
};

**Comment by dpadula** [comment]
I guess that if you are using react-native-paper or another package in babel, the config could be like:

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
};

**Comment by symanhnguyen** [comment]
after add react-native-reanimated/plugin, and reset cache using yarn command,  i can't fix this bug

**Comment by Htoomyat99** [comment]
Thank you so much,  after adding plugin and clear cache , I can solve this error.

**Comment by codefromrvk** [comment]
Do not confuse **presets** with **plugins**. 
Create a new field called plugin if its not already there.
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```

**Comment by mamuga** [comment]
still doesn't work for me even after adding 'react-native-reanimated/plugin' as a plugin

**Comment by flawlessk** [comment]
i read all the comments, added  plugins of reanimated/plugin in babel, also did reset cache but it's not working, again same error, what should i do in this case?

**Comment by mary-caraveo** [comment]
I had the same problem, but I solved it by performing the following steps:

1. `yarn add react-native-reanimated`
2. babel.config.js
`module.exports = {
presets: ['module:metro-react-native-babel-preset'],
plugins: ['react-native-reanimated/plugin'],
};`

3. `yarn start --reset-cache`

I hope it works for you

**Comment by ThugYugi** [comment]
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};



It Works for me

**Comment by jroux-git** [comment]
I had this issue as well:
![image](https://user-images.githubusercontent.com/8018138/185742122-59dfa77d-91e9-41b1-8657-955dbd3b6068.png)

When did it occur? After run expo upgrade to expo SDK v46 and related updates and updated to expo cli v6.0.5

What worked for me: updated my babel.config.js as follows:
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      'react-native-reanimated/plugin'
    ]
  };
};
`

**Comment by terriadsit** [comment]
Changed Babel.config.js as ThugYugi recommends above,

module.exports = {
presets: ['module:metro-react-native-babel-preset'],
plugins: ['react-native-reanimated/plugin'],
};
 then at command prompt:  

expo start -c 

as per michelorthcba's suggestion above.

Originally tried these steps on my app and still could not get the drawer to work. Had to make a complete new app with just the drawer.

**Comment by lorissikora** [comment]
Faced the same issue for my setup using Expo and rnuilib, which depends on react-native-reanimated. It seemed to have been some caching issue which I was only able to clear using `expo start --clear`.

[Source](https://docs.expo.dev/versions/latest/sdk/reanimated/#installation)

**Comment by mar4elkin** [comment]
@dpadula thanks, you saved my day!

**Comment by pottercomuneo** [comment]
For all the ones like me still struggling after adding the element into the array (babel.config.js) and doing reset-cache, make sure you added the row in the _outer_ array, you may be sure you did but in the end you may just have seen wrong 😁

**Comment by MehmetKaplan** [comment]
# Not Working vs Working Configs

## Not working

#### babel.config.js

```javascript
module.exports = function (api) {
	api.cache(true);
	return {
		presets: ['babel-preset-expo'],
		plugins: ['react-native-reanimated/plugin']
	};
};
```

#### Compile Output

```bash
mehmetkaplan:example$ expo start --web -c
...
...
Web Bundling complete 7845ms
./node_modules/react-native-animated-layout/node_modules/react-native-reanimated/lib/index.web.js 3:9
Module parse failed: Unexpected token (3:9)
File was processed with these loaders:
 * ../../../../.config/yarn/global/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import "./reanimated2/js-reanimated/global";
| export * from "./reanimated2";
> export * as default from "./Animated";
Started Metro Bundler
```

## Working

#### babel.config.js

Added `'@babel/plugin-proposal-export-namespace-from'` into the `plugins` array, still keeping `'react-native-reanimated/plugin'` as the last entry in the array:

```javascript
module.exports = function (api) {
	api.cache(true);
	return {
		presets: ['babel-preset-expo'],
		plugins: ['@babel/plugin-proposal-export-namespace-from', 'react-native-reanimated/plugin']
	};
};
```

#### Compile Output

```bash
mehmetkaplan:example$ expo start --web -c
...
Started Metro Bundler
Web Bundling complete 12568ms
````

Works like charm at this point.

PS: The problem pops every now and then. I am not so sure if npm command lets modifying the `babel.config.js` file programmatically. But if it is possible, maybe it is better to patch the reanimated2 installation so that it does not need to be done manually.

**Comment by jo-joanna** [comment]
> 

Thanks so much! You're a life saver :D

**Comment by jo-joanna** [comment]
> I guess that if you are using react-native-paper or another package in babel, the config could be like:
> 
> module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], env: { production: { plugins: ['react-native-paper/babel'], }, }, };

@dpadula Thanks so much! You're a life saver :D

**Comment by ru88s** [comment]
I have referred to this one but it still doesn't work for me.
"expo":"^46.0.0",
"react-native": "0.69.6",

**Comment by ru88s** [comment]
```js
"babel-preset-expo": "~9.2.0",
"expo": "^46.0.14",
"react-native": "0.69.6",
"react-native-gesture-handler": "~2.5.0",
"react-native-paper": "^4.11.2",
"react-native-reanimated": "~2.9.1",
```

```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      "@babel/plugin-proposal-export-namespace-from",
      "react-native-reanimated/plugin",
    ],
    env: {
      production: {
        plugins: ["react-native-paper/babel"],
      },
    },
  };
};
```

Still no solution.
Please help.

**Comment by adamhari** [comment]
I've been struggling with this. I ensured my `babel.config.js` was proper and that my yarn cache was cleared. It worked fine locally but failed to build with this error in Github Actions CI/CD, even after disabling the yarn cache from the `setup-node` action. Downgrading from 2.10.0 to 2.9.1 immediately fixed it.

**Comment by KristinaHus** [comment]
@adamhari In my case, it was completly opposite. As soon as I updated to react-native-reanimated v2.10.0 it started to work. Thanks for pointing to the module version, because as I updated to Expo SDK 46 it automatically installed v2.9.1.

**Comment by mvrahas** [comment]
I'm using the Expo (v46) managed workflow with a custom dev client. I was seeing an error even after following the steps [here](https://docs.expo.dev/versions/latest/sdk/reanimated/) to install react-native-reanimated. After rebuilding a new version of the custom dev client using EAS Build, the error disappeared. It could be worth a try for anybody still struggling with this.

**Comment by ru88s** [comment]
Still not resolved.
Is there anyone like you?

```
module.exports = function (api) {
	api.cache(true);
	return {
		presets: ['babel-preset-expo'],
		plugins: ['@babel/plugin-proposal-export-namespace-from', 'react-native-reanimated/plugin'],
                env: {
                  production: {
                    plugins: ['react-native-paper/babel'],
                  },
                },
	};
};
```

**Comment by Yevl** [comment]
1. Add plugins: ['react-native-reanimated/plugin'] as a plugin
2. yarn add react-native-reanimated
3. yarn -clean

**Comment by msaiedimoien** [comment]
I had this problem, but I solved it by performing the following steps:

- yarn add react-native-reanimated

- babel.config.js
   module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: ['react-native-reanimated/plugin'], };

- yarn start --reset-cache

**Comment by zeze111** [comment]
> Faced the same issue for my setup using Expo and rnuilib, which depends on react-native-reanimated. It seemed to have been some caching issue which I was only able to clear using `expo start --clear`.
> 
> [Source](https://docs.expo.dev/versions/latest/sdk/reanimated/#installation)

@lorissikora this worked like a charm, was finding it difficult looking for solutions for expo react-native projects and this did the trick!

**Comment by trevorallred** [comment]
I'm on Expo 46. Downgrading to 2.9.1 immediately fixed this issue. Thanks @adamhari for the tip.

I looks like "@babel/plugin-proposal-export-namespace-from" was dropped after 2.9.1. I don't see it in the latest 2.12.1. I can see [this commit](https://github.com/software-mansion/react-native-reanimated/commit/9a6f1610a523512d00659e336dd37b7f36a57688#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) that drops it. But I can't find an exact commit that drops it between 2.9 and 2.12.

**Comment by Melvin231** [comment]
add this code in your babel.config.js  it is located in the root directory of your project

module.exports = {
presets: ['module:metro-react-native-babel-preset'],
plugins: [
///This Plugin should be last
'react-native-reanimated/plugin',
],
};

the run this command

npm start --cache-reset

hopefully it will work for you

**Comment by sreuter** [comment]
We ran into the same issue. It doesn't seem to be officially documented that you'll need to manually include `@babel/plugin-proposal-export-namespace-from`, looking at https://docs.swmansion.com/react-native-reanimated/docs/2.2.x/installation/#babel-plugin. We actually ran into this after upgrading from Expo 44 to 46.

@piaskowyk @brentvatne  I'd assume more people will run into this after upgrading to Expo 46. If including `@babel/plugin-proposal-export-namespace-from` is actually the solution, should we add it to the docs above?

After fixing this, we actually ran into another issue with our react native web bundle, being that it's now throwing `TypeError: undefined is not an object (evaluating 'e[t].call')` on load. Not sure if related, but I thought I would bring it up, as we're worried adding the plugin is actually hiding some runtime errors, as mentioned by @adamhari in https://github.com/software-mansion/react-native-reanimated/issues/3364#issuecomment-1270483525. It seems like some people even opted for downgrading from the Expo 46 recommended version of reanimated.

**Comment by erisvaldojunior** [comment]
same issue here (Expo SDK 47). Had to manually add  "@babel/plugin-proposal-export-namespace-from" on babel.config.js plugins array.

**Comment by lucksp** [comment]
I have this with Expo SDK46, after installing the `react-native-bottom-sheet` library

**Comment by goltra** [comment]
Expo SDK 48, only way to work, almost for me, was  adding  "@babel/plugin-proposal-export-namespace-from" to babel.config.js before "react-native-reanimated/plugin".

```
plugins: [
            ...
            "@babel/plugin-proposal-export-namespace-from",
            "react-native-reanimated/plugin"
        ]
```

**Comment by VishalKishwer5** [comment]
### After adding plugins im facing same error in react-native
s: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  5 | export * from './reanimated1';
  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';
`module.exports = function(api) {
  
 
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    presets: ["module:metro-react-native-babel-preset"],
    plugins: ["react-native-reanimated/plugin"],
  };
};
module.exports = {
  presets: [
      ['module:metro-react-native-babel-preset', { useTransformReactJSXExperimental: true }],
  ],
  plugins: [
      [
          '@babel/plugin-transform-react-jsx',
          {
              runtime: 'automatic',
          },
      ],
      
  ],
};`
**Can anyoneHelp me**

**Comment by smwq** [comment]
I first faced the web server deprecated warning after updating to expo 48 and also some warning in react-native-reanimated and react-native-paper. 

[https://github.com/expo/expo/issues/21728](url)

![image](https://github.com/expo/expo/assets/8836421/55b1510d-b20d-43ea-a53d-d38312ea6cf2)
![image](https://github.com/expo/expo/assets/8836421/1d3fc3a5-c13b-4c82-81e9-0aeb62210e7d)

I tried the provided fix in the issue to add bundler as metro for web in app.json and it worked to remove all warnings. It started working without any warnings again.
{ "expo": { //... "web": { "bundler": "metro", //... } } }

But after few hours, I was getting react-native-reanimated export namespace error.
[https://github.com/software-mansion/react-native-reanimated/issues/3364](url)

![image](https://github.com/expo/expo/assets/8836421/84f74f24-28e2-4425-aab6-22afda52d140)

So, I tried the solution provided in that issue to add @babel/plugin-proposal-export-namespace-from and insert in babel.config.js plugin array and the error was fixed. One user also reported that adding this plugin fixes the error but may hide some runtime errors.

Is anyone else also facing these issues after updating to expo 48?

@goltra Did you came across any other issue related to this since then after adding export namespace plugin?

**Comment by goltra** [comment]
> I first faced the web server deprecated warning after updating to expo 48 and also some warning in react-native-reanimated and react-native-paper.
> 
> [https://github.com/expo/expo/issues/21728](url)
> 
> ![image](https://user-images.githubusercontent.com/8836421/248776755-55b1510d-b20d-43ea-a53d-d38312ea6cf2.png) ![image](https://user-images.githubusercontent.com/8836421/248777061-1d3fc3a5-c13b-4c82-81e9-0aeb62210e7d.png)
> 
> I tried the provided fix in the issue to add bundler as metro for web in app.json and it worked to remove all warnings. It started working without any warnings again. { "expo": { //... "web": { "bundler": "metro", //... } } }
> 
> But after few hours, I was getting react-native-reanimated export namespace error. [https://github.com/software-mansion/react-native-reanimated/issues/3364](url)
> 
> ![image](https://user-images.githubusercontent.com/8836421/248778682-84f74f24-28e2-4425-aab6-22afda52d140.png)
> 
> So, I tried the solution provided in that issue to add @babel/plugin-proposal-export-namespace-from and insert in babel.config.js plugin array and the error was fixed. One user also reported that adding this plugin fixes the error but may hide some runtime errors.
> 
> Is anyone else also facing these issues after updating to expo 48?
> 
> @goltra Did you came across any other issue related to this since then after adding export namespace plugin?

no... only a simple question, have you remove node modules and install again ?

**Comment by smwq** [comment]
> > I first faced the web server deprecated warning after updating to expo 48 and also some warning in react-native-reanimated and react-native-paper.
> > [https://github.com/expo/expo/issues/21728](url)
> > ![image](https://user-images.githubusercontent.com/8836421/248776755-55b1510d-b20d-43ea-a53d-d38312ea6cf2.png) ![image](https://user-images.githubusercontent.com/8836421/248777061-1d3fc3a5-c13b-4c82-81e9-0aeb62210e7d.png)
> > I tried the provided fix in the issue to add bundler as metro for web in app.json and it worked to remove all warnings. It started working without any warnings again. { "expo": { //... "web": { "bundler": "metro", //... } } }
> > But after few hours, I was getting react-native-reanimated export namespace error. [https://github.com/software-mansion/react-native-reanimated/issues/3364](url)
> > ![image](https://user-images.githubusercontent.com/8836421/248778682-84f74f24-28e2-4425-aab6-22afda52d140.png)
> > So, I tried the solution provided in that issue to add @babel/plugin-proposal-export-namespace-from and insert in babel.config.js plugin array and the error was fixed. One user also reported that adding this plugin fixes the error but may hide some runtime errors.
> > Is anyone else also facing these issues after updating to expo 48?
> > @goltra Did you came across any other issue related to this since then after adding export namespace plugin?
> 
> no... only a simple question, have you remove node modules and install again ?

@goltra No, I didn't remove node_modules and install again. I just installed the plugin and added in app.json plugin array.
What is recommended? Shall I remove node_modules and install again?

**Comment by goltra** [comment]
Until I did it, it didn't work.

**Comment by Pulimet** [comment]
I've missed the following (selected) line in .../packages/storybook/.storybook/main.js:
![image](https://github.com/software-mansion/react-native-reanimated/assets/6112126/b7d11a25-11ca-43ef-8ed2-b0844781e300)

After added the issue resolved.
