### ISSUE TITLE
'_ref$current.animateNextTransition' is undefined

### ISSUE THREAD

**Issue by kartikMygoldkart** [software-mansion/react-native-reanimated#3366]
## Description

TypeError: _ref$current.animateNextTransition is not a function
When trying to run  ref.current.animateNextTransition() getting animateNextTransition is undefined
TypeError: _ref$current.animateNextTransition is not a function. (In '_ref$current.animateNextTransition()', '_ref$current.animateNextTransition' is undefined)

### Expected behavior
Expecting it To transition to next state

### Actual behavior & steps to reproduce
getting animateNextTransition is undefined

## Snack or minimal code example

import React, { useRef, useState } from "react";
import { StyleSheet, Dimensions, View } from "react-native";
import {OVERVIEW} from '../../Constants/index'
import Tab from './Tab'
import Transitioning, { Transition ,TransitioningView} from "react-native-reanimated"
const { height } = Dimensions.get("window");

const Tabs= ({Tabs:tabsProps})=>{
    const transition = (
            <Transition.Change interpolation="easeInOut"/>
        )
    const ref = useRef(null);
    const [tabs,setTabs] = useState([...tabsProps]);
    const v = OVERVIEW
    const [selectedTab,setSelectedTab] = useState(v);
    return (
        <View style={{ 
            backgroundColor: "black",
            height: tabsProps.length * height}}>
           <Transitioning.View style={StyleSheet.absoluteFill} ref={ref} transition={transition}>
                {tabs.map((tab,index)=>{
                   return (<Tab
                    closeTab={()=>{
                        if(ref.current){
                            ref.current.animateNextTransition()
                        }
                        setTabs([...tabs.slice(0,index),...tabs.slice(index+1)]);
                    }}
                    onPress={()=>{
                        
                        ref?.current?.animateNextTransition();
                        setSelectedTab(selectedTab===index ? OVERVIEW:index);
                    }}
                    tab={tab}
                    index={index}
                    selectedTab={selectedTab}
                    />)
                })}
           </Transitioning.View>
        </View>
    )
}
export default Tabs;

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.69.0      |
| react-native-reanimated              |  2.9.1       |
| NodeJS                               |    16.4.2     |
| Xcode                                |    13.3     |
| Java                                 |   11.0.11      |
| Gradle                               |   7.4.2      |
| expo                                 |   45.0.6      |

## Affected platforms

- [ x] Android
- [x ] iOS
- [ ] Web

**Comment by kartikMygoldkart** [comment]
here is git repository https://github.com/kartikMygoldkart/reanimatedTransition.git 
but you have to make changes in node modules of react-native-web according to the error you are getting

**Comment by piaskowyk** [comment]
Hey, I am not sure what you want to do, but Reanimated hasn't any Transition or TransitioningView objects. I just can suggest to you check out our API in the documentation - https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle
