### ISSUE TITLE
Tried to synchronously call function {parseISO} from a different thread - but it's marked as a worklet?

### ISSUE THREAD

**Issue by Norfeldt** [software-mansion/react-native-reanimated#3367]
## Description

Marking function as worklet but it still tries to call it on the JS thread

### Expected behavior

It will run on the UI thread

### Actual behavior & steps to reproduce

Try out the snack (will not show logs or the error)

or pull down the example repo try it locally (will show logs and error)

![simulator_screenshot_9F3A86CA-C246-4BE0-8274-B6E912A8BEDE](https://user-images.githubusercontent.com/678806/177544078-107ade3e-e73d-4702-981c-bb3031fc28fe.png)

## Snack or minimal code example

https://github.com/Norfeldt/worklet-example/blob/main/App.tsx

https://snack.expo.dev/@nord_investments/worklet-example

```
import React, { useEffect } from 'react';
import { StyleSheet, View, Text } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withSpring,
  withRepeat,
  useAnimatedGestureHandler,
} from 'react-native-reanimated';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';
import { ReText } from 'react-native-redash';
import { format, parseISO } from 'date-fns'

const someWorklet = (year: string, displayFormat = 'dd.MM.yyyy') => {
  'worklet';

  console.log('worklet log');
  const formattedDate = format(parseISO(`${year}-01-01`), displayFormat);

  return formattedDate;
};

export default function App() {
  const year = useSharedValue('2022');
  const randomDate = useSharedValue('N/A');

  const tapGesture = Gesture.Tap().onStart(() => {
    console.log('getsture logging');
    randomDate.value = someWorklet(year.value);
  });

  return (
    <View style={styles.container}>
      <GestureHandlerRootView style={styles.gestureArea}>
        <GestureDetector gesture={tapGesture} style={styles.gestureArea}>
          <Animated.View style={styles.gestureArea}>
            <Text>Static Text</Text>
            <ReText text={randomDate} style={styles.text} />
          </Animated.View>
        </GestureDetector>
      </GestureHandlerRootView>
    </View>
  );
}
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.64.3     |
| react-native-reanimated              |     ~2.3.1    |
| NodeJS                               |     v16.15.1    |
| Xcode                                |   N/A      |
| Java                                 |     N/A    |
| Gradle                               |      N/A   |
| expo                                 |      44   |

> package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "react-native-paper": "4.9.2",
    "@expo/vector-icons": "^12.0.0",
    "expo-constants": "~13.0.2",
    "react-native-reanimated": "~2.3.1",
    "react-native-screens": "~3.10.1",
    "react-native-gesture-handler": "~2.1.0",
    "date-fns": "^2.28.0",
    "react-native-redash": "^18.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "typescript": "~4.3.5"
  },
  "private": true,
  "resolutions": {
    "@types/react": "~17.0.47"
  }
}

## Affected platforms

- [ ] Android
- [ x] iOS
- [ ] Web

**Comment by Norfeldt** [comment]
Can anyone reporduce the issue with the provided repo?

**Comment by tomekzaw** [comment]
Hello! Thanks for reporting this issue.

The problem here is that `someWorklet` tries to synchronously call `parseISO` function which is not a worklet.
This means that it can be invoked only from the main JS VM and cannot be executed on the secondary Reanimated JS VM running on the UI thread.

The error message suggests to use `runOnJS` but in this case it doesn't really make sense to wait until this function completes on the main RN JS VM since this could slow down the animations if JS thread is currently busy.

Unfortunately, currently there is no easy way of workletizing functions from third-party libraries (unless they are explicitely marked as worklets, obviously). As a workaround, you can implement `parseISO` and `format` yourself and don't forget to mark them as worklets.

**Comment by Norfeldt** [comment]
Quite new to the worklet concept. But is one of the problems that is being imported on the JS thread and therefore can't be declared as a worklet.

If so isn't there a way to "bundle" a 3rd party into a worklet?

**Comment by tomekzaw** [comment]
@Norfeldt Currently I'm not aware of any direct method of bundling 3rd party library as worklets. In general, worklets are meant to be short and simple JS functions used mostly for mathematical calculations related to animations which doesn't involve third-party libs.

As a workaround, you can pre-calculate the values of 3rd-party library function on JS thread, aggregate them in an array and send the results to the secondary UI JS context either using `runOnUI` or via a shared value. Then, on each animation frame, you can read and use appropriate value from the array in worklet.

**Comment by Norfeldt** [comment]
Is it correctly understood that a shared value is only initially "shared" in a way that it comes from the JS react thread but like react ref there isn't the same life cycle methods/events that makes react evaluate the virtual DOM every time it changes?

Transforming the data and putting it in a shared value makes sense then.


Using how to pass context via RunOnUI I don't understand how can be archived since the docs uses a worklet as the example and the event comes from the UI thread (pan gesture scroll showing for different dates). Could you elaborate a little more on this approach?

**Comment by tomekzaw** [comment]
> Is it correctly understood that a shared value is only initially "shared" in a way that it comes from the JS react thread but like react ref there isn't the same life cycle methods/events that makes react evaluate the virtual DOM every time it changes?

Shared values are completely independent from React, component life cycle, virtual DOM etc. Basically, shared value is just some JS value (number, string, array or object) that you can read and update from both JS contexts, i.e. from RN code and from worklets. In worklets, reading and writing to shared value is synchronous. In regular RN JS code, reading shared value is synchronous (but the result can be outdated) and writing to shared value is asynchronous (i.e. scheduled on the UI thread). Shared values can be used to share some data between these two JS contexts.

> Using how to pass context via RunOnUI I don't understand how can be archived since the docs uses a worklet as the example and the event comes from the UI thread (pan gesture scroll showing for different dates). Could you elaborate a little more on this approach?

The workaround I have suggested only makes sense when the "update" originates from the main JS context (e.g. after RN component state change, when some network request completes, etc.). In cases when the event originates from the UI thread (i.e. when using Gesture Handler), we would like to handle it on the UI thread so the app feels responsive. In the specific case of showing different dates depending on pan gesture scroll, I would recommend implementing the formatting function as a worklet on your own.

**Comment by Norfeldt** [comment]
Thank you very much for this great clarification - it's a great help to me.
