### ISSUE TITLE
Support long paths when building with new architecture on windows

### ISSUE THREAD

**Issue by aleluiah** [software-mansion/react-native-reanimated#3378]
react-native-reanimated and react-native-gesture-handler build failed on windows when using the new arch enabled due to windows long path limit

Task :react-native-gesture-handler:buildNdkBuildDebug[arm64-v8a][rngesturehandler_modules]
C/C++: C:/android-ndk-r21e/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld: cannot find C:\Cliqueon\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Debug\3x5p2864/obj/local/arm64-v8a/objs-debug/rngesturehandler_modules/C_/Cliqueon/node_modules/react-native-gesture-handler/android/src/main/jni/RNGestureHandlerComponentsRegistry.o: No such file or directory
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++: make: *** [C:/android-ndk-r21e/build//../build/core/build-binary.mk:725: C:\Cliqueon\node_modules\react-native-gesture-handler\android\build\intermediates\cxx\Debug\3x5p2864/obj/local/arm64-v8a/librngesturehandler_modules.so] Error

check out https://github.com/facebook/react-native/pull/33784

**Comment by tomekzaw** [comment]
Hello @aleluiah! Thanks for reporting this issue! We also appreciate pointing out the analogous issue in react-native repo.

I'm afraid that we don't have any setup for building Reanimated on Windows. Could you please check if adding `LOCAL_SRC_FILES := $(subst $(LOCAL_PATH)/,,$(LOCAL_SRC_FILES))` after [this](https://github.com/software-mansion/react-native-reanimated/blob/150e787d1101249122871128be5805c4fe288286/FabricExample/android/app/src/main/jni/Android.mk#L16) line in our `Android.mk` for Fabric resolves the issue? Thank you in advance.

**Comment by vreoo** [comment]
> Hello @aleluiah! Thanks for reporting this issue! We also appreciate pointing out the analogous issue in react-native repo.
> 
> I'm afraid that we don't have any setup for building Reanimated on Windows. Could you please check if adding `LOCAL_SRC_FILES := $(subst $(LOCAL_PATH)/,,$(LOCAL_SRC_FILES))` after [this line in our `Android.mk` for Fabric](https://github.com/software-mansion/react-native-reanimated/blob/150e787d1101249122871128be5805c4fe288286/FabricExample/android/app/src/main/jni/Android.mk#L16) resolves the issue? Thank you in advance.

I can't seem to find Fabric in my package files at all, So what is the deal here??
I am using v2.10.0 of react-native-reanimated.

**Comment by Latropos** [comment]
Closing, since we don't have any setup for building Reanimated on Windows
