### ISSUE TITLE
react-native-v8 compatibility with reanimated v2

### ISSUE THREAD

**Issue by shamilovtim** [software-mansion/react-native-reanimated#3381]
## Description

In #3132 v8 compatibility was landed for reanimated but it seems like this was only merged for v3 and not cherry-picked onto v2

### Expected behavior

Expect compatibility with v8 in react-native-reanimated v2

**Comment by shamilovtim** [comment]
> because reanimated v2 shipped prebuilt aar and it doesn't make sense to include more aar for v8. maybe i can have a reanimated fork, is it feasible to you?

Yeah that would be alright! Let me know if I can help maintain. My IDE isn't setup for C++ projects but I'd be happy to start dipping my feet in the water if it eases the burden.

**Comment by AndreiCalazans** [comment]
Hey @Kudo we also need to migrate to Reanimated V2. Anything we can do to help expedite a fork or a PR for Reanimated V2 to support V8?

**Comment by Kudo** [comment]
added v8 support for reanimated 2 here: https://github.com/kudo/react-native-reanimated/tree/v8/2.9.1
could install it through `yarn add kudo/react-native-reanimated#v8/2.9.1`

**Comment by tomekzaw** [comment]
@Kudo Thanks for taking care of this issue! 🎉

I wonder whether it's possible to use Reanimated with V8 on iOS, have you tried it?

**Comment by Kudo** [comment]
@tomekzaw for the prebuilt AAR in reanimated 2, [the v8 support commit is intentionally building from source](https://github.com/Kudo/react-native-reanimated/commit/2b96fdc9676e83594ab886d02c42a03365fc12f2#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR140-R142). it would not increase the npm package size much for you.

as far as i know, there're some developers still stick on reanimated v1. they could not upgrade v3 for this purpose. that's why   i was helping to add v8 support on v2.

> PS. @Kudo I wonder whether it's possible to use Reanimated with V8 on iOS, have you tried it?

i did once have it but no longer maintain. v8 on ios doesn't support JIT and WebAssembly. i don't think there're strength to run v8 on ios than jsc or hermes. besides, the v8 library should disable ios Bitcode to reduce size. developers should also disable bitcode for their apps.

**Comment by shamilovtim** [comment]
Is there a migration guide to move from v1 to v2? I see recommendations in the blog post to do it but I don't see it documented what got deprecated and what replaces it.

**Comment by tomekzaw** [comment]
> @tomekzaw for the prebuilt AAR in reanimated 2, [the v8 support commit is intentionally building from source](https://github.com/Kudo/react-native-reanimated/commit/2b96fdc9676e83594ab886d02c42a03365fc12f2#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR140-R142). it would not increase the npm package size much for you.

Thanks @Kudo for your answer. I wasn't aware of the fact that it builds from sources too. Do you want to keep and maintain it as a fork or shall we backport this back to v2 as well? cc @piaskowyk 

> v8 on ios doesn't support JIT and WebAssembly. i don't think there're strength to run v8 on ios than jsc or hermes.

That's right. I've heard that V8 has great performance on arithmetic operations (i.e. calculating animations, crypto stuff, etc.) but most likely that's thanks to JIT which is not available on iOS. Besides, I'm not sure if Apple allows running JS VMs other than JSC (or Hermes) for App Store review.

**Comment by shamilovtim** [comment]
> > @tomekzaw for the prebuilt AAR in reanimated 2, [the v8 support commit is intentionally building from source](https://github.com/Kudo/react-native-reanimated/commit/2b96fdc9676e83594ab886d02c42a03365fc12f2#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR140-R142). it would not increase the npm package size much for you.
> 
> Thanks @Kudo for your answer. I wasn't aware of the fact that it builds from sources too. Do you want to keep and maintain it as a fork or shall we backport this back to v2 as well? cc @piaskowyk
> 
> > v8 on ios doesn't support JIT and WebAssembly. i don't think there're strength to run v8 on ios than jsc or hermes.
> 
> That's right. I've heard that V8 has great performance on arithmetic operations (i.e. calculating animations, crypto stuff, etc.) but most likely that's thanks to JIT which is not available on iOS. Besides, I'm not sure if Apple allows running JS VMs other than JSC (or Hermes) for App Store review.
> 
> > Is there a migration guide to move from v1 to v2? I see recommendations in the blog post to do it but I don't see it documented what got deprecated and what replaces it.
> 
> @shamilovtim Reanimated 1 and 2 are two completely different APIs and I'm afraid that there is no simple migration guide other than "rewrite everything using worklets". I highly encourage you to check out [this post](https://blog.swmansion.com/introducing-reanimated-2-752b913af8b3) as well as [other articles](https://blog.swmansion.com/search?q=reanimated+2) on SWM blog with introduction to basics of Reanimated 2 as well as numerous examples.

Okay thanks! Am I correct in understanding that there's no way we can reason about this migration in a way where replace `useCode()` with `useNewHook()` and in all cases we should start by completely deleting the v1 animation and rewriting it from the ground up using the new docs? I assume the new approach doesn't use refs and part of this migration will be removal of the ref based approach?

**Comment by tomekzaw** [comment]
@shamilovtim I think it all depends on the complexity of the animation; some parts of lengthy code using Reanimated 1 API (or even DSL) doing some mathematical operations and interpolations can be easily converted to worklets (from Reanimated 2 API) where you can express the calculations elegantly in pure JS. When it comes to refs, I'm not familiar enough with Reanimated 1 to answer this question, but most likely all you need to do is to pass the result of `useAnimatedStyle` hook to `style` prop in `Animated.View`.

**Comment by Kudo** [comment]
> Thanks @Kudo for your answer. I wasn't aware of the fact that it builds from sources too. Do you want to keep and maintain it as a fork or shall we backport this back to v2 as well? cc @piaskowyk

ideally, i would like to backport to v2 if v2 is still going to maintain for a while.
  
> That's right. I've heard that V8 has great performance on arithmetic operations (i.e. calculating animations, crypto stuff, etc.) but most likely that's thanks to JIT which is not available on iOS. Besides, I'm not sure if Apple allows running JS VMs other than JSC (or Hermes) for App Store review.

i think most review concern for running other JS VMs on iOS is Over-The-Air updates. if no OTA there, Apple should allows for other JS VMs.

**Comment by shamilovtim** [comment]
I think this can be closed right? Do the docs need to be updated
