### ISSUE TITLE
react native animated2 TypeError: global.__reanimatedWorkletInit is not a function

### ISSUE THREAD

**Issue by Ahmed-Shehzad** [software-mansion/react-native-reanimated#3394]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-reanimated@2.8.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-reanimated/lib/reanimated2/core.js b/node_modules/react-native-reanimated/lib/reanimated2/core.js
index 284915e..cc8bbbf 100644
--- a/node_modules/react-native-reanimated/lib/reanimated2/core.js
+++ b/node_modules/react-native-reanimated/lib/reanimated2/core.js
@@ -8,6 +8,9 @@ if (global._setGlobalConsole === undefined) {
         // noop
     };
 }
+
+global.__reanimatedWorkletInit = () => { };
+
 const testWorklet = () => {
     'worklet';
 };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by tomekzaw** [comment]
Hello @Ahmed-Shehzad! Thanks for submitting the issue and patch.

As of Reanimated 2.7.0, we completely removed `__reanimatedWorkletInit` from Reanimated codebase (see #3143).

Can you please tell us why exactly this change was necessary for `react-native-reanimated@2.8.0`?

**Comment by hotaryuzaki** [comment]
> Hello @Ahmed-Shehzad! Thanks for submitting the issue and patch.
> 
> In Reanimated 2.7.0 we completely removed `__reanimatedWorkletInit` from Reanimated codebase (see #3143).
> 
> Can you please tell us why exactly this change was necessary for `react-native-reanimated@2.8.0`?

i have same issue here.
```global.__reanimatedWorkletInit is not a function. (In 'global.__reanimatedWorkletInit(_f)', 'global.__reanimatedWorkletInit' is undefined)```
