### ISSUE TITLE
Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from` on `export * as default from './Animated';`

### ISSUE THREAD

**Issue by tomekzaw** [software-mansion/react-native-reanimated#3410]
## Description

Starting from Reanimated 2.9.0, **if you forget to add Reanimated's Babel plugin**, instead of a user-friendly error message, the following error will appear:

```sh
error: node_modules/react-native-reanimated/src/index.ts: /Users/tomekzaw/RNOS/Issue3397/node_modules/react-native-reanimated/src/index.ts: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  5 | export * from './reanimated1';
  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';
    |        ^^^^^^^^^^^^
  8 |
```

| Android | iOS |
|:-:|:-:|
| <img src="https://user-images.githubusercontent.com/20516055/180992073-0c43b86b-84bb-4cc0-8a0f-fae2cd89beda.png" alt="iOS error" height="700" /> | <img src="https://user-images.githubusercontent.com/20516055/180992066-da1f2227-7dc0-46e8-9e1b-55eb0bd095f0.png" alt="Android error" height="700" /> |

![funny meme](https://media.makeameme.org/created/but-we-have-5b164d.jpg)

## Solution

1. Add Reanimated's babel plugin to your `babel.config.js`:
```diff
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
+  plugins: ['react-native-reanimated/plugin'],
};
```

2. Clear application cache (depending on your workflow or favourite package manager):
* `yarn start --reset-cache`
* OR: `npm start -- --reset-cache`
* OR: `expo start -c`

3. Reload app

See [installation docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin) for more details.

## Disclaimer

Obviously, we need to restore [the original user-friendly error message](https://github.com/software-mansion/react-native-reanimated/blob/150e787d1101249122871128be5805c4fe288286/src/reanimated2/core.ts#L49-L51):
* https://github.com/software-mansion/react-native-reanimated/pull/3437

**Comment by DiyarYelbaka** [comment]
Bro you saved my life ! Thank you :)

**Comment by justindc100** [comment]
Thank you for this! was about to pull my hair out

**Comment by PerryRylance** [comment]
Brilliant, thanks folks

**Comment by jdc0092** [comment]
Hello friend, it works quite well for me. Thank you for your contribution and help, greetings! :+1:
