### ISSUE TITLE
RN 0.69.3, ReactNativeConfig.h file not found

### ISSUE THREAD

**Issue by alzhab** [software-mansion/react-native-reanimated#3430]
## Description

After updating project to new version RN 0.69.3 and run project on Xcode, error comings out

<img width="1512" alt="Schermata 2022-08-01 alle 16 46 30" src="https://user-images.githubusercontent.com/47349292/182132287-0efacc21-b6d1-4df7-b17e-d698046e4075.png">

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |0.69.3|
| react-native-reanimated              | ^2.4.1|
| NodeJS                               |18.7.0|
| Xcode                                |13.4.1|
| Java                                 |openjdk version "11.0.16"|
| Gradle                               |7.3.3|
| expo                                 ||

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello @alzhab! Thanks for submitting the issue. Here are some more questions:

1. Do you use Expo?
2. Did you remember to run `RCT_NEW_ARCH_ENABLED=1 pod install` in `ios` directory of your app?

**Comment by tomekzaw** [comment]
I've just created a fresh RN 0.69.3 app, added react-native-reanimated, build the app for iOS and it works fine.

Please make sure that you enable Fabric via environmental variable `RCT_NEW_ARCH_ENABLED` and not directly in Podfile.

Related issues:
* https://github.com/software-mansion/react-native-reanimated/issues/2991
* https://github.com/software-mansion/react-native-reanimated/issues/3316

**Comment by alzhab** [comment]
> 

Hello
1 No, i don't use Expo
2 Yes Fabric enabled and run command with flag RCT_NEW_ARCH_ENABLED=1

**Comment by alzhab** [comment]
> I've just created a fresh RN 0.69.3 app, added `react-native-reanimated`, build the app for iOS and it works fine, both with Fabric enabled and disabled.
> 
> If you want to use Reanimated with Fabric enabled, please make sure that you enable Fabric via environmental variable `RCT_NEW_ARCH_ENABLED=1` when running `pod install`, and not directly in Podfile.
> 
> Related issues:
> 
> * [Not working with Fabric on iOS #2991](https://github.com/software-mansion/react-native-reanimated/issues/2991)
> * [Building failed on 0.69 for iOS #3316](https://github.com/software-mansion/react-native-reanimated/issues/3316)

Thanks, i will try it and close issue if it will help
