### ISSUE TITLE
[Fabric] ScrollView `scrollTo`/`onScroll` loop crash (3.0.0-rc.0, iOS)

### ISSUE THREAD

**Issue by naftalibeder** [software-mansion/react-native-reanimated#3434]
## Description

When calling `scrollTo` on an animated ref inside of a scroll handler callback like this:

```ts
const ref = useAnimatedRef<Animated.ScrollView>();

const scrollHandler = useAnimatedScrollHandler((event) => {
  scrollTo(ref, 0, 0, false);
});

return (
  <Animated.ScrollView
    ref={ref}
    onScroll={scrollHandler}
    ...
  </Animated.ScrollView>
);
```

the app crashes with the following stacktrace:

```
libc++abi: terminating with uncaught exception of type facebook::jsi::JSError: Maximum call stack size exceeded (native stack depth)

RangeError: Maximum call stack size exceeded (native stack depth)
    at _f (native)
    at _f (<path>/react-native-reanimated/src/reanimated2/hook/useAnimatedScrollHandler.ts (53:4):1:271)
    at _f (native)
    at _dispatchCommand (native)
    at dispatchCommand (<path>/react-native-reanimated/src/reanimated2/NativeMethods.ts (56:7):1:194)
    at dispatchCommand (native)
    at _f (<path>/react-native-reanimated/src/reanimated2/NativeMethods.ts (77:13):1:95)
    at _f (native)
    at _f (<path>/react-native-reanimated/FabricExample/src/ScrollViewExample.tsx (14:49):1:110)
    at _f (native)
```

On V2, the `scrollTo` method did not trigger the `onScroll` callback if the previous and next offsets were identical.

### Expected behavior

If the `ScrollView`'s offset is already `0`, calling `scrollTo(ref, 0, 0, false)` should not trigger the `onScroll` handler.

### Actual behavior & steps to reproduce

Any `scrollTo` call triggers the handler, which results in an infinite loop if the handler contains a `scrollTo` call.

## Snack or minimal code example

See this [example](https://github.com/TruckMap/react-native-reanimated/blob/bug/fabric/FabricExample/src/ScrollViewExample.tsx).

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.69.0      |
| react-native-reanimated              |     3.0.0-rc.0    |
| NodeJS                               |    16.16.0     |
| Xcode                                |    13.4     |

## Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

**Comment by tomekzaw** [comment]
Hello @naftalibeder! Thanks for reporting the problem.

I was able to reproduce the issue on iOS with Fabric enabled. Good news is that on Android it works fine.

<details>
<summary>App.tsx</summary>

```tsx
import * as React from 'react';

import Animated, {
  scrollTo,
  useAnimatedRef,
  useAnimatedScrollHandler,
} from 'react-native-reanimated';

import { Text } from 'react-native';

export default function App() {
  const ref = useAnimatedRef<Animated.ScrollView>();

  const scrollHandler = useAnimatedScrollHandler(() => {
    console.log(performance.now());
    scrollTo(ref, 0, 0, false);
  });

  return (
    <Animated.ScrollView
      ref={ref}
      onScroll={scrollHandler}
      scrollEventThrottle={16}>
      <Text style={{ fontSize: 40 }}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed gravida, mi
        non tristique pellentesque, est purus tincidunt lacus, eget venenatis
        ligula sem ut velit. Praesent ut ipsum tristique nisi maximus eleifend
        non et mauris. Nulla et nulla nisi. In at auctor metus. Mauris a
        volutpat mi. Duis eu ipsum a ante mollis luctus sit amet ut felis.
        Pellentesque habitant morbi tristique senectus et netus et malesuada
        fames ac turpis egestas. Aliquam a dui urna. Vestibulum velit eros,
        dapibus nec fringilla vitae, tristique ut dui. Integer molestie
        fermentum ex id sagittis. Suspendisse sodales urna at mauris bibendum,
        quis volutpat nisl lobortis. Nam aliquam rhoncus bibendum. Maecenas a
        ligula mattis odio pharetra fermentum eu ut odio. Curabitur facilisis
        efficitur ipsum, nec lobortis mi porta id. Quisque id neque nisl.
      </Text>
    </Animated.ScrollView>
  );
}
```

</details>

I need to check whether this change of behaviour originates from Reanimated or maybe from React Native itself.

**Comment by tomekzaw** [comment]
It looks like the change in the behaviour of `onScroll` between Paper and Fabric actually originates from React Native and happens only on iOS. I've submitted an issue:
* https://github.com/facebook/react-native/issues/34327

If this issue won't be resolved on react-native side, most likely we will compensate for this change in Reanimated by adding some logic to skip unwanted events and prevent looping.

Currently, we recommend applying the workaround directly in worklets, as suggested in https://github.com/software-mansion/react-native-reanimated/issues/3434#issuecomment-1202116319.

Also, the crash in Reanimated happens due to the fact that in Reanimated we don't handle `facebook::jsi::JSError` exceptions in worklets properly. This is a separate issue that we need to fix.

**Comment by naftalibeder** [comment]
Thank you for putting so much effort into this already!

> I'm wondering if this can be implemented more elegantly using `scrollEnabled` property

From my experience with `UIScrollView` on iOS, changing the enabled property kills the active gesture - the only way I’ve ever found to implement this functionality natively is to continuously set the scroll offset to 0.

> Currently, we recommend applying the workaround directly in worklets, as suggested in https://github.com/software-mansion/react-native-reanimated/issues/3434#issuecomment-1202116319.

I had tried that, but ended up with the same issues you faced. Seems like this needs to get handled all the way down in the React Native `ScrollView` implementation, like you found.

**Comment by tomekzaw** [comment]
@sammy-SC resolved the issue on react-native side in https://github.com/facebook/react-native/commit/dfbf7d4e142a35c5380019a3b485cbad0922e063.

Also, based on the example you have provided, I've checked that this change in react-native repo resolves this issue in Reanimated, see the attached screen recording:

https://user-images.githubusercontent.com/20516055/183507779-0af78d7c-34d5-4706-938a-74ff465b0380.mov

Thanks again for reporting this issue 😄

**Comment by naftalibeder** [comment]
@tomekzaw Confirmed, works perfectly! Thanks!

**Comment by Nader-CS** [comment]
this issue still exist in "react-native-reanimated": "3.19.5", and "react-native": "0.81.6",

**Comment by Nader-CS** [comment]
it crash in ios but works well in android
