### ISSUE TITLE
[transition][android] issue with absoluteFill Images

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#345]
Here the snack of the issue:
https://snack.expo.io/@wcandillon/tactless-chocolate

Works great on iOS in any scenario, fails on Android. Without `ref.current.animateNextTransition()` it will work on Android too.  If you enable `ref.current.animateNextTransition()`and remove the image, it works great on Android. I hope this is enough information. Please let me know if I can provide more information.

**Comment by sinodko** [comment]
something new on this one?

**Comment by jakub-gonet** [comment]
Hey @wcandillon,
sorry that this issue went unnoticed. Is this bug still present in the current version of Reanimated and if so, could you please provide an updated snack?

**Comment by ShaMan123** [comment]
check [this](https://streamable.com/pn0q5) out.
Could it be that components that have inner state management require re-rendering beyond the next transition, hence missing out the animation? e.g `FlatList`
or is it to do with `absolute` positioning?
You can reproduce yourself: [Example/directManipulation/shuffle](https://github.com/ShaMan123/react-native-reanimated/blob/master/Example/directManipulation/shuffle.js)

**Comment by ShaMan123** [comment]
#483 fixed the issue

**Comment by jakub-gonet** [comment]
All right, closing then.
