### ISSUE TITLE
[transition] Cannot transition on opacity, backgroundColor nor color.

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#347]
I was thinking that the transition API would be great to implement a smooth transition from dark to light mode. Unless mistaken, it doesn't seem possible, unfortunately. If the list of properties that can be transition available somewhere?

In case someone is reading this issue and is looking for a workaround, I recommend the `useTransition` hook from redash (https://github.com/wcandillon/react-native-redash#usetransitionstate-any-source-node-destination-node-duration-number-easing-easingfunction-node).

**Comment by jakub-gonet** [comment]
We discussed Transitions internally in our team. Considering that v2 makes creating animations easier and Transitions was an experimental API for a long time, we decided to leave Transitions as they are.
 
We won’t actively fix bugs in them, but we’ll happily merge any PR with fixes. We’re also thinking about rewriting Transitions in v2 sometime in the future.

I’m closing this issue, but if you have further questions, I will be happy to help.
