### ISSUE TITLE
TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by benmechen** [software-mansion/react-native-reanimated#3484]
### Description

When running on Android (issue does not occur on iOS) in _release mode only_, we get the below error:
```
E/ReactNativeJS: TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes
```

![Screenshot 2022-08-17 at 13 24 06](https://user-images.githubusercontent.com/11067128/185118634-4f347771-0b5d-4b43-9a8b-e1db6a08ec3a.png)

This does not occur when running in _debug_ mode, so is only affecting our release builds distributed to testers and users. 
We have followed the suggested steps in the similar issue threads (#2525, #846, #3420), including:
* Adding plugin to babel.config.js
* Resetting metro cache
* Ensuring [installation instructions](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation) have been followed correctly

However most of these issues are iOS only - our issue is the opposite, iOS runs fine but Android does not. 

We have created a reproduction app by stripping everything but react-native-reanimated out of our main app. 

We did recently upgrade from RN 0.64 to 0.68, however this was done a couple weeks before we saw this issue. There have been no changes since that would have an effect on this library that we are aware of. 
We have also tried both upgrading and downgrading the library (2.4.x and 3.0.0-rc.1) with no success. 

### Steps to reproduce

1. Clone reproduction repo
2. Install packages (`npm i`)
3. Run the `stagingRelease` variant (either via Android Studio or via `npm run android`)
4. The app will crash on startup, and an error will be logged in Android Studio only

### Snack or a link to a repository

https://github.com/chelsea-apps/reanimated-repro

### Reanimated version

2.9.1

### React Native version

0.68.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

Pixel 3A API 32

### Acknowledgements

Yes

**Comment by benmechen** [comment]
Reproduction repository is included in the issue, https://github.com/chelsea-apps/reanimated-repro

**Comment by tomekzaw** [comment]
Hey @benmechen!

Can you paste the output of `npm ls react-native-reanimated`? We suspect there can be two versions of Reanimated installed simultaneously which might be the cause of the issue.

**Comment by benmechen** [comment]
@tomekzaw Sure! Here's the output, looks like there's just one

```
ben@Bens-MBP hiver-android-repro-issue % npm ls react-native-reanimated
beepro-frontend@0.1.154 /Users/ben/Documents/Work/hiver/hiver-android-repro-issue
└── react-native-reanimated@2.9.1
```

**Comment by benmechen** [comment]
Going to try running on Fabric and see if it works with TurboModules enabled

**Comment by tomekzaw** [comment]
Hey, I still don't know what is the cause of this issue 😞 

I will let you know if we find something.

**Comment by benmechen** [comment]
Thanks for having a look @tomekzaw. I'm having issues enabling TurboModules, I suspect something may have been missed when we upgraded from RN 0.64 to 0.68 that is only surfacing now. I'm going to try generate a new RN project and see if I can recreate this issue.

**Comment by benmechen** [comment]
Closing this @tomekzaw, turns out to not be an issue with this library directly, instead it was an issue with RN itself. Thanks for your help.

For anyone else with this issue, here's how I solved it:
@tomekzaw's original comment regarding there possibly being multiple versions made me think. Whilst there was only one version installed in node_modules (and as such the dev build of the app), when the app is built for release all JS is bundled into index.android.bundle. 

I had a dig into this and it seems to not have been generated correctly (seems to be an ongoing RN issue). Presumably the RN CLI caches bundles to save build time, and it had cached an old version of the bundle with an old version of Reanimated. When we then updated Reanimated, the two bundled versions were conflicting, causing this issue. 

Removing the cached bundle (which was in source control but I've now removed), and manually generating it using:
```
npx react-native bundle --entry-file index.js --platform android --bundle-output android/app/src/main/assets/index.android.bundle --dev false
```
fixed the issue with the malformed bundle and resolved the original error.

**Comment by roots-ai** [comment]
> Hey @benmechen!
> 
> Can you paste the output of `npm ls react-native-reanimated`? We suspect there may be two versions of Reanimated installed simultaneously which might be the cause of the issue.

├── react-native-reanimated@2.9.1
└─┬ react-native-router-flux@4.3.1
  ├─┬ react-navigation-drawer@2.7.2
  │ └── react-native-reanimated@2.9.1 deduped invalid: "^1.0.0" from node_modules/react-navigation-drawer
  └─┬ react-navigation-tabs@2.11.2
    ├── react-native-reanimated@2.9.1 deduped invalid: "^1.0.0" from node_modules/react-navigation-drawer, "^1.0.0-alpha" from node_modules/react-navigation-tabs
    └─┬ react-native-tab-view@2.16.0
      └── react-native-reanimated@2.9.1 deduped invalid: "^1.0.0" from node_modules/react-navigation-drawer, "^1.0.0-alpha" from node_modules/react-navigation-tabs

I am getting the following output..seems like there are two versions of react-native-reanimated. How to resolve this?

**Comment by tincorvia** [comment]
Hi I am facing this same issue running react native v0.64 and react native reanimated v2.14.4. Reanimated works when I run react-native run-ios, but throws this error when the app is booting if I try to run the same .app file using the xcrun command.

**Comment by cmchandan-CM** [comment]
When I installed 3.1.0 so it is not working but version upgrade with ^3.4.2
It is working fine
![Uploading IMG_20230901_104431.jpg…]()

**Comment by ThalesBMC** [comment]
Anyone found any solution?
One time I was able to fix this error but got an even worse error that just says "Thread crashed"
