### ISSUE TITLE
3.0.0-rc.1 published without types

### ISSUE THREAD

**Issue by natew** [software-mansion/react-native-reanimated#3487]
### Description

Small issue but hard to upgrade to it.

### Steps to reproduce

No TS types.

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/

### Reanimated version

3.0.0-rc.1

### React Native version

0.69.0

### Platforms

Web

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @natew, thanks for letting us know so early and sorry for inconvenience 😄

Indeed, 3.0.0-rc.1 does not include `react-native-reanimated.d.ts`.

We will release 3.0.0-rc.2 with types soon.
