### ISSUE TITLE
Babel/TS transform for writing the animation specifications

### ISSUE THREAD

**Issue by wokalski** [software-mansion/react-native-reanimated#349]
I am wondering if you considered some sort of transform to go from a subset of Javascript to the declarations. So that something like this:

```js
return @reanimated({
  if (!clockRunning(clock)) {
    state.finished = 0;
    state.velocity = velocity;
    state.position = value;
    config.toValue = dest;
    startClock(clock);
  };
  spring(clock, state, config);
  if (state.finished) { 
    stopClock(clock)
  };
  return state.position;
})
```

is transformed into:

```js
  return [
    cond(not(clockRunning(clock)), [
      set(state.finished, 0),
      set(state.velocity, velocity),
      set(state.position, value),
      set(config.toValue, dest),
      startClock(clock)
    ]),
    spring(clock, state, config),
    cond(state.finished, stopClock(clock)),
    state.position
  ];
```

Of course the `@reanimated` decorator might not be the best idea but I'm asking for general feedback. Thanks!

**Comment by wcandillon** [comment]
How could this be achieved technically? I have no idea about babel's capabilities in that regard.

**Comment by wokalski** [comment]
Good question! It's great to see some interest.

Babel supports all kinds of transforms. Transforming the inner block is rather simple. In the example above we have the following types of expressions:

- [`if`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel-types/index.d.ts#L180)
- [`!`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel-types/index.d.ts#L59) or [unary expression](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel-types/index.d.ts#L320)
- [Assignment](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel-types/index.d.ts#L52)
- [etc. see here for more details](https://astexplorer.net/#/gist/04c984f0cdd55be43f87e98faced6908/1b31f9c4e17e872557b54b256dab5ec83acf0aed)

The simplest babel transform is defined with a visitor which calls you when it encounters certain kind of expression/statement, and then you transform it in some way. (Check out [this](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md), [this](https://kentcdodds.com/blog/write-your-own-code-transform), [or this](https://medium.com/the-guild/this-is-how-i-build-babel-plug-ins-b0a13dcd0352)).

The only tricky part is what syntax we'd want for defining the reanimated block. In babel everything is possible, including what I suggested above but it's not actually valid syntax. I.e. [decorators](https://github.com/tc39/proposal-decorators) are only valid in certain contexts. I'm wondering if there's something nicer that could be used if we're operating outside of the valid syntax constraint anyway.

**Comment by wokalski** [comment]
We could always use a comment like:

```
// @reanimated
return () => {
}
```

**Comment by terrysahaidak** [comment]
There are several macro implementations, for example, this one: https://www.npmjs.com/package/reanimated.macro

**Comment by jakub-gonet** [comment]
Hi @wokalski,

I don't think we will officially release some plugin for babel, but we can link to those in docs.
