### ISSUE TITLE
PLEASE REPORT: Excessive number of pending callbacks: 501

### ISSUE THREAD

**Issue by maxmandia** [software-mansion/react-native-reanimated#3490]
### Description

Hi,

I keep the getting the error seen on the screenshot below. For context, I'm creating an app (IOS) where users can swipe through a number of songs to listen to the audio and comment on each song.

This error warning shows when I finish swiping on a song and load the next one. Any help would be great - my app keeps crashing on my physical device (fine on simulator) after a few swipes. Full error shown below.
![Simulator Screen Shot - iPhone 13 - 2022-08-17 at 17 38 14](https://user-images.githubusercontent.com/89795178/185253010-a397c94a-c6ce-48b1-a493-1b40415ad266.png)

### Steps to reproduce

Swipe through songs to reproduce. 

### Snack or a link to a repository

https://snack.expo.dev/@mmandia511/test-snack

### Reanimated version

2.9.1

### React Native version

0.69.1

### Platforms

iOS

### Build type

Release mode

### Device

Real device

### Device model

iphone 12 mini

### Acknowledgements

Yes

**Comment by reggie3** [comment]
I am seeing the same error as @maxmandia .  Here are my details:

Reanimated version
2.12.0

React Native version
0.70.5

Platforms
iOS simulator

**Comment by reggie3** [comment]
The issue in my case was related to background location updates resulting in many state updates.  These state updates caused one of my screens to rerender on every location update.  Decreasing the number of renders seems to have fixed the problem for me.
