### ISSUE TITLE
False positive "Multiple versions of Reanimated" because of local .yarn cache in 2.10.0

### ISSUE THREAD

**Issue by honzajerabek** [software-mansion/react-native-reanimated#3509]
### Description

Hi, I'm getting an error `Multiple versions of Reanimated were detected` on my gitlab runner environment. I'm using local `.yarn` cache in the root of the project.

**iOS:**
```
[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: [Reanimated] Multiple versions of Reanimated were detected. Only one instance of react-native-reanimated can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/troubleshooting#multiple-versions-of-reanimated-were-detected 

Conflict between: 
- /.yarn/v6/npm-react-native-reanimated-2.10.0-ed53be66bbb553b5b5e93e93ef4217c87b8c73db-integrity/node_modules/react-native-reanimated
- /node_modules/react-native-reanimated
.
```

**Android:**
```
* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> 
  Multiple versions of Reanimated were detected. Only one instance of react-native-reanimated can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/troubleshooting#multiple-versions-of-reanimated-were-detected 
  
  Conflict between: 
  - /.yarn/v6/npm-react-native-reanimated-2.10.0-ed53be66bbb553b5b5e93e93ef4217c87b8c73db-integrity/node_modules/react-native-reanimated
  - /node_modules/react-native-reanimated
  


```

My project, however, resolves to `2.10.0` only:

```
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "react-native-reanimated"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-native-reanimated@2.10.0"
info Has been hoisted to "react-native-reanimated"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "27.16MB"
info Disk size with unique dependencies: "27.36MB"
info Disk size with transitive dependencies: "32.86MB"
info Number of shared dependencies: 40
✨  Done in 0.32s.
```

Shouldn't the yarn/npm cache be excluded from the duplicities check? Or maybe it should search only in the scope of the root `node_modules` ?

### Steps to reproduce

**iOS**
1. have a project with one installation of rn-reanimated of `2.10.0`
2. rm -rf node_modules
3. yarn install --cache-folder .yarn
4. cd ios
5. pod install
6. error ❌

**Android**
1. have a project with one installation of rn-reanimated of `2.10.0`
2. rm -rf node_modules
3. yarn install --cache-folder .yarn
4. react-native run-android
5. error ❌

### Snack or a link to a repository

🤷‍♂️

### Reanimated version

2.10.0

### React Native version

0.69.4

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @honzajerabek, thanks for reporting this issue! We will investigate it.

**Comment by mjooms** [comment]
I just ran into a similar error message when updating to 2.10.0.

```
Conflict between:
- /.yarn/unplugged/react-native-reanimated-virtual-d6a84045dc/node_modules/react-native-reanimated
- /node_modules/react-native-reanimated
```

**Comment by mjooms** [comment]
Works! 

I noticed the PR is based on 3.0.0-rc.2. So I verified 3.0.0-rc.2 also gave the error. It does.

Specifying your PR:
```
    "react-native-reanimated": "https://github.com/software-mansion/react-native-reanimated#874792921f64f526899fad9c39b168458813570b",
```

makes pod install behave again.

**Comment by honzajerabek** [comment]
@tomekzaw works also for me! 🙌 thanks

**Comment by tomekzaw** [comment]
Great, thanks a lot!

**Comment by seamive** [comment]
Same error.

Should we use the custom PR link until the official patch is published?

**Comment by tomekzaw** [comment]
> Should we use the custom PR link until the official patch is published?

Sure, go ahead, but note that the PR is based on 3.0.0-rc.2.

If you use Reanimated 2.x, I recommend using [patch-package](https://www.npmjs.com/package/patch-package) (at least until we backport this PR to the 2.x branch).

**Comment by vimukthinuclei** [comment]
Try doing this. I fixed the issue from these steps.

https://docs.swmansion.com/react-native-reanimated/docs/next/fundamentals/troubleshooting/#:~:text=Multiple%20versions%20of%20Reanimated%20were%20detected%E2%80%8B&text=It%20can%20occur%20when%20some,install%20the%20same%20Native%20Module.

Cheers

**Comment by dlbnco** [comment]
Here is the patch file in case you want to apply the fix to 2.10.0:

```
patches/react-native-reanimated+2.10.0.patch
```
```diff
diff --git a/node_modules/react-native-reanimated/RNReanimated.podspec b/node_modules/react-native-reanimated/RNReanimated.podspec
index d53cb12..dbb0322 100644
--- a/node_modules/react-native-reanimated/RNReanimated.podspec
+++ b/node_modules/react-native-reanimated/RNReanimated.podspec
@@ -39,7 +39,7 @@ rescue
 end
 
 if isUserApp
-  libInstances = %x[find ../../ -name "package.json" | grep "/react-native-reanimated/package.json"]
+  libInstances = %x[find ../../ -name "package.json" | grep "/react-native-reanimated/package.json" | grep -v "/.yarn/"]
   libInstancesArray = libInstances.split("\n")
   if libInstancesArray.length() > 1
     parsedLocation = ''
diff --git a/node_modules/react-native-reanimated/android/build.gradle b/node_modules/react-native-reanimated/android/build.gradle
index 6b5e3fc..47e44f9 100644
--- a/node_modules/react-native-reanimated/android/build.gradle
+++ b/node_modules/react-native-reanimated/android/build.gradle
@@ -116,7 +116,7 @@ if (CLIENT_SIDE_BUILD) {
     List<Path> paths = Files.find(
             Paths.get(rootDir.parent),
             Integer.MAX_VALUE,
-            {path, fileAttributes -> path.toString().endsWith("/react-native-reanimated/package.json") }
+            { path, basicFileAttributes -> path.toString().endsWith("/react-native-reanimated/package.json") && !path.toString().contains("/.yarn/") }
     ).toArray()
 
     String parsedLocation = ""
```

**Comment by dmitrymaslov99** [comment]
> Here is the patch file in case you want to apply the fix to 2.10.0:
> 
> ```
> patches/react-native-reanimated+2.10.0.patch
> ```
> 
> ```diff
> diff --git a/node_modules/react-native-reanimated/RNReanimated.podspec b/node_modules/react-native-reanimated/RNReanimated.podspec
> index d53cb12..dbb0322 100644
> --- a/node_modules/react-native-reanimated/RNReanimated.podspec
> +++ b/node_modules/react-native-reanimated/RNReanimated.podspec
> @@ -39,7 +39,7 @@ rescue
>  end
>  
>  if isUserApp
> -  libInstances = %x[find ../../ -name "package.json" | grep "/react-native-reanimated/package.json"]
> +  libInstances = %x[find ../../ -name "package.json" | grep "/react-native-reanimated/package.json" | grep -v "/.yarn/"]
>    libInstancesArray = libInstances.split("\n")
>    if libInstancesArray.length() > 1
>      parsedLocation = ''
> diff --git a/node_modules/react-native-reanimated/android/build.gradle b/node_modules/react-native-reanimated/android/build.gradle
> index 6b5e3fc..47e44f9 100644
> --- a/node_modules/react-native-reanimated/android/build.gradle
> +++ b/node_modules/react-native-reanimated/android/build.gradle
> @@ -116,7 +116,7 @@ if (CLIENT_SIDE_BUILD) {
>      List<Path> paths = Files.find(
>              Paths.get(rootDir.parent),
>              Integer.MAX_VALUE,
> -            {path, fileAttributes -> path.toString().endsWith("/react-native-reanimated/package.json") }
> +            { path, basicFileAttributes -> path.toString().endsWith("/react-native-reanimated/package.json") && !path.toString().contains("/.yarn/") }
>      ).toArray()
>  
>      String parsedLocation = ""
> ```

How can this be applied?

**Comment by tomekzaw** [comment]
Hey, upgrade to 2.12.0 and the issue will be gone.

**Comment by dmitrymaslov99** [comment]
I have this error reproduced on 2.12.0. I was able to fix it by installing the version
`yarn add react-native-reanimated@3.0.0-rc.2`

**Comment by tomekzaw** [comment]
@dmitrymaslov99 Then maybe you have two versions of Reanimated installed indeed...

**Comment by dmitrymaslov99** [comment]
No, no, I've double-checked it a few times.

**Comment by Slapbox** [comment]
> Hey, upgrade to 2.12.0 and the issue will be gone.

Nope. The issue only started for us with `2.12.0` - although other dependencies also changed. Something about `react-native-reanimated` causes `yarn` to install it into two places with a monorepo, in very particular circumstances.

Specifically, when `@babel/core` is listed as a `devDependencies` in our subpackage, then the `[root]/node_modules` and the `[root]/packages/[package-name]/node_modules` both will contain `react-native-reanimated` - even if we specify it in `nohoist`.

Any ideas? We're experiencing this due to a bug in Yarn, I guess, but I can't find any way around it with Expo because `eas prebuild` forcibly add the problematic `devDependency` and subsequently `react-native-reanimated` will be installed in two places.

**Comment by justblender** [comment]
@Slapbox, where exactly do you mean to add `@babel/core`? 

Let's say I've got Reanimated in two places - `apps/expo` and `packages/app`. `apps/expo` already includes `@babel/core` as a dev dependency, so where are you supposed to add another dependency?

**Comment by ahmedfouad01099** [comment]
while I'm trying to install pods using arch -x86_64 pod install command this error occurs:

[!] Failed to load 'RNReanimated' podspec: 
[!] Invalid `RNReanimated.podspec` file: [react-native-reanimated] Multiple versions of Reanimated were detected. Only one instance of react-native-reanimated can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/troubleshooting#multiple-versions-of-reanimated-were-detected 

Conflict between: 
- /Users/ahmedfouad/Documents/UD-Almería/mobile/testing-github1/node_modules/react-native-reanimated
- /Users/ahmedfouad/Documents/UD-Almería/mobile/testing-github1/node_modules/react-native-reanimated
.

 #  from /Users/ahmedfouad/Documents/UD-Almería/mobile/testing-github1/node_modules/react-native-reanimated/RNReanimated.podspec:6
 #  -------------------------------------------
 #  config = find_config()
 >  assert_no_multiple_instances(config)
 #  assert_no_reanimated2_with_new_architecture(reanimated_package_json)
 #  -------------------------------------------
 
 any ideas for a solution?

**Comment by gpawlik** [comment]
@Slapbox Have you manually added `@babel/core` to `devDependencies` or `[root]/packages.json` or `[root]/packages/[package-name]/packages.json` ?

**Comment by Slapbox** [comment]
We already had it in `[root]/packages.json` and so we added it to `[root]/packages/[package-name]/packages.json` to match the root level version - otherwise Expo may add a non-matching version, which then leads to react-native-reanimated not being hoisted, if I recall correctly.

**Comment by gpawlik** [comment]
Thanks! In my case I was needing `react-native-reanimated` to not be hoisted, as I have a patch applied. What worked for me was listing the other libraries that were depending on `react-native-reanimated` in the `nohoist` section.
```    
"nohoist": [
  "**/react-native-reanimated",
  "**/react-native-reanimated-carousel",
  "**/@gorhom/bottom-sheet"
]
```
