### ISSUE TITLE
CMake 3.24.1 not supported

### ISSUE THREAD

**Issue by xgenem** [software-mansion/react-native-reanimated#3516]
### Description

In Ubuntu I get the following errors when building.

```
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1301] - CMake '3.24.1' found in PATH did not satisfy requested version.
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1301] - CMake '3.24.1' found in PATH did not satisfy requested version.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> [CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
```

### Steps to reproduce

1. add react-native-reanimated to project
2. build
3. observe result

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

2.9.0

### React Native version

0.69.0

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

PIXEL 3A

### Acknowledgements

Yes

**Comment by jpaas** [comment]
I ran into this too. Strangely though it happened when I upgraded to 2.10. Rolling back to 2.9 made it go away.

**Comment by xgenem** [comment]
@jpaas It went away after I downgraded CMake to 3.18.1 but I had to go through lots of troubles to get there.

**Comment by chungtvdev** [comment]
> @jpaas It went away after I downgraded CMake to 3.18.1 but I had to go through lots of troubles to get there.
Hi, Could you share the way to fix problem?
