### ISSUE TITLE
 Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by zaffy88** [software-mansion/react-native-reanimated#3518]
### Description

<img width="1398" alt="截屏2022-08-25 下午8 50 03" src="https://user-images.githubusercontent.com/91537571/186671406-90311f28-c5c0-46bc-ac88-9ea26cac9516.png">

### Steps to reproduce

1.upgrade react-native-reanimated version from 2.4.1 to 2.9.1, react native from 0.67.3 to 0.69.4
2.npm install
3.npm start -- --reset-cache
4.error in node terminal

### Snack or a link to a repository

no link

### Reanimated version

2.9.1

### React Native version

0.69.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

小米10s

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @zaffy88, thanks for submitting this report.

This looks like a build or config issue.

Did you remember to build the app after upgrade with `yarn react-native run-android`, `cd android && ./gradlew assembleDebug` or using Android Studio?

**Comment by zaffy88** [comment]
> cd android && ./gradlew assembleDebug

thanks , no problem now

**Comment by dreadlocker** [comment]
Hi, i ran this command
`****`
