### ISSUE TITLE
[iOS] Can't build with the new architecture and Expo

### ISSUE THREAD

**Issue by TomCorvus** [software-mansion/react-native-reanimated#3522]
### Description

Hi 👋

I have an error when I try to build iOS app with the new architecture enabled in expo bare workflow environment.

```
/Users/tom/Documents/Laboratory/RNANewArchitecture/ios/Pods/Headers/Public/hermes-engine/hermes/hermes.h:11:10: 'exception' file not found
/Users/tom/Documents/Laboratory/RNANewArchitecture/ios/Pods/Headers/Private/React-bridging/react/bridging/react/bridging/LongLivedObject.h:10:10: 'memory' file not found
/Users/tom/Documents/Laboratory/RNANewArchitecture/node_modules/react-native-reanimated/ios/REAEventDispatcher.h:2:9: Could not build module 'React'
```

If I remove react-native-reanimated, it's working.

Thanks

### Steps to reproduce

1. `npx create-expo-app my-app`
2. `expo eject`
3. `yarn add react-native-reanimated@next`
4. `RCT_NEW_ARCH_ENABLED=1 pod install` in iOS folder
5. `expo run:ios`

### Snack or a link to a repository

https://github.com/TomCorvus/RNANewArchitecture

### Reanimated version

3.0.0-rc.2

### React Native version

0.69.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 13 (iOS 15.5)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, Expo does not support Fabric yet, see https://github.com/software-mansion/react-native-reanimated/issues/3466#issuecomment-1224034652.

**Comment by TomCorvus** [comment]
Oh, my bad. 
I thought it was supported since I was able to build the app without react-native-reanimated and new architecture enabled.
Thanks for your reply.
