### ISSUE TITLE
React screens not working in iOS

### ISSUE THREAD

**Issue by sakshiGoel26** [software-mansion/react-native-reanimated#3527]
### Description

Getting following error:

1.  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[19], "@gorhom/bottom-sheet").BottomSheetModalProvider')

2.  Error: Requiring module "node_modules/@gorhom/bottom-sheet/src/index.ts", which threw an exception: TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions') 

3.  TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions') 

### Steps to reproduce

Installed v4.4.3, and when trying to load react screens from native iOS application following errors occur:

![Simulator Screen Shot - iPhone 13 mini - 2022-08-30 at 13 38 15](https://user-images.githubusercontent.com/14308339/187416396-169fd00e-4a5e-43e2-9970-21774d9c7d83.png)
![Simulator Screen Shot - iPhone 13 mini - 2022-08-30 at 16 09 29](https://user-images.githubusercontent.com/14308339/187416425-cc0b9b55-2f09-417a-b76e-5c09406e93f7.png)
![Simulator Screen Shot - iPhone 13 mini - 2022-08-30 at 16 09 36](https://user-images.githubusercontent.com/14308339/187416448-f3965a86-cb87-4f90-b8f2-98daf2bf7a76.png)

### Snack or a link to a repository

nil

### Reanimated version

2.8.0

### React Native version

0.68.2

### Platforms

iOS

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by sakshiGoel26** [comment]
I wil try to create a repo for same and share it.

**Comment by williamsilveira45** [comment]
@sakshiGoel26 did you solve it? if yes, how =(?
