### ISSUE TITLE
Simple app crashes on reload on iOS with Fabric enabled

### ISSUE THREAD

**Issue by tomekzaw** [software-mansion/react-native-reanimated#3530]
### Description

When reloading a simple app with Fabric enabled on iOS, the app crashes in one of the following ways:

Option 1:
<img width="1512" alt="Zrzut ekranu 2022-08-31 o 10 09 46" src="https://user-images.githubusercontent.com/20516055/187627226-3c926ceb-cb64-48dd-8c7d-82d51066c9d3.png">
Option 2:
<img width="1512" alt="Zrzut ekranu 2022-08-31 o 09 57 35" src="https://user-images.githubusercontent.com/20516055/187627022-b8e21742-f3a2-42bb-8cc1-f4046c5c8910.png">
Option 3:
<img width="1512" alt="Zrzut ekranu 2022-08-31 o 09 59 15" src="https://user-images.githubusercontent.com/20516055/187627056-7d43862d-6d48-4c63-822b-986e3634062b.png">

### Steps to reproduce

1. Clone repository
2. Install node_modules and Pods
3. Paste the following code to `FabricExample/App.tsx`:
```tsx
import { Text, View } from 'react-native';

import React from 'react';
import { useSharedValue } from 'react-native-reanimated';

export default function App() {
  useSharedValue(42); // comment out this line and the crash is gone!

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>OK</Text>
    </View>
  );
}
```
4. Build FabricExample for iOS
5. Launch the app on iOS simulator
6. Reload the app by clicking `r` in the simulator

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/commit/acf7429068c4f801eef41267c2a94b5515ec4ff8

### Reanimated version

3.0.0-rc.2

### React Native version

0.70.0-rc.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 12 Pro (iOS 15.5)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Looks like it works on 559a842ca88cfc88a7547bc0045bec70f24b4826

**Comment by szydlovsky** [comment]
Doesn't happen anymore 🥳
