### ISSUE TITLE
Task `react-native-reanimated:generateJsonModelDebug` fails on Windows due to CMake

### ISSUE THREAD

**Issue by Quintis1212** [software-mansion/react-native-reanimated#3533]
### Description

I created a new project with npx react-native init with react-native version 0.68.0, then I installed react-native-reanimated and tried to build the project. But I had an error:

```
* What went wrong:
Execution failed for task ':react-native-reanimated:generateJsonModelDebug'.
> exception while building Json A problem occurred starting process 'command 'C:\Users\29416\AppData\Local\Android\sdk\cmake\3.18.1-2\bin\cmake.exe''
```

### Steps to reproduce

1) Start  new project with npx react-native init AwesomeProject --version 0.68.0
2) Install react-native-reanimated
3) Build the project

I tried gradlew clean command

### Snack or a link to a repository

n/a

### Reanimated version

2.10.0

### React Native version

 0.68.0

### Platforms

Android

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Acknowledgements

Yes

**Comment by Quintis1212** [comment]
How to reproduce failed build  in snack ?

**Comment by Guccieii** [comment]
Had same issue. Maybe related to this.

#3516

**Comment by Kwasow** [comment]
Hey @Quintis1212, have you tried building the app again after it failed (without cleaning)? It sometimes makes the error go away. If not, then please try it.

If the error is still there, then please provide the full error message, so we can see what's wrong.

**Comment by Quintis1212** [comment]
@Kwasow  Hi . Yes I tried building the app again but still have an error

**Comment by Kwasow** [comment]
Then please provide the full error message, as it is cut off in the original post.

**Comment by Quintis1212** [comment]
@Kwasow  Here it is: 
```
> Task :react-native-reanimated:generateJsonModelDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
418 actionable tasks: 62 executed, 356 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:generateJsonModelDebug'.
> exception while building Json A problem occurred starting process 'command 'C:\Users\29416\AppData\Local\Android\sdk\cmake\3.18.1-2\bin\cmake.exe''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 37s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:generateJsonModelDebug'.
> exception while building Json A problem occurred starting process 'command 'C:\Users\29416\AppData\Local\Android\sdk\cmake\3.18.1-2\bin\cmake.exe''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 37s

    at makeError (C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
```

**Comment by Kwasow** [comment]
There seems to be an issue running `cmake.exe`. Are you sure you have sufficient permissions to run the command? Try running it from the command prompt manually (ex. with the `help` parameter) to see if it works.

**Comment by Quintis1212** [comment]
@Kwasow Please give me more details, I use win 10 powershell , how I can run cmake.exe in terminal ?
Do you try to build react-native 0.680 with reanimated lib ?

**Comment by Quintis1212** [comment]
@Kwasow I always use powershell  as admin

**Comment by Kwasow** [comment]
You should be able to run it like this:

```
cd C:\Users\29416\AppData\Local\Android\sdk\cmake\3.18.1-2\bin
.\cmake.exe --help
```

but I'm not very familiar with Windows, so this might be wrong.

**Comment by Quintis1212** [comment]
@Kwasow  I tried cmake.dir config but it did not help

**Comment by Quintis1212** [comment]
@Kwasow  Please , can you reproduce this bug with  react-native 0.68.0  and reanimated lib ? If build will be success please share your config : node js version , android studio version ...

**Comment by Kwasow** [comment]
I'm unable to reproduce the issue in my working environment. Please make sure that the file that gradle tries to execute exists and that it is executable as I mentioned earlier.

**Comment by Quintis1212** [comment]
@Kwasow  could you please share your  your config : node js version , android studio version ... ?

**Comment by muneeb-urr-rehman** [comment]
react-native-reanimated:configureCMakeDebug FAILED i am also getting this error how can i solve it

**Comment by Kwasow** [comment]
Hey @muneeb-urr-rehman, the description of this issue doesn't actually match the actual issue, because it's not about the failed `react-native-reanimated:configureCMakeDebug` task. I'll update the description

**Comment by NOORULAJAM** [comment]
facing same issue...Anyone know how to resolve it:-(

**Comment by loyalty-thameem** [comment]
> after gradlew clean :
> 
> ```
> > Task :react-native-reanimated:generateJsonModelDebug FAILED
> w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
> 414 actionable tasks: 414 executed
> Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
> Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
> Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-android-location-enabler\android\src\main\java\com\heanoria\library\reactnative\locationenabler\RNAndroidLocationEnablerModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\Camera2.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\geolocation\android\src\main\java\com\reactnativecommunity\geolocation\GeolocationModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-google-signin\android\src\main\java\co\apptailor\googlesignin\RNGoogleSigninModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-google-signin\android\src\main\java\co\apptailor\googlesignin\RNGoogleSigninModule.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-firebase\crashlytics\android\src\main\java\io\invertase\firebase\crashlytics\ReactNativeFirebaseCrashlyticsModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@invertase\react-native-apple-authentication\android\src\main\java\com\RNAppleAuthentication\AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-share\android\src\main\java\cl\json\RNSharePathUtil.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\VirtualView.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-video\android\src\main\java\com\brentvatne\react\ReactVideoViewManager.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-reanimated:generateJsonModelDebug'.
> > exception while building Json A problem occurred starting process 'command 'C:\Users\29416\AppData\Local\Android\sdk\cmake\3.18.1-2\bin\cmake.exe''
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 1s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
> Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
> Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
> Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-android-location-enabler\android\src\main\java\com\heanoria\library\reactnative\locationenabler\RNAndroidLocationEnablerModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\Camera2.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\geolocation\android\src\main\java\com\reactnativecommunity\geolocation\GeolocationModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-google-signin\android\src\main\java\co\apptailor\googlesignin\RNGoogleSigninModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-google-signin\android\src\main\java\co\apptailor\googlesignin\RNGoogleSigninModule.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-firebase\crashlytics\android\src\main\java\io\invertase\firebase\crashlytics\ReactNativeFirebaseCrashlyticsModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@invertase\react-native-apple-authentication\android\src\main\java\com\RNAppleAuthentication\AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-share\android\src\main\java\cl\json\RNSharePathUtil.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\VirtualView.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-video\android\src\main\java\com\brentvatne\react\ReactVideoViewManager.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\Users\29416\Desktop\rn\12c-react-native\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-reanimated:generateJsonModelDebug'.
> > exception while building Json A problem occurred starting process 'command 'C:\Users\29416\AppData\Local\Android\sdk\cmake\3.18.1-2\bin\cmake.exe''
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 1s
> 
>     at makeError (C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
>     at C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async runOnAllDevices (C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
>     at async Command.handleAction (C:\Users\29416\Desktop\rn\12c-react-native\node_modules\@react-native-community\cli\build\index.js:192:9)
> info Run CLI with --verbose flag for more details.
> ```


**_Do you find any solution?_**

**Comment by loyalty-thameem** [comment]
**I have same issue...**

**Comment by swatantragoswami09** [comment]
I am also getting the same error please help me 
![image](https://user-images.githubusercontent.com/54662673/195415022-079bfb43-e5c1-43fa-9e9d-5d4bb301ce8c.png)

![image](https://user-images.githubusercontent.com/54662673/195414555-f9b67081-8e9c-4223-9f9d-8600270fc73a.png)

**Comment by Ranjithramesh67** [comment]
Try to reinstall  react-native-reanimated to latest version, this solved the issue for me
using this command to do that 
`npm uninstall react-native-reanimated && npm install react-native-reanimated@latest`

**Comment by fujikazu** [comment]
This worked for me

yarn remove react-native-reanimated 
yarn add react-native-reanimated@latest
