### ISSUE TITLE
3.0.0-rc.2 Android - TypeError: Cannot read property 'stateNode' of undefined

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-reanimated#3534]
### Description

I'm attempting to use Fabric with 3.0.0-rc.2. iOS works fine however on Android I get the following attempting to render an Animated.View.

```
 ERROR  TypeError: Cannot read property 'stateNode' of undefined

This error is located at:
    in AnimatedComponent(View) (at createAnimatedComponent.tsx:533)
```

### Steps to reproduce

Render an ``<Animated.View/>``

### Snack or a link to a repository

https://github.com/kyle-ssg/reanimated-reproduction

### Reanimated version

3.0.0-rc.2

### React Native version

0.69.5 (I can confirm this also happens on RN 0.70.rc-4)

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kyle-ssg** [comment]
I can confirm this also happens on RN 0.70.rc-4

**Comment by Chenbao2021** [comment]
Same problem

**Comment by khushal87** [comment]
Facing the same problem with `0.70.1` while opting in the new arch.

**Comment by khushal87** [comment]
Hey @kyle-ssg, any chance you are using @gorhom's bottom-sheet, too?

**Comment by khushal87** [comment]
Hey @kyle-ssg, any chance you are using @gorhom's bottom-sheet, too?

**Comment by kyle-ssg** [comment]
Hmm, I was but I could replicate this by rendering a plain reanimated view.

**Comment by keshav-raj** [comment]
Facing the same issue on new Archtecture

**Comment by keshav-raj** [comment]
@kyle-ssg Did you find any workaround am also facing the same issue. I am using "@react-navigation/drawer": "^6.5.0".
I'm facing this issue only if I add Drawer scenes

**Comment by anirudhdream11** [comment]
Any solution till now?
I am facing same issue for Android only, However ios looks fine.

**Comment by thanggggg1** [comment]
> Any solution till now?
> I am facing same issue for Android only with new architecture on RN 0.70.1, However ios looks fine.

Did you find the solution

**Comment by ugurdalkiran** [comment]
The same problem continues.

**Comment by kyle-ssg** [comment]
Yeah just to confirm, haven't found a workaround for this.

**Comment by anirudhdream11** [comment]
> > Any solution till now?
> > I am facing same issue for Android only with new architecture on RN 0.70.1, However ios looks fine.
> 
> Did you find the solution

It was worked for me when I upgraded reanimated to "3.0.0-rc.3"

Combination of below dependencies was worked for me :
    "react-native": "0.70.1",
    "react-native-gradle-plugin": "0.70.1",
    "react-native-reanimated": "3.0.0-rc.3",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "3.17.0",

**Comment by tomekzaw** [comment]
Hey @kyle-ssg, thanks for submitting this issue and marking other issues as duplicate.

Based on the repro you have provided, I was able to successfully reproduce the issue on app launch.

We will investigate this error further.

**Comment by tomekzaw** [comment]
The root cause of the issue is the fact that Reanimated uses Fabric mode while the app still runs on Paper (old renderer):

![](https://user-images.githubusercontent.com/20516055/202200330-e0636cb5-ac0b-46d1-a4ca-45c603a2d689.png)

As you can see, there's no `"fabric":true` in the logs, meaning that your app still runs on the old architecture.

Based on the value of `newArchEnabled` property, Reanimated correctly detects that Fabric is enabled and sets `global._IS_FABRIC` to `true` which causes Reanimated to use Fabric implementation (e.g. to obtain ShadowNodeWrapper from `stateNode` field, which is undefined on Paper).

The problem is that for some reason React Native doesn't enable Fabric. This may be because your app is totally out-of-sync with React Native 0.69.5 template. In particular, the Android app still runs on Paper because the following method is missing:

```java
    @Override
    protected ReactRootView createRootView() {
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }
```

I've replaced `MainActivity.java` in your project with the one from RN 0.69.5 app template (see [here](https://github.com/facebook/react-native/blob/v0.69.5/template/android/app/src/main/java/com/helloworld/MainActivity.java)), changed the Java package and app name. The app now runs on Fabric and the issue is gone:

![](https://user-images.githubusercontent.com/20516055/202207849-492cb394-7108-4fb0-8dc2-0d43c1b8baa8.png)

Finally, many of the third-party libraries that you use are not Fabric-compatible yet, for instance:
* react-native-linear-gradient
* react-native-modal-datetime-picker
* react-native-keyboard-aware-scroll-view
* react-native-webview

Closing this issue as it's not a bug in Reanimated, but a config issue on your side.

**Comment by ugurdalkiran** [comment]
With Fabric enabled, the signed APK app crashes on first launch. That's why I disable Fabric.

**Comment by tomekzaw** [comment]
@ugurdalkiran @fgagneten
1. Do you have Fabric (new architecture) enabled?
2. If yes, do you have `{"fabric":true}` in Metro bundler console?
3. Can you replicate the issue on a fresh React Native app initialized with `npx react-native init MyApp --version 0.x.y`?

**Comment by kyle-ssg** [comment]
@tomekzaw Thanks so much for the explaination and the ``"fabric":true`` tip!

**Comment by fgagneten** [comment]
@tomekzaw 
1. yes, I do (android)
2. Yes, I do: ` Running "myapp" with {"fabric":true,"initialProps":{"concurrentRoot":true},"rootTag":1}`
3. I couldn't replicate it due to the number of dependencies I have right now. I will try again tonight

**Comment by kyle-ssg** [comment]
Since yesterday I got my setup working (iOS and android) with quite a few dependencies, including @gorhom's bottom sheet, though from this I learnt I won't switch to the new architecture for a while, seems too risky. Lottie is a notable module that doesn't work at the moment in addition to the list above. A few things:

- If you're coming from a project that has gone through many version upgrades, https://github.com/software-mansion/react-native-reanimated/tree/main/FabricExample is a really good example to look at to compare with your own, in particular the AppDelegate.mm and build.gradle's 
- There are lots of red herring errors due to cache when opting in and out, removing iOS/Android build folders and clearing all the caches is a good

Here's a list of dependencies that currently work for me 

```
     react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    
        "react-native-gesture-handler": "2.8.0",
        "react-native-reanimated": "3.0.0-rc.3",
         "react-native-safe-area-context": "^4.4.1",
         "react-native-screens": "^3.18.0",
         "react-native-svg": "^13.3.0",
         "react-native-date-picker": "^4.2.6",

```

In order to work, this requires this in react-native-config.js

```
    '@react-native-community/datetimepicker': {
      platforms: {
        android: {
          androidMkPath: null,
          cmakeListsPath: null,
          componentDescriptors: null,
          libraryName: null,
        },
      },
    },
```

These don't work
 - react-native-linear-gradient <2.6.2 (it won't crash the app but it won't display). It looks like this is a replacement though haven't tried it yet https://github.com/fyndx/react-native-gradient
 - react-native-lottie: This will crash the app on attempting to render an animation view, it looks like there's a promising PR https://github.com/lottie-react-native/lottie-react-native/pull/910
- react-native-modal-datetime-picker: playing around with it, I feel like this can be replaced with the bottomsheet + @react-native-community/datetimepicker
- react-native-webview: I imagine like Lottie this would be quite a bit deal, this PR looks promising https://github.com/react-native-webview/react-native-webview/pull/2686

**Comment by khushal87** [comment]
Hey @kyle-ssg do you recommend not upgrading to new arch with the bottom-sheet version 4.4.5?

**Comment by prince-sugarfit** [comment]
Is there any way I can use it with newArchitecture = true & fabric = false?

**Comment by tomekzaw** [comment]
@prince-sugarfit nope, we don't support this currently (and honestly we don't plan to).

**Comment by LadislavBohm** [comment]
If someone is running into similar issue (for me it was property 'version' of undefined) my solution was to modify properly metro.config.js. I had react-native-svg-transformer included in project as well and you need to follow the new way to integrate it on it's official github page.

**Comment by hssdiv** [comment]
> If someone is running into similar issue (for me it was property 'version' of undefined) my solution was to modify properly metro.config.js. I had react-native-svg-transformer included in project as well and you need to follow the new way to integrate it on it's official github page.

Thanks for the tip, had that in expo-app and I simply needed to set sourceExts the way official documentation says it should be set (same way as assetExts)
[https://docs.expo.dev/guides/customizing-metro/](https://docs.expo.dev/guides/customizing-metro/)

**Comment by TassainRasool** [comment]
react native version == 0.68.5
on updating the reanimated from 2.17.0 (RNReanimated (2.17.0)) to any higher version I am facing many issues with it.
some common issues are showing undefined methods which are working fine with the 1.17.0 version.


<img width="683" alt="logs" src="https://github.com/software-mansion/react-native-reanimated/assets/72487520/35169456-b046-43db-b46f-30a808b62ec0">

any suggestions or sol?

**Comment by ShamraizRajpoot1** [comment]
Reset cache it's working for me
 npm start -- --reset-cache
