### ISSUE TITLE
interpolate API is undefined.

### ISSUE THREAD

**Issue by jdzamface** [software-mansion/react-native-reanimated#3542]
### Description

`import { interpolate } from 'react-native-reanimated'`
interpolate is undefined.

react-native-reanimated: 3.0.0-rc2
react-native: 0.69.5
new architecture enalbed
hermes enabled
react native without expo

### Steps to reproduce

1. import interpolate from 'react-native-reanimated'
2. use interpolate
3. crash (undefined is not function)

### Snack or a link to a repository

none

### Reanimated version

3.0.0-rc2

### React Native version

0.69.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by graszka22** [comment]
It works for me on `3.0.0-rc.9`. Make sure you set up your project correctly (add babel plugin etc https://docs.swmansion.com/react-native-reanimated/docs/next/fundamentals/installation), if problem persists provide link to the project that reproduces the issue.
