### ISSUE TITLE
Animation is not rendering on android emulator

### ISSUE THREAD

**Issue by iandev096** [software-mansion/react-native-reanimated#3544]
### Description

I am working on a progress loader component. The animation works on ios, but it doesn't work on android. I have tried it on a couple of different emulators as well as as actual devices, the the animation just does not render
<img width="504" alt="Screen Shot 2022-09-05 at 11 18 51 AM" src="https://user-images.githubusercontent.com/68153591/188437046-b1a38b86-1558-4b5e-8818-995d27c2932a.png">

### Steps to reproduce

Below is the code for the whole component

```
import React, { useEffect } from "react";
import { Modal, StyleSheet, Text, View } from "react-native";
import Animated, {
  useAnimatedProps,
  useSharedValue,
  withRepeat,
  withTiming,
} from "react-native-reanimated";
import Svg, { Circle } from "react-native-svg";


const CIRCLE_LENGTH = 201; // 2 * PI * r
const RADIUS = CIRCLE_LENGTH / (2 * Math.PI); // C / (2 * PI)
const STROKE_LENGTH = 4;

const AnimatedCircle = Animated.createAnimatedComponent(Circle);

export default function App() {
  const progress = useSharedValue(0);

  useEffect(() => {
    progress.value = withRepeat(withTiming(1, { duration: 5000 }), 100, true);
  }, [progress]);

  const animatedProps = useAnimatedProps(() => ({
    strokeDashoffset: CIRCLE_LENGTH * (1 - progress.value),
    strokeDasharray: CIRCLE_LENGTH,
  }));
  const baseCircleProps = {
    cx: RADIUS + STROKE_LENGTH / 2,
    cy: RADIUS + STROKE_LENGTH / 2,
    r: RADIUS,
    strokeWidth: STROKE_LENGTH,
    stroke: "#EEEEEE",
    // strokeLinecap: "round",
  };
  const baseAnimatedCircleProps = {
    ...baseCircleProps,
    stroke: "#161925",
    transform: `rotate(${-90},${RADIUS + STROKE_LENGTH / 2},${
      RADIUS + STROKE_LENGTH / 2
    })`,
  };

  return (
    <Modal animationType="fade" transparent={true} visible={true}>
      <View style={styles.background}>
        <View style={styles.progressContainer}>
          <Svg>
            <Circle {...baseCircleProps} />
            <AnimatedCircle
              animatedProps={animatedProps}
              {...baseAnimatedCircleProps}
            />
          </Svg>
          <Text numberOfLines={1} style={styles.loadingText}>
            Signing in...
          </Text>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  background: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  progressContainer: {
    width: RADIUS * 2 + STROKE_LENGTH,
    height: RADIUS * 2 + STROKE_LENGTH,
  },
  loadingText: {
    lineHeight: 20,
    fontSize: 16,
    textAlign: "center",
    marginTop: 27,
    overflow: "visible",
  },
});

```

### Snack or a link to a repository

https://snack.expo.dev/@ianyimiah/reanimated-circular-progress-loader

### Reanimated version

2.9.1

### React Native version

0.69.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Build type

Debug mode

### Device model

Pixel 4a

### Acknowledgements

Yes

**Comment by IvaTsu** [comment]
Indeed, very interesting case, when reproducing it locally, I found out that the circle is being filled on Android once you hit hot-reload stuff, I mean, each render iteration adds a piece of the circle (but it is not going back that way though).

See below screenshots I have taken during hitting `cmd + S`. Hope it will help you to troubleshout this, unfortunately I have no idea what might be the case.

![photo_2022-09-05 15 16 46](https://user-images.githubusercontent.com/7797773/188458773-3952a1db-6554-4934-b158-0409010ef272.jpeg)
![photo_2022-09-05 15 16 52](https://user-images.githubusercontent.com/7797773/188458803-c7111284-1e1e-451d-83f5-06b622bb861f.jpeg)
![photo_2022-09-05 15 16 55](https://user-images.githubusercontent.com/7797773/188458824-8cb3ade1-737b-4f53-bb2b-d023c58fecc8.jpeg)

**Comment by lennartschoch** [comment]
I think I might face a similar issue - I have an animation that works flawlessly on iOS as well as on modern Android phones, but it fails to load on slower Android devices. 
Also, forcing the screen to re-render (like you did by triggering the hot reload) seems to do the trick for me. I did this by incrementing a state variable (inside of the parent component of the animation) with an interval.

**Comment by iandev096** [comment]
@lennartschoch That is interesting. I am starting to think this issue with performance may have to do with react-native-svg as well. I tried animating a regular View just above the progress loader using the same sharedValue and it worked fine. So this issue seems to only come up in the case of the react-native-svg components.

**Comment by Latropos** [comment]
Hi, your issue is luckily easy to fix:
1. Please wrap this in array: `strokeDasharray: CIRCLE_LENGTH` ➡️ `strokeDasharray: [CIRCLE_LENGTH]`
2. Since `strokeDasharray: [CIRCLE_LENGTH]` is not animating at all move it inside `baseAnimatedCircleProps` for better performance
3. Voila!
