### ISSUE TITLE
Unsupported ABI fro NDK r19+: ARMEABI

### ISSUE THREAD

**Issue by phamqthanh** [software-mansion/react-native-reanimated#3565]
### Description

I have a problem when I try to build release. I can build my project when using Mac Intel, but this happened when i try to build on Mac M1

![ảnh](https://user-images.githubusercontent.com/93968819/189628733-9b85a11c-1a10-4805-bc6a-ac8e85ec9fec.png)

### Steps to reproduce

Basically I just install package into project.

1. yarn add react-native-reanimated@^2.10.0
2. yarn start
3. yarn react-native run-android

### Snack or a link to a repository

https://

### Reanimated version

2.10.0

### React Native version

0.68.2

### Platforms

Android

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, can you try `armeabi-v7a` instead of `ARMEABI`?

**Comment by phamqthanh** [comment]
I didn't change any default settings, this is default `reactNativeArchitectures` in properties.

<img width="518" alt="ảnh" src="https://user-images.githubusercontent.com/93968819/189665109-8b7b30d8-80f1-4aa3-b3b6-eb88d14fee4c.png">

I also tried this command to build, it still throw same error.
`./gradlew :app:assembleDebug -PreactNativeArchitectures=armeabi-v7a`

This error also happens when i install `expo` package.

**Comment by tomekzaw** [comment]
Can you try with NDK 21.4.7075529? You can install it via SDK Manager in Android Studio.

**Comment by tatranfonos** [comment]
I already met it 2 weeks ago, just delete all android ndk and reinstall. Hope will help you.

**Comment by phamqthanh** [comment]
> I already met it 2 weeks ago, just delete all android ndk and reinstall. Hope will help you.

It workded, thanks for your help. 👍

**Comment by StephenChips** [comment]
I met the same error too, how can I delete all android ndk?
