### ISSUE TITLE
useAnimatedKeyboard native iOS crash on keyboardDidHide

### ISSUE THREAD

**Issue by MichaelDanielTom** [software-mansion/react-native-reanimated#3568]
### Description

When using the `useAnimatedKeyboard` hook, there are occasional crashes when the keyboard is shown/hidden on iOS. Here is the stack objc stack and location of the error within the screenshot.

![image](https://user-images.githubusercontent.com/5520838/189823336-c7fced2c-7c3a-41d3-9309-b4204787d2f2.png)

### Steps to reproduce

I have been having a hard time reproducing it deterministically, however anecdotally it seems to occur after the device/simulator has been on for at least a few minutes. It can happen when the keyboard is closing or opening. 

### Snack or a link to a repository

n/a

### Reanimated version

2.10.0

### React Native version

0.66.0

### Platforms

iOS

### Acknowledgements

Yes

**Comment by MingaudasVagonis** [comment]
This seems to happen quite frequently when navigating to a screen with `autoFocus` on one of the inputs enabled. Happens 1 out 5 times or so. 
<details>
<summary>Quite easy to reproduce with this simple component</summary>

```
import React, { FC, memo } from 'react';
import Animated, {
  useAnimatedKeyboard,
  useAnimatedStyle,
} from 'react-native-reanimated';

type KeyboardFillerProps = {
  offset?: number;
};

export const KeyboardFiller: FC<KeyboardFillerProps> = memo(({ offset }) => {
  const { height } = useAnimatedKeyboard();

  const placeholderStyle = useAnimatedStyle(
    () => ({
      height: height.value - (offset || 0),
    }),
    [offset],
  );

  return <Animated.View style={placeholderStyle} />;
});

KeyboardFiller.displayName = 'KeyboardFiller';
```

</details>

**Comment by gtokman** [comment]
I'm also seeing an intermittent crash. 

@MingaudasVagonis I don't think that `autoFocus` is the reason. I'm not using that prop.

**Comment by ChildishForces** [comment]
I had a similar bug, and solved it by doing the following:

```ts
const animatedStyle = useAnimatedStyle(() => ({
  transform: [{ translateY: -(keyboard?.height?.value ?? 0) })],
});
```

It appears it is possible for the value to not be a number under certain conditions. I don't know this for a fact, but doing this solved my issue based off my hunch.
