### ISSUE TITLE
Transition API not behaving Ideally.

### ISSUE THREAD

**Issue by Kida007** [software-mansion/react-native-reanimated#358]
I took a simple example for the repo examples . it is running as it should as the only component : 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22558035/62416989-78212880-b662-11e9-8e9b-ac90f09971c6.gif)

## Problem
but when I tried to use it in complex component as child , it is not behaving properly . for clear difference I Increased the animation duration to 2000ms :

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/22558035/62417076-d2bb8400-b664-11e9-912a-430c1a9fe97d.gif)

## WorkAround
Ultimately I have to convert the root Component to  Transition.View to make it work .

**Comment by wojtus7** [comment]
Hi, thanks for the feedback! 😄 
I tried to reproduce this issue but unfortunately wasn't able to do it. Can you provide some Github repo or some more info about how to reproduce it?

**Comment by Kida007** [comment]
Hey , Thanks for the concern!  
currently im busy with exams , so i wont be able to provide a repo .  
The issue is quite old and i haven't tested the Transition API on new versions.
so Im gonna close this issue , comeback soon and test it 😄 .
