### ISSUE TITLE
 Failed to notify project evaluation listener.

### ISSUE THREAD

**Issue by valn1** [software-mansion/react-native-reanimated#3587]
### Description

when running android with react-native-reanimated 2, the application throws 

`A problem occurred configuring project ':react-native-reanimated'.
> Failed to notify project evaluation listener.
   > /home/path/to/my/react-native/project/node_modules/react-native-reanimated/android/build/intermediates/cxx/ndk_locator_record_3r5a1r6h.log (Permission denied)
` 
and this warning
![image](https://user-images.githubusercontent.com/40465512/191115391-f947e317-8228-47d8-80a6-0dabf50ab19c.png)

### Steps to reproduce

run-android

### Snack or a link to a repository

https://github.com/valn1/reanimated-bug

### Reanimated version

2.10.0

### React Native version

0.70.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung galaxy s20+

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, can you remove clean build folder along with Gradle caches and then try building the app again?

**Comment by valn1** [comment]
i tried ./gradlew clean, it didnt work, ran sudo ./gradlew clean and it worked

i, then proceeded to try and run the project with sudo to see if it was some issue with file permissions, however, it threw a different error

![image](https://user-images.githubusercontent.com/40465512/191498649-916d3e4a-4c85-4db3-81b8-33ac9821084c.png)

**Comment by valn1** [comment]
i also tried with and without hermes, cleaning thhe build whenever i changed the configuration

**Comment by valn1** [comment]
https://github.com/valn1/reanimated-bug

here is a minimal repro, just run android and the two errors above will show up

**Comment by valn1** [comment]
looks like the error i am getting now is from react-native-vision camera and the previous error had to do with some weird permission issues, i couldn't reproduce that same error tho, so i am closing this issue since it doesn't happen anymore
