### ISSUE TITLE
Execution failed for task ':react-native-reanimated:unzipHermes'.

### ISSUE THREAD

**Issue by sairajKalkundre** [software-mansion/react-native-reanimated#3590]
### Description

I have upgraded react-native to 0.70.0 and also react-native-reanimated to "^3.0.0-rc.2" or "2.10.0" . While building the app on android it is failing with 

```
What went wrong:
Execution failed for task ':react-native-reanimated:unzipHermes'.
> Could not read node_modules/react-native/sdks/download/hermes.tar.gz.
   > java.io.EOFException (no error message)


```

### Steps to reproduce

1.Update react-native to 0.70.0
2.update reanimated to "^3.0.0-rc.2"

### Snack or a link to a repository

none

### Reanimated version

3.0.0-rc^2

### React Native version

0.70.0

### Platforms

Android

### Architecture

old

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, can you reinstall node_modules with `yarn --force` and then try building the app again?

**Comment by sairajKalkundre** [comment]
@tomekzaw  I did , still same.

**Comment by sairajKalkundre** [comment]
Fixed it, deleted hermes from folder and now it works.

**Comment by gulgulia17** [comment]
@sairajKalkundre what do you mean, deleted? I'm facing same issue from what path it needs to be removed?

**Comment by sairajKalkundre** [comment]
@gulgulia17 node_modules/react-native/sdks/download/**hermes.tar.gz** . I have deleted the file and ran npm run android . It automatically downloaded the proper file and it ran properly.
