### ISSUE TITLE
ninja: error: /arm64-v8a/libhermes.so', needed by /arm64-v8a/libreanimated.so

### ISSUE THREAD

**Issue by imadarif** [software-mansion/react-native-reanimated#3594]
### Description

gradlew assembleRelease

getting this error after update from 0.69 to 0.70

execution failed for task ':react-native-reanimated:buildCMakeRelWithDebInfo[arm64-v8a]'.
> Build command failed.
  Error while executing process C:\Users\ABC\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C D:\app\myapp\node_modules\react-native-reanimated\android\.cxx\RelWithDebInfo\l4546g3a\arm64-v8a reanimated}
  ninja: Entering directory `D:\app\myapp\node_modules\react-native-reanimated\android\.cxx\RelWithDebInfo\l4546g3a\arm64-v8a'   
  [0/2] Re-checking globbed directories...

  ninja: error: '../../../../build/third-party-ndk/hermes/jni/arm64-v8a/libhermes.so', needed by 'D:/app/myapp/android/build/react-native-reanimated/intermediates/cxx/RelWithDebInfo/l4546g3a/obj/arm64-v8a/libreanimated.so', missing and no known rule to make it

### Steps to reproduce

1.updated to 0.70 and added reanimated plugin 3.0.0.rc
2.just run the command gradlew assembleRelease

### Snack or a link to a repository

-

### Reanimated version

3.0.0-rc.2

### React Native version

0.70.0

### Platforms

Android

### Build type

Release mode

### Acknowledgements

Yes

**Comment by imadarif** [comment]
i have try 2.10.0 react-native-reanimated version still same error.

**Comment by imadarif** [comment]
i have enabled the newArchEnabled=true now i got this error

Task :ReactAndroid:hermes-engine:buildCMakeMinSizeRel[arm64-v8a][libhermes] FAILED
C/C++: ninja: error: 'E:/app/android/build/hermes-engine/hermes/bin/MinSizeRel/hermesc.exe', needed by 'lib/InternalBytecode/InternalBytecode.hbc', missing and no known rule to make it

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ReactAndroid:hermes-engine:buildCMakeMinSizeRel[arm64-v8a][libhermes]'.
> Build command failed.
  Error while executing process C:\Users\ImadArif\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C E:\app\node_modules\react-native\ReactAndroid\hermes-engine\.cxx\MinSizeRel\g4kh2x3g\arm64-v8a libhermes}
  ninja: Entering directory `E:\app\node_modules\react-native\ReactAndroid\hermes-engine\.cxx\MinSizeRel\g4kh2x3g\arm64-v8a'     

  ninja: error: 'E:/app/android/build/hermes-engine/hermes/bin/MinSizeRel/hermesc.exe', needed by 'lib/InternalBytecode/InternalBytecode.hbc', missing and no known rule to make it

**Comment by imadarif** [comment]
@tomekzaw

**Comment by tomekzaw** [comment]
Hey @imadarif, thanks for submitting this issue. We haven't tried building Reanimated for Fabric on Windows yet. We will investigate this issue further.

**Comment by imadarif** [comment]
any update ? anyone facing same issue ?

**Comment by tomekzaw** [comment]
Hey @nstoilov, can you check if `lib/x86/libhermes.so` exists in the .apk file?

**Comment by expouic** [comment]
I have the same issue after update the react-native-reanimated to the latest version. Current solution, rollback to the version 2.9.1

**Comment by tomekzaw** [comment]
@expouic Can you check if `lib/x86/libhermes.so` exists in the .apk file?

**Comment by expouic** [comment]
Even with version 2.9.1 and react-native version 0.68.1 I can't run the release build. Got this error:

```
com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
```
Debug versions works fine with both versions!

@tomekzaw `libhermes.so` no! But have this two `libhermes-executor-debug.so` and `libhermes-executor-release.so`
<img width="541" alt="Screenshot 2022-10-30 at 10 16 07" src="https://user-images.githubusercontent.com/1051643/198873446-2ac765e5-cf66-4e5b-b543-ceb578f5eab5.png">

**Comment by nstoilov** [comment]
> Hey @nstoilov, can you check if `lib/x86/libhermes.so` exists in the .apk file?

No, I generated and unzipped an apk, libhermes.so is not there.

**Comment by tomekzaw** [comment]
Hey, unfortunately I wasn't able to reproduce this issue. Here's what I did:

```
npx react-native@next init MyApp --version 0.70.0
cd MyApp
yarn add react-native-reanimated@2.12.0
cd android
./gradlew installRelease
```

I'm building the app on a M1 Pro. What OS are you on? @nstoilov @expouic

**Comment by nstoilov** [comment]
Mac OS 12.6, i7 processor @tomekzaw

**Comment by tomekzaw** [comment]
@nstoilov Okay, thanks. Have you tried building Reanimated with a fresh RN 0.70.0 app like I did?

**Comment by nstoilov** [comment]
@tomekzaw runs fine with a clean app...

**Comment by migueldaipre** [comment]
@tomekzaw I'm facing the same problem with 
RN 0.70.6
Hermes true
proguard enabled

Do you have any idea?

`E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.x, PID: 858
    g4.c: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libhermes-executor-debug.so" not found: needed by /data/app/~~Ns2koKqLBQX7wBUnu4tVuQ==/com.x-AIBSl2ICRWAREL01a4QKbg==/lib/arm64/libreanimated.so in namespace classloader-namespace, js engine: hermes, stack:`

I have realmjs installed and saw [this](https://github.com/realm/realm-js/issues/5186)

**Comment by krmao** [comment]
I found the key, change jdk version from 17 to 11

**Comment by ACareBell** [comment]
npm uninstall react-native-reanimated
npm install react-native-reanimated@2.9.1

use this it will work
