### ISSUE TITLE
Text opacity randomly not obeying useSharedValue

### ISSUE THREAD

**Issue by dereknelson** [software-mansion/react-native-reanimated#3607]
### Description

I have some text like this:
```
const containerStyle = useAnimatedStyle(() => {
    return {
      opacity: withTiming(sectionTextOpacity.value, { duration: 500, easing: Easing.linear }),
    }
  })
return (
        <Reanimated.View style={containerStyle}>
          <Paragraph color="#B6B4E8">{region.name}</Paragraph>
        </Reanimated.View>
)
```
where `const sectionTextOpacity = useSharedValue(0)` is passed in via props from a parent component.
Basically, it will randomly obey the opacity. It gets set to `1` the same way every time. Clicking inspect scares the elements into doing the right thing. Also, tapping elsewhere on the screen to start an interaction makes them flash being shown before they're removed from render by the back interaction.

https://user-images.githubusercontent.com/6868432/192113172-711a01db-90cb-460a-a443-9b19e098dd68.mov

### Steps to reproduce

1. click `answer`
2. tap on the left or right arm
3. witness text being invisible
4. try to touch where the text would be or turn on the element inspector
code is here: `src/screens/PainCheckIn/BodySections.tsx`

### Snack or a link to a repository

https://github.com/dereknelson/issue-demo

### Reanimated version

6.9.1

### React Native version

0.69.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

all of them

### Acknowledgements

Yes

**Comment by lukepereira** [comment]
Hey @dereknelson, I randomly stumbled on your animation while working on something similar in my public benefit app: https://www.animiapp.com/ 

Was wondering if this was released or if the code is open-sourced anywhere. I think it would be a great visualization for appraisal, interoception, and body scanning guides. Feel free to reach out to my email lukejoepereira@gmail.com
