### ISSUE TITLE
Invalid Revision: 3.18.1

### ISSUE THREAD

**Issue by nwpnkmngm** [software-mansion/react-native-reanimated#3609]
### Description

Hi, I try to start Android simulator with my project and got  build failed with error ':react-native-reanimated:generateJsonModelDebug' - Invalid revision: 3.18.1-g262b901. I also try to downgrade CMake version to 3.10.2.4988404 but your library required CMake version 3.18.1. I don't know why? How can I fix this issue?

![image](https://user-images.githubusercontent.com/48342930/192262404-cae933cb-bb3a-481e-b124-64277c9457f5.png)

thanks

### Steps to reproduce

1. Install Android CMake version 3.18.1
2. compileSdkVersion = 30
3. targetSdkVersion = 30
4. buildToolsVersion = 30.0.2

### Snack or a link to a repository

-

### Reanimated version

2.10.0

### React Native version

0.67.4

### Platforms

Android

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 2 API 29 (Android 10)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, here's the PR that fixes this issue: #3521

This fix has already been released in 3.0.0-rc.3.

For those who cannot upgrade to Reanimated 3, we plan to release 2.11 this week.

**Comment by karmil32** [comment]
Hi, when can we expect 2.11 version?

**Comment by tomekzaw** [comment]
Most likely this week

**Comment by tomekzaw** [comment]
@nwpnkmngm @karmil32 We have just published 2.11.0 which hopefully resolves this issue: https://www.npmjs.com/package/react-native-reanimated/v/2.11.0

**Comment by zachgibson** [comment]
Iʼm experiencing this on version `2.13.0`. Currently trying to figure out where/how this invalid revision is getting sourced but no luck so far.

**Comment by iampato** [comment]
Also facing the issue with `2.13.0`
