### ISSUE TITLE
Comparing Animated Values

### ISSUE THREAD

**Issue by EddieEJ** [software-mansion/react-native-reanimated#361]
How can I check if one Animated.Value is equal to another one and depending on that perform different logic in a method?

I have been trying this but it does not seem to work for me:
```
animatedVal = new Value(1);
animatedVal2 = new Value(2);

readValues = (animatedVal, animatedVal2) => {
   cond(eq(animatedVal,animatedVal2), console.log("YES"), console.log("NOPE"))
}
```
Can anyone suggest what the right way to perform this would be?

**Comment by mikedemarais** [comment]
👋️🤠️well howdy there @EddieEJ!

i think the `call` node is what you are looking for! [https://github.com/kmagiera/react-native-reanimated#call](https://github.com/kmagiera/react-native-reanimated#call)

```
animatedVal = new Value(1);
animatedVal2 = new Value(2);

readValues = (animatedVal, animatedVal2) => {
  return cond(
    eq(animatedVal,animatedVal2), 
    call([], () => console.log("YES")), 
    call([], () => console.log("NOPE")), 
  )
}
```

have fun!

**Comment by wcandillon** [comment]
`call` is to call back to the JS land. If you just want to debug your values, you can use `debug`

**Comment by jakub-gonet** [comment]
Hi @EddieEJ, 

I believe answers provided by @wcandillon and @mikedemarais resolve your problem, so I'm closing this issue.

If you have any questions please feel free to ask
