### ISSUE TITLE
Build failed: react-native-reanimated:configureCMakeDebug[arm64-v8a]

### ISSUE THREAD

**Issue by MejriMarwa** [software-mansion/react-native-reanimated#3621]
### Description

Build failed when using react-native-reanimated 2.10.0 with react-native 0.70.0 

![image](https://user-images.githubusercontent.com/37385426/192795243-5d425c45-bc20-41ff-b465-d6d190f9db16.png)

### Steps to reproduce

1- Upgrade react-native 0.60.0 to 0.70.0
2-install react-native-reanimated 2.10.0
3-run project

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

2.10.0

### React Native version

0.70.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

Real device

### Device model

android 12

### Acknowledgements

Yes

**Comment by saravanaS2108** [comment]
I'm also facing the exact issue. please help us ASAP.

**Comment by saravanaS2108** [comment]
97987987879879879797979797978

**Comment by JonsonHI** [comment]
I'm also facing the exact issue. please help us ASAP.

**Comment by EduFrazao** [comment]
Same problem here folks, with RN 0.70.1

`
  CMake Error at CMakeLists.txt:74 (add_library):
    Cannot find source file:
  
      /home/eduardo/Projetos/DavinTI/virtruvio/vitruvio-react-native/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp
  
    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
    .hpp .hxx .in .txx
  
  
  CMake Error at CMakeLists.txt:74 (add_library):
    No SOURCES given to target: reanimated

`

**Comment by Deepa-Palani** [comment]
I am also facing same issue.please help me to fix this issue

**Comment by FAIZ117** [comment]
reanimated =>2.10.0
Change the cmake version in node_modues => react-native-reanimated=> android => build.gradle to 3.24.2

And extract the cmake 3.24.2 dowloaded binary.zip inside your %appdata% => local > android> sdk => cmake and add the path to the cmake /bin to the user environment variable.

this fixed my issue for the time being unless the fix is released.

**Comment by bukhari-flip** [comment]
> Same problem here folks, with RN 0.70.1
> 
> ` CMake Error at CMakeLists.txt:74 (add_library): Cannot find source file:
> 
> ```
>   /home/eduardo/Projetos/DavinTI/virtruvio/vitruvio-react-native/node_modules/react-native-reanimated/Common/cpp/Fabric/FabricUtils.cpp
> 
> Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
> .hpp .hxx .in .txx
> ```
> 
> CMake Error at CMakeLists.txt:74 (add_library): No SOURCES given to target: reanimated
> 
> `

I think it's because v2.10.0 try to include FabricUtils.cpp which is not found on that [version](https://github.com/software-mansion/react-native-reanimated/tree/2.10.0/Common/cpp)

**Comment by AliMSbaee** [comment]
@EduFrazao 
Try building with `newArchEnabled=false`. This worked for me ( RN@0.70.1 & RNR@2.10.0)

**Comment by lekbit** [comment]
> we fixed it with the solution [here](https://github.com/mrousavy/react-native-vision-camera/issues/1283#issuecomment-1380368472)

But for me, the post below helped 😅 [here](https://github.com/mrousavy/react-native-vision-camera/issues/1283#issuecomment-1400287872)

**Comment by piaskowyk** [comment]
@andreacab2 thanks for posting a solution 🙌

**Comment by Shahzaib114** [comment]
resolved....please follow below link
https://github.com/software-mansion/react-native-reanimated/issues/4971#issuecomment-1837591885
