### ISSUE TITLE
Using reanimated 1 API on web, throws an exception

### ISSUE THREAD

**Issue by lkinasiewicz** [software-mansion/react-native-reanimated#3623]
### Description

When using `EasingNode`, the app throws an error, because it is undefined:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'ease')
```

### Steps to reproduce

1. Install react-native-web in your project.
2. Try to import `EasingNode` and use it:
```ts
import {EasingNode} from 'react-native-reanimated';

const easing = EasingNode.ease;
```
3. Run the web app.
4. Application throws an error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'ease')
```

### Snack or a link to a repository

Snack does not work with reanimated 2.10.0

### Reanimated version

2.10.0

### React Native version

0.68.2

### Platforms

Web

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Closed with #3624
