### ISSUE TITLE
Not working on react-native 0.60.4

### ISSUE THREAD

**Issue by fouad1994** [software-mansion/react-native-reanimated#363]
How to let it work on react-native 0.60.4 now I get an error while sync gradle

**Comment by BravenxX** [comment]
try: 

in android folder using terminal: 
 
-> gradlew clean

im working with react-native 0.60.4 too and works fine for me

**Comment by Tochukwuibe** [comment]
experiencing this same issue and gradlew clean is not working for me.

**Comment by empiteranga** [comment]
not working for me either

**Comment by Tochukwuibe** [comment]
This fixed the issue for me (You might want to refresh your node_modules and invalidate the android cache first).

npm install --save-dev jetifier
npx jetify

**Comment by jakub-gonet** [comment]
Hi @fouad1994,
I hope the solution provided by @Tochukwuibe solved your problem and if not feel free to reopen 🙂
