### ISSUE TITLE
Multiple versions of Reanimated were detected

### ISSUE THREAD

**Issue by souna23** [software-mansion/react-native-reanimated#3637]
### Description

this happend after upgrad to version 2.10.0 
with version 2.9.1 everything is good 
this solution is not working https://docs.swmansion.com/react-native-reanimated/docs/next/fundamentals/troubleshooting/

help please

### Steps to reproduce

1.upgrade to 2.10.0

### Snack or a link to a repository

https://docs.swmansion.com/react-native-reanimated/docs/next/fundamentals/troubleshooting/

### Reanimated version

2.10.0

### React Native version

0.69.4

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Can you paste the output of `npm ls react-native-reanimated`?

**Comment by souna23** [comment]
thank you very much for responding 
this is what it shows 
myproject@0.0.1 /Users/m/Documents/...path to my project
├─┬ @react-navigation/drawer@6.5.0
│ └── react-native-reanimated@2.10.0 deduped
└── react-native-reanimated@2.10.0

**Comment by souna23** [comment]
Hi, yes actually i am using monorepo for both operating systems android and ios, I used this instruction " sudo rm -rf node_modules" to remove the nodes modules file and reinstall them again with npm install and error still exist, all packages are updated, i dont understand 
here all my dependancies 

 "@react-native-async-storage/async-storage": "^1.17.9",
    "@react-native-community/geolocation": "^3.0.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "appcenter": "^4.4.5",
    "appcenter-analytics": "4.4.5",
    "appcenter-crashes": "4.4.5",
    "axios": "^0.27.2",
    "chalk": "^5.0.1",
    "deprecated-react-native-prop-types": "^2.3.0",
    "eventsource": "^2.0.2",
    "haversine": "^1.1.1",
    "latlng-to-zip": "0.0.2",
    "react": "18.1.0",
    "react-dom": "^18.1.0",
    "react-native": "0.70.1",
    "react-native-android-location-enabler": "^1.2.2",
    "react-native-code-push": "^7.0.5",
    "react-native-elements": "^3.4.2",
    "react-native-geolocation-service": "^5.3.0",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-maps": "1.3.2",
    "react-native-permissions": "^3.6.1",
    "react-native-platform-touchable": "^1.1.1",
    "react-native-reanimated": "2.10.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sse": "^1.1.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^11.23.0",
    "react-navigation-header-buttons": "^9.0.1",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0",
    "redux-thunk": "^2.4.1"

I don't know how to prepare a repro, can you give me a little guide please

**Comment by souna23** [comment]
thank you so mush, i will wait your result

**Comment by piaskowyk** [comment]
Have you tried setting the `resolutions` property in the workspace `package.json` or in `package.json` inside a single application?

**Comment by piaskowyk** [comment]
Ok, thanks for notifying me.

**Comment by Sub-Zero-1** [comment]
@tomekzaw I have the same issue with the 2.11.0. I can do a pod install with successfully with 2.10.0, but 2.10.0 does not work due to monorepo issues. The more, the monorepo issues persisted with 2.11.0 and I had to patch it myself. The path is different for me.

build.gradle:
`def reactNativeFromProjectNodeModules = file("${rootProject.projectDir}/../node_modules/react-native")`

for me it works with: 
`def reactNativeFromProjectNodeModules = file("${rootProject.projectDir}/..**/../**node_modules/react-native")`

Now, I get:


```
[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: [Reanimated] Multiple versions of Reanimated were detected. Only one instance of react-native-reanimated can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/troubleshooting#multiple-versions-of-reanimated-were-detected 

Conflict between: 
- /Users/abc/Documents/Develop/bla/node_modules/react-native-reanimated
- /Users/abc/Documents/Develop/bla/app/node_modules/react-native-reanimated
.

 #  from /Users/abci/Documents/Develop/bla/app/node_modules/react-native-reanimated/RNReanimated.podspec:6
 #  -------------------------------------------
 #  config = find_config()
 >  assert_no_multiple_instances(config)
 #  
 #  -------------------------------------------
.

 #  from /Users/aari/Documents/Develop/barmer-frontends/app/ios/Podfile:12
 #  -------------------------------------------
 #  target 'baseapp' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by swethamadhamshetty** [comment]
> npm ls react-native-reanimated

├─┬ cumo-rn-animation@3.2.0
│ └── react-native-reanimated@1.13.4
├── react-native-reanimated@2.10.0
├─┬ react-native-skeleton-content-nonexpo@1.0.11
│ ├── react-native-reanimated@1.13.4
│ └─┬ react-native-redash@14.2.4
│   └── react-native-reanimated@1.13.4 deduped
└─┬ react-native-tab-view@2.16.0 invalid: ">= 3.0.0" from node_modules/@react-navigation/material-top-tabs
  └── react-native-reanimated@2.10.0 deduped

**Comment by swethamadhamshetty** [comment]
> Can you paste the output of `npm ls react-native-reanimated`?

├─┬ cumo-rn-animation@3.2.0
│ └── react-native-reanimated@1.13.4
├── react-native-reanimated@2.10.0
├─┬ react-native-skeleton-content-nonexpo@1.0.11
│ ├── react-native-reanimated@1.13.4
│ └─┬ react-native-redash@14.2.4
│   └── react-native-reanimated@1.13.4 deduped
└─┬ react-native-tab-view@2.16.0 invalid: ">= 3.0.0" from node_modules/@react-navigation/material-top-tabs
  └── react-native-reanimated@2.10.0 deduped

**Comment by sacru2red** [comment]
[#3411](https://github.com/software-mansion/react-native-reanimated/pull/3441#issue-1329708619)

**Comment by birukindrias** [comment]
guys am getting this still '                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


 WARN  the transform cache was reset.
                Welcome to Metro v0.81.1
              Fast - Scalable - Integrated


info Dev server ready

i - run on iOS
a - run on Android
r - reload app
d - open Dev Menu
j - open DevTools

info Opening app on Android...
info A dev server is already running for this project on port 8081.
info Installing the app...
> Task :gradle-plugin:settings-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:compileKotlin UP-TO-DATE
> Task :gradle-plugin:shared:compileJava NO-SOURCE
> Task :gradle-plugin:shared:processResources NO-SOURCE
> Task :gradle-plugin:shared:classes UP-TO-DATE
> Task :gradle-plugin:shared:jar UP-TO-DATE
> Task :gradle-plugin:settings-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:settings-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:settings-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:settings-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:settings-plugin:classes UP-TO-DATE
> Task :gradle-plugin:settings-plugin:jar UP-TO-DATE
> Task :gradle-plugin:react-native-gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:react-native-gradle-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:react-native-gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:react-native-gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:react-native-gradle-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:react-native-gradle-plugin:classes UP-TO-DATE
> Task :gradle-plugin:react-native-gradle-plugin:jar UP-TO-DATE

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 8.6.0
Gradle: 8.7

> Task :app:checkKotlinGradlePluginConfigurationErrors
> Task :app:generateAutolinkingPackageList UP-TO-DATE
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-async-storage_async-storage:preBuild UP-TO-DATE
> Task :react-native-async-storage_async-storage:preDebugBuild UP-TO-DATE
> Task :react-native-async-storage_async-storage:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-date-picker:preBuild UP-TO-DATE
> Task :react-native-date-picker:preDebugBuild UP-TO-DATE
> Task :react-native-date-picker:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-gesture-handler:preBuild UP-TO-DATE
> Task :react-native-gesture-handler:preDebugBuild UP-TO-DATE
> Task :react-native-gesture-handler:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-linear-gradient:preBuild UP-TO-DATE
> Task :react-native-linear-gradient:preDebugBuild UP-TO-DATE
> Task :react-native-linear-gradient:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-reanimated:assertLatestReactNativeWithNewArchitectureTask SKIPPED
> Task :react-native-reanimated:assertNoMultipleInstances FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
21 actionable tasks: 5 executed, 16 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* Where:
Build file '/home/USD/Documents/mi/node_modules/react-native-reanimated/android/build.gradle' line: 597

* What went wrong:
Execution failed for task ':react-native-reanimated:assertNoMultipleInstances'.
> 
  [react-native-reanimated] Multiple versions of Reanimated were detected. Only one instance of react-native-reanimated can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/troubleshooting#multiple-versions-of-reanimated-were-detected 
  
  Conflict between: 
  - /home/USD/Documents/mi/node_modules/react-native-reanimated
  - /home/USD/Documents/mi/node_modules/nativewind/node_modules/react-native-reanimated


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
info Run CL'
