### ISSUE TITLE
[Android] Layout animations enabled by default on android

### ISSUE THREAD

**Issue by maxencehenneron** [software-mansion/react-native-reanimated#3643]
### Description

Layout Animations are enabled by default on Android. The react-native doc says they are experimental on this platform: 

https://reactnative.dev/docs/layoutanimation

I use layout animations on my app on iOS only and having them enabled on android breaks multiple parts of the app. Is it safe to just disable them again by calling the following code?

```javascript
if (Platform.OS === 'android') {
  if (UIManager.setLayoutAnimationEnabledExperimental) {
    UIManager.setLayoutAnimationEnabledExperimental(false);
  }
}
```

Here's the line that enables them: 

https://github.com/software-mansion/react-native-reanimated/blob/e52d733ab9f0fc33e52c54c8d7adbfe86a2608ac/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java#L259

### Steps to reproduce

Just install react-native-reanimated, launch an app ( you can use the example ).

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/tree/main/Example

### Reanimated version

2.9.0

### React Native version

0.67.4

### Platforms

Android

### JavaScript runtime

Hermes

### Acknowledgements

Yes

**Comment by hirbod** [comment]
React Native Layout Animation are something completely different than LayoutAnimation by react-native-reanimated.
And you should avoid using it at the current stage, until the rewrite is done, see https://github.com/software-mansion/react-native-reanimated/issues/3124

**Comment by hirbod** [comment]
You're referring to https://reactnative.dev/docs/layoutanimation, which has nothing to do with https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/layout_animations

**Comment by maxencehenneron** [comment]
I know these are completely different. This is what I'm saying. react-native-reanimated is enabling react-native's layout animation which I believe should not happen, hence, I created this issue. 

![Screen Shot 2022-10-06 at 9 47 29 AM](https://user-images.githubusercontent.com/377682/194371765-2e7d07d8-be6f-4d84-a473-0f2823d12ef9.png)


If you put a breakpoint **inside** react-native's code to enable react-native's implementation of layout animations, you can clearly see that it is being enabled by react-native-reanimated. It should not.

**Comment by hirbod** [comment]
Kinda weird, but try this

```
import { enableLayoutAnimations } from 'react-native-reanimated';

enableLayoutAnimations(false);
```

**Comment by rvieceli** [comment]
I had the same problem on iOS and Android (Expo SDK47 - without reanimated)

```tsx
  <View style={{
    justifyContent: "center",  ///<-- this was my problem
  }}>
  ```
This `View` is the container of the screen.

**Comment by tmitchel2** [comment]
I also have this issue.

Using setLayoutAnimationEnabledExperimental does not seem to work for IOS so that still causes native react native layout animations and react-native-reanimated layout animations to stumble over each other when using KeyboardAvoidingView on that platform.  Turning react-native-reanimated layout animations off gets rid of the issue but then obviously you miss the animations you want to keep.

@hatem-72 have you managed to get react-native-reanimated + KeyboardAvoidingView + IOS working?

**Comment by fukemy** [comment]
I got this noisy warning from v3, it's show with IOS device
