### ISSUE TITLE
Sending `onReanimatedPropsChange` with no listeners registered.

### ISSUE THREAD

**Issue by SkylerB1** [software-mansion/react-native-reanimated#3651]
### Description

I am getting this warning after implementing drawer navigation in my app with with react-native-reanimated@3.0.0-rc.3, react-native 0.70.0 and drawer 6.5.0.

### Steps to reproduce

1. Implement @react-navigation/drawer": "^6.5.0" with "react-native-reanimated": "^3.0.0-rc.3"

### Snack or a link to a repository

NA

### Reanimated version

3.0.0-rc.3

### React Native version

0.70.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 12

### Acknowledgements

Yes

**Comment by roryabraham** [comment]
We're seeing this too

**Comment by yanush** [comment]
I'm also getting thousands of these warnings after upgraded to 3.0.0-rc.3. using RN 0.70.3
Everything seems to work fine though, but it looks like a very fundamental operation causes this

**Comment by hannojg** [comment]
Reproduction and PR in #3716

**Comment by Latropos** [comment]
Closing, since #3716 is merged
