### ISSUE TITLE
gestureEvent context's parameter is empty and context.offsetX is undefined

### ISSUE THREAD

**Issue by NaraaDev** [software-mansion/react-native-reanimated#3658]
### Description

Context is undefined

### Steps to reproduce

1.I can't use context. Context is undefined
<img width="1792" alt="Screen Shot 2022-10-08 at 13 31 36" src="https://user-images.githubusercontent.com/99318619/194697014-5d60908c-3040-4920-9aad-4aca0d769baf.png">
<img width="1792" alt="Screen Shot 2022-10-08 at 13 31 38" src="https://user-images.githubusercontent.com/99318619/194697021-06ba524a-5543-47d2-b827-520129f30630.png">
`const panEvent = useAnimatedGestureHandler<PanGestureHandlerGestureEvent>({
    onStart: (event, ctx) => {
      console.log(ctx.offsetX); // undefined
    },
    onActive: event => {
      translateX.value = event.translationX;
    },
    onEnd: event => {
      translateX.value = event.translationX;
    },
  });`

### Snack or a link to a repository

https://snack.expo.dev/aisdkYV8w

### Reanimated version

2.10.0

### React Native version

0.70.2

### Platforms

iOS

### Workflow

React Native (without Expo)

### Device

iOS simulator

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
`useAnimatedGestureHandler` is deprecated by now, plase use `react-native-gesture-handler` which is now integrated with Reanimated
