### ISSUE TITLE
Animated.View does not update exiting/entering layout animations dynamically

### ISSUE THREAD

**Issue by fivecar** [software-mansion/react-native-reanimated#3662]
### Description

Changing `exiting` or `entering` properties on an animated component doesn't have an effect.

Since `createAnimatedView` only ever registers `entering` or `exiting` animations during `_setComponentRef`, updates to `exiting` and `entering` don't ever take effect (i.e. `componentDidUpdate` in animated components doesn't ever re-register `exiting` and `entering` via `LayoutAnimationRepository.registerConfig`).

I tried the obvious "fix," which was to call `registerConfig` with an updated `exiting`/`entering` during `componentDidUpdate`, but that led to a crash. I'm likely misunderstanding the threading/data-usage of configurations once registered. The real fix would be to update registered configurations with new layout animations whenever those properties change.

### Steps to reproduce

1. Create an `Animated.View` with `exiting={LightSpeedOutLeft}`, and `key={42}`
2. Dynamically update its `exiting` to `LightSpeedOutRight`. Make sure component renders before next step.
3. Change `key` to `"Thank you very much, Mr. Roboto"`. Once again, this step should only be taken AFTER step 2 has rendered, or else you'll simply be setting a different animation on a new view.

RESULT: View animates out left.
EXPECTED: View animates out right.

### Snack or a link to a repository

https://snack.expo.dev/@fivecar/reanimated2-layout-animations-not-updating

### Reanimated version

2.10.0

### React Native version

0.69.3

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by fendermany** [comment]
Hello,

Same problem. Any updates?

**Comment by Cookizza** [comment]
There's a handful of issues around Layout exit animations but this one describes our simple issue the best.

Updating the exit transition config of a key'd component does nothing.

It does seem like the rewrite PR fixes this, but I know there are concerns around native view teardowns etc - following closely!

**Comment by fendermany** [comment]
Layout animation rewrite exactly fixed this? And how? We can use only statements for dynamic changes next animation?

**Comment by fendermany** [comment]
Looks like an exit animation has not been fixed in the new version, I checked 3.0.0-rc6

**Comment by nfmshow** [comment]
Any hope that this will ever be fixed?

**Comment by nfmshow** [comment]
@michal4511, this [package](https://moti.fyi) helped to achieve what I wanted

**Comment by bviebahn** [comment]
I encountered the same problem and found a workaround using a custom animation as described here: https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/customAnimations#custom-exiting-animation

In my case I want to set the exit animation to either `SlideOutLeft` or `SlideOutRight` depending on which way the view was swiped. My solution looks something like this:

```javascript
import Animated, {
    SlideOutLeft,
    SlideOutRight,
    useSharedValue,
} from 'react-native-reanimated';

const slideOutLeftAnimation = new SlideOutLeft().build();
const slideOutRightAnimation = new SlideOutRight().build();

const MyComponent = () => {
    const exitDirection = useSharedValue('left');

    const CustomExitingAnimation = (values) => {
        'worklet';

        return exitDirection.value === 'left'
            ? slideOutLeftAnimation(values)
            : slideOutRightAnimation(values);
    };

    return (
        <Animated.View
            exiting={CustomExitingAnimation}
            onTouchMove={() => {
                exitDirection.value = someCondition ? 'left' : 'right';
            }}
        />
    );
}
```

**Comment by Cookizza** [comment]
The example by @bviebahn is the correct way to do this, using shared values and the animation builder. The example even extends a reanimated preset which is great for people looking for a copy paste solution. Great contribution!

**Comment by fendermany** [comment]
> I encountered the same problem and found a workaround using a custom animation as described here: https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/customAnimations#custom-exiting-animation
> 
> In my case I want to set the exit animation to either `SlideOutLeft` or `SlideOutRight` depending on which way the view was swiped. My solution looks something like this:
> 
> ```js
> import Animated, {
>     SlideOutLeft,
>     SlideOutRight,
>     useSharedValue,
> } from 'react-native-reanimated';
> 
> const slideOutLeftAnimation = new SlideOutLeft().build();
> const slideOutRightAnimation = new SlideOutRight().build();
> 
> const MyComponent = () => {
>     const exitDirection = useSharedValue('left');
> 
>     const CustomExitingAnimation = (values) => {
>         'worklet';
> 
>         return exitDirection.value === 'left'
>             ? slideOutLeftAnimation(values)
>             : slideOutRightAnimation(values);
>     };
> 
>     return (
>         <Animated.View
>             exiting={CustomExitingAnimation}
>             onTouchMove={() => {
>                 exitDirection.value = someCondition ? 'left' : 'right';
>             }}
>         />
>     );
> }
> ```

This is definitely a great tip! Could you tell me why it works?

**Comment by 0xAsimetriq** [comment]
Solution above won't work if there is no "pre-rerender" action (in this case touchmove) that happens before exit animation gets triggered i.e. example below enters or exits view with slide left or right similar to what is achieved above, however in this case when view changes exiting animation still uses previous value it seems.

```ts
export function TabView({ children, headless, style }: Props) {
  const { view } = useStore(RouterStore)

  return (
    <AnimatedView
      entering={AnimationTool.tabViewIn(view)}
      exiting={AnimationTool.tabViewOut(view)}
    >
      {children}
    </AnimatedView>
  )
}
```

**Comment by m-bert** [comment]
Hi @fivecar! This issue should be fixed by [this PR](https://github.com/software-mansion/react-native-reanimated/pull/5371). I'll leave this issue open until fix gets merged.

**Comment by Slapbox** [comment]
This issue affects us even if we use a ternary to alternatively render one of two separate `Animated.View`s, each with their own static animations.

**Comment by m-bert** [comment]
Hi! We've just merged #5371, could you please check if this issue still persists?

**Comment by davidjbng** [comment]
It is resolved for me (tested with `3.7.0-nightly-20240117-e973fcc7d`).

In my case I was dynamically changing a layout transition depending on react state which is working as expected now.

**Comment by m-bert** [comment]
I'm happy to hear that! I'll close this issue, feel free to reopen it if necessary.

**Comment by minawalphonce** [comment]
this should be added to documentation. it is very common issue and no clear answer. however @bviebahn example is clear and good
