### ISSUE TITLE
Getting `Can't merge user-tart_xconfig for pod targets: ["RNReanimated", "hermes-engine"]` error on `pod install`

### ISSUE THREAD

**Issue by KrisLau** [software-mansion/react-native-reanimated#3664]
### Description

When I run `pod install` or `pod update`, I'm getting a warning/error:
```
Can't merge user_target_xcconfig for pod targets: ["Reanimated", "hermes-engine"] Singular build setting CLANG_CXX_LIBRARY has different values.

Can't merge user_target_xcconfig for pod targets: ["Reanimated", "hermes-engine"] Singular build setting CLANG_CXX_LIBRARY has different values.

Can't merge user_target_xcconfig for pod targets: ["Reanimated", "hermes-engine"] Singular build setting CLANG_CXX_LIBRARY has different values.

Can't merge user_target_xcconfig for pod targets: ["Reanimated", "hermes-engine"] Singular build setting CLANG_CXX_LIBRARY has different values.
```

Also tried following the answer here: https://stackoverflow.com/a/73530687/9927977 but I'm already on v2.10.0.

### Steps to reproduce

1. Create a react native project on v0.70.0
2. Install reanimated v2.10.0

### Snack or a link to a repository

N/A

### Reanimated version

2.10.0

### React Native version

0.70.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 11 (13.6)

### Acknowledgements

Yes

**Comment by KrisLau** [comment]
Nevermind just found the solution: https://github.com/Shopify/react-native-skia/issues/405#issuecomment-1250633417 which was just to upgrade to v3.0.0-rc.3

**Comment by arnoldc** [comment]
i encountered this issue as well

but I use reanimated  2.17.0 + react native 0.70.14 and i dont see the issue anymore
