### ISSUE TITLE
vulnerable to ReDoS alert when installing with npm

### ISSUE THREAD

**Issue by shant1010** [software-mansion/react-native-reanimated#3665]
### Description

When installing using the `npm i react-native-reanimated` command, nom states there is a severe vulnerability. 

if you run ` npm audit fix` you get this:

> react-native-reanimated  <3.0.0-rc.1
> Severity: high
> react-native-reanimated vulnerable to ReDoS - https://github.com/advisories/GHSA-2j79-8pqc-r7x6
> No fix available
> node_modules/react-native-reanimated

### Steps to reproduce

`npm i react-native-reanimated`
`npm audit fix`

### Snack or a link to a repository

n/a

### Reanimated version

2.10.0

### React Native version

0.70.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Acknowledgements

Yes

**Comment by Jare9716** [comment]
I install the react-native-reanimated
as 
npm i react-native-reanimated@3.0.0-rc.0

meaby it works for you.

**Comment by shant1010** [comment]
Yeah, unfortunately it still shows the vulnerability :(

**Comment by lcsjunior** [comment]
Me too.

![image](https://user-images.githubusercontent.com/8947621/197191732-9dfe291c-d6e1-4533-a802-6d4223e8b2d4.png)

**Comment by tomekzaw** [comment]
The vulnerability was effectively patched in 3.0.0-rc.1 and 2.10.0.

I've changed the affected versions in GitHub Advisory Database (https://github.com/advisories/GHSA-2j79-8pqc-r7x6).

Please upgrade to 2.10.0+ (currently the latest release is 2.11.0) and you should be safe.
