### ISSUE TITLE
Build failing when enabled newArchEnabled=true

### ISSUE THREAD

**Issue by AamirHafiez** [software-mansion/react-native-reanimated#3675]
### Description

While building the app with newArchEnabled=true, the build is giving the following error

`BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

/Users/aamirhafiez/Documents/projects/ScoreTest/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:15: error: package com.swmansion.reanimated does not exist
import com.swmansion.reanimated.ReanimatedPackage;
                               ^
/Users/aamirhafiez/Documents/projects/ScoreTest/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:65: error: cannot find symbol
      new ReanimatedPackage(),
          ^
  symbol:   class ReanimatedPackage
  location: class PackageList
Note: /Users/aamirhafiez/Documents/projects/ScoreTest/android/app/src/debug/java/com/scoretest/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org` 

### Steps to reproduce

1. created a new react native app template with typescript using 
`npx react-native init AwesomeTSProject --template react-native-template-typescript`

2. Installed some packages (not in reference to reanimated), and id required installation steps
`yarn add @react-navigation/native
 yarn add react-native-screens react-native-safe-area-context
`

3. Installed reanimated using
`yarn add react-native-reanimated`

4. Added to babel.config.js
`react-native-reanimated/plugin`

5. Enabled new Architecture in gradle.properties
`newArchEnabled=true`

6. Build App
`npx react-native run-android`

### Snack or a link to a repository

https://github.com/AamirHafiez/TestAnimated

### Reanimated version

2.11.0

### React Native version

0.70.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
read this: https://github.com/software-mansion/react-native-reanimated/blob/main/README-Fabric.md

2.x is not compatible with fabric

**Comment by tomekzaw** [comment]
Reanimated 2.x doesn't support Fabric. Upgrade to Reanimated 3.0.0-rc.3 for Fabric support.
