### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by swatantragoswami09** [software-mansion/react-native-reanimated#3676]
### Description

when I install the "react-native-reanimated": "^2.1.0", library I  get this error
![image](https://user-images.githubusercontent.com/54662673/195839408-371f9cbe-9769-41be-893e-d643c40a0ee7.png)

### Steps to reproduce

1. npm i @rainbow-me/animated-charts
2. npm i react-native-reanimated"

### Snack or a link to a repository

https://github.com/swatantragoswami09/RNCryptoWallet-DarkMode/tree/reanimated-bug

### Reanimated version

2.1.0

### React Native version

0.64.1

### Platforms

Android

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Please upgrade to Reanimated 2.11.0.
