### ISSUE TITLE
iOS Warning: RCTBridge required dispatch_sync to load REAModule

### ISSUE THREAD

**Issue by dimaischenko** [software-mansion/react-native-reanimated#3678]
### Description

When the application starts, I get the following warning: `RCTBridge required dispatch_sync to load REAModule. This may lead to deadlocks`

### Steps to reproduce

Every time the application is launched

<img width="359" alt="Знімок екрана 2022-10-15 о 11 33 43" src="https://user-images.githubusercontent.com/4239355/195977395-d98bad06-46ad-4796-92da-e5e7a0ebb4be.png">

### Snack or a link to a repository

Sorry

### Reanimated version

2.11.0

### React Native version

0.70.3

### Platforms

iOS

### Workflow

React Native (without Expo)

### Acknowledgements

Yes

**Comment by dpyeates** [comment]
I see am seeing this as well now.

**Comment by godlikeAlex** [comment]
+1

**Comment by enahum** [comment]
same

**Comment by godlikeAlex** [comment]
I solve the problem like this:
```
1)npm install react-native-reanimated@2.10.0 
2) cd ios/
3) pod install
```
Then you need rebuild your application

if you are using a phone
`npx react-native run-ios`

if physical device, **Go to Xcode and build your app.**

**Comment by dimaischenko** [comment]
Thank you, so the downgrade will help, but maybe someone will know what a patch or fixes for the current release

**Comment by aymather** [comment]
I can also confirm that moving from `2.10.0` -> `2.11.0` introduced this issue.

**Comment by tomekzaw** [comment]
Hey, we are investigating this issue and working on a fix. Feel free to use 2.10.0 or add `LogBox.ignoreLogs` to ignore this warning.

**Comment by Max-DVS** [comment]
Hello,

I stumbled upon the same issue today using 2.11.0 

Just start a fresh project and follow react navigation documentation to add a drawer...

The only missing piece on their docs is to add react-native-reanimated/plugin into babel...

did a pod install and the only thing I got was that error, a regular stack works while a drawer will throw that error.

The fix was to get back to 2.10.0

**Comment by shant1010** [comment]
Same issue here. Honestly kinda gave up on react-native-reanimated for now. Crazy how many issues this package brings. They fixed the vulnerability in 2.11.0, but now this happens :/

**Comment by hadnet** [comment]
Same here using Reanimated 3-RC3

**Comment by alqamabinsadiq** [comment]
Same problem. For me even if I downgrade the version to `2.10.0` I see the warning.

**Comment by alqamabinsadiq** [comment]
Downgrading to `2.10.0` worked for me too.

**Comment by tomekzaw** [comment]
The offending PR is #3555. Fixed in #3698.

**Comment by dimaischenko** [comment]
@tomekzaw Thank you for such a quick response, work and clarification!

**Comment by skam22** [comment]
> 

not to nitpick but the method is LogBox.ignoreLogs, not LogBox.ignore:

```
import { LogBox } from 'react-native';

LogBox.ignoreLogs(['RCTBridge required dispatch_sync to load REAModule']);
```

**Comment by tomekzaw** [comment]
This issue has been fixed in #3698 and released in 2.12.0 so upgrade and you will never see this warning again.

**Comment by derwaldgeist** [comment]
I'm seeing this in a brand-new installation of RN (macOS Sonoma, iOS 17). Shouldn't this be fixed by now?

**Comment by tomekzaw** [comment]
@derwaldgeist Yes, this should be fixed. Which version of Reanimated exactly are you using?

**Comment by derwaldgeist** [comment]
> @derwaldgeist Yes, this should be fixed. Which version of Reanimated exactly are you using?

Oh, sorry. I just realized that this repo is related to a certain library. I just came here via Google and thought it was on the react-native repo itself. I just tried out RN, to check how far I can get on a Vision Pro (but the issue also occurred on iOS).

**Comment by tuantvk** [comment]
@tomekzaw I got the same warning in the new version.
```json
"react-native": "0.73.3",
"react-native-reanimated": "^3.6.2",
```

I think maybe it is related to the new version react-native.

```m
  // This dispatch_async avoids a deadlock while configuring native modules
  dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INTERACTIVE, 0), ^{
    id a11yManager = [self->_bridge moduleForName:@"AccessibilityManager"
                                             lazilyLoadIfNecessary:YES];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(didReceiveNewContentSizeMultiplier)
                                                 name:@"RCTAccessibilityManagerDidUpdateMultiplierNotification"
                                               object:a11yManager];
```

[packages/react-native/React/Modules/RCTUIManager.m](https://github.com/facebook/react-native/commit/f39f34ed82997d0595522a285c3cb8693594e718#diff-81ff84d57d20963d22937a0eac3403fe54baa536cabfbc84dc64d7a1a187469e)

**Comment by correafederico25** [comment]
@tuantvk  I also have the same warning in version 0.73.3

A few days ago I built an app with version 0.73.2 and I didn't have any problems. 1 hour ago I built a new app with version 0.73.3 and started seeing this warning.

```
{
  "name": "AwesomeProject2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.20",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.4",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```

**Comment by Milutin-P** [comment]
@correafederico25 Are you sure that it is the same message? I got `RCTBridge required dispatch_sync to load RCTAccessibilityManager. This may lead to deadlocks.` Which is not related to RNA, I would say.

**Comment by uen** [comment]
Check https://github.com/facebook/react-native/issues/42728 - it is fixed in 0.73.4

**Comment by nima-ap** [comment]
Hey @tomekzaw
We're hitting a deadlock caused by the `RCTUnsafeExecuteOnMainQueueSync` call in [cleanupListeners](https://github.com/software-mansion/react-native-reanimated/blob/028a750aa6a6edc0661e40a08334ad9859fcb730/packages/react-native-reanimated/apple/reanimated/apple/keyboardObserver/REAKeyboardEventObserver.mm#L290) on iOS.
If the main thread is blocked for any reason (in our case, a native module constructor acquiring a mutex during the new bridge's module initialization) this creates a circular deadlock.

We've locally patched around this by replacing `RCTUnsafeExecuteOnMainQueueSync` with `dispatch_async` in `cleanupListeners`, plus an immediate removal of the `RCTBridgeDidInvalidateModulesNotification` observer before the async block to prevent re-entrancy. This has been stable thus far with no regressions in keyboard handling.

Would the team consider changing this to `dispatch_async` upstream? The bridge is already being torn down, so blocking the JS thread to wait for main queue clean up might not be needed.

**Comment by tjzel** [comment]
Hi @nima-ap, could you share the patch and possibly a reproduction? I see no issue with your approach but I'd preferably see for myself how this deadlock happens so we could possibly identify other hot-spots like this one.
