### ISSUE TITLE
Issues with "react-native-reanimated": "3.0.0-rc.1" - need to use this dependency because of Vulnerable To ReDoS

### ISSUE THREAD

**Issue by dah-projects** [software-mansion/react-native-reanimated#3679]
### Description

Hello,

In npm package react-native-reanimated a vulnerability was found: [react-native-reanimated vulnerable to ReDoS](https://github.com/advisories/GHSA-2j79-8pqc-r7x6). It works just fine with an older version like react-native-reanimated:~2.9.1. I just don't know how bad this vulnerability is to be honest, but I'd rather have a project where I don't get such severity issues when installing dependencies. 

So when setting up a fresh project I tried to use this patched dependency, which currently is not useable with @react-navigation/drawer. After running in IOS I get the following error: 
**"can't find variable: _updatePropsPaper."**
This is in a fresh project, in another project I got a different error: 
**"tried to synchronously call anonymous function from a different thread".** 
So this package is not working well at all. 

I've added a simple repo which you can run locally in IOS emulator and to reproduce the problem
<img width="429" alt="image" src="https://user-images.githubusercontent.com/37047137/195978942-e80173fd-1520-46bb-a2eb-82cb9e3d3e4a.png">

### Steps to reproduce

node -v v16.17.1

1. Clone: https://github.com/dah-projects/drawer-dep-repro
1. npm i --force
2. npx expo start -c --ios

### Snack or a link to a repository

https://github.com/dah-projects/drawer-dep-repro

### Reanimated version

3.0.0-rc.1

### React Native version

0.69.6

### Platforms

iOS

### Workflow

Expo managed workflow

### Device

iOS simulator

### Device model

Iphone 12

### Acknowledgements

Yes

**Comment by R4Y-repo** [comment]
This happened to me too
Had to use the rc version in my project to make the error disappear

**Comment by dah-projects** [comment]
> 

Not sure what you mean, you don't get the same error as in my screenshot ("can't find variable: _updatePropsPaper.") when using  "react-native-reanimated": "3.0.0-rc.1"?

**Comment by dah-projects** [comment]
> This happened to me too Had to use the rc version in my project to make the error disappear

Not sure what you mean, you don't get the same error as in my screenshot ("can't find variable: _updatePropsPaper.") when using "react-native-reanimated": "3.0.0-rc.1"?

**Comment by tomekzaw** [comment]
Update to 3.0.0-rc.3.

**Comment by tomekzaw** [comment]
> So this package is not working well at all.

Thanks

> can't find variable: _updatePropsPaper

Did you remember to run `pod install` and build the app for iOS after bumping the version?

Also, please upgrade to 3.0.0-rc.3 which is the latest release.

**Comment by dah-projects** [comment]
> Thanks
Haha sorry, it's working perfectly fine without using > 3.0.0-rc.1. 

> Did you remember to run `pod install` and build the app for iOS after bumping the version?
I'm using expo and from my understanding you don't need to use pod like with CLI version, right?
> Also, please upgrade to 3.0.0-rc.3 which is the latest release.
When I used that version (or rc.2) my IOS emulator crashes and shows a crash report. 

Have you tried the github project I mentioned?

**Comment by tomekzaw** [comment]
@dah-projects 

> I'm using expo and from my understanding you don't need to use pod like with the CLI version, correct?

If you use Expo managed workflow, then you must use the exact version of Reanimated that Expo SDK was compiled with, otherwise there's a mismatch of JS code (3.0.0-rc.1) and native code (2.9.1) that was compiled to Expo binaries.

**Comment by dah-projects** [comment]
> @dah-projects
> 
> > I'm using expo and from my understanding you don't need to use pod like with the CLI version, correct?
> 
> If you use Expo managed workflow, then you must use the exact version of Reanimated that Expo SDK was compiled with, otherwise there's a mismatch of JS code and native code that was compiled to Expo binaries. In this case, your JS code (that uses Reanimated 3.0.0-rc.1) tries to call function `_updatePropsPaper` that doesn't exist, because the native part (2.9.1) injects a function called `_updateProps`, not `_updatePropsPaper`.
> 
> Also, I think that Expo CLI should somehow warn you that it expects 2.9.1, not 3.0.0-rc.1.

It does indeed, so I basically just have to wait for react-navigation to be compatible with newest versions of react-native-reanimated?

**Comment by kacperkapusciak** [comment]
Hi @dah-projects 👋 

It's not an issue with react-native-reanimated v3 support in react-navigation. You **can** use Reanimated v3 with the drawer navigator but that's **not** the problem you're facing.


You're using expo-managed workflow which unless you [prebuild your workflow](https://docs.expo.dev/workflow/prebuild/) it doesn't support installing custom versions of native packages. 

With each Expo SDK (here SDK 46) there's one paired version of Reanimated (here v2.9). Expo authors knew it would be confusing so they created `npx expo install` command which does the `SDK` ↔️ `package` pairing automatically. Docs: https://docs.expo.dev/workflow/using-libraries/#installing-a-third-party-library

TLDR:
You can't use Reanimated v3 with Expo SDK 46. 

PS:
Use `npx expo install` to install packages in managed workflow

**Comment by tomekzaw** [comment]
The vulnerability was effectively patched in 3.0.0-rc.1 and 2.10.0.

I've changed the affected versions for this vulnerability in GitHub Advisory Database (https://github.com/advisories/GHSA-2j79-8pqc-r7x6).
