### ISSUE TITLE
Typo in documentation under proc node

### ISSUE THREAD

**Issue by yanush** [software-mansion/react-native-reanimated#368]
The given example for proc node contains a typo:

> proc
> Returns a callable function node that can be used to define expressions that can be called from other nodes.
> 
> Example:
> 
> // Global constant
> const myProc = proc((a, b) => multiply(a,b));
> 
> // In your component
> const style = { width: proc(10, 10 )};

The last line should be:

> const style = { width: myProc(10, 10 )};

**Comment by wcandillon** [comment]
Could you provide a PR for this directly?

**Comment by jakub-gonet** [comment]
Fixed in #484, thanks for filling this issue
