### ISSUE TITLE
Build failed with an exception react-native-reanimated@2.11.0

### ISSUE THREAD

**Issue by fkazemi5236** [software-mansion/react-native-reanimated#3680]
### Description

I upgrade react-native-reanimated to 2.11.0 and when I want to run app, terminal show this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-reanimated:classpath'.     
      > Could not find com.android.tools.build:gradle:7.3.0.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom   
          - https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
        Required by:
            project :react-native-reanimated

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-reanimated:classpath'.
      > Could not find com.android.tools.build:gradle:7.3.0.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
          - https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
        Required by:
            project :react-native-reanimated

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Steps to reproduce

1. yarn remove react-native-reanimated
2. yarn add react-native-reanimated
3. yarn start --reset-cache
4. npx react-native run-android

### Snack or a link to a repository

https://gitlab.com

### Reanimated version

2.11.0

### React Native version

0.70.3

### Platforms

Android

### Acknowledgements

Yes

**Comment by fgagneten** [comment]
Same issue here. Upgrading to reanimated 3 compiles run the app I still facing other issues as well

**Comment by tomekzaw** [comment]
Hey @fkazemi5236, thanks for submitting this issue.

Building Reanimated 2.11.0 on Android works fine for me.

Can you check if you can reach the URL from the logs? https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom

**Comment by masads** [comment]
> Hey @fkazemi5236, thanks for submitting this issue.
> 
> Building Reanimated 2.11.0 on Android works fine for me.
> 
> Can you check if you can reach the URL from the logs? https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom

It works, but why is it still having an issue with the latest version?

**Comment by masads** [comment]
> Hey @fkazemi5236, thanks for submitting this issue.
> 
> Building Reanimated 2.11.0 on Android works fine for me.
> 
> Can you check if you can reach the URL from the logs? https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom

its Worked.
but why it's still having issues with the latest version?
