### ISSUE TITLE
useDerivedValue is not updating on Android

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#3688]
### Description

```
  const progress = useDerivedValue(() => {
    return isActive ? withTiming(1, {duration: 500}) : withTiming(0);
  }, [isActive]);
  // "#ffB692", "#FA6B17", "#FAEBE5"
  const rStyle = useAnimatedProps(() => {
    const c1 = interpolateColor(progress.value, [0, 1], ["#BDC3C7", "#ffB692"]);
    const c2 = interpolateColor(progress.value, [0, 1], ["#BDC3C7", "#FA6B17"]);
    const c3 = interpolateColor(progress.value, [0, 1], ["#BDC3C7", "#ffB692"]);
    return {
      colors: [c1, c2, c3],
    };
  });
  return (
    <View
      pointerEvents={"none"}
      style={{zIndex: 9999, width, height, position: "absolute", alignSelf: "center", alignItems: "center"}}
    >
      <MaskedView
        style={{width: "100%", flexDirection: "row", height: "100%"}}
        maskElement={
          <View
            style={{
              // Transparent background because mask is based off alpha channel.
              backgroundColor: "transparent",
              flex: 1,
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Text style={[textStyles().fontSize16, textStyles().bold]}>{text}</Text>
          </View>
        }
      >
        <AnimatedGradient
          animatedProps={rStyle}
          style={{width: "100%", height: 50}}
        />
      </MaskedView>
    </View>
```

Here i just wanted to try out something. 
Basically i created a custom compoent that renders a text with a gradient background. So i get a `isActive` state from outside and if its true i switch colors from static to gradient colors.. i hold this state in `progress`. and once isActive changes, im interpolating my colors smoothly. This behavior works perfectly on IOS but on Android it doesnt work at all.

I checked isActive changes dynamically and i also console logged the `c1 c2 c3` they also changing  but, these values not being applied to the AnimatedGradient which is a custom component i generated by `Animated.createAnimatedComponent`

as linear gradient i use react-native-linear-gradient...

### Steps to reproduce
npm install or pod install 
then run npx react-native run-android

### Snack or a link to a repository
https://github.com/Bayramito/reproducable

### Reanimated version

2.11.0

### React Native version

0.70.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Xiaomi mi 8

### Acknowledgements

Yes

**Comment by Bayramito** [comment]
https://github.com/Bayramito/reproducable

here is the reproducable repo for you.

just `npm install / pod install` then run `npx react-native run-android` or `npx react-native run-ios`  to see difference.

as like i mentioned above all i want to do set new colors when the active state is changed, so to produce this behavior i made a single clickable called `BAS` when you click it gradient color in the component should change smoothly. This works on iOS but not on Android

**Comment by TheWirv** [comment]
As far as I understand it, `useDerivedValue` was made to _derive_ a shared value from another shared value. See the documentation for its first parameter:
> `updaterWorklet` [worklet]
>
> The first argument is a worklet that gets triggered whenever at least one of the shared values used in that worklet changes. [...]

In contrast, your `useDerivedValue`'s `updaterWorklet` does not contain any shared values. I would use `useSharedValue` to create `progress`, and then a `useEffect` that depends on `isActive`:
```typescript
useEffect(() => {
  progress.value = isActive ? withTiming(1, {duration: 500}) : withTiming(0);
}, [isActive]);
```

**Comment by Latropos** [comment]
Yes, see our official documentation [LINK](https://docs.swmansion.com/react-native-reanimated/docs/core/useDerivedValue/) for more info
