### ISSUE TITLE
using proc node

### ISSUE THREAD

**Issue by yanush** [software-mansion/react-native-reanimated#369]
When trying to use proc node I keep getting:
> proc is not a function

React Native: 0.60.5
React Native Reanimated: 1.2.0

Any ideas?

**Comment by chrfalch** [comment]
You need to provide some more context to what you are trying to do, can you give a short code example?

**Comment by yanush** [comment]
even the simplest thing isn't working with proc.
example for code:

```
/**
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {
	View,
	Text,
} from 'react-native';
import Animated, {Easing} from 'react-native-reanimated';

const {
	multiply,
	proc,
	Value,
} = Animated;


export default class App extends Component {
	animatedValue0 = new Value(0);
	animatedValue1 = new Value(1);

	constructor(props) {
		super(props);
	}

	render() {
		const myProc = proc((a, b) => multiply(a, b));

		return (
			<View style={{
				flex: 1,
				backgroundColor: '#ffff00',
				alignItems: 'center',
				justifyContent: 'center',
			}}>
				<Text>Test</Text>
				<Animated.View style={{
					width: 100,
					height: 100,
					backgroundColor: '#0000ff',
					opacity: myProc(this.animatedValue0, this.animatedValue1),
				}}/>
			</View>
		);
	}
}
```

I keep getting TypeError: proc is not a function

**Comment by chrfalch** [comment]
Proc nodes should **not** be instantiated in the render method - create the proc as a module constant (const outside your component.

The point of introducing the proc node is to be able to declare parts of a node graph once - and then reuse it to save the number of nodes that are transported across the js-bridge. 

Move the following line to the line before you declare your component:

```js
const myProc = proc((a, b) => multiply(a, b));
```

**Comment by yanush** [comment]
this is what it looks like now:

```
/**
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {
	View,
	Text,
} from 'react-native';
import Animated from 'react-native-reanimated';

const {
	multiply,
	proc,
	Value,
} = Animated;

const myProc = proc((a, b) => multiply(a, b));

export default class App extends Component {
	animatedValue0 = new Value(0);
	animatedValue1 = new Value(1);

	constructor(props) {
		super(props);
	}

	render() {
		return (
			<View style={{
				flex: 1,
				backgroundColor: '#ffff00',
				alignItems: 'center',
				justifyContent: 'center',
			}}>
				<Text>Test</Text>
				<Animated.View style={{
					width: 100,
					height: 100,
					backgroundColor: '#0000ff',
					opacity: myProc(this.animatedValue0, this.animatedValue1),
				}}/>
			</View>
		);
	}
}
```
still getting an error: 

> proc is not a function

**Comment by terrysahaidak** [comment]
@yanush proc is available starting from 1.3.0-alpha, make sure you've upgraded.

**Comment by yanush** [comment]
@terrysahaidak 1.3.0-alpha is not released yet. i will wait for the release.
on a side note, I think it shouldn't be documented until it's released to avoid confusion

**Comment by terrysahaidak** [comment]
@yanush you're reading master's branch documentation, please refer to 1.2.0 one:
https://github.com/kmagiera/react-native-reanimated/tree/1.2.0

**Comment by chrfalch** [comment]
I think @yanush is right, @terrysahaidak - the README-file displayed on the project GitHub is from the master branch... So it says `proc` nodes are available.

**Comment by terrysahaidak** [comment]
@yanush sorry if my response looks rude :) 

@chrfalch You're right. I think the best option here is to add the notice to readme saying something like "You're reading master's branch documentation, please refer to the documentation of the version you're currently using" and add several latest releases links, because it's not always obvious for the user how to navigate to specific branch/tag readme.

Also, would be cool to have a [CHANGELOG](https://keepachangelog.com/en/1.0.0/) file which may contain unreleased and alpha release changes, because there is no any mention about 1.3.0 release in a releases page

/cc @kmagiera

**Comment by jakub-gonet** [comment]
Hi all,
I'm really sorry about docs version confusion. I don't think there's an easy way to version minor releases in docs, so the best solution to this is to check `.md` files / `README.md` (we transitioned recently to GH pages docs) directly by using a specific release tag.

We don't plan using CHANGELOG, we're using release notes in GH

I believe @yanush's problem was solved by @chrfalch and @terrysahaidak - thank you for your help 🎉 

If you have further questions don't hesitate to reopen this issue 🙂

**Comment by DanielWoldehana** [comment]
@jakub-gonet @chrfalch @terrysahaidak: I am getting error TypeError: proc is not a function (it is undefined), js engine: hermes

"react": "18.2.0",
"react-native": "0.73.1",
 "react-native-reanimated": "3.15.0",
 
 
<img width="402" alt="Screenshot 2024-08-07 at 11 33 36 AM" src="https://github.com/user-attachments/assets/3932bbf2-037f-4c8e-b6c2-8785db158cb5">

Error showing in screenshot seems to be from this file: /node_modules/react-native-redash/lib/module/v1/Math.js
I am on the latest version of react-native-reanimated so I am not sure why this is happening.

**Comment by NazmaD** [comment]
@DanielWoldehana Has the issue been resolved for you? I'm encountering the same problem
