### ISSUE TITLE
Cannot compare same arrays by reference in useAnimatedReaction: they are always different.

### ISSUE THREAD

**Issue by rozhkovs** [software-mansion/react-native-reanimated#3693]
### Description

Hey!
I use useAnimatedReaction to call various functions if needed. In the "prepare" function, I pass an object that contains a property with an array value. When I try to compare this property with the previous value by reference, I get false, although the array itself is the same.
Comparison with objects occurs correctly.

### Expected behavior
When comparing identical arrays by reference in useAnimatedReaction , the result is true.

### Steps to reproduce

1. Return an object containing a property with an array value in the "prepare" function.
2. The "prepare" function must be called 2 times. The array reference must be the same.
3. In the "react" function, compare the current property with the previous one.

### Snack or a link to a repository

https://snack.expo.dev/mKhShjUd31

### Reanimated version

3.0.0-rc.3

### React Native version

0.69.4

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 (iOS 16)

### Acknowledgements

Yes

**Comment by SergeyRozhkov** [comment]
The problem also manifests itself in [another environment](https://github.com/SergeyRozhkov/react-native-reanimated-3693)
Reanimated version: 3.0.0-rc.3.
React Native version: 0.70.3.
Architecture: Paper (Old Architecture)
JavaScript runtime: Hermes.
Device model: iPhoneSE (iOS 16)

**Comment by Latropos** [comment]
I've just tested and it looks that the problem is already solved in the newest reanimated 🥳 
```
 LOG  cur.trigger:  80 prev.trigger:  79
 LOG  cur.arrStt === prev.arrStt:  true
 LOG  cur.objStt === prev.objStt:  true
 LOG  cur.arrSv === prev.arrSv:  true
 LOG  cur.objSv === prev.objSv:  true
```
