### ISSUE TITLE
Performance issue when app contains multiple FlatLists.

### ISSUE THREAD

**Issue by pjc0247** [software-mansion/react-native-reanimated#3697]
### Description

We have `FlatList`s in almost every screen like below:
https://user-images.githubusercontent.com/1961216/196878160-188d648e-70b3-49f7-8966-3f275f15a05b.MP4

So there are stacked FlatLists under the screen, and I'm considering to use `LayoutAnimation` in every `ProductCard`.

However, putting the entering/exiting animations on all ProductCards causes serious performance issues and cannot be used.

I also know this is not a bug but a special case. But can I get a tip regarding optimization?
(react-freeze may have other unexpected issues, so we're not considering it right now.)

### Steps to reproduce

1. https://snack.expo.dev/ftHxGESkE
2. Works smoothly
3. change the `useReanimated` value to `true`.
4. You may see the performance spikes while scrolling.

### Snack or a link to a repository

https://snack.expo.dev/ftHxGESkE

### Reanimated version

2.11.0

### React Native version

0.69.0

### Platforms

iOS

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @pjc0247 !
You can try setting `getItemLayout` or limit number of elements to render (you can use `maxToRenderPerBatch`).
Also please update to Reanimated v3
