### ISSUE TITLE
Typo in documentation under Blocks

### ISSUE THREAD

**Issue by yanush** [software-mansion/react-native-reanimated#370]
There is a typo in the documentation under Blocks section:
> Blocks
> Blocks are just arrays of nodes that are being evaluated in a particular order and return the value of the last node. It can be created using block command but also when passed as an argument to other nodes the block command can be omitted and we can just pass a nodes array directly. See an example below:
> 
> cond(
>   eq(state, State.ACTIVE),
>   [
>     stopClock(clock),
>     set(transX, add(transX, diffX))
>   ],
>   runTiming(clock, state, config)
> )

runTiming is not a valid node, I'm assuming you meant:
> timing(clock, state, config)

**Comment by wcandillon** [comment]
No, in this case, it would be correct. But I agree that it might be confusing because we only see runTiming below in the documentation.
