### ISSUE TITLE
Require Cycle warning related to "useScrollViewOffset"

### ISSUE THREAD

**Issue by gp3gp3gp3** [software-mansion/react-native-reanimated#3703]
### Description

In version 2.11.0 reanimated is now throwing a warning about require cycles.

```
Require cycle: node_modules/react-native-reanimated/src/reanimated2/hook/index.ts -> node_modules/react-native-reanimated/src/reanimated2/hook/useScrollViewOffset.ts -> node_modules/react-native-reanimated/src/reanimated2/hook/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```
![IMG_44591E6437C2-1](https://user-images.githubusercontent.com/9616513/197024166-43183bba-ccfd-4053-8a12-dba9d091dae4.jpeg)

### Steps to reproduce

Upgrade reanimated to 2.11.0

### Snack or a link to a repository

Sorry

### Reanimated version

2.11.0

### React Native version

0.68.2

### Platforms

Android, iOS

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @gp3gp3gp3, thanks a lot for reporting this issue.

Indeed, there is a require cycle when using `useScrollViewOffset`.

We have a CI job that should detect circular dependencies but it looks like for some reason it didn't detect this specific require cycle in `src/` directory.

Fixed in #3713.
