### ISSUE TITLE
App build failure from monorepo  [expo/node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)]

### ISSUE THREAD

**Issue by joseito-terence** [software-mansion/react-native-reanimated#3711]
### Description

I'm unable to build the app. It throws an error.
It works fine with Expo Go, no issues there.

I've tried playing around with the version of react-native-reanimated but no luck

Error looks like this:

```
[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/apps/expo/node_modules/react-native-reanimated/android/build.gradle' line: 7
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':react-native-reanimated'.
[stderr] > /home/expo/workingdir/build/apps/expo/node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':expo'.
[stderr] > compileSdkVersion is not specified. Please add it to build.gradle
[stderr] * Try:
[stderr] Run with -stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] * Get more help at https://help.gradle.org/
[stderr] BUILD FAILED in 44s
```

### Steps to reproduce

1. git clone https://github.com/joseito-terence/build-error-repo.git
2. yarn
3. cd apps/expo
4. eas build -p android

### Snack or a link to a repository

https://github.com/joseito-terence/build-error-repo

### Reanimated version

2.3.1

### React Native version

0.64.3

### Platforms

Android

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, 2.3.1 is like 10 months old, please upgrade to 2.11.0 and re-open the issue if the problem persists.

**Comment by joseito-terence** [comment]
Hi, I've upgraded to 2.11.0, but the build still fails

````code
[stderr] FAILURE: Build failed with an exception.
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/apps/expo/node_modules/react-native-reanimated/android/build.gradle' line: 115
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':react-native-reanimated'.
[stderr] > [Reanimated] Unable to resolve react-native location in node_modules. You should project extension property (in app/build.gradle) `REACT_NATIVE_NODE_MODULES_DIR` with path to react-native.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 59s
```

**Comment by tomekzaw** [comment]
What's your setup for monorepo? Can you please describe the structure of directories (app directory, path to react-native node_modules, path to react-native-reanimated node_modules)? Note that you can override path to React Native node_modules by setting environment variable `REACT_NATIVE_NODE_MODULES_DIR`.

**Comment by joseito-terence** [comment]
You may check the monorepo here,
https://github.com/joseito-terence/build-error-repo

repo
  |---apps
  |        |----nextjs project
  |        |----expo project
  |---packages
  |        |----core

I checked the node_modules
react-native-reanimated isn't hoisted to the root node_modules of the workspace.
it exists in /apps/expo/node_modules
and react-native is in /node_modules
