### ISSUE TITLE
Data race on unsubscribeFromKeyboardEvents

### ISSUE THREAD

**Issue by chrisnojima** [software-mansion/react-native-reanimated#3712]
### Description

Hi,

I'm looking at some data races using tsan in xcode and believe there is an issue with the `REAKeyboardEventObserver`. 

The `_listeners` dictionary (https://github.com/software-mansion/react-native-reanimated/blob/main/ios/keyboardObserver/REAKeyboardEventObserver.m#L16) 

which is touched by `unsubscribeFromKeyboardEventsFunction` (https://github.com/software-mansion/react-native-reanimated/blob/main/ios/native/NativeProxy.mm#L335)

can happen on the non-main thread. There is no synchronizing going on so it's not thread safe. 

I can reliably get unsubscribe to mutate `_listeners` from a JS thread while `updateKeyboardFrame` is happening in the main thread.
(https://github.com/software-mansion/react-native-reanimated/blob/main/ios/keyboardObserver/REAKeyboardEventObserver.m#L102)

I'm not familiar with the code enough to put forward and PR, but thought I would point it out.

### Steps to reproduce

1. Enable the thread sanitizer in xcode
2. Push a view with a keyboard that uses the `useAnimatedKeyboard` hook
3. Pop the view
4. goto 2

### Snack or a link to a repository

sorry i don't have the time now to do this

### Reanimated version

2.11.0

### React Native version

0.69.6

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by chrisnojima** [comment]
Related PR: https://github.com/software-mansion/react-native-reanimated/pull/3263

**Comment by piaskowyk** [comment]
Thanks for your help investigation! This is so helpful! 🙌
