### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by xcoderreal** [software-mansion/react-native-reanimated#3723]
### Description

I followed the instructions at https://github.com/software-mansion/react-native-reanimated/tree/main/Example to build and run ios app locally, but got stuck at this error:

![image](https://user-images.githubusercontent.com/11373889/198105981-1421c237-256b-46d1-9292-e08fcef593ff.png)

### Steps to reproduce

1. Follow the instructions at https://github.com/software-mansion/react-native-reanimated/tree/main/Example
2. Run command all the way through `yarn react-native run-ios`

### Snack or a link to a repository

N/A

### Reanimated version

3.0.0-rc.3

### React Native version

0.70.3

### Platforms

iOS

### Acknowledgements

Yes

**Comment by xcoderreal** [comment]
A Snack or a link to GitHub repo isn't applicable here, since this is asking about running example code after cloning the whole `react-native-reanimated` repository.

**Comment by tomekzaw** [comment]
Hey, you need to run `yarn start` to start Metro bundler.

**Comment by xcoderreal** [comment]
Ah, you're right! Thanks and sorry for the noob question.

**Comment by tomekzaw** [comment]
`yarn start` is indeed missing in the README, so I updated the instructions in #3731. Thanks for noticing this.

**Comment by xcoderreal** [comment]
Thanks for updating.
