### ISSUE TITLE
null is not an object (evaluating '_ReanimatedModule.default.createNode')

### ISSUE THREAD

**Issue by roadmanfong** [software-mansion/react-native-reanimated#3725]
### Description

I installed react-native-animated@2.11.0
When start react native develop server, this error message show up.

In this version, I saw some typescript file in src, I'm wondering if this is the reason it can't work.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/2047789/198178198-cc2660f9-76b6-4fc5-9f37-4b7487cb4f41.png">

### Steps to reproduce

1. installed react-native-animated@2.11.0
2. expo start

### Snack or a link to a repository

nope

### Reanimated version

2.11.0

### React Native version

0.68.2

### Platforms

Android

### Workflow

Expo managed workflow

### Build type

Debug mode

### Device

Android emulator

### Device model

simulator pixel 4xl

### Acknowledgements

Yes

**Comment by sunnylqm** [comment]
react native supports ts long ago (like since 0.57?)
whenever you saw some native modules are null or undefined, most likely you haven't recompiled your project.

**Comment by roadmanfong** [comment]
Thanks for replying.
I developed with Expo client app, and the client app was built on EAS server.

I also tried to delete all node_modules and install again. 
and with command line `expo start -c` but It seems not work.

**Comment by sunnylqm** [comment]
For managed workflow you actually can not update any native modules (that's why it's called `managed`)

**Comment by roadmanfong** [comment]
I thought EAS build could let me switch some native modules. 
I use react-native-v8 and I need the last react-native-animated to make it work.

Is bare workflow the only way?

**Comment by roadmanfong** [comment]
I will try a different way to workaround.
