### ISSUE TITLE
Build from source doesn't generate same .so files

### ISSUE THREAD

**Issue by androideveloper** [software-mansion/react-native-reanimated#3733]
### Description

Hey! We recently needed to patch this package to try fixing ANRs on android, but the rn-patch of native didn't work. We enabled the [flag](https://github.com/software-mansion/react-native-reanimated/pull/2933) to force rebuild native to include patch changes too. While it works and successfully patches, the .so file generated is smaller in size compared to the .so files shipped with npm package. The app is still working and no animation issues so far. But what could be the reason of smaller .so files generated?

<img width="1172" alt="Screenshot 2022-10-27 at 20 44 51" src="https://user-images.githubusercontent.com/1249919/198623545-353fd05c-f935-49d0-96e6-07556876a522.png">

### Steps to reproduce

1. Enable gradle flag to force rebuild reanimated
`    reanimated = [
        buildFromSource: true
    ]`
2. Generate 2 apks with `buildFromSource` true and false.
3. Diff apks in Android Studio and compare .so file sizes

### Snack or a link to a repository

--

### Reanimated version

2.9.1

### React Native version

0.68.3

### Platforms

Android

### JavaScript runtime

Hermes

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, thanks for letting us know.

The first reason that comes to my mind is different NDK version. Before the release, we build the package (including AARs for Android) on CI with NDK r21d 21.3.6528147. Can you check if you use the same version? You can also send me these two .so files so I can compare and investigate them.

**Comment by androideveloper** [comment]
Hey. I'm not sure which version is used on CI, but locally I have `21.4.7075529`.
Please find attached 2 .so files. 
[Archive.zip](https://github.com/software-mansion/react-native-reanimated/files/9929262/Archive.zip)

**Comment by androideveloper** [comment]
How can we check debug symbols?

**Comment by tomekzaw** [comment]
Thanks for the attachment, gonna check it out soon.

> How can we check debug symbols?

You can run `file path/to/libreanimated.so` and check if it's `stripped` or `not stripped, with debug_info`.

The second option is to list all symbols with `nm path/to/libreanimated.so` or only debug symbols with `nm -D path/to/libreanimated.so`. You can also pass `-C` flag to demangle function signatures.

**Comment by androideveloper** [comment]
Thanks for the investigation! 21 is the min sdk for us, could it be that other unused part (16-21) is removed then?

**Comment by androideveloper** [comment]
> ABI_ANDROID_API: 16
what is the min sdk of reanimated? where is this abi defined?

**Comment by tomekzaw** [comment]
> could it be that other unused part (16-21) is removed then?

Not sure. Can you try building the app with `minSdkVersion` 16?

**Comment by androideveloper** [comment]
Unfortunately it won't work :/ It's too big and a lot of libs don't support min sdk 16. What about you trying bump min sdk to 21 and rebuilding reanimated?

**Comment by tomekzaw** [comment]
If your app uses `minSdkVersion = 21`, then `safeExtGet("minSdkVersion", 16)` still returns 21, so that's okay.

I've performed the following experiment:

1. Build libreanimated.so from source in a fresh RN app:

```sh
npx react-native@next init MyApp --version 0.68.3
cd MyApp
yarn add react-native-reanimated@2.12.0
code android/app/build.gradle
# add project.ext.reanimated = [ buildFromSource: true ]
yarn react-native run-android
find . -name "*.apk"
unzip ./android/app/build/outputs/apk/debug/app-debug.apk
du -sh ./lib/arm64-v8a/libreanimated.so  # 2,4M
file ./lib/arm64-v8a/libreanimated.so  # stripped
```

2. Build libreanimated.so for react-native-reanimated package

```sh
git clone https://github.com/software-mansion/react-native-reanimated
cd react-native-reanimated
git checkout 2.12.0
yarn && cd Example && yarn && cd ..
code createNPMPackage.sh
# replace: versions=("0.68.3")
# replace: version_name=("68")
# replace: for index in {0..0}
./createNPMPackage.sh
tar -xvf ./react-native-reanimated-2.12.0.tgz
unzip ./package/android/react-native-reanimated-68-jsc.aar
du -sh jni/arm64-v8a/libreanimated.so  # 5,2M
file jni/arm64-v8a/libreanimated.so  # not stripped
```

For some reason, the shared library from prebuilt .aar within react-native-reanimated package published on npm is not stripped. This, however, doesn't replicate the original issue as both files in Archive.zip are stripped.

**Comment by androideveloper** [comment]
Ah, nice! Yeah, that is a separate issue then.
What I asked in the message above was trying to rebuild reanimated in a fresh app with 
`minSdkVersion safeExtGet("minSdkVersion", 16) `replaced with 
` minSdkVersion safeExtGet("minSdkVersion", 21) `
. Or just providing minSdkVersion in the fresh app (16 and 21).

**Comment by androideveloper** [comment]
Comparing min sdk 16 and 21 in a fresh app will provide the answer to the original issue

**Comment by tomekzaw** [comment]
> Or just providing minSdkVersion in the fresh app (16 and 21).

React Native 0.68.3 (the version you stated in the issue description) won't let you build the app with `minSdkVersion = 16`. On the other hand, if I replace `minSdkVersion safeExtGet("minSdkVersion", 16)` in Reanimated's build.gradle, it will still read project `minSdkVersion` which is 21.

**Comment by androideveloper** [comment]
Gotcha. But the .so filed that is currently prebuilt in the npm package is ABI_ANDROID_API = 16. My idea with bumping 
`minSdkVersion safeExtGet("minSdkVersion", 16)` to `minSdkVersion safeExtGet("minSdkVersion", 21)` is to try building new temp npm package and see the diff.

**Comment by androideveloper** [comment]
As you mentioned above:

> $ python3 parse_elfnote.py libreanimated_original.so   
----------ABI INFO----------
ABI_ANDROID_API: 16
ABI_NDK_VERSION: r21e
ABI_NDK_BUILD_NUMBER: 7075529


this 16 is probably coming from this line
https://github.com/software-mansion/react-native-reanimated/blob/8933a00fce0fa2b3f636c83f75ad708bfbb3e9d0/android/build.gradle#L439

**Comment by androideveloper** [comment]
When npm package is built (I guess this file https://github.com/software-mansion/react-native-reanimated/blob/2.9.1/createNPMPackage.sh), it doesn't have `minSdkVersion ` passed and takes the default 16 specified in gradle file

**Comment by tomekzaw** [comment]
@androideveloper I've build the package locally on the commit from v2.9.1 but I'm getting `ABI_ANDROID_API: 21`. I expected this to be `ABI_ANDROID_API: 16`, like for `libreanimated_original.so`.

**Comment by androideveloper** [comment]
hmm :/ could you please check this .so file? This is what we shipped to  Play Store before enabling "build from source". Which should be using 68-hermes aar.

[libreanimated.so.zip](https://github.com/software-mansion/react-native-reanimated/files/9937897/libreanimated.so.zip)

**Comment by tomekzaw** [comment]
```
----------ABI INFO----------
ABI_ANDROID_API: 16
ABI_NDK_VERSION: r21e
ABI_NDK_BUILD_NUMBER: 7075529
```

Are you sure this is 2.9.1? Honestly I don't know what's happening here 😢

**Comment by androideveloper** [comment]
yes `"react-native-reanimated": "2.9.1"` 🤔

**Comment by androideveloper** [comment]
so just to verify, is it possible to create npm package with this line changed?
`minSdkVersion safeExtGet("minSdkVersion", 21) `

**Comment by androideveloper** [comment]
just a temp one, branching out from 2.9.1 version

**Comment by androideveloper** [comment]
Found this link where it describes how this works: https://developer.android.com/ndk/guides/application_mk#app_platform
>APP_PLATFORM declares the Android API level this application is built against and corresponds to the application's minSdkVersion.

I still think that reanimated is targeting min sdk 16 and when we rebuild we target min sdk 21 and that explains the diff

**Comment by cw-sanjeev** [comment]
@androideveloper we too are facing issues related to libanimated.so
```
Crashed: Thread: SIGSEGV  0x0000000000000045
#00 pc 0xc5c1e libreanimated.so (BuildId: 21982f237e63616997fced4de3d0be95dd988e27)
```

Were you able to solve this issue?

**Comment by androideveloper** [comment]
Our original problem was ANR which we fixed by patching, your issue looks like a crash, could be a different thing.

**Comment by piaskowyk** [comment]
Since we dropped support for Reanimated 2 and do not ship prebuilt binaries in v3, I believe this issue is no longer relevant. For anyone with that problem I recommend to upgrade Reanimated to the latest version.
