### ISSUE TITLE
`withTiming` should have an option to interpolate colors

### ISSUE THREAD

**Issue by pvinis** [software-mansion/react-native-reanimated#3735]
### Description

Seeing that https://github.com/software-mansion/react-native-reanimated/issues/2193#issuecomment-1100198265 is the best way to do color change with a `withTiming`, we should really have a way to do that without this whole code. Ideally we should have something like:

```
const textColor = useSharedValue("blue")
const textAnim = useAnimatedStyle(() => ({
  color: withTiming(textColor.value, { duration: 200, interpolation: "color" }),
}))

return <Text style={textAnim}>wow</Text>
```

### Steps to reproduce

Working with colors is hard.

### Snack or a link to a repository

N/A

### Reanimated version

2.12.0

### React Native version

0.69.0

### Platforms

iOS

### Acknowledgements

Yes

**Comment by graszka22** [comment]
Hey, `withTiming` should interpolate colors out of the box. In this PR https://github.com/software-mansion/react-native-reanimated/pull/3891 I added an example and verified it works: 
```js
function DefaultInterpolation({
  color1,
  color2,
}: {
  color1: string;
  color2: string;
}) {
  const color = useSharedValue(color1);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      backgroundColor: withTiming(color.value, { duration: 500 }),
    };
  });

  return (
    <View>
      <Text>Default:</Text>
      <View style={styles.colorContainer}>
        <Animated.View style={[styles.bigbox, animatedStyle]} />
        <Button
          onPress={() => {
            color.value = color2;
          }}
          title="run animation"
        />
      </View>
    </View>
  );
}
```
