### ISSUE TITLE
interpolateColor input and output range required > 2

### ISSUE THREAD

**Issue by lmasneri** [software-mansion/react-native-reanimated#3749]
### Description

The app crash as interpolateColor require array with AT LEAST two element but the error says that the inputRange or outputRange must be > 2. It should be >= 2.

### Steps to reproduce

Create sharedValue with a number.
Create animatedStyle with interpolate color as following:
```
const backgroundColor = interpolateColor(
      noteBackgroundColor.value,
      [0, 1],
      ['red', 'white'],
    )
```
Create a `<Animated.View style={animatedStyle} />`

### Snack or a link to a repository

https://snack.expo.dev/@lmasneri/animated-interpolatecolor-crash

### Reanimated version

2.9.1

### React Native version

0.68.4

### Platforms

Android, iOS

### Device model

iPhone 14 (iOS 16)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @lmasneri, thanks for reporting this issue.

Would you be so kind to submit a PR that improves the error message?

**Comment by lmasneri** [comment]
> 

Hello, yes I can, but it is not an error message issue. It is detect as an error whereas it is not one.

**Comment by lmasneri** [comment]
> Hey @lmasneri, thanks for reporting this issue.
> 
> Would you be so kind to submit a PR that improves the error message?

Hello, yes I can, but it is not an error message issue. It is detect as an error whereas it is not one.

**Comment by lmasneri** [comment]
@tomekzaw  ?

**Comment by graszka22** [comment]
Hey, I tested your snack and it's working for me (no error message at all, even when only two values are passed to `interpolateColor`). Furthermore the logic and message seems correct to me https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/interpolation.ts#L153-L157 (`interpolateColor` uses `interpolate`)

**Comment by lmasneri** [comment]
> 

Seems to be fixed too, I don't have the issue anymore
