### ISSUE TITLE
PanGestureEvent visual misrepresentation on start

### ISSUE THREAD

**Issue by nadiemedicejose** [software-mansion/react-native-reanimated#3751]
### Description

Hi team,

I just wanted to report a bug on PanGestureEvent start, the switch displays an instantaneous selection to the MIC state and then moves completely down to the INT state. Attached to this, you can find a video of this gesture in action. As you can see, it doesn't happen when moving up to the MIC.

I expect the knob to move without this glitch and go straight to the INT state.

Thank you in advance!
Jose

https://user-images.githubusercontent.com/44657605/200446195-1e575848-fd81-4406-9798-fb1f6dcfa679.mp4

### Steps to reproduce

1. Do a pan gesture movement to the bottom using the knob handler.

### Snack or a link to a repository

https://github.com/nadiemedicejose/pangestureevent-switch-handler

### Reanimated version

^2.11.0

### React Native version

0.70.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy Tab A7 Lite

### Acknowledgements

Yes

**Comment by nadiemedicejose** [comment]
Will update the repo tomorrow 😄

**Comment by Bijiabo** [comment]
I faced the same problem. By looking at the data, the batch events for `onActive` will not trigger for the first 10px when moving

**Comment by nadiemedicejose** [comment]
I have fixed this by implementing an if-else-if clause:

```jsx
		onActive: (event, context) => {
			translateY.value = event.translationY + context.translateY;
			if (translateY.value > DEFAULT_POSITION) {
				translateY.value = INT_ACTIVE_POSITION;
				runOnJS(setMicSwitchPos)('10');
			} else if (translateY.value < DEFAULT_POSITION) {
				translateY.value = MIC_ACTIVE_POSITION;
				runOnJS(setMicSwitchPos)('01');
			}
		},
```

Previous version was just an if-else:

```jsx

		onActive: (event, context) => {
			translateY.value = event.translationY + context.translateY;
			if (translateY.value > DEFAULT_POSITION) {
				translateY.value = INT_ACTIVE_POSITION;
				runOnJS(setMicSwitchPos)('10');
			} else {
				translateY.value = MIC_ACTIVE_POSITION;
				runOnJS(setMicSwitchPos)('01');
			}
		},

```
