### ISSUE TITLE
Invalid `RNReanimated.podspec` file: no implicit conversion of nil into Array. IOS when updating from reanimated 2.8.0 to 2.12.0

### ISSUE THREAD

**Issue by FrozenPyrozen** [software-mansion/react-native-reanimated#3754]
### Description

When update reanimated from `2.8.0` to `2.12.0` got error when installing pods, also update to reanimated `2.9.0` gives the same error:
```
`npx pod-install`
Scanning for pods...
1.11.3
> pod install

[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: no implicit conversion of nil into Array.

 #  from /Users/admin/Projects/test_project/node_modules/react-native-reanimated/RNReanimated.podspec:6
 #  -------------------------------------------
 #  config = find_config()
 >  assert_no_multiple_instances(config)
 #  assert_no_reanimated2_with_new_architecture(reanimated_package_json)
 #  -------------------------------------------
.

 #  from /Users/admin/Projects/test_project/ios/Podfile:8
 #  -------------------------------------------
 #  target 'MobileWebWallet' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...
> pod install --repo-update

[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: no implicit conversion of nil into Array.

 #  from /Users/admin/Projects/test_project/node_modules/react-native-reanimated/RNReanimated.podspec:6
 #  -------------------------------------------
 #  config = find_config()
 >  assert_no_multiple_instances(config)
 #  assert_no_reanimated2_with_new_architecture(reanimated_package_json)
 #  -------------------------------------------
.

 #  from /Users/admin/Projects/test_projectt/ios/Podfile:8
 #  -------------------------------------------
 #  target 'MobileWebWallet' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: no implicit conversion of nil into Array.

 #  from /Users/admin/Projects/test_project/node_modules/react-native-reanimated/RNReanimated.podspec:6
 #  -------------------------------------------
 #  config = find_config()
 >  assert_no_multiple_instances(config)
 #  assert_no_reanimated2_with_new_architecture(reanimated_package_json)
 #  -------------------------------------------
.

 #  from /Users/admin/Projects/test_project/ios/Podfile:8
 #  -------------------------------------------
 #  target 'MobileWebWallet' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Steps to reproduce

1. Got "react-native-reanimated": "^2.8.0",
2. Update "react-native-reanimated": "^2.12.0",

### Snack or a link to a repository

no link

### Reanimated version

2.8.0

### React Native version

0.69.4

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by VihangaAW** [comment]
I am also getting this error when I tried to update from `2.10.0` to `2.12.0`

**Comment by rahul26496** [comment]
I am also facing same issue today, yesterday it was working fine.

**Comment by lorenzomilesi** [comment]
Same problem here. What I tried:
```
pod deintegrate
pod repo update
pod install
```
I also deleted Podfile.lock with no luck. Even reinstalling the previous version I had (1.13.x) leads me to a failure.

**Comment by ibrahimmemonn** [comment]
**For those using RBENV for managing ruby versions, whenever you install a different ruby version and then you'll be faced with the following error(not 100% same lol):**

```
gem update --system
bundle update --bundler
```

**Both these commands will be helpful in fixing the issue.**

**Comment by JFmagicoder** [comment]
It took me hours but in my case, the issue was having space in the project name.  
i.e ABC Project 
Changing that to ABCProject worked for me. I know it's a bit weird, but this worked for me twice.

**Comment by munsifhayat** [comment]
It took me hours but in my case, the issue was having space in the project name.
i.e ABC Project
Changing that to ABCProject worked for me. I know it's a bit weird, but this worked for me twice.

**Comment by jfkm69** [comment]
Looks like the problem lies here (https://github.com/software-mansion/react-native-reanimated/blob/05c93b02ede93950904812239fbe95366e372ab6/scripts/reanimated_utils.rb#L63), its possible that we can have multiple instances of react-native-reanimated in the same node_modules directory. Suggested fix is here: https://github.com/software-mansion/react-native-reanimated/pull/3774

**Comment by ali-husnain** [comment]
Anyone please help me after upgrading expo sdk 46 to 47 with `react-native-reanimated 2.12.0` my ios build failed.
Also having this
 ```
"expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
  }
```

![image](https://user-images.githubusercontent.com/56598032/207917963-07edbdb3-97c0-4911-addd-e594c606b686.png)

**Comment by AbdulmalekAlshugaa** [comment]
Hi guys, anyone still face this issue, please advise , almost one day without lack to fix it up

**Comment by rohit1345** [comment]
same issue , i'm also facing, suggest me a solution.

**Comment by SamithaMaddekanda** [comment]
Invalid `Podfile` file: 
Invalid `RNReanimated.podspec` file: different prefix: ""  while trying to do pod install 

 reanimated_package_json = JSON.parse(File.read(File.join(__dir__, "package.json")))
 >  config = find_config()
 #  assert_no_multiple_instances(config)

Currently  using  react-native-reanimated  "^2.13.0"

Did anybody get this issue?

**Comment by rohit1345** [comment]
> Invalid `Podfile` file: Invalid `RNReanimated.podspec` file: different prefix: "" while trying to do pod install
> 
> reanimated_package_json = JSON.parse(File.read(File.join(**dir**, "package.json")))
> 
> > config = find_config()
> 
> # assert_no_multiple_instances(config)
> Currently using react-native-reanimated "^2.13.0" (latest)
> 
> Did anybody get this issue?

i'm also facing same issue.

**Comment by jfkm69** [comment]
The issue you are facing is occurs when you have multiple instances of RNAnimated (https://docs.swmansion.com/react-native-reanimated/docs/next/fundamentals/troubleshooting/#multiple-versions-of-reanimated-were-detected) and it has been described here (https://github.com/software-mansion/react-native-reanimated/pull/3774). TLDR; there's a problem with the `assert_no_multiple_instances` function in this file (https://github.com/software-mansion/react-native-reanimated/blob/05c93b02ede93950904812239fbe95366e372ab6/scripts/reanimated_utils.rb). The fix is available in this release (https://github.com/software-mansion/react-native-reanimated/releases/tag/3.0.0-rc.7) but its still a pre-release candidate so I'm not sure how stable it is to use in production code. You can always just apply the changes in this PR (https://github.com/software-mansion/react-native-reanimated/pull/3774) to your node_modules folder and persist them using [patch-package](https://www.npmjs.com/package/patch-package) or something similar.

**Comment by vizsatiz** [comment]
@jfkm69 This worked for me, lots of thanks. But now I have to wait for a stable version of the lib. 

I did the patch-package fix and latest rc version was giving me other issues

**Comment by ledesmaromeo** [comment]
Hi all 👋 I have managed to fix this issue on my machine by doing the following:

1. `brew uninstall cocoapods`
2. `gem install cocoapods -v 1.10.1` (I'm using `rbenv` to manage my Ruby versions by the way)
3. Navigate to the `ios` directory
4. `pod install`

Hope someone else finds this useful! 🤞

**Comment by rhkdgns95** [comment]
@jfkm69 thank you i solved it thanks to you!

**Comment by piaskowyk** [comment]
Should be fixed in 2.14.0 and in 3.0.0-rc.10

**Comment by Aaron5277** [comment]
> Should be fixed in 2.14.0 and in 3.0.0-rc.10

That's works for me , 2.12.0 => 2.14.0.

**Comment by codekojo** [comment]
Check if you have spaces in your path.

Example: /Users/me/Documents/Github/Sample Project/reactnativeproject

**Comment by pedrodaltoe** [comment]
> I am also getting this error when I tried to update from `2.10.0` to `2.12.0` I had to update due to #3743, now Android app builds without any errors but `pod install` fails

Thank so much, you helped me!
