### ISSUE TITLE
CMake Error at CMakeLists.txt:61 (add_library):

### ISSUE THREAD

**Issue by orchsik** [software-mansion/react-native-reanimated#3756]
### Description

I use "react-native-reanimated": "2.12.0",

### When I do "npx react-native run-android" I get the following error:
```
CMake Error at CMakeLists.txt:61 (add_library):
Legacy variable expansion in source file
"{MY_PROJECT_ROOT}\node_modules\react-native/ReactCommon/jsi/jsi/jsi.cpp"
expanded to "D:
epo_rmsa
msa-android
```

### I cleaned the project and did it.
```
rm -rf node_modules
rm -rf yarn.lock
cd android &&  ./gradlw clean
```

### Steps to reproduce

npx react-native run-android

### Reanimated version

2.12.0

### React Native version

0.64.0

### Platforms

Android

### Build type

Debug mode

### Device

Real device

**Comment by piccinnigius** [comment]
the same

**Comment by Rk5422686** [comment]
I hit on the same error I have tried downgrading the version to react-native-reanimated": **"^1.13.1"** and it worked.

**Comment by piaskowyk** [comment]
Hey 👋 Which CMake version do you use?
