### ISSUE TITLE
[Android] Views with exiting layout animations aren't removed immediately when a stack screen is popped

### ISSUE THREAD

**Issue by jwajgelt** [software-mansion/react-native-reanimated#3757]
#### Current behaviour
When a screen containing components with `exiting` layout animations is popped from a stack navigator, the views disappear, but remain mounted in the view hierarchy until their animations end.
You can see these views aren't unmounted by using the Layout Inspector tool.

This issue prevents interacting with the UI covered by these invisible views, which is especially noticeable with long exiting animations.

#### Expected behaviour
When a screen is popped, all of the components on that screen should be removed immediately, without running their exiting animations

### Steps to reproduce

In the snack:
1. Press the button to go to the "Test" screen.
2. Go back to the "Home" screen.
3. Try pressing the button to go to the "Test" screen again. 
The button will be unresponsive for roughly 20 seconds, while the view from the "Test" screen finishes its `exiting` animation
4. After 20 seconds, the button should work again.

### Snack or a link to a repository

https://snack.expo.dev/@jwajgelt/long-exiting-layout-animation-causes-views-to-not-be-unmounted-when-screen-is-popped

### Reanimated version

2.9.1

### React Native version

0.70.5

### Platforms

Android

### Acknowledgements

Yes

**Comment by rhernand3z** [comment]
Seeing the same issue on Android for me as well
