### ISSUE TITLE
AnimatedFlatList jumped to the first when I update it's data

### ISSUE THREAD

**Issue by Tohid1999** [software-mansion/react-native-reanimated#3764]
### Description

When `AnimatedFlatList` reached to end I just update it's data.
but immediately after that it jump to the first of list.

This just happened with `AnimatedFlatList` and normal `FlatList` works fine

```
const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);

return (
  <AnimatedFlatList
       scrollEventThrottle={1}
       data={data}
       keyExtractor={item => item.id}
       onEndReached={({distanceFromEnd}) => {
         if (distanceFromEnd < 0) {
            return;
         }
         fetchMoreData();
       }}
  />
)
```

### Steps to reproduce

Just scroll to the end of list

### Snack or a link to a repository

https://snack.expo.dev/@tohid_t/animatedflatlist

### Reanimated version

2.12.0

### React Native version

0.70.4

### Platforms

Android

### Acknowledgements

Yes

**Comment by Latropos** [comment]
@Tohid1999 Hi! It looks that there is no bug and in fact both FlatList and AnimatedFlatList work the same way.

 Please notice that the following line was located inside function App():
```tsx
  const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);
 ```
 It means, that you re-define `AnimatedFlatList` each time state inside `App` changes, so the `AnimatedFlatList` has to be rendered once again.
 
 Please move the above-mentioned line of code out of `App` or use `Animated.FlatList` component for even simpler use and it should work as expected.


https://github.com/software-mansion/react-native-reanimated/assets/56199675/b2427e3a-cc26-4a9d-991c-0902ce4b3141
