### ISSUE TITLE
react_ native_ minor_ The version value cannot always be taken from our own build of react native

### ISSUE THREAD

**Issue by jamninetyfive** [software-mansion/react-native-reanimated#3767]
### Description

react_ native_ minor_version value cannot always be taken from our own build of react native version was 1000

### Steps to reproduce

1.get react-native own version react-native@1000.0.0-1183bbe92.
2.yarn add react-native-reanimated@2.12.0
3.cd ios && pod install 
4.xcode run.

#if DREACT_NATIVE_MINOR_VERSION < 63
#import <ReactCommon/BridgeJSCallInvoker.h>
#endif

get this error. but our rn version was base on 0.66.4.
'ReactCommon/BridgeJSCallInvoker.h' file not found

### Snack or a link to a repository

none

### Reanimated version

2.12.0

### React Native version

react-native@1000.0.0-1183bbe92

### Platforms

iOS

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! Sorry but we unfortunately  don't support custom RN build. Please se supported React Native versions here: https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility
