### ISSUE TITLE
[2.13.0] Invalid `RNReanimated.podspec` file: no implicit conversion of nil into Array.

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#3779]
### Description

After upgrading to `2.13.0` it throws the error below. I've `rm -rf Pods`, `rm Podfile.lock`, `pod install` and the issue persists. 

```ruby
[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: no implicit conversion of nil into Array.

 #  from /Users/stathis/WebstormProjects/xxxxxx/node_modules/react-native-reanimated/RNReanimated.podspec:6
 #  -------------------------------------------
 #  config = find_config()
 >  assert_no_multiple_instances(config)
 #  assert_no_reanimated2_with_new_architecture(reanimated_package_json)
 #  -------------------------------------------
.

 #  from /Users/stathis/WebstormProjects/xxxxx/ios/Podfile:25
 #  -------------------------------------------
 #  target 'xxxx' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

full `Podfile`: 

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

IS_CI = ENV['APPCENTER_BUILD_ID']

# Define find-and-replace function
# def find_and_replace(dir, findstr, replacestr)
#  Dir[dir].each do |name|
#      text = File.read(name)
#      replace = text.gsub(findstr,replacestr)
#      replaced = text.index(replacestr)
#      if replaced == nil && text != replace
#          puts "Fix: " + name
#          File.open(name, "w") { |file| file.puts replace }
#          STDOUT.flush
#      end
#  end
#  Dir[dir + '*/'].each(&method(:find_and_replace))
#end

target 'xxxx' do
	config = use_native_modules!

	# Flags change depending on the env values.
	flags = get_default_flags()

	use_react_native!(
		:path => config[:reactNativePath],
		# to enable hermes on iOS, change `false` to `true` and then install pods
		:hermes_enabled => true,
		:fabric_enabled => flags[:fabric_enabled],
		# An absolute path to your application root.
		:app_path => "#{Pod::Config.instance.installation_root}/.."
	)

	permissions_path = '../node_modules/react-native-permissions/ios'

	pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
	pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
	pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
	pod 'FlipperKit/SKIOSNetworkPlugin', '=' + "0.162.0"


	use_native_modules!

	pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'

	# Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
	# you should disable these next few lines.
	if not IS_CI
		use_flipper!({ 'Flipper' => '0.162.0' })
		pod 'RNLocalize', :path => '../node_modules/react-native-localize'

	end
	post_install do |installer|
		react_native_post_install(installer)
		installer.pods_project.targets.each do |target|

			if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
				target.build_configurations.each do |config|
					config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
				end
			end
		end
		# # to build for the simulator on Apple M1
		# installer.pods_project.targets.each do |target|
		#   target.build_configurations.each do |config|
		#     # disables arm64 builds for the simulator
		#     config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
		#   end
		# end

		#find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
		#"atomic_notify_one(state)", "folly::atomic_notify_one(state)")

		#find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
		#"atomic_wait_until(&state, previous | data, deadline)", "folly::atomic_wait_until(&state, previous | data, deadline)")

		installer.pods_project.build_configurations.each do |config|
			if config.name == 'Release'
				config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
			end
		end
	end
end

```

### Steps to reproduce

1. Update to `2.13.0`
2. Pod install

### Snack or a link to a repository

no snack

### Reanimated version

2.13.0

### React Native version

0.68.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
downgrading to `2.12.0` works fine.

**Comment by tomekzaw** [comment]
Hey @efstathiosntonas, thanks for reporting this issue.

Can you please check if the following patch for `RNReanimated.podspec` resolves this issue on 2.13.0?

```diff
-config = find_config()
+reanimated_config = find_config()
-assert_no_multiple_instances(config)
+assert_no_multiple_instances(reanimated_config)
```

**Comment by efstathiosntonas** [comment]
@tomekzaw it throws the same arror.

These are the applied changes:

```ruby
reanimated_package_json = JSON.parse(File.read(File.join(__dir__, "package.json")))
# config = find_config()
reanimated_config = find_config()
# assert_no_multiple_instances(config)
assert_no_multiple_instances(reanimated_config)
assert_no_reanimated2_with_new_architecture(reanimated_package_json)
```

**Comment by efstathiosntonas** [comment]
@tomekzaw found the culprit, had nothing to do with reanimated, I had a resolution on package.json pointing to 2.12.0. Damn I hate monorepos and the 100 package.json files. Sorry for the inconvenience.

**Comment by eegbunam** [comment]
@efstathiosntonas When yo found the resolution in your package.json what did you do? I am running into this same issue

**Comment by efstathiosntonas** [comment]
@eegbunam make sure that the resolution version is the same as in your dependencies. That’s the only thing to do.

**Comment by eegbunam** [comment]
@efstathiosntonas Thanks for the help! This let me progress to my next error. for anyone running into this. Go to your package.json and add another key called resolutions. 


Something like this:

{
  "name": "approachablenative",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@ant-design/react-native": "^5.0.0",
    "@bothrs/expo-mixpanel-analytics": "^2.0.0",
    "@emailjs/browser": "^3.6.2",
    "@expo-google-fonts/inter": "^0.2.2",
    "@expo-google-fonts/poppins": "^0.2.2",
    "@gorhom/bottom-sheet": "^4",
    "@maksymblank/react-native-date-input": "^1.0.1",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-native-community/geolocation": "^2.1.0",
    "@react-native-firebase/app": "^14.5.0",
    "@react-native-google-signin/google-signin": "^7.0.4",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "axios": "^0.27.2",
    "dayjs": "^1.11.1",
    "expo": "^47.0.0",
    "expo-app-loading": "~2.1.1",
    "expo-apple-authentication": "~5.0.1",
    "expo-auth-session": "~3.8.0",
    "expo-build-properties": "~0.4.1",
    "expo-camera": "~13.1.0",
    "expo-dev-client": "~2.0.1",
    "expo-device": "~5.0.0",
    "expo-font": "~11.0.1",
    "expo-google-app-auth": "~8.3.0",
    "expo-google-sign-in": "~10.1.0",
    "expo-image-manipulator": "~11.0.0",
    "expo-image-picker": "~14.0.2",
    "expo-location": "~15.0.1",
    "expo-notifications": "~0.17.0",
    "expo-permissions": "~14.0.0",
    "expo-random": "~13.0.0",
    "expo-status-bar": "~1.4.2",
    "firebase": "^9.6.9",
    "formik": "^2.2.9",
    "lottie-ios": "^3.2.3",
    "lottie-react-native": "5.1.4",
    "moment": "^2.29.3",
    "radio-buttons-react-native": "^1.0.4",
    "radio-buttons-react-native-expo": "^1.1.0",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-animatable": "^1.3.3",
    "react-native-autoscroll-flatlist": "^1.11.1",
    "react-native-elements": "^3.4.2",
    "react-native-fast-image": "^8.5.11",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-keyboard-avoiding-scroll-view": "^1.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.3.2",
    "react-native-maps-directions": "^1.8.0",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-pager-view": "6.0.1",
    "react-native-paper": "^4.12.1",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "2.12.0",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-root-toast": "^3.3.1",
    "react-native-safe-area-context": "4.4.1",
    "react-native-scalable-image": "^1.1.0",
    "react-native-screens": "~3.18.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-skeleton-content": "^1.0.24",
    "react-native-svg": "13.4.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-switch": "^1.5.1",
    "react-native-tab-view": "^3.1.1",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-web": "~0.18.7",
    "react-redux": "^7.2.8",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "uuid": "^8.3.2",
    "yup": "^0.32.11"
  },
  "resolutions": {
    "react-native-reanimated": "2.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3"
  },
  "private": true
}


**As you can see I have resolutions under dependencies**
