### ISSUE TITLE
[Android] Section List performance issues

### ISSUE THREAD

**Issue by michalsek** [software-mansion/react-native-reanimated#3785]
### Description

Reanimated seems to cause performance issues for inverted SectionList on android 13. After some time of scrolling back end forth the UI and JS thread fps fall down to almost 0. The performance drop doesn't happen when reanimated ins't installed in the project.

https://user-images.githubusercontent.com/9112173/202222914-e66662cf-476d-4b45-85c7-d2aad3bef2bb.mov

Tested on react-native `0.69` and `0.70`. 
Happens on real device as well as emulator, both on debug and release builds.
Probably occurs also on some earlier android versions, but it takes way longer time to reproduce it. 

### Steps to reproduce

1. Run the example application from the linked repository
2. Scroll up and down for some time, the drop will eventually happen, but it isn't deterministic

### Snack or a link to a repository

https://github.com/michalsek/secionlistbugrepro

### Reanimated version

2.12.0

### React Native version

0.69.6, 0.70.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 5 API 33

### Acknowledgements

Yes

**Comment by smali-kazmi** [comment]
I am very disappoint with react native community seems like it is a good time to move to other framework because on Samsung Device React native Text Inputs don't work properly now SelectionList

**Comment by Latropos** [comment]
Hi! After testing I've found out that you were mistaken and the bug happens when our library is not installed.
In fact it is a known bug and there are many open issues in react-native (like this one: https://github.com/facebook/react-native/issues/35350).
Closing, since this is not related to react-native-reanimated at all.
