### ISSUE TITLE
3.0.0.rc6 crashes on application load

### ISSUE THREAD

**Issue by rexpeditionco** [software-mansion/react-native-reanimated#3793]
### Description

I migrated a previously working react-native-animated project from 2.9.1. to 3.0.0.rc6 and it just crashes the second the app loads. Are there migration steps that are necessary?

### Steps to reproduce

migrate a 2.9.1 expo project to 3.0.0.rc6

### Snack or a link to a repository

n/a

### Reanimated version

3.0.0.rc6

### React Native version

0.69.6

### Platforms

iOS

### Device

iOS simulator

### Device model

iphone 13 pro

### Acknowledgements

Yes

**Comment by channeladam** [comment]
I just tried rc6 and get an error on the first screen that does
``` const AnimatedView = Animated.createAnimatedComponent(View); 
![image](https://user-images.githubusercontent.com/655569/202637537-bd25fdec-dac8-49b1-961a-26b8720def77.png)

**Comment by tomekzaw** [comment]
> migrate a 2.9.1 expo project to 3.0.0.rc6

Hey, do you use Expo managed workflow?

**Comment by fendermany** [comment]
Hi, I use expo managed workflow and same too, can't load app, crashed after complete building.

**Comment by tomekzaw** [comment]
If you use Expo managed workflow, you cannot use different version of Reanimated than the one bundled into Expo SDK. That's because Reanimated contains native code which needs to be compiled and the JS part needs to match the interface of native functions.

**Comment by fendermany** [comment]
> If you use Expo managed workflow, you cannot use different version of Reanimated than the one bundled into Expo SDK. That's because Reanimated contains native code which needs to be compiled and the JS part needs to match the interface of native functions.

I didn't quite understand what this means: do I have to rebuild the build for development or does my sdk(46) not support this?

**Comment by tomekzaw** [comment]
You need to rebuild the native app, see https://docs.expo.dev/introduction/managed-vs-bare/#what-happens-if-i-run-up-against

**Comment by channeladam** [comment]
fyi, I use Expo bare, RN 0.68.5

**Comment by rexpeditionco** [comment]
I have tried dev builds which to my understanding should support this also.

**Comment by rexpeditionco** [comment]
> You need to rebuild the native app, see https://docs.expo.dev/introduction/managed-vs-bare/#what-happens-if-i-run-up-against

Thats what im doing, still crashes on load

**Comment by fendermany** [comment]
Looks like it doesn't work with Expo.

What I did:

expo prebuild
install react-native-reanimated@3.0.0.rc6
cd ios && pod install
expo run ios

` Error: Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: ReferenceError: Property '_updatePropsPaper' doesn't exist, js engine: hermes
`

I tried rebuilding the development build & again the expo prebuild, but nothing changes.

**Comment by fendermany** [comment]
Updated to SDK 47, now it works

**Comment by hugoh59** [comment]
How do you do that @fendermany ?

**Comment by piaskowyk** [comment]
What is the current state of this issue? Did someone try the latest stable version of 3.x?

**Comment by Latropos** [comment]
Closing, due to inactivity, I assume that the problem was fixed with new version of reanimated
