### ISSUE TITLE
3.0.0-rc.6 layout bug zIndex is not respected while navigating.

### ISSUE THREAD

**Issue by batuhansahan** [software-mansion/react-native-reanimated#3794]
### Description

When navigating screen(on IOS) LinearGradient instantly dissolves and zIndex is not respected anymore or opening app first time(on Android) LinearGradient does not respect of entering animation its just flashes and zIndex not respected for few seconds, in 3.0.0-rc.4 there was no problem with the new rewrite of Layout rc.6 there is.

### Steps to reproduce

I already mention at above

### Snack or a link to a repository

there is no

### Reanimated version

3.0.0-rc.6

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by fendermany** [comment]
Also, have a bug with Zindex, but not in navigation. The animated component goes below the child that replaces it.

**Comment by piaskowyk** [comment]
Hey @batuhansahan could you provide a reproduction of your issue? 🙏
