### ISSUE TITLE
MacCatalyst Failed to Build  on "3.0.0-rc.6"

### ISSUE THREAD

**Issue by ZComwiz** [software-mansion/react-native-reanimated#3800]
### Description

On line 403 of NativeProxy.mm in RNReanimated iOS Library, when building to MacCatalyst, the following Build Error Occurs:

`Cannot initialize a parameter of type 'REAHasAnimationBlock _Nonnull' (aka 'BOOL (^)(NSNumber * _Nonnull __strong, NSString * _Nonnull __strong)') with an rvalue of type 'bool (^)(NSNumber * _Nonnull __strong, NSString * _Nonnull __strong)'`

for the function:

```
[animationsManager setHasAnimationBlock:^(NSNumber *_Nonnull tag, NSString *_Nonnull type) {
    auto layoutAnimationsProxy = weakLayoutAnimationsProxy.lock();
    if (layoutAnimationsProxy == nullptr) {
      return false;
    }
    return layoutAnimationsProxy->hasLayoutAnimation([tag intValue], std::string([type UTF8String]));
  }];
```

### Steps to reproduce

1. On the latest version of react native (0.70.6) and with react-native-reanimated v.  "3.0.0-rc.6" in package.json, attempt to target MacCatalyst in Release mode.

Build Error Ensues.

### Snack or a link to a repository

N/A

### Reanimated version

"3.0.0-rc.6"

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Macbook Pro M1 Max

### Acknowledgements

Yes

**Comment by ZComwiz** [comment]
This looks like its related to a change in BuildSettings:

```
-				CLANG_CXX_LANGUAGE_STANDARD = "c++17";
+				CLANG_CXX_LANGUAGE_STANDARD = "c++14";
```

**Comment by WillyRamirez** [comment]
Getting the same error in CI when archiving on version 3.0.0-rc.9

`❌  /Users/runner/work/1/s/node_modules/react-native-reanimated/ios/native/NativeProxy.mm:394:43: cannot initialize a parameter of type 'REAHasAnimationBlock _Nonnull' (aka 'BOOL (^)(NSNumber * _Nonnull __strong, NSString * _Nonnull __strong)') with an rvalue of type 'bool (^)(NSNumber * _Nonnull __strong, NSString * _Nonnull __strong)'
`

**Comment by robertying** [comment]
`layoutAnimationsManager().hasLayoutAnimation` returns a `bool`:

https://github.com/software-mansion/react-native-reanimated/blob/63960981c7b2b613bf99cc56f4fb7ed810ad57cb/Common/cpp/LayoutAnimations/LayoutAnimationsManager.cpp#L22

However, `setHasAnimationBlock` wants a `BOOL`:

https://github.com/software-mansion/react-native-reanimated/blob/63960981c7b2b613bf99cc56f4fb7ed810ad57cb/ios/LayoutReanimation/REAAnimationsManager.h#L15

One workaround is to explicitly return a `BOOL` using the `bool` value:

```diff
diff --git a/node_modules/react-native-reanimated/ios/native/NativeProxy.mm b/node_modules/react-native-reanimated/ios/native/NativeProxy.mm
index 6a13661..cda43d8 100644
--- a/node_modules/react-native-reanimated/ios/native/NativeProxy.mm
+++ b/node_modules/react-native-reanimated/ios/native/NativeProxy.mm
@@ -393,7 +393,7 @@ std::shared_ptr<NativeReanimatedModule> createReanimatedModule(
 
   [animationsManager setHasAnimationBlock:^(NSNumber *_Nonnull tag, NSString *_Nonnull type) {
     return weakModule.lock()->layoutAnimationsManager().hasLayoutAnimation(
-        [tag intValue], std::string([type UTF8String]));
+        [tag intValue], std::string([type UTF8String])) ? YES : NO;
   }];
 
   [animationsManager setAnimationRemovingBlock:^(NSNumber *_Nonnull tag) {

```
