### ISSUE TITLE
global _updatePropsPaper _updatePropsFabric not getting resolved. Import Error.

### ISSUE THREAD

**Issue by shubhamdeol** [software-mansion/react-native-reanimated#3806]
### Description

Error coming from path
/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts

Error Message: Property '_updatePropsPaper' doesn't exist, js engine: hermes

<img width="329" alt="Screenshot 2022-11-24 at 8 12 17 PM" src="https://user-images.githubusercontent.com/11364449/203810872-b1f19fe8-3263-4306-b798-f203aa5bc670.png">

### Steps to reproduce

updating reanimated from 2.13.0 to 3.0.0-rc.6

### Snack or a link to a repository

NA

### Reanimated version

3.0.0-rc.6

### React Native version

0.68.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

PIXEL_5_API_31

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, did you remember to re-build your app after upgrading Reanimated?

**Comment by shubhamdeol** [comment]
yes, I did. 

steps I took.
- rm -rf node_modules/ && yarn cache clean && yarn install
- yarn start --reset-cache
- gradle clean
- rebuild

also looked into https://github.com/software-mansion/react-native-reanimated/issues/2502
no luck

there are others also facing same issue. 
https://stackoverflow.com/questions/73839500/referenceerror-property-updatepropspaper-doesnt-exist-js-engine-hermes

**Comment by tomekzaw** [comment]
Can you please try to reproduce the issue on a fresh RN 0.68.5 app with Reanimated 3.0.0-rc.6?

**Comment by shubhamdeol** [comment]
Not able to reproduce with dependences. 

`"dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.5",
    "react-native-reanimated": "3.0.0-rc.6"
  },`

**Comment by shubhamdeol** [comment]
My project started to work now. 
Looks like issue was with caching. I do not know what exactly fixed it.
