### ISSUE TITLE
latest version fails to build with 'butter/map.h' error (react-native@0.71.0-rc.2)

### ISSUE THREAD

**Issue by mgcrea** [software-mansion/react-native-reanimated#3823]
### Description

Starting a new project using the latest rc available, Xcode won't build once I've added `react-native-reanimated`.

Error is related to an include: `#include <butter/map.h>`

`/node_modules/react-native/ReactCommon/react/bridging/Object.h:13:10 'butter/map.h' file not found`

### Steps to reproduce

1. `npx react-native init ETSMobile --version 0.71.0-rc.2`
2. `yarn add react-native-reanimated` + babel config
3. `npm run ios` or build via xcode`xed ios/`

### Snack or a link to a repository

https://github.com/mgcrea/react-native-sandbox/tree/reanimated-bug

### Reanimated version

2.13.0

### React Native version

0.71.0-rc.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by krmao** [comment]
I am also face this problem.

**Comment by wojtekmaj** [comment]
Interestingly, I don't use react-native-reanimated and I also faced this error in 0.71.0.

**Comment by tomekzaw** [comment]
> Interestingly, I don't use react-native-reanimated and I also faced this error in 0.71.0.

This might be a matter of outdated files in `ios/build` directory due to broken cleanup script.

Please clean Xcode build folder, then run the following commands:

* `rm -rf ios/build`
* `rm -rf Pods`
* `pod install`

and try again.

**Comment by wojtekmaj** [comment]
I came up with this handy command:

```
  "nuke": "rm -rf node_modules; rm -rf ios/build; rm -rf ios/Pods; rm -rf ios/Podfile.lock; yarn; yarn podinstall"
```

**Comment by tomekzaw** [comment]
Hey, while Reanimated 2.13.0 technically works with React Native 0.71.0-rc.x on iOS, it doesn't compile on Android due to many breaking changes in React Native itself.

We already have a PR that adds support for React Native 0.71.0 (#3745) which we plan to merge and release soon, so I'm closing this issue.

**Comment by sunilsaguna** [comment]
> > Interestingly, I don't use react-native-reanimated and I also faced this error in 0.71.0.
> 
> This might be a matter of outdated files in `ios/build` directory due to broken cleanup script.
> 
> Please clean Xcode build folder, then run the following commands:
> 
> * `rm -rf ios/build`
> * `rm -rf Pods`
> * `pod install`
> 
> and try again.

great! it's working for me

**Comment by Akeuuh** [comment]
> I came up with this handy command:
> 
> ```
>   "nuke": "rm -rf node_modules; rm -rf ios/build; rm -rf ios/Pods; rm -rf ios/Podfile.lock; yarn; yarn podinstall"
> ```

I like the spirit haha!

**Comment by edgarcandales** [comment]
I came out with a bash script. Create a file in the main folder and call it "start.sh". Put this code inside it:
`#Mechanism that will start the app in a completely clean environemt
rm -rf node_modules
rm -rf ios/Pods 
rm -rf ios/build
rm ios/Podfile.lock
rm package-lock.json
kill $(lsof -t -i :8081)
npm start -- --reset-cache &
pid=$!
sleep 5
kill $pid
npm i
cd ios
pod install
cd ..
npx react-native run-ios
#npx react-native run-ios --simulator="iPhone 8"
#npx react-native run-ios --simulator="iPhone 8 Plus"
#npx react-native run-ios --simulator="iPhone 11"
#npx react-native run-ios --simulator="iPhone 11 Pro"
#npx react-native run-ios --simulator="iPhone 11 Pro Max"
#npx react-native run-ios --simulator="iPhone SE (2nd generation)"
#npx react-native run-ios --simulator="iPhone 12 mini"
#npx react-native run-ios --simulator="iPhone 12"
#npx react-native run-ios --simulator="iPhone 12 Pro"
#npx react-native run-ios --simulator="iPhone 12 Pro Max"
#npx react-native run-ios --simulator="iPhone 13 Pro"
#npx react-native run-ios --simulator="iPhone 13 Pro Max"
#npx react-native run-ios --simulator="iPhone 13 mini"
#npx react-native run-ios --simulator="iPhone 13"
#npx react-native run-ios --simulator="iPhone 14 Pro Max"
#npx react-native run-ios --simulator="iPhone 14"
#npx react-native run-ios --simulator="iPhone 14 Pro"

#npx react-native run-android

`
uncomment  and comment any npx as convinient (depending on the device you want to run the app). Tu run the app simply write in your terminal "bash start.sh".

**Comment by RaguRam1991** [comment]
> > Interestingly, I don't use react-native-reanimated and I also faced this error in 0.71.0.
> 
> This might be a matter of outdated files in `ios/build` directory due to broken cleanup script.
> 
> Please clean Xcode build folder, then run the following commands:
> 
> * `rm -rf ios/build`
> * `rm -rf Pods`
> * `pod install`
> 
> and try again.

thanks, this working for me
