### ISSUE TITLE
dispatchCommand called without surfaceId- Fabric dispatchCommand must be called through Fabric JSI API

### ISSUE THREAD

**Issue by BloodyMonkey** [software-mansion/react-native-reanimated#3828]
### Description

I upgraded RN to 0.70.5
Reanimated to 3.0.0-rc.7
Lottie to 5.1.4

New arch enabled, hermes disabled

Build successful but app crash at launch

`dispatchCommand called without surfaceId- Fabric dispatchCommand must be called through Fabric JSI API`

![Screenshot 2022-12-01 at 1 44 44 PM](https://user-images.githubusercontent.com/65278563/205056187-67bc95cf-bcb5-4528-a48f-2945cb6f1059.png)

### Steps to reproduce

1. Install RN 0.70.5, Lottie 5.1.4, Reanimated 3.0.0-rc.7
2. Build debug 
3. Crash

### Reanimated version

3.0.0-rc.7

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

JSC

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 6 Pro API 31

### Acknowledgements

Yes

**Comment by zichengbohan** [comment]
这个问题有大佬解了吗？

**Comment by sudhanva-games24x7** [comment]
Facing the same issue. Any luck with this?

**Comment by piaskowyk** [comment]
@sudhanva-games24x7 could you provide a reproduction for this issue? please 🙏

**Comment by luiscarvalho2000** [comment]
Hi, i have this issue.

libraries versions:
`"@rnmapbox/maps": "^10.0.15",`
`"react-native": "0.72.4",`

This is my final return:
> return (<View style={styles.container}>
            {allContainers && (
              <MapView
                style={styles.map}
                styleJSON={JSON.stringify(MapStyle)}
                logoEnabled={false}
                rotateEnabled={false}>
                <Camera
                  ref={camera}
                  bounds={bounds}
                  animationMode={'linearTo'}
                  zoomLevel={12}
                  centerCoordinate={[-8.601, 40.346]}
                />
                <UserLocation androidRenderMode="normal" minDisplacement={1} />

                {/** SHOWS CONTAINER GROUP MANAGERS */}
                {!isFocused &&
                  allContainers.map(container => {
                    if (container.location) {
                      if (container.is_group_manager && !!container.hardware_device) {
                        return (
                          <MarkerView
                            id={container.id.toString()}
                            key={container.id}
                            coordinate={container.location.coordinates}>
                            <MapIcons
                              nContainers={2}
                              trio={true}
                              id={container.id}
                              selected={containerInfo && container.id === containerInfo.id}
                              onPress={id => updateContainerInfo(id)}
                              type={'point'}
                            />
                          </MarkerView>
                        )
                      } else if (container.group_manager == null && !!container.hardware_device) {
                        return (
                          <MarkerView
                            id={container.id.toString()}
                            key={container.id}
                            coordinate={container.location.coordinates}>
                            <MapIcons
                              type={container.type}
                              trio={false}
                              id={container.id}
                              selected={containerInfo && container.id === containerInfo.id}
                              onPress={id =>
                                getContainerInfo(id)
                                  .then(response => {
                                    setContainerInfo(response.data)
                                    setError(undefined)
                                    setModalVisible(true)
                                    setCamera(response.data.location.coordinates)
                                  })
                                  .catch(error => {
                                    setError(error)
                                    setIsFocused(false)
                                    console.log(error)
                                  })
                              }
                            />
                          </MarkerView>
                        )
                      }
                    }
                  })}
                {/** SHOWS CONTAINER GROUP MEMBERS */}
                {isFocused &&
                  allContainers.map(container => {
                    if (container.is_group_manager === false && selectedGroupMembers.includes(container.id)) {
                      return (
                        <MarkerView
                          id={container.id.toString()}
                          key={container.id}
                          coordinate={container.location.coordinates}>
                          <MapIcons
                            type={container.type}
                            trio={false}
                            id={container.id}
                            selected={containerInfo && container.id === containerInfo.id}
                            onPress={id =>
                              getContainerInfo(id)
                                .then(response => {
                                  setContainerInfo(response.data)
                                  setError(undefined)
                                  setModalVisible(true)
                                  setCamera(response.data.hardware_device.location.coordinates)
                                })
                                .catch(error => {
                                  setError(error)
                                  setIsFocused(false)
                                  console.log(error)
                                })
                            }
                          />
                        </MarkerView>
                      )
                    }
                  })}
              </MapView>
            )}
          </View>)

after I haver tag **<UserLocation />** cleaned but have a error invalid displacement -1.0, and I had this parameters **<UserLocation androidRenderMode="normal" minDisplacement={1} />**. Have the same error in title of this issue.
