### ISSUE TITLE
Cannot install react-native-animated

### ISSUE THREAD

**Issue by CutieCat6778** [software-mansion/react-native-reanimated#3830]
### Description

![image](https://user-images.githubusercontent.com/51492960/205123529-eeec7df8-ce18-4364-92ec-80e2f93f12ba.png)

I trying to install `react-native-animated`, but it didn't work!

### Steps to reproduce

1. I ran command `npm i react-native-animated`, also tried `npx expo install react-native-animated`.
2. It request me to login into my github account.
3. I loged in
4. It showed me that I don't have permissions to access that github repo (look at the picture).

### Snack or a link to a repository

Private

### Reanimated version

lastest

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

V8

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Iphone XR

### Acknowledgements

Yes

**Comment by pavankommi** [comment]
There is no such dependency as "react-native-animated". You might be looking for "[react-native-reanimated](https://www.npmjs.com/package/react-native-reanimated)".

**Comment by piaskowyk** [comment]
It looks like problem with configuration of `npm` on your local machine. See potential solution - https://stackoverflow.com/questions/35021692/npm-install-error-code-128
