### ISSUE TITLE
3.0.0-rc.8 No member named 'ShareableValue' in namespace 'reanimated' 

### ISSUE THREAD

**Issue by jamninetyfive** [software-mansion/react-native-reanimated#3831]
### Description

3.0.0-rc.8 No member named 'ShareableValue' in namespace 'reanimated' 

with react-native-vision-camera

### Steps to reproduce

react-native-vision-camera

### Snack or a link to a repository

none

### Reanimated version

3.0.0-rc.8

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by fahad86** [comment]
also seeing many crashes in Google Play due to this issue

**Comment by sarath40158** [comment]
No member named 'ShareableValue' in namespace  in **3.0.0-rc.8**

<img width="1238" alt="Screenshot 2022-12-19 at 10 04 58 AM" src="https://user-images.githubusercontent.com/94572332/208348599-1a552404-ab3f-495e-bcc5-b10bbab08c22.png">

**Comment by alexstanbury** [comment]
> also seeing many crashes in Google Play due to this issue

Why are you using a release candidate build in a production app?!?

And @sarath40158 react native vision camera doesn't appear to be compatible with this version and I wouldn't expect it to be until reanimated 3 is released and stable.

**Comment by piaskowyk** [comment]
Hey, `react-native-vision-camera` doesn't supports Reanimated 3, if you want to use `react-native-vision-camera` you need to downgrade Reanimated to latest version 2.+ unfortunately 😔

**Comment by hari-mohan-choudhary** [comment]
but 2+ is not supporting fabric

**Comment by kshanmugam73** [comment]
I encountered the same issue with version 0.71.4, but after updating to "react-native-reanimated": "^2.3.0" in my project, I received a positive response.

**Comment by Etaliya** [comment]
Any update regarding support react-native-reanimated V3?

**Comment by animatereactnative** [comment]
Please, if you have time, could you do this, it will solve a lot of problems
