### ISSUE TITLE
Unable to build application for android after installing react-native-reanimated

### ISSUE THREAD

**Issue by andreatrio** [software-mansion/react-native-reanimated#3841]
### Description

Hi, I’ve recently encountered this error while trying to build my application for android. I have already configured the package following this [documentation](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/).

## I'm currently using:
- react-native-reanimated: 2.13.0
- gradle: distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
- More info about system and tools are provided in the list below 

## Error when trying to build application for android
```
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-70-hermes.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}.
      > Execution failed for JetifyTransform: /Users/username/Documents/work/projects/test_m1/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar.
         > Check failed.
```

## npx react-native info
System:
OS: macOS 13.0.1
CPU: (10) arm64 Apple M1 Pro
Shell: 5.8.1 - /bin/zsh
Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
Java: 11.0.17 - /usr/bin/javac
react: 18.1.0
react-native: 0.70.2

### Steps to reproduce

react-native run-android

### Snack or a link to a repository

https://github.com/andreatrio/test_m1

### Reanimated version

2.13.0

### React Native version

0.70.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Parkjunwu** [comment]
In my case, when project is under the folder not using english name, then this happen. (My case, project is under korean name folder).

Checking project's path maybe help you.

**Comment by iamsrikanthnani** [comment]
have uploaded all AAR and JRC files here on this repo: [rn-reanimated-aar-files](https://github.com/iamsrikanthnani/rn-reanimated-aar-files/tree/master)
tested: 
`"react-native": "0.70.x"` and  `"react-native": "0.71.x"`,
`"react-native-reanimated": "^2.14.1"` or `"react-native-reanimated": "^2.10.0"`

### WORKING 🤘

**Comment by andreatrio** [comment]
Problem fixed with new react-native-reanimated 3 version
