### ISSUE TITLE
No errors in logs

### ISSUE THREAD

**Issue by jlongster** [software-mansion/react-native-reanimated#385]
I'm running on the iOS simulator in debug mode. If I make an error in in a `block` in an `Animated.event`, my app doesn't load and there not errors in the console. An example that seems to make it hang is `A.call([translationX], onDragMove)` where `translationX` is an argument to the function (where I think I can only pass an animated node). Additionally, `A.debug("hey", x)` where `x` is an animated node logs nothing to the console.

Has anyone ever seen this before? It's like I see no logs at all from reanimated.

**Comment by usrbowe** [comment]
I had the same problem, but later I read docs, where there is explanation of where logs are displayed.
Expo projects -> `JS console`
Ejected projects ->
a) `native console` (ie.: iOS -> Xcode)
b) remote debugging ON -> `JS console`


Additionally in my case, I had disabled native log with this run argument: `OS_ACTIVITY_MODE=DISABLE` (https://stackoverflow.com/a/39461256/3507122).

**Comment by jakub-gonet** [comment]
Hi @jlongster,
solution provided by @usrbowe should resolve your problem

I'm closing this thread due to inactivity, but if it didn't help or you have any further questions don't hesitate to ask
