### ISSUE TITLE
Babel plugin (react-native-reanimated/plugin) causing invalid sourcemap

### ISSUE THREAD

**Issue by MorganTrudeau** [software-mansion/react-native-reanimated#3870]
### Description

Hey everyone,

First bug I have seen with this package. Could be something I am missing, but coming here for advice.

What I am seeing is adding this babel plugin (react-native-reanimated/plugin) is causing source maps to be invalid when bundling. I am using Bugsnag and it is saying my source map does not match my code. I validated the source map using the npm package ```sourcemap-validator``` and it indeed throws an error saying the source map doesn't match the bundle. 

I have reproduced this with a new react-native init project. This error occurs in my project using react-native 0.66.4 and in the sample app with react-native 0.70.6

Sample App
https://github.com/MorganTrudeau/rn-sample

There is a README in the repo with steps to reproduce the invalid source map.

Thanks for the help.

### Steps to reproduce

Clone sample app and follow steps in README file.

### Snack or a link to a repository

https://github.com/MorganTrudeau/rn-sample

### Reanimated version

2.2.4

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, 2.2.4 is like 2 years old, have you considered using 2.13.0 or even 3.0.0-rc.8?

**Comment by tomekzaw** [comment]
Hey, thanks for the repro, we will take a look at it soon.

**Comment by MorganTrudeau** [comment]
Awesome thanks 👍

**Comment by Latropos** [comment]
This problem was probably solved with the newest Reanimated v3. Please feel free to reopen this issue if you keep seeing any inconsistencies
