### ISSUE TITLE
Error running new RN architecture (0.71.0-rc.4) on IOS

### ISSUE THREAD

**Issue by RalissonMattias** [software-mansion/react-native-reanimated#3871]
### Description

I installed the new version of RN to test the app's behavior, but I can't run it with the next version of reanimated. I get some error in xcode

## npx react-native info

```
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M2
    Memory: 103.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/ralissonmattias/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0-rc.4 => 0.71.0-rc.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
![Captura de Tela 2022-12-15 às 20 38 06](https://user-images.githubusercontent.com/92331757/207989365-9d3dc858-6508-49e3-9468-81e25a87a387.png)
![Captura de Tela 2022-12-15 às 20 38 34](https://user-images.githubusercontent.com/92331757/207989416-a938a46d-df6d-4b10-a8cc-37bfde816c90.png)

### Steps to reproduce

1. Install latest rc version of the RN `npx react-native init projectName --version 0.71.0-rc.4`
2. Install react-native-reanimated v3 with `react-native-reanimated@3.0.0-rc.8` and configure
3. Run `RCT_NEW_ARCH_ENABLED=1 pod install`
4. Run project in Xcode

### Snack or a link to a repository

https://github.com/RalissonMattias/reanimated-issue

### Reanimated version

3.0.0-rc.8

### React Native version

0.71.0-rc.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

Iphone 13 - IOS 15.*, Iphone 14 - IOS 16.*

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, we are still working on 0.71 support, see the PR:

* #3745
