### ISSUE TITLE
Android gravity sensor is not working if phone doesn't have a gyroscope

### ISSUE THREAD

**Issue by alikazemkhanloo** [software-mansion/react-native-reanimated#3876]
### Description

I tried to use the example [here](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedSensor) but with GRAVITY sensor. However, the {x,y,z} values are always zero. it is working as expected in phones with gyroscopes and the android emulator.

### Steps to reproduce

1. get a phone without a gyroscope
2. try to use useAnimatedSensor with GRAVITY sensor (or use the snack link)
3. observe that {x,y,z} values never change. (the size of the box should change as you tilt the device)

### Snack or a link to a repository

https://snack.expo.dev/@alikazemkhanloo/reanimatedsensor-gravity

### Reanimated version

2.9.0

### React Native version

0.69

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

Real device

### Device model

Xiaomi Redmi 9a

### Acknowledgements

Yes

**Comment by ashuvssut** [comment]
What sensors does the GRAVITY animatedSensor use?

**Comment by tomekzaw** [comment]
Hey @alikazemkhanloo , thanks for reporting this issue?

> it is working as expected in phones with gyroscopes and the android emulator.
> get a phone without a gyroscope

What's the expected result of gravity measurement in case when the phone actually doesn't have the sensor?

**Comment by alikazemkhanloo** [comment]
May I should ask a question to make sure we are on the same page:

There are two types of sensors in phones, a gyroscope, and an accelerometer. The latter is used to measure acceleration. it means it will give you 9.8 m/s2 in the z-axis if the phone is resting on a table. 

Now if you rotate the phone on the z-axis, the accelerometer will not detect that. Here we will need a gyroscope to detect that.

Now the question is what type of `SensorType` should I use in `useAnimatedSensor` to measure the accelerometer's data? I am currently using the `Accelerometer` from the 'expo-sensors' package and it works. but performance is not good.

**Comment by alikazemkhanloo** [comment]
@graszka22 thank you for the clarification.

It's probably not the device fault, as it is working with expo's library. I am using `expo install` to install the same version that is built into expo (the native part) which is definitely not the up to date version. so it might be because of that.

And the fact that you tested on similar device and couldn't reproduce it, I guess it is resolved or just specific to Redmi 9a.
Anyway, I decided not to support low-end devices and used `ROTATION` sensor. I'm gonna close this issue for now till I test it with the latest version.
