### ISSUE TITLE
☂️ Deadlock/ANR in performOperations

### ISSUE THREAD

**Issue by tomekzaw** [software-mansion/react-native-reanimated#3879]
### Description

This is an umbrella issue for ANRs/deadlocks on Android/iOS in NodesManager.performOperations.

The bug was introduced in #1215.

Android:
- #2251
- #3062

iOS:
- #3180
- #3862
- #3946

PRs trying to solve this issue:
- #3082
- #3194

### Repro

We don't have a repro yet but it needs to use modal or datetime picker as well as animate layout props using Reanimated.

### Reanimated version

\>= 2.0.0, >= 3.0.0

### Platforms

Android, iOS

**Comment by casperstr** [comment]
What is the status of this. Is this fixed in 3.0?

**Comment by malikzype** [comment]
Facing the same issue in Android with reanimated v3.....any update on this issue?

**Comment by tomekzaw** [comment]
Fixed in #4239, will be released in 3.1.0 and 2.15.0.
