### ISSUE TITLE
[ANDROID] Crash app after finish animation

### ISSUE THREAD

**Issue by bachlongkocanh** [software-mansion/react-native-reanimated#3880]
### Description

My app has crash after animation finish.
```
const gestureHandler =
    useAnimatedGestureHandler<PanGestureHandlerGestureEvent>({
      onActive(event) {
        'worklet';
        if (event.translationX < MIN_SLIDE) {
          return;
        }
        if (event.translationX + SLIDE < WRAPSLIDE) {
          x.value = withSpring(event.translationX, {
            damping: 20,
            stiffness: 90,
          });
        }
      },
      onFinish(event) {
        'worklet';
        if (event.translationX + SLIDE < WRAPSLIDE) {
          x.value = 0;
        } else {
           /**
           * Code working when comment this, but crash when remove comment code
           */
          // Alert.alert('aaaa');
          // navigation.navigate(SCREEN_NAME.SLIDE_WELCOME);
          x.value = 0;
        }
      },
    });
  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateX: x.value,
        },
      ],
    };
  });
```
What is incorrect?

### Steps to reproduce

1. Pan container
2. App crash when start run Alert or navigate

### Snack or a link to a repository

https://snack.expo.dev/@huutho/crash-animated

### Reanimated version

2.11.0

### React Native version

0.69.5

### Platforms

Android

### JavaScript runtime
Hermes

### Workflow
React Native (withour expo)

### Architecture

New fabric

### Build type

Debug mode

### Device

Real device

### Device model

Nokia X6

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, thanks for reporting this issue.

You cannot call `Alert.alert` or `navigation.navigate` directly from a worklet, you need to use `runOnJS`:

```ts
import { runOnJS } from 'react-native-reanimated';

runOnJS(Alert.alert)('aaaa');
runOnJS(navigation.navigate)(SCREEN_NAME.SLIDE_WELCOME);
```

**Comment by bachlongkocanh** [comment]
> Hey, thanks for reporting this issue.
> 
> You cannot call `Alert.alert` or `navigation.navigate` directly from a worklet, you need to use `runOnJS`:
> 
> ```ts
> import { runOnJS } from 'react-native-reanimated';
> 
> runOnJS(Alert.alert)('aaaa');
> runOnJS(navigation.navigate)(SCREEN_NAME.SLIDE_WELCOME);
> ```

Thank you very much, saved my day.
