### ISSUE TITLE
 3.0.0-rc.9 , useAnimatedScrollHandler with FlashList not working,

### ISSUE THREAD

**Issue by hamdij0maa** [software-mansion/react-native-reanimated#3889]
### Description

No event emitted, 
when using Flashlist or MasonryFlashlist with Reanimated 

### Steps to reproduce

```tsx
const AnimatedFlashList = Animated.createAnimatedComponent(MasonryFlashList);

 const scrollHandler = useAnimatedScrollHandler(
    {
      onBeginDrag: () => {
        cancelAnimation(scrollY);
      },
      onScroll: event => {
        'worklet';
        scrollY.value = clamp(
          event.contentOffset.y,
          -SIZES.screenHeight,
          HEADER_PROFILE_HEIGHT - heightMenu - 2 * theme.spacing.s,
        );
      },
      onMomentumEnd: () => {
        cancelAnimation(scrollY);
      },
    },
    [],
  );
  
  <AnimatedFlashList
   onScroll={scrollHandler}
    renderItem={renderItem}
  />
```

### Snack or a link to a repository

https://gist.github.com/hamdij0maa/c9ed404672e2c70871495fd579350f09

### Reanimated version

 3.0.0-rc.9

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by hamdij0maa** [comment]
https://gist.github.com/hamdij0maa/c9ed404672e2c70871495fd579350f09

**Comment by PeterOla** [comment]
Having same issue, Any update on this?

**Comment by marf** [comment]
We have the same issue.

**Comment by geroale** [comment]
Same issue here

**Comment by LeviWilliams** [comment]
We also were unable to get this scroll handler working at all in reanimated 3, tried both flashlist and flatlist. A blocker for us to try it out.

**Comment by hieu1871998** [comment]
Can anyone confirm this bug is resolved on 3.0.0-rc10? The scroll event still not working on Android, on iOS it's working fine even in rc9.

**Comment by hamdij0maa** [comment]
"react-native-reanimated": "^2.14.0", => now we have a new bug, using : createAnimatedComponent, 
"ViewTag" is read-only

**Comment by efstathiosntonas** [comment]
@hamdij0maa this is fixed on `2.14.1` that is coming out any moment now

**Comment by hamdij0maa** [comment]
good news, thanks @efstathiosntonas

**Comment by hamdij0maa** [comment]
> @hamdij0maa this is fixed on `2.14.1` that is coming out any moment now

After upgrade the useAnimatedSCrollHandler is not working on Android

**Comment by orekasep** [comment]
> > @hamdij0maa this is fixed on `2.14.1` that is coming out any moment now
> 
> After upgrade the useAnimatedSCrollHandler is not working on Android

I am having the same issue. useAnimatedScrollHandler no longer works as expected.

**Comment by efstathiosntonas** [comment]
Leaving this here, it seems that they try to better handle the ref: https://github.com/Shopify/flash-list/pull/381/files

**Comment by orekasep** [comment]
> Leaving this here, it seems that they try to better handle the ref: https://github.com/Shopify/flash-list/pull/381/files

Thanks, I have tried to patch createAnimatedComponent.tsx and seems back to works

`      if (componentName?.endsWith('FlashList') && this._component) {
        // @ts-ignore it's FlashList specific: https://github.com/Shopify/flash-list/blob/218f314e63806b4fe926741ef73f8b9cd6ebc7eb/src/FlashList.tsx#L824
        viewTag = findNodeHandle(this._component.**recyclerlistview_unsafe**);
      }`

with 

`      if (componentName?.endsWith('FlashList') && this._component) {
        // @ts-ignore it's FlashList specific: https://github.com/Shopify/flash-list/blob/218f314e63806b4fe926741ef73f8b9cd6ebc7eb/src/FlashList.tsx#L824
        viewTag = findNodeHandle(this._component.**getScrollableNode()**);
      }`

**Comment by efstathiosntonas** [comment]
@orekasep patched it like you did, it works fine now. @tomekzaw

**Comment by tomekzaw** [comment]
Thanks @orekasep, are you willing to submit a PR with this fix?

**Comment by efstathiosntonas** [comment]
@tomekzaw do you think that this fix can be applied on rc or it's another story?

**Comment by orekasep** [comment]
@tomekzaw: I have just submit a pull request from here:

https://github.com/software-mansion/react-native-reanimated/pull/3938

**Comment by pavangoyal42** [comment]
In 3.0.0-rc.10 I am using flatlist by using createAnimatedComponent. Still facing the same issue in android. any updates on this ?
`const AnimatedFlatList = Animated.createAnimatedComponent(
  FlatList,
) as typeof FlatList
`

**Comment by mrkpatchaa** [comment]
@pavangoyal42 did you find a solution? 
I am also using `Animated.createAnimatedComponent( FlatList )` but `refreshControl` is not working.
```
"@shopify/flash-list": "1.4.3",
"react-native-reanimated": "~3.3.0"
```
@orekasep any insights? Thanks

**Comment by mrkpatchaa** [comment]
Sorry my mistake...
I found out that when using it and applying margin to another component, it is breaking the refreshcontrol.
Here is my code...
```
const AnimatedFlashList = Animated.createAnimatedComponent<FlashListProps<ListingRow>>(FlashList)
....
  const animatedHeaderStyle = useAnimatedStyle(() => {
    return {
      marginTop: interpolate(
        sv.value,
        [0, 120, 300, Infinity],
        [0, -sv.value / 4 - safeAreaInsets.top, -100 - safeAreaInsets.top, -100]
      ),
      opacity: interpolate(sv.value, [0, 120, 300, Infinity], [1, 0, 0, 0]),
    }
  })
...
<View>
      <Animated.View
        style={[
          {
            height: 60,
            paddingLeft: 20,
            justifyContent: 'flex-start',
          },
          animatedHeaderStyle,
        ]}
      >
....
<AnimatedFlashList
        onScroll={scrollHandler}
...
</View>
```

The marginTop applied to the other view is causing the issue....

**Comment by mrkpatchaa** [comment]
I just made it work by doing this : 
```
const animatedHeaderStyle = useAnimatedStyle(() => {
    return {
      marginTop: interpolate(
        sv.value,
        [-100, 0, 120, 300, Infinity],
        [0, 0, -sv.value / 4 - safeAreaInsets.top, -100 - safeAreaInsets.top, -100]
      ),
      opacity: interpolate(sv.value, [0, 120, 300, Infinity], [1, 0, 0, 0]),
    }
  })
```
