### ISSUE TITLE
Error: Requiring module "node_modules/react-native-reanimated/src/index.ts"

### ISSUE THREAD

**Issue by ahmedfouad01099** [software-mansion/react-native-reanimated#3890]
### Description

 ERROR  Error: Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreanimated.so
	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.udalmeria/lib-main flags = 1]
	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.udalmeria-3xtM7BedHESIojQllZgeJA==/lib/arm64 flags = 0]
	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
	Native lib dir: /data/app/com.udalmeria-3xtM7BedHESIojQllZgeJA==/lib/arm64
 result: 0, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

### Steps to reproduce

1. yarn install react-native-reanimated version 3.0.0-rc.9 it worked once with me on android and after that it generated that error I'm sharing with you
2. yarn start --reset-cach
3. yarn android to build app
4. app doesn't open at all and the bundle corrupted and build complete successfully but open white blank screen that doesn't contain anything.

### Snack or a link to a repository

https://github.com/ahmedfouad01099/UD-Almeria

### Reanimated version

3.0.0-rc.9

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

Poco x3 NFC

### Acknowledgements

Yes

**Comment by kfernandes29** [comment]
Same issue here. Anyone able to solve this?

**Comment by ahmedfouad01099** [comment]
note: this error happens on m1 mac machine

**Comment by ThushalIntervest** [comment]
any solutions?

**Comment by trungtruc91** [comment]
same issue

**Comment by denvermccarthy** [comment]
Same here
`
"react-native": "0.63.5",
 "react-native-reanimated": "2.14.0",
`
Reverting to `2.13.0` solved the issue for me

**Comment by Sumansourabh14** [comment]
@denvermccarthy Did you use dev client?
I use the command `npx expo start --dev-client` to run the application but still the error remains.
