### ISSUE TITLE
[Feature] support autolinking for RN 0.60.x

### ISSUE THREAD

**Issue by zxccvvv** [software-mansion/react-native-reanimated#391]

**Comment by jakub-gonet** [comment]
Hi @zxccvvv,
AFAIK Reanimated supports auto-linking.

If you have an issue with auto-linking please reply.

**Comment by zxccvvv** [comment]
@jakub-gonet i don't know if `Reanimated` already supported `autolinking`, because i'm used it long time ago, and if Reanimated already support `autolinking`, i think it's good to edit the [doc](https://software-mansion.github.io/react-native-reanimated/getting-started.html) because it's still says:
> Link native code with react-native cli:
  react-native link react-native-reanimated

**Comment by rsallar** [comment]
Please, could you update the documentation web page? it keeps showing:
_Link native code with react-native cli:
react-native link react-native-reanimated_
Thank you!
