### ISSUE TITLE
App crashes in reanimated::MutableValue::set::lambda

### ISSUE THREAD

**Issue by tastydev** [software-mansion/react-native-reanimated#3912]
### Description

Hello,

we are currently experiencing high crashrates in `reanimated::MutableValue::set` operations on. `iPhones`:

Sentry is reporting the following stack trace:
<img width="900" alt="Screenshot 2023-01-05 at 09 32 16" src="https://user-images.githubusercontent.com/39250826/210738402-902d50dd-dd39-4ceb-ad15-4267eb4f1062.png">

We are experiencing this crash really often on iOS 16.x but it is also present in lower iOS versions, see: 
<img width="413" alt="Screenshot 2023-01-05 at 09 26 20" src="https://user-images.githubusercontent.com/39250826/210739040-de7d206a-0948-4861-b97c-654423716f02.png">

We are using `useSharedValue` quite often but could not find the animation which is causing it yet.

We are not experiencing these crashes on android as sentry is only reporting iOS Devices.

### Steps to reproduce

We are currently not sure how this is possible to reproduce, but it may be a multithreading (ui + reactjs thread) issue when setting animated shared values?

### Snack or a link to a repository

none

### Reanimated version

2.13.0

### React Native version

0.66.5

### Platforms

Android, iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

All iPhones

### Acknowledgements

Yes

**Comment by tomdalling** [comment]
Looks like a duplicate of https://github.com/software-mansion/react-native-reanimated/issues/3632

**Comment by shaibt** [comment]
We're also seeing this issue in production apps. 
As @tastydev describes with high probability (>90%) on iOS 16.x devices and lower (<30%) on iOS 15.
See crash stack below (looks like same as OP).
Few observations:
1) using latest `react-native-reanimated` ver `2.14.1`, react-native `0.67.3`
2) crash happens when app navigates to new screen that involve a few animations. Not all animations/navigations fail - just this particular navigation to a new page using `@react-navigation/stack`. 
3) seems this started happening around when we starting building production app using Xcode 14.x. Might be noise but thought worth mentioning.
4) Xcode crash stack mentions that the main thread crashes (see stack attached) from an event dispatched from the JS thread: `"Enqueued from com.apple.root.default-qos.overcommit"`. `overcommit` means the queue is overwhelmed by requests. We don't control the dispatch queue between the JS/RN thread and the main iOS thread. could it be that `react-native-reanimated` is overwhelming the queue somehow?

![Screen Shot 2023-01-15 at 15 08 26](https://user-images.githubusercontent.com/25963448/213209447-45d32477-a557-4463-aa9a-bfa5e48721ef.png)
<img width="964" alt="Screen Shot 2023-01-18 at 17 15 32" src="https://user-images.githubusercontent.com/25963448/213209558-fe915b46-3fdf-4fe5-bc8f-205aa5fc9943.png">

**Comment by tastydev** [comment]
@shaibt We are currently deploying a possible fix and i will inform you if the fix will be successful. This is a `garbage pointer` access as you can see in the sentry stack trace so we thought about possible reasons for the js thread to access a already "garbage collected" value. We instantly thought about react component lifecycle issues and indeed found some `useEffect` hooks were a `useSharedValue` reference was used without having the reference of that useSharedValue in the dependency array of the useEffect. So our opinion is that there is a possibility of reanimated trying to access a pointer/reference of a value which was already garbage collected of the JS abstraction layer. You can think of a race condition between the reanimated native multithreading implementation and the JS engine garbage collector. Reanimated might be multithreading safe but it might not be atomic safe. That are our thoughts. Maybe you can do something with. See you!

**Comment by shaibt** [comment]
Thanks for the tip @tastydev.
We reviewed all our code and couldn't find cases where values created by `useSharedValue` were incorrectly missing from hook dependencies. 
One direction we investigated is reducing the amount of components and renders that use `reanimated`. The page being rendered (where the crash happens) uses the library heavily and the thought process was lets reduce the load (and JS<-> main inter-thread comms) on reanimated. We discovered that even after this type of refactoring the probability of crashes does not change. 
One other area of investigation is gesture handlers provided by `react-native-gesture-handler` which are also used (and animated) in the relevant page.

**Comment by shaibt** [comment]
We've upgraded `reanimated` to ver `3.0.0-rc.10`.
Cannot reproduce this crash w/ new version.

**Comment by tomdalling** [comment]
> We've upgraded `reanimated` to ver `3.0.0-rc.10`.
> Cannot reproduce this crash w/ new version.

Do we know exactly what fixes the issue? Could it be backported to a 2.x release?

**Comment by shaibt** [comment]
See this comment in issue https://github.com/software-mansion/react-native-reanimated/issues/3917#issuecomment-1380943001

> Also, Reanimated 3 comes with a new implementation of shared values which is ~2x faster and also eliminates some random crashes that occurred on 2.x and haven't been fixed yet.

**Comment by mtebele** [comment]
Same issue here:

```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000018

Crashed: com.apple.main-thread
0  appname                          0x19c780 std::__1::__function::__func<reanimated::MutableValue::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)::$_2, std::__1::allocator<reanimated::MutableValue::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)::$_2>, void ()>::operator()() + 580 (shared_ptr.h:580)

1  appname                          0x1c1894 reanimated::Scheduler::triggerUI() + 463 (function.h:463)

2  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32

3  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20

4  libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928

5  libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44

6  CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16

7  CoreFoundation                 0x7c058 __CFRunLoopRun + 2036

8  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612

9  GraphicsServices               0x1368 GSEventRunModal + 164

10 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888

11 UIKitCore                      0x3a2034 UIApplicationMain + 340

12 appname                          0x4ff0 main + 7 (main.m:7)

13 ???                            0x1b2464960 (Falta)
```

**Comment by fadi-quader-mox** [comment]
App freeze with this error when i use ShardElement transition on Reanmited 3.1
<img width="657" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/102506966/589ce176-1aa7-4bbe-befb-7f6a90898cb3">
