### ISSUE TITLE
useAnimatedScrollHandler not working on Android with RefreshControl version 2.14.1

### ISSUE THREAD

**Issue by hamdij0maa** [software-mansion/react-native-reanimated#3937]
### Description

useAnimatedScrollHandler not working on Android with RefreshControl

### Steps to reproduce

const AnimatedFlashList = Animated.createAnimatedComponent(FlashList);
 <AnimatedMasonryFlashList
        ref={refList}
        scrollEventThrottle={16}
        data={[...posts]}
        refreshControl={
          <RefreshControl
            onRefresh={() => {
              try {
                onRefresh();
                refetch();
              } catch (x) {}
            }}
            title={t('pull-to-refresh').toString()}
            progressViewOffset={
              Platform.OS === 'ios' ? undefined : HEADER_PROFILE_HEIGHT
            }
            refreshing={isRefreshing}
          />
        }
        numColumns={3}
        contentContainerStyle={flatenContentContainerStyle}
        estimatedItemSize={100}
        renderItem={renderPostItem}
      />

### Snack or a link to a repository

https://gist.github.com/hamdij0maa/b6538a211b35e7f7b3ca1650b727d624

### Reanimated version

2.14.1

### React Native version

0.70+

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel

### Acknowledgements

Yes

**Comment by hamdij0maa** [comment]
Here is a minimal repro https://gist.github.com/hamdij0maa/b6538a211b35e7f7b3ca1650b727d624
its not working only on Android when using a RefreshControl

**Comment by orekasep** [comment]
Possible fix with this patch:

https://github.com/software-mansion/react-native-reanimated/pull/3938

**Comment by hamdij0maa** [comment]
hopefully we get ur PR accepted soon

**Comment by hamdij0maa** [comment]
@orekasep  is the fix will be released soon ?

**Comment by hamdij0maa** [comment]
Bug is in version 2.14.1

**Comment by tomekzaw** [comment]
@hamdij0maa Can you confirm #3938 resolves the issue for you?

**Comment by hamdij0maa** [comment]
@tomekzaw honestly am waiting for the release to be secure, did not play with the fix yet, 
any news ?

**Comment by tomekzaw** [comment]
It's just a simple change in JavaScript code, would you be so kind to apply the patch locally in your node_modules and let us know if it works for you? This way we can merge and release it quite confidently.

**Comment by hamdij0maa** [comment]
sure, 
yes working fine. 
waiting for the release now <3 thank you
