### ISSUE TITLE
App freezes when animating height and rendering DateTimePicker at the same time 

### ISSUE THREAD

**Issue by MaxAst** [software-mansion/react-native-reanimated#3946]
### Description

My app freezes without throwing errors when trying to run the following code using an expo managed workflow:

```
import { useState } from "react";
import { SafeAreaView, View, Pressable } from "react-native";
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from "react-native-reanimated";
import DateTimePicker from "@react-native-community/datetimepicker";

export default function Plan() {
  const [date, setDate] = useState(new Date());
  const [toggle, setToggle] = useState(false);

  const height = useSharedValue(150);

  const style = useAnimatedStyle(() => {
    return {
      height: withTiming(height.value),
    };
  });

  const onDateChange = (_, selectedDate) => {
    setDate(selectedDate);
  };

  return (
    <SafeAreaView
      style={{
        flex: 1,
      }}
    >
      <View style={{ flex: 1, paddingHorizontal: 20, marginTop: 60 }}>
        <Pressable
          onPress={() => {
            setToggle((toggle) => !toggle);
            if (height.value === 150) {
              height.value = 300;
            } else {
              height.value = 150;
            }
          }}
        >
          <Animated.View style={[{ backgroundColor: "orange" }, style]}>
            {toggle && (
              <DateTimePicker
                value={date}
                mode="date"
                is24Hour={true}
                onChange={onDateChange}
              />
            )}
          </Animated.View>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}
```

~~What really puzzles me is that this works with an Expo Snack, but not when I run it on my machine. Because of this, I also prepared a repo reproducing this, that you can clone and try running with Expo Go: https://github.com/MaxAst/expo-reanimated-datetimepicker~~
I accidentally used expo version 46 in the snack, instead of 47. With 47 I get the following error after pressing the `Pressable` component:
```
View config getter callback for component `RNDateTimePicker` must be a function (received `undefined`).
```

### Steps to reproduce

1. run `npx create-expo-app expo-reanimated-datetimepicker` to create a new expo project
2. run `npx expo install react-native-reanimated @react-native-community/datetimepicker`
3. add `plugins: ['react-native-reanimated/plugin']` to babel.config.js
4. copy code above into `App.js`
5. run `npx expo start --clear` and open app on Expo Go
6. try pressing the yellow rectangle - app will freeze after pressing

### Snack or a link to a repository

https://snack.expo.dev/@maxast31/tenacious-pretzel

### Reanimated version

2.12.0

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 12 Pro

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, this may be related to #3879.

**Comment by ajsmth** [comment]
I've had this exact same issue with the same combination of libraries: 
```
"react-native-reanimated@2.12.0" 
@react-native-community/datetimepicker@6.7.5
```

**Comment by johnhaup** [comment]
[ajsmth](https://github.com/ajsmth)'s answer solved it for me.

**Comment by piaskowyk** [comment]
This issue is fixed with - https://github.com/software-mansion/react-native-reanimated/pull/4403. Available in the newest version of Reanimated 3

**Comment by AtlasShd** [comment]
> This issue is fixed with - #4403. Available in the newest version of Reanimated 3

It is not fixed on the 25.02.2024 moment

**Comment by tomekzaw** [comment]
@AtlasShd What version of Reanimated are you using?

**Comment by AtlasShd** [comment]
> @AtlasShd What version of Reanimated are you using?

I am using "react-native-reanimated": "3.7.1" and "@react-native-community/datetimepicker": "7.6.2".

Minimal handle example:
const [isPickerShown, setIsPickerShown] = useState(false);
const height = useSharedValue(0);

  useEffect(() => {
    height.value = isPickerShown ? 217 : 0;
  }, [isPickerShown]);

  const animatedStyle = useAnimatedStyle(() => ({
    height: withTiming(height.value, {
      duration: 200,
      easing: Easing.inOut(Easing.quad),
    }),
  }));

Minimal component example:
  <TouchableOpacity onPress={() => setIsPickerShown((prev) => !prev)}/>
  <Animated.View style={animatedStyle}>
        <DateTimePicker
          value={value}
          display='spinner'
          onChange={handleOnChange}
          mode='time'
        />
      </Animated.View>
