### ISSUE TITLE
[iOS][JSC] Adding react-native-reanimated adds a second JSContext from Safari dev tools

### ISSUE THREAD

**Issue by Chris-Guy** [software-mansion/react-native-reanimated#3957]
### Description

Hello,
it looks like a second JSContext is created when using react-native-reanimated. I wanted to know if it is expected?
If it was unintended, it potentially requires more resource from the device to keep such a additional JS Context (even if it is empty and does not run anything).

This has been seen when looking at the Safari inspectors list:
![image](https://user-images.githubusercontent.com/6816661/212740093-40b697de-4384-4264-a9c9-654dee1cff39.png)

### Steps to reproduce

1. Create a React Native app by executing the CLI: ```npx react-native init MyRn706App --template react-native@0.70.6```
2. Disable Hermes so that the JS Context can be attached from Safari: go to ios/Podfile and change the variable ```hermes_enabled``` to ```false```
3. Run ```yarn add react-native-reanimated```
4. Run ```npx react-native run-ios```
5. Look at the JS contexts in the Safari inspector tabs: there will be two instead of only one

### Snack or a link to a repository

https://github.com/Chris-Guy/MyRn706App

### Reanimated version

latest

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @Chris-Guy, yes, this is expected. Reanimated creates a secondary JS runtime on the UI thread to synchronously calculate animations for the current frame independently from the main React Native JS VM that runs the React.js code, etc. See more details in the documentation [here](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets).

**Comment by Chris-Guy** [comment]
Ah, my bad, I should have read the documentation for Reanimated 2 instead of searching through issues, I have no excuses since it was in the first pages!
One other curiosity question: do you have an idea of the memory footprint of the JS context by itself?

**Comment by tomekzaw** [comment]
No problem at all, I'm happy to answer all questions.

Nope, I don't have exact numbers (probably a few MBs) but I think I can easily measure that for you if you're interested.

**Comment by Chris-Guy** [comment]
Yes, I would be interested to have numbers if you can measure it. I think it would also help for your documentation to indicate that the second JS context actually has a small memory footprint to increase confidence on this approach!
