### ISSUE TITLE
v2.14.1 and RN 0.71.0 (Android) Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by codewithmecoder** [software-mansion/react-native-reanimated#3959]
### Description

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\projects\electronic-signature-frontend\node_modules\react-native-reanimated\android\build.gradle' line: 246      

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Steps to reproduce

1. When I run the app it is showing the error above.

### Snack or a link to a repository

dont have

### Reanimated version

2.14.1

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by marceloch2** [comment]
Same here, it started while upgrading to React Native 71, trying to solve it and going to share if there is any luck.

**Comment by tomekzaw** [comment]
Hey, unfortunately I wasn't able to reproduce the issue on a fresh RN 0.71.0 app with Reanimated 2.14.1.

Here are my steps:

```
npx react-native@next init MyApp --version 0.71.0 --skip-install
cd MyApp
yarn add react-native-reanimated@2.14.1
# add `plugins: ['react-native-reanimated/plugin'],` in babel.config.js
# copy FabricExample/src/BokehExample.tsx from react-native-reanimated repo to App.js
# change `export default function BokehExample` to `export default function App`
open -a "Android Studio" android
yarn start --reset-cache
# Build the app from Android Studio
```

1. Remove all your build folders with `rm -rf node_modules android/.cxx android/build android/app/build android/app/.cxx && yarn --force`
2. Make sure your app is consistent with the RN 0.71.0 app template

**Comment by codewithmecoder** [comment]
> Hey, unfortunately I wasn't able to reproduce the issue on a fresh RN 0.71.0 app with Reanimated 2.14.1.
> 
> Here are my steps:
> 
> ```
> npx react-native@next init MyApp --version 0.71.0 --skip-install
> cd MyApp
> yarn add react-native-reanimated@2.14.1
> # add `plugins: ['react-native-reanimated/plugin'],` in babel.config.js
> # copy FabricExample/src/BokehExample.tsx from react-native-reanimated repo to App.js
> # change `export default function BokehExample` to `export default function App`
> open -a "Android Studio" android
> yarn start --reset-cache
> # Build the app from Android Studio
> ```
> 
> 1. Remove all your build folders with `rm -rf node_modules android/.cxx android/build android/app/build android/app/.cxx && yarn --force`
> 2. Make sure your app is consistent with the RN 0.71.0 app template: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.0



Thanks for the  suggestion. I'll try it and let you know. Thanks again.

**Comment by codewithmecoder** [comment]
> 


Thank you so mush. It is working now.

**Comment by noypi** [comment]
Leaving it here for future reference. Changing the if condition works for me. thanks.

       if (REACT_NATIVE_MINOR_VERSION >= 71 && appProject?.ext?.react?.enableHermes?.toBoolean()) {
           return "hermes"
       }

**Comment by tomekzaw** [comment]
Hey @noypi, which version of RN are you using? Can you confirm that your app is consistent with RN 0.71 app template?

**Comment by feardarkness** [comment]
I had the same issue. Just find the file gradle.properties and add at the end:

`hermesEnabled=true`

**Comment by error-try-again** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

This worked for me

**Comment by MahdiZahrani** [comment]
> hermesEnabled=true

thanks

**Comment by tdduydev** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

thanks

**Comment by cgorrieri** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`
This worked for me as well.

For expo projects where `expo.jsEngine=hermes`, could `hermesEnabled` be automatically enabled?

**Comment by Danushka96** [comment]
[https://react-native-community.github.io/upgrade-helper/?from=0.68.5&to=0.71.0](https://react-native-community.github.io/upgrade-helper/?from=0.68.5&to=0.71.0)

Update the package.json and app/build.gradle file according to the changes

**Comment by ALI-SAMPSON** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

Worked for me. Thanks.

**Comment by brysonjonesy** [comment]
`hermesEnabled=false` worked in gradle.properties worked because we also have `enableHermes: false` in the build.gradle

**Comment by hemanthAppmaker** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

worked for me 
`hermesEnabled=true`
was not on my gradle.properties file

**Comment by jeanmarcos552** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

Worked for me. Thanks.

**Comment by lfoliveir4** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

Thanks!!!!

**Comment by feliksius** [comment]
> Leaving it here for future reference. Changing the if condition works for me. thanks.
> 
> ```
>    if (REACT_NATIVE_MINOR_VERSION >= 71 && appProject?.ext?.react?.enableHermes?.toBoolean()) {
>        return "hermes"
>    }
> ```

Still working on me,
Thank you !

**Comment by jemilehin** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

it works thanks. But how did you know it will solve the problem

**Comment by farhanbudye** [comment]
> I had the same issue. Just find the file gradle.properties and add at the end:
> 
> `hermesEnabled=true`

worked for me, thanks!
