### ISSUE TITLE
Is tag 1.2.0 pointing to right source

### ISSUE THREAD

**Issue by darshannahar** [software-mansion/react-native-reanimated#396]
I observed package.json for tag 1.2.0 says the version is 1.1.0.

https://github.com/kmagiera/react-native-reanimated/blob/1.2.0/package.json

Is tag 1.2.0 correctly pointing to the source files as present in npm?

**Comment by haithemT** [comment]
also the changes related to androidX migration are in master branch but not in 1.20 neither in 1.3.0 alpha

**Comment by osdnk** [comment]
Hey, yes,
this tag point to proper code. We made a release a little bit later after extra changes we decided to move to the next release. Therefore commit bumping version is chronologically after these changes so after merging it to `master` we wanted to tag the last commit included in a release. So tag on GH and NPM release is actually the same thing (but for manually modified version in a `package.json`)
