### ISSUE TITLE
v2.14.1 RN 0.71.0 (iOS) Hermes disabled 'jsi/JSCRuntime.h' file not found in NativeProxy.mm

### ISSUE THREAD

**Issue by tindn** [software-mansion/react-native-reanimated#3965]
### Description

- react-native version: `0.71.0`
- react-native-reanimated version: `2.14.2`
- platform: `iOS`
- hermes `disabled`
- using old react architecture

When building the ios app, I'm running into the following error
`'jsi/JSCRuntime.h' file not found` on line 26 of file `RNReanimated/ios/native/NativeProxy.mm`.

I'm noticing this switch logic https://github.com/software-mansion/react-native-reanimated/blame/2.14.2/android/src/main/cpp/NativeProxy.cpp#L15 in the Android code that has been there since version `2.14.0` that would fix this issue.

### Steps to reproduce

1. `yarn install`
2. `cd ios && NO_FLIPPER=1 pod install`
3. Update ios code signing and build the ios app, this should build without an error.
4. `cd ios && NO_FLIPPER=1  USE_HERMES=0 RCT_NEW_ARCH_ENABLED=0 pod install`
5. Try building the ios app again, this will result in the error reported above

### Snack or a link to a repository

https://github.com/tindn/MyApp

### Reanimated version

2.14.2

### React Native version

0.71.0

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by vadimdanilov** [comment]
Same error after upgrading to RN 0.71.0 with (hermes disabled)

**Comment by tomekzaw** [comment]
Hey, thanks @tindn for reporting this issue and @vadimdanilov for confirming it.

Should be fixed with #3969.

**Comment by tomekzaw** [comment]
@tindn  hank you for your investigation and suggesting a correct solution! Most likely we will publish 2.14.3 with this fix.

**Comment by Gavin-PunchCard** [comment]
> @tindn Thank you for your investigation and suggesting a correct solution! Most likely we will publish 2.14.3 with this fix.

Great news!  I came here looking for a solution with the same issues after upgrading to 0.71.0 with hermes disabled!

**Comment by tomekzaw** [comment]
Fixed in react-native-reanimated@2.14.3.

**Comment by BRaymond69** [comment]
Hello, I have the same issue when I m building my application with expo (error during Fastlane build):
`
❌  (node_modules/expo-dev-menu/vendored/react-native-reanimated/ios/native/NativeProxy.mm:26:9)

  24 | #import <hermes/hermes.h>
  25 | #else
> 26 | #import <jsi/JSCRuntime.h>
     |         ^ 'jsi/JSCRuntime.h' file not found
  27 | #endif
`
Here system version, I m using "react-native-reanimated": "~2.12.0" but I have try with the lasted 2.14.2 and 2.14.3 (there is always the same issue/error)

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 188.03 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/benjaminraymond/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
Thank you in advance for any help

**Comment by urtheone** [comment]
I don't know why, but both **'jsi/JSCRuntime.h'** file and **'jsc/JSCRuntime.h'** not found in my project.
`"react-native-reanimated": "^3.4.2",
`
