### ISSUE TITLE
Native crash when using an undefined Animated.Value in a debug node

### ISSUE THREAD

**Issue by yolpsoftware** [software-mansion/react-native-reanimated#397]
When setting the value of an Animated.Value object to `null` or `undefined` and then using it in a `debug` statement in an `Animated.Code` block, we get a native exception that crashes the app.

Reproducible demo:

```javascript

import React, {Fragment} from 'react';
import {
  SafeAreaView,
  Text,
  TouchableOpacity,
} from 'react-native';

import Animated from 'react-native-reanimated';
const {
  set,
  block,
  debug,
} = Animated;

const node = new Animated.Value(0);

const App = () => {
  return (
    <Fragment>
      <Animated.Code>
        {() => block([debug('node value: ', node)])}
      </Animated.Code>
      <SafeAreaView>
        <TouchableOpacity
          onPress={() => node.setValue(undefined)}    // setValue(null) will throw a different exception
          style={{padding: 20}}
        >
          <Text>Click Me</Text>
        </TouchableOpacity>
      </SafeAreaView>
    </Fragment>
  );
};

export default App;
```

This error can be quite difficult to find in a complex animation, since there is no indication about what the problem is. If it is intended that an error is thrown on an undefined `Value`, then a better error message would be very useful.

The exact error is on line 21 of `REAJSCallNode.m`:

    [error][tid:main][RCTUIManager.m:1133] Exception thrown while executing UI block: *** -[__NSArrayM setObject:atIndexedSubscript:]: object cannot be nil

In the case of setting the `Value` to `null`, we get a JS exception: `Unhandled JS Exception: Cannot read property '__isProxy' of null`.

Here are the versions used:

    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-reanimated": "1.2.0"

**Comment by Hirbod** [comment]
Ping

**Comment by Jarred-Sumner** [comment]
More info from debugging this a little.

I'm seeing this too. It happens when:
- The component is unmounted
- The component is detached (e.g. `display: none`)
- Fast refresh loads the component (sometimes)

If you have any animated nodes inside a `<Modal>`, it breaks.

It happens right here:
![image](https://user-images.githubusercontent.com/709451/73701132-636b2f00-469d-11ea-8d43-2998543d0ed8.png)

In `-(id) evaluate` for most (maybe all) of the nodes, this error can happen.

Most likely, the logic for detaching animated nodes needs to account for whether the view backing the node is attached (`superview != nil && window != nil`). It probably shouldn't be evaluating these nodes on a detached view anyway, since that likely means if you have an inactive screen with animated nodes on it, those `Animated.Node` will continue to be evaluated which can cause performance issues.

**Comment by jakub-gonet** [comment]
Hi @yolpsoftware,
sorry for the late response.

I was unable to reproduce `undefined` case, could you confirm that's not a problem anymore?
Null problem is still happening, I'll take a look at that.

Thanks for reporting!

**Comment by yolpsoftware** [comment]
Hi @jakub-gonet 

No problem. Yes it seems the undefined case is solved.

Thanks for having a look at the null case. However, please note that this ticket is way less important than the native crash 216:

https://github.com/software-mansion/react-native-reanimated/issues/216

Thanks for this great library!
Best regards

**Comment by jakub-gonet** [comment]
I'll keep an eye on that, thanks for update!

**Comment by jakub-gonet** [comment]
@yolpsoftware

After thinking about it for a while I believe forbidding `null`s as a Value is the best solution here. I don't really see any use case for it, except when using the `defined` node for initialization. For that, we use undefined at the moment. 

We can also internally replace nulls with undefined, but I'd find that behavior confusing.

Do you have any thoughts?

**Comment by yolpsoftware** [comment]
@jakub-gonet sounds good to me. Main point of the ticket IMO is to prevent the confusing error message. In a complex project, you wouldn't know where to look for the problem.

**Comment by marqroldan** [comment]
I'm having the same issue with 1.13.0 setting values to undefined, this wasn't the case on 1.9.0 and I'm not sure what exactly changed. Should I open another ticket?

**Comment by jakub-gonet** [comment]
@marqroldan, could you please provide some minimal code example reproducing this crash?

**Comment by Sevendaye** [comment]
this.position = new Animated.ValueXY();
...
` onPanResponderMove: (event, gesture) => {
        this.position.setValue({ x: gesture.dx, y: 0})
      },`
...


Even if you only use x, you must put y to 0 so that they are not undefined
It should have default values if not initialized.
