### ISSUE TITLE
Reanimated fails to compile on Web (Next.js)

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-reanimated#3971]
### Description

Currently, it isn't possible to use Reanimated with Next.js 13. I believe this is related to the SWC plugin. @piaskowyk discussed this in the Showtime Slack, but I don't have access to that thread. It seems to be due to SWC not transforming the Reanimated code. 

As it stands, our website can't build or work in dev mode due to this issue. I have hundreds of animations relying on Reanimated, so it would be quite difficult to refactor them all away.

I'm not sure if this is a problem with Next.js or the Reanimated plugin, or both. Related issue is https://github.com/vercel/next.js/issues/43886

The plugin is provided from #3341 

<img width="1643" alt="Screenshot 2023-01-18 at 2 42 34 PM" src="https://user-images.githubusercontent.com/13172299/213279607-e3b61934-2b06-422b-b44d-53ce7a711f6a.png" />

### Steps to reproduce

I placed a reproduction below.

<details>
<summary>View reproduction steps</summary>

1. Install dependencies

```sh
npx create-next-app reanimated
cd reanimated
yarn add react-native-web react-native-reanimated react-native-reanimated-swc-plugin raf
```

2. Add `next.config.js` with the reanimated plugin (`0.3.0` for `next@13.1.2`):

```js
const nextConfig = {
  reactStrictMode: false,
  experimental: {
    swcPlugins: [['react-native-reanimated-swc-plugin']],
  },
  webpack: (config) => {
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      // Transform all direct `react-native` imports to `react-native-web`
      'react-native$': 'react-native-web',
    }
    config.resolve.extensions = [
      '.web.js',
      '.web.ts',
      '.web.tsx',
      ...config.resolve.extensions,
    ]
    return config
  },
  transpilePackages: ['react-native-reanimated'],
}

module.exports = nextConfig
```

3. Add `import 'raf/polyfill'` to the top of `pages/_app.js`:

```tsx
import 'raf/polyfill'

export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```

4. Add a Reanimated view to `pages/index.js`:

```tsx
import Animated from 'react-native-reanimated'

export default function Home() {
  return <Animated.View />
}
```

5. Run `yarn next`, and open `localhost:3000`: it breaks

</details>

### Snack or a link to a repository

https://github.com/nandorojo/reanimated-next13-issue

### Reanimated version

2.9.0 (tried many)

### React Native version

react-native-web 0.18

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @nandorojo, since you've contributed support of Reanimated without usage of Babel/SWC plugins in #3997, could we close this issue? 

Regrettably, we don't have people that specialise in Rust at the moment while also not having any other requests for SWC support so it's extremely unlikely that our SWC plugin will be getting updates.

**Comment by nandorojo** [comment]
Yes, that PR should suffice. I'll close this.
