### ISSUE TITLE
Cannot assign to read-only property in Reanimated 2.14.3

### ISSUE THREAD

**Issue by hamdij0maa** [software-mansion/react-native-reanimated#3976]
### Description

<img width="278" alt="image" src="https://user-images.githubusercontent.com/20734472/213509991-eb7cf0f0-ad8f-47da-8cee-47bd50fcbea3.png">

### Steps to reproduce

just update to the 2.14.3

### Snack or a link to a repository

just update to the 2.14.3

### Reanimated version

2.14.3

### React Native version

0.71.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 pro

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
It looks like the offending PR is #3950, reverted in 6271c4c3d04e8a1674021a95d20d5a4276a12f5e, will publish 2.14.4 soon, sorry for the inconvenience. 😢
