### ISSUE TITLE
Attempt to assing to readonly property in Reanimated 2.14.3 (No Hermes)

### ISSUE THREAD

**Issue by Audrey-Ann** [software-mansion/react-native-reanimated#3978]
### Description

Hello there!

I am implemented a hybrid (IOS & Android) application using React-Native with Typescript and I am experiencing a new issue for IOS after running 

```
npm install --legacy-peer-deps && cd ios && pod install && cd ..
npm react-native start --reset-cache
react-native run-ios 
```

Here are my latest packages' version: 
```
"react-native": "~0.71.0-rc.6",
"react-native-reanimated": "~2.14.3",
```

Here is the issue I am getting on IOS emulator: 

![Screen Shot 2023-01-19 at 12 44 08 PM](https://user-images.githubusercontent.com/16864703/213520603-beb340a6-99d0-4702-bf43-0db6902e134e.png)

Thank you again for your help!

### Steps to reproduce

1. Upgrade to package 
```
"react-native": "~0.71.0-rc.6",
"react-native-reanimated": "~2.14.3",
```
2. Run 
```
npm install --legacy-peer-deps && cd ios && pod install && cd ..
npm react-native start --reset-cache
react-native run-ios 
```

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

~2.14.3

### React Native version

~0.71.0-rc.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Looks like duplicate of #3976.

**Comment by Audrey-Ann** [comment]
The error message is tiny bit different but it looks quite similar 🙏

**Comment by tomekzaw** [comment]
Do you use JSC or Hermes?

**Comment by tomekzaw** [comment]
This explains why the error message is different as it comes directly from the VM.

**Comment by Audrey-Ann** [comment]
@tomekzaw makes, sense. Thank you for the explanation 🙏 . 

My understanding then is that, this issue is the same as [3976](https://github.com/software-mansion/react-native-reanimated/issues/3976), but 3976 uses Hermes whereas this one doesn't.

Looking forward to the bug fix! Thanks for your support and quick response too!

**Comment by piaskowyk** [comment]
hey @Audrey-Ann could you try the latest patch 2.14.4? I hope that this version should resolve your problem

**Comment by Audrey-Ann** [comment]
@piaskowyk @tomekzaw I just upgraded `react-native-reanimated` to version `2.14.4` and the error is gone 🍾! 

Thank you very much for fixing this so quickly! 😸 

Closing this issue 👏
