### ISSUE TITLE
Wrong values of targetGlobalOriginX in custom layout animations

### ISSUE THREAD

**Issue by akozlov98** [software-mansion/react-native-reanimated#3991]
### Description

Hi, I'm getting wrong values of targetGlobalOriginX and targetGlobalOriginY in my custom entering animation.

<details><summary>entering function code</summary>
<p>

```TSX
const SlideThroughScreen = (values) => {
  'worklet';
  const animations = {
    originX: withRepeat(
      withTiming(-values.targetGlobalOriginX + screenWidth, {
        duration: 2000,
        easing: Easing.linear,
      }),
      -1,
    ),
  };

  const initialValues = {
    originX: -values.targetGlobalOriginX,
  };

  return {
    initialValues,
    animations,
  };
};
```

</p>
</details>

I have markup like below, and I want all the red lines to slide from the left side of screen to the right side
<img width="318" alt="image" src="https://user-images.githubusercontent.com/96730191/214385440-afed0328-a3ee-4e9d-add2-017b2f71312c.png">

### Expected result

With `originX: -values.targetGlobalOriginX` all the red lines should be at start of the screen

<details><summary>Expected initial position</summary>

<img width="318" alt="image" src="https://user-images.githubusercontent.com/96730191/214391448-caa86539-0fbe-4ee7-bcc1-27845f36a757.png">

</details>

<details><summary>Expected animation</summary>

#### Wasn't able to screencast expected result with 4 blocks

https://user-images.githubusercontent.com/96730191/214387908-834d75a8-2bcd-4cfd-86e8-30fe45699283.mp4

</details>

### Actual result

With `originX: -values.targetGlobalOriginX` not all red lines are at the start of the screen
If reloading the app values of targetGlobalOriginX changing, so it's not stable 

<details><summary>Actual initial position</summary>

<img width="318" alt="image" src="https://user-images.githubusercontent.com/96730191/214391885-7eb2125f-2ef1-4885-81a6-8f5999a4894a.png">

</details>

<details><summary>Actual animation</summary>

https://user-images.githubusercontent.com/96730191/214391178-06e8a6fc-3ba2-4385-88ca-f4136904dcfa.mp4

</details>

### Steps to reproduce

I provided a repo from reanimated playground, just added markup and animations

1. `git@github.com:akozlov98/reanimated-target-origin-values.git`
2. `cd reanimated-target-origin-values`
3. `yarn install`
4. `cd ios && pods install`
5. run any emulator or device

### Snack or a link to a repository

https://github.com/akozlov98/reanimated-target-origin-values

### Reanimated version

2.3.1

### React Native version

0.65.1

### Platforms

Android, iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

IPhone 12 (tried a lot, real and emulators)

### Acknowledgements

Yes

**Comment by graszka22** [comment]
Hi thanks for reporting the issue and the repro! I managed to reproduce it on the newest reanimated version too. I'm going to investigate this.
