### ISSUE TITLE
 After upgrading to  2.14.4 - Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project

### ISSUE THREAD

**Issue by ps-danielk** [software-mansion/react-native-reanimated#3996]
### Description

When upgrading to react-native-reanimated v 2.14.4, I get the following error when building my android app locally:

```Build file '/Users/danielkurfirst/Desktop/PrincipleProjects/FAHW-MobileApp/node_modules/react-native-reanimated/android/build.gradle' line: 246

A problem occurred evaluating project ':react-native-reanimated'.
> Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.
```

I have hermes enabled defined in android/app/build.gradle here:

```
project.ext.react = [
    ...
    enableHermes: false
]
```

Have tried clearing cache, cleaning project, ./gradlew clean etc and nothing is working. 

Please advise, thanks

### Steps to reproduce

1.Upgrade react-native-reanimated to v 2.14.4
2.Try to build app locally

### Snack or a link to a repository

n/a

### Reanimated version

2.14.0

### React Native version

0.71.1

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 6

### Acknowledgements

Yes

**Comment by hasansajora** [comment]
Facing the same issue here.
Did you find any workaround other than downgrading the package?

**Comment by ps-danielk** [comment]
@hasansajora no I have not yet

**Comment by satheshrgs** [comment]
@ps-danielk @hasansajora Add the `hermesEnabled=true` in your gradle.properties file.

**Comment by hasansajora** [comment]
Thank you @satheshrgs

**Comment by tomekzaw** [comment]
@ps-danielk, according to RN 0.71.0 app template, your app should have `hermesEnabled=false | true` in gradle.properties.

**Comment by rrdesignweb** [comment]
Hi there just wondering what the solution here is for an expo managed project? On the latest Expo SDK 48 (it is now enabled by default) 

My error
`Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.`

Another reference to this discussion https://github.com/software-mansion/react-native-reanimated/issues/3959#issuecomment-1449693242 

thanks

**Comment by brysonjonesy** [comment]
`hermesEnabled=false` worked in gradle.properties worked because we also have `enableHermes: false` in the build.gradle

**Comment by aubryll** [comment]
> `hermesEnabled=false` worked in gradle.properties because we also have `enableHermes: false` in the build.gradle

Worked for me.

**Comment by sharabhh** [comment]
> @ps-danielk @hasansajora Add the `hermesEnabled=true` in your gradle.properties file.

this worked for me thanks a ton!
