### ISSUE TITLE
A bug in babel automatic workletization

### ISSUE THREAD

**Issue by janpe** [software-mansion/react-native-reanimated#4001]
### Description

Hi. If I'm on the right tracks I think there is an improvement that could be made to the automatic workletization of gesture callbacks. I have a library that uses `react-native-gesture-handler` and `react-native-reanimated`. It works as expected in our esm build but breaks in commonjs. It seems that the automatic workletization described in the documentation doesn't work in the latter. We found a workaround this though, I'll describe it when we get to the code. I'm sorry but I wasn't able to minimally reproduce this in an Expo snack, at least yet.

So when I have a import and usage like this it works fine in esm but breaks in commonjs. _WORKLET is false

`import { GestureDetector, Gesture } from 'react-native-gesture-handler';`

```
const pinchGesture = Gesture.Pinch()
      .manualActivation(true)
      .onTouchesMove(({ numberOfTouches }, s) => {
        console.log(_WORKLET);
        if (numberOfTouches > 1) {
          s.activate();
        }
      })
```

The resulting commonjs code

`const react_native_gesture_handler_1 = require("react-native-gesture-handler");`

```
const pinchGesture = react_native_gesture_handler_1.Gesture.Pinch()
            .manualActivation(true)
            .onTouchesMove(({ numberOfTouches }, s) => {
              console.log(_WORKLET);
              if (numberOfTouches > 1) {
                s.activate();
              }
        })
```

But if I change the imports in my code to be like this

```
import * as GestureHandler from 'react-native-gesture-handler';

const { GestureDetector, Gesture } = GestureHandler;
```

The resulting commonjs code is like this, worklet is true and everything works as expected

```
const GestureHandler = __importStar(require("react-native-gesture-handler"));

const { GestureDetector, Gesture } = GestureHandler;

const pinchGesture = Gesture.Pinch()
            .manualActivation(true)
            .onTouchesMove(({ numberOfTouches }, s) => {
              console.log(_WORKLET);
              if (&& numberOfTouches > 1) {
                s.activate();
              }
        })
```

### Steps to reproduce

1. Use named imports from `react-native-gesture-handler`
2. Setup a pinch gesture with `onTouchesMove` with manual activation
3. Build it into commonjs
4. Automatic workletization doesn't seem to work

### Snack or a link to a repository

/

### Reanimated version

2.9.0

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @janpe, as for this issue we decided that best solution is currently to drop support of CommonJS. Is CommonJS necessary in your project or ES modules are enough?

**Comment by janpe** [comment]
> Hi @janpe, as for this issue we decided that best solution is currently to drop support of CommonJS. Is CommonJS necessary in your project or ES modules are enough?

Hi! I'm not currently facing this issue anymore so feel free to proceed as you prefer!

**Comment by tjzel** [comment]
Thanks! I'm happy to close the issue then :)
