### ISSUE TITLE
[3.0.0-rc.10]  Error: Unable to resolve module ../../../package.json

### ISSUE THREAD

**Issue by alabsi91** [software-mansion/react-native-reanimated#4015]
### Description

- After upgrading to version `3.0.0-rc.10`, I encountered this error. I tried using both the old and new architecture, performing a clean build, and clearing the cache, but nothing worked.

`error: Error: Unable to resolve module ../../../package.json from node_modules\react-native-reanimated\lib\commonjs\reanimated2\platform-specific\checkVersion.js:`

```console
error: Error: Unable to resolve module ../../../package.json from node_modules\react-native-reanimated\lib\commonjs\reanimated2\platform-specific\checkVersion.js:

exports.checkVersion = checkVersion;
var _package = require("../../../package.json");
                       ^
```
- I resolved the issue by editing the `package.json` file in the `node_modules/react-native-reanimated folder` :

```diff
 // `node_modules\react-native-reanimated\package.json`

- "main": "lib/commonjs/index",
+ "main": "src/index",
```

### Steps to reproduce

 upgrading to version `3.0.0-rc.10`,

### Snack or a link to a repository

//

### Reanimated version

3.0.0-rc.10

### React Native version

0.71.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by ouabing** [comment]
Same issue here, using 3.0.0-rc.10 with RN 0.70.6

**Comment by alabsi91** [comment]
@jwajgelt, you were correct. I created a fresh React Native project and it worked as expected. Regarding the project with the issue, I checked the `metro.config.js` file and made some modifications to it previously in order to make `firebase` work. After removing these changes, the issue was resolved, this an old hack for older versions which I did not fully test to see if it would still work without it in the current version.
```js
const {getDefaultConfig} = require('metro-config');
const {resolver: defaultResolver} = getDefaultConfig.getDefaultValues();

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    ...defaultResolver,
    sourceExts: [...defaultResolver.sourceExts, 'cjs'], // for firbase to work
  },
};
```

**Comment by marcocaldera** [comment]
In my case the error is showing up in one of my testing files in which I have:
`jest.unmock('react-native-reanimated');`

```
    "react-native-reanimated": "^3.0.0-rc.10",
    "react-native": "0.70.6",
```

**Comment by nikonhub** [comment]
+1. It's been like this since rc.01

**Comment by Tohix** [comment]
have the same problem.
`
 "react-native": "0.71.3",
"react-native-reanimated": "3.0.0-rc.10",
`

**Comment by jwajgelt** [comment]
We changed how the version check is made with the release of `3.0.0`. This issue should've (hopefully) been fixed.
