### ISSUE TITLE
 Task :react-native-deepar:bundleReleaseLocalLintAar FAILED

### ISSUE THREAD

**Issue by Ridwan226** [software-mansion/react-native-reanimated#4025]
### Description

 Task :react-native-deepar:bundleReleaseLocalLintAar FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-deepar:bundleReleaseLocalLintAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-deepar:bundleReleaseLocalLintAar'
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-deepar project caused this error: /Users/ridwanromadhon/Documents/RidwanGanteng/Program/Kerjaan/NewFramme/AppsReactNative/Newfemme-RN-CLI/node_modules/react-native-deepar/android/libs/deepar-3.4.4.aar

### Steps to reproduce

 ./gradlew assembleRelease

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

2.10.0"

### React Native version

0.70.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Android 

### Acknowledgements

Yes

**Comment by graszka22** [comment]
I'm closing this, because it's not related to Reanimated library. In the error message there is only `react-native-deepar` mentioned, so please post this issue there.

**Comment by mbrazzoduro** [comment]
> 

It's not a problem, it's just that the deepar-3.4.4.aar module is not being read. Add in your build.gradle the dependency implementation files('libs/deepar-3.4.4.aar')
