### ISSUE TITLE
Error: Requiring module "node_modules\react-native-reanimated\src\index.ts", which threw an exception: Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by viscardo** [software-mansion/react-native-reanimated#4035]
### Description

Hi everyone

I am getting the error below, everytime i am trying to build to debug or upload it to apple or android using EAS build.

**Error: Requiring module "node_modules\react-native-reanimated\src\index.ts", which threw an exception: Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.** 

I already changed my babel.config.js as you can see below:

**module.exports = function (api) {
	api.cache(true);
	return {
		presets: ['babel-preset-expo'],
		plugins: [
			'react-native-reanimated/plugin',
			['module:react-native-dotenv', {
			'moduleName': '@env',
			'path': '.env',
			'blacklist': null,
			'whitelist': null,
			'safe': false,
			'allowUndefined': true
		}]]
	};
};**

I also changed my package.json with  the below configuration

  **"resolutions": {
    "react-native-reanimated": "^2.9.1"
  },
  "overrides": {
    "react-native-reanimated": "^2.9.1"
  },**

I actually do not use the react-native-reanimated direct in my project, but I use the **react-native-skeleton-content** with use reanimated as dependency plugin

Can anyone help me to solve this issue?

I am stuck in this situation for a week.

### Steps to reproduce

1 -  eas build --profile development --platform ios
2 -  expo start --dev-client --clear

### Snack or a link to a repository

https://snack.expo.dev/@realizeti/client-mobile-kd

### Reanimated version

^2.9.1

### React Native version

0.69.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

iphone 13

### Acknowledgements

Yes

**Comment by coreyherbert** [comment]
Did you find a resolution for this? I am unable to build for iOS.

**Comment by viscardo** [comment]
Did you find a resolution for this? I am unable to build for iOS.

No I could not find the solution. It happens when i am using the EAS only. If I debug on expo Go it works fine

**Comment by muteshi** [comment]
Having the same issue. I am completely unable to build on iOS after installing reanimated
