### ISSUE TITLE
No matching constructor for initialization of 'facebook::react:UlManagerBinding'. IOS

### ISSUE THREAD

**Issue by SandipJawaleRN** [software-mansion/react-native-reanimated#4040]
### Description

![image](https://user-images.githubusercontent.com/94618389/217544849-782d76f4-aaae-44c3-92fe-0a121029f3a6.png)

Getting above error 
Reanimated version "react-native-reanimated": "^3.0.0-rc.10",

### Steps to reproduce

Install "react-native-reanimated": "^3.0.0-rc.10",
Enable Fabric
Build

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/

### Reanimated version

^3.0.0-rc.8

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
FYI In #3985 we added a mechanism that should provide a developer-friendly user message in such case but it got merged after 3.0.0-rc.10 was released and will be available starting from rc.11.
