### ISSUE TITLE
JSX syntax in js files

### ISSUE THREAD

**Issue by pzoli** [software-mansion/react-native-reanimated#4057]
### Description

Support for the experimental syntax 'jsx' isn't currently enabled.

### Current behavior

I tried use react-navigation drawer in a react-native web application, but I get 3 error messages.

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\work\integrity\projects-node\WebDemoProject-drawer\node_modules\react-native-reanimated\lib\createAnimatedComponent.js: Support for the experimental syntax 'jsx' isn't currently enabled (511:21):

```
[StackOverflow - How to enable jsx syntax in js files](https://stackoverflow.com/questions/75408500/react-native-how-to-enable-jsx-syntax-in-js-files)

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/drawer              | 6.5.8
| @react-navigation/native               | 6.1.3
| react-native-reanimated                 | 2.14.4
| react-native                                     | 0.71.2
| node                                                | 18.12.1
| npm or yarn                                    | 8.19.2, 1.22.19

### Steps to reproduce

1. Download github repo
2. yarn install
3. yarn web

### Snack or a link to a repository

https://github.com/pzoli/WebDemoProject-drawer

### Reanimated version

2.14.4

### React Native version

0.71.2

### Platforms

Web

### JavaScript runtime

Node 18.12.1

### Workflow

None

### Architecture

x86 64

### Build type

None

### Device

Emulator

### Device model

Nexus 7

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey, thanks for the report but this issue seems like configuration problem in your project. Unfortunately, I'm not familiar enough with web configuration to give you valuable advice :/
