### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Jeet989** [software-mansion/react-native-reanimated#4071]
### Description

Unable to run jest after installing the navigation dependency and the required other dependencies. I think so you can reproduce this issue by creating a new project as well. Here, I have also created a new project with the same issue and below is the git link. 

Here is the issue screenshot:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/40856822/219961935-d0ccce3a-d226-4281-857f-f97e4aa7bcec.png">

### Steps to reproduce

Just create a new project and add the react navigation dependencies. Then add the reanimated library and configure it with the proper jest files and then you will be able to get the same issue.

### Snack or a link to a repository

https://github.com/Jeet989/Testing

### Reanimated version

^2.14.4

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by andrzej-hanusek-tg** [comment]
@Jeet989 How did you resolve this issue?

**Comment by Jeet989** [comment]
@andrzej-hanusek-tg not yet. I am trying to see if I get any solution

**Comment by andrzej-hanusek-tg** [comment]
@Jeet989 

Try to with jest.config.js like below

```
{
  "preset": "react-native",
  "moduleFileExtensions": ["ts", "tsx", "js", "jsx", "json", "node"],
  "setupFiles": ["./node_modules/react-native-gesture-handler/jestSetup.js"],
  "setupFilesAfterEnv": ["./jest-setup.js"],
  "transformIgnorePatterns": ["jest-runner"],
  "testTimeout": 30000,
  "moduleNameMapper": {
    "\\.svg": "<rootDir>/__mocks__/svgMock.js",
    "^@/(.*)$": "<rootDir>/src/$1"
  }
}
```

**Comment by Tohix** [comment]
Have the same problem

**Comment by markcabadsan** [comment]
Try to add `react-native-reanimated` to `transformIgnorePatterns` in `package.json`
```
 "transformIgnorePatterns": [
      "node_modules/(?!(@react-native|react-native|react-native-reanimated)/)"
    ],
```
