### ISSUE TITLE
Animated.createAnimatedComponent does not work with react-native-webview

### ISSUE THREAD

**Issue by peterlazar1993** [software-mansion/react-native-reanimated#4100]
### Description

When I try to create an AnimatedWebView via Animated.createAnimatedComponent the render fails with the following stacktrace.

```
Error: Argument appears to not be a ReactComponent. Keys: goForward,goBack,reload,stopLoading,postMessage,injectJavaScript,requestFocus

This error is located at:
    in Unknown (created by AnimatedComponent(Component))
    in AnimatedComponent(Component)
    in Unknown (created by App)
    in RCTSafeAreaView (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in bug(RootComponent), js engine: hermes

```

<img src="https://user-images.githubusercontent.com/4848554/221159018-42d3581b-45f0-4f58-bcd7-b0c3c1ce35db.png" width="300">

This error does not occur with with `Animated` from react-native

### Steps to reproduce

```
import WebView from 'react-native-webview';
import Animated from 'react-native-reanimated';

const AnimatedWebView = Animated.createAnimatedComponent(WebView);

# render AnimatedWebView
```

### Snack or a link to a repository

https://github.com/peterlazar1993/webview-reanimated-bug

### Reanimated version

2.14.4

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by mstach60161** [comment]
Hello, thank you for reporting the issue! Unfortunately we don't support animated `react-native-webview`. If you want to animate a `WebView`, you can wrap it in an animated `View` component.
