### ISSUE TITLE
Exiting animation not working on Animated.View

### ISSUE THREAD

**Issue by FN-FAL113** [software-mansion/react-native-reanimated#4108]
### Description

Entering works fine but exiting animation do not work
I even tried making a new app to test it out using the guide from the docs:
https://docs.swmansion.com/react-native-reanimated/docs/tutorials/LayoutAnimations/layoutAnimations

### Steps to reproduce

1. Created a new app 
2. followed the layout animations guide for testing it against my main app
3. Exiting animations does not work either even with the only needed packages for reanimated

### Reanimated version

2.14.4

### React Native version

0.71.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 5

### Acknowledgements

Yes

**Comment by FN-FAL113** [comment]
fixed, just add a container content style inside scrollview for wrapping child views, saw this fix here from a previous closed issue
```
<Animated.ScrollView 
        contentContainerStyle={{ flex: 1 }}
>
```

**Comment by vozaldi** [comment]
> fixed, just add a container content style inside scrollview for wrapping child views, saw this fix here from a previous closed issue
> 
> ```
> <Animated.ScrollView 
>         contentContainerStyle={{ flex: 1 }}
> >
> ```

This worked for me. Thanks!

---

In my case I already added `contentContainerStyle` but I used an array.

```
<Animated.ScrollView contentContainerStyle={[{ flexGrow: 1 }]}>
```

Removing the array fixed my issue.

```
<Animated.ScrollView contentContainerStyle={{ flexGrow: 1 }}>
```

This is a weird bug in my opinion 😕
