### ISSUE TITLE
v1.3.0 doesn't work with jetify -r

### ISSUE THREAD

**Issue by grit96** [software-mansion/react-native-reanimated#411]
I have updated to v1.3.0 and I am getting Android build errors with `react-native` 0.59.10.

```package android.support.transition does not exist```

I am using `jetify -r` in my `postinstall` because I cannot enable AndroidX yet.

**Comment by SaeedZhiany** [comment]
It's because the latest Gradle file is not backward compatible with support libraries.
`jetify -r` just converts `androidx` to `support ` in java files not the Gradle file.
for more information, you can take a look at a similar issue in [react-native-inappbrowser](https://github.com/proyecto26/react-native-inappbrowser/issues/96) that has been solved by its maintainer

**cc** @kmagiera

**Comment by SaeedZhiany** [comment]
@grit96 
you have two options:
1. modify [this line](https://github.com/kmagiera/react-native-reanimated/blob/7017262e86899845fa9813c4d9c0f0b5f1832bfa/android/build.gradle#L34) in the library's Gradle file manually and convert it back to use support library.

2. use a previous version of this library that doesn't migrate the Gradle file to androidx.

@kmagiera it worth if you add backward compatibility for support library just like the way @jdnichollsc has done in [this PR](https://github.com/proyecto26/react-native-inappbrowser/pull/97)

**Comment by timothystewart6** [comment]
Not sure if there is a 3rd option but I have been using `jetifier` as a `devDependency` along with

```
    "postinstall": "npx jetify",
```

and this has been working for me.  When switching to `jetify -r` is breaks.

Like so:

`yarn add --dev jetifier`

update `package.json`

```
    "postinstall": "npx jetify",
```

`react-native run-android`

Hope this helps! 😄

**Comment by SaeedZhiany** [comment]
@timothystewart6 
using `jetify` without the `-r` option migrate supportLib usages to androidx in java files and this is good only for those using RN +60, but @grit96 said that he is using RN 0.59.10 so your suggestion does not seem to be correct.

**Comment by chj-damon** [comment]
> @grit96
> you have two options:
> 
> 1. modify [this line](https://github.com/kmagiera/react-native-reanimated/blob/7017262e86899845fa9813c4d9c0f0b5f1832bfa/android/build.gradle#L34) in the library's Gradle file manually and convert it back to use support library.
> 2. use a previous version of this library that doesn't migrate the Gradle file to androidx.
> 
> @kmagiera it worth if you add backward compatibility for support library just like the way @jdnichollsc has done in [this PR](https://github.com/proyecto26/react-native-inappbrowser/pull/97)

any idea which version that doesn't migrate the Gradle file to androidx? I encountered the same problem. same react-native version 0.59.10

**Comment by timothystewart6** [comment]
@chj-damon  judging only be the [release notes](https://github.com/kmagiera/react-native-reanimated/releases) it looks like this was introduced on `1.3.0` so `1.2.0`.

**Comment by chj-damon** [comment]
@timothystewart6 Thanks！

**Comment by jdnichollsc** [comment]
If you want to avoid breaking changes from this library, you can add backward compatibility (maintainer) => https://twitter.com/jdnichollsc/status/1162451046544879616

**Comment by hello-jun** [comment]
> I have updated to v1.3.0 and I am getting Android build errors with `react-native` 0.59.10.
> 
> `package android.support.transition does not exist`
> 
> I am using `jetify -r` in my `postinstall` because I cannot enable AndroidX yet.

Open the file `android/gradle.properties`,and add the code below,you can  fixed the issue
```js
android.enableJetifier=true
android.useAndroidX=true
```

**Comment by jakub-gonet** [comment]
This issue is outdated right now, current React Native is 0.62 and we released reanimated v2 (changing `build.gradle` configs completely), so I'm closing it.
