### ISSUE TITLE
Using an array as a param of Animated.proc

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#412]
I'm using `proc` a lot currently and it fixes almost all my issues with reanimated (mostly perf issues). Especially I'm using it a lot with `interpoalte`, but it's quite limited. For now, I need to create separate interpolate proc for each `inputRange/outputRange` length.

Is it event possible (with some changes, of course) to pass an array as a param?

**Comment by jakub-gonet** [comment]
May be related to #287

**Comment by terrysahaidak** [comment]
Hi @jakub-gonet, not really. That one is about `Animated.sequence` alternative for Reanimated. My issue about dynamic params for the `Reanimated.proc` @chrfalch has implemented.

I would like to wrap interpolation in my animation into a proc for performance reasons. In order to get it workin, I have to pass all the arguments one by one. But as you may know interpolate requires me to pass two arrays - input range and output range.
So in order to wrap interpolate into a proc, I have to create proc for each my potential input range: for 2 elements, for 3 elements etc.

**Comment by jakub-gonet** [comment]
Overlooked this issue, sorry.

I think after releasing v2 this problem may be less inconvenient and Reanimated v1 will mostly receive bugfixes now, so I'm gonna close it now, but PRs are welcome if this change will be reasonably small.
