### ISSUE TITLE
Setting node value in native module (iOS)

### ISSUE THREAD

**Issue by Jarred-Sumner** [software-mansion/react-native-reanimated#413]
I'm writing a native module that plays video. I want to write the UI for the progress bar in JS, but set the progress value of the progress bar in native code. 

Ideally, I would pass an `Animated.Value` as a prop to the native module, and then call the equivalent of `Animated#setValue` but in Objective C.

Two questions:
1.  How do I access an `REANode` object passed as a prop? Typically, you get it via the node handle, but `REANode` doesn't subclass `UIView`, so you can't use `UIManager#addBlock`.
2. How do I call `setValue` on the `REANode`? Would it receive an `REAValueNode` and then call setValue on that?
https://github.com/kmagiera/react-native-reanimated/blob/master/ios/Nodes/REAValueNode.m#L16

Bonus question: How would I add a custom event here?
https://github.com/kmagiera/react-native-reanimated/blob/master/ios/REANodesManager.m#L358

**Comment by sebinq** [comment]
Hello @Jarred-Sumner. I would like to ask you if you solved your problem and if you can give me any hint to access Animated Node in my own NativeModule? Thanks!

**Comment by Jarred-Sumner** [comment]
You probably don’t want to, you should be able to pass the animated node to
the component like normal and react-native-reanimated will swap out the
node with the value for you automatically
