### ISSUE TITLE
[Reanimated] Couldn't determine the version of the native part of Reanimated. 

### ISSUE THREAD

**Issue by pouyarezvani** [software-mansion/react-native-reanimated#4134]
### Description

When Upgrading to version 3 I get the following error.
[Reanimated] Couldn't determine the version of the native part of Reanimated. Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must use the exact version which is bundled into Expo SDK.

![image](https://user-images.githubusercontent.com/32917154/222111227-91e71ebb-e04b-4543-8854-810c5d980bda.png)

I am using Expo Version 37, React Version 18, and reanimated Version "next" and react-native Version 0.70.5

### Steps to reproduce

1. upgrade to reanimated version 'next/3' and
2. Run expo GO
3. and get that error

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.0.0

### React Native version

70

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by arasrezaei** [comment]
expo still do not support V3.

**Comment by radko93** [comment]
Expo go do not support new reanimated. Also you might want to be on Expo 48 already.

**Comment by pouyarezvani** [comment]
@radko93 
Do you know how soon we can start using v3?
Thanks

**Comment by Wolf-111** [comment]
@pouyarezvani Hey did you happen to find a reliable fix for this? I'm using expo SDK 48 and I've tried pretty much everything I can think of with no luck

**Comment by AnatuGreen** [comment]
Expo continues with it's many problems. I am stuck with this also

**Comment by camchis** [comment]
Same error for me 
`"react-native": "^0.70.7"`
`"react-native-reanimated": "2.14.4"`

Not an expo project

**Comment by powerpivar** [comment]
Same issue for me,

`"react": "18.2.0"`
`"react-native": "0.72.3"`
`"react-native-reanimated": "2.14.4"`

No expo, IOS platform.

**Comment by fukemy** [comment]
any solution now?

**Comment by iainb123** [comment]
I'm having the same problem, using react-native 0.71.8, react-native-reanimated 2.14.4, no expo, IOS platform.  It looks like the native component should set "_REANIMATED_VERSION_CPP" when it loads.  I can see this in the .mm file in REAInitializer in the npm package, and this is visible in XCode in the Pods project, so it appears to be being built.  Somehow it isn't getting copied, or it is failing to initialise.

Can anyone point me to some docs that explain how this all fits together?  I'd like to trace the path through from a .mm in an npm package to XCode to some kind of binary.

**Comment by callmemonky** [comment]
Facing this w/

"react-native-reanimated": "3.4.2"
"react-native": "0.70.10"
  
 
Migrated from react-natigve-reanimated 2.13.0. We get these errors mostly when we do OTA update.

**Comment by awesomedan93** [comment]
still nothing ?

**Comment by Aakash359** [comment]
Hello i currenlty i am using react native version react-native@0.73.0 and i have the reanimated version 3.5.4 it is working in android simulator but when i am trying to run on my android devices then it's giving this error i had tried many version of reanimated lib but none of them working getting same issues pls someone help me to resolve this issues 
![Uploading 7ddcf101-2471-4672-9ef4-d316d472ca56.JPG…]()

**Comment by teddybee** [comment]
Same issue here with Expo SDK  50.0.2, 
npx expo install --fix is not fixing this warning.
"expo": "^50.0.2",
"react-native": "0.73.2",
"react-native-reanimated": "~3.6.0",
"@react-navigation/drawer": "^6.6.6",

**Comment by bobOnGitHub** [comment]
same.

**Comment by kiyohken2000** [comment]
same issue.

**Comment by demfabris** [comment]
Yep, upgraded to expo sdk 50 and I'm also seeing this

**Comment by ewein** [comment]
I'm seeing the issue as well.

**Comment by ewein** [comment]
I upgraded react-native-reanimated to 3.6.1 which seems to have fixed the issue.

**Comment by Shazam72** [comment]
That's though. I upgraded to 3.6.1 and i'm using expo sdk 50 (migrated from sdk 48) but it's still the same

**Comment by Shazam72** [comment]
Everything's working but the wanings are making me crazy.
Gotta build it with the warnings, the client want his app tomorrow

**Comment by i1kaaasra** [comment]
I see it with the latest versions

**Comment by ananduremanan** [comment]
downgrading expo to "expo": "~49.0.15" fix this issue for me...

**Comment by phillippschmedt** [comment]
Seeing the same issue.

**Comment by ananduremanan** [comment]
Seems like they messed up in the new expo version

**Comment by AlexNodex** [comment]
Same, Expo 50 upgrade from 49....

**Comment by wrobirson** [comment]
Same here from a brand new expo project with SDK 50.

**Comment by ambikaKum** [comment]
facing same issue over Android, no expo
"react-native-reanimated": "3.6.1",
 "react-native": "^0.73.1",

**Comment by piaskowyk** [comment]
When using Expo Go, it's important to stick to the recommended version of Reanimated. Expo Go includes a built-in version of Reanimated, so updating the Reanimated version only affects the JS part of Reanimated. Since Expo Go can't be recompiled without calling the `prebuild` command, there's a possibility of a mismatch between the JS part and the native part of Reanimated, which could lead to crashes.
