### ISSUE TITLE
[V3] ReferenceError: Property '_updateDataSynchronously' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by addingama** [software-mansion/react-native-reanimated#4137]
### Description

I'm getting this error message after upgrading the library to the latest

![image](https://user-images.githubusercontent.com/2896774/222137293-b262546f-7fde-4ccc-8d63-1153ea637fcc.png)

I've checked the source file and the `_updateDataSynchronously` is not defined anywhere on the file
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/2896774/222137496-770013ec-ac7c-4012-ad41-22a55e7b7a62.png">

### Steps to reproduce

-

### Snack or a link to a repository

-

### Reanimated version

3.0.0

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by mmmoussa** [comment]
I was able to get past this by restarting metro using `yarn start --reset-cache`

**Comment by piaskowyk** [comment]
I think that upgrade of Reanimated to the latest version and clear of cache should solve proble.
