### ISSUE TITLE
V3 Failed to create a worklet.

### ISSUE THREAD

**Issue by offcarlospetit** [software-mansion/react-native-reanimated#4138]
### Description

Hi, im actually testing new reanimated V3 in bare RN(0.71.3) app with  `react navigation v6` and `@shopify/restyle`, but i got this problem 

`Failed to create a worklet. Did you forget to add Reanimated Babel plugin in babel.config.js?`

And i already put that config in babel.config file 

### Steps to reproduce

`npm run start --reset-cache`

select ios emulator 

### Snack or a link to a repository

is a private repo

![Simulator Screen Shot - iPhone 14 - 2023-03-01 at 10 20 51](https://user-images.githubusercontent.com/15495315/222183302-0e72d331-af79-4a14-aae3-12ea3dcc9d9a.png)

### Reanimated version

3.0.0

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro Max

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi! Could you provide your `babel.config.js` file?

**Comment by terrysahaidak** [comment]
just to double check, @offcarlospetit, did you run your packager with `--reset-cache` after adding renimated plugin?

**Comment by offcarlospetit** [comment]
Hi, @tjzel this is my `babel.config.j`
<img width="615" alt="Screenshot 2023-03-01 at 19 40 31" src="https://user-images.githubusercontent.com/15495315/222300164-32fd84a4-a673-433d-97c4-caafd400e256.png">

And yes @terrysahaidak only remains restart my computer 😂

**Comment by tomekzaw** [comment]
Hey, for all npm users, the command should be `npm run start -- --reset-cache`, i.e. with `--` before `--reset-cache`.

**Comment by offcarlospetit** [comment]
perfect! now is working after this `npm run start -- --reset-cache` 
im already had do it this, but, works and this is the important fact! 😂

thanks @tomekzaw 🚀
