### ISSUE TITLE
Android stacked views

### ISSUE THREAD

**Issue by gringocl** [software-mansion/react-native-reanimated#414]
After upgrading to `1.3.0` we started seeing stacked views in android.

![Screenshot 2019-10-04 08 21 03](https://user-images.githubusercontent.com/3166322/66220687-4dfbdf00-e682-11e9-8357-113302c998c6.png)

This [change](https://github.com/kmagiera/react-native-reanimated/commit/c826e768a4789441b4927dbcae1ae4186787ecd8), This [line](https://github.com/kmagiera/react-native-reanimated/blob/c826e768a4789441b4927dbcae1ae4186787ecd8/android/src/main/java/com/swmansion/reanimated/nodes/Node.java#L35).  Java is not my strong suit, but with bisect and the only change that really made sense I was able to narrow it down.

**Comment by jakub-gonet** [comment]
Thanks for submitting an issue.

I'm assuming this particular problem was solved in the linked issue, so I'm closing it.

If you have any further concerns feel free to reopen
