### ISSUE TITLE
Cannot find module 'string-hash-64' 

### ISSUE THREAD

**Issue by jamesmbowler** [software-mansion/react-native-reanimated#4144]
### Description

On starting the app in android, I see this error:

> jamesbowler@Jamess-MacBook-Pro Example % yarn start  
yarn run v1.22.19
warning ../../package.json: No license field
$ node ./scripts/generateIndex.js && react-native start
reading file /Users/jamesbowler/react-native-reanimated/Example/index-template.js
writing to /Users/jamesbowler/react-native-reanimated/Example/index.js

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒

                Welcome to Metro v0.73.7
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

info Opening the app on Android...
info JS server already running.
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin UP-TO-DATE
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :react-native-gradle-plugin:processResources UP-TO-DATE
> Task :react-native-gradle-plugin:classes UP-TO-DATE
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :react-native-gradle-plugin:jar UP-TO-DATE

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.3.1
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :react-native-community_picker:preBuild UP-TO-DATE
> Task :react-native-community_picker:preDebugBuild UP-TO-DATE
> Task :react-native-community_picker:compileDebugAidl NO-SOURCE
> Task :react-native-community_slider:preBuild UP-TO-DATE
> Task :react-native-community_slider:preDebugBuild UP-TO-DATE
> Task :react-native-community_slider:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:assertNoMultipleInstances
> Task :react-native-gesture-handler:preBuild
> Task :react-native-gesture-handler:preDebugBuild
> Task :react-native-reanimated:assertLatestReactNativeWithNewArchitectureTask SKIPPED
> Task :react-native-reanimated:assertNoMultipleInstancesTask SKIPPED
> Task :react-native-reanimated:assertNoReanimated2WithNewArchitectureTask SKIPPED
> Task :react-native-reanimated:preBuild UP-TO-DATE
> Task :react-native-reanimated:preDebugBuild UP-TO-DATE
> Task :react-native-reanimated:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :react-native-masked-view_masked-view:preBuild UP-TO-DATE
> Task :react-native-masked-view_masked-view:preDebugBuild UP-TO-DATE
> Task :react-native-masked-view_masked-view:compileDebugAidl NO-SOURCE
> Task :react-native-pager-view:preBuild UP-TO-DATE
> Task :react-native-pager-view:preDebugBuild UP-TO-DATE
> Task :react-native-pager-view:compileDebugAidl NO-SOURCE
> Task :react-native-safe-area-context:preBuild UP-TO-DATE
> Task :react-native-safe-area-context:preDebugBuild UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugAidl NO-SOURCE
> Task :react-native-screens:preBuild UP-TO-DATE
> Task :react-native-screens:preDebugBuild UP-TO-DATE
> Task :react-native-screens:compileDebugAidl NO-SOURCE
> Task :react-native-svg:preBuild UP-TO-DATE
> Task :react-native-svg:preDebugBuild UP-TO-DATE
> Task :react-native-svg:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-community_picker:packageDebugRenderscript NO-SOURCE
> Task :react-native-community_slider:packageDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :react-native-masked-view_masked-view:packageDebugRenderscript NO-SOURCE
> Task :react-native-pager-view:packageDebugRenderscript NO-SOURCE
> Task :react-native-reanimated:packageDebugRenderscript NO-SOURCE
> Task :react-native-safe-area-context:packageDebugRenderscript NO-SOURCE
> Task :react-native-screens:packageDebugRenderscript NO-SOURCE
> Task :react-native-svg:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :react-native-community_picker:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-community_slider:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-gesture-handler:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-masked-view_masked-view:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-pager-view:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-reanimated:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-safe-area-context:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-screens:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-svg:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :react-native-community_picker:compileDebugRenderscript NO-SOURCE
> Task :react-native-community_picker:generateDebugResValues UP-TO-DATE
> Task :react-native-community_picker:generateDebugResources UP-TO-DATE
> Task :react-native-community_picker:packageDebugResources UP-TO-DATE
> Task :react-native-community_slider:compileDebugRenderscript NO-SOURCE
> Task :react-native-community_slider:generateDebugResValues UP-TO-DATE
> Task :react-native-community_slider:generateDebugResources UP-TO-DATE
> Task :react-native-community_slider:packageDebugResources UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugResources UP-TO-DATE
> Task :react-native-gesture-handler:packageDebugResources UP-TO-DATE
> Task :react-native-masked-view_masked-view:compileDebugRenderscript NO-SOURCE
> Task :react-native-masked-view_masked-view:generateDebugResValues UP-TO-DATE
> Task :react-native-masked-view_masked-view:generateDebugResources UP-TO-DATE
> Task :react-native-masked-view_masked-view:packageDebugResources UP-TO-DATE
> Task :react-native-pager-view:compileDebugRenderscript NO-SOURCE
> Task :react-native-pager-view:generateDebugResValues UP-TO-DATE
> Task :react-native-pager-view:generateDebugResources UP-TO-DATE
> Task :react-native-pager-view:packageDebugResources UP-TO-DATE
> Task :react-native-reanimated:compileDebugRenderscript NO-SOURCE
> Task :react-native-reanimated:generateDebugResValues UP-TO-DATE
> Task :react-native-reanimated:generateDebugResources UP-TO-DATE
> Task :react-native-reanimated:packageDebugResources UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugRenderscript NO-SOURCE
> Task :react-native-safe-area-context:generateDebugResValues UP-TO-DATE
> Task :react-native-safe-area-context:generateDebugResources UP-TO-DATE
> Task :react-native-safe-area-context:packageDebugResources UP-TO-DATE
> Task :react-native-screens:compileDebugRenderscript NO-SOURCE
> Task :react-native-screens:generateDebugResValues UP-TO-DATE
> Task :react-native-screens:generateDebugResources UP-TO-DATE
> Task :react-native-screens:packageDebugResources UP-TO-DATE
> Task :react-native-svg:compileDebugRenderscript NO-SOURCE
> Task :react-native-svg:generateDebugResValues UP-TO-DATE
> Task :react-native-svg:generateDebugResources UP-TO-DATE
> Task :react-native-svg:packageDebugResources UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-community_picker:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-community_picker:processDebugManifest UP-TO-DATE
> Task :react-native-community_slider:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-community_slider:processDebugManifest UP-TO-DATE
> Task :react-native-gesture-handler:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-gesture-handler:processDebugManifest UP-TO-DATE
> Task :react-native-masked-view_masked-view:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-masked-view_masked-view:processDebugManifest UP-TO-DATE
> Task :react-native-pager-view:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-pager-view:processDebugManifest UP-TO-DATE
> Task :react-native-reanimated:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-reanimated:processDebugManifest UP-TO-DATE
> Task :react-native-safe-area-context:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-safe-area-context:processDebugManifest UP-TO-DATE
> Task :react-native-screens:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-screens:processDebugManifest UP-TO-DATE
> Task :react-native-svg:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-svg:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :react-native-community_picker:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-community_picker:parseDebugLocalResources UP-TO-DATE
> Task :react-native-community_picker:generateDebugRFile UP-TO-DATE
> Task :react-native-community_slider:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-community_slider:parseDebugLocalResources UP-TO-DATE
> Task :react-native-community_slider:generateDebugRFile UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-gesture-handler:parseDebugLocalResources UP-TO-DATE
> Task :react-native-reanimated:parseDebugLocalResources UP-TO-DATE
> Task :react-native-reanimated:generateDebugRFile UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugRFile UP-TO-DATE
> Task :react-native-masked-view_masked-view:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-masked-view_masked-view:parseDebugLocalResources UP-TO-DATE
> Task :react-native-masked-view_masked-view:generateDebugRFile UP-TO-DATE
> Task :react-native-pager-view:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-pager-view:parseDebugLocalResources UP-TO-DATE
> Task :react-native-pager-view:generateDebugRFile UP-TO-DATE
> Task :react-native-reanimated:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-safe-area-context:parseDebugLocalResources UP-TO-DATE
> Task :react-native-safe-area-context:generateDebugRFile UP-TO-DATE
> Task :react-native-screens:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-screens:parseDebugLocalResources UP-TO-DATE
> Task :react-native-screens:generateDebugRFile UP-TO-DATE
> Task :react-native-svg:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-svg:parseDebugLocalResources UP-TO-DATE
> Task :react-native-svg:generateDebugRFile UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :react-native-community_picker:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-community_picker:javaPreCompileDebug UP-TO-DATE
> Task :react-native-community_picker:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-community_picker:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-community_slider:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-community_slider:javaPreCompileDebug UP-TO-DATE
> Task :react-native-community_slider:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-community_slider:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-reanimated:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-reanimated:javaPreCompileDebug UP-TO-DATE
> Task :react-native-reanimated:packageNdkLibs NO-SOURCE
> Task :react-native-reanimated:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-reanimated:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugKotlin UP-TO-DATE
> Task :react-native-gesture-handler:javaPreCompileDebug UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-gesture-handler:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-masked-view_masked-view:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-masked-view_masked-view:javaPreCompileDebug UP-TO-DATE
> Task :react-native-masked-view_masked-view:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-masked-view_masked-view:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-pager-view:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-pager-view:compileDebugKotlin UP-TO-DATE
> Task :react-native-pager-view:javaPreCompileDebug UP-TO-DATE
> Task :react-native-pager-view:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-pager-view:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-safe-area-context:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugKotlin UP-TO-DATE
> Task :react-native-safe-area-context:javaPreCompileDebug UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-safe-area-context:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-screens:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-screens:compileDebugKotlin UP-TO-DATE
> Task :react-native-screens:javaPreCompileDebug UP-TO-DATE
> Task :react-native-screens:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-screens:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-svg:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-svg:javaPreCompileDebug UP-TO-DATE
> Task :react-native-svg:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-svg:bundleLibCompileToJarDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :react-native-community_picker:mergeDebugShaders UP-TO-DATE
> Task :react-native-community_picker:compileDebugShaders NO-SOURCE
> Task :react-native-community_picker:generateDebugAssets UP-TO-DATE
> Task :react-native-community_picker:packageDebugAssets UP-TO-DATE
> Task :react-native-community_slider:mergeDebugShaders UP-TO-DATE
> Task :react-native-community_slider:compileDebugShaders NO-SOURCE
> Task :react-native-community_slider:generateDebugAssets UP-TO-DATE
> Task :react-native-community_slider:packageDebugAssets UP-TO-DATE
> Task :react-native-gesture-handler:mergeDebugShaders UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugShaders NO-SOURCE
> Task :react-native-gesture-handler:generateDebugAssets UP-TO-DATE
> Task :react-native-gesture-handler:packageDebugAssets UP-TO-DATE
> Task :react-native-masked-view_masked-view:mergeDebugShaders UP-TO-DATE
> Task :react-native-masked-view_masked-view:compileDebugShaders NO-SOURCE
> Task :react-native-masked-view_masked-view:generateDebugAssets UP-TO-DATE
> Task :react-native-masked-view_masked-view:packageDebugAssets UP-TO-DATE
> Task :react-native-pager-view:mergeDebugShaders UP-TO-DATE
> Task :react-native-pager-view:compileDebugShaders NO-SOURCE
> Task :react-native-pager-view:generateDebugAssets UP-TO-DATE
> Task :react-native-pager-view:packageDebugAssets UP-TO-DATE
> Task :react-native-reanimated:mergeDebugShaders UP-TO-DATE
> Task :react-native-reanimated:compileDebugShaders NO-SOURCE
> Task :react-native-reanimated:generateDebugAssets UP-TO-DATE
> Task :react-native-reanimated:packageDebugAssets UP-TO-DATE
> Task :react-native-safe-area-context:mergeDebugShaders UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugShaders NO-SOURCE
> Task :react-native-safe-area-context:generateDebugAssets UP-TO-DATE
> Task :react-native-safe-area-context:packageDebugAssets UP-TO-DATE
> Task :react-native-screens:mergeDebugShaders UP-TO-DATE
> Task :react-native-screens:compileDebugShaders NO-SOURCE
> Task :react-native-screens:generateDebugAssets UP-TO-DATE
> Task :react-native-screens:packageDebugAssets UP-TO-DATE
> Task :react-native-svg:mergeDebugShaders UP-TO-DATE
> Task :react-native-svg:compileDebugShaders NO-SOURCE
> Task :react-native-svg:generateDebugAssets UP-TO-DATE
> Task :react-native-svg:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :react-native-community_picker:processDebugJavaRes NO-SOURCE
> Task :react-native-community_picker:bundleLibResDebug NO-SOURCE
> Task :react-native-community_slider:processDebugJavaRes NO-SOURCE
> Task :react-native-community_slider:bundleLibResDebug NO-SOURCE
> Task :react-native-gesture-handler:processDebugJavaRes NO-SOURCE
> Task :react-native-gesture-handler:bundleLibResDebug UP-TO-DATE
> Task :react-native-masked-view_masked-view:processDebugJavaRes NO-SOURCE
> Task :react-native-masked-view_masked-view:bundleLibResDebug NO-SOURCE
> Task :react-native-pager-view:processDebugJavaRes NO-SOURCE
> Task :react-native-pager-view:bundleLibResDebug UP-TO-DATE
> Task :react-native-reanimated:processDebugJavaRes NO-SOURCE
> Task :react-native-reanimated:bundleLibResDebug NO-SOURCE
> Task :react-native-safe-area-context:processDebugJavaRes NO-SOURCE
> Task :react-native-safe-area-context:bundleLibResDebug UP-TO-DATE
> Task :react-native-screens:processDebugJavaRes NO-SOURCE
> Task :react-native-screens:bundleLibResDebug UP-TO-DATE
> Task :react-native-svg:processDebugJavaRes NO-SOURCE
> Task :react-native-svg:bundleLibResDebug NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :react-native-gesture-handler:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-reanimated:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-community_picker:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-community_slider:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-masked-view_masked-view:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-pager-view:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-safe-area-context:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-screens:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :react-native-svg:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeProjectDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-community_picker:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-community_picker:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-community_picker:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-community_slider:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-community_slider:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-community_slider:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-gesture-handler:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-gesture-handler:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-gesture-handler:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-masked-view_masked-view:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-masked-view_masked-view:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-masked-view_masked-view:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-pager-view:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-pager-view:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-pager-view:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-reanimated:configureCMakeDebug[arm64-v8a]
> Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
> Task :react-native-reanimated:configureCMakeDebug[armeabi-v7a]
> Task :react-native-reanimated:buildCMakeDebug[armeabi-v7a]
> Task :react-native-reanimated:configureCMakeDebug[x86]
> Task :react-native-reanimated:buildCMakeDebug[x86]
> Task :react-native-reanimated:configureCMakeDebug[x86_64]
> Task :react-native-reanimated:buildCMakeDebug[x86_64]
> Task :react-native-reanimated:externalNativeBuildDebug

> Task :react-native-reanimated:mergeDebugJniLibFolders
Execution optimizations have been disabled for task ':react-native-reanimated:mergeDebugJniLibFolders' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/jamesbowler/react-native-reanimated/android/src/main/jniLibs'. Reason: Task ':react-native-reanimated:mergeDebugJniLibFolders' uses this output of task ':react-native-reanimated:packageNdkLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :react-native-reanimated:mergeDebugNativeLibs UP-TO-DATE
> Task :react-native-reanimated:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-safe-area-context:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-safe-area-context:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-safe-area-context:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-screens:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-screens:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-screens:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :react-native-svg:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-svg:mergeDebugNativeLibs NO-SOURCE
> Task :react-native-svg:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:createDebugApkListingFileRedirect UP-TO-DATE

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_2_API_31(AVD) - 12' for :app:debug
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 21s
210 actionable tasks: 13 executed, 197 up-to-date
info Connecting to the development server...
8081
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.swmansion.reanimated.example/.MainActivity }
 BUNDLE  ./index.js 

error: index.js: [BABEL]: Cannot find module 'string-hash-64'
Require stack:
- /Users/jamesbowler/react-native-reanimated/plugin/index.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/@babel/core/lib/config/files/index.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/@babel/core/lib/index.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/metro-transform-worker/src/index.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/metro/src/DeltaBundler/Worker.flow.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/jamesbowler/react-native-reanimated/Example/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js (While processing: /Users/jamesbowler/react-native-reanimated/plugin/index.js)

### Steps to reproduce

1. clone repo && cd to Example
2. yarn 
3. yarn start
4. click "a" to open in android

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated
main branch on public repo

### Reanimated version

3.0 (main branch)

### React Native version

"react-native": "0.71.3" (from package.json)

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

multiple android, pixel 6/4

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi! According to Example installation README first step is to execute `yarn` in root directory (not in `Example`) directory. Have you done that?

**Comment by jamesmbowler** [comment]
Oh, that was it - thank you and sorry 🙏

**Comment by tjzel** [comment]
No problem, that's what issues are for :)

**Comment by error-try-again** [comment]
Hi @tjzel I am also experiencing the issue as described by OP and have followed the installation instructions, as well as the proposed solution here.

**Comment by tjzel** [comment]
@error-try-again hi, I would need some information about the steps to reproduce your issue. I know you said you followed the instructions but we would need to pin down why the solution didn't work for you.

**Comment by piaskowyk** [comment]
Closed due to inactive 😔

To sum up, if you want to run example app from Reanimated repo you need to follow this instruction:
https://github.com/software-mansion/react-native-reanimated/tree/main/Example#readme
