### ISSUE TITLE
Keyframes are not working with SVG components using createAnimatedComponent

### ISSUE THREAD

**Issue by bhushan-patil-official** [software-mansion/react-native-reanimated#4146]
### Description

I am trying to create an animated svg using keyframes, but it is not animating. I tried animating a normal view using the keyframes, view works fine. But svg does not.

### Steps to reproduce

1. Create a component using Animated.createAnimatedComponent(Circle)
2. Create a keyframe and use that keyframe for entering
3. The animation does not work

### Snack or a link to a repository

https://snack.expo.dev/@bhushan.patil/forlorn-mixed-nuts

### Reanimated version

2.9.0

### React Native version

0.69.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @bhushan-patil-official, thanks for reporting this issue. Can you please check if the problem still persists on 3.0.0?

**Comment by bhushan-patil-official** [comment]
Hey @tomekzaw thanks for the quick reply. I am not able to install 3.0.2 the latest stable version. When I do, and run the app. I am getting this error:
`TypeError: undefined is not a constructor (evaluating 'new react_native_reanimated_1.default.Value(0)')`

Can you help me find what I am doing wrong?

**Comment by tomekzaw** [comment]
@bhushan-patil-official Unfortunately, Reanimated v3 doesn't support Reanimated v1 API. (`new Animated.Value(0)`). Do you use v1 API in your app directly or via some third-party library?

**Comment by piaskowyk** [comment]
Closed due to inactivity.
