### ISSUE TITLE
Markers are not removed when used with react-native-maps

### ISSUE THREAD

**Issue by sebastienlabine** [software-mansion/react-native-reanimated#4152]
### Description

When used with react-native-maps, markers on the maps are never removed. They will always stay visible.

 A patch is actually working to fix this problem:
https://github.com/l-barbosa/react-native-maps-reanimated-issue/blob/master/patches/react-native-reanimated%2B2.8.0.patch

https://github.com/react-native-maps/react-native-maps/issues/4214
https://github.com/react-native-maps/react-native-maps/issues/4102
### Steps to reproduce

1. Use react-native-maps
2. Add a marker with a transition inside of it
3. Remove the marker from the map
4 The marker will still be there 

### Snack or a link to a repository

https://github.com/l-barbosa/react-native-maps-reanimated-issue/tree/master

### Reanimated version

2.9.1

### React Native version

0.69.6

### Platforms

Android, iOS

### JavaScript runtime

JSC

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

Real device

### Device model

iPhone 12 16.0.1

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @sebastienlabine, thanks for reporting this issue as well as for the fix. Layout Animations were rewritten in #3332 and we released the new implementation along with Reanimated 3.0.0. Can you please check if v3 resolves this issue? Note that Expo SDK still uses Reanimated v2.

**Comment by sebastienlabine** [comment]
Hey @tomekzaw I'll try to take a look this week with V3. thanks

**Comment by piaskowyk** [comment]
Let us know if you still facing this issue.

**Comment by andrecrimb** [comment]
Issue still persists. 
I've noticed that I'm not able to reproduce this issue locally, but only via production builds. Furthermore, it tends to occur when a marker is rendered/removed without being in focus. For example, if the map is currently centered on city X, and a pin is added or removed in city Y, which is outside the current visible area.

**Comment by falk-stefan** [comment]
I don't know if I face the same root cause, but markers are not disappearing or getting unmounted as they should with:

```json
    "react-native-maps": "^1.27.2",
    "react-native-reanimated": "~4.1.1",
```
