### ISSUE TITLE
v3 regression TypeError: Cannot convert undefined value to object

### ISSUE THREAD

**Issue by haibert** [software-mansion/react-native-reanimated#4153]
### Description

Hey guys,

before this was acceptable 

```
             <Animated.View style={[animatedStyle, props.someStyle]}>
                {children}
            </Animated.View>
```

But now if in your component you dont pass someStyle, you get an error: 

"TypeError: Cannot convert undefined value to object"

and for this reason the react-navigation drawer component makes the app crash unless you add an empty object to the style. 

```  
                screenOptions={{
                    drawerStyle: {},
                }}
```

### Steps to reproduce

1. add reaniamted v3
2. create a component that optionally passed a style object to an animated view
3. dont pass the optional style

### Snack or a link to a repository

https://snack.expo.dev/

### Reanimated version

3

### React Native version

71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 pro

### Acknowledgements

Yes

**Comment by TowhidKashem** [comment]
Try the patch here:

https://github.com/software-mansion/react-native-reanimated/issues/4139

It worked for me.

**Comment by haibert** [comment]
> Try the patch here:
> 
> #4139
> 
> It worked for me.

Its all good, I added this to the drawer navigation and the crash went away. I just wanted to bring this to the teams attention so they fix it over all. 

```
  <Drawer.Navigator
          screenOptions={{
             drawerStyle: {},
          }}
```
