### ISSUE TITLE
v3 => Can't find variable: _notifyAboutProgress

### ISSUE THREAD

**Issue by fukemy** [software-mansion/react-native-reanimated#4156]
### Description

I got this error when run android after update to v.3.0.0
***Can't find variable: _notifyAboutProgress***

<img width="658" alt="Screen Shot 2023-03-03 at 14 57 20" src="https://user-images.githubusercontent.com/8202437/222663923-0930a3f4-7b02-4f6e-bd50-92a84467fafd.png">

### Steps to reproduce

npm i reanimated@3.0.0
npm run android --reset-cache

### Snack or a link to a repository

No snack here

### Reanimated version

3.0.0

### React Native version

0.68.2

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Android Vsmart

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Please run `npm run start -- --reset-cache` first.

**Comment by fukemy** [comment]
I successful run project, but got this error next: 
```
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[40], "react-native-reanimated").Transition.Together')
 ERROR  Error: Requiring module "screen/home/RecentScreen.js", which threw an exception: TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[40], "react-native-reanimated").Transition.Together')
```

can u help?

**Comment by tomekzaw** [comment]
@fukemy The error is caused by using `<Transition.Together>` which comes from Reanimated v1 API which is no longer available in v3.

**Comment by fukemy** [comment]
sorry for borther you @tomekzaw . I just check the reanimated source, and I still found class for Transition like this:

<img width="1512" alt="Screen Shot 2023-03-03 at 15 32 00" src="https://user-images.githubusercontent.com/8202437/222671159-fdfa6b43-1cfe-4762-9b41-95b59acd39fd.png">


Im sure I am using v3.0.0, but I dont know why the Transition api make this crash

**Comment by fukemy** [comment]
I follow to the v2 document here: https://docs.swmansion.com/react-native-reanimated/docs/2.x/api/LayoutAnimations/layoutTransitions
Here is my code:
const AnimatedComponent = Animated.createAnimatedComponent(View)
const transition = Transition.duration(3000).otherModifier()
return <AnimatedComponent ref={parentRef} transition={transition}>....

```

 But I got this error when define : const transition = Transition.duration(3000).otherModifier()
 
 Can u help:

**Comment by tomekzaw** [comment]
@fukemy There are 2 different Transitions: 
* Transitions from v1 API (https://docs.swmansion.com/react-native-reanimated/docs/1.x/transitions/)
* Layout Transitions from v2 API (https://docs.swmansion.com/react-native-reanimated/docs/2.x/api/LayoutAnimations/layoutTransitions/)

Transitions from v1 API are no longer available in Reanimated v3 (we removed the JavaScript files but we forgot to remove TypeScript definitions from `react-native-reanimated.d.ts`, will remove it soon).

Layout Transitions from v2 API are perfectly valid to use in Reanimated v3.

**Comment by fukemy** [comment]
thanks, I switched back to LayoutAnimation API from react-native because I can not make shuffle animation without Transition v2 API :(

**Comment by tomekzaw** [comment]
@fukemy You can use Layout Transitions from v2 API with Reanimated 3.

**Comment by a-tokyo** [comment]
@tomekzaw Do you happen to know the equivalent of Transition.Together in v3? I am trying to fix a library?

I checked the migration guide from 1 to 2 and it only had docs about interpolate, no transition docs

Thanks in advance!
