### ISSUE TITLE
[Question] Assign and callback in a block

### ISSUE THREAD

**Issue by chuanhd** [software-mansion/react-native-reanimated#416]
Hi everybody,

I want to ask how to assign animated node to value and call a callback in a block. 

More specific, I want to call `this.endDragging`  and set `this._translateY` to zero when gestureState END

```javascript
this._translateY = [
      cond(
        eq(this._isResizing, 0),
        cond(eq(this.gestureState, State.ACTIVE), addY, 
        [
          cond(eq(this.gestureState, State.END), [call([addY], this.endDragging), 0]),
          set(this.offsetY, addY),
        ]),
        0
      ),
    ]
```

Thanks in advance

**Comment by jakub-gonet** [comment]
Not sure if understood correctly, but every node returns a value, so your code should work:
```
[
	call([addY], this.endDragging),  // this calls this.endDragging if addY changed
	0                                // this returns 0
]
```

If that's not the case please provide a minimal reproducible example on https://snack.expo.io/.

**Comment by chuanhd** [comment]
Thanks for your reply. I made it work

**Comment by JulianKingman** [comment]
@chuanhd how did you accomplish it?
