### ISSUE TITLE
defineProperty2.default is not a function

### ISSUE THREAD

**Issue by AndreiCalazans** [software-mansion/react-native-reanimated#4162]
### Description

This seems like a Babel plugin issue, we consume a shared lib and one of its useAnimatedStyle crashes defineProperty2.default is not a function. 

This is the untranspiled TS snippet of code where the crash happens:
```typescript
      const animatedStyles = useAnimatedStyle(() => ({
        [animateInMaxSize.property]: heightAnimatedValue.value,
        opacity: Number(opacityAnimatedValue.value),
      }));

```

This is how we consume it (transpiled)
```javascript
function(){var _ref2;return _ref2={},(0,_defineProperty2.default)(_ref2,animateInMaxSize.property,heightAnimatedValue.value),(0,_defineProperty2.default)(_ref2,"opacity",Number(opacityAnimatedValue.value)),_ref2;}
```

Odd enough, if in node_modules I turn this package file to TypeScript and paste its untranspiled version I don't get the crash.

<img width="200px" src="https://user-images.githubusercontent.com/20777666/222743960-16bc608c-b90c-4eb4-b3aa-ab22098e48e2.png" />

Notes:
- This only seems to happen where we have the bracket notation to define property
- Other places in the transpiled code where we have `defineProperty2.default` they don't seem to crash.

### Steps to reproduce

1. Create a useAnimatedStyle that uses bracket notation to define the returned style object. 

### Snack or a link to a repository

None

### Reanimated version

3.0.0

### React Native version

0.70.3

### Platforms

Android, iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @AndreiCalazans! I made a simple app and failed to reproduce the error. Here's the snippet:

```typescript
import React from 'react';
import { Text } from 'react-native';

import { useAnimatedStyle, useSharedValue } from 'react-native-reanimated';
import Animated from 'react-native-reanimated';

export default function App() {
  const backgroundColor = useSharedValue('red');
  const flex = useSharedValue('1');
  const verticalAlignProp = useSharedValue('verticalAlign');
  const obj = {
    flexProp: 'flex',
    justifyContentProp: 'justifyContent',
    justifyContentValue: 'center',
    backgroundColorProp: 'backgroundColor',
  };

  const animatedStyles = useAnimatedStyle(() => ({
    [obj.justifyContentProp]: obj.justifyContentValue,
    [obj.backgroundColorProp]: backgroundColor.value,
    [obj.flexProp]: Number(flex.value),
    [verticalAlignProp.value]: 'middle',
  }));

  return (
    <Animated.View style={animatedStyles}>
      <Text>Animate!</Text>
    </Animated.View>
  );
}
```

Maybe the problem is `animateInMaxSize` object?

**Comment by AndreiCalazans** [comment]
Hey @tjzel, 

Can you verify and try the following:

1. Verify that the resulting transpiled code for the useAnimatedStyle actually has the usage of _defineProperty2 from the 
2. Can you try using an object that is imported from another file or something? (in our case the object used as a key was returned by custom hook)

> Maybe the problem is animateInMaxSize object?
The crash was not pointing to animateInMaxSize but rather to the specifically the Babel transpiling function not being present (_defineProperty2.default), I believe this function is from one of the Babel's transformers for computed values.

**Comment by tjzel** [comment]
Still no crashes.
### App.tsx
```TypeScript
import React from 'react';
import { Text } from 'react-native';
import { obj } from './AppObject';

import { useAnimatedStyle, useSharedValue } from 'react-native-reanimated';
import Animated from 'react-native-reanimated';

export default function App() {
  const backgroundColor = useSharedValue('red');
  const flex = useSharedValue('1');
  const verticalAlignProp = useSharedValue('verticalAlign');

  const animatedStyles = useAnimatedStyle(() => ({
    [obj.justifyContentProp]: obj.justifyContentValue,
    [obj.backgroundColorProp]: backgroundColor.value,
    [obj.flexProp]: Number(flex.value),
    [verticalAlignProp.value]: 'middle',
  }));

  return (
    <Animated.View style={animatedStyles}>
      <Text>Animate!</Text>
    </Animated.View>
  );
}
```
### AppObject.tsx:
```TypeScript
const obj = {
  flexProp: 'flex',
  justifyContentProp: 'justifyContent',
  justifyContentValue: 'center',
  backgroundColorProp: 'backgroundColor',
};

export { obj };
```
### Transpiled code:
```JavaScript
var _f=function _f(){var _ref;return _ref={},(0,_defineProperty2.default)(_ref,_AppObject.obj.justifyContentProp,_AppObject.obj.justifyContentValue),(0,_defineProperty2.default)(_ref,_AppObject.obj.backgroundColorProp,backgroundColor.value),(0,_defineProperty2.default)(_ref,_AppObject.obj.flexProp,Number(flex.value)),(0,_defineProperty2.default)(_ref,verticalAlignProp.value,'middle'),_ref;};_f._closure={obj:_AppObject.obj,backgroundColor:backgroundColor,flex:flex,verticalAlignProp:verticalAlignProp};_f.__initData=_worklet_13339348172784_init_data;_f.__workletHash=13339348172784;_f.__stackDetails=_e;return _f;}());
```
As you can see `_defineProperty2` is there. I think a more extensive repro is required here.
Just to be sure, did you run `yarn start --reset-cache` (or its npm counterpart `npm run start -- --reset-cache`) after bumping to reanimated 3.0?

**Comment by AndreiCalazans** [comment]
@tjzel thanks for looking into, I'll close the issue since you couldn't reproduce it and try to investigate in our end again. Thank you.
