### ISSUE TITLE
hooks randomly stop running

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#4168]
### Description

I'm the maintainer of [`react-native-collapsible-tab-view`](https://github.com/PedroBern/react-native-collapsible-tab-view). 

I recently released version 6.0 of the aforementioned library and bumped reanimated to version 3.0.

I noticed that with reanimated 3.0 that hooks like `useAnimatedReaction`, `useDerivedValue` and `useAnimatedStyle` randomly stop running their code. Only tested on iOS so far.

## Broken:

Notice how in the recording below, the code in `useDerivedValue` is not printing anything:

https://user-images.githubusercontent.com/697707/222921089-4d3cf34f-d0f0-4803-8f22-3a2c66c88d4b.mp4

## Working:

If I reload the app, it starts working again. One thing to note is that when this starts occuring, the entire app seems affected. Remounting the React component does not help. Reanimated seems dead unless the app is reloaded. Using the dev menu to reload does work, so I'm unsure if this is an issue in the native layer.

https://user-images.githubusercontent.com/697707/222921139-854a1f76-b2e6-41b4-bcf6-75546d93fde6.mp4

### Steps to reproduce

The issue occurs randomly, but I'm able to repro it in the example app of https://github.com/PedroBern/react-native-collapsible-tab-view

Go to `example` and run `yarn ios` then try swiping around the pages and scroll up and down until it eventually breaks. It's easiest to reproduce in the `Scrollable Tabs` example.

### Snack or a link to a repository

https://github.com/PedroBern/react-native-collapsible-tab-view

### Reanimated version

3.0.1

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by andreialecu** [comment]
I just confirmed it to also occur on Android.

**Comment by andreialecu** [comment]
Here's how to reproduce it using the example app in: https://github.com/PedroBern/react-native-collapsible-tab-view

https://user-images.githubusercontent.com/697707/222922104-41e8c1b7-c3ef-44da-aa38-529419964762.mp4

**Comment by andreialecu** [comment]
I've been trying various Reanimated versions and cannot reproduce it on `3.0.0-rc.9`. 

The first version I can reproduce it on is `rc.10`.

For reference: https://github.com/software-mansion/react-native-reanimated/compare/3.0.0-rc.9...3.0.0-rc.10

**Comment by piaskowyk** [comment]
We are working on this issue. I will post the update soon.

**Comment by trungledangAxonActive** [comment]
I'm still facing this issue after the fix from @mstach60161, All the hooks related to animated are dead and they don't run sometimes. 
I'm using `react-native-reanimated: "3.3.0"`

**Comment by Karthik-B-06** [comment]
I am still facing this issue. The `useAnimatedReaction` hooks work the first time when the component is mounted and not for the next remounts.

Is there a fix? Or a hacky way around? 

I am Using `react-native-reanimated": "~3.6.3`
