### ISSUE TITLE
User has minSdkVersion 16 but library was built for 21 [//ReactAndroid/fabricjni]

### ISSUE THREAD

**Issue by tapz** [software-mansion/react-native-reanimated#4169]
### Description

I get this error when building the app:

```
Execution failed for task ':react-native-reanimated:configureCMakeDebug[armeabi-v7a]'.
[CXX1214] .../node_modules/react-native-reanimated/android/CMakeLists.txt debug|armeabi-v7a : User has minSdkVersion 16 but library was built for 21 [//ReactAndroid/fabricjni]
```

I'm using an M2 Max MacBook Pro.

### Steps to reproduce

1. react-native run-android

### Snack or a link to a repository

x

### Reanimated version

3.0.0

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by reyanshmishra** [comment]
I am too facing the same issue!!

**Comment by buraksaritas** [comment]
> Added this to my build.gradle and the build now succeeds.
> 
> ```
> buildscript {
>   ext.minSdkVersion = 22
> ```
> 
> But I get this warning:
> 
> ```
> > Task :react-native-reanimated:mergeDebugJniLibFolders
> Execution optimizations have been disabled for task ':react-native-reanimated:mergeDebugJniLibFolders' to ensure correctness due to the following reasons:
>   - Gradle detected a problem with the following location: '.../node_modules/react-native-reanimated/android/src/main/jniLibs'. Reason: Task ':react-native-reanimated:mergeDebugJniLibFolders' uses this output of task ':react-native-reanimated:packageNdkLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
> ```

What is the solution for your latest warning?
