### ISSUE TITLE
Jest import incorrect

### ISSUE THREAD

**Issue by bitcrumb** [software-mansion/react-native-reanimated#4172]
### Description

The [documentation](https://docs.swmansion.com/react-native-reanimated/docs/guide/testing) mentions importing from `react-native-reanimated/lib/reanimated2/jestUtils` to be able to call `setUpTests`. However, this import can't be resolved:

<img width="1019" alt="Screenshot 2023-03-06 at 08 38 10" src="https://user-images.githubusercontent.com/135126/223047944-3a0ede9d-715c-4b90-ba4f-f394d98255d7.png">

Changing the import path to `react-native-reanimated/src/reanimated2/jestUtils` (so using `src` instead of `lib`) does seem to work, but not sure this is intended/best practice.

### Steps to reproduce

1. Install react-native-reanimated 3.0.0
2. Setup jest
3. Follow instructions on https://docs.swmansion.com/react-native-reanimated/docs/guide/testing

### Snack or a link to a repository

n/a

### Reanimated version

3.0.0

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by andreialecu** [comment]
Same issue, this worked:

```ts
jest.mock('react-native-reanimated', () =>
  require('react-native-reanimated/mock'),
);
```

**Comment by bitcrumb** [comment]
@andreialecu I'm doing that as well for importing the mock (and this still works).

It is my understanding however, that some extra setup needs to happen as well. That is why you need to call `setUpTests` as indicated in the docs.

Calling this method used to work in version 2, however since version 3 the path can't be resolved. That's what this issue is about.

**Comment by sanduluca** [comment]
Din anyone have a solution ?

When setup like in docs 
```tsx
require('react-native-reanimated').setUpTests();

// ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as Animated from './Animated';
//                                                                                      ^^^^^^
//  SyntaxError: Cannot use import statement outside a module
```

```tsx
jest.mock('react-native-reanimated', () =>
  require('react-native-reanimated/mock'),
);

// import { SensorType } from './commonTypes';
//    ^^^^^^
//    SyntaxError: Cannot use import statement outside a module
```


```tsx
require('react-native-reanimated/src/reanimated2/jestUtils').setUpTests();

//    import { isJest } from './PlatformChecker';
//    ^^^^^^
//    SyntaxError: Cannot use import statement outside a module
```

```tsx
import { setUpTests } from 'react-native-reanimated';
setUpTests();

// ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as Animated from './Animated';
//                                                                                      ^^^^^^
//    SyntaxError: Cannot use import statement outside a module
//    > 1 | import { setUpTests } from 'react-native-reanimated';
```

**Comment by fkapsahili** [comment]
I added it into the `transformIgnorePatterns` in `jest.config.js`. Subsequently, I initialized the library in `jest.setup.ts` as follows:
```js
require("react-native-reanimated").setUpTests();
```

But my tests were still not erroring, so I additionally had to add the mock in my jest setup as well and now my issues seems to be resolved:
```js
jest.mock("react-native-reanimated", () =>
  require("react-native-reanimated/mock")
);
```

**Comment by khethelogp** [comment]
Still facing this issue 😢

**Comment by eduardoborges** [comment]
Someone resolved this?

**Comment by diegoMontesinos** [comment]
@khethelogp @eduardoborges 
I solved it by adding `react-native-reanimated` to the `transformIgnorePatterns`:

```js
module.exports = {
  preset: 'react-native',
  transformIgnorePatterns: [
    'node_modules/(?!(@react-native|react-native|react-native-reanimated)/)',
  ],
  setupFiles: ['./node_modules/react-native-gesture-handler/jestSetup.js'],
};
```

And create a file `__mocks__/react-native-reanimated.js` with:

```js
const Reanimated = require('react-native-reanimated/src/mock');
const Animated = Reanimated.default;

module.exports = {
  ...Reanimated,

  default: {
    ...Animated,
  },
};
```

**Comment by ava-m-c** [comment]
Current documentation of Reanimated mentions

`require('react-native-reanimated').setUpTests();`

which seems to work.

https://docs.swmansion.com/react-native-reanimated/docs/guides/testing/

**Comment by MichalSmaliraITM** [comment]
Still occurs in 3.15.0
