### ISSUE TITLE
Shared element transition is flickering using this config (bugs)

### ISSUE THREAD

**Issue by hamdij0maa** [software-mansion/react-native-reanimated#4173]
### Description

on IOS , the shared element transition is flickering using this config : 

Image component using Expo-image : 
const AnimatedExpoImage = Animated.createAnimatedComponent(Image);

type AnimatedImageViewProps = Animated.AnimateProps<ImageProps>;

type Props = BoxProps<Theme> & AnimatedImageViewProps;

const AnimatedImage = createRestyleComponent<Props, Theme>(
  [spacing, backgroundColor, spacing, border, shadow],
  AnimatedExpoImage,
);

export default AnimatedImage;

transition Config : 
export const sharedLayoutTransition = SharedTransition.custom(values => {
  'worklet';

  return {
    width: withSpring(values.targetWidth, springConfig),
    height: withSpring(values.targetHeight, springConfig),
    originX: withSpring(values.targetOriginX, springConfig),
    originY: withSpring(values.targetOriginY, springConfig),
  };
});

video : 
https://drive.google.com/file/d/1zRVHneqcD1ooq4HBbA8mJ000daQe9Tl8/view?usp=share_link

### Steps to reproduce

Image component using Expo-image : 
const AnimatedImage = Animated.createAnimatedComponent(Image);
export default AnimatedImage;

/
....
./

transition Config : 
export const sharedLayoutTransition = SharedTransition.custom(values => {
  'worklet';

  return {
    width: withSpring(values.targetWidth, springConfig),
    height: withSpring(values.targetHeight, springConfig),
    originX: withSpring(values.targetOriginX, springConfig),
    originY: withSpring(values.targetOriginY, springConfig),
  };
});

### Snack or a link to a repository

https://drive.google.com/file/d/1zRVHneqcD1ooq4HBbA8mJ000daQe9Tl8/view?usp=share_link

### Reanimated version

3.0.1

### React Native version

0.71.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by hamdij0maa** [comment]
@tomekzaw do you have any idea if am missing something please?

**Comment by szydlovsky** [comment]
Hey @hamdij0maa the link to code doesn't work anymore. Would you be able to try reproducing the issue? Shared Element Transitions have gone a long way since March 2023 and I believe it could be fixed by now 😄

**Comment by hamdij0maa** [comment]
-> yes 🙏
