### ISSUE TITLE
`withTiming` animations are not working during first render 

### ISSUE THREAD

**Issue by marcocaldera** [software-mansion/react-native-reanimated#4176]
### Description

Here is the first report:
https://github.com/software-mansion/react-native-reanimated/discussions/4050

During the first render, the animation is not executed as it should and the app directly render the final value.

Tested on multiple reanimated versions.

### Steps to reproduce

```typescript
import { StatusBar } from "expo-status-bar";
import React from "react";
import { Button, StyleSheet, Text, View } from "react-native";
import Animated, {
  useAnimatedStyle,
  withTiming,
  useSharedValue,
} from "react-native-reanimated";

export default function App() {
  const opacity = useSharedValue(1);

  const loadingOpacityStyle = useAnimatedStyle(() => {
    // opacity.value = withTiming(0, {
    //   duration: 5000,
    // });

    return {
      opacity: opacity.value,
    };
  });

  const changeOpacity = () => {
    opacity.value = withTiming(0, {
      duration: 5000,
    });
  };

  return (
    <Animated.View style={[styles.container, loadingOpacityStyle]}>
      <Text>Open up App.js to start working on your app!</Text>
      <Button title="ciao" onPress={changeOpacity} />
      <StatusBar style="auto" />
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

By using the commented lines I would expect to see a slow fading out of the opacity of the view. Everything works as expected by pressing the button.

I run more tests and saw that up until `3.0.0-rc.7` it was working. Could it be that this issue is related to this PR: https://github.com/software-mansion/react-native-reanimated/pull/3722

### Snack or a link to a repository

https://snack.expo.dev/@caldux/rn-styles?platform=ios

### Reanimated version

3.0.1

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey, thanks for your report, but we currently don't support this syntax. I wrote an explanation and solution in the discussion thread here - https://github.com/software-mansion/react-native-reanimated/discussions/4050#discussioncomment-5268142
