### ISSUE TITLE
Typescript. Unsafe assignment of an `any` value. Animated.EasingFunction with any type.

### ISSUE THREAD

**Issue by NikitaDudin** [software-mansion/react-native-reanimated#4178]
### Description

<img width="560" alt="image" src="https://user-images.githubusercontent.com/25579397/223400324-75233ddb-f76a-4011-84d9-def1a82ad149.png">

All functions of the Easing object haves type any instead EasingFunction.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/25579397/223401940-72387158-d6f5-4b10-bdd5-9e75e203ca5c.png">

Possible solution: 
Replace `Animated.EasingFunction` with `EasingFunction` for each field in the [EasingStatic](https://github.com/software-mansion/react-native-reanimated/blob/a38678d6ada894f4c42461de806a90d2a94a688a/react-native-reanimated.d.ts#L834-L861) object.

Temp solution: [patch-package](https://github.com/ds300/patch-package#readme) patch file. 
[react-native-reanimated+3.0.1.patch](https://github.com/software-mansion/react-native-reanimated/files/10908598/react-native-reanimated%2B3.0.1.patch)

`./lib/types` dir doesn't exist in the node modules:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/25579397/223427751-227e8454-05ed-495f-b75b-fa6343a6c9f1.png">
 

### Steps to reproduce

Typescript sample code: 

```ts
 withTiming(1, { easing: Easing.linear });
 ```

### Reanimated version

3.0.1

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Thanks for reporting this issue. Fixed with #4180, will be released in 3.0.2.
