### ISSUE TITLE
ERROR ReanimatedError: Cannot read property 'value' of undefined, js engine: reanimated

### ISSUE THREAD

**Issue by ThinkerLu** [software-mansion/react-native-reanimated#4186]
### Description

A useSharedValue name that starts with current will trigger ERROR ReanimatedError: Cannot read property 'value' of undefined, js engine: reanimated

### Steps to reproduce

  const сurrentscroll = useSharedValue(0);

  const translateY = useDerivedValue(
    () => сurrentscroll.value,
    [сurrentscroll],
  );

### Snack or a link to a repository

https://snack.expo.dev/@thinkerlu/reanimatederror

### Reanimated version

3.0.0

### React Native version

0.71.1

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by TomCorvus** [comment]
it's fixed since 3.0.1
https://github.com/software-mansion/react-native-reanimated/pull/4159

**Comment by javier-sauma-rocketlab** [comment]
i have this problem with 3.0.2

**Comment by JameDodgers** [comment]
@ThinkerLu I was experiencing the same error, but then I realized that the fragment of code I copied from an example contained the character `U+04141` "с" which is different from the character `U+0063` "c" that we commonly use. It's the same character in the code snippet you posted above
