### ISSUE TITLE
issue v3: Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by chubo274** [software-mansion/react-native-reanimated#4198]
### Description

i can build success after install, add babel, clean cache.
but i got [native] Cannot read properties of undefined (reading 'apply') on Xcode when i add this code in file: 
import Animated, { Extrapolation, interpolate, useAnimatedScrollHandler, useAnimatedStyle, useSharedValue } from 'react-native-reanimated'

const scrollY = useSharedValue(0);
    const scrollHandler = useAnimatedScrollHandler({
        onScroll: (e) => {
            scrollY.value = e.contentOffset.y
        }
    })
    const positionFilter = useAnimatedStyle(() => {
        const position = interpolate(
            scrollY.value,
            [0, 1], [2, 1],
            { extrapolateRight: Extrapolation.CLAMP }
        )

        return { top: position }
    })
    
    how can i show this?

### Steps to reproduce

1. install, add in babel, clean cache
2. using import Animated, { Extrapolation, interpolate, useAnimatedScrollHandler, useAnimatedStyle, useSharedValue } from 'react-native-reanimated'
3. got error Cannot read properties of undefined (reading 'apply')

### Snack or a link to a repository

nan

### Reanimated version

3.0.2

### React Native version

0.70.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
You need to use newer version of Reanimated, this issue has been already solved.
