### ISSUE TITLE
[Android] scrollTo with animated=true does not work

### ISSUE THREAD

**Issue by peterlazar1993** [software-mansion/react-native-reanimated#4200]
### Description

I am trying to implement a scroll behaviour where the scroll snaps to a position based on the offset at end of the scroll.

The behaviour works as expected on iOS.
On Android, the scrollTo method does not work when `animated: true` is set.

Strangely, on Android, the behaviour works as expected when the scrollTo method is called from within a gesture handler, as can be seen in the video. On panning the wheel and stopping between items, the scrollview snaps to an offset with animation.

By the way, the code for the reproduction is based on [this blogpost from swmansion](https://blog.swmansion.com/reanimated-2-events-part-ii-scroll-events-a319fd9f1e62)

There seems to be similar issue here #3064

### Android

https://user-images.githubusercontent.com/4848554/224363928-197fcd9a-053d-4abe-b704-e3daece1c009.mp4

### iOS

https://user-images.githubusercontent.com/4848554/224363963-44d06a28-4b4b-44c7-9427-c4d0a20276a1.mp4

### Steps to reproduce

1. Clone repo
2. Try scrolling the artwork
3. You will notice on iOS, the scroll position snaps if scroll is stopped mid swipe
4. On Android, the scroll stops where the swipe ended

### Snack or a link to a repository

https://github.com/peterlazar1993/reanimated-bug

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

None

### Device model

Realme X7 Max - Android 12

### Acknowledgements

Yes

**Comment by codiku-dev** [comment]
I confirm this issue, on Expo as well.

**Comment by peterlazar1993** [comment]
@codiku-dev this has been fixed in 3.1.0

https://github.com/software-mansion/react-native-reanimated/releases/tag/3.1.0
