### ISSUE TITLE
ReanimatedError: Cannot read property '__remoteFunction' of undefined, js engine: reanimated

### ISSUE THREAD

**Issue by 11AA8R4** [software-mansion/react-native-reanimated#4201]
### Description

when I release the touch a GestureDetector with a code like the bellow the following error occours:
ReanimatedError: Cannot read property '__remoteFunction' of undefined, js engine: reanimated

appearently located at threads.ts(129:10)

```
const panGesture = Gesture.Pan()
.onFinalize(event=>{
    runOnJS(Keyboard.dismiss)()
})
```

### Steps to reproduce

create a GestureDetector container
create a gestureEvent for it like bellow:
```
const panGesture = Gesture.Pan()
.onFinalize(event=>{
    runOnJS(Keyboard.dismiss)()
})
```

### Snack or a link to a repository

noLinkProvided

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

doogee s88 plus

### Acknowledgements

Yes

**Comment by nornewman** [comment]
I have the same issue

**Comment by YaoHuiJi** [comment]
here is the xcode log when crash occurs, hope it's helpful:

```
libc++abi: terminating with uncaught exception of type facebook::jsi::JSError: Cannot read property '__remoteFunction' of undefined

TypeError: Cannot read property '__remoteFunction' of undefined
    at runOnJS (JavaScript:1:83)
    at handleOnEnd (JavaScript:1:1308)
    at anonymous (JavaScript:1:215)
    at apply (native)
    at runWorklet (JavaScript:1:207)
    at anonymous (JavaScript:1:886)
    at handleAndFlushImmediates (JavaScript:1:143)
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib
terminating with uncaught exception of type facebook::jsi::JSError: Cannot read property '__remoteFunction' of undefined

TypeError: Cannot read property '__remoteFunction' of undefined
    at runOnJS (JavaScript:1:83)
    at handleOnEnd (JavaScript:1:1308)
    at anonymous (JavaScript:1:215)
    at apply (native)
    at runWorklet (JavaScript:1:207)
    at anonymous (JavaScript:1:886)
    at handleAndFlushImmediates (JavaScript:1:143)
```

**Comment by levipro** [comment]
Define an arrow function outside of any worklet callback and pass that instead:

```
const dismissKeyboard = () => {
  Keyboard.dismiss();
};
```

**Comment by YaoHuiJi** [comment]
@levipro thank you! it works!

**Comment by ansh** [comment]
Likely the function being passed into `runOnJs()` has not been defined. Define it before you pass it into `runOnJs()`
