### ISSUE TITLE
Error: Exception in HostFunction: java.lang.NoSuchMethodError: no non-static method

### ISSUE THREAD

**Issue by muzhaqi16** [software-mansion/react-native-reanimated#4202]
### Description

Error: Exception in HostFunction: java.lang.NoSuchMethodError: no non-static method "Lcom/swmansion/reanimated/NativeProxy;.registerEventHandler(Lcom/swmansion/reanimated/nativeProxy/EventHandler;)V", js engine: hermes
 LOG  Running "AwesomeProject" with {"rootTag":11}
 ERROR  Invariant Violation: "AwesomeProject" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### Steps to reproduce

1. Create a new project using the latest react-native `npx react-native@latest init AwesomeProject`
2. Add react-native-reanimated `yarn add react-native-gesture-handler`
3. Add the example code 
```
 <Animated.View
        style={[
          {width: 100, height: 80, backgroundColor: 'black', margin: 30},
          style,
        ]}
      />
```
4. Run the application

### Snack or a link to a repository

https://github.com/muzhaqi16/react-native-reanimated-bug

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy S22 Ultra

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey 👋 Thanks for your report and for providing repro! But if you don't mind I'll merge this issue with previous report [#4135](https://github.com/software-mansion/react-native-reanimated/issues/4135) to keep everything in one place.

**Comment by zhaozedong** [comment]
请问解决了吗？我也遇到相同问题了
