### ISSUE TITLE
[Shared Element Transition] Wrong position in case the previous screen is changed after the transition

### ISSUE THREAD

**Issue by yepMad** [software-mansion/react-native-reanimated#4203]
### Description

If the previous screen is changed after the transition when going back to it the element will be in the previous position to the modifications that occurred while the screen was not in focus

It happens on Android. I haven't tested it on iOS.

https://user-images.githubusercontent.com/22564368/224524537-f8304262-e400-4f28-933f-54e227afc25b.mp4

### Steps to reproduce

1. Run attached repository locally
2. Click on one of the colored cards
3. Go back to the previous screen using the lower red button

### Snack or a link to a repository

https://github.com/yepMad/react-native-reanimated-issues/tree/issues/4203

### Reanimated version

3.0.2

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy M12

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
Hey @yepMad , can confirm that SETs as of 3.12.1 have no such issues!
