### ISSUE TITLE
OnRender error

### ISSUE THREAD

**Issue by CFPanda** [software-mansion/react-native-reanimated#4204]
### Description

I used react-native-realtimate to make a rotation chart, but when I opened the react- native page, I reported an error。

OnRender error

reanimated::REAIOSErrorHandler::raiseSpec()
   REAIOSErrorHandler.mm:18
reanimated::ErrorHandler::raise()::'lambda'()::operator()()
decltype(static_cast<reanimated::ErrorHandler::raise()::'lambda'()&>(fp)()) std::__1::__invoke<reanimated::ErrorHandler::raise()::'lambda'()&>(reanimated::ErrorHandler::raise()::'lambda'()&&&)
void std::__1::__invoke_void_return_wrapper<void, true>::__call<reanimated::ErrorHandler::raise()::'lambda'()&>(reanimated::ErrorHandler::raise()::'lambda'()&&&)
std::__1::__function::__alloc_func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocator<reanimated::ErrorHandler::raise()::'lambda'()>, void ()>::operator()()
std::__1::__function::__func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocator<reanimated::ErrorHandler::raise()::'lambda'()>, void ()>::operator()()
std::__1::__function::__value_func<void ()>::operator()() const
std::__1::function<void ()>::operator()() const
reanimated::REAIOSScheduler::scheduleOnUI(std::__1::function<void ()>)
reanimated::ErrorHandler::raise()
reanimated::NativeReanimatedModule::onRender(double)
reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1::operator()(double) const
decltype(static_cast<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1&>(fp)(static_cast<double>(fp0))) std::__1::__invoke<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1&, double>(reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1&&&, double&&)
void std::__1::__invoke_void_return_wrapper<void, true>::__call<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1&, double>(reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1&&&, double&&)
std::__1::__function::__alloc_func<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1, std::__1::allocator<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1>, void (double)>::operator()(double&&)
std::__1::__function::__func<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1, std::__1::allocator<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptr<facebook::react::CallInvoker>, std::__1::shared_ptr<reanimated::Scheduler>, std::__1::shared_ptr<facebook::jsi::Runtime>, std::__1::shared_ptr<reanimated::ErrorHandler>, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptr<reanimated::LayoutAnimationsProxy>, reanimated::PlatformDepMethodsHolder)::$_1>, void (double)>::operator()(double&&)
std::__1::__function::__value_func<void (double)>::operator()(double&&) const
std::__1::function<void (double)>::operator()(double) const
invocation function for block in reanimated::createReanimatedModule(RCTBridge*, std::__1::shared_ptr<facebook::react::CallInvoker>)::$_2::operator()(std::__1::function<void (double)>, facebook::jsi::Runtime&) const
-[REANodesManager onAnimationFrame:]
-[DYDisplayLinkInterposer forwardDisplayLinkCallback:]
<redacted>
<redacted>
<redacted>
<redacted>
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
<redacted>

### Steps to reproduce

无

### Snack or a link to a repository

无

### Reanimated version

2.10.0

### React Native version

0.64.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

所有机型

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?
