### ISSUE TITLE
[3.0] Using a ref from useImperativeHandle breaks react setState calls with read-only errors

### ISSUE THREAD

**Issue by mgcrea** [software-mansion/react-native-reanimated#4213]
### Description

I needed to use a ref from a children component (exposed via `forwardRef` + `useImperativeHandle`). As soon as I read the ref in the parent component (like in a `useAnimatedReaction()` prepare call), it somehow freeze external react state (in that case react-navigation) And breaks inside react on a `setState` call when you ty to navigate away. The bug occurs whatever the ref value is (can be `null`).

Did set up a basic repro case that you can find here: [mgcrea/react-native-reanimated-sandbox](https://github.com/mgcrea/react-native-reanimated-sandbox/blob/master/src/screens/ReadOnlyRefScreen.tsx)

A possible workaround could have been to use a shared value instead of a ref, but unfortunately it breaks other things (shared values aren't updated anymore, still digging into it), while it 100% works with a classic ref until react-navigation needs a`setState`.

```tsx
<ComponentWithRef ref={(value) => { sharedRef.value = value; }} />
```

--- 

Video:

https://user-images.githubusercontent.com/108273/224832474-f198dff5-cef1-430e-8c61-8a5ce49ba246.mp4

--- 

Trace:

<img width="337" alt="Screenshot 2023-03-13 at 22 12 02" src="https://user-images.githubusercontent.com/108273/224833387-a6763288-92e8-4c96-8134-a4566229d9bc.png">

### Steps to reproduce

```tsx
import { forwardRef, FunctionComponent, PropsWithChildren, useImperativeHandle, useRef } from "react";
import { SafeAreaView } from "react-native";
import { useAnimatedReaction } from "react-native-reanimated";

export const ReadOnlyRefScreen: FunctionComponent = () => {
  const ref = useRef<Handle>(null);

  useAnimatedReaction(
    () => ref.current,
    (next, prev) => {
      // console.log([prev, next]);
    }
  );

  return (
    <SafeAreaView style={{ flex: 1 }}>
      <ComponentWithRef ref={ref} />
    </SafeAreaView>
  );
};

type Handle = {
  foo: string;
};

const ComponentWithRef = forwardRef<Handle, PropsWithChildren>(function ComponentWithRef({ children }, ref) {
  useImperativeHandle(
    ref,
    () => {
      return {
        foo: "bar",
      };
    },
    []
  );
  return <>{children}</>;
});
```

--- 

Video:

https://user-images.githubusercontent.com/108273/224832474-f198dff5-cef1-430e-8c61-8a5ce49ba246.mp4

--- 

Trace:

<img width="337" alt="Screenshot 2023-03-13 at 22 12 02" src="https://user-images.githubusercontent.com/108273/224833387-a6763288-92e8-4c96-8134-a4566229d9bc.png">

### Snack or a link to a repository

https://github.com/mgcrea/react-native-reanimated-sandbox/blob/master/src/screens/ReadOnlyRefScreen.tsx

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! @mgcrea
Unfortunately you can't use useAnimatedReaction the way you want ([documentation](https://docs.swmansion.com/react-native-reanimated/docs/advanced/useAnimatedReaction/))
>useAnimatedReaction allows you to respond to changes in a [shared value](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/glossary#shared-value). It's especially useful when comparing values previously stored in the shared value with the current one.
