### ISSUE TITLE
[3.0.x][CRASH] When using Animated.ScrollView with scrollEventThrottle and onScroll, and animating inside it

### ISSUE THREAD

**Issue by yepMad** [software-mansion/react-native-reanimated#4221]
### Description

I created a demo application that illustrates my real code, going straight to the point of the problem. As far as I could identify, when you have an Animated.ScrollView that has the properties "scrollEventThrottle" and "onScroll" (useAnimatedScrollHandler) the application crashes when there is animation in the last elements of the list.

https://user-images.githubusercontent.com/22564368/225136699-2cbbf4db-0c89-40a4-8eb7-21080801660a.mp4

Notes:

- **The same code works fine in version 2.14.4**
- It happens on iOS. I haven't tested it on Android.
- In the example "useAnimatedScrollHandler" is without listeners, but even with listeners the problem occurs.

### Steps to reproduce

1. Run attached repository locally
2. Click to expand the last but one element
3. Click again to back to the default state
4. Application crashes

### Snack or a link to a repository

https://github.com/yepMad/react-native-reanimated-issues/tree/issue/reanimated-crash

### Reanimated version

3.0.2

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone SE 3rd Gen

### Acknowledgements

Yes

**Comment by vozaldi** [comment]
#4306 similar issue with `<Animated.ScrollView />` happening on Android

**Comment by LuisRego** [comment]
I'm having the same crash when animating a `height` of an element. If we handle the gesture by using `Animated.Event()` from `react-native` everything works fine. The crash is only happening on IOS.

**Comment by FutureOfRussia** [comment]
Same crash on version 3.1.0

**Comment by Latropos** [comment]
@yepMad Hi! I am unable to reproduce this bug on IOS simulator (I've even used iPhone SE 3rd Gen to match the one in the issue), on latest react-native. Everything works fine - folds and unfolds as expected.
