### ISSUE TITLE
Memory leak linked to useAnimatedStyles

### ISSUE THREAD

**Issue by freeboub** [software-mansion/react-native-reanimated#4236]
### Description

I have identify a memory leak on 2.14.4 and 3.0.0-rc.10 as well but it is fixed on 3.0.2.
The use case is linked to hidden (out of screen for exemple) views (useAnimlatedStyle to be exact).

Reproduced on android (not tested on ios)

I attached a sample code to the ticket. It is looping and display very rapidly animated Views outside of the screen.

Sample code:
```
// Section is an animated View
<View style={{top: 10000}}>
         <Section key={it} sharedVal={sharedVal} />
</View>
```

Additional tests done:
- try to use jsc instead of hermes (same issue)
- try to call gc() on UI Thread (same issue)

Screenshot of memory profiler: 
![Screenshot 2023-03-17 at 09 03 47 2](https://user-images.githubusercontent.com/62574056/225847619-ccf39c78-d537-44c4-a458-a896d1a0fb31.jpeg)

As it is fixed on 3.0.2 Not really sure this is relevant, but I didn't find the information if 2.XX branch will be maintained.

Thank you.

### Steps to reproduce

- while (true)
   - Add an animated view out side of the screen
    - umount it.
- endWhile

### Snack or a link to a repository

https://github.com/freeboub/reanimatedSample

### Reanimated version

2.14.4

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Device model

All (all android TV I used (10 types) and emulator )

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
In Reanimated v3 we rewrote the whole logic related to Shared Values and Layout Animation to eliminate memory leaks. We recommend using the v3 version.

**Comment by freeboub** [comment]
@piaskowyk ok, not problem. I spend at least 1 week to identify precisely the issue, so I report it 😁 if no maintenance on 2.xx, let's close this ticket ?
