### ISSUE TITLE
Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]

### ISSUE THREAD

**Issue by souna23** [software-mansion/react-native-reanimated#4241]
### Description

> Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
C/C++: ninja: Entering directory `/Users/m/Documents/****/***/***/node_modules/react-native-reanimated/android/.cxx/Debug/1p4y3f41/arm64-v8a'
C/C++: ld: error: undefined symbol: __cxa_begin_catch
C/C++: ld: error: undefined symbol: std::terminate()
C/C++: ld: error: undefined symbol: std::__ndk1::__shared_weak_count::__release_weak()
C/C++: ld: error: undefined symbol: operator delete(void*, std::align_val_t)
C/C++: ld: error: undefined symbol: operator delete(void*)
C/C++: ld: error: undefined symbol: __cxa_allocate_exception
C/C++: ld: error: undefined symbol: __cxa_throw
C/C++: ld: error: undefined symbol: std::exception::~exception()
C/C++: ld: error: undefined symbol: vtable for std::exception
C/C++: ld: error: undefined symbol: typeinfo for std::length_error
C/C++: ld: error: undefined symbol: std::length_error::~length_error()
C/C++: ld: error: undefined symbol: __cxa_free_exception
C/C++: ld: error: undefined symbol: operator new(unsigned long, std::align_val_t)
C/C++: ld: error: undefined symbol: operator new(unsigned long)
C/C++: ld: error: undefined symbol: std::logic_error::logic_error(char const*)
C/C++: ld: error: undefined symbol: vtable for std::length_error
C/C++: ld: error: undefined symbol: std::__ndk1::__shared_weak_count::lock()
C/C++: ld: error: undefined symbol: std::__ndk1::__next_prime(unsigned long)
C/C++: ld: error: undefined symbol: vtable for __cxxabiv1::__si_class_type_info
C/C++: ld: error: undefined symbol: typeinfo for std::exception
C/C++: ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce

upgrade to version 3.x

### Snack or a link to a repository

dont'have

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by VienLeVan** [comment]
I had the same issue for android when upgrading from V2 to V3.

**Comment by Limoer96** [comment]
same!

**Comment by croaker** [comment]
I'm not entirely sure why, but on a Mac M1 machine, `softwareupdate --install-rosetta` solved the issue for us.

**Comment by Akeuuh** [comment]
Hello @piaskowyk 

I'd like to reopen this issue because I have exactly the same error.

I could provide a repo to replicate the issue, but you can do it alone by doing

```
npx react-native init test
yarn add react-native-reanimated

cd android

./gradlew installDebug
```

### Some context about my project:
- react-native: 0.71.6
- react-native-reanimated: 3.0.2

### How I ended here:
The project was working well yesterday, building nicely on Android.
I have an issue in production as the app wasn't opening on Android 8. To work on that issue, I created an Android8 emulator and apply [this patch ](https://gist.github.com/balmasich/e13ae0b12d3b4ab166a6143204b87dae).

Since then, I'm unable to build on any version of Android, despite I rolled back the change, uninstall and reinstall Android studio, reinstall my all project.

It seems that the issue is larger than my project since I cannot build on a brand new project.

Thank for your help if you can, I'm available for any question.

**Comment by efstathiosntonas** [comment]
same here with the same error like @Akeuuh above. Out of the sudden, without touching anything it started failing 🤔

**Comment by efstathiosntonas** [comment]
> same here with the same error like @Akeuuh above. Out of the sudden, without touching anything it started failing 🤔
> 
> using `react-native-reanimated@3.3.0` on `react-native@0.71.10`
> 
> on a M1 machine using this on `build.gradle`:
> 
> ```
>  if (System.properties['os.arch'] == "aarch64") {
>             ndkVersion = "24.0.8215888"
>         } else {
>             ndkVersion = "23.1.7779620"
>         }
> ```

I removed NDK from Android Studio -> Tools -> SDK Manager -> SDK Tools, reinstalled them and then the error is gone. Really weird

**Comment by Akeuuh** [comment]
> > same here with the same error like @Akeuuh above. Out of the sudden, without touching anything it started failing 🤔
> > using `react-native-reanimated@3.3.0` on `react-native@0.71.10`
> > on a M1 machine using this on `build.gradle`:
> > ```
> >  if (System.properties['os.arch'] == "aarch64") {
> >             ndkVersion = "24.0.8215888"
> >         } else {
> >             ndkVersion = "23.1.7779620"
> >         }
> > ```
> 
> I removed both NDK versions from Android Studio -> Tools -> SDK Manager -> SDK Tools, reinstalled them and then the error is gone. Really weird. Thanks @kapir

Yes I did the same and forgot to share sorry

**Comment by blwinters** [comment]
Yep, who knows why, but uninstalling and reinstalling my version of the NDK, `23.1.7779620`, fixed the error.

**Comment by vishalpawar048** [comment]
closing the metro terminal and running `cd android && ./gradlew clean` worked for me.

**Comment by gavrilikhin-d** [comment]
> closing the metro terminal and running `cd android && ./gradlew clean` worked for me.

Didn't help me

**Comment by Taraslysak** [comment]
For some magical reason, switching between `react-native-reanimated` versions (3.5.3 and 3.5.4 via `yarn upgrade`) solves the issue for me. But these crashes happen pretty often (twice a week)

**Comment by kannapoix** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/4679 may helps you.

**Comment by jagataess** [comment]
@efstathiosntonas  Thanks man! Your solution finally fixed this issue for me also it worked.

**Comment by Digital-Human-BK** [comment]
> @efstathiosntonas Thanks man! Your solution finally fixed this issue for me also it worked.

Can you show me an example of the full build.gradle file after you added the conditional statement? I'm not sure where and how to add the suggested snippet.

` if (System.properties['os.arch'] == "aarch64") {
            ndkVersion = "24.0.8215888"
        } else {
            ndkVersion = "23.1.7779620"
        }`

**Comment by efstathiosntonas** [comment]
@Digital-Human-BK this is my full `android/build.gradle`:

```gradle
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        // keep both vars, some modules do not follow common standard
        kotlin_version = "1.8.22"
        kotlinVersion = "1.8.22"
        if (System.properties['os.arch'] == "aarch64") {
            ndkVersion = "24.0.8215888"
        } else {
            ndkVersion = "23.1.7779620"
        }
    }
    repositories {
        google()
        mavenCentral()
    }

    configurations.all {
        resolutionStrategy {
            force "androidx.browser:browser:1.5.0"
            force "com.squareup.okhttp3:okhttp:4.11.0"
            force "com.squareup.okhttp3:okhttp-urlconnection:4.11.0"
            force "com.squareup.okio:okio:3.3.0"
        }
    }

    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.15'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:7.+"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
    }
}
```

**Comment by jagataess** [comment]
> > @efstathiosntonas Thanks man! Your solution finally fixed this issue for me also it worked.
> 
> Can you show me an example of the full build.gradle file after you added the conditional statement? I'm not sure where and how to add the suggested snippet.
> 
> ` if (System.properties['os.arch'] == "aarch64") { ndkVersion = "24.0.8215888" } else { ndkVersion = "23.1.7779620" }`

I just deleted and reinstalled the NDK module from Android Studio and it worked.

**Comment by coder-minchu** [comment]
@efstathiosntonas **### Thanks a lot** now i am able to build.

**Comment by AriqAhmer** [comment]
**@efstathiosntonas** **Thanks a LOT for this!**. Finally it built!

**Comment by ClenildoCardoso** [comment]
Você pode resolver esse problema da seguinte forma: 

Exclua todas as pastas NDKs em:
C:\Users\N\AppData\Local\Android\Sdk\ndk\ 

Depois vá no Android Studio e reinstale o NDK

![Captura de Tela (272)](https://github.com/software-mansion/react-native-reanimated/assets/70482417/9db6b8e0-9a15-4817-b9db-30b1556f1a72)

**Comment by efstathiosntonas** [comment]
@ClenildoCardoso english please, use google translate, why we should do it for you?

**Comment by analuizaalvesm** [comment]
Facing the same issue for react-native@0.73.6 and react-native-reanimated@3.8.0. Reinstalling NDK did not work for me.

**Comment by kalash-copods** [comment]
> Facing the same issue for react-native@0.73.6 and react-native-reanimated@3.8.0. Reinstalling NDK did not work for me.

Same I am using react-native@0.73.6 and react-native-reanimated@3.8.1, above steps didn't worked for me

**Comment by analuizaalvesm** [comment]
> > Facing the same issue for react-native@0.73.6 and react-native-reanimated@3.8.0. Reinstalling NDK did not work for me.
> 
> Same I am using react-native@0.73.6 and react-native-reanimated@3.8.1, above steps didn't worked for me

Unfortunaley, for now, I had to stop using the library and its dependents. I found a way to build and run the app on my personal computer, but my other colleagues were facing the same issues I had before for building. Also, I was unable to generate APKs and AABs, so I will just wait for a definitive fix

**Comment by ClenildoCardoso** [comment]
@efstathiosntonas eu respondo em qual idioma eu quiser, se quiser traduzir bem, se não fod#-se.

**Comment by asKaera** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/4971#issuecomment-1852734095  
my problem was a long project folder name on c:\

**Comment by c-info** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/6411#issuecomment-2337830549

try to read this comment once may resolve the issue.

**Comment by habibrayhan007** [comment]
I'm facing the same issue.

Execution failed for task ':react-native-reanimated:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\FAQ\fixxt-planability-mobile-app\Code\PlanabilityApp\node_modules\react-native-reanimated\android\.cxx\Debug\6h4r4p5l\arm64-v8a'   
  [0/2] Re-checking globbed directories...
  ninja: build stopped: .

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\FAQ-User-17\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\FAQ\\fixxt-planability-mobile-app\\Code\\PlanabilityApp\\node_modules\\react-native-reanimated\\android\\.cxx\\Debug\\6h4r4p5l\\arm64-v8a" ^
        reanimated ^
        worklets
    from D:\FAQ\fixxt-planability-mobile-app\Code\PlanabilityApp\node_modules\react-native-reanimated\android
  ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/D_/FAQ/fixxt-planability-mobile-app/Code/PlanabilityApp/node_modules/react-native-reanimated): No such file or directory
  
**React Native version**
0.74.2

**Platforms**
Android

**Reanimated Version**
^3.9.0-rc.1

**build.gradle file:** 
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"
    }
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.react:react-native:0.74.2'
        }
    }
    
    **![Screenshot 2024-10-21 085721](https://github.com/user-attachments/assets/64185c10-0825-4fdf-9564-bc5881675eab)**

**Comment by ng-cen** [comment]
> For me on an intel device:
> 
> Reinstalling ndk;23.1.7779620 fixes it for some time, until i need to do it again

i struggled because this error for a whole day long.... i wished i'd seen ur comment earlier.
`remove & re-install ndk 23.1.7779620` works good for me. thank you very much
