### ISSUE TITLE
3.0.2 react_native_node_modules_dir can't support custom package for nodeModule

### ISSUE THREAD

**Issue by urtheone** [software-mansion/react-native-reanimated#4247]
### Description

In my project, we put the iOS code in the root dir, and put react native code in the root/RN dir, the 3.0.2 can't support this.
i have find the error place:
In **reanimated_utils.rb** file line 20 :

**react_native_node_modules_dir = File.join(File.dirname(`cd "#{Pod::Config.instance.installation_root.to_s}" && node --print "require.resolve('react-native/package.json')"`), '..')**

if i change it to 

 _**react_native_node_modules_dir = File.join(File.dirname(\`cd "#{Pod::Config.instance.installation_root.to_s}/RN" && node --print "require.resolve('react-native/package.json')"\\`), '..')**_

i can build my project success.
I hope in new version, it can be fixed.

### Steps to reproduce

npm install
npm start
run project

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.0.2

### React Native version

0.70.7

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Actually you can force Reanimated to search react native in different location. You can set `REACT_NATIVE_NODE_MODULES_DIR` env - https://github.com/software-mansion/react-native-reanimated/blob/main/scripts/reanimated_utils.rb#L25
