### ISSUE TITLE
3.0.2 Android Cannot read property 'stateNode' of undefined

### ISSUE THREAD

**Issue by fine0813** [software-mansion/react-native-reanimated#4256]
### Description

if an animated component has a ref provided by useAnimatedRef hook, it will produce this undefined error, even though fabric is enabled.

### Steps to reproduce

1. create react-native app by react-native-cli with latest stable version
2. enable new arch 
3. create an animate component in app.tsx and then give it a ref provide by useAnimatedRef hook

### Snack or a link to a repository

https://github.com/fine0813/reanimated-crash

### Reanimated version

3.0.2

### React Native version

0.71.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by fine0813** [comment]
![image](https://user-images.githubusercontent.com/109655399/226792112-f986af6f-aa7e-4524-be7c-65ef06c496dc.png)

**Comment by fgagneten** [comment]
I'm getting the same issue when I sue gorhom bottom sheet lib

**Comment by pjc0247** [comment]
i think this one is related with https://github.com/software-mansion/react-native-reanimated/issues/3951

i guess reanimated 3 has some black magic stuffs that breaks previous code.

**Comment by sehrish30** [comment]
same issue

**Comment by AlanSl** [comment]
I'm having the same issue using [react-native-reanimated-carousel](https://github.com/software-mansion/react-native-reanimated) on Fabric (RN 0.71, RNR 3.0.2), which crashes with the same error. I've looked at the PR on https://github.com/software-mansion/react-native-reanimated/pull/4445, and it looks like it might fix the issue for animated `FlatList`s so is probably worth releasing for that case, but, won't do anything for other animated components.

e.g. [`react-native-reanimated-carousel` renders one of these](https://github.com/dohooo/react-native-reanimated-carousel/blob/main/src/ScrollViewGesture.tsx) in a context provider, and causes this error in Reanimated on Fabric:

```tsx
  // ...
  const containerRef = useAnimatedRef<Animated.View>();
  // ...
  return (
    <PanGestureHandler
      {...panGestureHandlerProps}
      enabled={enabled}
      onGestureEvent={panGestureEventHandler}
    >
      <Animated.View
        ref={containerRef}
        testID={testID}
        style={style}
        onTouchStart={onTouchBegin}
        onTouchEnd={onTouchEnd}
      >
        {props.children}
      </Animated.View>
    </PanGestureHandler>
  )
```

I'll try creating a reproduction with animated views, RN 0.72.0-rc.3 and RNR 3.1.0.

**Comment by prince-sugarfit** [comment]
Is there any way I can use it with newArchitecture = true & fabric = false?

**Comment by Pulimet** [comment]
I had a similar issue, solution: https://github.com/software-mansion/react-native-reanimated/issues/7764
