### ISSUE TITLE
[Reanimated] Couldn't determine the version of the native part of Reanimated.

### ISSUE THREAD

**Issue by brandon2580** [software-mansion/react-native-reanimated#4257]
### Description

I am trying to upgrade my react-native version and in the process of doing so, I have ran into an issue with react-native-reanimated. Whenever my app builds, I get the following error in my metro console - 
`[Reanimated] Couldn't determine the version of the native part of Reanimated. Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must use the exact version which is bundled into Expo SDK`

I have tried:
- `expo doctor --fix-dependencies`
- Deleting podfile.lock, DerivedData folder, build folder, Pods folder, project_name.xcworkspace folder, node_modules, yarn.lock and reinstalling packages using yarn install
- `npx expo install react-native-reanimated`
- `yarn cache clean`
- `expo start --clear`

Here is my `metro.config` - 
```const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      }),
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg", "cjs"]
    }
  };
})();
```

Here is my `babel.config.js` - 
```
const config = {
  presets: ['module:metro-react-native-babel-preset','babel-preset-expo'],
  env: {
    production: {
      plugins: ['transform-remove-console'],
    },
    test: {
      plugins: [
        [
          'module:react-native-dotenv',
          {
            moduleName: '@env',
          },
        ],
      ],
    },
  },
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        safe: true,
        allowUndefined: true,
      },
    ],
    [
      '@babel/plugin-proposal-decorators',
      {
        legacy: true,
      },
    ],
    '@babel/plugin-proposal-optional-catch-binding',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-numeric-separator',
    [
      'module-resolver',
      {
        root: ['./'],
        extensions: [
          '.ios.js',
          '.android.js',
          '.js',
          '.jsx',
          '.ts',
          '.tsx',
          '.json',
        ],
        alias: {
          '^@app/(.+)': './app/\\1',
          '^@story/(.+)': './.storybook/\\1',
        },
        cwd: 'packagejson',
      },
    ],
    'react-native-reanimated/plugin',
  ],
};

module.exports = (api) => {
  api.cache(true);
  return config;
};
```

Any pointers in the right direction would be hugely helpful. I spent a whole day trying to resolve this with no luck unfortunately.

### Steps to reproduce

1. `yarn install`
2. Build app from XCode (14.2)
3. Once simulator loads & metro builds the app, I get the error

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

2.14.4

### React Native version

0.71.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

2020 M1 Macbook Pro

### Acknowledgements

Yes

**Comment by Wolf-111** [comment]
Hi @tomekzaw - Expo 48 requires Reanimated 2.14.4 specifically. Is there another approach I can take? Should I move to a different architecture?

**Comment by tomekzaw** [comment]
@Wolf-111, I'm afraid you cannot use Fabric with Expo managed workflow (SDK 48). So you can either use Expo bare workflow and use Reanimated 3 with Fabric enabled (the new renderer) or stick with Expo managed workflow and use Reanimated 2 on Paper (the old renderer).

**Comment by Wolf-111** [comment]
@tomekzaw Unfortunately even when I try to use Expo bare workflow (using expo prebuild), I still encounter the same error

**Comment by efstathiosntonas** [comment]
@Wolf-11199.9% it will break things entirely but have you tried using `package.json`  resolutions object eg:

```
  "resolutions": {
    "react-native-reanimated": "3.0.2",
  }
```

**Comment by ansh** [comment]
Make sure you clear cache too. `expo start -c`

**Comment by omarhamedx** [comment]
-change gesture handler version to npm i react-native-gesture-handler@2.2.0

**Comment by omarhamedx** [comment]
first step try this version its just worked for me on upgrading to 0.71.3 
- npm i react-native-reanimated@1.13.4 
- if it didnt work try npm i react-native-gesture-handler@2.2.0 
-

**Comment by Aakash359** [comment]
![Uploading 7ddcf101-2471-4672-9ef4-d316d472ca56.JPG…]()

Hello i currenlty i am using react native version react-native@0.73.0 and i have the reanimated version 3.5.4 it is working in android simulator but when i am trying to run on my android devices then it's giving this error i had tried many version of reanimated lib but none of them working getting same issues pls someone help me to resolve this issues
![7ddcf101-2471-4672-9ef4-d316d472ca56](https://github.com/software-mansion/react-native-reanimated/assets/54428958/46e5b68d-bc30-46db-b112-896829d62763)

**Comment by tomekzaw** [comment]
> i am using react native version react-native@0.73.0 and i have the reanimated version 3.5.4

Reanimated 3.5.4 does not support React Native 0.73.0, you need to upgrade Reanimated to 3.6.1.

**Comment by Aakash359** [comment]
> > i am using react native version react-native@0.73.0 and i have the reanimated version 3.5.4
> 
> Reanimated 3.5.4 does not support React Native 0.73.0, you need to upgrade Reanimated to 3.6.1.
> 
> Also, are you using JS bundle in dev mode with release build of the app?

ok let try and check

**Comment by sahiljaidka224** [comment]
Hey,

anyone found solution to this, I've tried everything
Expo SDK 50
RN 0.73.2
reanimated 3.6.0 have tried 3.6.1 as well

**Comment by abpbackup** [comment]
Same here as @sahiljaidka224. I started getting that warning after upgrading from 49 to 50.0.3. I already have reanimated 3.6.1

**Comment by Jerere** [comment]
We also received this warning after upgrading Expo to 50. Updated react-native-reanimated from 3.6.0 to 3.6.2 and the warning disappeared.

**Comment by codewithsabri** [comment]
> We also received this warning after upgrading Expo to 50. Updated react-native-reanimated from 3.6.0 to 3.6.2 and the warning disappeared.

I confirm, did the same and warning disappeared, thanks a lot upgrade to 3.6.2 guys :)

**Comment by pollyolly** [comment]
This is working for M1 IOS React reanimated 3.6.2
