### ISSUE TITLE
Cannot read property 'code' of undefined at valueUnpacker

### ISSUE THREAD

**Issue by devoren** [software-mansion/react-native-reanimated#4260]
### Description

After upgrading from 2.14.4 to 3.0.2 this problem appears:

![Screenshot_1679503385](https://user-images.githubusercontent.com/99968085/226977216-ee6825af-2102-40d1-8c49-b9d6172c00d0.png)

### Steps to reproduce

1. Update the library to the latest version in an existing application.
2. Run on Android

### Snack or a link to a repository

NA

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 4 API 31

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@devoren, did you run `yarn start --reset-cache` or `npm start -- --reset-cache` before submitting this issue?

**Comment by devoren** [comment]
yeah you were right, but now  another error (i use FrameProcessor in react-native-vision-camera):
`ReferenceError: Property '_setGlobalConsole' doesn't exist`

**Comment by tomekzaw** [comment]
@devoren, did you check issues in react-native-vision-camera repository?

* https://github.com/mrousavy/react-native-vision-camera/issues/1514
* https://github.com/mrousavy/react-native-vision-camera/issues/1510

As @mrousavy said in https://github.com/mrousavy/react-native-vision-camera/issues/1210#issuecomment-1457776475, Vision Camera v2 doesn't support Reanimated v3, so please upgrade to Vision Camera v3. Moreover, we will be working on integrating Vision Camera v3 with Reanimated v3 so stay tuned!

**Comment by devoren** [comment]
@tomekzaw Thanks a lot for the quick and clear answer!

**Comment by erksch** [comment]
I also get the error

```
Cannot read property 'code' of undefined at valueUnpacker 
```

- React Native: 0.71.3
- RN Babel Plugin: 0.73.7
- Reanimated: 3.0.2

I cleared my metro cache many times.

Are there any other ideas for a solution?

**Comment by julian-dotcom** [comment]
Resetting the cache worked for me! (`yarn start --reset-cache or npm start -- --reset-cache`)

**Comment by tomekzaw** [comment]
# Solution

Read the docs. [Installation](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started#installation)

## Step 1: Install the package

```
yarn add react-native-reanimated
npm install react-native-reanimated
npx expo install react-native-reanimated
```

## ⚠️ Step 2: Add Reanimated's babel plugin

`babel.config.js`

```diff
 module.exports = {
   presets: ['module:metro-react-native-babel-preset'],
+  plugins: ['react-native-reanimated/plugin'],
 };
```

## ⚠️ Step 3: Clear Metro bundler cache

```
yarn start --reset-cache
npm start -- --reset-cache
npx expo start -c
```
