### ISSUE TITLE
V3 makes AsyncStorage hang while remote debugging

### ISSUE THREAD

**Issue by msageryd** [software-mansion/react-native-reanimated#4267]
### Description

It took a long time triaging this weird bug. I ended up here at react-native-reanimated.

Everything works great with react-native-reanimated v2.5.
After upgrading to 3.0.2 (yes, I cleared the cache, cleaned build folders, pod install) my app works as usual, but as soon as I start remote debugging the app hangs while awaiting Async storage.

A similar problem seems to have existed in RN before. Could it be that Reanimated somehow clashes with Async storage? I know, this is weird and really far fetched, that's why I have tried several times to go between 2.5 and 3.0.2. The problem is 100% reproducible.

I found a lot of issues describing this. The following seems to be the solution which was merged a long time ago.
https://github.com/facebook/react-native/pull/18522

### Steps to reproduce

Working:
1. Install Reanimated 2.5 and @react-native-async-storage/async-storage
2. Have your app await something from AsyncStorage, `const myValue = await AsyncStorage.getItem('myKey');``
3. Run the app
4. Turn on remote debugging
5. This should work fine

Not working:
1. Install Reanimated 3.0.2 and @react-native-async-storage/async-storage
2. Have your app await something from AsyncStorage, `const myValue = await AsyncStorage.getItem('myKey');``
3. Run the app
4. Turn on remote debugging
5. AsyncStorage will not resolve the promise so your app will hang

### Snack or a link to a repository

I have no clue how to make a snack out of this scenario

### Reanimated version

3.0.2

### React Native version

0.68.2

### Platforms

iOS

### JavaScript runtime

V8

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by msageryd** [comment]
Could someone please chime in on this in spite of the missing minimal reproduction?
The reproduction includes `pod install`. How can I make a snack to demonstrate this behaviour?

**Comment by Lakston** [comment]
I have a similar setup (except using RN v0.70.5) and facing the same issue

**Comment by yatessss** [comment]
same issue
