### ISSUE TITLE
interpolate doesn't seem to work

### ISSUE THREAD

**Issue by lkoehl** [software-mansion/react-native-reanimated#427]
In my application I have an animated value ranging from 0 to 1 to track the progress of the animation. 

`this.expanded = new Value(0);`

Now I want to base multiple animations based on this value. There I am using the interpolate function and using it like in an example:

    this.opacity = interpolate(this.expanded, {
      inputRange: [0, 1],
      outputRange: [0, 1],
    });`

All this code is inside the constructor for my class based component. 
Now in my render method I set the style as following:

```
<AnimatedPopover
  style={{opacity: this.expanded}} // works
  style={{opacity: this.opacity}}  // doesn't work
</AnimatedPopover>
```

So this leads me to believe the interpolation isn't working correctly and something breaks it. Could this be a way or am I simply using the interpolation in a wrong manner? The touching is handled by another component inside the render method which triggers this code:

```
this.expanded = this.runCardExpand(
  new Clock(),
  cond(eq(this.expanded, 0), 0, 1),
  cond(eq(this.expanded, 0), 1, 0),
);
```

**Comment by lkoehl** [comment]
Fixed it by using interpolate like in the example of the [IconDrawer.js](https://github.com/kmagiera/react-native-reanimated/blob/067b440b33617f3e4928d19e79e945a71f0acf50/Example/interactablePlayground/examples/IconDrawer.js) instead of the example [WithDrag.js](https://github.com/kmagiera/react-native-reanimated/blob/07a5c8c27105c7c159b1c3104f1871252aa0e00b/Example/src/interpolate/WithDrag.js)

Still there might be a problem with the usage.

**Comment by osdnk** [comment]
Thanks for debugging!
