### ISSUE TITLE
useAnimatedScrollHandler doesnt work with newest stack

### ISSUE THREAD

**Issue by NotGeorgeMessier** [software-mansion/react-native-reanimated#4299]
### Description

Overall methods inside hook do not triggers onScroll event

changing shared value from js thread (by onpress 4example) is working ok!

### Steps to reproduce

1. just an example from docs: https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedScrollHandler

`const scrollHandler = useAnimatedScrollHandler((event) => {
    translationY.value = event.contentOffset.y;
  });
 `
the same code as in docs
seems like nothing inside that scope working
i may change to smth static and anyway no animation
`    translationY.value = 200;`
    
May it be because newest rn version with new arch + reanimated v3 combo?
Any thoughts?

### Snack or a link to a repository

https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedScrollHandler

### Reanimated version

3.0.2

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iphone 14

### Acknowledgements

Yes

**Comment by NotGeorgeMessier** [comment]
useScrollViewOffset from the example https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useScrollViewOffset
not interact too

**Comment by aleksey-mukho** [comment]
I have the same problem. (iOS, react-native 0.71.6, react-native-reanimated 3.0.2, new architecture), on Android is working fine.

**Comment by aleksey-mukho** [comment]
@NotGeorgeMessier did you have the possibility to find the reason for such behavior?

**Comment by NotGeorgeMessier** [comment]
> @NotGeorgeMessier did you have the possibility to find the reason for such behavior?

looks like there is still no solution, and overall, about amount of issues with last versions, seems, there is lot work to fix that all)

**Comment by fmorau** [comment]
Faced the same issue,
Did you find any workaround to it?

**Comment by Sergiohcp** [comment]
Has anyone managed to resolve this?

**Comment by Yurii-Lutsyk** [comment]
The same issue

**Comment by top-kat** [comment]
@NotGeorgeMessier I've open a similar issue, not sure it is related => #5494 

In my case, it works fine in android but not on ios. Also values are updated, but only on scroll start / end, that seem to differ from the original issue you posted.

Here is a snack to demonstrate the issue:

https://snack.expo.dev/@topkat/issue-4299-with-usescrollviewoffset-on-ios-


And video screenshot: 

https://github.com/software-mansion/react-native-reanimated/assets/17770809/34e564b0-315c-467f-805d-517c206afa0a

**Comment by szydlovsky** [comment]
Hey everyone, I can confirm that currently both [useAnimatedScrollHandler docs](https://docs.swmansion.com/react-native-reanimated/docs/scroll/useAnimatedScrollHandler) as well as [useScrollViewOffset docs](https://docs.swmansion.com/react-native-reanimated/docs/scroll/useScrollViewOffset) examples work perfectly on Fabric arch
