### ISSUE TITLE
Components randomly changing to other components' styles after hot reload without a recognizable pattern

### ISSUE THREAD

**Issue by canpoyrazoglu** [software-mansion/react-native-reanimated#4314]
### Description

I'm working on a fresh project and installed Reanimated for the first time.

I have a `MyComponent` component which has an inner view with animated opacity value and uses it similar to the following:

```
import Animated, {
    useSharedValue,
    withTiming,
  } from 'react-native-reanimated';

[...]

const activeValue = useSharedValue(props.isActive ? 1 : 0);
    useEffect(() => {
        activeValue.value = withTiming(props.isActive ? 1 : 0, {
            duration: 300
        });
    }, [props.isActive])
[...]
return [...]  <Animated.View style={[styles.activeBackground, {
            opacity: activeValue
        }]} />[...]
```

I have multiple, independent instances X and Y of `MyComponent`. X uses the active value property (provided to the component) whereas Y doesn't use it at all. Whenever I hot reload, sometimes, Y also starts acting like X as if it also has an `activeValue` and displays the view with that opacity whereas there is literally no way that it can have that value in that component. There is no discernible pattern of this happening, it happens to happen randomly, but always after a hot reload.

### Steps to reproduce

1. Have a component class use an inner `Animated.View` and `useSharedValue` to drive opacity. (don't know the exact pattern, but it was this way in my case)
2. Have multiple instances of that component. I had two, one was having a shared value number being driven, whereas the other had it static (never changing after component was created).
3. Do something, perhaps completely unrelated, and do hot reload by simply saving a file.
4. The problem *MIGHT* occur. I don't see a solid pattern though, sometimes it just works perfectly without the issue.

### Snack or a link to a repository

-

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by vozaldi** [comment]
Do you experience this in production build?

I think on real case, user won't be able to do hot reload. As long as it only occur on debug mode, I'd say it's safe to ignore.

**Comment by Latropos** [comment]
Yes, we are aware of the problem but are unable to propose a good solution because of the way fast reload works. The issue is described here: https://reactnative.dev/docs/fast-refresh
You can add a comment `// @refresh reset` anywhere in your file to fix it, but state no longer will be persisted and work with your app will get more cumbersome

**Comment by damianbeles** [comment]
@Latropos are you actively looking for a solution on this?
It happens for me too.

Should we take the "Close action" as "We won't solve this" or why would you close it otherwise?

**Comment by Latropos** [comment]
@damianbeles We won't solve this, this bug is expected due to the way fast refresh works. Please read this docs for documentation: https://reactnative.dev/docs/fast-refresh#fast-refresh-and-hooks

You can add comment `// @refresh reset` anywhere in your file and component state won't be preserved any longer.
