### ISSUE TITLE
Entry/Exit animation causes memory leak

### ISSUE THREAD

**Issue by bglgwyng** [software-mansion/react-native-reanimated#4322]
### Description

I've invested memory usage in entry/exit animation.
I found that memory usage grows by repeating it.
When the entry/exit animation is unset(not giving `entry` and `exit` props), memory usage doesn't grow.

### Steps to reproduce

1. Repeat mounting and unmounting `Animated.View` with `entry` and `exit` props.
3. See memory usage growing

### Snack or a link to a repository

https://github.com/bglgwyng/Reanimated3Sandbox

### Reanimated version

3.0.2

### React Native version

0.71.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Thank you for submitting the issue with example and reproduction :heart:
We have investigated your issue and we suppose there is no leak. Some unused refs are removed by garbage collector only after receiving a signal to do this.
Lets modify your code to make your app's performance heavier:
```tsx
    <View style={{flexGrow: 1}}>
      {foo &&
        [...new Array(1000)].map((_, idx) => (
          <Animated.View
            key={idx}
            entering={FadeIn}
            exiting={FadeOut}
            style={[StyleSheet.absoluteFill, {backgroundColor: 'blue'}]}
          />
        ))}
    </View>
```

Now memory use gets stable. You can see the attached recording of performace monitor:


https://user-images.githubusercontent.com/56199675/233957945-5ff00fbc-5e58-47a9-9f67-e8dba85a33ba.mov
