### ISSUE TITLE
Had reanimated something equivalent to 'Animated.forkEvent()' from the Animated api?

### ISSUE THREAD

**Issue by brunocrpontes** [software-mansion/react-native-reanimated#433]
Sometimes when we build a component over an existing component, you need to use its events within that component and keep it visible to your parents as well. In the Animated API, the [forkEvent](https://facebook.github.io/react-native/docs/animated#forkevent) function does this work. Would reanimated have any equivalent function?

**Comment by ShaMan123** [comment]
I have a working fork for android, no iOS yet.
Once #469 is merged I'll PR.

**Comment by jkadamczyk** [comment]
Hey @brunocrpontes this is not currently available, like @ShaMan123 stated he has a PR, but none of us had time to review it recently, and everything related to this became a bit stale 😞
