### ISSUE TITLE
SharedElementTransition not working with use_frameworks!

### ISSUE THREAD

**Issue by kapir** [software-mansion/react-native-reanimated#4337]
### Description

After a lot of reasarching and reverese engineerring example app i found the issue.
Not getting any errors, it just does not work.

I used the example listed in the documentation (https://docs.swmansion.com/react-native-reanimated/docs/api/sharedElementTransitions)

Might not be worth a fix, but would be great if its listed in known problems

### Steps to reproduce

1. Create default rn-app
2. Add react-navigation with native stack and reanimated
3. Add react-native-firebase and use_frameworks! in podfile.

### Snack or a link to a repository

No repro

### Reanimated version

3.0.2

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by selven** [comment]
Having the same issue, did you find a workaround at all?

**Comment by tjzel** [comment]
Closing this in favor of https://github.com/software-mansion/react-native-reanimated/issues/4966 which had a longer discussion.
