### ISSUE TITLE
V3 performance issue when repeatedly calling animations using withTiming or withSpring

### ISSUE THREAD

**Issue by psquizzle** [software-mansion/react-native-reanimated#4338]
### Description

I am performing a simple animation on metering data from recording. This worked perfectly on V2 and actually V3 rc ("3.0.0-rc.10"). On V3 UI thread fps goes to 0 and the app freezes up.

### Steps to reproduce

1. Run the example app using "3.0.0-rc.10"
2. Install the latest reanimated v3, (any version above rc.10)
3. App freezes up
4. Remove withSpring animation and it works but without smooth animation

### Snack or a link to a repository

https://github.com/psquizzle/ra-issue.git

### Reanimated version

3.0.0

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 14 Pro Max

### Acknowledgements

Yes

**Comment by psquizzle** [comment]
The issue appears to be resolved in ~3.3.0. Thank you.

**Comment by DorianMazur** [comment]
@psquizzle It's not

**Comment by psquizzle** [comment]
Tested on my example repo, UI thread no longer goes to 0 fps.
