### ISSUE TITLE
App crash on iOS 16 or higher systems

### ISSUE THREAD

**Issue by CFPanda** [software-mansion/react-native-reanimated#4341]
### Description

The crash stack is as follows：

Caused by:Attempted to dereference null pointer
1	
0 TestDemo 0x0000000106777044 std::__1::__shared_ptr_emplace<facebook::jsi::Function, std::__1::allocator<facebook::jsi::Function> >::__on_zero_shared() (in TestDemo) (shared_ptr.h:315)
2	
1 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
3	
2 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
4	
3 TestDemo 0x0000000106797c64 reanimated::HostFunctionHandler::~HostFunctionHandler() (in TestDemo) (HostFunctionHandler.h:11)
5	
4 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
6	
5 TestDemo 0x00000001067979ac reanimated::HostFunctionWrapper::~HostFunctionWrapper() (in TestDemo) (ValueWrapper.h:74)
7	
6 TestDemo 0x0000000106797694 reanimated::ShareableValue::~ShareableValue() (in TestDemo) (ShareableValue.h:23)
8	
7 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
9	
8 TestDemo 0x0000000106778908 std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> > > >::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> >, void*>*>*) (in TestDemo) (__hash_table:1580)
10	
9 TestDemo 0x00000001067788c8 std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<reanimated::ShareableValue> > > >::~__hash_table() (in TestDemo) (__hash_table:1523)
11	
10 TestDemo 0x0000000106764ff0 reanimated::FrozenObject::~FrozenObject() (in TestDemo) (FrozenObject.h:16)
12	
11 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
13	
12 TestDemo 0x0000000106797824 reanimated::FrozenObjectWrapper::~FrozenObjectWrapper() (in TestDemo) (ValueWrapper.h:82)
14	
13 TestDemo 0x0000000106797694 reanimated::ShareableValue::~ShareableValue() (in TestDemo) (ShareableValue.h:23)
15	
14 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
16	
15 TestDemo 0x0000000105d63e9c std::__1::__vector_base<std::__1::shared_ptr<reanimated::WorkletEventHandler>, std::__1::allocator<std::__1::shared_ptr<reanimated::WorkletEventHandler> > >::~__vector_base() (in TestDemo) (vector:487)
17	
16 TestDemo 0x0000000106797d54 reanimated::FrozenArrayWrapper::~FrozenArrayWrapper() (in TestDemo) (ValueWrapper.h:96)
18	
17 TestDemo 0x0000000106797694 reanimated::ShareableValue::~ShareableValue() (in TestDemo) (ShareableValue.h:23)
19	
18 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
20	
19 TestDemo 0x000000010676b864 reanimated::MutableValue::~MutableValue() (in TestDemo) (MutableValue.h:18)
21	
20 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
22	
21 TestDemo 0x0000000106825b6c facebook::jsi::DecoratedHostObject::~DecoratedHostObject() (in TestDemo) (decorator.h:57)
23	
22 hermes 0x000000010cf15644 0x000000010cf08000 + 4956
24	
23 hermes 0x000000010cf162f4 0x000000010cf08000 + 8204
25	
24 hermes 0x000000010cfca6d0 0x000000010cf08000 + 694548
26	
25 hermes 0x000000010cfcbc64 0x000000010cf08000 + 700072
27	
26 hermes 0x000000010cf67c98 0x000000010cf08000 + 290524
28	
27 hermes 0x000000010cf67f8c 0x000000010cf08000 + 291280
29	
28 hermes 0x000000010cf15644 0x000000010cf08000 + 4956
30	
29 hermes 0x000000010cf15574 0x000000010cf08000 + 4748
31	
30 hermes 0x000000010cf14300 0x000000010cf08000 + 24
32	
31 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
33	
32 TestDemo 0x0000000106823880 facebook::react::(anonymous namespace)::DecoratedRuntime::~DecoratedRuntime() (in TestDemo) (HermesExecutorFactory.cpp:172)
34	
33 TestDemo 0x00000001058159a4 std::__1::shared_ptr<std::__1::__empty_state<char> >::~shared_ptr() (in TestDemo) (shared_ptr.h:959)
35	
34 TestDemo 0x00000001068235b0 facebook::react::JSIExecutor::~JSIExecutor() (in TestDemo) (JSIExecutor.h:71)
36	
35 TestDemo 0x0000000106823694 facebook::react::HermesExecutor::~HermesExecutor() (in TestDemo) (HermesExecutorFactory.h:41)
37	
36 TestDemo 0x000000010685ed80 facebook::react::tryAndReturnError(std::__1::function<void ()> const&) (in TestDemo) (function.h:0)
38	
37 TestDemo 0x0000000106869684 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) (in TestDemo) (RCTMessageThread.mm:69)
39	
38 TestDemo 0x00000001068699c8 facebook::react::RCTMessageThread::runOnQueueSync(std::__1::function<void ()>&&) (in TestDemo) (RCTMessageThread.mm:92)
40	
39 TestDemo 0x00000001068fff64 facebook::react::NativeToJsBridge::destroy() (in TestDemo) (NativeToJsBridge.cpp:285)
41	
40 TestDemo 0x00000001068f7a88 facebook::react::Instance::~Instance() (in TestDemo) (Instance.cpp:40)
42	
41 TestDemo 0x000000010685c658 std::__1::__shared_ptr_pointer<facebook::react::Instance*, std::__1::shared_ptr<facebook::react::Instance>::__shared_ptr_default_delete<facebook::react::Instance, facebook::react::Instance>, std::__1::allocator<facebook::react::Instance> >::__on_zero_shared() (in TestDemo) (shared_ptr.h:267)
43	
42 TestDemo 0x00000001068595d8 __26-[RCTCxxBridge invalidate]_block_invoke (in TestDemo) (RCTCxxBridge.mm:1242)
44	
43 TestDemo 0x000000010685ed80 facebook::react::tryAndReturnError(std::__1::function<void ()> const&) (in TestDemo) (function.h:0)
45	
44 TestDemo 0x0000000106854e94 -[RCTCxxBridge _tryAndHandleError:] (in TestDemo) (RCTCxxBridge.mm:317)
46	
45 Foundation 0x00000001b76dd7cc __NSThreadPerformPerform (in Foundation) + 264
47	
46 CoreFoundation 0x00000001bd404f24 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ (in CoreFoundation) + 28
48	
47 CoreFoundation 0x00000001bd4112fc __CFRunLoopDoSource0 (in CoreFoundation) + 176
49	
48 CoreFoundation 0x00000001bd3951c0 __CFRunLoopDoSources0 (in CoreFoundation) + 244
50	
49 CoreFoundation 0x00000001bd3aab7c __CFRunLoopRun (in CoreFoundation) + 836
51	
50 CoreFoundation 0x00000001bd3afeb0 CFRunLoopRunSpecific (in CoreFoundation) + 612
52	
51 TestDemo 0x0000000106854dcc +[RCTCxxBridge runRunLoop] (in TestDemo) (RCTCxxBridge.mm:0)
53	
52 Foundation 0x00000001b76fd518 __NSThread__start__ (in Foundation) + 716
54	
53 libsystem_pthread.dylib 0x000000020b5b16cc _pthread_start (in libsystem_pthread.dylib) + 148

### Steps to reproduce

1. Open an RN page

2. Using the react-native-draggable-flatlist component

3. Destroy RN page and App crash

react-native-draggable-flatlist version is 4.0.1
react-native-gesture-handler version is 2.8.0
eact-native-reanimated version is 2.10.0

After using the drag and drop component, a crash occurred during the page destruction attempt, which occurred in the animation library。

### Snack or a link to a repository

无

### Reanimated version

2.10.0

### React Native version

0.64.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

 iOS 16 or higher systems

### Acknowledgements

Yes

**Comment by billnbell** [comment]
Same issue here!

**Comment by efstathiosntonas** [comment]
@CFPanda can you please use Xcode instruments and check/profile for memory leaks?

**Comment by tomekzaw** [comment]
Hey, please upgrade to Reanimated v3 (latest is 3.0.2) which resolves this kinds of bugs.

**Comment by angelica-snowit** [comment]
Not everyone can upgrade to v3!
https://github.com/mrousavy/react-native-vision-camera (the only lib to manage camera on react native currently mantained) still depends on v2.
