### ISSUE TITLE
useAnimatedGestureHandler incompatible with GestureDetector

### ISSUE THREAD

**Issue by JS-GitRepo** [software-mansion/react-native-reanimated#4345]
### Description

The React Native Gesture Handler docs advise against the pattern listed in the Reanimated docs [here](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedGestureHandler), suggesting the use of "GestureDetector" instead of  "TapGestureHandler". The issue is that the required prop for GestureDetector, "gesture={}" does not accept the result of useAnimatedGestureHandler() or variations thereof as an input. useAnimatedGestureHandler()'s type is infered as "OnGestureEvent-PanGestureHandlerGestureEvent-". In summary, is this hook now deprecated?

Overall, it appears that the Reanimated docs need to be updated for compatibility with GestureDetector if the other Gesture Handler methods are on the road to deprecation.

### Steps to reproduce

1. Try to use useAnimatedGestureHandler() results with GestureDetector from RNGH
2. Try to follow Reanimated docs to resolve issues with filling gesture={} prop
3. Little to no info on how to do this; docs advise using methods from RNGH that are on road to deprecation

Attached link is a rough mockup of the kind of setup I'm describing, but the issue is more about a lack of documentation for approaching this problem. I have tried many variations of the example including adding a const gesture = Gesture.Tap(useAnimatedGestureHandler() result) format etc and can't get it to work.

### Snack or a link to a repository

https://snack.expo.dev/@js-dev/quick-reanimated-error-ex

### Reanimated version

3.0.2

### React Native version

0.71.6

### Platforms

Android, iOS, Web

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Google Pixel 7

### Acknowledgements

Yes

**Comment by iway1** [comment]
you need to use the new gesture API to use `GestureDetector`, useAnimatedGestureHandler is the old API.

Yeah the docs are extremely lacking, I just came here to open an issue about it. I'm using the new API in my app and I legit cannot find docs for it I can't even remember where I found them in the first place

**Comment by tomekzaw** [comment]
Hey, we're working on new docs. As for now, here's an example how to use Gesture Handler v2 API with Reanimated: https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/GestureHandlerExample.tsx
