### ISSUE TITLE
[Question] useCode vs. onChange

### ISSUE THREAD

**Issue by ShaMan123** [software-mansion/react-native-reanimated#435]
I wanted to ask about best practice.

**`useCode` is straight forward great.**
I find myself using it a lot and I wanted to ask what's better perfomance-wise:

a. using multiple `useCode` hooks in a function component
b. using as little as possible `useCode` hooks and managing nodes with `onChange`
c. no difference

Thanks

**Comment by osdnk** [comment]
So basically `useCode` is a hook that attaches and detaches nodes from the JS side. 

`onChange` is a derived node which evaluates the second argument on change value of the first one
