### ISSUE TITLE
Unable to run on Android with RN 0.71.0

### ISSUE THREAD

**Issue by Daneyl** [software-mansion/react-native-reanimated#4371]
### Description

After upgrading with RN version to 0.71.0 I am getting this error:

`FAILURE: Build failed with an exception.

* Where:
Build file '/Users/daniyalpasha/Documents/SG/CA/consignor-app/node_modules/react-native-reanimated/android/build.gradle' line: 678

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Expected directory '/Users/daniyalpasha/Documents/SG/CA/consignor-app/node_modules/react-native/android' to contain exactly one file, however, it contains no files.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings`

### Steps to reproduce

1- Get the latest RN version (0.71.0)
2- After running yarn and pod install, run `./gradlew clean` inside android folder
3- You should see this above posted error 

### Snack or a link to a repository

none

### Reanimated version

2.10.0

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by hexadecy** [comment]
Reanimated version should be at least 2.14.0.
