### ISSUE TITLE
scrollTo not working with FlashList

### ISSUE THREAD

**Issue by QOAL** [software-mansion/react-native-reanimated#4376]
### Description

I've seen there's been previous work done to accommodate FlashList with Reanimated, but I'm still suffering from an issue when using it myself.

Using scrollTo on an animated reference of a FlashList does nothing, but works fine with a standard FlatList.

The provided test case is quite similar to actual usage in my app, other than I actually use a gesture to set the position.

### Steps to reproduce

Run the provided repository and press the `New Pos` button, or see App.js

### Snack or a link to a repository

https://github.com/QOAL/rnflrepro

### Reanimated version

3.0.2

### React Native version

0.71.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Realme 7 (Global)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @QOAL, thanks for reporting this issue and for the repro, I will take a look on it.

**Comment by tomekzaw** [comment]
Hey @QOAL, based on the repro you have provided I was able to successfully reproduce the issue, find out what's wrong and come up with a fix:

https://github.com/software-mansion/react-native-reanimated/blob/b44920c101778de8566a3247061b14775cb21737/src/reanimated2/hook/useAnimatedRef.ts#L30

```diff
-tag.value = getTagValueFunction(component);
+tag.value = getTagValueFunction(component.getScrollableNode ? component.getScrollableNode() : component);
```

I will submit a PR with this fix soon. Thanks again!

**Comment by tomekzaw** [comment]
Here's the PR: #4384
