### ISSUE TITLE
Animated styles are not properly reactive in V3, but an extra touch triggers rerendering

### ISSUE THREAD

**Issue by bglgwyng** [software-mansion/react-native-reanimated#4382]
### Description

Animated styles from `useAnimatedStyle` is not applied immediately when it is recomputed. I don't mean that there are few frames passed. It's just not applied until there comes an extra touch on the screen.

Expected behavior:

https://user-images.githubusercontent.com/19142113/233308867-5575e339-12cd-43fe-93dd-aaf98a721a9b.mp4

You can see the red rectangle and the green rectangle appears at once when the button gets pressed.

Actual behavior:

https://user-images.githubusercontent.com/19142113/233308994-ec205dd7-a793-45c4-9e2b-e456f03e5cb5.mp4

You can see the green rectangle doesn't appear the first time. But after the extra touch comes, then it does.

I tested on iPhone 13, Galaxy S10, and Galaxy S20 and an Android emulator. The behaviors were the same.
One more strange behavior is that when I tested it via Expo Snack [here](https://snack.expo.dev/), it worked properly.

# More context
Once I posted [this](https://github.com/software-mansion/react-native-reanimated/discussions/3925) on Discussions.
After that, I saw a PR titled [Add setImmediate implementation to the UI runtime](https://github.com/software-mansion/react-native-reanimated/pull/3970) and expected that they are relevant. So I tested the same code with Reanimated V3 and observed the behavior described here.

### Steps to reproduce

1. Clone the repo below
2. Press 'Press me' button.
3. See the green rectangle not visible
4. Touch anywhere on the screen and the green rectangle shows up

### Snack or a link to a repository

https://github.com/bglgwyng/Reanimated3Sandbox/tree/animated-style-test

### Reanimated version

3.0.2

### React Native version

0.71.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy S10

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Should be fixed with #4329.
