### ISSUE TITLE
(REANodesManager) NSInternalInconsistencyException - Mouting block is expected to not be set

### ISSUE THREAD

**Issue by LeviWilliams** [software-mansion/react-native-reanimated#4394]
### Description

While implementing https://github.com/gorhom/react-native-bottom-sheet (5.0.0-alpha to support reanimated v3) I was able to reproduce this crash consistently.  Opening / closing the bottom sheet with pan and attempting to scroll a flatlist within it causes the crash.

Trace:
```
NSInternalInconsistencyException: Mounting block is expected to not be set

0  CoreFoundation +0x9e84             ___exceptionPreprocess
1  libobjc.A.dylib +0x178d4           _objc_exception_throw
2  Foundation +0x545c84               -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:]
3  fiftyfour.e.oneputtgolf +0xee3570  -[REANodesManager uiManager:performMountingWithBlock:] (REANodesManager.mm:246:3)
4  fiftyfour.e.oneputtgolf +0x107f058 -[RCTUIManagerObserverCoordinator uiManager:performMountingWithBlock:] (RCTUIManagerObserverCoordinator.mm:81:11)
5  fiftyfour.e.oneputtgolf +0x107a0a0 -[RCTUIManager flushUIBlocksWithCompletion:] (RCTUIManager.m:1206:7)
6  fiftyfour.e.oneputtgolf +0x1079e10 -[RCTUIManager _layoutAndMount] (RCTUIManager.m:1172:3)
7  fiftyfour.e.oneputtgolf +0x1079ba0 -[RCTUIManager batchDidComplete] (RCTUIManager.m:1148:3)
8  fiftyfour.e.oneputtgolf +0xee2ae4  -[RCTUIManager(SyncUpdates) runSyncUIUpdatesWithObserver:] (REANodesManager.mm:81:3)
9  fiftyfour.e.oneputtgolf +0xee3c2c  __36-[REANodesManager performOperations]_block_invoke (REANodesManager.mm:289:9)
10 fiftyfour.e.oneputtgolf +0x107f930 __RCTExecuteOnUIManagerQueue_block_invoke (RCTUIManagerUtils.m:60:7)
11 libdispatch.dylib +0x24b0          __dispatch_call_block_and_release
12 libdispatch.dylib +0x3fd8          __dispatch_client_callout
13 libdispatch.dylib +0xb690          __dispatch_lane_serial_drain
14 libdispatch.dylib +0xc1dc          __dispatch_lane_invoke
15 libdispatch.dylib +0x16e0c         __dispatch_workloop_worker_thread
16 libsystem_pthread.dylib +0xdf4     __pthread_wqthread
17 libsystem_pthread.dylib +0xb94     _start_wqthread
```

### Steps to reproduce
There are many ways but I was able to do it with a combo of the following:
1. Open a bottom sheet that contains a flatlist
2. Close the modal using pan gesture 
3. Open modal and attempt to scroll as its opening

### Snack or a link to a repository

.

### Reanimated version

3.0.2

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 12 pro 

### Acknowledgements

Yes

**Comment by LeviWilliams** [comment]
I was able to fix this by closing the modal via ref instead of unmounting and then later unmounting. Not a hack so all good - but still unexpected behaviour as unmounting this sheet shouldn't crash the app.

**Comment by LeviWilliams** [comment]
Duplicate - https://github.com/software-mansion/react-native-reanimated/issues/2285
Though the bottom sheet is using a flatlist

**Comment by cormacbeagan** [comment]
I am seeing this crash for reanimated versions 2.15.0, 2.16.0 2.17.0 and 3.1.0 on a heavy drag and drop interface including a flatlist with a PanGestureHandler per item. 
RN 0.68.6
iOS 16.4 - real device (iPad) 

2.14.4 seems to be stable 🤞

**Comment by LeviWilliams** [comment]
Fixed by #4403

**Comment by radekzz** [comment]
3.5.4 still facing same error

**Comment by cihangir-mercan** [comment]
i was getting below crashes at 2.17.0. i have reverted back to 2.14.4

*** Assertion failure in -[REANodesManager uiManager:performMountingWithBlock:](), /Users/cm/IdeaProjects/crypto_commits/node_modules/react-native-reanimated/ios/REANodesManager.m:237
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Mouting block is expected to not be set'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001195f8761 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000113cd8904 objc_exception_throw + 48
	2   Foundation                          0x000000011a41db27 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
	3   cm                        0x0000000102b218e1 -[REANodesManager uiManager:performMountingWithBlock:] + 433
	4   cm                        0x0000000102e94660 -[RCTUIManagerObserverCoordinator uiManager:performMountingWithBlock:] + 800
	5   cm                        0x0000000102e898c9 -[RCTUIManager flushUIBlocksWithCompletion:] + 1209
	6   cm                        0x0000000102e892f8 -[RCTUIManager _layoutAndMount] + 1576
	7   cm                        0x0000000102e88ca1 -[RCTUIManager batchDidComplete] + 81
	8   cm                        0x0000000102b1fe9e -[RCTUIManager(SyncUpdates) runSyncUIUpdatesWithObserver:] + 606
	9   cm                        0x0000000102b223cd __36-[REANodesManager performOperations]_block_invoke + 909
