### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by maugou** [software-mansion/react-native-reanimated#4396]
### Description

- error message
``` 
TypeError: undefined is not a function
    at reportFatalError (/Users/app/node_modules/react-native-reanimated/lib/commonjs/reanimated2/initializers.js:151:29)
    at callGuardDEV (worklet_2058902618278:9:43)
```

- component
```
import React from 'react';
import Animated from 'react-native-reanimated';

function App(): JSX.Element {
  return <Animated.View style={{ flex: 1 }} />;
}

export default App;
```

If you apply only Animated as in the code above, the above error occurs.
It doesn't seem to happen in new projects, so it seems to be my  problem, but I can't figure out why.

Has anyone experienced the above problem?

### Steps to reproduce

1. react-native-reanimated v3 install
2. use 'Animated' from 'react-native-reanimated'

### Snack or a link to a repository

-

### Reanimated version

3.1.0

### React Native version

0.71.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey 👋 If it doesn't happen in the new project it means this is a Babel cache issue. Try to clear your cache like that:
```
watchman watch-del-all
yarn start --reset-cache
```

**Comment by maugou** [comment]
> Hey 👋 If it doesn't happen in the new project it means this is a Babel cache issue. Try to clear your cache like that:
> 
> ```
> watchman watch-del-all
> yarn start --reset-cache
> ```


Thank you for answer.
However, I tried the method you guided and it was the same.😭

Could another cache be involved?

**Comment by BogdanRad** [comment]
I have same problem... @maugou did you find a solution? thank you

**Comment by bhavink-hkis** [comment]
did you find 
any solution  ? @maugou

**Comment by maugou** [comment]
@BogdanRad @bhavink-hkis 

Try upgrading to version 3.2.0
The above problem does not appear.

**Comment by RGDEV2022** [comment]
Still having the same issue on 3.3.0

**Comment by Rehan-05** [comment]
Still having the same issue.

 ERROR  TypeError: undefined is not a function, js engine: hermes
 LOG  Running "soscolab2019" with {"rootTag":11}
 ERROR  Invariant Violation: "soscolab2019" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
