### ISSUE TITLE
[3.1.0] Unable to launch iOS app

### ISSUE THREAD

**Issue by TomCorvus** [software-mansion/react-native-reanimated#4400]
### Description

Since I updated REA to 3.1.0, the app crashes before launching.
This problem occurs only on iOS and debug mode only.

I tried to disable Hermes and Fabric, remove caches.
![Simulator Screenshot - iPhone 14 Pro Max - 2023-04-24 at 16 22 41](https://user-images.githubusercontent.com/3451011/234025664-e5f8d9f7-bc08-487f-abe1-389338af79d8.png)

<img width="665" alt="Capture d’écran 2023-04-24 à 16 22 10" src="https://user-images.githubusercontent.com/3451011/234025561-cc6b2daf-f455-4c9d-b798-e36fbc784ec5.png">

For now, I don't reproduce on a fresh install, the problem, but I'm on it.
It's just to know if someone else have the same error.

I'm on Xcode 14.3.

Downgrade to REA 3.0.2 and the problems disappears.

### Steps to reproduce

Soon, I hope

### Snack or a link to a repository

Soon, I hope

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo bare workflow

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro Max (iOS 16.4)

### Acknowledgements

Yes

**Comment by davoam** [comment]
In my case on iOS it immediately crashes, on Android it shows an error which I did not have in reanimated version 2

**Comment by TomCorvus** [comment]
All dependencies is up-to-date. I will try to remove animations one by one and simplify the code to have a clue.
@davoam Do you have your error with REA 3.0.2? And what is this error? Do you have a message?

**Comment by davoam** [comment]
> All dependencies is up-to-date. I will try to remove animations one by one and simplify the code to have a clue. @davoam Do you have your error with REA 3.0.2? And what is this error? Do you have a message?

I tried `3.0.2` it didn't help. I don't get any error message. As per Xcode error happens somewhere here 
![image](https://user-images.githubusercontent.com/9194866/234335407-83e75cd6-4349-4171-9694-b75f25bba185.png)

I even simplified my code to one view. If I don't import anything from `react-native-reanimated`, the app does not crash, If I import and use `useSharedValue`, it crashes

**Comment by vanGalilea** [comment]
> Not sure if it's the same issue, but I got past this by updating all react-navigation dependencies - don't forget react-native-safe-area-context and react-native-screens.

Upgrading `react-native-screens` from 3.2.0 to 3.20.0 has solved my issue.

**Comment by BakkerTom** [comment]
I had the same issue. In my case, it was due to a mismatched babel plugin version. Restarting the metro bundler and clearing the cache solved the issue for me. 

```
yarn start --reset-cache
```

**Comment by Essam-Harrous** [comment]
> yarn start --reset-cache

this worked for me thanks

**Comment by TomCorvus** [comment]
Thanks @BakkerTom, it seems to be working for me too.

**Comment by fukemy** [comment]
> I had the same issue. In my case, it was due to a mismatched babel plugin version. Restarting the metro bundler and clearing the cache solved the issue for me.
> 
> ```
> yarn start --reset-cache
> ```

which babel plugin version matched? THanks
