### ISSUE TITLE
Assertion failed: (shareableWorklet->valueType() == Shareable::WorkletType && "only worklets can be scheduled to run on UI"), function scheduleOnUI, file NativeReanimatedModule.cpp, line 214.  (lldb)

### ISSUE THREAD

**Issue by PrincyVaidya** [software-mansion/react-native-reanimated#4423]
### Description

Ios App crashed after running from XCode 
<img width="1790" alt="Screenshot 2023-05-03 at 5 53 00 PM" src="https://user-images.githubusercontent.com/99018580/235918418-f241c300-a26d-494d-9fe7-0ef68beefeae.png">

### Steps to reproduce

npm install react-native-reanimated
cd ios
pod install
open xcode & clean build folder 
run project
1st default screen came with app name , after bundle start app getting crash

### Snack or a link to a repository

NA

### Reanimated version

3.0.1

### React Native version

0.69.7

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

iphone 16.4.1

### Acknowledgements

Yes

**Comment by lukeeey** [comment]
did you fix the issue? im getting this too

**Comment by Princy-vaidya** [comment]
> 

No, Still stuck on this issue.

**Comment by piaskowyk** [comment]
Hey! Thanks for the report but without reproduction, we can't help you, because this problem can be caused by other dependencies of your application that uses Reanimated. If anyone provides repro I will be happy to reopen the issue again 😀

**Comment by hoseinfo** [comment]
any fix for it?

**Comment by devinMcArthur** [comment]
@hoseinfo, I just ran into this problem after updating the package, the issue was a result of not having the `react-native-reanimated` plugin in my `babel.config.js`.

Documentation can be found on their website: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

Hope this helps.
