### ISSUE TITLE
Calling scrollTo from useDerivedValue results in error on web (TypeError: e(...).scrollTo is not a function)

### ISSUE THREAD

**Issue by azcarraga** [software-mansion/react-native-reanimated#4424]
### Description

Calling `scrollTo()` from within a `useDerivedValue()` results in the error below on web only (works fine on iOS + Android):
```
TypeError: e(...).scrollTo is not a function
    at e (NativeMethods.ts:116:13)
 ```
NativeMethods.ts: 116
```
  113 |     'worklet';
  114 |     const element = animatedRef() as unknown as HTMLElement;
  115 |     // @ts-ignore same call as in react-native-web
> 116 |     element.scrollTo({ x, y, animated });
  117 |   };
  118 | } else if (isNative && global._IS_FABRIC) {
  119 |   scrollTo = (
```

### Steps to reproduce

1. Open attached snack on web - error triggers on first call to useDerivedValue()

Expected: App should load, and pressing "Scroll" button should scroll the ScrollView. The demo works on app platforms.

### Snack or a link to a repository

https://snack.expo.dev/@aazcarraga/4717a4?platform=web

### Reanimated version

3.1.0

### React Native version

0.69.5

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Web (Chrome)

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @azcarraga! I've prepared [PR](https://github.com/software-mansion/react-native-reanimated/pull/4984) that should fix this issue. Could you check that and let me know if it works?

**Comment by azcarraga** [comment]
@m-bert thank you for fixing this! I will try this out soon and get back to you.
