### ISSUE TITLE
Shared Element Transitions not working for iOS when adding use_frameworks inside Podfile.

### ISSUE THREAD

**Issue by jerinjohnk** [software-mansion/react-native-reanimated#4425]
### Description

On adding the line 
`use_frameworks! :linkage => :static` inside `Podfile` 
shared transitions stop working in the iOS build.

My main project has a dependency on [rnfirebase](https://rnfirebase.io/). 
As stated in its documentation [here](https://rnfirebase.io/#altering-cocoapods-to-use-frameworks), it requires CocoaPods to use frameworks.

The shared transition animation stops working when adding the use_frameworks line and rebuilding the project.
After opting out of the use frameworks usage and rebuilding the project fixes this issue, but rnfirebase stops working.
Need help in getting both rnfirebase and shared elements transitions to work together.

In the minimal repo inside `App.tsx` I am calling [ManyScreensExample](https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/SharedElementTransitions/ManyScreens.tsx) to test the transition.

### Steps to reproduce

In [main](https://github.com/jerinjohnk/reanimatedTest/tree/main) branch inside podfile

1. Added line `use_frameworks! :linkage => :static`
2. Commented line  `:flipper_configuration => flipper_config,`

A stable version can be found in the branch [stable/shared](https://github.com/jerinjohnk/reanimatedTest/tree/stable/shared) 

1. Commented line `use_frameworks! :linkage => :static`
2. Uncommented line  `:flipper_configuration => flipper_config,`

### Snack or a link to a repository

https://github.com/jerinjohnk/reanimatedTest/tree/main

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by yaroslavnikiforov** [comment]
The same for me. So you can't use this feature with @react-native-firebase for example.

**Comment by Bayramito** [comment]
I just created a fresh clean project to test this feature on react native latest (0.71.7) 

installed reanimated 3.0.1
react-native-screens 3.20.x

but seems like it is not working at all..
tested with same packages same sample of code on react-native 0.70.9 , it is working fine

seems like something happened  on versions>0.70.9

**Comment by zhenkaGo** [comment]
Try adding this to the Podfile

```
$static_framework = ['RNScreens']

pre_install do |installer|
   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
   installer.pod_targets.each do |pod|
     if $static_framework.include?(pod.name)
       def pod.build_type;
         Pod::BuildType.static_library
       end
     end
   end
end
```

**Comment by jerinjohnk** [comment]
> Try adding this to the Podfile
> 
> ```
> $static_framework = ['RNScreens']
> 
> pre_install do |installer|
>    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>    installer.pod_targets.each do |pod|
>      if $static_framework.include?(pod.name)
>        def pod.build_type;
>          Pod::BuildType.static_library
>        end
>      end
>    end
> end
> ```

Thanks @zhenkaGo adding these lines did fix the issue. 
It won't introduce any breaking change in reanimated or react-native-screens, right?

**Comment by zhenkaGo** [comment]
It should work usually. We build RNScreens as static_library it is the default behavior when you don't use use_frameworks. You can see related issues in these libraries react-native-screens, flipper, react-native-permissions

**Comment by Darren120** [comment]
> Try adding this to the Podfile
> 
> ```
> $static_framework = ['RNScreens']
> 
> pre_install do |installer|
>    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>    installer.pod_targets.each do |pod|
>      if $static_framework.include?(pod.name)
>        def pod.build_type;
>          Pod::BuildType.static_library
>        end
>      end
>    end
> end
> ```

do you know what are the configs for expo managed?

**Comment by TowhidKashem** [comment]
> It should work usually. We build RNScreens as static_library it is the default behavior when you don't use use_frameworks. You can see related issues in these libraries react-native-screens, flipper, react-native-permissions

hey @zhenkaGo @jerinjohnk , does it matter where in the pod file you add this:

```
$static_framework = ['RNScreens']

pre_install do |installer|
   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
   installer.pod_targets.each do |pod|
     if $static_framework.include?(pod.name)
       def pod.build_type;
         Pod::BuildType.static_library
       end
     end
   end
end
```
I don't know Ruby so not sure if I need to put it at any specific spot or if I can just place it at the top of the file? Here's how my Podfile looks like for reference:

```
# [mod]: install react-native-firebase as a static framework
$RNFirebaseAsStaticFramework = true

# [mod]: disable IDFA for react-native-firebase-analytics
$RNFirebaseAnalyticsWithoutAdIdSupport = true

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'AppFoo' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

```

**Comment by zhenkaGo** [comment]
> 'AppFoo'

@TowhidKashem put it in your target 'AppFoo'. near post_install

**Comment by julian-gargicevich** [comment]
> > Try adding this to the Podfile
> > ```
> > $static_framework = ['RNScreens']
> > 
> > pre_install do |installer|
> >    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> >    installer.pod_targets.each do |pod|
> >      if $static_framework.include?(pod.name)
> >        def pod.build_type;
> >          Pod::BuildType.static_library
> >        end
> >      end
> >    end
> > end
> > ```
> 
> do you know what are the configs for expo managed?

Did you figure this out? I'm using expo dev client with firebase and reanimated

**Comment by jerinjohnk** [comment]
@TowhidKashem  & @julian-gargicevich  Sorry for the late reply. Here's my podfile for which it had worked.
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAnalyticsWithoutAdIdSupport=false
$RNAppsFlyerStrictMode=false

use_frameworks! :linkage => :static

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Demo' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'DemoTests' do
    inherit! :complete
    # Pods for testing
  end

  $static_framework = ['RNScreens']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      end
    end
  end
end
```

Hope that helps.

**Comment by shantanu-daisy** [comment]
This patch did not work for me. Does there seem to be an issue with expo 50?

**Comment by MehediH** [comment]
This issue is still persistent, this issue should be reopened

**Comment by AppKidd** [comment]
Issue persists – please reopen

**Comment by andrianarivo** [comment]
I have the same issue with expo 49, reanimated 3.10
