### ISSUE TITLE
The app crashes after migrating from version 2 to version 3

### ISSUE THREAD

**Issue by oleksandr-sokolov** [software-mansion/react-native-reanimated#4426]
### Description

I'm receiving the following error on iOS:

```
...
libc++abi: terminating with uncaught exception of type facebook::jsi::JSError: undefined is not a function

TypeError: undefined is not a function
    at reportFatalError (/Users/master/aaa/ddd/app-mobile/node_modules/react-native-reanimated/lib/commonjs/reanimated2/initializers.js:151:29)
    at callGuardDEV (worklet_2058902618278:9:43)
terminating with uncaught exception of type facebook::jsi::JSError: undefined is not a function

TypeError: undefined is not a function
    at reportFatalError (/Users/master/aaa/ddd/app-mobile/node_modules/react-native-reanimated/lib/commonjs/reanimated2/initializers.js:151:29)
    at callGuardDEV (worklet_2058902618278:9:43)
CoreSimulator 885.2 - Device: iPhone 14 Pro (0C267BBF-5454-4A20-A904-FBE8C009F46E) - Runtime: iOS 16.1 (20B72) - DeviceType: iPhone 14 Pro
(lldb) 
```

While searching for the issue, I noticed a clue in the metro.config.js file. My configuration looks like this:
```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const {getDefaultConfig} = require('metro-config');
const {resolver: defaultResolver} = getDefaultConfig.getDefaultValues();

//
//

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    ...defaultResolver,
    sourceExts: [...defaultResolver.sourceExts, 'cjs', 'mjs'],
  },
};
```

If I change it to the following, everything works fine:
```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

### Steps to reproduce

- git clone git@github.com:oleksandr-sokolov/ReanMetroIssue.git
- yarn && npx pod-install && yarn start
- press  "i" - run on iOS

### Snack or a link to a repository

https://github.com/oleksandr-sokolov/ReanMetroIssue

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by pohsiu** [comment]
Same issue here with v3.1

**Comment by kumar-rahul** [comment]
@oleksandr-sokolov have you tried downgrading it to 2.17.0

**Comment by CHANDRAMOHANnegi** [comment]
<img width="800" height="500" alt="Screenshot 2023-05-11 at 4 22 29 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/32297380/584042fc-1adc-428f-895c-a1a93deca25c">

**Comment by guyromb** [comment]
Same here.

**Comment by fukemy** [comment]
reanimated v3 seem does not support < v7.0.x, all of us need to upgrade `react-native`, `react-native-screen` version to avoid crash

**Comment by guyromb** [comment]
I am currently using:
"react": "18.2.0",
"react-native": "0.71.8",
"react-native-screens": "~3.20.0",
"expo": "~48.0.15",

And it is still crashing @fukemy

**Comment by fukemy** [comment]
> I am currently using:
> 
> "react": "18.2.0",
> 
> "react-native": "0.71.8",
> 
> "react-native-screens": "~3.20.0",
> 
> "expo": "~48.0.15",
> 
> 
> 
> And it is still crashing @fukemy 
> 
> 

please upgrade react navigation/stack to lasted version

**Comment by guyromb** [comment]
I already have:
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
@fukemy

**Comment by guyromb** [comment]
Full list;
  "dependencies": {
    "@bacons/link-assets": "^1.1.0",
    "@gorhom/bottom-sheet": "^5.0.0-alpha.1",
    "@hookform/resolvers": "^3.1.0",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@shopify/flash-list": "1.4.3",
    "@shopify/react-native-skia": "^0.1.192",
    "@tanstack/react-query": "^4.29.7",
    "axios": "^1.4.0",
    "expo": "~48.0.15",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-image": "~1.2.3",
    "expo-localization": "~14.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-system-ui": "~2.2.1",
    "expo-updates": "~0.16.4",
    "i18next": "^22.5.0",
    "lodash.memoize": "^4.1.2",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-error-boundary": "^4.0.4",
    "react-hook-form": "^7.43.9",
    "react-i18next": "^12.3.1",
    "react-native": "0.71.8",
    "react-native-flash-message": "^0.4.1",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-mmkv": "2.8.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.3",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.9.0",
    "react-native-web": "~0.19.4",
    "react-query-kit": "^1.4.5",
    "zod": "^3.21.4",
    "zustand": "^4.3.8"
  },
  "devDependencies": {
    "@babel/core": "^7.21.8",
    "@commitlint/cli": "^17.6.3",
    "@commitlint/config-conventional": "^17.6.3",
    "@expo/config": "~8.0.2",
    "@react-native-community/eslint-config": "^3.2.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/jest-native": "^5.4.2",
    "@testing-library/react-native": "^12.1.2",
    "@types/i18n-js": "^3.8.4",
    "@types/jest": "^29.5.1",
    "@types/lodash.memoize": "^4.1.7",
    "@types/react": "~18.2.7",
    "@types/react-native": "~0.72.1",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.59.7",
    "@typescript-eslint/parser": "^5.59.7",
    "babel-plugin-module-resolver": "^5.0.0",
    "dotenv": "^16.0.3",
    "eslint": "^8.41.0",
    "eslint-plugin-i18n-json": "^4.0.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "eslint-plugin-tailwindcss": "^3.12.0",
    "eslint-plugin-unicorn": "^47.0.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^8.0.3",
    "jest": "^29.5.0",
    "jest-coverage-badges": "^1.1.2",
    "jest-environment-jsdom": "^29.5.0",
    "jest-expo": "48.0.2",
    "lint-staged": "^13.2.2",
    "metro-babel-register": "^0.76.5",
    "np": "^7.7.0",
    "prettier": "^2.8.8",
    "react-test-renderer": "^18.2.0",
    "tailwindcss": "^3.3.2",
    "ts-jest": "^29.1.0",
    "typescript": "^5.0.4"
  },
