### ISSUE TITLE
Task :react-native-reanimated:downloadHermes FAILED

### ISSUE THREAD

**Issue by yujunfan** [software-mansion/react-native-reanimated#4430]
### Description

运行yarn add react-native-reanimated,之后配置babel.config.js
babel.config.js 配置如下：
module.exports = {
  presets: [],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        relativeSourceLocation: true,
      },
    ],
  ],
}; 
组件中引入import Animated from 'react-native-reanimated'; 启动时就会报
> Task :react-native-reanimated:downloadHermes FAILED

> Task :react-native-reanimated:downloadDoubleConversion
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :react-native-reanimated:downloadDoubleConversion FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts 
or plugins.

### Steps to reproduce

1运行yarn add react-native-reanimated；
2配置babel.config.js
babel.config.js 配置如下：
module.exports = {
  presets: [],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        relativeSourceLocation: true,
      },
    ],
  ],
}; 
3 app.tsx 中引入  import Animated from 'react-native-reanimated';
4 yarn android 启动项目

### Snack or a link to a repository

https://snack.expo.dev/

### Reanimated version

3.1.0

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey! Thanks for the report but without reproduction, we are unable to help you. This looks like a problem with your local environment: `Detected multiple Kotlin daemon sessions at build\kotlin\sessions` - I think, this post could help you - https://stackoverflow.com/questions/67135414/w-detected-multiple-kotlin-daemon-sessions-at-build-kotlin-sessions
