### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by djaffer** [software-mansion/react-native-reanimated#4432]
### Description

All the warnings are coming. Fix these so we can have production builds and eslint.

Attempted import error: 'default'.'Clock' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'Value' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'onChange' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'clockRunning' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'startClock' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'stopClock' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'spring' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'abs' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'add' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'and' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'block' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'call' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'cond' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'divide' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'eq' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'event' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'greaterThan' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'lessThan' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'max' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'min' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'multiply' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'neq' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'or' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'set' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'sub' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'Value' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'Value' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'Code' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'Code' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'interpolate' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'interpolateNode' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'cond' is not exported from 'react-native-reanimated' (imported as 'Animated').

Attempted import error: 'default'.'greaterThan' is not exported from 'react-native-reanimated' (imported as 'Animated').
Done in 284.63s.

### Steps to reproduce

1, Install the library
2. Run the app

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Those imports come from Reanimated API v1. We removed Reanimated 1 API in Reanimated 3. So if you still want to use API v1 you need to stay with Reanimated 2 which will be deprecated soon. That's why I highly recommend an upgrade to Reanimated v2 API
