### ISSUE TITLE
Reanimated becomes  completely unresponsive on Android after time

### ISSUE THREAD

**Issue by ealmiladi** [software-mansion/react-native-reanimated#4434]
### Description

While developing on Android, every once in a while all the animations on the screen (i.e. withTiming, entering, exiting) just completely stop working.  In some cases, the screen goes completely blank. When the animations work, they work great, however I'll leave my emulator running for a while and grab lunch, then come back and all animations in the app are completely broken. Sometimes it happens after 30 seconds, other times 30 minutes.

This issue does not occur on Reanimated 2 and only occurs on Reanimated >= 3. Unfortunately, I'm not able to present a reproducible example for this issue, as it appears at random.

Possibly related to https://github.com/software-mansion/react-native-reanimated/issues/4422, https://github.com/software-mansion/react-native-reanimated/issues/4419, https://github.com/software-mansion/react-native-reanimated/issues/4387.

### Steps to reproduce

1. Can not narrow down reproducible steps.

### Snack or a link to a repository

N/A

### Reanimated version

3.1.0

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by ealmiladi** [comment]
Possibly related to https://github.com/software-mansion/react-native-reanimated/issues/4422.

**Comment by ealmiladi** [comment]
This is still an issue, but I'm unsure of what it's actually related to.

**Comment by lorenc-tomasz** [comment]
I have noticed the same with 3.x. Animation works for some time and then stops

**Comment by chinamcafee** [comment]
I encountered the same problem with 3.x too, when I use animation on react-navigation's initialRoute page, Animation works when I open App first time, but when I killed App and restart it again, animation didn't work.
 I must clean data of my App and open it again, animation did work, but still didn't work after I restart App

But if I don't use animation on react-navigation's initialRoute page, the animation of the same page above will works every time.

**Reanimated version**
3.1.0

**React Native version**
0.71.7

**Comment by piaskowyk** [comment]
@lorenc-tomasz @chinamcafee could you provide any reproduction?

**Comment by ealmiladi** [comment]
I still can't come up with a reproducible example, though it seems to occur when the following exception occurs:

```06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager: Unable to update properties for view tag 4365
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 4365 could not be found.
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:111)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:138)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:281)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.NodesManager.updateProps(NodesManager.java:357)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.nativeProxy.NativeProxyCommon.updateProps(NativeProxyCommon.java:97)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:30)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Handler.handleCallback(Handler.java:942)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Handler.dispatchMessage(Handler.java:99)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Looper.loopOnce(Looper.java:201)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Looper.loop(Looper.java:288)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at android.app.ActivityThread.main(ActivityThread.java:7872)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at java.lang.reflect.Method.invoke(Native Method)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-05 22:56:47.219 15705 15705 E unknown:NativeViewHierarchyManager:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager: Unable to update properties for view tag 4365
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 4365 could not be found.
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:111)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:138)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:281)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.NodesManager.updateProps(NodesManager.java:357)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.nativeProxy.NativeProxyCommon.updateProps(NativeProxyCommon.java:97)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:30)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Handler.handleCallback(Handler.java:942)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Handler.dispatchMessage(Handler.java:99)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Looper.loopOnce(Looper.java:201)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at android.os.Looper.loop(Looper.java:288)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at android.app.ActivityThread.main(ActivityThread.java:7872)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at java.lang.reflect.Method.invoke(Native Method)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-05 22:56:47.222 15705 15705 E unknown:NativeViewHierarchyManager:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by piaskowyk** [comment]
I think I fixed this issue with this PR - https://github.com/software-mansion/react-native-reanimated/pull/4579 If you want you can try the nightly build, or you can wait until next release of reanimated 😃

If you still have this issue in the future feel free to ping me I will reopen issue.

**Comment by Georgio-Saad** [comment]
@ealmiladi Currently facing the same issue on Android, it's driving me insane.

- Reanimated v.3.3.0
- Expo v.49.0.19
- React Native v.0.72.4

Did you manage to solve this issue?

**Comment by joao-lexart** [comment]
> @ealmiladi Currently facing the same issue on Android, it's driving me insane.
> 
> * Reanimated v.3.3.0
> * Expo v.49.0.19
> * React Native v.0.72.4
> 
> Did you manage to solve this issue?

I had the exactly same versions and I have the same error, do you advanced on that? I really need help on this, and can't find similar cases on the forum

**Comment by Georgio-Saad** [comment]
@ealmiladi Unfortunatley i'm unable to upgrade to latest version of reanimated, since i'm limited by the version supported by expo which is 3.3.0

**Comment by olarra** [comment]
> @ealmiladi Currently facing the same issue on Android, it's driving me insane.
> 
>     * Reanimated v.3.3.0
> 
>     * Expo v.49.0.19
> 
>     * React Native v.0.72.4
> 
> 
> Did you manage to solve this issue?

I literally spent a few weeks trying to figure it out where the problem comes from

**Comment by olarra** [comment]
This was totally driving me crazy too. I spend a few weeks debugging animations because behavior was  so much random. I used patch-package to patch react-native-reanimated@3.3.0 because I'm also using expo sdk 49. and I finally have my animations not being canceled 😃 @Georgio-Saad try patching the module.

**Comment by Georgio-Saad** [comment]
@olarra Even after patching and reinstalling etc.. i still had this issue, turns out it was my withRepeat animations running infinitley, after a while (always a random amount i noticed), all animations would break except my interpolate animations,


These interpolate animations would for some reason make all the other animations work again.


What i ended up doing was not using withRepeat on the animations on android and simply keeping it on ios


All is working now, very weird issue.

Happy Coding.

**Comment by joao-lexart** [comment]
> @ealmiladi Unfortunatley i'm unable to upgrade to latest version of reanimated, since i'm limited by the version supported by expo which is 3.3.0

I solved just upgrading manually in package.json to ~3.5.4 and the error didn't came back.

**Comment by hotaryuzaki** [comment]
> > @ealmiladi Unfortunatley i'm unable to upgrade to latest version of reanimated, since i'm limited by the version supported by expo which is 3.3.0
> 
> I solved just upgrading manually in package.json to ~3.5.4 and the error didn't came back.

what is your expo version??

**Comment by Vittor-Javidan** [comment]
> > @ealmiladi Unfortunatley i'm unable to upgrade to latest version of reanimated, since i'm limited by the version supported by expo which is 3.3.0
> 
> I solved just upgrading manually in package.json to ~3.5.4 and the error didn't came back.

How did you upgrade above 3.3.0 exacly? When i do this, using dev client, it says babel plugin do not recognize the package version. It looks like we need a help from expo on this. I'm facing this same issue, and it is the animations bugging for sure. I know this because every other function on my app works fine without getting corrupted, and the animations just not work.

**Comment by Vittor-Javidan** [comment]
I worked on expo dev client, and for me the solution for this issue was to change my package.json file dependencies to:

expo-dev-client: ~3.3.4
react-native-reanimated: ~3.4.0

If the dev client version is too old, the app will not recognize a version newer than 3.3.0 on reanimated, which is the bugged version i suppose.

**Comment by TomasSestak** [comment]
this is real

**Comment by Elue-dev** [comment]
please any solution for this? i am experiencing this in expo sdk 49

**Comment by Elue-dev** [comment]
> atest version of reanimated, since i'm limited by the version supported by expo which is 3.3.0

please how can i do this

**Comment by szydlovsky** [comment]
@Elue-dev you can either upgrade expo sdk (I'd suggest 51) or use [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) to manually manage dependencies' versions.

**Comment by Elue-dev** [comment]
> @Elue-dev you can either upgrade expo sdk (I'd suggest 51) or use [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) to manually manage dependencies' versions.

i upgraded reanimated to 3.4.0 and it was fine after that, thanks
