### ISSUE TITLE
Aplicando debug50, diz que breakpoint não existe já estando add(Vermelho) e a aba Debugger não abre!

### ISSUE THREAD

**Issue by PHenriqueSe** [software-mansion/react-native-reanimated#4435]
### Description

https://user-images.githubusercontent.com/131043351/236901837-34fa046e-8642-47fb-a4c0-d55fcd01b507.mp4

https://user-images.githubusercontent.com/131043351/236901863-636b821d-0a97-427c-8293-be231ad733f9.mp4

Aguardo um retorno para solucionar meu problema. 
Referência minuto 42:14 do vídeo - https://www.youtube.com/watch?v=yvAVgpKW6tY&t=1360s - do curso CS50 IDE - Módulo 02.

Grato, Paulo Henrique!

### Snack or a link to a repository

#include <cs50.h>
#include <stdio.h>

// Protótipo
int get_negative_int(void);

int main(void)
{
// Pega um número inteiro negativo do usuário
int i = get_negative_int();
printf("%i\n",i);
}

int get_negative_int(void)
{
int n;
do
{
n = get_int("Número inteiro negativo: ");
}
enquanto (n <0);
retornar n;
} #include <cs50.h>
#include <stdio.h>

// Protótipo
int get_negative_int(void);

int main(void)
{
// Pega um número inteiro negativo do usuário
int i = get_negative_int();
printf("%i\n",i);
}

int get_negative_int(void)
{
int n;
do
{
n = get_int("Número inteiro negativo: ");
}
enquanto (n <0);
retornar n;
}

### Reanimated version

0.00.0

### React Native version

0.00.0

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

NoteBook Intel I5

### Acknowledgements

Yes

**Comment by PHenriqueSe** [comment]
Fiz uma pequena alteração mas para segurança, segue abaixo o código:

#include <cs50.h>
#include <stdio.h>

// Protótipo
int get_negative_int(void);

int main(void)
{
// Pega um número inteiro negativo do usuário
int i = get_negative_int();
printf("%i\n",i);
}

int get_negative_int(void)
{
int n;
do
{
n = get_int("Número inteiro negativo: ");
}
enquanto (n <0);
retornar n;
} #include <cs50.h>
#include <stdio.h>

// Protótipo
int get_negative_int(void);

int main(void)
{
// Pega um número inteiro negativo do usuário
int i = get_negative_int();
printf("%i\n",i);
}

int get_negative_int(void)
{
int n;
do
{
n = get_int("Número inteiro negativo: ");
}
enquanto (n <0);
retornar n;
}

**Comment by Latropos** [comment]
@PHenriqueSe Bardzo dziękujemy za zgłoszenie problemu, niestety skoro występuje on na platformie webowej ma on dość niski priorytet, tym bardziej że nie wspieramy naszej biblioteki w wersji 0.00.0
