### ISSUE TITLE
Entry & Exit Layout Animations do not work on web

### ISSUE THREAD

**Issue by oparisblue** [software-mansion/react-native-reanimated#4443]
### Description

When creating a view with Entry and Exit layout animations, these run correctly on iOS and Android, however the animations do not play on web.

### Steps to reproduce

1. Add entry / exit layout animations to a view
2. Run the application on iOS or Android and observe that the animations play and trigger their callbacks correctly
3. Run the application on web and observe that the animations do not play and their callbacks are never triggered

The Snack link shows an example of this: you can switch between the different devices at the top, and see the fade in / fade out animation work correctly when pressing the "toggle" button on the device when iOS or Android is selected, but see that the element appears and disappears immediately when running on the web version.

Locally, we're using Expo SDK 48 with Reanimated 2.14.4, so this issue exists back in version 2 as well. Additionally, we do have the Babel plugin installed and as the last line of our babel config.

### Snack or a link to a repository

https://snack.expo.dev/@oparisblue/0892fd

### Reanimated version

3.1.0

### React Native version

0.71.4

### Platforms

Android, iOS, Web

### JavaScript runtime

V8 on web (hermes on mobile devices)

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Target: web, tested on MacBook Pro 16" 2021, macOS 12.6.5, Chrome 112.0

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Thanks for the report! Unfortunately, we haven't been supporting layout animation on the web but soon we want to work on implementing it, so stay tune 🙏
