### ISSUE TITLE
Build error for RN 0.71.7

### ISSUE THREAD

**Issue by one-god** [software-mansion/react-native-reanimated#4463]
### Description

:react-native-reanimated:compileDebugJavaWithJavac FAILED	
/my-app/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/keyboardObserver/ReanimatedKeyboardEventListener.java:67: error: cannot find symbol	
              rootView.getRootView().findViewById(com.swmansion.reanimated.R.id.action_bar_root)	
                                                                            ^	
  symbol:   variable id	
  location: class R	
/my-app/node_modules/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/keyboardObserver/ReanimatedKeyboardEventListener.java:152: error: cannot find symbol	
        getRootView().getRootView().findViewById(com.swmansion.reanimated.R.id.action_bar_root);	
                                                                           ^	
  symbol:   variable id	
  location: class R

### Steps to reproduce

Upgrade to RN 0.71.7
yarn android

### Snack or a link to a repository

N/A

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey! Thanks for the report. Could you tell which Android SDK version do you use?

**Comment by androideveloper** [comment]
Did you bump the AGP plugin to 8.0 or add `-android.nonTransitiveRClass=true` to your gradle properties?
That will enforce non-transitive R class and fail the build. I got the same now when I tried to add the flag to prepare for AGP 8.0 release.

@piaskowyk do you know where `action_bar_root` comes from? 
This should be changed to the real R class usage:
```
com.swmansion.reanimated.R.id.action_bar_root -> {package}.R.id.action_bar_root
```

I assume it's androidx.appcompat.R.id.action_bar_root
