### ISSUE TITLE
[Question] nested procs

### ISSUE THREAD

**Issue by ShaMan123** [software-mansion/react-native-reanimated#447]
It's a bit unclear in the docs if one can nest a proc inside the other.
```ts
const procA = proc((a, b)=>multiply(a, b))
const nestedProc = proc((a, b, c)=>add(c, procA(a, b)))
```

I tried it and some strange things happened, but I'm not sure what's the root cause (#354 | #417 )

**Comment by osdnk** [comment]
Basically it should work  ¯\_(ツ)_/¯

**Comment by ShaMan123** [comment]
hmmm...
I'm not sure what's the problem but could it be memozation?
If I don't nest procs the problem seems to resolve.
However I'm not even sure this is true because I believe that `Fast Refresh` doesn't play nicely with reanimated. Nodes become unresponsive as if they've detached, some stop updating. 
What about procs and `Fast Refresh`? Do procs get reinitialized while the app updates in `__DEV__` mode? This is desirable.

**Comment by ShaMan123** [comment]
It works.
The problem was caused by #417
