### ISSUE TITLE
Android 13, ANR triggered by slow operations in blamed thread #2489

### ISSUE THREAD

**Issue by chaitu14** [software-mansion/react-native-reanimated#4493]
### Description

After performing few actions on bottom sheet or modal app goes to ANR state in android 13 version

OS version: android13
Model:Galaxy Tab S6 Lite
Date:May 25, 2023, 5:23:01 PM

"react-native-reanimated": "^3.1.0",
"react-native-gesture-handler": "2.10.1",
"@gorhom/bottom-sheet": "4.4.6",
"react-native": "0.71.3",
[https://youtu.be/7QKgvF3Zufg](https://github.com/software-mansion/react-native-gesture-handler/issues/2489)
Even after removing the video inside the bottom sheet, my app still goes into an ANR state after some swipe actions. I removed the bottom sheet and used a model, but the same issue persists. However, if I render directly in the view, it works fine.

### Steps to reproduce

The parent view has a root GestureHandlerRootView, and there is a bottom sheet inside it.

When users perform swipe-down or swipe-up gestures or click inside the bottom sheet for certain actions, the app goes into an ANR state with UI deadlock.

Even I removed bottom sheet used modal still same behaviour

### Snack or a link to a repository

https://snack.expo.dev/@chaitanya26/3bdea9

### Reanimated version

2.10.1

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Model:Galaxy Tab A8

### Acknowledgements

Yes

**Comment by chaitu14** [comment]
diff --git a/node_modules/react-native/Libraries/Lists/VirtualizedList.js b/node_modules/react-native/Libraries/Lists/VirtualizedList.js
index e948a85..487533e 100644
--- a/node_modules/react-native/Libraries/Lists/VirtualizedList.js
+++ b/node_modules/react-native/Libraries/Lists/VirtualizedList.js


I fixed this by adding below patch

 const styles = StyleSheet.create({
-  verticallyInverted: {
-    transform: [{scaleY: -1}],
-  },
+
+  verticallyInverted: Platform.OS === 'android'
+  ? {transform: [{ rotate: '180deg' }]}
+  : { transform: [{scaleY: -1}] },
+

**Comment by km5x2** [comment]
> diff --git a/node_modules/react-native/Libraries/Lists/VirtualizedList.js b/node_modules/react-native/Libraries/Lists/VirtualizedList.js index e948a85..487533e 100644 --- a/node_modules/react-native/Libraries/Lists/VirtualizedList.js +++ b/node_modules/react-native/Libraries/Lists/VirtualizedList.js
> 
> I fixed this by adding below patch
> 
> const styles = StyleSheet.create({
> 
> * verticallyInverted: {
> * transform: [{scaleY: -1}],
> * },
> 
> * verticallyInverted: Platform.OS === 'android'
> * ? {transform: [{ rotate: '180deg' }]}
> * : { transform: [{scaleY: -1}] },

This is a bug which I never imagined would even exist. This solved the issue I was facing 🙂. Thanks
