### ISSUE TITLE
Error: Layout: -4486 < 0 

### ISSUE THREAD

**Issue by bunyaminmrcn** [software-mansion/react-native-reanimated#451]
While running Example app I got this error . Others working well. But when i opening
`width & height & more` example  occur `Error: Layout: -4486`  Here is Screenshot . Nothing touched in code
Negative value changes to another ?

![reanimated-1 5 0](https://user-images.githubusercontent.com/30148504/68095552-824dff80-febb-11e9-91ba-6645c123fb5e.png)

**Comment by lake2** [comment]
same issue . How do you fix it?
