### ISSUE TITLE
Reanimated v 3.2.0 has broken withSpring animations

### ISSUE THREAD

**Issue by nicolascavallin** [software-mansion/react-native-reanimated#4510]
### Description

We have created a pin input (like iOS or Android locked screen), so you input your pin and if it's wrong there is a shake animation and reset the pin.

We are using a sequence with `withTiming` and `withSpring`. 

Everything works well with reanimated 3.1.0. After update to 3.2.0

Replacing the `withSpring` animation with `withTiming` the bug doesn't appears.

### With Reanimated v 3.2.0

https://github.com/software-mansion/react-native-reanimated/assets/22961489/0c62a821-4d14-4824-848e-4b08a267027c

### with Reanimated v 3.1.0

https://github.com/software-mansion/react-native-reanimated/assets/22961489/e1236349-15a9-425a-8cd0-c844476f587e

### Steps to reproduce

1. Create a sequence animation that includes `withSpring`
2. Run it

The sequence we are using is:

```
    pinShake.value = withSequence(
      withTiming(20, { duration: 75 }),
      withTiming(-20, { duration: 75 }),
      withTiming(20, { duration: 75 }),
      withSpring(0, { damping: 50, stiffness: 500, mass: 2.8 }, () => runOnJS(resetPin)()),
    );
```

But if we just use `withSpring`(without a sequence) it's also broken.

### Snack or a link to a repository

pending

### Reanimated version

3.2.0

### React Native version

0.71.8

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Thank you for posting this issue! Looks that we have solved, so version 3.2.1 will surely include the fix.
