### ISSUE TITLE
Upgrading 0.72.0-rc.5 with 3.2.0 causes runtime error with metro.

### ISSUE THREAD

**Issue by gtokman** [software-mansion/react-native-reanimated#4521]
### Description

I'm experiencing an error after upgrading RN to `0.72.0-rc.5`. I tried reseting the cache with `yarn start --reset-cache` too.

```
 ERROR  Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
  - not rebuilding the app after installing or upgrading Reanimated
  - trying to run Reanimated on an unsupported platform
  - running in a brownfield app without manually initializing the native library, js engine: hermes
 LOG  Running "mobile" with {"rootTag":1,"initialProps":{}}
 ERROR  Invariant Violation: "mobile" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

<img width="414" alt="CleanShot 2023-06-01 at 12 01 12@2x" src="https://github.com/software-mansion/react-native-reanimated/assets/12258850/6e400f78-8947-406a-b2f4-6122bdb07164">

### Steps to reproduce

1. Create a project with reanimated 3.2.0
2. Upgrade React Native to `0.72.0-rc.5`
3. Run the app

### Snack or a link to a repository

n/a

### Reanimated version

3.2.0

### React Native version

0.72.0-rc.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by thomasarogers** [comment]
Getting the same with react-native 0.71.8 - tried resetting metro cache, clearing node modules, clearing Pods dir and Podfile.lock, clearing derived data and clean build in xcode as well as a machine and phone restart with no luck

**Comment by tomekzaw** [comment]
Hey @gtokman, thanks for reporting this issue. We're actively working on it but adding support for upcoming releases is not that easy these days. Will keep you updated!

**Comment by firehand33** [comment]
I'm still getting this error on 0.72.0 with version 3.3.0....

<img width="650" alt="Screenshot 2023-06-24 at 10 09 05 AM" src="https://github.com/software-mansion/react-native-reanimated/assets/6487857/bccc3520-1ce9-4cd4-b038-09b7c258fe4e">

**Comment by tomekzaw** [comment]
@firehand33 Did you rebuild the native part of the app after upgrading Reanimated?

**Comment by samir-anghan** [comment]
Hi, @tomekzaw Thanks for looking into and working on this.
I'm also getting the same error on the iOS run, Android works fine.

> BUNDLE  ./index.js 
> 
>  ERROR  Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
>   - not rebuilding the app after installing or upgrading Reanimated
>   - trying to run Reanimated on an unsupported platform
>  ERROR  Invariant Violation: "******" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

I have tried everything from the above conversation.
Also, I have tried many times re-building after cleaning the necessary folders. (`rm -rf node_modules ; rm -rf ios/Pods ios/Podfile.lock ios/build`)

iOS iPhone 14, iOS 16.4
`"react-native": "^0.72.0"`
`"react-native-reanimated": "3.3.0"`

**Below is my other dependencies list with versions:**

├── @babel/core@7.22.5
├── @babel/preset-env@7.22.5
├── @babel/preset-typescript@7.22.5
├── @babel/runtime@7.22.5
├── @react-native-community/clipboard@1.5.1
├── @react-native-community/eslint-config@3.2.0
├── @react-native-community/masked-view@0.1.11
├── @react-native-community/netinfo@9.3.10
├── @react-native-community/slider@4.4.2
├── @react-navigation/drawer@6.6.3
├── @react-navigation/elements@1.3.18
├── @react-navigation/native@6.1.7
├── @react-navigation/stack@6.3.17
├── @rnx-kit/align-deps@2.2.2
├── @sentry/react-native@5.6.0
├── @types/jest@29.5.2
├── async-mutex@0.4.0
├── axios@1.4.0
├── babel-jest@29.5.0
├── eslint-config-airbnb@19.0.4
├── eslint-config-prettier@8.8.0
├── eslint-plugin-import@2.27.5
├── eslint-plugin-jsx-a11y@6.7.1
├── eslint-plugin-node@11.1.0
├── eslint-plugin-prettier@4.2.1
├── eslint-plugin-promise@6.1.1
├── eslint-plugin-react-native@4.0.0
├── eslint-plugin-react@7.32.2
├── eslint@8.42.0
├── i18next@23.2.3
├── jest@29.5.0
├── lodash.debounce@4.0.8
├── metro-react-native-babel-preset@0.76.6
├── moment@2.29.4
├── query-string@8.1.0
├── react-i18next@13.0.1
├── react-native-barcode-mask@1.2.4
├── react-native-camera@4.2.1
├── react-native-circular-progress@1.3.9
├── react-native-collapsible@1.6.1
├── react-native-color-picker@0.6.0
├── react-native-device-info@10.6.0
├── react-native-draggable-flatlist@4.0.1
├── react-native-fs@2.20.0
├── react-native-gesture-handler@2.12.0
├── react-native-gradle-plugin@0.71.19
├── react-native-haptic-feedback@2.0.3
├── react-native-linear-gradient@2.7.3
├── react-native-localize@3.0.1
├── react-native-mail@6.1.1
├── react-native-maps@0.30.2
├── react-native-prompt-android@1.1.0
├── react-native-raw-bottom-sheet@2.2.0
├── react-native-reanimated@3.3.0
├── react-native-safe-area-context@4.6.3
├── react-native-screens@3.22.0
├── react-native-splash-screen@3.3.0
├── react-native-sqlite-storage@6.0.1
├── react-native-svg@13.9.0
├── react-native-testing-library@6.0.0
├── react-native-text@1.2.2
├── react-native-vector-icons@9.2.0
├── react-native-webview@13.2.2
├── react-native@0.72.0
├── react-navigation@4.4.4
├── react-test-renderer@18.2.0
├── react@18.2.0
├── realm@11.10.1
├── redux-persist-sqlite-storage@1.0.4
├── styled-components@5.3.11
└── webdriverio@8.11.2

**Pods > Developement Pods > RNReanimated:**

![image](https://github.com/software-mansion/react-native-reanimated/assets/25671636/0f4311d5-4150-4f7b-bf6c-52983d29b2ce)

I have also tried using various combinations of previous react-native versions along with earlier versions of react-native-reanimated. Nothing worked.

Do you see anything here that is causing the error? Let me know if you need any other details of my react-native configuration. Thanks in advance.

**Comment by efstathiosntonas** [comment]
@samir-anghan maybe a long shot but can you add this in your `android/app/build.gradle`:

```
project.ext.reanimated = [
        buildFromSource: true
]
```

right under the 

```
project.ext.react = [
…
]
```

**Comment by samir-anghan** [comment]
@efstathiosntonas Thanks for the suggestion, tried it but did not work.

**Comment by efstathiosntonas** [comment]
@samir-anghan did you tried running metro bundler with `—reset-cache` trigger?

**Comment by samir-anghan** [comment]
@efstathiosntonas Yes, tried, but unfortunately, none of these helped - clearing metro cache, clearing node modules, clearing Pods folder and deleting Podfile.lock, clearing derived data and running the clean build in Xcode :(

 Tried everything that I could think of. Any further suggestions are appreciated.

**Comment by tomekzaw** [comment]
Hey @samir-anghan, I've tried to reproduce the problem but it works for me. Here's what I did:

```
npx react-native@next init MyApp --version 0.72.0 --skip-install
cd MyApp
yarn add react-native-reanimated@3.3.0
cd ios
pod install
cd ..
# overwrite App.tsx with https://raw.githubusercontent.com/software-mansion/react-native-reanimated/main/app/src/examples/BokehExample.tsx
# add `plugins: ['../plugin'],` in babel.config.js
open ios/MyApp.xcworkspace
# build the app in Xcode
```

I'm afraid this problem might be specific to your application.

**Comment by niranjan2210** [comment]
> Hey @samir-anghan, I've tried to reproduce the problem but it works for me. Here's what I did:
> 
> ```
> npx react-native@next init MyApp --version 0.72.0 --skip-install
> cd MyApp
> yarn add react-native-reanimated@3.3.0
> cd ios
> pod install
> cd ..
> # overwrite App.tsx with https://raw.githubusercontent.com/software-mansion/react-native-reanimated/main/app/src/examples/BokehExample.tsx
> # add `plugins: ['../plugin'],` in babel.config.js
> open ios/MyApp.xcworkspace
> # build the app in Xcode
> ```
> 
> I'm afraid this problem might be specific to your application.

I am also having this error in my app.

**Comment by tapz** [comment]
I upgraded from 2.14.4 to 3.3.0 and am now seeing this error. How exactly should the native part be initialized? Should I call something in AppDelegate?

**Comment by tomekzaw** [comment]
@tapz It should be installed automatically, at least it works this way in a fresh RN 0.72.0 app. Do you have some custom native code (like AppDelegate written in Swift) or something like this?

**Comment by felipegmg** [comment]
same issue here!

**Comment by artemis-prime** [comment]
This seems to be fixed with the combo of RN 0.72.x and RNR 3.4.x  (So no need to mess with AppDelegate files)

NOTE: Remember to do `pod install` and also to start metro with --reset-cache to pick up the new version of the babel plugin

**Comment by NewvilleMedia** [comment]
Any fix to this?

**Comment by rustyonrampage** [comment]
Still getting this issue for android (could be for IOS as well, havent checked cuz running windows).  
"react": "18.2.0",
"react-native": "0.72.4",
"react-native-reanimated": "^3.5.4"

**Comment by kulbir22** [comment]
> Still getting this issue for android (could be for IOS as well, havent checked cuz running windows). "react": "18.2.0", "react-native": "0.72.4", "react-native-reanimated": "^3.5.4"

I too have same configuration and same issue..

**Comment by tomekzaw** [comment]
# Solution


1. Bump `react-native-reanimated` to 3.6.0
2. (iOS only) Reinstall pods: `cd ios && pod install && cd ..`
3. Rebuild your native app: `yarn react-native run-ios`
