### ISSUE TITLE
ReferenceError: Can't find variable: React

### ISSUE THREAD

**Issue by vancerbtw** [software-mansion/react-native-reanimated#4531]
### Description

I just upgraded to reanimated 2 from 3.1.0 to 3.2.0. The Animated.ScrollView now errors "ReferenceError: Can't find variable: React".

I changed
import { ForwardedRef, forwardRef, RefObject } from 'react';
to
import React, { ForwardedRef, forwardRef, RefObject } from 'react'; 

The error no longer persists with this change.

I can try to open a repository if needed.

### Steps to reproduce

I am not quite sure

### Snack or a link to a repository

n/a

### Reanimated version

3.2.0

### React Native version

0.68.2

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by mrtawil** [comment]
Same here

**Comment by tomekzaw** [comment]
Hey @vancerbtw, thanks for reporting this issue! Would you be so kind to submit a PR with this change?

**Comment by vancerbtw** [comment]
I am unfortunately on vacation right now. The problematic file is located at: "react-native-reanimated/src/reanimated2/component/ScrollView.tsx"

**Comment by tomekzaw** [comment]
Should be fixed with #4532.
