### ISSUE TITLE
React native - 0.71.8.  React reanimated - 3.2.0 error when put newArchEnabled to true in gradle

### ISSUE THREAD

**Issue by davidgvf** [software-mansion/react-native-reanimated#4535]
### Description

[Error](react-native-reanimated:assertLatestReactNativeWithNewArchitectureTask)

![image](https://github.com/software-mansion/react-native-reanimated/assets/62423420/4534dee2-76c7-49a4-acc2-bf44ef20c66a)

### Steps to reproduce

Put in gradle.properties newArchEnabled to true and start aplication

### Snack or a link to a repository

s

### Reanimated version

3.2.0

### React Native version

0.71.8

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by matteodanelli** [comment]
The issue is the following:
```
react-native-reanimated/android/build.gradle' line: 626

* What went wrong:
Execution failed for task ':react-native-reanimated:assertLatestReactNativeWithNewArchitectureTask'.
> 
  [react-native-reanimated] Reanimated 3.2.0 supports the New Architecture only on the latest minor release of React Native. Please upgrade to React Native 0.72.0+ or downgrade to an older version of Reanimated v3.

```

WTH is the reason to support ONLY an unreleased versione of ReactNative?!
0.72 is still in RC

**Comment by tomekzaw** [comment]
> WTH What is the reason to support ONLY an unreleased version of ReactNative?!
> 0.72 is still in RC

Since Fabric is experimental, we only support one most recent version of React Native. There were some major changes to be done in order to add support for 0.72-rc so we decided to drop support for 0.71 to avoid spoiling our code with weird conditionals. Obviously, you can use an earlier release (like 3.1.0) and it will work just fine.

**Comment by anisurrahman072** [comment]
Does it mean, i need to upgrade my project to 0.72?

**Comment by sagarjeu** [comment]
for "react-native": "0.71.13",
New Arch = true

Execution failed for task ':react-native-reanimated:assertLatestReactNativeWithNewArchitectureTask'.

[react-native-reanimated] Reanimated 3.1.0 supports the New Architecture only on the latest minor release of React Native. Please upgrade to React Native 0.72.0+ or downgrade to an older version of Reanimated v3.

**Comment by vyasdarshan** [comment]
Upgraded the 
`"react-native-reanimated": "^3.13.0" `
to 
`"react-native-reanimated": "^3.14.0",`

My React-native Version is 
`"react-native": "0.72.6",`
