### ISSUE TITLE
deprecated  componentWillReceiveProps 

### ISSUE THREAD

**Issue by gharsallahmoez** [software-mansion/react-native-reanimated#454]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

Please update the following components: withAnimatable(Component)

any help?

**Comment by felippepuhle** [comment]
This warning is not from `react-native- reanimated`, it's from `react-native-animatable`.

I suppose you're using `react-native-dialog` or an old version of `react-native-modal`.
`react-native-modal` uses `react-native-animatable` under the hood.

They already handled  this warning(https://github.com/oblador/react-native-animatable/blob/master/createAnimatableComponent.js#L329), but they'll need to get rid of `componentWillReceiveProps` soon.

I think we can close this issue.

Thanks!

**Comment by jakub-gonet** [comment]
Thanks @felippepuhle for the detailed explanation!

I'm closing it now, but if you need further clarification let me know.
