### ISSUE TITLE
JSI-related Xcode build errors upon installation of 2.14.4 (Brownfield)

### ISSUE THREAD

**Issue by henrygrant** [software-mansion/react-native-reanimated#4543]
### Description

Hi there! 

A feature team at my organization requested that we add this library to our project, but upon installation I'm getting build failures. I'm a bit stumped on what the issue may be.

Unfortunately I can't share the repository, but I can give you some context. We are migrating from two separate native apps to  one React Native app, but are currently operating with a React Native instance set up inside the native app. The directory structure looks something like 

```
MyProject/
  MyApp/
    ReactNative/
      ReactNative.h
      ReactNative.m
      ReatNativeManager.swift
      ReactNativeManagerBridge.m
      ReactNativeViewController.swift
      main.jsbundle
    NativeFeature/
      ...
    ...
  package.json
  package-lock.json
  babel.config.js
  react-native-config.js
  index.js
  metro.config.js
```

My Podfile looks something like this:
```
ENV['RCT_NEW_ARCH_ENABLED'] = '0';

# source react native scripts from node_modules
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'MyProject.xcodeproj'
source 'https://github.com/LivePersonInc/iOSPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, min_ios_version_supported
prepare_react_native_project!
inhibit_all_warnings!
use_frameworks!

def myReactNative_pods
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )
end

def foundation_pods
    pod 'SomePod'

end

def shared_pods
    foundation_pods
    pod 'LPMessagingSDK'
    pod 'SwiftLint'
    pod 'lottie-ios'
    pod 'Firebase/Analytics'
    pod 'FBSDKCoreKit'
    pod 'AdobeMobileSDK'
    pod 'HorizonCalendar'
    pod 'Plaid'
    pod 'AWSMobileClient'
    pod 'AWSPinpoint'
    myReactNative_pods
end

target 'MyApp' do
    shared_pods
end
```

We currently have Hermes enabled and Fabric disabled, new architecture disabled, and use `use_frameworks!` in our podfile. 

`npm install` and `pod install` run clean, but upon trying to build in Xcode I get a lot of jsi-related `Undefined Symbol` errors. 

![Screenshot 2023-06-06 at 8 52 24 PM](https://github.com/software-mansion/react-native-reanimated/assets/12072806/4d8cc1d6-d5bc-4f40-91f0-c29c29513f26)

I'm having trouble finding anything here or elsewhere that is similar to this issue, though after reading your installation guide I see that it is probably related to our brownfield implementation of React Native. 

I'll also note that I tried updating to `3.2.0` with the same results, which makes me think this is a configuration problem. 

### Steps to reproduce

npm install
pod install
xcode build

### Snack or a link to a repository

None

### Reanimated version

2.14.4

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

Iphone 14 Pro

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @henrygrant, thanks for reporting this problem.

Could you please check if #4504 resolves your issue?

Also, I would recommend using Reanimated 3.2.0 instead of v2 which is no longer actively supported.

**Comment by henrygrant** [comment]
This worked! Thank you @tomekzaw
