### ISSUE TITLE
RCTAppDelegate.h file not found

### ISSUE THREAD

**Issue by thanhloc-17** [software-mansion/react-native-reanimated#4553]
### Description

I install nightly version (**3.3.0-nightly-20230608-2426f3209**) with React Native **0.72.0-rc.5**, it work well on android, but when build on IOS, i meet the issue as below:

<img width="850" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/20339875/07cc0782-1b57-43ca-8f0e-c566320caa03">

I use Expo Module with my Podfile:
```
...
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Test' do
  
  $RNFirebaseAsStaticFramework = true

  use_expo_modules!
  config = use_native_modules!
 
  use_frameworks! :linkage => :static # for Firebase

  # Flags change depending on the env values.
  flags = get_default_flags()

  pod 'FBSDKLoginKit'
  # pod 'RNFS', :path => '../node_modules/react-native-fs'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    #
    # Uncomment to opt-in to using Flipper
    # Note that if you have use_frameworks! enabled, Flipper will not work
    :flipper_configuration => FlipperConfiguration.disabled,
  )
...
```

### Steps to reproduce

yarn add react-native-reanimated@nightly
npx pod-install
npx react-native run-ios

### Snack or a link to a repository

none

### Reanimated version

3.3.0-nightly-20230608-2426f3209

### React Native version

0.72.0-rc.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @thanhloc-17, thanks for submitting this issue.

I've tried to reproduce the error on a fresh `react-native@0.72.0-rc.5` with `react-native-reanimated@3.3.0-nightly-20230608-2426f3209` but it works fine for me. I suspect that this issue might be related to Expo modules which come with `EXAppDelegateWrapper` which extends `RCTAppDelegate`.

When I try to install Expo modules automatically with `npx install-expo-modules@latest`, I get the following error:
```
Uncaught Error Error: Unable to find compatible expo sdk version - reactNativeVersion[0.72.0-rc.5]
```

Could you please paste the output of `cd ios && find . -name "RCTAppDelegate.h"`? Mine is
```
➜  MyApp cd ios && find . -name "RCTAppDelegate.h"
./Pods/Headers/Public/React-RCTAppDelegate/RCTAppDelegate.h
./Pods/Headers/Private/React-RCTAppDelegate/RCTAppDelegate.h
```

**Comment by hiagolfMB** [comment]
@tomekzaw 
I do not use Expo but I am getting the same error.

Nothing is returning by the command:
`cd ios && find . -name "RCTAppDelegate.h"`

**Comment by thanhloc-17** [comment]
@tomekzaw, thanks for your reply
I try to run command: 
`cd ios && find . -name "RCTAppDelegate.h"` -> There is nothing

I install the latest version of Expo Module and it work well without Reanimated.

**Comment by tomekzaw** [comment]
Thanks @thanhloc-17, what about `cd ios && find . -name "AppDelegate.h"`?

**Comment by MicroDroid** [comment]
@tomekzaw for me it's:

```
./<target>/AppDelegate.h
```

**Comment by thanhloc-17** [comment]
@tomekzaw, there is a result from this command.
`cd ios && find . -name "AppDelegate.h"`
=> `./{AppName}/AppDelegate.h`

**Comment by tomekzaw** [comment]
That's really weird. Are you sure that your app is compliant with React Native 0.72.0-rc.5 app template? Would be great if someone could provide a repro so we can investigate it further.

**Comment by MicroDroid** [comment]
I don't know about the template, but I'm pretty sure I followed the upgrade instructions by the upgrade helper every single time

**Comment by thanhloc-17** [comment]
@tomekzaw, I sure that I followed the upgrade helper of React Native and expo-template,
You can find the template at link https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum

**Comment by tomekzaw** [comment]
@thanhloc-17 and @MicroDroid thanks for your cooperation, finally I was able to reproduce the issue, indeed there's some mismatch of header files when using `use_frameworks! :linkage => 'static'`, here's a patch that works for me, hopefully it will work for you as well: #4558

**Comment by cmit-emrekorpe** [comment]
The content of your pod file should be like this
`# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'YOURPROJECTNAME' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'YOURPROJECTNAMETests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

`

**Comment by EmreKorpe** [comment]
The content of your pod file should be like this

`require Pod::Executable.execute_command('node', ['-p',
'require.resolve(
"react-native/scripts/react_native_pods.rb",
{paths: [process.argv[1]]},
)', dir]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym
end

target 'YOURPROJECTNAME' do
config = use_native_modules!

flags = get_default_flags()

use_react_native!(
:path => config[:reactNativePath],
:hermes_enabled => flags[:hermes_enabled],
:fabric_enabled => flags[:fabric_enabled],
:flipper_configuration => flipper_config,
:app_path => "#{Pod::Config.instance.installation_root}/.."
)

target 'YOURPROJECTNAMETests' do
inherit! :complete
end

post_install do |installer|
react_native_post_install(
installer,
config[:reactNativePath],
:mac_catalyst_enabled => false
)
__apply_Xcode_12_5_M1_post_install_workaround(installer)
end
end

`

**Comment by EmreKorpe** [comment]
> The content of your pod file should be like this
> 
> `require Pod::Executable.execute_command('node', ['-p', 'require.resolve( "react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]}, )', dir]).strip
> 
> platform :ios, min_ios_version_supported prepare_react_native_project!
> 
> flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
> 
> linkage = ENV['USE_FRAMEWORKS'] if linkage != nil Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green use_frameworks! :linkage => linkage.to_sym end
> 
> target 'YOURPROJECTNAME' do config = use_native_modules!
> 
> flags = get_default_flags()
> 
> use_react_native!( :path => config[:reactNativePath], :hermes_enabled => flags[:hermes_enabled], :fabric_enabled => flags[:fabric_enabled], :flipper_configuration => flipper_config, :app_path => "#{Pod::Config.instance.installation_root}/.." )
> 
> target 'YOURPROJECTNAMETests' do inherit! :complete end
> 
> post_install do |installer| react_native_post_install( installer, config[:reactNativePath], :mac_catalyst_enabled => false ) __apply_Xcode_12_5_M1_post_install_workaround(installer) end end
> 
> `

after pod-install
