### ISSUE TITLE
Can't find variable: queueMicrotask after upgrading to v3.2.0 (Android)

### ISSUE THREAD

**Issue by rayjackson13** [software-mansion/react-native-reanimated#4559]
### Description

After upgrading react-native-reanimated from v2.14.4 to v3.2.0 and running `react-native run-android`, the app throws an exception on launch with the following message:

> Error: Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: ReferenceError: Can't find variable: queueMicrotask

![Screenshot_20230612_120005](https://github.com/software-mansion/react-native-reanimated/assets/19687202/37ef1070-b64a-4d87-9536-0599aa86e3f7)

OS: Android 13

### Steps to reproduce

1. Install react-native-reanimated v2.14.4 to a sample project
2. Run project, everything should work fine
3. Upgrade to v3.2.0
4. Run project

### Snack or a link to a repository

https://snack.expo.dev/@kostya.kononov/reanimated-3-2-0-issue

### Reanimated version

3.2.0

### React Native version

0.64.4

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @rayjackson13, thanks for submitting the issue. I'm afraid we no longer support React Native 0.64.4, can you please check if the problem occurs on some newer version like 0.71.10?

**Comment by sleaper** [comment]
I have the same issue on React native 0.71.11 and react-native-reanimated v3.3.0

**Comment by LeNgoc82** [comment]
same issue,

**Comment by scottgrunerud** [comment]
I am also having the same issue `ReferenceError: Property 'queueMicrotask' doesn't exist`

**Comment by piaskowyk** [comment]
It seems like cache issue 🤔 Did you try to run `yarn start --reset-cache` ?

**Comment by sleaper** [comment]
> It seems like cache issue 🤔 Did you try to run `yarn start --reset-cache` ?

Nope, will try.

**Comment by scottgrunerud** [comment]
I actually managed to solve this for me by using the following dependency versions:

```
  "react-native": "^0.65.1",
  "react-native-gesture-handler": "1.9.0",
  "react-native-reanimated": "^2.3.1",
```

Hope this helps someone!

**Comment by LeNgoc82** [comment]
> I actually managed to solve this for me by using the following dependency versions:
> 
> ```
>   "react-native": "^0.65.1",
>   "react-native-gesture-handler": "1.9.0",
>   "react-native-reanimated": "^2.3.1",
> ```
> 
> Hope this helps someone!

Thanks for your comment.
My RN ver is 0.65.2
xcode 14.2 (From 14.3 I downgraded but not works)

I reinstall "react-native-gesture-handler": "1.9.0", with exact version as you said 
And It works for both android and ios
one again, many thanks

**Comment by mateusmatosleonardo** [comment]
> Na verdade, consegui resolver isso para mim usando as seguintes versões de dependência:
> 
> ```
>   "react-native": "^0.65.1",
>   "react-native-gesture-handler": "1.9.0",
>   "react-native-reanimated": "^2.3.1",
> ```
> 
> Espero que isso ajude alguém!

Thank you friend. This solved my problem!

**Comment by janziemba** [comment]
For anyone struggling with this, I have 'fixed' it using `queueMicrotask` [pollyfill](https://github.com/zloirock/core-js#queuemicrotask). I put this at the top of the main index.js:
```
import 'core-js/actual/queue-microtask';
```

```
"expo": "~49.0.6",
"react-native": "0.72.3",
"react-native-gesture-handler": "~2.12.0",
"react-native-reanimated": "~3.3.0",
```

**Comment by m-bert** [comment]
Hi @LeNgoc82! We are aware of this issue in `react-native-gesture-handler`. Since you said that downgrading it helped, could you please check if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2612) helps?

**Comment by m-bert** [comment]
Okay, I think it is safe to assume that [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2612) fixed that problem.

If that's not the case, feel free to reopen it.
