### ISSUE TITLE
`diff(node)` returns difference only from its last 😵own evaluation

### ISSUE THREAD

**Issue by yairopro** [software-mansion/react-native-reanimated#456]
Hello

First of all, thank you so much for this **AMAZING** library ! Really

Now get down to business 😁

I don't know if you consider the following as a bug.
When I see the ```diff``` operator, I think "_Oh cool ! With this operator, I can know if a value has changed **since last frame**_".
But clearly that's not what it does.😭 It's **not** from the last frame, but **from last evaluation of the node itself, the ```diff``` one**, not the parameter one. Which leads to bug when you wish to use this inside a ```cond``` of the same node you make a ```diff``` on.

[Here's a snack](https://snack.expo.io/@yairopro/reanimated-diff-issue) where I evaluate the diff inside a ```cond```. You will be able to see the use of a ```diff``` node before a ```cond```and from inside the ```cond```. And when inside the ```cond```, it never change.

**Comment by osdnk** [comment]
Hey,
It's expected behavior 😄. If you need to know the difference between current value and value from the previous frame, you should not rely on it.

**Comment by wcandillon** [comment]
@osdnk is correct. If you want the diff for every frame

```
const dx = new Value(0);
useCode(() => set(dx, diff(x)), []);
```
