### ISSUE TITLE
Unable to find a specification for `React-hermes` depended upon by `RNReanimated` after update 3.3.0

### ISSUE THREAD

**Issue by lym3074** [software-mansion/react-native-reanimated#4562]
### Description

I was experiencing an error with worklets. I upgraded to version 3.3.0, which was supposed to fix it, but I'm still encountering the following error.

### Steps to reproduce

1. npm install
2. pod install
->
[!] Unable to find a specification for `React-hermes` depended upon by `RNReanimated`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

### Snack or a link to a repository

none

### Reanimated version

3.3.0

### React Native version

0.70.8

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by lym3074** [comment]
in addition, "pod install" with a different version, the same error does not occur.

**Comment by tomekzaw** [comment]
Hey @lym3074, thanks for submitting this issue. Can you please check if the following commands work for you?

```
cd ios
rm -rf Pods Podfile.lock build
pod install
```

**Comment by sohail232** [comment]
Same issue on my side

**Comment by lym3074** [comment]
> Hey @lym3074, thanks for submitting this issue. Can you please check if the following commands work for you?
> 
> ```
> cd ios
> rm -rf Pods Podfile.lock build
> pod install
> ```

thanks for your comment :)
before writing the post, I had executed related tasks in the Podfile. but still didn't work.

whoever when i changed ' :hermes_enabled => true ' in Podfile, 'pod install' was worked.
but occurred another issues. because i'm not using the hermes engine.

Do I have to use the Hermes engine?

**Comment by tomekzaw** [comment]
@lym3074 It's up to you, Reanimated works with JSC as well. You'll simply need to run `USE_HERMES=0 pod install` or  just need to set `ENV['USE_HERMES'] = '0'` in your Podfile (recommended).

**Comment by lym3074** [comment]
> @lym3074 It's up to you, Reanimated works with JSC as well. You'll simply need to run `USE_HERMES=0 pod install` or just set `ENV['USE_HERMES'] = '0'` in your Podfile (recommended).

Both options works in my project. thank you. :)

**Comment by cKurultayKalkan** [comment]
Same here. Unfortunately solved with ENV['USE_HERMES'] = '0' .  Thanks @tomekzaw

**Comment by chj-damon** [comment]
I'm using react-native 0.66.5 and facing the same problem. for sure change `:hermes_enabled => true` solved this problem, but I don't want to enable hermes on IOS. any way that I can do to fixed this problem with `:hermes_enabled =>false` ? @tomekzaw

**Comment by tomekzaw** [comment]
@chj-damon You can literally paste `ENV['USE_HERMES'] = '0'` at the beginning of your Podfile.

**Comment by sevensSolver** [comment]
> @lym3074 It's up to you, Reanimated works with JSC as well. You'll simply need to run `USE_HERMES=0 pod install` or just set `ENV['USE_HERMES'] = '0'` in your Podfile (recommended).

set `ENV['USE_HERMES'] = '0' , It is worked for me , Thanks a lot.

**Comment by harisbaig100** [comment]
If you encounter version dependency errors after updating React Native, ensure to update dependent libraries accordingly. For instance, if your project relies on RNReanimated, navigate to its npm page, review each version's peer dependencies, and install the compatible version. Following these steps will resolve the error seamlessly.

**Comment by mehuljetani** [comment]
**Solution:**
To resolve this, I ran the following command:

    USE_HERMES=0 pod install

Alternatively, you can set it directly in your Podfile by adding:

    ENV['USE_HERMES'] = '0'
This allowed me to proceed without issues.
