### ISSUE TITLE
app crashed with react native reanimated and react native gesture handler 

### ISSUE THREAD

**Issue by AzadMohammadi-z** [software-mansion/react-native-reanimated#4565]
### Description

when install package react-native-reanimated(v2) and react native-gesture-handler together app crashed

### Steps to reproduce

"react-native": "0.70.6",
 gradle:  gradle-7.5.1
 buildToolsVersion = "33.0.0"
 minSdkVersion = 21
 compileSdkVersion = 33
 targetSdkVersion = 33

### Snack or a link to a repository

https://github.com/AzadMohammadi-z/optimaPlus

### Reanimated version

2.17.0

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
@AzadMohammadi-z Hi! Did you forget to attach link to some repro? You link redirects me to your githhub page instead.
