### ISSUE TITLE
Flatlist support

### ISSUE THREAD

**Issue by achrafKara** [software-mansion/react-native-reanimated#457]
I wanted to use an animated Flatlist to extract the scroll offset and use it to hide and show my header,
but i got an error: 
`Invariant violation: element type is invalid: expect a string or class/function but got undefined.`

```
import React from 'react';
import {Text, View, Button} from 'react-native';
import Animated from 'react-native-reanimated';

const Screen= props=> {

		return (
			<View>
				<Button
					title= "Go back"
					onPress= {() => props.navigation.goBack()}
				/>
				<Text>This is the Test screen</Text>
				<Animated.Flatlist />	
			</View>
		);
}

Screen.navigationOptions = ({navigation}) => {
	return {title: 'Test'}
}

export default Screen;
```
Any suggestion it doesn't work with Flatlist, knowing that if i change Animatet.Flatlist to Animated.Scrollview it works.

**Comment by ShaMan123** [comment]
pass prop [`renderScrollComponent`](https://facebook.github.io/react-native/docs/listview#renderscrollcomponent)

**Comment by achrafKara** [comment]
ShaMan123 
These are the props i pass to my flatlist:
`<Animated.FlatList 
			scrollEventThrottle= {16}
			onScroll= {Animated.event(
				[
					{nativeEvent: {contentOffset:{y: scrollY}}}
				],
				{ useNativeDriver: true }
			)}
			style= {{paddingHorizontal: 15, paddingTop: 70}}
			contentContainerStyle= {{paddingBottom: 75}}
			bounces= {false}
			alwaysBounceVertical= {false}
			data= {names}
			renderItem= {({item})=> 
				<View style= {{paddingVertical: 10, marginBottom: 10}}>
				<Text>{item}</Text>
				</View>
			}
			keyExtractor= {item=> item}
			/>`

Do i need to pass renderScrollComponent

**Comment by ShaMan123** [comment]
try passing all scroll related props through `renderScrollComponent`:
```ts

<FlatList 
  {..props}
  renderScrollComponent={(props) => <ScrollView {...props} {...moreProps} />}
/>
```

**Comment by jakub-gonet** [comment]
Hi @achrafKara,
did the solution presented by @ShaMan123 solve your issue?

**Comment by achrafKara** [comment]
@jakub-gonet  yes it did

**Comment by nandorojo** [comment]
I'd like to reopen this.

While using the `renderScrollComponent` _does_ work, it doesn't allow all props to work.

If you use the `renderScrollComponent` with an `onScroll` prop for the `Animated.ScrollView`, the `onViewableItemsChanged` callback never fires after the first time when the component mounts.

```jsx
import * as React from 'react'
import { FlatList, Dimensions } from 'react-native'
import Animated from 'react-native-reanimated'
import { onScroll } from 'react-native-redash'

export default () => {
  const itemHeight = Dimensions.get('window').height
  return (
    <FlatList
        data={data}
        renderItem={renderItem}
        keyExtractor={(_, index) => index.toString()}
        renderScrollComponent={props => (
          <Animated.ScrollView
            {...props}
               // 👇if you comment this in, onViewableItemsChanged won't fire.
               // onScroll={onScroll({ y: feedScroll })}
               // 👇same goes if you comment this in
               // onScroll={() => null} 
             />
         )}
        pagingEnabled
        getItemLayout={(_, index) => {
          return {
            length: itemHeight,
            index,
            offset: index * itemHeight
          };
        }}
        showsVerticalScrollIndicator={false}
        onViewableItemsChanged={console.log} // only logs the first time 
        viewabilityConfig={viewabilityConfig}
      />
  )
}

const viewabilityConfig = {
  itemVisiblePercentThreshold: 80
};
```

**Comment by yairopro** [comment]
@nandorojo  It seems that's because you overwrite the default `props.onScroll` set by the FlatList itself, which allows it to know when to trigger `onViewableItemsChanged`.

<img width="793" alt="Screen Shot 2020-04-20 at 14 50 47" src="https://user-images.githubusercontent.com/8110568/79748829-ba84b580-8316-11ea-9ea9-bf3158dc2e05.png">

**Comment by nandorojo** [comment]
Not sure why I didn't think of this sooner. I haven't tried this since I moved on from this project, but I have a feeling this will fix it:

```jsx
import * as React from 'react'
import { FlatList, Dimensions } from 'react-native'
import Animated from 'react-native-reanimated'
import { onScroll } from 'react-native-redash'

export default () => {
  const itemHeight = Dimensions.get('window').height
  return (
    <FlatList
      data={data}
      renderItem={renderItem}
      keyExtractor={(_, index) => index.toString()}
      renderScrollComponent={(props) => (
        <Animated.ScrollView
          {...props}
          onScroll={(event) => {
            onScroll({ y: feedScroll })(event)
            props.onScroll(event)
          }}
        />
      )}
      pagingEnabled
      getItemLayout={(_, index) => {
        return {
          length: itemHeight,
          index,
          offset: index * itemHeight
        }
      }}
      showsVerticalScrollIndicator={false}
      onViewableItemsChanged={console.log} // only logs the first time
      viewabilityConfig={viewabilityConfig}
    />
  )
}

const viewabilityConfig = {
  itemVisiblePercentThreshold: 80
}
```

**Comment by yairopro** [comment]
@nandorojo that's right.

**Comment by denisdenes** [comment]
@nandorojo just a small typo, i think you meant to import `import { onScrollEvent } from "react-native-redash"` and then use it like this

```
renderScrollComponent={(props) => (
  <Animated.ScrollView
    {...props}
    onScroll={(event) => {
      onScrollEvent({ y: feedScroll })
      props.onScroll(event)
    }}
  />
)}
```

**Comment by MkNiloufar** [comment]
I didn't manage to work with flatList using these solutions. any update?

**Comment by MkNiloufar** [comment]
@denisdenes What is the y value?

**Comment by denisdenes** [comment]
@MkNiloufar the y value will be a float number that depends on the vertical scroll position

**Comment by Stevemoretz** [comment]
I have a question
`
renderScrollComponent={props => (
          <Animated.ScrollView
`
Wouldn't this essentially convert the flatlist to a scrollview and kill all its nice features? eg : would render all the items even if not visible?

**Comment by yairopro** [comment]
`renderScrollComponent` is a prop the `FlatList` inherits from `VirtualizedList` and it doesn't override the prop. So the `` basically uses its default scroll component which is a simple ``:

**Comment by Simranjeetnayol** [comment]
Hi everyone,
There is alternative solution to use **Animated FlatList** in **react-native-reanimated v2.0.0**. 

import React from 'react';
import {View, Image, FlatList, StyleSheet} from 'react-native';
import Animated, {
  useAnimatedScrollHandler,
  useSharedValue,
} from 'react-native-reanimated';

import {StatusBarHeight, Stylebase} from '../../Constants/Stylebase';
import RenderItems from './RenderItem';

const data = [...Array(30).keys()].map((_, i) => {
  return {
    key: Math.random().toString(36).slice(2),
    image: `https://randomuser.me/api/portraits/women/${Math.floor(
      Math.random() * 100,
    )}.jpg`,
    jobtitle: Math.random().toString(36).slice(2),
    email: Math.random().toString(36).slice(2),
  };
});

const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);

const backgroundImage =
  'https://i.pinimg.com/originals/73/7d/01/737d014f201a5cd79257dd313e09b7d7.jpg';

function FirstAnimation() {
  const onScrollY = useSharedValue(0);

  const scrollHandler = useAnimatedScrollHandler(event => {
    onScrollY.value = event.contentOffset.y;
  });

  return (
    <View style={Stylebase.flex1}>
      <Image
        source={{uri: backgroundImage}}
        style={StyleSheet.absoluteFillObject}
        blurRadius={50}
      />
      <AnimatedFlatList
        data={data}
        keyExtractor={item => item.key}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{
          alignItem: 'center',
          paddingTop: StatusBarHeight,
        }}
        onScroll={scrollHandler}
        renderItem={({item, index}) => {
            const inputRange = [-1, 0, item_size * index, item_size * (index + 2)];
            const opacityInputRange = [-1, 0, item_size * index, item_size * (index + 1)];
          
            const ItemViewAnimatedStyle = useAnimatedStyle(() => {
              const scale = interpolate(
                onScrollY.value,
                inputRange,
                [1, 1, 1, 0],
                Extrapolate.CLAMP,
              );
          
              const opacity = interpolate(
                onScrollY.value,
                opacityInputRange,
                [1, 1, 1, 0],
                Extrapolate.CLAMP,
              );
              return {transform: [{scale}], opacity};
            });
          
            return (
              <Animated.View style={[styles.itemView, ItemViewAnimatedStyle]}>
                <Image source={{uri: item.image}} style={styles.itemImage} />
                <View>
                  <Text style={styles.nameText}>{item.key}</Text>
                  <Text style={styles.jobtitle}>{item.jobtitle}</Text>
                  <Text style={styles.email}>{item.email}</Text>
                </View>
              </Animated.View>
            );
          }}
      />
    </View>
  );
}
export default FirstAnimation;


Please ignore the style part. It's gonna definitely work. Thanks in advance.

**Comment by mostafanadi** [comment]
const AnimatedFlatList = Animated.createAnimatedComponent(
    FlatList
  );

**Comment by Tohid1999** [comment]
> ```js
>   renderScrollComponent={props => (
>           <Animated.ScrollView
>             {...props}
>                // 👇if you comment this in, onViewableItemsChanged won't fire.
>                // onScroll={onScroll({ y: feedScroll })}
>                // 👇same goes if you comment this in
>                // onScroll={() => null} 
>              />
>          )}
> ```

What if i want to use onEndReached at same time?
in this way you can use only one onEndReached or onScroll, not both in same time

**Comment by Tohid1999** [comment]
> I'd like to reopen this.
> 
> While using the `renderScrollComponent` _does_ work, it doesn't allow all props to work.
> 
> If you use the `renderScrollComponent` with an `onScroll` prop for the `Animated.ScrollView`, the `onViewableItemsChanged` callback never fires after the first time when the component mounts.
> 
> ```js
> import * as React from 'react'
> import { FlatList, Dimensions } from 'react-native'
> import Animated from 'react-native-reanimated'
> import { onScroll } from 'react-native-redash'
> 
> export default () => {
>   const itemHeight = Dimensions.get('window').height
>   return (
>     <FlatList
>         data={data}
>         renderItem={renderItem}
>         keyExtractor={(_, index) => index.toString()}
>         renderScrollComponent={props => (
>           <Animated.ScrollView
>             {...props}
>                // 👇if you comment this in, onViewableItemsChanged won't fire.
>                // onScroll={onScroll({ y: feedScroll })}
>                // 👇same goes if you comment this in
>                // onScroll={() => null} 
>              />
>          )}
>         pagingEnabled
>         getItemLayout={(_, index) => {
>           return {
>             length: itemHeight,
>             index,
>             offset: index * itemHeight
>           };
>         }}
>         showsVerticalScrollIndicator={false}
>         onViewableItemsChanged={console.log} // only logs the first time 
>         viewabilityConfig={viewabilityConfig}
>       />
>   )
> }
> 
> const viewabilityConfig = {
>   itemVisiblePercentThreshold: 80
> };
> ```


@nandorojo 
What if you want to use `onEndReached` and `onScroll` at the same time?
in this way you can only use one `onEndReached `or `onScroll`, not both in the same time

**Comment by maleking** [comment]
this

> > I'd like to reopen this.
> > While using the `renderScrollComponent` _does_ work, it doesn't allow all props to work.
> > If you use the `renderScrollComponent` with an `onScroll` prop for the `Animated.ScrollView`, the `onViewableItemsChanged` callback never fires after the first time when the component mounts.
> > ```js
> > import * as React from 'react'
> > import { FlatList, Dimensions } from 'react-native'
> > import Animated from 'react-native-reanimated'
> > import { onScroll } from 'react-native-redash'
> > 
> > export default () => {
> >   const itemHeight = Dimensions.get('window').height
> >   return (
> >     <FlatList
> >         data={data}
> >         renderItem={renderItem}
> >         keyExtractor={(_, index) => index.toString()}
> >         renderScrollComponent={props => (
> >           <Animated.ScrollView
> >             {...props}
> >                // 👇if you comment this in, onViewableItemsChanged won't fire.
> >                // onScroll={onScroll({ y: feedScroll })}
> >                // 👇same goes if you comment this in
> >                // onScroll={() => null} 
> >              />
> >          )}
> >         pagingEnabled
> >         getItemLayout={(_, index) => {
> >           return {
> >             length: itemHeight,
> >             index,
> >             offset: index * itemHeight
> >           };
> >         }}
> >         showsVerticalScrollIndicator={false}
> >         onViewableItemsChanged={console.log} // only logs the first time 
> >         viewabilityConfig={viewabilityConfig}
> >       />
> >   )
> > }
> > 
> > const viewabilityConfig = {
> >   itemVisiblePercentThreshold: 80
> > };
> > ```
> 
> @nandorojo What if you want to use `onEndReached` and `onScroll` at the same time? in this way you can only use one `onEndReached `or `onScroll`, not both in the same time

I have this problem also
