### ISSUE TITLE
what version of react-native does reanimated v3 support?

### ISSUE THREAD

**Issue by chj-damon** [software-mansion/react-native-reanimated#4574]
### Description

I'm currently running react-native@0.66, with reanimated@2.x it works fine. but recently I upgrade reanimated to v3, and it reports an error on IOS:
```code
Build input file cannot be found: '/xxx/node_modules/react-native-reanimated/Common/cpp/Registries/WorkletsCache.cpp'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'RNReanimated' from project 'Pods')
```
I searched this `WorkletsCache.cpp` and it surely not exists.
maybe react-native@0.66 is not supported? what is the minimum version of react-native that v3 support?

### Steps to reproduce

clone [https://github.com/thundersdata-frontend/rn-template](https://github.com/thundersdata-frontend/rn-template) and change reanimated version to `3.0.0`

### Snack or a link to a repository

https://github.com/thundersdata-frontend/rn-template

### Reanimated version

3.0.0

### React Native version

0.66.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @chj-damon, thanks for submitting this issue. `WorkletsCache.cpp` no longer exists on v3. Did you remember to run `cd ios && pod install` after upgrade?

**Comment by chj-damon** [comment]
oh, thanks. it's my bad. I forget to clean cache. I delete pod folder and rerun `pod install`, now it works fine.
