### ISSUE TITLE
When enabling the debug getting "com.facebook.react.common.Javascr iptException: console.assert is not a function" 

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [software-mansion/react-native-reanimated#4575]
### Description

Hi I want to use React native debugger but when I enable it I am getting the following error

com.facebook.react.common.Javascr iptException: console.assert is not a function

This issue is create since the release of react-native-reanimated 2. Before this I worked with react native debugger and it worked fine.

### Steps to reproduce

1. Create a react native project and follow the steps to add [drawer-navigation](https://reactnavigation.org/docs/drawer-navigator)
2. Run the application press and enable debigging

### Snack or a link to a repository

https://github.com/esqualltpl/Coachieve
Can be create easily using reproduce steps

### Reanimated version

^3.0.1

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by ghana7989** [comment]
there is a thread with similar issue https://github.com/software-mansion/react-native-reanimated/issues/3951 check if it helps

**Comment by tomekzaw** [comment]
@ZeeshanAhmadKhalil Please upgrade to 3.3.0 and let us know if it works for you.

**Comment by Latropos** [comment]
I remember that bug, it got already solved 🥳
