### ISSUE TITLE
android.view.ViewRootImpl cannot be cast to android.view.View

### ISSUE THREAD

**Issue by huy-lv** [software-mansion/react-native-reanimated#4578]
### Description

Error: android.view.ViewRootImpl cannot be cast to android.view.View
![Screenshot_1686818267](https://github.com/software-mansion/react-native-reanimated/assets/7688070/ca456223-221a-404b-b085-2407a56456d9)

### Steps to reproduce

1. Clone this: https://github.com/huy-lv/reanimated-shared-elements
2. yarn
3. yarn android
4. Open app
5. Press to a item on homescreen -> crash

### Snack or a link to a repository

https://github.com/huy-lv/reanimated-shared-elements

### Reanimated version

3.3.0

### React Native version

0.71.8

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by fadi-quader-mox** [comment]
I get this error too

**Comment by fadi-quader-mox** [comment]
this patch fixes it for me 
```diff
diff --git a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
index 91a0ef5..fe24aef 100644
--- a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
+++ b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
@@ -119,10 +119,10 @@ public class SharedTransitionManager {
       if (parent.getClass().getSimpleName().equals("Screen")) {
         return false;
       }
-      if (parent instanceof View) {
+      try {
         parent = (View) parent.getParent();
-      } else {
-        return false;
+      } catch (Exception e) {
+        parent = null;
       }
     }
     return false;

```

**Comment by Latropos** [comment]
Closing since the bug is already solved
