### ISSUE TITLE
Animated2 doesn't work even though the value in useSharedValue has changed

### ISSUE THREAD

**Issue by LuckyBoy124** [software-mansion/react-native-reanimated#4581]
### Description

**Function**: I want to run the animation as soon as I enter a screen.
**Error**: When I start the screen, my animation works sometimes it doesn't. When I get an error I log the value of useSharedValue and see its value changed but the animation doesn't work
**Error rate**: 3% -> 5%
**Can you guys help me? Thank you!**

### Steps to reproduce

1. Select screen
2. Observe animation (Default when entering the call screen always run animation)
3. Chance of not running animation is 3% -> 5%

**Image error**
![Screenshot 2023-06-16 at 11 29 23](https://github.com/software-mansion/react-native-reanimated/assets/108321684/8e1880f8-92e0-42a1-9b7d-fce42fa79aed)
**Image correct**
![Screenshot 2023-06-16 at 11 31 17](https://github.com/software-mansion/react-native-reanimated/assets/108321684/4cdd191f-7659-470d-b8cd-dc2cc846b536)

### Snack or a link to a repository

https://gist.github.com/LuckyBoy124/5501cff784129d1bab6d1b608a7fe88c

### Reanimated version

2.13.0

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Real device

### Device model

IPhone 14Pro - Ios 16.5

### Acknowledgements

Yes

**Comment by Latropos** [comment]
According to provided information you are trying to run new Architecture with Reanimated 2, which is not supported. New Architecture requires at least reanimated 3.
