### ISSUE TITLE
TypeScript Error when using useDerivedValue and interpolateColor for animated backgroundColor

### ISSUE THREAD

**Issue by c-goettert** [software-mansion/react-native-reanimated#4584]
### Description

I am happily using react-native-reanimated with the following configuration:

- react-native: 0.71.7
- typescript: 4.8.4
- react-native-reanimated: 3.1.0

I am using an animated background color based on the useDerivedValue hook and an anmiated value like this:
```
  const backgroundColor = useDerivedValue(() => {
    return interpolateColor(
      animatedIndex.value,
      [0, 1, 2],
      ['#273D3A', '#8B645C', '#60545A'],
    );
  });
```
I apply my animated background color value to the animated view, like this:

```
      <Animated.View
        style={{
          flex: 1,
          paddingBottom: baseMargin,
          height: '100%',
          backgroundColor,
        }}
      >
```
The animation works fine, but typescript is giving me the following error:

> Type '{ flex: number; paddingBottom: number; height: string; backgroundColor: Readonly<Animated.SharedValue<string>>; }' is not assignable to type 'StyleProp<AnimateStyle<StyleProp<ViewStyle>>>'.
      Types of property 'backgroundColor' are incompatible.
        Type 'Readonly<SharedValue<string>>' is not assignable to type 'number | ColorValue | undefined'.

### Steps to reproduce

<img width="1015" alt="Bildschirmfoto 2023-06-17 um 10 46 22" src="https://github.com/software-mansion/react-native-reanimated/assets/7591624/d23e45e8-6fb5-4843-b9c6-5deaf159cc84">

### Snack or a link to a repository

it's just a linter / typescript issue

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by c-goettert** [comment]
Hi @tjzel , thanks for your reply! I tried your solution, and indeed the typescript error disappeard. Unfortunately, the animation seemd to behave buggy when assigning `backgroundColor: backgroundColor.value` directly and also the Library started giving me the following warning:
![Simulator Screenshot - iPhone 8 - 2023-06-24 at 11 58 02](https://github.com/software-mansion/react-native-reanimated/assets/7591624/7fd3ed2b-7840-42a3-925e-78422e81e5d7)

Nevertheless, your answer helped me to find a working solution: Not using an inline style but the `useAnimatedStyle` hook like so:
```
  const animatedStyle = useAnimatedStyle(() => {
    return {
        flex: 1,
        paddingBottom: baseMargin,
        height: '100%',
        backgroundColor: backgroundColor.value,
    };
  });
...
    <Animated.View
      style={animatedStyle}
    >
```
So if you want you can close the ticket, on the other hand I think TypeScript should probably be configured to allow the (working) inline style as well.

**Comment by tjzel** [comment]
Thank you, you've been very helpful. Your usage of inline styles for `Animated.View` was correct in the first place and I have to apologise for forgetting that and claiming you were wrong. 

We are currently in the process of refactoring our TypeScript API and this seems to be one of the things that has been omitted in the past - I'm very grateful for finding that.

The best solution for now, if you want to keep clean TypeScript code would be exactly what you do - use of `useAnimatedStyle`.

I will keep the issue open for now and close it when the required fix appears.
