### ISSUE TITLE
Changing its height while ScrollView is scrolling horizontial doesn't work porperly

### ISSUE THREAD

**Issue by zerosrat** [software-mansion/react-native-reanimated#4585]
### Description

The scene: when scrolling horizontal ScrollView, it changes its height simultaneously.
I use `Animated` of react native lib to implement the correct effect which is illustrated as below.

![Simulator Screen Recording - iPhone 14 Pro - 2023-06-17 at 22 44 19](https://github.com/software-mansion/react-native-reanimated/assets/8179987/254d2ab7-9282-4ac1-be30-883e70e34c13)

When I use `react-native-reanimated`, Android platform works fine with same code while iOS doesn't. The wrong effect is illustrated as below.

![Simulator Screen Recording - iPhone 14 Pro - 2023-06-17 at 22 41 16](https://github.com/software-mansion/react-native-reanimated/assets/8179987/01556da9-6ae9-42cf-a25e-bc41b130f479)

### Steps to reproduce

```tsx
import React from 'react';
import {Dimensions, Text, View} from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedScrollHandler,
  useAnimatedStyle,
} from 'react-native-reanimated';

const winWidth = Dimensions.get('window').width;

export const Swiper = () => {
  const scrollOffset = useSharedValue(0);
  const animatedStyle = useAnimatedStyle(() => {
    return {
      height: (scrollOffset.value / winWidth) * 200 + 200,
    };
  });

  const scrollHandler = useAnimatedScrollHandler({
    onScroll: event => {
      scrollOffset.value = event.contentOffset.x;
    },
  });

  return (
    <Animated.View style={animatedStyle}>
      <Animated.ScrollView
        horizontal
        pagingEnabled
        onScroll={scrollHandler}
        showsHorizontalScrollIndicator={false}
        bounces={false}
        style-={{flex: 1}}>
        <View style={{width: winWidth, height: 200, backgroundColor: 'blue'}}>
          <Text>1</Text>
        </View>
        <View style={{width: winWidth, height: 400, backgroundColor: 'yellow'}}>
          <Text>2</Text>
        </View>
      </Animated.ScrollView>
    </Animated.View>
  );
};
```

### Snack or a link to a repository

https://github.com/zerosrat/react-native-interactive/blob/feature/reanimated/src/pages/interactive-screen/components/swiper.tsx

### Reanimated version

3.3.0

### React Native version

0.71.11

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by zerosrat** [comment]
setup `scrollEventThrottle={16}` on the ScrollView fixed this issue.

> [scrollEventThrottle](https://reactnative.dev/docs/scrollview#scrolleventthrottle-ios): The default value is 0, which results in the scroll event being sent only once each time the view is scrolled.

**Comment by piaskowyk** [comment]
> setup scrollEventThrottle={16} on the ScrollView fixed this issue.
@zerosrat Thanks for sharing the solution!
