### ISSUE TITLE
Missing Dependency in React Native Drawer Overlay

### ISSUE THREAD

**Issue by natainditama** [software-mansion/react-native-reanimated#4592]
### Description

When compiling a web application that uses React Navigation Drawer, a warning is encountered regarding a missing dependency. The warning indicates that the "interpolate" function from the "react-native-reanimated" library is not found when attempting to import it as "Animated" in the Overlay.js file.

### Steps to reproduce

1. Set up a web application using React Navigation Drawer.
2. Attempt to compile the application.
3. Observe the warning message mentioned above.

WARNING in ./node_modules/@react-navigation/drawer/lib/module/views/legacy/Overlay.js:11:4
export 'default'.'interpolate' (imported as 'Animated') was not found in 'react-native-reanimated' (possible exports: Clock, Code, EasingNode, Extrapolate, FlatList, Image, Node, ScrollView, SpringUtils, Text, Transition, Transitioning, Value, View, abs, acc, acos, adapt, add, addWhitelistedNativeProps, addWhitelistedUIProps, always, and, asin, atan, block, call, ceil, clockRunning, color, concat, cond, cos, createAnimatedComponent, createTransitioningComponent, debug, decay, defined, diff, diffClamp, divide, eq, event, exp, floor, greaterOrEq, greaterThan, interpolateColors, interpolateNode, lessOrEq, lessThan, log, max, min, modulo, multiply, neq, not, onChange, or, pow, proc, round, set, sin, spring, sqrt, startClock, stopClock, sub, tan, timing, useCode, useValue)
   9 |   cond,
  10 |   greaterThan,
> 11 | } = Animated;
     |    ^
  12 |
  13 | const interpolate: typeof interpolateNode =
  14 |   interpolateNode ?? interpolateDeprecated;

web compiled with 1 warning

### Snack or a link to a repository

none

### Reanimated version

~2.14.4

### React Native version

0.71.8

### Platforms

Web

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by brada1703** [comment]
I am experiencing the same issue. Has anyone found a solution?

**Comment by piaskowyk** [comment]
Hey 👋 Without reproduction we can't help :/ If anyone provides any reproduction I will be happy to reopen this issue!
