### ISSUE TITLE
[Bug] withSpring config doesn't work in 3.2.0+

### ISSUE THREAD

**Issue by kesha-antonov** [software-mansion/react-native-reanimated#4603]
### Description

Hi,

I've attached videos. In 3.1.0 animation config works. In 3.2.0+ it's broken.

Same config is used for both versions. I've tried to change different values of config - animation doesn't change. Only duration is adjustable.

```
withSpring(value, {
  // How hard the animation decelerates.
  damping: 1,
  // The weight of the spring. Reducing this value makes the animation faster.
  mass: 1,
  // BOUNCINESS
  stiffness: 5,
  overshootClamping: false,
  restSpeedThreshold: 1,
  duration: 2800,
})
```

https://github.com/software-mansion/react-native-reanimated/assets/11584712/e521a94b-2bab-451e-800d-d708a0835dcd

https://github.com/software-mansion/react-native-reanimated/assets/11584712/3c38957c-eebd-42a2-8434-f8e4ae787000

### Steps to reproduce

1. Install reanimated v3.2.0+
2. Try adjust any withSpring animation configs

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

3.3.0

### React Native version

0.71.11

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @kesha-antonov! 
This is the correct type of spring config:
```
{
    stiffness?: number;
    overshootClamping?: boolean;
    restSpeedThreshold?: number;
    restDisplacementThreshold?: number;
    velocity?: number;
  } & (
    | {
        mass?: number;
        damping?: number;
        duration?: never;
        dampingRatio?: never;
      }
    | {
        mass?: never;
        damping?: never;
        duration?: number;
        dampingRatio?: number;
      }
  );
```

Please notice that if you want to specify duration you should use dampingRatio instead of damping.

**Comment by kesha-antonov** [comment]
> Hi @kesha-antonov! This is the correct type of spring config:
> 
> ```
> {
>     stiffness?: number;
>     overshootClamping?: boolean;
>     restSpeedThreshold?: number;
>     restDisplacementThreshold?: number;
>     velocity?: number;
>   } & (
>     | {
>         mass?: number;
>         damping?: number;
>         duration?: never;
>         dampingRatio?: never;
>       }
>     | {
>         mass?: never;
>         damping?: never;
>         duration?: number;
>         dampingRatio?: number;
>       }
>   );
> ```
> 
> Please notice that if you want to specify duration you should use dampingRatio instead of damping. Provide lower `dampingRatio` for more bounces (the default value is 0.5).

Thanks for the reply! I'll try that
