### ISSUE TITLE
Update value in the callback of withTiming with  withSequence not work 

### ISSUE THREAD

**Issue by XHMM** [software-mansion/react-native-reanimated#4604]
### Description

When using `withTiming` with `withSequence`, change value in the callback not work.

### Steps to reproduce

As the following runnable example, I want to reset `v.value` to 0 when animation finished, the 'bad' case always log `1` except the first round, the 'ok' case always log `0` as expected:
```js
import {
  useSharedValue,
  withSequence,
  withTiming,
} from 'react-native-reanimated';
import {Text, Pressable} from 'react-native';

export const Demo = () => {
  const v = useSharedValue(0);

  return (
    <>
      <Pressable
        onPress={() => {
          console.log('[bad]value:', v.value);
          v.value = withSequence(
            withTiming(
              1,
              {
                duration: 100,
              },
              (finished, current) => {
                v.value = 0;
                console.log('finished:', finished);
              },
            ),
          );
        }}>
        <Text style={{fontSize: 20}}>Click(bad)</Text>
      </Pressable>

      <Pressable
        onPress={() => {
          console.log('[ok]value:', v.value);
          v.value = withTiming(
            1,
            {
              duration: 100,
            },
            (finished, current) => {
              v.value = 0;
              console.log('finished:', finished);
            },
          );
        }}>
        <Text style={{fontSize: 20}}>Click(ok)</Text>
      </Pressable>
    </>
  );
};

```

### Snack or a link to a repository

https://snack.expo.dev/VVl_zhTHu

### Reanimated version

3.3.0

### React Native version

0.71.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! Generally you should never overwrite the sharedValue you animate in animation callback.
We have decided that the current behaviour should be expected. Please notice that the final value of `withSequence` is 1, therefore it overwrites the value from your callback (which is executed)
