### ISSUE TITLE
Layout animation does not work in ScrollView when removeClippedSubviews={true}

### ISSUE THREAD

**Issue by wshinigamic** [software-mansion/react-native-reanimated#4605]
### Description

I am trying to implement a 2 column list of cards with layout animation. Using FlatList with numColumns={2} does not work (see #2806) but ScrollView with cards at 50% width does.

However, this leads to sub-optimal rendering. To improve performance, I set removeClippedSubviews in ScrollView to true, but this causes the layout animation to stop working.

### Steps to reproduce

Please see example below. It does not matter whether the card width is 100% (single column) or 50% (2 column).

```
import { useState } from 'react';
import { Button, Text, View, ScrollView, StyleSheet } from 'react-native';
import Animated, { Layout } from 'react-native-reanimated'

const NUMBERS = [...Array(20).keys()]

const Card = ({ number, removeNumber }) => {
  return (
    <Animated.View 
      style={{width:"100%"}}
      layout={Layout}
    >
      <View style={styles.cardContainer}>
        <Text>{number}</Text>
        <Button title="remove" onPress={()=>removeNumber(number)}/>
      </View>
    </Animated.View>
  )
}

export default function App() {
  const [numbers, setNumbers] = useState(NUMBERS)
  const removeNumber = (number) => {
    setNumbers(numbers.filter(item => item !== number))
  }
  return (
    <ScrollView
      style={{ width: "100%" }}
      contentContainerStyle={{ flexDirection: "row", flexWrap: "wrap" }}
      removeClippedSubviews={true}
    >
      {numbers.map(number => (
        <Card key={number} number={number} removeNumber={removeNumber}/>
      ))}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  cardContainer: {
    margin: 8,
    backgroundColor: "lightgray",
    height: 200,
    justifyContent: "center",
    alignItems:"center"
  }
});

```

### Snack or a link to a repository

https://snack.expo.dev/g_pASWHGt

### Reanimated version

2.9.0

### React Native version

0.69.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Thank you fr submitting the issue!
https://github.com/software-mansion/react-native-reanimated/assets/56199675/e0eaf477-05c0-440f-9f36-2fa1381e500e

Unfortunately, since the bug has relatively low impact it is possible that we won't be able to look into the problem.

However although we don't support `FlatList` with multiple columns you can pass the whole row of elements to `renderItem` to create similar effect.

**Comment by wshinigamic** [comment]
Hey, thanks for your reply!

I tried following your suggestion to pass 2 elements at a time to `renderItem` to create a 2 column `FlatList`. However, the layout animation is still not working.

Please let me know if I am following your suggestion correctly? 

[https://snack.expo.dev/Wv7CZ8SNW](https://snack.expo.dev/Wv7CZ8SNW)

```
import { useState } from 'react';
import { Button, FlatList, Text, View, StyleSheet } from 'react-native';
import Animated, { Layout } from 'react-native-reanimated'
import { chunk } from 'lodash';

const NUMBERS = [...Array(20).keys()]

const Card = ({ number, removeNumber}) => {
  return (
    <Animated.View 
      style={{width:"50%"}}
      layout={Layout}
    >
      <View style={styles.cardContainer}>
        <Text>{number}</Text>
        <Button title="remove" onPress={()=>removeNumber(number)}/>
      </View>
    </Animated.View>
  )
}

const CardRow = ({ item, removeNumber }) => {
  const a = item[0]
  const b = item[1]
  return (
    <View style={{flexDirection:"row"}}>
      <Card number={a} removeNumber={removeNumber} />
      {
        b != null ? <Card number={b} removeNumber={removeNumber} /> : null
      }
    </View>
  )
}

export default function App() {
  const [numbers, setNumbers] = useState(NUMBERS)
  const removeNumber = (number) => {
    setNumbers(numbers.filter(item => item !== number))
  }
  return (
    <FlatList
      style={{width: "100%"}}
      data={chunk(numbers, 2)}
      renderItem={({item, i}) => <CardRow key={i} item={item} removeNumber={removeNumber}/>}
    />
  );
}

const styles = StyleSheet.create({
  cardContainer: {
    margin: 8,
    backgroundColor: "lightgray",
    height: 200,
    justifyContent: "center",
    alignItems:"center"
  }
});
```

**Comment by Latropos** [comment]
@wshinigamic Sorry, I thought it may work, this is how multi-column list is implemented under the hood. But it will not do, since components changing layout should have the same parent view.

However once you add   `flexWrap: 'wrap'` to `contentContainerStyle` the result is probably the one you want (however it is officialy not supported here, and you will get console.warn)

<table><tr><td>

https://github.com/software-mansion/react-native-reanimated/assets/56199675/9f6ce89b-005e-439b-b310-5b26a91712e3

</td><td>

https://github.com/software-mansion/react-native-reanimated/assets/56199675/2b0567d0-d141-4868-957e-4e3464090cc3

</td></tr></table>

**Comment by wshinigamic** [comment]
@Latropos Yes, the behaviour of the screen recording on the right is exactly what I want. Was that achieved using FlatList? I tried adding `contentContainerStyle={{flexDirection:"row", flexWrap:"wrap"}}` but layout animation is not working.

[https://snack.expo.dev/Qh2c7UMTA](https://snack.expo.dev/Qh2c7UMTA)

Grateful if you can share the code that produces this. Thank you!

**Comment by Latropos** [comment]
@wshinigamic I've fixed your example:

```import { useState } from 'react';
import {
  Button,
  Dimensions,
  Text,
  View,
  FlatList,
  StyleSheet,
} from 'react-native';
import Animated, {
  Layout,
  FadeIn,
  FadeOut,
  enableLayoutAnimations,
} from 'react-native-reanimated';

enableLayoutAnimations(true);
const { width } = Dimensions.get('window');
const NUMBERS = [...Array(20).keys()];

const Card = ({ number, removeNumber }) => {
  return (
    <Animated.View
      entering={FadeIn}
      exiting={FadeOut}
      style={{ width: width / 2 }}
      layout={Layout.springify()}
      key={number + ''}>
      <View style={styles.cardContainer}>
        <Text>{number}</Text>
        <Button title="remove" onPress={() => removeNumber(number)} />
      </View>
    </Animated.View>
  );
};

export default function App() {
  const [numbers, setNumbers] = useState(NUMBERS);
  const removeNumber = (number) => {
    setNumbers(numbers.filter((item) => item !== number));
  };
  return (
    <Animated.FlatList
      contentContainerStyle={{ flexDirection: 'row', flexWrap: 'wrap' }}
      itemLayoutAnimation={Layout.springify()}
      data={numbers}
      renderItem={({ item }) => (
        <Card number={item} removeNumber={removeNumber} />
      )}
      keyExtractor={(item) => '' + item}
    />
  );
}

const styles = StyleSheet.create({
  cardContainer: {
    margin: 8,
    backgroundColor: 'lightgray',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```
Mind, that it does't work in the sandbox (`snack.expo`).
