### ISSUE TITLE
Ask a question to people who often use realistic

### ISSUE THREAD

**Issue by afeichuanqi** [software-mansion/react-native-reanimated#461]
I want to ask people who understand realized.

I now encounter a thorny problem, that is, after the whole layout animation is drawn. It turns out that when I use react navigation to switch bottom navigation, the first response is about 2-3 seconds. I can't take it. I'm very focused on render. So it's unlikely to be a performance issue caused by render I want to ask if this has something to do with realized. I used realized in about 4-5 places on the page. It's not easy to check now. Forget to tell.

**Comment by Jarred-Sumner** [comment]
If it's on iOS, you could try profiling in Instruments that would help you identify the cause.

![image](https://user-images.githubusercontent.com/709451/68828716-8b796200-065b-11ea-9055-cb00ffcb5401.png)

To do that,  click "Profile in Instruments" and then look at the CPU usage in Instruments for the time range where you're noticing the performance issues.

**Comment by afeichuanqi** [comment]
> If it's on iOS, you could try profiling in Instruments to get more information.
> 
> ![image](https://user-images.githubusercontent.com/709451/68828716-8b796200-065b-11ea-9055-cb00ffcb5401.png)
> 
> To do that, click "Profile in Instruments" and then look at the CPU usage in Instruments for the time range where you're noticing the performance issues.

Will reanimated evaluate the animation node or initialize the animation when entering the page? Is reanimated and react-native's own animated different in initialization?

**Comment by WoLewicki** [comment]
Could you provide a code example of the issue?
