### ISSUE TITLE
[Android] ScrollView "stops" reanimated on some Android devices

### ISSUE THREAD

**Issue by robrechtme** [software-mansion/react-native-reanimated#4626]
### Description

I'm sorry to report this very weird issue. The issue seems to appear on _some_ Android devices (at the moment only **OnePlus 11 5G** and **OnePlus 8**), but it is consistently reproducible. 

We have an issue where Reanimated sometimes seemingly randomly "stops working". I was able to narrow it down to a minimally reproducible example; scrolling a simple `ScrollView` up and down sometimes blocks Reanimated. Only a cold boot resolves it. 

This is a OnePlus 11 5G with Android 13: 

https://github.com/software-mansion/react-native-reanimated/assets/24371353/2fb5534e-5a6f-4084-a29b-5038a47fcb07

I have some Flipper logs as well, hope this helps!

<details>
  <summary>Flipper logs</summary>
  

![Screenshot 2023-06-26 at 14 54 27](https://github.com/software-mansion/react-native-reanimated/assets/24371353/a3de35e0-421e-445e-902e-8f9664371119)

</details>

### Steps to reproduce

1. `npx react-native init`
2. `yarn add react-native-reanimated` and update the babel config
3. Edit `App.tsx`

```tsx
import React, {useEffect} from 'react';
import {SafeAreaView, ScrollView, StatusBar, StyleSheet} from 'react-native';
import Animated, {
  Easing,
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withTiming,
} from 'react-native-reanimated';

import {Colors} from 'react-native/Libraries/NewAppScreen';

function App(): JSX.Element {
  const angle = useSharedValue(0);

  useEffect(() => {
    angle.value = withRepeat(
      withTiming(360, {duration: 1000, easing: Easing.linear}),
      -1,
    );
  }, [angle]);

  const rotateStyle = useAnimatedStyle(() => ({
    transform: [{rotate: `${angle.value}deg`}],
    width: 100,
    height: 100,
    backgroundColor: 'red',
  }));

  return (
    <SafeAreaView style={styles.background}>
      <StatusBar
        barStyle={'light-content'}
        backgroundColor={styles.background.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        contentContainerStyle={styles.contentContainer}>
        <Animated.View style={rotateStyle} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  background: {
    backgroundColor: Colors.darker,
  },
  contentContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '150%',
  },
});

export default App;
```

### Snack or a link to a repository

https://github.com/robrechtme/ReanimatedBug

### Reanimated version

3.3.0

### React Native version

0.72.0 (but 0.71.0 as well)

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode
Production build as well

### Device

Real device

### Device model

OnePlus 11 5G
OnePlus 8

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
I’m experiencing the same on 3.3.0 and only in rn 0.72.0, 0.71.x works fine. In my case I animate 2 elements on top and it seems that the scrollY of the list can’t reach 0 if the user scrolls fast enough towards the top. It’s totally random, sometimes is closer to 0 and sometimes farther, it all depends how fast the user is scrolling.

**Comment by mhammerc** [comment]
I experience the exact same bug on a OnePlus 8T.

**Comment by mhammerc** [comment]
Can reproduce on `react-native-reanimated 3.3.0`, `Expo 49` and `react-native 0.72`.
But can not reproduce on `react-native-reanimated 2.14.4`, `Expo 48` and `react-native 0.71`.

**Comment by iArchin** [comment]
Also happens to me with  `OPPO A55` Device. 
Tried on `react-native 0.71.8` with `react-native-reanimated 3.2.0`  and also `react-native 0.72.2` with `react-native-reanimated 3.3.0`

**Comment by piaskowyk** [comment]
Hey, I think that this is the solution: https://github.com/software-mansion/react-native-reanimated/pull/4579

**Comment by robrechtme** [comment]
@piaskowyk I tried your patch locally and I cannot manage to reproduce the bug anymore!
 
Thank you very much for fixing this super weird issue 😅

**Comment by robrechtme** [comment]
If you can't wait for the next release and you're using [patch-package](https://github.com/ds300/patch-package), here's the patch:

<details>

<summary>react-native-reanimated+3.3.0.patch</summary>


```diff
diff --git a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
index e974f8e..7c10650 100644
--- a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
+++ b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
@@ -81,7 +81,7 @@ public class NodesManager implements EventDispatcherListener {
   private RCTEventEmitter mCustomEventHandler;
   private List<OnAnimationFrame> mFrameCallbacks = new ArrayList<>();
   private ConcurrentLinkedQueue<CopiedEvent> mEventQueue = new ConcurrentLinkedQueue<>();
-  public double currentFrameTimeMs;
+  private double lastFrameTimeMs;
   public Set<String> uiProps = Collections.emptySet();
   public Set<String> nativeProps = Collections.emptySet();
   private ReaCompatibility compatibility;
@@ -234,25 +234,31 @@ public class NodesManager implements EventDispatcherListener {
   }
 
   private void onAnimationFrame(long frameTimeNanos) {
-    currentFrameTimeMs = frameTimeNanos / 1000000.;
+    double currentFrameTimeMs = frameTimeNanos / 1000000.;
 
-    while (!mEventQueue.isEmpty()) {
-      CopiedEvent copiedEvent = mEventQueue.poll();
-      handleEvent(copiedEvent.getTargetTag(), copiedEvent.getEventName(), copiedEvent.getPayload());
-    }
+    if (currentFrameTimeMs > lastFrameTimeMs) {
+      // It is possible for ChoreographerCallback to be executed twice within the same frame
+      // due to frame drops. If this occurs, the additional callback execution should be ignored.
+      lastFrameTimeMs = currentFrameTimeMs;
 
-    if (!mFrameCallbacks.isEmpty()) {
-      List<OnAnimationFrame> frameCallbacks = mFrameCallbacks;
-      mFrameCallbacks = new ArrayList<>(frameCallbacks.size());
-      for (int i = 0, size = frameCallbacks.size(); i < size; i++) {
-        frameCallbacks.get(i).onAnimationFrame(currentFrameTimeMs);
+      while (!mEventQueue.isEmpty()) {
+        CopiedEvent copiedEvent = mEventQueue.poll();
+        handleEvent(
+            copiedEvent.getTargetTag(), copiedEvent.getEventName(), copiedEvent.getPayload());
+      }
+
+      if (!mFrameCallbacks.isEmpty()) {
+        List<OnAnimationFrame> frameCallbacks = mFrameCallbacks;
+        mFrameCallbacks = new ArrayList<>(frameCallbacks.size());
+        for (int i = 0, size = frameCallbacks.size(); i < size; i++) {
+          frameCallbacks.get(i).onAnimationFrame(currentFrameTimeMs);
+        }
       }
-    }
 
-    performOperations();
+      performOperations();
+    }
 
     mCallbackPosted.set(false);
-
     if (!mFrameCallbacks.isEmpty() || !mEventQueue.isEmpty()) {
       // enqueue next frame
       startUpdatingOnAnimationFrame();
```

</details>
