### ISSUE TITLE
Native side not loading with custom AppDelegate.swift

### ISSUE THREAD

**Issue by danielRChildrens** [software-mansion/react-native-reanimated#4631]
### Description

I am receiving the following error after converting the AppDelegate.mm to AppDelegate.swift:

Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized.

AppDelegate.swift
```
import Foundation

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?
  var bridge: RCTBridge!

  func application(_ application:UIApplication, didFinishLaunchingWithOptions launchOptions:[UIApplication.LaunchOptionsKey : Any]?) -> Bool {
    let jsCodeLocation: URL
    
    jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")

    let rootView = RCTRootView(bundleURL: jsCodeLocation, moduleName: "DigitalFrontDoor", initialProperties: nil, launchOptions: launchOptions)

    let rootViewController = UIViewController()
    rootViewController.view = rootView
    self.window = UIWindow(frame: UIScreen.main.bounds)
    self.window?.rootViewController = rootViewController
    self.window?.makeKeyAndVisible()
    
    return true
    
  }


  /// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
  ///
  /// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
  /// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
  /// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
  func concurrentRootEnabled() -> Bool {
    return true
  }
}
```

Notes:
- The iOS build is completing successfully
- Android is working as expected
- I have tried removing the Pods, node_modules, build folders and reinstalling everything.
- I have tried restarting my computer
- Converting the AppDelegate to swift works without Reanimated
- I have followed this post for the AppDelegate swift migration (https://ospfranco.com/post/2021/07/31/migrate-rn-appdelegate-to-swift/)

### Steps to reproduce

I have two Branches as follows:

- Branch 1 (reanimated): Regular AppDelegate with Reanimated, In this branch everything works as expected in both platforms
- Branch 2 (swift-app-delegate): Swift AppDelegate without Reanimated, In this branch everything works as expected in both platforms

When both branches are merged (swift-appdelegate-reanimated), getting Swift AppDelegate With Reanimated, the iOS build works, but when the app is launched I get the error:

![image](https://github.com/software-mansion/react-native-reanimated/assets/122642384/4eebad4e-3428-43b7-b07a-619098f74743)

### Snack or a link to a repository

https://github.com/danielRChildrens/SwiftReanimated/tree/swift-appdelegate-reanimated

### Reanimated version

3.3.0

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iOS 16 iphone 14

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @danielRChildrens, thanks for reporting this issue.

Currently, our initialization flow for iOS assumes that `AppDelegate` extends `RCTAppDelegate`. We swizzle `jsExecutorFactoryForBridge` method in order to call `reanimated::REAInitializer(bridge)` at the early stage of app startup (see [`RCTAppDelegate+Reanimated.mm`](https://github.com/software-mansion/react-native-reanimated/blob/main/ios/native/RCTAppDelegate%2BReanimated.mm)).

Please let me know if any of the approaches below works for you:
1. Make changes to `AppDelegate` so that it extends `RCTAppDelegate`
```diff
-class AppDelegate: UIResponder, UIApplicationDelegate {
+class AppDelegate: RCTAppDelegate, UIResponder, UIApplicationDelegate {
```
2. Override method `jsExecutorFactoryForBridge` and manually call `reanimated::REAInitializer(bridge)

**Comment by tapz** [comment]
@tomekzaw Could you please give more information about the approach 2? Tried to make my AppDelegate.swift to implement `RCTCxxBridgeDelegate`, but got error `"Cannot find type 'RCTCxxBridgeDelegate' in scope"`. Tried to add import React, but that did not help.

**Comment by tomekzaw** [comment]
@tapz I'm a Swift beginner so I don't think I can help much in this case. Basically, you need to call `reanimated::REAInitializer(bridge)` function somewhere at the beginning of the initialization flow of the app.

**Comment by tapz** [comment]
@tomekzaw `RCTAppDelegate` does not support Swift, so probably `RCTCxxBridgeDelegate` neither. Do you have any solution that would work with Swift? Otherwise Reanimated 3 does not work with Swift at all.

**Comment by tapz** [comment]
@tomekzaw Ok, I'll try to add it to as early as possible in the app initialization.

**Comment by tomekzaw** [comment]
@tapz We're currently working on a better solution so hopefully Reanimated 3.4.0 will no longer use this mechanism.

**Comment by tapz** [comment]
The problem is that I don't know how to call `reanimated::REAInitializer(bridge)` from Swift. I have the bridge object, as I instantiate it myself. But not the error is 

`Cannot find 'reanimated' in scope`
`Consecutive statements on a line must be separated by ';'`
`Expected expression`

or if I remove `reanimated::`

`"Cannot find type 'REAInitializer' in scope"`

Probably have to write some kind of Objective-c bridge to make the call.

**Comment by tomekzaw** [comment]
Yup, `reanimated::REAInitializer` is a function written in Objective-C++.

**Comment by tapz** [comment]
I created a bridge, but now the app crashes to this:

`Exception	NSException *	"[<RCTBridge 0x28357dce0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _callableJSModules."	0x00000002810c2e20
`
REAnimatedBridge.h

```
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>

@interface REAnimatedBridge : NSObject

- (void) rainit:(RCTBridge *)bridge;


@end
```

REAnimatedBridge.mpp

```
#import <RNReanimated/REAInitializer.h>
#import "REAnimatedBridge.h"

@implementation REAnimatedBridge

- (void) rainit:(RCTBridge *)bridge {
  reanimated::REAInitializer(bridge);
}

@end
```

MyApp-Bridging-Header.m

`#import "REAnimatedBridge.h"`

AppDelegate.swift

`REAnimatedBridge().rainit(bridge)`

rainit probably could be static, so there would be no need to create an instance of `REAnimatedBridge`.

**Comment by tomekzaw** [comment]
@tapz What do you mean by "I created a bridge"? You need to pass the same instance of bridge which has already been created by React Native.

**Comment by tapz** [comment]
@tomekzaw Since I'm not using RCTAppDelegate, I need to create the bridge myself.

```
guard let bridge = RCTBridge(delegate: self, launchOptions: launchOptions) else { return false }
let rootView = RCTRootView(bridge: bridge, moduleName: "Tulka", initialProperties: [:])
...
window.rootViewController = rootViewController
window.makeKeyAndVisible()
```

**Comment by zack2012** [comment]
@tapz try pass  `RCTCxxBridge` not `RCTBridge` class. Below code is work for me:
```swift
let bundle = Bundle.main.url(forResource: "main", withExtension: "jsbundle") ?? URL(string: "http://localhost:8081/index.bundle?platform=ios")!
rootView = RCTRootView(
  bundleURL: bundle,
  moduleName: moduleName,
  initialProperties: initialProperties,
  launchOptions: nil)                           
RNObjcHacker.initializeBridge(rootView.bridge.batched)
```
```objc
// header.h
NS_ASSUME_NONNULL_BEGIN

@interface RNObjcHacker : NSObject

+ (void)initializeBridge:(RCTBridge *)bridge;

@end

NS_ASSUME_NONNULL_END

// .mm 
#import "RNObjcHacker.h"
#import <RNReanimated/REAInitializer.h>

@implementation RNObjcHacker

+ (void)initializeBridge:(RCTBridge *)bridge {
  reanimated::REAInitializer(bridge);
}

@end
```

**Comment by tapz** [comment]
@tomekzaw I updated from 3.3.0 to 3.4.1 and now `reanimated::REAInitializer` cannot be found.

> REAnimatedBridge.mpp:15:15 No type named 'REAInitializer' in namespace 'reanimated'

**Comment by tapz** [comment]
Does not seem to require the `REAInitializer` call anymore...

**Comment by piaskowyk** [comment]
yes, you no longer need to call REAInitializer
