### ISSUE TITLE
Potential TypeScript errors in react-native-reanimated 3.4.0

### ISSUE THREAD

**Issue by tjzel** [software-mansion/react-native-reanimated#4645]
### Description
This issue is dedicated for all `react-native-reanimated` users that have upgraded to 3.4.0. We made a significant change in which we remove old, manually typed definition file `react-native-reanimated.d.ts` to use automatically generated `.d.ts` files. 

However, the code base is complex enough that full transition could not be done all at once and some type errors are to be expected. Therefore, please report your type problems in this issue, so we could have them all in one place.

Moreover, if issues that emerged are too burdensome for you to keep up smooth development with `react-native-reanimated` we've prepared a quick guide on how to revert those changes, until the fixes come.

This is a [special branch](https://github.com/software-mansion/react-native-reanimated/tree/restore-d.ts) that is the current version of `react-native-reanimated` but doesn't use automatically generated types. Keep in mind, that this version is also not type errors free and we don't plan on improving it, since its maintenance is too time consuming.

#### CLI solve

```bash
cd <path to node_modules> ; \
cd react-native-reanimated ; \
rm package.json ; \
wget https://raw.githubusercontent.com/software-mansion/react-native-reanimated/restore-d.ts/package.json ; \
wget https://raw.githubusercontent.com/software-mansion/react-native-reanimated/restore-d.ts/react-native-reanimated.d.ts
```

#### Manual solve

1. Open our [special branch](https://github.com/software-mansion/react-native-reanimated/tree/restore-d.ts).
2. From there download two files:
    - `package.json` (make sure it's the file that's in the root of repository)
    - `react-native-reanimated.d.ts`
3. Move those files (replace package.json) in `node_modules/react-native-reanimated` in your project files.
4. In case TypeScript has trouble resolving types after that, a restart of your IDE/TypeScript compiler might be necessary.

### Steps to reproduce

1. Upgrade `react-native-reanimated` to `3.4.0`.

### Reanimated version

3.4.0

### Platforms

Android, iOS, Web

**Comment by aliza-khu** [comment]
@tjzel, Any estimation time for release 3.4.0? And is the resolution of this [issue](https://github.com/software-mansion/react-native-reanimated/issues/4537) going to be included in it or not?

**Comment by renchap** [comment]
I tried the `nightly` package in our app, and I am seeing one issue:

We store some shared values in a context, but the context default values are not proper shared values objects, as (afaik) you can not create share values outside of a component.

We initialize them with `{ value: 0 }` objects, which are never used as those context values are always set when rendering the provider.

Example:

```ts
export const myContext = createContext<{ counter: SharedValue<number> }>({
  counter: { value: 0 },
})

// Then used like this:

const Component: React.FC = () => {
  const counter = useSharedValue(0)

  <myContext.Provider value={{ counter }}>
    {/* … */}
  </myContext.Provider>
}
```

This fails with the following error:

```
index.tsx:76:3 - error TS2739: Type '{ value: number; }' is missing the following properties from type 'SharedValue<number>': addListener, removeListener, modify
```

**Comment by tjzel** [comment]
Hi @renchap.
What you're describing is an issue stemming from improper typing in manually written types file. Out of simplicity `SharedValue` type was declared as an object with only `value` prop. This wasn't true though and `SharedValue` has its other properties 'revealed' now. Assigning an object that has only `value` prop is correctly detected as an error.

From my personal experience I also found default values for `useContext` a pain. I'd suggest the following:

```TypeScript
export const myContext = createContext<{ counter: SharedValue<number> }>({
  counter: undefined as unknown as SharedValue<number>,
})
```

I know it's not pretty, but you could make it better:

```TypeScript
interface myContextType {
  counter: SharedValue<number>;
}

export const myContext = createContext<myContextType>(
  {} as myContextType
);
```

Which I think is much more elegant.

**Comment by tjzel** [comment]
@aliza-khu About the release, I believe it may require a few additional weeks. With regards to the issue you raised, we will make every effort to fix it before the release, provided that we have sufficient time. If you have any ideas for a desired fix, we would be delighted if you could open a pull request.

Lastly, I kindly request that you avoid including non-TypeScript problems in this issue to ensure that all matters are handled systematically.

**Comment by jblarriviere** [comment]
Hello ! I tried the nightly package in our app as well, and I've encountered this issue:

We used to provide an adapter created through `createAnimatedPropAdapter` as a 3rd argument to `useAnimatedProps`.

Example:

This example from the docs would raises the same error we have : https://reanimated-beta-docs.swmansion.com/docs/core/useAnimatedProps#adapters-

It fails with the following error: 
```error
TS2345: Argument of type 'AdapterWorkletFunction' is not assignable to parameter of type 'PropsAdapterFunction | PropsAdapterFunction[] | null | undefined'

Please let me know if there's more I can do !

**Comment by tjzel** [comment]
@jblarriviere Thanks for pointing that out! Adapters are quite complex and so far I had to cast it to old `.d.ts` types but missed some places - but thanks to your quick feedback [a fix](https://github.com/software-mansion/react-native-reanimated/pull/4653) is already there!

**Comment by robwalkerco** [comment]
@tjzel After upgrading to 3.4.0 from 3.3.0 I'm getting the following type error:
```
node_modules/react-native-reanimated/src/reanimated2/threads.ts: /<redacted>/app/node_modules/react-native-reanimated/src/reanimated2/threads.ts: Unknown node type: "TSInstantiationExpression"
```

I've reviewed the latest installation instructions and updated versions of Babel etc. but the error persists.

**Comment by casperolesen** [comment]
> @tjzel After upgrading to 3.4.0 from 3.3.0 I'm getting the following type error:
> 
> `node_modules/react-native-reanimated/src/reanimated2/threads.ts: /<redacted>/app/node_modules/react-native-reanimated/src/reanimated2/threads.ts: Unknown node type: "TSInstantiationExpression"`
> 
> I've reviewed the latest installation instructions and updated versions of Babel etc. but the error persists.

Same here

**Comment by tjzel** [comment]
Hi @robwalkerco @casperolesen! Is this error coming from babel? It seems like it. I just built a fresh RN app with Reanimated and it works for me - could you post more details about the error you are encountering?

**Comment by robwalkerco** [comment]
I resolved the `TSInstantiationExpression` issue by deleting yarn.lock and regenerating it. I was not able to find the specific dependency causing the issue.

**Comment by casperolesen** [comment]
> Hi @robwalkerco @casperolesen! Is this error coming from babel? It seems like it. I just built a fresh RN app with Reanimated and it works for me - could you post more details about the error you are encountering?

I also tried testing in a fresh RN 0.72.3 build with Reanimated 3.4.0 with no errors.
Then I added all the dependencies from my project to this fresh build - still no errors.

So then I tried to delete the yarn.lock in my project - and it resolved the `Unknown node type: "TSInstantiationExpression"`

**Comment by tjzel** [comment]
It's weird because yarn.lock is supposed to be auto-generated but funny things is we also had a case in the past in our repo that yarn.locks got corrupted somehow and I had to delete them and let them generate from scratch.
Thanks for troubleshooting this problem (it would be a pain to get to it I guess since the error was so unspecific).

**Comment by robwalkerco** [comment]
Correction - adding the following to package.json `resolutions` has resolved the issue for me:

```
"resolutions": {
    "@babel/plugin-transform-typescript": "^7.20.0",
    "@babel/types": "^7.20.0",
    ...
  },
```

**Comment by bfricka** [comment]
The main issue I have with these changes is that not enough structural types are exported. Previously we had stuff like `WithSpringConfig` and `WithTimingConfig`. These types that describe configuration interfaces for various functions are very useful for composing helpers and predefined animations.

With these changes I now have to type them manually or extract them from the functions:

```ts
import { withTiming } from 'react-native-reanimated'

type TimingConfig = Parameters<typeof withTiming>['1']
```

Most of these types should be exported. Things like `EasingFn`, `EasingFactoryFn`, and all similar types should be exported. The only things that shouldn't be exported are the types that describe internal details. I'm actually really surprised that so few types are being exported that are associated with the public API of reanimated.

**Comment by tjzel** [comment]
Hi @bfricka. You're absolutely right.

This pull request is not supposed to be a breaking change - it shouldn't change our API. I should've explained this more elaborately in this issue's description, but types are not supposed to be gone in `3.4.0` - therefore, if a type you imported from `react-native-reanimated` is missing then it's an error and you are more than welcome to report it - and I will restore it.

Reason for some types missing is the fact that old `.d.ts` contained actual errors and imports that couldn't be resolved - therefore I decided to actually get as little from it as possible; also our codebase is quite complex and it's sometimes hard to tell if some piece of code is relevant (especially when its types are incorrect).

Those structural types you mention are an obvious mistake on my side - I focused on getting exported, auto-generated types right and didn't think about the fact that some important types might actually not be exported in our `.ts` code.

I will go through the types from our old `.d.ts` once again and add all missing, relevant types. Thank you for pointing this out!

**Comment by diegolmello** [comment]
We got around this issue with this patch https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5128/commits/9f93bc3543a63fa7484387c0c113c150f8967c6f

```diff
diff --git a/node_modules/react-native-reanimated/package.json b/node_modules/react-native-reanimated/package.json
index 0ffa9d3..00d6cd1 100644
--- a/node_modules/react-native-reanimated/package.json
+++ b/node_modules/react-native-reanimated/package.json
@@ -34,8 +34,8 @@
   },
   "main": "lib/module/index",
   "module": "lib/module/index",
-  "react-native": "src/index",
-  "source": "src/index",
+  "react-native": "lib/module/index",
+  "source": "lib/module/index",
   "types": "lib/typescript/index",
   "files": [
     "Common/",
```

**Comment by tjzel** [comment]
@diegolmello What issue do you mean?

**Comment by diegolmello** [comment]
@tjzel https://github.com/software-mansion/react-native-reanimated/issues/4645#issuecomment-1649993021

**Comment by tjzel** [comment]
With this patch you are forcing RN to use emitted ESModule instead of source code. This issue stems from some `yarn.lock` corruption. Try to delete your `node_modules` or `node_modules` and `yarn.lock` and see if the issue is gone without applying this patch.

**Comment by diegolmello** [comment]
> Try to delete your node_modules or node_modules and yarn.lock and see if the issue is gone without applying this patch.

It didn't work.

**Comment by tjzel** [comment]
It's weird, in this directory we have source TS files and there shouldn't be any error resolving them, somehow the transpiler must be taking it as `ESModule` location or something. Perhaps your repo is misconfigured? You can also try deleting your `yarn`'s cache.

**Comment by GleidsonDaniel** [comment]
> With this patch you are forcing RN to use emitted ESModule instead of source code. This issue stems from some `yarn.lock` corruption. Try to delete your `node_modules` or `node_modules` and `yarn.lock` and see if the issue is gone without applying this patch.

If I'm using the library and it already has the types, why would I want to use source code instead of compiled code? (Which would even avoid all this problem with types)

**Comment by tjzel** [comment]
That's a fair question that I'm not sure I know an answer to at the moment. Probably depends on your configuration - if you need to compile source code to a form that suits your project.

**Comment by bfricka** [comment]
> Releasing a breaking change in a patch (!!) version is causing us a lot of headache:
> 
> [tamagui/tamagui#1363 (comment)](https://github.com/tamagui/tamagui/issues/1363#issuecomment-1671234125)
> 
> We have to now replace all these types with our own manual types because otherwise we can’t support both versions.

These are not breaking changes. None of the interfaces are different, only the types. We cannot expect authors to guarantee perfect TypeScript back compatibility, because there are just too many permutations of how user land can interact with and use types. There's no way to guarantee that a type change doesn't break someone's usage.

That said, I agree that primary interface types should have been exported. Frankly, it's not a hard thing to address, and you're you still get to benefit from someone else's hard work.

Since you did all the work of replacing the previously exported types with your own, why not open a PR that exports the types you need? That would benefit everyone.

**Comment by tjzel** [comment]
@natew This was not on purpose. Accidentally `WithDecayConfig` was imported as `import` instead of `import type` and for some reasons that's illegal on web. Relevant fix has already been merged and we are preparing `3.5.0` that will have this and other fixes included. If you need it asap I suggest installing `react-native-reanimated`'s nightly version (`yarn add react-native-reanimated@nightly` or `npm install react-native-reanimated@nightly`).

**Comment by natew** [comment]
@bfricka removing an exported type export is a breaking change, that said I am one of the biggest proponents of Reanimated and the Software Mansion team and my comment was only made out of concern. I also haven't replaced the types yet myself, but in any case I'd need official word from the team on what they'd want to do before I made any contribution.

@tjzel thanks! Look forward to it.

Look forward to 3.5.0.

**Comment by efstathiosntonas** [comment]
leaving this here since the other issue is closed: 

@tjzel this issue is back on [0.72.4](https://github.com/facebook/react-native/releases/tag/v0.72.4), offending(?) commit: https://github.com/facebook/react-native/commit/2558c3d4f56776699602b116aff8c22b8bfa176a 

using: `3.5.0-nightly-20230813-f55e831b1`

![Screenshot 2023-08-14 at 13 44 03](https://github.com/software-mansion/react-native-reanimated/assets/717975/b1cc9597-7e69-4d9c-ab6a-dd9435224082)

**Comment by tjzel** [comment]
@efstathiosntonas Yeah, after I 'fixed' this error, and then 'fixed' it again I realised there are more entry points for it to break, so I decided to finally rewrite and [fix styles of Animated Components](https://github.com/software-mansion/react-native-reanimated/pull/4923).

If you want (I'd appreciate it) I can build a tarball from that branch so you could check if it fixes your issues - I think it should, since I added a bunch of type tests and it's passing them.

**Comment by efstathiosntonas** [comment]
@tjzel sure, post the link when ready!

**Comment by Crare** [comment]
after metro bundle load I get this error:
```

 BUNDLE  ./index.js 

error: node_modules/react-native-reanimated/src/reanimated2/threads.ts: <project-folder>/node_modules/react-native-reanimated/src/reanimated2/threads.ts: unknown node of type "TSInstantiationExpression" with constructor "Node"
```

using react-native-reanimated 3.4.2

**Comment by tjzel** [comment]
@efstathiosntonas https://github.com/software-mansion/react-native-reanimated/blob/%40tjzel/tarball/types/animated-style/react-native-reanimated-3.4.9.tgz, preferably download the file into your project and use `yarn add file:./react-native-reanimated-3.4.9.tgz`, don't mind the version, it's just to differentiate from others since if you use `3.4.0` it could try to install it from cache instead of this tarball. Thanks and let me know about TS errors you encounter!

**Comment by devoren** [comment]
When i use  `useAnimatedRef<Reanimated.ScrollView>();` i get this type error: 

`index.d.ts(154, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<AnimatedScrollViewClass> & Readonly<AnimateProps<AnimatedScrollViewProps>>'`

`helperTypes.d.ts(32, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<AnimatedScrollViewClass> & Readonly<AnimateProps<AnimatedScrollViewProps>>'`

<img width="560" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/99968085/0f824f66-dc9b-4a75-971e-92f9d490a51b">

**Comment by AntQwanlity** [comment]
still having `unknown node of type "TSInstantiationExpression" with constructor "Node"` issue after deleting node_modules and yarn.lock, anyone else ?

**Comment by tjzel** [comment]
Hi @thanksyouall. It seems upgrading Reanimated in your project has failed and not all the files got updated. I suggest you remove your `node_modules` and do `npm cache clean` or `yarn cache clean`. If this didn't help, remove your `package-lock.json` or `yarn.lock` and repeat the previous steps.

**Comment by Xmaxer** [comment]
This is probably related so I thought I'd throw this in here:

```javascript
 const animatedInputWidthStyle = useAnimatedStyle<ViewStyle>(() => {
    const nextWidth = `${interpolate(
      expandingAnimation.value,
      [0, 1],
      [30, 100],
    )}%`;

    return {
      width: nextWidth,
    };
  });
```

produces:

```
TS2345: Argument of type '() => { width: string; }' is not assignable to parameter of type '() => ViewStyle'.
Call signature return types '{ width: string; }' and 'ViewStyle' are incompatible.
The types of 'width' are incompatible between these types.
Type 'string' is not assignable to type 'DimensionValue | undefined'.
```

But assigning it to ViewStyle directly definitely works:

```
  const x: ViewStyle = {
    width: '100%',
  };
```

produces no errors.

**Comment by Xmaxer** [comment]
I also tried out the latest nightly build, to no avail.

**Comment by Xmaxer** [comment]
@tjzel  Ah I see, my fault for not checking the true definition of DimensionValue.
Thanks for the clarification and explanation, much appreciated.

**Comment by devoren** [comment]
@tjzel Hello! Unfortunately, it did not help, the same error: 
 `Type 'AnimatedRef<AnimatedScrollView>' is not assignable to type 'LegacyRef<AnimatedScrollViewClass> | undefined'.` 
 And
 `Type 'false | ViewStyle | { flex: number; } | RegisteredStyle<ViewStyle> | RecursiveArray<ViewStyle | Falsy | RegisteredStyle<ViewStyle>> | null' is not assignable to type 'StyleProp<AnimateStyle<MaybeSharedValue<StyleProp<ViewStyle>>>>'.`

**Comment by tjzel** [comment]
@devoren 
I think that when I told you to use nightly relevant fix wasn't actually in the nightly yet, I apologise for that. If it didn't work a few days back please check it again. If the error is actually from today, then I think something went wrong with the upgrade, as `style` prop being of type `StyleProp<AnimateStyle<MaybeSharedValue...` is no longer the case right now.

![Screenshot 2023-09-06 at 09 17 31](https://github.com/software-mansion/react-native-reanimated/assets/40713406/6c2de729-f097-475c-a350-c952316d6e86)
As you can see, there are no errors with more or less the use case you posted.

**Comment by tjzel** [comment]
@AuroPick This is unfortunately something we cannot do anything about. VSCode scans our library recursively and suggests to import some internal objects - it's a [known issue](https://github.com/microsoft/TypeScript/issues/35395) (thanks @satya164 for pointing me to it). Fortunately there is [a solution](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8-rc/#exclude-specific-files-from-auto-imports). All you need to do is to add to auto-import ignored directories `**/react-native-reanimated/lib`.

**Comment by tjzel** [comment]
@devoren There is still something wrong with your version - e.g. type `AdaptTransforms` is no longer used in Animated Styles. Try to remove your `node_modules`, then install the packages again. After that please use `npm why react-native-reanimated` or `yarn why react-native-reanimated` to see if you actually only have the nightly version installed.

**Comment by devoren** [comment]
@tjzel Thank you! You were right, after removing `node_modules` and reinstalling everything works!

**Comment by doomsower** [comment]
I'm getting this errors with `react-native-reanimated@3.5.2`:

```
export 'WorkletRuntime' (reexported as 'WorkletRuntime') was not found in './core' (possible exports: configureLayoutAnimations, configureProps, createWorkletRuntime, enableLayoutAnimations, getViewProp, initializeSensor, isConfigured, isReanimated3, makeMutable, makeRemote, makeShareable, makeShareableCloneRecursive, registerEventHandler, registerSensor, runOnJS, runOnUI, startMapper, stopMapper, subscribeForKeyboardEvents, unregisterEventHandler, unregisterSensor, unsubscribeFromKeyboardEvents)
ERROR in ../../node_modules/react-native-reanimated/lib/module/reanimated2/index.js 2:0-188
```

It appears that js file `node_modules/react-native-reanimated/lib/module/reanimated2/index.js` contains following line:

```js
export { runOnJS, runOnUI, createWorkletRuntime, WorkletRuntime, makeMutable, makeShareableCloneRecursive, isReanimated3, isConfigured, enableLayoutAnimations, getViewProp } from './core';
```

But `node_modules/react-native-reanimated/lib/module/reanimated2/core.js` does not export `WorkletRuntime`.

That's because it's exported as a type from `node_modules/react-native-reanimated/src/reanimated2/core.ts`:
```ts
export type { WorkletRuntime } from './runtimes';
```

Temporary reverting to v `3.3.0` fixes this issue

**Comment by tjzel** [comment]
Hi @doomsower. The issue was fixed in #5074 - for now I suggest using the nightly version of Reanimated (`yarn add react-native-reanimated@nightly`).

**Comment by efstathiosntonas** [comment]
@tjzel hi, after upgrading to 3.5.3 it throws this: 

`Extrapolation' cannot be used as a value because it was exported using 'export type'.
215       Extrapolation.CLAMP`

![Screenshot 2023-09-20 at 16 43 12](https://github.com/software-mansion/react-native-reanimated/assets/717975/f14caa12-c3ae-48e5-ae63-fd957989432f)

**Comment by tjzel** [comment]
Yes, I didn't check for enums, guess I have to release 3.5.4 soon, thanks for noticing it.

**Comment by tjzel** [comment]
@efstathiosntonas Just released `3.5.4` with relevant fix.

**Comment by erikkjernlie** [comment]
I am getting an error for missing semicolon in `FlatList.tsx`. I am using react native `0.69.12` and react-native-reanimated `3.5.4`. Anyone else experiencing this? 

![Simulator Screenshot - iPhone 15 - 2023-09-25 at 14 31 09](https://github.com/software-mansion/react-native-reanimated/assets/25264680/7fe0266f-0759-497a-b725-274ebb9d2466)

**Comment by tjzel** [comment]
@erikkjernlie I suggest bumping your minor version of React-Native

**Comment by MystDexter** [comment]
> I am getting an error for missing semicolon in `FlatList.tsx`. I am using react native `0.69.12` and react-native-reanimated `3.5.4`. Anyone else experiencing this?
> 
> ![Simulator Screenshot - iPhone 15 - 2023-09-25 at 14 31 09](https://user-images.githubusercontent.com/25264680/270353847-7fe0266f-0759-497a-b725-274ebb9d2466.png)

I am having the same issue. I am using react native 0.72.4 and react-native-reanimated 3.5.4

**Comment by satya164** [comment]
You may need to update your version of `metro-react-native-babel-preset` and `@babel/core`. And reset the metro cache (`yarn start --reset-cache`)

**Comment by devoren** [comment]
Hello! TypeError when i use AnimatedFlashList:

<img width="560" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/99968085/97701d3e-82e1-4960-b0f2-607726ec6135">

**Comment by tjzel** [comment]
@devoren it seems like your FlashList doesn't have its item's types but renderItem is typed. Could you show a code snippet that leads to it?

**Comment by devoren** [comment]
@tjzel Component:
```
const array = [1,2,3,4,5,6,7[
const renderItem: ListRenderItem<number> = ({ item }) => {
return (
	<LiveItem
		item={item}
	/>
);
};

const keyExtractor = (item: number, index: number) => {
return item.toString();
};

return (
<>
	<FocusAwareStatusBar barStyle={'light-content'} />
	<AnimatedFlashList
		data={array}
		renderItem={renderItem}
		keyExtractor={keyExtractor}
		estimatedItemSize={window.height}
		pagingEnabled
		decelerationRate={'normal'}
	/>
</>
);
```

**Comment by tjzel** [comment]
@devoren I'm afraid a definition for `AnimatedFlashList` is a must here.

**Comment by devoren** [comment]
@tjzel Sorry to bother you, after changing the type everything works here: 
before:
 `const AnimatedFlashList = Animated.createAnimatedComponent(FlashList);`
after: 
`const AnimatedFlashList = Animated.createAnimatedComponent(FlashList<number>);`

**Comment by tjzel** [comment]
@devoren No problems, I'm glad to see that it works since types for `createAnimatedComponent` can be troublesome at the moment!

**Comment by Rakha112** [comment]
I get an error when giving types for useAnimatedRef and Animated.FlatList,
I'm using Reanimated 3.5.2
```
const ref = useAnimatedRef<FlatList<any>>();
```
or
```
const ref = useAnimatedRef<Animated.FlatList<any>>();
```
and this is the error
```
No overload matches this call.
  Overload 1 of 2, '(props: AnimateProps<ReanimatedFlatListPropsWithLayout<any>> | Readonly<AnimateProps<ReanimatedFlatListPropsWithLayout<any>>>): ReanimatedFlatListClass<...>', gave the following error.
    Type 'AnimatedRef<FlatList<any>>' is not assignable to type 'LegacyRef<ReanimatedFlatListClass<any>> | undefined'.
      Type 'AnimatedRef<FlatList<any>>' is not assignable to type '(instance: ReanimatedFlatListClass<any> | null) => void'.
        Types of parameters 'component' and 'instance' are incompatible.
          Type 'ReanimatedFlatListClass<any> | null' is not assignable to type 'FlatList<any> | undefined'.
            Type 'null' is not assignable to type 'FlatList<any> | undefined'.
  Overload 2 of 2, '(props: AnimateProps<ReanimatedFlatListPropsWithLayout<any>>, context: any): ReanimatedFlatListClass<any>', gave the following error.
    Type 'AnimatedRef<FlatList<any>>' is not assignable to type 'LegacyRef<ReanimatedFlatListClass<any>> | undefined'.ts(2769)
```

**Comment by emil-malmgaard-rasmussen** [comment]
> I am getting an error for missing semicolon in `FlatList.tsx`. I am using react native `0.69.12` and react-native-reanimated `3.5.4`. Anyone else experiencing this?
> 
> ![Simulator Screenshot - iPhone 15 - 2023-09-25 at 14 31 09](https://user-images.githubusercontent.com/25264680/270353847-7fe0266f-0759-497a-b725-274ebb9d2466.png)

Having same issue: Reanimated 3.5.4 and RN 0.67.4

**Comment by pioner92** [comment]
The same issue 
`.../node_modules/react-native-reanimated/src/reanimated2/threads.ts: [Reanimated] Babel plugin exception: ReferenceError: unknown node of type "TSInstantiationExpression" with constructor "Object"`

"react-native-reanimated":"3.5.4"
"react-native": "0.70.13",

**Comment by dsound-zz** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/4645#issuecomment-1733700583

G

> > I am getting an error for missing semicolon in `FlatList.tsx`. I am using react native `0.69.12` and react-native-reanimated `3.5.4`. Anyone else experiencing this?
> > ![Simulator Screenshot - iPhone 15 - 2023-09-25 at 14 31 09](https://user-images.githubusercontent.com/25264680/270353847-7fe0266f-0759-497a-b725-274ebb9d2466.png)
> 
> Having same issue: Reanimated 3.5.4 and RN 0.67.4

I'm also getting the same error. Unable to use react-native-reanimated

react-native: 0.67.5
react-native-reanimated: 3.5.4

**Comment by tenShotsMiss** [comment]
> I get an error when giving types for useAnimatedRef and Animated.FlatList, I'm using Reanimated 3.5.4
> 
> ```
> const ref = useAnimatedRef<FlatList<any>>();
> ```
> 
> or
> 
> ```
> const ref = useAnimatedRef<Animated.FlatList<any>>();
> ```
> 
> and this is the error
> 
> ```
> No overload matches this call.
>   Overload 1 of 2, '(props: AnimateProps<ReanimatedFlatListPropsWithLayout<any>> | Readonly<AnimateProps<ReanimatedFlatListPropsWithLayout<any>>>): ReanimatedFlatListClass<...>', gave the following error.
>     Type 'AnimatedRef<FlatList<any>>' is not assignable to type 'LegacyRef<ReanimatedFlatListClass<any>> | undefined'.
>       Type 'AnimatedRef<FlatList<any>>' is not assignable to type '(instance: ReanimatedFlatListClass<any> | null) => void'.
>         Types of parameters 'component' and 'instance' are incompatible.
>           Type 'ReanimatedFlatListClass<any> | null' is not assignable to type 'FlatList<any> | undefined'.
>             Type 'null' is not assignable to type 'FlatList<any> | undefined'.
>   Overload 2 of 2, '(props: AnimateProps<ReanimatedFlatListPropsWithLayout<any>>, context: any): ReanimatedFlatListClass<any>', gave the following error.
>     Type 'AnimatedRef<FlatList<any>>' is not assignable to type 'LegacyRef<ReanimatedFlatListClass<any>> | undefined'.ts(2769)
> ```

I'm also getting this one. 

"react-native": "0.72.5",
"react-native-reanimated": "^3.5.4"

**Comment by tjzel** [comment]
AnimatedRef & FlatList error will be fixed with #5308.

**Comment by thongquach** [comment]
> You may need to update your version of `metro-react-native-babel-preset` and `@babel/core`. And reset the metro cache (`yarn start --reset-cache`)

Hi @satya164, which versions should I upgrade till? I'm still facing this error.

> [Reanimated] Babel plugin exception: Error: Unknown node type: "TSInstantiationExpression"

**Comment by manjeetcars24** [comment]
missing semicolon in FlatList.tsx error is still coming on the latest version (3.5.4) + RN(0.70.12). Anyone able to have a proper fix for it ?

**Comment by dmontag23** [comment]
It seems the `toHaveAnimatedStyle` method on the `jest` object throws a `Property 'toHaveAnimatedStyle' does not exist on type 'Matchers...` error. However, the error seems to only be a typescript error as the test still runs without any issues and passes as expected.

**Comment by dmontag23** [comment]
It seems the `toHaveAnimatedStyle` method on the `jest` object throws a `Property 'toHaveAnimatedStyle' does not exist on type 'Matchers...` error. However, the error seems to only be a typescript error as the test still runs without any issues and passes as expected.

It seems this happens because I'm explicitly importing `expect` from `@jest/globals`, but `node_modules/react-native-reanimated/lib/typescript/reanimated2/jestUtils.d.ts` does not extend explicit `@jest/globals` `expect` matchers. For an example of how this can be done, check out [this file](https://github.com/callstack/react-native-testing-library/blob/ab679c90755b12c8ead9b3b7ff05b396cee2d659/src/matchers/extend-expect.d.ts#L36) from the react testing library.

I fixed this by adding a `reanimated.d.ts` file to my project with the following contents: 
```
// Explicit `@jest/globals` `expect` matchers.
declare module '@jest/expect' {
  interface Matchers<R extends void | Promise<void>> {
      toHaveAnimatedStyle(style: Record<string, unknown>[] | Record<string, unknown>, config?: {
          shouldMatchAllProps?: boolean;
      }): R;
  }
}
```

But something similar should be automatically included in the types for reanimated.

**Comment by tjzel** [comment]
@dmontag23 We will look into it.

**Comment by tjzel** [comment]
Closing this issue since collective TS errors stemming from 3.4.0 are resolved. Please open new issues for new TS errors.

As for those semicolons @manjeetcars24, try upgrading your TypeScript and maybe React Native.

**Comment by AntQwanlity** [comment]
Still having `TSInstantiationExpression` in 3.6.1

**Comment by VladSt90** [comment]
> Still having `TSInstantiationExpression` in 3.6.1

The same.
Latest version of react-native

**Comment by chriskrogh** [comment]
want to flag that I ran into this issue after creating a managed expo app in a monorepo:
```
[Reanimated] Babel plugin exception: ReferenceError: unknown node of type "TSInstantiationExpression" with constructor "Node"
```
the root cause was because I moved the `typescript` dev dependency to the root `package.json` instead of each individual package's `package.json`. removing from the root into each package's `devDependencies` solved the issue for me

**Comment by patlux** [comment]
> [Reanimated] Babel plugin exception: ReferenceError: unknown node of type "TSInstantiationExpression" with constructor "Node"

Had to remove a outdated ui library that used a older react-native-reanimated version. That's fixed it for me.

Run `npm why react-native-reanimated` to check which dependencies are uses react-native-reanimated.

**Comment by JasonOuyang21** [comment]
> > I am getting an error for missing semicolon in `FlatList.tsx`. I am using react native `0.69.12` and react-native-reanimated `3.5.4`. Anyone else experiencing this?
> > ![Simulator Screenshot - iPhone 15 - 2023-09-25 at 14 31 09](https://user-images.githubusercontent.com/25264680/270353847-7fe0266f-0759-497a-b725-274ebb9d2466.png)
> 
> Having same issue: Reanimated 3.5.4 and RN 0.67.4
This has worked for me 

diff --git a/node_modules/react-native-reanimated/src/reanimated2/component/FlatList.tsx b/node_modules/react-native-reanimated/src/reanimated2/component/FlatList.tsx
index 3687f47..bed6f4c 100644
--- a/node_modules/react-native-reanimated/src/reanimated2/component/FlatList.tsx
+++ b/node_modules/react-native-reanimated/src/reanimated2/component/FlatList.tsx
@@ -93,5 +93,5 @@ const styles = StyleSheet.create({
   horizontallyInverted: { transform: [{ scaleX: -1 }] },
 });
 
-export type ReanimatedFlatList<T> = typeof ReanimatedFlatListClass<T> &
+export type ReanimatedFlatList<T> = ReanimatedFlatListClass<T> &
   FlatList<T>;

**Comment by ilterugur** [comment]
I also get this error when i'm integrating react native to a monorepo while using this package. 

MacOS
react-native-reanimated version: 3.16.1
infinitered ignite commit number: 5ea9c7a
bun version: 1.2.4
turborepo version: 2.4.4

**Comment by tjzel** [comment]
@ilterugur Take a took at #5883
