### ISSUE TITLE
wrong path resolution of babel plugin when metro config is not in app root

### ISSUE THREAD

**Issue by macrozone** [software-mansion/react-native-reanimated#4651]
### Description

https://dev.to/dannyhw/multiple-entry-points-for-react-native-storybook-4dkp provides a fix to switch between storybook and the normal app without accidentially bundling both in the production app.

this is a good approach.

but however as it is also described in the comment, this aproach does not work if you use react-native-reanimated, because there is something wrong with the module resolution.

### Steps to reproduce

1. create new react-native project (not expo)
2. install react-native-reanimated and the babel plugin
3. follow https://dev.to/dannyhw/multiple-entry-points-for-react-native-storybook-4dkp to have a different metro config in a subfolder
4. start the app, y

### Snack or a link to a repository

not applicable, since its not a expo problem

### Reanimated version

3.1.0

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tjzel** [comment]
This seems like a duplicate of #4561. Could you please:

1. Check if the issue appears with nightly (`yarn add react-native-reanimated@nightly`) build? Make sure to rerun the app with `yarn start --reset-cache`.
2. If the error persists, could you at least post a screenshot of it? It'd be much simpler to attempt to reproduce the error if I know what I'm looking for.
