### ISSUE TITLE
Support for react-native-macos is missing ever since version 3

### ISSUE THREAD

**Issue by hsjoberg** [software-mansion/react-native-reanimated#4659]
### Description

Hey guys.
Ever since version 2 of react-native-reanimated, support for react-native-macos seems to have been dropped.

In version 1, it would gracefully fallback via `ReanimatedModule.macos.js` -> `ReanimatedModuleCompat.js`.

https://github.com/software-mansion/react-native-reanimated/blob/dd5e716998a7a840cca0d624242f027a889a9cc9/src/ReanimatedModule.macos.js#L1-L3

Would it be possible to restore this?

### Steps to reproduce

Just try building a react-native-macos project with react-native-reanimated.

```
 ERROR  Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
  - not rebuilding the app after installing or upgrading Reanimated
  - trying to run Reanimated on an unsupported platform
  - running in a brownfield app without manually initializing the native library
```

### Snack or a link to a repository

N/A

### Reanimated version

3.3.0

### React Native version

0.72.1

### Platforms

macOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by hsjoberg** [comment]
Actually, I see that there is compat mode in version 2, but I have never gotten that one to work.

**Comment by tomekzaw** [comment]
Hey @hsjoberg, thanks for submitting this issue.

> Ever since version 2 of react-native-reanimated, support for react-native-macos seems to have been dropped.

That's actually true, we don't support macOS (yet). However, this feature is definitely on our roadmap.

> Actually, I see that there is compat mode in version 2, but I have never gotten that one to work.

I think in this case, as a workaround, it might be possible to enable web implementation which is JS-only (so-called JSReanimated). Please modify `shouldBeUseWeb` implementation in `PlatformChecker.ts` so that it returns `true` and let me know if it works for you.

**Comment by hsjoberg** [comment]
Thank you so much for your reply @tomekzaw.

Yes, modifying `shouldBeUseWeb` to also check for macOS helped.
But `nativeShouldBeMock` also needs to be changed, because `configureProps` in `core.ts` tries to use the native module:

https://github.com/software-mansion/react-native-reanimated/blob/c35c122eadae6a4a8027f82368e958f0e9ae8359/src/reanimated2/core.ts#L249-L252

After this, the simple [box demo](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/animations) from the v3 docs works.

Unfortunately, I could not get everything to work for my project -- specifically @react-navigation/drawer, which uses react-native-reanimated, crashes.

```
ERROR  TypeError: undefined is not an object (evaluating 'this.view.style['touchAction'] = 'none'')

This error is located at:
    in PanGestureHandler (created by Drawer)
    in Drawer (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
```

But I am not sure what this is about or where the error is. Regardless, I've opened a pull request for that adds back react-native-macos support #4669.

**Comment by tomekzaw** [comment]
Hey @hsjoberg, thanks for your investigation and submitting the PR!

**Comment by Latropos** [comment]
Closing since we have already merged https://github.com/software-mansion/react-native-reanimated/pull/4912 and added support for react-native-macos 🥳

**Comment by hsjoberg** [comment]
@kaiyes Yes, I've gotten it to work. Make sure you're running the react-navigation 7 alphas, because they have explicit checks for macos to make sure gesture handler is not enabled.
https://github.com/react-navigation/react-navigation/blob/adbf863c148a6d389a69745b8a88c0c706ebfb4c/packages/react-native-drawer-layout/src/views/Drawer.tsx#L61-L63

I currently have a mixture of 7 alpha and 6 because 7 alpha has been a bit buggy in some of their libs, but you may could use them all in depending on your situation.
https://github.com/hsjoberg/blixt-wallet/blob/743c0ecc1a95d22b67679c0ec28fcdf4ae6e7d47/package.json#L66-L70

**Comment by kaiyes** [comment]
I was greeted with many errors on ios with  @react-navigation/drawer@7.0.0-alpha.2. I guess I will let it go for now. Drawer in macos is not worth the hassle

![Uploading simula
![simulator_screenshot_6A79BAB9-D52E-459F-B127-A0BAEA8C55C9](https://github.com/software-mansion/react-native-reanimated/assets/5293742/68b7b333-8051-4a03-9e49-c99fa8b7cad1)

![simulator_screenshot_FAC3B84D-5DF7-48A1-A0E8-3709A3143BF1](https://github.com/software-mansion/react-native-reanimated/assets/5293742/94b2fccc-e203-433f-8f4f-5beabfa0a2f4)
tor_screenshot_D386AE48-45E3-4CD7-92F8-3AD33CBE19C9.png…]()

**Comment by hsjoberg** [comment]
@kaiyes Yeah the one "cannot read 'bold' of undefined is something I am running into too.
Trying to figure out what's wrong regarding that one.
As aforementioned it's possible to get things working by a mixture of react-navigation 6 and 7. But yeah just waiting for stable 7 is probably better in order to spare headache.
