### ISSUE TITLE
The native part of Reanimated doesn't seem to be initialized

### ISSUE THREAD

**Issue by cheynewallace** [software-mansion/react-native-reanimated#4663]
### Description

After upgrading to react-native `0.72.1` and react-native-animated `3.3.0` im no longer able to start the app in dev, with metro server throwing the following error:

```
Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
  - not rebuilding the app after installing or upgrading Reanimated
  - trying to run Reanimated on an unsupported platform
  - running in a brownfield app without manually initializing the native library
 ```

I've spent half a day on this error and come up with nothing, im stumped.   

The error im seeing is on IOS,  im not very familiar with the IOS native files so im not really sure where to look here.   This was working on version `2.14.4`. 

Have been through all the recommended steps
- Triple checked bable.config.js
- Cleared caches, rebuilt pods
- Even wiped node_modules, cleared cached and rebuilt again.
- Tried latest nightly `3.4.0` build
- Rolling back a version to 3.2.0

Same issues..  What am I missing here?

index.js
```
import "react-native-gesture-handler";
import { AppRegistry } from "react-native";
import App from "./App";

AppRegistry.registerComponent('main', () => App);
```

babel.config.js
```
module.exports = function (api) {
	api.cache(true);
	return {
		presets: ["module:metro-react-native-babel-preset"],
		plugins: [
			"@babel/plugin-proposal-unicode-property-regex",
			"react-native-reanimated/plugin",
		],
	};
};
```

Let me know if you need to see other files

### Steps to reproduce

1. Start dev server `react-native start --reset-cache`
2. Build app `yarn ios`
3. App boots, starts loading bundle, crashes with error

### Snack or a link to a repository

Sorry I dont have one..

### Reanimated version

3.3.0

### React Native version

0.72.1

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @cheynewallace, thanks for submitting this issue. Is your AppDelegate written in Swift by chance?

**Comment by cheynewallace** [comment]
Thanks for responding @tomekzaw 

So, the AppDelegate is not written in Swift, it's a .mm file. 

I did spend a long time however combing through the React Native template application, and the IOS specific files found at: https://github.com/react-native-community/rn-diff-purge/blob/version/0.72.1/RnDiffApp/ios/RnDiffApp

I did find a few differences between ours and what I saw there. I believe we possibly missed a few things during previous updates.   I went through everything line by line and updated ours to match,  as a result this error is now resolved.

To anyone else hitting this error, it's an odd one as the app builds just fine and appears to be something to do at the React level (metro reports it).  I would suggest going through the diff docs or using the template app in the link above to match everything up.

Ill close this off now, thanks @tomekzaw

**Comment by tomekzaw** [comment]
@cheynewallace Thanks for the explanation!

**Comment by nikolal** [comment]
@cheynewallace 
Can you tell us what differences did you find?
Or at least what files to check?

I am having the same issue.

**Comment by cheynewallace** [comment]
Hey @nikolal 

Sure, I cant say for sure what did it, but im pretty sure it was a combination of updating the `AppDelegate.mm` and AppDelegate.h` files.  
A year or so ago we ejected from an expo app and have somewhat been cleaning up bits and peices ever since.

I based my updates on this 0.72.1 diffApp: https://github.com/react-native-community/rn-diff-purge/tree/version/0.72.1/RnDiffApp

For starters, I noticed we had `AppDelgate.m` not `.mm`, not sure if that matters, but that's what the latest template says it should be.

Our `AppDelegate.h` also had some different content, likely from a previous versions standard as I don tthink this is a commonly changed file.   
I changed ours to match this: https://github.com/react-native-community/rn-diff-purge/blob/version/0.72.1/RnDiffApp/ios/RnDiffApp/AppDelegate.h

Our AppDelegate.mm cotent was also quite different, with a bunch of outdated Flipper setup lines in there, I removed all those as it's part of framework by default now.

I based our new AppDelegate on this: https://github.com/react-native-community/rn-diff-purge/blob/version/0.72.1/RnDiffApp/ios/RnDiffApp/AppDelegate.mm

Our new AppDelegate.mm is close to this and now looks like 

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

#import "RNSplashScreen.h"

@interface AppDelegate () <RCTBridgeDelegate>
  @property (nonatomic, strong) NSDictionary *launchOptions;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"main";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (RCTBridge *)initializeReactNativeApp
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:0.13 green:0.13 blue:0.13 alpha:1];// Change the background colour of the app starting up

  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  // Set the splash screen to show by default.
  [RNSplashScreen show]; 

  return bridge;
 }

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

@end
```

I didnt change anything in React land before it started working, so I think your problem will be around these files too..

Our index.js is stock standard 

```
import { AppRegistry } from "react-native";
import App from "./App";
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

Once this error cleared, I did have to wrap our app in a `<GestureHandlerRootView style={{ flex: 1 }}>`  at the root level to clear a different error, although the docs on this on the software-mansion website were pretty clear,

I hope that helps.

**Comment by nikolal** [comment]
Hey @cheynewallace ,

Thanks for your help.

It seems my issue is something else since I had those files almost exact copy as the diffApp.

I also double checked my upgrade steps.

Thanks once again!

**Comment by nikolal** [comment]
I managed to fix it by running:

`npx react-native-clean-project`

And clearing all IOS files and Pods.

**Comment by cheynewallace** [comment]
Good to hear it was an easy fix for you, it was definately more than that for me,  I must of cleared every cache, the entire node_modules folder etc a dozen times in frustration.

**Comment by dspacejs** [comment]
After installing the library, I ran `expo run:ios` and this fixed the error for me.

**Comment by NikTheGeek1** [comment]
> hecked my upgrade steps.

Just confirming that this solution worked for me too. I didn't change the file extension from '.m' to '.mm', but I updated the content of the file using the resources provided by @cheynewallace. Thanks a lot, it would have taken me more time than it should to solve this on my own ✌️

**Comment by cheynewallace** [comment]
Amazing @NikTheGeek1 🙂
Happy to hear it helped save you some time!

**Comment by yxwandroid** [comment]
> 
ios端使用的是 swift

**Comment by snapre** [comment]
I am having the same issue.

**Comment by artemis-prime** [comment]
This is still happening for me with rn 0.72.3 and 3.4.2.  Even after trying your fix @cheynewallace .

And how is this a "fix"?  

Also, when you say "your" version of the file, do you mean the one in the module, or the one in the app?  I tried modifying my version to basically yours (minus splash screen), and still got the error.

So could you please clarify what the *client app* needs to do to resolve this?

**Comment by SanjaySargam** [comment]
> This is fixed with the combo of RN 0.72.x and RNR 3.4.x So no need to modify any app delegate files.
> 
> And don't forget to do `pod install` and also to start metro with --reset-cache to pick up the new version of the babel plugin

How can I install pod

**Comment by SanjaySargam** [comment]
> I managed to fix it by running:
> 
> `npx react-native-clean-project`
> 
> And clearing all IOS files and Pods.

@nikolal  Can you please explain in detail ? I am also facing with the same error

**Comment by ilmatic** [comment]
I'm also still seeing this issue. Have spent several hours troubleshooting and still getting this error. I'm using NX monorepo:

- react-native: 0.72.3
- react-native-reanimated: 3.4.2
- @react-navigation/native: 6.1.7
- @react-navigation/drawer: 6.6.3

Have run react-native-project-clean. Have manually cleaned. Have restarted computer. Have deleted node_modules and cleared npm cache. Have deleted pods and reinstalled. Have cleared watchman and metro cache. I've gone into xcworkspace and manually cleaned and rebuilt. I've reset all content and settings from my iOS simulator. This project is brand new, just generated using nx-create-workspace this morning. It has no other code in it except trying to create a drawer navigator.

I've peeked into AppDelegate.h and it's already using RCTDelegate instead of UIResponder. Still can't get past this error. Can someone reopen this issue?

**Comment by ilmatic** [comment]
Stripped this back even further to just using react-native-drawer-layout, no navigation. Created 2 brand new projects: one with Bare React Native, and one with NX React Native. Followed exact same setup instructions step-by-step. Bare React Native works, NX React Native has this error. 

So it definitely seems NX related, but can't for the life of me think what in this regard would be different and cause this. AppDelegate files are identical with the exception of self.moduleName and jsBundleURLForBundleRoot, which are both appropriate. 

Both builds work if I pull out the <Drawer> component that uses reanimated.

**Comment by ilmatic** [comment]
SUCCESS!

It is most certainly Nx related. My knowledge of dependency loading is not the deepest so this is a bit of a guess, but Nx doesn't seem pick up on peer dependencies of implicit dependencies (the ones it establishes by analyzing source code). The reason this was a problem was that Nx's `sync-deps` step didn't update the project's package.json with the `react-native-reanimated: "*"` entry that would signal Nx React Native to scan the package and install the corresponding Pods if necessary. So I didn't have a Reanimated Pod at all.

So if you use Nx and run into this, add

```
{
    "dependencies": {
        "react-native-reanimated": "*"
    }
}
```

to the package.json of your target. Then run the `npx nx pod-install [target]`, and you should be good to go!

**Comment by SanjaySargam** [comment]
@ilmatic 

> npx nx pod-install [target]a

Here what is `target`

**Comment by ilmatic** [comment]
[target] is the name of the Nx app that you're building in React Native. So in my Nx workspace, which is called `my-app`, I have an app target called `mobile`, which was created using `npx nx g @nx/react-native:app mobile`. It's basically my React Native app. 

So for me, I would run `npx nx pod-install mobile`

**Comment by ilmatic** [comment]
Note that `npx nx pod-install` would only be an appropriate command to use if you're working on a Nx monorepo. If you have a Bare React Native project, it'd be `npx pod-install ios`. I believe Expo has its own pod install command but I don't know it off-hand.

**Comment by SanjaySargam** [comment]
> Note that `npx nx pod-install` would only be an appropriate command to use if you're working on a Nx monorepo. If you have a Bare React Native project, it'd be `npx pod-install ios`. I believe Expo has its own pod install command but I don't know it off-hand.

I am using react-native cli instead of expo

**Comment by martinezguillaume** [comment]
@nikolal 
> npx react-native-clean-project

Wow, many many thanks, I didn't know this package but it works very very well.
My app is now building

my stack :
```json
"react-native": "0.72.4",
"react-native-reanimated": "^3.4.2",
```

**Comment by nikolal** [comment]
> @nikolal Can you please explain in detail ? I am also facing with the same error

Hey @SanjaySargam ,

Just run `npx react-native-clean-project` in terminal. 
It will ask you to install the package and you can just follow the steps. Just answer `Y` for all IOS steps and `N` to all Android steps unless you want to clean Android project too.

**Comment by olasamuel486** [comment]
Go too your  babel config. js  file  and   add These to you code     plugins : [ 'react-native-reaanimated/plugins']
 and go back  too you  Terminal  and restart  with these command  line 
npm start --  ---reset--cache

**Comment by marioposada** [comment]
I'm working on:

```
"react-native": "0.70.13",
"react-native-reanimated": "^3.4.2",
```

and had to downgrade reanimated to : 3.0.0 and fix my issue!

**Comment by yanni-fe** [comment]
> Hey @cheynewallace, thanks for submitting this issue. Is your AppDelegate written in Swift by chance?

I am facing this issue now. And my AppDelegate is written in Swift and doesn't confirm to RCTAppDelegate. Since I just add RN to my native app. 

I find in the document "If you are using Reanimated in a brownfield app, make sure to initialize the native library manually." 

my question is how to initialize the native library manually?

**Comment by davidwinograd1** [comment]
Any solution?

**Comment by maxwelljmckee** [comment]
> After installing the library, I ran `expo run:ios` and this fixed the error for me.

Retweet

**Comment by monilraycha** [comment]
I just solved this error by removing build files and clean the Gradle then rebuild the project it will run

**Comment by Dajust** [comment]
On Android
"react-native": "0.79.2"

Downgrading from 3.18.0 to 3.17.5 fixed this for me.

> > I'm working on:
> > ```
> > "react-native": "0.70.13",
> > "react-native-reanimated": "^3.4.2",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and had to downgrade reanimated to : 3.0.0 and fix my issue!
> 
> same downgrading to 3.0.0 worked for me (i tried many things, but downgrading version only thing that worked)

**Comment by jaketoolson** [comment]
This error is the death of me.

```{
  "name": "@go/mobile",
  "main": "index.tsx",
  "version": "4.0.0",
  "scripts": {
    "eas-build-pre-install": "./eas-build-pre-install.sh",
    "android": "expo run:android",
    "android:uninstall": "adb uninstall com.esource42.getoutpass",
    "android:verify-auth0": "./scripts/verify-auth0-config.sh",
    "android:clean": "cd android && ./gradlew clean && cd ..",
    "build:android:dev": "npx eas build -e development -p android --clear-cache",
    "build:android:preview": "npx eas build --profile preview -p android --clear-cache",
    "build:android:preview-dev": "npx eas build --profile preview-dev -p android --clear-cache",
    "build:android:preview:run": "npx eas build:run --profile preview --platform android --clear-cache",
    "build:android:prod": "npx eas build -e production -p android --clear-cache",
    "build:check": "npx expo install --check",
    "build:ios:dev": "npx eas build:dev -e development -p ios --clear-cache",
    "build:ios:preview": "npx eas build --profile preview -p ios --clear-cache",
    "build:ios:preview-dev": "npx eas build --profile preview-dev -p ios --clear-cache",
    "build:ios:preview:run": "npx eas build:run --profile preview --platform ios --clear-cache",
    "build:ios:prod": "npx eas build -e production -p ios --clear-cache",
    "clean": "rm -rf .expo node_modules",
    "device:create": "eas device:create",
    "expo:start": "npx expo start --clear",
    "format": "prettier --write \"./**/*.{ts,js,tsx}\"",
    "ios": "expo run:ios",
    "logs:ios": "xcrun simctl spawn booted log stream --predicate 'process == \"GetOut\" OR processImagePath CONTAINS \"GetOut\"' --style compact --color always",
    "logs:ios:all": "xcrun simctl spawn booted log stream --style compact --color always",
    "metro:kill": "pkill -f expo && pkill -f metro || true",
    "metro:reset": "npm start -- --reset-cache",
    "prebuild": "npx expo prebuild",
    "prep": "npm run clean && npm install && npm run prebuild",
    "start": "npx expo start  --clear --dev-client",
    "submit:android:dev": "eas submit --platform android --profile development",
    "submit:android:prod": "eas submit --platform android --profile production",
    "submit:ios:dev": "eas submit --platform ios --profile development",
    "submit:ios:prod": "eas submit --platform ios --profile production",
    "sync:version": "eas build:version:sync"
  },
  "dependencies": {
    "@babel/runtime": "^7.26.0",
    "@expo/config-plugins": "^10.1.2",
    "@expo/vector-icons": "14.1.0",
    "@gop/shared": "file:../shared",
    "@kichiyaki/react-native-barcode-generator": "^0.6.7",
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-clipboard/clipboard": "^1.16.3",
    "@react-native-community/datetimepicker": "8.4.1",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native-community/slider": "^5.0.1",
    "@react-native-vector-icons/ionicons": "^7.4.0",
    "@react-native/assets-registry": "^0.76.6",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/drawer": "^7.1.1",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/stack": "^7.1.1",
    "@sentry/react-native": "7.3.0",
    "@shopify/react-native-skia": "v2.0.0-next.4",
    "@tanstack/react-query": "^5.59.16",
    "@types/lodash": "^4.17.15",
    "axios": "^1.7.7",
    "babel-plugin-module-resolver": "^5.0.2",
    "date-fns": "^4.1.0",
    "expo": "53.0.23",
    "expo-asset": "11.1.7",
    "expo-blur": "14.1.5",
    "expo-constants": "17.1.7",
    "expo-contacts": "14.2.5",
    "expo-crypto": "~14.1.5",
    "expo-dev-client": "5.2.4",
    "expo-font": "13.3.2",
    "expo-haptics": "~14.1.4",
    "expo-image-manipulator": "13.1.7",
    "expo-image-picker": "~16.1.4",
    "expo-linking": "7.1.7",
    "expo-location": "18.1.6",
    "expo-splash-screen": "0.30.10",
    "expo-system-ui": "5.0.11",
    "expo-web-browser": "14.2.0",
    "formik": "^2.4.6",
    "lodash": "^4.17.21",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-native": "0.79.5",
    "react-native-actions-sheet": "^0.9.7",
    "react-native-auth0": "^4.6.0",
    "react-native-edge-to-edge": "^1.6.0",
    "react-native-fast-confetti": "^1.1.1",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-keychain": "^10.0.0",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-maps": "1.20.1",
    "react-native-mmkv": "^2.12.2",
    "react-native-paper": "^5.14.5",
    "react-native-qrcode-svg": "^6.3.15",
    "react-native-range-slider-expo": "^1.4.3",
    "react-native-reanimated": "3.17.4",
    "react-native-reanimated-carousel": "4.0.3",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "4.11.1",
    "react-native-svg": "^15.11.2",
    "react-native-uuid": "^2.0.3",
    "react-native-vector-icons": "^10.2.0",
    "react-native-web": "~0.20.0",
    "react-native-webview": "13.13.5",
    "yup": "^1.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.26.0",
    "@types/react": "~19.0.14",
    "@types/react-native-linear-gradient": "^2.4.0",
    "@types/react-test-renderer": "^18.3.0",
    "@types/uuid": "^10.0.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.2.1",
    "globals": "^15.14.0",
    "react-test-renderer": "19.0.0",
    "typescript": "~5.8.3"
  },
  "pnpm": {
    "overrides": {
      "expo-image-loader": "5.0.0"
    }
  },
  "private": true
}
```

Adding this directly to  `MainApplication.kt` 
```import com.swmansion.reanimated.ReanimatedPackage``` 

solves it

**Comment by mahammad72** [comment]
"react-native": "0.83.1",    
"react-native-reanimated": "^4.2.1",
    "react-native-worklets": "^0.7.1",

@cheynewallace
in my case android working fine but when i going to ios then it give me an error like 
`[runtime not ready]: ReanimatedError: [Reanimated] Native part of Reanimated doesn't seem to be initialized.
See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#native-part-of-reanimated-doesnt-seem-to-be-initialized for more details.`

import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
import GoogleMaps

@main
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ReactNativeDelegate?
  var reactNativeFactory: RCTReactNativeFactory?

  func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    

    
    let delegate = ReactNativeDelegate()
    let factory = RCTReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "end2EndNew",
      in: window,
      launchOptions: launchOptions
    )

    return true
  }

}

class ReactNativeDelegate: RCTDefaultReactNativeFactoryDelegate {
  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}
