### ISSUE TITLE
SnapTo works only on double click 

### ISSUE THREAD

**Issue by cedricsandars** [software-mansion/react-native-reanimated#467]
**Issue:**

I am using the Notification Panel example for one of my projects. I am trying to snap the panel to the initial state when we click on the close button. This works when I double click the button but the single click is not triggering the action.

**Code:**

```
...other code
export default class App extends Component {
notif = React.createRef()
render() {
    return (
      <View style={styles.container}>
...other code
        <Interactable.View
            ref={this.notif}
            verticalOnly={true}
            snapPoints={[
              { y: 0, tension: 0, damping: 1 },
              { y: -Screen.height + 80 },
            ]}>
...other code
            <Button title="Close" onPress={() => this.notif.current.snapTo({index: 1})} ></Button>
       </Interactable.View>
     }
}
...other code
```

![snap](https://user-images.githubusercontent.com/2046221/68702199-64b12200-05ae-11ea-9dd7-540495311e23.gif)
FYI-- I was doing double click during the last few seconds where the panel goes to correct snap.

Let me know if I am doing something wrong.

**Comment by wilau2** [comment]
I experience the same issue on the initial rendering of the panel only.

Step to reproduce
- Set verticalOnly={true}
- The first button click nothing happens 
- The second button click it opens

I managed to fix it by removing the `verticalOnly={true}` property but now the panel can move on the x axis as well.

**Comment by wilau2** [comment]
I hardcoded this: 
![image](https://user-images.githubusercontent.com/5473183/69819085-26ca1580-11cc-11ea-9cda-7ae23f4fbf31.png)

**Comment by wilau2** [comment]
Nevermind the real fix is this: 
![image](https://user-images.githubusercontent.com/5473183/69885991-e93db900-12ad-11ea-8a85-3e2ebc8fa797.png)

if you were using verticalOnly of horizontalOnly you would experience the multiple click needed on first render.

**Comment by cedricsandars** [comment]
@wilau2 - The fix worked. Thanks a lot!!

**Comment by wilau2** [comment]
@cedricsandars  My fix was not the right fix, it just make the clock run all the time. 

I found the right fix: 
https://github.com/software-mansion/react-native-reanimated/issues/182#issuecomment-519632308

**Comment by cedricsandars** [comment]
@wilau2 - Thanks for helping again. Love the way how open source community works to help others even without even expecting anything in return :)
