### ISSUE TITLE
Easing was renamed to EasingNode in Reanimated 2. Please use EasingNode instead

### ISSUE THREAD

**Issue by gwonsuji** [software-mansion/react-native-reanimated#4670]
### Description

I'm trying to upgrade from react-native 0.64.3 to react-native 0.68.6 using react native cli.
Accordingly, we changed the react-native-reanimated from 1.7.0 to 2.8.0.

And I changed Easy to EasyNode in the source code.

But when it's actually running on Android, it keeps showing me the phrase, "Easing was renamed to EasyNode in Reinforced 2. Please use EasyNode instead."

ex)
import Animated, { Easing, Value } from 'react-native-reanimated';
=> import Animated, { EasingNode, Value } from 'react-native-reanimated';

const _openDrawer = useCallback(() => {
    Animated.timing(drawerValue, {
      toValue: 0,
      duration: 300,
      easing: Easing.ease,
      useNativeDriver: true,
    }).start();
  }, [drawerValue]);
=>
const _openDrawer = useCallback(() => {
    Animated.timing(drawerValue, {
      toValue: 0,
      duration: 300,
      easing: EasingNode.inOut(EasingNode.ease),
      useNativeDriver: true,
    }).start();
  }, [drawerValue]);

### Steps to reproduce

I'll put in the regeneration code tomorrow. I'll fix it by putting in the code.

### Snack or a link to a repository

I'll put in the regeneration code tomorrow. I'll fix it by putting in the code.

### Reanimated version

2.8.0

### React Native version

0.68.6

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

Expo bare workflow

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Latropos** [comment]
🤔 It looks like if you have build android with old code. Have you already fixed the problem?

**Comment by piaskowyk** [comment]
The problem is because you are mixing Reanimated v1 API with v2 API, I recommend to check out the new documentation - https://docs.swmansion.com/react-native-reanimated/docs/animations/withTiming
