### ISSUE TITLE
React Native Error - The native part of Reanimated doesn't seem to be initialized

### ISSUE THREAD

**Issue by Ritik1330** [software-mansion/react-native-reanimated#4673]
### Description

when i use react drowar navigation and setup the reanimated i got this error 

ERROR  [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
  - not rebuilding the app after installing or upgrading Reanimated
  - trying to run Reanimated on an unsupported platform
  - running in a brownfield app without manually initializing the native library
 
ERROR  Error: Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes
 
ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 
ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.

### Steps to reproduce

this issu with reactdrower navigation

### Snack or a link to a repository

https://stackoverflow.com/questions/76265185/react-native-error-the-native-part-of-reanimated-doesnt-seem-to-be-initialize

### Reanimated version

3.3.0

### React Native version

7.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

android 8

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@Ritik1330 have you seen #4663?

**Comment by Ritik1330** [comment]
i found the solution of this juast create project with react native latest varsion

**Comment by yxwandroid** [comment]
我遇到相同的问题 
 ERROR  [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
  - not rebuilding the app after installing or upgrading Reanimated
  - trying to run Reanimated on an unsupported platform
  - running in a brownfield app without manually initializing the native library
 ERROR  TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions')
 WARN  Module FastImageView requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
 LOG  2 evn
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by yxwandroid** [comment]
遇到相同的问题  请问如何解决

**Comment by artemis-prime** [comment]
I'm still seeing this w RN 0.72.3 and 3.4.2 of this library!  (Please don't be so eager to close issues.)

**Comment by JCcastagne** [comment]
Why is this issue closed if the error persists?

**Comment by JCcastagne** [comment]
If anyone else is having issues even after doing everything that was mentioned, here's what finally worked for me:

1. Delete the following folders: ios, android, node_modules.
2. Restart computer.
3. update package.json : `"expo-dev-client": "~2.4.6"` --> `"expo-dev-client": "2.4.7"` and also `"react-native-reanimated": "~3.3.0"` --> `"react-native-reanimated": "^3.4.1"`.
4. `npm install`
5. `npx expo install`
6. `npx expo prebuild`
7. `npx expo run:ios`

**Comment by martinacostapaisanos** [comment]
> If anyone else is having issues even after doing everything that was mentioned, here's what finally worked for me:
> 
> 1. Delete the following folders: ios, android, node_modules.
> 2. Restart computer.
> 3. update package.json : `"expo-dev-client": "~2.4.6"` --> `"expo-dev-client": "2.4.7"` and also `"react-native-reanimated": "~3.3.0"` --> `"react-native-reanimated": "^3.4.1"`.
> 4. `npm install`
> 5. `npx expo install`
> 6. `npx expo prebuild`
> 7. `npx expo run:ios`

Works for me! Thanks. 

I have only react-native-reanimated, so I update only that to 3.4.1 and works!
