### ISSUE TITLE
Updating LottieView progress via useAnimatedProps broken

### ISSUE THREAD

**Issue by AlexanderEggers** [software-mansion/react-native-reanimated#4674]
### Description

When trying to update the progress of a LottieView (lottie-react-native) via the useAnimatedProps hook, the actual update is not received by the component and nothing seems to change on the screen. That used to work in v2 without issues.

Possible workaround for a few cases but not all:

```typescript
  const animationProgressController = useSharedValue(0);

  const animatedProps = useAnimatedProps(() => ({
    progress: animationProgressController.value,
  }));
  const [progress, setProgress] = useState<number>(0);
  useDerivedValue(() => {
    runOnJS(setProgress)(animationProgressController.value);
  }, [animationProgressController]);
```

### Steps to reproduce

1. Checkout https://github.com/AlexanderEggers/ReanimatedIssue/tree/reanimated-hook-issue
2. You will notice that nothing happens on the screen
3. Update the reanimated version to the latest v2
4. Run the application again and the lottie animation progress is now correctly handled 

### Snack or a link to a repository

https://github.com/AlexanderEggers/ReanimatedIssue/tree/reanimated-hook-issue

### Reanimated version

3.3.0

### React Native version

0.71.11

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by AlexanderEggers** [comment]
@tomekzaw This is the other blocking issue in my project to update to reanimated v3 that I have mentioned [here](https://github.com/software-mansion/react-native-reanimated/issues/4522#issuecomment-1621007156).

**Comment by tomekzaw** [comment]
@AlexanderEggers Thanks for submitting the issue as well as providing the repro, currently I'm quite busy but I will take a look at it soon.

**Comment by AlexanderEggers** [comment]
@tomekzaw Do you have any updates yet?

**Comment by AlexanderEggers** [comment]
I think I found the root cause of this issue which is around the latest stable lottie-react-native version. I had a try with the latest preview version and everything seem to be working fine for me now. I believe this PR likely fixed the issue on the lottie-react-native side: https://github.com/lottie-react-native/lottie-react-native/pull/992 

@tomekzaw So my question would be why v3 is not working with the current stable and seems to be requiring https://github.com/lottie-react-native/lottie-react-native/pull/992?

**Comment by LeoAnt02** [comment]
Any update on this ? @tomekzaw
