### ISSUE TITLE
Output of react-native bundle containes source code loation when using with babel plugin

### ISSUE THREAD

**Issue by XHMM** [software-mansion/react-native-reanimated#4689]
### Description

When I running ` npx react-native bundle --dev false  --platform ios --minify --bundle-output ./bundle.js --entry-file ./index.js --reset-cache` for building a release bundle, I foud that my source code location  was included in the output file like this:
<img width="1065" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/24786522/22a39581-70db-43bd-bbcd-b9b095a6a97d">

If I removed `react-native-reanimated/plugin` from `babel.config.js` and rebuild, the output content will not include these location which was expected.

I noticed that the code from `react-native-gesture-handler` and `react-native-reanimated` will have location output, I am not very sure the issue was from metro or babel or this babel plugin

### Steps to reproduce

-

### Snack or a link to a repository

-

### Reanimated version

3.3.0

### React Native version

0.71.11

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

None

### Device model

-

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @XHMM, thanks for this issue! Indeed this is our (Reanimated Babel Plugin's) fault and this has been like this forever - I'm surprised nobody has ever reported it. I already make a PR that fixes it since it's an easy fix.
