### ISSUE TITLE
[android][release] makeShareableCloneRecursive Call Stack Size Exceeded

### ISSUE THREAD

**Issue by thespacemanatee** [software-mansion/react-native-reanimated#4690]
### Description

I'll start by saying that I've spent many days on this and already looked at #4140, #4177, #4367 and #4475, and this is a separate issue. I also created an issue at expo/expo#23297 but I don't think it's expo's fault because I could not reproduce this on their bare template. It's worth noting that this does not occur on `react-native@0.71` or `expo@48`.

The bug, for me, only occurs on the Android `release` build or the `debug` build with the `JS Dev Mode` disabled.

![photo_2023-07-09_19-04-45](https://github.com/software-mansion/react-native-reanimated/assets/6837599/114b39bc-91ec-41d5-8cfe-6ed53bf56760)

This gave me the idea to search for all `__DEV__` flags within the installed version in my `node_modules` and flip all of them so that I can see the error in dev mode and get a nicer stacktrace. Here's what I got:

![photo_2023-07-09_19-07-21](https://github.com/software-mansion/react-native-reanimated/assets/6837599/d337f2ce-8d53-4c65-bba7-8f737ea8dcb6)

This narrows down the problem quite well, and I found that the following patch solves my issue:

```patch
diff --git a/node_modules/react-native-reanimated/src/reanimated2/shareables.ts b/node_modules/react-native-reanimated/src/reanimated2/shareables.ts
index 4f358f4..8be3e2b 100644
--- a/node_modules/react-native-reanimated/src/reanimated2/shareables.ts
+++ b/node_modules/react-native-reanimated/src/reanimated2/shareables.ts
@@ -1,6 +1,6 @@
 import NativeReanimatedModule from './NativeReanimated';
-import { ShareableRef } from './commonTypes';
 import { shouldBeUseWeb } from './PlatformChecker';
+import { ShareableRef } from './commonTypes';
 import { registerWorkletStackDetails } from './errors';
 import { jsVersion } from './platform-specific/jsVersion';
 
@@ -146,8 +146,9 @@ export function makeShareableCloneRecursive<T>(
               value.__workletHash,
               value.__stackDetails
             );
-            delete value.__stackDetails;
           }
+          // TODO: This is the fixes Maximum call stack size exceeded error
+          delete value.__stackDetails;
           // to save on transferring static __initData field of worklet structure
           // we request shareable value to persist its UI counterpart. This means
           // that the __initData field that contains long strings represeting the
```

Obviously, this is not ideal and doesn't seem like the official solution (why would stackDetails have anything to do with the fix?), so I'm hoping the team will have a better idea. Thanks for the great work!

### Steps to reproduce

I could not reproduce this on the bare expo template, but I'm linking it anyway. I hope the patch I provided above will give some clue as to why it only happens on some projects.

1. Install `react-native-reanimated@3.3.0`
2. `npx pod-install`
3. Importing the library using `import 'react-native-reanimated'` in `App.tsx` is enough to trigger the bug

### Snack or a link to a repository

https://github.com/thespacemanatee/expo-dev-menu-repro/tree/repro/reanimated-makeShareableCloneRecursive-crash

### Reanimated version

3.3.0

### React Native version

0.72.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

Pixel 7 Pro (Android 13) and Pixel 3a (Android 10)

### Acknowledgements

Yes

**Comment by thespacemanatee** [comment]
@tomekzaw this is still an issue for my team. Could we get some advisory on whether the workaround above is viable, and why it might be happening?

**Comment by tomekzaw** [comment]
Hey @thespacemanatee, thanks for reporting this issue, investigating the root cause as well as providing the workaround.

> Could we get some advisory on whether the workaround above is viable, and why it might be happening?

Sure, we will investigate this issue once we finish investigating other issues that we're looking into right now.

**Comment by devoren** [comment]
same issue +1

**Comment by a-eid** [comment]
I'm getting a similar issue on android in release mode, in development everything works fine.

**Comment by hirbod** [comment]
@tomekzaw can you give me some directions how/where I should look for `__version` ?

**Comment by tomekzaw** [comment]
@hirbod Sure! Are you able to extract the JS bundle file from your app? If not, I'll think of some different way on how to check this.

**Comment by hirbod** [comment]
Maybe the recent changes to Metro and Expos ability to load .env files are the reason here. Seems like --variant Release is still loading .env.development instead of .env.production. 

So this means, between every local change from development -> production, we need to run `./gradlew clean` or it will break.

**Comment by thespacemanatee** [comment]
@tomekzaw the issue occurs again now and then and doesn't seem to have a deterministic solution, @hirbod could you confirm if it works every time and on different machines?

I also think it's weird that this issue only happens to Android. If it is what the team says it is, that the Android build cache needs to be cleared, then why does the solution in #4737 suggest fixes in the JS-land (solution 2)? And why does this affect Android only and not iOS as well? More investigations need to be done to find the root cause.

**Comment by hirbod** [comment]
@thespacemanatee I did not test on a different machine but it was working for my mate and on EAS. I also had the suspicion that --variant Release vs --variant release (lowercase) might have been the root cause to the issue. After using EXPO_NO_DOTENV=1 with lowercase "release" I did not run into this issue anymore so far.

**Comment by thespacemanatee** [comment]
@hirbod the variant casing should depend on the build flavours that you defined in `app/build.gradle`. Mine is `productionRelease`. I can also confirm (for now) that the builds on EAS work, but not local builds, even after deleting and cloning the repository again. Maybe it's something on expo's side.

**Comment by hirbod** [comment]
I haven't defined any build flavours, and have been using the defaults provided by Expo. I figured out that using an uppercase 'R' was causing some issues for me. For example, it generated a production app, but loaded a development bundle. I'm not certain if this was merely a coincidence or not, but something seems off since the introduction of SDK 49 (and it's ability to read our local DOTENV / NODE_ENV)

**Comment by hirbod** [comment]
@tomekzaw this matches exactly my issue. So the uppercase R was the main problem for me. I retried couple of times and could reproduce this reliable.

**Comment by thespacemanatee** [comment]
@tomekzaw @hirbod If my variant is `productionRelease`, how would I go about this? The funny thing is that I tried `npx expo run:android productionrelease` and it works, and thereafter `npx expo run:android productionRelease` also works as well, until it stops working randomly. I think it's related to expo but I'm not sure how to phrase it as an issue.

**Comment by thespacemanatee** [comment]
@hirbod please read about multiple build variants here: https://docs.expo.dev/build-reference/variants/

The syntax I provided is correct. Internally it transformed the variant to `assembleProductionRelease` etc

**Comment by hirbod** [comment]
I don't see any indication that your syntax is correct. Only EAS commands should include `profile`. I'm not saying you're incorrect, but this is new to me and I can't recall any documents using your syntax.

Here is a link for reference: https://docs.expo.dev/build-reference/troubleshooting/#verify-that-your-project-builds-and-runs-locally

The only "official" guidance I have is a direct message from @EvanBacon, who figured I passed an uppercase 'R' for android (instead iOS). Perhaps he can provide further clarification. For me, it fixed the issues.

**Comment by thespacemanatee** [comment]
@hirbod I've seen that documentation. If you try creating multiple build variants you'll realise that the `npx expo run:android --variant release` command no longer works because there's no such Gradle task 'installRelease`, which is expected because it should not be `installProductionRelease`. We figured by trial and error that we have to pass in `--variant productionRelease`, and I've also seen many projects using such syntax. If `NODE_ENV` is somehow being set by this then it should be considered a bug.

**Comment by hirbod** [comment]
<img width="487" alt="Bildschirmfoto 2023-07-18 um 04 21 26" src="https://github.com/software-mansion/react-native-reanimated/assets/504909/b6ab7801-febc-4b1e-a3a3-bf5da22549a5">

**Comment by thespacemanatee** [comment]
@hirbod sorry I was typing on my phone. This is very helpful, thanks. There isn't really any documentation about configuring `NODE_ENV` so I guess we'll have to pass that env variable with every build command?

**Comment by hirbod** [comment]
Yes you can try NODE_ENV=production npx expo run:android....

**Comment by thespacemanatee** [comment]
@hirbod Just tried it and the issue still occurs 🤔 @tomekzaw I patched `plugin.js` with #4747 but the issue still occurs. Even just returning `true` doesn't work, what gives?

![Screenshot 2023-07-22 at 1 36 21 AM](https://github.com/software-mansion/react-native-reanimated/assets/6837599/eb06c2fb-c2e6-44bf-8f45-df0a2af2c244)
