### ISSUE TITLE
'React-Fabric/react/renderer/core/ShadowNode.h' file not found

### ISSUE THREAD

**Issue by LimitedDani** [software-mansion/react-native-reanimated#4701]
### Description

When building the app for iOS I get an error about missing 'React-Fabric/react/renderer/core/ShadowNode.h' file not found

<img width="979" alt="Screenshot 2023-07-11 at 10 27 14" src="https://github.com/software-mansion/react-native-reanimated/assets/11191383/c8b9a90a-c13e-4ddc-b998-ef8ce8f0c49a">

### Steps to reproduce

1. Run a build with new architecture on React Native 0.72.1

### Snack or a link to a repository

-

### Reanimated version

3.3.0

### React Native version

0.72.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro Max

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @LimitedDani, can you please run `cd ios && RCT_NEW_ARCH_ENABLED=1 pod install && find . -name "ShadowNode.h"` and paste the output here?

**Comment by billnbell** [comment]
I had this and fixed IOS on new Arch on RN 0.72.1. `NO_FLIPPER=1 USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 yarn install`

Patch: react-native-reanimated+3.3.0.patch

```
diff --git a/node_modules/react-native-reanimated/ios/native/NativeProxy.mm b/node_modules/react-native-reanimated/ios/native/NativeProxy.mm
index 2676e73..c6c6cec 100644
--- a/node_modules/react-native-reanimated/ios/native/NativeProxy.mm
+++ b/node_modules/react-native-reanimated/ios/native/NativeProxy.mm
@@ -16,8 +16,8 @@
 
 #ifdef RCT_NEW_ARCH_ENABLED
 #import <RNReanimated/ReanimatedUIManagerBinding.h>
-#import <React-Fabric/react/renderer/core/ShadowNode.h>
-#import <React-Fabric/react/renderer/uimanager/primitives.h>
+#import <react/renderer/core/ShadowNode.h>
+#import <react/renderer/uimanager/primitives.h>
 #import <React/RCTBridge+Private.h>
 #import <React/RCTScheduler.h>
 #import <React/RCTSurfacePresenter.h>
```

**Comment by LimitedDani** [comment]
> Hey @LimitedDani, can you please run `cd ios && RCT_NEW_ARCH_ENABLED=1 pod install && find . -name "ShadowNode.h"` and paste the output here? Could you also please change `React-Fabric` to `React_Fabric` in import path and let me know if it works for you?

`
Using firebase.json from '/Users/daniquedejong/Projects/MapName/firebase.json'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `MapName`: A0Auth0, RNDefaultPreference, RNFBApp, RNFBMessaging, RNFastImage, RNFlashList, RNGestureHandler, RNReanimated, RNSVG, RNScreens, ReactNativeGetLocation, react-native-orientation-locker, react-native-pager-view, react-native-safe-area-context, react-native-video, and react-native-webview
is Fabric Enabled?: true
Framework build type is static framework
[Codegen] Adding script_phases to React-Codegen.
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] Processing react-native core libraries
[Codegen] Found react-native


[Codegen] >>>>> Searching for codegen-enabled libraries in /Users/daniquedejong/Projects/MapName/node_modules
[Codegen] Found react-native-gesture-handler
[Codegen] Found react-native-pager-view
[Codegen] Found react-native-safe-area-context
[Codegen] Found react-native-screens
[Codegen] Found react-native-svg
[Codegen] Found react-native-webview


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js


[Codegen] >>>>> Searching for codegen-enabled libraries in the app


[Codegen] >>>>> Processing FBReactNativeSpec
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/FBReactNativeSpecBDSUoM/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


[Codegen] >>>>> Processing rncore
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/rncorehMIlHT/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


[Codegen] >>>>> Processing rngesturehandler_codegen
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/rngesturehandler_codegenZKz1RS/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


[Codegen] >>>>> Processing RNCViewPager
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/RNCViewPageridH8Cv/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


[Codegen] >>>>> Processing safeareacontext
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/safeareacontextUAVExd/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


[Codegen] >>>>> Processing rnscreens
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/rnscreenszgXgcb/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


[Codegen] >>>>> Processing rnsvg
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/rnsvg4KnoR6/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


[Codegen] >>>>> Processing RNCWebViewSpec
[Codegen] Generated schema: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/RNCWebViewSpecz8OfFZ/schema.json
[Codegen] Generated artifacts: /Users/daniquedejong/Projects/MapName/ios/build/generated/ios


>>>>> Creating component provider
Generated schema list: /var/folders/sn/_1p_5xcs12vdx8y2dk2v9lj80000gp/T/rn-tmp-schema-list.json
Generated provider in: /Users/daniquedejong/Projects/MapName/node_modules/react-native/React/Fabric


[Codegen] Done.
Analyzing dependencies
RNFBApp: Using overridden static_framework value of 'true'
RNFBMessaging: Using overridden static_framework value of 'true'
Downloading dependencies
Generating Pods project
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++17 on /Users/daniquedejong/Projects/MapName/ios/MapName.xcodeproj
Pod install took 25 [s] to run
Integrating client project
Pod installation complete! There are 62 dependencies from the Podfile and 79 total pods installed.
`

**Comment by tomekzaw** [comment]
@LimitedDani Can you please also paste the output of `find . -name "ShadowNode.h"`?

**Comment by tomekzaw** [comment]
@LimitedDani Thanks! Could you please check if the following diff works for you?

```diff
-#import <React-Fabric/react/renderer/core/ShadowNode.h>
-#import <React-Fabric/react/renderer/uimanager/primitives.h>
+#import <React_Fabric/react/renderer/core/ShadowNode.h>
+#import <React_Fabric/react/renderer/uimanager/primitives.h>
```

**Comment by LimitedDani** [comment]
> @LimitedDani Thanks! Could you please check if the following diff works for you?
> 
> ```diff
> -#import <React-Fabric/react/renderer/core/ShadowNode.h>
> -#import <React-Fabric/react/renderer/uimanager/primitives.h>
> +#import <React_Fabric/react/renderer/core/ShadowNode.h>
> +#import <React_Fabric/react/renderer/uimanager/primitives.h>
> ```

That worked

**Comment by LimitedDani** [comment]
<img width="397" alt="Screenshot 2023-07-12 at 11 44 36" src="https://github.com/software-mansion/react-native-reanimated/assets/11191383/eee7c265-25f6-4702-bea9-c851516972e8">
@tomekzaw but now an other issue stands up

**Comment by tomekzaw** [comment]
Thanks for checking this. Does the problem with redefinitions also happens with your patch, i.e. without `React_Fabric/` at the beginning?

**Comment by LimitedDani** [comment]
@tomekzaw I can confirm this solves it.

**Comment by tomekzaw** [comment]
@LimitedDani Turns out we already use `ShadowNode.h` without `React-Fabric/` in other places so that's okay. I've submitted a PR #4718. Thanks for pointing this out!

**Comment by a-eid** [comment]
I am seeing this error with reanimated v4 & RN 77.1

```bash
[RUN_FASTLANE]
❌  (../../node_modules/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.cpp:1:10)

> 1 | #include <react/renderer/components/rnreanimated/ReanimatedShadowNode.h>
    |          ^ 'react/renderer/components/rnreanimated/ReanimatedShadowNode.h' file not found
  2 |
  3 | namespace facebook::react {
  4 |
```

![Image](https://github.com/user-attachments/assets/066719f2-9743-4f1e-b907-642198ab71e3)

**Comment by tomekzaw** [comment]
@a-eid Thanks for reporting this. We might have broken compatibility with 0.77 so we'll need to check it. cc @piaskowyk

**Comment by piaskowyk** [comment]
@a-eid I've tried to build app with:
- `react-native@0.77.2`
- `react-native-reanimated@4.0.0-nightly-20250428-fbca6a281`
- `react-native-worklets@0.3.0-nightly-20250429-685a632d0`
and it works without any issues. I'm afraid that without reproduction i can help you :/
