### ISSUE TITLE
Intl is not available in reanimated

### ISSUE THREAD

**Issue by kievu** [software-mansion/react-native-reanimated#4714]
### Description

This issue regarding support of Intl was closed a while ago, based on the fact that Intl wasn't supported on Hermes at that time https://github.com/software-mansion/react-native-reanimated/issues/872.

Intl is now supported on Hermes, but is still not available in reanimated worklet.

What is missing? Should it work?

### Steps to reproduce

This code should work in any workletized reanimated API (e.g. useAnimatedStyle, useDerivedValue, useAnimatedGestureHandler)
```
    const formatter = new Intl.NumberFormat('en');
    formatter.format(1000);
```
But error says `ReanimatedError: Cannot read property 'prototype' of undefined, js engine: reanimated`

### Reanimated version

3.2.0

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

iPhone SE

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @kievu, thanks for reporting this issue! Can you please check if #4717 resolves your issue?

**Comment by kievu** [comment]
Perfect, I patched with your changes locally and it works as intended. Thank you @tomekzaw for the swift reply and fix 🙏
