### ISSUE TITLE
Bug on web for some events

### ISSUE THREAD

**Issue by djbuch** [software-mansion/react-native-reanimated#472]
Hello,
I have a bug with react-navigation-drawer on web (https://github.com/react-navigation/drawer/pull/124)  : when I click on the overlay the drawer doesn't close.

You can see this bug happening here : https://snack.expo.io/@djbuch/bug-web-drawer

Regards,
David-Julian

**Comment by Arttii** [comment]
I am also having the same issue

**Comment by mattop1709** [comment]
I am also having the same issue

**Comment by jakub-gonet** [comment]
May be related to #481

**Comment by jkadamczyk** [comment]
The only person I remember was working on web support for reanimated is Evan @EvanBacon if you have any clue and will to look into this please do, if not I will close this issue soon as it is stale.
