### ISSUE TITLE
Animations are automatically cancelled depending on current value from defineAnimation which may be unexpected

### ISSUE THREAD

**Issue by DrRefactor** [software-mansion/react-native-reanimated#4721]
### Description

This code automatically cancels animation before onStart, if `current` is same as `_value`
```
 // prevent setting again to the same value
    // and triggering the mappers that treat this value as an input
    // this happens when the animation's target value(stored in animation.current until animation.onStart is called) is set to the same value as a current one(this._value)
    // built in animations that are not higher order(withTiming, withSpring) hold target value in .current
    if (sv._value === animation.current && !animation.isHigherOrder) {
      animation.callback && animation.callback(true);
      return;
    }
```

This may be unexpected for animations that don't have defined target in a similar manner that withSpring and withTiming do.
Imagine an animation of endless spinning wheel, where SharedValue represents current angle. Starting angle may be anything between 0 and 360, animation is cancellable only by `cancelAnimation` API:

```
export function withSpin(
  value: SharedValue<number>,
  config: SpinConfig,
  callback?: AnimationCallback,
): number {
  'worklet';

  return defineAnimation<SpinAnimation>(0, () => {
    'worklet';

    function spin(animation: InnerSpinAnimation, now: number): boolean {
      const {lastTimestamp, current} = animation;
      const deltaTime = Math.min(now - lastTimestamp, 64);

      animation.current = current + (animation.velocity * deltaTime) / 1000;
      // start over from min when max reached
      animation.current = moduloClamp(animation.current, config.min, config.max);

      // never stop until manually cancelled
      return false;
    }

    function onStart(animation: SpinAnimation, value: number, now: Timestamp): void {
      animation.current = value;
      animation.lastTimestamp = now;
    }
    return {
      onFrame: spin,
      onStart,
      callback: (finished, value) => {
        if (callback) {
          runOnJS(callback)(finished, value);
        }
      },
      // THIS IS PROBLEMATIC, REQUIRES HACKY SOLUTION
      current: value.value + 1,
      lastTimestamp: 0,
    } as SpinAnimation;
  });
}
```

I must use hacky `current: value.value + 1` to make it different than current value. In some animations, there is simply no defined target. withSpin is only simplified example of few animations of mine that encounter this.

I suggest we use `animation.toValue` instead of `animation.current`, for which I will prepare PR soon.

### Steps to reproduce

Use my animation above, change `current: value.value` to anything else, e.g. `0` or `value.value`.

### Snack or a link to a repository

https://snack.expo.dev/@drrefactor/reanimated-define-animation-repro

Press "unbreak" button to make animation work, press "break" to reproduce bug again. Reproduces on iOS and android, does not reproduce on web.

### Reanimated version

master

### React Native version

0.69

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by DrRefactor** [comment]
PR created:
https://github.com/software-mansion/react-native-reanimated/pull/4724

**Comment by Latropos** [comment]
Hi!
Thank you for your work however we can't change the way our animations work. It would damage lot of existing apps of users of our library!
Anyway you can easily achieve the look you want using `withRepeat` higher order animation, like here: https://mobiledevtutorials.com/how-to-2-create-spinner/

**Comment by DrRefactor** [comment]
Thanks, please bear in mind, that above guide only mentions simple spinner.

I provided an example of animation starting from value Y that loops between X and Z boundaries (where X < Y < Z).

As stated in description:
> Starting angle may be anything between 0 and 360
