### ISSUE TITLE
Single page documentation

### ISSUE THREAD

**Issue by Jarred-Sumner** [software-mansion/react-native-reanimated#473]
It's great that `react-native-reanimated` now has a dedicated [documentation site](https://software-mansion.github.io/react-native-reanimated/). The sidebar listing all the different pages is helpful.

One thing that was nice about the previous iteration where it lived in this repository's `README.md` was that I could quickly <kbd>⌘+F</kbd> to find the documentation on the specific thing I was looking for without having to use my mouse to click on the page.  That worked well since the docs was one long file. Is there any chance that could come back? (<kbd>⌘+F</kbd>'ing without having to click separate pages)

**Comment by osdnk** [comment]
Hey, we're a little bit concerned about maintaining two docs pages. Can't you use a search bar on the website?
