### ISSUE TITLE
[Solution] Using dev bundle in a release app build is not supported.

### ISSUE THREAD

**Issue by piaskowyk** [software-mansion/react-native-reanimated#4737]
## Introduction
Hey there! 👋 This post has some potential solutions for when your application crashes with this message: `Using dev bundle in a release app build is not supported.` This is in response to the issue https://github.com/software-mansion/react-native-reanimated/issues/4690.

## Why did my app crash?
Well, it seems that you're using the debug version of the JavaScript bundle in your release application. This can lead to unexpected issues and hard-to-detect crashes. We thought it's better to give you a heads up before things potentially get worse.

## What does mean this error?
In debug mode, our Babel plugin adds extra information to every worklet, such as its location in the file, source map, and stack trace. However, these details are useless in release mode, so to improve performance, we don't include them in the release bundle build. This means that the debug bundle is different from the release bundle. There are a couple of potential causes for this issue:
- **[Issue 1]** You haven't cleared your Android cache in your application.
- **[Issue 2]** One of your dependencies uses worklets and provides code that has already been transpiled by the Reanimated Babel plugin.

### Solution for **Issue 1**
To fix this, you need to clear your Android cache. Here's what you can do in your terminal:
```bash
cd android && ./gradlew clean
```
Credit goes to @hirbod for originally posting this solution 🙌 <img src="https://cdn3.emoji.gg/emojis/2747_PartyParrot.gif" height="24px" alt="PartyParrot" /> You can find more details [here](https://github.com/software-mansion/react-native-reanimated/issues/4690#issuecomment-1634344638).

### Solution for **Issue 2**
To resolve this, you should check which of your dependencies are using Reanimated. If you find one, you can force the library to load the non-transpiled source file from `/src/*` instead of `/lib/*.` Then you can use `patch-package` and modify the package.json file in the library by making the following change:
```diff
- "main": "lib/module/index",
+ "main": "src/index",
```
Additionally, make sure to report this issue in the repository of the library because you're probably not the only one facing this problem.

**Comment by thespacemanatee** [comment]
Just quoting my own solution here https://github.com/software-mansion/react-native-reanimated/issues/4690#issuecomment-1630364015 here since I did try `./gradlew clean` initially but it did not work.

**Comment by mrshahzeb7** [comment]
any solution to this ?

I disabled JS dev mode inside the developer menu to test performance

    "react": "^18.2.0",
    "react-native": "^0.72.4",
    "react-native-reanimated": "^3.4.2",

**Comment by janicduplessis** [comment]
I am also seeing this issue when trying to run release JS in a native debug build, which is useful to measure JS perf.

**Comment by ElSierra** [comment]
> I am also seeing this issue when trying to run release JS in a native debug build, which is useful to measure JS perf.

did you find a fix ?

**Comment by harrisrobin** [comment]
I'm running into this as well, for some reason reanimated is behaving differently in release vs dev so it would have been useful to be able to do this for debugging.

**Comment by chanphiromsok** [comment]
I got crashed like this when release but dev is work fine
<img width="878" alt="Screen Shot 2023-09-25 at 1 30 46 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/65760336/33e9bfad-d901-48b7-bbd8-2f3beb41a020">

## My Solution I export NODE_ENV="production" then release is ok with android

**Comment by pfcodes** [comment]
This is happening when I load an EAS Update inside of an expo-dev-client

**Comment by LeonardoCalazans** [comment]
Execution failed for task ':react-native-gesture-handler:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by Lakston** [comment]
> I am also seeing this issue when trying to run release JS in a native debug build, which is useful to measure JS perf.

dame here, all the performance libraries suggest to turn off __DEV__  mode for proper benchmarking and measurements but reanimated is preventing it. I tried the gradlew clean suggestion but it did not work.

running RN 0.72.7 and reanimated 3.4.2, I'll update to reanimated latest and report back if anything changes.
