### ISSUE TITLE
Difference in values of currentGlobalOriginX, currentGlobalOriginY for IOS and android

### ISSUE THREAD

**Issue by prakhar2407** [software-mansion/react-native-reanimated#4746]
### Description

Their are different values for currentGlobalOriginX and currentGlobalOriginY for IOS and android due to which their is difference in animations of both while in android it is performing as per the requirement but because the values are different in IOS the custom animation is not working as required

### Steps to reproduce

Make a custom exiting animation for both IOS and android, you will see the difference

### Snack or a link to a repository

N/A

### Reanimated version

2.12.0

### React Native version

0.67.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey! Thanks for the report but unfortunately without any reproduction this is hard to find a solution for your issue :/

**Comment by Latropos** [comment]
@prakhar2407 Could you provide screenshots, recordings or code? We have no information and we can't even say if this is an expected behaviour or an actual bug.
