### ISSUE TITLE
Reanimated with gl-react-native or gl-react-expo

### ISSUE THREAD

**Issue by JesterDunice** [software-mansion/react-native-reanimated#475]
I tried to create animated Blur component(https://github.com/gre/gl-react-blur) with Reanimated.createAnimatedComponent,  but faced with next error:
![Simulator Screen Shot - iPhone X - 2019-11-17 at 02 17 15](https://user-images.githubusercontent.com/25579397/69000413-66e1ec00-08e0-11ea-8052-33c2d11625fd.png)
It is good working, when wrapping with react-native Animated lib. It is possible use Reanimated with gl-react-*?

**Comment by jakub-gonet** [comment]
Unfortunately, Reanimated doesn't support functional components yet, however PRs are welcome

In upstream there's a bit better error message showing up
![image](https://user-images.githubusercontent.com/12465392/70240839-3f0ed700-176e-11ea-91cb-3568e4fb79ab.png)

I checked `gl-react-blur` and it's implemented with Functional components, so this won't work 😞

I'm closing it, but if you have any further questions or you did manage to work around that don't hesitate to comment.

**Comment by JesterDunice** [comment]
Thanks, @jakub-gonet!
