### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.    > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.

### ISSUE THREAD

**Issue by vengat180497** [software-mansion/react-native-reanimated#4750]
### Description

When I run the react-native run-android while I am getting the below error

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :app
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_messaging
         project :app > project :softoat_react-native-geocoder
         project :app > project :react-native-pager-view
   > Could not find any matches for com.facebook.react:hermes-engine:+ as no versions of com.facebook.react:hermes-engine are available.
     Required by:
         project :app 

### Steps to reproduce

 I tried cd android && ./gradlew clean and uninstall the node_modules then install but couldn't solved

### Snack or a link to a repository

app/build.gradle // Top-level build file where you can add configuration options common to all sub-projects/modules.  buildscript {     ext {         googlePlayServicesVersion = "+" // default: "+"         firebaseMessagingVersion = "21.1.0" // default: "21.1.0"         buildToolsVersion = "33.0.0"         minSdkVersion = 21         compileSdkVersion = 33         targetSdkVersion = 33                  if (System.properties['os.arch'] == "aarch64") {             // For M1 Users we need to use the NDK 24 which added support for aarch64             ndkVersion = "24.0.8215888"         } else {             // Otherwise we default to the side-by-side NDK version from AGP.             ndkVersion = "23.1.7779620"         }     }     repositories {         google()         mavenCentral()     }     dependencies {         classpath 'com.google.gms:google-services:4.3.15'         classpath("com.android.tools.build:gradle:7.3.1")         classpath("com.facebook.react:react-native-gradle-plugin")         classpath("de.undercouch:gradle-download-task:5.0.1")                    // NOTE: Do not place your application dependencies here; they belong         // in the individual module build.gradle files     } }  allprojects {     repositories {         maven {             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm             url("$rootDir/../node_modules/react-native/android")         }         maven {             // Android JSC is installed from npm             url("$rootDir/../node_modules/jsc-android/dist")         }         mavenCentral {             // We don't want to fetch react-native from Maven Central as there are             // older versions over there.             content {                 excludeGroup "com.facebook.react"             }         }         google()         maven { url 'https://www.jitpack.io' }            exclusiveContent {            filter {                includeGroup "com.facebook.react"            }            forRepository {                maven {                    url "$rootDir/../node_modules/react-native/android"                }            }        }     } }  subprojects {     afterEvaluate {project ->         if (project.hasProperty("android")) {             android {                 compileSdkVersion rootProject.ext.compileSdkVersion                 buildToolsVersion rootProject.ext.buildToolsVersion             }         }     } }

### Reanimated version

3.3.0

### React Native version

before 0.70.6 after 0.7.12

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
This problem doesn't seem to be related to reanimated
