### ISSUE TITLE
Exception '-[RCTUIManager setFlushUiOperations:]: unrecognized selector sent to instance 0x600000b39110'

### ISSUE THREAD

**Issue by siemya** [software-mansion/react-native-reanimated#4774]
### Description

I am getting this error (which is weird that I close the red screen and my app works fine until I reopen the app again)

`Exception '-[RCTUIManager setFlushUiOperations:]: unrecognized selector sent to instance 0x600000b39110' was thrown while invoking installTurboModule on target ReanimatedModule with params ...`

### Steps to reproduce

1- I have upgraded react-native to 0.72.0
2- I have upgraded react-native-animated to 3.3.0
3- App crashes on initial launch

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

3.3.0

### React Native version

0.72.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @siemya, thanks for reporting this issue! Fortunately, `flushUiOperations` was removed in #4619 which is already merged but hasn't been released yet. Once we release 3.4.0, please check if it works for you.

**Comment by jakoblorz** [comment]
@tomekzaw  Had the same issue on `3.3.0`, updating to `3.4.0` and rebuilding my custom dev client solved it! Thanks!

**Comment by tomekzaw** [comment]
Fixed in #4619. Thanks for info @jakoblorz!
