### ISSUE TITLE
[event] nested proxy

### ISSUE THREAD

**Issue by ShaMan123** [software-mansion/react-native-reanimated#478]
Working as expected:
```ts
event([{
      nativeEvent: ({ contentOffset: { x, y } }) => block([
          set(scrollX, x),
          set(scrollY, y),
        ])
    }])

```

Not working:
```ts
 event([{
      nativeEvent: {
        contentOffset: ({ x, y }) => block([
            set(scrollX, x),
            set(scrollY, y),
          ])

      }
    }])
```

`sanitizeArgMapping` treats the nested proxy as if it were a value. I think logic should be changed to handle this case.

**Comment by jakub-gonet** [comment]
And what should happen if we have more than one property in the event?
Something like:
```js
{
	nativeEvent: {
		fieldA: ({a, b}) => /* animated node */
		fieldB: ({a, b}) => /* other animated node */
	}
}
```

I think it should map every animated node. But what happens after introducing shared nodes there:
```js
// `shared` is some `Animated.Value`
{
	nativeEvent: {
		fieldA: ({a}) => set(shared, a)
		fieldB: ({b}) => set(shared, b)
	}
}
```

after evaluating event node `shared` should have value of `a` or `b`? Objects are unordered in JS so how should we handle the order there?

We _could_ enforce only one function inside the event.

I'm not sure this functionality is needed, as original Animated seems to have only arg mapping via object properties and not functions. I don't think that it's worth changing now.

Closing for now but I'm open for discussion.
