### ISSUE TITLE
App crash with Assertion failed on file YogaLayoutableShadowNode.cpp in new architecture IOS.

### ISSUE THREAD

**Issue by meghvarse** [software-mansion/react-native-reanimated#4784]
### Description

Facing crash on IOS with below error after enable new architecture.
It happens on @gorhom/bottom-sheet which seems related to reanimated things.

react_native_assert failure: yogaChild->getContext() == traitCast<YogaLayoutableShadowNode const *>(child.get())
Assertion failed: (yogaChild->getContext() == traitCast<YogaLayoutableShadowNode const *>(child.get())), function ensureYogaChildrenAlignment, file YogaLayoutableShadowNode.cpp, line 915.
Message from debugger: Terminated due to signal 6

### Steps to reproduce

Open / Close same bottom sheet view multiple times,

### Snack or a link to a repository

https://snack.expo.dev/tJaNBdm25

### Reanimated version

3.3.0

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @meghvarse, thanks for reporting this issue. I believe this could be already fixed, can you please check if `yarn install react-native-reanimated@nightly` fixes this problem?

**Comment by meghvarse** [comment]
@tomekzaw after installing react-native-reanimated@nightly got below issue.

Error: [Reanimated] Unknown version of Reanimated Babel plugin. Using release bundle with debug build of the app is not supported. If the issue still persists, make sure that none of your dependencies contains already transformed worklets bundled with an outdated version of the Reanimated Babel plugin., js engine: hermes

**Comment by tomekzaw** [comment]
Hey @meghvarse, can you please try resetting Metro bundler cache with `yarn start --reset-cache` or `npm start -- --reset-cache`?

**Comment by meghvarse** [comment]
@tomekzaw Yes trying with same but still getting the same issue.

**Comment by meghvarse** [comment]
@tomekzaw issue fixed after upgrade node version v18.17.0. Thank you so much.
