### ISSUE TITLE
Several bugs (JNIEnv::CallLongMethod, reanimated::NativeProxy::handleEvent, JNIEnv::CallVoidMethod)

### ISSUE THREAD

**Issue by smatoox** [software-mansion/react-native-reanimated#4786]
### Description

We have several Android crashes, Sentry and Google Console indicate several problems. We can't find the reasons for all these bugs.

1. [libreanimated.so] _JNIEnv::CallLongMethod(_jobject*, _jmethodID*, ...) **SIGABRT**
   - _JNI DETECTED ERROR IN APPLICATION: obj == null_
3. [libreanimated.so] reanimated::NativeProxy::handleEvent(facebook::jni::alias_ref<facebook::jni::JString>, facebook::jni::alias_ref<facebook::react::WritableMap>) **SIGSEGV**
4. [libreanimated.so] _JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...) **SIGABRT**

These crashes affect all versions of Android (mainly 13 12 11).

### Steps to reproduce

It's difficult to have a method for reproducing problems.
We use "Reanimated" on several pages : Team | Competition | Player | Match.

It used for have a sticky Header and translate header on scroll.

<img width="551" alt="Capture d’écran 2023-07-21 à 12 15 06" src="https://github.com/software-mansion/react-native-reanimated/assets/26866646/30eea797-b605-4bbb-a655-b0b3dd7cb815">
<img width="551" alt="Capture d’écran 2023-07-21 à 12 15 24" src="https://github.com/software-mansion/react-native-reanimated/assets/26866646/b3cfdf30-fe45-414a-beb8-7cf0d994c1dd">

### Snack or a link to a repository

Fichajes (on PlayStore and AppStore)
https://play.google.com/store/search?q=fichajes&c=apps&hl=en

### Reanimated version

3.3.0

### React Native version

0.71.11

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

samsung huawei honor xiaomi (lot of models)

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey @smatoox thanks for the report! Do you uses codepush or similar OTA updates in your application?

**Comment by smatoox** [comment]
Hey @piaskowyk, yes we use Wonderpush with a NativeModules

**Comment by cw-sanjeev** [comment]
@piaskowyk we are facing similar crashes with codepush (although this crash has been present before too) but the frequency of these crashes rocketed after pushing codepush update. Anyway to mitigate it?
Thanks

**Comment by callmemonky** [comment]
Getting this in 3.4.2 as well.

When we pushed an update using CodePush, we started seeing these error on Sentry

**Comment by callmemonky** [comment]
@piaskowyk Any idea why this might be happening?

**Comment by lupena-pana** [comment]
Same for me with:
"react-native": "0.72.4"
"react-native-reanimated": "~3.3.0",
"expo": "~49.0.7",

**Comment by duhuajin** [comment]
Same issue with:
"react-native": "0.71.7",
"react-native-reanimated": "2.17.0"
Platform:android
When we pushed an update using CodePush,
then launch app may crash

**Comment by guihendias** [comment]
We're facing this problem as well. Over 800 users affect in the past 28 days.

```
    "expo": "~49.0.6",
    "expo-updates": "~0.18.12",
    "react-native": "0.72.4",
    "react-native-reanimated": "~3.3.0"
```

Same behavior as mentioned before, the app crashes when a new release is deployed (we use expo-updates most of the time)

**Comment by JClackett** [comment]
Also having this quite often too!

**Comment by cpintos-sc** [comment]
Same here, using codepush

**Comment by dylanclements** [comment]
Same here, using EAS updates

**Comment by lfvarela** [comment]
Same here, seeing issues here!

**Comment by jaslloyd** [comment]
@smatoox did you ever find what was causing this / a workaround

**Comment by warrenmcquinn** [comment]
I'm also encountering this issue and awaiting the [react-native-reanimated PR](https://github.com/software-mansion/react-native-reanimated/pull/5198) that appears to contain a fix.

**Comment by jfedak** [comment]
Hi, we have not merged [this PR](https://github.com/software-mansion/react-native-reanimated/pull/5198) yet as we want to investigate this issue further on our own.

**Comment by LunatiqueCoder** [comment]
Hello. On our side, we started experiencing this when using CodePush ONLY AFTER moving from bare workflow to expo managed workflow. The app didn't use Expo before, we gradually adopted it.
