### ISSUE TITLE
Examples don't run on iOS

### ISSUE THREAD

**Issue by brobertsUPS** [software-mansion/react-native-reanimated#480]
Thanks for the project!
I am getting an error when running the examples:

```
/react-native-reanimated/Example/ios/Pods/Target Support Files/Pods-ReanimatedExample/Pods-ReanimatedExample.debug.xcconfig: unable to open file (in target "ReanimatedExample" in project "ReanimatedExample") (in target 'ReanimatedExample'
```

I thought this might be similar to this failure to run the examples but I get a different error than in this issue: https://github.com/software-mansion/react-native-reanimated/issues/326

I follow the instructions for the example by:

```
Run yarn to install the dependencies of library
cd to Example directory
Run yarn to install the dependencies of example
Run yarn start to start the packager with custom config
react-native run-ios
```

I ensured that I have the pre-req `react-native` installed globally as well. Not sure if I missed something but I thought that would do it.

**Comment by RockinRonE** [comment]
@brobertsUPS I was able to get this to work by running `npm run start` in one tab in my terminal and then running `react-native run-ios`. I also used `npm install`. 

I also went into the `Pods` directory and ran `pod install`. I'm not sure which one was the right way, but that was my sequence of events to get it to run!

**Comment by brobertsUPS** [comment]
Thanks @RockinRonE! I was able to get them running after I did the `pod install` in the `ios` directory. I will update the readme in the `Example` directory.
