### ISSUE TITLE
Shared element transitions not working when using use_frameworks! :linkage => :static in podfile

### ISSUE THREAD

**Issue by jvgeee** [software-mansion/react-native-reanimated#4801]
### Description

I've got an existing app (set up with InfiniteRed's Ignite boilerplate), I already use Reanimated and React Navigation. I'm trying to use shared transitions so that a thumbnail image will animate to full-screen when clicked.

I'm using the sample code directly from [the Reanimated docs](https://docs.swmansion.com/react-native-reanimated/docs/api/sharedElementTransitions/).

The transition doesn't work when navigating between screens.

Editing this to say that I've narrowed in on the bug a bit: I set up a new repo with the bare-bones on it, and the transition works. However, when I enable `use_frameworks!` (required for RN Firebase), it fails

This breaks the transition (but RN Animated still works everywhere else)

```
use_frameworks! :linkage => :static
```

Repo attached add / remove the use_frameworks flag from the Podfile to see it break

**Comment by Darren120** [comment]
+1

**Comment by Darren120** [comment]
did u manage to solve this good sir?

**Comment by jvgeee** [comment]
@Darren120 Sadly no, needs a fix from the Reanimated team. Although it did prompt me to investigate whether we were actually using Firebase, and we're not, so I've removed it. Not a good solution though!

**Comment by Darren120** [comment]
i do use the messaging module, but that depends on the firebase app module :/

**Comment by Darren120** [comment]
> @jvgeee see #4425

what is the static framework name for pod in ios?

**Comment by jvgeee** [comment]
> @jvgeee see #4425

This is good, thank you, couldn't find this thread after searching strangely. 

For anyone else who comes across this, the solution from that thread is:

```
$static_framework = ['RNScreens']

pre_install do |installer|
   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
   installer.pod_targets.each do |pod|
     if $static_framework.include?(pod.name)
       def pod.build_type;
         Pod::BuildType.static_library
       end
     end
   end
end
```

**Comment by TowhidKashem** [comment]
> > @jvgeee see #4425
> 
> This is good, thank you, couldn't find this thread after searching strangely.
> 
> For anyone else who comes across this, the solution from that thread is:
> 
> ```
> $static_framework = ['RNScreens']
> 
> pre_install do |installer|
>    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>    installer.pod_targets.each do |pod|
>      if $static_framework.include?(pod.name)
>        def pod.build_type;
>          Pod::BuildType.static_library
>        end
>      end
>    end
> end
> ```

thanks @jvgeee , where did you add this code in the podfile, does it matter or can I add it at the top of the file?

**Comment by jvgeee** [comment]
@TowhidKashem Nup, you've gotta add it within your target block.

In your podfile you'll see:

`target 'MyAppNameHere' do`

there'll be a bunch of stuff inside, and then at the end there'll be an `end` for it. Put it somewhere inside that block.

**Comment by BitPhinix** [comment]
Fix packaged up as an expo plugin:

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const { withDangerousMod, withPlugins } = require("@expo/config-plugins");
const {
  mergeContents,
} = require("@expo/config-plugins/build/utils/generateCode");
const fs = require("fs");
const path = require("path");

const STATIC_FRAMEWORKS = ["RNScreens"];

/**
 * @param {string} src
 * @param {string[]} staticFrameworks
 */
function addStaticFrameworks(src, staticFrameworks) {
  const staticFrameworksString = staticFrameworks
    .map((v) => `"${v}"`)
    .join(", ");

  const newSrc = `  $static_framework = [${staticFrameworksString}]
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end`;

  return mergeContents({
    tag: "./plugins/withStaticFrameworks.js",
    src,
    newSrc,
    anchor: /use_expo_modules!/m,
    offset: 0,
    comment: "#",
  }).contents;
}

const withStaticFrameworks = (
  /** @type {import("@expo/config-types").ExpoConfig} */ c,
) => {
  return withDangerousMod(c, [
    "ios",
    async (config) => {
      const file = path.join(config.modRequest.platformProjectRoot, "Podfile");
      const contents = await fs.promises.readFile(file, "utf8");
      await fs.promises.writeFile(
        file,
        addStaticFrameworks(contents, STATIC_FRAMEWORKS),
        "utf8",
      );
      return config;
    },
  ]);
};

module.exports = (
  /** @type {import("@expo/config-types").ExpoConfig} */ config,
) => withPlugins(config, [withStaticFrameworks]);
```

Add in `app.config.ts` under `"plugins": [...]`,
