### ISSUE TITLE
Animated.View layout animations break inside react-navigation

### ISSUE THREAD

**Issue by joeporpeglia** [software-mansion/react-native-reanimated#4816]
### Description

Layout animations stop working in some situations using `@react-navigation/bottom-tabs`. In the linked repository, the layout animations on tab one works until you navigate to tab two. The same layout animation works on tab two regardless of navigation state.

https://github.com/software-mansion/react-native-reanimated/assets/1399969/ca37c41d-084f-4037-8f5a-743e3d42806d

### Steps to reproduce

1. Run the app from the linked repository on an iOS simulator
2. Press the toggle button on the initial screen (tab one) - observe expected layout animation
3. Switch to tab two, then back to tab one
4. Press the toggle button again - observe that the layout animation doesn't run

### Snack or a link to a repository

https://github.com/joeporpeglia/repro-tab-navigator-layout-animation

### Reanimated version

3.3.0

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14

### Acknowledgements

Yes

**Comment by joeporpeglia** [comment]
**Workaround:** set `detachInactiveScreens={false}` on the tab navigator

**Comment by joeporpeglia** [comment]
Renamed this issue because the problem also exists for stack navigators (see #4822)

**Comment by AlexDM0** [comment]
I might be running into this as well. It seems that if you change the key of the animated object and have it hotreload it works again. Might be a hint?

**Comment by grifotv** [comment]
I'm experiencing the same issue since upgrading Reanimated from `2.14.4` to `3.3.0`.

**Comment by idrakimuhamad** [comment]
I'm facing this too which I think does relates to #4822 . My workaround right now is to give the component a random value of key.

```jsx
<AnimatedBox
    pos="relative"
    layout={Layout.springify()}
    key={`${Math.random()}`} <-- added this
/>
```

I do not however confirm if this could cause performance issue, but my screen having a rather small list of items, so I could take the chances.

**Comment by AlexanderEggers** [comment]
@Latropos I noticed that this issue also happens on Android when using 0.72 but not 0.71.

**Comment by jslok** [comment]
Seeing a similar issue when switching tabs on rn 0.81.4 and reanimated 4. detachInactiveScreens=false solves it but is not ideal.
