### ISSUE TITLE
react native reanimated onscroll event doesn't fire

### ISSUE THREAD

**Issue by theartificialguy** [software-mansion/react-native-reanimated#4849]
### Description

I'm trying to use react-native-reanimated (v2) in expo (sdk 48), the onScroll event ofuseAnimatedScrollHandler doesn't fire neither in FlatList nor in ScrollView, and yes I have added 'react-native-reanimated/plugin' in babel.config.js in plugins array as last item.

babel.config.js:
```
plugins: ['expo-router/babel', 'react-native-reanimated/plugin'],
```

Link to reproducible example: https://snack.expo.dev/@rog9274/rn-reanimated-scroll

### Steps to reproduce

1. create a new expo app (sdk 48)
2. install react-native-reanimated (using `npx expo install react-native-reanimated`)
3. add `react-native-reanimated/plugin` to `babel.config.js` plugins array as last item.
4. start server using `expo start --clear`
5. implement Animated FlatList to capture `onScroll` using `useAnimatedScrollHandler` hook `from react-native-reanimated`

Link to reproducible example: https://snack.expo.dev/@rog9274/rn-reanimated-scroll

### Snack or a link to a repository

https://snack.expo.dev/@rog9274/rn-reanimated-scroll

### Reanimated version

~2.14.4

### React Native version

0.71.8

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! @theartificialguy 
Yes, it doesn't work on Fabric (New Architecture). Here is our announcement of Reanimated 3.0: [LINK](https://blog.swmansion.com/announcing-reanimated-3-16167428c5f7). Only versions 3.x.x of react-native-reanimated are expected to work with the new architecture.

I've tested your example with old architecture and it works well. It should work with Reanimated3 and new architecture as well.

https://github.com/software-mansion/react-native-reanimated/assets/56199675/f166f532-a839-4286-afaa-fe5d0575a1e9

**Comment by little-buddy** [comment]
same issue, I use expo@49,
Does 49 turn on the new architecture by default?

**Comment by Latropos** [comment]
@little-buddy
I don't know, try this
```javascript
const uiManager = global?.nativeFabricUIManager ? 'Fabric' : 'Paper';
console.log(`Using ${uiManager}`);
```
and you will find out
