### ISSUE TITLE
Trouble running examples in Catalina

### ISSUE THREAD

**Issue by PaulHaze** [software-mansion/react-native-reanimated#487]
So I am having issues getting the Example folder up and running. I have followed the instructions in the Readme, have tried installing things with both Yarn and Npm, run pod install in the ios folder, run the npm run start in a separate terminal tab before trying react-native run-ios, deleted node_modules and yarn.lock/package-lock and restarted/rebooted everything, but no matter what I consistently get this error message:

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening ReanimatedExample.xcworkspace. Run CLI with --verbose flag for more details.`

`note: Using new build system`
`note: Planning build`
`note: Constructing build description`
`warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'RNScreens' from project 'Pods')`

`error: /Users/paulhayes/code/react/Native/UI/react-native-reanimated/Example/ios/Pods/Pods/Target Support Files/Pods-ReanimatedExample/Pods-ReanimatedExample.debug.xcconfig: unable to open file (in target "ReanimatedExample" in project "ReanimatedExample") (in target 'ReanimatedExample' from project 'ReanimatedExample')`

`2019-11-23 09:09:11.411 xcodebuild[59128:1648844] [MT] PluginLoading: Required plug-in compatibility UUID A74FBA51-FFEA-4409-B976-6FC3225A6F64 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SimplePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs`
`2019-11-23 09:09:11.412 xcodebuild[59128:1648844] [MT] PluginLoading: Required plug-in compatibility UUID A74FBA51-FFEA-4409-B976-6FC3225A6F64 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdjustFontSize.xcplugin' not present in DVTPlugInCompatibilityUUIDs`
`** BUILD FAILED **`

**Comment by PaulHaze** [comment]
I have a feeling the issue has to do with the fact that it seems to reference the Pods folder twice:
![Artboard](https://user-images.githubusercontent.com/20569604/69465478-5c8a8b00-0dd5-11ea-995a-f43e2a63c9fc.png)

and I was actually able to get it up and running by copying the pods folder and pasting it INTO the existing pods folder(!?). Not sure if that's really what is meant to solve the problem though....

**Comment by rafaelfaria** [comment]
+1 having the same issue.

**Comment by jakub-gonet** [comment]
Hi @PaulHaze,
try updating cocoapods on your system, it may be related with this issue https://github.com/CocoaPods/CocoaPods/issues/8091

If the problem persists please reopen.
