### ISSUE TITLE
Layout Animations not working in new architecture mode 

### ISSUE THREAD

**Issue by phamvantien96** [software-mansion/react-native-reanimated#4870]
### Description

I run FabricExample in our repo, i checkout to tag 3.4.1 then run FarbicExample on my device but the Layout Animations seem not working.

### Steps to reproduce

1. git clone https://github.com/software-mansion/react-native-reanimated
2. cd react-native-reanimated
3. yarn
4. cd FabricExample && yarn
5. yarn run android

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

3.4.1

### React Native version

0.71.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Device model

Realme x7 Pro (Android 12)

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Yes, we haven't ported Layout Animations to Fabric yet, but we are working on it. So I hope it we are available in upcoming months.

**Comment by elroyshilling** [comment]
> Yes, we haven't ported Layout Animations to Fabric yet, but we are working on it. So I hope it we are available in upcoming months.

@piaskowyk  This is an important feature raised more than a [year](https://github.com/software-mansion/react-native-reanimated/issues/3439) ago. This is literally blocking the switch to fabric.

**Comment by j-q-in-berlin** [comment]
Any news here?
