### ISSUE TITLE
EXC_BAD_ACCESS Exception 1, Code 16, Subcode 8 > Attempted to dereference garbage pointer 0x10.

### ISSUE THREAD

**Issue by saadiyakazi** [software-mansion/react-native-reanimated#4877]
### Description

Based on the sentry report the app crashes with the following error on App start in release mode

![Screenshot 2023-08-03 at 3 56 07 PM](https://github.com/software-mansion/react-native-reanimated/assets/50286168/cea0a953-5465-4a82-a9b7-6b2d786bd0b3)

### Steps to reproduce

Works fine on simulator and emulator have not faced issue

### Snack or a link to a repository

No Link

### Reanimated version

3.3.0

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

iPhone 13 pro max

### Acknowledgements

Yes

**Comment by dhameliyadharmesh** [comment]
facing same issue?

**Comment by piaskowyk** [comment]
Probably fixed with https://github.com/software-mansion/react-native-reanimated/pull/4878, but unfortunately without any reproduction, we are unable to help more 😔 We can reopen issue if you just provide some reproduction 🙏
