### ISSUE TITLE
Support for 0.59

### ISSUE THREAD

**Issue by Foskas** [software-mansion/react-native-reanimated#488]
Hi,

Can someone tell me what version should I use with React Native 0.59 ? I'm trying the latest but it refers to androidx.

Thank you!

**Comment by todorone** [comment]
@Foskas `1.2.0`

**Comment by sallar** [comment]
I think this issue can be closed now, because `1.2.0` is the last version that works with <= 0.59.x

**Comment by Foskas** [comment]
Thank you @todorone, I'll try as soon as possible.

Agree @sallar

**Comment by jakub-gonet** [comment]
I'll close it then
