### ISSUE TITLE
Cannot assign to read only property 'message' of object

### ISSUE THREAD

**Issue by ggunti** [software-mansion/react-native-reanimated#4885]
### Description

Hello.
I just installed and setup `react-native-reanimated@3.4.2`. But when I run the application, I get the following error message:
```
error: node_modules/react-native-reanimated/src/reanimated2/threads.ts: Cannot assign to read only property 'message' of object 'SyntaxError: unknown: Unexpected token (14:41)
```

<img width="575" alt="Captură de ecran din 2023-08-04 la 17 04 34" src="https://github.com/software-mansion/react-native-reanimated/assets/26307699/502dd71a-c308-4dbd-b7b9-4b49099d011c">

### Steps to reproduce

1. Create a react-native project (I use react-native 0.71.3)
2. Install and setup `react-native-reanimated@3.4.2`
3. run the project

### Snack or a link to a repository

-

### Reanimated version

3.4.2

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey 👋 Could you provide a reproduction of your issue because without it we can't help you 😔

**Comment by HilSny** [comment]
@ggunti we had this same problem and actually fixed it by regenning the yarn.lock file. Its a super strange fix for it but we got the hint to try that from t[his discussion](https://github.com/software-mansion/react-native-reanimated/issues/4645).

**Comment by piaskowyk** [comment]
@HilSny thanks for posting a solution 🙌
