### ISSUE TITLE
cancelAnimation seems to slow down the animation every time it starts again

### ISSUE THREAD

**Issue by michelecocuccio** [software-mansion/react-native-reanimated#4889]
### Description

I am trying to reproduce the [example on the documentation](https://reanimated-beta-docs.swmansion.com/docs/core/cancelAnimation) where I could start / stop an animation. The problem is that whenever i stop the animation with `cancelAnimation` and then start it again, it feels like the animation becomes slower and slower. I initially thought that it could be related to the Easing, but even with the linear easing it occurs. The video show the behaviour.

https://github.com/software-mansion/react-native-reanimated/assets/8071249/24c43644-362d-4827-9402-4910810520c5

I haven't added any fancy code, 

```
export default function Test() {
  const progress = useSharedValue(0);

  const progressBarStyle = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: progress.value }],
    };
  });

  const pauseAnimation = () => {
    cancelAnimation(progress);
  };

  const startAnimation = () => {
    progress.value = withTiming(200, {
      duration: 3000,
      easing: Easing.linear,
    });
  };

return (
      <Animated.View
        style={[{ width: 20, height: 20, backgroundColor: "red" }, progressBarStyle]}
      />
      <Text color={LBA_COLORS.BRAND_DARK_GOLD} onPress={pauseAnimation}>
        stop
      </Text>
      <Text color={LBA_COLORS.BRAND_DARK_GOLD} onPress={startAnimation}>
        start
      </Text>
)
  }

  ```

Expo version is 49.0.3
  
  

### Steps to reproduce

- Create a new shared value using `useSharedValue`
- Create a new animation and try stop / resume it using the example provided [here](https://reanimated-beta-docs.swmansion.com/docs/core/cancelAnimation) 
- You will notice the animation will slow down every time is started again

### Snack or a link to a repository

https://snack.expo.dev/@thewave/supportive-scone?platform=ios

### Reanimated version

3.3.0

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey there! 👋 This is not a bug 😅 The purpose of this API is not to pause or resume animations but to cancel the current animation and start a new one form current position. So, whenever you click "startAnimation", a new animation is initiated with a duration of 3000 ms from the current position of the component. This can give the impression that the animation is slower because the component has a shorter distance to travel in the same amount of time.

**Comment by michelecocuccio** [comment]
Yeah there was a flaw in my logic. I apologize for the useless opened issue.

**Comment by piaskowyk** [comment]
No problem! Thanks to your report probably other folks will find a solution faster 😃
