### ISSUE TITLE
Pattern to use animateNextTransition before an uncontrolled state change?

### ISSUE THREAD

**Issue by brunocrpontes** [software-mansion/react-native-reanimated#489]
Have any pattern to use animateNextTransition to handle uncontrolled state changes?

**Comment by mikedemarais** [comment]
hey @brunocrpontes! all these examples show how to use `animateNextTransition` in uncontrolled components! https://github.com/software-mansion/react-native-reanimated/tree/master/Example/transitions

**Comment by brunocrpontes** [comment]
Thanks bro! 😃

**Comment by mikedemarais** [comment]
gotchu fam 🤘️🤘️🤘️🤘️🤘️🤘️
