### ISSUE TITLE
ReferenceError: requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by nDeavor9** [software-mansion/react-native-reanimated#4890]
### Description

I'm using Expo SDK 49 with Router v2 and when I enable static output and export web using metro bundler, I get this error:
`ReferenceError: requestAnimationFrame is not defined at JSReanimated.scheduleOnUI`

[This issue](https://github.com/expo/router/issues/718) talks about it and [this PR](https://github.com/software-mansion/react-native-reanimated/pull/4665) is what I think is initiated to solve this issue. 

But it's been a month since the PR is opened and no moves are made on it yet.

If there's any work around I can do till then, please suggest. Thank you.

P.S: I'm not attaching any snack link because this issue doesn't appear during local runtime and can only be reproducible if we export it.

### Steps to reproduce

1. Install expo 49 with expo router v2.
2. Use drawer from expo-router/drawer.
3. Set bundler as 'metro' and output as 'static' in app.json.
4. Try exporting it using `npx expo export --platform web`

### Snack or a link to a repository

N/A

### Reanimated version

3.3.0

### React Native version

0.72.3

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by nDeavor9** [comment]
@piaskowyk Sorry for tagging directly. Can you please look into this? It's urgent.

**Comment by heythisischris** [comment]
I'm also experiencing this issue- would appreciate any help!

**Comment by awilson9** [comment]
Have a minimum reproducible example here: https://github.com/expo/expo/issues/23412#issuecomment-1680016933

It's the same error message (`ReferenceError: requestAnimationFrame is not defined`)

No idea if it's related but definitely feels like it is

**Comment by mamatsunami** [comment]
I had exactly the same issue but on Next.js.

Don't know why, but moving `import "raf/polyfill";` from `_app.tsx` to `_document.tsx` fixed the issue on my app.

**Comment by nightness** [comment]
@mamatsunami Thanks! I didn't even have a "raf/polyfill"

**Comment by piaskowyk** [comment]
Should be solved by https://github.com/software-mansion/react-native-reanimated/pull/4665

This fix is available since 3.5.0
