### ISSUE TITLE
textShadowRadius not animating on web

### ISSUE THREAD

**Issue by itsramiel** [software-mansion/react-native-reanimated#4903]
### Description

I am trying to animated the value of textShadowRadius. Works on ios, android, but not web

https://github.com/software-mansion/react-native-reanimated/assets/80689446/ab3cf3b1-ff4f-4ce7-a2ff-23b03c656406

### Steps to reproduce

1. Simply try to animate the textShadowRadius
Here is a sample code:
```
import { StatusBar } from "expo-status-bar";
import { useEffect } from "react";
import { StyleSheet, View } from "react-native";
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withSequence,
  withTiming,
} from "react-native-reanimated";

export default function App() {
  const radius = useSharedValue(0);

  useEffect(() => {
    radius.value = withRepeat(
      withSequence(
        withTiming(10, { duration: 500 }),
        withTiming(0, { duration: 500 })
      ),
      -1,
      true
    );
  }, []);

  const rStyles = useAnimatedStyle(() => {
    return {
      textShadowColor: "rgba(255, 0, 0, 0.7)",
      textShadowRadius: radius.value,
      textShadowOffset: { height: 0, width: 0 },
    };
  }, []);

  return (
    <View style={styles.container}>
      <Animated.Text style={rStyles}>
        Open up App.tsx to start working on your app!
      </Animated.Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

### Snack or a link to a repository

https://github.com/itsramiel/text-shadow-radius-web

### Reanimated version

3.3.0

### React Native version

0.72.3

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @itsramiel! I've merged [this PR](https://github.com/software-mansion/react-native-reanimated/pull/4967) which should fix this issue. Could you please confirm that it is indeed solved?

**Comment by itsramiel** [comment]
Actually not sure I can patch since I need the transpiled js I guess. Any release anytime soon?

**Comment by m-bert** [comment]
Yes! We do have release plans for 3.5.0 in the near future.
