### ISSUE TITLE
FlatList onScroll event

### ISSUE THREAD

**Issue by davx1992** [software-mansion/react-native-reanimated#491]
Hello All,
I have an issue that when I use FlatList to create horizontal scroll I need to listen for OnScroll event.
When I mapping Native event with event() I receive error that I need to add Animated prefix to FlatList to use event(), however then I receive error:
`Invariant violation: element type is invalid: expect a string or class/function but got undefined.`

Does FlatList is working in reanimated? When I changed FlatList to ScrollView it worked with Animated.ScrollView .
Do we have any working example with OnScroll and FlatList?

**Comment by terrysahaidak** [comment]
Hi @davx1992. react-native-reanimated does not provide an Animated FlatList, but it provides the ScrollView component, so you can use `renderScrollComponent` to provide an Animated ScrollView to your FlatList:

```jsx
<FlatList 
  {...props}
  renderScrollComponent={(props) => <ScrollView {...props} onScroll={(evt) => {
    console.log(evt);
  }} />}
/>
```

**Comment by davx1992** [comment]
Thank you @terrysahaidak, will try with your example.

**Comment by Daavidaviid** [comment]
I can't make it works, it's like the `renderScrollComponent` prop is not called.

**Comment by MoeMamdouh** [comment]
It doesn't work with me too

**Comment by terrysahaidak** [comment]
Hi @MoeMamdouh, could you provide a snack or some sample code, please?

**Comment by CoryWritesCode** [comment]
I have an `Animated.createAnimatedComponent(FlatList)` and it doesn't seem to be firing the `onScroll={({ nativeEvent }) => console.log(nativeEvent)}`

**Comment by jakub-gonet** [comment]
@CoryWritesCode, please provide a small repro we can test it on.
