### ISSUE TITLE
[{... width: <<NaN>>}] is not usable as a native method argument

### ISSUE THREAD

**Issue by canpoyrazoglu** [software-mansion/react-native-reanimated#4919]
### Description

I'm using styles like this:

```
 const expandedWidth = Math.round(props.expandedWidth);
    const animatedStyle = useAnimatedStyle(() => {
        return {
            width: interpolate(props.expansionAnimation.value, [0, 1], [0, expandedWidth]),
            marginHorizontal: interpolate(props.expansionAnimation.value, [0, 1], [0, HYPHEN_EXPANDED_MARGIN_HORIZONTAL]),
        };
    });
    return (
        <Animated.View
            style={[
                styles.hyphen,
                animatedStyle,
            ]}
        />
    );

[...]
const styles = StyleSheet.create({
    hyphen: {
        height: 4,
        borderRadius: 3,
        backgroundColor: '#2C73D2',
    },
   [...]
});
```

Expansion animation is `Animated.SharedValue<number>`. I guarantee that it's never null or undefined (I have logs, just in case, checking it and they never get hit). I also log `expandedWidth` and it also has positive, "sane" values like 100-ish (nothing like 0, negative, infinity, NaN etc.).

It works perfect on iOS. However, on Android, after navigating to some other screens and back around, I get the following error:

`[7405,RCTView", 11,"height": 4,borderRadius":3,"backgroundColor":-13863982,width":"<<NaN>>""'marginHorizontal" :0.28953504585401957,collapsable":false}] is not usable as a native method argument` (that's also how I pinpointed the issue to the specific component by checking the other style values).

Here is a screenshot with the error too:
![Screenshot 2023-08-12 at 13 46 30](https://github.com/software-mansion/react-native-reanimated/assets/4348413/075955d1-91e7-40e4-9278-8515408ff7e9)

I don't know where "collapsable" is coming from, it's not in my code. I suspect `width` being `NaN` causes this. Why would `width` which is set to `interpolate(props.expansionAnimation.value, [0, 1], [0, expandedWidth])` ever be `NaN` (assuming _that_ is the problem)? Or what else can be the problem? This is only happening on Android and generally after navigating around the app.

### Steps to reproduce

1. Have a view as such:
```
   const animatedStyle = useAnimatedStyle(() => {
        return {
            width: interpolate(props.expansionAnimation.value, [0, 1], [0, expandedWidth]),
            marginHorizontal: interpolate(props.expansionAnimation.value, [0, 1], [0, HYPHEN_EXPANDED_MARGIN_HORIZONTAL]),
        };
    });
    return (
        <Animated.View
            style={[
                styles.hyphen,
                animatedStyle,
            ]}
        />
    );
```

2. Navigate around the app. Navigate around screens etc.

(because of the complex nature of the problem I don't know what exact steps are)

---

I also don't know how/when it started as I have always been developing the app on iOS simulators/devices and never on Android. 

### Reanimated version

3.4.1

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 5 (Emulator) Android 13

### Acknowledgements

Yes

**Comment by canpoyrazoglu** [comment]
Dear @github-actions I know you are a bot but I can't replicate such a complex behavior as it doesn't seem to happen in isolation but only in my app with a complex hierarchy.

**Comment by dhruvpvx** [comment]
log the expandedWidth and props.expandedWidth one of them is NaN

**Comment by raajeshmani** [comment]
Happens to me when i pass in an interpolate's return value to a style field that expects a number. 

```
const animatedStyles = useAnimatedStyle(() => {
    const translateY = interpolate(value, [0, 1], [250, 0])
    return {
      transform: [{ translateY: translateY }],
    }
  })
```
`transformY: <<NaN>>` is not usable as a native method argument is the error. And downgrading to `3.3.0` from `3.4.2` gives the error `transformY: 0` is not usable as a native method argument.

**Comment by canpoyrazoglu** [comment]
One of my colleagues suggested a solution to check whether a value is NaN in a worklet function and assign a default to it if it is NaN. While it "works", I still have no idea why it's being passed NaN in the first place.

**Comment by Latropos** [comment]
I am unable to reproduce this error on our end. Could you please give some more information:

>Why would width which is set to interpolate(props.expansionAnimation.value, [0, 1], [0, expandedWidth]) ever be NaN (assuming that is the problem)?

You can log your width to check if this ever turn to NaN: 
```diff
    const animatedStyle = useAnimatedStyle(() => {
+ const interpolatedWidth = interpolate(props.expansionAnimation.value, [0, 1], [0, expandedWidth]);
        return {
-            width: interpolate(props.expansionAnimation.value, [0, 1], [0, expandedWidth]),
+            width: interpolatedWidth
            marginHorizontal: interpolate(props.expansionAnimation.value, [0, 1], [0, HYPHEN_EXPANDED_MARGIN_HORIZONTAL]),
        };
    });
```

>This is only happening on Android and generally after navigating around the app.
Do you use `@react-navigation/bottom-tabs` or `@react-navigation/stack`?

**Comment by henrymoulton** [comment]
@Latropos we're seeing this too

**Comment by welschmoor** [comment]
I have the same happening. I don't have any dynamic width in my app:
<img width="474" alt="Screenshot 2024-02-14 at 08 48 48" src="https://github.com/software-mansion/react-native-reanimated/assets/87126711/d117ff77-bd0b-4e30-a1d3-9c4d5d7558de">

**Comment by rohit9625** [comment]
Encountered this error recently even though I didn't make any changes to the code. What is going on with reanimated?

**Comment by piaskowyk** [comment]
Hey @rohit9625, could you provide me with a reproduction so I can try to debug it on my own?

**Comment by rohit9625** [comment]
It was a very strange issue, @piaskowyk. I spent hours on solving and eventually did, but after that the issue was automatically resolved even without my changes. I still don't know the cause but somewhere in the I had height and width set as null.
