### ISSUE TITLE
Composing/forwarding onScroll handlers

### ISSUE THREAD

**Issue by ACHP** [software-mansion/react-native-reanimated#4922]
Hello :)
First: Thank you for this amazing library, it is really awesome

_Disclaimer_ : This is not a bug but a question/idea that has already been posted 1 year ago in the [*Discussion*](https://github.com/software-mansion/react-native-reanimated/discussions/3611) section, but didn't received any response from the community.

I have a question regarding what we could call "ScrollHandler composition".
I was wondering if there was a **clean** way to "compose"/"merge" 2 different `useAnimatedScrollHandler` hook ?

## why

Let's say I want to create a Fancy ScrollView that use `useAnimatedScrollHandler` internally to do some animation, on the background color for example.
I want to expose this new component to the team and let them use their own animations (in addition to mines) using `reanimated` primitives.

Maybe I missed something in the documentation, but as of today it seems that there is no **easy** way to do it.
We have to provide a custom API for our `FancyScrollView` to handle `onScroll`, `onMomentumScrollEnd` etc ...
This is not ideal because now the implementation details of our FancyScrollView have somehow leaked outside our component.

## Example

```typescript jsx
import ReAnimated, {useAnimatedScrollHandler, useAnimatedStyle, useSharedValue} from 'react-native-reanimated';

/**
 * Base Fancy component
 */
const FancyScrollView = (props) => {
  const scrollOffsetY = useSharedValue<number>(0);
  const scrollViewStyle = useAnimatedStyle(()=> {
    return {/*...*/}
  })
  const onScrollLocalHandler = useAnimatedScrollHandler((event) => (scrollOffsetY.value = event.contentOffset.y));

  const onScrollHandler = onScrollLocalHandler; // <- how can I merge props.onScroll here ?
  
  return <ReAnimated.ScrollView onScroll={onScrollHandler} style={scrollViewStyle}>{props.children}</ReAnimated.ScrollView>;
};

/**
 * SuperFancy component overload
 */
const SuperFancyScrollView = (props) => {
  const scrollOffsetY = useSharedValue<number>(0);
  const onScrollLocalHandler = useAnimatedScrollHandler((event) => (scrollOffsetY.value = event.contentOffset.y));

  return <FancyScrollView onScroll={onScrollLocalHandler}>{props.children}</FancyScrollView>;
};

```

## Possibly terrible solution
With my zero expertise in **ReAnimated**, I managed to code a helper function to easily compose `onScroll` handler.
I'm pretty sure I should not call `ref.current?.worklet(event)` myself nor using `useHandler` that way but it seems to work.
(I removed the typing for simplicity)
```typescript jsx
function useComposedScrollHandler(
  onScrollRefList,
) {
  const {doDependenciesDiffer} = useHandler({}, onScrollRefList);

  return useEvent(
    (event) => {
      'worklet';

      for (const ref of onScrollRefList) {
        ref.current?.worklet?.(event);
      }
    },
    ['onScroll', 'onScrollBeginDrag', 'onScrollEndDrag', 'onMomentumScrollBegin', 'onMomentumScrollEnd'],
    doDependenciesDiffer,
  );
}

// usage
const FancyScrollView = (props) => {
  const scrollOffsetY = useSharedValue<number>(0);
  const scrollViewStyle = useAnimatedStyle(()=> {
    return {/*...*/}
  })
  const onScrollLocalHandler = useAnimatedScrollHandler((event) => (scrollOffsetY.value = event.contentOffset.y));

  const onScrollHandler = useComposedScrollHandler([onScrollLocalHandler, props.onScroll]);

  return <ReAnimated.ScrollView onScroll={onScrollHandler} style={scrollViewStyle}>{props.children}</ReAnimated.ScrollView>;
};
```

Thank you for your answers and your time ... and this Library

_Originally posted by @ACHP in https://github.com/software-mansion/react-native-reanimated/discussions/3611_

**Comment by NicholasBoccuzzi** [comment]
Any update on this? Would be extremely helpful.

**Comment by ACHP** [comment]
@kmagiera maybe ?
