### ISSUE TITLE
Invalid `RNReanimated.podspec` file: different prefix: ""

### ISSUE THREAD

**Issue by 571024079** [software-mansion/react-native-reanimated#4924]
### Description

Fetching podspec for `RCT-Folly` from `../../RN/node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'react-native/package.json'
Require stack:
- /Users/admin/GerritRep/unity/HomeNative/home-iOS/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at [eval]:1:9
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at node:internal/process/execution:75:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:74:60)
    at node:internal/main/eval_string:27:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/admin/GerritRep/unity/HomeNative/home-iOS/[eval]'
  ]
}
[!] Failed to load 'RNReanimated' podspec: 
[!] Invalid `RNReanimated.podspec` file: different prefix: "" and "/Users/admin/GerritRep/unity/HomeNative/home-iOS/Pods".

 #  from /Users/admin/GerritRep/unity/RN/node_modules/react-native-reanimated/RNReanimated.podspec:5
 #  -------------------------------------------
 #  reanimated_package_json = JSON.parse(File.read(File.join(__dir__, "package.json")))
 >  config = find_config()
 #  assert_no_multiple_instances(config)
 #  -------------------------------------------

### Steps to reproduce

1、react-native-gesture-handler need react-native-reanimated
2、config package.json
3、yarn install
4、pod install  

### Snack or a link to a repository

N/A

### Reanimated version

3.4.2

### React Native version

0.70.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 pro 16.1

### Acknowledgements

Yes

**Comment by 571024079** [comment]
I guess it was caused by a problem with my file path. I tried to modify the file path of the project again and found that the error disappeared. Can you tell me how to modify config=find_ Config() obtains the path for the configuration

**Comment by 571024079** [comment]
![image](https://github.com/software-mansion/react-native-reanimated/assets/6406223/0066c1c3-0f60-40fd-939b-4a1d0234853f)
change to "Pathname.new(react_native_common_dir_absolute).realpath" can install

**Comment by Alvi24** [comment]
i have the same issue:

```
Cause: Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: different prefix: "" and "/Users/alvipalloshi/Projects/LookUp/apps/mobile/ios/Pods".
 #  -------------------------------------------
 #  reanimated_package_json = JSON.parse(File.read(File.join(__dir__, "package.json")))
 >  $config = find_config()
 #  assert_minimal_react_native_version($config)
 #  -------------------------------------------
```

    "expo": "~54.0.11",
    "react-native": "0.81.4",
    "react-native-reanimated": "~4.1.1",

**Comment by jnsdrssn** [comment]
make sure you have `react-native-worklets` installed (if on v4)
