### ISSUE TITLE
Child component does not resize properly if it remounts when parent changes dimensions

### ISSUE THREAD

**Issue by tpcstld** [software-mansion/react-native-reanimated#4932]
### Description

When a child component is using relative layouts such as `height: 100%`, it sometimes does not properly resize when the parent resizes instantaneously via `useAnimatedStyle` and the child component is remounting.

This affects iOS, and I am unsure if it affects other platforms. From my testing, this occurs in both debug and release builds, and on both physical devices and simulators.

### Steps to reproduce

The minimal repro is below. In the repro, the "parent" element is has a red background and the child component has a green background. Clicking "Press Me" toggles the height of the parent element while remouting the child. I expect that I would just see the green rectangle expand and shrink.

Instead, sometimes when I click the green rectangle does not shrink. Other times, the green rectangle does not expand and I see the red peek out.

https://github.com/software-mansion/react-native-reanimated/assets/5456182/e580c151-28fa-47fa-a3ae-649bdcd94aef

I notice that:

1. If I animate the height transition (e.g. using `withSpring`) then the issue does not occur.
2. If I remove the `key` prop on the child, thus no longer remounting, then the issue does not occur.

```typescript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import Reanimated, {
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';
import {Pressable, View, StyleSheet, Text} from 'react-native';

function App(): JSX.Element {
  const [value, setValue] = React.useState(false);
  const height = useSharedValue(100);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      backgroundColor: 'red',
      height: height.value,
      width: '100%',
    };
  });

  const animate = React.useCallback(() => {
    setValue(v => !v);
    height.value = height.value === 100 ? 200 : 100;
  }, [height]);

  return (
    <View style={styles.container}>
      <Reanimated.View style={animatedStyle}>
        <Reanimated.View key={value ? 1 : 2} style={styles.inner} />
      </Reanimated.View>
      <Pressable onPress={animate} style={styles.button}>
        <Text>Press Me</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    height: '100%',
  },
  button: {
    position: 'absolute',
    bottom: 100,
  },
  inner: {
    backgroundColor: 'green',
    height: '100%',
  },
});

export default App;
```

### Snack or a link to a repository

https://github.com/tpcstld/reanimated-bug

### Reanimated version

3.4.2

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by tpcstld** [comment]
I've noticed that when the child fails to layout properly, `onLayout` for the child is called twice (once with the previous height, and another with the new height (which it fails to go to)). But when the child does lay out properly, `onLayout` is called only once.

If the child does not remount itself, then `onLayout` is also only called once.

**Comment by tpcstld** [comment]
Also when it works, the child's `onLayout` fires after the parent `onLayout`, but when it doesn't work both of the child's `onLayout` fires before the parent's.

**Comment by piaskowyk** [comment]
Hey! Thanks for the report and the detailed issue description 🙌 I was able to reproduce this problem, and I'm trying to fix it. I'll notify you about progress, but it can take time because this isn't a trivial issue 😅
