### ISSUE TITLE
export 'WithDecayConfig' was not found in './decay' (possible exports: withDecay)

### ISSUE THREAD

**Issue by JacobDel** [software-mansion/react-native-reanimated#4936]
### Description

I have an app that I use for android, ios and web.
When I launch the react native web application I get the following error:

```
Failed to compile.

export 'WithDecayConfig' (reexported as 'WithDecayConfig') was not found in './decay' (possible exports: withDecay)
ERROR in ./node_modules/react-native-reanimated/lib/module/reanimated2/animation/index.js 4:0-53
export 'WithDecayConfig' (reexported as 'WithDecayConfig') was not found in './decay' (possible exports: withDecay)

webpack compiled with 1 error
No issues found.
```

### Steps to reproduce

1. set babel.config.js content to:
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset', '@babel/preset-react'],
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
  plugins: [
    [
      'module-resolver',
      {
        root: [
          './src',
        ],
        alias: {
          '@shared': './src/shared',
          '@api': './src/Api/generated',
        },
        extentions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
      },
    ],
    '@babel/plugin-proposal-export-namespace-from',
    'react-native-reanimated/plugin',
  ],
};
```
2.  execute `react-app-rewired start`

### Snack or a link to a repository

[snack](https://snack.expo.dev/jv2x-3FAi)

### Reanimated version

3.4.2

### React Native version

0.70.6

### Platforms

Web

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by JacobDel** [comment]
This can not be reproduced in a snack due to the lack of terminal, config-overrides.js, babel.config.js functionality

**Comment by brianreavis** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/4645#issuecomment-1671875388
