### ISSUE TITLE
ReanimatedRuntime'jsc/JSCRuntime.h' file not found

### ISSUE THREAD

**Issue by urtheone** [software-mansion/react-native-reanimated#4937]
### Description

after upgrade RN to 0.72.3, 
with "react-native-reanimated": "^3.4.2",
building in xcode:
`ReanimatedRuntime'jsc/JSCRuntime.h' file not found`

### Steps to reproduce

1. rn 0.72.3
2. "react-native-reanimated": "^3.4.2",

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.4.2

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

Real device

### Device model

ios 16.2

### Acknowledgements

Yes

**Comment by Latropos** [comment]
> Hey 👋
Could you provide a reproduction for this issue? Unfortunately we can't help without any information about reproduction 😕

I'm closing the issue due to inactivity
