### ISSUE TITLE
useAnimatedGestureHandler is returning object instead of function. 

### ISSUE THREAD

**Issue by ponikar** [software-mansion/react-native-reanimated#4939]
### Description

I am using Expo managed workflow.

`useAnimatedGestureHandler` hook seems to be not working in the next version of reanimated. 

I am trying to use this hook with `PanGestureHandler` and its throwing error when user starts swiping.

I checked the docs I couldn't found `useAnimatedGestureHandler` documentation section for this hook.

Am I missing something here? Did we drop a support for gesture handlers? 

Here's the code snippets. 

```javascript 
const onGesture = useAnimatedGestureHandler({
    onStart: (e, context) => {
      context.lastY = e.translationY;
      isDragging.current = true;
    },
    onActive: (e, context) => {
      ballY.current = e.translationY + context.lastY;
    },
    onEnd: (_, context) => {
      context.lastY = _.translationY;
      isDragging.current = false;
    },
  });

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <PanGestureHandler onGestureEvent={onGesture}>
        <Canvas
          style={{
            flex: 1,
          }}
        >
          <Image
            width={dimens.width}
            fit="cover"
            height={dimens.height}
            image={background}
          />

          <Image
            width={200}
            height={200}
            image={pikachu}
            x={pikaMovement}
            y={200}
            fit="contain"
          />

          <Image
            width={200}
            height={200}
            image={image}
            x={center.x - 100}
            y={ballY}
            fit="cover"
          />
        </Canvas>
      </PanGestureHandler>
    </GestureHandlerRootView>
  );
};
```

Here's the error 
![image](https://github.com/software-mansion/react-native-reanimated/assets/54766861/7c73bb05-8f58-4d09-8618-9b5feb112ec2)

### Steps to reproduce

1. Create a expo project 
2. Install `react-native-reanimated` and `react-native-gesture-handler`
3. Try to use `useAnimatedGestureHandler` hook with `PanGestureHandler`. 

### Snack or a link to a repository

https://example.com

### Reanimated version

~3.3.0

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @ponikar, `useAnimatedGestureHandler` is old API which is no longer supported. Check https://docs.swmansion.com/react-native-gesture-handler/docs/guides/upgrading-to-2 for more information about how to migrate to new API.

**Comment by ponikar** [comment]
I see, Thank you :)
