### ISSUE TITLE
V3 Failed to create a worklet. Did you forget to add Reanimated Babel plugin in babel.config.js?

### ISSUE THREAD

**Issue by alejandro-geeksquare** [software-mansion/react-native-reanimated#4940]
### Description

I have deleted node_modules, ios and android folder. Cleared cache, restarted my computer but still getting the same error. Any ideas? Thank you so much

<img width="855" alt="Captura de pantalla 2023-08-18 a las 17 51 47" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/c0de80df-fd99-4346-80d2-aa883e495300">
<img width="855" alt="Captura de pantalla 2023-08-18 a las 17 51 37" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/ba249b35-d452-405f-8be7-855c4830f8b8">
<img width="855" alt="Captura de pantalla 2023-08-18 a las 17 50 38" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/27d7d720-dca9-4828-be3c-8174fa93e9b4">
<img width="421" alt="Captura de pantalla 2023-08-18 a las 17 52 23" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/c10f7a6f-7923-4028-9640-2edff1694fb7">
<img width="1251" alt="Captura de pantalla 2023-08-18 a las 17 52 38" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/6e091209-a303-45a5-90a9-3f2be837c196">

**Comment by alejandro-geeksquare** [comment]
this problem appears when i try to start
const Drawer = createDrawerNavigator()
from "@react-navigation/drawer"

**Comment by danielk-sn** [comment]
Also seeing the same, trying to upgrade my project and this has been a huge headache for the past week

**Comment by dhruvpvx** [comment]
You are writing it wrong

change

`module.exports = function (api) {
api.cache(true)
return {
presets: ["babel-preset-expo"], plugins: [
"module-resolver"
root: [".
"],
alias: {
src: "./src"
?
}, "react-native-reanimated/plugin"
]
]`

to 

`module.exports = function (api) {
api.cache(true)
return {
presets: ["babel-preset-expo"], plugins: [
"module-resolver"
root: [".
"],
alias: {
src: "./src"
?
}
],
"react-native-reanimated/plugin"
]`

**Comment by alejandro-geeksquare** [comment]
@dhruvpvx Thank you very much, this stupid error is driving me crazy

**Comment by Salmahana** [comment]
I am having same problem above , but I am not able to understand the changes that dhruvpvx wrote , is it in babel.config.js file ?

**Comment by dhruvpvx** [comment]
> I am having same problem above , but I am not able to understand the changes that dhruvpvx wrote , is it in babel.config.js file ?

Yes
