### ISSUE TITLE
SyntaxError: unknown: Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by iSplasher** [software-mansion/react-native-reanimated#4943]
### Description

Trying to use this package in my project and have followed the installation steps to a T but still run into an error when I try to use jsx syntax in a file where I import the components from this package.
Same thing in a brand new project, see repro.

### Steps to reproduce

1. Install expo as per their docs
2. Install this package as per docs
3. Run `npm start -- --reset-cache`

App won't compile and you get: `TypeError: Cannot assign to read only property 'message' of object 'SyntaxError: unknown: Support for the experimental syntax 'jsx' isn't currently enabled (13:14):`

### Snack or a link to a repository

https://github.com/iSplasher/expo-react-react-native-reanimated-error

### Reanimated version

~3.3.0

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @iSplasher. I took a look at your repro and found the reason for this error. You are trying to define a component inside `useAnimatedStyle` and this is not supported - this function is meant only to create animated styles for components - its code is ran on UI thread where creating `Animated.View` or `View` doesn't make much sense. You should move that logic elsewhere.

**Comment by iSplasher** [comment]
Thanks for letting me know. That piece of info sounds incredibly valuable. Would it make sense to add a notice/warning in the docs?

**Comment by iSplasher** [comment]
That sounds reasonable. Perhaps you could just point it out briefly under the UI/JavaScript thread explanation. Thanks for the reply!
