### ISSUE TITLE
-0.0 is not equal to 0.0 on Android

### ISSUE THREAD

**Issue by zamotany** [software-mansion/react-native-reanimated#495]
## Bug report

Animated Value of `-0.0` is not equal to Animated Value of `0.0` on Android, but it's working properly on iOS. Even when wrapping `-0.0` with `abs` the result is the same.

## Environment
- `react-native`: `0.61.2`
- `react-native-reanimated`: `1.4.0`

## Repro code

Running the following code:

```js
Animated.useCode(
    () =>
      Animated.block([
        Animated.debug(
          'ReanimatedTest: is -0.0 equal 0.0 =',
          Animated.eq(new Animated.Value(-0.0), new Animated.Value(0.0)),
        ),
        Animated.debug(
          'ReanimatedTest: is -0.0 less or equal 0.0 =',
          Animated.lessOrEq(new Animated.Value(-0.0), new Animated.Value(0.0)),
        ),
        Animated.debug(
          'ReanimatedTest: is 0.0 less or equal -0.0 =',
          Animated.lessOrEq(new Animated.Value(0.0), new Animated.Value(-0.0)),
        ),
        Animated.debug(
          'ReanimatedTest: is abs(-0.0) equal 0.0 =',
          Animated.eq(
            Animated.abs(new Animated.Value(-0.0)),
            new Animated.Value(0.0),
          ),
        ),
      ]),
    [],
  );
```
Gives:
```
ReanimatedTest: is -0.0 equal 0.0 = 0.0
ReanimatedTest: is -0.0 less or equal 0.0 = 1.0
ReanimatedTest: is 0.0 less or equal -0.0 = 1.0
ReanimatedTest: is abs(-0.0) equal 0.0 = 0.0
```

## Workaround

When comparing value which can be `-0.0` for equality, the following snippet returns correct results:

```js
lessOrEq(
  yourAnimatedValue,
  new Animated.Value(0.0),
)
```

**Comment by jakub-gonet** [comment]
Hey @zamotany, thanks for reporting!

Could you write how you stumbled upon this bug? It's a bit unusual to compare doubles by eq and even more unusual to get `-0.0`. I wrote explanation below, but I'm deeply interested how did you manage to discover that :>

This happened because we compared values by `Double.equals(Double)` which respects [IEEE 754 standard](https://en.wikipedia.org/wiki/Signed_zero) and that's why `-0.0 != 0.0` on Android.

After merging #498 this should be consistent on all platforms.

**Comment by zamotany** [comment]
I'm have a draggable (vertically) element and some fixed list of points, when the element passes this point is needs to run a callback with normalised value `0`, `1`, etc. So I have to compare the translation Y with the points and it happens that for the top point on Android the translation is `-0.0`.

**Comment by jakub-gonet** [comment]
I see, did you consider comparing by using some small delta? Floating point numbers aren't precise, so you can miss some points by using `eq`.

Just some food for thoughts 😛
