### ISSUE TITLE
Typescript - Issue with useAnimatedProps type conflicting with type Component<AnimateProps<ViewProps>>

### ISSUE THREAD

**Issue by JDMathew** [software-mansion/react-native-reanimated#4952]
### Description

If I have the following simplified example

``` typescript
const App () => {
  const headerProps = useAnimatedProps(
    () => ({
      pointerEvents:
        scrollY.value < APPEARANCE_OFFSET
          ? 'none'
          : 'auto',
    }),
    [],
  );
  
 return (<Animated.View
      animatedProps={headerProps}
    />);
};

const APPEARANCE_OFFSET = 60;


```

I would get the following ts error on `animatedProps`:

```
    No overload matches this call.
  Overload 1 of 2, '(props: AnimateProps<ViewProps> | Readonly<AnimateProps<ViewProps>>): View', gave the following error.
    Type 'Partial<{ pointerEvents: string; }>' is not assignable to type 'Partial<AnimateProps<ViewProps>>'.
      Types of property 'pointerEvents' are incompatible.
        Type 'string | undefined' is not assignable to type '"box-none" | "none" | "box-only" | "auto" | SharedValue<"box-none" | "none" | "box-only" | "auto" | undefined> | undefined'.
  Overload 2 of 2, '(props: AnimateProps<ViewProps>, context: any): View', gave the following error.
    Type 'Partial<{ pointerEvents: string; }>' is not assignable to type 'Partial<AnimateProps<ViewProps>>'.ts(2769)
    
```

This is because in the above example `headerProps` type would result in `Partial<{pointerEvents: string}>` while the Animated View expects  `Partial<Animated.AnimateProps<ViewProps>> | undefined` 

The underlying issue is the return type for `useAnimatedProps` is not narrowing in the above example to: `pointerEvents: "none" | "auto"` while the expected type for pointerEvents from ViewProps is: `pointerEvents?: 'box-none' | 'none' | 'box-only' | 'auto' | undefined`

### Steps to reproduce

1. copy above code into a ts react native app or code sandbox environment with the latest packages for `react native` and `react-native-reanimated`
2. verify / inspect error

### Snack or a link to a repository

https://gist.github.com/JDMathew/b803a3263a4911c4538c8c98d054a277

### Reanimated version

3.3.0

### React Native version

0.72.3

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by dhruvpvx** [comment]
`const headerProps = useAnimatedProps<Partial<AnimateProps<ViewProps>>>(
    () => ({
      pointerEvents: scrollY.value < APPEARANCE_OFFSET ? 'none' : 'auto',
    }),
    [],
  );`

**Comment by JDMathew** [comment]
@dhruvpvx, thanks that does solve the type issue but I believe with typescript 5.0 we can now update the `useAnimatedProps` function type to auto narrow so one doesn't need to pass a type through to the function.

**Comment by tjzel** [comment]
Hi @JDMathew. You should make the following change:

```typescript  
const headerProps = useAnimatedProps(
    () => ({
      pointerEvents:
        scrollY.value < APPEARANCE_OFFSET
          ? 'none' as const
          : 'auto' as const,
    }),
    [],
  );
```
To get rid of the error and which is reasonable solution within TypeScript ecosystem. Currently `useAnimatedProps` is awaiting it's type refactor.

While the new `const` marking feature of the whole type from TS5 seems interesting and good for solving these types of cases, we are currently not planning to upgrade to TS5 and use its new syntax since then our users would be forced to upgrade as well. In the future I'm definitely interested in using that however I'm not sure it will help with all the quirks of these type of issues.
