### ISSUE TITLE
Animating height of last item in FlatList or ScrollView is laggy.

### ISSUE THREAD

**Issue by slavko-lukic** [software-mansion/react-native-reanimated#4959]
### Description

In a FlatList, if every item has animation on height (in my case, list item expands to show more options), only when animation runs on last item it causes lag, animation on other items are smooth.

### Steps to reproduce

1. Create FlatList
2. Add animations for height on component that is called by renderItem

### Snack or a link to a repository

/

### Reanimated version

3.1.0

### React Native version

0.71.7

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by fukemy** [comment]
at least give some video/code...

**Comment by slavko-lukic** [comment]
I found different solution to my problem in the meantime, but now when I tried to reproduce the problem as simple as possible to upload video and code there was no lag so potentially something else caused this initially.

I will close issue for now.
