### ISSUE TITLE
Unable to resolve module '../utils'

### ISSUE THREAD

**Issue by andrewterex20190813** [software-mansion/react-native-reanimated#497]
I added react-native-animated@1.4.0 package to my react native project as peer dependency.
> npm install react-native-reanimated@1.0.0 --save-dev --ignore-scripts install-peers

And run the project.
> react-native run-android

But get this error in red screen.
> Unable to resolve module '../utils' from 'node_modules\\react-native-reanimated\\src\\core\\AnimatedClock.js'

I struggled with this problem for a whole day, install other versions, npm cache clean, npm install gain and even rebuild project totally from the first.

Anyone who have much experience in react native, please help me.
Thank you.

**Comment by jakub-gonet** [comment]
Hi @andrewterex20190813!

You added `1.0.0` version, can you provide an output of `ls -Rl node_modules\react-native-reanimated\src`?

**Comment by andrewterex20190813** [comment]
Hello, thank you for your reply.
I removed node_modules and npm install again.
However, now is okay.

**Comment by jakub-gonet** [comment]
Cool, glad it worked eventually!

**Comment by dragneel30** [comment]
Hi, the error is happening to me and removing and install the node_modules didnt work.

**Comment by jakub-gonet** [comment]
Hi @dragneel30, can you provide more info?
Namely, React, React Native, Reanimated and Expo SDK (if you're using Expo)
