### ISSUE TITLE
[CXX1429] error when building with cmake using 

### ISSUE THREAD

**Issue by sebasg0** [software-mansion/react-native-reanimated#4971]
### Description

[CXX1429] error when building with cmake using /Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/CMakeLists.txt: -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected unified Clang toolchain
-- The C compiler identification is Clang 12.0.8
-- The CXX compiler identification is Clang 12.0.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - broken
-- Configuring incomplete, errors occurred!
See also "/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/.cxx/Debug/2m5o5448/arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/.cxx/Debug/2m5o5448/arm64-v8a/CMakeFiles/CMakeError.log".

C++ build system [configure] failed while executing:
    /Users/sebastiangarcia/Library/Android/sdk/cmake/3.22.1/bin/cmake \
      -H/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=21 \
      -DANDROID_PLATFORM=android-21 \
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
      -DANDROID_NDK=/Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620 \
      -DCMAKE_ANDROID_NDK=/Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620 \
      -DCMAKE_TOOLCHAIN_FILE=/Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/Users/sebastiangarcia/Library/Android/sdk/cmake/3.22.1/bin/ninja \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/build/intermediates/cxx/Debug/2m5o5448/obj/arm64-v8a \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/build/intermediates/cxx/Debug/2m5o5448/obj/arm64-v8a \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_FIND_ROOT_PATH=/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/.cxx/Debug/2m5o5448/prefab/arm64-v8a/prefab \
      -B/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/.cxx/Debug/2m5o5448/arm64-v8a \
      -GNinja \
      -DANDROID_STL=c++_shared \
      -DREACT_NATIVE_MINOR_VERSION=72 \
      -DANDROID_TOOLCHAIN=clang \
      -DCMAKE_C_FLAGS=-march=armv8-a \
      -DCMAKE_CXX_FLAGS=-march=armv8-a \
      -DCMAKE_EXE_LINKER_FLAGS=-Wl,--no-dead-strip-dylibs \
      -DREACT_NATIVE_DIR=/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native \
      -DJS_RUNTIME=hermes \
      -DJS_RUNTIME_DIR=/Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native/sdks/hermes \
      -DCLIENT_SIDE_BUILD=true \
      -DIS_NEW_ARCHITECTURE_ENABLED=false \
      -DIS_REANIMATED_EXAMPLE_APP=false \
      -DPLAYGROUND_APP_NAME=AwesomeProject \
      -DREANIMATED_PACKAGE_BUILD=null \
      -DREANIMATED_VERSION=3.4.2 \
      -DHERMES_ENABLE_DEBUGGER=1
  from /Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android
CMake Error at /Users/sebastiangarcia/Library/Android/sdk/cmake/3.22.1/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  Change Dir:
  /Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/.cxx/Debug/2m5o5448/arm64-v8a/CMakeFiles/CMakeTmp

    
    Run Build Command(s):/Users/sebastiangarcia/Library/Android/sdk/cmake/3.22.1/bin/ninja cmTC_7cd0f && [1/2] Building C object CMakeFiles/cmTC_7cd0f.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_7cd0f
    FAILED: cmTC_7cd0f 
    : && /Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -march=armv8-a  -O2 -g -DNDEBUG -Wl,--no-dead-strip-dylibs CMakeFiles/cmTC_7cd0f.dir/testCCompiler.c.o -o cmTC_7cd0f  -latomic -lm && :
    ld: error: unknown argument '--no-dead-strip-dylibs'
    clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    
    "/Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/sebastiangarcia/Desktop/work/flm/this/AwesomeProject/node_modules/react-native-reanimated/android/.cxx/Debug/2m5o5448/arm64-v8a/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/Users/sebastiangarcia/Library/Android/sdk/cmake/3.22.1/bin/ninja cmTC_7cd0f && [1/2] Building C object CMakeFiles/cmTC_7cd0f.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_7cd0f
    FAILED: cmTC_7cd0f 
    : && /Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/Users/sebastiangarcia/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -march=armv8-a  -O2 -g -DNDEBUG -Wl,--no-dead-strip-dylibs CMakeFiles/cmTC_7cd0f.dir/testCCompiler.c.o -o cmTC_7cd0f  -latomic -lm && :
    ld: error: unknown argument '--no-dead-strip-dylibs'
    clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

### Steps to reproduce

1. Create a new project with latest RN version
2. install reanimated
3. run build in android
4. observe compilation issue

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/

### Reanimated version

3.4.2

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by sebasg0** [comment]
I'm on an m1 chip with macos Ventura 13.5.1 (22G90)

**Comment by nth-zik** [comment]
THe same on me, only work when use sudo

**Comment by piaskowyk** [comment]
Hey 👋 
First thing: Could you provide a reproduction of your issue?
Second thing: Do you have installed Rosetta on your computer?

**Comment by nth-zik** [comment]
First thing: Fail when I init new project too, just use react native init with template typescript
Second thing: yes.
The library will work fine if I run 
```
sudo yarn android
```
Work well for iOS

**Comment by a-tokyo** [comment]
I'm still facing the same issue with rn 0.72.4

**Comment by anopaishemeki** [comment]
I'm am also facing the same issue with rn 0.72.4

On windows 11 core i7 8th gen

**Comment by a-tokyo** [comment]
I solved this issue by installing ninja-build using `sudo apt-get ninja-build`

We use CircleCI and RN 0.72.4

I am not sure if this solution will work for everyone, but it's worth a try.
It will solve the issue if: ninja is missing or outdadted

**Comment by nth-zik** [comment]
`ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /Users/hung/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -C \
        /Users/hung/Code/pm-apartment/pma/node_modules/react-native-reanimated/android/.cxx/Debug/5y2j84a3/arm64-v8a \
        reanimated
    from /Users/hung/Code/pm-apartment/pma/node_modules/react-native-reanimated/android`
  
This is my stack trace.

Note: run success when use sudo

**Comment by Andres0101** [comment]
I'm having the same [CXX1429] issue in windows. And I notice that it happends due to the Android Gradle plugin version in my project.
**Reanimated version**
3.4.2

**React Native version**
0.68.2

**android/build.gradle**
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = '23.1.7779620'
        kotlinVersion = '1.6.21'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.0'
        classpath 'com.google.gms:google-services:4.3.14'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

If I change to `com.android.tools.build:gradle:7.0.4` it works fine but I need the update to `7.4.0` so that my application targets Android 13, requirement by google play store.
Any solution ?

**PS:** I even try with the lastest version, at the moment, of `react-native-reanimated` **3.5.4** and it does not build, get the same `[CXX1429]` error

**Comment by dilawer-dev** [comment]
I am facing the same issue any help will be appreciated

**Comment by buuhvprojects** [comment]
On android studio you need to install CMake

**Comment by Sergiohcp** [comment]
> On android studio you need to install CMake

So, currently I am using bitrise with fastlane to deploy .aab direct to google play console.

The problem occurs in build phase (gradle) of fastlane.

**Comment by sidm033** [comment]
fix this problem you have to set a Kotlin version on your project-level build grade android/build.gradle
for example:

buildscript {
    ext {
        // ...
        kotlin_version = '1.6.10' // <- add this line
    }

    dependencies {
        // ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version" // <- add this line
        // ...
    }
}

**Comment by nth-zik** [comment]
I solve this issue by add SUDO to command
`sudo yarn run android`
 On MacOS 14

**Comment by syedmohsin7975** [comment]
Task :react-native-reanimated:configureCMakeDebug[armeabi-v7a]
C/C++: CMake Warning at G:/SDK/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   G:/SDK/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
C/C++:   G:/SDK/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++:   CMakeLists.txt:1 (project)
C/C++: CMake Warning at G:/SDK/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   G:/SDK/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
C/C++:   G:/New/Laundrizy/laundrizyapp/node_modules/react-native-reanimated/android/.cxx/Debug/454223d6/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   G:/New/Laundrizy/laundrizyapp/node_modules/react-native-reanimated/android/.cxx/Debug/454223d6/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
C/C++: CMake Warning at G:/SDK/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   G:/SDK/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
C/C++:   G:/New/Laundrizy/laundrizyapp/node_modules/react-native-reanimated/android/.cxx/Debug/454223d6/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   G:/New/Laundrizy/laundrizyapp/node_modules/react-native-reanimated/android/.cxx/Debug/454223d6/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

> Task :react-native-reanimated:buildCMakeDebug[armeabi-v7a]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: EPERM: operation not permitted, lstat 'G:\New\Laundrizy\laundrizyapp\node_modules\react-native-reanimated\android\build\intermediates\cxx\Debug\454223d6\obj\armeabi-v7a\libreanimated.so.tmpb5c42ed'
Emitted 'error' event on NodeWatcher instance at:
    at G:\New\Laundrizy\laundrizyapp\node_modules\metro-file-map\src\watchers\NodeWatcher.js:231:14 {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'G:\\New\\Laundrizy\\laundrizyapp\\node_modules\\react-native-reanimated\\android\\build\\intermediates\\cxx\\Debug\\454223d6\\obj\\armeabi-v7a\\libreanimated.so.tmpb5c42ed'
}

Node.js v20.8.0


I got this error, when checked the react-native-reanimated library files in node modules found CMake version is 3.18.1 where build recommended is Update to CMake 3.19 or newer to use.

I have directly downloaded the CMake Zip, copy and pasting the CMakeFiles will fix the issue? 

![image](https://github.com/software-mansion/react-native-reanimated/assets/46786289/6f8adb4d-0ec7-4090-a251-e4cab9e3798e)

**Comment by syedmohsin7975** [comment]
> On android studio you need to install CMake

Well, I did install but stil getting the version error as  An old version of CMake is being used that cannot automatically detect compiler attributes. Compiler identification is being bypassed. Some values may be wrong or missing. Update to CMake 3.19 or newer to use CMake's built-in compiler identification.

**Comment by usmanabid94** [comment]
I ama facing the same issue on 0.72.6 with react native reanimated version 3.5.4? 
This is the error message from android studio:
from /Users/apple/Desktop/UsmanData/PetroRigs/node_modules/react-native-reanimated/android
CMake Error at CMakeLists.txt:48 (find_package):
  Could not find a package configuration file provided by "fbjni" with any of
  the following names:

    fbjniConfig.cmake
    fbjni-config.cmake

  Add the installation prefix of "fbjni" to CMAKE_PREFIX_PATH or set
  "fbjni_DIR" to a directory containing one of the above files.  If "fbjni"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by BichThien** [comment]
i fixed it by follow this guide but after a while, when i opened the project and build again, i faced it again and now have no clue to fix it.
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/main/BUILDING.md

**Comment by usmanabid94** [comment]
@BichThien i am facing this issue as i have updated my react native project form 0.66 to 0.72.6 version the issue mentioned appears on the react native version when buidling the app for android app only the IOS app compiles fine this issue only appears in android studio when the project is being synced or being build.
node_modules/react-native-reanimated/android
CMake Error at CMakeLists.txt:48 (find_package):
Could not find a package configuration file provided by "fbjni" with any of
the following names:

fbjniConfig.cmake
fbjni-config.cmake
Add the installation prefix of "fbjni" to CMAKE_PREFIX_PATH or set
"fbjni_DIR" to a directory containing one of the above files. If "fbjni"
provides a separate development package or SDK, be sure it has been
installed.

**Comment by Digital-Human-BK** [comment]
Any update I've been trying to solve the issue for the last 2 days but no luck so far...
`React-native v0.72.6` with `react-native-reanimated v3.5.4`

This is the actual error message: 
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using D:\Coding\React-Native-Projects\MyProject\node_modules\react-native-reanimated\android\CMakeLists.txt: C++ build system [configure] failed while executing:      @echo off
      "C:\\Users\\user\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
        "-HD:\\Coding\\React-Native-Projects\\MyProject\\node_modules\\react-native-reanimated\\android" ^
        "-DCMAKE_SYSTEM_NAME=Android" ^
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
        "-DCMAKE_SYSTEM_VERSION=21" ^
        "-DANDROID_PLATFORM=android-21" ^
        "-DANDROID_ABI=arm64-v8a" ^
        "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^`

**Comment by BichThien** [comment]
@Digital-Human-BK, I figure out that Cmake ver 3.22.1 is error, the simple solution to fix it is make the version down, 3.10.3 fine to work.

**Comment by Digital-Human-BK** [comment]
The problem is, that I delete the Cmake v3.22.1, then install the 3.10.3 from Android studio, and when run the `yarn android` command, it automatically installs 3.22 back and doesn't pick up the oldest version of the Cmake I have installed (3.10.3 for example).

**Comment by Digital-Human-BK** [comment]
I finally managed to get it working. It turned out to be the JDK version in my case. I was with version 11.0.18 (RN Docs recommend JDK11 for development). 

`A simple update to version 11.0.20 solved all the problems.`

**Comment by usmanabid94** [comment]
> @BichThien i am facing this issue as i have updated my react native project form 0.66 to 0.72.6 version the issue mentioned appears on the react native version when buidling the app for android app only the IOS app compiles fine this issue only appears in android studio when the project is being synced or being build. node_modules/react-native-reanimated/android CMake Error at CMakeLists.txt:48 (find_package): Could not find a package configuration file provided by "fbjni" with any of the following names:
> 
> fbjniConfig.cmake fbjni-config.cmake Add the installation prefix of "fbjni" to CMAKE_PREFIX_PATH or set "fbjni_DIR" to a directory containing one of the above files. If "fbjni" provides a separate development package or SDK, be sure it has been installed.

I was facing this isssue but i have deleted the android folder and created it again and then the dependencies were installed correctly i guess it has something to do wiht the latest version of react native with the android project of react native by using the command mentioned and turns out that the things are working fine till now:
npx react-native eject

**Comment by Shahzaib114** [comment]
if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake

Make Sure to following C++ extensions in visual studio code
C/C++
C/C++ Theme 
C/C++ Extensions Pack
CMake
CMake Tools
Gradle for Java

Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1


Restart your vs code or your System

**Comment by Shahzaib114** [comment]
if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake, it's because you do not have C++ configurations in project. For that follow below instructions

Make Sure to following C++ extensions in visual studio code
C/C++
C/C++ Theme 
C/C++ Extensions Pack
CMake
CMake Tools
Gradle for Java

Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1


Restart your vs code or your System

**Comment by GaboRocker1992** [comment]
It's funny and absurd, but the issue is due to the project path being too long. I recommend copying or moving your project to c:\ or desktop. Delete the node_modules folder, run npm i, cd android & ./gradlew clean, and then build.

**Comment by RONAKDHOLARIYA** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake, it's because you do not have C++ configurations in project. For that follow below instructions
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System

This thing resolve my issue in windows pc 

Thanks @Shahzaib114

**Comment by david10191** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System

Just downloaded this, and it worked like magic. Thanks

**Comment by MasterAlex233** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System

Thank you for being my savior

**Comment by Thomas-Vargas** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System

This solved my issues on windows 11 machine as well, Thank you!

**Comment by neilanthonyte** [comment]
> I solve this issue by add SUDO to command `sudo yarn run android` On MacOS 14

for some weird reason the error was gone after running react native with sudo

**Comment by lavisar** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System

Thank you so much, I've dowloaded it and it work!!!!

**Comment by Ritikkk-09** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System


Thanks a lot,  it work for react-native-reanimated and react-native-screens  both library problem

**Comment by itmsroohim** [comment]
Whats the solution for Mac OS ?

**Comment by ErAz7** [comment]
installing `Visual C++ Redistributable for Visual Studio 2015` as suggested by @Shahzaib114 fixed the error
Cheers @Shahzaib114 🥂 , saved my day

**Comment by szydlovsky** [comment]
Feels like most of you found your answers 😄 I'll close it now. If anyone still faces some issues (after trying aforementioned fixes) - make sure to open new issue cause this one is already really crowded

**Comment by Master-gg-02** [comment]
I remove project, this folder then  it is work
D:\xxxProjectRoot\node_modules\react-native-reanimated\android\.cxx

![image](https://github.com/user-attachments/assets/e8f37282-a20d-4c72-b7eb-31a10baadc7b)

**Comment by felipezucco** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System

I faced with this same problem: Error CXX1429 at cmake and this comment from @Shahzaib114 worked for me. 
I did some of this steps, but I think install Visual C++ Redistributable for Visual Studio 2015 was the solution.

**Comment by afiq234** [comment]
still facing the problem although download this

> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System


still facing the same problem although follow the steps

**Comment by afiq234** [comment]
{
  "name": "TestDetection",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-reanimated": "^3.15.4",
    "react-native-vision-camera": "^4.5.2",
    "react-native-worklets-core": "^1.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.87",
    "@react-native/eslint-config": "0.74.87",
    "@react-native/metro-config": "0.74.87",
    "@react-native/typescript-config": "0.74.87",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

this one solved my issues

**Comment by gd-salle** [comment]
I tried every solution found here but nothing worked. Running it with npx expo start works, but when I do ./gradlew assembleDebug this issue arises. Ive been looking for solution for 2 days already and nothing works.

`* What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeDebug[arm64-v8a]'.
> [CXX1210] C:\Users\GDS\Desktop\Project\React_Native\GSPOS\node_modules\expo-modules-core\android\CMakeLists.txt debug|arm64-v8a : No compatible library found`

**Comment by AleeFarook** [comment]
> if you have tried all the possible solutions ad still facing CXX[1429] or CXX[1405] for cMake
> 
> Make Sure to following C++ extensions in visual studio code C/C++ C/C++ Theme C/C++ Extensions Pack CMake CMake Tools Gradle for Java
> 
> Main Thing, install "Visual C++ Redistributable for Visual Studio 2015" from the following link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
> 
> Restart your vs code or your System


I have done all these steps and still seeing this error 
[CXX1429] error when building with cmake using C:\Users\Ali Farooq\Documents\GitHub\builddeiveryapp-New\node_modules\react-native-screens\android\CMakeLists.txt: -- Detecting C compiler ABI info

Please help

**Comment by tomekzaw** [comment]
Hi all, we added **"Building for Android on Windows"** troubleshooting guide to Reanimated docs. Please consult this page if you face any build errors for Android devices when building your app on Windows.

➡️ **https://docs.swmansion.com/react-native-reanimated/docs/guides/building-on-windows**

If the problem still persists, feel free to re-open the issue or submit a new one.

**Comment by Rahul0001k** [comment]
solved after changing jdk21 to jdk 17

**Comment by VEmpink** [comment]
> solved after changing jdk21 to jdk 17

For me switching between JDK 17 to JDK 21 is solved. But switching again back to JDK 17 from JDK 21 is also work, weird.
