### ISSUE TITLE
[iOS building] [React native 0.72.4] No visible @interface for 'RNSScreenView' declares the selector 'isModal'

### ISSUE THREAD

**Issue by konri** [software-mansion/react-native-reanimated#4992]
### Description

Hi guys, 
I have a problem after updating react native to the latest version. When I want to build my application via xcode I got the information: 
/my_path/node_modules/react-native-reanimated/ios/LayoutReanimation/REAScreensHelper.m:41:28 No visible @interface for 'RNSScreenView' declares the selector 'isModal'

![Screenshot 2023-08-27 at 23 35 41](https://github.com/software-mansion/react-native-reanimated/assets/3826473/694016ee-fcbf-4432-a6c2-0a59ca5b2ae2)

I need to remove this piece of code to run my application. 
```
bool isModal = [screen isModal];
    if (!isModal) {
      // case for modal with header
      RNSScreenView *parentScreen = (RNSScreenView *)[REAScreensHelper getScreenForView:screen.reactSuperview];
      if (parentScreen != nil) {
        isModal = [parentScreen isModal];
      }
    }
```

### Steps to reproduce

1. Update with https://react-native-community.github.io/upgrade-helper/?from=0.70.3&to=0.72.4 to latest react native version 
2. build application for ios with xcode 
3. problem occured at the end of building. 

### Snack or a link to a repository

https://react-native-community.github.io/upgrade-helper/?from=0.70.3&to=0.72.4

### Reanimated version

3.4.0

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Ok, I know how to fix it. But overall you just need to upgrade you screens version to solve this issue

**Comment by manurodriguezDL** [comment]
@piaskowyk Could you give any more information on how to fix it? I'm facing the same issue.

**Comment by Korin92** [comment]
I have same problema, someone know how to fix this?

**Comment by Korin92** [comment]
I fix this, I had to update react-native-screens to the last version

**Comment by noviogroup** [comment]
@Korin92  I fix this, I had to update react-native-reanimated, react-native-screens and react-native-safe-area-context to the last version

Yes this worked, some reason i had to use yarn add because npm gave errors.

**Comment by eisodev** [comment]
Think it is react-native-screens that caused this issue (not safe-area-context), see 3.25.0 bugfixes for RNSScreenView#finalizeUpdates:
https://github.com/software-mansion/react-native-screens/releases/tag/3.25.0

**Comment by farhanbudye** [comment]
Upgrading **react-native-screens** worked for me Thanks @eisodev !

**Comment by choijiho0021** [comment]
> I fix this, I had to update react-native-reanimated, react-native-screens and react-native-safe-area-context to the last version

Thank you for save my time.

**Comment by 2maleek** [comment]
> @Korin92 I fix this, I had to update react-native-reanimated, react-native-screens and react-native-safe-area-context to the last version
> 
> Yes this worked, some reason i had to use yarn add because npm gave errors.


Thanks a lot bro, it works.
you save my day.

**Comment by wj0990** [comment]
> 认为是 react-native-screens 导致了此问题（而不是 safe-area-context），请参阅 RNSScreenView#finalizeUpdates 的 3.25.0 错误修复：https: [//github.com/software-mansion/react-native-screens/releases/tag/3.25.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.25.0)

@eisodev  Thanks a lot bro, it works.
