### ISSUE TITLE
Issue on Android, very hard to reproduce but freeze completely the reanimated thread

### ISSUE THREAD

**Issue by ScreamZ** [software-mansion/react-native-reanimated#5001]
### Description

Hi,

Sorry if I killed the english language 😅

I'm facing a really strange bug that occurs on Android only. I'm using EXPO 49, which is shipped with Reanimated ~3.3.0.

On iOS everything works well and easy, on Android I'm facing an animation thread freeze that I can't really explain.
It freezes specifically on displaying the Alert modal using this code, no matter if I say YES or NO.

```tsx
import { UNSTABLE_usePreventRemove } from "@react-navigation/native";
import { useNavigation } from "expo-router";
import { Alert } from "react-native";

type Props = {
  title: string;
  message: string;
  cancelText: string;
  confirmText: string;
};
export function usePreventGoBackModal({ title, message, cancelText, confirmText }: Props, isEnabled: boolean) {
  const navigation = useNavigation();

  UNSTABLE_usePreventRemove(isEnabled, (e) => {
    Alert.alert(
      title,
      message,
      [
        { text: cancelText, style: "cancel", onPress: () => {} },
        {
          text: confirmText,
          style: "destructive",
          onPress: () => navigation.dispatch(e.data.action),
        },
      ],
      { cancelable: false },
    );
  });
}
```

I was able to reproduce it randomly without the `UNSTABLE_usePreventRemove` hook which is required for native router.

It seems to work also if i use the following code which is a noop
```ts
export function usePreventGoBackModal({ title, message, cancelText, confirmText }: Props, isEnabled: boolean) {
  const navigation = useNavigation();

  UNSTABLE_usePreventRemove(isEnabled, (e) => {
    navigation.dispatch(e.data.action);
  });
}
```

Also tried a plain old 

```ts
export function usePreventGoBackModal({ title, message, cancelText, confirmText }: Props, isEnabled: boolean) {
  const navigation = useNavigation();

  Alert.alert(
    title,
    message,
    [
      { text: cancelText, style: "cancel", onPress: () => {} },
      {
        text: confirmText,
        style: "destructive",
        onPress: () => navigation.goBack(),
      },
    ],
    { cancelable: false },
  );
}
```

Sometimes it freezes sometimes not, it looks like `Alert.alert` is an issue.

I'm not sure if it is related to expo-router, react-navigation, or reanimated, but the consequences are clearly related to reanimated which becomes completely frozen

Here are some footage.

**Without the usePreventGoBackModal hook**

https://github.com/software-mansion/react-native-reanimated/assets/6640835/5d57c481-8830-4e66-9536-e2776eaa715a

**On Android With hooks that display the modal**

https://github.com/software-mansion/react-native-reanimated/assets/6640835/fde49445-a4db-47a1-b55f-a32a9e4a20c8

**ON iOS (everything is OK)**

https://github.com/software-mansion/react-native-reanimated/assets/6640835/78373006-ee26-42e4-9325-4135737f926f

### Steps to reproduce

Please refer to the above paragraph

### Snack or a link to a repository

I'm unable to generate a expo-router snack ? Can you share me a link with a base ?

### Reanimated version

~3.3.3

### React Native version

expo 49

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Bonjour @ScreamZ
I am afraid we can't help you. Please notice that in provided blocks of code there is no use of reanimated. You said
>It freezes specifically on displaying the Alert modal using this code, no matter if I say YES or NO.
And see
```javascript
import { Alert } from "react-native";
...

  UNSTABLE_usePreventRemove(isEnabled, (e) => {
    Alert.alert(     
      ....    
    );
  });
}
```
you are using default react-native animations, not ours. Therefore you may want to address your issue to react-navigation team
