### ISSUE TITLE
[nightly-20230828] 'JsiUtils.h' file not found

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#5002]
### Description

After installing `3.5.0-nightly-20230828-e860ae5c4` iOS cannot compile, it throws `'JsiUtils.h' file not found` on `WorkletRuntimeDecorator`. This started on `20230826` build. 

Android builds fine. Please note that I use `expo-modules` in a bare react-native project.

I've uninstalled and reinstalled node_modules, cleared derived data, deleted pods folder and podfile.lock.

![Screenshot 2023-08-29 at 09 09 58](https://github.com/software-mansion/react-native-reanimated/assets/717975/071e8cf9-cf7f-4442-b474-93517fb51ee2)

### Steps to reproduce

1. Update to `3.5.0-nightly-20230828-e860ae5c4`
2. Run app with Xcode

### Snack or a link to a repository

/

### Reanimated version

3.5.0-nightly-20230828-e860ae5c4

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
probably offending [PR](https://github.com/software-mansion/react-native-reanimated/commit/cb04295c9b574342bcc3e68db42a83742acbdadd#diff-02b248e4321a5e3cf1a4866f35dc89a7c8e310c3eeaf3a4f15d1dc3e3f690a9b)

**Comment by piaskowyk** [comment]
Hey there! 👋 Thanks for your report! We really appreciate having such active and committed people like you in our community 😍 We've also noticed an issue with expo-dev-client on our CI. You can find more information about it here: [CI Issue](https://github.com/software-mansion/react-native-reanimated/actions/runs/6004184473). I'll try to fix it.

**Comment by efstathiosntonas** [comment]
Thanks @piaskowyk, let me know if you want me to test any fixes!

**Comment by efstathiosntonas** [comment]
Thanks @piaskowyk! Keep it up!
