### ISSUE TITLE
 Uncaught Error Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by philipheinser** [software-mansion/react-native-reanimated#5012]
### Description

Uncaught Error
Attempted to assign to readonly property.

### Steps to reproduce

1. put sharedTransitionTag on 2 views
2. navigate  

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.4.2

### React Native version

0.71.7

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by philipheinser** [comment]
![Screenshot 2023-08-30 at 18 43 57](https://github.com/software-mansion/react-native-reanimated/assets/3705499/f7dda088-c0b8-4ddb-8418-8b2580b8215e)

**Comment by Latropos** [comment]
Hi! In the snack you've provided I don't see any import of reanimated. Also in your log there is nothing about reanimated. If your problem is indeed related to our library but you've accidentally linked wrong code feel free to link the good one and reopen this issue.

**Comment by TuanTran-Tsk** [comment]
i got same issue
