### ISSUE TITLE
Second shared transition after go back

### ISSUE THREAD

**Issue by hamdij0maa** [software-mansion/react-native-reanimated#5026]
### Description

<img width="529" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/20734472/7a676a35-60f6-48f5-b9ac-48fe2391f634">

### Steps to reproduce

import Image from "expo-image"
const AnimatedImage = Animated.createAnimatedComponent(Image)
 <AnimatedImage
          sharedTransitionTag={sharedTransitionTag}
          placeholderContentFit="cover"
          pointerEvents="none"
          position="absolute"
          top={0}
          left={0}
          right={0}
          bottom={0}
          overflow="hidden"
          width={SQUARE_POST_WIDTH}
          height={SQUARE_POST_HEIGHT}
          priority="low"
          transition={150}
          backgroundColor="postImageBackground"
          cachePolicy="memory-disk"
          recyclingKey={thumbnail_url}
          contentFit="cover"
          contentPosition="center"
          source={{
            uri: thumbnail_url,
            width: thumbnailServerSize.width,
            height: thumbnailServerSize.height,
          }}
        />

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/issues/new?assignees=&labels=Needs+review&projects=&template=bug-report.yml

### Reanimated version

3.4.2

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 5

### Acknowledgements

Yes

**Comment by Latropos** [comment]
I have no idea what and why happens, since no repro was provided, but please use `react-native` Image instead of Expo one.
``` diff
- import Image from "expo-image"
+ import { Image } from 'react-native';
```

**Comment by hamdij0maa** [comment]
to reproduce it you need a tabs and over it a stack navigation, 
2 or more go in and back and the error shows up, 
sorry I can not share the code right now, 
i'll debug it more and came back with a clear issue

**Comment by kmagiera** [comment]
@hamdij0maa Do you have any updates here? We'd like to look into this issue but the description miss not only a reproducable demo but even some basic description. I understand you're getting the error but the description doesn't even mention what you attempted to do. 

Despite all that I put my best effort to try and reproduce this. Here is the App.tsx that I build trying to use expo image and the parameters you put in the description. Apparently, this seem to run w/o any errors on the most recent react native and reanimated versions. https://gist.github.com/kmagiera/dd8a718c5451c9c178afe5fa5673569c

If you'd like us to look into the issue we'd ask hat you provide a bit more details about the problem and a reproducible demo.

**Comment by hamdij0maa** [comment]
@kmagiera I missed closing the issue, thank you.
