### ISSUE TITLE
[android only] withSpring returns Nan value most of the time in android 

### ISSUE THREAD

**Issue by Hassaan68** [software-mansion/react-native-reanimated#5047]
### Description

[android only] withSpring returns Nan value most of the time in android. Just run the app and sometime withSpring works correctly but most of the time returns Nan value. Just run the animation and refresh the screen or reload the app.

### Steps to reproduce

1. use withSpring animation inside useAnimatedStyle or useDerivedValue hook.
2. The code was working fine before in reanimated v2.12.0

```
const springOptions = {
  damping: 15,
  mass: 1,
  stiffness: 100,
};
function Section({children, title}: SectionProps): JSX.Element {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);
  const progress = useDerivedValue(() => {
    return withRepeat(
      withSequence(
        withTiming(400, {
          easing: Easing.cubic,
          duration: 0,
        }),
        withTiming(400, {
          easing: Easing.cubic,
          duration: 0,
        }),
        withTiming(180, {
          easing: Easing.cubic,
          duration: 1400,
        }),
        withTiming(180, {
          easing: Easing.cubic,
          duration: 1400,
        }),
        withTiming(180, {
          easing: Easing.cubic,
          duration: 0,
        }),
      ),
      -1,
      false,
    );
  });

  const viewWidth = useDerivedValue(() => {
    return withSpring(progress.value, springOptions);
  }, [progress]);

  const animatedStyle = useAnimatedStyle(() => {
    if (isNaN(viewWidth.value)) {
      console.log('WidthValue ', viewWidth.value);
    }
    return {
      width: withSpring(progress.value, springOptions),
      height: withSpring(progress.value / 1.5),
      opacity: progress.value,
    };
  }, [mounted, viewWidth.value, progress.value]);
  return (
    <View style={styles.sectionContainer}>
      <Animated.View style={[animatedStyle]}>
        <View
          width={'100%'}
          height={'100%'}
          style={{backgroundColor: 'yellow'}}></View>
      </Animated.View>
    </View>
  );
}
```

### Snack or a link to a repository

https://github.com/Hassaan68/ReanimatedWIthSpringIssue

### Reanimated version

3.4.2

### React Native version

0.72.4

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Android 13

### Acknowledgements

Yes

**Comment by kaioduarte** [comment]
This issue is not happening with the main code, I tested it with today's nightly version, not sure which PR fixed it though.

**Comment by Hassaan68** [comment]
> This issue is not happening with the main code, I tested it with today's nightly version, not sure which PR fixed it though.

is main code is of different version than 3.4.2? you can reproduce the issue in provided repo.

**Comment by kaioduarte** [comment]
Yes, there were a bunch of changes since the last release, it seems the next version will be released soon, see #5040.

**Comment by Hassaan68** [comment]
> Yes, there were a bunch of changes since the last release, it seems the next version will be released soon, see #5040.

Thanks. is there a way to update the reanimated package to use latest main code before release of 3.5.0?

**Comment by kaioduarte** [comment]
just use the nightly tag when installing REA: `npm i react-native-reanimated@nightly`

**Comment by Hassaan68** [comment]
> just use the nightly tag when installing REA: `npm i react-native-reanimated@nightly`

Thank you @kaioduarte , I will try and give you feedback

**Comment by Hassaan68** [comment]
@kaioduarte , the issue seems fixed react-native-reanimated@nightly version. waiting for 3.5.0 version released to be soon.

**Comment by kacperkapusciak** [comment]
@Hassaan68 Reanimated 3.5 is live. Can we close this issue?
