### ISSUE TITLE
useAnimatedScrollHandler's `onMomentumBegin` & `onMomentumEnd` is not firing

### ISSUE THREAD

**Issue by arasrezaei** [software-mansion/react-native-reanimated#5058]
### Description

Hi there,
useAnimatedScrollHandler not firing `momentum events` on Animated.ScrollView.
it's working when you call event direcrly as a prop: (<Animated. ScrollView onMomentums={} />)
unfortunately on `web` non of them working.
i tested it on actual phone.

### Steps to reproduce

1.open snack
2. try to scroll on device
3. useAnimatedScrollHandler hook not firing momentum events

### Snack or a link to a repository

https://snack.expo.dev/@arasrezaie/onmomentum-useanimatedscrollhandler

### Reanimated version

3.4.2

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy note 4

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @arasrezaei. I tried to reproduce your issue but both on Android simulator and real device the momentum events are fired. Maybe the reason for you not receiving them is the typo you have in `runOnJS` in your snack? (you have `runOnJs` instead)

**Comment by arasrezaei** [comment]
> Hi @arasrezaei. I tried to reproduce your issue but both on Android simulator and real device the momentum events are fired. Maybe the reason for you not receiving them is the typo you have in `runOnJS` in your snack? (you have `runOnJs` instead)

Oh my bad, it's working now!!

**Comment by matinzd** [comment]
No it's still not working ...

**Comment by WayneKim92** [comment]
No it's still not working ...
