### ISSUE TITLE
[nightly/3.5.0] ReferenceError: Property '_IS_FABRIC' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#5061]
### Description

Hey folks, I know you're fine tuning Fabric just before releasing `3.5.0`, just wanted to bring this to your attention.

I've deleted node_modules, cleared derived data, deintegrated pods, --reset-cache on metro but the issue persists. 

Please note that I use `"expo-modules-core": "1.7.0"` and `"expo": "^49.0.10"` on a bare Paper react-native project.

Let me know if you need me to test anything. 

### Steps to reproduce

1. Update to 3.5.0-nightly-20230910-073b64568
2. This was happening on previous nightly versions too. 

See attached screenshot: 
![simulator_screenshot_EA9424C7-ED53-4238-A1E9-79FA31DC0A93](https://github.com/software-mansion/react-native-reanimated/assets/717975/f5165e7c-29a0-40ef-b890-f2d5cc733e7e)

### Snack or a link to a repository

none

### Reanimated version

3.5.0-nightly-20230910-073b64568

### React Native version

0.72.4

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by thefranfran** [comment]
Same here

**Comment by radko93** [comment]
Facing the same issue. Not an expo app but using Expo.

**Comment by piaskowyk** [comment]
Ok, I need to check it 🫡

**Comment by efstathiosntonas** [comment]
@piaskowyk thanks, iirc this goes back 4-5 days so probably around 200230905 the change took place.

**Comment by efstathiosntonas** [comment]
@piaskowyk I've just installed `3.5.0` and I get this errror

**Comment by kartikk221** [comment]
@efstathiosntonas Is right. Just installed 3.5.0 and am receiving this error. Full set of package.json dependencies if needed:
```json
{
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@gorhom/bottom-sheet": "git@github.com:kartikk221/react-native-bottom-sheet.git",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-masked-view/masked-view": "0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@shopify/flash-list": "^1.5.0",
    "burnt": "^0.11.7",
    "cached-lookup": "^5.3.3",
    "events": "^3.3.0",
    "expo": "^49.0.10",
    "expo-apple-authentication": "~6.1.0",
    "expo-build-properties": "~0.8.3",
    "expo-clipboard": "^4.3.1",
    "expo-crypto": "~12.4.1",
    "expo-dev-client": "^2.4.8",
    "expo-font": "~11.4.0",
    "expo-haptics": "~12.4.0",
    "expo-image": "~1.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-notifications": "~0.20.1",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "^0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-store-review": "~6.4.0",
    "expo-system-ui": "~2.4.0",
    "expo-updates": "^0.18.12",
    "expo-web-browser": "~12.3.2",
    "p-queue": "^6.6.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-animateable-text": "^0.11.0",
    "react-native-collapsible-tab-view": "git@github.com:kartikk221/react-native-collapsible-tab-view.git",
    "react-native-fast-shadow": "^0.1.0",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-hyperlink": "^0.0.22",
    "react-native-image-viewing": "^0.2.2",
    "react-native-mmkv": "^2.10.2",
    "react-native-pager-view": "6.2.0",
    "react-native-reanimated": "^3.5.0",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-share": "^9.4.1",
    "react-native-svg": "^13.10.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "^13.2.3",
    "react-native-zoom-reanimated": "git@github.com:kartikk221/react-native-zoom-reanimated.git",
    "recyclerlistview": "^4.2.0"
  }
  ```

**Comment by efstathiosntonas** [comment]
fixed: 

`react-native-reanimated+3.5.0.patch`

```patch
diff --git a/node_modules/react-native-reanimated/src/reanimated2/NativeMethods.ts b/node_modules/react-native-reanimated/src/reanimated2/NativeMethods.ts
index b29ac0f..9eb2ad4 100644
--- a/node_modules/react-native-reanimated/src/reanimated2/NativeMethods.ts
+++ b/node_modules/react-native-reanimated/src/reanimated2/NativeMethods.ts
@@ -62,7 +62,7 @@ if (isWeb()) {
       return null;
     }
 
-    const measured = _IS_FABRIC
+    const measured = global._IS_FABRIC
       ? // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
         _measureFabric!(viewTag as ShadowNodeWrapper)
       : // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
```

**Comment by taylor-ortiz** [comment]
@efstathiosntonas  has this been resolved yet? I am also facing the same issue

**Comment by efstathiosntonas** [comment]
@taylor-ortiz I've just opened a PR about it, you can use `patch-package` to patch it with [this](https://github.com/software-mansion/react-native-reanimated/issues/5061#issuecomment-1714548068) until it's merged and released

**Comment by taylor-ortiz** [comment]
@efstathiosntonas appreciate it man. thank you.
