### ISSUE TITLE
[3.5.1] Babel incompatible issue

### ISSUE THREAD

**Issue by jp928** [software-mansion/react-native-reanimated#5072]
### Description

After upgrade to 3.5.1 from 3.4.2, encountering the problem `mismatch between javascript code version and reanimated babel plugin version`.
![Simulator Screenshot - iPhone 14 - 2023-09-13 at 09 14 09](https://github.com/software-mansion/react-native-reanimated/assets/659612/b3044adb-b68c-47c2-be86-8680b5a97d72)

I had tried delete the entire node_modules folder and yarn cache clean. No luck.

### Steps to reproduce

1. yarn install
2. expo run:ios

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.5.1

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @jp928. Make sure to reset your bundler's cache (`yarn start --reset-cache` or `npm start -- --reset-cache`).

**Comment by ppritesh** [comment]
Same issue. what should be quick fix ?

**Comment by idrissakhi** [comment]
yarn start --reset-cache should resolve your issues. and this issue can be closed

**Comment by vinamrahalgar** [comment]
Mismatch between JavaScript code version and Reanimated Babel plugin version - getting this issue, 
[Reanimated] Mismatch between JavaScript code version and Reanimated Babel plugin version (3.11.0 vs.3.8.0)
(yarn start --reset-cache or npm start -- --reset-cache) -> This doesn't seem to work in my system. Any other solution?
