### ISSUE TITLE
processInlineStylesWarning function should be called only on files that has reanimated import

### ISSUE THREAD

**Issue by anta-semenov** [software-mansion/react-native-reanimated#5094]
### Description

I started to integrate Reanimated into the project that already uses default react-native animations.

So in a lot of components I use styles liek `{ translateY: showStatusBarAnimaton.value }`.

I started to use reanimated in couple of components and it works fine.

But now I see a lot of warnings in console
```
It looks like you might be using shared value's .value inside reanimated inline style. If you want a component to update when shared value changes you should use the shared value directly instead of its current state represented by `.value`.
```

for components that use react-native Animated and not Reaninimated.

### Steps to reproduce

1. Open project that use reanimated library
2. Create new component file
3. Add any react-native default animation (for instance opacity) and use it in inline style like `style={ { opacity: animation.value } }
4. See warning in console

### Snack or a link to a repository

nda

### Reanimated version

3.4.2

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
You're right, indeed processInlineStylesWarning function should be called only on files with reanimated import.
Is this bug still burdensome when you just disable these logs? (They won't disappear from the console though).
```
LogBox.ignoreLogs([
  "It looks like you might be using shared value's .value inside reanimated inline style. " +
    'If you want a component to update when shared value changes you should use the shared value' +
    ' directly instead of its current state represented by `.value`. See documentation here: ' +
    'https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/glossary/#animations-in-inline-styling',
]);
```

**Comment by tjzel** [comment]
Hi @anta-semenov. Reanimated was made to replace Animated instead of working alongside it, therefore we don't really have settings that would allow to trigger it only on Reanimated Animated components. However, you can suppress these warnings with an option to our Reanimated Babel plugin:

```diff
// babel.config.js
plugins: [
-  'react-native-reanimated/plugin',
+  ['react-native-reanimated/plugin', { disableInlineStylesWarning: true }],
]
```

**Comment by anta-semenov** [comment]
@tjzel @Latropos thank, will disable warnings.

I understand that reanimated is aimed to replace the default animations, but it's hard to do in one go on existing project

**Comment by MuhammadMuzammilQadri** [comment]
> Hi @anta-semenov. Reanimated was made to replace Animated instead of working alongside it, therefore we don't really have settings that would allow to trigger it only on Reanimated Animated components. However, you can suppress these warnings with an option to our Reanimated Babel plugin:
> 
> ```diff
> // babel.config.js
> plugins: [
> -  'react-native-reanimated/plugin',
> +  ['react-native-reanimated/plugin', { disableInlineStylesWarning: true }],
> ]
> ```


After couple of hours of research I found that this also fixes those failing jest tests that fail with the below error:
`TypeError: require(...).getUseOfValueInStyleWarning is not a function`

**Comment by marqroldan** [comment]
Hi, I noticed I'm getting this warning as well whenever I have a style that uses `.value` even though it's not a reanimated-related object

Repro:

```
const colors = [
  '#060001',
  '#1e0008',
  '#2c000f',
  '#3a0017',
  '#48001f',
  '#700035',
  '#950049',
  '#bc005f',
  '#ff008b',
  '#ff7daf',
  '#ffa8c7',
  '#ffc2d8',
  '#ffd3e3',
  '#ffdfec',
  '#ffe6f1',
  '#ffeef6',
  '#fff5fb',
  '#fff8fd',
].reduce((acc, color) => {
  acc.push({
    value: color,
  });
  return acc;
}, []);

  return (
    <View style={{flex: 1}}>
      {colors.map((a) => {
        return (
          <View style={{width: 40, height: 40, backgroundColor: a.value}} />
        );
      })}
    </View>
  );
```

I was wondering if it's really safe to have `{ disableInlineStylesWarning: true }` ?

**Comment by tjzel** [comment]
@marqroldan Yes, it's safe 😃
