### ISSUE TITLE
[Reanimated] `valueUnpacker` is not a worklet

### ISSUE THREAD

**Issue by hoangSuy** [software-mansion/react-native-reanimated#5099]
### Description

 Error: [Reanimated] `valueUnpacker` is not a worklet, js engine: hermes
 LOG  Running "app_name" with {"rootTag":71}
 ERROR  Invariant Violation: "KBuilding_Admin" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### Steps to reproduce

1. yarn android

### Snack or a link to a repository

Not available

### Reanimated version

3.5.2

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by codeion** [comment]
Hi, make sure to add Reanimated's babel [plugin.](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/)

**Comment by hoangSuy** [comment]
oh, thank you!

**Comment by privatepej** [comment]
did you able to fix it?

**Comment by NixFull** [comment]
yes i found the solution. You have make your babel.config.js like this:

const presets = ['module:metro-react-native-babel-preset'];
const plugins = [['react-native-reanimated/plugin']];

plugins.push([
  'module-resolver',
]);

module.exports = {
  presets,
  plugins,
};

**Comment by Iuriy-Budnikov** [comment]
I have the same issue event when I have `'module-resolver'`

**Comment by Iuriy-Budnikov** [comment]
lol `yarn start --reset-cache` it helped
