### ISSUE TITLE
Master branch build fails with a syntax error

### ISSUE THREAD

**Issue by mikedemarais** [software-mansion/react-native-reanimated#510]
🤔️ the reason this is happening is not obvious to me... cc @wcandillon @osdnk 

related to this commit: https://github.com/software-mansion/react-native-reanimated/commit/f8b3047cc27bd686a76bcb7d972a4a68132bcdd8
```
error: bundling failed: SyntaxError: [omitted]/node_modules/react-native-reanimated/src/Animated.js: 
Unexpected token, expected "," (79:7)

  77 |
  78 |   // animations
> 79 |   decay: decayWrapper,
     |        ^
  80 |   timing: timingWrapper,
  81 |   spring: springWrapper,
  82 |   SpringUtils,
```

**Comment by SaeedZhiany** [comment]
So `Fix: CI 💚` pull request causes `Break: CI ❤️`. 😄

**Comment by wcandillon** [comment]
Why these errors are only caught on master? 🤔
