### ISSUE TITLE
App crashes when using a ref inside useAnimatedReaction

### ISSUE THREAD

**Issue by KennyCallegari** [software-mansion/react-native-reanimated#5101]
### Description

When I try to call `scrollTo` method of a `scrollViewRef` inside a `useAnimatedReaction`, the app crashes on ios.
On android I have the error : "Trying to access property of an object which cannot be sent to the UI runtime"

I tried runOnUI and runOnJS without success.
I hope it's only a misunderstanding on my part and not an issue with this beautiful library !

### Steps to reproduce

- set up a SharedValue (`sharedValue`) and a scrollView with a ref (`scrollViewRef`).
- try to use `scrollViewRef.scrollTo` inside a `useAnimatedReaction()` :

```
useAnimatedReaction(
  () => sharedValue.value,
  (currentValue) =>  {
     scrollViewRef.current.scrollTo({ x: 0, y: currentValue, animated: false })
  }
)
```
- it crashes the app

### Snack or a link to a repository

https://snack.expo.dev/@kennyledev/4255b7?platform=ios

### Reanimated version

3.3.0

### React Native version

0.72.4

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

None

### Build type

None

### Device

iOS simulator

### Device model

iPhone 14 Pro Max - iOS 16.4

### Acknowledgements

Yes

**Comment by NikitaDudin** [comment]
Wrap scrollTo with function. You should to use [runOnJS](https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS/).
```JS
  const scrollTo = useCallback((currentValue) =>  {
      if (selectedListRef?.current) selectedListRef.current.scrollTo({ x: 0, y: currentValue, animated: false });
    }, []);
    
    ...
  useAnimatedReaction(
      () => scrollY.value,
      (currentValue) =>  {
        runOnJS(scrollTo)(currentValue);
      },
      [scrollTo],
    );
```

**Comment by Latropos** [comment]
Yes, this is a valid solution. You should get `[Reanimated] Trying to access property 'scrollTo' of an object which cannot be sent to the UI runtime.` error message. Probably we should make this error log more descriptive, maybe we add link to `runOnJS` in docs?

**Comment by tjzel** [comment]
The error is verbose enough, but I think we could add a sentence ("If this was intentional, you should wrap the code that accesses "<name of the property>" in `runOnJS`."

**Comment by KennyCallegari** [comment]
> Wrap scrollTo with function. You should to use [runOnJS](https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS/).
> 
> ```js
>   const selectedListRef = useRef();
>   ...
>   const scrollTo = useCallback((currentValue) =>  {
>       if (selectedListRef?.current) selectedListRef.current.scrollTo({ x: 0, y: currentValue, animated: false });
>     }, []);
>     
>     ...
>   useAnimatedReaction(
>       () => scrollY.value,
>       (currentValue) =>  {
>         runOnJS(scrollTo)(currentValue);
>       },
>       [scrollTo],
>     );
> ```
> 
> Or use scrollTo reanimated helper and animated ref.
> 
> ```js
> const selectedListRef = useAnimatedRef();
> ...
>   useAnimatedReaction(
>     () => scrollY.value,
>     (currentValue) =>  {
>       if (currentValue) scrollTo(selectedListRef, 0, currentValue, false);
>     },
>   );
> ```

Thank you so much, both methods work for me !
