### ISSUE TITLE
[v2] reanimated 2 does not work with expo 49 (react-native 0.72) on android

### ISSUE THREAD

**Issue by PrajTS** [software-mansion/react-native-reanimated#5106]
### Description

I need to use react-native-reanimated v2. During android build, I get this warning

`WARNING reanimated - no version-specific reanimated AAR for react-native version 72 found.
Falling back to AAR for react-native version 71.
The react-native JSI interface is not ABI-safe yet, this may result in crashes.
Please post a pull request to implement support for react-native version 72 to the reanimated repo.
Thanks!`.

<img width="821" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/31252757/3088c2a3-25f7-47fe-add1-570aa3896405">

When I try to run the app, the get the following error

` ERROR  Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8facebook5react19ReadableNativeArrayC1EN5folly7dynamicE" referenced by "/data/app/~~pJKVSOSw9TXUlUfK49FGTA==/com.onecode.gorhomv42-dXfMUFZfXOXDMwjZ0vJo_w==/lib/arm64/libreanimated.so"..., js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes`

<img width="832" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/31252757/f616f0a1-fae4-46a6-b664-f2cbf4bdac1b">

### Steps to reproduce

1. create project with expo
2. yarn add reanimated@2
3. run npx expo run:android

### Snack or a link to a repository

https://github.com/PrajTS/reanimated-2-issue

### Reanimated version

2.17.0

### React Native version

0.72.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

One plus nord CE 2 (Android 13)

### Acknowledgements

Yes

**Comment by PrajTS** [comment]
This seems to be an issue with gorham bottomsheet

**Comment by julianD77** [comment]
I ran into the same `UnsatisfiedLinkError` as above too and then discovered this comment regarding discussion indicating that Reanimated 2 will not be supported on 0.72.x

https://github.com/software-mansion/react-native-reanimated/discussions/4693

> at the moment we don't plan supporting React Native v0.72 in Reanimated2 and we strongly suggest upgrading to Reanimated3 if possible

Updating to Reanimated 3.4.0 solved the issue for us.
