### ISSUE TITLE
How to automatically fill in otp input in react naive?

### ISSUE THREAD

**Issue by hoangSuy** [software-mansion/react-native-reanimated#5107]
### Description

How to autofill otp input in react naive without using library?

### Steps to reproduce

1. yarn android

### Snack or a link to a repository

Not available

### Reanimated version

3.4.2

### React Native version

0.71.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
I'm afraid this is not an issue and I'm not certain if the question you ask is related to Reanimated.
