### ISSUE TITLE
ScrollHandler "breaks" after re-render in v3 (works in v2)

### ISSUE THREAD

**Issue by blumendorf** [software-mansion/react-native-reanimated#5114]
### Description

We attach a single scroll handler to multiple lists nested inside another list (for animation purposes).
In reanimated v2 this worked, even when the top component was re-rendered.

In reanimated v3 re-rendering the top component "detaches" the scrollHandler from _some_ of the nested lists.

Here is a snack to reproduce the issue:
https://snack.expo.dev/@marco.blu/6b7527?platform=ios

The effect in line 86 causes the re-render and afterwards the scrollHandler of the 3rd page of the list is broken.
Removing the effect resolves the issue.
Also changing  to react-native-reanimated ^2 in package.json fixes the issue.

Here is a video showing that the scrollHandler works on NestedFlatList 1 and 2 but not on 3.
https://github.com/software-mansion/react-native-reanimated/assets/2630943/21746b0d-ba90-436b-a466-5b49e65525b0

It took me a while to extract the exact issue from our code (which is a lot more complex) and now am wondering if this is a bug in v3 (because it worked in v2) or if we need to fix our logic and wait for the data to load before rendering anything. 

Background:
We have a header that is changing based on the scroll position of a vertical list nested inside a horizontal list.
Therefore we create the scrollHandler (useAnimatedScrollHandler) in the top level component and pass it through the horizontal list to the vertical lists.

### Steps to reproduce

1. re-render nested lists from a component that loads data
2. (see the snack for details)

### Snack or a link to a repository

https://snack.expo.dev/@marco.blu/6b7527?platform=ios

### Reanimated version

3.5.2

### React Native version

0.72.4

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by NikitaDudin** [comment]
Try to use zero array [dependencies](https://docs.swmansion.com/react-native-reanimated/docs/scroll/useAnimatedScrollHandler#dependencies-array) to stop recreating the scroll handler callback on each render.
```JS
  const scrollHandler = useAnimatedScrollHandler((event) => {
    translationY.value = event.contentOffset.y;
    console.log(event.contentOffset.y);
  }, 
  [], // <------ add this
  ); 
```

**Comment by blumendorf** [comment]
Oh nice. Can't believe I missed that, Thanks a lot.
