### ISSUE TITLE
r.g.__reanimatedWorkletInit is not a function

### ISSUE THREAD

**Issue by AliYar-Khan** [software-mansion/react-native-reanimated#5130]
### Description

i am working on an expo app and it is not working because of an issue

```
TypeError: r.g.__reanimatedWorkletInit is not a function
    at t.Z (@react-navigation.drawer:3:91480)
```

### Steps to reproduce

1. add "react-native-reanimated": "~3.3.0", in an expo app with sdk 49.0.0
2. it will give the error 

### Snack or a link to a repository

https://snack.expo.dev/@aliyark145/fe8782?platform=web

### Reanimated version

3.3.0

### React Native version

0.71.3

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! It looks that the problem comes from `react-navigation/drawer`, you can see there is an open issue with this bug: https://github.com/react-navigation/react-navigation/issues/11034.
According to the issue the bug affect drawer v6.3.2 to v6.5.1+, so you may try downgrading it to v6.3.1 or below.
