### ISSUE TITLE
how can i use animated value as props to send to custom component?

### ISSUE THREAD

**Issue by KingAmo** [software-mansion/react-native-reanimated#514]
i want to send an animated value to `MyComponent` as a props, `MyComponent ` can use the props to set to its `Animated.View` ,and when the  animated value change,  `MyComponent` could animate.

but unfortunately it seems it does not work. 

what should i do ?

**Comment by jakub-gonet** [comment]
Hi @KingAmo!

Please provide a [snack](https://snack.expo.io/) with code and libs versions, we can't help you without that. 

That being said, passing `Value`s as props should work, I modified `widthAndHeight `example from Reanimated repo to use Text as a standalone component, you can see it in action [here](https://snack.expo.io/@jgonet/thrilled-tea)

If this doesn't help please reply, I'll reopen.
