### ISSUE TITLE
Poor transitions' docs

### ISSUE THREAD

**Issue by osdnk** [software-mansion/react-native-reanimated#516]

**Comment by ovy9086** [comment]
can we just rename this to 'Poor docs' in general 😆 ?
for me it's the 3rd time I'm trying to get up to speed with the library, but the docs seem not enough, and the `Example/` project seems to have a lot of outdated, inconsistent samples 🤔  

i feel like some 'How to XYZ' , easy guides would benefit a lot of people.

**Comment by jakub-gonet** [comment]
@ovy9086, I'm working on some "first steps" type guide, so this should be solved sometime soon :>

'How to XYZ' is IMO too general, it's hard to say which use cases should land in  there

**Comment by adamczyk777** [comment]
@osdnk @jakub-gonet I can help with the docs, I started using Transitions in commercial project and the lack of good docs is making me slow.

**Comment by nwaughachukwuma** [comment]
😆 Anyone ever got to configure animated switch with the transition prop? Please share what you did right

**Comment by jpudysz** [comment]
I would like to give it a try but it's pretty hard to learn reanimated. Do you know any resources or tutorials (except Can it be done in react native)? 😅

**Comment by pranaybinju** [comment]
> I would like to give it a try but it's pretty hard to learn reanimated. Do you know any resources or tutorials (except Can it be done in react native)? 😅

Hi,
I've tried to explain basics of react-native-reanimated by a hands-on approach in a blog.
Hope this helps!
https://blog.kiprosh.com/react-native-reanimated-a-hands-on-approach-1/

I'm trying to create its part-2 that involves transformation (translation specifically). But it seems interpolate doesn't accepts '%' in output.

**Comment by jpudysz** [comment]
@pranaybinju thanks for your post, I will take a look

**Comment by servonlewis** [comment]
I've just given up on this library. I love what people do with it but i am completely new to animations and the lack of docs makes it unbearable. 

Was simply trying to do a fade transition in.
