### ISSUE TITLE
'hermes/inspector/chrome/Registration.h' file not found on react-native@0.73-RC.1

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#5182]
### Description

After upgrading to react-native@0.73.0-RC.1 it throws 'hermes/inspector/chrome/Registration.h' file not found on `ReanimatedHermesRuntime` on both Platforms.

<details>
  <summary>Xcode screenshot</summary>

![Screenshot 2023-10-05 at 08 20 59](https://github.com/software-mansion/react-native-reanimated/assets/717975/420ca15b-336e-48a7-8222-b763912a1516)

</details>

### Steps to reproduce

1. Upgrade to react-native@0.73-RC.1
2. Build on Xcode 15
3. Do the same for Android

### Snack or a link to a repository

/

### Reanimated version

3.5.4

### React Native version

0.73.0-RC.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

both platforms simulators

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @efstathiosntonas, we're working on support for 0.73, see #4913.

**Comment by tjzel** [comment]
<details>

```
MMMMMMMMMMMMMMMMMMMMMMMWNXKKKKKKKKKKXWMMMMMMMMMMMMMMMWWWWMMMMMMM
MMMMMMMMMMMMMMMWX0XWWNXK00KXXXNXXXX0OOKNNWWMMMMMMMMMN0kOKNMMMMMM
MMWXXWMMMMMMMW0dllkKK0OO0KKXXXXXXKK0OO0KKKXXNWMMMMMMW0dxKWMMMMMM
MW0loXMMMMMMWXOxk0KXXKOOOO00000KKKKKKKXXXXKKKKXNNMMMMWKXWMMMMMMM
W0c;oKMMMMMNK0KXXXK00OxdddxkkOOO000KKKXKK0KXXXXK0XWMMMMMMMMMMMMM
Xl',l0WWWWNKO00KK00Okxl::codkkOOOOOO0000OkO0KKK0OOKNWWMMMMMMMMMM
0;..'l0XXXKKKK0OkkOOkkoccdk0KXXKKK0OkkkOOkkkkkO0KKXKXXXNWMMMMMMM
NkoddxOKXXXNNXK00KKXXK0kk0XXXXXXXXK0kkOKXXXK000KXXXNXXK0KNMMMMMM
MMMNOkO0KKXXXKOO0KXXXK0OO0KKKKKKKK0OkxOKK00K00OOKXXXKK0Ok0WMMMMM
MMMXxdxkOOOOOkddkOO0OOxddxkOOOOOOOkxdodkxdxkkkxxxkOOOOkxod0NWMMM
MMMNxcloodddol::clooolc::cllooddoool:;:cloxkkkxdoldddooc:ldONMMM
MMMMKo;;;;;;;,,'',,,,,'''',,;;;;;;,,''',:ldxxddlc;;:;;;,:odxKMMM
WX00KKkl;,''''''''..'''''...........''',:cloolc:,''...';lood0WMM
Nd:ldONWXOxl;'''''.';cc,................',;cc:;,......,::clkNMMM
MKl:lxKMMMMWXOdlc;';kXk;..................,lxkxl'...',;;;:xNMMMM
MMKl:d0KXWMMMMWK0OkO0xc,,,,,;,,,,,,,;;,;;;l0WMWOol:;,;cxOKNMMMMM
MMM0l:;;ckXWMMMMMMMMXxl:,..............,:lONMMMMWWNK00XWMMMMMMMM
MMMMNXx,';lKWMMMMMMNXKKKx'            .okk0KKNWWMMMMMMMMMMMMMMMM
MMMMMMWOodONMWXOOOOo::col:;;;,'...',,,:c:;;;;cox0XWWWMMMMMMMMMMM
MMMMMMMMWXK0Okl;;c:'..'',,,,,;cc:::cllllc:;;,'',:dxkXMMMMMMMMMMM
MMMMMMMW0ol:;''';c:,.',,,,,;;:cllcclllccc::ccc:::lo0WMMMMMMMMMMM
MMMMMMMMNOo:;,..'''..',,,''.',:llllllcccccllc::::lOWMMMMMMMMMMMM
MMMMMMMMMWXx:'......',;;;,,,'.':clooollllolc:cc:cxNMMMMMMMMMMMMM
MMMMMMMMMMMW0c......';;;;;;;;'.';:looooooolcclccckWMMMMMMMMMMMMM
MMMMMMMMMMWXkc......',,,,''',;'.';cloooooolc::cclOWMMMMMMMMMMMMM
MMMMMMMMMNkc'........'',.. .::,..,:cllooool;,:c:oKMMMMMMMMMMMMMM
MMMMMMMN0l;,'........',;.  ......';:clloool'..,:dXMMMMMMMMMMMMMM
MMMMMMNk:;;,'.......',;:,   ....'',;:ccllll;..,co0WMMMMMMMMMMMMM
MMMMMWKo;;;,'......',,;::,....''''',;:cclllc;;cllxXWMMMMMMMMMMMM
MMMMNkl;;,,'......',,;;::;;,,,''''',;;:cccccccclllxXMMMMMMMMMMMM
MMMNOo:,'''.......'',;;;;;;,,,'''''',;;:::cccccccllOWMMMMMMMMMMM
MMMMWNk;'''........',,,,,,,,''''''''',;;;;::cccccccdXMMMMMMMMMMM
MMMMMNd'''.........'',,,,,''.........',;;:clllllllcl0MMMMMMMMMMM
MMMMM0:'''..........'''','...........';:cccccccccccl0MWNMMMMMMMM
MMMMWx,'''............';o:..........';;;;:::c:c:::coKN0KWMWNWMMM
MMMMXo'''......;,.....'lkl.........',,'..,;::::,.';cxkkKWNOONMMM
MMMMNd;,'.....;dc...  .lOk:'......',,....';;::;...':okkxkxdONMMM
MMMMWNK0c....'lkd,..  .;d00Oo,....,;'. .';:::cc,..,cdxoclokXWMMM
MMMMMMMWk,...,lxOxc;;,;;;:ldd:....'::,';cccccllc::cloooodkXWMMMM
MMMMMMMMXl...':ok0XXKK0Oc...'......,:ccccccccclllccoddxOKWMMMMMM
MMMMMMMMMKkko,.;cdk000ko;'..',,,,,'',,;::::cccccoxO0KXNWMMMMMMMM
MMMMMMMMMMMMNx,..',;c:,..''.',;;;;,,,,,;,,,;,,:dKWMMMMMMMMMMMMMM
MMMMMMMMMMMMMNx;,::,',,'..'''',;;;;;;;;;'.''':xXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWXKNNKo;,;;,''',;;;;;;;,,';:;,cONMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWXKKkl;,,,:ccccc:::cc:;l0WMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMN0o:,,,,,,;;,,,,:xXMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0d:,,,'''',:d0WMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o:,.'',ckNMMMMMMMMMMMMMMMMMMMMMMM
```

</details>

**Comment by efstathiosntonas** [comment]
@tomekzaw totally forgot about that PR 🤦‍♂️, thanks for the update. 

Closing this since it’s wip

**Comment by manodupont** [comment]
On react-native: 0.73.0 and "react-native-reanimated": "3.1.0", i do have that problem. Is it supposed to be done according to this ticket ? I don't see a release though

**Comment by mMarcos208** [comment]
same issue 0.73.1

**Comment by tomekzaw** [comment]
@mMarcos208 no way

**Comment by VladosusCocosus** [comment]
Same issue 0.73.2

**Comment by damianimashaun** [comment]
running into the same issue. **0.73.2**
I know its WIP, just nudging you guys

**Comment by MattBlack01** [comment]
same issue

**Comment by Polombo98** [comment]
Guys I'm facing the same issue

**Comment by Robogram** [comment]
getting this error "'hermes/inspector/chrome/Registration.h' file not found". so annoying

using:
"react-native": "0.73.2",
"vision-camera-face-detector": "^0.1.8",
"react-native-vision-camera": "2.16.1",
"react-native-reanimated": "3.5.4"

**Comment by cblaze22** [comment]
Same deal here, .73.2

**Comment by Robogram** [comment]
> getting this error "'hermes/inspector/chrome/Registration.h' file not found". so annoying
> 
> using: "react-native": "0.73.2", "vision-camera-face-detector": "^0.1.8", "react-native-vision-camera": "2.16.1", "react-native-reanimated": "3.5.4"

Hi, do you know any alternative library to "vision-camera-face-detector"?

Thanks:)

**Comment by yokozawa0701** [comment]
I've solved it to see below.

https://github.com/software-mansion/react-native-reanimated/issues/5605#issuecomment-1905566011

**Comment by gibo77** [comment]
Running on same issue with 0.74

**Comment by 5PK** [comment]
> Running on same issue with 0.74

Did you try @yokozawa0701's fix? worked for me.

**Comment by wmonecke** [comment]
@5PK what version did you end up using?

Im on:
"react-native": "0.73.10",
"react-native-reanimated": "3.6.1",

still seeing the issue

**Comment by 5PK** [comment]
@wmonecke 

This is what I’m using rn 

    "react-native": "0.74.5",
    "react-native-reanimated": "3.15.3",

**Comment by wmonecke** [comment]
@5PK did that finally solve the issue for you? thanks for the help 🙌

**Comment by 5PK** [comment]
@wmonecke Yes, but I'm also using Expo 51, not sure if that applies to you.
