### ISSUE TITLE
[Docs] Your First Animation demo doesn't work

### ISSUE THREAD

**Issue by la55u** [software-mansion/react-native-reanimated#5207]
### Description

The demo in [this](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/your-first-animation#using-an-animation-function) section of the docs doesn't work (nothing happens on click of the button).

### Steps to reproduce

1. Visit the demo [here](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/your-first-animation#using-an-animation-function)
2. Click on the Click me button
3. _Nothing visible happens_

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/blob/main/docs/src/examples/FirstAnimation.jsx

### Reanimated version

latest

### React Native version

-

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

Firefox Developer Edition 119

### Acknowledgements

Yes

**Comment by Latropos** [comment]
@kacperkapusciak It works on when I run our docs locally, probably this is an issue with inline props, that were broken on web. Should we upgrade reanimated for docs?
