### ISSUE TITLE
[Android] [useAnimatedKeyboard] useAnimatedKeyboard returns an incorrect keyboard height between keyboard type changes

### ISSUE THREAD

**Issue by A-Yatsyk** [software-mansion/react-native-reanimated#5208]
### Description

useAnimatedKeyboard does not update the height value when the keyboard is open and we switch focus between input fields with different input types.

https://github.com/software-mansion/react-native-reanimated/assets/20336643/c791b162-4ea3-4fb3-b706-83c1e29ca70f

```
const aKeyboard = useAnimatedKeyboard();

const aStyle = useAnimatedStyle(() => ({
  transform: [{ translateY: -aKeyboard.height.value }]
}));

```
```
return (
  <SafeAreaView style={{ flex: 1, justifyContent: 'flex-end', paddingHorizontal: 20 }}>
    <Animated.View style={aStyle}>
      <TextInput
        inputMode="email"
        style={{ height: 46, width: '100%', borderRadius: 10, borderWidth: 2, borderColor: 'gray' }}
        placeholder="inputMode: email"
      />

      <View style={{ height: 20 }} />

      <TextInput
        inputMode="numeric"
        style={{ height: 46, width: '100%', borderRadius: 10, borderWidth: 2, borderColor: 'gray' }}
        placeholder="inputMode: numeric"
      />
    </Animated.View>
  </SafeAreaView>
);
```

### Steps to reproduce

1. Add `useAnimatedKeyboard`;
2. Add two or more input fields with different keyboard types (for different keyboard heights);
3. Add `useAnimatedStyle` to provide the offset based on keyboard height;
4. Apply animated style to `Animated.View`;
5. Focus on the first input field (the height will be correct);
6. Focus on the second input field (the height of the keyboard won't change but keyboard height is different).

### Snack or a link to a repository

https://snack.expo.dev/@ayatsyk/react-native-reanimated-useanimatedkeyboard-issue

### Reanimated version

3.3.0-3.5.4

### React Native version

0.70.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 4

### Acknowledgements

Yes

**Comment by oleksandr-dziuban** [comment]
Hello guys, I have the same issue...

Could you please review?

**Comment by JMinayaT** [comment]
Hello,  I have the same issue.

**Comment by andreysam** [comment]
Hey @A-Yatsyk @oleksandr-dziuban @JMinayaT Created minor fix for similar issue but it needs more testing. Can you try it in your cases? 🙏

**Comment by A-Yatsyk** [comment]
> Hey @A-Yatsyk @oleksandr-dziuban @JMinayaT Created minor fix for similar issue but it needs more testing. Can you try it in your cases? 🙏

Sure, thanks, I'll let you know about the result.
