### ISSUE TITLE
Uncaught ReferenceError: _removeFromPropsRegistry is not defined on Web

### ISSUE THREAD

**Issue by TNAJanssen** [software-mansion/react-native-reanimated#5211]
### Description

When trying to animate after upgrading to 3.5.4 (tried 3.4.2 as well) from 3.3.0, the web version does not load.

### Steps to reproduce

1. Upgrade 3.3.0 to 3.4.2
2. Try accessing web
3. see error

### Snack or a link to a repository

not created yet

### Reanimated version

3.5.4

### React Native version

0.72.4

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Chrome

### Acknowledgements

Yes

**Comment by cjmling** [comment]
@TNAJanssen  I see you closed. Having the same issue, any help on what you did to fix this issue?

**Comment by TNAJanssen** [comment]
@cltsang run the start with clear
