### ISSUE TITLE
Android/IOS: interpolate working on wrong way when step not same (input,output)

### ISSUE THREAD

**Issue by MasonLe2497** [software-mansion/react-native-reanimated#5217]
### Description

When i use GestureDetector to change the box. In hapycase, input and output of ```interpolate``` are same step:
```tsx
              const nextValue = translateY.value + changeY;
              translateY.value = interpolate(nextValue, [0, 100], [0, 100]);
```

https://github.com/software-mansion/react-native-reanimated/assets/43195241/76306ad2-c7d6-4a39-bac3-3ff6a6b2ef27

But, when input and output of ```interpolate``` are diff step, the box can not moving correctly:
```tsx
              const nextValue = translateY.value + changeY;
              translateY.value = interpolate(nextValue, [0, 100], [0, 90]);
```

https://github.com/software-mansion/react-native-reanimated/assets/43195241/1cfb5910-a4dd-4559-b939-3d2853668f2a

### Steps to reproduce

1. Init project
2. Install reanimated and react-native-gesture-handler
3. Copy my code below:
```tsx
import React from 'react';
import {SafeAreaView, StyleSheet, View} from 'react-native';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';
import Animated, {
  interpolate,
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';

export const App = () => {
  // state
  const translateY = useSharedValue(0);

  // style
  const headerStyle = useAnimatedStyle(() => {
    return {
      height: 50,
      width: 50,
      backgroundColor: 'red',
      position: 'absolute',
      zIndex: 12,
      transform: [{translateY: translateY.value}],
    };
  });

  return (
    <GestureHandlerRootView style={styles.root}>
      <SafeAreaView style={styles.root}>
        <View style={styles.root}>
          <Animated.View style={headerStyle} />
          <GestureDetector
            gesture={Gesture.Pan().onChange(({changeY}) => {
              const nextValue = translateY.value + changeY;
              translateY.value = interpolate(nextValue, [0, 100], [0, 90]);
            })}>
            <View style={StyleSheet.absoluteFillObject} />
          </GestureDetector>
        </View>
      </SafeAreaView>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
});

```

### Snack or a link to a repository

You can see my simple code above

### Reanimated version

3.5.4

### React Native version

0.72.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi, let's go step by step through your code:

```javascript
              const nextValue = translateY.value + changeY;
              translateY.value = interpolate(nextValue, [0, 100], [0, 80]);
```
Assume that translateY.value = 200

1. Move square 0 px down 
3. Next value = 200px
4. translateY.value = .80 * 200 = 160

Voila! You get big jumps when you slightly move your square? And the translateY is going exponentially to 0.

To fix that please replace `changeY` with `translationY` (see gesture handler docs: https://docs.swmansion.com/react-native-gesture-handler/docs/1.x/api/gesture-handlers/pan-gh/) and do the following:

```diff
-              const nextValue = translateY.value + changeY;
-              translateY.value = interpolate(nextValue, [0, 100], [0, 80]);
+              translateY.value = interpolate(translationY, [0, 100], [0, 80]);
```
