### ISSUE TITLE
reanimated installation bug 

### ISSUE THREAD

**Issue by shubham6772** [software-mansion/react-native-reanimated#5234]
### Description

when i try to install the react-native-reanimated 
it install correctly but when i run the gradle or do npm start -- --reset-cache as suggested by official libarary it show
 
Exception in HostFunction: java.lang.NoClassDefFoundError: com.swmansion.reanimated.NativeProxy, js engine: hermes
or
WARNING reanimated - no version-specific reanimated AAR for react-native version 72 found.
Falling back to AAR for react-native version 71.
or
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-72.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.

every time a new error .....................
but work with expo fine....................

### Steps to reproduce

on windows

1. Create a Project
2. Install the react navigation drawer
3. It ask you to install react-native-reanimated library.
4. when you install the library using npm i react-native-reanimated
5. it tell you to update babel file after adding plugin
6. start npm start -- reset-cache or use any command 
7. boom errors start knocking on your door. unable to delete file from node module not find failed to compile etc etc

### Snack or a link to a repository

https://github.com/shubham6772/reanimated-bug

### Reanimated version

2.17.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Real device

### Device model

Realme 8 (Realme UI 4.0)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@shubham6772 Thanks for submitting this issue. Unfortunately, Reanimated 2.17.0 does not support React Native 0.72. Please upgrade to Reanimated 3.5.4.
