### ISSUE TITLE
withTiming config duration is not correct with real time

### ISSUE THREAD

**Issue by hungtooc** [software-mansion/react-native-reanimated#5275]
### Description

Hi, I try to animate value from 0 to 1 exactly in 10 seconds:
```javascript
progress.value = withTiming(1, {duration: 10000});
```
but I measured that it ran faster and finished in less than 8 seconds

### Steps to reproduce

```javascript
progress.value = withTiming(1, {duration: 10000});
```

### Snack or a link to a repository

none 

### Reanimated version

3.5.4

### React Native version

0.71.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

Samsung A71

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @hungtooc. I'm sorry, but we are not developing Reanimated2 anymore beside critical fixes. Please consider upgrading to Reanimated3.

**Comment by hungtooc** [comment]
Hi @tjzel, I updated to version `3.5.4`  but I still get this error

**Comment by wcandillon** [comment]
@tjzel this bug was reported against Skia and we kinda of mentionned that this was reanimated responsibility

@hungtooc one thing I would recommend to experiment with you own timing implementation to see if you can find the source of the issue (you will have access to all the internal animation states). you can find an example here: https://github.com/wcandillon/react-native-redash/blob/a8d0d0a03d7be74fdd4a5a35b71f1ebf215ca198/src/Animations.ts#L10

**Comment by tjzel** [comment]
I tested it with `performance.now()` on JS thread and got 10s of animation duration confirmed. I will try some other methods to measure time to see if this could be a problem. 

@hungtooc Could you provide more information about how you measured it?

@wcandillon Could you provide some link to that bug report?

**Comment by hungtooc** [comment]
Hi @tjzel,

I use withTiming() to control how skia animate my images and how the green cursor moving on the timeline.  
I recorded the screen and looked at the duration of the video I recorded. The measuring time started when the green cursor started moving in the timeline and ended when the cursor moved all the way to the end of the timeline. 
I measured 3 times, 10 seconds, 20 seconds and 30 seconds respectively. And this is the result:

https://github.com/software-mansion/react-native-reanimated/assets/24487114/34cae05a-0655-4506-9a27-55659bee3a56


https://github.com/software-mansion/react-native-reanimated/assets/24487114/ef009969-e080-42f2-be53-012a33858cbe


https://github.com/software-mansion/react-native-reanimated/assets/24487114/2cf5c0b7-0a3c-411f-9aad-afbc00640fe9

**Comment by hungtooc** [comment]
Hi @tjzel I saw an error in my code, there is no error in your library!

**Comment by hungtooc** [comment]
> @hungtooc one thing I would recommend to experiment with you own timing implementation to see if you can find the source of the issue (you will have access to all the internal animation states). you can find an example here: https://github.com/wcandillon/react-native-redash/blob/a8d0d0a03d7be74fdd4a5a35b71f1ebf215ca198/src/Animations.ts#L10

Thank you for sharing the great code, you accidentally shared with me `withPause()`, it will help me in pausing/resume my video. Also thanks to Skia `Shader` for helping me create my transition effect
