### ISSUE TITLE
[ANDROID]: React-native-reanumated: 3.5.4; react-native: 0.72.6

### ISSUE THREAD

**Issue by AliakseiPaseishvili** [software-mansion/react-native-reanimated#5276]
### Description

The build fails on task: app:compileDebugJavaWithJavac FAILED

Repo with example is provided.

<img width="1004" alt="Screenshot 2023-10-19 at 15 00 05" src="https://github.com/software-mansion/react-native-reanimated/assets/50828981/b8714861-4e49-4983-93b7-986148fc987c">

### Steps to reproduce

1. download repo
2. run npm i
3.  run npx jetify
4. run npx react-native run-android

### Snack or a link to a repository

https://github.com/AliakseiPaseishvili/dms-demo

### Reanimated version

3.5.4

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by wanderSX** [comment]
@AliakseiPaseishvili 
move **package com.dmsdemo;** to the top of your MainActivity.java

**Comment by AliakseiPaseishvili** [comment]
@wanderSX thanks, you are right!
