### ISSUE TITLE
Re-rendering component with inline SharedValues causes style loss

### ISSUE THREAD

**Issue by marklawlor** [software-mansion/react-native-reanimated#5296]
### Description

When using inline `useSharedValue` animated components lose styling when the component rerenders due to a state update or fast-refresh.

https://github.com/software-mansion/react-native-reanimated/assets/3946701/7435d3c4-fc6e-4413-b78a-c1d369455c2c

### Steps to reproduce

- Clone repo.
  - It was created by `npx react-native@latest init` and following the Getting Started and Your First Animation guides.

- Click the button and observe
  - Purple rectangle flickers (it disappears for 1 frame)
  - Red text turns gray

- Reload app

- Modify a component and observe
  - Purple rectangle disappears
  - Red text turns gray

### Snack or a link to a repository

https://github.com/marklawlor/reanimated-inline

### Reanimated version

3.5.4

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel XL API 33

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Thanks for the issue, we are already working on it in https://github.com/software-mansion/react-native-reanimated/pull/5268
