### ISSUE TITLE
[IOS]: Reanimated Hook can not access js function

### ISSUE THREAD

**Issue by masonle2x2** [software-mansion/react-native-reanimated#5303]
### Description

I have some js function want to exec inside reanimated hook.
But on release mode, js function is undefined.
When i exec that function, it still work.
sometime, i pass js function is optional. so i have to check it is a function or not
My video:

https://github.com/software-mansion/react-native-reanimated/assets/43195241/ffe2d18a-444c-476c-bb4c-34a4f11dbdb7

### Steps to reproduce

```tsx
import React from 'react';
import {Button, SafeAreaView, StyleSheet, Text, View} from 'react-native';
import {
  GestureHandlerRootView,
  PanGestureHandler,
} from 'react-native-gesture-handler';
import Animated, {
  useAnimatedGestureHandler,
  useAnimatedScrollHandler,
  useAnimatedReaction,
  useSharedValue,
} from 'react-native-reanimated';

const UsePanHandler = ({jsFuncProps}: {jsFuncProps: () => void}) => {
  const localFunction = () => {};

  const gestureHandler = useAnimatedGestureHandler({
    onActive: () => {
      console.log(
        'useAnimatedGestureHandler - jsFuncProps is function: ',
        typeof jsFuncProps === 'function',
      );
      console.log(
        'useAnimatedGestureHandler - localFunction is function: ',
        typeof localFunction === 'function',
      );
    },
  });

  return (
    <>
      <Text>useAnimatedGestureHandler</Text>
      <PanGestureHandler onGestureEvent={gestureHandler}>
        <Animated.View style={styles.box} />
      </PanGestureHandler>
    </>
  );
};

const UseScroll = ({jsFuncProps}: {jsFuncProps: () => void}) => {
  const localFunction = () => {};
  const scroll = useAnimatedScrollHandler({
    onBeginDrag: () => {
      console.log(
        'useAnimatedScrollHandler - jsFuncProps is function: ',
        typeof jsFuncProps === 'function',
      );
      console.log(
        'useAnimatedScrollHandler - localFunction is function: ',
        typeof localFunction === 'function',
      );
    },
  });

  return (
    <>
      <Text>useAnimatedScrollHandler</Text>
      <View style={styles.scroll}>
        <Animated.ScrollView onScroll={scroll} scrollEventThrottle={16}>
          <Animated.View style={styles.contentScroll} />
        </Animated.ScrollView>
      </View>
    </>
  );
};

const UseReaction = ({jsFuncProps}: {jsFuncProps: () => void}) => {
  const value = useSharedValue(0);

  const handleChangeValue = () => {
    value.value = Math.random();
  };
  const localFunction = () => {};

  useAnimatedReaction(
    () => value.value,
    () => {
      console.log(
        'useAnimatedReaction - jsFuncProps is function: ',
        typeof jsFuncProps === 'function',
      );
      console.log(
        'useAnimatedReaction - localFunction is function: ',
        typeof localFunction === 'function',
      );
    },
  );

  return (
    <>
      <Text>useAnimatedReaction</Text>
      <Button onPress={handleChangeValue} title="Click to change share value" />
    </>
  );
};

export const App = () => {
  // func
  const jsFunction = () => {};

  // render
  return (
    <GestureHandlerRootView style={styles.root}>
      <SafeAreaView style={styles.content}>
        <Text>Mode: {__DEV__ ? 'DEV' : 'RELEASE'}</Text>
        <UsePanHandler jsFuncProps={jsFunction} />
        <UseScroll jsFuncProps={jsFunction} />
        <UseReaction jsFuncProps={jsFunction} />
      </SafeAreaView>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  scroll: {
    height: 200,
  },
  contentScroll: {
    height: 1000,
    backgroundColor: 'red',
  },
  root: {
    flex: 1,
  },
  box: {
    width: 100,
    height: 100,
    backgroundColor: 'pink',
  },
  content: {
    flex: 1,
    backgroundColor: 'white',
  },
});

```

### Snack or a link to a repository

See my code above

### Reanimated version

3.5.4

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by marcuzgabriel** [comment]
> Try to use [runOnJS](https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS/)
> 
> ```js
> runOnJS(jsFuncion)()
> ```

Yep. Your are trying to execute a JS function on the UI thread. That won't work. https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS/.

runOnJS would be the solution here. Alternatively, if you want to execute a function on the UI thread you could 'workletize' it.

```ts
const localFunction = () => {
  'worklet'
};
```

**Comment by masonle2x2** [comment]
> > Try to use [runOnJS](https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS/)
> > 
> > ```js
> > runOnJS(jsFuncion)()
> > ```
> 
> Yep. Your are trying to execute a JS function on the UI thread. That won't work. https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS/.
> 
> runOnJS would be the solution here. Alternatively, if you want to execute a function on the UI thread you could 'workletize' it.
> 
> ```ts
> const localFunction = () => {
>   'worklet'
> };
> ```
> 

Yes, sure. But when jsfunction props is undefined, app can be crash. So i want to check it is a function or not

**Comment by marcuzgabriel** [comment]
@masonle2x2. Okay i see. Would it work if you try to make the reaction listen to that function? 

 useAnimatedReaction(
    () => ({ localFunction, value: value.value }),
    res => {
      console.log(
        'useAnimatedReaction - jsFuncProps is function: ',
        typeof res.localFunction === 'function',
      );
      console.log(
        'useAnimatedReaction - localFunction is function: ',
        typeof res.localFunction === 'function',
      );
    },
    [localFunction, value], <---
  );

**Comment by masonle2x2** [comment]
> @masonle2x2. Okay i see. Would it work if you try to make the reaction listen to that function? :octocat:. It surely does seems strange that dependent on mode then the JS function can turn out to be undefined.
> 
> ```ts
> useAnimatedReaction(
>     () => ({ localFunction, value: value.value }),
>     res => {
>       console.log(
>         'useAnimatedReaction - jsFuncProps is function: ',
>         typeof res.localFunction === 'function',
>       );
>       console.log(
>         'useAnimatedReaction - localFunction is function: ',
>         typeof res.localFunction === 'function',
>       );
>     },
>     [localFunction, value], <---
>   );
> ```

Yeah. In my case. I use gesture to swipe an item to left or right. Some i item have renderLeftAction, some i tem have renderRightAction. So when PanGesture active, i check renderLeftAction or renderRightAction to translate item or disable it.
So i resolve issue by: create 2 shareValue boolean. Use useEffect to update 2 value when jsFunction is undefined or not. In PanGesture, i check sharevalue to translate.
So i think this solution is not good

**Comment by masonle2x2** [comment]
```tsx
const haveRenderLeft = useSharedValue(false)
const haveRenderRight = useSharedValue(false)
const panGesture = useAnimatedGestureHandler<
      PanGestureHandlerGestureEvent,
      { startX: number }
    >({
      onStart: (_, ctx) => {
        ctx.startX = translateX.value;
      },
      onActive: (event, ctx) => {
        const nextX = ctx.startX + event.translationX;

        if (nextX > 0 && haveRenderLeft.value ) {
          translateX.value = -nextX;
        } else if (nextX < 0 && haveRenderRight.value) {
          translateX.value = nextX;
        }
      },
      
    });
useEffect(()=>{
haveRenderLeft.value = typeof renderLeftActions === 'function'
haveRenderRight.value = typeof renderRightActions === 'function'
}, [])
```

**Comment by marcuzgabriel** [comment]
@masonle2x2,

I see. Yeah that can be tricky trying to listen on something on JS thread in onActive scope in pan gesture. I would probably have used a derived value or defined the values directly.  But it would achieve the same as your useEffect.

```ts
const { haveRenderLeft, haveRenderRight } = useDerivedValue(() => ({
  haveRenderLeft: typeof renderLeftActions === 'function',
  haveRenderRight: typeof renderRightActions === 'function',
})

or defined the animated values directly

const haveRenderLeft = useSharedValue(typeof renderLeftActions === 'function')
```

**Comment by Latropos** [comment]
Thank you all for the answers, yes I know this is tricky, thats why we have updated our troubleshooting docs, I hope now debugging may get easier: https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting/
