### ISSUE TITLE
LayoutAnimationConfig doesnt exist

### ISSUE THREAD

**Issue by pluckannfeel** [software-mansion/react-native-reanimated#5326]
### Description

Hi I am using  "react-native-reanimated": "~3.3.0",

and i want to implement LayoutAnimatedConfig, however it doesnt exist/available whenever i try to call it. 

https://docs.swmansion.com/react-native-reanimated/docs/layout-animations/layout-animation-config

### Steps to reproduce

1. Call LayoutAnimationConfig :
import { LayoutAnimationConfig } from 'react-native-reanimated';

2. Error comes saying
'"react-native-reanimated"' has no exported member named 'LayoutAnimationConfig'. Did you mean 'LayoutAnimation'?ts(2724)

### Snack or a link to a repository

n/a

### Reanimated version

3.3.0

### React Native version

0.72.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Sorry for misleading, but this feature is unreleased yet :/ We want to publish release in the next couple of days

**Comment by pluckannfeel** [comment]
thanks for the information.
