### ISSUE TITLE
unable to build android app

### ISSUE THREAD

**Issue by usmanabid94** [software-mansion/react-native-reanimated#5327]
### Description

I am facing the same issue on 0.72.6 with react native reanimated version 3.5.4?
This is the error message from android studio:
from /Users/apple/Desktop/UsmanData/PetroRigs/node_modules/react-native-reanimated/android
CMake Error at CMakeLists.txt:48 (find_package):
Could not find a package configuration file provided by "fbjni" with any of
the following names:

fbjniConfig.cmake
fbjni-config.cmake
Add the installation prefix of "fbjni" to CMAKE_PREFIX_PATH or set
"fbjni_DIR" to a directory containing one of the above files. If "fbjni"
provides a separate development package or SDK, be sure it has been
installed.

### Steps to reproduce

I am facing the same issue on 0.72.6 with react native reanimated version 3.5.4?
This is the error message from android studio:
from /Users/apple/Desktop/UsmanData/PetroRigs/node_modules/react-native-reanimated/android
CMake Error at CMakeLists.txt:48 (find_package):
Could not find a package configuration file provided by "fbjni" with any of
the following names:

fbjniConfig.cmake
fbjni-config.cmake
Add the installation prefix of "fbjni" to CMAKE_PREFIX_PATH or set
"fbjni_DIR" to a directory containing one of the above files. If "fbjni"
provides a separate development package or SDK, be sure it has been
installed.

### Snack or a link to a repository

none

### Reanimated version

3.5.4

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

pixel 5

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey, all of our example apps builds on rn@0.72.6 https://github.com/software-mansion/react-native-reanimated/blob/main/Example/package.json#L22 without problems, so without link to repository with reproduction we can't help 😔

**Comment by usmanabid94** [comment]
Here is the pacage.json file attached below and facing issue still mentioned above on android app:
{
  "name": "app name",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@babel/runtime": "^7.3.4",
    "@edose/react-native-linkedin": "^1.0.5",
    "@freakycoder/react-native-bounceable": "^1.0.3",
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.15.16",
    "@react-native-community/checkbox": "^0.5.12",
    "@react-native-community/datetimepicker": "^6.1.2",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/analytics": "^18.5.0",
    "@react-native-firebase/app": "^18.5.0",
    "@react-native-firebase/auth": "^18.5.0",
    "@react-native-firebase/messaging": "^18.5.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-native-picker/picker": "^2.4.4",
    "@react-native/normalize-color": "^2.0.0",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/drawer": "^6.6.5",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.19",
    "@sharcoux/slider": "^6.0.3",
    "@supersami/rn-foreground-service": "^1.1.1",
    "@worldpay-beta/access-worldpay-checkout-react-native-sdk-beta": "^1.0.0",
    "accordion-collapse-react-native": "^1.1.0",
    "animated": "^0.2.2",
    "buffer": "^6.0.3",
    "flutterwave-react-native": "^1.0.2",
    "force": "^0.0.3",
    "formik": "^2.2.9",
    "lottie-react-native": "^5.1.6",
    "moment": "^2.29.4",
    "native": "^0.3.3",
    "npm-upgrade": "^2.0.4",
    "radio-buttons-react-native": "^1.0.4",
    "react": "18.2.0",
    "react-devtools": "^4.24.1",
    "react-linkedin-login-oauth2": "^2.0.1",
    "react-native": "0.72.6",
    "react-native-animated-pagination-dot": "^0.3.2",
    "react-native-autoheight-webview": "^1.6.4",
    "react-native-braintree-dropin-ui": "^1.1.3",
    "react-native-confirmation-code-field": "^7.3.0",
    "react-native-countdown-component": "^2.7.1",
    "react-native-credit-card-input": "^0.3.1",
    "react-native-document-picker": "^8.1.0",
    "react-native-draggable-flatlist": "^1.1.9",
    "react-native-dynamic-search-bar": "^2.0.1",
    "react-native-elements": "^3.4.1",
    "react-native-fast-image": "^8.5.11",
    "react-native-fbsdk-next": "^7.2.0",
    "react-native-geocoding": "^0.5.0",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "^2.13.3",
    "react-native-get-location": "^2.2.1",
    "react-native-google-mobile-ads": "^11.1.1",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-grid-image-viewer": "^1.3.0",
    "react-native-iap": "^8.1.3",
    "react-native-image-crop-picker": "^0.37.2",
    "react-native-image-viewing": "^0.2.1",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-spacer-view": "^0.0.3",
    "react-native-location": "^2.5.0",
    "react-native-maps": "^0.30.2",
    "react-native-material-menu": "^2.0.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-modal-dropdown": "^1.0.2",
    "react-native-pager-view": "^5.4.15",
    "react-native-paper": "^4.9.1",
    "react-native-paystack-webview": "^4.0.3",
    "react-native-pell-rich-editor": "^1.8.8",
    "react-native-phone-input": "^1.3.4",
    "react-native-push-notification": "^8.1.1",
    "react-native-ratings": "^8.0.4",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-razorpay": "^2.3.0",
    "react-native-reanimated": "^3.5.4",
    "react-native-render-html": "^6.3.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-restart": "^0.0.24",
    "react-native-root-toast": "^3.2.0",
    "react-native-safe-area-context": "^3.4.1",
    "react-native-screens": "^3.26.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-sliders": "^1.1.1",
    "react-native-spinkit": "^1.5.1",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-textinput-effects": "^0.6.2",
    "react-native-vector-icons": "^8.1.0",
    "react-native-virtualized-view": "^1.0.0",
    "react-native-walkthrough-tooltip": "^1.3.1",
    "react-native-webview": "^11.17.2",
    "react-native-youtube": "^2.0.2",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-devtools-extension": "^2.13.9",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "rn-checkbox-list": "^1.1.0",
    "rn-fetch-blob": "^0.12.0",
    "rn-range-slider": "^2.1.1",
    "underscore": "^1.13.2",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by AlixH** [comment]
Up
