### ISSUE TITLE
React Native iOS app crashes when animate svg component

### ISSUE THREAD

**Issue by Yurii-Lutsyk** [software-mansion/react-native-reanimated#5335]
### Description

The React Native (0.76) iOS app crashes with an Assertion failed error in the Loader component when trying to animate the SVG path component. The error occurs in the src/components/svg/Loader file.

Expected Result:
The app should not crash and the Loader component should animate as expected.

Actual Result:
The app crashes with an Assertion failed error in the Loader component.

Affected Version:
React Native 0.76
react-native-svg 13.14.0

Steps Taken to Resolve:
1. Tried updating React Native to the latest version, but the issue persisted.
2. Checked the code for any obvious errors, but could not find any.
3. Searched for similar issues online, but could not find any relevant solutions.

### Steps to reproduce

1. Run yarn to install dependencies.
2. Run yarn pod-install to install pods.
3. Run yarn ios to start the app on iOS simulator.
4. Navigate to the screen with the Loader component.
5. Observe the app crashing with an Assertion failed error.

### Snack or a link to a repository

https://github.com/Yurii-Lutsyk/rnapp2

### Reanimated version

3.5.4

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! I have troubles to run your example. I always get error
> Command PhaseScriptExecution failed with a nonzero exit code
Is it possible that your podfile is corrupted?

**Comment by Yurii-Lutsyk** [comment]
@Latropos Please change the nodePath here, sorry for this
https://github.com/Yurii-Lutsyk/rnapp2/blob/main/ios/.xcode.env

**Comment by Latropos** [comment]
https://github.com/software-mansion/react-native-reanimated/assets/56199675/4e3c2fb8-cd50-4136-aaed-5da810522a29

Your code was incorrect, 

```diff
- withSequence(
-  (color.value = withTiming(1, { duration: 5000 })),
-  (color.value = withTiming(0, { duration: 1000 }))
+ color.value = ithSequence(
+  withTiming(1, { duration: 1000 }),
+. withTiming(0, { duration: 1000 })
),
```

**Comment by Yurii-Lutsyk** [comment]
@Latropos Thank you so much!
