### ISSUE TITLE
Entering animation crash when withCallback() is set

### ISSUE THREAD

**Issue by perroudsky** [software-mansion/react-native-reanimated#5343]
### Description

A simple entering animation crash when a callback is set.

```js
  <View style={styles.container}>
          <Animated.View style={styles.box} entering={SlideInLeft.withCallback((finished) => {
    console.log(`finished without interruptions: ${finished}`);
  })}>
              <Text>Hellooo</Text>
          </Animated.View>     
    </View>
  );
```

### Steps to reproduce

Run the snack provided

### Snack or a link to a repository

https://snack.expo.dev/@perroudsky/shallow-red-candy

### Reanimated version

3.3.0

### React Native version

snack version

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
@perroudsky Thats weird, everything works for me

https://github.com/software-mansion/react-native-reanimated/assets/56199675/aeaab0c6-3140-4be7-b73c-5ede6d321dbd

**Comment by Latropos** [comment]
@perroudsky
1. Are you sure that the crash is on IOS?
2. Could you describe the crash? Provide error logs?

**Comment by perroudsky** [comment]
Hi @Latropos !
1. I originally tried it with a custom dev client but it also does crash on iOS with simulator and with expo go. 
2. It crashes when the callback starts. Removing the callback prevents the crash

here's a simple repro
[https://github.com/perroudsky/reanimated-callback-crash-repro](url)

**Comment by jfedak** [comment]
Hi @perroudsky! It was fixed in newer version of Reanimated. I checked it with Expo SDK 50 with Reanimated 3.6.1. and it seems to work fine.

**Comment by thuongtv-vn** [comment]
hummm i got the same issue. even using the latest version:
```  const scaleDownAnimation = useMemo(() => {
    return new Keyframe({
      0: { transform: [{ scale: 1 }] }, // Original size
      100: { transform: [{ scale: 0.8 }] }, // Scale down to 80%
    })
      .duration(500)
      .withCallback((finished) => {
        
      });
  }, []);```

**Comment by JaapWeijland** [comment]
I get the same issue, running in Expo Go SDK 55.

Working:

```
<Animated.View
	key={transaction.id}
	className="flex-row"
	entering={FadeInDown.delay(delayToTotal * 100)
		.easing(Easing.inOut(Easing.ease))}
	exiting={FadeOutUp}
>
```

Breaking:

```
<Animated.View
	key={transaction.id}
	className="flex-row"
	entering={FadeInDown.delay(delayToTotal * 100)
		.easing(Easing.inOut(Easing.ease))
		.withCallback(() => {
			Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
		})}
	exiting={FadeOutUp}
>
```
