### ISSUE TITLE
Library not compatible with React Native 0.73

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [software-mansion/react-native-reanimated#5346]
### Description

I am trying the latest RC version of React Native, I see few issues to work with Reanimated library:
1. Android build.gradle is not updated to include namespace definition.
2. On build I am getting below error:
/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/messageQueueThread/latest/com/swmansion/reanimated/ReanimatedMessageQueueThread.java:7: error: ReanimatedMessageQueueThread is not abstract and does not override abstract method isIdle() in MessageQueueThread
public class ReanimatedMessageQueueThread extends ReanimatedMessageQueueThreadBase {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

### Steps to reproduce

Integrate Reanimated with latest RC of React Native (0.73.0-rc.3)

3. Lots of error related to C++20 extension

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.5.4

### React Native version

0.73.0-rc.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @ravindraguptacapgemini. If you want to test Reanimated with RC version of React-Native you should try our latest nightly build, since e.g. we recently [merged support for React Native 0.73]. cc @piaskowyk if any of the mentioned errors here sounds familiar to you.

**Comment by Latropos** [comment]
Yes, Reanimated 3.4 still doesn't support React Native 0.73, please see the compatibility table: https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility
