### ISSUE TITLE
Broken Web Animations Starting With v3.5.0

### ISSUE THREAD

**Issue by yulolimum** [software-mansion/react-native-reanimated#5347]
### Description

Hello!

I am adding web support to an app. Started with the latest versions of react-native-web and react-native-reanimated. Animations seem to not be working without any console error output. Started backtracking on versions to find the last working version

Version 3.5.3->nightlies has animations that don't run. 
Version 3.5.0-3.5.2 has web TS issues: https://github.com/software-mansion/react-native-reanimated/issues/5073
Version 3.4.2 has an TS export issue: https://github.com/tamagui/tamagui/issues/1363#issuecomment-1671234125
Version 3.4.1 seems like the last working version.

Additionally, I tried to replicate the issue on the example application within this repo with same results.

| **3.4.1**                                                                                                                       | **3.5.4**                                                                                                                        |
|---------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/1775841/664479cf-9d04-423e-a50c-84c1a63604dd" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/1775841/6cf221d9-7efb-47df-b240-27fca1f1cb6a" /> |

Thank you!

### Steps to reproduce

1. `git clone git@github.com:yulolimum/tmp-reanimated-repro.git`
2. `yarn`
3. `yarn dev`

---

To see a non-broken version:
1. `git clone -v 3.4.1 git@github.com:yulolimum/tmp-reanimated-repro.git`
2. `yarn`
3. `yarn dev`

---

To see the non-working code in this repo:
1. `git clone git@github.com:software-mansion/react-native-reanimated.git`
2. `yarn`
3. `cd WebExample`
4. `yarn`
5. `yarn start`

### Snack or a link to a repository

https://github.com/yulolimum/tmp-reanimated-repro

### Reanimated version

3.5.4

### React Native version

0.72.6

### Platforms

Web

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @yulolimum. I just ran your example with Reanimated 3.5.4 and everything is working fine. It seems that you have `Reduced motion` accessibility setting enabled and that's why the animation doesn't trigger.

**Comment by yulolimum** [comment]
lol you're totally right. had no idea that'd affect web. thank you for pointing that out! looks like v3.5.0 introduced that and i have that setting on on all my Macs. thanks again!
