### ISSUE TITLE
nightly fails with Unhandled JS Exception: Error: Exception in HostFunction: [Reanimated] C++ side failed to resolve JavaScript code version

### ISSUE THREAD

**Issue by Pingou** [software-mansion/react-native-reanimated#5352]
### Description

nightly fails with Unhandled JS Exception: Error: Exception in HostFunction: [Reanimated] C++ side failed to resolve JavaScript code version.
Have updated to 3.6.0-nightly-20231107-c56d44fd9.
Pod install succeed, the app works in debug on iOS but fails in release mode (on a real device).
May be related to https://github.com/software-mansion/react-native-reanimated/pull/4914

### Steps to reproduce

1 - install react-native-reanimated nightly
2 - pod install
3 - launch in release mode on real device

### Snack or a link to a repository

-

### Reanimated version

3.6.0-nightly-20231107-c56d44fd9

### React Native version

0.72.4

### Platforms

iOS 17

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iPhone 12

### Acknowledgements

Yes

**Comment by tjzel** [comment]
@Pingou This is a known issue and I'm currently investigating it. What is your XCode version?

**Comment by Pingou** [comment]
@tjzel thank you for your answer. I use xcode 15.0.
Do you have any idea when that may be fixed? I'm trying to decide if I release with a bug that is fixed in the nightly or if I wait for the fix.

**Comment by tjzel** [comment]
This is definitely our priority right now, I'd suggest waiting for the fix.

**Comment by Pingou** [comment]
@tjzel Any update? It seems to work on iOS now but fails on Android.
