### ISSUE TITLE
Horizontal Flatlist separators do not render inline

### ISSUE THREAD

**Issue by GibbyBox** [software-mansion/react-native-reanimated#5355]
### Description

I'm trying to leverage the `ItemSeparatorComponent` prop in `Animated.FlatList` in the latest version of reanimated.

When using the `horizontal` prop, the separators are pushed to a new row. The expectation is that they are between items in the list.

I included a snack to observe this issue. 

There is a [PR](https://github.com/facebook/react-native/pull/15865) made to the react-native repo way back that documented and resolved a similar issue.

### Steps to reproduce

1. Use Animated.Flatlist with the horizontal prop and ItemSeparatorComponent prop
2. Observe issue
3. Swap to using Animated.Flatlist from react-native
4. Observe expected behavior

### Snack or a link to a repository

https://snack.expo.dev/@gibbybox/reanimated-horizontal-flatlist-separator-issue

### Reanimated version

3.5.4

### React Native version

0.72

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by GibbyBox** [comment]
I updated the snack to include a side by side of the expected vs the actual

**Comment by Latropos** [comment]
The problem appears only when reanimated is used with expo

**Comment by Latropos** [comment]
This problem was resolved in: https://github.com/software-mansion/react-native-reanimated/pull/5295, please update your reanimated to start using the fixed version

**Comment by GibbyBox** [comment]
Thanks for closing the issue. I appreciate the quick response. @Latropos

FYI, the fix hasn't been included in any released version yet. Do you have a timeline for when the next version drops?
