### ISSUE TITLE
[Android Release build Crash] TypeError: undefined is not an object (evaluating 'valueUnpacker.__initData.code'), stack:

### ISSUE THREAD

**Issue by Helen2hang** [software-mansion/react-native-reanimated#5362]
### Description

Hi,
We are currently using reanimated with our React-native application that we created using [Nx](https://nx.dev)
But for some reason, when we make a release build on Android, it keeps crashing directly after the splash screen. 
**Important to note:** It doesn't crash on Android debug build.

When we used logcat to find the crash error message, we saw this error message:
![image](https://github.com/software-mansion/react-native-reanimated/assets/25255911/d44831a2-d0a6-4064-ba14-bd8a66cf946f)

We disabled Hermes to see the error in more detail, and we saw this error message.

`TypeError: undefined is not an object (evaluating 'valueUnpacker.__initData.code'), stack:`

![image](https://github.com/software-mansion/react-native-reanimated/assets/25255911/8e9eb256-335b-4365-a674-b7f1c59546d7)

I found that it comes from the code of Reanimated in this PR: https://github.com/software-mansion/react-native-reanimated/pull/4944/files. 

We do have `react-native-reanimated/plugin` is listed in our babel.config.js, so I am not sure what else we are missing.

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};

```
Maybe we are missing an important `@babel` package? Can someone list me the `@babel package` that are necessary for reanimated to work properly? Or if someone knows what we are missing that could cause the crash to only happen on release mode but not on debug mode...

### Steps to reproduce

It's more related to our project, so I don't think it is easy to reproduce.

### Snack or a link to a repository

-

### Reanimated version

3.5.4

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

Pixel 7 Pro API 31, Android 12

### Acknowledgements

Yes

**Comment by Helen2hang** [comment]
sorry, it's not an issue with reanimated. Our NX project was not well setup. It wasn't detecting the babel.config in the mobile project for android release build for some reason.

**Comment by ChenShiChao** [comment]
this error: 

2024-03-14 11:29:19.132 6945-6971/com.my.app  E/ReactNativeJS: Error: Requiring module "635", which threw an exception: TypeError: undefined is not an object (evaluating 'valueUnpacker.__initData.code')
    
    --------- beginning of crash
2024-03-14 11:29:19.142 6945-6972/com.my.app E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.evergrande.hamapp, PID: 6945
    com.facebook.react.common.JavascriptException: Error: Requiring module "635", which threw an exception: TypeError: undefined is not an object (evaluating 'valueUnpacker.__initData.code'), stack:
    h@2:1600
    <unknown>@1015:719
    h@2:1709
    <unknown>@1011:332
    h@2:1709
    <unknown>@1009:634
    h@2:1709
    <unknown>@1007:2648
    h@2:1709
    <unknown>@576:334
    h@2:1709
    <unknown>@556:261
    h@2:1709
    <unknown>@554:1570
    h@2:1709
    <unknown>@553:704
    h@2:1709
    <unknown>@547:112
    h@2:1709
    <unknown>@546:364
    h@2:1709
    <unknown>@545:101
    h@2:1709
    <unknown>@541:73
    h@2:1709
    <unknown>@540:47
    h@2:1709
    <unknown>@384:154
    h@2:1709
    <unknown>@6:57
    h@2:1709
    d@2:1082
    global code@2403:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:923)

**Comment by 576** [comment]
这是来自QQ邮箱自动回复邮件.
您的邮件我已经收到，谢谢祝您愉快！！！

**Comment by 576** [comment]
这是来自QQ邮箱自动回复邮件.
您的邮件我已经收到，谢谢祝您愉快！！！

**Comment by Helen2hang** [comment]
The problem is because the babel.config was being looked for from the root of the project instead the mobile folder.
You have to make change the `root`  inside the `build.gradle` so that it enters in the mobile folder.

**Comment by richao03** [comment]
my issue turned out not not related to reanimated either, my azure task was pointing the working directory to our `android/wrapperAndroid/` directory instead of `android/`, this break happened when updating react-native from 0.68.5 to react-native 0.71.14, thank you @Helen2hang for pointing me in the right direction!!!

**Comment by JamesBondPc** [comment]
> The problem is because the babel.config was being looked for from the root of the project instead the mobile folder. To fix it, we changed the `root` parameter inside the `build.gradle` so that it enters in the mobile folder.

show code

**Comment by 576** [comment]
这是来自QQ邮箱自动回复邮件.
您的邮件我已经收到，谢谢祝您愉快！！！
