### ISSUE TITLE
Error: [Reanimated] `valueUnpacker` is not a worklet, js engine: hermes

### ISSUE THREAD

**Issue by andremelo97** [software-mansion/react-native-reanimated#5396]
### Description

I'm getting the error mentioned when I try to run my application as well as trying to re-build it. I tried following the orientations from the issue: [https://github.com/software-mansion/react-native-reanimated/issues/5209](url) - but none of it is working for me. I tried downgrading reanimated and react native multiple times for different versions and still nothing.

-----
My babel.config.js file is looking like this:

module.exports = {
  presets: [
  'module:metro-react-native-babel-preset',
  ],
  plugins: [
  "react-native-reanimated/plugin",
  ],
};

-----

The full log is:
 ERROR  Error: [Reanimated] `valueUnpacker` is not a worklet, js engine: hermes
 LOG  Running "app" with {"rootTag":191}
 ERROR  Invariant Violation: "app" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

----

My dependecies are:
"dependencies": {
    "@mdi/font": "^7.3.67",
    "@react-native-community/async-storage": "^1.12.1",
    "add": "^2.0.6",
    "immer": "^10.0.3",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "^0.72.7",
    "react-native-gesture-handler": "^2.13.4",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-paper": "^5.11.1",
    "react-native-reanimated": "^3.5.4",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-simple-modal": "^9.0.1",
    "react-native-vector-icons": "^10.0.2",
    "react-redux": "^8.1.3",
    "reactotron-react-native": "^5.0.3",
    "reactotron-redux": "^3.1.3",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "redux": "^4.2.1",
    "redux-saga": "^1.2.3",
    "styled-components": "^6.1.1",
    "yarn": "^1.22.21"

### Steps to reproduce

scripts:
"android": "react-native run-android && adb reverse tcp:8081 tcp:8081",
"start": "react-native start && adb reverse tcp:8081 tcp:8081 --reset-cache"

### Snack or a link to a repository

https://github.com/andremelo97/skedi

### Reanimated version

^3.5.4

### React Native version

^0.72.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

Real device

### Device model

moto e40

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@andremelo97 Did you reset Metro bundler cache using `yarn start --reset-cache` or `npm start -- --reset-cache`?

**Comment by andremelo97** [comment]
@tomekzaw Yes, I'm using yarn start --reset-cache and still does not work for me.

**Comment by andremelo97** [comment]
@tomekzaw Yes, I used this command again today after I reboot everything and apparently I'm receiving it anymore. Now the error doesn't say much is in the image below:

![Imagem do WhatsApp de 2023-11-23 à(s) 07 03 18_f31a406e](https://github.com/software-mansion/react-native-reanimated/assets/99205402/c61393e5-74c4-415c-a02d-b3a4c925201d)

I'm guessing it relates 'BottomSheet' from reanimated-bottom-sheet... Can you help me?

**Comment by jenskuhrjorgensen** [comment]
That lib seems pretty outdated (last release was in 2020). Maybe you should consider using react-native-bottom-sheet instead https://github.com/gorhom/react-native-bottom-sheet.
