### ISSUE TITLE
Animated.stagger counterpart in Reanimated

### ISSUE THREAD

**Issue by afeichuanqi** [software-mansion/react-native-reanimated#540]
Animated.stagger(250, [
            Animated.spring(this.translateY, {useNativeDriver, toValue: -50}),
            Animated.spring(this.translateY, {
                useNativeDriver,
                toValue: 1000,
            }),
        ]).start();
        Animated.timing(this.opacity, {
            useNativeDriver,
            toValue: 0,
            duration: 700,
            delay: 250,
        }).start(() => {
               // do something
        });

<-------------->
   I try  
<-------------->

        cond(clockRunning(clock), 0, [
            [
                set(state.finished, 0),
                set(state.time, 0),
                set(state.position, value),
                set(state.velocity, 30),
                set(config.toValue, -50),
                startClock(clock),
            ],
            cond(not(clockRunning(clock)), 0, [
                [
                    set(state.finished, 0),
                    set(state.time, 0),
                    set(state.position, value),
                    set(state.velocity, 30),
                    set(config.toValue, 1000),
                    startClock(clock),
                ],

            ])
        ]),
        spring(clock, state, config),
        cond(state.finished, debug('stop clock', stopClock(clock))),

How to connect the original API's three animation APIs so that he can execute them in sequence

**Comment by jakub-gonet** [comment]
Hi @afeichuanqi,

if you want to achieve the same effect as in `Animated.stagger` you can use thresholds which will run animation after some delay:

```js
const delay = 500; // some delay value

// out of block()
const delayed = new Value(0);

// in block()
cond(clockRunning(clock), 0, [
    // (...)
    cond(eq(delayed, 0), set(delayed, add(delay, clock)))
])

cond(greaterThan(clock, delayed), timing(clock, state, config)) // thing you want to run after delay
```

Does it answer your question?
