### ISSUE TITLE
Inverted Animated.FlatList behaves incorrectly on Android

### ISSUE THREAD

**Issue by jinliming2** [software-mansion/react-native-reanimated#5414]
### Description

I've encountered an issue with the `inverted` property of `Animated.FlatList` on Android. When I use this property, the output is mirrored, which is not the expected behaviour. This issue does not occur when using the native `FlatList`.

Here is a screenshot for reference: ![image](https://github.com/software-mansion/react-native-reanimated/assets/10294977/948ca7c2-f74b-47d1-a143-d2062e5595e0)

This issue has only been observed on Android, and I have not been able to reproduce it on iOS. The device I'm using is a Pixel 3XL running Android 12.

### Steps to reproduce

Add `inverted` property to `Animated.FlatList`.

### Snack or a link to a repository

https://snack.expo.dev/@jinliming2/reanimated-flatlist

### Reanimated version

^3.5.4

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Pixel 3XL (Android 12)

### Acknowledgements

Yes

**Comment by bartlomiejbloniarz** [comment]
Can you check if it works properly on 3.6.0. This issue should have been fixed by #5295.

**Comment by jinliming2** [comment]
This issue no longer reproduces in version 3.6.0.
