### ISSUE TITLE
[Android] ScrollView scrolls when translateY it using PanGestureHandler 

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#542]
I've been working on Instagram-like Pull-to-refresh animation using react-native-gesture-handler and react-native-reanimated.

Got a weird bug on Android: scroll view scrolls when you translate it using PanGestureHandler. This only happens on Android and only with reanimated. ReactNative's Animated works perfectly fine here.

Here is a video showing the issue (you can see scrollY value changes and prints into the console only on Android):
https://twitter.com/i/status/1216720811140227074

Here is the snack:
https://snack.expo.io/@terrysahaidak/reanimatedscrollviewtranslatebug

**Comment by jakub-gonet** [comment]
Hi @terrysahaidak, 
could you update the snack? It crashes with `_reactNativeReanimated.Value is not a constructor` error

**Comment by terrysahaidak** [comment]
Hi @jakub-gonet, thank you, I fixed the issue. Expo still used the old version without autoimport #325

**Comment by jakub-gonet** [comment]
Thanks, will look into that!

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request.
