### ISSUE TITLE
'ScrollTo' Method Blocks Component Updates in Flatlist Child

### ISSUE THREAD

**Issue by spagrhetti** [software-mansion/react-native-reanimated#5426]
### Description

I am trying to use React Native Reanimated's 'ScrollTo' method to create an automatic scrolling component. However, this component is used in a FlatList, and my problem is that I cannot interact with anything else inside of the Flatlist while the animation is running.

Here is an example of the behavior, outside and inside a FlatList:
![screen-recording](https://github.com/software-mansion/react-native-reanimated/assets/139802043/f95274f7-0b90-4bc1-b2ec-aea1862b02b7)

And here is a link to that Snack:

https://snack.expo.dev/@spagrhetti/react-reanimated-in-flatlist-child?platform=ios

I have tried debugging by playing around with the different parameters (the WithTiming and WithRepeat values), but nothing seems to change the behavior. I am relatively new to React Native Reanimated, so please let me know if I am misusing the library.

Additionally, here is a link to a SO post I made about the problem: https://stackoverflow.com/questions/77557565/react-native-reanimated-scrollto-blocks-component-updates-in-flatlist-child

Note: in the snack, the same behavior does NOT happen on web or Android, only iOS.

### Steps to reproduce

1. Make a component with an auto scrolling list using the 'scrollTo' method
2. In that component, also include a button with some kind of visual change on click
3. Test that the button updates when pressed while the list is scrolling
4. Now make a flatlist with a renderItem function that returns the list + button component
5. Try to click the button in the flatlist while the animation is running. It should no longer update.

### Snack or a link to a repository

https://snack.expo.dev/@spagrhetti/react-reanimated-in-flatlist-child?platform=ios

### Reanimated version

3.4.0

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

iOS simulator

### Device model

iPhone Xs

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! The problem is that your JS thread is busy doing
`scrollTo(aref, 0, currentScroll * (ITEM_SIZE + 2 * ITEM_MARGIN), false);`
Please notice that you have a separate call for each frame since you use `animated:false` and nothing is scheduled on UI.
Please try this: https://stackoverflow.com/questions/48179447/i-want-change-scrollview-rolling-speed-in-react-native
Generally you can't use `ScrollTo` for linear scrolling, this is for accelerated scroll, please use offset instead.

**Comment by spagrhetti** [comment]
@Latropos thank you so much! Your suggestion worked perfectly.
