### ISSUE TITLE
[3.6.0] [Reanimated] Couldn't load entering/exiting animation. Current version supports only predefined animations with modifiers: duration, delay, easing, randomizeDelay, wtihCallback, reducedMotion.

### ISSUE THREAD

**Issue by devoren** [software-mansion/react-native-reanimated#5429]
### Description

Hello! I updated to the latest version 3.6.0. Then I got this error:

<img width="746" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/99968085/29ee2ff1-ccc9-4eb0-8d26-222a949eccdb">

The problem is that when I used `entry/exit animations` before, I didn't have these problems, but no web animations. In my case I don't need web animation so I can't use reanimated without this error. What should I do? The animation works great in the native application!

### Steps to reproduce

1. Update reanimated to 3.6.0v
2. Create Animated Component
3. Add entering animation
4. Open web app

### Snack or a link to a repository

NA

### Reanimated version

3.6.0

### React Native version

0.72.6

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Device model

Chrome Browser

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @devoren, thanks for submitting this issue.

In Reanimated 3.6.0 we added basic support for Layout Animations on web. Previously, they were no-ops on web. Starting from 3.6.0 predefined Layout Animations like `FadeIn` or `SlideFromLeft` work also on web. However, we are still actively working on custom layout animations (i.e. defined by the user as a worklet).

The warning `Couldn't load entering/exiting animation` means that somewhere in your application code you use a layout animation which is not yet supported on web. You can easily disable this animation only for web and leave the original behavior on native with the following change:

```diff
 <Animated.View
-  entering={YourLayoutAnimation}
+  entering={Platform.OS === 'web' ? undefined : YourLayoutAnimation}
 />
```

**Comment by m-bert** [comment]
Hi @devoren! It seems that you're using custom animations that, as @tomekzaw said, aren't currently supported.

However, it is strange that your code breaks at reading `transform` from undefined - this part of code shouldn't be reached since failing function at the beginning has a check to ensure that the parameter is undefined. Could you please provide a small reproduction (or show us how you create animations)?

**Comment by devoren** [comment]
@m-bert I have Animated Pressable and i use custom entering: 
```
<AnimatedPressable
	style={[styles.container, props.style]}
	onPress={() => {
		if (props.onPress) {
			props.onPress();
		}
	}}
	layout={props.layout}
	entering={props.entering}
>...</AnimatedPressable>

const entering = (targetValues: EntryAnimationsValues) => {
'worklet';
const animations = {
	originX: withTiming(targetValues.targetOriginX, {
		duration: 350,
		reduceMotion: ReduceMotion.System,
	}),
	originY: withTiming(targetValues.targetOriginY, {
		duration: 350,
		reduceMotion: ReduceMotion.System,
	}),
	width: withTiming(targetValues.targetWidth, {
		duration: 350,
		reduceMotion: ReduceMotion.System,
	}),
};
const initialValues = {
	originX: scale.md,
	originY: referrer === 'catalog' ? scale.ml * 2 + insets.top : insets.top + scale.vl,
	width: targetValues.windowWidth - scale.ml,
};
return {
	initialValues,
	animations,
};
};
```

**Comment by devoren** [comment]
> ```diff
>  <Animated.View
> -  entering={YourLayoutAnimation}
> +  entering={Platform.OS === 'web' ? undefined : YourLayoutAnimation}
>  />
> ```

@m-bert After switching all entering to `Platform.OS === 'web' ? undefined : YourLayoutAnimation` now works without warning and error. But i have interesting behavior on web: 

native app:

https://github.com/software-mansion/react-native-reanimated/assets/99968085/d9a46434-f2ee-4998-9796-3fccfe522f38

web app:

https://github.com/software-mansion/react-native-reanimated/assets/99968085/82f355f5-28eb-4a3e-a3c5-30a48fd33a72


const AnimatedPressable = Animated.createAnimatedComponent(Pressable);

```
<View>
...

        // Back button
        <AnimatedPressable
	        style={styles.back}
	        onPress={goBack}
	        entering={FadeIn}
	        exiting={FadeOut}>
	        <View style={styles.icon}>
		        <Icons.ArrowLeft
			        color={colors.gray900}
			        width={scale.lg}
			        height={scale.lg}
		        />
	        </View>
        </AnimatedPressable>
	<Text style={styles.title}>
		Title
	</Text>
	<Pressable style={styles.close} onPress={closeBottomSheet}>
		<View style={styles.icon}>
			<Icons.Close
				color={colors.gray400}
				width={scale.lg}
				height={scale.lg}
			/>
		</View>
	</Pressable>
	...
   <BottomSheetScrollView
	style={{ flex: 1 }}
	contentContainerStyle={{ flexGrow: 1, position: 'relative' }}>
       
       // List with animation
	<Animated.View layout={SlideInRight} style={{ flex: 1 }}>
		{List}
	</Animated.View>
     </BottomSheetScrollView>
	...
</View>
```

Should I disable it for now on Web?

**Comment by m-bert** [comment]
>@m-bert After switching all entering to Platform.OS === 'web' ? undefined : YourLayoutAnimation now works without warning and error

Yes, it won't cause any error since those animations are not loaded. The thing is, I want to find out why you've got `cannot read properties of undefined` error.

> But i have interesting behavior on web:

Layout transitions are calculated when component changes its layout. On web we currently support 3 transitions - `linear`, `fading` and `sequenced`. Using predefined animation as layout transition won't work (at least for now).

**Comment by devoren** [comment]
@m-bert I found this error - `cannot read properties of undefined`:

i have a custom component: 

```
import React, { memo } from 'react';
import { Pressable, StyleProp, ViewStyle } from 'react-native';
import Animated, {
	BaseAnimationBuilder,
	EntryExitAnimationFunction,
} from 'react-native-reanimated';

const AnimatedPressable = Animated.createAnimatedComponent(Pressable);

interface HeaderBackButtonProps {
	style?: StyleProp<ViewStyle>;
	color?: string;
	onPress?: () => void;
	entering?:
		| BaseAnimationBuilder
		| typeof BaseAnimationBuilder
		| EntryExitAnimationFunction
		| undefined;
}

const HeaderBackButton: React.FC<HeaderBackButtonProps> = memo((props) => {
	return (
        <AnimatedPressable
	      style={[{ padding: scale.ss }, props.style]}
	      onPress={props.onPress }
	      entering={props.entering}>
	      <Icons.ArrowLeft
		      width={scale.lg}
		      height={scale.lg}
		      color={props.color ? props.color : colors.gray950}
	      />
        </AnimatedPressable>
	);
});

export default HeaderBackButton;

```

And i use it like this:

```
<HeaderBackButton
	entering={SlideInLeft.delay(0).duration(400).withInitialValues({
		originX: -50,
	})}
/>
```
If i remove entering it works fine

**Comment by m-bert** [comment]
Thanks for this code @devoren! Could you please check if [this PR](https://github.com/software-mansion/react-native-reanimated/pull/5449) helps?
