### ISSUE TITLE
useAnimatedProps doesnt update text props in TextInput

### ISSUE THREAD

**Issue by Rakha112** [software-mansion/react-native-reanimated#5432]
### Description

I tried to animate the text in the TextInput using useAnimatedProps, but the text didn't change at all even though the sharedValue changed as seen from the log, works fine on Reanimated v3.4.2, starts not working on v3.5.0 to v3.6.0, and I got a type error
```
Type 'Partial<{ text: string; }>' has no properties in common with type 'Partial<AnimatedPropsProp<TextInputProps>>'
```

<details>
  <summary>Full Code</summary>

```js
import {
  SafeAreaView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
} from 'react-native';
import React from 'react';
import Animated, {
  useAnimatedProps,
  useDerivedValue,
  useSharedValue,
} from 'react-native-reanimated';

const App = () => {
  const value = useSharedValue(0);
  const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

  const handlePress = () => {
    value.value = value.value + 1;
  };

  useDerivedValue(() => {
    console.log(value.value);
  }, []);

  const animatedText = useAnimatedProps(() => {
    return {
      text: `${value.value}`,
    };
  });

  return (
    <SafeAreaView style={styles.container}>
      <AnimatedTextInput
        style={styles.text}
        animatedProps={animatedText}
        editable={false}
        defaultValue={'0'}
      />
      <TouchableOpacity style={styles.button} onPress={handlePress}>
        <Text>PLUS</Text>
      </TouchableOpacity>
    </SafeAreaView>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    color: 'black',
    fontSize: 28,
    fontWeight: 'bold',
    margin: 10,
  },
  button: {
    backgroundColor: 'orange',
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 100,
  },
});
```

</details>

expected behavior

https://github.com/software-mansion/react-native-reanimated/assets/61527649/4caef774-d2fc-4f3d-8e9d-1f0bd75633aa

current behavior

https://github.com/software-mansion/react-native-reanimated/assets/61527649/2006ef7f-f7ae-4537-9f6e-8d26c71ba486

Thakyou!!

### Steps to reproduce

1. create AnimatedTextInput using `const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);`
2. create the animatedProps
```
  const animatedText = useAnimatedProps(() => {
    return {
      text: `${value.value}`,
    };
  });
```
3. add the animatedProps to AnimatedTextInput component
```
<AnimatedTextInput
        style={styles.text}
        animatedProps={animatedText}
        editable={false}
        defaultValue={'0'}
/>
```
4. Press the button

<details>
  <summary>Full Code</summary>

```js
import {
  SafeAreaView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
} from 'react-native';
import React from 'react';
import Animated, {
  useAnimatedProps,
  useDerivedValue,
  useSharedValue,
} from 'react-native-reanimated';

const App = () => {
  const value = useSharedValue(0);
  const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

  const handlePress = () => {
    value.value = value.value + 1;
  };

  useDerivedValue(() => {
    console.log(value.value);
  }, []);

  const animatedText = useAnimatedProps(() => {
    return {
      text: `${value.value}`,
    };
  });

  return (
    <SafeAreaView style={styles.container}>
      <AnimatedTextInput
        style={styles.text}
        animatedProps={animatedText}
        editable={false}
        defaultValue={'0'}
      />
      <TouchableOpacity style={styles.button} onPress={handlePress}>
        <Text>PLUS</Text>
      </TouchableOpacity>
    </SafeAreaView>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    color: 'black',
    fontSize: 28,
    fontWeight: 'bold',
    margin: 10,
  },
  button: {
    backgroundColor: 'orange',
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 100,
  },
});
```

</details>

### Snack or a link to a repository

https://github.com/Rakha112/useAnimatedProps-bug

### Reanimated version

3.6.0

### React Native version

0.72.7

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
I can confirm that your code works for older version of our library. I hope I'll find explanation of this soon.

**Comment by tomekzaw** [comment]
@Rakha112 You need to add the following line in your code:

```ts
Animated.addWhitelistedNativeProps({ text: true });
```

You can call it only once outside of the `App` component.

**Comment by Rakha112** [comment]
hello @Latropos @tomekzaw, I got error when adding that code
```js
Animated.addWhitelistedNativeProps({ text: true });
```
```js
Error: [Reanimated] Property `text` was whitelisted both as UI and native prop. Please remove it from one of the lists., js engine: hermes
```
<img width="357" alt="Screenshot 2023-11-30 at 07 28 12" src="https://github.com/software-mansion/react-native-reanimated/assets/61527649/b9b6ebd6-1859-423d-b940-bc44388c6676">

**Comment by tomekzaw** [comment]
Glad to hear that @Rakha112!

As for the type error, please follow this example from our repo: https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/CounterExample.tsx The types seem to work fine here.

**Comment by Rakha112** [comment]
> Glad to hear that @Rakha112!
> 
> As for the type error, please follow this example from our repo: https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/CounterExample.tsx The types seem to work fine here.

Hey @tomekzaw, adding defaultValue to the animatedProps fixes the type error
```js
const animatedText = useAnimatedProps(() => {
    return {
      text: `${value.value}`,
      defaultValue: `${value.value}`,
    };
  });
```
but in the example you gave before, if I delete defaultValue from the animatedProps, the same type error will appear
```js
Type 'Partial<{ text: string; }>' has no properties in common with type 'Partial<AnimatedPropsProp<TextInputProps>>'.ts(2559)
```

**Comment by Latropos** [comment]
Unfortunately it is not possible to give an ideal solution for this type error on our end.
We could create `Animated.TextInput` just like we have `Animated.FlatList`, but I am afraid it wouldn't be a good solution, since lots of users use TextInput from external libraries.

So please, just disable the warning an ignore it // @ts-ignore
cc @tjzel

**Comment by Rakha112** [comment]
Alright, thank you so much for your help and explanation @Latropos @tomekzaw

**Comment by Lobovem** [comment]
> > Glad to hear that @Rakha112!
> > As for the type error, please follow this example from our repo: https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/CounterExample.tsx The types seem to work fine here.
> 
> Hey @tomekzaw, adding defaultValue to the animatedProps fix the type error
> 
> ```js
> const animatedText = useAnimatedProps(() => {
>     return {
>       text: `${value.value}`,
>       defaultValue: `${value.value}`,
>     };
>   });
> ```
> 
> but in the example you gave before, if I remove the defaultValue from animatedProps, the same type error will appear
> 
> ```js
> Type 'Partial<{ text: string; }>' has no properties in common with type 'Partial<AnimatedPropsProp<TextInputProps>>'.ts(2559)
> ```

for me a way is work

**Comment by ucheNkadiCode** [comment]
Thank you once again @tomekzaw  - this worked for me I am now calling it at the beginning of my app initialization in App.tsx

```
Animated.addWhitelistedNativeProps({ text: true });
```

**Comment by Filip-Slepcev** [comment]
Hi I am running into a similar issue and have added the default value `Type 'Partial<{ text: string; defaultValue: string; }>' has no properties in common with type 'Partial<AnimatedPropsProp<TextProps>>'.ts(2559)
`

**Comment by Filip-Slepcev** [comment]
> Hi I am running into a similar issue and have added the default value `Type 'Partial<{ text: string; defaultValue: string; }>' has no properties in common with type 'Partial<AnimatedPropsProp<TextProps>>'.ts(2559) `

I seemed to have fixed the issue by casting the animatedProps with the type "any"
