### ISSUE TITLE
[Question] Is it possible to re-use the same animation using the start() api?

### ISSUE THREAD

**Issue by tomball123** [software-mansion/react-native-reanimated#544]
Hi,

Loving the performance improvements with react-native-reanimated.

I'm still trying to get a grasp on it and was wondering if someone could offer a solution to this.

Is it possible to re-use the start api on a timer for example, without getting the error message 'Animation has been finished before'.

```
constructor(props) {
    super(props);
    this.opacity = new Value(1);
    this.configOut = {
      toValue: 0,
      duration: 3000,
      easing: Easing.inOut(Easing.ease),
    };
    this.configIn = {
      toValue: 1,
      duration: 3000,
      easing: Easing.inOut(Easing.ease),
    };

    this.fadeIn = timing(this.opacity, this.configIn);
    this.fadeOut = timing(this.opacity, this.configOut);
  }
```

```
this._animationInterval = setInterval(() => {
    this.fadeOut.start(() => {
        this.setState({ titleText: someOtherTitleText }, () => {
          this.fadeIn.start();
        });
      });
    }, 3000);
```
This code works the first time, however 'Animation has been finished before' crops up when it tries to run again.

Apologies if i'm missing the point of the library and will be happy to be corrected! Using start() is just so convenient.

**Comment by tomball123** [comment]
Update, I got round the error by moving the animation definitions out of the constructor and in the timer, is this an acceptable way around?

```
this._animationInterval = setInterval(() => {
    const fadeIn = timing(this.opacity, this.configIn);     
    const fadeOut = timing(this.opacity, this.configOut);

    this.fadeOut.start(() => {
        this.setState({ titleText: someOtherTitleText }, () => {
          this.fadeIn.start();
        });
      });
    }, 3000);

**Comment by terrysahaidak** [comment]
Yeah, they're (Animated.timing.start and Reanimated's one) pretty much the same, but Animated will produce way less calls over the bridge, so in your particular example (animating opacity) it's better to use Animated or check out Reanimated's Transitions API.

**Comment by jakub-gonet** [comment]
It seems answered, so I'm closing it. If you have further concerns feel free to respond.
