### ISSUE TITLE
Cannot assign to read-only property 'validated'

### ISSUE THREAD

**Issue by KrisLau** [software-mansion/react-native-reanimated#5447]
### Description

Getting `TypeError: Cannot assign to read-only property 'validated'` in one of my components similar to https://github.com/software-mansion/react-native-reanimated/issues/4942. Commenting out the `prompt` from the component seems to get rid of the error but i have no clue why. It's annoying because i cant even downgrade the package because 3.1.0 doesn't work with RN0.72.

It doesn't recreate the error on the snack but i think it's because of bare React native and expo differences

### Steps to reproduce

1. RN v0.72.7 & react-native-reanimated v3.6.0
2. Use this component in a screen:
   ```jsx
    import React from 'react';
    import {Image, View} from 'react-native';
    import {Icon, Text} from '@rneui/themed';
    import PropTypes from 'prop-types';
    
    import {Colors} from '../../../styles';
    import styles from './styles';
    
    function ListEmpty({custom, listItemName, customMessage, prompt, containerStyle}) {
      return (
        <View style={[styles.container, containerStyle]}>
          <Image
            source={require('../../../assets/images/nothing-found.png')}
            style={{backgroundColor: 'transparent'}}
          />
          <Text h4>{custom ? `${customMessage}` : `No ${listItemName} added yet!`}</Text>
          {prompt} //this
        </View>
      );
    }
    
    ListEmpty.defaultProps = {
      custom: false,
      listItemName: 'events',
      customMessage: '',
      prompt: (
        <Text style={styles.prompt}>
          Tap the <Icon size={15} name={'pluscircle'} type={'antdesign'} color={Colors.SECONDARY} /> to
          get started
        </Text>
      ),
      containerStyle: {},
    };
    
    ListEmpty.propTypes = {
      custom: PropTypes.bool,
      listItemName: PropTypes.string,
      customMessage: PropTypes.string,
      prompt: PropTypes.element,
      containerStyle: PropTypes.object || PropTypes.any,
    };
    
    export default ListEmpty;
   ```
3. Navigate to the screen with the component and you should get the error 
4. Comment out `{prompt}` like this: `{/*{prompt}*/}` and the error disappears

### Snack or a link to a repository

https://snack.expo.dev/I44bwgWAQ

### Reanimated version

3.6.0

### React Native version

0.72.7

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 11 (16.4)

### Acknowledgements

Yes

**Comment by KrisLau** [comment]
welp not sure why but removing the prompt element and using `children` seemed to work

**Comment by tjzel** [comment]
I tried to reproduce the error you mention @KrisLau but I'm not getting any. You don't seem to be using `react-native-reanimated` actually. Could you provide a reproduction as a GitHub repo perhaps?

**Comment by KrisLau** [comment]
@tjzel I'll try and get one done but I might be a little slow cause we're working on a deployment rn

**Comment by tjzel** [comment]
No rush 😅

**Comment by ducpt-bili** [comment]
+1 for the issue on 3.6.1
I just follow the simple blog here.
https://dev.to/dimaportenko/collapsible-card-with-react-native-reanimated-495a
Note: i also have Moti for animation, and it had the same error when i trying not using directly reanimated.

**Comment by KrisLau** [comment]
@tjzel I figured it out! Basically had to pass in prompt as a child of the component instead of as a prop. Someone on the React Native discord helped me figure it out!

**Comment by Jon-edge** [comment]
@tjzel @ducpt-bili +1 on this issue. We currently do and may want to continue pass components as props for our org. Is there some future plans to allow support for this usage again in the future?

**Comment by tjzel** [comment]
@Jon-edge I don't exactly see how this is related to Reanimated.
