### ISSUE TITLE
useAnimatedProps does not update "value" props of animated textinput

### ISSUE THREAD

**Issue by renochew** [software-mansion/react-native-reanimated#5448]
### Description

I want to animated the text of a TextInput component, but reanimated doesn't seems to respond to the change of the "value" prop, so I look around some example code, it seems we should animate the "text" prop instead, which is not documented, it would be great if some one could explain to me the reason behind that.

Thank you.

### Steps to reproduce

This is what I did, and its not working:

  ```
const AnimProps = useAnimatedProps(() => {
    return {value: timeRemain.value.toString()};
  });
```

This is working:

  ```
const AnimProps = useAnimatedProps(() => {
    return {text: timeRemain.value.toString()};
  });
```

### Snack or a link to a repository

https://snack.expo.dev/@renochew/talking-orange-bananas

### Reanimated version

3.6

### React Native version

0.72.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hi @renochew, thanks for submitting this suggestion.

Here's what we can do:
1. Add an example on how to animate `<TextInput />` value to Reanimated docs 
2. Point to [CounterExample.tsx](https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/CounterExample.tsx) in our example app which makes use of this technique
3. Point to `<ReText />` component from `react-native-redash` (see [docs](https://wcandillon.gitbook.io/redash/strings)) which hides this complexity under the hood
4. Enable passing a shared value to `value` prop of `<Animated.TextInput />` directly

**Comment by renochew** [comment]
Hi @tomekzaw, thank you very much for taking the time to reply. I think that will do.

But ultimately I think animating text is such a fundamental thing that there should be a proper "Animated.Text" core component, using <TextInput/> seems more to be a workaround than anything as lining thing up is a pain, I am using "react-native-animateable-text" at the moment, but the owner already mentioned he don't have time to maintain it anymore. 

Will your team consider incorporate that repo to the core package?

Thanks again for the reply.

**Comment by tomekzaw** [comment]
@renochew Sure, this is exactly what I proposed in this tweet: https://twitter.com/tomekzaw_/status/1734178011149226086

**Comment by renochew** [comment]
Excellent! Thank you very much @tomekzaw  :)
