### ISSUE TITLE
addWhitelistedNativeProps  addWhitelistedUIProps are missing from documentation

### ISSUE THREAD

**Issue by owinter86** [software-mansion/react-native-reanimated#545]
addWhitelistedNativeProps is required if attempting to natively animate SVG values as discovered in this issue https://github.com/software-mansion/react-native-reanimated/issues/537, I do not believe that many people know about this and its likely due to the missing documentation.

**Comment by likern** [comment]
@owinter86 @jakub-gonet I see this method used in here https://github.com/gorhom/react-native-bottom-sheet/blob/v3/src/components/bottomSheet/BottomSheet.tsx

Are these methods required / applied for Reanimated V2?

Should we add it to documentation?

**Comment by jakub-gonet** [comment]
I believe it can be used in the v2, I'll prepare a PR.
