### ISSUE TITLE
[3.6.1] [Reanimated] TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by ranaavneet** [software-mansion/react-native-reanimated#5461]
### Description

Starting with Reanimated 3.6.0, if you try to do a setState for a view which has FastImage component created using createAnimatedComponent with a ref assigned, you get the following error

![Simulator Screenshot - iPhone 15 Pro Max - 2023-12-04 at 10 29 26](https://github.com/software-mansion/react-native-reanimated/assets/25902558/34289eec-0e94-4fe8-a1e5-15f8b9ffa3c7)

The PR which caused this issue is #4805

### Steps to reproduce

1. Create a animated FastImage component `const ReanimatedFastImage = Animated.createAnimatedComponent(FastImage)`
2. Create a ref for it `const cardImageRef = useRef<any>(null)`
3. Assign the ref to animatedComponent `<ReanimatedFastImage ref={cardImageRef} />`
4. onPress -> change the value of setState variable
5. You get the error _**Cannot red property 'getBoundingClientRect' of null**_

### Snack or a link to a repository
[https://github.com/ranaavneet/renanimated-fast-image-error](https://github.com/ranaavneet/renanimated-fast-image-error)

### Reanimated version

3.6.1

### React Native version

0.70.7

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

iOS simulator

### Device model

iPhone 15 Pro Max

### Acknowledgements

Yes

**Comment by ranaavneet** [comment]
Hi @m-bert , I found the exact reproducible. It happens when you use FastImage using createAnimatedComponent and assign it a ref.

Here is a repro for same:

`
import React, {useRef, useState} from 'react'
import {StyleSheet, Text, TouchableOpacity, View, ViewStyle} from 'react-native'
import Animated from "react-native-reanimated"
import FastImage from "react-native-fast-image"

export const ReanimatedFastImage = Animated.createAnimatedComponent(FastImage)
const App = () => {

  const [value, setValue] = useState(false)
  const cardImageRef = useRef<any>(null)

  const onPress = () => {
    setValue(!value)
  }

  return (
    <View style={styles.container}>
      <ReanimatedFastImage ref={cardImageRef} />
      {value ? <View /> : null}
      <TouchableOpacity onPress={onPress} style={styles.buttonStyle}>
        <Text>Toggle Set State</Text>
      </TouchableOpacity>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
    alignItems: 'center'
  } as ViewStyle,
  buttonStyle: {
    backgroundColor: 'grey',
    width: 200,
    height: 50,
    marginVertical: 20,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default App
`

**Comment by m-bert** [comment]
We do have plans to release 3.6.2 later this week. If you need this asap, you can use `patch-package`.
