### ISSUE TITLE
[BUG] animation inline styling doesn't work when component rerender

### ISSUE THREAD

**Issue by daehyeonmun2021** [software-mansion/react-native-reanimated#5466]
### Description

https://github.com/software-mansion/react-native-reanimated/assets/96194917/2922d052-7bff-4120-8989-6f15b4cce45d

Hi :) I really love using reanimated. Thanks for your great supports.

I just found out animation inline styling doesn't work when component rerenders.

In the code below, when you press the button, It looks like backgroundColor animation inline styling doesn't override but on mount phase it works well. (backgroundColor is just an example.)

You can reproduce it by following code:
```
import { useState } from 'react';
import { Text, TouchableOpacity, View } from 'react-native';
import Animated, { useSharedValue } from 'react-native-reanimated';

export const PlaygroundScreen = () => {
  const [state, setState] = useState({});
  const backgroundColor = useSharedValue('blue');

  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'gray',
      }}
    >
      <Animated.View
        style={[
          {
            width: 200,
            height: 200,
            backgroundColor: 'orange',
          },
          {
            backgroundColor,
          },
        ]}
      />
      <TouchableOpacity
        style={{
          position: 'absolute',
          bottom: 30,
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          width: '100%',
          height: 50,
          backgroundColor: 'blue',
        }}
        onPress={() => setState({})}
      >
        <Text
          style={{
            color: 'white',
            textAlign: 'center',
            fontWeight: 'bold',
            fontSize: 24,
          }}
        >
          Rerender
        </Text>
      </TouchableOpacity>
    </View>
  );
};

```

Thanks you :)

### Steps to reproduce

1. Add animation inline styling to your Animated.View
2. Rerender your component
3. As a result, animation Inline styling doesn't work !

### Snack or a link to a repository

.

### Reanimated version

3.6.1

### React Native version

0.72.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
Then usage of `useAnimatedStyle` is required, re-render won't reset or re-trigger the shared value.

**Comment by daehyeonmun2021** [comment]
@efstathiosntonas Yes we decided not to use animation inline styling till this issue is solved. We can make animations with useAnimatedStyle as u said. It looks like re-rendering breaks connection between ui and sharedValues passed as inline style.
