### ISSUE TITLE
React-native reanimated:  A problem occurred starting process 'command 'C:\mingw64\bin\cmake

### ISSUE THREAD

**Issue by Godknowsegi** [software-mansion/react-native-reanimated#5469]
### Description

ANDROID-STUDIO-SDK MANAGER-SETUP:

<img width="523" alt="Screenshot 2023-12-06 182241" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/05f27e42-c852-428c-9f1e-450efbaa59f6">

<img width="516" alt="Screenshot 2023-12-06 182301" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/28c4ba6a-eb27-4c5d-aa3c-879c75fc15b5">

<img width="527" alt="Screenshot 2023-12-06 182317" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/73e9c020-b5f9-4e25-9e1c-3bbb02f61c1f">

<img width="511" alt="Screenshot 2023-12-06 182342" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/99d4bf01-d765-4229-befe-7c43d29ee223">

<img width="496" alt="Screenshot 2023-12-06 182358" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/8db3c1b1-1053-4aee-8d41-e3d79a7217ed">

<img width="518" alt="Screenshot 2023-12-06 182440" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/a5ca56ac-5a14-493f-a2ca-b89a7d90e439">

<img width="521" alt="Screenshot 2023-12-06 182459" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/b5074534-ef19-4496-b37d-0e32cbba1032">

<img width="286" alt="Screenshot 2023-12-d06 182608" src="https://github.com/software-mansion/react-native-reanimated/assets/112111666/29e3928e-332d-4c85-9c46-144ec92d99b5">

PACKAGE-JSON:
<pre>
  {
  "name": "bbg",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.7",
    "react-native-reanimated": "^3.4.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}

</pre>

ERROR MESSAGE:
<pre>info Opening the app on Android...
info JS server already running.
info Installing the app...
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :gradle-plugin:inspectClassesForKotlinIC

> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> A problem occurred starting process 'command 'C:\mingw64\bin\cmake''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s</pre>
BUILD FAILED in 52s</pre>

### Steps to reproduce

STEPS :

`npx react-native  init bbg`

`yarn add  react-native-reanimated`

BABEL CONFIG:

<pre>module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
</pre>

`yarn start --reset-cache`

ERROR:
<pre>info Opening the app on Android...
info JS server already running.
info Installing the app...
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :gradle-plugin:inspectClassesForKotlinIC

> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> A problem occurred starting process 'command 'C:\mingw64\bin\cmake''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s</pre>

### Snack or a link to a repository

https://github.com/Godknowsegi/bbg-test

### Reanimated version

^3.4.2

### React Native version

0.72.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Dom000** [comment]
> Hey! 👋 
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?

I added a minimal reproduction link already

**Comment by tomekzaw** [comment]
@Godknowsegi Can you try running Android Studio as administrator?

**Comment by suhithas** [comment]
> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
25 actionable tasks: 2 executed, 23 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple build operations failed.
      Cannot snapshot output property 'outputDirectory'.
      Cannot snapshot output property 'outputDirectory'.
      Cannot snapshot output property 'outputDirectory'.
   > Cannot snapshot output property 'outputDirectory'.
   > Cannot snapshot output property 'outputDirectory'.
   > Cannot snapshot output property 'outputDirectory'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
error Failed to install the app.
