### ISSUE TITLE
> Task :react-native-reanimated:downloadDoubleConversion FAILED 

### ISSUE THREAD

**Issue by codewitharun** [software-mansion/react-native-reanimated#5478]
### Description

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:downloadDoubleConversion'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > de.undercouch.gradle.tasks.download.org.apache.hc.core5.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 7012573; received: 796890)

### Steps to reproduce

npx react-native run-android

### Snack or a link to a repository

nill

### Reanimated version

3.6.0

### React Native version

0.69.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
There was a connection error while downloading double-conversion.

> de.undercouch.gradle.tasks.download.org.apache.hc.core5.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 7012573; received: 796890)

Please build the app again.

**Comment by chuangdev** [comment]
Same Issue  https://github.com/software-mansion/react-native-reanimated/issues/3625


Check your local hosts file for any configurations related to GitHub's domain, and check your VPN available.

I solved the problem by removing the GitHub host from the host file
