### ISSUE TITLE
useAnimatedReaction unable to trigger scrollToOffset( ) method of a <Animated.FlatList>

### ISSUE THREAD

**Issue by renochew** [software-mansion/react-native-reanimated#5489]
### Description

Hi I want to use a changing SharedValue inside a useAnimatedReaction to trigger scrolling of a FlatList, but it doesn't seems to work.

### Steps to reproduce

In the snack provided, the useAnimatedReaction seems not doing anything. But in my actual test, I can see it successfully recognize the change in value (current!=previous), I can even logged the updated current value inside the block. But the  called to "scrollToOffset()" yield nothing.

### Snack or a link to a repository

https://snack.expo.dev/@renochew/1b23ef

### Reanimated version

3.6

### React Native version

0.72.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by renochew** [comment]
Maybe the reason is, "useAnimatedRef.current" is not defined in the UI thread? I tried to do it in JS thread instead. It seems "runOnJS" is not working at all inside the react function. 

EDIT: I updated the snack with relevant test code.

**Comment by Latropos** [comment]
@renochew Yes, you can't access this on UI thread.
You can move interval on JS thread to make it work, for example:
```
  const [counter, setCounter] = useState(0);

  useEffect(() => {
    console.log(counter);
    const interval = setInterval(() => {
      setCounter((x) => x + 1);
    }, 500);
    return () => clearInterval(interval);
  }, [counter]);

  useEffect(() => {
    refFlatList.current?.scrollToOffset({
      offset: counter * 20,
      animated: true,
    });
  }, [refFlatList, counter]);
```

**Comment by renochew** [comment]
Hi @Latropos , thanks for the reply, but then how do you do that we "useAnimatedReaction"? As I need to drive the scrollToOffset using a SharedValue inside useAnimatedReaction.

**Comment by Latropos** [comment]
Documentation: https://docs.swmansion.com/react-native-reanimated/docs/scroll/scrollTo

**Comment by renochew** [comment]
Hi @Latropos , thank you very much for the prompt reply. It looks very promising! I will try to impalement it in my actual code to see if it works. Also, if I put "runOnJS" inside the function, it doesn't called, do you think it is by design or a bug?

**Comment by Latropos** [comment]
It is by design, however if you don't get a valid warning message then it is also a bug.

**Comment by tomekzaw** [comment]
> Also, if I put "runOnJS" inside the function, it doesn't called, do you think it is by design or a bug?

How do you call it, `runOnJS(func)` or `runOnJS(func)()`?

**Comment by renochew** [comment]
Hi @tomekzaw, thanks for the reply again. Actually if I call say `runOnJS(console.log)('test');`

I get an error:
`ReanimatedError: Exception in HostFunction: [Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable., js engine: reanimated`

**Comment by tomekzaw** [comment]
@renochew `console.log` is an exception here, you can call it without `runOnJS`.

**Comment by renochew** [comment]
@tomekzaw, ah, that make sense. I think that answer all my questions. :) 

Thank you very much again.
