### ISSUE TITLE
useScrollViewOffset not updating value while scrolling on ios

### ISSUE THREAD

**Issue by top-kat** [software-mansion/react-native-reanimated#5494]
### Description

Not sure it is related to #4299 

On android values updates as we scroll, but on ios it only update on scroll start or end.

Just in case, here is the video screen shot on expo

https://github.com/software-mansion/react-native-reanimated/assets/17770809/05064921-5455-4e79-9afe-f912e3cc64ba

### Steps to reproduce

1. open snack

### Snack or a link to a repository

https://snack.expo.dev/@topkat/issue-4299-with-usescrollviewoffset-on-ios-

### Reanimated version

~3.3.0

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

None

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by bxvd** [comment]
Setting the `scrollEventThrottle` prop fixed this for me.

**Comment by top-kat** [comment]
@Latropos why closing this issue ? Should not it be at least in the doc or somewhere ? Actually, it not seem like the expected behavior.

**Comment by Latropos** [comment]
@top-kat Yes, you're right. However I believe that sb who will encounter this problem in the future would easily find this issue, so there is no need to include it in docs as well. WDYT?

**Comment by tomekzaw** [comment]
@top-kat This issue was resolved in PR #4589 which was released in Reanimated 3.4.0, however you're still on 3.3.0.

**Comment by top-kat** [comment]
@tomekzaw @Latropos So that's all fine, thanks for everything 👍
