### ISSUE TITLE
Animated.event can not use config

### ISSUE THREAD

**Issue by fwon** [software-mansion/react-native-reanimated#550]
https://github.com/software-mansion/react-native-reanimated/blob/master/src/core/AnimatedEvent.js#L81

**config** params is useless here, so the second param like "listener" cannot be used to do some handler

**Comment by curiousdustin** [comment]
Is there a workaround to add a `listener`?

**Comment by curiousdustin** [comment]
Does #531 fix this?

**Comment by SaveYourTime** [comment]
Same here, when trying to use the config like this...

```js
// pan is defined somewhere
const pan = useRef(new Animated.ValueXY()).current;

...

onPanResponderMove: Animated.event([null, { dx: pan.x, dy: pan.y }], {
      useNativeDriver: true,
      listener: (event, gestureState) => {
          console.log(pan.x._value);
      },
}),
```

<img width="400" alt="截圖 2020-04-15 上午11 32 42" src="https://user-images.githubusercontent.com/35715664/79296035-d64e1d00-7f0c-11ea-91f7-f602c5ef51d1.png">

**Comment by karltaylor** [comment]
I noticed this to. When I pass a `listener` to second paramater nothing would happen:

```js
<AnimatedFlatList
  keyExtractor={keyExtractor}
  scrollEventThrottle={1}
  onScroll={Animated.event(
    [
      {
        nativeEvent: {
          contentOffset: {
            y: scrollY
          }
        }
      }
    ],
    { listener: event => console.log(event) } // nothing logs
  )}
>
```

**Comment by edykim** [comment]
FYI https://github.com/software-mansion/react-native-reanimated/issues/67#issuecomment-545955795

**Comment by jakub-gonet** [comment]
As @edykim wrote, this can be solved by using `call` node. We recently released reanimated v2 which completely changes and simplifies doing animations, you may want to check it out.

**Comment by dangnguyen1004** [comment]
how to detect that the scroll event is close to bottom when using this approve
