### ISSUE TITLE
Fail to install pods react-native 0.72.3 - cocapods - 1.12

### ISSUE THREAD

**Issue by ShaulBenDavid** [software-mansion/react-native-reanimated#5509]
### Description

I try to install the library and I fail to install pods
![291495169-72b1bf11-0319-4541-96da-f9f8a6d9bca8](https://github.com/software-mansion/react-native-reanimated/assets/79593694/700f9810-c5d8-42aa-aa10-38ede92ff557)

### Steps to reproduce

1.npm i.react-native-reanimated 
2.adding to babel.config react-native-reanimated/plugin
3.cd ios && pod install
fail

### Snack or a link to a repository

private

### Reanimated version

3.6.1

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

all

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @ShaulBenDavid 
I can run app with reanimated, I use cocapods 1.14.2 and ruby 2.6.10
It looks to me like a corrupted podfile,
please see this discussion: https://github.com/facebook/react-native/issues/34979 as it may be helpful
