### ISSUE TITLE
Error: no type "Lcom/facebook/react/fabric/Binding;" found and so no field "mBinding" could be found in class (RN 0.73.1, Android, new arch + Reanimated 3.6.1, proguard enabled)

### ISSUE THREAD

**Issue by ahmetbicer** [software-mansion/react-native-reanimated#5514]
### Description

This is likely a side effect of the issue https://github.com/facebook/react-native/pull/41657. React Native 0.73.1 addressed that problem, but now I'm encountering the following error when Proguard is enabled. Everything works as expected when Proguard is disabled.

`Error: Exception in HostFunction: java.lang.NoSuchFieldError: no type "Lcom/facebook/react/fabric/Binding;" found and so no field "mBinding" could be found in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses`

### Steps to reproduce

1- Use the repro provided below.
2- Build and run a release build with yarn react-native run-android --mode Release

### Snack or a link to a repository

https://github.com/ahmetbicer/mBinding-proguard-repro

### Reanimated version

3.6.1

### React Native version

0.73.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Release app & production bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by migueldaipre** [comment]
Hey guys, you can add this in your **`proguard-rules.pro`** until a new patch release with the fix.

`-keep class com.facebook.react.fabric.** { *; }`

**Comment by indraprashad** [comment]
React native 0.76.3
Exception com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.NoSuchFieldError: no type "Lcom/facebook/react/fabric/Binding;" found and so no field "mBinding" could be found in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses, stack:
requireModule@1:76569
get@1:76633
anonymous@1:1248449
loadModuleImplementation@1:51859
guardedLoadModule@1:51383
metroRequire@1:51013
anonymous@1:1236000
loadModuleImplementation@1:51859
guardedLoadModule@1:51340
metroRequire@1:51013
NativeStackViewInner@1:1207888
renderWithHooks@1:118468
beginWork@1:135865
performUnitOfWork@1:153507
workLoopSync@1:152575
renderRootSync@1:152407
performConcurrentWorkOnRoot@1:149993
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (SourceFile:77)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (SourceFile:1)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2 (SourceFile:36)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl.b (SourceFile:1)
  at com.facebook.react.bridge.queue.b.run (SourceFile:1)
  at java.lang.Thread.run (Thread.java:920)

**Comment by benedict-pureweb** [comment]
Similar to @indraprashad, I'm facing this same issue after upgrading from 0.75.4 to react native 0.76.9.
As suggested, this proguard-rule does fix the issue: `-keep class com.facebook.react.fabric.** { *; }`
My question is why is this still an issue when it was already fixed in 0.73.1? Could I have made mistakes while upgrading react native? Everything else was working fine in 0.75.4.

**Comment by tomekzaw** [comment]
@benedict-pureweb We haven't heard about ProGuard issues recently so most likely this is some issue on your side.
