### ISSUE TITLE
App silently crashes after pressing "debug with chrome"

### ISSUE THREAD

**Issue by Brandon-Perry** [software-mansion/react-native-reanimated#5520]
### Description

My app crashes if I press Debug with Chrome without throwing any errors or anything. It just silently exits. 
If the app loads with debug already on however, it doesn't seem to be a problem.
Only tested on iOS simulator.
I'm also using M1 Mac.
Edit: Ran with Metro inside a x86_64 emulation and made no differnce

### Steps to reproduce

1. `npm install && cd ios && pod install` to install packages and pod files
2. `npm start --reset-cache` to start metro server
3. `npm run ios` to startup ios simulator
4. Open the app, shake, and press 'Debug with Chrome'
5. Everything works fine as expected.
6. Do 4 again and stop debugging
7. Go to App.tsx and comment back in the Animated.View component
8. Do 4 again.
9. App now crashes without any errors.

### Snack or a link to a repository

https://github.com/Brandon-Perry/reanimated_crash

### Reanimated version

3.6.1

### React Native version

0.72

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Brandon-Perry** [comment]
From XCode debugger, it looks like these two asserts in JSCRuntime is throwing the error. Commenting them out will let you temporarily avoid the problem.

```
JSCRuntime::~JSCRuntime() {
  // On shutting down and cleaning up: when JSC is actually torn down,
  // it calls JSC::Heap::lastChanceToFinalize internally which
  // finalizes anything left over.  But at this point,
  // JSValueUnprotect() can no longer be called.  We use an
  // atomic<bool> to avoid unsafe unprotects happening after shutdown
  // has started.
  ctxInvalid_ = true;
  JSGlobalContextRelease(ctx_);
#ifndef NDEBUG
  assert(
      objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object");
  assert(
      stringCounter_ == 0 && "JSCRuntime destroyed with a dangling API string");
#endif
}
```

**Comment by piaskowyk** [comment]
It interesting because Fabric on react-native@0.72 doesn't support remote chrom debugger 🤔
I tested it on Paper and it works:

https://github.com/software-mansion/react-native-reanimated/assets/36106620/aca7d393-aede-4122-8acc-ac6297fc0521

I can confirm that problem with `objectCounter_` exists on JSC. This is problem with JSC specific memory management, and destroying runtime after reload. At this moment commenting out those assertion is a best option. You can switch to Hermes engine - there is no such problem.

**Comment by piaskowyk** [comment]
This is issue is caused by this one - https://github.com/software-mansion/react-native-reanimated/issues/4783 so I close thi one, to keep conversation in one place
