### ISSUE TITLE
Exiting layout animation of the child component prevents removing parent until animation is finished

### ISSUE THREAD

**Issue by MatiPl01** [software-mansion/react-native-reanimated#5534]
#### Current behavior

When any of descendant components of the unmounted component use the `exiting` layout animation, the parent component will be rendered as long as the layout animation is being executed and will immediately disappear after the descendant is eventually removed from the screen.

What is even worse, all remaining children of the removed parent component will disappear immediately, but the parent and descendants with `exiting` layout animation will be visible.

#### Example recordings

You can see on the recording below that the white rectangle (the plain `View`) disappears immediately but the dark blue (`Animated.View` with `exiting` animation) is displayed until the animation finishes. Also the light blue parent component (plain `View`) is rendered as long as the exiting animation is executed.

| iOS | Android |
|-|-|
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/52978053/ac02bdf1-071b-4b75-88a0-d26884147440" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/52978053/c86b7cf0-d3ed-4156-91a4-e4c138e084c0" /> |

#### Expected behavior

All descendant component should disappear immediately when the parent component that has no `exiting` animation is removed.

#### Example from GitHub

1. Clone the https://github.com/MatiPl01/reanimated-issues repository:
```sh
git clone https://github.com/MatiPl01/reanimated-issues.git && cd reanimated-issues
```

2. Switch branch to the `exiting-layout-animation`:
```sh
git fetch && git switch exiting-layout-animation
```

3. Install dependencies and run the project
- iOS
```sh
yarn && yarn pod && yarn ios
```

- android
```sh
yarn && yarn android
```

#### Code snipped
Alternatively, you can copy-paste this code snippet

```tsx
import React from 'react';
import {useState} from 'react';
import {
  SafeAreaView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import Animated, {FadeOut} from 'react-native-reanimated';

function App(): JSX.Element {
  const [displayed, setDisplayed] = useState(true);

  return (
    <SafeAreaView>
      <View style={styles.container}>
        <TouchableOpacity
          style={styles.button}
          activeOpacity={0.75}
          onPress={() => {
            setDisplayed(!displayed);
          }}>
          <Text style={styles.buttonText}>{displayed ? 'Hide' : 'Show'}</Text>
        </TouchableOpacity>

        {displayed && (
          <View style={styles.parent}>
            {/* Animated child component with exiting animation */}
            <Animated.View style={styles.animatedChild} exiting={FadeOut} />
            {/* Another child component without exiting animation */}
            <View style={styles.anotherChild} />
          </View>
        )}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 20,
    gap: 20,
  },
  button: {
    backgroundColor: '#06196d',
    padding: 20,
    borderRadius: 10,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  parent: {
    height: 300,
    backgroundColor: '#96cae5',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  animatedChild: {
    width: 100,
    height: 100,
    backgroundColor: '#06196d',
    borderRadius: 10,
  },
  anotherChild: {
    width: 100,
    height: 100,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
});

export default App;
```

### Snack or a link to a repository

 https://github.com/MatiPl01/reanimated-issues 

### Reanimated version

3.6.1

### React Native version

0.71.13

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
@MatiPl01 Perhaps this is the answer to your issue?

https://docs.swmansion.com/react-native-reanimated/docs/layout-animations/layout-animation-config

**Comment by MatiPl01** [comment]
> https://docs.swmansion.com/react-native-reanimated/docs/layout-animations/layout-animation-config

I tried this before and it didn't work as expected. Maybe I've been doing something wrong as I works now with the `LayoutAnimationConfig`. Thank you for help.
