### ISSUE TITLE
Render Error - useAnimatedSensor - Cannot assign to read-only property "sensor" after rerender

### ISSUE THREAD

**Issue by net-runner** [software-mansion/react-native-reanimated#5538]
### Description

After the: https://www.youtube.com/watch?v=ExnJCyh-zVA 
useAnimatedSensor works fine with expo 49.

I wanted to use the useAnimatedSensor hook for animations in my app.
When using useAnimatedSensor for animations with react-native-reanimated, Render Error occurs if the screen containing the sensor is rerendered. 
Crash is reproducible on iOS and Android. On freshly created react-native or expo 50 beta app.

### Steps to reproduce
1. run the app
2. click the button to rerender.
### When not using example repository:
1. Create a npx react-native@latest init or expo yarn create expo-app --template blank@beta
4.  add reanimated - yarn add react-native-reanimated@3.6.1
5.  add "react-native-reanimated/plugin" to plugins to babel config
6.  add useAnimatedSensor combine it with useAnimatedStyle
```jsx  
const rotation = useAnimatedSensor(SensorType.ROTATION, {
    interval: 20,
  });

  const backgroundStyle = useAnimatedStyle(() => {
    const {roll, pitch} = rotation.sensor.value;
    return {
      transform: [
        {
          translateX: withSpring(-roll * 25, {
            damping: 200,
          }),
        },
        {
          translateY: withSpring(-pitch * 25, {
            damping: 200,
          }),
        },
      ],
    };
  });
```
7. Trigger rerender 

### Snack or a link to a repository

https://github.com/net-runner/rn-0.73.1-reanimated-useAnimatedSensor-onRerender-rerenderError-example

### Reanimated version

3.6.1 also 3.3.0 and 3.0.0

### React Native version

0.73.1

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

iPhone 12 - 17.2, Redmi Note 5 - Android 9

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @net-runner. When passing `useAnimatedSensor` return value to a worklet, you should currently be doing it granularly like this:

```ts
const { sensor } = useAnimatedSensor(SensorType.ROTATION, {
    interval: 20,
  });

  const backgroundStyle = useAnimatedStyle(() => {
    const {roll, pitch} = sensor.value;
    return {
      transform: [
        {
          translateX: withSpring(-roll * 25, {
            damping: 200,
          }),
        },
        {
          translateY: withSpring(-pitch * 25, {
            damping: 200,
          }),
        },
      ],
    };
  });
```

In #5537 we will decide if we want to keep this behavior or change it so destructuring wouldn't be necessary.
