### ISSUE TITLE
Suggest live example (for web) in the docs

### ISSUE THREAD

**Issue by mschipperheyn** [software-mansion/react-native-reanimated#554]
Live examples are a great way to "sell" people on a project.
Unfortunately, the docs site doesn't have them. I'm not sure if web support is on par with native functionality, but if it is, it would make sense to make the examples run inside the docs website.

**Comment by slorber** [comment]
agree, opened this issue: https://github.com/callstack/component-docs/issues/30

**Comment by jakub-gonet** [comment]
I'll try to tackle that when resolving #516, thought of using snacks, as web support for reanimated is kinda unstable.

**Comment by jakub-gonet** [comment]
It seems that I won't have any time to do that anytime soon and considering the release of v2 this may be outdated a little bit.

I'm closing it but I'll happily merge PR fixing that.
