### ISSUE TITLE
Cannot read property 'makeMutable' of undefined

### ISSUE THREAD

**Issue by thecodecafe** [software-mansion/react-native-reanimated#5545]
### Description

When I call `useSharedValue(0)` the app crashes with the following message.
```
Cannot read property 'makeMutable' of undefined
```

### Steps to reproduce

1. Run your app in development
2. Create a shared value with `useSharedValue(0)`

### Snack or a link to a repository

Private Repo

### Reanimated version

3.6.1

### React Native version

0.73.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @thecodecafe, I'm afraid we cannot help you without any reproduction. We use `useSharedValue` everywhere in our examples and never had this kind of error.

**Comment by Hamidrezana** [comment]
I have same problem

**Comment by Latropos** [comment]
Since there are more users facing the same problem I was trying to reproduce it independently and also failed. Looks that we really need a reproducible example.

**Comment by thecodecafe** [comment]
@Latropos thanks, I'll try and set up a fresh react native project with the same setup and put it on a public repo by Sunday, I'm currently travelling.

**Comment by Latropos** [comment]
@thecodecafe Hi! Were you able to reproduce this issue?

**Comment by thecodecafe** [comment]
Hi @Latropos sorry for the delayed response, a colleague of mine was able to find the problem, there's was a slight mistake when I was adding the plugin in the babel file due to nesting from another plugin, it was resolved by properly adding the plugin in the babel file.
I'll go ahead and close this because that was the solution to the problem.
Thanks for following up.

**Comment by keygun-development** [comment]
@thecodecafe I'm glad it has been resolved. I'm facing the same issue are you able to share your solution to this problem? It might help others aswell.

**Comment by ShepSims** [comment]
For others looking to resolve - this is what your babel.config.js should look like if using useSharedValue / reanimated

module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    /// This Plugin should be last
    'react-native-reanimated/plugin',
  ],
};

**Comment by pacehutt** [comment]
> Hi @Latropos sorry for the delayed response, a colleague of mine was able to find the problem, there's was a slight mistake when I was adding the plugin in the babel file due to nesting from another plugin, it was resolved by properly adding the plugin in the babel file. I'll go ahead and close this because that was the solution to the problem. Thanks for following up.

Could you share how it got fixed?

**Comment by GoygovRustam** [comment]
I'm having the same issue.

**Comment by SonBeoDeveloper** [comment]
I'm having the same issue.

**Comment by nhyu** [comment]
I solved this problem.（我解决了这个问题）

 react-native-reanimated-carousel 版本：3.5.1

这个问题是因为两个依赖库版本的问题，我从 react-native-reanimated-carousel 的 package.json 中发现依赖库版本并不是最新版本，所以用下面命令重新安装了这两个库。
`yarn add react-native-reanimated@~3.3.0 react-native-gesture-handler@~2.12.0`

安装完又按照下面文档进行了配置
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/

然后重启app错误就没有了。

**Comment by CarlosAlbertoTI** [comment]
I'm having the same issue.

**Comment by AdnanBadshah007** [comment]
i've faced the same issue i put plugin at last 
ex :-
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['nativewind/babel',
  [
    'module-resolver',
    {
      root: ['.'],
      extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
      alias: {
        '@screens': './screens',
        '@public': './public',
      },
    },
  ],
  'react-native-reanimated/plugin',
  ],
};

and then after i run a comman  npm start -- --reset-cache and its works

**Comment by Zontex** [comment]
> Since we haven't received any reproduction for this issue, I will close this issue. Feel free to ping me if you have a reproduction, preferably as a github repository. Only then will I reopen this issue.

module.exports = {
presets: ['module:@react-native/babel-preset'],
plugins: [
/// This Plugin should be last
'react-native-reanimated/plugin',
],
};

this solved the problem for me as well, adding 'react-native-reanimated/plugin', to babel file. on the previous RN version it wasn't required.

**Comment by deban07** [comment]
am getting the same issue in latest react native version.Have anyone reproduce the issue.

**Comment by KingAmo** [comment]
same here, and only happens in android, while ios is fine

**Comment by deban07** [comment]
> am getting the same issue in latest react native version.Have anyone reproduce the issue.

Now it solved by using "react-native-reanimated": "^3.12.0", and add *(plugins: ['react-native-reanimated/plugin']* on bable.config.js. 
Dont know the logic behind it but first run the ios and keep it on and then run the android.
In my case it is working.

**Comment by LGtuan** [comment]
I upgraded rn to 0.74.2

**Comment by mrityu-jha** [comment]
For me it got fixed by installing NativeWind v4 followed by `npm start --reset-cache` .

**Comment by Deepakvermaadequate** [comment]
For me it got fixed by `npm start --reset-cache` , mine was
 `"dependencies": {
    "@react-native-community/netinfo": "^11.4.1",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/native-stack": "^7.2.0",
    "moment": "^2.30.1",
    "react": "18.3.1",
    "react-native": "0.77.0",
    "react-native-gesture-handler": "^2.22.1",
    "react-native-reanimated": "^3.16.7",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "^5.1.0",
    "react-native-screens": "^4.5.0"
  },`

**Comment by pelivan** [comment]
Had the same error while updating to React Native 0.76 and new architecture.

Solved by running `bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install` in /`ios` folder.

**Comment by StockFish233** [comment]
> I'm getting this issue on `"react-native-reanimated": "3.17.5",` and `"react-native": "^0.79.2",`
> 
> <img alt="" width="270" src="https://private-user-images.githubusercontent.com/50201790/447687982-89b257cb-9dad-421e-8bf1-d78011f2f4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg0OTQyMjcsIm5iZiI6MTc0ODQ5MzkyNywicGF0aCI6Ii81MDIwMTc5MC80NDc2ODc5ODItODliMjU3Y2ItOWRhZC00MjFlLThiZjEtZDc4MDExZjJmNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTI5VDA0NDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjQ0Mjg1NTc2NWZiMmYzMzgxZTY1ZWYxZGMwMWEwMWZkZDhlZWFjNzMxNGI4YjA4ZWMyNjRhZTc1YTgwYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XbAOMKMWlPG5OoA77j61-ptqrxZyTES6uqxTcfA2an8">
> Not sure if I should open a new bug for this. I have tried downgrading to 3.16, but that didn't work, and I ended up with so many other bugs that you guys mentioned were fixed on the 3.17 version, so I'm stuck with this error, or no solution. Does anyone have any clues on how to solve this in the new architecture?

Me too. How did you finally solve it?

**Comment by MarlonAEC** [comment]
> > I'm getting this issue on `"react-native-reanimated": "3.17.5",` and `"react-native": "^0.79.2",`
> > <img alt="" width="270" src="https://private-user-images.githubusercontent.com/50201790/447687982-89b257cb-9dad-421e-8bf1-d78011f2f4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg0OTQyMjcsIm5iZiI6MTc0ODQ5MzkyNywicGF0aCI6Ii81MDIwMTc5MC80NDc2ODc5ODItODliMjU3Y2ItOWRhZC00MjFlLThiZjEtZDc4MDExZjJmNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTI5VDA0NDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjQ0Mjg1NTc2NWZiMmYzMzgxZTY1ZWYxZGMwMWEwMWZkZDhlZWFjNzMxNGI4YjA4ZWMyNjRhZTc1YTgwYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XbAOMKMWlPG5OoA77j61-ptqrxZyTES6uqxTcfA2an8">
> > Not sure if I should open a new bug for this. I have tried downgrading to 3.16, but that didn't work, and I ended up with so many other bugs that you guys mentioned were fixed on the 3.17 version, so I'm stuck with this error, or no solution. Does anyone have any clues on how to solve this in the new architecture?
> 
> Me too. How did you finally solve it?

At the end I ended up using reanimated 3.17.1 and react native 0.78.2 with new architecture enabled. That was the only combination that worked.
