### ISSUE TITLE
Examples are broken in docs

### ISSUE THREAD

**Issue by maxkrieger** [software-mansion/react-native-reanimated#5549]
### Description

In the latest versions of Chrome and Safari on MacOS, none of the examples animate.

Eg: https://docs.swmansion.com/react-native-reanimated/docs/animations/withSpring

### Steps to reproduce

Go to https://docs.swmansion.com/react-native-reanimated/docs/animations/withSpring, press the replay button.

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

3.6.1

### React Native version

0.73.1

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Release app & dev bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@maxkrieger Probably you have reduced motion setting enabled, that's why animations are disabled.

Maybe we should add a warning similar to the one from #5479 to the docs as well.

cc @bartlomiejbloniarz @kacperkapusciak

**Comment by Latropos** [comment]
I would rather suggest setting `ReduceMotion.Never` everywhere in docs.

**Comment by tomekzaw** [comment]
Sounds good but then we need to add `ReduceMotion.Never` to the actual code snippets.

Would be good to have some kind of a global switch for this :grief:

**Comment by bartlomiejbloniarz** [comment]
I don't think changing this globally makes sense, because in the current state users can see how reduced motion is implemented in reanimated. I would much rather have a warning.

**Comment by tjzel** [comment]
Me likes switch idea

**Comment by Latropos** [comment]
@tomekzaw @tjzel @bartlomiejbloniarz
After listening to all your suggestions I suppose that the first option, the warning, is the best one. I could implement it

**Comment by tjzel** [comment]
I didn't mean a switch to enable/disable it (however it would essentially be that) but instead a switch to show how it would look with `reduceMotion` enabled/disabled.

**Comment by bartlomiejbloniarz** [comment]
Such switch is already present in `withSpring` and `withTiming` playgrounds. I think we should add the warning first, but maybe allowing application users to override the system setting is a use case that makes the global override function in reanimated worth considering.

**Comment by Latropos** [comment]
@kacperkapusciak 
Should we use analogues banner to this warning we have for old verisons of reanimated?
<img width="1185" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/56199675/d6f7bfac-4028-4c0f-832f-026465f8e1e8">

**Comment by bartlomiejbloniarz** [comment]
@Latropos I think it would be nice if the user had a "don't show again" option

**Comment by maxkrieger** [comment]
Thanks for looking into this, all! I agree that reduceMotion should be surfaced explicitly, I only have it off on my system because a lot of native mac animations are annoying and slow.

**Comment by kacperkapusciak** [comment]
We should add a:

- tiny (one line of text)
- unobstructing (preferably at the top)
- dismissable (with a **x** button)

 yellow stip with a warining to each playground when user has ReducedMotion enabled in their system settings.
