### ISSUE TITLE
Worklets nested within objects throw error on update to RN 73, Reanimated 3.6.1

### ISSUE THREAD

**Issue by computerjazz** [software-mansion/react-native-reanimated#5555]
### Description

This may be an RNGH issue and not Reanimated, but posting here since the error is a reanimated error. I have a pan gesture that must register an `onTouchesMove` callback, but cannot do it inline and take advantage of the auto-workletizing that is documented here: https://docs.swmansion.com/react-native-gesture-handler/docs/#automatic-workletization-of-gesture-callbacks 

So, I am explicitly marking this method as `"worklet";`. In expo 49/react-native 0.72.3 and Reanimated 3.5.4 and RNGH 2.13.4 , the following code worked:

```ts
function Demo() {

  const panGesture = Gesture.Pan()
  
  panGesture.onTouchesMove((evt, mgr) => {
    'worklet'
    console.log('move!!')
  })

  return (
    <GestureHandlerRootView style={{ flex: 1, backgroundColor: 'seashell' }}>
      <GestureDetector gesture={panGesture}>
        <Animated.View style={{ flex: 1 }} />
      </GestureDetector>
    </GestureHandlerRootView>
  )
}
```

After upgrading to expo 50 and Reanimated 3.6.1 and RNGH 2.14.0 I see this error on pan:

```
Error: ENOENT: no such file or directory, open '/Users/REDACTED/installValueUnpacker'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (/Users/REDACTED/node_modules/metro/src/Server.js:927:18)
    at Server._symbolicate (/Users/REDACTED/node_modules/metro/src/Server.js:1010:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Server._processRequest (/Users/REDACTEDnode_modules/metro/src/Server.js:422:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/REDACTED/installValueUnpacker'
}
 ERROR  ReanimatedError: [Reanimated] Tried to synchronously call a non-worklet function on the UI thread.
See `https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-synchronously-call-a-non-worklet-function-on-the-ui-thread` for more details., js engine: reanimated

```

Note that only the `onTouchesX` callbacks trigger the error -- the workletized `onBegin` `onEnd` do not.
(something to do with handlers that set `config.needsPointerData = true`?)

I have tried resetting metro cache and `watchman watch-del-all`

Possibly related to https://github.com/software-mansion/react-native-reanimated/issues/5541

### Steps to reproduce

Run the above demo on: 
- expo 50.0.0-preview.7
- react-native 0.73.1
- RNGH 2.14.0

### Snack or a link to a repository

n/a, reanimated version not yet supported 

### Reanimated version

3.6.1

### React Native version

0.73.1

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by computerjazz** [comment]
Update: it appears that the issue is in calling `GestureStateManager.create()`

here: https://github.com/software-mansion/react-native-gesture-handler/blob/94c462b84a54125ecfd3897d4e1a1b334634632c/src/handlers/gestures/GestureDetector.tsx#L504


Is it possible that these functions are not properly worletized when nested within an object?
https://github.com/software-mansion/react-native-gesture-handler/blob/94c462b84a54125ecfd3897d4e1a1b334634632c/src/handlers/gestures/gestureStateManager.ts#L22

**Comment by computerjazz** [comment]
A reanimated-only example displaying the issue:

```tsx
import { useEffect } from 'react'
import { View } from 'react-native'
import Animated, { useAnimatedStyle, useSharedValue } from 'react-native-reanimated'

function rootLevelWorklet() {
  'worklet'
  console.log('root!')
  return 0.5
}

const MyObject = {
  nestedWorklet() {
    'worklet'
    console.log('nested!')
    return 1
  },
}

export default function Demo() {
  const myVal = useSharedValue(0)

  useEffect(() => {
    setTimeout(() => {
      // set myVal to 1 after 2 seconds to trigger bug within `useAnimatedStyle
      myVal.value = 1
    }, 2000)
  }, [myVal])

  const style = useAnimatedStyle(() => {
    return {
      width: 100,
      height: 100,
      backgroundColor: 'tomato',
      // the rootLevelWorklet works as expected, the nested worklet throws an error
      opacity: myVal.value < 0.5 ? rootLevelWorklet() : MyObject.nestedWorklet(),
    }
  }, [] )

  return (
    <View style={{ flex: 1 }}>
      <Animated.View style={style} />
    </View>
  )
}

```
![reanimated-nested-worklet-bug](https://github.com/software-mansion/react-native-reanimated/assets/6730148/8328ed59-b1ae-41d8-ac53-8dd8853d3eed)

**Comment by tsogzark** [comment]
I encountered the same error and [#2715](https://github.com/software-mansion/react-native-gesture-handler/pull/2715) not work for me.The following is the sample code from [here](https://medium.com/react-native-rocket/building-a-hand-drawing-app-with-react-native-skia-and-gesture-handler-9797f5f7b9b4)
```typescript
import React, { useState } from "react";
import { View } from "react-native";
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from "react-native-gesture-handler";
import { Canvas, Path } from "@shopify/react-native-skia";

interface IPath {
  segments: String[];
  color?: string;
}

export default function Draw() {
  const [paths, setPaths] = useState<IPath[]>([]);

  const pan = Gesture.Pan()
    .onStart((g) => {
      const newPaths = [...paths];
      newPaths[paths.length] = {
        segments: [],
        color: "#06d6a0",
      };
      newPaths[paths.length].segments.push(`M ${g.x} ${g.y}`);
      setPaths(newPaths);
    })
    .onUpdate((g) => {
      const index = paths.length - 1;
      const newPaths = [...paths];
      if (newPaths?.[index]?.segments) {
        newPaths[index].segments.push(`L ${g.x} ${g.y}`);
        setPaths(newPaths);
      }
    })
    .minDistance(1);

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <GestureDetector gesture={pan}>
        <View style={{ flex: 1, backgroundColor: "black" }}>
          <Canvas style={{ flex: 8 }}>
            {paths.map((p, index) => (
              <Path
                key={index}
                path={p.segments.join(" ")}
                strokeWidth={5}
                style="stroke"
                color={p.color}
              />
            ))}
          </Canvas>
        </View>
      </GestureDetector>
    </GestureHandlerRootView>
  );
}
```

**Comment by computerjazz** [comment]
@tsogzark that case may be different -- did it work pre-RN73/Reanimated 3.6.1?

If gesture callbacks are auto-workletized when defined inline with the gesture you may need to wrap your state setters in `runOnJS`, something like:
```ts
runOnJS(setPaths)(newPaths);
```

**Comment by tsogzark** [comment]
@computerjazz Thank you very much. I use runOnJS to wrap the callback in onStart and on Update and It is work well.
```typescript
    private pan = Gesture.Pan()
        .onStart(runOnJS((g) => {
            this.initTouchPayload = g;
            if (g.numberOfPointers === 1) {
                cardEditorModel.addPath({
                    segments: [`M ${g.x} ${g.y}`],
                    color: "#06d6a0",
                });
            }
        }))
        .onUpdate(runOnJS((g) => {
            if (g.numberOfPointers === 1 && this.initTouchPayload?.numberOfPointers === 1) {
                cardEditorModel.addSegToLastPath(`L ${g.x} ${g.y}`);
            }
        }))
        .minDistance(1);
```

**Comment by computerjazz** [comment]
Thanks for your help on this @j-piasecki , but I think this issue should be reopened. The RNGH issue was just one instance of a downstream effect due to breaking changes in worletization in Expo 50/RN73, which feels like a legitimate Reanimated issue.  

For example, this snack, which works on Expo 49, breaks when upgrading to expo 50 due to the same bug: https://snack.expo.dev/@easydan/reanimated-workletization-bug

Do we know what caused the breaking change in workletization in expo 50/RN 73?

**Comment by j-piasecki** [comment]
I didn't even realize that merging your PR would close the linked issue cross-repository 🤯

**Comment by computerjazz** [comment]
Doh, probably because I used `Fixes ###` syntax in my RNGH PR description. I shouldn't have added that since it doesn't fix this issue.

**Comment by piaskowyk** [comment]
I can confirm that it seems like something changed in babel in expo sdk 50. I tested in in plain React Native app and it works. Problem exists only in Expo SDK 50.

**Comment by piaskowyk** [comment]
@computerjazz Thanks for the report and well description! This is currently under investigation 🫡

**Comment by tjzel** [comment]
It was working before because it used to transform:

```ts
const MyObject = {
  nestedWorklet() {
    'worklet';
    console.log('nested!');
    return 1;
  },
};
```

into

```ts
var MyObject = {
  nestedWorklet: function nestedWorklet() {
    'worklet';

    console.log('nested!');
    return 1;
  },
};
```

and currently in the plugin we are not looking for `ObjectMethods` directly (which is a mistake). I will hotfix that but I don't know exactly how does this regression happen since when I transpile the file with `expo-babel-preset` used in Expo SDK 50 I get the same results as with Expo SDK 49.
