### ISSUE TITLE
react-native-reanimated V3.3.0 report "Incompatible Reanimated version(useValue not found)" 

### ISSUE THREAD

**Issue by SmileYang966** [software-mansion/react-native-reanimated#5559]
### Description

When I upgrade the expo to V49 , RN is "react-native": "0.72.6", the expo also updates the relevant dependencies versions , 
such as  "react-native-reanimated" changed from "~2.14.4" to "~3.3.0" 。
react-native-draggable-flatlist still was "react-native-draggable-flatlist": "^3.1.2" , not changed.

Then , I run the app , it report the error like below : 

![IMG_C92B636EF29F-1](https://github.com/software-mansion/react-native-reanimated/assets/39889153/284b403d-cd7e-423f-a06e-1a33d7cbed10)

Below is the package.json of react-native-draggable-flatlist
`
{
  "name": "react-native-draggable-flatlist",
  "version": "3.1.2",
  "description": "A drag-and-drop-enabled FlatList component for React Native",
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "scripts": {
    "test": "jest",
    "build": "tsc",
    "typecheck": "tsc --noEmit"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/computerjazz/react-native-draggable-flatlist.git"
  },
  "keywords": [
    "react-native",
    "sortable",
    "draggable",
    "flatlist",
    "drag",
    "drop",
    "sort",
    "list"
  ],
  "author": "Daniel Merrill",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/computerjazz/react-native-draggable-flatlist/issues"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ],
    "transform": {
      "^.+\\.[t|j]sx?$": "babel-jest"
    },
    "transformIgnorePatterns": []
  },
  "homepage": "https://github.com/computerjazz/react-native-draggable-flatlist#readme",
  "peerDependencies": {
    "react-native": ">=0.64.0",
    "react-native-gesture-handler": ">=1.10.0",
    **_"react-native-reanimated": ">=2.2.0"_**
  },
  "devDependencies": {
    "@testing-library/react-native": "^7.2.0",
    "@types/react": "^17.0.3",
    "@types/react-native": "^0.64.2",
    "babel-jest": "^26.6.3",
    "husky": "^4.2.0",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "pretty-quick": "^2.0.1",
    "react": "^17.0.2",
    "react-native": "^0.64.0",
    "react-native-gesture-handler": "^2.1.0",
    _**"react-native-reanimated": "^2.3.1",**_
    "react-test-renderer": "^17.0.2",
    "typescript": "^4.2.4"
  }
}
`

What should I do for this situation ? 

### Steps to reproduce

1. upgrade the expo to V49
2. updates the relevant dependencies versions , RN is "react-native": "0.72.6" ,  "react-native-reanimated" changed from "~2.14.4" to "~3.3.0" , react-native-draggable-flatlist still was "react-native-draggable-flatlist": "^3.1.2" , not changed.
3. when app launch ,the error appeared

### Snack or a link to a repository

https://github.com/

### Reanimated version

3.3.0

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

iphone7

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Reanimated 3 drops support for Reanimated v1 API (e.g. `useValue`).

You need to rewrite your code to Reanimated v2 API or stick with 2.x releases.

If you use `react-native-draggable-flatlist`, please try upgrading to 4.0.1.
