### ISSUE TITLE
Web layout animation fails to load on production mode

### ISSUE THREAD

**Issue by linhvovan29546** [software-mansion/react-native-reanimated#5561]
## Expected behavior: 
- The layout animation should work correct on production mode.
## Actual behavior:
- The layout animation is not working on production mode. 
-  The initAnimationName is set to `c` instead of the correct value.

<img width="808" alt="Screen Shot 2024-01-06 at 4 38 07 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/84692183/85ed9251-8bd6-4dd2-bbff-9ff6d085d966">
<img width="883" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/84692183/6283bbc1-1463-4ec4-847a-6c81f69dedd7">

### Steps to reproduce

1. Build the application with the production mode `npx expo export -p web`
2. Deploy app (netlify,...)
3. Open the application on a web browser and navigate to the page with the layout animation.
5. See result

### Snack or a link to a repository

https://snack.expo.dev/@vovanlinh29546/react-native-web-reanimated-layout-animation

### Reanimated version

3.6.1

### React Native version

0.72.3

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper

### Build type

Release app & production bundle

### Device

None

### Device model

None

### Acknowledgements

Yes

**Comment by linhvovan29546** [comment]
My solution is to create a className for the animation class https://github.com/software-mansion/react-native-reanimated/blob/4ad3a517d80f1680f9d9c8897f2211358bd142a6/src/reanimated2/layoutReanimation/defaultAnimations/Slide.ts#L335C23-L335C23
```
export class SlideOutDown extends ComplexAnimationBuilder implements IExitAnimationBuilder {
  className: string = 'SlideOutDown'; // Adding className property

  // ... existing code ...

}
```
<img width="809" alt="Screen Shot 2024-01-06 at 5 04 30 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/84692183/112ad4ce-29ca-4c62-849c-f6d02579657c">

**Comment by tomekzaw** [comment]
Thanks for reporting this issue! cc @m-bert

**Comment by m-bert** [comment]
Hi @linhvovan29546! Could you please check if [this PR](https://github.com/software-mansion/react-native-reanimated/pull/5562) fixes this issue?

**Comment by m-bert** [comment]
Indeed, it looks like it comes from another PR. I will merge mine and we will look into `style.viewRef.delete is not a Function` next.

cc @tjzel.

**Comment by tjzel** [comment]
Hotfix is in https://github.com/software-mansion/react-native-reanimated/pull/5578

**Comment by m-bert** [comment]
I'm closing this issue since both fixes have been merged. Feel free to open a new one if you find something else!
