### ISSUE TITLE
Reanimated Don't Work on Realese Version (.apk) Android 

### ISSUE THREAD

**Issue by djimi007** [software-mansion/react-native-reanimated#5579]
### Description

 **I'm using Reanimated in Expo and it works in the development build as expected but in build (.apk) it doesn't work.**

https://github.com/software-mansion/react-native-reanimated/assets/61278204/d51e596f-dac6-43a7-8305-0a6c1cfd2123

### Steps to reproduce

1.i use the docs code to test 
2.i checked the docs there is no extra steps to work with  reanimated

### Snack or a link to a repository

https://snack.expo.io/)

### Reanimated version

3.3.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

Redmi Note 9S (MIUI 14.0.3)

### Acknowledgements

Yes

**Comment by sonodima** [comment]
I am having a similar issue with Android release builds.
I have some components with animations when they are shown or hidden, and frequently on final Android builds these animations stop. The rest of the application is still working.

Expo: 49.0.21
RN: 0.72.6
Reanimated: 3.3.0

**Comment by djimi007** [comment]
> I am having a similar issue with Android release builds. I have some components with animations when they are shown or hidden, and frequently on final Android builds these animations stop. The rest of the application is still working.
> 
> Expo: 49.0.21 RN: 0.72.6 Reanimated: 3.3.0

i updated react-native to latest version and it's fixed i noticed that when i was writing this issue that 3.3.0 it's not the latest version 3.6.1 is the latest 
run 'npm i react-native-reanimated@latest' and prebuild and you'll be ok good luck

**Comment by djimi007** [comment]
i update react-native-reanimated to the latest version and it's work in version 3.6.1 
run npm i react-native-reanimated@latest 
good luck to everyone

**Comment by sonodima** [comment]
> i update react-native-reanimated to the latest version and it's work in version 3.6.1 run npm i react-native-reanimated@latest good luck to everyone

That's great and has worked for me, thank you! 👍

**Comment by Latropos** [comment]
I am very happy that updating solves the problem. I assume I can close this issue now.

**Comment by Code-Victor** [comment]
@Latropos , did you also update your expo version? I'm asking because I'm getting with warning
```bash
Some dependencies are incompatible with the installed expo version:
  react-native-reanimated@3.6.2 - expected version: ~3.3.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
```

**Comment by djimi007** [comment]
@Code-Victor yes i updated expo version
