### ISSUE TITLE
exception thrown while executing ui block 'parentnode' is a required parameter

### ISSUE THREAD

**Issue by levinhky** [software-mansion/react-native-reanimated#5596]
### Description

![image](https://github.com/software-mansion/react-native-reanimated/assets/82246828/f25373ef-3273-4258-928e-b1f5e299a5ab)

can you guys please give me some solution to fix that 

### Steps to reproduce

Open app 
click on checkout
click go back
close app
open again
then error show but if dismiss it, functional working normally but text on checkout page disapeared

### Snack or a link to a repository

private

### Reanimated version

2.2.3

### React Native version

0.64.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

IOS 17

### Acknowledgements

Yes

**Comment by levinhky** [comment]
> Hey! 👋
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?

that's private

**Comment by piaskowyk** [comment]
Hey, I'm think that upgrade if Reanimated will help you. The current version (2.2.3) is quite old, and we have dropped support for Reanimated 2 since the release of version 3. You can safely use version 2.17.0, which can be found at this link: [react-native-reanimated v2.17.0](https://www.npmjs.com/package/react-native-reanimated/v/2.17.0).

**Comment by levinhky** [comment]
> Hey, I'm think that upgrade if Reanimated will help you. The current version (2.2.3) is quite old, and we have dropped support for Reanimated 2 since the release of version 3. You can safely use version 2.17.0, which can be found at this link: [react-native-reanimated v2.17.0](https://www.npmjs.com/package/react-native-reanimated/v/2.17.0).

I has upgrade to 2.17.0 and it still error

**Comment by piaskowyk** [comment]
Without any reproduction I can't help :/

**Comment by levinhky** [comment]
https://github.com/software-mansion/react-native-reanimated/assets/82246828/fe26c4f8-1008-4428-918a-ee8162c58cc8

here's the case it's on live so it not showing error but when click go back it show exception like issue title
