### ISSUE TITLE
Build Failed Expo Sdk 50

### ISSUE THREAD

**Issue by djimi007** [software-mansion/react-native-reanimated#5600]
### Description

**### > Task :react-native-reanimated:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.**

* What went wrong:
Execution failed for task ':react-native-reanimated:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-reanimated:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\Djimi\AppData\Local\Android\Sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Eclipse Adoptium\jdk-21.0.2.13-hotspot\bin\jlink.exe with arguments {--module-path C:\Users\Djimi\.gradle\caches\transforms-3\7df6c81b81c170b35586e4d612b7a488\transformed\output\temp\jmod --add-modules java.base --output C:\Users\Djimi\.gradle\caches\transforms-3\7df6c81b81c170b35586e4d612b7a488\transformed\output\jdkImage --disable-plugin system-modules}

### Steps to reproduce

i tried to change jdk versions i tested jdk (21/20/17/11)

### Snack or a link to a repository

https://snack.expo.io/)

### Reanimated version

3.6.1

### React Native version

0.73.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

Redmi Note 9S (MIUI 14.0.3)

### Acknowledgements

Yes

**Comment by sawako094** [comment]
Same here!

**Comment by ThusSpokeNomad** [comment]
FWIW, the solution for me was to install JDK 17 specifically — I had JDK 21 and downgraded to JDK 17 and things went perfectly from there.

https://docs.expo.dev/guides/local-app-development/#prerequisites

**Comment by FelipeVa** [comment]
> FWIW, the solution for me was to install JDK 17 specifically — I had JDK 21 and downgraded to JDK 17 and things went perfectly from there.
> 
> https://docs.expo.dev/guides/local-app-development/#prerequisites

This worked. I had the same issue but additionally with `react-native-async-storage/async-storage`.

**Comment by sawako094** [comment]
> FWIW, the solution for me was to install JDK 17 specifically — I had JDK 21 and downgraded to JDK 17 and things went perfectly from there.
> 
> https://docs.expo.dev/guides/local-app-development/#prerequisites

@ThusSpokeNomad you saved me! Thank you, I downgraded from JDK 21 to JDK 17 and now builds successfully

**Comment by puopg** [comment]
For anyone who needs to downgrade, and you for some reason have JDK 21. Just 
```
rm -rf /Library/Java/JavaVirtualMachines/jdk-21.jdk
```

or something. Literally i was like how the fk do I downgrade this thing, and just removed it and boom now the android app is building again.

**Comment by kiewfenix** [comment]
> FWIW, the solution for me was to install JDK 17 specifically — I had JDK 21 and downgraded to JDK 17 and things went perfectly from there.
> 
> https://docs.expo.dev/guides/local-app-development/#prerequisites

That works great, but it's so stupid that we need to use specific version of jdk for 'expo' :)
