### ISSUE TITLE
[Reanimated] Couldn't determine the version of the native part of Reanimated. - Expo SDK 50

### ISSUE THREAD

**Issue by alan-hadyk** [software-mansion/react-native-reanimated#5602]
### Description

It seems that there's an issue with `react-native-reanimated` in Expo SDK 50 (`50.0.2`). Whenever I start Expo with `expo start`, there's a warning:

```
 WARN  [Reanimated] Couldn't determine the version of the native part of Reanimated.
    See `https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#couldnt-determine-the-version-of-the-native-part-of-reanimated` for more details.
    at ContextNavigator (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:152328:24)
    at ExpoRoot (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:152284:28)
    at App
    at ErrorToastContainer (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:189104:24)
    at ErrorOverlay
    at withDevTools(ErrorOverlay) (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:188638:27)
    at RCTView
    at View (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:40740:43)
    at RCTView
    at View (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:40740:43)
    at AppContainer (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:40551:36)
    at main(RootComponent) (http://192.168.1.45:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:124397:28)
```

### Steps to reproduce

1. Create new Expo project with `npx create-expo-app --template`
2. Select `Navigation (TypeScript)` template
3. `cd` into project
4. Delete `package-lock.json` and `node_modules`
5. `yarn install`
6. Install React Native Reanimated - `npx expo install react-native-reanimated`
7. Add `'react-native-reanimated/plugin'` to `babel.config.js`
8. Add the following JSX to `components/EditScreenInfo.tsx`:
```
import Animated from 'react-native-reanimated';

<Animated.View
      style={{
        width: 100,
        height: 100,
        backgroundColor: 'violet',
      }}
    />
```
9. Run the app with `yarn start`

### Snack or a link to a repository

https://github.com/alan-hadyk/reanimated-expo-bug

### Reanimated version

3.6.0

### React Native version

0.73.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

iPhone 15 Pro (iOS 17.2)

### Acknowledgements

Yes

**Comment by wodin** [comment]
See also:
https://github.com/expo/expo/issues/26534

**Comment by jamesedmonston** [comment]
I'm seeing similar, but mine seems to fully throw. Weirdly the versions log okay, but it errors when trying to access: `const babelVersion = value.__initData.version;`

<img width="1498" alt="Screenshot 2024-01-21 at 19 14 32" src="https://github.com/software-mansion/react-native-reanimated/assets/4851924/dc0a23d1-7d68-40c9-8b4e-7d6e00e486b1">

**Comment by rohitverma-dev29** [comment]
Experiencing same issue

**Comment by rhh4x0r** [comment]
Same here.

**Comment by Kief5555** [comment]
Having the same issue - for anyone that wants to silence it (within expo go) you can import `LogBox` from RN and `LogBox.ignoreLogs(['Reanimated']);`

**Comment by vitaliyhan** [comment]
same.

**Comment by EbubekirYucel** [comment]
same issues after the update expo 50 sdk

**Comment by johnbindel** [comment]
Same after expo 50 upgrade

**Comment by jeokeefe** [comment]
same here after upgrade from 49 to 50.0.2

**Comment by cmalescov** [comment]
Same problem here, upgrading to expo sdk 50.0.2, reanimated 3.6.0

**Comment by pluckyhd** [comment]
Seeing this as well although expo-doctor reports nothing wrong

**Comment by phillippschmedt** [comment]
Same

**Comment by pluckyhd** [comment]
Ok I was able to fix for some reason my app.json somewhere i had added 

`  "expo": {
    "install": {
      "exclude": [
        "react-native-reanimated"
      ]
    }
  },`

Removing this and running -fix again allowed the correct reanimate library to be installed. I don't remember why I added that but maybe others did as well.

**Comment by lautenschlager-dev** [comment]
Same issue. I do not have ` "expo": { "install": { "exclude": [ "react-native-reanimated" ] } },` in my app config

**Comment by katvengo** [comment]
I'm facing the same issue using Expo SDK 50 with React Native 0.73. 

Would like to see this fixed so we don't get the warning anymore.

**Comment by AlejandroRM-DEV** [comment]
Same problem here

**Comment by cyberkaidev** [comment]
Same problem

**Comment by wodin** [comment]
> I tried adding in the following to my app.json but it didn't fix my issue.
> 
> ` "expo": { "install": { "exclude": [ "react-native-reanimated" ] } },`

That would *not* fix the issue. Rather remove it, or it could cause other issues down the line.

The above just tells `expo-doctor` not to complain if you install a version of `react-native-reanimated` that is different to the expected version for the version of the Expo SDK

**Comment by wodin** [comment]
Please, instead of adding a comment to say "Same problem", rather just add a thumbs up to the first comment.

**Comment by PrithirajTalukder** [comment]
same problem

**Comment by nemanjamitric** [comment]
Update. Now I can't combine stack and drawer navigation like before, so I removed stack, but then react native elements <Icon /> component stopped working. All in all I suggest sticking to Expo 49 for a while longer.

**Comment by piaskowyk** [comment]
You can use the newest patch version - https://www.npmjs.com/package/react-native-reanimated/v/3.6.2 We removed this warning.

**Comment by Curtis-iac** [comment]
Had this same issue after upgrading to SDK 50. 

**Resolved by running:**

npm i expo@latest
npm i react-native-reanimated@latest

**Comment by ReeceKenney** [comment]
I solved my issue by upgrading to `react-native-reanimated: "~3.6.2"`. 

I also ran `npx expo start --clear` to clear the cache but I don't know if this was necessary or not. 

After that, my project runs as normal again
