### ISSUE TITLE
Reanimated withRepeat animation stops on updating some props

### ISSUE THREAD

**Issue by t0ms0n00** [software-mansion/react-native-reanimated#5604]
### Description

When we're having animation that runs all the time and we're changing any style in another RN component, the animation stops.

### Steps to reproduce

```js
import Animated, {
  useAnimatedProps,
  useSharedValue,
  withRepeat,
  withTiming,
} from 'react-native-reanimated';
import {Circle, Svg} from 'react-native-svg';
import {StyleSheet, View, TouchableOpacity} from 'react-native';
import React from 'react';

const AnimatedCircle = Animated.createAnimatedComponent(Circle);

Animated.addWhitelistedNativeProps({r: true});

export default function SvgExample() {
  const sv = useSharedValue(0);

  sv.value = withRepeat(withTiming(1, {duration: 500}), -1, true);

  const animatedProps = useAnimatedProps(() => {
    return {
      r: `${1 + sv.value * 49}%`,
    };
  });

  return (
    <>
      <View style={styles.container}>
        <Svg height="200" width="200">
          <AnimatedCircle
            cx="50%"
            cy="50%"
            fill="lime"
            animatedProps={animatedProps}
          />
        </Svg>
      </View>
      <TouchableOpacity style={styles.box} />
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    backgroundColor: 'red', // change the value here and the animation should freeze
    height: 200,
  },
});
```

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/SvgExample.tsx

### Reanimated version

3.6.0

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @t0ms0n00!
This is because of the way fast refresh works: https://reactnative.dev/docs/fast-refresh#limitations

If you don't like this behaviour please add comment `// @refresh reset` anywhere in you file.
