### ISSUE TITLE
☔️ Regression in 1.6.0 / 1.5.0 

### ISSUE THREAD

**Issue by osdnk** [software-mansion/react-native-reanimated#561]
I have released a 1.6.0 version yesterday. It was containing a lot of small changes and updates and unfortunately brought few regressions. I want to get rid of them as soon as I can collecting feedback from the community.

Here's a list of issues I'm conscious about: 

1. https://github.com/software-mansion/react-native-reanimated/issues/551 fixed  by https://github.com/software-mansion/react-native-reanimated/issues/551
2. #559 fixed by https://github.com/software-mansion/react-native-reanimated/pull/560
3. https://github.com/software-mansion/react-native-reanimated/issues/557#issuecomment-575009400 fixed by https://github.com/software-mansion/react-native-reanimated/pull/566
4. https://github.com/software-mansion/react-native-reanimated/issues/558 fixed by #562
5. https://github.com/software-mansion/react-native-reanimated/issues/555 fixed by (#568) 
6. https://github.com/software-mansion/react-native-reanimated/issues/563 fixed by https://github.com/software-mansion/react-native-reanimated/pull/564

Also, I want to include https://github.com/software-mansion/react-native-reanimated/pull/556 in order to verify reanimated with a complex example

**Comment by Jarred-Sumner** [comment]
Flagging this comment incase it was missed: https://github.com/software-mansion/react-native-reanimated/commit/bdc7b5962a8fec49230446a21c1f739c98b8effa#commitcomment-36633385

It’s probably too vague to be actionable though

**Comment by osdnk** [comment]
All issues should be gone
