### ISSUE TITLE
Exception in HostFunction: java.lang.unsatisfiedLinkError: dlopen failed: library "libreanimated.so" not found

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion/react-native-reanimated#5613]
### Description

i have updated from react-native 71 to 73 and reanimated 3.5.4 to 3.6.2, although release version works, debug version doesn't work.

![Screenshot_1706599510](https://github.com/software-mansion/react-native-reanimated/assets/45505767/2bdf25ad-f632-41c6-bf43-e3fe63bb4aa0)

### Steps to reproduce

update react-native to 73 and reanimated to 3.6.2.  also 3.6.1 and 3.5.4 doesn't work

### Snack or a link to a repository

https://snack.expo.dev/

### Reanimated version

3.6.2

### React Native version

0.73.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by migueldaipre** [comment]
Please add a minimal reproducer

**Comment by hosseinmd** [comment]
It was about compiler, I am using repack.

**Comment by SounakB** [comment]
@hosseinmd can you please elaborate what solved this issue, I am getting it now

**Comment by hosseinmd** [comment]
Repack new version fixed this issue.

**Comment by SounakB** [comment]
I am not using repack or expo, jus plain react native but still facing this issue
Here is the package.json contents
```JSON
"dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.3",
    "react-native-reanimated": "^3.6.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.20",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.4",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
```

Any help is appreciated @hosseinmd @migueldaipre

**Comment by migueldaipre** [comment]
> I am not using repack or expo, jus plain react native but still facing this issue Here is the package.json contents
> 
> ```json
> "dependencies": {
>     "react": "18.2.0",
>     "react-native": "0.73.3",
>     "react-native-reanimated": "^3.6.2"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.20.0",
>     "@babel/preset-env": "^7.20.0",
>     "@babel/runtime": "^7.20.0",
>     "@react-native/babel-preset": "0.73.20",
>     "@react-native/eslint-config": "0.73.2",
>     "@react-native/metro-config": "0.73.4",
>     "@react-native/typescript-config": "0.73.1",
>     "@types/react": "^18.2.6",
>     "@types/react-test-renderer": "^18.0.0",
>     "babel-jest": "^29.6.3",
>     "eslint": "^8.19.0",
>     "jest": "^29.6.3",
>     "prettier": "2.8.8",
>     "react-test-renderer": "18.2.0",
>     "typescript": "5.0.4"
>   },
>   "engines": {
>     "node": ">=18"
>   }
> ```
> 
> Any help is appreciated @hosseinmd @migueldaipre

Can you add a github repro?

**Comment by SounakB** [comment]
@migueldaipre I have added it here https://github.com/software-mansion/react-native-reanimated/issues/5625

**Comment by hhimanshii108** [comment]
Im still facing this issue

"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.6.0",
    "@fortawesome/free-brands-svg-icons": "^6.6.0",
    "@fortawesome/free-regular-svg-icons": "^6.6.0",
    "@fortawesome/free-solid-svg-icons": "^6.6.0",
    "@fortawesome/react-native-fontawesome": "^0.3.2",
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-native-cookies/cookies": "^6.2.1",
    "@react-native-google-signin/google-signin": "^13.1.0",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@reduxjs/toolkit": "^2.3.0",
    "axios": "^1.7.7",
    "hugeicons-react-native": "^0.0.2",
    "nativewind": "^2.0.11",
    "react": "18.3.1",
    "react-native": "0.75.4",
    "react-native-gesture-handler": "^2.20.0",
    "react-native-reanimated": "^3.15.5",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-safe-area-context": "^4.11.0",
    "react-native-screens": "^3.27.0",
    "react-native-size-matters": "^0.4.2",
    "react-native-svg": "^15.8.0",
    "react-native-toast-message": "^2.2.1",
    "react-native-vector-icons": "^10.2.0",
    "react-native-video": "^6.7.0",
    "react-redux": "^9.1.2"
  },
