### ISSUE TITLE
Nightly version errors on supportsLocking_ when building release & staging

### ISSUE THREAD

**Issue by jasminmif** [software-mansion/react-native-reanimated#5616]
### Description

Building android for staging and release throws an error in `supportsLocking_` which was introduced on the last nightly version.

Error:

```
/node_modules/react-native-reanimated/android/../Common/cpp/ReanimatedRuntime/WorkletRuntime.h:69:14: error: private field 'supportsLocking_' is not used [-Werror,-Wunused-private-field]
  const bool supportsLocking_;
```

```
cd android
./gradlew clean
./gradlew assembleReleaseStaging  check -x lint --stacktrace
```

### Steps to reproduce

Use react-native v72.7 and reanimated nightly version 
Run command to generate release and staging build in android:

cd android
./gradlew clean
./gradlew assembleReleaseStaging  check -x lint --stacktrace

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/blob/720fefba7cd53471e98d52282c783701233861a7/Common/cpp/ReanimatedRuntime/WorkletRuntime.h#L29

### Reanimated version

3.7.0-nightly-20240126-720fefba7

### React Native version

0.72.7

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by DrRefactor** [comment]
Hello, I've already created PR for that.
https://github.com/software-mansion/react-native-reanimated/pull/5615
