### ISSUE TITLE
Not able to use Reanimated(3.6.2) useScrollViewOffset hook with Expo 50.0.4.

### ISSUE THREAD

**Issue by sultanhunter** [software-mansion/react-native-reanimated#5622]
### Description

On using the reanimated useScrollViewOffset hook I am getting:
" ERROR  Error: Exception in HostFunction: Value is null, expected a number" 

Expo SDK version: 50.0.4
Reanimated version: 3.6.2
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-31 at 18 51 40](https://github.com/expo/expo/assets/39861073/8b17369b-2c33-4a34-a211-f10af7f1c0a0)

### Steps to reproduce

1. Add react-native-reanmiated 3.6.2 dependecy with expo-50.0.4 sdk.
2. import useScrollViewOffset hook from react-native-animated & use it in the code.
3. It will throw the error.

### Snack or a link to a repository

https://github.com/sultanhunter/reanimated-expo-bug

### Reanimated version

3.6.2

### React Native version

0.73.2

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

None

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by ahmadbakhshi** [comment]
Same here with expo 50.0.5

**Comment by KaisSalha** [comment]
I'm running into the same issue.

The main reason for this is that `useScrollViewOffset` is incapable of handling an `undefined` ref. So when you're rending the loading text it throws the error. Until it's fixed, you'll need to raise the fetching to a higher component and have the component with `useScrollViewOffset` run only when the data is available.

**Comment by sultanhunter** [comment]
Yeah, you are right, by making <Animated.ScrollView> always available & rendering the components of the <Animated.ScrollView> based on if the data is loaded, it gets resolved.
` <Animated.ScrollView
        ref={scrollRef}
        contentContainerStyle={{ paddingBottom: 100 }}
        scrollEventThrottle={16}
      >
        {!item && <Text>Loading...</Text>}
        {item && (
          <>
           [Child Components]
          </>
        )}
      </Animated.ScrollView>`
Thanks.

**Comment by leomarker** [comment]
> I'm running into the same issue.
> 
> The main reason for this is that `useScrollViewOffset` is incapable of handling an `undefined` ref. So when you're rending the loading text it throws the error. Until it's fixed, you'll need to raise the fetching to a higher component and have the component with `useScrollViewOffset` run only when the data is available so this part is always available: `<Animated.ScrollView ref={scrollRef} scrollEventThrottle={16}>`
> 
> Edit: this seems to work:
> 
> ```
> if (loading)
> 		return (
> 			<View ref={scrollRef as any} style={{ flex: 1 }}>
> 				<LoadingScreen />
> 			</View>
> 		);
> ```

This works thanks

**Comment by RiczCalixto** [comment]
What if I want to use with FlatList? im having problem using useScrollViewOffet with FlatList. That solution doesn't work.

**Comment by erquhart** [comment]
@sultanhunter this is a valid bug, should be reopened so the team knows it needs to be fixed. The workaround is helpful, but `useScrollViewOffset()` still doesn't work the way it's described in the docs until this is fixed.
