### ISSUE TITLE
Exception thrown while executing UI block: -[__NSDictionaryM doubleValue]: unrecognized selector sent to instance 0x600002a99900

### ISSUE THREAD

**Issue by osdnk** [software-mansion/react-native-reanimated#563]
![image](https://user-images.githubusercontent.com/25709300/72550291-68884b80-3860-11ea-8657-79ab70b352f5.png)

Repro: click on snappable in the example app

**Comment by enterteg** [comment]
I bumped into this error today. Make sure you are using `sharedValue.value` and not just `sharedValue` 🙇
