### ISSUE TITLE
_getAnimationTimestamp is not defined

### ISSUE THREAD

**Issue by ertemishakk** [software-mansion/react-native-reanimated#5635]
### Description

   "react-native-gesture-handler": "^2.14.1",
   "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
   "react-native-reanimated": "^3.6.2"

These are my versions - when i spin up using the code below to create a Drawer i get this warning 

I'm using web browser to test this.

![image](https://github.com/software-mansion/react-native-reanimated/assets/56520971/2636957f-717f-4390-ad98-5260c789d73a)

### Steps to reproduce

`import { createDrawerNavigator } from "@react-navigation/drawer";`

`const Drawer = createDrawerNavigator();`

### Snack or a link to a repository

n/a

### Reanimated version

3.6.2

### React Native version

0.72

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by jacklj** [comment]
Same issue - upgraded reanimated, now iOS app immediately crashes (on Simulator)

**Comment by m-bert** [comment]
Hi @ertemishakk! Could you provide a reproduction? I've just created new react native app, used example from [react navigation docs](https://reactnavigation.org/docs/drawer-based-navigation/) and there was no crash in my case.

**Comment by m-bert** [comment]
@jacklj I've tested example mentioned above on iOS simulator and it also works fine, do you have any reproduction that we could look at?
