### ISSUE TITLE
I got this error " Task :app:compileDevDebugKotlin FAILED" while updating the react native 0.73.4 

### ISSUE THREAD

**Issue by NikhilMasurkar** [software-mansion/react-native-reanimated#5659]
### Description

Configure project :react-native-reanimated
Android gradle plugin: 8.1.1

Gradle: 8.3
WARNING: The specified Android SDK Build Tools version (29.0.3) is ignored, as it is below the minimum supported version (33.0.1) for Android Gradle Plugin 8.1.1.

Android SDK Build Tools 33.0.1 will be used.
To suppress this warning, remove "buildToolsVersion '29.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:generateBundledResourcesHashDevDebug
67434154867de7be7d8b9fc89dddfb975e8e7ba60e8aae6961750d0c1933ad50

> Task :app:compileDevDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.                                                

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
848 actionable tasks: 13 executed, 835 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainActivity.kt:40:1 Expecting a top level declaration
e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:26:37 Return type of 'getPackages' is not a subtype of the return type of the overridden member 'protected/*protected and package*/ abstract fun getPackages(): (MutableList<ReactPackage!>..kotlin.collections.List<ReactPackage!>?) defined in com.facebook.react.defaults.DefaultReactNativeHost'
e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:27:13 Type mismatch: inferred type is ArrayList<ReactPackage!>! but List<ReactPackage> was expected
e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:27:40 Type mismatch: inferred type is ArrayList<ReactPackage!>! but List<ReactPackage> was expected
e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:30:20 Unresolved reference: OrientationPackage

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugKotlin'.

> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction    
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 39s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDevDebug -PreactNativeDevServerPort=8081
e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainActivity.kt:40:1 Expecting a top level declaration e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:26:37 Return type of 'getPackages' is not a subtype of the return type of the overridden member 'protected/*protected and package*/ abstract fun getPackages(): (MutableList<ReactPackage!>..kotlin.collections.List<ReactPackage!>?) defined in com.facebook.react.defaults.DefaultReactNativeHost' e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:27:13 Type mismatch: inferred type is ArrayList<ReactPackage!>! but List<ReactPackage> was expected e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:27:40 Type mismatch: inferred type is ArrayList<ReactPackage!>! but List<ReactPackage> was expected e: file:///C:/Project_Repo/App_Frontend/IndigoLearn/android/app/src/main/java/com/fin1/MainApplication.kt:30:20 Unresolved reference: OrientationPackage FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:compileDevDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 1m 39s.

### Steps to reproduce

i build the project and using the latest version of     "react-native-reanimated": "^3.7.0", and react native 0.73.4 
while building the app  i got the following error ,
please check.

![Screenshot 2024-02-12 125441](https://github.com/software-mansion/react-native-reanimated/assets/101415426/c1bf20bb-0615-4f0e-94f6-4c56fb9ffddb)

### Snack or a link to a repository

N\a

### Reanimated version

3.7.1

### React Native version

0.73.4

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by lucianolopezz** [comment]
same error

**Comment by rafael-castelo** [comment]
Any update on this? same error

**Comment by NikhilMasurkar** [comment]
> Any update on this? same error

not yet

**Comment by lucianolopezz** [comment]
I solved following step by step this doc: https://docs.expo.dev/bare/upgrade/?fromSdk=49&toSdk=50

**Comment by NikhilMasurkar** [comment]
@lucianolopezz  I'm working on cli project so this is not helpful for me

**Comment by rutgervanwilligen** [comment]
Possibly a partial answer: I had the three type mismatch errors (lines 26 and 27) in `MainApplication.kt` too, after migrating from `MainApplication.java`. In my case, it was because of two imports I overlooked (`java.util.Arrays` and `java.util.List`). Removing those fixed these errors for me.

**Comment by NikhilMasurkar** [comment]
i also remove the same lines but issue is still present 

```
onfigure project :react-native-reanimated
Android gradle plugin: 8.1.1
Gradle: 8.3
WARNING: The specified Android SDK Build Tools version (29.0.3) is ignored, as it is below the minimum supported version (33.0.1) for Android Gradle Plugin 8.1.1.
Android SDK Build Tools 33.0.1 will be used.
To suppress this warning, remove "buildToolsVersion '29.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:generateBundledResourcesHashDevDebug
107f0556aa5d6caf1733f7ece0fe0ec0918782533bbcd3b7d7fb2c4c8faa3a97

> Task :app:mergeDevDebugAssets FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.                                                 

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
709 actionable tasks: 8 executed, 701 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

ERROR: C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash: Resource and asset merger: Duplicate resources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDevDebugAssets'.
> C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash      C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash: Error: Duplicate resources    

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 57s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDevDebug -PreactNativeDevServerPort=8081
ERROR: C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash: Resource and asset merger: Duplicate resources FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:mergeDevDebugAssets'. > C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash       C:\Project_Repo\App_Frontend\IndigoLearn\android\app\build\generated\assets\createBundleDevDebugJsAndAssets\CodePushHash: Error: Duplicate resources * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 1m 57s.
```

**Comment by iliapnmrv** [comment]
For me the reason was an import as @rutgervanwilligen mentioned https://github.com/software-mansion/react-native-reanimated/issues/5659#issuecomment-2017927599 

`import java.util.List;`

It was removed in version 0.73
[0.72](https://react-native-community.github.io/upgrade-helper/?from=0.72.12&to=0.73.6#RnDiffApp-android-app-src-main-java-com-rndiffapp-MainApplication.java-deleted) - still has this List import 

[0.73](https://react-native-community.github.io/upgrade-helper/?from=0.72.12&to=0.73.6#-dev-null-RnDiffApp-android-app-src-main-java-com-rndiffapp-MainApplication.kt) - no List import

**Comment by NikhilMasurkar** [comment]
MY MainApplication.kt file 


```
package com.indigolearn.fin1

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.react.flipper.ReactNativeFlipper
import com.facebook.soloader.SoLoader
import com.microsoft.codepush.react.CodePush
import com.razorpay.rn.RazorpayPackage
import org.wonday.orientation.OrientationActivityLifecycle
import com.reactnativecommunity.webview.RNCWebViewPackage;

class MainApplication :Application() , ReactApplication {

 
  override val reactNativeHost: ReactNativeHost =

     object : DefaultReactNativeHost(this) {
       
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
               add(OrientationPackage()) 
                add(RNCWebViewPackage())
            }
        override fun getJSMainModuleName(): String = "index"
        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG
        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
        // override fun getJSBundleFile: String = CodePush.getJSBundleFile()
      }


  override val reactHost: ReactHost
    get() = getDefaultReactHost(this.applicationContext, reactNativeHost)

 override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
    ReactNativeFlipper.initializeFlipper(this, reactNativeHost.reactInstanceManager)
    registerActivityLifecycleCallbacks(OrientationActivityLifecycle.getInstance())
  }
}
```

**Comment by NikhilMasurkar** [comment]
issue solve when I check mainActivity.kt file 
this is correct way to write 
```
package packageName

import android.content.Intent
import android.content.res.Configuration
import android.os.Bundle
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import org.devio.rn.splashscreen.SplashScreen

class MainActivity : ReactActivity() {

    /**
     * Returns the name of the main component registered from JavaScript. This is used to schedule
     * rendering of the component.
     */
     
    override fun onCreate(savedInstanceState: Bundle?) {
        SplashScreen.show(this) // here
        super.onCreate(null)
    }

    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        val intent = Intent("onConfigurationChanged")
        intent.putExtra("newConfig", newConfig)
        this.sendBroadcast(intent)
    }

    override fun getMainComponentName(): String = "name"
    

    /**
    * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
    * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
    */
   

  
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}

```

**Comment by pranshuchittora** [comment]
Facing the same in RN 0.75.2 removing `import java.util.List;` fixed the issue.

**Comment by israel-mc** [comment]
> Possibly a partial answer: I had the three type mismatch errors (lines 26 and 27) in `MainApplication.kt` too, after migrating from `MainApplication.java`. In my case, it was because of two imports I overlooked (`java.util.Arrays` and `java.util.List`). Removing those fixed these errors for me.

This works for me 👏
