### ISSUE TITLE
 Cannot read property 'isConfigured' of undefined 

### ISSUE THREAD

**Issue by elkee2003** [software-mansion/react-native-reanimated#5664]
### Description

I tried running my code and I got this error:
npm start -- --reset-cache

### Steps to reproduce

1. npm start
2. npm run android
3. the error occurs

### Snack or a link to a repository

https://github.com/elkee2003/Atua2024.git

### Reanimated version

3.7.0

### React Native version

0.73.4

### Platforms

Android, Web

### JavaScript runtime

JSC

### Workflow

React Native

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by anatooly** [comment]
@elkee2003 how you fix this?

**Comment by elkee2003** [comment]
> @elkee2003 how you fix this?

This error normally happens when you use drawer navigator. To solve this, you have to go to babel.config.js file.
and paste this:
`plugins: [
    "react-native-reanimated/plugin",
  ],
`
The whole code will look like this:
`module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    "react-native-reanimated/plugin",
  ],
};
`
After that run:
`npm start -- --reset-cache`

**Comment by Kenildev007** [comment]
thank you so much bro i was trying to solve this for more than 3 hours and you solution works immediately

**Comment by Yahya-Naeem** [comment]
I got this error as well but it is showing me this 
![image](https://github.com/software-mansion/react-native-reanimated/assets/104232936/77ec25e1-e5e2-4a3f-8f8e-d732433eb747)
is there any way I can Solve it ?
`
//React imports
import 'react-native-gesture-handler';
import { SafeAreaView, ScrollView, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
//navigation Import 
import OuterTabs from './navigations/outernavigator/Navigator.jsx';

//icons import
import { EllipseIcon,TopEllipseIcon } from './assets/svgs/index.js';

//styles import 
import AppStyles from './styles/Styles.jsx';
import HomeNavigator from './navigations/homenavigator/Navigator.jsx';

function App () {
  return (
    <NavigationContainer>
    <SafeAreaView style={[AppStyles.background]}>
      <ScrollView
        contentContainerStyle={AppStyles.container}
        >
          <View style={{left:-20,top:0}}>
              <EllipseIcon width={165} height={165} />
          </View>
          <View style={{position:'absolute',top:-20,left:0}}>
              <TopEllipseIcon width={165} height={165} />
          </View>

          
            <HomeNavigator />
          
      </ScrollView>
    </SafeAreaView>
    </NavigationContainer>
  );
}

export default App;

`
import * as React from 'react';
import { createDrawerNavigator } from '@react-navigation/drawer';
import HomeScreen from '../../screens/home/HomeScreen.jsx';
import SettingsScreen from '../../screens/settings/SettingsScreen.jsx' ;
import Login from '../../screens/login/Login.jsx';
const Drawer = createDrawerNavigator();
export default function HomeNavigator() {
  return (
        <Drawer.Navigator>
            
            <Drawer.Screen 
                name="Logout" 
                component={Login} 
            />
        </Drawer.Navigator>
  );
}

`

**Comment by razannael** [comment]
Thanks, your solution ends 7 hours of hell.

**Comment by Yahya-Naeem** [comment]
What is it ?

**Comment by Naveenzerobugz** [comment]
This error normally happens when you use drawer navigator. To solve this, you have to go to babel.config.js file.
and paste this:
plugins: [ "react-native-reanimated/plugin", ], 
The whole code will look like this:
module.exports = { presets: ['module:@react-native/babel-preset'], plugins: [ "react-native-reanimated/plugin", ], }; 
After that run:
npm start -- --reset-cache

i have tried this but not working for me

**Comment by SSHshadow222** [comment]
> I got this error as well but it is showing me this ![image](https://private-user-images.githubusercontent.com/104232936/308731746-77ec25e1-e5e2-4a3f-8f8e-d732433eb747.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTQzNjEsIm5iZiI6MTcxMTIxNDA2MSwicGF0aCI6Ii8xMDQyMzI5MzYvMzA4NzMxNzQ2LTc3ZWMyNWUxLWU1ZTItNGEzZi04ZjhlLWQ3MzI0MzNlYjc0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxNzE0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWE0ZGM0OTlmNzY4NTFkMWZkMGY5NDlkZDkwZGVmMDdhZDc2MTlkZjY3MGFjNDk5Y2MzNDRmNzc2ZDJkNmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.61hWIudO1GZybRYfKsueX6bCduDpuxrjuOOvrSG2_Kc) is there any way I can Solve it ? ` //React imports import 'react-native-gesture-handler'; import { SafeAreaView, ScrollView, View } from 'react-native'; import { NavigationContainer } from '@react-navigation/native'; //navigation Import import OuterTabs from './navigations/outernavigator/Navigator.jsx';
> 
> //icons import import { EllipseIcon,TopEllipseIcon } from './assets/svgs/index.js';
> 
> //styles import import AppStyles from './styles/Styles.jsx'; import HomeNavigator from './navigations/homenavigator/Navigator.jsx';
> 
> function App () { return ( <View style={{position:'absolute',top:-20,left:0}}>
> 
> ```
>         <HomeNavigator />
>       
>   </ScrollView>
> </SafeAreaView>
> </NavigationContainer>
> ```
> 
> ); }
> 
> export default App;
> 
> ` import * as React from 'react'; import { createDrawerNavigator } from '@react-navigation/drawer'; import HomeScreen from '../../screens/home/HomeScreen.jsx'; import SettingsScreen from '../../screens/settings/SettingsScreen.jsx' ; import Login from '../../screens/login/Login.jsx'; const Drawer = createDrawerNavigator(); export default function HomeNavigator() { return ( <Drawer.Navigator>
> 
> ```
>         <Drawer.Screen 
>             name="Logout" 
>             component={Login} 
>         />
>     </Drawer.Navigator>
> ```
> 
> ); }
> 
> `

I had the exact same issue and solved it by updating the outdated dependencies in my project to their latest version. 
If you're using NPM, [this](https://www.freecodecamp.org/news/how-to-update-npm-dependencies/) guide might be helpful.

**Comment by alexsvt2** [comment]
@Yahya-Naeem.   

Did you solve your problem? 

Because I'm facing the same errors 😅

**Comment by Yahya-Naeem** [comment]
Yes, It was because of reanimated version . Uninstall current and download
2. version of reanimated
, Hope it will help .

**Comment by Siddharth692k** [comment]
> > @elkee2003 how you fix this?
> 
> This error normally happens when you use drawer navigator. To solve this, you have to go to babel.config.js file. and paste this: `plugins: [ "react-native-reanimated/plugin", ], ` The whole code will look like this: `module.exports = { presets: ['module:@react-native/babel-preset'], plugins: [ "react-native-reanimated/plugin", ], }; ` After that run: `npm start -- --reset-cache`

Thank God this worked for me. 
I've been trying to figure out what went wrong for two days straight.
Couldn't come up with a remedy.
Finally doing the above helped me.

**Comment by Alonso9** [comment]
> > @elkee2003 how you fix this?
> 
> This error normally happens when you use drawer navigator. To solve this, you have to go to babel.config.js file. and paste this: `plugins: [ "react-native-reanimated/plugin", ], ` The whole code will look like this: `module.exports = { presets: ['module:@react-native/babel-preset'], plugins: [ "react-native-reanimated/plugin", ], }; ` After that run: `npm start -- --reset-cache`

Thanks

**Comment by CarlosAlbertoTI** [comment]
> > @elkee2003 how you fix this?
> 
> This error normally happens when you use drawer navigator. To solve this, you have to go to babel.config.js file. and paste this: `plugins: [ "react-native-reanimated/plugin", ], ` The whole code will look like this: `module.exports = { presets: ['module:@react-native/babel-preset'], plugins: [ "react-native-reanimated/plugin", ], }; ` After that run: `npm start -- --reset-cache`

I tried this and didn't work
