### ISSUE TITLE
1.7.0 regression while moving objects using PanGestureHandler

### ISSUE THREAD

**Issue by sebqq** [software-mansion/react-native-reanimated#570]
Hello there.

I've noticed some regression using latest 1.7.0 reanimated while moving objects. Using older 1.4.0 everything works just fine.

## How it should look like

![good](https://user-images.githubusercontent.com/33039909/72597102-57e1df00-390d-11ea-9b10-35f3284f679a.gif)

## How it actually looks like
![bad](https://user-images.githubusercontent.com/33039909/72597404-0128d500-390e-11ea-9ae5-d1105ccbd8b2.gif)

## Reproducible Demo

Please find reproducible demo in following git repository [repo](https://github.com/sebinq/react-native-reanimated-bug)

Thanks.

**Comment by jakub-gonet** [comment]
Hi @sebinq,

thanks for reporting, unfortunately I wasn't able to reproduce this on 1.4, looks pretty much the same as in 2nd gif. Did you do anything else besides running `yarn` and `pod install`?

**Comment by sebinq** [comment]
Hi @jakub-gonet. No I'm just switching versions of react-native-reanimated using `yarn add react-native-reanimated@1.4.0 && cd ios && pod install`

**Comment by jakub-gonet** [comment]
All right, I managed to get that to work. Will look into it, thanks!

**Comment by sebinq** [comment]
Can you let me know what was the reason my repro was not working right out of the box so I can prepare better repro if needed in future? Thanks :)

**Comment by jakub-gonet** [comment]
That was my mistake, I assumed that manually changing dep version in `package.json` and running `yarn` is sufficient to convince yarn to upgrade / downgrade versions 😅

**Comment by sebinq** [comment]
Thanks! 😄
