### ISSUE TITLE
Error when use call() inside event()

### ISSUE THREAD

**Issue by Strate** [software-mansion/react-native-reanimated#571]
Try to use this code:

```
onScroll={
  Animated.event([
    {
      nativeEvent: evt => Animated.call(
        [evt.contentOffset.y],
        ([scrollY]) => this._handle(scrollY)
      )
    }
  ])
}
```

This will fail with this error: Reanimated: Animated.call node args should be an array with elements of type AnimatedNode. One or more of them are not AnimatedNodes

Looks like this is because AnimatedEvent calls nested functions with Proxy object, which are not satisfy condition `args.every(el => el instanceof AnimatedNode)`

Looks like happen after https://github.com/software-mansion/react-native-reanimated/commit/c7b664d19300df36d316bd9d1f9c311e6c62029c

**Comment by osdnk** [comment]
Hey, @Strate 
Thanks. 
I reset to 1.4.0 and after adding 
```
    this.handleRotate = event([
      {
        nativeEvent: (e) =>
            Animated.call([e.rotation], console.log)
      },
    ]);
```
I regret to say that it does not work so it's not a regression (hoewever, still bug).

Thanks!

**Comment by mym0404** [comment]
how can we solve this?

**Comment by Magikmagnum** [comment]
I have the same problem

**Comment by mym0404** [comment]
I am considering version 2.
In v2, we don't need use node blocks

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request. I recommend using Reanimated v2.
