### ISSUE TITLE
Issue on createAnimatedComponent.tsx Unexpected token, expected ","

### ISSUE THREAD

**Issue by codeweight** [software-mansion/react-native-reanimated#5725]
### Description

Running an expo react-native application with expo version "expo": "^49.0.0" and system MAC M1 Venture 13.2.1 (22D68)
Node version is v20.11.1
& npm version is 10.2.4
& npx version is 10.2.4

Have configured all the packages and plugins correctly even **./gradlew clean** command is getting successful.
But while running the **yarn android** on run time on the emulator below issue arises for the react-native-reanimated for syntax error.

Find the issue as below,

`error: SyntaxError: /Users/devendraahirwar/Desktop/Documents/apps/expoapps/mm/matrimoniallagnagathi/node_modules/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx: Unexpected token, expected "," (105:28)

  103 | // @ts-ignore This is required to create this overload, since type of createAnimatedComponent is incorrect and doesn't include typeof FlatList
  104 | export function createAnimatedComponent(
> 105 |   component: typeof FlatList<unknown>,
      |                             ^
  106 |   options?: Options<any>
  107 | ): ComponentClass<AnimateProps<FlatListProps<unknown>>>;
  108 |
`

Have the dependency version as,
`
"react-native": "0.72.10",
"react-native-reanimated": "^3.7.1",

`

and 
babel.config.js as followed as,
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};`

Android screenshot:
![Screenshot_1708773423](https://github.com/software-mansion/react-native-reanimated/assets/92736340/e2497af1-14e9-4ef0-acc2-30254bb5424f)

Also in the iOS platform, it fails with the react-native-reanimated package: 
Below is the iOS runtime error caught on simulator
`iOS Bundling failed 12533ms
error: SyntaxError: /Users/devendraahirwar/Desktop/Documents/apps/expoapps/mm/matrimoniallagnagathi/node_modules/react-native-reanimated/src/reanimated2/threads.ts: Unexpected token (235:47)

  233 |
  234 |     return (...args) =>
> 235 |       runOnJS(runWorkletOnJS<Args, ReturnValue>)(
      |                                                ^
  236 |         fun as WorkletFunction<Args, ReturnValue>,
  237 |         ...args
  238 |       );

`
iOS screenshot:
![Simulator Screen Shot - iPhone 14 Pro Max - 2024-02-24 at 16 46 01](https://github.com/software-mansion/react-native-reanimated/assets/92736340/b5bb5052-de88-448b-86f8-0a88fea65e9b)

Any solution to this?

### Steps to reproduce

While running the application on the emulator it shows the error

### Snack or a link to a repository

https://sudodev8898@bitbucket.org/sysmarche/matrimonial.git

### Reanimated version

3.7.1

### React Native version

0.72.10

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
I've just created a new app with reanimated and everything seems to work. I use  "expo": "^50.0.1", and my node version is 21.1.0

**Comment by codeweight** [comment]
Hi @Latropos, I have updated my expo to "expo": "^49.0.0" will this it work or I need to create a new app only.
