### ISSUE TITLE
Use `useMemo` for reference stability instead of `useRef`

### ISSUE THREAD

**Issue by tjzel** [software-mansion/react-native-reanimated#5731]
### Description

Currently, Reanimated uses a pattern of `useRef` with follow-up initialization for memoization:

```js
function useCustomHook(){
  const ref = useRef(null);
  if (ref.current === null){
    ref.current = initialize();
  };
};
```

---

List of files that need the aforementioned change:

- [ ] ViewDescriptorSet.ts #5732 
- [ ] useAnimatedKeyboard.ts 
- [ ] useAnimatedRef.ts
- [ ] useAnimatedStyle.ts
- [ ] useDerivedValue.ts
- [ ] useEvent.ts (and all other hooks that use it):
    1. useAnimatedScrollHandler.ts
    2. useScrollViewOffset.ts
    3. useAnimatedGestureHandler.ts (deprecated)
- [ ] useHandler.ts
    1. useAnimatedScrollHandler.ts
    2. useAnimatedGestureHandler.ts (deprecated)
- [ ] useScrollViewOffset.ts

---
We should also asses if memoization if those files is acceptable:

- [ ] FlatList.tsx
- [ ] useAnimatedSensor.ts
- [ ] LayoutAnimationConfig.ts
- [ ] useFrameCallback.ts

---

Then we will have to assure that all our hooks return new reference had some of their dependencies changed as it can happen for example in https://github.com/software-mansion/react-native-reanimated/issues/5364.

### Steps to reproduce

n/a

### Snack or a link to a repository

n/a

### Reanimated version

n/a

### React Native version

n/a

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Closing since it seems to be irrelevant.

**Comment by Rexogamer** [comment]
looks like this issue wasn't closed?

**Comment by tjzel** [comment]
@Rexogamer I must've been very tired already 😄
