### ISSUE TITLE
Android back button no longer works with reduced motion

### ISSUE THREAD

**Issue by pierroo** [software-mansion/react-native-reanimated#5737]
### Description

I recently upgraded to reanimated v3
since then, lots of issue that were already discussed in other topics (I also wish there was a general settings to turn it off for the whole app)

But I didn't see a mention of android back button no longer working because of it.

Users who face that issue, confirmed that turning off reduced motion in their android settings fixed the back button.

### Steps to reproduce

1- turn reduce motion ON
2- use hardware back button on android (the one at the bottom right of android)
3- doesn't work 

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

3.6.2

### React Native version

0.73.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @pierroo 
I was unable to reproduce your issue in our example app, 
we were using
```tsx

import { NavigationContainer, useNavigation } from '@react-navigation/native';
import {
//...
  NativeStackNavigationProp,
} from '@react-navigation/native-stack';

//...
const Stack = createNativeStackNavigator();
//...
  return (
    <NavigationContainer independent={true}>
      <Stack.Navigator>
        <Stack.Screen name="First" component={FirstScreen} />
        <Stack.Screen name="Second" component={SecondScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
```

What type of navigator do you use? Could you provide a simple reproduction?
