### ISSUE TITLE
[Bug🐛] layout function not behaving as expected in Expo 50.0.8 with new-arch

### ISSUE THREAD

**Issue by tcloudAce** [software-mansion/react-native-reanimated#5748]
### Description

Hello,

I've been encountering an issue with the  Layout function in the `react-native-reanimated` library within my expo project. The function does not seem to work as anticipated.

**Environment**:
- Expo version: 50.0.8 with new-arch
- React Native version: 0.73.4
- React Native Reanimated version: 3.7.1
- Platform(s):  iOS, Android
- Device info: All 

**Expected behavior**:
I expected all animations provided by the react-native-reanimated library, including SlideInLeft, SlideOutRight, and others, to work correctly. These animations should allow elements to smoothly transition in and out when they are added to or removed from the component tree.

**Actual behavior**:
However, I am observing that none of the animations from the react-native-reanimated library are working as expected. There is no animation occurring at all – elements appear and disappear abruptly without any transition. This issue is not limited to just SlideInLeft and SlideOutRight, but extends to all animations provided by the library. It seems like the animation functions are either not being triggered or are not responding in the specified environment, leading to a complete lack of animated transitions.

**Steps to reproduce**:
1. Initialize a new project with `npx create-expo-app@latest -e with-new-arch`
2. Implement the following sample code:

```javascript
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useReducer } from "react";
import Animated, { SlideInLeft, SlideOutRight } from "react-native-reanimated";

export default function App() {
  const [show, toggle] = useReducer((_) => !_, false);

  return (
    <View style={styles.container}>
      <TouchableOpacity onPress={toggle}>
        <Text>Press me</Text>
      </TouchableOpacity>
      {show && (
        <Animated.View
          entering={SlideInLeft}
          exiting={SlideOutRight}
          style={{ width: 100, height: 100, backgroundColor: "red" }}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

### Steps to reproduce

**Steps to reproduce**:
1. Initialize a new project with `npx create-expo-app@latest -e with-new-arch`
2. Implement the following sample code:

```javascript
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useReducer } from "react";
import Animated, { SlideInLeft, SlideOutRight } from "react-native-reanimated";

export default function App() {
  const [show, toggle] = useReducer((_) => !_, false);

  return (
    <View style={styles.container}>
      <TouchableOpacity onPress={toggle}>
        <Text>Press me</Text>
      </TouchableOpacity>
      {show && (
        <Animated.View
          entering={SlideInLeft}
          exiting={SlideOutRight}
          style={{ width: 100, height: 100, backgroundColor: "red" }}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

### Snack or a link to a repository

...

### Reanimated version

～3.7.1

### React Native version

0.73.4

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Fabric (New Architecture)

### Build type

Debug app & production bundle

### Device

iOS simulator

### Device model

ALL

### Acknowledgements

Yes

**Comment by danielhover** [comment]
See https://github.com/software-mansion/react-native-reanimated/issues/3439

**Comment by tomekzaw** [comment]
Thanks @tcloudAce for taking your time to report this issue (we really appreciate the quality of this report 🙏 ). I'm going to close the issue since we already track the progress of Layout Animations for Fabric in #3439.
