### ISSUE TITLE
[iOS] Buggy onScroll with Reanimated

### ISSUE THREAD

**Issue by oguzhanali** [software-mansion/react-native-reanimated#575]
When you use onScroll event with Reanimated on iOS, event values is only set after the scroll actions with momentum. It doesn't respond to scroll with drag gestures. Former issues seems closed #160 and inactive #309 but this is an ongoing issue. 

Here is a minimal example: [[iOS] Buggy onScroll with Reanimated](https://snack.expo.io/@cyborg/[ios]-buggy-onscroll-with-reanimated)

It works fine with RN Animated.

Env:
"react": "16.9.0",
"react-native": "...expo.../sdk-36..",
 "react-native-reanimated": "~1.4.0",

**Comment by lindesvard** [comment]
Try set `scrollEventThrottle={1}`. I think that will solve your problem

**Comment by oguzhanali** [comment]
scrollEventThrottle={16} solved it. It seems on iOS with reanimated, this rate have to be declared. @lindesvard thanks for the reply.
