### ISSUE TITLE
Can't run reanimated 3.7.2 with expo 50.0.1, but reanimated 3.6.0 can

### ISSUE THREAD

**Issue by ht19** [software-mansion/react-native-reanimated#5753]
### Description

i getting start with follow step in guild line: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started, I can't run bundle on ios device, it get error: 

```
Exception in HostFunction: <unknown>, "main" has not been registered. This can happen if: 
*Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```
Then i'm downgrade `react-native-reanimated` to ~3.6.0, it can run normally.

### Steps to reproduce

1. npx create-expo-app my-app -e with-reanimated
2. yarn add react-native-reanimated
3. Add (plugins: [
      ...
      'react-native-reanimated/plugin',
    ],)
4. yarn start --reset-cache
5. Getting error like in this Description above

### Snack or a link to a repository

https://snack.expo.dev/@tlhbuildapp/error-with-reanimated-3-7-2

### Reanimated version

3.7.2

### React Native version

0.73.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by scriptprojectsdev** [comment]
Downgrading to 3.6.0 worked me as well. Thanks.

**Comment by AdamGerthel** [comment]
I just upgraded to Expo SDK 50 and I'm using `Keyframe` which worked in 3.3.0 which I was using before. Since Expo is pinned to 3.6.2, I can't upgrade because `Keyframe` doesn't seem to be working in 3.6.2.

**Comment by vinceprofeta** [comment]
Is there an update on this issue?
