### ISSUE TITLE
Android crashed in production mode (APK)

### ISSUE THREAD

**Issue by alexandr-feschenko** [software-mansion/react-native-reanimated#5762]
### Description

Android crashed on production mode (APK). But it works fine on development mode. I use react-native CLI
"react-native-reanimated": "^3.7.2",
"react-native": "0.73.4",

### Steps to reproduce

make android release apk
install it
build crashes

### Snack or a link to a repository

*

### Reanimated version

3.7.2

### React Native version

0.73.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by migueldaipre** [comment]
Add a minimal repro

**Comment by tjzel** [comment]
Hi @alexandr-feschenko. Is it a duplicate of #5660?
