### ISSUE TITLE
Task :app:mergeDebugResources FAILED

### ISSUE THREAD

**Issue by shubhu151** [software-mansion/react-native-reanimated#5768]
### Description

Android app is not building it is giving error
Task :app:mergeDebugResources FAILED
react-native-reanimated - 3.6.3
react-native - 0.72.11

### Steps to reproduce

1. run-android

### Snack or a link to a repository

xyz

### Reanimated version

3.6.3

### React Native version

0.72.11

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @shubhu151!
Could you please provide a reproduction, or tell us, why you think that this crash is caused by reanimated? Was it a consequence of updating of some of your libraries? Which ones? From which version?

**Comment by shubhu151** [comment]
Hi @Latropos  

we are trying to update react native 0.67 to 0.72 while upgrading we are facing this issue. while using this library we are getting this issue.

**Comment by Latropos** [comment]
@shubhu151 
I assume that everything works for IOS, does it?
Did you run `react-native doctor`?
Please run your android app with AndroidStudio, remove all cache and sync gradle.
