### ISSUE TITLE
Performance regression between 1.7 and 1.4

### ISSUE THREAD

**Issue by Jarred-Sumner** [software-mansion/react-native-reanimated#577]
I tried upgrading to 1.7.0 and noticed that there are more main thread frame drops on iOS when using lots of nodes and higher CPU usage.

Here are two 30fps GIFs of the same screen, with the only difference being the version of `react-native-reanimated` used. The red circle is the `absoluteX` / `absoluteY` of a `PanGestureHandler`.

Notice how the right one looks smoother than the left one.

| `v1.7.0^` (New version) | `v1.4.0` (Old version) |
| ------------- | ------------- |
| ![1 7 0-trim](https://user-images.githubusercontent.com/709451/72759999-4fe3a280-3b8c-11ea-8eec-27141088e5be.gif) | ![1 4 0-trim](https://user-images.githubusercontent.com/709451/72759966-2fb3e380-3b8c-11ea-9e01-3185d985c0e5.gif) |

The jump at the end is just the GIF looping. I had to trim / crop / convert the videos so GitHub would accept them, you can see the original [videos here](https://github.com/software-mansion/react-native-reanimated/files/4088080/videos.zip)

**Comment by ShaMan123** [comment]
@Jarred-Sumner could you try with #528 fork?

**Comment by Jarred-Sumner** [comment]
Performance with your fork is much better! It doesn’t seem any different
than without.

I didn’t use exactly your fork —
https://github.com/Jarred-Sumner/react-native-reanimated/commits/yeet

I have a branch where I backported some bug fixes into 1.4.0 and merged
your PR into it

**Comment by Jarred-Sumner** [comment]
After testing some more, it seems that `onLayout` doesn't fire on the initial mount when using an `AnimatedEvent`.

It fires on subsequent layout updates, however.

My guess is that `setNativeProps` runs too late -- after this code already checks for the existence of a callback:

https://github.com/facebook/react-native/blob/0507d7368d236f8e7e34bb581ce0463648066e2f/React/Modules/RCTUIManager.m#L559-L569

What if we tried the `true` trick but in the props we pass to the component instead? I will try that in my branch.

**Comment by ShaMan123** [comment]
Tested that. It fails due to props type check.
In the example it did fire on first layout.

בתאריך יום א׳, 26 בינו׳ 2020, 10:14, מאת Jarred Sumner ‏<
notifications@github.com>:

**Comment by Jarred-Sumner** [comment]
Yeah I just tried that.

If you add a dummy function (like the current solution), the `AnimatedEvent` still seems to be ignored on the first render. It goes to the dummy function, however.

First mount:

`Animated.debug` inside an `<Animated.Code />` block:
```
2020-01-26 00:29:22.135367-0800 yeet[11066:107748] OFFSET Y 0
```

```
 LOG  Dummy Received! {"nativeEvent": {"layout": {"height": 310, "width": 414, "x": 0, "y": 193}, "target": 3807}}
```

After doing something that triggers `onLayout`:
```
2020-01-26 00:30:42.437571-0800 yeet[11066:107748] OFFSET Y 171
```

```
 LOG  Dummy Received! {"nativeEvent": {"layout": {"height": 354, "width": 414, "x": 0, "y": 171}, "target": 3807}}
```

**Comment by Jarred-Sumner** [comment]
Not 100% confident about the details, but this seems to work:
```patch
- (void)uiManagerWillPerformMount:(RCTUIManager *)uiManager
+ (void)uiManagerWillPerformLayout:(RCTUIManager *)uiManager
{
  if (_operations.count == 0) {
    return;
  }

  NSArray<AnimatedOperation> *operations = _operations;
  _operations = [NSMutableArray new];

  REANodesManager *nodesManager = _nodesManager;

+  RCTExecuteOnMainQueue(^{
+    for (AnimatedOperation operation in operations) {
+      operation(nodesManager);
+    }
+    [nodesManager operationsBatchDidComplete];
+  });

-  [uiManager addUIBlock:^(__unused RCTUIManager *manager, __unused NSDictionary<NSNumber *, UIView *> *viewRegistry) {
-    for (AnimatedOperation operation in operations) {
-      operation(nodesManager);
-    }
-    [nodesManager operationsBatchDidComplete];
-  }];

}
```
<sup>This is not a real `.patch` I just made it look like one to highlight the changes I made locally</sup>

On first render:
```
2020-01-26 00:52:41.830787-0800 yeet[16477:158417] OFFSET Y 0
2020-01-26 00:52:41.902331-0800 yeet[16477:158417] OFFSET Y 193
```

Perhaps `attachEvent` and `detachEvent` should be run on `uiManagerWillPerformLayout` when the event is not already attached, instead of on `uiManagerWillPerformMounting`?

From [`RCTUIManager.m`](https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L1135-L1155), we can see that `uiManagerWillPerformMounting` is called after performing layout. 

```objc
- (void)_layoutAndMount
{
  [self _dispatchPropsDidChangeEvents];
  [self _dispatchChildrenDidChangeEvents];

  [_observerCoordinator uiManagerWillPerformLayout:self];

  // Perform layout
  for (NSNumber *reactTag in _rootViewTags) {
    RCTRootShadowView *rootView = (RCTRootShadowView *)_shadowViewRegistry[reactTag];
    [self addUIBlock:[self uiBlockWithLayoutUpdateForRootView:rootView]];
  }

  [_observerCoordinator uiManagerDidPerformLayout:self];

  [_observerCoordinator uiManagerWillPerformMounting:self];

  [self flushUIBlocksWithCompletion:^{
    [self->_observerCoordinator uiManagerDidPerformMounting:self];
  }];
}
```

This means that any shadow views which send events during layout (such as `onLayout`) will never trigger for any `react-native-reanimated` events, since those events won't be registered by the time the code checks for the existence of them.

**Comment by Jarred-Sumner** [comment]
This seems to fix `onLayout`: https://github.com/Jarred-Sumner/react-native-reanimated/commit/92d7429084b4d047b29d71327e14b9d73f2a0750#diff-bc22b333aee7e217b792641f94005bf6

This will only connect nodes & attach/detach events before layout. All other operations happen during mount (like before).

**Comment by jakub-gonet** [comment]
@Jarred-Sumner,
could you provide some [snack](https://snack.expo.io/) which shows this regression? It's hard to reproduce without this.

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request. I recommend using Reanimated v2.
