### ISSUE TITLE
Pan Gesture accelerates the animation speed

### ISSUE THREAD

**Issue by Rakha112** [software-mansion/react-native-reanimated#5776]
### Description

I'm facing a weird bug, during a pan gesture, the animation speed of the circle seems faster compared to when there's no pan gesture. You can see it in the video below. Is this because I'm updating a sharedValue by directly incrementing it inside useAnimatedStyle ?

https://github.com/software-mansion/react-native-reanimated/assets/61527649/38255f89-1d2c-4eea-b4d7-9c19a4090ecc

<details>
  <summary>Full Code</summary>

```js
/* eslint-disable react-native/no-inline-styles */
import React from 'react';
import {StyleSheet, View} from 'react-native';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
} from 'react-native-reanimated';

export default function App() {
  const t = useSharedValue(0);

  const infinityStyle = useAnimatedStyle(() => {
    t.value += 0.05;
    const scale = (2 / (3 - Math.cos(2 * t.value))) * 150;
    return {
      transform: [
        {translateX: scale * Math.cos(t.value)},
        {translateY: scale * (Math.sin(2 * t.value) / 2)},
      ],
    };
  });

  const pan = Gesture.Pan().onBegin(() => {
    console.log('onBegin');
  });

  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <GestureDetector gesture={pan}>
        <View style={styles.container}>
          <Animated.View style={[styles.dot, infinityStyle]} />
        </View>
      </GestureDetector>
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 150,
  },
  dot: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#b58df1',
    position: 'absolute',
  },
});
```

</details>

### Steps to reproduce

1. Clone the repo or copy the code
2. Run the app
3. Performing a pan gesture
4. Observe the speed of the circle

### Snack or a link to a repository

https://github.com/Rakha112/reanimated-pan-gesture-bug

### Reanimated version

3.8.0

### React Native version

0.73.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @Rakha112
> Is this because I'm updating a sharedValue by directly incrementing it inside useAnimatedStyle ?
Yes, it is. Imagine you want to drag a circle across the screen - then you want this circle to stick as close to your finger as possible. Therefore registering event handler may influence the app behaviour and cause additional animation frames. Because you increment t inside `useAnimatedStyle` the animation gets faster.

If you want to see how you can create your animation you can open our example app and look at this example https://github.com/software-mansion/react-native-reanimated/blob/main/app/src/examples/PlanetsExample.tsx
