### ISSUE TITLE
 ERROR  ReferenceError: Property '_updateDataSynchronously' doesn't exist

### ISSUE THREAD

**Issue by version-mm** [software-mansion/react-native-reanimated#5778]
### Description

https://github.com/software-mansion/react-native-reanimated/blob/3.6.3/src/reanimated2/mutables.ts#L40
 ERROR  ReferenceError: Property '_updateDataSynchronously' doesn't exist
 react-native-reanimated@3.6.3
 expo@50.0.11

### Steps to reproduce

```jsx
import { View, Text, Switch } from "react-native-ui-lib"

<Switch  />
```

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

3.6.3

### React Native version

0.73.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by version-mm** [comment]
I believe that a minimal reproduction may not be necessary in this case, as the issue appears to be immediately evident through the code provided.
```js
    set _value(newValue: T) {
      value = newValue;
      if (syncDataHolder) {
        _updateDataSynchronously(
          syncDataHolder,
          makeShareableCloneOnUIRecursive(newValue)
        );
      }
      listeners.forEach((listener) => {
        listener(newValue);
      });
    },

```
_updateDataSynchronously  not find in the code in that tag 3.6.3.

**Comment by piaskowyk** [comment]
In version 3.6.3, the `_updateDataSynchronously` method was injected into the runtime as a global JSI function from C++ code - thats why you couldn't find them. However, in the latest version, we have completely removed the `_updateDataSynchronously` method. Therefore, I suggest checking if it works with version 3.8.0

**Comment by version-mm** [comment]
Thank you for your response. It seems that "runtime injected" is a blind spot in my knowledge. I have upgraded to version 3.8 a few days ago, and everything seems to be normal now.

**Comment by nhatItsforce** [comment]
I tried to start metro with --reset-cache option and it works.
`yarn start --reset-cache`

Hope it will help everyone~
