### ISSUE TITLE
when i use react-native-draggable-flatlist i saw error... [Reanimated] Tried to synchronously call a non-worklet function on the UI thread.

### ISSUE THREAD

**Issue by Byeong-soo** [software-mansion/react-native-reanimated#5787]
### Description

I am using react-native-draggable-flatlist in my company. When I drag an item, an error occurs: [Reanimated] Tried to synchronously call a non-worklet function on the UI thread.

I am using version 3.6.1 of Reanimated and version 4.0.1 of draggable flatlist. Everything works normally when I switch to Reanimated version 3.7.0, but I must use 3.6.1... I can patch the files to make it work. Could you give me a hint on which parts need to be modified? Thank you.

### Steps to reproduce

1. use react-native-draggble-flatlist 

### Snack or a link to a repository

https://github.com/computerjazz/react-native-draggable-flatlist

### Reanimated version

3.6.1

### React Native version

0.73.1

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey! 👋 Is there any specific reason related to Reanimated that's preventing you from upgrading to the latest version? I'm trying to understand the obstacles you're facing with the upgrade. If there are any issues, we'd like to address them.

**Comment by Byeong-soo** [comment]
The company is using various libraries, but I'm worried that updating the version might affect other places. In particular, I got an error message saying [Reanimated] Tried to synchronously call a non-worklet function on the UI thread. Is this a problem caused by synchronously calling the task that should be passed to the worklet function?

The `onGestureHandlerStateChange` and `onGestureHandlerEvent` events seem to be causing errors when they are working. Is there any reason to guess in this regard?

**Comment by Latropos** [comment]
Hi @Byeong-soo 
Unfortunately `react-native-draggable-flatlist` uses react-native-reanimated v2, which is no longer supported
