### ISSUE TITLE
Entering/Exiting animation crashes app on 3.8.0

### ISSUE THREAD

**Issue by lucasrose** [software-mansion/react-native-reanimated#5792]
### Description

After recently upgrading from reanimated 3.7.1 to 3.8.0, I started getting the following error from the animationBuilder when mounting an Animated.View with an `entering` animation. Specifically, the component looked like this:

```
const test = ({ styles }: Props) => (
    <Animated.View
      style={[tw`p-2 rounded-lg gap-2 mt-2`, containerStyle, styles?.container]}
      entering={FadeIn}
      exiting={FadeOut}
    />
);

```
`getCommonProperties` is operating under the assumption that a style will always be an object type. In the case above, it can be undefined.

A simple change to assign default value resolves the issue
```
 componentStyleFlat = componentStyleFlat.map((style = {}) =>
    'initial' in style
      ? style.initial.value // Include properties of animated style
      : style
  );
```

![image](https://github.com/software-mansion/react-native-reanimated/assets/145227565/fe141a1f-245f-4419-826b-a34cc30d19e8)

### Steps to reproduce

1. Install reanimated 3.8.0
2. Create Animated.View with `entering` animation. Specifically, saw the issue with `FadeIn`

I was not able to reproduce this in snack, but attached an example

### Snack or a link to a repository

https://snack.expo.dev/@lucasrose7/privileged-yellow-pudding

### Reanimated version

3.8.0

### React Native version

0.73.2

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

iPhone 15 Pro - iOS 17.2 Simulator

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Fixed with https://github.com/software-mansion/react-native-reanimated/pull/5784 We'll release it as a patch soon 🫡
