### ISSUE TITLE
Apple privacy declaration

### ISSUE THREAD

**Issue by johnhatvani** [software-mansion/react-native-reanimated#5801]
### Description

Summary

Apple's requirement to document usages of certain Api's is coming into effect May 1. 
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

using these ([here](https://github.com/Wooder/ios_17_required_reason_api_scanner) & [here](https://gist.githubusercontent.com/MarcoEidinger/22feb1588c3d7be41c42853a77e52772/raw/c045e5116d6606722015f7223f8564babd40ccf4/findRequiredReasonAPIUsage.sh)) tools to scan for usages of these API's/symbols 

and there are a couple of results found for reanimated:

```
./node_modules/react-native-reanimated/ios/sensor/ReanimatedSensor.m:                    double currentTime = [[NSProcessInfo processInfo] systemUptime];
./node_modules/react-native-reanimated/ios/sensor/ReanimatedSensor.m:                                         double currentTime = [[NSProcessInfo processInfo] systemUptime];
./node_modules/react-native-reanimated/ios/sensor/ReanimatedSensor.m:                            double currentTime = [[NSProcessInfo processInfo] systemUptime];
./node_modules/react-native-reanimated/ios/sensor/ReanimatedSensor.m:                            double currentTime = [[NSProcessInfo processInfo] systemUptime];
./node_modules/react-native-reanimated/ios/sensor/ReanimatedSensor.m:                                                    double currentTime = [[NSProcessInfo processInfo] systemUptime];
```

```
Used symbols in binary ./Frameworks/RNReanimated.framework/RNReanimated: systemUptime
```

plus some peer dependencies:
```
./node_modules/react-native/Libraries/Image/RCTImageLoader.mm:  return (mach_absolute_time() * tb_info.numer) / tb_info.denom;

```

```
Used symbols in binary ./Frameworks/RCTSettings.framework/RCTSettings: NSUserDefaults
Used symbols in binary ./React-RCTImage/RCTImage.framework/RCTImage: mach_absolute_time
Used symbols in binary ./React-CoreModules/CoreModules.framework/CoreModules: NSUserDefaults
Used symbols in binary ./React-cxxreact/cxxreact.framework/cxxreact: fstat, stat
```

- https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394
- https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401
- https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397

Is this something the team is aware of? or have an ETA for?

### Steps to reproduce

- 

### Snack or a link to a repository

-

### Reanimated version

3.3.0

### React Native version

0.71.15

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by Vivek-rudhva** [comment]
facing the same issue, kindly add privacy manifest file for ios

**Comment by tomekzaw** [comment]
Hey @johnhatvani, thanks for submitting this issue!

> Is this something the team is aware of?

We were not aware of this requirement so thanks again!

Turns out we don't need to know the system uptime; instead of calling `systemUptime` we can just use `CACurrentMediaTime()` which is safe to use without a privacy manifest file.

> or have an ETA for?

I've submitted a PR that resolves this issue (#5819). Once it lands on main, it will be available as nightly (`yarn add react-native-reanimated@nightly`). We can follow up with a stable release (3.9.0) quite soon.

**Comment by james-ovens-eurostar** [comment]
> We can follow up with a stable release (3.9.0) quite soon.

Do you have a timeline for when this might be available?

**Comment by tomekzaw** [comment]
@james-ovens-eurostar We plan to publish 3.9.0 next week.

**Comment by tomekzaw** [comment]
@tdraper-dev Sure, we're just doing some final round of testing for 3.9.0, hopefully should be published tomorrow.
