### ISSUE TITLE
[3.8.1] Typescript - Error: Debug Failure. False expression: Should only get Alias here.

### ISSUE THREAD

**Issue by fadiquader** [software-mansion/react-native-reanimated#5802]
### Description

I was on `3.6.1` version and then I bumped to `3.8.1`.  I get this error when I run `yarn tsc --noEmit` 
![image](https://github.com/software-mansion/react-native-reanimated/assets/23264052/9ba5127d-fa82-4d0e-910a-ec2418e2e43e)

Deps: 
Typescript: 5.1.6
NodeJs: v18.17.1

### Steps to reproduce

1. run `yarn tsc --noEmit` 
2. it fails as you can see in the screenshot above. 

### Snack or a link to a repository

N/A

### Reanimated version

3.6.1

### React Native version

0.72.9

### Platforms

iOS, macOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Device model

N/A

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Without a reproduction, we are unable to provide assistance 😕 I can only recommend clearing the cache and ensuring that all of your dependencies are up to date.
