### ISSUE TITLE
How to evaluate an Animated Value against normal index Value

### ISSUE THREAD

**Issue by igarcido95** [software-mansion/react-native-reanimated#581]
Hello,

I'm trying to evaluate an Animated Value against a normal index value. What I'm trying to do is create an output range array based on the active index (which is the animated Value). What I've tried to do is the following.

```
set(
  state.position,
  interpolate(activeIndexTransition, {
    inputRange: tabs.map((_tab, i) => i),
    outputRange: positions.map((value, index) => {
      cond(eq(activeIndexTransition, index), [state.position], [-1 * value])
    })
  })
),
```

So basically, if current activeIndexTransition equals index, then return the state.position por this given position in the outputrange array, if not return the predefined value. I've also tried to equal the map index to an animated value like this. But it seems it does not work.

`const AnimatedIndex = new Value(index)`

How could I achieve this logic?
Thanks

**Comment by jakub-gonet** [comment]
Hi @igarcido95,

I'm afraid I don't understand what you want to achieve. `interpolate`'s `inputRange` and `outputRange` take an increasing list of numbers, not nodes. Could you describe the animation you want to create?

**Comment by igarcido95** [comment]
Hi @jakub-gonet,

I've created a scrollable header that is translated based on two sources: Y-Position and horizontal scroll. This is what I have right now: [Scrollable header](https://gph.is/g/ZYlb6dJ)

In order to translate the header based on Y Position, I use an activeIndex to detect which section of the screen is active and then interpolate to an X position of the header. 

However, the position of the header can also be modified by scrolling. In that case, I would need that the interpolatation goes from the current position to the next interpolate value. Right now I have this weird behaviour if I scroll the header to a position different than the outputRange value: [Weird behaviour](https://gph.is/g/Zd7yVN2)

If I could compare the activeIndex with the index of the .map I could replace that value within the output range with the current position. Does it make sense? Do you think in another workaround?

**Comment by jakub-gonet** [comment]
So if I understand correctly:
the header is scrolled to some position based by where you scrolled in the list and by scrolling header itself.

You want to map items scroll position to some position in the header and I'm confused here: "the interpolatation goes from the current position to the next interpolate value", how should it work exactly? I think scrolling header should override automatic scroll in some way.

And, you're animating the entire header or that green selector? Some [snack](https://snack.expo.io/) would be very helpful.

**Comment by igarcido95** [comment]
Sorry @jakub-gonet, I know it's a little but difficult to explain.

The header uses a PanGestureHandler not a Scrollview, as I need that two sources of movement affect the same value.

The thing is that het interpolation has a set of output values based on X position of each category of the header [50, 100, 160, ...]. The tricky part is you can modify the position of the header doing a scroll. So in that case, the interpolation from i.e 50 to 100 position can be wrong, as you are not in 50 but in 300 if you have scrolled manually. That's why I'm trying to replace the output value for a given input for the dynamic value current.state.

Here is a snack so you can take a look:  [Snack](https://snack.expo.io/BJpRruFXI )

**Comment by jakub-gonet** [comment]
Sorry that I left you hanging, do you still face this issue or you managed to solve that?

**Comment by igarcido95** [comment]
Yes @jakub-gonet, still facing the issue. Really stuck on how to update the outputRange array based on activeIndexTransition value.

**Comment by jakub-gonet** [comment]
Your snack isn't working, unfortunately.
I think it'd be needed to basically recreate your use case because I don't know yet how to easily solve your problem.

I'll keep it open for now though.

**Comment by jakub-gonet** [comment]
Closing due to no response.
