### ISSUE TITLE
getRelativeCoords not work correctly on android

### ISSUE THREAD

**Issue by doublelam** [software-mansion/react-native-reanimated#5810]
### Description

```
const inRect = useCallback((point: Point, rect: Rect) => {
        'worklet';

        const coords = getRelativeCoords(containerRef, point.x, point.y);
...
```
```
 const panGesture = Gesture.Pan()
        .onBegin(() => {
            runOnJS(onBegin)();
        })
        .onUpdate((e) => {
            if (!visible) { return; }
            if (inRect({ x: e.absoluteX, y: e.absoluteY }, trashNode)) {
...
```
the coords is expected to be a relative value but got an absolute value. 
not working on android, works well on ios.

### Steps to reproduce

as official example

### Snack or a link to a repository

null

### Reanimated version

3.5.4 - 3.8.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
Hey @doublelam ! Thanks for submitting the issue but there is no *****complete repro***** - please attach one if You have time. Meanwhile, I created a small snippet that returns correctly relative coords for both iOS and Android - take a look into it - maybe you forgot about something? Let me know if it helps!

<details><summary>Code</summary>

``` TYPESCRIPT
import React from 'react';
import Animated, {
  useAnimatedRef,
  getRelativeCoords,
} from 'react-native-reanimated';
import { StyleSheet } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';

export default function EmptyExample() {
  const aref = useAnimatedRef();

  const panGesture = Gesture.Pan().onEnd((event) => {
    const coords = getRelativeCoords(aref, event.absoluteX, event.absoluteY);
    console.log(coords);
  });

  return (
    <Animated.View ref={aref}>
      <GestureDetector gesture={panGesture}>
        <Animated.View style={styles.box} />
      </GestureDetector>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  box: { width: 100, height: 100, backgroundColor: 'pink' },
});

```
</details>

**Comment by szydlovsky** [comment]
Hi @doublelam - indeed the function returns wrong values - it should be fixed in https://github.com/software-mansion/react-native-reanimated/pull/5926.

**Comment by szydlovsky** [comment]
@doublelam the fix got merged - it should be available in the next nightly build (around 2AM CEST time) - see [npm page](https://www.npmjs.com/package/react-native-reanimated?activeTab=versions)
