### ISSUE TITLE
Call useAnimatedKeyboard hook breaks screen area

### ISSUE THREAD

**Issue by TomCorvus** [software-mansion/react-native-reanimated#5811]
### Description

Hello,

On my project, I call `useAnimatedKeyboard` hook to get keyboard height and push my content accordingly with an animated component, but I notice that calling this hook breaks app display area. In the repo, I hide status bar to make the problem more visible. Comment the hook call, and the problem is fixed.

![share_1657837725477601185](https://github.com/software-mansion/react-native-reanimated/assets/3451011/b807a7a6-64fa-43b9-b728-ac3bed067a5c)

On the repo, I installed `[react-native-avoid-softinput](https://github.com/mateusz1913/react-native-avoid-softinput)` because I have the same problem with the `setShouldMimicIOSBehavior`hook. Only on Android too.

### Steps to reproduce

1. Init a fresh project
2. Install REA
3. call `useAnimatedKeyboard ` hook

### Snack or a link to a repository

https://github.com/TomCorvus/RNSAV

### Reanimated version

3.8.1

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

V8

### Workflow

React Native

### Architecture

None

### Build type

Release app & dev bundle

### Device

Real device

### Device model

Google Pixel 7

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@TomCorvus @kesha-antonov can you please check if #5851 resolves the problem?

**Comment by fax1ty** [comment]
How about navigation bar? @TomCorvus 

> When `isStatusBarTranslucentAndroid` is true **it applies bottom padding according to the navigation inset** and sets top margin to 0.

What if I want to fill up the whole screen?

**Comment by TomCorvus** [comment]
Not sure about that but if you configure your manifest and set full screen mode, there is no bottom padding because your navigation inset doesn't exist.

**Comment by fax1ty** [comment]
But what if I want to have a bottom navigation, but have the content underneath it
@piaskowyk Is it possible to make `isNavigationBarTranslucentAndroid`?

**Comment by ShootingStar91** [comment]
> `useAnimatedKeyboard({ isStatusBarTranslucentAndroid: true });` fix the problem.

This did not fix it on android when in landscape mode - content goes below the android 3 button menu

**Comment by ShootingStar91** [comment]
> > But what if I want to have a bottom navigation, but have the content underneath it [@piaskowyk](https://github.com/piaskowyk) Is it possible to make `isNavigationBarTranslucentAndroid`?
> 
> For fullscreen layouts:
> 
> ```
> const keyboard = useAnimatedKeyboard({
>     isStatusBarTranslucentAndroid: true,
>     isNavigationBarTranslucentAndroid: true,
> });
> ```
> 

Is there a similar solution for landscape mode? Calling the hook breaks landscape mode safe area on android - when the 3-button menu is open on the left, the login inputs go below it.
