### ISSUE TITLE
ConcurrentModificationException crash on Android

### ISSUE THREAD

**Issue by Vepsur** [software-mansion/react-native-reanimated#5822]
### Description

I got a crash error in my Sentry in the production version of the app on Android

Sentry report:

ConcurrentModificationException java.util.HashMap$HashIterator in nextNode
mechanism: UncaughtExceptionHandler

Stack trace:
```
java.util.HashMap$HashIterator in nextNode at line 1574
java.util.HashMap$ValueIterator in next at line 1602
com.swmansion.reanimated.keyboard.KeyboardAnimationManager in notifyAboutKeyboardChange at line 44
com.swmansion.reanimated.keyboard.KeyboardAnimationManager$$ExternalSyntheticLambda0 in call at line 2
com.swmansion.reanimated.keyboard.WindowsInsetsManager in onApplyWindowInsetsListener at line 63
com.swmansion.reanimated.keyboard.WindowsInsetsManager in $r8$lambda$Gx1x4Lxu9gvvZb85XEKpmqU242U
com.swmansion.reanimated.keyboard.WindowsInsetsManager$$ExternalSyntheticLambda2 in onApplyWindowInsets at line 2
androidx.core.view.ViewCompat$Api21Impl$1 in onApplyWindowInsets at line 4858
android.view.View in dispatchApplyWindowInsets at line 12341
android.view.ViewGroup in dispatchApplyWindowInsets at line 7868
android.view.ViewRootImpl in dispatchApplyInsets at line 3683
android.view.ViewRootImpl in performTraversals at line 3963
android.view.ViewRootImpl in doTraversal at line 3248
android.view.ViewRootImpl$TraversalRunnable in run at line 11206
android.view.Choreographer$CallbackRecord in run at line 1650
android.view.Choreographer$CallbackRecord in run at line 1659
android.view.Choreographer in doCallbacks at line 1129
android.view.Choreographer in doFrame at line 1055
android.view.Choreographer$FrameDisplayEventReceiver in run at line 1622
android.os.Handler in handleCallback at line 958
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loopOnce at line 230
android.os.Looper in loop at line 319
android.app.ActivityThread in main at line 8893
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 608
com.android.internal.os.ZygoteInit in main at line 1103
```

I faced this bug in the dev environment. I solved it in debug mode on my Android via the created async hook, which waits while the keyboard closes and only then navigates to another screen.
But I got the error in my Sentry after releasing a new version with fixes, so I missed something.

P.S. I also suggest that can be related to [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller) or [react-native-screens](https://github.com/software-mansion/react-native-screens) enableFreeze(true) and will continue my investigation

22-mar updates: 
- It happens only if u using a top/bottom bar RN navigation
- I reproduce it in our app if u navigate on the top bar navigator and immediately tap on text input/area
- I fixed it by adding ["lazy"](https://reactnavigation.org/docs/material-top-tab-navigator/#lazy) property in the stack navigator, but can not be completely sure that it will fix in all cases and devices

5-apr updates:
- It's not an issue of the tab navigation
- It's an issue of using the `useAnimatedKeyboard` hook inside the items of `FlatList`
- I created a reproduction repository and added a link to it

### Steps to reproduce

1. Tap on the `Navigate to profile` button
2. Immediately after navigation, tap on text input
3. The app should crash most of the time

1. Tap on the `Navigate to profile` button
2. After navigation, tap on text input
3. While the keyboard is open, try scrolling `FlatList`
4. The app should crash often enough

### Snack or a link to a repository

[reanimated-android-crash-example](https://github.com/Vepsur/reanimated-android-crash-example)

### Reanimated version

3.8.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hi @Vepsur, thanks for reporting this issue. It looks like something related to `useAnimatedKeyboard` which we have recently refactored. Assigning our keyboard expert @piaskowyk.

**Comment by Vepsur** [comment]
Here are a few updates about the behavior of the crash:

- It happens only if u using a top/bottom bar RN navigation
- I reproduce it in our app if u navigate on the top bar navigator and immediately click on text input/area
- I fixed it by adding ["lazy"](https://reactnavigation.org/docs/material-top-tab-navigator/#lazy) property in the stack navigator, but can not be completely sure that it will fix in all cases and devices

And I try to create a separate reproduction repository for that issue

**Comment by solitarysp** [comment]
I also received the same error.

**Comment by Vepsur** [comment]
Here are a few updates about the behavior of the crash:
- It's not an issue of the tab navigation
- It's an issue of using the `useAnimatedKeyboard` hook inside the item of `FlatList`
- I created a reproduction repository and added a link to it
- I will update the reproducing steps in the description

**Comment by Vepsur** [comment]
![android-keyboard-renimated-crash (1)](https://github.com/software-mansion/react-native-reanimated/assets/103031604/4337cc69-f69c-437c-88bf-cd71d3b7b1f9)
![android-keyboard-renimated-crash (2)](https://github.com/software-mansion/react-native-reanimated/assets/103031604/990f3570-fc18-43dd-a3b2-dca17eebff65)

**Comment by Vepsur** [comment]
![android-keyboard-renimated-crash (1)](https://github.com/software-mansion/react-native-reanimated/assets/103031604/d490b584-78da-4be2-92fe-15ea9e58f2cb)
![android-keyboard-renimated-crash (2)](https://github.com/software-mansion/react-native-reanimated/assets/103031604/ece1dbb6-e723-4e60-af3f-16bc2d7a3338)

**Comment by Vepsur** [comment]
![android-keyboard-renimated-crash (1)](https://github.com/software-mansion/react-native-reanimated/assets/103031604/4743ecaf-0300-4318-b1a5-6a15b0b3c8bb)
![android-keyboard-renimated-crash (2)](https://github.com/software-mansion/react-native-reanimated/assets/103031604/b6b583a0-8ff9-40dd-bce3-78211b311622)

**Comment by tomekzaw** [comment]
cc @maciekstosio
