### ISSUE TITLE
Custom Animation with "withDelay" cause strange behavior

### ISSUE THREAD

**Issue by renochew** [software-mansion/react-native-reanimated#5826]
### Description

Please refer to the snacks. There is 2 version of custom enter animation, one with a withDelay, one without. The one without delay working fine, you can see smooth transition of color. But the other version didn't work properly

### Steps to reproduce

1. Open Snack
2. Click "Add Element" to see the problematic enter animation

### Snack or a link to a repository

https://snack.expo.dev/@renochew/thoughtful-orange-croissant?platform=android

### Reanimated version

3.6.2

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi @renochew!
It looks that you have provided wrong snack, in the attached example you don't have any delay, nor custom animation. In fact you don't import `react-native-reanimated` at all.

**Comment by renochew** [comment]
Sorry @Latropos, stupid me, I forgot to save the snack..

The linked snack should work now.

Thanks.

**Comment by szydlovsky** [comment]
Hello again @renochew, the fix got merged and it should be available in the next nightly build of Reanimated (around 2AM CEST time) - see [npm page](https://www.npmjs.com/package/react-native-reanimated?activeTab=versions).
