### ISSUE TITLE
Scrollview event on android

### ISSUE THREAD

**Issue by Daavidaviid** [software-mansion/react-native-reanimated#585]
Hi,
Does anyone got it to work smoothly on Android ? On iOS no problem, but android always gives me a lots of lagging.

```
...
const scrollY = new Value(0);
...

<>
  <Header y={scrollY} /> // the height of Header is changing accordingly with scrollY
  <Animated.ScrollView onScroll={onScroll({y: scrollY})} scrollEventThrottle={16}>
     ...
  </Animated.ScrollView>
</>
```
I don't know where it might come from, as every example I find on the internet seems to work perfectly...
Ex: 
https://blog.bam.tech/developer-news/an-introduction-to-react-native-reanimated (only iOS)

Any idea ?

**Comment by ardyfeb** [comment]
Same here

**Comment by thatcharles** [comment]
Have you tried this?
```javascript
onScroll={
    event(
        [
            {nativeEvent:{contentOffset:{y:scrollY}}}
        ]
    )
}
```

**Comment by Brunoalcau** [comment]
in the react-native-redash lib function, onScroll has been renamed to onScrollEvent

**Comment by jakub-gonet** [comment]
This is connected to the `react-native-redash` lib. Please submit bug report there.

**Comment by ardyfeb** [comment]
> This is connected to the `react-native-redash` lib. Please submit bug report there.

I use `react-native-reanimated` not `react-native-redash`
