### ISSUE TITLE
`useAnimatedKeyboard` height visually lags behind actual keyboard height

### ISSUE THREAD

**Issue by BitPhinix** [software-mansion/react-native-reanimated#5853]
### Description

See https://github.com/software-mansion/react-native-reanimated/issues/4324#issuecomment-1497308987, mainly creating this issue for more visibility of the issue

https://github.com/software-mansion/react-native-reanimated/assets/13185548/3f461611-9b69-429f-9fdd-1c222ee9330f

### Steps to reproduce

1. use `useAnimatedKeyboard`

### Snack or a link to a repository

https://github.com/terrysahaidak/UseAnimatedKeyboardBug1

### Reanimated version

3.6.3

### React Native version

0.73.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @BitPhinix, thanks for reporting this issue.

I believe the problem should be gone after we merged #5705 from @piaskowyk who did some clever math to overcome iOS limitations.

Please upgrade to Reanimated >= 3.8.0 (current latest is 3.8.1) and see if it helps.

Closing the issue now but feel free to re-open it.
