### ISSUE TITLE
Drawer Error: Cannot read property 'isConfigured' of undefined

### ISSUE THREAD

**Issue by Hwang-YoonJi** [software-mansion/react-native-reanimated#5856]
### Description

I'm trying to use drawer navigation, but I get an error.

ERROR  TypeError: Cannot read property 'isConfigured' of undefined

This error is located at:
in DrawerViewBase (created by DrawerView)
in RNGestureHandlerRootView (created by GestureHandlerRootView)
in GestureHandlerRootView (created by DrawerView)
in RNCSafeAreaProvider (created by SafeAreaProvider)
in SafeAreaProvider (created by SafeAreaProviderCompat)
in SafeAreaProviderCompat (created by DrawerView)
in DrawerView (created by DrawerNavigator)
in PreventRemoveProvider (created by NavigationContent)
in NavigationContent
in Unknown (created by DrawerNavigator)
in DrawerNavigator (created by Navigation)
in EnsureSingleNavigator
in BaseNavigationContainer
in ThemeProvider
in NavigationContainerInner (created by Navigation)
in Navigation (created by App)
in RCTView (created by View)
in View (created by App)
in App
in RCTView (created by View)
in View (created by AppContainer)
in RCTView (created by View)
in View (created by AppContainer)
in AppContainer
in safety_guide_new(RootComponent), js engine: hermes

import React from 'react';
import {createDrawerNavigator} from '@react-navigation/drawer';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';
import Home from '../screens/home';
import Settings from '../screens/settings';
import Header from '../components/Header';

const Drawer = createDrawerNavigator();
const Stack = createStackNavigator();

const HomeStack = () => {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="Home"
        component={Home}
        options={{
          header: () => <Header />,
        }}
      />
    </Stack.Navigator>
  );
};

const SettingsStack = () => {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="Settings"
        component={Settings}
        options={{
          header: () => <Header />,
        }}
      />
    </Stack.Navigator>
  );
};

const Navigation: React.FC = () => {
  return (
    <NavigationContainer>
      <Drawer.Navigator>
        <Drawer.Screen name="Home" component={HomeStack} />
        <Drawer.Screen name="Settings" component={SettingsStack} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
};

export default Navigation;

<package.json>
 "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^3.8.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.30.1",

<babel.config.js>
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};

### Steps to reproduce

npm run android

### Snack or a link to a repository

https://stackoverflow.com/questions/77879924/react-native-drawer-cannot-read-property-isconfigured-of-undefined-reanim

### Reanimated version

3.8.1

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
Hey @Hwang-YoonJi 👋 I tried reproducing the issue and it seems to not occur for me. Did you try rebuilding all the dependencies? (deleting the `node_modules` and installing dependencies again, you might even try `git clean -xdf` as it cleans all untracked/ignored files in the project and might take care of some troublesome caches).

**Comment by vishalsohani27** [comment]
hey, @Hwang-YoonJi 
i am getting same error.
'Failed to create worklet' and 'can not read property isconfigured'
while implementing Drawer.
i have been added plugin details to babel.config.js also, please let me know, if you found any solution.

**Comment by ShahidJanAmin** [comment]
Hey, @Hwang-YoonJi 
I am getting the same error. 'Cannot read property 'isConfigured' of undefined' or 'Failed to create a worklet.'
I rebuild and also cleared the cache still I face problem. If you found any  solution Please shear with us.

**Comment by Dilawar4Ali** [comment]
> ### Description
> I'm trying to use drawer navigation, but I get an error.
> 
> ERROR TypeError: Cannot read property 'isConfigured' of undefined
> 
> This error is located at: in DrawerViewBase (created by DrawerView) in RNGestureHandlerRootView (created by GestureHandlerRootView) in GestureHandlerRootView (created by DrawerView) in RNCSafeAreaProvider (created by SafeAreaProvider) in SafeAreaProvider (created by SafeAreaProviderCompat) in SafeAreaProviderCompat (created by DrawerView) in DrawerView (created by DrawerNavigator) in PreventRemoveProvider (created by NavigationContent) in NavigationContent in Unknown (created by DrawerNavigator) in DrawerNavigator (created by Navigation) in EnsureSingleNavigator in BaseNavigationContainer in ThemeProvider in NavigationContainerInner (created by Navigation) in Navigation (created by App) in RCTView (created by View) in View (created by App) in App in RCTView (created by View) in View (created by AppContainer) in RCTView (created by View) in View (created by AppContainer) in AppContainer in safety_guide_new(RootComponent), js engine: hermes
> 
> import React from 'react'; import {createDrawerNavigator} from '@react-navigation/drawer'; import {NavigationContainer} from '@react-navigation/native'; import {createStackNavigator} from '@react-navigation/stack'; import Home from '../screens/home'; import Settings from '../screens/settings'; import Header from '../components/Header';
> 
> const Drawer = createDrawerNavigator(); const Stack = createStackNavigator();
> 
> const HomeStack = () => { return ( <Stack.Navigator> <Stack.Screen name="Home" component={Home} options={{ header: () =>
> 
> ,
> }}
> />
> </Stack.Navigator>
> );
> };
> const SettingsStack = () => { return ( <Stack.Navigator> <Stack.Screen name="Settings" component={Settings} options={{ header: () =>
> 
> ,
> }}
> />
> </Stack.Navigator>
> );
> };
> const Navigation: React.FC = () => { return ( <Drawer.Navigator> <Drawer.Screen name="Home" component={HomeStack} /> <Drawer.Screen name="Settings" component={SettingsStack} /> </Drawer.Navigator> ); };
> 
> export default Navigation;
> 
> <package.json> "@react-navigation/drawer": "^6.6.15", "@react-navigation/native": "^6.1.17", "@react-navigation/stack": "^6.3.29", "react": "18.2.0", "react-native": "0.73.6", "react-native-gesture-handler": "^2.16.0", "react-native-push-notification": "^8.1.1", "react-native-reanimated": "^3.8.1", "react-native-safe-area-context": "^4.9.0", "react-native-screens": "^3.30.1",
> 
> <babel.config.js> module.exports = { presets: ['module:@react-native/babel-preset'], plugins: ['react-native-reanimated/plugin'], };
> 
> ### Steps to reproduce
> npm run android
> 
> ### Snack or a link to a repository
> https://stackoverflow.com/questions/77879924/react-native-drawer-cannot-read-property-isconfigured-of-undefined-reanim
> 
> ### Reanimated version
> 3.8.1
> 
> ### React Native version
> 0.73.6
> 
> ### Platforms
> Android
> 
> ### JavaScript runtime
> None
> 
> ### Workflow
> None
> 
> ### Architecture
> None
> 
> ### Build type
> None
> 
> ### Device
> Noneg 
> 
> ### Device model
> _No response_
> 
> ### Acknowledgements
> Yes

Hi i am also having the same issue. Installed the latest packages "@react-navigation/drawer": "^6.6.15", and     "react-native-reanimated": "^3.8.1",
I did add the    plugins: ["react-native-reanimated/plugin", ], in babel.config.js and also ran npm start -- --reset-cache but still there is error. Screenshot of error are attached. If @Hwang-YoonJi you found the solution please share.
![error 1](https://github.com/software-mansion/react-native-reanimated/assets/119816862/67405788-3495-4eca-9004-be9fd4ced15d)
![error 2](https://github.com/software-mansion/react-native-reanimated/assets/119816862/a8c74ac4-7873-43ef-a5d6-89cbf4cedce4)

**Comment by ejmdenham** [comment]
Worked for me. 
1. Delete node_modules
2. rerun npm install
3. Add **plugins: [ "react-native-reanimated/plugin", ],**  to your babel.config.js (in the backets)
4. npm start -- --reset-cache

**Comment by CarlosAlbertoTI** [comment]
> Worked for me.
> 
> 1. Delete node_modules
> 2. rerun "npm install"
> 3. Add >> **plugins: [ "react-native-reanimated/plugin", ],**  to your babel.config.js (in the backets)
> 4. npm start -- --reset-cache

This solution didn't work for me

**Comment by TSD404** [comment]
> Worked for me.
> 
> 1. Delete node_modules
> 2. rerun "npm install"
> 3. Add >> **plugins: [ "react-native-reanimated/plugin", ],**  to your babel.config.js (in the backets)
> 4. npm start -- --reset-cache

this solution didn't work

**Comment by vkarkhanis** [comment]
In my case the problem was I was using yarn and I was using yarn start -- --reset-cache instead of yarn start --reset-cache
Using the right command to reset cache worked for me

https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting/#mismatch-between-javascript-code-version-and-reanimated-babel-plugin-version

**Comment by szydlovsky** [comment]
@TSD404 @CarlosAlbertoTI @Dilawar4Ali hey guys could you try [this fix using yarn](https://github.com/software-mansion/react-native-reanimated/issues/5856#issuecomment-2118767624)?

**Comment by TSD404** [comment]
> > Worked for me.
> > 
> > 1. Delete node_modules
> > 2. rerun "npm install"
> > 3. Add >> **plugins: [ "react-native-reanimated/plugin", ],**  to your babel.config.js (in the backets)
> > 4. npm start -- --reset-cache
> 
> this solution didn't work

I just created a new project and now its working fine. Not sure what was wrong in the previous project

**Comment by ark-fabtechsol** [comment]
Anyone encountering this issue , This issue is related to package compatibility with drawer package. So what you need to do is to downgrade the version of reanimated, delete node modules and yarn lock , reinstall them, reinstall pods after cleaning them and then rebuild the application. This will be ressolved .

**Comment by fahad-Ahmad-fabtechsol** [comment]
@ark-fabtechsol this was the most authentic solution i have found.

**Comment by Cigal** [comment]
this  the solution that worked for me ..


module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};

 I installed  yarn ..
1. npm install --global yarn
2.  yarn start --reset-cache.

this worked for me

**Comment by AkhaniDarshan179** [comment]
> 4\. npm start -- --reset-cache

Thanks bro

**Comment by muralivegesna1381** [comment]
> Worked for me.
> 
> 1. Delete node_modules
> 2. rerun "npm install"
> 3. Add >> **plugins: [ "react-native-reanimated/plugin", ],**  to your babel.config.js (in the backets)
> 4. npm start -- --reset-cache

works for me follow exactly what he said. 3rd step need to be add after step1 and step2.

**Comment by Zara3574** [comment]
> 3\. plugins: [ "react-native-reanimated/plugin", ],

Work for me

**Comment by zeeshan9** [comment]
I am getting into same issues can someone. please share the compatible version of react-native-reanimated & react-native-gesture-handler or drawer I triend the above solution but didn't work for me. so i think i need to get correct version if anyone share the latest compatible version that works for them.

Error is: **cannot read property 'isConfigured' of undefined**

navigation packages version 
    "react-native-reanimated": "^3.15.1",
    "react-native-gesture-handler": "^2.18.1",

    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "react-native-screens": "^3.33.0",

**Comment by zeeshan9** [comment]
I found the compatible packages:
    "react-native-gesture-handler": "^2.17.1",
    "react-native-reanimated": "^3.10.1",

**Comment by rushibhumkar11** [comment]
> Worked for me.
> 
> 1. Delete node_modules
> 2. rerun "npm install"
> 3. Add >> **plugins: [ "react-native-reanimated/plugin", ],**  to your babel.config.js (in the backets)
> 4. npm start -- --reset-cache

worked for me

**Comment by Alatius** [comment]
I struggled with this problem as I upgraded to RN 0.76. Tried any combinations of different package versions, etc., and nothing worked. Finally, I narrowed it down to some changes I had made to my AppDelegate.mm. So, if you have modified it, try going back to the default AppDelegate for your React Native version, and take it from there!
In my case, I had created a custom view controller (for the purpose of overriding some view controller methods such as  prefersHomeIndicatorAutoHidden and preferredScreenEdgesDeferringSystemGestures):
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  CustomViewController *rootViewController = [CustomViewController new];
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}
```
This approach ultimately resulted in "Cannot read property 'isConfigured' of undefined" somehow.

**Comment by cuongtrong193** [comment]
After half a day I found a way to fix the error, for me the problem was solved when installing the correct version of the libraries
```
"dependencies": {
……………
"react-native-gesture-handler": "2.15.0”,
"react-native-reanimated": "3.7.0",
"react-native-screens": "3.29.0",
……………
}
"devDependencies": {
………………
"@babel/core": "7.23.9",
"@babel/preset-env": "7.23.9",
"@babel/runtime": "7.23.9",
"@react-native/babel-preset": "0.73.21"
……………
}
```

**Comment by davidfeldt** [comment]
If you are getting this mismatch error on iOS builds using Cocoapods, I found a solution.  After trying endless iterations of removing node_modules, clearing yarn.lock and rebuilding app, the following worked for me:

1.  pod cache clean --all
2. npx pod-install to rebuild pods
3. yarn install
4. ...

The pod cache was the problem all along.

Hope this helps some of you!
