### ISSUE TITLE
useCode ignores a state value change

### ISSUE THREAD

**Issue by alexwasner** [software-mansion/react-native-reanimated#586]
I'm not sure I fully understand how `useCode` is meant to work. I have a scrollview that has a y contentoffset animated value as seen below
``` 
const translateYRaw = useMemoOne(() => new Value(0));
  const gestureState = useMemoOne(() => new Value(State.UNDETERMINED));
  const onScroll = useMemoOne(() =>
    event([
      {
        nativeEvent: {
          contentOffset: { y: translateYRaw },
          state: gestureState,
        },
      },
    ]),
  );

  const hasPassed = useMemoOne(()=>new Value(0));

  const state = {
    time: new Value(0),
    position: new Value(0),
    velocity: new Value(0),
    finished: new Value(0),
  };
  const { onLayout, ...layout } = useLayout();
  const [height, setHeight] = useRef(window.height);
  useEffect(() => {
    setHeight(layout.height);
  }, [layout]);
  useCode(() => {
    return block([
      debug('hasPassed',1),
      debug('currentRaw',translateYRaw),
      set(
        someValue,
        block([
          cond(
            greaterOrEq(translateYRaw, height),
            set(hasPassed, 1),
            set(hasPassed, 0),
          ),
          state.position,
        ]),
      ),
    ]);
  }, []);

  return (
    <NativeViewGestureHandler
      ref={scrollPosition.scrollRef}
      simultaneousHandlers={[panRef, masterRef]}>
      <AScrollViewContainer
        {...{
          onScroll,
        }}
      </ScrollViewContainer>
    </NativeViewGestureHandler>
```

The calculations for hasPassed are based on the window height, not the new value after the layout height changes and updates that value. If I pass it in as a param to `[layout.height, translateYRaw, gestureState, hasPassed....` it only calls `useCode` a couple times and doesn't stay actively watching. WHen I scroll, it never calls those debugs. 

How do I get it to use the correct height value but also continue to stay active like it does when there are no deps in the `[]` array

**Comment by alexwasner** [comment]
For future devs reading this, check the value of each of the animated `__nodeID` as even though they were memoized, a parent element was triggering a re-render and the animated value was changing. I'm still not sure why, but 🤷‍♂

**Comment by JackShannon** [comment]
Hi @alexwasner ,

Same problem, how did you fix this since memoizing doesn't work?

**Comment by Mbompr** [comment]
Hello,
I am likely facing the same issue, could you elaborate a bit more ? At which point do you check the value of `__nodeID` and what do you trigger when it changes ?
Thanks !

**Comment by alexwasner** [comment]
@Mbompr I don't remember exactly, but I checked the value at init and then potentially some loop cycle or re-render. The __nodeID was changing, so I prevented the parent's unneeded re-render and it solved my issue. As mentioned, still not sure if this is the intended behavior of `useCode` or if it's a bug that I was able to work around.
