### ISSUE TITLE
`Duplicate shared tag "sharedTag" on the same screen` in 3.9.0-rc.0

### ISSUE THREAD

**Issue by bglgwyng** [software-mansion/react-native-reanimated#5871]
### Description

After updating the Reanimated library to version 3.9.0-rc.0 in my project, the shared element transition began malfunctioning, displaying the error: `[Reanimated] Duplicate shared tag 'tag' on the same screen.` However, this issue was not present in version 3.8.1, where the same code operated correctly.

### Steps to reproduce

run [the example app](https://docs.swmansion.com/react-native-reanimated/docs/shared-element-transitions/overview#examples)

### Snack or a link to a repository

https://github.com/bglgwyng/reanimated-bug-reproducer

### Reanimated version

3.9.0-rc.0

### React Native version

0.73.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by bglgwyng** [comment]
the repo link is added.

**Comment by tjzel** [comment]
Hi @bglgwyng. When using Expo Go you shouldn't install packages that are not included in Expo SDK. I tried running your App with `prebuild` and haven't encountered any errors.
