### ISSUE TITLE
iOS privacy manifest

### ISSUE THREAD

**Issue by gkasireddy202** [software-mansion/react-native-reanimated#5878]
### Description

I am using the "react-native-reanimated": "^1.13.4" in my project react-native version n:0.68.7.
Apple needs the API manifest file reason for this mach_absolute_time().
Found potentially required reason API usage 'mach_absolute_time()' in './node_modules/react-native-reanimated/ios/Transitioning/REATransitionAnimation.m'
Line numbers: 47

### Steps to reproduce

Found potentially required reason API usage 'mach_absolute_time()' in './node_modules/react-native-reanimated/ios/Transitioning/REATransitionAnimation.m'
Line numbers: 47

### Snack or a link to a repository

./node_modules/react-native-reanimated/ios/Transitioning/REATransitionAnimation.m

### Reanimated version

1.13.4

### React Native version

0.68.7

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

iOS simulator

### Device model

iOS Simulator 15 Pro Max

### Acknowledgements

Yes

**Comment by gkasireddy202** [comment]
There is no issue with the code.
Need API type and reason for usage 'mach_absolute_time()'.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

**Comment by tomekzaw** [comment]
Closing this issue as Reanimated v1 is no longer maintained.
