### ISSUE TITLE
Unable to run on iOS 

### ISSUE THREAD

**Issue by gkasireddy202** [software-mansion/react-native-reanimated#5882]
### Description

I installed the   "react-native-reanimated": "^3.8.1" in my project and unable to run the iOS build.Getting below error.
node_modules/react-native-reanimated/apple/LayoutReanimation/REAScreensHelper.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods')

### Steps to reproduce

I installed the   "react-native-reanimated": "^3.8.1", in my project using below steps.
npm install react-native-reanimated
  module.exports = {
    presets: [
      ... // don't add it here :)
    ],
    plugins: [
      ...
      'react-native-reanimated/plugin',
    ],
  };
npm start -- --reset-cache

pod install

### Snack or a link to a repository

n/a

### Reanimated version

3.8.1

### React Native version

0.73.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

iOS Simulator 15 Pro Max

### Acknowledgements

Yes

**Comment by gkasireddy202** [comment]
The GitHub repository is private and it belongs to my company.

**Comment by tjzel** [comment]
Hi @gkasireddy202. The recommended way of installing the pods in React Native currently is

`bundle install && bundle exec pod install`. Please check if it fixes your issue.

**Comment by gkasireddy202** [comment]
> Hi @gkasireddy202. The recommended way of installing the pods in React Native currently is
> 
> `bundle install && bundle exec pod install`.
> 
> Please check if it fixes your issue.

@tjzel  - Thanks for your reply.

bundle install && bundle exec pod install.
Unable to run the build.
Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/REAScreensHelper.o
node_modules/react-native-reanimated/apple/LayoutReanimation/REAScreensHelper.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods'

**Comment by szydlovsky** [comment]
@gkasireddy202 Hi! Have you tried resetting your pods and xcode cache?
- pods: run `pod deintegrate` in a directory with `Pods` catalog
- xcode: proceed to upper window menu `Product` -> `Clean Build Folder`
When clean finishes, you can try building the pods the same way @tjzel suggested. Sometimes some build artifacts may persist in pods/xcode directories and throw some strange errors.

**Comment by gkasireddy202** [comment]
> @gkasireddy202 Hi! Have you tried resetting your pods and xcode cache?
> 
> * pods: run `pod deintegrate` in a directory with `Pods` catalog
> * xcode: proceed to upper window menu `Product` -> `Clean Build Folder`
>   When clean finishes, you can try building the pods the same way @tjzel suggested. Sometimes some build artifacts may persist in pods/xcode directories and throw some strange errors.

I tried with pod install and clean build folder in Xcode. I will try with pod disintegrate.

**Comment by szydlovsky** [comment]
Hey @gkasireddy202, any updates? Has the clean helped?

**Comment by gkasireddy202** [comment]
> Hey @gkasireddy202, any updates? Has the clean helped?

@szydlovsky - Still getting the same error. Does any other npm package depend on this react-native-reanimated npm?

**Comment by szydlovsky** [comment]
@gkasireddy202  You can find a complete list of packages dependent on reanimated [here](https://www.npmjs.com/package/react-native-reanimated?activeTab=dependents).

**Comment by gkasireddy202** [comment]
> @gkasireddy202 You can find a complete list of packages dependent on reanimated [here](https://www.npmjs.com/package/react-native-reanimated?activeTab=dependents).

I am using the following listed packages in my project.

{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@bam.tech/react-native-image-resizer": "^3.0.7",
    "@bugsnag/react-native": "^7.20.2",
    "@el173/react-native-passcode-auth": "^1.0.1",
    "@ismnoiet/react-native-dropdown": "0.0.2",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^5.9.10",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-native-cookies/cookies": "^6.2.1",
    "accounting": "^0.4.1",
    "axios": "^0.21.4",
    "base-64": "^1.0.0",
    "buffer": "^6.0.3",
    "create-react-class": "^15.7.0",
    "expo-local-authentication": "^9.5.0",
    "install": "^0.13.0",
    "intl": "^1.2.5",
    "mock-async-storage": "^2.2.0",
    "mockstorage": "^0.1.4",
    "moment": "^2.30.1",
    "moment-timezone": "^0.5.43",
    "native-base": "^2.15.2",
    "npm": "^6.14.18",
    "pdf-to-base64": "^1.0.3",
    "querystring": "^0.2.1",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.73.2",
    "react-native-alert-pro": "^1.1.2",
    "react-native-calendar-events": "^2.2.0",
    "react-native-calendars": "^1.1303.0",
    "react-native-device-info": "^7.4.0",
    "react-native-dialog": "^6.2.0",
    "react-native-document-picker": "^4.3.0",
    "react-native-drop-down-item": "^1.1.0",
    "react-native-elements": "^2.3.2",
    "react-native-file-viewer": "^2.1.5",
    "react-native-floating-label-text-image-input": "^1.0.1",
    "react-native-floating-labels": "^1.1.9",
    "react-native-fs": "^2.20.0",
    "react-native-geocoding": "^0.4.0",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-google-maps-directions": "^2.1.1",
    "react-native-htmlview": "^0.16.0",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-crop-picker": "^0.40.3",
    "react-native-image-progress": "1.1.1",
    "react-native-indicators": "^0.17.0",
    "react-native-keychain": "^6.2.0",
    "react-native-localize": "^2.2.6",
    "react-native-maps": "^0.27.1",
    "react-native-material-dropdown": "github:harshitjee/react-native-material-dropdown",
    "react-native-material-menu": "^1.2.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^11.0.0",
    "react-native-navigation-directions": "^1.0.4",
    "react-native-open-maps": "^0.3.6",
    "react-native-openanything": "0.0.6",
    "react-native-orientation": "^3.1.3",
    "react-native-permissions": "^3.10.1",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-progress": "^4.1.2",
    "react-native-read-more-text": "^1.1.2",
    "react-native-reanimated": "^1.13.4",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-scoped-storage": "^1.9.2",
    "react-native-screens": "^2.18.1",
    "react-native-sectioned-multi-select": "^0.10.0",
    "react-native-signature-capture": "^0.4.12",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-splash-screen": "^3.3.0",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-super-grid": "^4.6.1",
    "react-native-svg": "^12.1.1",
    "react-native-tab-view": "^2.16.0",
    "react-native-textarea": "^1.0.4",
    "react-native-unimodules": "^0.11.0",
    "react-native-vector-icons": "^10.0.3",
    "react-native-whc-toast": "^1.0.0",
    "react-navigation": "^4.4.4",
    "react-navigation-drawer": "^2.7.2",
    "react-navigation-stack": "^2.10.4",
    "react-navigation-tabs": "^2.11.2",
    "rn-fetch-blob": "^0.12.0",
    "uninstall": "0.0.0",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.19",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.3",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

**Comment by tomekzaw** [comment]
@gkasireddy202 Could you please upgrade `react-native-screens` to the latest version and see if it helps?

**Comment by gkasireddy202** [comment]
> @gkasireddy202 Could you please upgrade `react-native-screens` to the latest version and see if it helps?

@tomekzaw - I will update it.

**Comment by szydlovsky** [comment]
@gkasireddy202 any updates?

**Comment by gkasireddy202** [comment]
@szydlovsky - Please close the issue. I updated the react-native-reanimated.
Now it is working fine.

**Comment by alray11** [comment]
@gkasireddy202 I'm facing a similar issue with the react-navigation 4 and react-navigation-tabs 2. Could you tell which version of react-native-reanimated have you installed in your project ? Thank you !

**Comment by gkasireddy202** [comment]
@alray11 - I resolved this issue by upgrading to Navigation 6 and react-native-reanimated.
