### ISSUE TITLE
Unhandled error SIGABRT: Abort program

### ISSUE THREAD

**Issue by vatsal-gadhiya-searce** [software-mansion/react-native-reanimated#5920]
### Description

Unhandled error
SIGABRT: Abort program

Location
/apex/com.android.runtime/lib64/bionic/libc.so:536816 - abort

Here is the bugsnag logs for the same:

0  libc.so +0x830f0               abort
1  libc.so +0xe7edc               __fortify_fatal(char const*, ...)
2  libc.so +0xe757c               HandleUsingDestroyedMutex(pthread_mutex_t*, char const*)
3  libc.so +0xe7430               pthread_mutex_lock
4  libc++_shared.so +0xc5d78      std::__ndk1::mutex::lock()
5  librealm.so +0x3b0614          0x7c753bb618
6  libhermes_executor.so +0x24740 facebook::jsi::DecoratedHostObject::~DecoratedHostObject()
7  libhermes.so +0x74a58          0x7d510c0a5c
8  libhermes.so +0x7f298          0x7d510cb29c
9  libhermes.so +0x1301fc         0x7d5117c200
10 libhermes.so +0x131b88         0x7d5117db8c
11 libhermes.so +0x131420         0x7d5117d424
12 libhermes.so +0x131290         0x7d5117d294
13 libhermes.so +0x7d5f8          0x7d510c95fc
14 libhermes.so +0x7af04          0x7d510c6f08
15 libhermes_executor.so +0x23de4 non-virtual thunk to facebook::jsi::RuntimeDecorator<facebook::jsi::Runtime, facebook::jsi::Runtime>::collectGarbage(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >)
16 libhermes_executor.so +0x27664 facebook::react::JSIExecutor::handleMemoryPressure(int)
17 libreactnativejni.so +0xb49f0  0x7d50cd09f4
18 libreactnativejni.so +0x89c14  0x7d50ca5c18
19 libfbjni.so +0x17eac           facebook::jni::detail::MethodWrapper<void (facebook::jni::JNativeRunnable::*)(), &facebook::jni::JNativeRunnable::run, facebook::jni::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>)
20 libfbjni.so +0x17dfc           facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*, void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>))
21 base.odex +0x16b428            art_jni_trampoline
22 boot-framework.oat +0x734e58   android.os.Handler.dispatchMessage
23 base.odex +0x2052f0            com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
24 boot-framework.oat +0x73846c   android.os.Looper.loop
25 base.odex +0x205518            com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
26 boot.oat +0x1a5164             java.lang.Thread.run
27 libart.so +0x137330            art_quick_invoke_stub
28 libart.so +0x145fe8            art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)
29 libart.so +0x4b13f0            art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)
30 libart.so +0x4b2504            art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)
31 libart.so +0x4f2ec0            art::Thread::CreateCallback(void*)
32 libc.so +0xe689c               __pthread_start(void*)
33 libc.so +0x84b68               __start_thread

### Steps to reproduce

Not sure

### Snack or a link to a repository

Not available

### Reanimated version

3.6.1

### React Native version

0.73.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

brand: Castles manufacturer Castles model S1E2L osName android osVersion 10 runtimeVersions {   "androidApiLevel": "29",   "osBuild": "1.4.1.129511" }

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
Hi @vatsal-gadhiya-searce - the stack trace doesn't contain anything related to Reanimated - if the problem still occurs please include a newer one

**Comment by tomekzaw** [comment]
Please upgrade to latest Reanimated (currently latest is 3.10.0) and feel free to re-open the issue if the problem still persists.
