### ISSUE TITLE
Invariant violation: `createAnimatedComponent` does not support stateless functional components

### ISSUE THREAD

**Issue by dinhmai74** [software-mansion/react-native-reanimated#593]
I got this error when use createAnimatedComponent function.

steps:

> create new expo typescript project
> install react-native-reanimated then use

code: 
```

import React from "react";
import { StyleSheet, Text, View } from "react-native";
import Animated, { Easing } from "react-native-reanimated";

function Button() {
  return <View />;
}

const AnimButton = Animated.createAnimatedComponent(Button);

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});

```

deps:
>     "expo": "~36.0.0",
>     "react": "~16.9.0",
>     "react-dom": "~16.9.0",
>     "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
>     "react-native-reanimated": "^1.7.0",
>     "react-native-screens": "2.0.0-alpha.12",
>     "react-native-web": "~0.11.7"

![Simulator Screen Shot - iPhone X - 2020-02-01 at 21 27 24](https://user-images.githubusercontent.com/40544043/73593715-a613f680-4539-11ea-8b36-49a71c546d84.png)

**Comment by jakub-gonet** [comment]
Hey @dinhmai74,
the problem lies in `const AnimButton = Animated.createAnimatedComponent(Button);` line, `Button` is a function and you're trying to use it in `createAnimatedComponent`, which, as the error says, doesn't allow function component.

**Comment by shamoons** [comment]
How would one change it to a class component?

**Comment by joeyfigaro** [comment]
@shamoons 

```ts
class Button extends React.Component {
  render() {
    return <View />
  }
}
```

**Comment by ShivamRawat0l** [comment]
>  Warning: findNodeHandle is deprecated in StrictMode. findNodeHandle was passed an instance of PathClass which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

After converting it is giving this kind of error.

**Comment by Slapbox** [comment]
I don't understand what `findNodeHandle` is. I guess it's the native equivalent of `findDOMNode`, but outside of this warning caused by `AnimatedComponent(View)` I can't find any reference to it.
