### ISSUE TITLE
[3.9.0] useAnimatedScrollHandler does not fire events from FlashList onScroll

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#5941]
### Description

Events are not being captured by `useAnimatedScrollHandler` from `FlashList@1.6.4` `onScroll` prop at least on `react-native@0.73.7` on Paper.

### Steps to reproduce

1. Install 3.9.0
2. Add onScroll handler on an Animated FlashList
3. useAnimatedScrollHandler won't listen to events

By replacing FlashList with FlatList works with no issues.

Let me know if you need a repro, I guess you already got FlashList setup/tests on your setups.

### Snack or a link to a repository

nope

### Reanimated version

3.9.0

### React Native version

0.73.7

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by NigelBreslaw** [comment]
Here is a reproduction https://snack.expo.dev/@nigelbreslaw/ra-flashlist-issue

**Comment by fadi-quader-mox** [comment]
I can reproduce this issue on 3.9.0 release

**Comment by felixaa** [comment]
Same issue here. `useAnimatedScrollHandler` is not firing when using 
```javascript
const AnimatedFlashList = Animated.createAnimatedComponent(FlashList)
```

**Comment by szydlovsky** [comment]
Hi everyone! We have identified the issue and can tell where the problem lies - but the potential fix has brought up many more questions than we thought and we are currently discussing what to do. Stay tuned ™️

**Comment by szydlovsky** [comment]
Hello again - the fix will probably be merged in quite a while since polish May holidays start soon. But do not worry, if you need the fix badly, you can install Reanimated from `@szydlovsky/rework-animatedComponent-tags` branch. It fixes the issue, yet it lacks testing on Fabric because I ran into some build issues.

**Comment by ElSeniorMikael** [comment]
@szydlovsky is the version 3.10.0 fixing the problem with useAnimatedScrollhandler not firing ?

**Comment by szydlovsky** [comment]
@ElSeniorMikael no - the release 3.10.0 had a different purpose: https://github.com/software-mansion/react-native-reanimated/pull/5963#issuecomment-2088155015. The PR with fix will probably be reviewed next week. Until then you can install Reanimated[ the way I mentioned above](https://github.com/software-mansion/react-native-reanimated/issues/5941#issuecomment-2085785963).

**Comment by emzet93** [comment]
Here is patch created from @szydlovsky PR. Can be used with `patch-package`:

[react-native-reanimated+3.10.0.patch](https://github.com/software-mansion/react-native-reanimated/files/15189507/react-native-reanimated%2B3.10.0.patch)

**Comment by khayym** [comment]
I encountered the same issue on version 3.11.0, however, it worked fine on version 3.8.1

**Comment by szydlovsky** [comment]
Hey everyone! As the fix got merged it should be available in the next nightly build at around 2AM CEST time - see [npm page](https://www.npmjs.com/package/react-native-reanimated?activeTab=versions)

**Comment by efstathiosntonas** [comment]
hey guys, sorry for being a party pooper but I encountered an issue on with they entire screen being detached when displaying an overlay after applying the patch. It's like the entire tree is gone, even the status bar is being hidden on both iOS and Android. 

rn 0.73.8, reanimated 3.11.0 with the patch for 3.10.0 mentioned above, gesture-handler 2.16.2

I cannot share the code I'm using since it's rarther complex and it's a private repo. Let me know if we can communicate in another way. It seems that it does not like being inside a ternary.

The main concept is this: 

```tsx
  const panStyle = useAnimatedStyle<ViewStyle>(() => ({
    transform: [
      {
        translateY: translateY.value
      },
      {
        scale: scale.value
      }
    ]
  }));


  <Overlay>
  {children}
   {overlay === "whatever" ?
     <Animated.View pointerEvents="auto" style={styles.absoluteFill}>
        <Animated.View style={styles.absoluteFill}>
          <View style={styles.flex}>
            <TapGestureHandler
              maxDist={32}
              onHandlerStateChange={({ nativeEvent: { state } }) => {
                if (state === State.END) {
                  setOverlay("none");
                  setSingleTap(false);
                  setOnlyReactions(false);
                }
              }}
            >
              <Animated.View style={[styles.flex, panStyle]}>
              children
              </Animated.View>
  ...all other closing tags
  : null}
  </Overlay>

**Comment by szydlovsky** [comment]
@efstathiosntonas Hi! Which patch did you use? [This one](https://github.com/software-mansion/react-native-reanimated/issues/5941#issuecomment-2090595770) is imperfect and I'd rather suggest [latest nightly version](https://www.npmjs.com/package/react-native-reanimated/v/3.12.0-nightly-20240508-deb782556) - there was some stuff missing in the patch.

**Comment by szydlovsky** [comment]
Alternatively, there is a "final patch" as well: [link](https://github.com/software-mansion/react-native-reanimated/pull/5960#issuecomment-2098548412)

**Comment by efstathiosntonas** [comment]
let me give it a shot. I used the 3.10.0, I missed the 3.11.0 one.

**Comment by efstathiosntonas** [comment]
@szydlovsky after applying patch 3.11.0 life got back to normal 😅. Thank you!

**Comment by szydlovsky** [comment]
@efstathiosntonas That's a relief 😅

**Comment by losh11** [comment]
Unfortunately `useAnimatedScrollHandler` doesn't seem to be firing for me with 3.11.0. I downgraded to 3.8.1 and it works. Would appreicate any assistance getting this to work.

```js
const AnimatedFlashList = Animated.createAnimatedComponent(FlashList);
  const translationY = useSharedValue(0);
  const animatedHeaderStyle = useAnimatedStyle(() => {
    return {
      opacity: interpolate(translationY.value, [0, 100], [1, 0]),
    };
  });

const scrollHandler = useAnimatedScrollHandler(event => {
  translationY.value = event.contentOffset.y;
});
```

Standard stuff right?

**Comment by szydlovsky** [comment]
@losh11 Have you even tried reading the discussion above? The fix will be present, perhaps, in 3.12 version. Until then, you can either install [latest nightly build](https://www.npmjs.com/package/react-native-reanimated/v/3.12.0-nightly-20240510-325bd18fb) or manually install [a patch](https://github.com/software-mansion/react-native-reanimated/pull/5960#issuecomment-2098548412).

**Comment by muhsin-life** [comment]
event is not firing in 3.16.2 version

**Comment by instesti** [comment]
We ended up going the native animation route sadly, as FlashList is just broken when it comes to REA.
