### ISSUE TITLE
Application crashes on Android when using entering/exiting

### ISSUE THREAD

**Issue by R0LLeX** [software-mansion/react-native-reanimated#5946]
### Description

When using entering/exiting in a component Animated.View
`<Animated.View entering={FadeInLeft}>....</Animated.View>`
the android app crashes

https://github.com/software-mansion/react-native-reanimated/assets/95383638/2ed95da4-655c-4982-8afb-df5e55372b3a

### Steps to reproduce

1. Go to the screen where the Animated.View component is used
Expected result: everything is working fine
The actual result: the application crashes on android Redmi Note 9 Pro, Android version: 10

### Snack or a link to a repository

https://snack.expo.dev/1e22PTDDTBsATEL0LtEop

### Reanimated version

3.9.0

### React Native version

0.73.2

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & dev bundle

### Device

Real device

### Device model

Redmi Note 9 Pro (Android 10)

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
@R0LLeX thanks for submitting the issue - could You please provide a stack trace of the crash as well?

**Comment by Latropos** [comment]
@R0LLeX Hi! Your example works fine in the simulator. Also the attached video is broken

**Comment by R0LLeX** [comment]
> @R0LLeX Hi! Your example works fine in the simulator. Also the attached video is broken

the flight takes place only in production on a real device, everything works fine in the android simulator

**Comment by anasvemmully** [comment]
Is it functioning well with the upgrade 3.14.0, as certain Redmi smartphones in the production app experience the same
