### ISSUE TITLE
Xcode looking for REAKeyboardEventObserver.m file, but only .mm is available

### ISSUE THREAD

**Issue by gibo77** [software-mansion/react-native-reanimated#5962]
### Description

Xcode looking for REAKeyboardEventObserver.m file, but only .mm is available.

### Steps to reproduce

1. Updated to 3.9.0
2. Follow website install procedure
3. babel config done.
4. pod install done.

### Snack or a link to a repository

not my program

### Reanimated version

3.9.0

### React Native version

0.74.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
@gibo77 Thanks for reporting this issue. Can you please provide more information, e.g. exact compile errors, so we can investigate this problem?

**Comment by gibo77** [comment]
> @gibo77 Thanks for reporting this issue. Can you please provide more information, e.g. exact compile errors, so we can investigate this problem?

Below is a copy of the error from Xcode build. I have this error in 3.9 and it is also showing in 3.10.0
Showing All Errors Only
_Build input file cannot be found: '/Users/xxxx/Documents/node_modules/react-native-reanimated/apple/keyboardObserver/REAKeyboardEventObserver.m'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?_

I did my investigation. I went to the file `/react-native-reanimated/apple/keyboardObserver/REAKeyboardEventObserver.m` This file REAKeyboardEventObserver.m in the folder is REAKeyboardEventObserver.mm. It is looking off .m file and not the .mm. C++ plus could not be compiled and looking for .m which is Objective-C only. 
How can Xcode compiler compile .mm file instead of .m?

**Comment by tomekzaw** [comment]
@gibo77 Can you run `pod install` in `ios` directory and see if it helps?

**Comment by gibo77** [comment]
> @gibo77 Can you run `pod install` in `ios` directory and see if it helps?

I did `cd iOS pod install cd .. `to no avail. Even re install Cocoapods and same error.

But I was able to remedy this. In Xcode go to Project folder navigator -> Development Pods -> RNReanimated ->keyboardObserver. Click REAKeyboardEventObserver.m. On the right screen Identity and Type change name of file REAKeyboardEventObserver.mm which will point to the Objective C++ file we have in the folder.

**Comment by Saifadin** [comment]
I know this is marked as completed, but shouldn't this be solved on a library level as well?

**Comment by tomekzaw** [comment]
@Saifadin We can't reproduce this error on our side; the library setup looks okay

**Comment by arochedy** [comment]
Same problem for me.

I don't undesrtand why when I rebuild pods it's not updated in my file project.pbxproj
