### ISSUE TITLE
[iOS] App crash when using navigation

### ISSUE THREAD

**Issue by inoxxe** [software-mansion/react-native-reanimated#5968]
### Description

App crashes when trigger navigation.goBack() on react navigation when using react navigation v6 and adding react native reanimated version 3.10.0 on my react native project.

Here is my package.json
```
  
  {
  "name": "testAnimated",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "react": "18.2.0",
    "react-native": "0.74.0",
    "react-native-reanimated": "^3.10.0",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.81",
    "@react-native/eslint-config": "0.74.81",
    "@react-native/metro-config": "0.74.81",
    "@react-native/typescript-config": "0.74.81",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```

### Steps to reproduce

1. create new React Native Project (0.74)
2. Add react-navigation library
3. Add react-native-reanimated (3.10.0)
4. trigger navigation.goBack() on stack navigator

### Snack or a link to a repository

https://github.com/inoxxe/test-reanimated

### Reanimated version

3.10.0

### React Native version

0.74

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by inoxxe** [comment]
> I think that I'm having a issue related with this. I'm having a crash with this error below when tap on BottomTabNavigation tab from `react-navigation`: ![image](https://private-user-images.githubusercontent.com/6640360/327503980-1f25137e-1c7f-4c3e-bf04-bc84861d966a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzA0MDYsIm5iZiI6MTcxNDY3MDEwNiwicGF0aCI6Ii82NjQwMzYwLzMyNzUwMzk4MC0xZjI1MTM3ZS0xYzdmLTRjM2UtYmYwNC1iYzg0ODYxZDk2NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMTcxNTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdiMWJjMzg0NmJkODEyNTI2N2FhOTA0YjEyMDRhN2MxZGE2YzdjZDIzNThhZTJjMTNjOTM0MzBhYWUzMWJjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wStB6GwCwaUrg1VF65jYuKV-kmbXkRFXlgTz_mLtd8M)
> 
> * React Native 0.74.0
> * Reanimated 3.10.0
> * React Navigation 6.5.20

Yup my app crashed when navigating back from another tab in bottom tab navigation

**Comment by foneazmi** [comment]
downgrade to 3.8.1 fix the issue

**Comment by angusryer** [comment]
Downgrading to `3.8.1` avoids the issue for me as well. I have the same Xcode log output as @GabeConsalter.

**Comment by erez-unitronics** [comment]
React native 0.74.1 solved this problem for me.
(with v3.10.0)

**Comment by tomekzaw** [comment]
Thanks @inoxxe for reporting this issue and everyone else for your comments.

Looks like this problem has already been reported so I'm gonna mark this issue as duplicate and close it in favor of:

* https://github.com/software-mansion/react-native-reanimated/issues/5947

**Comment by inoxxe** [comment]
Thank you for the fix @tomekzaw 
My temp solution is to add 
```objective-c
use_frameworks! :linkage => :static
``` 
In your podfile for anyone who encounter this issue.
