### ISSUE TITLE
[Bug]: useAnimatedScrollHandler is not working properly with React Native FlashList in version 3.9+

### ISSUE THREAD

**Issue by prince-d-simform** [software-mansion/react-native-reanimated#5970]
### Description

useAnimatedScrollHandler is working perfectly fine with reanimated version <= 3.8 but with recent versions >= 3.9 it is not working 

```
import Animated, { useAnimatedScrollHandler } from 'react-native-reanimated';

import { FlashList, FlashListProps } from '@shopify/flash-list';

const AnimatedFlashList =
  Animated.createAnimatedComponent<FlashListProps<StoriesType>>(FlashList);
```

```
const onScroll = useAnimatedScrollHandler(event => {
    scrollX.value = event.contentOffset.x;
});

<AnimatedFlashList
     horizontal
     pagingEnabled       
     data={stories}
     onScroll={onScroll}
 />
```

### Steps to reproduce

1. Use React Native FlashList: https://github.com/Shopify/flash-list
2. Use React Native Reanimated version >= 3.9
3. Create animatedComponent of Flashlist
4. Use that AnimatedFlashList 
5. Use onScroll method with useAnimatedScrollHandler

### Snack or a link to a repository

N/A

### Reanimated version

3.9.0

### React Native version

0.71.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by emzet93** [comment]
I can confirm that. Worked perfectly with reanimated 3.8.1. Today I upgraded to 3.10 and it broke :(

**Comment by emzet93** [comment]
@prince-d-simform see this https://github.com/software-mansion/react-native-reanimated/issues/5941.

**Comment by tomekzaw** [comment]
Sorry to hear that, we'll need to take a closer look.

@szydlovsky Could you please investigate this issue?
