### ISSUE TITLE
Exception in Hostfunction: not implemented

### ISSUE THREAD

**Issue by ShahzaibMunir** [software-mansion/react-native-reanimated#5974]
### Description

![Screenshot 2024-05-05 at 12 00 10 AM](https://github.com/software-mansion/react-native-reanimated/assets/102753733/66b59bb7-fac9-4097-bedc-893961d6977f)

this error produce after installation of the app

### Steps to reproduce

Add library to package.json file
run yarn
pod install
install app

### Snack or a link to a repository

I have problem in my project

### Reanimated version

3.8.1

### React Native version

0.73.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by ShahzaibMunir** [comment]
I have my own project that is not possible to share

**Comment by tomekzaw** [comment]
@ShahzaibMunir Can you please run `pod install` in `ios` directory of your app again and see if it helps?

**Comment by jenny-chiang** [comment]
I have the same problem.
I've tried deleting the pod folder and run `pod install`, but still can't solve it.

Reanimated version
3.10.0
React Native version
0.73.8

**Comment by NeverGone97** [comment]
I have the same problem.
I've tried deleting nodemodule, yarn lock ,pod lock and run again, the Pods folder and run pod install, but still can't solve it.

Reanimated version
3.10.0
React Native version
0.72.4

**Comment by Squanbri** [comment]
"react-native-gesture-handler" - "2.14.1"
"react-native-reanimated" - "3.8.1"

Got the same error on any use of reanimated

**Comment by Geenesh03** [comment]
Facing the same issue, 
 `Error: Exception in HostFunction: Not implemented`

Please let me know if there is any fix for this issue

**Comment by tomekzaw** [comment]
Thanks for reporting this problem.

Can you please submit a repro or at least paste full logs from Metro console (from the very beginning)?

**Comment by akylbek-hostaways** [comment]
@tomekzaw It seems like this issue happens when we try to use "@gorhom/bottom-sheet": "^4.5.1", and the latest reanimated version

**Comment by Geenesh** [comment]
One possible solution is that we can downgrade the version of react-native-reanimated to something less than 3.10.0 both globally and within the project. This solved the issue for me until react-native-reanimated solves the issue.

**Comment by szydlovsky** [comment]
@ShahzaibMunir @jenny-chiang @NeverGone97 @daveosterjr  @Squanbri @Geenesh03 @akylbek-hostaways (sorry for the verbose ping)
Hey everyone! I will soon try to find a repro for the issue, but before that try making a ***full clear*** of the project:

1. Run `git clean -xdf` from the root of the project
2. From the root execute: `yarn build && yarn && cd ios && bundle install && bundle exec pod install && cd .. && yarn start --reset-cache` It pretty much resets all caches and stuff

Let me know if made any difference. If not - I will proceed to finding the repro.

**Comment by szydlovsky** [comment]
Also, @akylbek-hostaways could you try applying the [patch from here](https://github.com/software-mansion/react-native-reanimated/pull/5960#issuecomment-2098548412)? Since you say it is connected to `@gorhom/bottom-sheet` that might fix it.

**Comment by PrinceD96** [comment]
@szydlovsky I just tried your steps but I keep getting 

```Exception in Hostfunction: not implemented```

**Comment by akylbek-hostaways** [comment]
@szydlovsky It's still not working. I'm getting these errors:

 ```
ERROR  Error: Exception in HostFunction: Not implemented 
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[21], "@gorhom/bottom-sheet").BottomSheetModalProvider')
```

**Comment by szydlovsky** [comment]
@akylbek-hostaways one more thing that sparks to mind - have you tried bumping bottom sheet package to the latest version (4.6.1) ?

**Comment by akylbek-hostaways** [comment]
@szydlovsky Yes, I tried with the alpha version as well, but I still get the same error.

**Comment by jenny-chiang** [comment]
I use react-native-reanimated `3.6.2` and it runs smoothly

**Comment by jenny-chiang** [comment]
@Geenesh03 I have not installed react-native-reanimated in the global.
I only installed in my project.

**Comment by Geenesh03** [comment]
> @ShahzaibMunir @jenny-chiang @NeverGone97 @daveosterjr @Squanbri @Geenesh03 @akylbek-hostaways (sorry for the verbose ping) Hey everyone! I will soon try to find a repro for the issue, but before that try making a _**full clear**_ of the project:
> 
> 1. Run `git clean -xdf` from the root of the project
> 2. From the root execute: `yarn && yarn build && cd ios && bundle install && bundle exec pod install && cd .. && yarn start --reset-cache` It pretty much resets all caches and stuff
> 
> Let me know if made any difference. If not - I will proceed to finding the repro.

@jenny-chiang follow these steps and check it

**Comment by szydlovsky** [comment]
Hey guys, I am still trying to find a repro. I created a sample repo with `@gorhom/bottom-sheet`, `react-native-reanimated` and `react-native-gesture-handler`: https://github.com/szydlovsky/reaniamtedHostFunctionCrashRepro

Its `package.json` is:
```
{
  "name": "reaniamtedHostFunctionCrashRepro",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4.6.1",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-reanimated": "^3.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.83",
    "@react-native/eslint-config": "0.74.83",
    "@react-native/metro-config": "0.74.83",
    "@react-native/typescript-config": "0.74.83",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4"
}
```
And its `babel.config.js` is:
```
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```

It consists some sample code using bottom-sheet. Can anyone clone it and see if the crash is still there? It works perfectly for me.

**Comment by AlekseyPim** [comment]
@szydlovsky works fine.
Interesting that for my repo everything worked fine till yesterday

**Comment by szydlovsky** [comment]
@akylbek-hostaways alright, your repro throws - time to investigate

**Comment by szydlovsky** [comment]
@akylbek-hostaways I've done some digging and found out that our repros mostly differ by `react-native` versions - your uses 0.73.8 and it doesn't work - my uses 0.74.1. I suggest you try bumping it up

**Comment by szydlovsky** [comment]
Here's some reference how to do it: https://reactnative.dev/docs/upgrading

**Comment by szydlovsky** [comment]
Also this: https://react-native-community.github.io/upgrade-helper/

**Comment by jordmccord** [comment]
Same issue on android RN version 73.6

**Comment by bear-ei** [comment]
> @akylbek-hostaways I've done some digging and found out that our repros mostly differ by `react-native` versions - your uses 0.73.8 and it doesn't work - my uses 0.74.1. I suggest you try bumping it up

Is there a way to solve this issue in 0.73.*? I can't upgrade to version 0.74.0 due to some compatibility reasons for now.

**Comment by mahipalsingh-syt** [comment]
any update on this ? facing same issue.

**Comment by FaggioniHQ** [comment]
Hello,

Any workaround for this?

Thanks in advance :)

**Comment by PrinceD96** [comment]
Until a fix is provided, you have 2 options:

1. Upgrade to `react-native` `v074.1` (can use latest `react-native-reanimated`)
2. Downgrade to `react-native-reanimated` `v3.6.1` (works with `react-native` `v73`)

**Comment by ahmad-elafify-pci** [comment]
Any resolution? @PrinceD96's solutionsd dont work for Expo SDK 50

**Comment by avtarvikas** [comment]
I faced the same issue while using bottom sheet, it got fixed by making these changes in the version

"@gorhom/bottom-sheet": "^4.6.1",
"react-native": "0.73.1",
"react-native-gesture-handler": "^2.16.2",
 "react-native-reanimated": "3.6.1",
  
  @PrinceD96 good workaround

**Comment by tarakagilefoways** [comment]
1. Downgrade to react-native-reanimated v3.6.1 by removing ^ in package.json
2. Install node_modules again,
3. reset cache of metro server.


**_the only workaround until you decide to upgrade project latest 74.* + version._**

**Comment by RohitDianApps** [comment]
I faced the same issue while using reanimated

"react-native": "0.72.1",
"react-native-reanimated": "^3.4.2",

Anyone find fix around?

**Comment by zanotta** [comment]
switching to "react-native-reanimated": "3.6.1" worked for me.

**Comment by RohitDianApps** [comment]
> switching to "react-native-reanimated": "3.6.1" worked for me.

yes now working

**Comment by kiwavi** [comment]
I fixed this error by observing the compatibility table and ensuring the reanimated version is compatible with the react native version. 

More inside https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility/

**Comment by PrinceD96** [comment]
> I fixed this error by observing the compatibility table and ensuring the reanimated version is compatible with the react native version.
> 
> More inside [docs.swmansion.com/react-native-reanimated/docs/guides/compatibility](https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility/)

If you read the OP's message, you'll see he's using 2 versions that should be compatible according to the compatibility version. RN v.73 and reanimated 3.8.1

<img width="996" alt="Screenshot 2024-06-08 at 2 45 13 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/53633741/5783b900-2ce9-42d8-8187-daa84afa17e1">

**Comment by kiwavi** [comment]
> > I fixed this error by observing the compatibility table and ensuring the reanimated version is compatible with the react native version.
> > More inside [docs.swmansion.com/react-native-reanimated/docs/guides/compatibility](https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility/)
> 
> If you read the OP's message, you'll see he's using 2 versions that should be compatible according to the compatibility table. RN `v.73` and reanimated `3.8.1`
> <img alt="Screenshot 2024-06-08 at 2 45 13 PM" width="996" src="https://private-user-images.githubusercontent.com/53633741/337925866-5783b900-2ce9-42d8-8187-daa84afa17e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDk4MTIsIm5iZiI6MTcxNzkwOTUxMiwicGF0aCI6Ii81MzYzMzc0MS8zMzc5MjU4NjYtNTc4M2I5MDAtMmNlOS00MmQ4LTgxODctZGFhODRhZmExN2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA1MDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MGNmYjI0YTk5YTA1NjA2OTk0ZmQ5NmE1NWQ0MDM3Yzc5ODI3NDczYWJkZjYwMTkxY2RjMDI5MWQyYWJhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITcwp5SXNmxVQq8v6tB6Cucz2d-gj_SLjKYVuS5aUR8">

Sorry I didn't notice that. But it might be helpful for others who maybe aren't using compatible versions.
