### ISSUE TITLE
Transform not working on react-native-web

### ISSUE THREAD

**Issue by jfrolich** [software-mansion/react-native-reanimated#598]
I have a few animated components ported over to the web. It all works great (opacity height) except that the transform style properties are not at all handled on web (even if I hardcode it with no animated values). Is this a known issue? I think I can make a reproducible case potentially.

**Comment by latviancoder** [comment]
Can you show the code? I am also exporting to web and latest version of react-native-reanimated works perfectly well with transforms.

**Comment by jfrolich** [comment]
Any node in my web app that is an Animated.View and that has a transform applied doesn't render with the transform (it also doesn't output the CSS).

```jsx
<Animated.View style={{ transform: [{ rotateZ: "10deg" }] }}>
  <View style={{ width: 100, height: 100, backgroundColor: "red" }} />
</Animated.View>
```

Any idea how I could debug this. I already tried to look in the internals, but couldn't find much code related to this.

**Comment by jfrolich** [comment]
Managed to reproduce it in a minimal example with just the essential requirements:

https://github.com/jfrolich/reanimated-bug

**Comment by jfrolich** [comment]
Would anyone be willing to look into this. This is a **very** minimal example of using reanimated transforms on the web, and it just doesn't work. Is there anything I am missing here? At least the behavior is not consistent with native.

**Comment by jfrolich** [comment]
![image](https://user-images.githubusercontent.com/579279/74699147-f037f000-523a-11ea-9d32-32e837a01eae.png)
Essentially the `View` renders fine, but the Reanimated `View` does not.

**Comment by jfrolich** [comment]
It would be great if anyone could give me some guidance what is going wrong here. It looks like a bug, but it might be some configuration I missed in my very minimal reproduction (but that would be strange because everything works except for the transforms).

**Comment by Jarred-Sumner** [comment]
I'm able to do `translateY` on the web just fine. I wonder if its specific to `rotateZ`

**Comment by jfrolich** [comment]
`translateY` is also not working for me in the reproduction. It's a very very basic reproduction, what am I missing?

**Comment by jfrolich** [comment]
Would really appreciate it if someone had a quick look at this 😃(cc @EvanBacon). For some people transforms work, but I can't get them to work (other properties animate), and created a minimal reproduction. Is it a bug or did I miss something?

**Comment by ianmartorell** [comment]
Hey @jfrolich I ran into this same issue, and playing around with your repro I got it to work using `Animated.Value`s and `Animated.concat` to append the rotation units. If you don't include the rotation units it'll work on mobile but not on web. You can check the code [here](https://github.com/ianmartorell/reanimated-transform)! I also tested it with an animation for good measure.

**Comment by jfrolich** [comment]
@ianmartorell: Great to hear. I didn't have the opportunity to test this in my codebase yet, but it seems like a feasible solution. Probably good to leave this issue as it is definitely a behavior that needs to be consistent across platforms, so I guess it's still a bug.

**Comment by jfrolich** [comment]
@ianmartorell: Thank you this actually solved my problem. To make it all work I found another bug in the web implementation:
https://github.com/software-mansion/react-native-reanimated/pull/695.

**Comment by albertcito** [comment]
I have a similar issue on web. Looks like it doesn't work with `react-native-svg` library in web.

Here a demo: https://snack.expo.io/@albertcito/circular-progress-strokedashoffset-with-re-animates

**Comment by albertcito** [comment]
I figure out that an animation with `interpolate` function [doesn't works properly](https://snack.expo.io/@albertcito/basic-opacity-re-animated) in web. But, if you just return a `block` the animations can works. Here the example: 

https://snack.expo.io/@albertcito/re-animated-translations-working-in-web

But, unfortunately the animations using `react-native-svg` elements [doesn't work](https://snack.expo.io/@albertcito/circular-progress-strokedashoffset-with-re-animates) 😢

**Comment by jakub-gonet** [comment]
@albertcito please open a new issue if you still experience the problem you described, we try to keep issues about one topic.
