### ISSUE TITLE
Feature request: throttle node for long-running, CPU-intensive animation.

### ISSUE THREAD

**Issue by noway** [software-mansion/react-native-reanimated#600]
Hello, I need something like a throttle node with which reanimated would throttle FPS from 60 to something less CPU-expensive, like 20. The use case would be something along those lines:

```jsx
      <Animated.Code
        exec={block([
          set(this.animationY, throttle20fps(timing({
            from: this.state.prevCoordinates[0],
            to: this.state.coordinates[0],
            duration: 1000,
            easing: Easing.linear,
          }))),
          set(this.animationX, throttle20fps(timing({
            from: this.state.prevCoordinates[1],
            to: this.state.coordinates[1],
            duration: 1000,
            easing: Easing.linear,
          }))),
        ])}
      />
```

In my use case, setting a certain prop could be CPU-intensive (for example, setting shape in ShapeSource in react-native-mapbox-gl is expensive), so I'd like to reduce number of updates to a minimum. 

Without this feature, I have to resort to setTimeout (which seems to be cheaper in RN that requestAnimatonFrame) + setNativeProps to set my own FPS, which in turn adds its own overhead due to it happening in Javascript thread.

Cheers

**Comment by jakub-gonet** [comment]
I think this issue is a bit outdated considering recent release of reanimated 2. I'm happy to merge PR implementing this, but throttling not on our roadmap right now.
