### ISSUE TITLE
Unable to run on Android

### ISSUE THREAD

**Issue by gkasireddy202** [software-mansion/react-native-reanimated#6017]
### Description

react-native run-android
react-native:0.68.7
react-native-reanimated:3.11.0
gradle:6.2-all

### Steps to reproduce

Getting the below error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/appName/node_modules/react-native-reanimated/android/build.gradle' line: 255

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Could not find method prefab() for arguments [build_9fwqb3yive7f4b3i9ubfzuskj$_run_closure4$_closure42@ea480c8] on extension 'android' of type com.android.build.gradle.LibraryExtension.

### Snack or a link to a repository

company repo

### Reanimated version

3.11.0

### React Native version

0.68.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

Real device

### Device model

One Plus(Android 12)

### Acknowledgements

Yes

**Comment by gkasireddy202** [comment]
> Hey! 👋
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?

https://github.com/gopikrishnacse55/UIExample.git

**Comment by szydlovsky** [comment]
Hey @gkasireddy202. React-native 0.68.7 isn't compatible with 3.9.x-3.11.x Reanimated versions. See [compatibility table](https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility) to adjust your versions properly.
