### ISSUE TITLE
[Question] Do animations need to be manually stopped when a components unmounts? 

### ISSUE THREAD

**Issue by hblumberg** [software-mansion/react-native-reanimated#602]
My team and I have been using RN's Animated API. We've found that if we do not call `stopAnimation` on `componentWillUnmount`, the app may crash.

When using Reanimated, is there any "clean up" necessary on unmount? The question seems to have been discussed [here](https://github.com/software-mansion/react-native-reanimated/issues/109), but it doesn't seem like a clear answer was reached. Thank you!

Thank you!

**Comment by jakub-gonet** [comment]
Hi @hblumberg,

sorry for the late response.

Nodes detach themselves on [`componentWillUnmount`](https://github.com/software-mansion/react-native-reanimated/blob/master/src/createAnimatedComponent.js#L39-L43), so it happens automatically.

If you have further questions feel free to reply.

**Comment by mym0404** [comment]
Great ❤️
