### ISSUE TITLE
Flickering in animation after updating react native

### ISSUE THREAD

**Issue by ArsenSheripov** [software-mansion/react-native-reanimated#6037]
### Description

Hello everyone, I had a problem after updating react native to version 0.74.1; after the update, the header animation began to flicker heavily when activated. 

### Steps to reproduce

```
const Component = ({ }) => {
 const [readerMode, setReaderMode]=useState({mode:'off'})
  const marginTop = useSharedValue(0);
  const animatedStyles = useAnimatedStyle(() => ({
    marginTop: withTiming(marginTop.value, { duration: 500 }),
  }));

  return (
      <View style={{flex: 1,}>
        <Animated.View style={[styles.safeBlock, safeBlockAnimatedStyles]} /> */}
        <Animated.View
          style={[{ height: 100, backgroundColor: 'red' }, animatedStyles]}
          onLayout={onLayout}
          {...props}
        />

        <ScrollView>
          <View style={{ height: 400, backgroundColor: 'blue' }} />
          <View style={{ height: 400, backgroundColor: 'green' }} />
          <View style={{ height: 400, backgroundColor: 'yellow' }} />
          <View style={{ height: 400, backgroundColor: 'teal' }} />
        </ScrollView>
        <Button
          text="On"
          onPress={() => setReaderMode({ mode: 'on' })}
        />
        <Button
          text="Off"
          onPress={() => setReaderMode({mode: 'off' })}
        />
      </View>
  );
};

```
### Snack or a link to a repository
https://snack.expo.dev/@arsen.sheripov/upbeat-blue-waffle

### Reanimated version

3.11.0

### React Native version

0.74.1

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by pavelbabenko** [comment]
Same issue with animating `height` in production

**Comment by exploIF** [comment]
@ArsenSheripov Can I ask you to provide working repro? Unfortunately your example is not working, also there is nothing in the code that triggers animation. Hard to help without that

**Comment by ArsenSheripov** [comment]
@exploIF https://snack.expo.dev/kLsBpRavc-_8FcsALDcbE?platform=android
ofcource, here I corrected the code

**Comment by exploIF** [comment]
@ArsenSheripov I've checked your repro on both Android and iOS and everything works fine on my end

**Comment by ArsenSheripov** [comment]
@exploIF 
Now in the repro, when you turn the reader on and off, there is no flickering, but when I reproduced the same example in my react-native-CLI project, the error was reproduced

**Comment by exodusanto** [comment]
I saw, trying each version, that the flick in my case starts since `>=3.9.0`, the `3.8.1` is the latest that works seamless

Maybe is one of this commits that introduce, in some edge case, the regression
https://github.com/software-mansion/react-native-reanimated/compare/3.8.1...3.9.0-rc.0

**Comment by ArsenSheripov** [comment]
downgrading doesn't work for me

**Comment by kmarushchakItomy** [comment]
> I saw, after trying each version, that the flick in my case starts since `3.9.0-rc.0`, the `3.8.1` is the latest that works seamlessly
> 
> Maybe one of these commits introduced the regression in some edge case [3.8.1...3.9.0-rc.0](https://github.com/software-mansion/react-native-reanimated/compare/3.8.1...3.9.0-rc.0)
> 
> Edit: Found the commit [74985c3](https://github.com/software-mansion/react-native-reanimated/commit/74985c35b444c1ce52736b31b0d03aa1c6a24774)
> 
> I'm using this patch now [react-native-reanimated+3.11.0.patch](https://github.com/software-mansion/react-native-reanimated/files/15495728/react-native-reanimated%2B3.11.0.patch) and the flick is gone
> 
> The original 3.11.x patch [#5960 (comment)](https://github.com/software-mansion/react-native-reanimated/pull/5960#issuecomment-2098548412) + revert of [74985c3](https://github.com/software-mansion/react-native-reanimated/commit/74985c35b444c1ce52736b31b0d03aa1c6a24774)

Thanks. Your patch fixed flickering on my side as well. I'm using JS variable (**containerWidth**) inside useAnimatedStyle's callback. It's **= 0** by default and then it changes once to **N**. Without that patch, useAnimatedStyle's callback would get called several times and would jump between using previous/stale (0) value and current one (N) whenever there is re-render caused by parent component.
```

  const style = useAnimatedStyle(() => {
    return {
      transform: [
        {translateX: value.value * containerWidth},
        {scale: scale.value},
      ],
    };
  }, [containerWidth]);
```


Had to revert from freshly released 3.12.0 back to 3.11.0 tho, because the issue's still happening with 3.12.0.

**Comment by szydlovsky** [comment]
Hey everyone, could you also try 3.12 version? It contains the aforementioned 3.11.x patch

**Comment by exodusanto** [comment]
Hi @szydlovsky, I tested it out.

> [!NOTE]
> A clean installation of 3.12.x triggers the property exception mentioned in #6082. I removed my patch and used the one attached to the issue for testing.

The flickering issue remains in version 3.12. Digging into the commit I mention before, I found that in this function:
https://github.com/software-mansion/react-native-reanimated/blob/74985c35b444c1ce52736b31b0d03aa1c6a24774/src/createAnimatedComponent/PropsFilter.tsx#L106-L116
`shallowEquals` always returns `false` when the style (using `useAnimatedStyle`) property updates, causing a re-render each time, which results in the flickering.

**Comment by ArsenSheripov** [comment]
> Hey everyone, could you also try 3.12 version? It contains the aforementioned 3.11.x patch

hi, I tried version 3.12, the flickering is still there

**Comment by ArsenSheripov** [comment]
Finaly, we rewrote the animations where we changed the position to absolute, useEffect to useAnimatedReaction, and also removed the timing() from useAnimatedStyle(), and the animation began to work smoothly again.

Thanks to all.

**Comment by szydlovsky** [comment]
Hey @ArsenSheripov @pavelbabenko @exodusanto @kmarushchakItomy could you guys try this patch?:
[reanimated_3.13.0_styles.patch](https://github.com/user-attachments/files/16110612/reanimated_3.13.0_styles.patch)
(together with, preferably, 3.13.0 version)

**Comment by exodusanto** [comment]
Great @szydlovsky! It's working on my end 🔝

**Comment by szydlovsky** [comment]
The fix should be there by the next stable version (3.14.0 or next iteration of 3.13.x)
