### ISSUE TITLE
Task :react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a] FAILED

### ISSUE THREAD

**Issue by snehal-phutane** [software-mansion/react-native-reanimated#6045]
### Description

when i try to create gradlew bundleRelease, it is gave me  following error

```
> Configure project :react-native-reanimated
Android gradle plugin: 8.2.1
Gradle: 8.6

> Task :react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a] FAILED
C/C++: ninja: error: manifest 'build.ninja' still dirty after 100 tries

 "react": "18.2.0",
 "react-native": "0.74.1",
"react-native-reanimated": "^3.11.0"
```

### Steps to reproduce

1. project>android>gradlew bundleRelease (for windows)

### Snack or a link to a repository

xxx

### Reanimated version

3.11.0

### React Native version

0.74.1

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by mohammed412** [comment]
I have the same issue when i run `npx expo run:android --variant=release` command i got the error

**Comment by tonypangs** [comment]
same issue too...... i am using react-native 0.72.7 and react-native-reanimated 3.12.0

**Comment by mohammed412** [comment]
i find the solution so the file path is too long for Windows. You could try moving your project to the root of the drive or closer to the root. Otherwise, maybe try [WSL](https://expo.fyi/wsl)

**Comment by vohoangankhanh** [comment]
please reopen the issue, I have the same problem with react-native 0.74.x, nx 19.2.2, react-native-animated: 3.9.x-3.13.x

**Comment by quanganh-snake** [comment]
i same issue, when i build app file .apk
- react-native: "0.75.3"
- react-native-reanimated: "^3.15.3",
i fix:
1. go to file "gradle.properties" in folder "android"
2. Edit change:
"reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64" 
==> "reactNativeArchitectures=arm64-v8a,x86,x86_64"

**Comment by kannan-rjp** [comment]
@elalami-m 

Your solution worked for me!

**Comment by Parmar-Bansi** [comment]
> i same issue, when i build app file .apk
> 
> * react-native: "0.75.3"
> * react-native-reanimated: "^3.15.3",
>   i fix:
> 
> 1. go to file "gradle.properties" in folder "android"
> 2. Edit change:
>    "reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64"
>    ==> "reactNativeArchitectures=arm64-v8a,x86,x86_64"

please give me in details 
I do not understand your reply

**Comment by Dhatchanamoorthi8** [comment]
@quanganh-snake 
"reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64"
==> "reactNativeArchitectures=arm64-v8a,x86,x86_64" 
this is work me

**Comment by shreysaroch** [comment]
> i same issue, when i build app file .apk
> 
> * react-native: "0.75.3"
> * react-native-reanimated: "^3.15.3",
>   i fix:
> 
> 1. go to file "gradle.properties" in folder "android"
> 2. Edit change:
>    "reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64"
>    ==> "reactNativeArchitectures=arm64-v8a,x86,x86_64"

I tried this, didn't work for me, I'm on the same rn and rn animated versions.

**Comment by sanjeev-san** [comment]
The issue has been closed without proper resolution. 
Path being too long is not the issue in first place.
The issue only occurs when you add armeabi-v7a architecture in gradle.properties and removing that is only a workaround not a solution.
Without adding this particular architecture, releasing the app will lead to a lot of crash issues in devices which require this architecture.
