### ISSUE TITLE
React Native Reanimated Not Responsive

### ISSUE THREAD

**Issue by Vimal1464** [software-mansion/react-native-reanimated#6074]
### Description

Why react-native-reanimated animation are shaky when scroll in drawer.
There is no way to create responsive animation in react native reanimated, I have tried thousands of way.
or is it the issue of react native reanimated it self, kindly help.

Please Community help me out with this

### Video 👍 
 https://drive.google.com/file/d/1O_WQa5nwhdNbsbwefCadfVdTDfkboerz/view?usp=share_link

### Steps to reproduce

1. Clone [https://github.com/Vimal1464/animated-custom-drawer](clone this repo)
2. npm install; 
3. For IOS run cd ios; pod install;
4. npm run android or npm run iOS

### Snack or a link to a repository

https://github.com/Vimal1464/animated-custom-drawer

### Reanimated version

3.10.0

### React Native version

0.74.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Vimal1464** [comment]
any one please help

**Comment by szydlovsky** [comment]
Hi there @Vimal1464, I regret to inform you that we spotted no shakiness in the given video.

**Comment by Vimal1464** [comment]
@szydlovsky  why sir, also the animation are not responsive sir,
what about that

**Comment by szydlovsky** [comment]
@Vimal1464 in what way unresponsive?

**Comment by Vimal1464** [comment]
@szydlovsky 
See the video,
in small device animation,
the profile photo and number is going out of the screen
