### ISSUE TITLE
Invalid `RNReanimated.podspec` file: [Reanimated] Unsupported React Native version. Please use 0.71 or newer. 

### ISSUE THREAD

**Issue by ayushcloudanalogy** [software-mansion/react-native-reanimated#6075]
### Description

Pod install return error "Invalid `RNReanimated.podspec` file: [Reanimated] Unsupported React Native version. Please use 0.71 or newer. Its working fine till yesterday " 

### Steps to reproduce

1.yarn install
2.pod install

### Snack or a link to a repository

None

### Reanimated version

3.7.1

### React Native version

0.70.14

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by ayushcloudanalogy** [comment]
![Uploading Screenshot 2024-06-04 at 3.28.53 PM.png…]()

**Comment by szydlovsky** [comment]
@ayushcloudanalogy Is there anything that forces you to use `react-native@0.70.x`? If not I would do exactly what the error states: upgrade RN to 0.71+.

**Comment by mubarizgh** [comment]
@ayushcloudanalogy how did you resolve it

**Comment by manosKas** [comment]
have u found out what it was ???

**Comment by Usmanqayyum109** [comment]
Downgrade **### react-native-reanimated** to version **### 3.5.0** for compatibility.

**Comment by mahesh970098** [comment]
> Downgrade react-native-reanimated to version 3.5.0 for compatibility with React Native 0.72.15.

Thanks man

**Comment by Aikenwu** [comment]
compatibility guide is here: https://docs.swmansion.com/react-native-reanimated/docs/3.x/guides/compatibility
