### ISSUE TITLE
RangeError: Set maximum size exceeded

### ISSUE THREAD

**Issue by Mutai-Gilbert** [software-mansion/react-native-reanimated#6086]
### Description

I am encountering a `RangeError: Set maximum size exceeded` error when using the `runPropUpdates` function in the AnimatedNode.js file. This issue occurs when the `visitedNodes` set grows too large, likely due to an infinite loop or a very large number of nodes being processed. The expected behavior is that the function should efficiently update nodes without exceeding the set size limit. Here’s a screenshot of the error:

![Screenshot 2024-06-07 at 13 36 35](https://github.com/software-mansion/react-native-reanimated/assets/43999618/181304bf-dda8-4007-a51c-589e1e471d68)

### Steps to reproduce

1. Run the app and trigger the animation updates `npm start-- --reset cache`
2. Observe the error `Set maximum size exceeded` in the console.

### Snack or a link to a repository

https://github.com/Mutai-Gilbert

### Reanimated version

2.17.0

### React Native version

0.69.12

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & production bundle

### Device

iOS simulator

### Device model

iPhone 14 Pro, iOS 16.2

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
@Mutai-Gilbert your repro link points to your github profile.

**Comment by Mutai-Gilbert** [comment]
Okay, let me share with you the correct link.
