### ISSUE TITLE
3.13.0-rc.0 crash on iOS (animated flatlist) in Release build only

### ISSUE THREAD

**Issue by karimb11** [software-mansion/react-native-reanimated#6092]
### Description

If you scroll through a flat list that has animated items (Just a boilerplate shared value scale animation per item using Animated.View), you get this exception:

![image](https://github.com/software-mansion/react-native-reanimated/assets/76182522/65c8a73e-deae-4f05-ba86-09bf3cea59d8)

This happens in release build only, I also tested multiple previous versions, so it's not exclusive to the latest release of react-native-reanimated.

### Steps to reproduce

I'm just looking for some pointers, it's hard to reproduce as the app is rather complex (react-navigation)

### Snack or a link to a repository

don't have any

### Reanimated version

3.13.0-rc.0

### React Native version

0.74.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

iPhone SE 2

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
Hey @karimb11 it might be due to a recent issue with Shareables, can you please try `3.13.0-rc.1` version? It contains a fix for it

**Comment by karimb11** [comment]
Hello @szydlovsky , thank you, I tried it but still getting a crash

![image](https://github.com/software-mansion/react-native-reanimated/assets/76182522/64d4fb2b-b648-46ea-8582-a8657d2a8078)

**Comment by bartlomiejbloniarz** [comment]
This was caused by an issue in `jsi`. I explain it more in depth [here](https://github.com/software-mansion/react-native-reanimated/issues/6114#issuecomment-2176533557).

**Comment by Antisane76** [comment]
Hi @bartlomiejbloniarz - I'm still seeing this kind of crash error on Android Release builds using the new architecture and hermes. I originally had the same issue on iOS that was occurring [here](https://github.com/software-mansion/react-native-reanimated/issues/6114#issuecomment-2176533557) but after patching RN with your [PR to RN](https://github.com/facebook/react-native/pull/45042) the iOS issue was resolved.

I've seen a few functions that appear to be causing this on android in the crash logs - setNativeState, setPropertyValue, call

I have a somewhat reliable way of recreating the crash on my app so I'm happy to test any patches or ideas. I've tried 3.12.1 and 3.13.0-rc.2 of reanimated on RN 0.74.2 (with above patch) with no luck.

**Comment by bartlomiejbloniarz** [comment]
Hi @Antisane76 👋 
How did you apply the patch on Android? I'm asking this question because on Android you have to [https://reactnative.dev/contributing/how-to-build-from-source](configure gradle to build RN from source). Otherwise it will use precompiled artifacts.

**Comment by Antisane76** [comment]
Ah good to know. I was just using 'patch-package'. I'll give it a crack and let you know but I bet that will resolve it. Thanks for your time!
