### ISSUE TITLE
TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

### ISSUE THREAD

**Issue by randurd** [software-mansion/react-native-reanimated#6100]
### Description

Hello, I'm having an issue with react-native-reanimated I'm using it for @gorhom/bottom-sheet but I'm getting this error when running the app on Android. However, it works fine on iOS.

Steps I tried:
- Followed the installation instructions.
- Cleared the cache.
- Reinstalled libraries.

Libraries: ( these versions work fine on iOS )
- "react-native-reanimated": "2.17.0"
- "@gorhom/bottom-sheet": "4.6.3"
- "react-native-gesture-handler": "1.10.3"
- "react-native": "0.64.0"

Errors:

![image](https://github.com/software-mansion/react-native-reanimated/assets/107166955/63569af6-2062-44c7-b539-64d1efe3d9f0)

### Steps to reproduce

N/A

### Snack or a link to a repository

N.A

### Reanimated version

2.17.0

### React Native version

0.64.0

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
@randurd you are running some super old versions of reanimated, gesture-handler and react-native, while using a pretty fresh bottom-sheets version. I'd suggest checking npm pages of these packages and bumping them up.

**Comment by szydlovsky** [comment]
Also, in terms of clearing cache, make sure you run `git clean -xdf` (it's a true full clear) and then install all the dependencies yet again.

**Comment by piaskowyk** [comment]
Unfortunately, we no longer support the Reanimated v1 API. I highly recommend upgrading to the latest Reanimated version, which includes many stability improvements. However, this upgrade will require the use of only the v2 API. For more details, refer to the documentation at https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/
