### ISSUE TITLE
Examples not working, & What does this error mean?

### ISSUE THREAD

**Issue by JBaczuk** [software-mansion/react-native-reanimated#611]
I'm trying to run the progress bar example, and getting this error, what does it mean? I'm getting it when I try to create my own animation as well. (iOS simulator)

<img width="435" alt="image" src="https://user-images.githubusercontent.com/8162417/74569265-3fc6a500-4f37-11ea-9019-f24c4ed6e5e0.png">

**Comment by jakub-gonet** [comment]
Hey @JBaczuk,

can you provide RN and Reanimated versions? I checked and `master` is working fine on IOS 8 simulator. Are you using JS operators on `Value` by any chance? 

Also, post minimal reproducible example with your code, we'll try to figure something out.

**Comment by jakub-gonet** [comment]
Hi!
This issue was inactive for a while, so I'm closing it.
If you still face this problem don't hesitate to ask.
