### ISSUE TITLE
Using `interpolateColor` inside `useDerivedValue` creates colors glitches on iOS

### ISSUE THREAD

**Issue by swansontec** [software-mansion/react-native-reanimated#6119]
### Description

Returning an `interpolateColor` value from a `useDerivedValue` will cause incorrect colors to appear on iOS. Here is the setup:

```js
const blue = '#2080c0';
const derivedColor = useDerivedValue(() =>
  interpolateColor(0, [0, 1], [blue, blue]),
);
```

This *should* always render as blue if we put it in an animated style:

```js
const animatedStyle = useAnimatedStyle(() => ({
  color: derivedColor.value,
}));
```

However, on iOS specifically, the text will glitch to pink after the first button press:

```js
  // Cause a re-render on press:
  const [count, setCount] = React.useState(0);
  const handleCount = () => setCount(count + 1);

  return (
    <>
      <Animated.Text style={animatedStyle}>
        {count}
      </Animated.Text>
      <Button onPress={handleCount} title="Count" />
    </>
  );
```

### Steps to reproduce

Here is what seems to be happening:

1. First render
  a. JS thread: `useDerivedValue` returns the string `"rgba(32, 128, 192, 1)"`
  b. JS thread: `useAnimatedStyle` returns the style `{ color: "rgba(32, 128, 192, 1)" }`
  c. The text renders as blue
  d. UI thread: `useDerivedValue` runs again, and returns the *integer* 0xff2080c0. This seems to be some sort of optimization, since this differs from what the JS thread returns.
2. User presses the button
3. Second render
  a. JS thread: `useDerivedValue` does *not* run, but returns the saved 0xff2080c0 from the UI thread.
  b. JS thread: `useAnimatedStyle` returns the style `{ color: 0xff2080c0 }`
  c. The text renders as pink

Directly rendering `<Text style={{ color: 0xff2080c0 }}>Hello</Text>` produces the same pink color (although TypeScript complains that numbers aren't valid colors). Messing around with the values, it seems that `useAnimatedStyle` on the JS thread interprets integers as 0xrrggbbaa, whereas the Reanimated UI thread interprets integers as 0xaarrggbb.

### Snack or a link to a repository

https://github.com/swansontec/PinkEyeTest

### Reanimated version

3.12.0

### React Native version

0.74.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Any

### Device

Any

### Acknowledgements

Yes

**Comment by swansontec** [comment]
As a hacky work-around (since I don't know Reanimated well enough to fix this myself), we are using [patch-package](https://www.npmjs.com/package/patch-package) to edit node_modules/react-native-reanimated/src/reanimated2/Colors.ts, around line 520:

-  if (IS_WEB || !_WORKLET) {
+  if (!IS_ANDROID || !_WORKLET) {
     return `rgba(${r}, ${g}, ${b}, ${alpha})`;
   }

This removes a performance optimization, but it does solve the bug.

**Comment by szydlovsky** [comment]
@swansontec  Seems like a fully fledged bug but I have one question: why use `interpolateColor` inside of `useDerivedValue`, if it doesn't use any other shared value? (useDerivedValue is specifically used for creating shared values based on other shared values).

**Comment by swansontec** [comment]
@szydlovsky Yeah, this code doesn't make any sense because it's a minimal repo case and animations aren't necessary to trigger the bug. In our actual app, we do use animations [to control the derived value](https://github.com/EdgeApp/edge-react-gui/blob/develop/src/components/themed/FilledTextInput.tsx#L228):

```ts
const iconColor = useDerivedValue(() => interpolateIconColor(focusAnimation, disableAnimation))
```

**Comment by szydlovsky** [comment]
Hey @swansontec turns out this "optmialisation" you mentioned was unneeded whatsoever haha. Once the PR goes through review I'll send you a patch to apply 👍

**Comment by szydlovsky** [comment]
Together with merge of the mentioned PR, the issue should be gone in the nearest nightly version (probably tomorrow morning) or in a next stable one - 3.14 or next iteration of 3.13.x

**Comment by swansontec** [comment]
We have updated to version 3.14.0, and everything works correctly! Thanks a bunch for getting this fix upstreamed.
