### ISSUE TITLE
Jest error when using .interpolate

### ISSUE THREAD

**Issue by thiagoferolla** [software-mansion/react-native-reanimated#612]
I wrote an animation using timing and interpolate but when testing the component with Jest it fails with the error `buttonAnimationState.interpolate is not a function` even though I'm using the official mock from react-native-reanimated.

`jest.mock("react-native-reanimated", () => require("react-native-reanimated/mock"))`

Checking the mock provided, I found an `.interpolate` definition so I don't know what's happening. Maybe it's missing in the `new Animated.Value()` mock

**Comment by jakub-gonet** [comment]
Hard to say, could you provide snack with said component and jest test case?

**Comment by josephluck** [comment]
Also running in to this. @thiagoferolla did you find a solution?

**Comment by mym0404** [comment]
I am on a same thing...

**Comment by Darapsas** [comment]
When are you planning to merge this issue? It is getting old, going, and changing this line of code in the node_modules.

**Comment by satya164** [comment]
@Darapsas just use https://github.com/ds300/patch-package

**Comment by Darapsas** [comment]
Holy shit - thanks a lot (@satya164 ). The more you know.
