### ISSUE TITLE
[DOCS] Interactive animation creator on docs site has a small bug

### ISSUE THREAD

**Issue by mandrade2** [software-mansion/react-native-reanimated#6126]
### Description

I noticed a small UI issue where the interactive animation maker on the docs site keeps showing a power slider if you used the 'in', 'out' or 'inOut' easings in combination with 'poly' and set a custom value on power. Not a mayor issue but should be a quick fix and hard to notice.

### Steps to reproduce

1. Go to any of the interactive animation makers like the one here https://docs.swmansion.com/react-native-reanimated/docs/animations/withTiming 
2. Select any of the 'in', 'out' or 'inOut' for easing. 
3. Now for the second in selector use 'poly'. You will now see a power slider.
4. If you set a value on this slider and then go back to any of the other easings you will keep seeing it even if it doesn't applies. If you don't set a value to it then there's no issue

### Snack or a link to a repository

-

### Reanimated version

-

### React Native version

-

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by mandrade2** [comment]
Dear github actions bot, I will add a repository with a repro only if a human asks so. Since in this case the bug should be easily reproducible. I see this on my mac M1 on Firefox 127.0b3. For anyone reading, thanks for the awesome repo, let me know if you need more info or the repo :)

**Comment by patrycjakalinska** [comment]
Hi! Thank you for finding this bug :> I linked a PR that fixes it by reseting value of hidden Easing that kept Power slider visible
