### ISSUE TITLE
Gesture conflict issue in Android - Help needed

### ISSUE THREAD

**Issue by cedricsandars** [software-mansion/react-native-reanimated#615]
I am facing an issue only in Android, where when I try to swipe/drag the notification panel upwards, the below Flatlist/Scrollable view is getting scrolled. This is happening only in Android, but in iOS it is working smoothly. 

Any advice to resolve this would be helpful. Following are some information that might be useful to provide a solution.

**Example**: I am using the Notification Panel from the Examples. 

https://github.com/software-mansion/react-native-reanimated/blob/master/Example/interactablePlayground/real-life-examples/NotifPanel.js

**Issue Video**:
You can notice in the video, at times the content below the notification panel is scrolling. The scroll is happening while I try to drag the notification panel upwards.

![ezgif com-optimize](https://user-images.githubusercontent.com/2046221/74839636-996e0b80-534b-11ea-95de-44f969d00eb3.gif)

**My Code Structure**:

App.js:

```
<Animated.View style={{
          position: 'absolute',
          backgroundColor: { bgColor },
          left: 0,
          right: 0,
          top: 0,
          opacity: 1,
          height: !this.state.activity ? header_height : 0,
          zIndex: 2,
          elevation: 100,
          category: '',
          transform: [{ translateY: translateY }]
        }}
        >
          <NotificationSection
           //custom props
          />
 </Animated.View>
<Animated.View style={{ flex: 1, zIndex: 1, elevation: 1 }}>
          <TabNavigation
//custom screen props
          />
</Animated.View>
```

NotificationSection: notification.js (The draggable notification panel)

```
<Interactable.View
          ref={this.notif}
          verticalOnly={true}
          snapPoints={[
            { y: 0, tension: 0, damping: 1 },
            { y: screen_height < 500 ? -screen_height + header_height : screen_height/2 },
            { y: !this.state.feed ? screen_height < 500 ? -screen_height + header_height - 26 : -screen_height + header_height : -screen_height }
            // { y: -screen_height + 80 },
          ]}
          gravityPoints={[
            {
              y: 0,
              strength: 220,
              falloff: screen_height * 8,
              damping: 0.7,
              influenceArea: { top: (-screen_height + header_height) * 0.5 },
            },
          ]}
          initialPosition={{ y: screen_height < 500 ? -screen_height + header_height - 26 : -screen_height + header_height }}
          boundaries={{
            top: -screen_height,
            bottom: 0,
            bounce: 2,
            haptics: true,
          }}>
// custom render function
</Interactable.View>
```

TabNavigation: feed.js (The main scrollable list in the background)

```
import { Text, View,  Dimensions,  FlatList} from 'react-native';
import Animated from 'react-native-reanimated';
const AnimatedFlatList = Animated.createAnimatedComponent(FlatList)

<AnimatedFlatList
                 data={this.state.data}
                  renderItem={this.renderSummaryItem}
                  keyExtractor={item => item.postId}
                  onEndReached={({ distanceFromEnd }) => {
                        if (distanceFromEnd >= 0){
                          this.handleLoadMore()
                        }
                    }}
                  onEndReachedThreshold={0.01}
                  extraData={this.state}
                  refreshing={this.state.isFetching}
                  onScroll={Animated.event(
                    [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
                    { useNativeDriver: true }
                  )
                  }
                  scrollEventThrottle={16}
                  bounces={false}
                  />
```

**Comment by cedricsandars** [comment]
@wilau2 - Trying to get help from you this time as well. Any advice or input would be of great help to resolve this. Thanks!

**Comment by wilau2** [comment]
Hey @cedricsandars 

I would suggest you put a touchable opacity so that if you click outside of the top pannel it closes the panel. 

This is the current setup I have in my app, Sorry I can't be as much help here as you thought! 

My opacity becomes darker the more open the panel is.

**Comment by cedricsandars** [comment]
@wilau2 - Thanks for your suggestion. Although it doesn't solve the issue I am facing, I understand the workaround/suggestion you have provided above. I will keep this issue open and see if I get from anyone else from the community on this.

Thanks for your input @wilau2 !

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
