### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by badredaha** [software-mansion/react-native-reanimated#6166]
### Description

Hi,

We use Snyk as a security SAST. When the scan is finished, the report show us: 

`com.google.protobuf:protobuf-java` and `io.netty:netty-codec-http2` as dependencies need to be updated to avoid a Denial of Service (DoS) attack.

I use reanimated 3.11 should update to the latest ?

### Steps to reproduce

scan with Snyk tools ( a security SAST tools)

### Snack or a link to a repository

https://myoungit.com

### Reanimated version

3.11.0

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

None

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
@badredaha do we really need these dependencies updated? We are not using them directly (might be dependencies of our dependencies), but Reanimated has nothing to do with networking.
