### ISSUE TITLE
useAnimatedProps causes crash when invoking a globally referenced function but works with a locally referenced one

### ISSUE THREAD

**Issue by ArtKullashi** [software-mansion/react-native-reanimated#6167]
### Description

When trying to use useAnimatedProps to set the text value of a TextInput component; Using a global function to format the text value before updating the prop causes a crash, full crash on iOS with no error on the js side. On android(expo go local dev) an error that returns:
> globalFormatNumber is not a function. (It is Object)

in short this works:
```

  const animatedTextInputProps = useAnimatedProps(() => {
    const localFormatNumber = (num) => new Intl.NumberFormat('EN-US').format(num);

    return {
      text: localFormatNumber(Math.floor(animatedNumber.value))
    }
  })

```
but this doesn't:
```

 const globalFormatNumber = (num) => new Intl.NumberFormat('EN-US').format(num);

  const animatedTextInputProps = useAnimatedProps(() => {
    return {
       text: globalFormatNumber(Math.floor(animatedNumber.value))
    }
  })

```
_Clarification_: I have not tried this on other components or outside of expo go, so I'm not sure if it is strictly related to the TextInput component or not.

![crashImage](https://github.com/software-mansion/react-native-reanimated/assets/53052111/086f896a-8478-454c-b7c7-04266e66ab3e)

### Steps to reproduce

1. Open the the provided snack
2. Comment line 15
3. Uncomment line 16

### Snack or a link to a repository

https://snack.expo.dev/@r2in360/reanimated-useanimatedprops-bug

### Reanimated version

3.10.1

### React Native version

0.74.1

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
`globalFormatNumber` needs to be marked as a worklet.

```ts
const globalFormatNumber = (num) => {
  'worklet';
  return new Intl.NumberFormat('EN-US').format(num);
};
```
