### ISSUE TITLE
Using translateY to non-absolute elements.

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#618]
Idk is there anybody who having this issue like me but, what im trying to do is , i want to collapse  my header up when i scroll down and show  it again immediately if i scroll  up. Basic animation you know it:

And im using a method like below for the animation:
```
 const H_MAX_HEIGHT = 130;
  const H_MIN_HEIGHT = 0;
  const scrollY = useRef(new Animated.Value(0)).current;
  const diffClampScrollY = Animated.diffClamp(scrollY, 0, H_MAX_HEIGHT);
  const headerScrollHeight = Animated.interpolate(diffClampScrollY, {
    inputRange: [H_MIN_HEIGHT, H_MAX_HEIGHT],
    outputRange: [H_MIN_HEIGHT, -H_MAX_HEIGHT],
    extrapolate: diffClampScrollY,
  });

```
H_MAX_HEIGHT 130 becouse my header is position absolute and it haas 130px of height.
so i give this `headerScrollHeight `to my header  as a translateY value, it goes up nothings wong. butt i want also the next element go up  and clear the empty area.... 
Actually  the next element is scrollview's itself, and its not position abosolute .. and if i give this headerScrollHeight to it as well, as a translateY value, its going up but shaking too much... :( i dont know what to do.. in the scrollview i have a masonrylist component, in which i can't get the scroll position with Animated... i can only get regular scrollY axis. thats why i collapsed the masonrylist component with a scrollview to convert it to `Animated.ScrollView..` to get Animated.event  properly... ... 

///// entire component is looking like that ///

  ```
 <Animated.View
          style={{
            left: 0,
            right: 0,
            top: 0,
            position: 'absolute',
            height: H_MAX_HEIGHT,
            width: width,
            paddingHorizontal: 20,
            transform: [{translateY: headerScrollHeight}],
            overflow: 'hidden',
            zIndex: 999,
            backgroundColor: '#fff',
          }}>
          <Animatable.View animation="bounceInDown" delay={1500}>
            <HeaderNavigation FilterItems={FilterItems} props={navigation} />
          </Animatable.View>
        </Animated.View>
        <Animated.ScrollView
          onScroll={Animated.event([
            {
              nativeEvent: {contentOffset: {y: scrollY}},
            },
          ])}
          scrollEventThrottle={1}
          bounces={false}
          style={[styles.Wrapper, {paddingTop: H_MAX_HEIGHT}]}>
          <MasonryList
            imageContainerStyle={styles.Image}
            columns={2}
            spacing={5}
            images={data}
            onPressImage={item => navigation.navigate('Detail', {item})}
          />
        </Animated.ScrollView>
```

**Comment by Mhde96** [comment]
i have the same problem if you solve it please tell me how

**Comment by matthieugayon** [comment]
Same here, did you manage to solve that issue ?

**Comment by jakub-gonet** [comment]
I think we have an example like that in the example app (interactable playground IIRC), maybe try that? Could you also add a [snack](https://snack.expo.io/) and describe what's happening more clearly? I'm afraid I don't understand your issue here.

BTW, this happens on android only?

**Comment by jakub-gonet** [comment]
Closing due to no response, if you still experience this feel free to reopen.

**Comment by waheedakhtar694** [comment]
@jakub-gonet I am having the same issue, I have implemented a youtube transition like this
https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season1/youtube-transitions/components
The problem is When I collapse the view it occupies the space from the top of the view 
<img width="314" alt="Screenshot 2020-10-20 at 6 31 22 PM" src="https://user-images.githubusercontent.com/45425486/96593107-97a57f00-1302-11eb-9f7f-5acf4683bc64.png">

Collapse view is appearing at the bottom like this but it's actually occupying the space from the top, as a result, this area becomes unclickable where this view appears.
<img width="310" alt="Screenshot 2020-10-20 at 6 31 36 PM" src="https://user-images.githubusercontent.com/45425486/96593532-0b478c00-1303-11eb-9bbd-84dcb40f0589.png">

In both images, there is the same view that is appearing in a different position and occupying space from different areas if I increase or decrease the size on the bottom collapse view the top view also increases or decreases.

**Comment by waheedakhtar694** [comment]
@Bayramito Did you solve this issue?

**Comment by waheedakhtar694** [comment]
@wcandillon Do you have some idea about this issue I followed your youtube transition example?

**Comment by waheedakhtar694** [comment]
@jakub-gonet Any update on this?

**Comment by jakub-gonet** [comment]
@waheedakhtar694 please provide minimal repro example, I can't help you without that.

**Comment by waheedakhtar694** [comment]
@jakub-gonet As I said earlier I am using this code 
https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season1/youtube-transitions
and the same code is making a problem.

**Comment by jakub-gonet** [comment]
This is unfortunately too big for being repro, we don't have resources to look into whole components written in reanimated, especially in the v1 version. Please add a smaller repro, ideally without any external libraries.

**Comment by waheedakhtar694** [comment]
@jakub-gonet The whole problem is here.
https://github.com/wcandillon/can-it-be-done-in-react-native/blob/62a147b0ee080e24283cd44b41de720b7f04fae4/season1/youtube-transitions/components/VideoModal.js#L202
and in this file, Can you please take a look at the render function of this file.
