### ISSUE TITLE
RN075 Support for Removed deprecated ReactMethod in Android.

### ISSUE THREAD

**Issue by raghav-reglobe** [software-mansion/react-native-reanimated#6197]
### Description

In react-native 0.75.0, 

UIManagerModule has been updated and some of it's methods are found such as.

>     dismissPopupMenu
>     showPopupMenu
>     measureLayoutRelativeToParent

In ReactNativeUtils, ReactViewBackgroundDrawable has some undefined Symbols.

### Steps to reproduce

Create a new react-native project with RN075:

> **RUN** : _npx react-native@next init RN075 --version next_
> **RUN** : _yarn add react-native-reanimated@latest_
> **RUN** : _react-native run-android_

### Snack or a link to a repository

https://snack.expo.dev/@raghav-cashify/rn075

### Reanimated version

3.13.0-rc.2

### React Native version

0.75.0-rc.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

Pixel 4a

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
Hey @raghav-reglobe we are already aware of that and are working on it here:
https://github.com/software-mansion/react-native-reanimated/pull/6185
Thanks for submitting nonetheless!

**Comment by raghav-reglobe** [comment]
Thanks.
