### ISSUE TITLE
Webpack error. It's not know how to run JSX code

### ISSUE THREAD

**Issue by EdDevs2503** [software-mansion/react-native-reanimated#620]
I attempt run the examples, but i don't. First, i attempted run with run-android and it's not run, well, next i attempt to run with Web. And it's show me more errors. The first i fixed, but the second told me this error. 
<img width="1026" alt="Screen Shot 2020-02-22 at 4 09 53 AM" src="https://user-images.githubusercontent.com/45980184/75088908-b06a5480-5529-11ea-99c6-8af191560dc9.png">

The error is in [react-native-reanimated-bottom-sheet](https://github.com/osdnk/react-native-reanimated-bottom-sheet) i put the Example folder from that repository directly in node_modules/reanimated-bottom-sheet because npm install no did't

Once that i solve the errors, i have one with webpack, or the log tell me it. I believe that the webpack config it's not correctly configured but i don't know how find it. Thanks for your time.

**Comment by jakub-gonet** [comment]
Hi @EdDevs2503,

if you still experience this error please create repo with reproduction.

I'm closing it for now.
