### ISSUE TITLE
Build failure for Windows 10

### ISSUE THREAD

**Issue by kaustavb79** [software-mansion/react-native-reanimated#6224]
### Description

Hi, 
I created a react native project using react-native-cli on Windows 10 and add the react-native-reanimated package and follow the instruction mentioned in the README.md file of the package. When I tried to install app on android emulator using the following command **npx react-native run-android** the build got stuck at react-native-reanimated and after 10-15 min it gave build failure error. Below I have pasted the build error screenshots. I have created a dummy project with the exact same package version as my origin app for testing and the app gets build successfully. Shared the repo link too.

![Screenshot (18)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/9276a918-8cff-436f-bc62-1cdc8e0aa6ea)
![Screenshot (10)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/a1eb2f1d-bf92-40ab-9ba3-660b841f4a0e)
![Screenshot (11)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/f06524f5-e7f2-4e3c-9e3f-0dfcdf8d3b9b)
![Screenshot (12)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/6398ce96-acee-4a5c-8ba5-d21a664e54cf)
![Screenshot (13)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/e526ed3c-3e06-4881-8a18-0ab19ea21fa1)
![Screenshot (14)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/c2c3e63d-cfda-4848-a0ea-4712fc15cf2e)
![Screenshot (15)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/9b6e3475-dd8e-49cb-9db4-73844fba555f)

![Screenshot (16)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/95cd2ddb-c953-4ed5-b3e7-1b7b6c91649b)
![Screenshot (17)](https://github.com/software-mansion/react-native-reanimated/assets/29993931/8a3bcfb5-fbd5-4646-9353-e29ea99833f4)

### Operating System
Windows 10

### CMake
Version: 3.29.6

### NodeJS
Version: 2.15.0

### npm
Version:  10.7.0

### yarn
Version: 1.22.22

### Android SDK
Version: 14 (UpsideDownCake) ---- Level : 34

### Watchman
Version: 20240616.093132.0

### Steps to reproduce

1 Open Android Studio
2. Create a virtual device with Android 14 (Level : 34)
3. Run the device
4. Pull the **dev** branch from t he git repo provided.
5. cd Reactnativeproj1
6. npm install
7. npx react-native run-android

### Snack or a link to a repository

https://github.com/kaustavb79/Reactnativeproj1.git

### Reanimated version

3.12.1

### React Native version

0.74.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Android emulator

### Device model

Pixel 8 --- Android 14

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
@kaustavb79 you have no babel plugin in your repo. I recommend visiting [installation guide](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/#step-2-add-reanimateds-babel-plugin) and adding it. Let me know if it helps

**Comment by kaustavb79** [comment]
Check the dev branch. It's the updated one.

https://github.com/kaustavb79/Reactnativeproj1/blob/dev/babel.config.js

**Comment by kaustavb79** [comment]
> Check the dev branch. It's the updated one.
> 
> https://github.com/kaustavb79/Reactnativeproj1/blob/dev/babel.config.js

This is working in Ubuntu 20.04 LTS and also in Mac but not in Windows 10.

**Comment by szydlovsky** [comment]
@kaustavb79 okay, what is your NDK version? When searching for similar issues (and we have had a bunch of them already - it doesn't hurt to search:) ) I found that it often comes down to wrong version. See for example [this](https://github.com/software-mansion/react-native-reanimated/issues/6159#issuecomment-2188316597)

**Comment by MatiPl01** [comment]
@kaustavb79 It might be also related to the path length limit issue. See [this](https://github.com/software-mansion/react-native-reanimated/discussions/5339#discussioncomment-9926819) comment with links to proposed solutions and check if some of these work for you.

**Comment by kaustavb79** [comment]
> @kaustavb79 okay, what is your NDK version? When searching for similar issues (and we have had a bunch of them already - it doesn't hurt to search:) ) I found that it often comes down to wrong version. See for example [this](https://github.com/software-mansion/react-native-reanimated/issues/6159#issuecomment-2188316597)

NDK version is **26.1.10909125**

**Comment by kaustavb79** [comment]
> @kaustavb79 It might be also related to the path length limit issue. See [this](https://github.com/software-mansion/react-native-reanimated/discussions/5339#discussioncomment-9926819) comment with links to proposed solutions and check if some of these work for you.

Is there a way to update the path limit?

**Comment by MatiPl01** [comment]
> > @kaustavb79 It might be also related to the path length limit issue. See [this](https://github.com/software-mansion/react-native-reanimated/discussions/5339#discussioncomment-9926819) comment with links to proposed solutions and check if some of these work for you.
> 
> Is there a way to update the path limit?

You can try [this](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html) and see if it works. Alternatively, just try to move your project to the shortest possible path (e.g. temporarily just store it in the root directory of your drive).

If it doesn't work for you, maybe try [this](https://github.com/ninja-build/ninja/issues/1900#issuecomment-1828258152) one.

**Comment by kaustavb79** [comment]
I checked the file path length and its 78 and default max length limit set by default is 260 characters.
I moved it to **C:\Users\msi-kb** but it still gave the same error.
ninja.exe is not getting installed. It disappears after opening a blank command prompt for 3-4 seconds.

**Comment by kaustavb79** [comment]
It worked.
Enabled the Win32 long path flag from registry by following the steps from below link.

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by MatiPl01** [comment]
> It worked. Enabled the Win32 long path flag from registry by following the steps from below link.
> 
> https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

I'm glad that you were able to fix the issue. Thank you for letting us know how you solved the problem.
