### ISSUE TITLE
Animating multiple children with slight time difference

### ISSUE THREAD

**Issue by shrikantr-iprogrammer** [software-mansion/react-native-reanimated#623]
Hi, I'm very new to Reanimated and I find it quite interesting but at the same time I'm facing challenges implementing it. Reference to basic examples one can easily find on Google but for unique requirements content is very less. 

I have this unique requirement where I have to animate component/page children (cards) on page focus and on blur. So on page focus children/cards will slightly slide to their exact position (like right to left). And same on page blur. 
I can go to each (child) card component and implement Reanimated but I want to make it something global which can be auto applied to all future pages. Hence I have created a Container component called 'Surface' where this reanimated logic will be applied to all children/cards irrespective to whatever it is. 

```javascript
class Surface extends PureComponent {
    render(){
        const childrenWrapper = Children.map(this.props.children, (child, index) => {
            return (
                <Animated.View style={{ transform: [{ translateX: translateX }]}}>
                    {child}
                </Animated.View> 
            );
        });
        return (
            <SafeAreaView style={{flex: 1}}>
                <View style={styles.container}>
                    {childrenWrapper}
                </View>
            </SafeAreaView>
        )
    }
}
```

Is this a right approach? If yes how I can give a delay in cards' animation on page focus. I want my 1st card to reach to its position first and then about 200 to 300 ms later 2nd card and so on.
Any assistance would be greatly appreciated.

**Comment by jakub-gonet** [comment]
Hi @shrikantr-iprogrammer,

sorry for the late response. The easiest way to achieve that is to make component which will accept delay number prop (e.g. `delay_ms`) and inside animation for that component add something like this:
```js
const clock = new Clock();
const delay = new Value(delay_ms);
const initialClock = new Value(0);

// in some loop
cond(clockRunning(), 0, [startClock(clock), set(initialClock, clock)]
cond(
	greaterOrEq(clock, add(initialClock, delay)),
	//your animation here
)
```

So basically save clock timestamp at start of the animation, compare current clock time with start clock time + delay and run animation if clock run for long enough.

**Comment by albarkahdev** [comment]
@jakub-gonet it works! Thank you
