### ISSUE TITLE
Animating a nested scrollview disables all gestures and touch events on IOS

### ISSUE THREAD

**Issue by AeternaEst** [software-mansion/react-native-reanimated#6242]
### Description

While an animation is running in a nested scrollview all gestures and touch events are not working on IOS. Removing the outer scrollview or if the animation is cancelled/finished, then the touch events work again.

I have tested both in expo go and on a preview build and the behavior is the same

### Steps to reproduce

1. Add an outer ScrollView (dosen't matter if it's from react-native or reanimated)
2. Add a nested Animated.ScrollView
3. Start an animation on the Animated.ScrollView (e.g contentOffset)
4. Try to click on any touchable/pressable while the animation is running

### Snack or a link to a repository

https://github.com/AeternaEst/reanimated-scrollview

### Reanimated version

3.10.1

### React Native version

0.74.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

IPhone 15

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
This issue is rather related to the react-native itself, not to the `react-native-reanimated` library. I noticed that when I changed `Animated.ScrollView` to `ScrollView` and used `ref.current?.scrollTo` in `setInterval`, I am still not able to press buttons on the bottom of the screen.

**Comment by MatiPl01** [comment]
[This](https://github.com/facebook/react-native/issues/35332) seems to be an issue similar to yours. It is already reported in the react-native repo and I think it should be fixed in there.  It mentions `FlatList`, but it uses a `ScrollView` internally, so seems to be the same problem.

I am closing this issue as there seems to be nothing we can do on our side. Feel free to re-open it or ask more questions if you have some.

**Comment by AeternaEst** [comment]
Hi @MatiPl01 

Thanks for looking into it. I can confirm your workaround is working with a slightly different syntax:

```
const tapHandler = Gesture.Tap()
    .onEnd(() => {
      Alert.alert("Click");
    })
    .runOnJS(true);
```

So I will continue with that. Thanks again.
