### ISSUE TITLE
useAnimatedStyle does not update Animated.View styles on rerender

### ISSUE THREAD

**Issue by AidenCohen31** [software-mansion/react-native-reanimated#6298]
### Description

Currently, when updating the state using a setState call, useAnimatedStyle does not properly update an Animated.View style on re-render. The expected behavior would be that after the useState call the slider thumb maintains its current position, however right now it resets to default position (height=0). Interestingly enough, replacing the animatedstyles variable with `{top : Math.round((height-20) * value.value/100) }` fixes the issue, but only updates the position on re-render.

Code below:
```
export default Parent= ()=>{
      const [height,setHeight] = useState(0);
      return <Slider max={10} min={0} onUpdate={(value:any)=>{setHeight(value)}} ></Slider>
}
export const Slider = (props)=>{
    const value = useSharedValue(0);
    const sliderRef = useAnimatedRef()
    const [height, setHeight] = useState(0);
    const onLayout = (e:any)=>{
        const {x, y, height, width} = e.nativeEvent.layout;
        setHeight(height)
    }
    const sliderGesture = Gesture.Pan().onUpdate((e)=>{
            value.value = clamp(Math.round((e.y/height) * 100), 0, 100)
    }).onEnd(
        (e)=>{
                    runOnJS(props.onUpdate)(value.value)
                    value.value = clamp(Math.round((e.y/height) * 100), 0, 100)
     })
    const animatedStyles = useAnimatedStyle(()=>{
        return {
            top : Math.round((height-20) * value.value/100)
        }
    })
    return(
      <GestureHandlerRootView>
        <GestureDetector gesture={sliderGesture} >
        <Animated.View ref={sliderRef} style={[props.styles, styles.selection]}  onLayout={(e)=>onLayout(e)}>
        <Animated.View  style={styles.sliderBack}>
            <Animated.View style={[styles.sliderThumb , animatedStyles]}>
            </Animated.View>
        </Animated.View>
        </Animated.View>
        </GestureDetector>
        </GestureHandlerRootView>
    )
}
```

### Steps to reproduce

1. check reproduction in snack

### Snack or a link to a repository

https://snack.expo.dev/@aidencohen31/funny-green-kiwi

### Reanimated version

3.10.1

### React Native version

0.74.3

### Platforms

Android, Web

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

None

### Acknowledgements

Yes

**Comment by AidenCohen31** [comment]
Thanks a lot, seems to work good now 👍

**Comment by MatiPl01** [comment]
Awesome!
I am closing the issue. Feel free to reopen it if you still encounter the problem.

**Comment by mjcarnaje** [comment]
Nice, Thanks @MatiPl01 🎉
