### ISSUE TITLE
PhaseScriptExecution fails for Hermes Engine after install of react-native-reanimated

### ISSUE THREAD

**Issue by mstohr1975** [software-mansion/react-native-reanimated#6333]
### Description

I've reproduced an issue, whenever I install with npm install react-native-reanimated, then reinstall the pods with cd ios && pod install && cd .. and build the app with npx react-native run-ios I run into an error on Hermes Engine:

PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/<user>/Library/Developer/Xcode/DerivedData/<dir>/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/hermes-engine.build/Script-46EB2E0001CA80.sh (in target 'hermes-engine' from project 'Pods')
(1 failure)

Same project before installing reanimated builds perfectly fine, I reproduced it a couple times. Any thoughts how to overcome this? Many thx

### Steps to reproduce

1. npm install react-native-reanimated
2. cd ios && pod install && cd ..
3. npx react-native run-ios

### Snack or a link to a repository

happy to share later

### Reanimated version

3.14.0

### React Native version

0.73.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by fredrifoUni** [comment]
This usually fixes it for me:
1. `rm ios/.xcode.env.local`
2. `pod install `

If that still doesn't work, clear the derived data and rebuild

**Comment by fredrifoUni** [comment]
@mstohr1975 
Did you try to delete the derived data folder? If not, I'm not sure what could be causing it
`Users/mstohr/Library/Developer/Xcode/DerivedData/`

**Comment by mixnam** [comment]
What is the config in your `ios/.xcode.env.local` ?
Make sure that right path to node is specified in NODE_BINARY var. If it's not the right path to your actual node version, then just correct it manually. It worked for me

**Comment by piaskowyk** [comment]
Hey, it appears that this issue is not Reanimated-related; rather, it seems to be a problem with the project configuration that is independent of Reanimated. You should define the environment variable `REACT_NATIVE_PATH`, and that should help resolve the issue.
![image](https://github.com/user-attachments/assets/98ad9f74-3481-496f-8bb3-eefb4b9577c9)

**Comment by Neeraj-WebNeuron** [comment]
The following build commands failed:
        PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/ios/build/Pods.build/Debug-iphoneos/hermes-engine.build/Script-46EB2E00021D90.sh (in target 'hermes-engine' from project 'Pods')
(1 failure)

**Comment by workflowdigital-george** [comment]
> The following build commands failed: PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/ios/build/Pods.build/Debug-iphoneos/hermes-engine.build/Script-46EB2E00021D90.sh (in target 'hermes-engine' from project 'Pods') (1 failure)
> 
> Facing issue since a week now

Also facing the same issue. Did you manage to resolve this?

**Comment by workflowdigital-george** [comment]
> Yes, we did...as mentioned above. Let me know if this helps, otherwise we're happy to support.

I'm using expo eas to to do the building so I don't believe I can get access to the xcode.env.local file.
