### ISSUE TITLE
Unable to set shadowOffset through reanimated

### ISSUE THREAD

**Issue by MoeMamdouh** [software-mansion/react-native-reanimated#634]
```
<Animated.View
  style={[
    styles.playBtn,
    {
      shadowOffset: {
        height: interpolate(progress, {
          inputRange: [0, 1],
          outputRange: [5, 10],
          extrapolate: Extrapolate.CLAMP,
        }),
        width: 0,
      },
    },
  ]}
/>
```
the results 
<img width="384" alt="Screen Shot 2020-03-06 at 7 48 32 PM" src="https://user-images.githubusercontent.com/16561058/76108770-ddb40980-5fe3-11ea-9ec6-e0bff823c570.png">

**Comment by pr0da** [comment]
I have the same problem with `textShadowOffset`. Other text shadow props work properly (e.g.: `textShadowRadius`).

**Comment by jakub-gonet** [comment]
Please provide repro, I wasn't able to reproduce it on my own.

It may be caused when certain properties aren't listed in the config, you can use `addWhitelistedNativeProps` and `addWhitelistedUIProps` to add them.

**Comment by nasmuris** [comment]
@jakub-gonet I have the same problem as @MoeMamdouh even when trying to use `addWhitelistedUIProps({shadowOffset:true})`, 
reanimated version `1.11.0`
platform: `iOS`

repro:
```
import Animated from 'react-native-reanimated';
Animated.addWhitelistedUIProps({shadowOffset:true});
const X = () => {
  const progress = useRef(new Animated.Value(0)).current;

  return <Animated.View
    style={[
      {
        shadowOffset: {
          height: interpolate(progress, {
            inputRange: [0, 1],
            outputRange: [5, 10],
            extrapolate: Extrapolate.CLAMP,
          }),
          width: 0,
        },
      },
    ]}
  />
}
```

**Comment by jakub-gonet** [comment]
This is related to the wrong handling of nested styles internally.

Repro:
```jsx
import React from 'react';

import Animated from 'react-native-reanimated';
Animated.addWhitelistedUIProps({shadowOffset: true});
const Example = () => {
  return (
    <Animated.View
      style={[
        {
          shadowOffset: {
            height: new Animated.Value(50),
            width: 20,
          },
        },
      ]}
    />
  );
};

export default Example;
```

PS. @nasmuris - if you use useRef like that: `useRef(new Animated.Value(0)).current;` it won't give you much value, because it's creating and disposing new `Animated.Value` per rerender. Check out [`useValue`](https://github.com/software-mansion/react-native-reanimated/blob/ba8423e472f64b619da18ea79cca1a079606a7f4/src/useValue.js)

**Comment by jakub-gonet** [comment]
Fixing this bug requires changing a lot of internal implementation (same problem as in transform node). We discussed it internally and decided to not fix this one - we're focusing on getting v2 stable in where this problem don't exist.

We're open for small PRs though.
