### ISSUE TITLE
WithDelay of 0ms should not cause any delay

### ISSUE THREAD

**Issue by Latropos** [software-mansion/react-native-reanimated#6341]
### Description

Definitely `withDelay(0,s omeAnimation);` shouldn't cause any delay, and even if it cause it should be to small to be noticeable.
Yet the delay is clearly visible;
The lower square in the recording has the delay of 0ms attached.

https://github.com/user-attachments/assets/261d92d2-f302-4240-96c8-3d14352431c2

### Steps to reproduce

Replace current EmptyExample with

```tsx
import { StyleSheet, View, Button } from 'react-native';
import React from 'react';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withDelay,
  withTiming,
} from 'react-native-reanimated';

export default function EmptyExample() {
  const leftSV = useSharedValue(0);

  const animatedStyle = useAnimatedStyle(() => {
    return { left: withTiming(leftSV.value) };
  });

  const animatedStyleDelayed = useAnimatedStyle(() => {
    return { left: withDelay(0, withTiming(leftSV.value)) };
  });

  return (
    <View style={styles.container}>
      <Button
        title="toggle"
        onPress={() => {
          leftSV.value = leftSV.value === 200 ? 0 : 200;
        }}
      />
      <Animated.View style={[styles.box, animatedStyle]} />
      <Animated.View style={[styles.box, animatedStyleDelayed]} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 50,
  },
  box: {
    height: 50,
    width: 50,
    backgroundColor: 'navy',
    borderRadius: 5,
    margin: 5,
  },
});
```

### Snack or a link to a repository

https://snack.expo.dev/tOBz0-UpuWHJjKJqu6p9-

### Reanimated version

nightly

### React Native version

0.74.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by TomCorvus** [comment]
For me, it is not a bug, it is just the delay to execute the code like a native `setTimeout`.
If you execute a function directly and execute the same function in a the setTimeout 0, the function called by the setTimeout will be always called after even if the `setTimeout` is called before.

```js
function consoleLog(mode = "directly") {
    console.log("called " + mode)
}

setTimeout(() =>{
    consoleLog("with timeout");
}, 0)

consoleLog();
```

if you don't want any delay, call `withTiming` directly. Or if the delay value is a prop, write a condition for calling `withTiming` if delay is > 0.
