### ISSUE TITLE
Can't run Code block on tests

### ISSUE THREAD

**Issue by Dan-Kovalsky** [software-mansion/react-native-reanimated#635]
Hey.
I have a reanimated view with reanimated.Code.
```
const {Code, Value, cond, set, and, call, block, eq} = Reanimated;

render() {
    return (
      <Reanimated.View>
        {loaded && <MyComponent/>}
        <Code>
          {this.renderCodeBlock}
        </Code>
      </Reanimated.View>
    );
}
```
The `Code` execute some reanimated nodes, that also change the value of loaded to render the MyComponent.

When I test it using

> jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));

The code block doesn't execute so MyComponent does not renders at all.
How can I mock `Code`?
Thanks

**Comment by jakub-gonet** [comment]
Hi @Dan-Kovalsky,

sorry for the late response.
We're mocking `Code` as `null` rendering component and most nodes as `NOOP`s (`function NOOP(){}`) which means you can't really execute code in reanimated.

You should provide your own implementation of `Code` mock which changes `loaded` based on some conditions in JS code.

If you have further questions feel free to reopen.
