### ISSUE TITLE
createEventObjectProxyPolyfill is broken

### ISSUE THREAD

**Issue by olegbl** [software-mansion/react-native-reanimated#639]
When Proxy isn't available, using Reanimated.event() with a callback will crash.

The issue is here: https://github.com/software-mansion/react-native-reanimated/blob/master/src/core/createEventObjectProxyPolyfill.js#L38

When traverse is called, `__isProxy` is already set. So, `__isProxy` will be one of the keys traversed. As a result, we will be trying to do `obj[key].__isProxy = true;` on `obj = {__isProxy: true}`, `key = '__isProxy'` which of course crashes since `true.__isProxy = true;` is not valid JavaScript.

Reordering the two lines (traversing before setting __isProxy) would likely resolve the issue. Alternatively, wrapping the set call in a typeof check would also work.

EDIT: Actually, `true.__isProxy = true;` surprisingly does work in some JavaScript runtimes (e.g. Chrome V8) but not all (e.g. [Hermes](https://github.com/facebook/hermes)).

EDIT: Or, more accurately, it seems that this statement is fine in non-strict mode JS but fails in strict mode JS.

**Comment by olegbl** [comment]
Actually, `true.__isProxy = true;` surprisingly does work in some JavaScript runtimes.

**Comment by TheWirv** [comment]
> Reordering the two lines (traversing before setting __isProxy) would likely resolve the issue. Alternatively, wrapping the set call in a typeof check would also work.

Thanks man, the reordering actually solved my problem. I updated a bunch of packages (incl. Hermes I guess), and all of a sudden all my event-driven animations threw an "Cannot create a new property on a transient object" exception.

As I said, the reordering seems to be the fix. Until this is implemented, I [patched my package](https://www.npmjs.com/package/patch-package).

**Comment by jakub-gonet** [comment]
Hi @olegbl,
thanks for reporting, I created PR fixing this one.
