### ISSUE TITLE
useAnimatedRef<Animated.FlatList<any>>() always return null v2.8.0

### ISSUE THREAD

**Issue by bonnmh** [software-mansion/react-native-reanimated#6416]
### Description

useAnimatedRef<Animated.FlatList>() always return null with react-native-reanimated@2.8.0. I tried following both v2 and v3 documentation but got null value. All operations are normal with useAnimatedRef<Animated.View>()

```
function App() {
  const animatedRef = useAnimatedRef();

  console.log(animatedRef.current); // 🚩 Returns null

  useEffect(() => {
    console.log(animatedRef.current); // ✅ Returns the component
  }, []);

  return <View ref={animatedRef} />;
}
```

### Steps to reproduce

useAnimatedRef<Animated.FlatList>() always return null with react-native-reanimated@2.8.0. I tried following both v2 and v3 documentation but got null value. All operations are normal with useAnimatedRef<Animated.View>()

```
function App() {
  const animatedRef = useAnimatedRef();

  console.log(animatedRef.current); // 🚩 Returns null

  useEffect(() => {
    console.log(animatedRef.current); // ✅ Returns the component
  }, []);

  return <View ref={animatedRef} />;
}
```

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

2.8.0

### React Native version

0.68.7

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

iPhone 14 Pro Max

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
Hey!
Will you be able to upgrade reanimated to v3 or you must use v2? We no longer support v2 and there is no issue in v3.

**Comment by bonnmh** [comment]
> Hey! Will you be able to upgrade reanimated to v3 or you must use v2? We no longer support v2 and there is no issue in v3.

Thanks for your feedback, I was using v3 fine in another project, unfortunately I can't use v3 in my current project due to some other issues. However, I switched to using the alternative solution using Animated.ScrollView

**Comment by MatiPl01** [comment]
Good to hear that you managed to resolve your problem. 
I will close this issue, since you said that `useAnimatedRef` works fine in v3 and we no longer actively support v2.
Feel free to re-open the issue and ask if you have more questions.
