### ISSUE TITLE
Fails to build on react-native-macos 0.74.1

### ISSUE THREAD

**Issue by hsjoberg** [software-mansion/react-native-reanimated#6421]
### Description

Hi. When trying to build react-native-reanimated with react-native-macos 0.74.1, the following syntax error is encountered in [REASizzledManager.mm#L235](https://github.com/software-mansion/react-native-reanimated/blob/b2f4e1dcfe51004becc0fb19d99ee073bf2c1229/packages/react-native-reanimated/apple/reanimated/LayoutReanimation/REASwizzledUIManager.mm#L235) and in other places.

```
Cannot initialize return object of type 'RCTViewManagerUIBlock' (aka 'void (^)(RCTUIManager *__strong, NSDictionary<NSNumber *,NSView *> *__strong)') with an rvalue of type 'void (^)(RCTUIManager *__strong, NSDictionary<NSNumber *,REAUIView *> *__strong)'
```

Simply changing `REAUIView` to `NSView` everywhere where the compiler complains seems to fix the issue.
But I don't know react-native-reanimated's inner workings well enough to understand if this is a sane approach.
If yes, I can submit a PR.

Also, react-native-gesture-handler has a similar issue as this one. I could file a bug report there too if needed.

### Steps to reproduce

Try to build the demo project to see the issue.

Due to an unrelated issue in react-native-macos 0.74.1 https://github.com/microsoft/react-native-macos/issues/2165, you may have to clear out the build phase script `[CP-User] [RN]Check rncore` in the `React-Fabric` pod before building.

### Snack or a link to a repository

https://github.com/hsjoberg/rnmacos74/tree/reanimated (`reanimated` branch)

### Reanimated version

3.15.0

### React Native version

0.74.1

### Platforms

macOS

### JavaScript runtime

JSC

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by hsjoberg** [comment]
It seems like NSView is being expected somewhere instead of REAUIView (which is a [typedef of RCTUIView](https://github.com/software-mansion/react-native-reanimated/blob/c7f4b5f9b1157a31da289f9065961ac526f96bf1/packages/react-native-reanimated/apple/reanimated/REAUIKit.h#L7-L11) for macOS, *not* NSVIew), but I cannot quite figure out where.

**Comment by hsjoberg** [comment]
The issue is essentially that `RCTViewManagerUIBlock` that's being used as arg to [`reanimated_addUIBlock()`]() expects `UIView` in react-native and `NSView` in react-native-macos, but reanimated's `REAUIView` is typedef'd as `RCTUIView` on macos.

`RCTViewManagerUIBlock`:
react-native (iOS): https://github.com/facebook/react-native/blob/ade863a48cd78039dd68e7176e339cdaca3b0f74/packages/react-native/React/Views/RCTViewManager.h#L22

react-native-macos: https://github.com/microsoft/react-native-macos/blob/042cd6c36b23c21d20de628bc9756793e01ce282/packages/react-native/React/Views/RCTViewManager.h#L22 (RCTPlatformView in turn defined as NSView: https://github.com/microsoft/react-native-macos/blob/042cd6c36b23c21d20de628bc9756793e01ce282/packages/react-native/React/Base/RCTUIKit.h#L382).

**Comment by hsjoberg** [comment]
Okay, I've quick & dirty fixes for react-native-reanimated and react-native-gesture-handler here:

https://github.com/hsjoberg/react-native-native-reanimated/tree/rn75fix
https://github.com/hsjoberg/react-native-gesture-handler/tree/rn75fix

Just using `#ifdef` to output NSView or UIView.

I don't know the proper solution here but I'm happy to make a PR if someone would give some directions.

**Comment by tomekzaw** [comment]
@hsjoberg Thanks for the investigation! I think we're okay with `#ifdef` approach in those cases, feel free to submit a PR.

**Comment by piaskowyk** [comment]
It's likely that this fix will also resolve https://github.com/software-mansion/react-native-reanimated/issues/6501

**Comment by hsjoberg** [comment]
@tomekzaw Sure, I can into submitting a PR soonish. 🙂 

> I'm also curious to learn more about your experience with RNGestureHandler on macOS since this is a pretty new feature that we'd like to get some feedback on (cc @m-bert who's the co-author of the macOS implementation).

Sorry, I don't have any direct feedback on regarding RNGestureHandler on macOS. I use @react-navigation/drawer, which pulls it in. I really appreciate react-native-{windows/macos} support for libs though. 💯 

@piaskowyk Yes, #6501 is the same issue.

**Comment by hsjoberg** [comment]
In closing this one in favor of upstream fixes in react-native-macos https://github.com/software-mansion/react-native-reanimated/issues/6501#issuecomment-2361833956.
