### ISSUE TITLE
[docs] wrong internal link in docs

### ISSUE THREAD

**Issue by 321paranoiawhy** [software-mansion/react-native-reanimated#6434]
### Description

In [this link](https://docs.swmansion.com/react-native-reanimated/docs/advanced/setNativeProps#remarks),  the href of `useAnimatedStyle` and `useAnimatedProps` are wrong, the shoule be `https://docs.swmansion.com/react-native-reanimated/docs/core/useAnimatedStyle/` and `https://docs.swmansion.com/react-native-reanimated/docs/core/useAnimatedProps/`

### Steps to reproduce

Go to [this link](https://docs.swmansion.com/react-native-reanimated/docs/advanced/setNativeProps#remarks) and click `useAnimatedStyle` and `useAnimatedProps`, you will see the wrong internal link.

### Snack or a link to a repository

None

### Reanimated version

3.12.1

### React Native version

0.74.2

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

Noe

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
Hey!

Thanks for reporting the issue. I prepared a PR that will fix these and other links in docs.
It should be merged soon.
