### ISSUE TITLE
all react-native-reanimated version giving error on latest react nativev0.75.2 cli project 

### ISSUE THREAD

**Issue by zeeshan9** [software-mansion/react-native-reanimated#6492]
### Description

I just created a new react native projec few days ago in 0.75.2 in react-native cli. I am using react navigation lib v6, i want to use drawer for that i installed react-native-reanimated package but it keeps showing error i have tried a lot things, combining different version between react-native-gesture-handler and reanimated, but it always show some new error.
Mostly its shown error worklet one and the isConfugured is undefined and other image that is shown. I have even create a project in cli 0.73.3 and in 0.72.6 hoping maybe reanimated work fine there but its giving issue everywhere, i have added import 'react-native-gesture-handler'; in top of my app.ts also saw a solution somewhere to do that.

i have added animated pugin in bable.config.js too,
module.exports = {
presets: ['module:@react-native/babel-preset'],
plugins: [
'react-native-reanimated/plugin',
],
};

i am stuck for many days, if anyone know the correct compatible version on which there app is running let me know.
i have run command npm run doctor my settings and other configuration are all good. i have install ndk in v26 from android sdk.
Really need help here, I am creating my first app to lauch in playstore and appstore. but my project have many screens so ineed drawer. Also just to let you know if i remove reanimated packge and also the drawer then project is running fine.
I have tried the its latest version, 3.3.0, 3.10.1 onward to to 3.15, also 2.2.0 , 2.7.0 but nothing seems to works.

>npx react-native info
System:
OS: macOS 14.5
CPU: (11) arm64 Apple M3 Pro
Memory: 67.27 MB / 18.00 GB
Shell:
version: "5.9"
path: /bin/zsh
Binaries:
Node:
version: 20.12.1
path: ~/.nvm/versions/node/v20.12.1/bin/node
Yarn:
version: 1.22.22
path: /opt/homebrew/bin/yarn
npm:
version: 10.5.0
path: ~/.nvm/versions/node/v20.12.1/bin/npm
Watchman:
version: 2024.08.05.00
path: /opt/homebrew/bin/watchman
Managers:
CocoaPods:
version: 1.15.2
path: /Users/zeeshanm/.rbenv/shims/pod
SDKs:
iOS SDK:
Platforms:
- DriverKit 23.5
- iOS 17.5
- macOS 14.5
- tvOS 17.5
- visionOS 1.2
- watchOS 10.5
Android SDK:
API Levels:
- "29"
- "33"
- "34"
Build Tools:
- 30.0.3
- 33.0.1
- 34.0.0
System Images:
- android-33 | Google Play ARM 64 v8a
Android NDK: Not Found
IDEs:
Android Studio: 2023.2 AI-232.10300.40.2321.11567975
Xcode:
version: 15.4/15F31d
path: /usr/bin/xcodebuild
Languages:
Java:
version: 17.0.10
path: /usr/bin/javac
Ruby:
version: 2.7.5
path: /Users/zeeshanm/.rbenv/shims/ruby
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.3.1
wanted: 18.3.1
react-native:
installed: 0.75.2
wanted: 0.75.2
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: false

### Steps to reproduce

1. create a react native cli project using android sdk set to 4 in sdk manager. or just install latest react cli 0.75.2
2. Install latest react navigation packages especially fordrawer and gesture handle and react-native-reanimated pakage.
3. run the project in npm run android, or in ios it give errors. below are the screen shots attach

![image](https://github.com/user-attachments/assets/385c9385-fdcf-4e78-bb5e-0c3f06962e19)
![image](https://github.com/user-attachments/assets/497ed328-30e7-462b-902e-e63af4c17ddc)

### Snack or a link to a repository

https://github.com/zeeshan9/wealthspecter.git

### Reanimated version

3.15.1

### React Native version

0.75.2

### Platforms

Android, iOS, macOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

PIxal 8 API level 33

### Acknowledgements

Yes

**Comment by tjzel** [comment]
I've looked into your repo and you don't have `react-native-reanimated` nowhere in the `package.json` nor `package-lock.json`. Are you sure you aren't installing Reanimated globally or in some other package accidentally?

We test bare RN apps from CLI with Reanimated every day and things are working fine. 

Regarding Android build errors, this is caused by using NDK27 which is not yet embedded into React Native. As I've noticed from your repo, you used nightly version which supports NDK27 so the build errors are gone.

**Comment by zeeshan9** [comment]
Because i am being updating the app and pushing changes and trying different version, sorry forgot to mentioend there is navigation-setup branch where i am using all navigation packages, Also I am using ndk 26 not 7, the nightly version is in my app is becaue i am testing whatever solution i can find. But reanimated really is giving issue also even on ios its not running. if you want to use drawer we need reanimated. and build always got fail. I have already seen more than 1 issue open in react native community in github. 
@EmilJunker is right ihave downgrade drawer reanimated and gesture but nothings work yet.
Reproduction: Just clone my repo or build latest react native project and install above package and run app build will fail. =

**Comment by zeeshan9** [comment]
Someone in react react-native-community/cli community have given me the answer, If i used yarn it its working fine and project also build fine for both ios and android. But if i used npm reanimated is giving error in not just latest but in some previous one too. 
But building on yarn project is running without any build error,
also run below command, if error comes
`yarn config set nodeLinker node-modules`

**Comment by santhana-10423maticz** [comment]
checklist
your babel.config look like this

```js
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```

you have to check react-native-reanimated plugin installed
Everything is work fine means still run time error present means you have to restart the system

**Comment by Hiten-Chavda** [comment]
Same problem I stucked.

**Comment by littleluckly** [comment]
> Someone in react-native-community/cli community have given me the answer, If i used yarn it its working fine and project also build fine for both ios and android. But if i used npm reanimated is giving error in not just latest but in some previous one too. But building on yarn project is running without any build error, also run below command, if error comes `yarn config set nodeLinker node-modules`

I encountered a similar issue with you, constantly getting errors with react-native@0.75.2 and react-native-reanimated@3.16.0, but it worked fine when I used yarn to install them.
