### ISSUE TITLE
Invariant violation native module cannot be null

### ISSUE THREAD

**Issue by alexandreaugus** [software-mansion/react-native-reanimated#650]
Hi, I have already double checked if the package was correctly linked and I still can't get it to work.
I am using
React: 16.12.0
React-Native: 0.61.5

Any ideas?

**Comment by Harsh2402** [comment]
Same issue

**Comment by miguel550** [comment]
Same issue

**Comment by jakub-gonet** [comment]
Hi @Harsh2402, @alexandreaugus, @miguel550 

please provide a link to the repository with smallest possible example which reproduces this error. Otherwise, we can't really help you.

**Comment by tmaly1980** [comment]
This happens for me when running tests. The native code has to be mocked up in a jest.setup.js, since jest is just testing the javascript/react. If I figure it out I'll post it here.

**Comment by jakub-gonet** [comment]
We have mocks ready for that, check out [`mock.js`](https://github.com/software-mansion/react-native-reanimated/blob/master/mock.js)

**Comment by tmaly1980** [comment]
@jakub-gonet Great, that worked for me. I just needed to add the jest.mock() call mentioned there into my jest.setup.js file

**Comment by jakub-gonet** [comment]
Closing due to no response.

**Comment by EvgenyBo** [comment]
![image](https://user-images.githubusercontent.com/18396912/89571587-98189880-d830-11ea-82b2-b472af92d248.png)

Can't launch the Example project.
Did everything according to the getting started guide.
