### ISSUE TITLE
Errors when running with bridgeless mode on

### ISSUE THREAD

**Issue by baselshlewett** [software-mansion/react-native-reanimated#6502]
### Description

If bridgeless mode is enabled on iOS(mainly, android seems to build and run fine) it will throw error ```Error: [Reanimated] Native part of Reanimated doesn't seem to be initialized.```

Turning off bridgeless mode on iOS seems to 'fix' the problem, but it's not a really good workaround.

### Steps to reproduce

1. Enable bridgeless mode on iOS and build the app.

### Snack or a link to a repository

private repository

### Reanimated version

3.15.1

### React Native version

75.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
I've just tried Reanimated on a fresh React Native app, and it works without any problems. 🤔 Unfortunately, without reproduction, I can't do more than suggest checking out the section in the documentation: [Troubleshooting - Reanimated](https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#native-part-of-reanimated-doesnt-seem-to-be-initialized). Ensure that you've run `pod install` and rebuilt the app after that.

How I tested it:
```
npx react-native init rn75 --version 0.75.2
cd rn75
yarn add react-native-reanimated
cd ios
export RCT_NEW_ARCH_ENABLED=1 && pod install
// add Reanimated babel plugin
yarn start
```
