### ISSUE TITLE
Shared value update in useEffect not reflected in view in v3

### ISSUE THREAD

**Issue by RestlessDream** [software-mansion/react-native-reanimated#6508]
### Description

There is an issue with updating a shared value inside useEffect based on state changes in v3. When the shared value is updated, the view does not consistently reflect this update. Additionally, after the state changes again, the shared value seems to use the previous state instead of using the most recent value.
https://snack.expo.dev/@iklapatniuk/rn-reanimated-v3-sv-update-in-useeffect

[RN-reanimated-v3.webm](https://github.com/user-attachments/assets/09f2fb05-8c27-47d8-b052-e36f82f50640)

It isn't reproducible in v2: https://snack.expo.dev/@iklapatniuk/rn-reanimated-v2-sv-update-in-useeffect

[RN-reanimated-v2.webm](https://github.com/user-attachments/assets/b462f31e-204c-4a70-afdc-ecb81237a570)

### Steps to reproduce

1. Create a state variable and a shared value.
2. In the useEffect, update the shared value whenever the state changes.
3. Observe that the view doesn't always reflect the updated shared value in Reanimated v3.
4. Change the state again, and notice that the shared value uses the older state instead of the most recent one.

### Snack or a link to a repository

https://snack.expo.dev/@iklapatniuk/rn-reanimated-v3-sv-update-in-useeffect

### Reanimated version

3.10.1

### React Native version

0.74.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

None

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @RestlessDream. Unfortunately, the use of `useEffect` here is incorrect in two ways.

First of all, React is not "aware" of changes to a Shared Value. Animations ran by Reanimated are decoupled from React and tied to the Native Views instead.

Second of all, take a look at this snippet:
```tsx
    const sv = useSharedValue(translateX);
    const sv2 = useSharedValue(translateX);
    useEffect(() => {
        sv.value = translateX
        sv2.value = translateX
    }, [translateX]);
```

Shared Values are in some way similiar to use ref - they hold some data, but the reference returned by the hook itself doesn't change. Therefore the `useEffect` callback won't get re-triggered ever. Keep in mind that putting `translateX.value` inside `useEffect`'s dependency array would still be a faulty solution. You can read more about it [here](https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue#remarks).

What you need here is either a [Derived Value](https://docs.swmansion.com/react-native-reanimated/docs/core/useDerivedValue) or [useAnimatedReaction](https://docs.swmansion.com/react-native-reanimated/docs/advanced/useAnimatedReaction) hook, i.e.

```tsx
const sv = useDerivedValue(() => translateX.value);
const sv2 = useDerivedValue(() => translateX.value);
```

**Comment by RestlessDream** [comment]
Hi @tjzel, thanks for the response. `translateX` is actually a React state, so it will be triggered. I'm not sure what's so special about `useEffect` here. At first, I thought the issue was with shared value synchronization between the JS and UI threads. But I tried a few things, like setting the shared value directly in the component and using `setInterval`, and everything worked perfectly every time.

I suspect it has something to do with when `useEffect` is triggered. I tested it with different versions—v2 works consistently, but none of the v3 versions do. And I've had the same issue on both architectures.

I'm glad you mentioned `useAnimatedReaction`. I initially thought it might be deprecated since there's no v3 documentation, but it turns out to be a workaround.

**Comment by tjzel** [comment]
@RestlessDream I apologize, I don't know why I read `translateX` as a Shared Value. I was replying to a similar issue at the same time and it seems I got it mixed up in my head 😅 

The problem you are facing here is the use of `translateX` in Gesture Handler's callbacks. `translateX` is a React state and the callback is a worklet. Therefore, `translateX` will never get updated in the worklet unless it gets invalidated occasionally.

All input values of worklets should be Shared Values if you expect reactivity.

Any input value that isn't a Shared Value won't ever change for the worklet during its lifetime. Let's look at this callback:

```tsx
        .onChange(e => {
            sv.value = translateX + e.translationX
        })
```

`translateX` is an input value in that case. It comes from outside and is used to get an output, `sv.value` in this case. Therefore, `translateX` won't ever change in this context, unless the worklet gets invalidated.

Looking at another callback:

```tsx
        .onEnd(e => {
            runOnJS(setTranslateX)(translateX + e.translationX)
        })
```
Here, again, `translateX` has the value it had __when the worklet was created__ which doesn't at all align with its current value on the React thread.
