### ISSUE TITLE
[3.15.3] is available as an update but not on npmjs site, there's no release PR either

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#6528]
### Description

Hey folks, don't know what's going on but it seems there's 3.15.3 available on npm registry but the npmjs site does not list it under `Versions` and there's no PR about releasing 3.15.3.

 # Are we doomed?

### Steps to reproduce

read above

![Screenshot 2024-09-20 at 15 26 25](https://github.com/user-attachments/assets/0a7fd59f-b12a-46f9-9261-911f04fb7d3d)

### Snack or a link to a repository

none

### Reanimated version

3.15.3?

### React Native version

0.75.3

### Platforms

Android, iOS, macOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment]
You made my day, I love it 😍 

@bartlomiejbloniarz went for a lunch when he was releasing. Also we don't usually do PRs for patches. 🚀

**Comment by efstathiosntonas** [comment]
@tjzel phew, I’ve runner 3 malware scans on my machine and I’ve sent the .tar on 3 online virus scanners hahahaha
