### ISSUE TITLE
Regression with proc'ed functions such as diffClamp

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#655]
proc'ed functions that invoke non-proc'ed functions such as diffClamp that invoke diff instead of internalDiff, seem to have serious regression.

I will make a bug-fix proposal for diffClamp, but mentioning the issue here in case it can help with other functions.

**Comment by wcandillon** [comment]
It looks like I maybe have been mistaken. My apologies.

**Comment by wcandillon** [comment]
My assumption is that any proc'ed function cannot call a non-procable function: for instance diffClampProc invoking diff. I will provide an example for this.

**Comment by wcandillon** [comment]
See https://github.com/wcandillon/react-native-redash/issues/234

**Comment by jakub-gonet** [comment]
[Here's](https://snack.expo.io/i2Cv9RZU8) an example with `proc` calling not `proc`'ed function

It works correctly, so I suppose this problem arises on the more complex scenario or when interacting with RNGH

**Comment by jakub-gonet** [comment]
Linked issues:
#789 - `proc` + `setState`
#809 - setting Value to Value (e.g. `set(a, b)`, where `a` and `b` are `Animated.Value`s) doesn't work properly in `proc` 
#594 - `overshootClamping` in `spring`
