### ISSUE TITLE
useAnimatedStyle not working with shadowOpacity

### ISSUE THREAD

**Issue by amirg** [software-mansion/react-native-reanimated#6550]
### Description

See this snack demonstrating the issue: https://snack.expo.dev/@amirzies/nervous-orange-strawberries

When setting shadowOpacity using useAnimatedStyle, the style does not appear to change. In the snack above, if I set opacity using the shared value, the box fades in and out; however, if I set shadowOpacity, the box shadow does not change.

### Steps to reproduce

1. See linked snack: https://snack.expo.dev/@amirzies/nervous-orange-strawberries
2. If you uncomment line 18, so that opacity uses the sharedValue, you will see that the shared value is updating and opacity changes. However, shadowOpacity on line 20 is not changing despite using the same shared value.

### Snack or a link to a repository

https://snack.expo.dev/@amirzies/nervous-orange-strawberries

### Reanimated version

3.10.1

### React Native version

0.74.3

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by vkl2109** [comment]
Running into same issue!!
