### ISSUE TITLE
Task :react-native-reanimated:buildCMakeDebug[arm64-v8a] FAILED

### ISSUE THREAD

**Issue by kikikiswanto** [software-mansion/react-native-reanimated#6594]
### Description

Error after upgrade RN
i create new project with new RN
i migrate all code to new project
all already fine
next step i install reanimated for using animate
but got error build 
current version "react-native-reanimated": "^3.15.5",

i try downgrade version "react-native-reanimated": "^2.7.0",
build success but app crash and stop working on android emulator

![image](https://github.com/user-attachments/assets/4ec529c3-4b72-4ad6-a9de-6606b8a50919)
![image](https://github.com/user-attachments/assets/95691386-a2a7-4641-af9d-46a66d120cd4)
![image](https://github.com/user-attachments/assets/4a94cbc0-0cd1-4678-8f8d-ca7783d14791)

### Steps to reproduce

1. npm install react-native-reanimated
2. add 'react-native-reanimated/plugin' in babel.config.js
3. npm start -- --reset-cache
4. select a (for run android)
5. and error

### Snack or a link to a repository

https://snack.expo.dev/eC-VGwPtg1zx37u3YD_V2

### Reanimated version

3.15.5

### React Native version

0.75.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

Android API 35 x86_64

### Acknowledgements

Yes

**Comment by Priyanshu-Agrawal** [comment]
Any update on that? i am running into the same issue

**Comment by crackernandal0** [comment]
same issue with me but the solution is simple For example if you're using C:\HP User\Documents\Projects\Mobile\Project_name change it to something shorter like: C:\Projects\Mobile\Project_name.

Reasons for this is that NDK has a limited number of path characters. IN one of my projects this was the cause of the issue.

Hope this helps save someone day.

This should work as it worked for me.

**Comment by kikikiswanto** [comment]
> same issue with me but the solution is simple For example if you're using C:\HP User\Documents\Projects\Mobile\Project_name change it to something shorter like: C:\Projects\Mobile\Project_name.
> 
> Reasons for this is that NDK has a limited number of path characters. IN one of my projects this was the cause of the issue.
> 
> Hope this helps save someone day.
> 
> This should work as it worked for me.

Great, solved with move project path.
thanks, very hard for find simple solution.

**Comment by jinphic** [comment]
> same issue with me but the solution is simple For example if you're using C:\HP User\Documents\Projects\Mobile\Project_name change it to something shorter like: C:\Projects\Mobile\Project_name.
> 
> Reasons for this is that NDK has a limited number of path characters. IN one of my projects this was the cause of the issue.
> 
> Hope this helps save someone day.
> 
> This should work as it worked for me.

thx!
I solved this problem with 2 steps
1. delete arm-related in gradle.properties
reactNativeArchitectures=x86,x86_64
2. move the project to C:\username\my_app

**Comment by AlexisKenAlvarez** [comment]
> same issue with me but the solution is simple For example if you're using C:\HP User\Documents\Projects\Mobile\Project_name change it to something shorter like: C:\Projects\Mobile\Project_name.
> 
> Reasons for this is that NDK has a limited number of path characters. IN one of my projects this was the cause of the issue.
> 
> Hope this helps save someone day.
> 
> This should work as it worked for me.

This solved my issue, thank you!

**Comment by anirban-baisya** [comment]
> same issue with me but the solution is simple For example if you're using C:\HP User\Documents\Projects\Mobile\Project_name change it to something shorter like: C:\Projects\Mobile\Project_name.
> 
> Reasons for this is that NDK has a limited number of path characters. IN one of my projects this was the cause of the issue.
> 
> Hope this helps save someone day.
> 
> This should work as it worked for me.

You saved me, bro, Thank you !!   
I'm struggling with this issue for 3 days.

**Comment by tomekzaw** [comment]
Hi all, we added **"Building for Android on Windows"** troubleshooting guide to Reanimated docs. Please consult this page if you face any build errors for Android devices when building your app on Windows.

➡️ **https://docs.swmansion.com/react-native-reanimated/docs/guides/building-on-windows**

If the problem still persists, feel free to re-open the issue or submit a new one.
