### ISSUE TITLE
[3.16.0] 'worklets/WorkletRuntime/ReanimatedHermesRuntime.h' file not found

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#6607]
### Description

After upgrading from 3.15.5 I get this error on `ReanimatedHermesRuntime`:

`'worklets/WorkletRuntime/ReanimatedHermesRuntime.h' file not found`

Tried with no luck:

1. pod deintegrate
2. removed derived data
3. rm -rf node_modules
4. install everything back

### Steps to reproduce

1. upgrade from 3.15.5
5. cannot build
6. xcode 16

### Snack or a link to a repository

none

### Reanimated version

7.16.0

### React Native version

0.75.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
I believe this is the offending PR: 

* https://github.com/software-mansion/react-native-reanimated/pull/6543

I use static framework on Podfile: 

`use_frameworks! :linkage => :static`

**Comment by piaskowyk** [comment]
You are so fast man! 🤯

**Comment by tomekzaw** [comment]
Working on it ⌛

**Comment by tomekzaw** [comment]
@werlensantos Please wait for 3.16.1

**Comment by tomekzaw** [comment]
Here's a workaround: https://github.com/software-mansion/react-native-reanimated/pull/6614

It also requires changes from https://github.com/software-mansion/react-native-reanimated/pull/6612

Waiting for an internal review

**Comment by efstathiosntonas** [comment]
> @werlensantos Please wait for 3.16.1 early next week

it will be available on nightly, right? 

thanks @tomekzaw for the quick fixes!

**Comment by ethanneff** [comment]
should you remove the `3.16.0` version since it is broken?

**Comment by efstathiosntonas** [comment]
> should you remove the `3.16.0` version since it is broken?

I believe that the only projects that are affected are the ones using react-native-firebase so it’s not entirely broken.

**Comment by efstathiosntonas** [comment]
@tomekzaw sure thing, will report back tomorrow morning.

**Comment by efstathiosntonas** [comment]
@tomekzaw tested `3.17.0-nightly-20241018-16297eb3c` and life got back to normal.

**Comment by tomekzaw** [comment]
@efstathiosntonas Thanks for checking! We'll publish 3.16.1 with the fix early next week.

**Comment by Anaskhan143** [comment]
This latest version worked as expected:
yarn add react-native-reanimated@^3.16.1
