### ISSUE TITLE
debug not showing any messages

### ISSUE THREAD

**Issue by grean** [software-mansion/react-native-reanimated#661]
Hi,
I'm using your example's demo but when i tried to see the value of a node with the "debug" function, i couldn't see any message.
However, the demos that i've tried works fine.
In your, progressBar exemple there is a "debug" call if the "state is finished" so i waited the progressbar to finish but no messages were displayed.. nor in debug console in vscode when i was debbuging tha app in ios nor in packager console, nor in xcode console.
Is any body knows where those messages are ?
William what do your think ?

I've ommited to say that i don't use expo.. but i have the same problem in an other app that is created with "npx react-native init someProject"

**Comment by victorrseloy** [comment]
hi @grean, 

Could you please post the code to reproduce the problem here?

Thanks

**Comment by grean** [comment]
Hi @victorrseloy,

You can use the progressBar exemple of reanimated repository but i don't know if you can reproduce it. Maybe the exemple will work on your configuration.
https://github.com/software-mansion/react-native-reanimated/blob/383d2b5874d98416a30d3ca957ebae88c214cd86/Example/progressBar/ProgressBar.js#L72
Let me know if you see the debug message and where you see it :)

**Comment by grean** [comment]
After some tests, it seems that VSCode chrome debugger extension is not able to display reanimated debug messages in vscode debugger view.
I restarted my mac. (don´t know if it has a real inpact but it was a long time that i didn´t restart it so...)
I have opened my project and try to see massages on vscode chrome debugger but nothing appears.
Then, i closed packager, ios simulator et relaunch with Xcode and finally i saw the messages in the native console :)
After that, i tested to see messages in chrome navigator instead of vscode chrome extension and i also was able to see debug messages.
Tell me if someone can see debug messages in vscode chrome extension because it´s better for developping !

**Comment by jakub-gonet** [comment]
Hi @grean,

`debug` node output should show in native console or in your browser when you run with debug mode. Please link to VSC extension which you're using for debugging.

I'm closing it as it's related to environment configuration, but feel free to comment.

**Comment by grean** [comment]
Hi @jakub-gonet,

The extension that i'm using is : 
https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome
I think that lots of poeple is using it and it would be nice to have somebody who can test this case in an other environment, because maybe the issue is in my configuration.

**Comment by jakub-gonet** [comment]
I'll try to test it tomorrow, thanks for the link!

**Comment by emclab** [comment]
I am having the same problem on VScode 1.47 and nothing for debug output. I did a workaround and use `call` to console.log the value. It is not the solution but just a workaround.
