### ISSUE TITLE
Using SharedValue.set() fails with 'Tried to synchronously call a non-worklet anonymous function on the UI thread.' when mixing with `with*` helpers

### ISSUE THREAD

**Issue by chrisnojima** [software-mansion/react-native-reanimated#6613]
### Description

I'm switching my code from using the old style `opacity.value = withDelay...` to `opacity.set(withDelay...` but this fails.
Instead it only works if i use the callback form `opacity.set(() => withDelay...`. Unclear if this is by design but it was definitely confusing

### Steps to reproduce

1. Update to 3.16.0
2. use `.set` with a `withDelay` (style) helper
3. see a red box error

### Snack or a link to a repository

sorry

### Reanimated version

3.16.0

### React Native version

0.75.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by contactsimonwilson** [comment]
I'm getting the same thing

**Comment by g-siedlecki** [comment]
I'm also wondering if this is a bug. 
I created a minimal reproduction repo: https://github.com/g-siedlecki/ReanimatedRepro
Running React Native 0.75.4 and Reanimated 3.16.1. Tested on both iOS and Android.

**Comment by tjzel** [comment]
This shouldn't happen. I'll investigate.

**Comment by gaearon** [comment]
We're adding `set(() => ...)` everywhere to work around this, seems to repro very consistently. Not sure if there's a risk that something deeper is broken and migrating to `set()` is actually a bad idea?
