### ISSUE TITLE
> Task :react-native-reanimated:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by abhishekgupta2144** [software-mansion/react-native-reanimated#6641]
### Description

> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 7.5
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
WARNING:The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (30.0.3) for Android Gradle Plugin 7.4.2.
Android SDK Build Tools 30.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-reanimated:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
242 actionable tasks: 2 executed, 240 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

/Users/abhishekgupta/Desktop/memorizz/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:440: error: switch rules are not supported in -source 11
      case "opacity" -> {
                     ^
  (use -source 14 or higher to enable switch rules)
/Users/abhishekgupta/Desktop/memorizz/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java:356: error: pattern matching in instanceof is not supported in -source 11
      if (props.get(Snapshot.TRANSFORM_MATRIX) instanceof ReadableNativeArray matrixArray) {
                                                                              ^
  (use -source 16 or higher to enable pattern matching in instanceof)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

### Steps to reproduce

by running this command ./gradlew build. 

### Snack or a link to a repository

....

### Reanimated version

3.6.1

### React Native version

0.72.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Rushikesh21-12** [comment]
Update the package.json file:

Change "react-native-reanimated": "^X.X.X" to "react-native-reanimated": "X.X.X" (remove the ^ to lock the version). (Still facing issue then use this version 3.5.4)

Run the following commands to apply changes:

rm -rf node_modules
npm cache clean
npm install
npm start -- --reset-cache

**Comment by mohamed-grt** [comment]
I have the same issue. 

## Reanimated version
3.6.1

## React Native version
0.72.7

## Platforms
Android

**Comment by inayatAliDev** [comment]
facing same issue

**Comment by asyncwolf** [comment]
Had the same issue, this worked for me: 
```
"react-native": "^0.72.17", 
"react-native-reanimated": "3.5.4",

**Comment by tjzel** [comment]
Hi @abhishekgupta2144. Reanimated 3.6.x doesn't support React Native 0.72 and below. For more information please refer to our [Compatibility Table](https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility/).

**Comment by petertoth-dev** [comment]
@tjzel this is not a solution for me. I have compatible versions installed, it also works on iOS but throws the same error on android

**Comment by GenGraphic** [comment]
This worked for me too:

"react-native": "0.71.7",
"react-native-reanimated": "3.5.4",

**Comment by dani-kinetikos** [comment]
Same error with the following versions:

"react-native": "0.72.9",
"react-native-reanimated": "^3.8.0"

**Comment by Agile123992** [comment]
> Update the package.json file:
> 
> Change "react-native-reanimated": "^X.X.X" to "react-native-reanimated": "X.X.X" (remove the ^ to lock the version). (Still facing issue then use this version 3.5.4)
> 
> Make sure to remove ^ icon from version name.
> 
> Run the following commands to apply changes:
> 
> rm -rf node_modules npm cache clean npm install npm start -- --reset-cache



Yeah this one worked for me too
Thanks @Rushikesh21-12  bhai......!!

**Comment by Harsh-Tuwar** [comment]
> Update the package.json file:
> 
> Change "react-native-reanimated": "^X.X.X" to "react-native-reanimated": "X.X.X" (remove the ^ to lock the version). (Still facing issue then use this version 3.5.4)
> 
> Make sure to remove ^ icon from version name.
> 
> Run the following commands to apply changes:
> 
> rm -rf node_modules npm cache clean npm install npm start -- --reset-cache

This work for me too. Thanks @Rushikesh21-12

**Comment by gani419** [comment]
i have the same issue. can anyone suggest me the correct version for react-native-reanimated for react-native-0.76.9. 
thanks in advance

**Comment by miayam** [comment]
Downgrade openjdk version from 21 to 17. It works on Ubuntu 24.04 LTS.
Check https://github.com/software-mansion/react-native-reanimated/issues/5855
