### ISSUE TITLE
Type annotations are not supported in __workletClass

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#6642]
### Description

A class that has the __workletClass annotation doesn't support any kind of type annotations.
The following works:
```tsx
class Test {
  __workletClass = true;
  value;

  constructor(value) {
    this.value = value;
  }
}
```

But the following wouldn't:
```
class Test {
  __workletClass = true;
  value: number;

  constructor(value: number) {
    this.value = value;
  }
}
```
or
```
class Test<T> {
  __workletClass = true;
  value: T;

  constructor(value: T) {
    this.value = value;
  }
}
```

### Steps to reproduce

Add a type annotation to a class that has the __workletClass property. Adding a type annotations to https://github.com/software-mansion/react-native-reanimated/blob/main/apps/common-app/src/examples/RuntimeTests/tests/plugin/fileWorkletization.ts should be enough to reproduce the issue.

### Snack or a link to a repository

https://github.com/shopify/react-native-skia

### Reanimated version

3.5.1

### React Native version

0.75.2

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
cc @tjzel Can you please take a look?

**Comment by wcandillon** [comment]
@tjzel any additional advices on how to we could package pieces of JS code to be workletlize? (like a full file for example?)

**Comment by wcandillon** [comment]
Adding a type annotations to https://github.com/software-mansion/react-native-reanimated/blob/main/apps/common-app/src/examples/RuntimeTests/tests/plugin/fileWorkletization.ts should be enough to reproduce the issue.

**Comment by NiuGuohui** [comment]
@tjzel Another problem is that it does not support the use of implements and extends keywords on class declarations

**Comment by tjzel** [comment]
@NiuGuohui Unfortunately supporting `extends` won't be a thing in the near future.

**Comment by NiuGuohui** [comment]
> @NiuGuohui Unfortunately supporting `extends` won't be a thing in the near future.

Sorry to bother you, but may I ask why there are no plans to support the `extends` keyword? I believe it's a very important feature in OOP. 
Is it possible to implement a more limited version of it? For example, requiring the parent class to also have `__workletClass`.

**Comment by wcandillon** [comment]
@tjzel I am also interesting by this question, currently we are refactoring our code base to not use extends so that it can be workletized. Of course if there are plans to support this feature eventually, we may reconsider.

**Comment by tjzel** [comment]
Current implementation of Worklet Classes is very hacky already. Supporting `extends` means more issues about hoisting, file execution order and polyfill workletizing. I could ignore those like you said @NiuGuohui and make a very constrained version - but it still requires a lot of effort; it's difficult to cover all the edge cases and assure stability. We want to move away from building atop of the Babel Plugin and explore more seamless ways of loading your code into the UI Runtime.

**Comment by NiuGuohui** [comment]
> Current implementation of Worklet Classes is very hacky already. Supporting `extends` means more issues about hoisting, file execution order and polyfill workletizing. I could ignore those like you said @NiuGuohui and make a very constrained version - but it still requires a lot of effort; it's difficult to cover all the edge cases and assure stability. We want to move away from building atop of the Babel Plugin and explore more seamless ways of loading your code into the UI Runtime.

I see, it sounds like quite a big challenge!
