### ISSUE TITLE
[3.16.1] [0.76.1] Implicit instantiation of undefined template 'std::basic_stringstream<char>'

### ISSUE THREAD

**Issue by dawid-bytys** [software-mansion/react-native-reanimated#6673]
### Description

Hello,

I found a bug when building for iOS in Release mode (in Debug it works fine) on RN version 0.76.1 and reanimated version 3.16.1. The bug is related to the new architecture (and possibly XCode version 15.2?).

### Steps to reproduce

1. `npx @react-native-community/cli@latest init App`
2. `yarn add react-native-reanimated`
3. `cd ios && pod install`
4. add plugin to the `babel.config.js`
5. try to build the app in XCode in Release mode (edit existing scheme and set Run to Release)

<img width="599" alt="Screenshot 2024-11-07 at 1 24 20 AM" src="https://github.com/user-attachments/assets/f1daf6de-ab95-44b5-ae95-b3aa6dd7f54f">

### Snack or a link to a repository

https://github.com/dawid-bytys/reanimated-bug-reproduction

### Reanimated version

3.16.1

### React Native version

0.76.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Other (please specify)

### Device

iOS simulator

### Device model

iPhone 15 Pro (iOS 17.2)

### Acknowledgements

Yes

**Comment by adrianperomingo** [comment]
Same versions as @dawid-bytys even Xcode 15.2 (15C500b)

This is the file which throws the error:
` .../node_modules/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp`

<img width="607" alt="Captura de pantalla 2024-11-07 a las 17 31 34" src="https://github.com/user-attachments/assets/76268448-ff2c-4656-b0d6-82ecf76b55f6">


Redirects to line 303 when clicks on the error

<img width="640" alt="Captura de pantalla 2024-11-07 a las 17 32 11" src="https://github.com/user-attachments/assets/27b6829f-e20d-46a2-afb0-e6747a386db0">

Please help 😞

**Comment by vincicat** [comment]
fixed by adding new import on top (or any place in the header section that you are sure it will load) of this file
`node_modules/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp`:

```
#include <sstream>
```

I am curious why it was fine in version in 0.75 but broken in 0.76.1....

**Comment by adrianperomingo** [comment]
Can someone add it to a commit and make a release for the hotfix? It's a very simple fix...

**Comment by dawid-bytys** [comment]
> Can someone add it to a commit and make a release for the hotfix? It's a very simple fix...

You can use `patch-package` for now.

**Comment by adrianperomingo** [comment]
can `patch-package` works in an CI/CD using AppCenter? @dawid-bytys

**Comment by vincicat** [comment]
> Can someone add it to a commit and make a release for the hotfix? It's a very simple fix...

Short Answer: I am not an expert of C++ and this library. Not sure will that cause duplicate header import in other React Native/XCode combination then break their building process...better use `patch-package` or `yarn patch` for now

**Comment by dawid-bytys** [comment]
> can `patch-package` works in an CI/CD using AppCenter? @dawid-bytys

Yes, just add `"postinstall: patch-package"` script to `package.json`.

**Comment by adrianperomingo** [comment]
Yes, i have already did it and works in local. I wanted to know about in AppCenter.
It's fine guys, thanks for the help ❤️

**Comment by gabrieldonadel** [comment]
@tjzel, any updates on this?

**Comment by tjzel** [comment]
@gabrieldonadel Thanks for pinging me, I didn't know there was an issue open about this. The fix for this has been released in `react-native-reanimated@3.16.2`:
- https://github.com/software-mansion/react-native-reanimated/pull/6725
