### ISSUE TITLE
Listener in Animated.event

### ISSUE THREAD

**Issue by aeruhxi** [software-mansion/react-native-reanimated#67]
```js
          onScroll={event(
            [
              {
                nativeEvent: {
                  contentOffset: {
                    y: this.scrollY
                  }
                }
              }
            ],
            {
              listener: () => {
                console.log('scrolling');
              }
            }
          )}
```
As in original Animated library, how do I pass a listener like this?

**Comment by AbdallaMohamed** [comment]
Can't you use this node `call(argsNodes, callback)`? It's in the docs.

**Comment by abs-zero** [comment]
I considered using it but I couldn't find any example on how I am supoosed to use it. Also, it's not clear what `argsNodes` is. A simple example could help.

**Comment by abs-zero** [comment]
Thanks for the explanation.

**Comment by zachgibson** [comment]
FYI for anyone using expo and not seeing more than one log: #90

**Comment by Strate** [comment]
I would like to add another one example to use `call`, because it was unclear for me how to use `call` to solve requested issue: capture scroll position on JS side. For me there was an solution:

```
onScroll={Animated.event(
              [
                {
                  nativeEvent: {
                    contentOffset: {
                      y: y =>
                        Animated.block([
                          Animated.set(this.scrollY, y),
                          Animated.call(
                            [y],
                            ([offsetY]) => (this.listOffsetY = offsetY)
                          )
                        ])
                    }
                  }
                }
              ],
              {
                useNativeDriver: true
              }
            )}
```

**Comment by Dihan101** [comment]
> I would like to add another one example to use `call`, because it was unclear for me how to use `call` to solve requested issue: capture scroll position on JS side. For me there was an solution:
> 
> ```
> onScroll={Animated.event(
>               [
>                 {
>                   nativeEvent: {
>                     contentOffset: {
>                       y: y =>
>                         Animated.block([
>                           Animated.set(this.scrollY, y),
>                           Animated.call(
>                             [y],
>                             ([offsetY]) => (this.listOffsetY = offsetY)
>                           )
>                         ])
>                     }
>                   }
>                 }
>               ],
>               {
>                 useNativeDriver: true
>               }
>             )}
> ```

Thank you for this solution bro. I came to this kind of logic where I need to animate my botttom tabBar component and also animating my header interpolated. Thanks for this, great job!

**Comment by jakub-gonet** [comment]
@geroale,
you always can create an Animated Value outside of event node, do `set(yourNode, y)` at start of the block and leave rest as it is

**Comment by Daavidaviid** [comment]
How would one do this and use FlatList with Reanimated 2 ? @jakub-gonet
