### ISSUE TITLE
Build fails on x86 when using New Architecture

### ISSUE THREAD

**Issue by laurensk** [software-mansion/react-native-reanimated#6709]
### Description

As the title says, the build fails on x86 after updating to Expo SDK 52 (RN 0.76.2) and enabling the New Architecture.

Here is the error from xcbuild:

```
The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/Redacted-ehjoqgcfwsuojfgztgkqgyjzbbtp/Build/Intermediates.noindex/ArchiveIntermediates/Redacted/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RNReanimated.build/Objects-normal/arm64/NativeReanimatedModule.o /Users/runner/actions-runner/_work/Redacted-app/Redacted-app/node_modules/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods')
(1 failure)
[16:30:39]: Exit status: 65
```

### Steps to reproduce

Create Expo project with SDK 52 and RN >=0.76 and enable the New Architecture

### Snack or a link to a repository

N/A

### Reanimated version

3.16.1

### React Native version

0.76.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo Dev Client

### Architecture

Fabric (New Architecture)

### Build type

Release app & production bundle

### Device

None

### Acknowledgements

Yes

**Comment by fonsecaBarreto** [comment]
Up

**Comment by fonsecaBarreto** [comment]
Upgrade your Xcode to version 16; this may resolve the issue

**Comment by laurensk** [comment]
Alright, this fixed it!
