### ISSUE TITLE
Flip card animation example is broken in iOS with Expo 52

### ISSUE THREAD

**Issue by david-bermejo** [software-mansion/react-native-reanimated#6722]
### Description

As the title says, flip card animation example present in your [page](https://docs.swmansion.com/react-native-reanimated/examples/flipCard/) is broken in iOS with Expo 52. I am using it in one of my projects and the same happens.

The provided Snack project is the one present in your page as an example. When flipped, the back card face is visible on top during the animation, and that should not happen. This bug was not present in Expo 51 or previous versions. Other platforms are not affected.

### Steps to reproduce

1. Open snack project
2. Make sure platform option is iOS and Expo version is 52.0.0
3. Click on Launch Snack

### Snack or a link to a repository

https://snack.expo.dev/@bermejus/flip-card-%7C-react-native-reanimated?platform=ios

### Reanimated version

3.16.1

### React Native version

0.76.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by patrycjakalinska** [comment]
Hi! It looks like on newer releases `backfaceVisibility` works slightly different. Setting `backfaceVisibility: 'hidden'` on both cards should fix this issue:

```
      // ...
      
      <FlipCard
        isFlipped={isFlipped}
        cardStyle={styles.flipCard}
        FlippedContent={<FlippedContent />}
        RegularContent={<RegularContent />}
      />
      
      // ...
      
      const styles = StyleSheet.create({
         flipCard: {
          width: 170,
          height: 200,
          backfaceVisibility: 'hidden'
  },
});
```

**Comment by david-bermejo** [comment]
> Hi @david-bermejo ! It looks like on newer releases `backfaceVisibility` works slightly different. Setting `backfaceVisibility: 'hidden'` on both cards should fix this issue:
> 
> 
> 
> ```
> 
>       // ...
> 
>       
> 
>       <FlipCard
> 
>         isFlipped={isFlipped}
> 
>         cardStyle={styles.flipCard}
> 
>         FlippedContent={<FlippedContent />}
> 
>         RegularContent={<RegularContent />}
> 
>       />
> 
>       
> 
>       // ...
> 
>       
> 
>       const styles = StyleSheet.create({
> 
>          flipCard: {
> 
>           width: 170,
> 
>           height: 200,
> 
>           backfaceVisibility: 'hidden'
> 
>   },
> 
> });
> 
> ```

Wow it really solved my problem, thank you for your time!

**Comment by eeebuba** [comment]
> Hi @david-bermejo ! It looks like on newer releases `backfaceVisibility` works slightly different. Setting `backfaceVisibility: 'hidden'` on both cards should fix this issue:

I was having the same problem, and this worked for me too, thanks!

**Comment by jingege** [comment]
Yes, it works for me too. Hope the example page also be fixed.
