### ISSUE TITLE
Running clock breaks PanGesture

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#674]
I'm using **PanGesture** to drag screen on **Android**. Until I add clock everything is working as expected and `Animated.View` is translated accordingly.

But when I just run clock on `State.END` event without any clock-based calculations, screen is starting twitching.

```ts
debug('[end] snap point is', snapPoint),
cond(
  not(clockRunning(clock)),
    [debug('clock is not running', clock), startClock(clock)],
    debug('clock running', clock)
)
```

https://gist.github.com/likern/7d37661b6cb2bec873c8b37e485c7271

**Comment by likern** [comment]
Also, **stopped** clock is self-updated. If I using only condition to stop clock and never run it, I still see clock value updates.

```ts
cond(eq(gestureState, State.BEGAN), [
  cond(
    clockRunning(clock),
    [debug('clock is not running', clock), stopClock(clock)],
    debug('clock running', clock)
  )
]),
```

![Снимок экрана от 2020-03-22 18-37-43](https://user-images.githubusercontent.com/842306/77253584-4221ca80-6c6c-11ea-8a28-4cb931448e3e.png)

**Comment by headfire94** [comment]
@likern I tried to run clock like you do in this example, and it works fine - https://snack.expo.io/@egorvodopyanov/05531b

**Comment by likern** [comment]
Close as no more using Reanimated V1.
