### ISSUE TITLE
Build faild with error in React native  0.76.3 

### ISSUE THREAD

**Issue by somnathnath8482** [software-mansion/react-native-reanimated#6753]
### Description

Getting the below error while building with react native reanimated. 

 ninja: build stopped: .

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\somnath\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\somnath\\REACT_PROJECT\\Myapp\\node_modules\\react-native-reanimated\\android\\.cxx\\Debug\\2c6q4iw2\\arm64-v8a" ^
        reanimated ^
        worklets
    from D:\somnath\REACT_PROJECT\Myapp\node_modules\react-native-reanimated\android
  ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/D_/somnath/REACT_PROJECT/Myapp/node_modules/react-native-reanimated): No such file or directory
  
  
  But without react native reanimated it works fine.  i have also tried with nightly version not worked

### Steps to reproduce

1. npx @react-native-community/cli@latest init myApp
2. npm install react-native-reanimated
3. set buble plugin   

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
  ],
};

5. npx react-native run-android

### Snack or a link to a repository

not availabe 

### Reanimated version

3.6.2

### React Native version

0.76.3 

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

realme c12 android 14

### Acknowledgements

Yes

**Comment by luan-nvg** [comment]
with similar problem

**Comment by andrejpavlovic** [comment]
Had the same issue trying to build locally with expo. Installing and setting CMake to latest version before building helped.

```powershell
$Env:CMAKE_VERSION = '3.31.0'
yarn android --variant release
```

**Comment by jonhy751** [comment]
> yarn react-native build-android --mode Release

Iam using expo, no working for me

**Comment by somnathnath8482** [comment]
in my case upgrading Cmake dosent helped me . I have solved the issue by moving my project to a shorter path .

from "D:\somnath\REACT_PROJECT\Myapp\" to "D:\Myapp\" 

and it solved my issue
