### ISSUE TITLE
[Android] Random crash with Could not enqueue microtask because they are disabled in this runtime, js engine: hermes

### ISSUE THREAD

**Issue by smfunder** [software-mansion/react-native-reanimated#6764]
### Description

I upgraded to RN 0.76.1 (and now to 0.76.3) and I'm facing random crashes of the Android app when running in release mode (APK file installed on a Samsung S20 FE), this is when I build the app with ./gradlew assembleStagingRelease

In particular it is happening the very first time I open the application after a fresh install and it is always replicable when receiving a push notification with the app in quit state using firebase headless task from messaging().setBackgroundMessageHandler.

The full stack trace says:

```
 E  Error: Exception in HostFunction: Could not enqueue microtask because they are disabled in this runtime, js engine: hermes
FATAL EXCEPTION: mqt_native_modules
Process: com.wavelengthlabs.airwave.staging, PID: 24803
com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: Could not enqueue microtask because they are disabled in this runtime, js engine: hermes, stack:
setImmediate@1:354687
setDriver@1:1343696
LocalForage@1:1342266
anonymous@1:1323807
s@1:1318618
e@1:1318361
anonymous@1:1318263
anonymous@1:1318111
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:1315887
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:1312232
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:1135293
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:1119732
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:1118839
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:1000229
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:849367
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:769700
loadModuleImplementation@1:141478
guardedLoadModule@1:141001
metroRequire@1:140631
anonymous@1:147390
loadModuleImplementation@1:141478
guardedLoadModule@1:140958
metroRequire@1:140631
global@1:140159

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.kt:52)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
```

When I try to find where this error comes from it is pointing only to RN Reanimated particularly in the libhermes.so file. No other reference to this error in my whole codebase.

Binary file ./react-native-reanimated/android/build/intermediates/cmake/release/obj/armeabi-v7a/libhermes.so matches
Binary file ./react-native-reanimated/android/build/intermediates/cmake/release/obj/x86/libhermes.so matches
Binary file ./react-native-reanimated/android/build/intermediates/cmake/release/obj/arm64-v8a/libhermes.so matches
Binary file ./react-native-reanimated/android/build/intermediates/cmake/release/obj/x86_64/libhermes.so matches
Binary file ./react-native-reanimated/android/build/intermediates/cxx/RelWithDebInfo/2adb1f44/obj/armeabi-v7a/libhermes.so matches
Binary file ./react-native-reanimated/android/build/intermediates/cxx/RelWithDebInfo/2adb1f44/obj/x86/libhermes.so matches
Binary file ./react-native-reanimated/android/build/intermediates/cxx/RelWithDebInfo/2adb1f44/obj/arm64-v8a/libhermes.so matches
Binary file ./react-native-reanimated/android/build/intermediates/cxx/RelWithDebInfo/2adb1f44/obj/x86_64/libhermes.so matches

I've tried with version 3.16.1, 3.16.3 and 3.17.0-rc.0 of RN Reanimated and in all the cases I'm facing the same issue.

Any help?

### Steps to reproduce

1. Build the Android app using ./gradlew assembleStagingRelease (clean up before building)
2. Install the APK in an Android device
3. Run the app for the first time
4. Observe the crash right away the app is open
5. Or send a push notification for the headless task and observe the crash using logCat in Android Studio putting the app in quit state (force close) first.

Observe this is not happening when in debug mode running rpm run android.

### Snack or a link to a repository

http://github.com/smfunder/

### Reanimated version

3.16.1, 3.16.3 and 3.17.0-rc.0

### React Native version

0.76.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

Samsung Galaxy S20 FE (but in general Android)

### Acknowledgements

Yes

**Comment by smfunder** [comment]
Closing this issue as the guilty library actually was react-native-push-notification in Android with RN 0.76.3 + New Arch + Bridgeless. It was not related to react-native-reanimated at all.

**Comment by kasterlod** [comment]
@smfunder can you share more details what was the real reason?

**Comment by smfunder** [comment]
@kasterlod yes, basically I had react-native-push-notification library running as as headless task on the main entry file. But that was causing the microtask issue. I finally switched to notifee to do the operation I needed (reset the badge number to zero). Not sure if this would be a similar case for you.

**Comment by smfunder** [comment]
@GSSPawanKumarSingh can you show your entry file (usually index.js) and provide some more context?

**Comment by GSSPawanKumarSingh** [comment]
> @GSSPawanKumarSingh can you show your entry file (usually index.js) and provide some more context?
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import {Provider} from 'react-redux';
import store from './src/Store/Store';
import './src/Util/i18n';
import 'react-native-gesture-handler';
import messaging from '@react-native-firebase/messaging';

import {Suspense} from 'react';
import LoadingComp from './src/UI/LoadingComp';
const AppStore = () => (
  // Added Suspense due to some error we are getting
  <Suspense fallback={<LoadingComp />}>
    <Provider store={store}>
      <App />
    </Provider>
  </Suspense>
);
messaging().setBackgroundMessageHandler(async message => {

  console.log('Messaeage', message);
});
AppRegistry.registerComponent(appName, () => AppStore);

**Comment by smfunder** [comment]
@GSSPawanKumarSingh is there a way you can slowly remove some imports and some code and run your app to check if this clears the error you get? That's what I did, I slowly removed every feature / code on startup until I detected the issue was with clearing the badge count on the app. I think you should do something similar until detect the guilty library.

**Comment by GSSPawanKumarSingh** [comment]
Okay sounds a lengthy approach however, let's give a try with this. I'll update whatever the outcome i found.

**Comment by GSSPawanKumarSingh** [comment]
Found the issue with react-native-push-notification. I guess we need to move from this package to notifee. Any other best open alternative?

**Comment by smfunder** [comment]
> Found the issue with react-native-push-notification. I guess we need to move from this package to notifee. Any other best open alternative?

@GSSPawanKumarSingh in my case I moved to notifee but I only needed the reset of badge count if I'm not wrong. I know that notifee has support these days, so I highly recommend to move to notifee for future maintenance.
