### ISSUE TITLE
Task :react-native-reanimated:configureCMakeDebug[arm64-v8a] FAILED

### ISSUE THREAD

**Issue by AnirudhMemani** [software-mansion/react-native-reanimated#6771]
### Description

I have tried everything but the error doesn't go away at all. Once I remove this library it builds properly. Things I have tried:

1. cd android && ./gradlew clean && ./gradlew :app:assembleDebug --refresh-dependencies
2. rm -rf node_modules && npm cache clean --force && npm install
3. echo "cmake.dir=\$ANDROID_HOME/cmake/3.22.1" >> local.properties
4. Turned off new architecture as well

And a lot of other things as well!!

### Steps to reproduce

1. npx @react-native-community/cli@latest init <appName>
2. npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
3. Do all the steps recommended by nativewind and react-native-reanimated in metro.config.js and babel.config.js
4. Trying running the project using npx react-native run-android

### Snack or a link to a repository

x

### Reanimated version

3.16.3

### React Native version

0.76.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Dezital** [comment]
@AnirudhMemani  Can you please tell were you able to fid you find any solution?

**Comment by rohits-tatamotors** [comment]
Same issue, please tell if you find any solution.

**Comment by bondarenkod** [comment]
Got the same issue, reverted back to previous version. Tried to update cmake to the latest version - nothing.

**Comment by AnirudhMemani** [comment]
> @AnirudhMemani Can you please tell were you able to fid you find any solution?

Nope. I tried everything and gave up. Hopefully someone here can help!

**Comment by Dezital** [comment]
@bondarenkod which version you reverted back to can please tell.

**Comment by bondarenkod** [comment]
> @bondarenkod which version you reverted back to can please tell.

3.14.0

**Comment by AnirudhMemani** [comment]
Any solutions? I have tried both downgrading and upgrading the gradle version from 8.10.2 to 8.11.1 and 8.9 respectively but no luck. I have also tried different cmake version but that too didn't work.

**Comment by kareem-g** [comment]
> Any solutions? I have tried both downgrading and upgrading the gradle version from 8.10.2 to 8.11.1 and 8.9 respectively but no luck. I have also tried different cmake version but that too didn't work.

Same Problem, Tried to upgrade and downgrade react-native-reanimated to the nightly version and older versions and same problem. :)

**Comment by burakaydinofficial** [comment]
I think I found the problem.
It fails to build on Windows if the directory path is long

```
cd D:\Test\
mkdir react-native-reanimated-test
cd react-native-reanimated-test
npx @react-native-community/cli@latest init rnat
cd rnat
npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
npm run android
```
Result: success

```
cd D:\Test\
mkdir react-native-reanimated-test
cd react-native-reanimated-test
mkdir very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890
cd very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890
npx @react-native-community/cli@latest init rnat
cd rnat
npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
npm run android
```
Result: fail

I grabbed several warnings in the logs like this:

C/C++: CMake Warning in src/main/cpp/worklets/CMakeLists.txt:
C/C++:   The object file directory
C/C++:     D:/Temp/react-native-animated-test/very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890/rnat/node_modules/react-native-reanimated/android/.cxx/Debug/3yj4b4c1/arm64-v8a/src/main/cpp/worklets/CMakeFiles/worklets.dir/./
C/C++:   has 243 characters.  The maximum full path to an object file is 250
C/C++:   characters (see CMAKE_OBJECT_PATH_MAX).  Object file
C/C++:     D_/Temp/react-native-animated-test/very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890/rnat/node_modules/react-native-reanimated/Common/cpp/worklets/Registries/EventHandlerRegistry.cpp.o
C/C++:   cannot be safely placed under this directory.  The build may not work
C/C++:   correctly.

I made a third test

```
cd D:\Test\
mkdir react-native-reanimated-test
cd react-native-reanimated-test
mkdir short_path
cd short_path
npx @react-native-community/cli@latest init rnat
cd rnat
npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
npm run android
```
Result: fail

I grabbed that path warning again but this time only a single one.

C/C++: CMake Warning in src/main/cpp/reanimated/CMakeLists.txt:
C/C++:   The object file directory
C/C++:     D:/Temp/react-native-animated-test/short_path/rnat/node_modules/react-native-reanimated/android/.cxx/Debug/5d683e10/armeabi-v7a/src/main/cpp/reanimated/CMakeFiles/reanimated.dir/./
C/C++:   has 180 characters.  The maximum full path to an object file is 250
C/C++:   characters (see CMAKE_OBJECT_PATH_MAX).  Object file
C/C++:     D_/Temp/react-native-animated-test/short_path/rnat/node_modules/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/ReanimatedWorkletRuntimeDecorator.cpp.o
C/C++:   cannot be safely placed under this directory.  The build may not work
C/C++:   correctly.

Then I made my last test
```
cd D:\Test\
mkdir react-native-reanimated-test
cd react-native-reanimated-test
mkdir sp
cd sp
npx @react-native-community/cli@latest init rnat
cd rnat
npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
npm run android
```
Result: success

**Comment by AnirudhMemani** [comment]
> I think I found the problem. It fails to build on Windows if the directory path is long
> 
> ```
> cd D:\Test\
> mkdir react-native-reanimated-test
> cd react-native-reanimated-test
> npx @react-native-community/cli@latest init rnat
> cd rnat
> npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
> npm run android
> ```
> 
> Result: success
> 
> ```
> cd D:\Test\
> mkdir react-native-reanimated-test
> cd react-native-reanimated-test
> mkdir very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890
> cd very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890
> npx @react-native-community/cli@latest init rnat
> cd rnat
> npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
> npm run android
> ```
> 
> Result: fail
> 
> I grabbed several warnings in the logs like this:
> 
> C/C++: CMake Warning in src/main/cpp/worklets/CMakeLists.txt: C/C++: The object file directory C/C++: D:/Temp/react-native-animated-test/very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890/rnat/node_modules/react-native-reanimated/android/.cxx/Debug/3yj4b4c1/arm64-v8a/src/main/cpp/worklets/CMakeFiles/worklets.dir/./ C/C++: has 243 characters. The maximum full path to an object file is 250 C/C++: characters (see CMAKE_OBJECT_PATH_MAX). Object file C/C++: D_/Temp/react-native-animated-test/very_long_directory_path_1234567890_1234567890_1234567890_1234567890_1234567890/rnat/node_modules/react-native-reanimated/Common/cpp/worklets/Registries/EventHandlerRegistry.cpp.o C/C++: cannot be safely placed under this directory. The build may not work C/C++: correctly.
> 
> I made a third test
> 
> ```
> cd D:\Test\
> mkdir react-native-reanimated-test
> cd react-native-reanimated-test
> mkdir short_path
> cd short_path
> npx @react-native-community/cli@latest init rnat
> cd rnat
> npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
> npm run android
> ```
> 
> Result: fail
> 
> I grabbed that path warning again but this time only a single one.
> 
> C/C++: CMake Warning in src/main/cpp/reanimated/CMakeLists.txt: C/C++: The object file directory C/C++: D:/Temp/react-native-animated-test/short_path/rnat/node_modules/react-native-reanimated/android/.cxx/Debug/5d683e10/armeabi-v7a/src/main/cpp/reanimated/CMakeFiles/reanimated.dir/./ C/C++: has 180 characters. The maximum full path to an object file is 250 C/C++: characters (see CMAKE_OBJECT_PATH_MAX). Object file C/C++: D_/Temp/react-native-animated-test/short_path/rnat/node_modules/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/ReanimatedWorkletRuntimeDecorator.cpp.o C/C++: cannot be safely placed under this directory. The build may not work C/C++: correctly.
> 
> Then I made my last test
> 
> ```
> cd D:\Test\
> mkdir react-native-reanimated-test
> cd react-native-reanimated-test
> mkdir sp
> cd sp
> npx @react-native-community/cli@latest init rnat
> cd rnat
> npm install nativewind tailwindcss react-native-reanimated react-native-safe-area-context
> npm run android
> ```
> 
> Result: success

Already tried this. Didn't work for me!

**Comment by bondarenkod** [comment]
> has 243 characters. The maximum full path to an object file is 250
> has 180 characters. The maximum full path to an object file is 250
>It fails to build on Windows if the directory path is long
What?

**Comment by bondarenkod** [comment]
@AnirudhMemani could you try to run this and then reboot?:
`New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`

But it could be that I have a different issue, because the command which you provided `./gradlew clean && ./gradlew :app:assembleDebug --refresh-dependencies` gives me an OK result when I run it locally and, on my windows server, based build agent OS.

**Comment by bondarenkod** [comment]
1. Check for the libraries versions:
`"react-native-reanimated": "3.16.3"`
` "realm": "^12.14.0", // I have it, it requires some kind old ndk version, so I decided to bump its version`
 
 2. Install cmake 3.31.0 via Android Studio. And only this version. I've removed all the rest of cmake versions.  
 3. Remove all the ndk except the last version one, install the latest version.  
 4. Enable long path on windows, reboot: ``` New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force ```
 5. execute in the project from the root path: `git clean -xfd && git submodule foreach --recursive git clean -xfd`
 6. in the same terminal window execute:
 6.1 `$Env:CMAKE_VERSION = '3.31.0'`
 6.2 `yarn react-native build-android --mode Release`
 
 
<img width="577" alt="image" src="https://github.com/user-attachments/assets/3f8385d8-ea39-4a5b-8edc-0850ba866ce2">


It seems like helped me.

**Comment by gmonb** [comment]
Did it fail because of Ninja missing? If so...

I'm using EAS and running the commands in a docker container. I had a similar error and this worked for me:

`
RUN apt-get update && apt-get install -y ninja-build
`

Hopefully this can be of any help.

**Comment by akshay-khapare** [comment]
move your project to windows C:\ directory it will be solved 😊

**Comment by Rose-wu** [comment]
![image](https://github.com/user-attachments/assets/6b7d8e62-c23e-46f9-a83a-9ebbf80ce2a4)  
我也遇到了相似的问题  .cxx/Debug/d2t2vr19下 没未生成 armeabi-v7a相关文件 已经清除缓存后  依旧不能成功运行  困扰我了许久

**Comment by tjzel** [comment]
Duplicate of https://github.com/software-mansion/react-native-reanimated/issues/6718

**Comment by Whiskas101** [comment]
The issue seems to persist, I am unable to build a release version even with the default expo app, no added dependencies whatsoever.

**Comment by ThukuWakogi** [comment]
> 6\. 6.1 `$Env:CMAKE_VERSION = '3.31.0'`

To avoid typing this command on every build, I added it to .env. I am using expo

**Comment by Whiskas101** [comment]
The fix that worked for me was manually finding the ninja executable within the binaries of cmake, and replacing it with the latest version,ninja >1.10 has fixed a bug with max path limitations.

**Comment by Magic-Front** [comment]
I have the same issue.

**Comment by rustemsarica** [comment]
local.properties => cmake.dir=C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\cmake\\3.31.1

**Comment by blinqwebstudio** [comment]
Had the exact same issue. Updating Cmake to 3.31.0 (from 3.22.1) and doing `$Env:CMAKE_VERSION = '3.31.0'` in the terminal before building the release version again fixed it for me.

**Comment by mustafahuseynov** [comment]
> 1. Check for the libraries versions:
>    `"react-native-reanimated": "3.16.3"`
>    ` "realm": "^12.14.0", // I have it, it requires some kind old ndk version, so I decided to bump its version`
> 2. Install cmake 3.31.0 via Android Studio. And only this version. I've removed all the rest of cmake versions.
> 3. Remove all the ndk except the last version one, install the latest version.  // again, it could be related to the realm which I have in use
> 4. Enable long path on windows, reboot: `New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`
> 5. execute in the project from the root path: `git clean -xfd && git submodule foreach --recursive git clean -xfd`
> 6. in the same terminal window execute:
>    6.1 `$Env:CMAKE_VERSION = '3.31.0'`
>    6.2 `yarn react-native build-android --mode Release`
> 
> <img alt="image" width="577" src="https://private-user-images.githubusercontent.com/3184414/391966828-3f8385d8-ea39-4a5b-8edc-0850ba866ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM4NjA3NjgsIm5iZiI6MTc0Mzg2MDQ2OCwicGF0aCI6Ii8zMTg0NDE0LzM5MTk2NjgyOC0zZjgzODVkOC1lYTM5LTRhNWItOGVkYy0wODUwYmE4NjZjZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MDVUMTM0MTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWI2NmQ4MDI4ZDhkOTBhN2M2YjhmMjk4MGQ2ZWI5MDhjMWIwZTY5ZjA2MDBmMjc4MDViMGUyNTU4MGFjMmJmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NuSuE-t5jyErlPSC-jr6izLL_fEBJmdSduRmTP9TqLE">
> It seems like helped me.

Installing CMake 3.31.0 helped me to fix the issue. Thank you!

**Comment by nazhhoglu** [comment]
> 1. Kütüphane sürümlerini kontrol edin:
>    `"react-native-reanimated": "3.16.3"`
>    ` "realm": "^12.14.0", // I have it, it requires some kind old ndk version, so I decided to bump its version`
> 2. Android Studio üzerinden cmake 3.31.0'ı yükleyin. Ve sadece bu sürümü. Diğer tüm cmake sürümlerini kaldırdım.
> 3. Son sürüm hariç tüm ndk'ları kaldırın, en son sürümü kurun. // tekrar ediyorum, kullandığım realm ile ilgili olabilir
> 4. Windows'ta uzun yolu etkinleştirin, yeniden başlatın:`New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`
> 5. projede kök yolundan çalıştırın:`git clean -xfd && git submodule foreach --recursive git clean -xfd`
> 6. aynı terminal penceresinde şunu çalıştırın: 
>    6.1 `$Env:CMAKE_VERSION = '3.31.0'`
>    6.2`yarn react-native build-android --mode Release`
> 
> <img alt="görüntü" width="577" src="https://private-user-images.githubusercontent.com/3184414/391966828-3f8385d8-ea39-4a5b-8edc-0850ba866ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUxMDMwNzcsIm5iZiI6MTc0NTEwMjc3NywicGF0aCI6Ii8zMTg0NDE0LzM5MTk2NjgyOC0zZjgzODVkOC1lYTM5LTRhNWItOGVkYy0wODUwYmE4NjZjZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTlUMjI0NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzkxNTliOWVlNjNlOTQ5MmNmYzFlZGI2ZDU1MmRhNDYyM2NkNDllZjNmMmRkNjgxNGQwMTgwZjE5YmMyYjRkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6EKx3on8z4oY20DEt3GblPcuanMJTWhSAdOlgfSTNcs">
> Bana yardımcı oldu sanırım.

**Comment by nazhhoglu** [comment]
> 1. Kütüphane sürümlerini kontrol edin:
>    `"react-native-reanimated": "3.16.3"`
>    ` "realm": "^12.14.0", // I have it, it requires some kind old ndk version, so I decided to bump its version`
> 2. Android Studio üzerinden cmake 3.31.0'ı yükleyin. Ve sadece bu sürümü. Diğer tüm cmake sürümlerini kaldırdım.
> 3. Son sürüm hariç tüm ndk'ları kaldırın, en son sürümü kurun. // tekrar ediyorum, kullandığım realm ile ilgili olabilir
> 4. Windows'ta uzun yolu etkinleştirin, yeniden başlatın:`New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`
> 5. projede kök yolundan çalıştırın:`git clean -xfd && git submodule foreach --recursive git clean -xfd`
> 6. aynı terminal penceresinde şunu çalıştırın: 
>    6.1 `$Env:CMAKE_VERSION = '3.31.0'`
>    6.2`yarn react-native build-android --mode Release`
> 
> <img alt="görüntü" width="577" src="https://private-user-images.githubusercontent.com/3184414/391966828-3f8385d8-ea39-4a5b-8edc-0850ba866ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUxMDMzNjUsIm5iZiI6MTc0NTEwMzA2NSwicGF0aCI6Ii8zMTg0NDE0LzM5MTk2NjgyOC0zZjgzODVkOC1lYTM5LTRhNWItOGVkYy0wODUwYmE4NjZjZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTlUMjI1MTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTVmZmJkZjFmYjA4ZjkxNDI5NmVlMmIzZmVhYWQwMDYyMmUxNDZlNjUxM2Y4NDNjY2Q3NzFjYmExOTRmZGJmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1aPBTbgNFWrfWDlCkl_7-n3j2_6CYNH8sZlxMisqc_w">
> Bana yardımcı oldu sanırım.

Thank you very much. I am very grateful to you. I was struggling with this error for about 2 months. Thanks to you, it was finally resolved.

**Comment by sandeepeven** [comment]
Using M3 and facing this same issue. Installing rosetta worked for me.

`softwareupdate --install-rosetta`

**Comment by mlorencs** [comment]
I had similar errors with :react-native-worklets:configureCMakeDebug[arm64-v8a] and :react-native-screens:configureCMakeDebug[arm64-v8a]

```
Execution failed for task ':react-native-worklets:configureCMakeDebug[arm64-v8a]'.
> WARNING: A restricted method in java.lang.System has been called
```

Turns out I was using higher OpenJDK version than recommended. Changed OpenJDK version to 17 and was able to finally run `npx expo run:android` successfully.

Just putting it out there in case someone runs into similar issues because this GitHub issue was the first one that got thrown out when I searched the error.

**Comment by gamerplant3** [comment]
Adding the environment variable fixed this error for me too.

Check version with 

`cmake --version`

then set the environment variable to whatever you get out of that

`$Env:CMAKE_VERSION = '3.31.1'`

**Comment by ShahFahad-530** [comment]
The error was related to CMake and the Android toolchain:

```
Could not find toolchain file:
.../ndk/27.1.12297006/build/cmake/android.toolchain.cmake

CMAKE_C_COMPILER not set
CMAKE_CXX_COMPILER not set

```
This happened even after clearing Gradle caches and reinstalling node modules.

Root Cause

The NDK version referenced in android/build.gradle was partially corrupted (likely due to SDK update or disk space issue).
Gradle kept resolving to that broken NDK and native modules (worklets/reanimated/etc.) could not compile.

Fix

Remove the problematic NDK version from the SDK directory

`~/Library/Android/sdk/ndk/27.1.12297006
`
Open Android Studio → SDK Manager → SDK Tools

Enable Show Package Details

Reinstall the same NDK version again

Update SDK tools if updates are available:

Android SDK Platform-Tools

Build-Tools

CMake (recommended compatible version)

Clean and rebuild project

```
cd android
./gradlew clean
cd ..
npx react-native run-android
```

Result

After reinstalling the NDK and updating SDK tools, the build succeeded and all native modules compiled normally.

**Comment by ekiwandanaputra** [comment]
Downgrade version  to "react-native-reanimated": "^4.2.1",

**Comment by K-E-L** [comment]
I am using macos and I installed openjdk through brew. I noticed that brew installed openjdk 25 by default. What I did was drop it down to openjdk@21 and that worked for me. I didn't need to go down to 17 as of April 2026.
