### ISSUE TITLE
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'. > [CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders.

### ISSUE THREAD

**Issue by mkchoudhary1** [software-mansion/react-native-reanimated#6778]
### Description

i have got an error while running  the react native app

Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders.

i have used like following version of packages:
 react native : "0.76.3"
 node: v22.11.0
@react-native-community/cli:  15.0.1

using : vanillacream sdk(15)

i am also new in learning React Native app development

### Steps to reproduce

building the project using :   npx react-native run-android

then  emulator opened  successfully 
info Installing the app...
> Task :app:configureCMakeDebug[arm64-v8a] FAILED
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exce
ption. * What went wrong: Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'. > [CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders. 

### Snack or a link to a repository

no repo

### Reanimated version

3.16.3

### React Native version

0.76.3

### Platforms

Android

### JavaScript runtime

v8

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

pixel 9

### Acknowledgements

Yes

**Comment by Rose-wu** [comment]
Has it been solved? I have similar problems, same environment configuration

**Comment by gmonb** [comment]
I'm using EAS and running the commands in a docker container. I had a similar error and this worked for me:

`
RUN apt-get update && apt-get install -y ninja-build
`

You should try installing ninja

**Comment by mkchoudhary1** [comment]
I get resolved it by following the below steps:
1. reinstalling the CMake Sdk tool (also make sure it's path .exe file added into the environment variables)
2. dowload ninja and added it to environment  variable path 
3. cd android and then ./gradlew clean  in terminal  
4. delete the build folder if any inside the android folder 
5. then reopen the project into IDE and then run the command npm react-native run-android

**Comment by akshay-khapare** [comment]
move your project to  windows C:\  directory it will be solved 😊
