### ISSUE TITLE
Crash on native release Android in a nightly

### ISSUE THREAD

**Issue by gaearon** [software-mansion/react-native-reanimated#6802]
### Description

Bisecting nightlies, something between https://github.com/software-mansion/react-native-reanimated/commit/b2b58a68db2220b0f787448be5c7cc8eb099f3a8 (last good one) and https://github.com/software-mansion/react-native-reanimated/commit/6fad03e080c8ea4919f35fefab659078b0f08e51 (first bad one) is causing instacrashes on Release Android build. I suspect it *might be* https://github.com/software-mansion/react-native-reanimated/pull/6539 but not sure.

### Steps to reproduce

I don't have a smaller repro than to take the https://github.com/bluesky-social/social-app/ repo and run `yarn android --variant release`. The error in logcat is:

```
E  FATAL EXCEPTION: mqt_native_modules
Process: xyz.blueskyweb.app, PID: 12643
com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: expected 0 arguments, got 1, js engine: hermes, stack:
callNativeSyncHook@1:161022
nonPromiseMethodWrapper@1:168634
NativeReanimated@1:705613
anonymous@1:699443
loadModuleImplementation@1:146748
guardedLoadModule@1:146277
metroRequire@1:145907
metroImportDefault@1:145971
makeShareableCloneRecursive@1:696452
makeShareableCloneRecursive@1:697238
makeShareableCloneRecursive@1:697127
makeShareableCloneRecursive@1:697238
makeMutableNative@1:691095
anonymous@1:690542
loadModuleImplementation@1:146748
guardedLoadModule@1:146277
```

### Snack or a link to a repository

https://github.com/bluesky-social/social-app/

### Reanimated version

3.17.0-nightly-20241119-6fad03e08

### React Native version

0.76.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tjzel** [comment]
I'll look into it.

**Comment by tjzel** [comment]
Hey @gaearon, it seems that Metro/Expo/Android Studio is pulling some invalid caches.

To reproduce the crash:
1. `yarn`
2. `yarn expo prebuild`
3. `yarn android --variant release`. (app doesn't crash)
4. `yarn add react-native-reanimated@nightly`
5. (optional) `yarn expo prebuild`
6. `yarn android --variant release`. (app crashes)

However, if you delete `./android` directory after installing `react-native-reanimated@nightly` the crash doesn't occur anymore and the app doesn't crash anymore.

**Comment by gaearon** [comment]
Fascinating, will check that.
