### ISSUE TITLE
Animated.operator node second argument should be one or more of type AnimatedNode, String or Number but got AnimatedNode

### ISSUE THREAD

**Issue by birken92** [software-mansion/react-native-reanimated#683]
Reanimated: Animated.operator node second argument should be one or more of type AnimatedNode, String or Number but got AnimatedNode, id: 20,AnimatedNode, id: 95

Have anyone seen this issue before?

**Comment by jakub-gonet** [comment]
Hi @birken92,
please add some code which causes this error to show, it's hard to say what's going on without it.

**Comment by birken92** [comment]
@jakub-gonet That is the interesting thing, it fails on our index.js file. So I updated the package to the newest and hopes that will fix the issue.

**Comment by jakub-gonet** [comment]
That's definitely strange, if updating reanimated doesn't help, please post full stacktrace.

**Comment by jakub-gonet** [comment]
Closing, if issue is still relevant please reply.
