### ISSUE TITLE
Svg/Defs/LinearGradient/Stop StopColor props can it be animated ?

### ISSUE THREAD

**Issue by grean** [software-mansion/react-native-reanimated#690]
Hi all,

I'm trying to change the color of my stroke´s circle when an animated value changed (the value changed when i detected the circle is full drag with PanGestureHandler, and i wanted to change the color in each new full circle) but i have this error on load : 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-27 at 15 51 16](https://user-images.githubusercontent.com/170967/77768469-d01dfc80-7042-11ea-9e92-0806d727e7ac.png)

my code : 
```
   const aroundCount = new Value(0); // this value is variaring in an animated.block. It increases by +1 by new circle reached. So i try to interpolate the corresponding color in function of that value and then change the stopColor prop.
   const bgColor = interpolateColor(aroundCount, {
     inputRange: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
     outputRange: ['#F0EFF5', '#00b5ad', '#2185D0', '#B5CC18', '#FBBD08', '#F2711C', '#DB2828', '#E03997', '#6435C9', '#A5673F', '#AAA', '#888', '#666', '#444', '#222', '#000'],
   });
  const fgColor = interpolateColor(aroundCount, {
    inputRange: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    outputRange: ['#00b5ad', '#2185D0', '#B5CC18', '#FBBD08', '#F2711C', '#DB2828', '#E03997', '#6435C9', '#A5673F', '#AAA', '#888', '#666', '#444', '#222', '#000'],
  });
```
```
              <Svg width={canvasSize} height={canvasSize}>
                <Defs>
                  <LinearGradient id="grad" x1="0" y1="0" x2="50%" y2="0">
                    <AnimatedStop key={0} offset="0" stopColor={bgColor} />
                    <AnimatedStop key={1} offset="1" stopColor={fgColor} />
                  </LinearGradient>
                  <LinearGradient id="plate" x1="0" y1="0" x2="50%" y2="0">
                    <Stop offset="0" stopColor="#222" />
                    <Stop offset="1" stopColor="#888" />
                  </LinearGradient>
                </Defs>
                <AnimatedPath
                  stroke="url(#grad)"
                  fill="none"
                  d={string`M ${startX} ${startY} A ${r} ${r} 0 ${largeArcFlag} ${sweep} ${endX} ${endY}`}
                  {...{ strokeWidth }}
                />
              </Svg>
```
As you can see, i've tried to make svg´s Stop component an animatedComponent but it produces the error below.
I've also tried to use this undocumented function without success :
Animated.addWhitelistedNativeProps({ stopColor: true });

Is it possible to change such a value ? How can i do this ?

**Comment by grean** [comment]
Update

I've tried to generate all the gradients before with :
```
  const gradients = ['#F0EFF5', '#00b5ad', '#2185D0', '#B5CC18', '#FBBD08', '#F2711C', '#DB2828', '#E03997', '#6435C9', '#A5673F', '#AAA', '#888', '#666', '#444', '#222', '#000'];

  const gradients2 = ['#00b5ad', '#2185D0', '#B5CC18', '#FBBD08', '#F2711C', '#DB2828', '#E03997', '#6435C9', '#A5673F', '#AAA', '#888', '#666', '#444', '#222', '#000', '#000'];
const grads = gradients.map((color, key) => {
    return (
      <LinearGradient id={`gradient-${key}`} {...{ key }}>
        <Stop
          stopColor={color}
          offset={0}
        />
        <Stop
          stopColor={gradients2[key + 1]}
          offset={1}
        />
      </LinearGradient>
    );
  });
```
and use with in my animatedPath like this :
´´´
<AnimatedPath
                  stroke={`url(#gradient-${aroundCount})`}
                  fill="none"
                  d={string`M ${startX} ${startY} A ${r} ${r} 0 ${largeArcFlag} ${sweep} ${endX} ${endY}`}
                  {...{ strokeWidth }}
                />
´´´
but no colors is displaying...
I even try to replace the line : 
stroke={`url(#gradient-${aroundCount})`} 
by
stroke={concat("url(#gradient-", aroundCount, ")")}
but i got this error :
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-27 at 17 06 51](https://user-images.githubusercontent.com/170967/77775863-7242e200-704d-11ea-8150-077c79b92f8e.png)

Do someone can explain to me why this is not working ?

**Comment by jakub-gonet** [comment]
This is connected with RN SVG library.

**Comment by Dean177** [comment]
@grean did you manage to get anywhere with this? I hit the same issue.

**Comment by grean** [comment]
@Dean177 sorry but i don´t remember.
But what i was trying to achieve was this component : https://github.com/grean/react-native-knob.
If you want to do a gradient in svg path, i remember that this is not possible in svg from my searches. But maybe i'm wrong..

**Comment by imsarulatha** [comment]
@Dean177 Got any solution for this ?
