### ISSUE TITLE
Animated.ScrollView ref RN[0.62]

### ISSUE THREAD

**Issue by tr3v3r** [software-mansion/react-native-reanimated#701]
## Animated.ScrollView ref RN[0.62]

0.62 for React Native brings deprecation related to getting refs from animated scroll nodes:

> Refs on an Animated component are now the internal component. The getNode call has been deprecated. (66e72bb4e0 by @yungsters)

So now instead of using 
```
ref.current._component.scrollTo(...)
```
We should use
```
ref.current.scrollTo(...)
```

It would be nice to have the same behavior while using Animated scrolls from reanimated.

**Comment by jkadamczyk** [comment]
@tr3v3r Do you maybe happen to have a minimal example I can test it on? If not, I can build sth myself relatively fast. Just wanted to save some time if possible 😄

**Comment by jkadamczyk** [comment]
I think I have a solution, it is still a draft, cause I need to test it and make a quick repro with a Reanimated Scroll View and ref usage. In current example app, it worked even with V2 examples and was not throwing errors. As I see using code from React Native repo helped and apparently works 😄
