### ISSUE TITLE
[Question] Is there a way to change height in native thread?

### ISSUE THREAD

**Issue by Garkavenko** [software-mansion/react-native-reanimated#705]
I tried to animate height in FlatList(i mean 60 fps), but every try was unsuccessful.
For example, if i have 100 items in FlatList and renderItem component looks like:
```js
function CollapsibleItemReanimated() {
  const [clock] = useState(new Clock());
  const [gstate] = useState(new Value(State.UNDETERMINED));

  const transState = useMemo(
    () => ({
      finished: new Value(0),
      position: new Value(0),
      time: new Value(0),
      frameTime: new Value(0),
    }),
    [],
  );

  const config = useMemo(
    () => ({
      duration: 500,
      toValue: new Value(100),
      easing: Easing.inOut(Easing.ease),
    }),
    [],
  );

  Animated.useCode(
    () =>
      cond(
        eq(gstate, 4),
        block([
          cond(clockRunning(clock), 0, [startClock(clock)]),
          timing(clock, transState, config),
        ]),
      ),
    [transState, config],
  );
  return (
    <View>
      <PanGestureHandler
        onGestureEvent={Animated.event([{nativeEvent: {state: gstate}}], {
          useNativeDriver: true,
        })}>
        <Animated.View>
          <Text>Press</Text>
        </Animated.View>
      </PanGestureHandler>
      <Animated.View
        style={{
          height: transState.position,
          width: '100%',
          backgroundColor: 'red',
        }}
      />
    </View>
  );
}

export default CollapsibleItemReanimated;
```
And if i swipe on some row, animation will work, but there will be a lot of dropped frames.
Transitioning also doesn't help, because it changes height with no animation
Is there a way to animate height in native thread?
Thanks.

**Comment by terrysahaidak** [comment]
Hi! Could you please create a `https://snack.expo.io`. This would help us a lot to reproduce the issues and find a way to fix it. Thanks.

**Comment by troublediehard** [comment]
I've also tried to create such behavior but looks like height isn't change position of other cells.

**Comment by terrysahaidak** [comment]
@troublediehard Hi, the only way to help you is to debug a reproducing example, os could you provide a snack, please?

**Comment by troublediehard** [comment]
@terrysahaidak I understand. Unfortunately, I've already removed my code (solve my problem with Transition API). I'll try to find time to create repro, but can't really promise.

**Comment by jakub-gonet** [comment]
BTW, you were animating height or using translate? If you animate height it's kinda expected to get decreased performance because you have to recalculate layout

**Comment by jakub-gonet** [comment]
Hi!
This issue was inactive for a while, so I'm closing it.
If you still face this problem don't hesitate to reopen.
