### ISSUE TITLE
Issue with TypeScript types for transforms

### ISSUE THREAD

**Issue by Jomik** [software-mansion/react-native-reanimated#708]
EDIT: Found relevant PR! #707 
I have an `Animated.Node<number>` that I am trying to pass to `translateY`. It works properly, but it says that it is not assignable to `number`, which makes sense. Sounds like a typing issue though.

```tsx
<Animated.View
  style={{
    transform: [
      {
        translateY: transY,
      },
    ],
  }}
/>
```

react-native-reanimate: v1.7.1
expo-sdk: 37
@types/react-native: v0.60.31

**Comment by jakub-gonet** [comment]
Hi @Jomik,
did you check if changes from #707 fix your problem? I don't have a TS project handy to test it.

**Comment by Jomik** [comment]
Yes.
I modified my local instance of react-native-reanimated to use the changes from the PR.
translateY is now an `Animated.Adaptable<number>`

**Comment by jakub-gonet** [comment]
Cool, I will merge it then :>
