### ISSUE TITLE
Latest 1.8.0 release breaks animated SVG paths on android

### ISSUE THREAD

**Issue by owinter86** [software-mansion/react-native-reanimated#718]
Due to this commit, animating svg paths will no longer work for android, as we initially pass in a path with no leading zeros, then the translation will then append the decimal place which will not work when iterpolating path. 

https://github.com/software-mansion/react-native-reanimated/commit/8a33e0e8569af03a5327d8c2ee08892aa3a1bcc2#diff-f137785d3392ec955cdfa51cd322cb53

This can be reproduced when trying to animate a path using interpolatePath with react-native-redash.

I think there is a lot of merit in having this functionality, but maybe we should introduce a new node, or a formatter node that can have the same result without breaking the previous implementation and retaining the ability to interpolate svg paths.

**Comment by sebinq** [comment]
I dont know but my svg animated paths are working as they should.

**Comment by owinter86** [comment]
This example without redash works pre 1.8.0 but does not for 1.8.0
```
import React from 'react';
import Animated, { concat, Easing } from 'react-native-reanimated';
import { View } from 'react-native';
import Svg, { Path } from 'react-native-svg';

const AnimatedPath = Animated.createAnimatedComponent(Path);

export default function App() {
  const animValue = React.useRef(new Animated.Value(1));

  React.useEffect(() => {
    Animated.timing(animValue.current, {
      toValue: 200,
      duration: 1000,
      easing: Easing.linear,
    }).start();
  }, []);

  return (
    <View style={{ marginTop: 40 }}>
      <Svg height="100" width="100">
        <Path d="M0.0,0.0 C0.0,0.0 200.0,0.0 200.0,0.0" fill="none" stroke="red" strokeWidth="5" />
      </Svg>

      <Svg height="100" width="400">
        <AnimatedPath
          d={concat('M', concat(animValue.current), '0.0 C0.0,0.0 200.0,0.0 200.0,0.0')}
          fill="red"
          stroke="red"
          strokeWidth="5"
        />
      </Svg>
    </View>
  );
}

```

**Comment by sebinq** [comment]
Hmm we are probably using different toolset to break svg's path. I'm using one from @wcandillon's [redash](https://wcandillon.github.io/react-native-redash/svg) package. You can try some of these functions and maybe you will get some positive results.

**Comment by owinter86** [comment]
@sebinq I am also using the redash interpolatePath method, see https://github.com/wcandillon/react-native-redash/issues/206, the above is showing an example which is what the redash helper will output.

**Comment by sebinq** [comment]
Did you try different android versions? Because I've tried only on emulator so maybe it isn't working for me either.

**Comment by owinter86** [comment]
Different android versions should not impact this, it seems like you may need to invalidate your caches (or delete your build folder) after upgrading reanimated to 1.8.0 and do a new build.

This is an example that uses the interpolate path and Retext from redash, if you remove the animated paths, you will see that the new concat node is working as expected (Not showing the leading zeros), but unfortunately will break the android animated path when going from integer to decimal string values.

```
import React from 'react';
import Animated, { concat, Easing } from 'react-native-reanimated';
import { ReText, interpolatePath } from 'react-native-redash';
import { View } from 'react-native';
import Svg, { Path } from 'react-native-svg';

const AnimatedPath = Animated.createAnimatedComponent(Path);
Animated.addWhitelistedNativeProps({ d: true });

export default function App() {
  const animValue = React.useRef(new Animated.Value(1));

  React.useEffect(() => {
    Animated.timing(animValue.current, {
      toValue: 200,
      duration: 1000,
      easing: Easing.linear,
    }).start();
  }, []);

  const getAnimatedSVGPath = interpolatePath(animValue.current, {
    inputRange: [1, 200],
    outputRange: ['M0,0 L200,0', 'M100,0 L200,0'],
  });

  return (
    <View style={{ marginTop: 40 }}>
      <ReText text={concat(animValue.current)} style={{ fontSize: 50 }} />

      <Svg height="100" width="100">
        <Path d="M0.0,0.0 C0.0,0.0 200.0,0.0 200.0,0.0" fill="none" stroke="red" strokeWidth="5" />
      </Svg>

      <Svg height="100" width="400">
        <AnimatedPath
          d={concat('M', concat(animValue.current), '0.0 C0.0,0.0 200.0,0.0 200.0,0.0')}
          fill="red"
          stroke="red"
          strokeWidth="5"
        />
      </Svg>

      <Svg height="100" width="100">
        <Path d="M0,0 L200,0" fill="none" stroke="red" strokeWidth="5" />
      </Svg>

      <Svg height="100" width="400">
        <AnimatedPath d={getAnimatedSVGPath} fill="red" stroke="red" strokeWidth="5" />
      </Svg>
    </View>
  );
}
```

**Comment by sebinq** [comment]
Hmm I've tried to `./gradlew clean` and `yarn run start --reset-cache` plus `yarn run android` again but my path animation still works on emulator. But as I said I'm doing it in a little bit different way.

```ts
const AnimatedSvgPath = ({
  d,
  fill,
  stroke,
  strokeWidth,
  durationMs,
  delayMs,
  easing,
}: Props) => {
  const [length, runner, clock, active, delayed] = useMemoOne(() => {
    const calcLength = parsePath(d).totalLength;
    return [calcLength, new Value(0), new Clock(), new Value(0), new Value(0)];
  }, [d]);

  useCode(
    () =>
      block([
        cond(
          not(delayed),
          delay(
            block([set(active, 1), set(delayed, 1)]),
            delayMs + DEFAULT_DISPLAY_DELAY,
          ),
        ),
        cond(active, [
          runTiming(runner, clock, 0, 1, durationMs, easing),
          cond(not(clockRunning(clock)), set(active, 0)),
        ]),
      ]),
    [],
  );

  return (
    <AnimatedPath
      d={d}
      strokeDasharray={length}
      strokeDashoffset={interpolate(runner, {
        inputRange: [0, 1],
        outputRange: [length, 1],
        extrapolate: Extrapolate.CLAMP,
      })}
      opacity={interpolate(runner, {
        inputRange: [0, 0.25, 1],
        outputRange: [0, 0.8, 1],
        extrapolate: Extrapolate.CLAMP,
      })}
      fill={fill}
      stroke={stroke}
      strokeWidth={strokeWidth}
    />
  );
};
```

**Comment by owinter86** [comment]
@sebinq This issue is for animating the actual path, so animating the `d` prop will not work on android using 1.8.0

**Comment by sebinq** [comment]
I’m sorry then. I can see now that I’m not helping here.

Anyway, I wish you best luck with solving your issue!

**Comment by jakub-gonet** [comment]
Hi @owinter86,

this patch fixed the difference between platforms, as IOS uses `NSNumber stringValue` method, do your animated SVG work on IOS?

One workaround may be making `concat(number, '.0')` if you always get integers or wrapping it with `cond(eq(round(number), number), concat(number, '.0'), concat(number))` but it creates some overhead

**Comment by owinter86** [comment]
Yeah works fine with iOS, typically when animating svg paths you will start with an integer and it will interpolate through decimal values to get to the final integer value. This seems to be a requirement for animated svg paths on android.

For now I have upgraded to 1.8.0 but applied a patch-package reverting that commit as the current app I am working on is heavily reliant on animated svg paths.

**Comment by jakub-gonet** [comment]
That's strange, I'll test it rn, thanks for submitting this issue!

**Comment by jakub-gonet** [comment]
OK, I got it working.

I checked and IOS isn't using localization to format this, so I suppose you're living in a country that uses comma as decimal separator.

Can you try changing your patch package to add:
```java
+ import java.util.Locale;

- private final static NumberFormat sFormatter = NumberFormat.getInstance();
+ private final static NumberFormat sFormatter = NumberFormat.getInstance(Locale.ENGLISH);

```

please?

**Comment by owinter86** [comment]
Ah sorry, I tried to simplify my example and did not place a comma after the `concat(animValue.current)`, so there is actually no issue with the example. I found that the issue is when above 1000, previous concat is `1000.00`, it is now `1,000` which will conflict with animated path value. So unfortunately the Locale.English will not work either.

Updated example below, it should run fine until the animation hits the value 1000 in the timing transition.

```
import React from 'react';
import Animated, { concat, Easing } from 'react-native-reanimated';
import { View } from 'react-native';
import Svg, { Path } from 'react-native-svg';

const AnimatedPath = Animated.createAnimatedComponent(Path);
Animated.addWhitelistedNativeProps({ d: true });

export default function App() {
  const animValue = React.useRef(new Animated.Value(1));

  React.useEffect(() => {
    Animated.timing(animValue.current, {
      toValue: 1500,
      duration: 1000,
      easing: Easing.linear,
    }).start();
  }, []);

  return (
    <View style={{ marginTop: 40 }}>
      <Svg height="100" width="400">
        <AnimatedPath
          d={concat('M', concat(animValue.current), ',0.0 C0.0,0.0 200.0,0.0 200.0,0.0')}
          fill="red"
          stroke="red"
          strokeWidth="5"
        />
      </Svg>
    </View>
  );
}
```

so pre this commit, the final aniamted path value is 
`M1500.0,0.0 C0.0,0.0 200.0,0.0 200.0,0.0`, 
with this commit it is
`M1,500,0.0 C0.0,0.0 200.0,0.0 200.0,0.0`
which causes the crash.

**Comment by owinter86** [comment]
Adding `sFormatter.setGroupingUsed(false);` to the previous commit will fix the issue, we do not need the locale changes in the end.

**Comment by jakub-gonet** [comment]
That's not a problem, add
`sFormatter.setGroupingUsed(false);` to resolve it.

**Comment by sebinq** [comment]
Similar problem is present for concat strings (for example during rotation handling)

In my use-case using:

```ts
transform: [{rotate: concat(rotate, 'deg')}]
```

Ends with:

![93277501_872504596510659_3485724564703412224_n](https://user-images.githubusercontent.com/33039909/78883733-2edb7100-7a5a-11ea-9517-484afd628cfb.jpg)

**Comment by wcandillon** [comment]
@sebinq I'm not sure what is happening here but could you use radian instead? Then you can pass a numerical value directly. redash provides a toRag() function but of course I would advocate to rewrite code to deal with radian directly if it makes sense ;-)

**Comment by owinter86** [comment]
@sebinq I believe this is due to the internationalising of the decimal place, this has been fixed in master, but yet to be released.

**Comment by sebinq** [comment]
@wcandillon Thank you, I will use radians :)

**Comment by jakub-gonet** [comment]
This may not help, as #720 fixed not only internationalization of numbers but also adding decimal separator, so if you use values above 999 it'll add comma there. The best thing to do right now is to use the reanimated package from the source at commit cec00c7 or wait for 1.9.0 release
