### ISSUE TITLE
How pass prop to make animation dinamically

### ISSUE THREAD

**Issue by cklinx** [software-mansion/react-native-reanimated#721]
Hi, i need to pass a prop in my childer component to make the animation variable:

This is my parent code:
```
export default function App() {
    const [min, setMin] = React.useState(200)
    return (
        <View style={styles.container}>
        <Snappable minValue={min} />
        <TouchableOpacity
            style={styles.touch}
            onPress={() => setMin(0)}>
            <Text>Change Props</Text>
        </TouchableOpacity>
        </View>
    );
}
```

My Snappable component seem not get the props (also with TouchableOpacity click)

expo code  [example](https://snack.expo.io/@cklinx/reanimated-props-change) 

 Can you help me please?
Thanks

**Comment by jakub-gonet** [comment]
Hi @cklinx,

try using ref to `Animated.Value` and pass that instead

**Comment by cklinx** [comment]
> Hi @cklinx,
> 
> try using ref to `Animated.Value` and pass that instead

Thanks @jakub-gonet can you show me an example please? Thanks in advance

**Comment by jakub-gonet** [comment]
Try creating ref in parent component: `const animValue = useRef(new Value(value));` and then pass it to child component: `<Child ref={animValue}/>`. Then you should be able to use that value as `animValue.current`

This is pretty much standard thing to do if you want to get around react state update and it's not special to reanimated
