### ISSUE TITLE
[Question] Controlled animated component ?

### ISSUE THREAD

**Issue by grean** [software-mansion/react-native-reanimated#728]
Is there a way to change an animated value from a parent component via ref or another way ?

For example, i want to click on a button and then it changes the value of an animated value and then refreshes the concerning component.

I do that with a useState in parentComponent and then passing the value as a prop and then change de key prop of the animated component so the component rerender but it flickers :(
So i wanted to avoid that behavior by changing the animated value directly inside wihout triggering a rendering with a useState.

**Comment by jakub-gonet** [comment]
If you want to update `Animated.Value` in an imperative manner you probably want to use [`setValue()`](https://software-mansion.github.io/react-native-reanimated/value.html) function.
It won't cause the component containing animated Value to rerender.

`Value`s are ordinary JS variables so you can use refs, arg passing and so on. 

If you have further concerns I'm happy to help.

**Comment by grean** [comment]
Thanks for the reply, but correct me if i'm wrong,
Do each setValue produce a refreshing of the component ?
In there a way of setting the value of more than one variable in the same time ?

**Comment by jakub-gonet** [comment]
You mean rerender? If yes, then no, the whole point of calling setValue is to avoid rerendering, because it resets all animation states. You unfortunately can't update multiple values in declarative fashion by using set node, but you can do it in the imperative manner.

**Comment by grean** [comment]
In fact, my problem is :
I have a component with an Animated.Code with at least 15 animated.nodes.
when i use it with gestures, my algorithm is fine, it does what i want.
But when i want to modify some variables imperatively, (via a ref) my component move very weird.
I thought that if i initialize the good nodes it will work as expected.
The animated.Code block is [https://github.com/grean/react-native-knob/blob/8e915876fe63d650cb6e602cb7966ae65b230975/src/CircularProgress.tsx#L130](here)
My imperative calls ar not checkin yet but do you think that what i want to acheive can work ?
Consecutive calls of setValues can lead to the context that i want or do each call of setValues will reset and reinit all nodes ?
I will try to test that tomorrow.

**Comment by grean** [comment]
@jakub-gonet 
Hi,
I've finally found the good solution. You can see my implementation [here](https://github.com/grean/react-native-knob/blob/b6bdfe4ad8a994f9698e41ffac86eed879c6ca64/src/CircularProgress.tsx#L128)
When i set the values of multiple nodes at the same imperative call, i have to be very vigilent on the order of the calls and on the state of the gesture automate.
It´s a bit hard to understand what's actually happening when we call setValue on each node.
I'm not totally sure of the behavior under the hood but it works well.

**Comment by jakub-gonet** [comment]
Cool, glad you figured it out eventually 😄

**Comment by jmkmay** [comment]
Hey @jakub-gonet, piggy backing off this post. I have a controlled animated value which determines the max drag value for a view. This value gets updated after two `onLayout` handlers get called. The purpose is to make sure that you can't drag one view such that it's bottom moves past the bottom of the screen.

```
const pageHeight = new Value()
const contentHeight = new Value()

const onContentLayout = (e: LayoutChangeEvent) => {
    console.log('Content height: ', e.nativeEvent.layout.height)
    contentHeight.setValue(e.nativeEvent.layout.height)
 }

const onPageLayout = (e: LayoutChangeEvent) => {
    console.log('Page Height: ', e.nativeEvent.layout.height)
    pageHeight.setValue(e.nativeEvent.layout.height)
 }

const maxDrag = cond(and(defined(pageHeight), defined(contentHeight)), sub(pageHeight, contentHeight), -75)
```

maxDrag here sort of unpredictably works as intended, but occasionally will reset itself to 0. (Why 0, I'm not sure. Given that the only possible values are undefined on component mount, correct value after layout, or -75 which is the default maxDrag).

Any ideas?

**Comment by jakub-gonet** [comment]
Hard to say, we often normalize values in the native side and the default is the `0`.

We have an issue with [`defined` node](https://github.com/software-mansion/react-native-reanimated/issues/793) so you may want to check if this is working correctly.

Please add some small [snack](https://snack.expo.io/) which will allow me to test it.

**Comment by jmkmay** [comment]
Hey @jakub-gonet thanks for the response. Turns out I didn't understand that `Animated.Value`s reset/reinitialize on react re-render. Basically there was something on the page triggering a re-render, and because that logic relies on those onLayout effects, there's some weird timing stuff which prevents it from getting set to the correct value.

My solution was to use a utility library called [use-memo-one](https://github.com/alexreardon/use-memo-one) which basically gives you a semantic guarantee that the animated value won't reset on re-render.

This might be a useful hook/addition for `react-native-reanimated`?

**Comment by jakub-gonet** [comment]
We have one already [`useAnimatedValue`](https://github.com/software-mansion/react-native-reanimated/blob/master/src/useValue.js) which uses `useRef` under the hood. It isn't released yet, but feel free to copy it and use in your project or just tick to use-memo-one

**Comment by jmkmay** [comment]
Is that in version 1 as well? I noticed that used when I tried upgrading to version 2, but we can't upgrade because of some conflicts with Hermes.

**Comment by jakub-gonet** [comment]
It's not released in v1 atm, v2 alpha-3 have master code, so includes this helper as well. For now, you can directly copy the code and use it in that way or you can wait until we release 1.10 (which may take some time)
