### ISSUE TITLE
Animated event properties

### ISSUE THREAD

**Issue by aminify** [software-mansion/react-native-reanimated#730]
I am new to react native and I don't have react native's built-in Animated background. As a learner who tries to make use of this library I'm getting so frustrated creating a simple drag and drop feature because of the lack of learning resources. I want to know when using `Animated.event` what are the properties available on the `nativeEvent` object and I couldn't find a place describing it. I've seen extracting both `x` and `translateX` property for example but I don't know the difference and none of them works as I expected. It would be appreciated if you could guide me through a reference for it.
also I looked up the [event handling with reanimated](https://software-mansion.github.io/react-native-reanimated/event-handling-with-reanimated-nodes.html) and there is a link as an example which results in a 404!

**Comment by jakub-gonet** [comment]
Hi @aminify,

firstly, sorry for 404, we've updated most of docs links to examples after updating Example app, but it seems not all, [Here's a new link, just add src/](https://github.com/software-mansion/react-native-reanimated/blob/master/Example/src/PanRotateAndZoom/index.js).

Secondly, `event` node just maps the object that you've passed to nodes.
So if you're using Gesture Handler like in the example, you're getting object with `nativeEvent` keys and properties from the given handler, for example, `PanGestureHandler` has [8 properties described in docs](https://software-mansion.github.io/react-native-gesture-handler/docs/handler-pan.html#event-data) besides base properties.
```js
this.onGestureEvent = event([
  {
    nativeEvent: {
      translationX: x => set(this._x, x),
    },
  },
]);
```

Here you can see basic mapping from `translationX` to function that returns `set`  node. If onGestureEvent is used somewhere and any of mapped properties change, it will reevaluate used nodes, in this case `set` node, causing `this._x` to change.

Does it help you?

**Comment by aminify** [comment]
Thanks for your explanation. I could finally get my code to behave as I expect.
I hadn't seen those [event properties](https://software-mansion.github.io/react-native-gesture-handler/docs/handler-pan.html#event-data) that you mentioned and didn't know it would be related to `Animated.event`.
After all I believe this is an amazing library and should be used by developers that are learning react native but the documention is very brief and targeted for experienced developers. Aren't there any plans to include a step by step guide to master this library? if so I would really love to contribute and as a new learner make it suitable for peaple like myself.

**Comment by jakub-gonet** [comment]
Those properties in event node aren't related to Reanimated, they're from Gesture Handler and in order to map some property to animated node we have to provide structured input for it.

We are aware of quality of docs, I have some drafts of new docs, but it needs to be polished.

#673 is related to that.
