### ISSUE TITLE
What to use instead parallel(...)?

### ISSUE THREAD

**Issue by Goldyukol** [software-mansion/react-native-reanimated#732]
What to use instead native parallel(...) method of for example in such a function?

```
`const open = () => {
  
  scrollRef && scrollRef.current
    ? scrollRef.current.scrollTo({x: 0, y: 0, animated: true})
    : null;
  setBabyOpened(true);
  Animated.parallel([
    Animated.timing(animationPositionX, {
      toValue: 0,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationPositionY, {
      toValue: 0,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationButtonCloseTop, {
      toValue: base * 12,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationButtonCloseRight, {
      toValue: base * 12,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationWidth, {
      toValue: screenWidth,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationViewHeight, {
      toValue: OPENEDHEIGHT,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationHeight, {
      toValue: screenHeight,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationPreViewHeight, {
      toValue: screenHeight,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationRadius, {
      toValue: 0,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationImageWidth, {
      toValue: OPENEDHEIGHT - base * 128,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationImageHeight, {
      toValue: OPENEDHEIGHT - base * 128,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationImagePositionX, {
      toValue: -base * 24,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationImagePositionY, {
      toValue: base * 24,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationImageRotate, {
      toValue: 0.15,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationCloseOpacity, {
      toValue: 1,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationProgressWidth, {
      toValue: screenWidth * 1 - base * 48,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationProgressBottom, {
      toValue: base * 88,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationInfoOpacity, {
      toValue: 1,
      duration: animationDuration,
      useNativeDriver: false,
    }),
    Animated.timing(animationFruitHeight, {
      toValue:
        screenHeight <= 580
          ? screenHeight - OPENEDHEIGHT + base * 72
          : screenHeight - OPENEDHEIGHT,
      duration: animationDuration * 2,
      useNativeDriver: false,
    }),
    Animated.timing(animationGradientHeight, {
      toValue:
        screenHeight <= 670
          ? screenHeight <= 580
            ? -base * 163
            : -base * 83
          : -base * 63,
      duration: animationDuration,
      useNativeDriver: false,
    }),
  ]).start();
  };`
```

**Comment by jakub-gonet** [comment]
Hi @Goldyukol,

you can try using Transitions or keep a list of `Value` nodes which will act like flags, so you can use `cond(eq(flag, 1), (your animation))` and just set it off like that: `map(flags, flag => flag.setValue(1))`

I believe there are more ways to do that too.

Related issue: #81 

Hope that helps.

**Comment by Goldyukol** [comment]
Can you describe in more detail how to draw a parallel?

**Comment by Goldyukol** [comment]
> Hi @Goldyukol,
> 
> you can try using Transitions or keep a list of `Value` nodes which will act like flags, so you can use `cond(eq(flag, 1), (your animation))` and just set it off like that: `map(flags, flag => flag.setValue(1))`
> 
> I believe there are more ways to do that too.
> 
> Related issue: #81
> 
> Hope that helps.



> Hi @Goldyukol,
> 
> you can try using Transitions or keep a list of `Value` nodes which will act like flags, so you can use `cond(eq(flag, 1), (your animation))` and just set it off like that: `map(flags, flag => flag.setValue(1))`
> 
> I believe there are more ways to do that too.
> 
> Related issue: #81
> 
> Hope that helps.

Can you describe in more detail how to draw a parallel(...)?

**Comment by jakub-gonet** [comment]
I need more info when you're triggering the animation? When component mounts? If yes, you can use multiple [`Animated.Code`](https://software-mansion.github.io/react-native-reanimated/animated-code.html) or just attach animated nodes to corresponding component properties. If later, you can use an array of flags and wrap every animation in cond as I've shown earlier. Then if you want to run your animation you just map every flag in onClick for example and set those to true (or 1 in the reanimated world). Every animation will update and run because one of theirs dependencies updated.

**Comment by nhimspec** [comment]
> I need more info when you're triggering the animation? When component mounts? If yes, you can use multiple [`Animated.Code`](https://software-mansion.github.io/react-native-reanimated/animated-code.html) or just attach animated nodes to corresponding component properties. If later, you can use an array of flags and wrap every animation in cond as I've shown earlier. Then if you want to run your animation you just map every flag in onClick for example and set those to true (or 1 in the reanimated world). Every animation will update and run because one of theirs dependencies updated.

@jakub-gonet could you give us any examples run every animation by flag on click?

**Comment by terrysahaidak** [comment]
I would suggest to have single animation value, animation from 0 to 1 and to use interpolate for everything else where input is `[0, 1]` and output is `[currentValue, toValue]`

**Comment by nhimspec** [comment]
> I would suggest to have single animation value, animation from 0 to 1 and to use interpolate for everything else where input is `[0, 1]` and output is `[currentValue, toValue]`

Could it parallel? Could you give me any simple example? I got stuck T__T
