### ISSUE TITLE
[Question] Flickering animations when using React Hooks

### ISSUE THREAD

**Issue by xignor** [software-mansion/react-native-reanimated#735]
I'm seeing flickering when using react hooks.  Here is a reproducible  snack:
https://snack.expo.io/ydvijSJI2

Trying to get the bottom view to go fullscreen on pan.

![ezgif-6-431d5d6db518](https://user-images.githubusercontent.com/36939901/79280360-17601600-7ea8-11ea-9fe3-dcb48f009392.gif)

Any thoughts on what might be going on?

**Comment by diegodls** [comment]
I fix my problem with TapGesture changing 

**event.nativeEvent.oldState**

to

**event.nativeEvent.state**

**Comment by jakub-gonet** [comment]
Hi @xignor,

that's really strange, maybe imperative API has some bug, I don't see any obvious mistake from your side.

That being said, you should implement your animations declaratively, check out [snappable example](https://github.com/software-mansion/react-native-reanimated/blob/master/Example/src/snappable/index.js), it should give you a good insight into how interactions between Reanimated and RNGH are managed.

**Comment by jakub-gonet** [comment]
This isn't related to Reanimated, the problem lies in the use of RNGH.
Try mapping `translationY` instead of `x` & `y` values because translation value is accumulated and the direct value of movement isn't fluid, so animation starts flickering.
