### ISSUE TITLE
Add threshold to `onChange`

### ISSUE THREAD

**Issue by pie6k** [software-mansion/react-native-reanimated#737]
Let me describe the use case.

I have drag'n'drop component and I have to call JS event during dragging.

However - I don't want to do it on every position change (as those are happening very often), but only if the change is meaningful for my case - in my case it's around 15 points.

In order to do that, I divide and floor finger position with

```
floor(divide(translationY, 15))
```

In such case - if I use `onChange` on this - indeed I'm able to call my JS callback only on 15 points change steps.

This, however 'pollutes' my blocks, and also in my callback, I have to remember to multiply divided value back with 

```
                call(
                  [dividedValue],
                  ([value]) => {
                    const realValue = value * 15;
                  },
                ),
```
.

I think it'd be great to have something like `onChange(translationY, someBlock, 15)` so it'll only execute the block when input value changed by 15 since last time `someBlock` was called.

**Comment by jakub-gonet** [comment]
Related issue #600

**Comment by jakub-gonet** [comment]
We recently released reanimated 2, so this issue isn't exactly on our roadmap and I'm closing it. But I'm happy to merge PR fixing this.
