### ISSUE TITLE
Move towards React host refs instead of findNodeHandle for compatibility react-native-web@next

### ISSUE THREAD

**Issue by jfrolich** [software-mansion/react-native-reanimated#738]
`findNodeHandle` should not be used anymore and recently it breaks compatibility with new builds of `react-native-web`. I also think this will enable `react-native-reanimated` to be compatible with function components, so that would be nice!

See here for more info: https://github.com/necolas/react-native-web/issues/1219#issuecomment-614395504

**Comment by piaskowyk** [comment]
Resolved 😄
