### ISSUE TITLE
Why exec of Animated Code have not fire when use hook with React.memo

### ISSUE THREAD

**Issue by CaoThien96** [software-mansion/react-native-reanimated#743]
## Description
I have make simple code Reanimated with Hook
.....

When i press Call Api i receive log : 
- Sub Render  true
- stateAni 1
- Sub Render false
My expected is:
- Sub Render  true
- stateAni 1
- Sub Render false
- stateAni 0
* I try change React.memo check shouldUpdate return False. It work fine but i don't want that
* I try write ViewLoading by Component and use 
componentWillReceiveProps(nextProps) {
        if (nextProps.isLoading) {
            this.stateAni.setValue(1)
        } else {
            this.stateAni.setValue(0)
        }
    } for trigger. It work fine

I don't know why it doesn't work when using Hook. Any thoughts on what might be going on? Thank every one

## Code
> export const useIsMount = () => {
 const isMountRef = useRef(true);
  useEffect(() => {
       isMountRef.current = false;
   }, []);
    return isMountRef.current;
};

>const ViewLoading = ({
    isLoading,
}) => {
    let [stateAni, setStateAni] = useState(new Value(isLoading ? 1 : 0))
    const isMount = useIsMount();
    useEffect(() => {
        if (isMount) {
            console.log('First Render');
        } else {
            if (isLoading) {
                stateAni.setValue(1)
                console.log('Sub Render ', isLoading);
            } else {
                stateAni.setValue(0)
                console.log('Sub Render', isLoading);
            }
        }
    }, [isLoading]);
    return (
        <View>
            <Text>Test Function</Text>
            <TouchableOpacity onPress={() => {
                stateAni.setValue(1)
            }}>
                <Text>Show </Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={() => {
                stateAni.setValue(0)
            }}>
                <Text>Hide</Text>
            </TouchableOpacity>
            <Test stateAni={stateAni} />
        </View>
    );
}

>const Test = React.memo(({ stateAni }) => (
    <Animated.Code
        exec={block([
            call([stateAni], ([a]) => {
                console.log('stateAni', a)
            }),
            cond(eq(stateAni, 1), [
               
            ], [])
        ])}
    />
), () => false)
const App = () => {
    const [isLoading, setLoading] = useState(false)
    return (
        <React.Fragment>
            <ViewLoading isLoading={isLoading} />
            <TouchableOpacity onPress={() => {
                setLoading(true)
                setTimeout(() => {
                    setLoading(false)
                }, 3000);
            }}>
                <Text>
                    Call Api
                </Text>
            </TouchableOpacity>
        </React.Fragment>
    )
}
export default App;

### Package versions

- React: 16.11.0
- React Native:0.62.1
- React Native Reanimated:^1.8.0

**Comment by jakub-gonet** [comment]
Hi @CaoThien96,

I don't really follow what you want to achieve here. You can't interleave Reanimated API with plain JS because Reanimated creates its nodes on the native side and they can't really interact with react (specifically, changing their value won't trigger rerender). Please describe your intentions clearer and provide a [snack](https://snack.expo.io/).

I'm closing this issue, I'll reopen when more info will be provided.

Also, try using code blocks instead of pasting code directly next time:
````
```js
// your code here
```
````
