### ISSUE TITLE
Transitions on the web

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion/react-native-reanimated#744]
## Description
Do transitions work on the web?
I tested transitions on the web, and that won't work.
I couldn't find anything about that.

### Package versions

- React: 16.12
- React Native: 0.61
- React Native Reanimated: 1.7

**Comment by albertcito** [comment]
Yep, looks like it doesn't work in web. I created two codes that work in iOS but not in web :(

Basic opacity: 
https://snack.expo.io/@albertcito/basic-opacity-re-animated

Circular Progress:
https://snack.expo.io/@albertcito/circular-progress-strokedashoffset-with-re-animates

**Comment by albertcito** [comment]
I figure out that an animation with `interpolate` function [doesn't works properly](https://snack.expo.io/@albertcito/basic-opacity-re-animated) in web. But, if you just return a `block` the animations can works. Here the example: 

https://snack.expo.io/@albertcito/re-animated-translations-working-in-web

**Comment by jakub-gonet** [comment]
At the moment they don't work, but we're accepting PRs for it.
