### ISSUE TITLE
React native reanimated component flashes before rendering

### ISSUE THREAD

**Issue by GiridharKarnik** [software-mansion/react-native-reanimated#751]
## Description

I have made a [progress graph](https://www.xelplus.com/wp-content/uploads/2019/09/ProgressCircle-04.png) like component, which is animated using `react-native-reanimated`. 

  The implementation is fairly straight forward, where the circle is made out of an animated `Circle` svg component pulled from `react-native-svg` and it's`strokeDashoffset` is animated based on the `timing` animation node of `react-native-reanimated`.

You can find the complete example [here.](https://snack.expo.io/@griffintaimer/3ca422) running pretty much as expected.

## Problem

The `Circle` component loads completely basically flashes before the animation kicks in. The strokeDashOffset is varied in the following line

```
const strokeDashoffset = sub(circumference, multiply(α, r));
```

When the animation is yet to start the value of `α` is 0 hence the value of `strokeDashoffset` should be equal to `circumference`, essentially meaning that the entire circle is hidden from view. 

  But that is not the case, the circle at first is completely visible and then when the animation kicks in, it vanishes, causing a brief flash, which leads to bad user experience. I am not able to figure out what the problem is. Please help me figure out and understand the part where I am going wrong. 🙏🏽

## Code

You can find the snack [here](https://snack.expo.io/@griffintaimer/3ca422).

### Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: ^1.8.0
- React Native SVG - ^12.0.3

**Comment by GiridharKarnik** [comment]
Thinking about it now, this might be completely unrelated to `react-native-reanimated` and the component might be rendering without styles at first, before the styles kick in.

**Comment by NathanSaunders01** [comment]
I have the same issue. I'm not sure if it's an issue with Reanimated or the SVG library but my current work around is to wrap the SVG in an animated view with an opacity interpolation.

`
  const opacity = interpolate(animation, {
    inputRange: [0, 0.01],
    outputRange: [0, 1],
    extrapolate: Extrapolate.CLAMP,
  });
`

Feels wrong but it does the job

**Comment by jakub-gonet** [comment]
#1027 should resolve the situation when styles are applied after a slight delay.
