### ISSUE TITLE
How can I work my animation with only toValue

### ISSUE THREAD

**Issue by Sargnec** [software-mansion/react-native-reanimated#755]
### Description
I'm making my tabbar dissappear while scrolling down with animation. onScroll works every frame. If I continue to scroll down onScroll still sends true value to my function and animaton works again. How can i disable postion  so only toValue is gonna work and my function will not trigger again while returning value is same

## Code

```
function runTiming(value, dest) {
    const clock = new Clock();
    const state = {
        finished: new Value(0),
        position: new Value(0),
        time: new Value(0),
        frameTime: new Value(0),
    };

    const config = {
        duration: 200,
        toValue: new Value(0),
        easing: Easing.inOut(Easing.cubic),
    };

    return block([

        cond(clockRunning(clock), 0, [

            set(state.finished, 0),
            set(state.time, 0),
            set(state.position, value),
            set(state.frameTime, 0),
            set(config.toValue, dest),
            startClock(clock),
        ]),
        timing(clock, state, config),
        cond(state.finished, debug('stop clock', stopClock(clock))),
        state.position,
    ]);
}
```

### Package versions

"react": "16.9.0",
"react-native": "0.61.5",
"react-native-reanimated": "^1.7.1",

**Comment by jakub-gonet** [comment]
Hi @Sargnec,

I think more code is needed to provide the context.

From now I think you may need to add some `Animated.Value` acting like a flag: when you end scrolling you set it to true in order to prevent triggering the animation.

**Comment by jakub-gonet** [comment]
@Sargnec,
this issue was inactive for a while, so I'm closing it.
If you still face this problem don't hesitate to ask.
