### ISSUE TITLE
Transitioning ScrollView – height jumps on Transition.Out, when scroll position is at the bottom and transition removes an element

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-reanimated#758]
## Description
in the example below when you the view transitions out the scrollview heights jumps while the view itself fades out normally, 

## Code
https://snack.expo.io/@aeid/nervous-macaroni-and-cheese

### Package versions

- React: 16.9.0
- React Native: 62.0
- React Native Reanimated: ^1.7.1

and the versions in the above snack.

**Comment by jakub-gonet** [comment]
We discussed Transitions internally in our team. Considering that v2 makes creating animations easier and Transitions was an experimental API for a long time, we decided to leave Transitions as they are.
 
We won’t actively fix bugs in them, but we’ll happily merge any PR with fixes. We’re also thinking about rewriting Transitions in v2 sometime in the future.

I’m closing this issue, but if you have further questions, I will be happy to help.
