### ISSUE TITLE
Clock initial value is negative

### ISSUE THREAD

**Issue by johnsiu2016** [software-mansion/react-native-reanimated#763]
## Description
I think clock value should always be greater than the old value? However, the screenshot shows that clock didn't behave like this and even caused the frameTime to be negative. This also made the animating view flickering. I think there are some bugs inside native code?

### Screenshots
![image](https://user-images.githubusercontent.com/17636906/80369562-11632f80-88c1-11ea-862f-bf66615d4fcd.png)

## Steps To Reproduce
runTiming code from https://software-mansion.github.io/react-native-reanimated/declarative-animation-api.html can reproduce this behaviour

## Package versions
react-native 0.62.0
react-native-reanimated 1.8.0
This bug actually has been a while, not just v.1.8.0

## Platform
iOS only

**Comment by jaulz** [comment]
Yep, I noticed something similar in browsers but it only happens once in a while (I assume if the animation is delayed because other stuff is loading) and I cannot really reproduce it:
![image](https://user-images.githubusercontent.com/5358638/80698259-82316400-8ada-11ea-8fd7-3b1bfe106422.png)

**Comment by jaulz** [comment]
@johnsiu2016 I just created a PR which solves the issue on my side. Please check it out and let me know if it helps you as well.

**Comment by johnsiu2016** [comment]
@jaulz 
![image](https://user-images.githubusercontent.com/17636906/80828867-9a0f0200-8c18-11ea-857c-ec6c26c11c51.png)

![image](https://user-images.githubusercontent.com/17636906/80828824-86fc3200-8c18-11ea-92a6-b1f21e808165.png)

I can confirm that the patch doesn't work for me.
Currently, my workaround is to filter out the bad values at the beginning and the animating view works as expected.

``` javascript
    cond(
      and(
        greaterOrEq(sub(state.position, newPosition), 0.15),
        eq(newPosition, 0),
      ),
      0,
      set(newPosition, state.position),
    ),
    newPosition,
```

**Comment by jakub-gonet** [comment]
No, this is intended (but unexpected). Stopped clocks don't keep their value frozen but still updates. Stopping a clock means that nodes that depend on that clock won't be updated.

Sorry for the confusion, I'll mention it in the docs.
