### ISSUE TITLE
Animated concat does not work anymore properly with animated value

### ISSUE THREAD

**Issue by RikSchefferOberon** [software-mansion/react-native-reanimated#772]
## Description

Since updating to version 1.8.0: When using Concat in combination with an animated value the app crashes with the error in the screenshot.
It did work great before (version 1.7.1 and lower)

### Screenshots

![Screenshot_20200429-111326](https://user-images.githubusercontent.com/49634416/80579595-9dcd3980-8a0a-11ea-9412-d5f962528cac.png)

## Steps To Reproduce

Bare minimum to crash:
`<Animated.View style={{width: Animated.concat(new Animated.Value(0.4), '%')}}></Animated.View>`

real life use case:
`this.animation` is an animated value.
`<Animated.View style={{width: Animated.concat(
    this.animation.interpolate({
        inputRange: [0, 1],
        outputRange: [0, 100],
        extrapolate: Animated.Extrapolate.CLAMP,
    }),
    '%'
),
height: 3, 
backgroundColor: 'red'}}/></Animated.View>`

### Expected behavior
Just like before: concatinate the animated value and the string.

### Actual behavior
The float is converted to a string but not concatinated with the second param ('%' in the example). Which results in `width: '0.4', which cannot be handled by react-native, which results in a crash.

## Snack or minimal code example

somewhere add this to the style: `width: Animated.concat(new Animated.Value(0.4), '%'),`

## Package versions

- React: 16.9.0
- React Native: 0.61.5
- React Native Reanimated: 1.8.0

**Comment by jakub-gonet** [comment]
This issue was fixed in [cec00c7](https://github.com/software-mansion/react-native-reanimated/commit/cec00c76855cbb4ef7cc3f6c864195130dc118e5), please upgrade Reanimated to 1.9.0

**Comment by nbaua** [comment]
Is this fixed?

TypeError: concat is not a function. (In 'concat(yRotate, "deg")', 'concat' is undefined)

**Comment by jakub-gonet** [comment]
This is unrelated to this issue, try reinstalling node_modules and running metro with --reset-cache flag.

**Comment by abdul-wajid-afridi** [comment]
how can we concat values in reanimated v2. or any other way may be in redash or if possible in react native reanimated v2 it will be good.

const text = useDerivedValue(() => { const formattedNumber = ReanimatedAddCommasUsStyle(commonAmountRaised); return${props.currency.symbol}${formattedNumber}; }, [commonAmountRaised, props.currency.symbol])
