### ISSUE TITLE
Math.trunc() function ?

### ISSUE THREAD

**Issue by grean** [software-mansion/react-native-reanimated#774]
In javascript, there is the Math.trunc() function to get the integer part of a number but this function is missing in the reanimated API why ?

**Comment by grean** [comment]
Maybe because we can replace by something like this  ?
set(intPart, cond(greaterThan(valueToTruncate, 0), floor(valueToTruncate), ceil(valueToTruncate))

**Comment by jakub-gonet** [comment]
It's basically that, using `trunc` is not really common and you can achieve this by using `floor` and `ceil` nodes.
