### ISSUE TITLE
Warning onReanimatedPropsChange

### ISSUE THREAD

**Issue by grean** [software-mansion/react-native-reanimated#775]
Hi,

I have this warning : 
Sending `onReanimatedPropsChange` with no listeners registered.

I'm using an animated prop that a i pass to an other component and it works as expected but i have this warning.
I'm using the clock example from the documentation [here](https://software-mansion.github.io/react-native-reanimated/declarative-animation-api.html) to obtain my animated variable.

I search in google, doc or issues but no success..
What does it mean ?

**Comment by jakub-gonet** [comment]
It means you're sending `onReanimatedPropsChange` and Reanimated didn't register any handler for it in RN. It shouldn't normally happen, as we register it in a `createAnimatedComponent`. Please add a [snack](https://snack.expo.io/) or post relevant pieces of implementation, I can't really help you without code.

**Comment by grean** [comment]
Thanks for your reply.
The warning has disappeared now.. but it sometimes (not always) comes back when i reload (menu -> reload) my code in the simulator..
I've tried to wrap the component that receive the animated prop with ```createAnimatedComponent```  but i have this error :
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-05-01 at 16 56 41](https://user-images.githubusercontent.com/170967/80814800-d0269480-8bcc-11ea-83b6-eb5a5065caa0.png)

**Comment by jakub-gonet** [comment]
This is expected when RN complains about handler not being registered 🙂 
Try using refs when passing Values around.
And as I said, can't help you much more without code.

**Comment by jakub-gonet** [comment]
Hi!
This issue was inactive for a while, so I'm closing it.
If you still face this problem don't hesitate to ask.

**Comment by Shiva207892** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-07-13 at 11 27 19](https://user-images.githubusercontent.com/59263070/178661209-756ba2c8-0adf-49d6-8b59-8ef6e61fd250.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-13 at 11 29 11](https://user-images.githubusercontent.com/59263070/178661434-d9e71e0f-8ba5-4fb4-a335-7164c60668fe.png)


Any suggestion to get rid of this warning , the warning comes when I click on top right drawer toggle button. And I have used nested navigators in this project like stack inside drawer and drawer inside stack

**Comment by gylychmedov** [comment]
@Shiva207892, how to fix error?
<img width="375" alt="Screen Shot 2022-07-17 at 20 18 01" src="https://user-images.githubusercontent.com/78946365/179405087-7ab57252-b1c0-4002-a349-d75c4a578f32.png">
<img width="554" alt="Screen Shot 2022-07-17 at 20 23 03" src="https://user-images.githubusercontent.com/78946365/179405144-4f18e0c6-5e9a-4fff-8521-a4a21ce37a68.png">

**Comment by hadnet** [comment]
Same error as above, @Shiva207892 did you find a solution?

**Comment by kevinchristianto** [comment]
I'm having the same issue with react-native-reanimated@3.0.0-rc.2, any solution?

**Comment by andreaPortfolio** [comment]
The same with  react-native-reanimated@3.0.0-rc.3 and react native 0.70.0 and  "@react-navigation/native": "^6.0.12"

**Comment by rayaladev** [comment]
Yes me too, the same with react-native-reanimated@3.0.0-rc.3 and react native 0.70.0, using Drawer 6.5.0

**Comment by SkylerB1** [comment]
Anyone able to solve this warning?? I got this after implementing drawer inside my app with react-native-reanimated@3.0.0-rc.3, react-native 0.70.0 and drawer 6.5.0.

**Comment by lorenjohnson** [comment]
Same, seemed I needed to get up to the release candidates for things to build right for me on RN 0.70.x. Can't remember the reasons right now, but didn't find much of an alternative. As it is I am getting this warning and some strange behaviors related to React Navigation animations and suspect it to be something going on here. So not much help yet, but watching 👀
