### ISSUE TITLE
Is there a way to mount a component when animation starts, and unmount it when animation ends?

### ISSUE THREAD

**Issue by lake2** [software-mansion/react-native-reanimated#778]
Is there a way to mount a component when animation starts, and unmount it when animation ends?

**Comment by jakub-gonet** [comment]
Hi @lake2,

you can use call node to do that:
let's suppose you have component `<A />` which will be mounted and unmounted.

Then you'll write something like that in your component:
```js
[visible, setVisible] = useState(true);

return ({visible && <A />});
```

and somewhere in the animation:
```js
call([animationStateChange], ()=>setVisible(!visible))
```
where `animationStateChange` is flag set at start of animation and unset on end


Does it make sense to you?

**Comment by lake2** [comment]
> Hi @lake2,
> 
> you can use call node to do that:
> let's suppose you have component `<A />` which will be mounted and unmounted.
> 
> Then you'll write something like that in your component:
> 
> ```js
> [visible, setVisible] = useState(true);
> 
> return ({visible && <A />});
> ```
> 
> and somewhere in the animation:
> 
> ```js
> call([animationStateChange], ()=>setVisible(!visible))
> ```
> 
> where `animationStateChange` is flag set at start of animation and unset on end
> 
> Does it make sense to you?

thanks. I will try this

**Comment by jakub-gonet** [comment]
Cool, if you have any further questions don't hesitate to ask.

I will close this issue for now.
