### ISSUE TITLE
Unsupported node type : param

### ISSUE THREAD

**Issue by jeanschneider** [software-mansion/react-native-reanimated#781]
## Description

The app crashes on start with the error "Unsupported node type : param

### Screenshots

![image](https://user-images.githubusercontent.com/46921251/81213920-6694f480-8fd7-11ea-999e-b990d7036e40.png)

## Steps To Reproduce

1. Open the app 

### Expected behavior

The app starts on Home screen

### Actual behavior

The app crashes

## Package versions

- React: "16.8.3",
- React Native: "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
- React Native Reanimated: "^1.4.0"

Thanks :)

**Comment by jakub-gonet** [comment]
Hi @jeanschneider,

can you provide code for your app, preferably on [snack](https://snack.expo.io/)? I'm afraid I can't help you without that.

**Comment by jeanschneider** [comment]
Hello, 
Thanks for your response.
I tried importing the code to snack but infortunately it doesn't work (there are so many other errors probably happenning before this one). 
Anyway here is the code : https://snack.expo.io/@jschneider/appli-matos

I saw there is an issue for the same problem opened on the react github and on stackoverflow. It seems like it suddenly happened (no changes have been made to the code, just opened it a few days later and it wasn't working anymore). On stackoverflow, the guy solved it by downgrading to 1.4.0. It didn't solved the issue for me

**Comment by jakub-gonet** [comment]
Oh, this is a huge repro 😄
I can't really debug on this one, please try submitting some smaller repro.
I think this may be related to react-navigation which uses reanimated in such a way that triggers this error

You can try checking if NodesManager.java in reanimated java sources from node_modules contains `else if ("param".equals(type)`. In your app, it throws an exception on line 277. This error is strange because on line 270 we check for param type, so it shouldn't be happening

**Comment by jeanschneider** [comment]
Yeah, it's a decent sized project !

Okayyy so latest updates  ! I realized the downgrade did not work (bcz of expo cache, so dumb I did not think about this one 🤬). Now that I downgraded reanimated to 1.4.0, it starts again !

**Comment by jakub-gonet** [comment]
Alright, I'll close this one for now in that case, because it's probably related to proc changes in 1.4 and we're aware of this problem. If you provide smaller repro I'm happy to reopen

**Comment by SomnathKadam** [comment]
steps for windows machine:

1. Delete .expo and node_modules folder
2. run command `npm install react-native-reanimated@1.4.0`
3. run command for clear expo cache, `expo r -c`
