### ISSUE TITLE
Cannot set RCTScrollView.scrollEnabled property using Reanimated API

### ISSUE THREAD

**Issue by handlerug** [software-mansion/react-native-reanimated#783]
## Description

Consider the following piece of code:

```jsx
<Animated.ScrollView
  scrollEnabled={cond(/* ... */, true, false)}>
  {/* ... */}
</Animated.ScrollView>
```

When I try to run it, Reanimated API tries to set scrollEnabled to some kind of Double (0f and 1f I think?) instead of boolean and fails with exception below.

### Screenshots

![Screenshot_20200507_113359_com rntest](https://user-images.githubusercontent.com/24986597/81255149-21b0a280-9057-11ea-8f05-6d34f4f3f0a0.jpg)

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 1.8.0

**Comment by jakub-gonet** [comment]
Hi @handlerug,

this is a current limitation of reanimated:
we convert every value from javascript to double internally, so Java can't handle this conversion.

As a workaround, you can use `call` node and `useState` but this will, unfortunately, rerender component.

**Comment by handlerug** [comment]
That's pretty sad :( As far as I know, Reanimated API supports strings (there was PR adding this functionality in this repo), and supporting booleans would be great too. Or this is a limitation of JS Animated.* nodes API?

**Comment by handlerug** [comment]
Oh, sorry for such a stupid question, I didn't read your reply carefully enough 🤦‍♂️

**Comment by yasintz** [comment]
Hi @handlerug,

> this is a current limitation of reanimated:
> we convert every value from javascript to double internally, so Java can't handle this conversion.

This does not provide native performance. Why is boolean not supported?

**Comment by jakub-gonet** [comment]
Reanimated mostly focus on animating styles where most of the values are string or double and that's how we manage it on the native side. Props support is merely a side-effect and wasn't really considered when Rea v1 was written. You can try Reanimated v2 which has a simpler API and should support animating styles and props with every value that JS supports (including arrays, objects, arrays, functions, etc).

Here's a link to the docs. On the main page, you'll find blog posts as well.
https://docs.swmansion.com/react-native-reanimated/docs/next#library-overview

**Comment by yasintz** [comment]
I found a different way for this. Enclose your list with `Animated.View` and send a props to this view.
`pointerEvents={Animated.cond(condition, 'auto', 'none')}`

Example:
```tsx
<Animated.View pointerEvents={Animated.cond(isActiveNode, 'auto', 'none')}>
   <Animated.ScrollView>
      ...
   </Animated.ScrollView>
</AnimatedView>

```

**Comment by 404-html** [comment]
Thanks for that @yasintz, very helpful 🙌
