### ISSUE TITLE
Why do we format double values?

### ISSUE THREAD

**Issue by heroic** [software-mansion/react-native-reanimated#785]
## Description

https://github.com/software-mansion/react-native-reanimated/blob/master/android/src/main/java/com/swmansion/reanimated/nodes/ConcatNode.java#L30

Why are doubles formatted, instead of simply being `String.valueOf`? If the goal is truncating them, then we should add `sFormatter.setGroupingUsed(false);`

Without this reanimated can't properly make SVG Paths. If there is no other reason for this, I can submit a PR to fix this

**Comment by jakub-gonet** [comment]
We use formatter to recreate behavior from IOS - we don't print decimal fraction when number can be represented as integer.

We also set grouping here
https://github.com/software-mansion/react-native-reanimated/blob/7876df5aaa781ff310549e626fa3d128a24eee96/android/src/main/java/com/swmansion/reanimated/nodes/ConcatNode.java#L15

But this isn't yet released, so 1.8 has problems with that.
