### ISSUE TITLE
Issue with call( calling setstate working only once and break the animation

### ISSUE THREAD

**Issue by djaoui** [software-mansion/react-native-reanimated#789]
## Description
I built the animation below in a Class Component.
Changing a state through call([], this.setState({****)) will work once and then will prevent the animated proc() to run ever again.

## Steps To Reproduce

1. Open the snack
2. Perform a drag movement of more than 5 sec several time and release

### Expected behavior
step 1 - A round view should progressively appear under pointer and the red box "Screen not Touched" should change color for skyblue and text should also changed inside the box to "screen not touched".

step 2 - On release, the view will desopacify until disappering and the box will revert back to red and the message to "screen not touched"

step 3 - Step 1 and 2 should be able to be repeated as will

### Actual behavior
When call() has been executed in and out, the animated function stops being accessible.
When call() is commented out the animated function remains accessible,

## Snack or minimal code example
https://snack.expo.io/@djaoui/screentouchtracker

## Package versions

- Expo 37.0.3
- React: 16.9.0
- React Native: 37.0.1
- React Native Reanimated: 1.7.0

**Comment by jakub-gonet** [comment]
Hi @djaoui,

I believe you forgot to add snack URL here 🙂

**Comment by djaoui** [comment]
> 
> 
> Hi @djaoui,
> 
> I believe you forgot to add snack URL here 🙂

Hi @jakub-gonet , I pasted things inside the comment brackets lol.

Edited and corrected now. Thanks for the heads up !
