### ISSUE TITLE
Question regarding backwards compatibility with vanilla Animated API

### ISSUE THREAD

**Issue by sankhadeeproy007** [software-mansion/react-native-reanimated#792]
## Description

The docs say that reanimated is backwards compatible with the vanilla Animated API and it uses nativeDeriver by default. So can I use Animated from reanimated the same way as vanilla  animated and still get the improved performance?

## Code

```
import Animated, {
  Value,
  Easing
} from 'react-native-reanimated';

Animated.timing(animatedValue, {
      toValue: 1,
      easing: Easing.ease,
      duration: 200
    }).start()

```

**Comment by jakub-gonet** [comment]
Hi @sankhadeeproy007,
except minor exceptions, Reanimated should be backwards compatible with Animated so you use it as drop-in replacement for Animated requiring little to no changes in your code.

We encourage users to use declarative API thought, you can find more information on it in the docs.

**Comment by sankhadeeproy007** [comment]
Got it. Thanks for the quick response and such a lovely library!
