### ISSUE TITLE
`defined` function gives 1 always

### ISSUE THREAD

**Issue by zarcode** [software-mansion/react-native-reanimated#793]
## Description
Docs say that `defined` should return `0` for  `Value(0)` and `Value(undefined)`, but it's not. It always return `1`.

***Note:*** This leads to unexpected behaviour on `diffClamp` function.
 
```
  useCode(
    () =>
      block([
        debug("test", defined(new Value())),
        debug("test2", defined(new Value(undefined))),
      ]),
    []
  );
```

## Steps To Reproduce

1. Try code above

### Expected behavior
`defined(new Value())` should be 0
`defined(new Value(undefined))` should be 0

### Actual behavior
`defined(new Value())` is 1
`defined(new Value(undefined))` is 1

## Snack or minimal code example
https://snack.expo.io/@zarcode/defined

## Package versions
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.8.0",

same with 
"react-native-reanimated": "~1.7.0",

- React:
- React Native:
- React Native Reanimated:

**Comment by jakub-gonet** [comment]
According to docs `defined(new Value(0))` should return 1, but you're right, undefined gives wrong value, because we're holding 0 instead of `undefined` internally.
