### ISSUE TITLE
Math errors with modulo on iOS

### ISSUE THREAD

**Issue by levibuzolic** [software-mansion/react-native-reanimated#797]
## Description

When using `modulo` with certain values, the result appears to be incorrect. I haven't worked out what the pattern is for values that cause this behaviour, and the bug only appears to exist on iOS. Reanimated, Android and Web appear to behave correctly.

As an example, the operation `9999999999 % 10 === 9` in JS. In Reanimated `modulo(new Value(9999999999), 10) === 9` on web and Android. However on Reanimated iOS I get a result of `0`.

Initially I thought this might have been an issue with being above max 32bit int, but that doesn't appear to be the case as some numbers give the correct result, while some values much smaller than max int do not.

### Screenshots

Reanimated Web | Reanimated Android | Reanimated iOS
---|---|---
`9` | `9` | `0`
![image](https://user-images.githubusercontent.com/721323/82626386-059e2b00-9c2b-11ea-8362-a2d6cee660e0.png) | ![image](https://user-images.githubusercontent.com/721323/82626592-9412ac80-9c2b-11ea-9aaf-8381fd7a8b11.png) | ![image](https://user-images.githubusercontent.com/721323/82626649-aee52100-9c2b-11ea-8bb8-df43e3dd4b5a.png)

## GIF from iOS

This GIF shows some of the unusual results that are given from my [expo snack](https://snack.expo.io/@levibuzolic/reanimated-math). Values appear to be mostly incorrect when the start value is `9999999999` (or a similarly large number) but setting the value to `1234567` and then gradually increasing the value, the result appears to be correct, even when exceeding a value of `9999999999`.

The left-hand side is pure JS (`value % 10`) while the right side is the result from reanimated (`modulo(animatedValue, 10)`).

![RPReplay_Final1590116531](https://user-images.githubusercontent.com/721323/82627412-b4dc0180-9c2d-11ea-8928-a3bf4a96a900.gif)

## Snack or minimal code example

https://snack.expo.io/@levibuzolic/reanimated-math

```js
import * as React from 'react';
import Animated from 'react-native-reanimated';
import { ReText } from 'react-native-redash';
const { concat, Value, modulo } = Animated;
const { useRef } = React;

export default function App() {
  const { current: animValue } = useRef(new Value(9999999999));
  return <ReText text={concat('', modulo(animValue, 10))} />;
}
```

## Package versions

For the sample app I've tested in Expo 37.0.0 (which I believe uses Reanimated 1.70)

The issue also exists in my current production app running:
- React: 16.9.0
- React Native: 0.61.5
- React Native Reanimated: 1.8.0

**Comment by levibuzolic** [comment]
Looking into this further with the help of @deecewan, it appears to be an issue with using single precision floats as `9999999999` cannot be safely represented as a float, so in iOS `9999999999` will end up being `10000000000` which will `fmodf` to `0`.

This _might_ be an issue specific to targeting non-64-bit architectures as the reanimated code looks to be using doubles, but `CGFloat` might downcast to a 32-bit float.

**Comment by deecewan** [comment]
yeah, from [here](https://developer.apple.com/documentation/coregraphics/cgfloat) it looks like if you're targeting a 32-bit architecture, `CGFloat` downcasts to a float instead of a double 😞

**Comment by jakub-gonet** [comment]
Hi @lebedev,
thanks for the detailed description.

We use `CGFloat` in [Operator node code](https://github.com/software-mansion/react-native-reanimated/blob/master/ios/Nodes/REAOperatorNode.m#L23-L24) and it downcasts to floats as @deecewan mentioned. We should use there plain `double` like in Android implementation. I'll prepare a PR.

Thanks!
