### ISSUE TITLE
Random operator

### ISSUE THREAD

**Issue by headfire94** [software-mansion/react-native-reanimated#801]
## Description

Is it possible to add random operator? I would like to change `config.toValue` in loop animation on each cycle with `Math.random()`? Is it any workaround to achive random animated value?

**Comment by jakub-gonet** [comment]
Hi @headfire94,

this is a bit unusual usage of reanimated and we don't have any node dedicated to evaluating to a random value.

You can try using clocks as values - run clock for some time, stop it, use its value to run itself for some time, use this value as random. It probably would be good enough.

You can also try using [Linear-feedback shift register](https://en.wikipedia.org/wiki/Linear-feedback_shift_register), but we don't have XOR, so you would have to come up with your own linear function.

If you don't need performance, you can use `call` node with `Math.random()` and call it a day 🙂 

BTW, can you describe your use case? Maybe it can be done by some other means?

**Comment by headfire94** [comment]
> BTW, can you describe your use case? Maybe it can be done by some other means?

Hi @jakub-gonet,
I would like to move element with random direction each second
For example:
1 cycle: from coordinates [0,0] to [50, 30]
2 cycle: from [50,30] to [20, 70]
and so on where coordinates inside box 100x100.

**Comment by jakub-gonet** [comment]
I see, try using one of the following then:
- `call` node with `Math.random()`
- some basic implementation of polynomial PRNG
- precomputing table of random values in JS side

I don't think your use case is that common and we're recently released Reanimated 2, which will solve this problem (you can use `Math.random` directly).

I'm open for discussion though.
