### ISSUE TITLE
Crash in RTL devices

### ISSUE THREAD

**Issue by club9822** [software-mansion/react-native-reanimated#808]
## Description
Copy pasted example from this repo for rotate and translate
every thing work fine in debug and release mode for android.

if language of device change to Arabic (RTL) crashes in Release mode or error in Debug

```
after investing in find out problem caused with type conversion
example : can not convert "۰" to "0". 
۰ is arabic number==zero
```
## Steps To Reproduce

1.  run this repo example in RTL device(Arabic Language or..) 

### Expected behavior
run animation exactly same as ltr device
### Actual behavior
crash in rtl mode

## Package versions

```
"dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-reanimated": "^1.7.0",
    "react-native-gesture-handler": "^1.6.0"
  }
```

**Comment by jakub-gonet** [comment]
Hi @club9822,

can you provide a link to the example which crashes? I was unable to reproduce this.

**Comment by jakub-gonet** [comment]
Hi @club9822,

(I removed prev comment because I tested it in iOS)
I couldn't reproduce this crash on android, can you add [snack](https://snack.expo.io/) with code that doesn't work or provide a link to the exact example which crashes?

**Comment by club9822** [comment]
@jakub-gonet thank u for attention

i copy pasted example from this link 
```https://docs.swmansion.com/react-native-reanimated-docs/declarative-animation-api.html```

every thing works fine in rlt devices. but crash in rtl devices

```
import React from 'react';
import {View,Text,StyleSheet} from 'react-native';
import Animated, { Easing } from 'react-native-reanimated';

const {
  Clock,
  Value,
  set,
  cond,
  startClock,
  clockRunning,
  timing,
  debug,
  stopClock,
  block,
} = Animated;

function runTiming(clock, value, dest) {
  const state = {
    finished: new Value(0),
    position: new Value(0),
    time: new Value(0),
    frameTime: new Value(0),
  };

  const config = {
    duration: 5000,
    toValue: new Value(0),
    easing: Easing.inOut(Easing.ease),
  };

  return block([
    cond(
      clockRunning(clock),
      [
        // if the clock is already running we update the toValue, in case a new dest has been passed in
        set(config.toValue, dest),
      ],
      [
        // if the clock isn't running we reset all the animation params and start the clock
        set(state.finished, 0),
        set(state.time, 0),
        set(state.position, value),
        set(state.frameTime, 0),
        set(config.toValue, dest),
        startClock(clock),
      ]
    ),
    // we run the step here that is going to update position
    timing(clock, state, config),
    // if the animation is over we stop the clock
    cond(state.finished, debug('stop clock', stopClock(clock))),
    // we made the block return the updated position
    state.position,
  ]);
}

export default class AnimatedBox extends Component {
  // we create a clock node
  clock = new Clock();
  // and use runTiming method defined above to create a node that is going to be mapped
  // to the translateX transform.
  transX = runTiming(this.clock, -120, 120);

  render() {
    return (
      <View style={styles.container}>
        <Animated.View
          style={[styles.box, { transform: [{ translateX: this.transX }] }]}
        />
      </View>
    );
  }
}

const styles=StyleSheet.create({
  styles:{flex:1}
})```

```
 "react": "16.11.0",
 "react-native": "0.62.2",
"react-native-reanimated": "^1.7.0",```

**Comment by jakub-gonet** [comment]
@club9822 

I wasn't able to reproduce this issue:
![image](https://user-images.githubusercontent.com/12465392/83414713-40b80f80-a41e-11ea-917f-d563e5088b0f.png)

![image](https://user-images.githubusercontent.com/12465392/83414723-457cc380-a41e-11ea-85be-28e1d6484930.png)

Could you provide an example you're using with "۰"? Your current example doesn't mention it anywhere.

BTW, you have a typo in `TouchableOpacity`

**Comment by anastely** [comment]
Hey @jakub-gonet 

I've faced the same issue in Android,
I don't know if it related in reanimated lib or react native core, 
But if you change your mobile language to **Arabic** Not Hebrew you will face it 

For example in this snippet code

```
return (
      <View style={styles.handlerContainer}>
        <AnimatedView
          style={[
            styles.handlerBar,
            {
              left: -7.5,

              transform: [
                {
                  rotate: Animated.concat(
                    animatedBar1Rotation([0.5, 0]),// crash here 0.5 it will turned to ٠.٥ in Arabic language so that's the reason of crash 
                    'rad',
                  ),
                },
              ],
            },
          ]}
        />
        <AnimatedView
          style={[
            styles.handlerBar,
            {
              right: -7.5,
              transform: [
                {
                  rotate: Animated.concat(
                    // @ts-ignore
                    animatedBar1Rotation([-0.5, 0]), // crash here -0.5 it will turned to -٠.٥ in Arabic language so that's the reason of crash 
                    'rad',
                  ),
                },
              ],
            },
          ]}
        />
      </View>
    );
```

Error
```
JSApplicationIllegalArgumentException
Error while updating property 'transform' of a view managed by: RCTView


```

**Comment by anastely** [comment]
Hey @jakub-gonet 

I've faced the same issue in Android,
 if you change your mobile language to **Arabic** you will face it 

For example in this snippet code

```
import Animated from 'react-native-reanimated';

const AnimatedView = Animated.View;

return (
      <View style={styles.handlerContainer}>
        <AnimatedView
          style={[
            styles.handlerBar,
            {
              left: -7.5,

              transform: [
                {
                  rotate: Animated.concat(
                    animatedBar1Rotation([0.5, 0]),// crash here 0.5 it will turned to ٠.٥ in Arabic language so that's the reason of crash 
                    'rad',
                  ),
                },
              ],
            },
          ]}
        />
        <AnimatedView
          style={[
            styles.handlerBar,
            {
              right: -7.5,
              transform: [
                {
                  rotate: Animated.concat(
                    // @ts-ignore
                    animatedBar1Rotation([-0.5, 0]), // crash here -0.5 it will turned to -٠.٥ in Arabic language so that's the reason of crash 
                    'rad',
                  ),
                },
              ],
            },
          ]}
        />
      </View>
    );
```

Error
```
JSApplicationIllegalArgumentException
Error while updating property 'transform' of a view managed by: RCTView

null
For input string: "٠"  // that's is **Zero** in Arabic Not **Dot** 
```

**Comment by club9822** [comment]
> @club9822
> 
> I wasn't able to reproduce this issue:
> ![image](https://user-images.githubusercontent.com/12465392/83414713-40b80f80-a41e-11ea-917f-d563e5088b0f.png)
> 
> ![image](https://user-images.githubusercontent.com/12465392/83414723-457cc380-a41e-11ea-85be-28e1d6484930.png)
> 
> Could you provide an example you're using with "۰"? Your current example doesn't mention it anywhere.
> 
> BTW, you have a typo in `TouchableOpacity`
@jakub-gonet 
I have tested this and it work on Hebrew but crashes in Arabic or Persian. 
Sorry for misguide

**Comment by jakub-gonet** [comment]
I believe this issue was related to using locale when formatting AnimatedValues, but I wasn't able to find the exact place responsible for it. 

From 1.9.0 we're formatting values in `concat` node based on EN_US locale, so it's should be working just fine.

If it isn't, please let me know.

**Comment by anastely** [comment]
@jakub-gonet Yes it works with me in 1.9.0
