### ISSUE TITLE
Using set in proc

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#809]
## Description

Using set in proc does not set the value (inside the proc function)

### Expected behavior

To display:
```
before a 1.0
before b 10.0
in b 1.0
in a 3.0      <=
after a 3.0
after b 1.0
```

### Actual behavior

To display:
```
before a 1.0
before b 10.0
in b 1.0
in a 1.0      <=
after a 3.0
after b 1.0
```

## Snack or minimal code example

```
const testProc = proc((a, b) => block([
    set(b, a),
    debug('in b', b),
    set(a, add(b, 2)),
    debug('in a', a)
]))

const a = new Animated.Value(1)
const b = new Animated.Value(10)

useCode(() => [
    debug('before a', a),
    debug('before b', b),
    testProc(a, b),
    debug('after a', a),
    debug('after b', b)
], [])
```

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 1.9.0

**Comment by jakub-gonet** [comment]
It seems that this bug only shows up when you reference other variable in `set` node.
