### ISSUE TITLE
I got an error using the library in react-native0.62.0 and asked for help

### ISSUE THREAD

**Issue by KGDeveloper** [software-mansion/react-native-reanimated#810]
When I ran the APP on iOS, everything was fine, but when I switched to Android, there was an error,
```
info Opening /Users/bszh/Desktop/RN_HJ/node_modules/react-native-reanimated/src/core/AnimatedNode.js with code
error spawn code ENOENT
```
I was very confused, so I searched and found the location and method of error reporting, but I didn't know how to modify and solve this problem

Under the path of the error log, I found the method of error reporting. The following is the source code of the library

```
 __nativeInitialize() {
    if (!this.__initialized) {
      ReanimatedModule.createNode(this.__nodeID, { ...this.__nodeConfig });
      this.__initialized = true;
    }
  }
```

**Comment by KGDeveloper** [comment]
sorry，please close this error

**Comment by jakub-gonet** [comment]
Closing as requested.

By the way, you can close your issues by yourself.
