### ISSUE TITLE
Unable to set state in call()

### ISSUE THREAD

**Issue by learner004** [software-mansion/react-native-reanimated#812]
I'm trying to update the state when there is a change in the animated value. I'm using call() to check for updates in the animated value and using the callback to set state. This doesn't seem to be working for some reason and it breaks the animation. Replacing the set state with console.log() i see that call() is capturing updates in the animated values. What am i doing wrong?
 var loc = new Value(0);

const [slideValue, setslideValue] = React.useState(0);

useCode(() =>
    call([loc], ([slide]) => {
     setslideValue(slide);
    }),
  );

**Comment by jakub-gonet** [comment]
Hi @learner004,

bear in mind that setting new state rerenders component which causes Reanimated nodes to detach and reattach - animation state resets.

**Comment by learner004** [comment]
Duplicate of Issue #789

**Comment by learner004** [comment]
Hi @jakub-gonet, 

 I had stored reanimated node as normal variable. As you pointed out, state change caused it to detach and reattach. Setting the reanimated node as state solved the issue for me. Thanks for the tip.

**Comment by jakub-gonet** [comment]
Using memo / refs are more common in reanimated, just pointing out. And if you use master version you can try using useValue (or copy it from the repo) to avoid creation of unnecessary reanimated nodes, when function arguments are evaluated at each rerender.
