### ISSUE TITLE
The inside code of <Animated.Code> is always executed when render runs

### ISSUE THREAD

**Issue by gaishimo** [software-mansion/react-native-reanimated#814]
## Description

The inside code of `<Animated.Code>` is always executed when `render` runs.
This happens in version 1.5 and above. (doesn't happen in version 1.4)

Please let me know if my code has some problems or there are any effective workarounds.

### Screenshots

| version 1.4 | version 1.5 and above |
|:---:|:-----:|
| <img src="https://user-images.githubusercontent.com/4277693/83129884-6d1b1580-a118-11ea-9ccf-fe969219bae3.gif"  width="220" /> | <img src="https://user-images.githubusercontent.com/4277693/83130038-a5baef00-a118-11ea-8a37-ca1d3cb1f33e.gif"  width="220" /> |

## Steps To Reproduce

Run this example Expo app on iOS or Android and drag the shape.
https://github.com/gaishimo/rn-gesture-with-renimated/

### Expected behavior

The inside code of `<Animated.Code>` should be executed only once.

https://github.com/software-mansion/react-native-reanimated/blob/9ab83d8f601c0280580e1a47794aa20d32e45f0b/docs/pages/09.code.md

> Note that the code you put is going to be executed only once. We currently have no way of telling if your code changes and so it will only be run in componentDidMount. If you wish for your reanimated nodes to be updated when the component updates, you can update the key property of the Animated.Code component, which will effectively unmount old and mount new versions of it in the React tree.

### Actual behavior

The inside code of `<Animated.Code>` is always executed when `render` runs. 

## Snack or minimal code example

https://github.com/gaishimo/rn-gesture-with-reanimated/blob/master/App.tsx#L74-L98

## Package versions

- React: 16.9.0
- React Native: 0.61 
- React Native Reanimated: 1.5 and above

**Comment by jakub-gonet** [comment]
This may be the same issue as #570

**Comment by jakub-gonet** [comment]
This should be resolved in master (most likely by [this commit](https://github.com/software-mansion/react-native-reanimated/commit/61ff5823c674191a2930fc199a85231e434a0373)).
