### ISSUE TITLE
Animated.set first argument should be of animatedNode

### ISSUE THREAD

**Issue by linusnyren** [software-mansion/react-native-reanimated#815]
## Description
Im trying to implement the instagram type of animations when transitioning as seen here 
https://www.youtube.com/watch?v=83GNiMp-qq0&list=PLdEgTN0HyxUJTFfZ3maa9PF6ncVxeYMAZ&index=2&t=1s

but i get this error even if i´ve practically copied the entire thing since its perfect for my project.
Reanimated: Animated.set first argument should be of type AnimatedNode but got undefined
## Code
my imports
```js
import Animated, {
    Extrapolate,
    and,
    block,
    call,
    cond,
    eq,
    interpolate,
    set,
    useCode,
  } from "react-native-reanimated";
  import { PanGestureHandler, State } from "react-native-gesture-handler";
  import {
    onGestureEvent,
    snapPoint,
    timing,
    useValues,
  } from "react-native-redash";
  import { useMemoOne } from "use-memo-one";
```
code
```js
const {goBack} = navigation
    const [
        translationX,
        translationY,
        velocityY,
        translateX,
        translateY,
        snapBack,
        state,
      ] = useValues([0, 0, 0, 0, 0, 0, State.UNDETERMINED]);
      const snapTo = snapPoint(translationY, velocityY, [0, height]);
      const scale = interpolate(translateY, {
        inputRange: [0, height / 2],
        outputRange: [1, 0.75],
        extrapolate: Extrapolate.CLAMP,
      });
      const gestureHandler = useMemoOne(
        () => onGestureEvent({ translationX, translationY, velocityY, state }),
        [state, translationX, translationY, velocityY]
      );
      useCode(
        () =>
          block([
            cond(
              and(eq(state, State.END), eq(snapTo, height), eq(snapBack, 0)),
              set(snapBack, 1)
            ),
            cond(
              snapBack,
              call([], () => goBack()),
              cond(
                eq(state, State.END),
                [
                  set(
                    translateX,
                    timing({ from: translationX, to: 0, duration: 250 })
                  ),
                  set(
                    translateY,
                    timing({ from: translationY, to: 0, duration: 250 })
                  ),
                ],
                [set(translateX, translationX), set(translateY, translationY)]
              )
            ),
          ]),
        []
      );
    return (
        <View style={{flex:1}}>
        <PanGestureHandler {...gestureHandler}>
        <Animated.View
          style={{
            flex: 1,
            backgroundColor: "white",
            transform: [{ translateX }, { translateY }, { scale }],
          }}
        >
//then regular views following here
```

### Package versions

- React: 16.9.0
- React Native: sdk 36 expo
- React Native Reanimated:1.9.0

**Comment by jakub-gonet** [comment]
Hi @lindesvard,

could you please include stack trace (screenshot / text)? It would be really helpful.

**Comment by linusnyren** [comment]
Of course!
Reanimated: Animated.set first argument should be of type AnimatedNode but got undefined
- node_modules/react-native-reanimated/src/core/AnimatedSet.js:10:27 in constructor
- node_modules/react-native-reanimated/src/core/AnimatedSet.js:36:16 in createAnimatedSet
* components/RentItemComponents/RentItem.js:300:8 in useCode$argument_0
* http://192.168.0.12:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:154140:29 in <unknown>
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:16921:31 in commitHookEffectList
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:16970:29 in commitPassiveHookEffects
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20061:28 in flushPassiveEffectsImpl
* [native code]:null in flushPassiveEffectsImpl
- node_modules/scheduler/cjs/scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18920:21 in renderRoot
* [native code]:null in renderRoot
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18709:28 in runRootCallback
* [native code]:null in runRootCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
- node_modules/scheduler/cjs/scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18796:28 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2709:30 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2794:17 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2814:26 in receiveEvent
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by jakub-gonet** [comment]
This error shows because any of `translateX`, `translateY`, or `snapBack` is undefined (you didn't include the line with `set()` that throws, so hard to say which of them).

Maybe `useValues` function has a bug? Try creating those `Values` manually and see if it still throws. It seems you don't have any typos, so I don't really know what else could be happening. 

Please provide a [snack](https://snack.expo.io/) with a minimal reproducible example as well, this will really help me help you 😄

**Comment by linusnyren** [comment]
Hi Jakub!
You were correct, it was the useValues function that didnt assign the values properly, changed them to useValue and it worked right away.
I´m not getting the transform animation though, it´s just the regular back animation with fading.
Any ideas?

**Comment by jakub-gonet** [comment]
Hard to say, please make a [snack](https://snack.expo.io/) so I can view and test your code easily.

**Comment by eshraj302** [comment]
Hey There!, I am also Stuck with the same problem, Any Updates to the solution?

**Comment by jakub-gonet** [comment]
@eshraj302, please provide your code in [snack](https://snack.expo.io/).

We can't help you without code which crashes.

**Comment by jakub-gonet** [comment]
Closing due to no response.

**Comment by MoeMamdouh** [comment]
its happens to me when i update `react-native-redash` lib

**Comment by daongochieu2810** [comment]
this seems to be a bug from `react-native-redash`. I used useValue instead of useValues and it works again

**Comment by MoeMamdouh** [comment]
Changing the `useValues([0, 0, 0, 0])` to `useValues(0, 0, 0, 0)`
