### ISSUE TITLE
Animated cond doesn't work

### ISSUE THREAD

**Issue by headfire94** [software-mansion/react-native-reanimated#820]
## Description
`Animated.cond` returns wrong value when I change `activeSlide` by `Animated.set(activeSlide,2)` (condition is still true and it uses interpolate)

```
this.slideOpacityFirst = cond(
      eq(activeSlide, 1),
      interpolate(abs(this.translateX), {
        inputRange: [0, REAL_WIDTH],
        outputRange: [1, 0],
      }),
      0
    );
```

## Steps To Reproduce
On IOS or Android:
1. Swipe view to the left, interpolation works fine and view moves to the left and hides with opacity
2. After animation finishes, view comes back to the initial state

### Expected behavior
View should be hidden because `slideOpacityFirst` should return `0` after `activeSlide` changes

### Actual behavior
View is visible even if `activeSlide = 2` (but it changes immediately if you try to swipe once again)
## Snack or minimal code example

Example in snack https://snack.expo.io/@egorvodopyanov/cond

## Package versions

v1.9.0

**Comment by headfire94** [comment]
`Animated.debug('test slide', activeSlide)` doesn't work in snack, but it shows `2` in local project

**Comment by headfire94** [comment]
Is there a way how can i debug native code to understand how it works and why node doesn't react on `activeSlide` changes?

**Comment by jakub-gonet** [comment]
Hi @headfire94,

I reproduced it locally, I'll try to narrow it down bc I don't yet know what can be causing this.

You can debug native code by using XCode, I don't have experience on debugging android though.

**Comment by jakub-gonet** [comment]
I tried to investigate it a little bit and it seems that's a problem with reevaluation order somewhere in conds managing touch events.

If you manage to simplify this code to show the problem clearly please reply. For now, I'm closing it as repro is too complex.
