### ISSUE TITLE
Can't find variable: setImmediate

### ISSUE THREAD

**Issue by emroot** [software-mansion/react-native-reanimated#824]
## Description
I'm using `setImmediate` with `expo`, `react-native`, and `next.js` for the web client.
When I build my project for the web, any page using `react-native-reanimated` works fine on Chrome (after I added a [polyfill](https://github.com/yuzujs/setImmediate#readme)), works on the first load on Safari, but not on subsequent page reloads. I get `Can't find variable: setImmediate` error. Only happens when I run a production build.
`Next.js` disabled `setImmediate` back in Feb. https://github.com/vercel/next.js/pull/10612 
Curious if there could be another alternative instead of  `setImmediate` that could be used [here](https://github.com/software-mansion/react-native-reanimated/blob/ad5606566413545abed89b66631ab156e9f3d624/src/core/AnimatedNode.js#L138).
The mozilla website says this regarding the use of `setImmediate`: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate
> **Non-standard**
This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

### Screenshots
![image](https://user-images.githubusercontent.com/110190/83227998-45d54000-a13a-11ea-92b1-3ed77236a427.png)

## Steps To Reproduce

1. Create an expo/next.js project
2. install `react-native-reanimated`
3. Build a production build
4. Run in Safari/Chrome and observe.

### Expected behavior

It shouldn't trigger `setImmediate is not defined` error.

### Actual behavior

It triggers `setImmediate is not defined`

## Snack or minimal code example

Can provide this tomorrow.

## Package versions

- React: ~16.9.0
- React Native: ~0.61.5
- React Native Reanimated: ^1.9.0
- Expo: ^37.0.8
- Next: ^9.4.4

**Comment by emroot** [comment]
Actually, ignore this. I found a way to inject the polyfill right before I make my call to `react-native-reanimated`, lower down the chain instead of `pages/_app.tsx` and it fixes the issue.

**Comment by pleaseshutup** [comment]
> Actually, ignore this. I found a way to inject the polyfill right before I make my call to `react-native-reanimated`, lower down the chain instead of `pages/_app.tsx` and it fixes the issue.

Please tell me how you did it!!!
