### ISSUE TITLE
install instructions for expo project

### ISSUE THREAD

**Issue by vamshi9666** [software-mansion/react-native-reanimated#825]
## Description

How to install reanimated2  in an expo project ?

I see some native file changes for installing, which can't be possible in an expo project.

**Comment by FLGMwt** [comment]
From [twitter](https://twitter.com/notbrent/status/1266050802025521152):

> we're holding off on including it in sdk 38 because a blocker is that reanimated 2 only supports hermes at the moment and we haven't shipped support for that in expo managed apps yet (for a variety of reasons, but we're hoping to in sdk 39 or 40)
Brent (@.notbrent)

**Comment by jakub-gonet** [comment]
As well as the second last point [here](https://docs.swmansion.com/react-native-reanimated/docs/about/#known-problems-and-limitations)

> Expo support is not ready yet, next SDK release will support React Native 0.62 – this will allow you to use Reanimated 2 in the ejected Expo app.
