### ISSUE TITLE
V2, Typescript support

### ISSUE THREAD

**Issue by dinhmai74** [software-mansion/react-native-reanimated#829]
## Description
Is this version support typescript yet? I got those warnings when import from reanimtead.
```
[tsserver 2614] [E] Module '"react-native-reanimated"' has no exported member 'useAnimatedStyle'. Did you mean to use 'import useAnimatedStyle from "react-
 from "re native-reanimated"' instead?
```

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: ^2.0.0-alpha.1

**Comment by terrysahaidak** [comment]
Unfortunately, there is no typings at the moment, but also you can't add typings to worklets right now. This is something which is on our roadmap. Stay tuned.

**Comment by jakub-gonet** [comment]
Related #840

**Comment by ReyhanFabianto** [comment]
Added in [2.0.0-alpha.3](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.3)

**Comment by terrysahaidak** [comment]
Only ability to use TS. typings are still on progress.
