### ISSUE TITLE
dissimilar behaviour between ios and android

### ISSUE THREAD

**Issue by sJJdGG** [software-mansion/react-native-reanimated#84]
I was testing this demo:
https://snack.expo.io/@codedaily/reanimatedopacitybasics
That i encountered a problem.
Simply it shows a box at the center and as long you touch it, its opacity is reduced.
On ios everything works as expected.
But on android when you press and hold on the box, after 1 second the box opacity unexpectedly increases back to 1.
this demo uses react-native-reanimated and react-native-gesture-handler simultaneously.
I naively guessed this would be the proper repository to report the issue.
"react-native": "0.55.4",
"react-native-gesture-handler": "1.0.7",
"react-native-reanimated": "1.0.0-alpha.6"
Tested on device(Android 9) and simulator(Android 6) and latest expo app. Same results.

**Comment by jakub-gonet** [comment]
Hey, thanks for submitting this issue!

I'm really sorry for the very late response 😔

If you want to reproduce IOS behavior in android you can set `maxDurationMs`property to some large value like 2 592 000 000 (around 30 days)

You can see this in action in this snack https://snack.expo.io/@jgonet/react-native-reanimated-issues-84



If you have any other concerns about this issue feel free to reopen
