### ISSUE TITLE
V2 installation failure - Build input file cannot be found: '...AppDelegate.m'

### ISSUE THREAD

**Issue by nextriot** [software-mansion/react-native-reanimated#841]
## Description

I believe I'm following the installation instructions correctly, however I can't seem to get the project to run. Clearly this is due to changing the extension, but I don't know enough about native development to pin down where the issue lies.

## Steps

I follow the installation instructions as outlined, then running `yarn react-native run-ios` gives the following error: `error: Build input file cannot be found: '.../AppDelegate.m'`

### Package versions

- React Native: 0.62.2
- React Native Reanimated: ^2.0.0-alpha.1
- Xcode: 10.3

**Comment by jakub-gonet** [comment]
Hi @nextriot,

please create a repository with your project and link it here.

**Comment by terrysahaidak** [comment]
Oh, I faced it too.

In order to fix this, open the project in XCode, then navigate to Build Phases, in Compile Sources remove the `AppDelegate.m` file and add `AppDelegate.mm` instead.

Perhaps, this should be mentioned in docs, not sure if there is easier way to fix this thing.

**Comment by drewandre** [comment]
I also had to change this line `sourcecode.c.objc` -> `sourcecode.cpp.objc` as noted in the [diff](https://github.com/software-mansion-labs/reanimated-2-playground/commit/f6f2b77496bc00601150f98ea19a341f844d06a3#diff-eacde6d0f9b5596ff5a6812d0b299e02R50). I ran into an issue where xcode compilation couldn't pick up the standard cpp files (memory.h in my case)

**Comment by nextriot** [comment]
> Oh, I faced it too.
> 
> In order to fix this, open the project in XCode, then navigate to Build Phases, in Compile Sources remove the `AppDelegate.m` file and add `AppDelegate.mm` instead.
> 
> Perhaps, this should be mentioned in docs, not sure if there is easier way to fix this thing.

This did it for me! Thanks a bunch @terrysahaidak 👍

**Comment by terrysahaidak** [comment]
Let's keep this open until we have this in docs @jakub-gonet

**Comment by nextriot** [comment]
Just wanted to point out that the note added to the docs doesn't address the fix in my case, which was @terrysahaidak's reccomendation
>In order to fix this, open the project in XCode, then navigate to Build Phases, in Compile Sources remove the AppDelegate.m file and add AppDelegate.mm instead.

**Comment by terrysahaidak** [comment]
Did you do the renaming within the XCode? How did you do it exactly?

**Comment by nextriot** [comment]
My apologies, I misunderstood the note. I had indeed made the change in my IDE 👍 ignore me :)
