### ISSUE TITLE
V2: Upgrade error `InnerNativeModule.installCoreFunctions`

### ISSUE THREAD

**Issue by xignor** [software-mansion/react-native-reanimated#846]
## Description

When running the app after 1.8 to 2 upgrade Reanimated throws this error:

```
Error: Requiring module "node_modules/react-native-reanimated/src/reanimated2/index.js", which threw an exception: TypeError: null is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
```

### Screenshots

![image](https://user-images.githubusercontent.com/36939901/83352300-5bb55180-a342-11ea-8e0c-e4383e44e761.png)

## Steps To Reproduce

1. Upgrade from1.8.0 to 2.0.0-alpha.1
2. Update babel.config.js, AppDelegate.h, AppDelegate.mm to reflect changes in https://docs.swmansion.com/react-native-reanimated/docs/installation

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.1

**Comment by terrysahaidak** [comment]
Hi. Did you run this with remote debugging enabled?

**Comment by xignor** [comment]
@terrysahaidak no, didn't had remote debugging enabled

**Comment by terrysahaidak** [comment]
What platform do you use?

**Comment by xignor** [comment]
@terrysahaidak ios and with
> Update babel.config.js, AppDelegate.h, AppDelegate.mm to reflect changes in https://docs.swmansion.com/react-native-reanimated/docs/installation

**Comment by terrysahaidak** [comment]
Ok, this is weird then. Could you try to clean build folder and rebuild your project from XCode?

**Comment by xignor** [comment]
@terrysahaidak tried cleared cached on react-native and clean build on XCode, and no avail

**Comment by terrysahaidak** [comment]
Then the only way to figure this out is to provide reproducing repo.

**Comment by xignor** [comment]
@terrysahaidak haven't had had a chance to create a reproducing repo but found that the issue is from adding

```
    _bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:_bridge
```

to a project using wix/react-native-navigation which uses multiple root views

**Comment by piaskowyk** [comment]
This issue should no longer appear. I am not able to reproduce on any stable version. If you still have this problem with the stable version please let me know.

**Comment by samrith-s** [comment]
Have this exact same issue with `reanimated@v2.3.0-beta.1` when trying to run the app. No idea what to do or fix, cannot create a reproduction repo as our project is extremely complicated. Can you point how to debug this? Where is it trying to find `installCoreFunctions`? Which file is calling it?

**Comment by 77TecShaeer** [comment]
+2

**Comment by rdbsf** [comment]
+1 also with "react-native-reanimated": "2.3.0-beta.2",

**Comment by rafwell** [comment]
Hi guys. I've found this issue when I upgrade from RN 0.65 to 0.66. I fixed folowing the installation instructions here https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

Well, I don't know why this was working before, but in my project was missing some steps, like enableHermes:true  and some overrides.

Now is working like a charm.

`"react-native": "0.66.0",
"react-native-reanimated": "^2.3.0-beta.2",'

**Comment by AHMAD19858** [comment]
> i have the same issue Cannot read property 'installCoreFunctions' of undefined, js engine: hermes
> 
> **"react-native": "0.66.0", "react-native-reanimated": "^2.3.0-beta.2",**

it worked with me after adding 
  plugins: [
    'react-native-reanimated/plugin',
]
**in babel.config.js**
after that **start --reset-cache**

hope it will work with u guys

**Comment by studiozocaro** [comment]
i have the same issue
TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
"react-native": "0.66.0",
"react-native-reanimated": "^2.3.0-beta.2",

Error in Android version. In ios "react-native-reanimated": "^2.3.0-beta.2" resolve problem.
both release and debug.

**Comment by victorzimnikov** [comment]
"react-native": "0.66.0",
"react-native-reanimated": "^2.3.0-beta.2",

:hermes_enabled => true

npm start --reset-cache

android works fine. ios error:
TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes

**Comment by harrymash2006** [comment]
any updates regarding this issue ?

**Comment by ajiehatajie** [comment]
same issue

**Comment by samrith-s** [comment]
I have been stuck with this issue for 2 months with no resolution at all. I have a more [detailed comment](https://github.com/software-mansion/react-native-reanimated/issues/2525#issuecomment-964370156) over at #2525. Any help would be highly appreciated!

**Comment by hugo-chq** [comment]
not sure if this helps, but I started getting this error when setting RNReanimated as static in podfile with this sort of change:

```
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNReanimated')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end
```

currently trying to get use_frameworks, react-native-screens and react-reanimated 2.3.0beta3 working together, so have been trying different changes to Podfile.

No solution for that so far, but for others removing code that sets RNReanimated as static could help

**Comment by hpardess** [comment]
I am experiencing similar issue and here is my dependencies:
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-reanimated": "^2.3.0",

```
 BUNDLE  ./index.js

 ERROR  TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

**Comment by DallAcqua** [comment]
> I am experiencing similar issue and here is my dependencies: "react": "17.0.2", "react-native": "0.66.4", "react-native-reanimated": "^2.3.0",
> 
> ```
>  BUNDLE  ./index.js
> 
>  ERROR  TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> ```

@hpardess I downgraded my reanimated version to "react-native-reanimated": "2.1.0", and it worked. I think other versions up to 2.3.0 works too.

**Comment by Wellers0n** [comment]
> I am experiencing similar issue and here is my dependencies: "react": "17.0.2", "react-native": "0.66.4", "react-native-reanimated": "^2.3.0",
> 
> ```
>  BUNDLE  ./index.js
> 
>  ERROR  TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> ```

I'm with this error too

**Comment by Wellers0n** [comment]
> was facing same problem "react-native": "0.66.0", "react-native-reanimated": "^2.3.0-beta.2",
> 
> I changed in android/app/build.gradle `project.ext.react = [ enableHermes: true ]`
> 
> and in the MainApplication.java I added on top ` import com.facebook.react.bridge.JSIModulePackage;` `import com.swmansion.reanimated.ReanimatedJSIModulePackage;` and in the function ReactNative Host () I added ` @Override protected JSIModulePackage getJSIModulePackage() { return new ReanimatedJSIModulePackage(); }`
> 
> It worked like a charm

it works for me

**Comment by dhamodar** [comment]
```
post_install do |installer|
   installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
           config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''
       end
   end
end
```
** solution for ios **

**Comment by casper-y** [comment]
> ```
> post_install do |installer|
>    installer.pods_project.targets.each do |target|
>        target.build_configurations.each do |config|
>            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''
>        end
>    end
> end
> ```
> 
> ** solution for ios add above code piece on podFile **

Thanks for this! This works for me,  for both android and iOS. I've been stuck on this for quite a few days.

I am on:
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-reanimated": "2.3.1",

**Comment by harry524483** [comment]
Fixed this issue by removing the changes made to **AppDelegate.m** file (https://github.com/facebook/react-native/issues/16376#issuecomment-891285914)

**Comment by quando2311** [comment]
i changed version of **react-native-reanimated** to 2.2.4 and it worked

**Comment by dhamodar** [comment]
change version of react-native-reanimated to ^1.0.0

**Comment by abdul-ahad-devs** [comment]
Can anyone kindly tell me what and why is it undefined in this latest update?

**Comment by Kazi-Yako** [comment]
> facebook/react-native#16376 (comment)

This works for me. Thank you!

I am on : 
- react-native": "0.66.4", 
- react: "17.0.2",
- "react-native-reanimated": "^2.3.0-beta.2",

I changed in android/app/build.gradle:
project.ext.react = [ enableHermes: true ]

In the MainApplication.java:
1. I added on top: 
- import com.facebook.react.bridge.JSIModulePackage; 
- import com.swmansion.reanimated.ReanimatedJSIModulePackage; 
2. In the function ReactNative Host (),  I added: 
@Override protected JSIModulePackage getJSIModulePackage() { 
        return new ReanimatedJSIModulePackage(); 
}

I deleted the node modules (rm -rf node_modules)

I ran yarn start --reset-cache

I ran "Yarn"

cd ios and ran Pod install

yarn run android

**Comment by munsifhayat** [comment]
> was facing same problem "react-native": "0.66.0", "react-native-reanimated": "^2.3.0-beta.2",
> 
> I changed in android/app/build.gradle `project.ext.react = [ enableHermes: true ]`
> 
> and in the MainApplication.java I added on top ` import com.facebook.react.bridge.JSIModulePackage;` `import com.swmansion.reanimated.ReanimatedJSIModulePackage;` and in the function ReactNative Host () I added ` @Override protected JSIModulePackage getJSIModulePackage() { return new ReanimatedJSIModulePackage(); }`
> 
> It worked like a charm

This solution is working fine for M1 as well.

**Comment by nabarun1995** [comment]
> This issue should no longer appear. I am not able to reproduce on any stable version. If you still have this problem with the stable version please let me know.

TypeError: Cannot read property 'installCoreFunctions' of undefined

i'm getiing this error

**Comment by Stephen-L-Wang** [comment]
> i changed version of **react-native-reanimated** to 2.2.4 and it worked

works for me   delete '^'

**Comment by mrshahzeb7** [comment]
target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
    end
    
   just replaced above code(copied from reanimated documentaion) with below one worked for me 
    
          target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''
    end
    
    
* inShort remove "-DDONT_AUTOINSTALL_REANIMATED" and use ''

**Comment by kaialsh705** [comment]
> > I am experiencing similar issue and here is my dependencies: "react": "17.0.2", "react-native": "0.66.4", "react-native-reanimated": "^2.3.0",
> > ```
> >  BUNDLE  ./index.js
> > 
> >  ERROR  TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
> >  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
> >       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> >  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
> >       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> > ```
> 
> @hpardess I downgraded my reanimated version specifically to "react-native-reanimated": "2.1.0" without the "^" operator, and it worked. I think other versions up to 2.3.0 works too.

this work for me.

**Comment by jdriverab** [comment]
> i changed version of **react-native-reanimated** to 2.2.4 and it worked

It worked too! at least with warns...

TYTY :)

**Comment by Alavifuentes** [comment]
Configuraciones de la documentacion

https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/
![image](https://user-images.githubusercontent.com/5463415/153102535-de5110ed-43a9-4dee-adb2-cb11612d181a.png)

**Comment by mehranMinaei** [comment]
You must install according to these instructions
Also, make no mistake 

Add this code in MainApplication
 @Override
 protected JSIModulePackage getJSIModulePackage() {
    return new ReanimatedJSIModulePackage(); // <- add
 }

**Comment by ybonnetain** [comment]
For wanderers having this issue on iOS (or very similar, something about the JSI module not having the VM reference early on)..
Make sure to init `RCTRootView` using the appropriate initialiser with the help of `RCTBridgeDelegate`
```objc
RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
                                          launchOptions:launchOptions];

RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                 moduleName:@"GroupeMutuelFrontGateway"
                                          initialProperties:initialProps];
```

Not `initWithBundleURL`

**Comment by yaronlevi** [comment]
@ybonnetain your comment saved me days of work!
I've tried everything but nothing helped.

Becuase we use Codepush we had this line:

````
let rootView = RCTRootView(bundleURL:jsCodeLocation!, moduleName: "rumble_mobile", initialProperties: nil, launchOptions:launchOptions)
````

But after changing it to:
```
let rctBridge = RCTBridge(delegate: self, launchOptions: launchOptions)    
let rootView = RCTRootView(bridge: rctBridge!, moduleName: "rumble_mobile", initialProperties: nil)
```

The installCodeFunctions error disappered.

I think many people that use CodePush had the same problem. Probably when integrating Codepush you accidentally remove the RCTBridge line and use the other variation of the constructor RCTRootView.

I think this should be added to the docs, just in case.

**Comment by siddiquesheikh30** [comment]
I have followed the guide of this comment https://github.com/software-mansion/react-native-reanimated/issues/846#issuecomment-943267584  and now it is giving me an error as this - 
"Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?, js engine: hermes" also this 
"Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes" I am using react-native 0.67 please help

**Comment by hienbv1312** [comment]
@yaronlevi you saved my life <3

**Comment by ybonnetain** [comment]
InitialProps is a NSDictionary that must be defined before.
It can be empty

**Comment by roots-ai** [comment]
Any updates here?

**Comment by ybonnetain** [comment]
> Tried with
> 
> ```
>   RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
>                                              launchOptions:launchOptions];
> 
>   RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
>                                                     moduleName:@"MyApp"
>                                              initialProperties:nil];
> ```
> 
> But now this gives another error and the app doesn't build
> 
> ```
> 
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate sourceURLForBridge:]: unrecognized selector sent to instance 0x283b010e0'
> ```
> 
> Any updates here?

You need to conform to `RCTBridgeDelegate`  in order to use these bridge and view initializers.
See the following gist for a complete example.
https://gist.github.com/ybonnetain/7b3e510050447ae52c0f8d6dd741d9d4

**Comment by roots-ai** [comment]
@ybonnetain it's giving a compilation error
`Use of undeclared identifier '$'`

Here is my [AppDelegate.m](https://wtools.io/paste-code/bF3S)


Stuck on this issue error since months now.

**Comment by ybonnetain** [comment]
Line 71, sorry it's @ not $.

But you also need to conform to RCTBridgeDelegate.

You may want to move this issue to stackoverflow and DM me the link ;)

**Comment by roots-ai** [comment]
https://stackoverflow.com/questions/73917181/typeerror-undefined-is-not-an-object-installcorefunctions-react-native-reanim

**Comment by roots-ai** [comment]
@ybonnetain Facing issues.

**Comment by roots-ai** [comment]
@ybonnetain Facing issues.

**Comment by lePoissonier** [comment]
> was facing same problem "react-native": "0.66.0", "react-native-reanimated": "^2.3.0-beta.2",
> 
> I changed in android/app/build.gradle `project.ext.react = [ enableHermes: true ]`
> 
> and in the MainApplication.java I added on top ` import com.facebook.react.bridge.JSIModulePackage;` `import com.swmansion.reanimated.ReanimatedJSIModulePackage;` and in the function ReactNative Host () I added ` @Override protected JSIModulePackage getJSIModulePackage() { return new ReanimatedJSIModulePackage(); }`
> 
> It worked like a charm

hi. i can't find android/app/build.gradle on my pc.

**Comment by Aggroid** [comment]
> ```objc
> RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
>                                           launchOptions:launchOptions];
> 
> RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
>                                                  moduleName:@"MyApp"
>                                           initialProperties:initialProps];
> ```

I don't know if you fix it but with the new react-native there is no more initialProperties:initialProps so instead of that use this solution but change initialPropertis:nil .

RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
                                          launchOptions:launchOptions];

RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                 moduleName:@"appName"
                                          initialProperties:nil];

That's how I made it work on react-native 0.68.1
