### ISSUE TITLE
Reset on button press

### ISSUE THREAD

**Issue by radaalinmihai** [software-mansion/react-native-reanimated#847]
## Description

How would I animate a view to a certain x on the press of a button? The button that I would use is from react-native-gesture-handler but I don't know how to do that.

**Comment by jakub-gonet** [comment]
Hi @radaalinmihai,

Please fill other sections from template, especially sections which ask you to provide code and library versions.

**Comment by radaalinmihai** [comment]
I don't have what to fill because I don't know how to do what I asked in the question.

**Comment by jakub-gonet** [comment]
At the moment we have Reanimated v1 and v2 which are extremely different, so we need that info to answer your question.

**Comment by radaalinmihai** [comment]
I'm using reanimated v1

**Comment by jakub-gonet** [comment]
You have a few options here:
- `start` API shown [here](https://github.com/software-mansion/react-native-reanimated/blob/master/Example/reanimated1/startAPI/index.js#L43)

- imperatively changing values by `.set()` method, shown [here](https://github.com/software-mansion/react-native-reanimated/blob/master/Example/reanimated1/imperative/index.js#L24)

I usually go with the second method which changes `to` value in spring / timing and forcing it to run.

**Comment by radaalinmihai** [comment]
Thank you
