### ISSUE TITLE
Link to getting started docs on README is broken

### ISSUE THREAD

**Issue by bmuthoga** [software-mansion/react-native-reanimated#854]
## Description
The link to the `getting started` docs seems to be broken.

### Screenshots
<img width="1019" alt="Screenshot 2020-06-02 at 17 08 42" src="https://user-images.githubusercontent.com/6702127/83530540-87783900-a4f4-11ea-8556-2f8e1b489a45.png">
<img width="1433" alt="Screenshot 2020-06-02 at 17 09 09" src="https://user-images.githubusercontent.com/6702127/83530547-8941fc80-a4f4-11ea-8a39-0e78567c0c1e.png">

## Steps To Reproduce

1. Click the `getting started` link on the `README.md`

### Expected behavior
The link should direct the user to the getting started docs
### Actual behavior
The link directs a user to a `404 not found` page
## Snack or minimal code example
N/A

## Package versions
N/A

**Comment by jakub-gonet** [comment]
Thanks, #855 should fix it.
