### ISSUE TITLE
V2: Not working with yarn workspace

### ISSUE THREAD

**Issue by Daavidaviid** [software-mansion/react-native-reanimated#858]
## Description

I tried to add React Native Reanimated 2 to a project in a yarn workspace. It didn't work I kept getting an error about `useAnimatedStyle` and `Object.values` and `_closure()`. I think the problem come from the babel plugin not loading properly when the `node_modules` is located above the root, but I'm not sure.

## Steps To Reproduce

1. Just create a project with a yarn monorepo structure using yarn workspaces.
2. Clone the Reanimated 2 Playground in it (https://github.com/software-mansion-labs/reanimated-2-playground)
3. Define the workspace for the React Native App `reanimated-2-playground`.
4. In the React native App `reanimated-2-playground` find and replace all the `../node_modules/` to `../../node_modules/`.
5. Create an `index.js` at the root of the monorepo with :
```
require('./reanimated-2-playground');
```
6. `yarn`, `pod install`, etc
7. Cry

### Expected behavior

The app should work

### Actual behavior

The app doesn't work

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.1

**Comment by egislook** [comment]
For me, it worked on my monorepo when I moved my babel configs from `package.json` to `babel.config.js` and changed the `metro-react-native-babel-preset` version to `0.58.0`

```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin']
}
```

**Comment by nikolaigeorgie** [comment]
@ericlifs i created a demo of a working version with reanimated + yarn workspaces. https://github.com/nikolaigeorgie/yarn-workspaces-reanimated.git check it out.. it's based off of https://github.com/brunolemos/react-native-web-monorepo

**Comment by fortezhuo** [comment]
I had same problem and finally solve the problem by learning from @nikolaigeorgie and brunolemos repo.

I have replaced again all "package/mobile/index.js" to "index.js" and set watchFolder for make this library working

Please follow below step
https://github.com/brunolemos/react-native-web-monorepo/commit/af2a79a60a8ff3136caaa75ea8a6b84e96567687

Hope this helps

**Comment by nikolaigeorgie** [comment]
@fortezhuo just clone the repo. run the repo. add react native reanimated.. and it should be chilling

**Comment by fortezhuo** [comment]
@nikolaigeorgie 
Yes, I have clone and run the repo
If I run using react native CLI => it works
If I run using XCode 12 => Failed 
```
Error: Unable to resolve module `./index` from ``: 
```
