### ISSUE TITLE
Scale down from top (anchor top)

### ISSUE THREAD

**Issue by CyberMew** [software-mansion/react-native-reanimated#865]
## Description

I have a flatlist/sectionlist, and I would like new incoming rows, to expand from their row. i.e. kinda like height 0 to their supposed row height, and at the same time fade in together. 

This will have a squeeze in effect as it appears to start from nothing and 'push' the rows downwards.

How can I get the former to work?

### Package versions

- React: 
- React Native: 0.61
- React Native Reanimated: 1.9.0

**Comment by terrysahaidak** [comment]
Hi! Check out this video, it might guide you to your own animation:
https://www.youtube.com/watch?v=NiFdK-s6OP8

**Comment by CyberMew** [comment]
Thanks for the link, I am currently wrapping the whole Sectionlist as it has the final say on the data/render, using Transitions, but from your link, it will not be possible in this case as we are running insert/delete operations here, the 'card' (i.e. row) will instantly disappear.

**Comment by jakub-gonet** [comment]
Hi!
This issue was inactive for a while so I'm closing it.
