### ISSUE TITLE
Unable to run Example App

### ISSUE THREAD

**Issue by derwo** [software-mansion/react-native-reanimated#868]
## Description

I'm unable to run the Example App in neither iOS device or simulator.

## Steps To Reproduce

1. Clone repo
2. `cd Example`
3. `yarn install`
4. `cd ios && pod install && cd ..`
5. `react-native run-ios`
6. Got a compile error
7. Changed Bundle Identifier through XCode
8. Give up using `react-native run-ios` since it still gives errors
9. Run `react-native start` and build through XCode
10. App installed correctly
11. Click on any example
12. App crashes:

![image](https://user-images.githubusercontent.com/38386337/83854909-a73b7700-a717-11ea-91d4-3ebe01052b63.png)

![image](https://user-images.githubusercontent.com/38386337/83856418-d05d0700-a719-11ea-93a9-677086f473aa.png)

I've noticed that most but not all of the 1.x version examples works.

### Expected behavior

The Example App should not crash.

### Actual behavior

The Example App crashes as soon as I open one of the examples.

## Snack or minimal code example

Using the latest [commit](https://github.com/software-mansion/react-native-reanimated/commit/9c0e3c8a6fff9283f9365d87fd205898caa6a3b9)

## Package versions

(from the Example App)
- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.1

**Comment by esthor** [comment]
Can also confirm I can't get the example app to build. Tried going back to initial V2 release commits from ~10 days ago, and still no luck.

In the meantime, if you are just trying to get your toes wet with v2, you can use the reanimated 2 playground app and just paste in the code from the Example app that you want to try out. They seem to work just fine. https://github.com/software-mansion-labs/reanimated-2-playground

**Comment by CyberMew** [comment]
I tried it 11 days ago and this was working for me, though I had to go up to root folder and install package first

**Comment by terrysahaidak** [comment]
The Example app uses master branch. Lately, there were few PRs with dependencies on each other. 

If you want to give a try to Reanimated, it's better to use playground repo which uses the latest stable release.

**Comment by drewandre** [comment]
@CyberMew could you explain what you mean by go up to root folder and install package first? Do you mean to just run npm install in the root directory...?

@terrysahaidak I assume you're referring to [this playground repo](https://github.com/software-mansion-labs/reanimated-2-playground)? After a fresh clone/npm install/pod install, I get what may look to be the same error as @derwo which I put in [this gist](https://gist.github.com/drewandre/1110faf4f0d030ef8a45d5b773d3bc8c). I want to help but I have no idea how to work with native backtraces like this.

Xcode version: 11.2.1
...(fresh repo running at 2.0.0-alpha.1, gesture handler ^1.6.1, etc)

**Comment by derwo** [comment]
@drewandre I had no issues running the playground repo

**Comment by arberK** [comment]
The "Developer menu" is not showing up.

**Comment by nextriot** [comment]
@terrysahaidak Can confirm the developer menu is not showing doing a standalone install, and the playground app is also crashing for me.

Followed the instructions. That's all.

Running on iOS 12.4 simulator. Not sure if that should makes a difference.

**Comment by esthor** [comment]
@arberK @nextriot The developer menu not working is probably related to a bug in iOS 13 and/or react native 61+ and is already opened here: https://github.com/facebook/react-native/issues/28552

**Comment by arberK** [comment]
> @arberK @nextriot The developer menu not working is probably related to a bug in Xcode/iOS and/or react native 61+ and is already opened here: [facebook/react-native#28552](https://github.com/facebook/react-native/issues/28552)

I dont think so. I followed instructions to integrate reanimated 2 in my existing project and the developer menu stopped showing up. I then deintegrated reanimated 2, and the developer menu is showing again.

Same for Example Playground App.

Im on iOS 13.5.1. react-native: "0.62.2".

**Comment by nextriot** [comment]
It seems to be related to the Turbo modules integration.
Removing the following line enables the menu again.

`RCTEnableTurboModule(YES);`

**Comment by terrysahaidak** [comment]
Here is the fix for dev menu:
https://github.com/software-mansion/react-native-reanimated/pull/917

**Comment by jakub-gonet** [comment]
I believe this issue is resolved, so I'll close it.

If that's not a case please comment.
