### ISSUE TITLE
Make Intl available in a worklet?

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#872]
Is it possible to make the `Intl` class available in a worket?

**Comment by terrysahaidak** [comment]
Since Reanimated2 uses Hermes on Android, it should be available there first:
https://github.com/facebook/hermes/issues/23

**Comment by outaTiME** [comment]
🙏

**Comment by piaskowyk** [comment]
> Is it possible to make the Intl class available for a worker?

It isn't possible at this moment. This isn't related to the Reanimated. `Intl` isn't available in Hermes yet - https://github.com/facebook/hermes/issues/23

**Comment by nandorojo** [comment]
`Intl` is now available in Hermes. However, I wasn't able to use `Intl.NumberFormat().format()` in a worklet.

**Comment by RichardLindhout** [comment]
Intl is not usable inside an animatedReaction

**Comment by gtokman** [comment]
Does anyone have a good way of solving this from an UI thread context?

**Comment by kievu** [comment]
From what I'm reading, `Intl` should be available in Hermes. I tried to run this snippet 
```
    const formatter = new Intl.NumberFormat('en');
    formatter.format(1000);
```
 in `useAnimatedProps() | useDerivedValue()`, but get this error `ReanimatedError: Cannot read property 'prototype' of undefined, js engine: reanimated`
