### ISSUE TITLE
V2: interpolateNode causes crash

### ISSUE THREAD

**Issue by sa8ab** [software-mansion/react-native-reanimated#875]
## Description
when using interpolateNode the app crashes

## Steps To Reproduce

1. create an interpolateNode value and assign it to useAnimatedStyle

```
const width = interpolateNode(tY.value, {
    inputRange: [10, 100],
    outputRange: [40, 200],
    Extrapolate: Extrapolate.CLAMP,
  });
```

Reanimated 2

**Comment by jakub-gonet** [comment]
You're mixing Reanimated 1 and reanimated 2, right? This may be not supported when you're using nodes in new hooks

**Comment by sa8ab** [comment]
No the tY in the example is equal to useSharedValue().

Can you provide an example of using interpolation in v2 please?

**Comment by terrysahaidak** [comment]
```
const width = interpolate(
    tY.value,
    [10, 100],
    [40, 200],
    Extrapolate.CLAMP,
);
```

**Comment by sa8ab** [comment]
No luck @terrysahaidak 

I tried the following
```
const width = **interpolateNode**(tY.value, {
    inputRange: [0, 100],
    outputRange: [10, 200],
    Extrapolate: Extrapolate.CLAMP,
  });
```
also 
```
const width = **interpolate**(tY.value, {
    inputRange: [0, 100],
    outputRange: [10, 200],
    Extrapolate: Extrapolate.CLAMP,
  });

```

and when using any of them in the useAnimatedStyle or direclty in the style of the component, it crashes, result of console.log of for the one you sent me (interpolate, not intepolateNode) was NaN,
also console logging the result of **interpolateNode** also causes crash

**Comment by terrysahaidak** [comment]
Please, carefully read my suggestion. The interpolation in Reanimated2 takes 4 parameters: sharedValue's value, array of input, array of output and extrapolate. You're using 2 parameters instead and passing the object as a second one. That's how interpolate node works

**Comment by sa8ab** [comment]
Thank you, sorry my bad didn't notice the change, Currently I do the following and I don't see any update in the interpolated value

`const width = interpolate(tY.value, [10, 100], [40, 200], Extrapolate.CLAMP);`

here is the log:
![image](https://user-images.githubusercontent.com/59901734/84123871-48178400-a9ef-11ea-906c-c9ac6165301e.png)

**Comment by terrysahaidak** [comment]
Could you post a code snipped with those logs and useAnimatedStyle?

**Comment by sa8ab** [comment]
Yes, sure. here you go.

```
import React from 'react';
import {StyleSheet, View, Text} from 'react-native';
import Animated, {
  withSpring,
  useSharedValue,
  useAnimatedStyle,
  useAnimatedGestureHandler,
  interpolate,
  Extrapolate,
} from 'react-native-reanimated';
import {PanGestureHandler} from 'react-native-gesture-handler';

const App = () => {
  const tY = useSharedValue(0);
  const width = interpolate(tY.value, [10, 100], [40, 200], Extrapolate.CLAMP);
  const gestureEvent = useAnimatedGestureHandler({
    onStart: (event, context) => {
      context.start_tY = tY.value;
    },
    onActive: (event, context) => {
      tY.value = event.translationY;

      console.log('tY.value', tY.value);
      console.log('width', width);
    },
    onEnd: () => {
      tY.value = withSpring(0);
    },
  });

  const sz = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateY: tY.value,
        },
      ],
    };
  });
  return (
    <View>
      <Text>hello</Text>
      <Animated.View style={{...s.pan2, width}} />
      <PanGestureHandler onGestureEvent={gestureEvent}>
        <Animated.View style={[s.pan, sz]} />
      </PanGestureHandler>
    </View>
  );
};

const s = StyleSheet.create({
  pan: {
    width: 80,
    height: 80,
    backgroundColor: 'teal',
  },
  pan2: {
    height: 80,
    backgroundColor: 'gray',
  },
});

export default App;

```

**Comment by terrysahaidak** [comment]
The interpolate function in Reanimated2 is a pure function. It takes arguments and returns a value.

You have two options here:
1. Use and log interpolate inside the worklet (useAnimatedStyle or inside any of the gesture handlers)
2. Wrap that interpolate call with useDerivedValue - it returns a shared value, so make sure to use .value:

```js
const width = useDerivedValue(() => {
  return interpolate(...);
});
```

**Comment by sa8ab** [comment]
Works perfectly now
thanks alot @terrysahaidak, :)

I used the derivedValue also had to use useAnimatedStyle to make it work.

**Comment by sa8ab** [comment]
just wonder why first syntax does not work and we need to use the second one
![image](https://user-images.githubusercontent.com/59901734/84127185-c24a0780-a9f3-11ea-9c82-d9738445ab86.png)

**Comment by terrysahaidak** [comment]
useAnimatedStyle bosy is executed on a UI Thread. When you pass its result (styles) to Animated.View as style, it bounds that style to that view and tells "if something changes in the AnimatesStyles, please update the view".

Since you can return different styles at any time from useAnimatedStyle, you cannot just "spread" it.

Also, you can no longer pass animated values (now they are shared values) as style properties.

**Comment by sa8ab** [comment]
@terrysahaidak Great explanation.
 What about clamping only left or only right? do they go as 5th and 6th parameters??

**Comment by terrysahaidak** [comment]
Seems like these are missing right now. Could you open a new issue for this?

**Comment by sa8ab** [comment]
@terrysahaidak indeed I will open a new one, what about color interpolations, is it possible in v2?

**Comment by terrysahaidak** [comment]
It is. Check out the first example in the example app.

**Comment by sa8ab** [comment]
@terrysahaidak I noticed it is basically using a value for HSL color, I wonder if it is possible like the "interpolateColors" from reanimated v2;

`https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/nodes/interpolateColors`

**Comment by terrysahaidak** [comment]
What is your use case? Do you want to be able to interpolate separately r/g/b?

**Comment by sa8ab** [comment]
@terrysahaidak 
Asking to see if I am able to do like the following

```
interpolateColors( //or interpolate()
   someValue.value, 
   [1, 100],
   [ 'red' , 'gold' ] //or HEX values
   Extrapolate.CLAMP
)
```

**Comment by terrysahaidak** [comment]
I believe @Szymon20000 has wrote some color interpolation logic already.

**Comment by sa8ab** [comment]
@terrysahaidak Will we have it on next updated?

**Comment by terrysahaidak** [comment]
@wcandillon has more context on this

**Comment by M2Changezi** [comment]
@terrysahaidak As documentation says that interpolate named to interpolateNode so how does reanimted 2 and up versions are accepting interpolate

**Comment by M2Changezi** [comment]
@terrysahaidak  May u suggest any better explanation  ,blog , etc of the reanimted 2 hooks under the hood

**Comment by terrysahaidak** [comment]
With Reanimated 2 interpolate accepts some value instead of animated node, and then two arrays - input range and output range. The last parameter is options.

You can take a look at example here:

 https://github.com/software-mansion/react-native-reanimated/blob/master/Example/src/ExtrapolationExample.tsx#L46

**Comment by M2Changezi** [comment]
@terrysahaidak  ok how about this question !


> @terrysahaidak As documentation says that interpolate named to interpolateNode so how does reanimted 2 and up versions are accepting interpolate

**Comment by terrysahaidak** [comment]
> @terrysahaidak  ok how about this question !
> 
> 
> > @terrysahaidak As documentation says that interpolate named to interpolateNode so how does reanimted 2 and up versions are accepting interpolate
> 

If you are using reanimated v1 then interpolate renamed to interpolateNode. If you want to use interpolation in V2 you can just import "interpolate" because now it's a worklet.

You can learn about worklet in documentation and [this video](https://youtu.be/e5ALKoP1m-k)

**Comment by M2Changezi** [comment]
@terrysahaidak  thanku Sir that helped me alot

**Comment by M2Changezi** [comment]
@terrysahaidak  how can we debug the code of reanimated 2 (hooks ,etc)

**Comment by shadahmad7** [comment]
Go to drawer.js file in /node_modules/react-navigation-drawer/lib/module/views/  and change interpolate to interpolatenode on two places. your problem solved

**Comment by chris-mactavis** [comment]
> Go to drawer.js file in /node_modules/react-navigation-drawer/lib/module/views/ and change interpolate to interpolatenode on two places. your problem solved

This works for me, thanks

**Comment by callmemonky** [comment]
Diffclamp is not working. @terrysahaidak any idea? How can we make it work.
