### ISSUE TITLE
V2: Spring Velocity!!!???

### ISSUE THREAD

**Issue by sa8ab** [software-mansion/react-native-reanimated#879]
## Description
Where should I pass the velocity as a config parameter to withSpring !!!???

I wanna drag and release an element and pass the velocity as the parameter, without velocity the gesture seems to be blocked for a moment since it slows down, there is velocity available in Animated/Reanimated V1, but I couldn't find any for V2 in the documentation.

**Comment by sa8ab** [comment]
`tY.value = withSpring(max, {velocity: event.velocityY});
`
basically this is what I want to do on the end of the gesture.

**Comment by terrysahaidak** [comment]
Yes, you should pass it into a config. But yeah, it doesn't work. That was a bug in the alpha 1 release. It's already fixed. Hope it will be released soon.

**Comment by terrysahaidak** [comment]
Here is the PR with fix. You can apply those changes to your local installation of Reanimated as a workaround for now:
https://github.com/software-mansion/react-native-reanimated/pull/853
