### ISSUE TITLE
"Error while updating property 'strokeDasharray' of a view managed by: RNSVGPath. java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableArray"

### ISSUE THREAD

**Issue by rhysdavies1994** [software-mansion/react-native-reanimated#881]
## Description
I am working on a React Native application and have been using react-native-reanimated to get some really nice animations into the app.

We had implemented an animation where a line graph would "draw" itself as the component was mounted; [Here is a link, visually explaining the animation concept in CSS](https://css-tricks.com/svg-line-animation-works/)

With a Path SVG, using `strokeDasharray` to be the length of the line and `strokeDashoffset` to be an animated value we were able to achieve this animation. 

I then tried using an ReAnimated Value in `strokeDasharray` to dynamically change the size of the line and it worked great on iOS but later noticed it completely crashes the whole app on Android with the following error message:

```
Error while updating property 'strokeDasharray' of a view managed by: RNSVGPath. java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableArray
```

- I've tried converting to string, same error but with 'String' instead of 'Double'
- I've tried putting the value into an array but get some circular call errors

This doesn't look to happen with a regular ReactNative.Animated value, but as we are using a bunch of reanimated calculations and values for other parts of the chart, moving back to RN Animated doesn't seem like an option at this point. 

I think this is related to the `Animated.createAnimatedComponent` function

I've been able to replicate this in the most bare bones RN app, please see below.

### Screenshots
![Screen Shot 2020-06-10 at 7 24 01 pm](https://user-images.githubusercontent.com/7247102/84251542-db1bff80-ab50-11ea-9d22-3a111c26305d.png)

## Steps To Reproduce

1. Create new react-native app
2. Install `react-native-svg` and `react-native-reanimated`
3. Use a Animated.Value from reanimated library inside of strokeDasharray
4. Run on Android simulator
5. Boom, App crashes with above error.

### Expected behavior
I expect to be able to use an animated value for strokeDasharray as it works fine on iOS

### Actual behavior
The app works as expected on iOS but crashes on Android

## Snack or minimal code example

```
import React from 'react';
import {View} from 'react-native';
import Animated from 'react-native-reanimated';
import {Svg, Path} from 'react-native-svg';

const App = () => {
    const AnimatedPath = Animated.createAnimatedComponent(Path);
    const strokeDasharray = new Animated.Value(100);

    return (
        <View>
            <Svg width={400} height={400}>
                <AnimatedPath
                    stroke='black' d='m 0 0 l 50 50 l 50 150 l 200 150 l -50 50'
                    strokeDasharray={strokeDasharray}
                    strokeDashoffset={50}/>
            </Svg>
        </View>
    );
};

export default App;
```

## Package versions

```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-reanimated": "1.9.0",
    "react-native-svg": "12.1.0"
```

**Comment by Lostkill** [comment]
i have the same issue, how solve?

**Comment by rhysdavies1994** [comment]
@Lostkill I have not been able to get this working with an Animated value

The only way I stopped the app from crashing is to use a regular JavaScript value, but that is no solution for actually animating strokeDasharray

**Comment by jakub-gonet** [comment]
`strokeDasharray` should be an array basing on docs and we don't support props which are arrays at the moment, so I'm assuming iOS is more liberal in things it accepts as an argument.

We don't plan to extend supported things in reanimated v1 right now but we gladly merge PR fixing this.

**Comment by reggie3** [comment]
Does alpha 7 of reanimated 2 support providing shared values to strokeDahsarray now?  If not, will that be a feature that will be provided?  I'm using the following syntax ut I'm not seeing any changes in the stroke:
```
 <AnimatedCircle
          animatedProps={animatedCircleProps}
          cx={r}
          cy={r}
          fill="transparent"
          r={radius}
          strokeWidth={strokeWidth}
          strokeDasharray={`${activeCircumference.value} ${inactiveCircumference.value}`}
        />
```

**Comment by terrysahaidak** [comment]
> Does alpha 7 of reanimated 2 support providing shared values to strokeDahsarray now?  If not, will that be a feature that will be provided?  I'm using the following syntax ut I'm not seeing any changes in the stroke:
> ```
>  <AnimatedCircle
>           animatedProps={animatedCircleProps}
>           cx={r}
>           cy={r}
>           fill="transparent"
>           r={radius}
>           strokeWidth={strokeWidth}
>           strokeDasharray={`${activeCircumference.value} ${inactiveCircumference.value}`}
>         />
> ```

You need to use those props in the object useAnimatedProps returns.

**Comment by reggie3** [comment]
@terrysahaidak You're talking about doing something like below where I add the `strokeDasharray` value to the return value of the `animatedCircleProps`?  I've given that a try and it just has no effect.

```
// get the difference between the start and end angles
  const difference = useDerivedValue(() => {
    return getDifferenceBetweenRadianValues(startTheta.value, endTheta.value);
  });

  // get the arc distance between start and end locations
  const activeArc = useDerivedValue(() => {
    return (difference.value.radians / (2 * Math.PI)) * circumference;
  });

  // set the values for the active arc's background and strokeDasharray
  const animatedCircleProps = useAnimatedProps(() => {
    const difference = getDifferenceBetweenRadianValues(
      startTheta.value,
      endTheta.value
    );
    console.log("difference.theta", difference.radians); // 5.148437336532542
    console.log("circumference", circumference); // 1066.3463064184784
    console.log("active arc value", activeArc.value); // 873.76336511438
    console.log("inactive arc value", circumference - activeArc.value); // 192.58294130409843
    console.log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");

    return {
      stroke: backgroundColor.value,
      strokeDasharray: `${activeArc.value} ${circumference - activeArc.value}`,
    };
  });
```

**Comment by TrebuhD** [comment]
This may need to be reopened. I'm still getting a crash on Android when animating `strokeDasharray`.

```
 Error while updating prop strokeDasharray
    java.lang.ClassCastException: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableArray
```
code:

```typescript
    const strokeDasharray = useDerivedValue(() =>
      Animated.interpolate(
        progress.value,
        [0, 1],
        [5, 10]
      )
    );

    const animatedProps = useAnimatedProps(() => ({
      strokeDasharray: withTiming(strokeDasharray.value),
      //               (`${withTiming(strokeDasharray.value)}` also doesn't work)
    }));
    
    return (
      <Svg>
        <AnimatedPath d={"M 10 10 h 80 v 80 h -80 Z"} animatedProps={animatedProps} />
      </Svg>
    );
```

**Comment by jakub-gonet** [comment]
@TrebuhD please open a new issue so we can track it there.
