### ISSUE TITLE
Installation on 0.61.5: failed: CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker"

### ISSUE THREAD

**Issue by 378978764** [software-mansion/react-native-reanimated#885]
## Description

Just follow the instruction, I tried install it as follows:
```
yarn add react-native-reanimated@alpha
```
However, this error occurs:
```
[!] CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker":
  In Podfile:
    ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)

None of your spec sources contain a spec satisfying the dependency: `ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Searched everywhere, still no solution.

## Steps To Reproduce

Just install it on `"react-native": "0.61.5",`

### Expected behavior
No error output.

## Snack or minimal code example

1. `yarn global add ignite-cli`
2. `ignite new MyNewAppName`
3. `cd` to `MyNewAppName`, and run this:
```
yarn add react-native-reanimated@alpha
```

## Package versions

- React: 16.9.0
- React Native: 0.61.5
- React Native Reanimated: 2.0.0-alpha.1

**Comment by terrysahaidak** [comment]
Unfortunately, Reanimated2 supports only React Native 0.62+. There is no way to run it with 0.61.
