### ISSUE TITLE
V2: Install not working with expo

### ISSUE THREAD

**Issue by ekatzenstein** [software-mansion/react-native-reanimated#886]
Followed directions as posted in the docs (https://docs.swmansion.com/react-native-reanimated/docs/installation)

On running the app on iOS, the error message is `TypeError: cannot read property 'installCoreFunctions' of null`

**Comment by ekatzenstein** [comment]
Has the request been made to the Expo repo to support Reanimated2?

**Comment by terrysahaidak** [comment]
You can refer to this thread: https://twitter.com/deiucanta/status/1266049769299947521?s=19

**Comment by nandorojo** [comment]
https://expo.canny.io/feature-requests/p/support-react-native-reanimated-v20 expo feature request for reanimated 2
