### ISSUE TITLE
Performance issue in reanimated 2?

### ISSUE THREAD

**Issue by henninghall** [software-mansion/react-native-reanimated#887]
## Description

I've been playing around with the new reanimated 2 and I am experiencing some performance problems compared to both Reanimated 1 and LayoutAnimation. This might very much be an edge case, but maybe worth investigating?

## Steps To Reproduce

1. Clone and install [this fork](https://github.com/henninghall/react-native-reanimated) of the repo.
2. Start Example app.
3. Enable "Heavy load" through the switch in the app
4. Navigate to Reanimated 2 and press on the middle card.

### Expected behavior
Same or better performance compared to Reanimated version 1. 

### Actual behavior
A bit laggy.

Screencap of the repro below. Reanimated 2 has notably worse performance than reanimated 1. (yeah I know the screencap only shows reanimated 1 and Animated) 

<img src="https://github.com/henninghall/react-native-animation-libraries-comparison/raw/master/screencap.gif" height="400"/>

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.1

**Comment by kmagiera** [comment]
Hey @henninghall ! Any chance you could try this with the most recent alpha and report back if the problem still persist?

**Comment by henninghall** [comment]
I tried running from master and the issue still exists there.

**Comment by terrysahaidak** [comment]
I would recommend to run it in a fresh project with latest alpha instead because with the master I faced few times some caching problems. All the cleaning things didn't help for me back then.

**Comment by henninghall** [comment]
Initially I tried to just update the alpha version but I got a crash of some reason and didn't feel to investigating further. If anyone want to try it out, you can copy paste the `src/henning` directory of this fork and you'll be good to go.

**Comment by Szymon20000** [comment]
Transitioning and LayoutAnimation are performed on a different layer then updates of Reanimated nodes and worklets. That's why they don't have to wait for UIManager. However, they are not as powerful as Reanimated is. In your example, the number of components is a struggle for UIManager. Maybe with Fabric, it can be avoided I will check it.

**Comment by henninghall** [comment]
I also compared it with Reanimated 1, which performs significantly better than reanimated 2, do you know why?

**Comment by terrysahaidak** [comment]
did you use alpha1 when comparing?

**Comment by henninghall** [comment]
Tried both alpha1 and master right after the release of alpha3

**Comment by Szymon20000** [comment]
@henninghall  Did you use nodes for that? Or just transitioning?

**Comment by henninghall** [comment]
Not sure, here is the implementation:
 https://github.com/henninghall/react-native-reanimated/blob/master/Example/src/henning/libs/Reanimated2.js

**Comment by michalpetrov** [comment]
I'm having similiar behavior probably related to this issue. Running simple animation (only translateX) on one View (the View is not in the SectionList) while also rendering a SectionList with 150 items. I can see JS frames droped to 20 fps, but UI frames are stable at 60 fps. So I would expect smooth transition but in reallity it's quite laggy. Teste on ios with rc3.

**Comment by VladMatvei** [comment]
I can also confirm that this issue persists in the latest version 2 on IOS. I've tested the performance on Android and it works fine. I had to migrate back to v1 as it works much better than v2

**Comment by 592da** [comment]
any updates regarding this?

**Comment by henninghall** [comment]
Still an issue in v2.2.0. Also tried including [this performance improvements commit](https://github.com/software-mansion/react-native-reanimated/commit/5d2cf0f7b6053a1b94b1d27570dee649f7d022a8). Still clearly worse perf than reanimated v1.

**Comment by terrysahaidak** [comment]
Anyone who reports this problem, could you verify the performance in a release build is still "worse"?

 I had similar problems in dev but in prod it works perfectly fine since the virtual machine in release build is using different flags with some of the performance improvements enabled, so it just runs JS code faster.

**Comment by henninghall** [comment]
@terrysahaidak The performance is definitely better in release mode, but the difference is still there. Both Reanimated 1 and LayoutAnimation perform better than Reanimated 2. At least in the example in the fork above.

**Comment by henninghall** [comment]
Related discussion: https://github.com/software-mansion/react-native-reanimated/discussions/1632

**Comment by codyweis** [comment]
Having issues on latest 2.2 as well. Building an array of more than 10 items and animating them causes major lag on JS frames and the screen freezes. Are there other 2.* Versions I should try or fixes? Or will they all have the issue?

**Comment by piaskowyk** [comment]
I have just tested on the current master version (2.3.0-beta.1) and after performance optimization an animation is smooth. 🚀

**Comment by piaskowyk** [comment]
Hey @codyweis 👋 Could you try use 2.3.0-beta.1? This version contains many performance optimization

**Comment by Only-IceSoul** [comment]
There should be an option that allows animatedstyle to be called when it is close to a range of values, so that it does not always call, on low phones, it is slow in a list.
