### ISSUE TITLE
Could not find transition.jar (androidx.transition:transition:1.2.0)

### ISSUE THREAD

**Issue by kliker02** [software-mansion/react-native-reanimated#889]
I get this error:
> * What went wrong:
> Execution failed for task ':app:mergeDebugJavaResource'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not find transition.jar (androidx.transition:transition:1.2.0).
>      Searched in the following locations:
>          https://dl.google.com/dl/android/maven2/androidx/transition/transition/1.2.0/transition-1.2.0.jar

I figure out there is no transition-1.2.0.jar and only transition-1.2.0.aar exist so I go to build.gradle and change it to this.
`implementation 'androidx.transition:transition:1.2.0@aar'`
 But it does not work

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 1.9.0

**Comment by jakub-gonet** [comment]
Hi @kliker02,

thanks for reporting, could you please include repository with project which reproduces this issue?

**Comment by kliker02** [comment]
@jakub-gonet, I created [repo](https://github.com/kliker02/ErrorJar)

**Comment by kliker02** [comment]
The problem disappeared when upgrade

| name| version from| version to|
------------ | -------------  | ------------- |
| Android Gradle Plugin Version | 3.5.2  | 4.0.0 |
| Gradle Version | 5.6.4  | 6.1.1 |

**Comment by squid17** [comment]
same issue
