### ISSUE TITLE
Animated Scrollview event not working on the web

### ISSUE THREAD

**Issue by DaniAkash** [software-mansion/react-native-reanimated#894]
## Description

I'm trying to do a parallax scroll header animation on the web. But it is not working. Works fine on Android & iOS

## Steps To Reproduce

1. Create an `Animated.Scrollview` component
2. Use the `onScroll` attribute with `event` from reanimated
3. The animated value is not updating

## Snack or minimal code example

The following animated scroll header works on Android & iOS but doesn't work on the web

https://snack.expo.io/@daniakash/reanimated-scroll-event-web-issue

## Package versions

- Expo: 37.0.0
- React Native: 0.61
- React Native Reanimated: 1.9.0
- React Native Web: 0.12.3

**Comment by emroot** [comment]
ditto here. maybe @EvanBacon might know about this?

**Comment by sertony** [comment]
It's just not implemented for web.

Here is why:

https://github.com/software-mansion/react-native-reanimated/blob/dcb018fc5fb038d571c5c80a1951f450ecc43e27/src/core/AnimatedEvent.js#L102

https://github.com/software-mansion/react-native-reanimated/blob/dcb018fc5fb038d571c5c80a1951f450ecc43e27/src/ReanimatedModule.js#L6

**Comment by nandorojo** [comment]
I recreated @DaniAkash's example with the vanilla `Animated` on Snack, and that works fine. 

https://snack.expo.io/@nandorojo/reanimated-scroll-event-web-issue

Using reanimated would be preferred, of course.

**Comment by DaniAkash** [comment]
> I recreated @DaniAkash's example with the vanilla `Animated` on Snack, and that works fine. 
> 
> https://snack.expo.io/@nandorojo/reanimated-scroll-event-web-issue
> 
> Using reanimated would be preferred, of course.

I am currently using the vanilla `Animated` component as the workaround...

**Comment by marcuzgabriel** [comment]
It is still possible to use reanimated on web without the event. For thoese who want to avoid setting a state and causing a rerendering effect on every scroll event, then use this work around. 

```
import React from 'react';
import styled from 'styled-components/native';
import Animated from 'react-native-reanimated';

const SCROLL_EVENT_THROTTHLE = 16;

const Wrapper = styled.View`
  position: fixed;
  height: 100%;
  width: 100%;
  overflow: auto;
`;

const ContentWrapper = styled.View`
  height: 100vh;
  width: 100vw;
`;

const {
  call,
} = Animated;

const ReanimatedScrollMeasuresOnWebWithoutEvent = () => {
  const scrollViewRef = useRef(null);
  const scrollY = useRef(new Animated.Value(0)).current;
  const contentSize = useRef(new Animated.Value(0)).current;
  const layoutHeight = useRef(new Animated.Value(0)).current;

  const onScrollHandler = (event) => {
    scrollY.setValue(new Animated.Value(event.nativeEvent.contentOffset.y));
    contentSize.setValue(new Animated.Value(event.nativeEvent.contentSize.height));
    layoutHeight.setValue(new Animated.Value(event.nativeEvent.layoutMeasurement.height));
  };

  const runAnimationCode = () => (
    call([scrollY, contentSize, layoutHeight], (val) => console.log({
      scrollY: val[0],
      contentSize: val[1],
      layoutHeight: val[2],
    }))
  );

  console.log('*** Should only log once render and not every scroll event change ***');

  return (
    <Wrapper>
      <Animated.ScrollView
        ref={scrollViewRef}
        onScroll={onScrollHandler}
        scrollEventThrottle={SCROLL_EVENT_THROTTHLE}
      >
        <Animated.View>
          <Animated.Code>{runAnimationCode()}</Animated.Code>
          <ContentWrapper />
          <ContentWrapper />
        </Animated.View>
      </Animated.ScrollView>
    </Wrapper>
  );
};

export default ReanimatedScrollMeasuresOnWebWithoutEvent;
```

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request. I recommend using Reanimated v2.
