### ISSUE TITLE
V2: useAnimatedProps

### ISSUE THREAD

**Issue by sa8ab** [software-mansion/react-native-reanimated#895]
## Description
I noticed useAnimatedProps hook used in reanimated V2 liquid swipe example and nothing in documentation about it. As the name suggests, is it used for the props that are updating, am I right? or it is only for the animated components that are created using createAnimatedComponent?

**Comment by wcandillon** [comment]
It's to animated props which are not style props. for instance

```
 const props = useAnimatedProps(() => {
    return {
      strokeDashoffset: theta.value * radius,
    };
  });
  return (
    <Svg style={StyleSheet.absoluteFill}>
      <AnimatedCircle
        animatedProps={props}
        cx={r}
        cy={r}
        fill="transparent"
        r={radius}
        stroke={StyleGuide.palette.primary}
        strokeDasharray={`${circumference}, ${circumference}`}
        {...{ strokeWidth }}
      />
    </Svg>
  );
```

**Comment by sa8ab** [comment]
Thanks @wcandillon for your great example. Means a lot to me.

**Comment by kmagiera** [comment]
hey, thanks for letting us know. This is definitely an oversight and we will add this to the documentation soon
