### ISSUE TITLE
Can't I do `setValue(new Value())` to a value that initially has `new Value()` instead of a number?

### ISSUE THREAD

**Issue by marqroldan** [software-mansion/react-native-reanimated#902]
## Description

Sorry for the confusing title, but basically the code below should explain it better
### Code 1
```
import Animated from 'react-native-reanimated';
const { Value } = Animated;
const First = new Value(10);
const Second = new Value(new Value(210));
Second.setValue(First);
```

The error I get is
```
Invariant Violation: [657,{"type":"value","value":"<<NaN>>}] is not usable as a native method argument
```

But why is this allowed?

### Code 2
```
const First = new Value(10);
const Second = new Value(20);
Second.setValue(First);
```

It's also weird that Code 1 doesn't emit any error in the snack.io

### Package versions
- React:  "react": "16.11.0",
- React Native: "react-native": "0.62.2",
- React Native Reanimated:  "react-native-reanimated": "^1.9.0",

**Comment by jakub-gonet** [comment]
This is inconsistency on our side, thanks for reporting.

**Comment by jakub-gonet** [comment]
Or not 😄 
Consider following code:
```js
import Animated, {useCode} from 'react-native-reanimated';
const {Value, debug} = Animated;

export default function Example() {
  const first = new Value(10);
  const second = new Value(first);
  useCode(() => debug('T:', second));
  
  return null;
}
```

This also crashes, because you use `Animated.Value` as value. In your second example, you use `value.setValue(anotherValue);` which is correct because this is a direct imperative counterpart to the `set()` node.
