### ISSUE TITLE
Transition not working as per LayoutAnimation

### ISSUE THREAD

**Issue by CyberMew** [software-mansion/react-native-reanimated#903]
## Description

Animation works nicely when using the native LayoutAnimation for transition when deleting a row from a FlatList (probably same for SectionList). Using Reanimation's Transitions, it does not.

Please run snacks below to visually see it.

## Snack or minimal code example
Swipe to delete to see the behaviour between those 2 versions.
----

Using built-in LayoutAnimation (Correct)
https://snack.expo.io/@computerjazz/swipetodelete-rngh-reanimated

If you slow down the animations (screen record it on iOS), you will notice that the next row will shift up, _covering_ the row that is to be delete. It is very obvious.

----
    
Using Reanimated (Incorrect)
https://snack.expo.io/@cybermew/swipetodelete-rngh-reanimated

However if we use Reanimated, it does not. On row delete, the next row will also shift up *but* it will go _under_ the deleting row. Super weird and inconsistent behaviour - does not look good at all with the deleting row 'floating' before disappearing.

 I can only surmise that the Transitions is incorrect, hence the weird behaviour.

**Comment by jakub-gonet** [comment]
Could you please fill the library versions section?

**Comment by CyberMew** [comment]
Do you mean the library version? It’s shown in package json right in the sidebar of the snack, 1.9.1.

**Comment by jakub-gonet** [comment]
We discussed Transitions internally in our team. Considering that v2 makes creating animations easier and Transitions was an experimental API for a long time, we decided to leave Transitions as they are.

We won’t actively fix bugs in them, but we’ll happily merge any PR with fixes. We’re also thinking about rewriting Transitions in v2 sometime in the future.

I’m closing this issue, but if you have further questions, I will be happy to help.

**Comment by CallumHemsley** [comment]
> We discussed Transitions internally in our team. Considering that v2 makes creating animations easier and Transitions was an experimental API for a long time, we decided to leave Transitions as they are.
> 
> We won’t actively fix bugs in them, but we’ll happily merge any PR with fixes. We’re also thinking about rewriting Transitions in v2 sometime in the future.
> 
> I’m closing this issue, but if you have further questions, I will be happy to help.

Hi @jakub-gonet, I'm curious about if flatlists now work with Transitions or not?

**Comment by jakub-gonet** [comment]
We haven't received any PRs regarding Transitions since my comment was written so there's no change in behavior (and this bug is likely still present).
