### ISSUE TITLE
How to set an animation value when listening for a Mobx observable change?

### ISSUE THREAD

**Issue by alejomendoza** [software-mansion/react-native-reanimated#905]
## Description

We want to set an animated value (slider) from an observable value change on a Mobx Store. Which is the best way to achieve this? How can we listen for an external event and perform an animation change?

## Code

```js
export default observer(() => {
  const { playerStore } = Stores();
  const translationX = new Value(0);

 useEffect(() => {
    autorun(() => {
       set(translationX, playerStore.seekSliderPosition * SLIDER_WIDTH);
     });
  });
```

### Package versions

- React:  16.9.0
- React Native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz 
- React Native Reanimated: ^1.9.0

**Comment by terrysahaidak** [comment]
You should set the value inside the playerStore based on animation (gesture handler) using call if you really need this. 

Or use `value.setValue()`.

**Comment by alejomendoza** [comment]
That worked, thanks @terrysahaidak
