### ISSUE TITLE
jest testing - '_reactNativeReanimated.default.Value is not a constructor'

### ISSUE THREAD

**Issue by ggunti** [software-mansion/react-native-reanimated#910]
## Description
In my `__mocks__/react-native-reanimated.js` file I have:
```
jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));
```
but when I execute `npm run test`, I get `TypeError: _reactNativeReanimated.default.Value is not a constructor` error.

```
"react": "16.11.0",
"react-native": "0.62.0",
"react-native-reanimated": "^1.8.0",
"jest": "^24.9.0",
```

### Screenshots
<img width="932" alt="Captură de ecran din 2020-06-19 la 21 18 00" src="https://user-images.githubusercontent.com/26307699/85168017-6e9cb100-b272-11ea-8e14-00e578d993e3.png">

## Steps To Reproduce

1. See Description above

### Expected behavior
Run test without errors.

### Actual behavior
Test fails with `TypeError: _reactNativeReanimated.default.Value is not a constructor` error.

## Snack or minimal code example
My `App-test.js` file:
```
import 'react-native';
import React from 'react';
import App from '../src/App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});
```

## Package versions

- React: 16.11.0
- React Native: 0.62.0
- React Native Reanimated: ^1.8.0

**Comment by vamshi9666** [comment]
Update jest ```transformIgnorePatterns``` config like [reference](https://github.com/software-mansion/react-native-reanimated/pull/439#issuecomment-547520712)

**Comment by ggunti** [comment]
Same error:
<img width="1017" alt="Captură de ecran din 2020-06-22 la 15 26 25" src="https://user-images.githubusercontent.com/26307699/85287325-c4ed3800-b49c-11ea-9538-85cb0fdd5c8b.png">

**Comment by vamshi9666** [comment]
Tried in 1.9.0 but still error in still there.

**Comment by professorkolik** [comment]
Same issue here

**Comment by jakub-gonet** [comment]
What happens if you change [`Value`](https://github.com/software-mansion/react-native-reanimated/blob/master/mock.js#L91) to `Value: AnimatedValue` in `node_modules/react-native-reanimated/mock.js`?

**Comment by ggunti** [comment]
Same error.
<img width="1017" alt="Captură de ecran din 2020-06-23 la 17 44 34" src="https://user-images.githubusercontent.com/26307699/85418251-3d292b80-b579-11ea-994b-58f54bdddd6e.png">

**Comment by jakub-gonet** [comment]
Oh, I didn't see you used it in the node_modules mock and not in the test.

You should use:
```js
jest.mock('react-native-reanimated', () =>
  require('react-native-reanimated/mock'),
);
```
in the tests testing components that use functions from Reanimated.

Global mock should be used by adding to `react-native-reanimated.js` one line:
```js
module.exports = require('react-native-reanimated/mock');
```

If this doesn't resolve your problem please respond.

**Comment by ggunti** [comment]
@jakub-gonet 
Thanks! It works.
As you suggested, in my `__mocks__/react-native-reanimated.js` file I just replaced
```
jest.mock('react-native-reanimated', () =>
  require('react-native-reanimated/mock'),
);
```
with
```
module.exports = require('react-native-reanimated/mock');
```

**Comment by claudioviola** [comment]
Hey guys!
Same issue here.
I have this line in my root folder `__mocks__/react-native-reanimated.js`
`module.exports = require('react-native-reanimated/mock');`

I added react-native-reanimated in the jest config as you can see here
![Schermata 2020-07-07 alle 20 03 12](https://user-images.githubusercontent.com/6689594/86823269-f06f4580-c08c-11ea-8de1-5b515f2b135e.png)

but I face always 

`TypeError: _reactNativeReanimated.Value is not a constructor`
![Schermata 2020-07-07 alle 20 04 04](https://user-images.githubusercontent.com/6689594/86823336-05e46f80-c08d-11ea-8d7c-5605ab83455d.png)

Any suggetion?
Thank you!

**Comment by claudioviola** [comment]
Figure out
that if I use in my code

static syntax like these example tests passed:
new Animated.Value(State.UNDETERMINED);
Animated.useCode(...
Animated.block([...
const zIndex = Animated.cond(Animated.eq(state, State.ACTIVE), 3, 0);

Maybe this can helps...

**Comment by JeremyBradshaw7** [comment]
Getting this error after I add the mock & change transformIgnorePatterns:

```
node_modules/react-native-reanimated/src/reanimated2/mock.ts:4:1 - error TS1208: 'mock.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

    4 const NOOP = () => {
      ~~~~~
```

**Comment by SMKH-PRO** [comment]
> Getting this error after I add the mock & change transformIgnorePatterns:
> 
> ```
> node_modules/react-native-reanimated/src/reanimated2/mock.ts:4:1 - error TS1208: 'mock.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
> 
>     4 const NOOP = () => {
>       ~~~~~
> ```

I am facing same error, were you able to fix this?

**Comment by md-cooper** [comment]
I mocked it like this:

`jest.mock('react-native-reanimated', () => {
  return class Reanimated {
    public static Value() {
      return jest.fn(() => {})
    }
  }
})`
