### ISSUE TITLE
Crash in V2 alpha 3 (new release)

### ISSUE THREAD

**Issue by sa8ab** [software-mansion/react-native-reanimated#912]
## Description
I had built the following code using previous alpha version. which was "2.0.0-alpha.1" and was working all fine,

then I updated to "2.0.0-alpha.3" and on navigation to that page the app crashes.

here is the code for the whole screen,

_edited and the minimal code is in the comment bellow_

**Comment by sa8ab** [comment]
Confirming that with this test code same happens as well ( crashes );
```
import React from 'react';
import {Text} from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withSpring,
} from 'react-native-reanimated';
const Test = () => {
  const height = useSharedValue(10);
  const sz = useAnimatedStyle(() => {
    return {
      height: withSpring(height.value),
    };
  });
  return (
    <Animated.View style={[sz]}>
      <Text>asdf</Text>
    </Animated.View>
  );
};
export default Test;
```

**Comment by sa8ab** [comment]
Is it me that can not set it up or it is a bug @terrysahaidak

**Comment by wcandillon** [comment]
In alpha.3 worklet import don't work anymore, this might be affecting @terrysahaidak component.

**Comment by terrysahaidak** [comment]
I have my gallery thing running on alpha.3. But yesterday it stopped working after some change in my TS code I'm not sure where. But it keeps telling me that `global.__reanimatedWorkletInit` is not a function.Not sure it's related

**Comment by karol-bisztyga** [comment]
The original issue could not be reproduced, provided code works for reanimated version alpha.3

**Comment by wcandillon** [comment]
This issue is safe to close. Can you confirm @sa8ab?

**Comment by sa8ab** [comment]
Yes @wcandillon  I just tested alpha3 and it was fine. although I didn't see any updates on npmjs versions.
