### ISSUE TITLE
V2: Breaks Debugger Menu

### ISSUE THREAD

**Issue by nextriot** [software-mansion/react-native-reanimated#913]
## Description

When following the [official installation instructions](https://docs.swmansion.com/react-native-reanimated/docs/installation) the debugger menu is unavailable in the simulator on iOS.

Have tried reverting back to `alpha.1` with no luck.

Seems to happen as a reult of adding Turbo Modules (`RCTEnableTurboModule(YES);`)

## Snack or minimal code example

[Example Repo](https://github.com/nextriot/reanimated-broken-debugger)

## Package versions

- React: 16.11.0
- React Native: 0.62.0
- React Native Reanimated: 2.0.0-alpha.1

**Comment by ReyhanFabianto** [comment]
It is mentioned in the docs that debugging is not possible :

> As the library uses JSI for synchronous native methods access, remote debugging is no longer possible. You can use Flipper for debugging your JS code, however connecting debugger to JS context which runs on the UI thread is not currently supported

You can check it out the [Known problems and limitations](https://docs.swmansion.com/react-native-reanimated/docs/#known-problems-and-limitations) section.

**Comment by ReyhanFabianto** [comment]
It is mentioned in the docs that remote debugging is not possible :

> As the library uses JSI for synchronous native methods access, remote debugging is no longer possible. You can use Flipper for debugging your JS code, however connecting debugger to JS context which runs on the UI thread is not currently supported

You can check it out the [Known problems and limitations](https://docs.swmansion.com/react-native-reanimated/docs/#known-problems-and-limitations) section.

**Comment by nextriot** [comment]
Thanks for pointing that out @ReyhanFabianto. The preceding section in the docs has  examples with logging so I naturally assumed it was supporting the native debugger.

Thanks again.

**Comment by yolpsoftware** [comment]
@ReyhanFabianto your link is dead, no section "Known problems and limitations" there.

**Comment by jakub-gonet** [comment]
[Here's updated link](https://docs.swmansion.com/react-native-reanimated/docs/next/#known-problems-and-limitations)

**Comment by yolpsoftware** [comment]
Thanks Jakub.

**Comment by michaelknoch** [comment]
Is there any possibility to use the debugger when using reanimated2? I don't want to debug animations, they could maybe be disabled in debugger mode entirely, no?

Not having a proper debugger is a decrease in Dx for my team.
