### ISSUE TITLE
Example cannot work

### ISSUE THREAD

**Issue by chj-damon** [software-mansion/react-native-reanimated#914]
### Screenshots
![image](https://user-images.githubusercontent.com/4902684/85221024-0c16f280-b3e3-11ea-8a8b-e0b15b523840.png)

## Steps To Reproduce

1. checkout branch v1.8.0
2. cd root directory and then `yarn`
3. cd Example directory and then `yarn`
4. cd ios and then `pod install`
5. run on xcode.

### Expected behavior
the example should work well.

### Actual behavior
it fails.

## Package versions

- React:
- React Native:
- React Native Reanimated:

**Comment by jakub-gonet** [comment]
I'm afraid it's problem with your setup, I wasn't able to reproduce it. Try following instructions in the screenshot.
