### ISSUE TITLE
'folly/folly-config.h' file not found

### ISSUE THREAD

**Issue by Inomezi** [software-mansion/react-native-reanimated#918]
## Description

When i try install react-native-reanimated version 1.9.0 i get error "'folly/folly-config.h' file not found" , this doesn't happened on alpha version 2.0.0-alpha.3, but i need 1.9.0

![image](https://user-images.githubusercontent.com/24946599/85321834-02b68480-b4ce-11ea-929b-c4c250dc3edc.png)

I tried:

rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/haste-* && watchman watch-del-all && npm cache clean --force && npm cache verify && rm -rf ios/build && rm -rf node_modules/ && npm i
rm -rf pods && pod install
scripts/ios-install-third-party.sh
cd third-party/glog-0.3.5
./configure
Xcode - Legacy Build
Xcode Clean Build Folder
But nothing helped

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: ^1.9.0

**Comment by jakub-gonet** [comment]
Hi, could you please include repository which reproduces this issue?

**Comment by Inomezi** [comment]
> Hi, could you please include repository which reproduces this issue?

Hi
https://github.com/Inomezi/react-native-reanimated-example/tree/master

**Comment by Inomezi** [comment]
I think it because of turbo modules, when i disabled 7 and 8 points of installation guide (https://docs.swmansion.com/react-native-reanimated/docs/installation/) it works

**Comment by tibuurcio** [comment]
> I think it because of turbo modules, when i disabled 7 and 8 points of installation guide (https://docs.swmansion.com/react-native-reanimated/docs/installation/) it works

After following the instructions on installing Version: 2.0.0-alpha we're having the same error.
Is there something we can do to help debug this issue?

![image](https://user-images.githubusercontent.com/5959178/85412991-97f26100-b540-11ea-8003-b81a73522fcd.png)

**Comment by Inomezi** [comment]
> > Я думаю, что из-за турбомодулей, когда я отключил 7 и 8 пунктов руководства по установке ( https://docs.swmansion.com/react-native-reanimated/docs/installation/ ), это работает
> 
> После следования инструкциям по установке версии: 2.0.0-alpha мы видим ту же ошибку.
> Что мы можем сделать, чтобы помочь отладить эту проблему?
> 
> ![образ](https://user-images.githubusercontent.com/5959178/85413416-2ff04a80-b541-11ea-8560-14f052ea5f52.png)

I'm just follow installation guide and after 7 point i got the same error. On version 2.0.0-alpha.3
this doesn't happened

**Comment by jakub-gonet** [comment]
I used your repository and can confirm this error is showing up. But it persists after removing react-native-reanimated from package.json and reinstalling node_modules as well as pods, so I'm pretty convinced that isn't directly connected to reanimated, so I'm closing this issue.

If you have further concerns I'm happy to help.

**Comment by a-eid** [comment]
@jakub-gonet same thing happened to me on a newly installed project after adding reanimated 2 alpha 6

**Comment by terrysahaidak** [comment]
I had this problem and removing and installing back podfiles fixed it.

**Comment by robrecord** [comment]
> I had this problem and removing and installing back podfiles fixed it.

How do you do this, please?

**Comment by terrysahaidak** [comment]
> > I had this problem and removing and installing back podfiles fixed it.
> 
> How do you do this, please?

`cd ios && rm -rf Pods && rm Podfile.lock && pod install`

**Comment by nehaejaz** [comment]
> > > I had this problem and removing and installing back podfiles fixed it.
> > 
> > 
> > How do you do this, please?
> 
> `cd ios && rm -rf Pods && rm Podfile.lock && pod install`

I did the same as above but still getting the error

**Comment by maq0n** [comment]
anyone found a solution?

**Comment by azizmobarak** [comment]
same problem here RN 0.69.4 with new arch

**Comment by Ahsanali012** [comment]
same problem with RN 0.72.3
