### ISSUE TITLE
"Cannot read property 'viewTag' of undefined" when used with react-native-tab-view

### ISSUE THREAD

**Issue by GuimoBear** [software-mansion/react-native-reanimated#919]
## Description

I'm using **react-native-tab-view** and decided to install **react-native-reanimated@alpha**, however, when I tried to use them together, the error "TypeError: cannot read property 'viewTag' of undefined" occurs whenever the component tries be rendered.

![WhatsApp Image 2020-06-23 at 11 02 59](https://user-images.githubusercontent.com/14862135/85413655-7776d680-b541-11ea-9cd0-19ceb113d9e8.jpeg)

I started looking for solutions and ended up arriving at the following code at _./reanimated2/createAnimatedComponent.js_

```js
          const processedStyle = styles.map(style => {
            if (style.viewTag) {
              // this is how we recognize styles returned by useAnimatedStyle
              return style.initial;
            } else {
              return style;
            }
          });
```

I noticed that this `style` is _null_ or _undefined_ at some point, to correct, I checked, before the `viewTag` property, the 'style' and the problem was solved.

```js
          const processedStyle = styles.map(style => {
            if (style && style.viewTag) {
              // this is how we recognize styles returned by useAnimatedStyle
              return style.initial;
            } else {
              return style;
            }
          });
```

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.3
- React Native Tab View: 2.14.4

**Comment by Dirk41Mavs** [comment]
Thank you guys! This problem makes me recognize even source code cant be careless
