### ISSUE TITLE
V2: re-use useAnimatedStyle in multiple views

### ISSUE THREAD

**Issue by xignor** [software-mansion/react-native-reanimated#920]
When using animated style on multiple style props, it only works on the last one. Would be great to be able to reuse it to for generic style properties:

In this example only the blue box gets the opacity style updated

```
...
  const opacityAnimatedStyle = useAnimatedStyle(() => {
    return {
      opacity: 1 // have something change this value between 0<->1 such from a pan handler translation
    };
  });
...
  return <Animated.View>
      <Animated.View style={[{height: 20, width: 20, backgroundColor: 'red'}, opacityAnimatedStyle]} />
     <Animated.View style={[{height: 20, width: 20, backgroundColor: 'blue'}, opacityAnimatedStyle]} />
  </Animated.View>;
```

**Comment by karol-bisztyga** [comment]
Hey, thanks for reporting! We are aware of the problem although we think it does not appear that often and also it can be done using multiple `useAnimatedStyle` calls. We are going to take care of this in the future.
Cheers

**Comment by a-eid** [comment]
@karol-bisztyga which more performant sharing the style down with children or calling `useAnimatedStyle` hook multiple times ?

**Comment by karol-bisztyga** [comment]
> @karol-bisztyga which more performant sharing the style down with children or calling `useAnimatedStyle` hook multiple times ?

Sharing the style with multiple children will not work in the first place. There is no difference if you do this in one component or in the decomposed way - the problem persists anyway.

**Comment by karol-bisztyga** [comment]
This feature has been added to the TODO list, thank you for contributing, closing this for now 🙏

**Comment by robrechtme** [comment]
Wow I just spent way too long debugging this 😄  Could this be mentioned in the docs maybe? Like a little note or a warning?

**Comment by M2Changezi** [comment]
@jakub-gonet  @karol-bisztyga  how to call  multiple useAnimatedStyle ?

**Comment by jakub-gonet** [comment]
@M2Changezi Not sure if I follow. You can use multiple UAS (`useAnimatedStyle`) hooks but you can't reuse one UAS, applying it to multiple views.

**Comment by VityaSchel** [comment]
How to call `useAnimatedStyle` with same argument as function? It throws `TypeError: Object.values requires that input parameter not be null or undefined`
