### ISSUE TITLE
CreateAnimatedComponent with Functional component

### ISSUE THREAD

**Issue by sa8ab** [software-mansion/react-native-reanimated#933]
## Description
When creating a functional component and passing it to Animated.createAnimatedComponent, I get the following error, How can I fix it without changing my component to a class based one?

![IMG_20200630_161933_278](https://user-images.githubusercontent.com/59901734/86122705-82a3a680-baed-11ea-9d7b-4f136fb1d033.jpg)

- React Native Reanimated: V2 alpha3

**Comment by jakub-gonet** [comment]
Currently `createAnimatedComponent` supports only class components, I'll investigate if support for functional components is possible.

**Comment by goleary** [comment]
Any update on your investigation @jakub-gonet? I'm trying to use a `createAnimatedComponent` with a functional component I import from another library (which I have no control over).

Also, does anyone know the best way to convert a Functional=>class component when you don't own the component? Some kind of wrapper to make it a class component perhaps?

**Comment by jakub-gonet** [comment]
Here's a discussion about that, you can post your solution to that. Automatically wrapping functional components is an interesting idea.

https://github.com/software-mansion/react-native-reanimated/discussions/1527
