### ISSUE TITLE
V2: Initial derived values don't work

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#937]
I have built two examples with displaying a text value (such as in the example below) and another one where I have the identical issue with a color animation value. Everything works great but the derived value has to change first (as seen on the example below).

The code snippet below doesn't work as excepted with v2.alpha3.

```tsx
import React, { useEffect } from "react";
import {
  View,
  TextInput
} from "react-native";
import Animated, {
  useSharedValue,
  useAnimatedProps
} from "react-native-reanimated";

const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

const Slider = () => {
  const theta = useSharedValue(Math.PI);
  const animatedProps = useAnimatedProps(() => {
    return {
      text: `Value: ${theta.value}`,
    };
  });
  useEffect(() => {
    setTimeout(() => {
      theta.value = 2 * Math.PI
    }, 3000);
  }, []);
  return (
    <View>
      <AnimatedTextInput
        underlineColorAndroid="transparent"
        editable={false}
        style={{ fontSize: 24 }}
        {...{ animatedProps }}
      />
    </View>
  );
}

export default Slider;
```

**Comment by sa8ab** [comment]
I did your code with a custom component, here is the result:

I created a functional component, then I wrote a simple class component to be able to pass it to createAnimatedComopnent
```
class AnimatedDotClass extends React.Component {
  render() {
    return <DotText {...this.props} />;
  }
}
```

`DotText` is my custom functional component.

Then passing down a number to the component like so
```
const props = useAnimatedProps(() => {
    return {
      text: activeValue.value,
    };
  });
```

in the template 
```
<AnimatedDotText animatedProps={props} />
```

DotText component: 
```
const DotText = props => {
  return (
    <View>
      <Text> onActiveValue: {props.text}</Text>
    </View>
  );
};
```

doing the following shows the initial value, however when updating the value `activeValue.value = 100` , it gives the following error: 

![photo_2020-07-02_06-05-42](https://user-images.githubusercontent.com/59901734/86362441-21cdb880-bc2a-11ea-9157-fca0f3fae547.jpg)

**Comment by Szymon20000** [comment]
@wcandillon  I think it's a problem with the wrong property name. There is no property 'text'.  
```JS
import React, { useEffect } from "react";
import {
  View,
  TextInput
} from "react-native";
import Animated, {
  useSharedValue,
  useAnimatedProps
} from "react-native-reanimated";

const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

const Slider = () => {
  const theta = useSharedValue(Math.PI);
  const animatedProps = useAnimatedProps(() => {
    return {
      value: `Value: ${theta.value}`,
    };
  });
  useEffect(() => {
    setTimeout(() => {
      theta.value = 2 * Math.PI
    }, 3000);
  }, []);
  return (
    <View>
      <AnimatedTextInput
        underlineColorAndroid="transparent"
        editable={false}
        style={{ fontSize: 24 }}
        animatedProps={animatedProps}
      />
    </View>
  );
}

export default Slider
```

**Comment by Szymon20000** [comment]
I see the problem right now. When we use 'value' prop then initial value works as expected but nothing changes after 3000ms. Only when you use both then it's working as expected.

**Comment by wcandillon** [comment]
@Szymon20000 I'm not experiencing the behavior you are describing (on iOS). Is the fact that I use the AnimatedTextInput component too confusing? I'm able to reproduce this bug on other animated components.

**Comment by wcandillon** [comment]
This example is indeed fixed by assigned the first value, via the `value` prop and then using the `text` props when animation. Thanks!

**Comment by euroclydon37** [comment]
I'm running into something similar to this (if I'm understanding the problem). I'm using a `useTransition` from `react-native-redash` (the problems exists even if I animate without that helper), and it seems like the animated style doesn't respect the initial value I'm setting.

Here's the code.
```ts
function BottomModal() {
  const [visible, setVisible] = useState(false);
  const transition = useTiming(visible, { duration: 400 });

  const insets = useSafeAreaInsets();

  const opacity = transition;
  const translateY = useDerivedValue(() => 100 - transition.value * 100);

  const animatedStyles = useAnimatedStyle(() => ({
    opacity: opacity.value,
    transform: [{ translateY: translateY.value }],
  }));

  useEffect(() => {
    setTimeout(() => setVisible(true), 2000);
  }, []);

  return (
    <Card
      style={[
        styles.cardStyle,
        { marginBottom: insets.bottom },
        animatedStyles,
      ]}>
      <LineItem label="One" value={25000} />
      <LineItem label="Two" value={32000} />
      <LineItem label="Three" value={55000} />
      <LineItem label="Four" value={21000} />
    </Card>
  );
}
```

And here's the result. I'm expecting the bottom card to be off screen and to animate on screen. But it starts on screen, and then does the correct animation afterward. (Forgive the looping gif)
![Problem](https://user-images.githubusercontent.com/9101935/114971967-12c79800-9e43-11eb-9c11-8d95734e7004.gif)
