### ISSUE TITLE
Why does runTiming example function only work in constructor?

### ISSUE THREAD

**Issue by ATClemente** [software-mansion/react-native-reanimated#938]
## Description

I am trying to change the rotations example (https://github.com/software-mansion/react-native-reanimated/blob/master/Example/reanimated1/rotations/index.js) to rotate the cubes on a button press. In the example, we simply set this.trans to the result of the runTiming function. I can run this on my device just fine. When the app loads the cubes spin. I tried to change this example slightly, by instead running this code in a button press. I must be misunderstanding something fundamental here because, I thought this would work, but it does not, the cubes do not spin. I noticed that when trying to run on the button press, the debug message for the stopping of the clock is never shown. 

How can I achieve the desired behavior here?

I am trying this all in an expo project.

## Code

```js
import React, { Component } from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';

import Animated, { Easing } from 'react-native-reanimated';

const {
  set,
  cond,
  startClock,
  stopClock,
  clockRunning,
  block,
  timing,
  debug,
  Value,
  Clock,
  divide,
  concat,
  interpolate,
  Extrapolate,
  abs
} = Animated;

function runTiming(clock, value, dest) {
    const state = {
      finished: new Value(0),
      position: new Value(0),
      time: new Value(0),
      frameTime: new Value(0),
    };
  
    const config = {
      duration: 5000,
      toValue: new Value(0),
      easing: Easing.inOut(Easing.ease),
    };
  
    return block([
      cond(clockRunning(clock), 0, [
        set(state.finished, 0),
        set(state.time, 0),
        set(state.position, value),
        set(state.frameTime, 0),
        set(config.toValue, dest),
        startClock(clock),
      ]),
      timing(clock, state, config),
      cond(state.finished, debug('stop clock', stopClock(clock))),
      state.position,
    ]);
}

export default class RotationTesting extends Component {
  constructor(props) {
    super(props);
    //this.trans = runTiming(new Clock(), 0, 360);
  }

  render() {
    return (
        <View style={styles.container}>
          <Animated.View
            style={[
              styles.box,
              { transform: [{ rotate: concat(this.trans, 'deg') }] },
            ]}
          />
          <Animated.View
            style={[
              styles.box,
              {
                transform: [
                  { rotate: concat(divide(this.trans, 57.2957795786), 'rad') },
                ],
              },
            ]}
          />

            <Button
                onPress={() => {
                    this.trans = runTiming(new Clock(), 0, 360);
                }}
                title="Start"
            />
        </View>
      );
  }


}

const BOX_SIZE = 100;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  box: {
    width: BOX_SIZE,
    height: BOX_SIZE,
    borderColor: '#F5FCFF',
    alignSelf: 'center',
    backgroundColor: 'plum',
    margin: BOX_SIZE / 2,
  },
});
```

### Package versions

- React:
- React Native: 0.61.4 (Expo SDK 36)
- React Native Reanimated: 1.4.0

**Comment by jakub-gonet** [comment]
Hi @ATClemente,
Reanimated basically works in the way that after creating animation consisting of nodes (`set`, `concat`, `spring`, etc) they're sent to the native side. That way animation can be smoothly ran and doesn't block JS thread.
That's why you want to create one instance of `runTiming` - in the c-tor. In order to run animation second time you have to change some `Animated.Value` which will cause nodes dependent on it to reevaluate - this works recursively.

The easiest way to do that is to use imperative `value.setValue()` or `clock.start()`:
```js
constructor(props) {
    super(props);
	this.clock = new Clock();
    this.trans = runTiming(clock, 0, 360);
  }
// (...)

<Button
	onPress={() => {
		this.clock.start();
	}}
	title="Start" />
```

`setValue` can be used if you introduce new value - named `animRunning` or something in that spirit, add it to the condition in the animation with `and` node, reset it on animation end and call `this.animRunning.setValue(1)` in the Button's `onPress`.

Hope that helps.
