### ISSUE TITLE
How to use existing function on UI Thread

### ISSUE THREAD

**Issue by Faisal-Manzer** [software-mansion/react-native-reanimated#940]
## Description
There are some good animation frameworks that are trying to support reanimated2 for performance. One of those is `react-spring` https://www.react-spring.io. React spring provide a hook `useSpring` which has declarative API. How to use the existing version of libraries on UI thread using work.

## Code
```js
import { useSpring } from 'react-spring/native';

const [animatedStyle, setStyle, stopAnimation] = useSpring(() => ({...}));

setStyle({...})
```
Any kind of worklet support for this?

### Package versions

- React: ^16.13.1
- React Native: 0.62.2
- React Native Reanimated: ^2.0.0-alpha.3

**Comment by likern** [comment]
@Faisal-Manzer @jakub-gonet Is there any solution for calling usual Javascript function on UI thread?
React Native [started publishing](https://github.com/facebook/react-native/commit/ab56ed7d96863d7b95521ce9a1e761c215ba0f98) it's internal code as separate packages.

For example, https://yarnpkg.com/package/@react-native/normalize-color.
Instead of copy-pasting `normalizeColor` or `processColor` into `src/reanimated2/Colors.js` we could reuse React Native's implementations and run these functions on UI thread without worrying about code synchronizaton.

**Comment by jakub-gonet** [comment]
For now, it's not really possible AFAIK.
However we want to support it and it's very likely that we will focus on it after stable v2 version release.

/cc @Szymon20000

**Comment by jakub-gonet** [comment]
I talked with @Szymon20000 and seems like we don't want to support this right now. 

The only possible way to do that is to create a babel plugin that adds `worklet` based on some whitelist and then uses Reanimated's _internal_ function `runOnUi`. 
I'd like to mention that this is a discouraged way of doing things, not supported by us and we may change or remove that function at any time - I'm only writing this to give some pointers to people that are desperate enough to do that kind of hacks 😄 

If we're talking about transforming ordinary library functions into worklets, this is impossible. 
We have to transform functions into worklets at build time, so the only way is to force babel to rewrite function by adding `'worklet'` directive on top of used functions. This approach is possible but may lead to huge bundle sizes as babel would have to rewrite every dependency of given function recursively. 
We may think about solving this problem in the future but for now it isn't our top priority.

**Comment by rana944** [comment]
@jakub-gonet , 

Thank you for giving hint for using Babel to run the functions on UI Thread. Actually, this is very similar to what I am trying to achieve from the last couple of weeks. I am using this superb library **reanimated2** for rendering graphs in our application. 

The main challenge I have been facing is I want to regenerate the path as soon as the user scrolls the graph in horizontal axis. This may sound incomplete information but I actually want to implement graph like Binance Inc. which allows user to scroll through the graph & also provide interactivity within the graph.

I am looking forward for the update in which we will be able to run 3rd party functions on the UIThread :)
