### ISSUE TITLE
Consider making shared value read only + setter method

### ISSUE THREAD

**Issue by scottmas** [software-mansion/react-native-reanimated#946]
## Motivation
In your article describing shared values you state: 

> When accessing and updating Shared Values from the React Native JS thread, it is best to think about it as if the value worked the same way as React’s state. We can make updates to the state, but the updates are not immediate, and in order to read the data we need to wait till the next re-render.

However, the api used for setting does not lend itself to this interpretation. e.g. The intuitive interpretation of the following code is to think synchronously:
```javascript
function SomeComponent() {
  const sharedVal = useSharedValue(0);
  return (
    <Button
      title="randomize"
      onPress={() => {
        sharedVal.value = 1;
        console.log(sharedVal.value) //Intuitively should come back as 1 every single time;
      }}
    />
  );
}
```

## Code example
However, if the api was changed to a setter, there would be no such mental model to deconstruct. When you call a method, developers don't immediately expect the value to update, especially if they're experienced with React. So the proposed api would be to make `sharedVal.value` read only, and then have a setter method on `sharedVal` that sets the value? For instance `sharedVal.setValue(1)`. 

## Caveats
This may make worklet code a little harder to reason about since in that context the operation is synchronous. Make the solution there would be an additional method that throws when called outside a worklet context: `sharedValue.setValueSync()`

This may seem like a proliferation of methods for little benefit, but I think the benefit in terms of support tickets and learning curve may be significant. Good code starts with good mental models.

**Comment by scottmas** [comment]
Upon more thought, this is likely a terrible idea. It would make usage more difficult and harder to follow, all for little benefit. In practice, I think this will trip people up that often even if they don't understand the sync/async divide.

**Comment by jakub-gonet** [comment]
We considered this syntax but got to the conclusion that method/setter is merely a convention and we find setters cleaner and easier to read.

Thanks for submitting your feedback!
