### ISSUE TITLE
Transitioning.View disappears while translated on Android

### ISSUE THREAD

**Issue by markneh** [software-mansion/react-native-reanimated#947]
## Description
Hi. As you can see on video below I have a view which is connected to scroll event to update it's x position. At some point I want to update content inside this view with smooth transition. It works as expected on iOS but doesn't on Android.

### Screenshots
![vid](https://user-images.githubusercontent.com/10013061/86517096-c7517980-be2e-11ea-8f73-260ad40934f2.gif)

## Steps To Reproduce
1. Just scroll anywhere to see animation

### Expected behavior
I see a smooth transition on Android.

### Actual behavior
I see a blink and no transition on Android. However, I can see it if scroll is very slow.

## Snack or minimal code example

https://snack.expo.io/@johnman25superstar/38e976

## Package versions

- Expo: ~38.0.0
- React: ~16.11.0
- React Native: 0.62
- React Native Reanimated: ^1.9.0

**Comment by jakub-gonet** [comment]
We discussed Transitions internally in our team. Considering that v2 makes creating animations easier and Transitions was an experimental API for a long time, we decided to leave Transitions as they are.

We won’t actively fix bugs in them, but we’ll happily merge any PR with fixes. We’re also thinking about rewriting Transitions in v2 sometime in the future.

I’m closing this issue, but if you have further questions, I will be happy to help.
