### ISSUE TITLE
[V1] How to manually run spring before current one finishes?

### ISSUE THREAD

**Issue by caiorios** [software-mansion/react-native-reanimated#948]
## Description

I am quite new at this lib, so I am still learning how to do things with it. Basicly, I want to manually run a animation (spring). For this, in some piece of my code, I set the value of the new height. It works fine if I stop the current running stops and click in the button to change the height. However, if I click fast, before the current animation stops, it doesn't spring the animation to the new height.

For a simpler use case, I putted only the piece of the code that simulates my problem. Actually, It has some more conditions involving gestures, etc.

## Code

```js
Animated.useCode(() => {
    return block([
      set(translateY, runSpring(clock, offsetY, manualHeight)),
      set(offsetY, translateY),
    ]);
}, []);
```
```js
manualHeight.setValue(-500);
```

**Comment by jakub-gonet** [comment]
Could you provide more code? Imperative `.setValue` removes animation from the JS side, so this may be the reason it's stopping.

You may be interested in v2, it's still in alpha, but it's pretty stable and way simpler to use than v1. IIRC we have an example for v2 like that in docs or blog post

**Comment by caiorios** [comment]
Hello @jakub-gonet, thank you for the reply. Unfortunately I am using Expo, so v2 is is not an option. Is there another way to achive what I need?

**Comment by caiorios** [comment]
> Could you provide more code?

Here is a full minimal example. Sorry if it's too big:

```js
import React from 'react';
import { Dimensions, Text } from 'react-native';
import Animated from 'react-native-reanimated';
import Constants from 'expo-constants';

import { useValue } from 'customHooks/animation';
import { runSpring } from 'utils/animation';

const { height: windowHeight } = Dimensions.get('window');
const TABBAR_HEIGHT = 53;

export const Views = {
  CLOSED: 0,
  MINIMAL: 1,
  CARDS: 2,
  FULL: 3,
};

export const Heights = {
  CLOSED: 0,
  MINIMAL: TABBAR_HEIGHT * 0.8,
  CARDS: 165,
  FULL: windowHeight - Constants.statusBarHeight,
};

const {
  Clock,
  Extrapolate,
  Value,
  block,
  set,
  multiply,
  interpolate,
} = Animated;

const Modal = React.forwardRef((_, ref) => {
  const offsetY = useValue(-Heights.MINIMAL);
  const manualHeight = useValue(0);
  const clock = new Clock();

  const translateY = block([
    set(offsetY, runSpring(clock, offsetY, manualHeight)),
    offsetY,
  ]);

  const finalTranslateY = multiply(translateY, new Value(-1));

  const height = interpolate(finalTranslateY, {
    inputRange: [0, Heights.CARDS, Heights.FULL],
    outputRange: [Heights.MINIMAL, Heights.CARDS, Heights.FULL],
    extrapolate: Extrapolate.CLAMP,
  });

  React.useImperativeHandle(ref, () => ({
    close: () => {
      manualHeight.setValue(Heights.CLOSED);
    },
    moveToMinimal: () => {
      manualHeight.setValue(-Heights.MINIMAL);
    },
    moveToFull: () => {
      manualHeight.setValue(-Heights.FULL);
    },
  }));

  return (
    <Animated.View style={{ position: 'absolute', bottom: 0, width: '100%' }}>
      <Animated.View style={{ backgroundColor: 'gray', height }}>
        <Text>Modal content</Text>
      </Animated.View>
    </Animated.View>
  );
});

export default React.memo(Modal);

```

```js
const ParentComponent = () => {
  const modal = React.useRef();
  return (
    <>
      <Modal ref={modal} />
      <Button
        onPress={() => modal.current.moveToFull()}
        title="Open full modal"
      />
      <Button
        onPress={() => modal.current.close()}
        title="Close modal"
      />
    </>
  );
};
```

**Comment by caiorios** [comment]
After the tip provided by @jakub-gonet about removal of animation with `setValue`, I better understood the problem. If I stop using ref to manually control my modal and instead of that pass a prop from the parent, and set it to a  `Animated.Value` I achive the expected behavior.

My bigger problem now is, how to put everything to work together, pan gesture + tap gesture + manual animation.
