### ISSUE TITLE
How to couple two ScrollViews together?

### ISSUE THREAD

**Issue by yolpsoftware** [software-mansion/react-native-reanimated#949]
## Description

I want to couple two (or more) ScrollViews together, so that the scrolling on one directly influences the scroll offset of the other, and vice versa. So if you scroll one of them, the other one scrolls as well (one of them faster, and not coupled in a linear way). A scroll bar would be an example of such a behavior. If you scroll the content, the scroll bar's knob would be scrolled as well. If you move the scroll bar, the content gets scrolled too.

Can it be done in React Native Reanimated?

I thought about having a main and secondary ScrollView (once called "master/slave pattern"). A `Reanimated.Value` is passed as the `contentOffset` prop to the secondary ScrollView, and the `onScroll` event of the main ScrollView would influence this value. However, when the user scrolls the secondary ScrollView, updating the main ScrollView would lead to an infinite loop, wouldn't it?

I also thought about having just one ScrollView which invisibly overlaps the secondary ScrollViews, so only one ScrollView gets any touch events. This would work, but then I need to somehow accelerate/decelerate the scroll speed as soon as the user scrolls in the region of the secondary ScrollViews.

Is there an obvious solution to this? I'm interested in all kinds of answers, does not matter if Reanimated v1 or v2.

**Comment by terrysahaidak** [comment]
so you need a real scroll view? or can it be implemented by your own?

if so, you can use decay animation to create your own scroll view.

**Comment by yolpsoftware** [comment]
@terrysahaidak A real scroll view would be very nice, since it would have the same properties (deceleration rate, bouncyness etc.) as the native one. Moreover, I want to use this in a `FlatList`. So if I'm implementing my own `ScrollView`, this would mean to also implement my own `FlatList`.

Moreover, if it is possible with Reanimated, it might be a good example to learn from.

**Comment by terrysahaidak** [comment]
there is work in progress for sync scrollTo calls from worklets in Reanimated2. this might help you.

could you describe your case more? why do you need flatlist? do you plan for few hundreds items to be rendered?

**Comment by yolpsoftware** [comment]
Yes, in one of the lists, there are hundreds of items.

My use case involves a big tree of data, like a big mind map. There are thousands of leaves, but having them in one big list is not helpful, so we use the tree to kind of index them. We don't want any nested expanders (like in a mind map). We prefer to show each tree level as a scrollable list. The first level might fit on an iPad screen, but on a phone it must be scrolled. The second level is scrollable on every device.

Now when the user scrolls one level, we naturally want the other levels to scroll accordingly.

**Comment by yolpsoftware** [comment]
@Szymon20000 thank you, but not sure if I understand. Will you PR allow `scrollTo` to be called from native code, i.e. from "Reanimated nodes"?

If you could provide some example code, I'd be happy to test it.

**Comment by Szymon20000** [comment]
@yolpsoftware It will allow `scrollTo` to be called from Reanimated worklets. Yes, it's synchronous so it's executed on UI thread without crossing the bridge. 
```JS
function () {
  'worklet' 
  scrollTo(viewTag, x, y, animated)
}
```

**Comment by yolpsoftware** [comment]
@Szymon20000 very cool, thanks a lot!

**Comment by yolpsoftware** [comment]
Might #462 also be a solution? Quote from there:

_The ultimate use case is scrolling a ScrollView. There wasn't a way to control scrolling with animation.
Now there is:_

```
dispatch('RCTScrollView', 'scrollTo', tag, scrollX, scrollY, animated)
```

**Comment by ShaMan123** [comment]
> Might #462/#469 also be a solution? Quote from there:
> 
> _The ultimate use case is scrolling a ScrollView. There wasn't a way to control scrolling with animation. Now there is:_
> 
> ```
> dispatch('RCTScrollView', 'scrollTo', tag, scrollX, scrollY, animated)
> ```

This is valid for V1 (android only), hopefully @Szymon20000 will take up the challenge.

**Comment by tudiantuan** [comment]
I am newbie react native. Can someone give me example for use it?

> @yolpsoftware It will allow `scrollTo` to be called from Reanimated worklets. Yes, it's synchronous so it's executed on UI thread without crossing the bridge.
> 
> ```js
> function () {
>   'worklet' 
>   scrollTo(viewTag, x, y, animated)
> }
> ```

**Comment by ArnabXD** [comment]
> I am newbie react native. Can someone give me example for use it?
> 
> > @yolpsoftware It will allow `scrollTo` to be called from Reanimated worklets. Yes, it's synchronous so it's executed on UI thread without crossing the bridge.
> > ```js
> > function () {
> >   'worklet' 
> >   scrollTo(viewTag, x, y, animated)
> > }
> > ```

this is how I used it

```ts
  const scrollRefOne = useAnimatedRef<Animated.ScrollView>();
  const onScroll = useAnimatedScrollHandler({
    onScroll: event => {
      // scrollX.value = event.contentOffset.x;
      scrollTo(scrollRefOne, event.contentOffset.x, 0, false);
    },
  });
```

**Comment by Eramirez06** [comment]
Man really you are a life savior, infinite thanks for this I had like 8 hours suffering with this before finding your comment
