### ISSUE TITLE
Build Android Error: "specified for property '$3' does not exist"

### ISSUE THREAD

**Issue by adrianwijaya0394** [software-mansion/react-native-reanimated#950]
## Description

I am using react-native-reanimated #908  Pull Request Head. But when I run react-native run-android, build error with Error: specified for property '$3' does not exist. Why this error occured?

### Screenshots
![build failed_70](https://user-images.githubusercontent.com/65936251/86877133-6668c080-c110-11ea-8fba-2c71538d24be.png)

## Steps To Reproduce

1. run : yarn add "software-mansion/react-native-reanimated#908/head"
2. build android with: npx react-native run-android

### Expected behavior

build android passed without error.

### Actual behavior

build android error, with Error: specified for property '$3' does not exist

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: react-native-reanimated@2.0.0-alpha-3#908

**Comment by likern** [comment]
@adrianwijaya0394 Have you solved this problem?
I came across the same bug when I forked repository and tried to build app from master.

**Comment by adrianwijaya0394** [comment]
no, I have not solved this problem.

**Comment by terrysahaidak** [comment]
Seems like Common directory should be symlinked/copied into `android/src/main`.

/cc @kmagiera

**Comment by ibrahim019** [comment]
> Seems like Common directory should be symlinked/copied into `Example/android/src/main`.
> 
> /cc @kmagiera

This works

**Comment by Szymon20000** [comment]
@adrianwijaya0394 We have a script for building npm package. It's not possible right now to add Reanimated 2 to a project directly from GitHub.
