### ISSUE TITLE
Missing pages from documentation documentation 

### ISSUE THREAD

**Issue by KishoreBarik** [software-mansion/react-native-reanimated#967]
## Description

This documentation [page](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/declarative) talks about going through [timing](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/timing.html) , [decay](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/decay.html) and [spring](https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/spring.html) but those links are returning 404 page.

**Comment by jakub-gonet** [comment]
This probably happened when docs from 1.x.x were moved into new docs framework, thanks for reporting it
