### ISSUE TITLE
How to use spring with interpolate in the right way?

### ISSUE THREAD

**Issue by zxccvvv** [software-mansion/react-native-reanimated#971]
## Description

How to use spring with interpolate in the right way?

when i used `import { ...another, Animated } from 'react-native';` it's run without problem
but with `import Animated from 'react-native-reanimated';` my white box just disappear

## Code

```
import React from 'react';
import { View, Dimensions, Text, Button } from 'react-native';
import Animated from 'react-native-reanimated';

const {width, height} = Dimensions.get('window')

export default class Home2 extends React.Component{
  constructor(props) {
    super(props);
    this.state = {
    }
    this.anim = new Animated.Value(0)
  }

  /**
  * List function to handling component
  */

  startAnim(){
    this.anim.setValue(0)
    Animated.spring(this.anim, {
      toValue:1,
      stiffness:50,
      useNativeDriver:false
    }).start()
  }

  /**
  * List function to render component
  */

  /**
  * End list function to render component
  */

  render() {
    const animated = this.anim.interpolate({
      inputRange:[0, 1],
      outputRange:[100, 0]
    })
    return(
      <View style={{flex:1, justifyContent:'center', alignItems:'center', backgroundColor:'red'}}>
        <Animated.View style={{transform:[{translateX:animated}]}}>
          <View style={{width:100, height:100, backgroundColor:'white'}}/>
        </Animated.View>
        <Button
          onPress={() => {
            this.startAnim()
          }}
          title="Start"
        />
      </View>
    )
  }
}
```

### Package versions

- React: "16.13.1",
- React Native: "0.63.0",
- React Native Reanimated: "^1.9.0",

**Comment by jakub-gonet** [comment]
Hi @zxccvvv, try adding all of the config values, e.g.:
```
Animated.spring(this.anim, {
 	  toValue: 1,
      mass: 1,
      stiffness: 10,
      overshootClamping: false,
      restSpeedThreshold: 0.2,
      restDisplacementThreshold: 0.1,
}).start()
```

**Comment by zxccvvv** [comment]
Hi @jakub-gonet , thank you for helping me,
with these config, the animation can running well, but why the expected result  is doesn't like `Animated Spring` of `React Native`? does it's the bevahiour of `Animated.Spring Reanimated`?

I mean, the animation keep running (loop), my expected result is just running once,
how can i do that?

> Hi @zxccvvv, try adding all of the config values, e.g.:
> 
> ```
> Animated.spring(this.anim, {
>  	  toValue: 1,
>       mass: 1,
>       stiffness: 10,
>       overshootClamping: false,
>       restSpeedThreshold: 0.2,
>       restDisplacementThreshold: 0.1,
> }).start()
> ```

**Comment by jakub-gonet** [comment]
If you used my **example** config this won't work, because it didn't set the `damping` parameter which damps the spring

Check this out:
```js
    Animated.spring(this.anim, {
      toValue: 1,
      damping: 2,
      mass: 1,
      stiffness: 121.6,
      overshootClamping: false,
      restSpeedThreshold: 0.001,
      restDisplacementThreshold: 0.001,
    }).start();
```
