### ISSUE TITLE
Get current screen position of an Animated View

### ISSUE THREAD

**Issue by BenjErgizerBunny** [software-mansion/react-native-reanimated#972]
## Description

How can I get the current position of an animation?  I want to find the x and y positions of my Animated.View each time it changes position during the animation.  So far I've only been able to find the starting and ending position.

## Code

**I tried creating a snack example but was receiving errors that react-native-renaimated coudl not be found**

Note: minWindowDimension & maxWindowDimension below are returned from a function which calculates the min and max window dimension from the react native useDimensions hook.

```
function style(squareSideLength) {
  const styles = StyleSheet.create({
    enemyBox: {
      width: squareSideLength,
      height: squareSideLength,
      backgroundColor: 'blue',
      position: 'absolute',
    },
  });
  return styles;
}

export default function enemyBox({
  squareSideLength,
  gameRunning,
}) {
  const {minWindowDimension, maxWindowDimension} = getWindowDimensions();
  const styles = style(squareSideLength);
  const x = useSharedValue(minWindowDimension * 0.1);
  const y = useSharedValue(maxWindowDimension * 0.1);
  if (gameRunning) {
    x.value = minWindowDimension - 75;
    y.value = maxWindowDimension - 75;
  }

  const enemyBoxAnimatedStyle = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateX: withTiming(x.value, {
            duration: 5000,
            easing: Easing.linear,
          }),
        },
        {
          translateY: withTiming(y.value, {
            duration: 5000,
            easing: Easing.linear,
          }),
        },
      ],
    };
  });
  return (
    <Animated.View
      style={[styles.enemyBox, enemyBoxAnimatedStyle]}
    />
  );
}
```

### Package versions

- React: 16.11.0
- React Native: 0.62.2 
- React Native Reanimated: 2.0.0-alpha.1

**Comment by terrysahaidak** [comment]
First of all, if you translate the view, you can calculate the position based on the amount of translation and the initial position of the view.

You can use `useDerivedValue` hook to have this value up to date.

Otherwise, there will be an ability to measure the view in worklet, but I don't think measuring it on each frame is a good idea overall.

**Comment by BenjErgizerBunny** [comment]
Calculating the position based on the amount of translation and initial position of the view was my first idea, but I want to track multiple views that will each be using multiple different types of Easing.  I also need 100% accuracy so that seemed complex since non-linear easing would be hard to calculate.  

I created a function to track the current view but I'm not sure where to place it.  Ideally I'd like to place it in the useAnimatedStyle function of the view I'm measuring the position of so I can get the position of each frame but that isn't working. Ideally I'd like to access the position of my view on each frame within the JS thread as I want to use the position as part of my business logic.  

Do you have any suggestions?

Below is the function is a snippet of the relevant code: 
 
```
function AnimatedComponent(){
  const ref = useRef();
  function testing(ref) {
    if (ref.current) {
      ref.current.measure((x, y, width, height, pageX, pageY) => {
        console.log('x in us effect', x);
      });
    }
  }

return(
    <View style={{ width: 100, height: 100, position: 'absolute' }}>
 <AnimatedView
        style={[styles.enemyBox, enemyBoxAnimatedStyle]}
        ref={ref}
      />
</View>
);
}
```

**Comment by terrysahaidak** [comment]
even if you use some easing, you animate same properties.

if you create separate shared values for each style property and animate them, then you shouldn't care about easings and etc. just use useDerivedValue hook where you add initial position to the animating value.

But still, check out the PR which addseasure and scrollTo.

**Comment by GanongLS** [comment]
waiting response, so i can learn something or two.
