### ISSUE TITLE
build.gradle import results in file not found exception

### ISSUE THREAD

**Issue by SudoPlz** [software-mansion/react-native-reanimated#984]
Looks like this is the wrong path:

https://github.com/software-mansion/react-native-reanimated/blob/90d5350175aec183529dbdd97fc7af59fb5f9548/android/build.gradle#L60

`$projectDir` translates to `./node_modules/react-native-reanimated`

going one dir back takes us to `./node_modules`

This has to change either to 
`"$rootDir/../node_modules/react-native/ReactAndroid/gradle.properties"`
or to:
`"$projectDir/../../node_modules/react-native/ReactAndroid/gradle.properties"`

**Comment by Szymon20000** [comment]
This file should be used only in the Reanimated repository.

**Comment by SudoPlz** [comment]
Could it be that it's happening because I'm installing the module from github directly like so?

`npm i react-native-reanimated@github:software-mansion/react-native-reanimated#90d5350175aec183529dbdd97fc7af59fb5f9548`

The reason I'm doing that is because alpha 4 is not released in npm yet and I need it to build with my react-native 0.63 project

**Comment by Szymon20000** [comment]
It has been released.
