### ISSUE TITLE
can't read property viewTag of null

### ISSUE THREAD

**Issue by Dirk41Mavs** [software-mansion/react-native-reanimated#988]
## Description
when app launched ,throw this error.
add addtional judgment"style &&" in src/createAnimatedComponent.js line:250 can solve this problem

## Steps To Reproduce

1.

## Package versions
2.0.0-alpha.3

- React:16.11.0
- React Native:0.62.2
- React Native Reanimated:2.0.0-alpha.3

**Comment by jakub-gonet** [comment]
Resolved by #923
