### ISSUE TITLE
Reanimated alpha v4, documentation install on Android

### ISSUE THREAD

**Issue by Piero87** [software-mansion/react-native-reanimated#990]
I can't understand the documentation for install reanimated alpha v4 on android, in particular this part:

```
  import com.facebook.react.bridge.JSIModulePackage; // <- add
  import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add
  ...
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
  ...

      @Override
      protected String getJSMainModuleName() {
        return "index";
      }

      @Override
      protected JSIModulePackage getJSIModulePackage() {
        return new ReanimatedJSIModulePackage(); // <- add
      }
    };
  ...
```

In what file I have to do it? If I search this: `getJSMainModuleName` in my code I found it in MainApplication.java but in a note under that snippet say MainActivity.js. Anyone can help me?

**Comment by likern** [comment]
@Piero87 I think it's a bug (as the link to diff is also wrong) in documentation.
These modifications should be done in `MainApplication.java`.

**Comment by Szymon20000** [comment]
Yes, `getJSIModulePackage` method should be added in MainApplication.java.

**Comment by likern** [comment]
Was fixed in https://github.com/software-mansion/react-native-reanimated/commit/3d6a18e9824061d325718b77cfe92c9d48cd9b83
