### ISSUE TITLE
[V2] Animation triggers inconsistently - Parallel/Sequence

### ISSUE THREAD

**Issue by ShaMan123** [software-mansion/react-native-reanimated#991]
## Description
I was playing around with [V2-playground](https://github.com/software-mansion-labs/reanimated-2-playground) and I've stumbled upon a bug.
I was trying to change the background color of the view with an animation that should run parallel to the change in width.
- If both of the values (width & color) reside in the same `useAnimatedStyle` hook (`styleA`) then the animation runs in sequence.
- If I split the values to 2 different `useAnimatedStyle` hooks (`styleB`, `styleC`) then the animation runs in parallel, as expected.
- However, if both `width` & `height` values reside in the same `useAnimatedStyle` hook (`styleD`) the animation runs in parallel, as expected.

See `styleA, styleB, styleC, styleD` in [App.js](https://github.com/ShaMan123/reanimated-2-playground/blob/master/App.js)
**TESTED on ANDROID only!**

----

![r2gif](https://user-images.githubusercontent.com/34343793/87850233-54003b00-c8f7-11ea-985d-141877b6f3ee.gif)

## Steps To Reproduce

1. Follow [ShaMan123/reanimated-2-playground](https://github.com/ShaMan123/reanimated-2-playground.git) README.
1. Run the app.

### Expected behavior
Both animations should run parallel to each other

### Actual behavior
See gif

## Snack or minimal code example
Provided a repo, snack caused problems

## Package versions
[package.json](https://github.com/ShaMan123/reanimated-2-playground/blob/master/package.json)

**Comment by Szymon20000** [comment]
Could you check if the issue still persists?  We have solved a similar problem and the solution is already in alpha.4 version.

**Comment by ShaMan123** [comment]
I'll Check and report back

**Comment by ShaMan123** [comment]
FIXED!
