### ISSUE TITLE
Object__DO_NOT_TRANSFORM transform causing issues with Hermes?

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#995]
This is a clone of software-mansion/react-native-reanimated#939 issue.
After checking new published `2.0.0-alpha.4` it looks like issue hasn't been solved.
Reproduction repository with `2.0.0-alpha.4` version: https://github.com/likern/hermes-do-not-transform-bug

More information on original issue.

> ## Description
> [facebook/hermes#280](https://github.com/facebook/hermes/issues/280) was opened against [Hermes](https://github.com/facebook/hermes). This seems related to #882. I'm a fair bit out of my depth here and hoping you can help point us in the right direction.
> 
> There's code in that issue which results in a JS error with Hermes:
> 
> `ReferenceError: Property Object__DO_NOT_TRANSFORM doesn't exist`
> 
> Unfortunately the bug report doesn't give specific npm module versions. I'm not sure how to put something together to repro this issue, but from the error, it feels like the renamed symbol is somehow getting referenced before being restored, which doesn't seem to be the intent of the plugin.
> 
> Any suggestions would be welcome. Thanks.

**Comment by terrysahaidak** [comment]
could you please test this with RN 0.63?

**Comment by Szymon20000** [comment]
That's caused by caches. Please add '--reset-cache' flag.

**Comment by likern** [comment]
@Szymon20000 Thank you, confirmed that after `--reset-cache` application is working.
